/* 我的规则仓库 v3.5.0-rc4 - settings with smart sync */
(function(R){
R.settingsPage=function(){
setPageTitle('设置');var d=[],cache=this.cacheMs(),probe=this.probeMs();this.pushNav(d,'settings');
this.pushSection(d,'云端同步','兼顾启动速度与目录实时性');
d.push({title:'完整索引缓存',desc:Math.round(cache/60000)+' 分钟 · 网络异常时继续使用最后一次有效缓存',url:$('5分钟,15分钟,30分钟,60分钟','选择完整索引缓存').select(function(){var map={'5分钟':300000,'15分钟':900000,'30分钟':1800000,'60分钟':3600000},r=$.require('hiker://page/ruleRepoCore');r.setSetting('cache_ms',map[String(input||'30分钟')]||1800000);refreshPage(false);return'toast://已设置';}),col_type:'text_1',extra:{lineVisible:false}});
d.push({title:'轻量变更探测',desc:(probe<=0?'已关闭':Math.round(probe/1000)+' 秒')+' · 只检查 revision，发现变化才重新下载完整 manifest',url:$('关闭,30秒,60秒,180秒,300秒','选择探测频率').select(function(){var map={'关闭':0,'30秒':30000,'60秒':60000,'180秒':180000,'300秒':300000},r=$.require('hiker://page/ruleRepoCore');r.setSetting('probe_ms',map[String(input||'60秒')]);refreshPage(false);return'toast://已设置';}),col_type:'text_1',extra:{lineVisible:false}});
d.push({title:'立即同步云端索引',desc:'清理本地 manifest / revision 缓存并重新读取云端。',url:$('#noLoading#').lazyRule(function(){showLoading('同步云端索引…');try{var r=$.require('hiker://page/ruleRepoCore');r.clearManifestCache();r.manifest(true);hideLoading();refreshPage(false);return'toast://云端索引已同步';}catch(e){hideLoading();return'toast://同步失败：'+String(e.message||e);}}),col_type:'text_1',extra:{lineVisible:false}});
d.push({title:'Core 更新与回退',desc:'当前通道独立更新；测试版不会影响正式版。',url:'hiker://page/ruleRepoUpdate?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'备份与恢复','备份收藏、版本记录、最近使用、搜索/导入历史和筛选设置。');d.push({title:'复制状态备份',desc:'生成 JSON 并复制到剪贴板；不包含 Cookie、Token 或账号凭据。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');return'copy://'+r.exportState();}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'从备份恢复',desc:'粘贴由本程序生成的 rule-repo-state JSON。',url:$('粘贴备份 JSON','').input(function(){try{var r=$.require('hiker://page/ruleRepoCore');r.restoreState(String(input||''));r.clearSelection();refreshPage(false);return'toast://备份已恢复';}catch(e){return'toast://恢复失败：'+String(e.message||e);}}),col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'本地记录','不会删除海阔里已经安装的小程序');d.push({title:'导入记录',desc:'查看最近导入 / 更新过的程序。',url:'hiker://page/ruleRepoHistory?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空搜索历史',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearSearchHistory();return'toast://搜索历史已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空最近使用',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearRecent();return'toast://最近使用已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空导入历史',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearImportHistory();refreshPage(false);return'toast://导入历史已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空版本记录',desc:'清除“已记录 / 可更新”判断依据。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearInstalled();refreshPage(false);return'toast://版本记录已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空收藏',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearFavorites();refreshPage(false);return'toast://收藏已清空';}),col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'界面与筛选','保持首页轻量，把复杂管理放到独立页面。');d.push({title:'重置全部筛选',desc:'重置分类、子分类、标签、排序、模式、首页状态与搜索关键词。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearAllFilters();clearMyVar('hc_repo_home_view');clearMyVar('hc_repo_home_category');clearMyVar('hc_repo_home_sort');clearMyVar('hc_repo_search_kw');r.clearSelection();refreshPage(false);return'toast://筛选状态已重置';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'主题适配',desc:'使用海阔原生组件与透明背景，自动跟随宿主浅色 / 深色主题。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'关于','版本与架构');d.push({title:'版本与更新日志',desc:'Core '+this.version+' · build '+this.build,url:'hiker://page/ruleRepoAbout?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'产品架构',desc:'一个程序一个云端入口 · Stable/Test 多通道 · 智能索引同步 · Remote Module · 可升级可回退',url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);
};
R.aboutPage=function(){setPageTitle('关于');var d=[];d.push({title:'我的规则仓库',desc:'Core '+this.version+' · build '+this.build+'\n海阔视界专属 · 云端程序管理中心',img:this.iconOf(this.findById('rule-repo')||{}),pic_url:this.iconOf(this.findById('rule-repo')||{}),url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});this.pushSection(d,'核心能力','分类 / 搜索 / 版本通道 / 更新回退 / 收藏 / 备份 / 批量管理 / 智能索引同步');d.push(this.quickCard('分类管理','hiker://page/ruleRepoCategory?rule=&simple=true'));d.push(this.quickCard('搜索中心','hiker://page/ruleRepoSearch?rule=&simple=true'));d.push(this.quickCard('更新中心','hiker://page/ruleRepoUpdates?rule=&simple=true'));this.pushSpacer(d);this.pushSection(d,'架构','Cloud Entry → Channel Selector → Shell → Bootstrap → Remote Manager → Versioned Release Modules。');var log='';try{log=this.apiText('apps/tools/rule-repo/CHANGELOG.md');}catch(e){log='更新日志读取失败：'+String(e.message||e);}d.push({title:'更新日志',desc:log,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);};
})(HikerRuleRepo);
