/* 我的规则仓库 v3.5.0-rc4 - clearer update center */
(function(R){
R.updatesPage=function(){setPageTitle('更新中心');var d=[],m,items;try{m=this.manifest(false);items=(m.items||[]).map(this.normalizeItem.bind(this));}catch(e){setResult([{title:'仓库读取失败',desc:String(e.message||e),url:'hiker://empty',col_type:'long_text'}]);return;}this.pushNav(d,'updates');var info={};try{if(typeof RuleRepoBoot==='object')info=RuleRepoBoot.info()||{};}catch(e){}var cur=info.current||{version:this.version,build:this.build},prev=info.previous||null,stats=this.stats(items),last=Number(getItem('hc_repo_updates_last_check','0')||0),edition=this.statePrefix.indexOf('test')>=0?'测试版 Test':'正式版 Stable';
d.push({title:'规则仓库 Core '+cur.version,desc:edition+' · build '+cur.build+' · Schema '+(m.schema||'?')+'\n'+(prev?'可回退 '+prev.version:'暂无回退记录'),img:this.iconOf(this.findById('rule-repo')||{}),pic_url:this.iconOf(this.findById('rule-repo')||{}),url:'hiker://page/ruleRepoUpdate?rule=&simple=true',col_type:'movie_1_left_pic',extra:{lineVisible:false,pageTitle:'Core 更新'}});
d.push(this.quickCard('Core 更新 / 回退','hiker://page/ruleRepoUpdate?rule=&simple=true'));d.push(this.quickCard('同步程序索引',$('#noLoading#').lazyRule(function(){showLoading('同步云端索引…');try{var r=$.require('hiker://page/ruleRepoCore');r.clearManifestCache();r.manifest(true);setItem('hc_repo_updates_last_check',String(Date.now()));hideLoading();refreshPage(false);return'toast://云端程序索引已同步';}catch(e){hideLoading();return'toast://同步失败：'+String(e.message||e);}})));d.push(this.quickCard('导入记录','hiker://page/ruleRepoHistory?rule=&simple=true'));
d.push({title:'自动同步',desc:'完整索引继续使用缓存；轻量 revision 默认每 '+Math.round(this.probeMs()/1000)+' 秒探测一次，云端目录变化会自动刷新。',url:'hiker://page/ruleRepoSettings?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'上次手动检查',desc:this.formatTime(last),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
d.push(this.statCard('已记录',stats.installed,'hiker://empty'));d.push(this.statCard('可更新',stats.updates,'hiker://empty'));d.push(this.statCard('远程',stats.remote,'hiker://empty'));d.push(this.statCard('本地',stats.local,'hiker://empty'));
var updates=items.filter(function(x){return x.entryType!=='channel-group'&&R.statusOf(x)==='可更新';});this.pushSpacer(d);this.pushSection(d,'程序更新',updates.length?'发现 '+updates.length+' 个可更新程序':'当前没有可更新程序');updates.forEach(function(x){d.push(R.itemCard(x));});if(!updates.length)this.pushEmpty(d,'全部已是最新记录','云端目录变化会自动探测，也可以手动同步。');
var installed=items.filter(function(x){return x.entryType!=='channel-group'&&R.statusOf(x)==='已同步';});if(installed.length){this.pushSpacer(d);this.pushSection(d,'已同步','已记录且云端版本未变化');installed.forEach(function(x){d.push({title:x.name,desc:String(x.version||''),img:R.iconOf(x),pic_url:R.iconOf(x),url:'hiker://page/ruleRepoDetail?rule=&simple=true',col_type:'avatar',extra:{lineVisible:false,pageTitle:x.name,hc_repo_item_id:x.id}});});}setResult(d);};
})(HikerRuleRepo);
