/* Hanime1 Test32 account: browser-session aware My/Account center */
(function(C,P,E,H,L){
var oldActive=C.activeAccount,profileCache=null,profileTs=0,PROFILE_TTL=45000;
function clean(v){return C.clean(String(v==null?'':v));}
function nodes(html,sel){try{return pdfa(String(html||''),sel)||[];}catch(e){return [];}}
function text(node,sel){try{return clean(pdfh(node,sel)||'');}catch(e){return '';}}
function attr(node,sel){try{return String(pdfh(node,sel)||'').replace(/&amp;/g,'&').trim();}catch(e){return '';}}
function firstText(node,sels){for(var i=0;i<sels.length;i++){var v=text(node,sels[i]);if(v)return v;}return '';}
function firstAttr(node,sels){for(var i=0;i<sels.length;i++){var v=attr(node,sels[i]);if(v)return v;}return '';}
function abs(base,u){u=String(u||'').trim();return u?C.abs(base,u):'';}
function videoId(u){var m=String(u||'').match(/[?&]v=(\d+)/);return m?m[1]:'';}
function profileItem(p){return p?{id:String(p.id||''),name:p.name||('用户 '+p.id),email:p.email||'',avatar:p.avatar||p.avatarUrl||'',cookie:p.cookie||'',base:p.base||'',browserSession:true}:null;}
function browserProfile(){try{var st=C.state();if(st&&st.managed)return null;var base=(st&&st.base)||C.resolveHost(false),cookie=C.browserCookie(base);if(!cookie)return null;if(profileCache&&Date.now()-profileTs<PROFILE_TTL)return profileCache;var p=P.profile();if(!p||!p.id)return null;profileCache=profileItem(p);profileTs=Date.now();return profileCache;}catch(e){return null;}}
C.activeAccount=function(){var a=null;try{a=oldActive();}catch(e){}return a||browserProfile();};
P.sessionProfile32=function(){var a=C.activeAccount();if(a)return a;return browserProfile();};
P.clearSessionProfile32=function(){profileCache=null;profileTs=0;};
function card(n,base){var href=firstAttr(n,['a[href*=watch]&&href','a.video-link&&href','[data-href]&&data-href','a&&href']),id=videoId(href),title=firstText(n,['.video-title&&Text','.title&&Text','.home-rows-videos-title&&Text','img.main-thumb&&alt','img&&alt']),img=firstAttr(n,['img.main-thumb&&src','img&&data-src','img&&src']);if(!id)return null;return {id:id,title:title||('影片 '+id),img:abs(base,img),artist:firstText(n,['.meta-author a&&Text','.subtitle a&&Text','.subtitle&&Text']),duration:firstText(n,['.duration&&Text','.card-mobile-duration&&Text']),views:firstText(n,['.stats-container&&Text','.card-mobile-meta&&Text']),upload:firstText(n,['.meta-stats span&&Text','.card-mobile-meta&&Text'])};}
function videoList(h,base){var out=[],seen={},sels=['.playlist-video-list > div.user-tab-item-wrapper','.user-tab-item-wrapper','div.horizontal-card','div[class^=video-item-container]','.home-rows-videos-wrapper > *','a[href*=watch]'];for(var s=0;s<sels.length;s++){var a=nodes(h,sels[s]);for(var i=0;i<a.length;i++){var x=card(a[i],base);if(x&&x.id&&!seen[x.id]){seen[x.id]=1;out.push(x);}}if(out.length&&s<2)break;}return out;}
function playlistCards(h,base){var a=nodes(h,'.user-tab-item-wrapper,.playlist-item-wrapper,.playlist-card'),out=[],seen={};for(var i=0;i<a.length;i++){var href=firstAttr(a[i],['a.video-link&&href','a[href*="playlist?list="]&&href','a[href*=playlist]&&href']),m=String(href||'').match(/[?&]list=([^&]+)/),id=m?m[1]:'',title=firstText(a[i],['.title&&Text','.playlist-title&&Text']);if(!id||!title||seen[id])continue;seen[id]=1;out.push({id:id,title:title,count:firstText(a[i],['.stat-item&&Text','.playlist-count&&Text']),img:abs(base,firstAttr(a[i],['img.main-thumb&&src','img&&src']))});}return out;}
P.librarySection30=function(kind){var a=P.sessionProfile32();if(!a||!a.id)throw new Error('请先登录');var base=C.resolveHost(false),id=String(a.id),path=kind==='watchLater'?('/user/'+id+'/saves'):kind==='favorites'?('/user/'+id+'/likes'):kind==='playlists'?('/user/'+id+'/playlists'):kind==='history'?('/user/'+id+'/histories?sort=latest&page=1'):'/subscriptions?page=1',r=C.get(base+path,{base:base,referer:base+'/',timeout:15000});if(!r||r.challenge||Number(r.statusCode||0)>=400)throw new Error('账号内容加载失败：HTTP '+Number((r&&r.statusCode)||0));var h=String(r.body||'');return kind==='playlists'?{playlists:playlistCards(h,base),items:[]}:{playlists:[],items:videoList(h,base)};};
function chooseAccountSection(k){return $('#noLoading#').lazyRule(function(v){putMyVar('hanime32_account_section',v);refreshPage(false);return 'hiker://empty';},k);}
function renderSection(d,cur){var r=P.librarySection30(cur);if(cur==='playlists'){d.push(H.sec('我的片单',r.playlists.length+' 个'));for(var i=0;i<r.playlists.length;i++){var p=r.playlists[i];d.push({title:p.title,desc:p.count||'',pic_url:p.img||'',url:H.route('hanimePlaylist',{id:p.id}),col_type:'movie_1_left_pic',extra:{lineVisible:false}});}if(!r.playlists.length)d.push(H.sec('暂无片单','官网当前没有返回可解析片单。'));return;}var names={favorites:'收藏',watchLater:'稍后看',subscriptions:'订阅',history:'观看历史'},list=r.items||[];d.push(H.sec(names[cur]||'账号内容',list.length+' 部'));for(var j=0;j<list.length;j++)d.push(L.video(list[j],'library'));if(!list.length)d.push(H.sec('暂无内容','当前栏目为空，或官网当前没有返回可解析影片。'));}
E.accountPage=function(){try{setPageTitle('账号中心');var d=[],p=null;try{p=P.profile();}catch(e){}if(!p||!p.id){d.push(H.sec('未登录','请先完成 Hanime1 登录。'));d.push(H.btn('登录 Hanime1',H.route('hanimeLogin',{}),'text_center_1'));setResult(d);return;}profileCache=profileItem(p);profileTs=Date.now();d.push({title:p.name||('用户 '+p.id),desc:[p.email,p.joined,'ID '+p.id].filter(Boolean).join(' · '),pic_url:p.avatar||'',url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false}});var cur=getMyVar('hanime32_account_section','playlists'),tabs=[['片单','playlists'],['收藏','favorites'],['稍后看','watchLater'],['订阅','subscriptions'],['历史','history']];for(var i=0;i<tabs.length;i++)d.push({title:(cur===tabs[i][1]?'✓ ':'')+tabs[i][0],url:chooseAccountSection(tabs[i][1]),col_type:'scroll_button'});d.push({col_type:'line_blank'});try{renderSection(d,cur);}catch(e){d.push(H.sec('账号内容加载失败',String(e.message||e)));}d.push(H.sec('账号资料'));d.push(H.btn('修改昵称','input://'+JSON.stringify({value:p.name||'',hint:'新昵称',js:"try{var p=$.require('hanime').provider(),x=p.profile();p.updateProfile(input,x.email||'');if(p.clearSessionProfile32)p.clearSessionProfile32();refreshPage(false);return 'toast://资料已更新';}catch(e){return 'toast://'+String(e.message||e);}"}),'text_2'));d.push(H.btn('修改邮箱','input://'+JSON.stringify({value:p.email||'',hint:'新邮箱',js:"try{var p=$.require('hanime').provider(),x=p.profile();p.updateProfile(x.name||'',input);if(p.clearSessionProfile32)p.clearSessionProfile32();refreshPage(false);return 'toast://邮箱已更新';}catch(e){return 'toast://'+String(e.message||e);}"}),'text_2'));d.push(H.btn('修改密码',H.route('hanimePassword',{}),'text_2'));d.push(H.btn('官网账号页面','x5://'+(p.base||C.resolveHost(false))+'/user/'+p.id+'/edit','text_2'));var saved=null;try{saved=oldActive();}catch(e){}if(!saved)d.push(H.btn('保存当前登录',$('#noLoading#').lazyRule(function(){try{var p=$.require('hanime').provider(),a=p.syncBrowserAccount();if(p.clearSessionProfile32)p.clearSessionProfile32();refreshPage(false);return 'toast://已保存 '+a.name;}catch(e){return 'toast://'+String(e.message||e);}}),'text_center_1'));d.push(H.btn('重新登录',H.route('hanimeLogin',{}),'text_center_1'));setResult(d);}catch(x){setResult([{title:'账号中心失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);
