/* Hanime1 Test32 community: resolve reply thread by video/comment index */
(function(C,P,E,H){
var ID_PREFIX='hanime32_comment_ids_',ID_TTL=120000;
function clean(v){return C.clean(String(v==null?'':v));}
function jsonPart(raw,key){try{var j=JSON.parse(String(raw||''));if(j&&typeof j[key]==='string')return j[key];}catch(e){}return String(raw||'');}
function xa(html,path){try{if(typeof xpathArray==='function')return xpathArray(String(html||''),path)||[];if(typeof xpa==='function')return xpa(String(html||''),path)||[];}catch(e){}return [];}
function idKey(videoId){return ID_PREFIX+String(videoId||'');}
function readIds(videoId){try{var raw=getItem(idKey(videoId),'');if(!raw)return null;var x=JSON.parse(raw);if(!x||!Array.isArray(x.ids)||!x.ids.length||Date.now()-Number(x.ts||0)>ID_TTL){clearItem(idKey(videoId));return null;}return x.ids;}catch(e){return null;}}
function writeIds(videoId,ids){if(!ids||!ids.length)return;try{setItem(idKey(videoId),JSON.stringify({ts:Date.now(),ids:ids}));}catch(e){}}
function extractIds(body){var out=[],seen={},re=/\bid\s*=\s*(["'])reply-section-wrapper-([^"']+)\1/gi,m;while((m=re.exec(String(body||'')))!==null){var id=String(m[2]||'');if(id&&!seen[id]){seen[id]=1;out.push(id);}if(m.index===re.lastIndex)re.lastIndex++;}if(out.length)return out;var a=xa(body,'//*[@id="comment-start"]//div[starts-with(@id,"reply-section-wrapper")]/@id');for(var i=0;i<a.length;i++){var s=String(a[i]||''),p='reply-section-wrapper-',id=s.indexOf(p)===0?s.slice(p.length):s;if(id&&!seen[id]){seen[id]=1;out.push(id);}}return out;}
P.commentIds32=function(videoId,force){videoId=String(videoId||'');if(!videoId)return [];if(!force){var c=readIds(videoId);if(c)return c;}var base=C.resolveHost(false),url=C.query(base+'/loadComment',{type:'video',id:videoId}),r=C.get(url,{base:base,referer:base+'/watch?v='+videoId,timeout:14000});if(!r||r.challenge||Number(r.statusCode||0)>=400||!String(r.body||''))return [];var ids=extractIds(jsonPart(r.body,'comments'));writeIds(videoId,ids);return ids;};
P.resolveReplyId32=function(videoId,index,fallback){var ids=P.commentIds32(videoId,false),i=Number(index);if(i>=0&&i<ids.length&&ids[i])return String(ids[i]);return String(fallback||'');};
function logged(){try{return !!P.profile();}catch(e){return false;}}
function composeReply(id,ok){return ok?('input://'+JSON.stringify({value:'',hint:'输入回复内容',js:"if(!input)return 'toast://回复不能为空';try{var p=$.require('hanime').provider();p.replyComment('"+id+"',input);if(p.clearReplyCache30)p.clearReplyCache30('"+id+"');refreshPage(false);return 'toast://回复已发布';}catch(e){return 'toast://'+String(e.message||e);}"})):H.route('hanimeLogin',{});}
function replyCard(d,x){d.push({title:x.user||'匿名用户',desc:x.time||'',pic_url:x.avatar||'',url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false}});d.push({title:x.content||'',url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false,textSize:16}});d.push({col_type:'line'});}
E.repliesPage=function(){try{var fallback=H.pv('id',''),videoId=H.pv('videoId',''),idx=Number(H.pv('index','-1')),expected=Number(H.pv('count','0')||0),u=H.pv('user','回复'),id=P.resolveReplyId32(videoId,idx,fallback),a=id?P.replies(id):[],used=id;if((!a||!a.length)&&fallback&&fallback!==id){var b=P.replies(fallback);if(b&&b.length){a=b;used=fallback;}}a=a||[];var d=[],ok=logged();setPageTitle(u+' · 回复');d.push(H.sec(u,'共 '+a.length+' 条回复'+(expected?(' · 原评论显示 '+expected+' 条'):'')));d.push(H.btn(ok?'回复此评论':'登录后回复',composeReply(used||fallback,ok),'text_center_1'));for(var i=0;i<a.length;i++)replyCard(d,a[i]);if(!a.length){d.push(H.sec('暂未取得回复','已按当前视频中的评论顺序重新定位真实回复线程；空结果不会缓存。'));d.push(H.btn('重新定位并重试',$('#noLoading#').lazyRule(function(v,fb){try{var p=$.require('hanime').provider();if(v){clearItem('hanime32_comment_ids_'+v);p.commentIds32(v,true);}if(p.clearReplyCache30&&fb)p.clearReplyCache30(fb);refreshPage(false);return 'toast://已重新定位回复线程';}catch(e){return 'toast://'+String(e.message||e);}},videoId,fallback),'text_center_1'));}setResult(d);}catch(x){setResult([{title:'回复加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
function composeComment(videoId,ok){return ok?('input://'+JSON.stringify({value:'',hint:'写下你的评论',js:"if(!input)return 'toast://评论不能为空';try{$.require('hanime').provider().postComment('"+videoId+"',input);refreshPage(false);return 'toast://评论已发布';}catch(e){return 'toast://'+String(e.message||e);}"})):H.route('hanimeLogin',{});}
function commentCard(d,c,videoId,index){var route=c.id?H.route('hanimeReplies',{id:c.id,videoId:videoId,index:index,count:c.replyCount||0,user:c.user||''}):'hiker://empty',meta=[c.time,c.replyCount?c.replyCount+' 回复':''].filter(Boolean).join(' · ');d.push({title:c.user||'匿名用户',desc:meta,pic_url:c.avatar||'',url:route,col_type:'avatar',extra:{lineVisible:false}});d.push({title:c.content||'',url:route,col_type:'long_text',extra:{lineVisible:false,textSize:16}});if(c.replyCount)d.push({title:'查看 '+c.replyCount+' 条回复 ›',url:route,col_type:'text_1',extra:{lineVisible:false}});d.push({col_type:'line'});}
E.commentsPage=function(){try{var videoId=H.pv('id',''),t=H.pv('title','视频'),r=P.comments(videoId),d=[],ok=logged(),page=Number(H.pv('page','1')||1),size=12;setPageTitle('评论');d.push(H.sec(t,'共 '+r.items.length+' 条评论 · 第 '+page+' 页'));d.push(H.btn(ok?'发表评论':'登录后发表评论',composeComment(videoId,ok),'text_center_1'));var start=(page-1)*size,end=Math.min(r.items.length,start+size);for(var i=start;i<end;i++)commentCard(d,r.items[i],videoId,i);if(page>1)d.push(H.btn('‹ 上一页',H.route('hanimeComments',{id:videoId,title:t,page:page-1})));if(end<r.items.length)d.push(H.btn('下一页 ›',H.route('hanimeComments',{id:videoId,title:t,page:page+1})));setResult(d);}catch(x){setResult([{title:'评论加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9);
