/* Hanime1 Test32 creator directory: real artist search + useful zero-query discovery */
(function(C,P){
var RECENT='hanime_recent_artists28';
function clean(v){return C.clean(String(v==null?'':v));}
function nodes(html,sel){try{return pdfa(String(html||''),sel)||[];}catch(e){return [];}}
function text(node,sel){try{return clean(pdfh(node,sel)||'');}catch(e){return '';}}
function attr(node,sel){try{return String(pdfh(node,sel)||'').replace(/&amp;/g,'&').trim();}catch(e){return '';}}
function firstText(node,sels){for(var i=0;i<sels.length;i++){var v=text(node,sels[i]);if(v)return v;}return '';}
function firstAttr(node,sels){for(var i=0;i<sels.length;i++){var v=attr(node,sels[i]);if(v)return v;}return '';}
function abs(base,u){u=String(u||'').trim();return u?C.abs(base,u):'';}
function pageCount(h,def){var total=Number(def||1),a=nodes(h,'ul.pagination li.page-item a.page-link');for(var i=0;i<a.length;i++){var n=parseInt(text(a[i],'Text'),10);if(n>total)total=n;}var mm=String(h||'').match(/page=(\d+)/g)||[];for(var j=0;j<mm.length;j++){var k=parseInt((mm[j].match(/\d+/)||['0'])[0],10);if(k>total)total=k;}return total;}
function recent(){try{var a=JSON.parse(getItem(RECENT,'[]'));return Array.isArray(a)?a:[];}catch(e){return [];}}
function add(out,seen,name,avatar,query,count){name=clean(name);if(!name||seen[name])return;seen[name]=1;out.push({name:name,avatar:avatar||'',query:query||name,count:count||''});}
function discover(){var out=[],seen={},a=recent();for(var i=0;i<a.length;i++)add(out,seen,a[i].name,a[i].avatar,a[i].query,a[i].count);try{var h=P.home(),sec=(h&&h.sections)||[];for(var s=0;s<sec.length&&out.length<30;s++){var list=sec[s].items||[];for(var j=0;j<list.length&&out.length<30;j++){var x=list[j];if(x&&x.artist)add(out,seen,x.artist,'',x.artist,'');}}}catch(e){}return out;}
function parseCards(h,base){var out=[],seen={},a=nodes(h,'.search-artist-card');for(var i=0;i<a.length;i++){var n=a[i],name=firstText(n,['.search-artist-title&&Text','.title&&Text']),img=firstAttr(n,['img[style*=object-fit]&&src','img&&data-src','img&&src']),href=firstAttr(n,['a.overlay&&href','a&&href']),q='';try{q=decodeURIComponent((String(href||'').match(/[?&]query=([^&]+)/)||[])[1]||'');}catch(e){}add(out,seen,name,abs(base,img),q||name,firstText(n,['.search-artist-count&&Text','.meta&&Text']));}if(out.length)return out;var src=String(h||''),re=/<[^>]+class\s*=\s*(["'])[^"']*search-artist-card[^"']*\1[^>]*>/gi,m,pos=[];while((m=re.exec(src))!==null){pos.push(m.index);if(m.index===re.lastIndex)re.lastIndex++;}for(var p=0;p<pos.length;p++){var f=src.slice(pos[p],p+1<pos.length?pos[p+1]:Math.min(src.length,pos[p]+18000)),nm=(f.match(/search-artist-title[^>]*>([\s\S]*?)<\//i)||[])[1]||'',hm=f.match(/href\s*=\s*(["'])([^"']+)\1/i),im=f.match(/<img\b[^>]*(?:data-src|src)\s*=\s*(["'])([^"']+)\1/i),cm=(f.match(/search-artist-count[^>]*>([\s\S]*?)<\//i)||[])[1]||'',href=hm?hm[2]:'',qq='';try{qq=decodeURIComponent((String(href).match(/[?&]query=([^&]+)/)||[])[1]||'');}catch(e){}add(out,seen,nm,abs(base,im?im[2]:''),qq||clean(nm),clean(cm));}return out;}
function fallbackFromVideos(q,page){var out=[],seen={};try{var r=P.search({query:q,page:page,type:''}),list=(r&&r.items)||[];for(var i=0;i<list.length;i++){var a=list[i]&&list[i].artist;if(a&&(!q||clean(a).toLowerCase().indexOf(clean(q).toLowerCase())>=0))add(out,seen,a,'',a,'来自影片结果');}return {items:out,page:Number(page||1),totalPages:Number((r&&r.totalPages)||page||1),query:q};}catch(e){return {items:[],page:Number(page||1),totalPages:Number(page||1),query:q};}}
P.artistDirectory28=function(query,page){var q=clean(query),p=Number(page||1);if(!q)return {items:discover(),page:1,totalPages:1,query:''};try{if(typeof P.artistDirectory26==='function'){var old=P.artistDirectory26(q,p);if(old&&old.items&&old.items.length)return old;}}catch(e){}var base=C.resolveHost(false),url=C.query(base+'/search',{page:p,query:q,type:'artist'}),r=C.get(url,{base:base,referer:base+'/',timeout:15000});if(r&&r.challenge)throw new Error('NEED_VERIFY|'+url+'|作者搜索');if(r&&Number(r.statusCode||0)<400){var h=String(r.body||''),items=parseCards(h,base);if(items.length)return {items:items,page:p,totalPages:pageCount(h,p),query:q};}return fallbackFromVideos(q,p);};
P.artistMeta28=function(name){name=clean(name);if(!name)return null;var r=P.artistDirectory28(name,1),a=r.items||[],pick=null;for(var i=0;i<a.length;i++){if(clean(a[i].name)===name){pick=a[i];break;}}return pick||(a.length?a[0]:null);};
})(HanimeCore,HanimeProvider);
