/* Hanime1 2.0.0-test.8 - professional filters / detail metadata / comments */
(function(C,P,E){
var BUILD='2.0.0-test.8';
function dec(v){v=String(v==null?'':v);for(var i=0;i<2;i++){try{var n=decodeURIComponent(v);if(n===v)break;v=n;}catch(e){break;}}return v;}
function pv(k,d){try{var x=getParam(k);if(x!==undefined&&x!==null&&String(x)!=='')return dec(x);}catch(e){}try{if(MY_PARAMS&&MY_PARAMS[k]!==undefined)return dec(MY_PARAMS[k]);}catch(y){}return d||'';}
function route(p,o){var q=[];Object.keys(o||{}).forEach(function(k){if(o[k]!==undefined&&o[k]!==null&&String(o[k])!=='')q.push(encodeURIComponent(k)+'='+encodeURIComponent(String(o[k])));});return 'hiker://page/'+p+'?rule=&simple=true'+(q.length?'&'+q.join('&'):'');}
function sec(t,d){return {title:t,desc:d||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}};}
function btn(t,u,c){return {title:t,url:u,col_type:c||'text_3',extra:{lineVisible:false}};}
function vin(x,c){return {title:x.title||'未命名',desc:[x.duration,x.views,x.rating,x.artist,x.upload].filter(Boolean).join(' · '),pic_url:x.img||x.cover||'',url:route('hanimeDetail',{id:x.id,title:x.title}),col_type:c||'movie_3',extra:{lineVisible:false}};}
function chip(t,selected,url){return {title:(selected?'✓ ':'')+t,url:url||'hiker://empty',col_type:'flex_button',extra:{lineVisible:false}};}
function label(arr,val){for(var i=0;i<arr.length;i++)if(String(arr[i][1])===String(val))return arr[i][0];return val||'全部';}
function tags(){try{var a=JSON.parse(getMyVar('hanime8_tags','[]'));return Array.isArray(a)?a:[];}catch(e){return [];}}
function state(){var cat=P.filterCatalog||{},ts=tags();return {sort:getMyVar('hanime8_sort','最新上傳'),genre:getMyVar('hanime8_genre',''),date:getMyVar('hanime8_date',''),duration:getMyVar('hanime8_duration',''),tags:ts,broad:getMyVar('hanime8_broad','0')==='1',cat:cat};}
function summary(s){return '类型 '+label(s.cat.genres||[],s.genre)+' · 排序 '+label(s.cat.sorts||[],s.sort)+' · 日期 '+label(s.cat.dates||[],s.date)+' · 时长 '+label(s.cat.durations||[],s.duration)+' · 标签 '+s.tags.length;}
function setChoice(key,val){return $('#noLoading#').lazyRule(function(k,v){putMyVar(k,v);refreshPage(false);return 'hiker://empty';},key,val);}
function toggleTag(v){return $('#noLoading#').lazyRule(function(x){var a=[];try{a=JSON.parse(getMyVar('hanime8_tags','[]'));if(!Array.isArray(a))a=[];}catch(e){}var i=a.indexOf(x);if(i>=0)a.splice(i,1);else a.push(x);putMyVar('hanime8_tags',JSON.stringify(a));refreshPage(false);return 'hiker://empty';},v);}
var oldExplore=E.renderExplore;
E.renderExplore=function(d){if(getMyVar('hanime2_content','video')==='comic')d.push({title:'漫画分类 · 标签 / 作者 / 角色 / 同人 / 社团',desc:'进入完整漫画目录筛选',url:route('hanimeComicFilter',{}),col_type:'text_1',extra:{lineVisible:false}});oldExplore(d);};
E.renderLibrary=function(d,page){page=Number(page||1);var s=state();if(page===1){d.push(sec('公开片库','无需登录。筛选参数直接使用 Hanime1 官网当前真实 search_key。'));d.push({title:'专业筛选',desc:summary(s),url:route('hanimeVideoFilter',{}),col_type:'text_1',extra:{lineVisible:false}});}var r=P.publicLibrary({sort:s.sort,genre:s.genre,date:s.date,duration:s.duration,tags:s.tags,broad:s.broad,page:page}),list=r.items||[];if(page===1)d.push(sec('筛选结果',list.length+' 部 · '+summary(s)));for(var i=0;i<list.length;i++)d.push(vin(list[i],'movie_3'));if(!list.length)d.push(sec('暂无结果','可进入“专业筛选”调整条件。'));};
E.videoFilterPage=function(){try{setPageTitle('影片筛选');var d=[],s=state(),cat=s.cat,g,i,arr;d.push(sec('影片筛选',summary(s)));d.push(sec('影片类型'));arr=cat.genres||[];for(i=0;i<arr.length;i++)d.push(chip(arr[i][0],String(s.genre)===String(arr[i][1]),setChoice('hanime8_genre',arr[i][1])));d.push(sec('排序方式'));arr=cat.sorts||[];for(i=0;i<arr.length;i++)d.push(chip(arr[i][0],String(s.sort)===String(arr[i][1]),setChoice('hanime8_sort',arr[i][1])));d.push(sec('发布日期'));arr=cat.dates||[];for(i=0;i<arr.length;i++)d.push(chip(arr[i][0],String(s.date)===String(arr[i][1]),setChoice('hanime8_date',arr[i][1])));d.push(sec('时长'));arr=cat.durations||[];for(i=0;i<arr.length;i++)d.push(chip(arr[i][0],String(s.duration)===String(arr[i][1]),setChoice('hanime8_duration',arr[i][1])));d.push(sec('内容标签',s.tags.length?'已选 '+s.tags.join(' / '):'未选择标签'));var groups=Object.keys(cat.tags||{}),cur=getMyVar('hanime8_tag_group',groups[0]||'影片属性');for(g=0;g<groups.length;g++)d.push({title:(cur===groups[g]?'● ':'')+groups[g],url:setChoice('hanime8_tag_group',groups[g]),col_type:'scroll_button'});arr=(cat.tags||{})[cur]||[];for(i=0;i<arr.length;i++)d.push(chip(arr[i],s.tags.indexOf(arr[i])>=0,toggleTag(arr[i])));d.push(sec('标签匹配'));d.push(chip('宽松匹配 broad',s.broad,setChoice('hanime8_broad',s.broad?'0':'1')));d.push(btn('清空全部筛选',$('#noLoading#').lazyRule(function(){putMyVar('hanime8_sort','最新上傳');clearMyVar('hanime8_genre');clearMyVar('hanime8_date');clearMyVar('hanime8_duration');clearMyVar('hanime8_tags');clearMyVar('hanime8_broad');refreshPage(false);return 'hiker://empty';}),'text_center_1'));s=state();var page=Number(pv('page','1')||1),r=P.publicLibrary({sort:s.sort,genre:s.genre,date:s.date,duration:s.duration,tags:s.tags,broad:s.broad,page:page}),list=r.items||[];d.push(sec('即时结果','第 '+page+' 页 · '+list.length+' 部'));for(i=0;i<list.length;i++)d.push(vin(list[i],'movie_3'));if(page>1)d.push(btn('‹ 上一页',route('hanimeVideoFilter',{page:page-1})));if(page<Number(r.totalPages||page))d.push(btn('下一页 ›',route('hanimeVideoFilter',{page:page+1})));setResult(d);}catch(x){setResult([{title:'筛选页加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.comicFilterPage=function(){try{setPageTitle('漫画分类');var d=[],tax=P.comicTaxonomy||[],cur=pv('path',getMyVar('hanime8_comic_tax','/comics/tags')),q=pv('q',''),i;d.push(sec('漫画分类','按 HanimeOne 官网目录浏览：标签、作者、角色、同人、社团、语言、分类。'));for(i=0;i<tax.length;i++)d.push({title:(cur===tax[i][1]?'● ':'')+tax[i][0],url:$('#noLoading#').lazyRule(function(v){putMyVar('hanime8_comic_tax',v);refreshPage(false);return 'hiker://empty';},tax[i][1]),col_type:'scroll_button'});d.push({title:'筛选目录关键词',url:'input://'+JSON.stringify({value:q||'',hint:'输入名称筛选当前目录',js:"return '"+route('hanimeComicFilter',{path:cur})+"&q='+encodeURIComponent(input);"}),col_type:'input'});var list=P.comicDirectory(cur),show=[];for(i=0;i<list.length;i++)if(!q||String(list[i].name).toLowerCase().indexOf(String(q).toLowerCase())>=0)show.push(list[i]);d.push(sec('目录','共 '+show.length+' 项'));for(i=0;i<show.length;i++)d.push(chip(show[i].name+(show[i].count?' · '+show[i].count:''),false,route('hanimeComicBrowse',{path:show[i].path,page:1})));setResult(d);}catch(x){var m=String(x.message||x);if(m.indexOf('NEED_VERIFY|')===0)setResult([sec('漫画站需要验证'),btn('打开漫画站验证',route('hanimeVerify',{url:m.split('|')[1]||C.comicHost}),'text_center_1')]);else setResult([{title:'漫画分类加载失败',desc:m,url:'hiker://empty',col_type:'text_center_1'}]);}};
E.detail=function(){try{var id=pv('id','');if(!id)throw new Error('缺少视频 ID');var v=P.video(id),d=[],top=(v.sources&&v.sources.length)?String(v.sources[0].quality||'最高'):'待解析';setPageTitle(v.title);d.push({title:v.title,desc:[v.artist,v.genre,v.views?('观看 '+v.views):'',v.upload,v.duration].filter(Boolean).join('\n'),pic_url:v.cover||'',url:$('#noLoading#').lazyRule(function(x){return $.require('hanime').play(x);},id),col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false}});d.push(btn('播放 · '+top,$('#noLoading#').lazyRule(function(x){return $.require('hanime').play(x);},id)));d.push(btn('稍后看',$('#noLoading#').lazyRule(function(x){try{$.require('hanime').provider().saveToPlaylist(x,'save',true);return 'toast://已加入稍后看';}catch(e){return 'toast://'+String(e.message||e);}},id)));d.push(btn('收藏',$('#noLoading#').lazyRule(function(x){try{$.require('hanime').provider().setFavorite(x,true);return 'toast://已收藏';}catch(e){return 'toast://'+String(e.message||e);}},id)));d.push(btn('加入片单',route('hanimePlaylistPicker',{id:id})));d.push(btn('评论'+(v.commentCount!==undefined?' · '+v.commentCount:''),route('hanimeComments',{id:id,title:v.title})));if(v.download)d.push(btn('下载原片','download://'+v.download));d.push(sec('影片信息',[v.artist?'作者：'+v.artist:'',v.genre?'类型：'+v.genre:'',v.views?'观看：'+v.views:'',v.upload?'上传：'+v.upload:'',v.duration?'时长：'+v.duration:'',v.commentCount!==undefined?'评论：'+v.commentCount:''].filter(Boolean).join('\n')));if(v.tags&&v.tags.length){d.push(sec('内容标签','点击标签可直接进入同标签影片筛选'));for(var i=0;i<v.tags.length;i++){var tg=v.tags[i];d.push(chip(tg.name+(tg.count?' · '+tg.count:''),false,$('#noLoading#').lazyRule(function(t){putMyVar('hanime8_tags',JSON.stringify([t]));return 'hiker://page/hanimeVideoFilter?rule=&simple=true';},tg.name)));}}if(v.sources&&v.sources.length)d.push(sec('画质','默认优先最高画质 · '+v.sources.map(function(s){return s.quality||'默认';}).join(' / ')));if(v.caption)d.push({title:'简介',desc:v.caption,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});if(v.related&&v.related.length){d.push(sec('相关推荐',v.related.length+' 部'));for(var j=0;j<v.related.length;j++)d.push(vin(v.related[j],'movie_3'));}setResult(d);}catch(x){setResult([{title:'详情加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.comicDetail=function(){try{var id=pv('id',''),c=P.comicDetail(id),d=[],u='pics://'+c.images.join('&&');setPageTitle(c.title);d.push({title:c.title,desc:[c.artist,c.upload,c.count?('共 '+c.count+' 页'):''].filter(Boolean).join('\n'),pic_url:c.cover||'',url:u,col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false}});d.push(btn('开始阅读',u,'text_center_1'));d.push(btn('漫画分类',route('hanimeComicFilter',{}),'text_center_1'));d.push(sec('漫画信息',[c.artist?'作者：'+c.artist:'',c.upload?'上传：'+c.upload:'',c.count?'页数：'+c.count:''].filter(Boolean).join('\n')));var groups={},i;for(i=0;i<(c.tags||[]).length;i++){var t=c.tags[i];if(!groups[t.type])groups[t.type]=[];groups[t.type].push(t);}Object.keys(groups).forEach(function(k){d.push(sec(k));for(var n=0;n<groups[k].length;n++){var t=groups[k][n];d.push(chip(t.name,false,route('hanimeComicBrowse',{path:t.path,page:1})));}});if(c.desc)d.push({title:'简介',desc:c.desc,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});if(c.related&&c.related.length){d.push(sec('相关漫画'));for(i=0;i<c.related.length;i++)if(String(c.related[i].id)!==String(id))d.push({title:c.related[i].title,pic_url:c.related[i].img,url:route('hanimeComicDetail',{id:c.related[i].id,title:c.related[i].title}),col_type:'movie_3'});}setResult(d);}catch(x){var m=String(x.message||x);if(m.indexOf('NEED_VERIFY|')===0)setResult([sec('漫画站需要验证'),btn('打开漫画站验证',route('hanimeVerify',{url:m.split('|')[1]||C.comicHost}),'text_center_1')]);else setResult([{title:'漫画详情失败',desc:m,url:'hiker://empty',col_type:'text_center_1'}]);}};
E.commentsPage=function(){try{var id=pv('id',''),t=pv('title','视频'),r=P.comments(id),d=[],logged=false,page=Number(pv('page','1')||1),size=40;try{logged=!!P.profile();}catch(e){}setPageTitle('评论');d.push(sec(t,'共 '+r.items.length+' 条 · 第 '+page+' 页'));d.push(btn(logged?'发表评论':'登录后发表评论',logged?('input://'+JSON.stringify({value:'',hint:'输入评论内容',js:"if(!input)return 'toast://评论不能为空';try{$.require('hanime').provider().postComment('"+id+"',input);refreshPage(false);return 'toast://评论已发布';}catch(e){return 'toast://'+String(e.message||e);}"})):route('hanimeLogin',{}),'text_center_1'));var start=(page-1)*size,end=Math.min(r.items.length,start+size);for(var i=start;i<end;i++){var c=r.items[i],tail=[c.time,c.replyCount?c.replyCount+' 回复':''].filter(Boolean).join(' · ');d.push({title:'‘‘'+c.user+'’’'+(tail?'  '+tail:''),desc:c.content,url:c.id?route('hanimeReplies',{id:c.id,user:c.user}):'hiker://empty',col_type:'text_1',extra:{lineVisible:true}});}if(page>1)d.push(btn('‹ 上一页',route('hanimeComments',{id:id,title:t,page:page-1})));if(end<r.items.length)d.push(btn('下一页 ›',route('hanimeComments',{id:id,title:t,page:page+1})));if(!r.items.length)d.push(sec('暂无评论'));setResult(d);}catch(x){setResult([{title:'评论加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.repliesPage=function(){try{var id=pv('id',''),u=pv('user','回复'),a=P.replies(id),d=[],logged=false;try{logged=!!P.profile();}catch(e){}setPageTitle(u+' · 回复');d.push(btn(logged?'回复此评论':'登录后回复',logged?('input://'+JSON.stringify({value:'',hint:'输入回复内容',js:"if(!input)return 'toast://回复不能为空';try{$.require('hanime').provider().replyComment('"+id+"',input);refreshPage(false);return 'toast://回复已发布';}catch(e){return 'toast://'+String(e.message||e);}"})):route('hanimeLogin',{}),'text_center_1'));for(var i=0;i<a.length;i++)d.push({title:'‘‘'+a[i].user+'’’'+(a[i].time?'  '+a[i].time:''),desc:a[i].content,url:'hiker://empty',col_type:'text_1',extra:{lineVisible:true}});if(!a.length)d.push(sec('暂无回复'));setResult(d);}catch(x){setResult([{title:'回复加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
function fmtMonth(v){v=String(v||'').replace(/[^0-9]/g,'');if(v.length<6){var n=new Date(),m=String(n.getMonth()+1);if(m.length<2)m='0'+m;v=String(n.getFullYear())+m;}return v.slice(0,4)+'-'+v.slice(4,6);}
function shiftMonth(v,step){v=String(v||'').replace(/[^0-9]/g,'');if(v.length<6)return fmtMonth(v);var y=parseInt(v.slice(0,4),10),m=parseInt(v.slice(4,6),10)-1+step,n=new Date(y,m,1),mm=String(n.getMonth()+1);if(mm.length<2)mm='0'+mm;return n.getFullYear()+'-'+mm;}
E.previews=function(){try{setPageTitle('新番预告');var m=fmtMonth(pv('month','')),d=[];d.push(btn('‹ '+shiftMonth(m,-1),route('hanimePreviews',{month:shiftMonth(m,-1)})));d.push(btn('月份 · '+m,'hiker://empty'));d.push(btn(shiftMonth(m,1)+' ›',route('hanimePreviews',{month:shiftMonth(m,1)})));var a=P.previews(m),src=a.length?(a[0].source||'Hanime1'):'Hanime1';d.push(sec('预告来源',src==='Getchu'?'Hanime1 预告接口当前不可用，已自动切换 Getchu 月度新番。':'Hanime1 官网预告'));for(var i=0;i<a.length;i++){var it=a[i],url=it.detailUrl?('x5://'+it.detailUrl):(/^\d+$/.test(String(it.id||''))?route('hanimeDetail',{id:it.id,title:it.title}):'hiker://empty');d.push({title:it.title,desc:[it.brand,it.desc,it.source].filter(Boolean).join('\n'),pic_url:it.img||'',url:url,col_type:'movie_1_left_pic',extra:{lineVisible:false}});}if(!a.length)d.push(sec('本月暂无预告'));setResult(d);}catch(x){var base=C.resolveHost(false),m=fmtMonth(pv('month','')),mm=String(m).replace(/-/g,'');setResult([sec('预告线路暂不可用',String(x.message||x)),btn('打开 Hanime1 预告','x5://'+base+'/previews/'+mm),btn('打开 Getchu 月度新番','x5://https://www.getchu.com/all/month_title.html?genre=anime_dvd&gage=adult&year='+mm.slice(0,4)+'&month='+mm.slice(4,6)+'&gc=gc')]);}};
E.build=BUILD;P.build=BUILD;C.build=BUILD;
})(HanimeCore,HanimeProvider,HanimePages);
