/* Hanime1 2.0.0-test.8 - exact official filters / cover repair / preview fallback */
(function(C,P,W){
var BUILD='2.0.0-test.8';
function dh(s){return W&&W.dh?W.dh(s):String(s==null?'':s).replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'");}
function strip(s){return W&&W.strip?W.strip(s):C.clean(s);}
function attr(tag,n){return W&&W.attr?W.attr(tag,n):((String(tag||'').match(new RegExp('\\b'+n+'\\s*=\\s*(["\\\'])([\\s\\S]*?)\\1','i'))||[])[2]||'');}
function abs(base,u){return C.abs(base,dh(u));}
function goodImg(u){u=String(u||'').trim();return !!u&&!/^(?:data:|about:blank)/i.test(u)&&!/placeholder|loading|spinner|home_poster_background|transparent|blank\.(?:gif|png)/i.test(u);}
function srcset(v){v=dh(v);if(!v)return '';var first=v.split(',')[0].trim();return first.replace(/\s+\d+(?:\.\d+)?[wx]$/i,'').trim();}
function tagImg(t){var names=['src','data-src','data-srcset','srcset'];for(var i=0;i<names.length;i++){var u=attr(t,names[i]);if(names[i].indexOf('srcset')>=0)u=srcset(u);if(goodImg(u))return u;}return '';}
function bestImage(f){f=String(f||'');var ts=f.match(/<img\b[^>]*>/gi)||[],i;for(i=0;i<ts.length;i++)if(/\bmain-thumb\b/i.test(attr(ts[i],'class'))){var m=tagImg(ts[i]);if(m)return m;}for(i=0;i<ts.length;i++){var u=tagImg(ts[i]);if(u)return u;}return '';}
function idFrom(u){var m=String(u||'').match(/[?&]v=(\d+)/i);return m?m[1]:'';}
function textClass(f,cls){if(W&&W.textClass)return W.textClass(f,cls);var m=String(f||'').match(new RegExp('<[^>]*class\\s*=\\s*(["\\\'])[^"\\\']*'+cls+'[^"\\\']*\\1[^>]*>([\\s\\S]*?)<\\/[^>]+>','i'));return m?strip(m[2]):'';}
function card(f,base){f=String(f||'');var hm=f.match(/href\s*=\s*(["'])([^"']*watch\?[^"']*\bv=\d+[^"']*)\1/i),href=hm?dh(hm[2]):'',id=idFrom(href);if(!id)return null;var title=textClass(f,'home-rows-videos-title')||textClass(f,'title')||textClass(f,'video-title'),im=bestImage(f),dur=textClass(f,'duration')||textClass(f,'card-mobile-duration'),artist=textClass(f,'subtitle')||textClass(f,'meta-author'),meta=textClass(f,'meta-stats')||textClass(f,'card-mobile-meta'),views='',rating='';var stats=[],re=/<[^>]+class\s*=\s*(["'])[^"']*stat-item[^"']*\1[^>]*>([\s\S]*?)<\/[^>]+>/gi,m;while((m=re.exec(f))!==null){var s=strip(m[2]);if(s)stats.push(s);if(m.index===re.lastIndex)re.lastIndex++;}if(stats.length){rating=stats[0]||'';views=stats[1]||stats[0]||'';}if(!title){var it=(f.match(/<img\b[^>]*>/i)||[])[0]||'';title=attr(it,'alt');}return {id:id,title:title||('影片 '+id),url:abs(base,href),img:abs(base,im),duration:dur,rating:rating,views:views,artist:artist,upload:meta};}
function cards(h,base){h=String(h||'');var out=[],pos=[],re=/<div\b[^>]*class\s*=\s*(["'])[^"']*(?:horizontal-card|video-item-container|user-tab-item-wrapper)[^"']*\1[^>]*>/gi,m;while((m=re.exec(h))!==null){pos.push(m.index);if(m.index===re.lastIndex)re.lastIndex++;}if(!pos.length){var rr=/href\s*=\s*(["'])[^"']*watch\?[^"']*\bv=\d+[^"']*\1/gi,mm;while((mm=rr.exec(h))!==null){pos.push(Math.max(0,mm.index-2500));if(mm.index===rr.lastIndex)rr.lastIndex++;}}var seen={};for(var i=0;i<pos.length;i++){var c=card(h.slice(pos[i],i+1<pos.length?pos[i+1]:Math.min(h.length,pos[i]+18000)),base);if(c&&!seen[c.id]){seen[c.id]=1;out.push(c);}}return out;}
var GENRES=[['全部',''],['里番','裏番'],['泡面番','泡麵番'],['Motion Anime','Motion Anime'],['3D动画','3DCG'],['2.5D','2.5D'],['2D动画','2D動畫'],['AI生成','AI生成'],['MMD','MMD'],['Cosplay','Cosplay']];
var SORTS=[['默认',''],['最新上市','最新上市'],['最新上传','最新上傳'],['本日排行','本日排行'],['本周排行','本週排行'],['本月排行','本月排行'],['观看次数','觀看次數'],['点赞比例','讚好比例'],['他们在看','他們在看'],['时长最长','時長最長']];
var DATES=[['全部',''],['过去24小时','過去 24 小時'],['过去2天','過去 2 天'],['过去1周','過去 1 週'],['过去1个月','過去 1 個月'],['过去3个月','過去 3 個月'],['过去1年','過去 1 年']];
var DURATIONS=[['全部',''],['1分钟以上','1 分鐘 +'],['5分钟以上','5 分鐘 +'],['10分钟以上','10 分鐘 +'],['20分钟以上','20 分鐘 +'],['30分钟以上','30 分鐘 +'],['60分钟以上','60 分鐘 +'],['0~10分钟','0 - 10 分鐘'],['0~20分钟','0 - 20 分鐘']];
var TAGS={
 '影片属性':['無碼','AI解碼','中文字幕','中文配音','同人作品','斷面圖','ASMR','1080p','60FPS'],
 '人物关系':['近親','姐','妹','母','女兒','師生','情侶','青梅竹馬','同事'],
 '角色设定':['JK','處女','御姐','熟女','人妻','女教師','男教師','女醫生','女病人','護士','OL','女警','大小姐','偶像','女僕','巫女','魔女','修女','風俗娘','公主','女忍者','女戰士','女騎士','魔法少女','異種族','天使','妖精','魔物娘','魅魔','吸血鬼','女鬼','獸娘','福瑞','乳牛','機械娘','碧池','痴女','雌小鬼','不良少女','傲嬌','病嬌','無口','無表情','眼神死','正太','偽娘','扶他'],
 '外貌身材':['短髮','馬尾','雙馬尾','丸子頭','巨乳','乳環','舌環','貧乳','黑皮膚','曬痕','眼鏡娘','獸耳','尖耳朵','異色瞳','美人痣','肌肉女','白虎','陰毛','腋毛','大屌','黑屌','著衣','水手服','體操服','泳裝','比基尼','死庫水','和服','兔女郎','圍裙','啦啦隊','絲襪','吊襪帶','熱褲','迷你裙','性感內衣','緊身衣','丁字褲','高跟鞋','睡衣','婚紗','旗袍','古裝','哥德','口罩','刺青','淫紋','身體寫字'],
 '情境场所':['校園','教室','圖書館','保健室','體育倉庫','游泳池','愛情賓館','醫院','辦公室','浴室','窗邊','公共廁所','公眾場合','戶外野戰','電車','車震','遊艇','露營帳篷','電影院','健身房','沙灘','溫泉','夜店','監獄','教堂'],
 '故事剧情':['純愛','戀愛喜劇','後宮','十指緊扣','開大車','NTR','精神控制','藥物','痴漢','阿嘿顏','哭泣','精神崩潰','獵奇','BDSM','綑綁','眼罩','項圈','調教','異物插入','尋歡洞','肉便器','性奴隸','胃凸','強制','輪姦','凌辱','性暴力','逆強制','女王樣','榨精','母女丼','姐妹丼','出軌','醉酒','攝影','睡眠姦','機械姦','蟲姦','性轉換','百合','耽美','時間停止','異世界','怪獸','哥布林','世界末日'],
 '性交体位':['手交','指交','玩乳頭','乳交','乳頭交','肛交','雙洞齊下','腳交','素股','拳交','3P','群交','口交','跪舔','深喉嚨','口爆','吞精','舔蛋蛋','舔穴','69','自慰','腋交','舔腋下','髮交','舔耳朵','舔腳','內射','外射','顏射','潮吹','懷孕','噴奶','放尿','排便','騎乘位','背後位','側面位','顏面騎乘','火車便當','一字馬','性玩具','飛機杯','跳蛋','毒龍鑽','觸手','獸交','頸手枷','扯頭髮','掐脖子','打屁股','肉棒打臉','陰道外翻','男乳首責','接吻','舌吻','POV']
};
P.filterCatalog={genres:GENRES,sorts:SORTS,dates:DATES,durations:DURATIONS,tags:TAGS};
P.filters={genres:GENRES,sorts:SORTS,dates:DATES,durations:DURATIONS,types:[['视频',''],['作者','artist']]};
P.search=function(o){o=o||{};var base=C.resolveHost(false),tags=Array.isArray(o.tags)?o.tags:[],url=C.query(base+'/search',{page:o.page||1,query:o.query||'',genre:o.genre||'',sort:o.sort||'',date:o.date||'',duration:o.duration||'','tags[]':tags,broad:o.broad?'on':'',type:o.type||''}),r=C.get(url,{base:base,referer:base+'/',timeout:18000});if(r.challenge)throw new Error('NEED_VERIFY|'+url+'|搜索');if(!r||Number(r.statusCode||0)>=400)throw new Error('搜索失败：HTTP '+Number((r&&r.statusCode)||0));var list=cards(r.body,base),total=Number(o.page||1),pm=String(r.body||'').match(/page=(\d+)/g)||[];for(var i=0;i<pm.length;i++){var n=parseInt((pm[i].match(/\d+/)||[0])[0],10);if(n>total)total=n;}return {url:url,items:list,artists:[],page:Number(o.page||1),totalPages:total};};
P.publicLibrary=function(opt){opt=opt||{};return P.search({query:'',genre:opt.genre||'',sort:opt.sort||'',date:opt.date||'',duration:opt.duration||'',tags:opt.tags||[],broad:!!opt.broad,type:'',page:Number(opt.page||1)});};
P.librarySorts=SORTS;
var oldVideo=P.video;
P.video=function(id){var v=oldVideo(id),h=String(v.raw||''),base=v.base||C.resolveHost(false),ri=h.indexOf('related-tabcontent');if(ri>=0)v.related=cards(h.slice(ri,Math.min(h.length,ri+220000)),base).filter(function(x){return String(x.id)!==String(id);});var cm=h.match(/id\s*=\s*(["'])tab-comments-count\1[^>]*>([\s\S]*?)<\/[^>]+>/i);if(cm)v.commentCount=parseInt(strip(cm[2]).replace(/\D/g,''),10)||0;var gm=h.match(/<a\b[^>]*href\s*=\s*(["'])[^"']*genre[^"']*\1[^>]*>([\s\S]*?)<\/a>/i);if(gm)v.genre=strip(gm[2]);return v;};
function previewItems(h,base){var out=[],re=/<div\b[^>]*class\s*=\s*(["'])[^"']*\brow\b[^"']*\1[^>]*\bid\s*=\s*(["'])([^"']+)\2[^>]*>/gi,m,starts=[];while((m=re.exec(String(h||'')))!==null){starts.push({i:m.index,id:m[3]});if(m.index===re.lastIndex)re.lastIndex++;}for(var i=0;i<starts.length;i++){var f=String(h).slice(starts[i].i,i+1<starts.length?starts[i+1].i:Math.min(String(h).length,starts[i].i+50000));if(f.indexOf('preview-info-cover')<0)continue;var im='',ims=f.match(/<img\b[^>]*>/gi)||[];for(var j=0;j<ims.length;j++){im=tagImg(ims[j]);if(im)break;}var tm=f.match(/<h4\b[^>]*>([\s\S]*?)<\/h4>/i)||f.match(/<h3\b[^>]*>([\s\S]*?)<\/h3>/i),title=tm?strip(tm[1]):'',bm=f.match(/preview-info-content-padding[\s\S]{0,8000}?<h5[^>]*>[\s\S]*?<a\b[^>]*>([\s\S]*?)<\/a>/i),brand=bm?strip(bm[1]):'',cap=textClass(f,'caption');if(title&&im)out.push({id:starts[i].id,title:title,img:abs(base,im),brand:brand,desc:cap,source:'Hanime1'});}return out;}
function getchu(month){var y=month.slice(0,4),mo=month.slice(4,6),base='https://www.getchu.com',url=C.query(base+'/all/month_title.html',{genre:'anime_dvd',gage:'adult',year:y,month:mo,gc:'gc'}),r=C.get(url,{base:base,referer:base+'/',timeout:20000,verify:false,headers:{'Cookie':'getchu_adalt_flag=getchu.com; gc=gc','content-type':'text/html; charset=EUC-JP'}});if(!r||Number(r.statusCode||0)<200||Number(r.statusCode||0)>=300)return [];var h=String(r.body||''),out=[],re=/<div\b[^>]*class\s*=\s*(["'])[^"']*div_product[^"']*\1[^>]*>([\s\S]*?)(?=<div\b[^>]*class\s*=\s*(["'])[^"']*div_product|$)/gi,m;while((m=re.exec(h))!==null){var f=m[2],lm=f.match(/<a\b[^>]*href\s*=\s*(["'])([^"']*(?:soft\.phtml|\/item\/)[^"']*)\1[^>]*>([\s\S]*?)<\/a>/i);if(!lm)continue;var href=dh(lm[2]),id=((href.match(/(?:id=|\/item\/)(\d+)/)||[])[1]||''),title=strip(lm[3]),ims=f.match(/<img\b[^>]*>/gi)||[],im='';for(var k=0;k<ims.length;k++){var u=tagImg(ims[k]);if(u&&/package/i.test(u)){im=u.replace('package_s.','package.');break;}}if(!title&&ims.length)title=attr(ims[0],'alt');if(id&&title)out.push({id:'getchu-'+id,title:title,img:abs(base,im),brand:'Getchu',desc:'新番发售预告',source:'Getchu',detailUrl:base+'/item/'+id+'/?gc=gc'});if(m.index===re.lastIndex)re.lastIndex++;}return out;}
P.previews=function(month){month=String(month||'').replace(/[^0-9]/g,'').slice(0,6);if(month.length<6){var d=new Date(),mm=String(d.getMonth()+1);if(mm.length<2)mm='0'+mm;month=String(d.getFullYear())+mm;}var hosts=C.videoHosts||[C.resolveHost(false)],errors=[];for(var i=0;i<hosts.length;i++){var b=String(hosts[i]).replace(/\/$/,''),u=b+'/previews/'+month,r=C.get(u,{base:b,referer:b+'/',timeout:15000});if(r&&Number(r.statusCode||0)>=200&&Number(r.statusCode||0)<300&&!r.challenge){var a=previewItems(r.body,b);if(a.length)return a;}errors.push(b+' HTTP '+Number((r&&r.statusCode)||0));}var g=getchu(month);if(g.length)return g;var e=new Error('预告线路均不可用：'+errors.join('；'));e.previewErrors=errors;throw e;};
P.previewMonth=function(v){v=String(v||'').replace(/[^0-9]/g,'');return v.length>=6?v.slice(0,6):'';};
P._test8={bestImage:bestImage,cards:cards,card:card};
P.build=BUILD;C.build=BUILD;
})(HanimeCore,HanimeProvider,HanimeWeb6);
