/* 我的规则仓库 v3.4.0 - category management center */
(function(R){
R.categoryPage=function(){setPageTitle('分类管理');var d=[],items;try{items=this.items(false);}catch(e){setResult([{title:'仓库读取失败',desc:String(e.message||e),url:'hiker://empty',col_type:'long_text'}]);return;}var state=this.filterState();this.pushNav(d,'category');
d.push({title:'当前筛选',desc:this.filterSummary(state),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'程序 '+this.applyFilters(items,state).length,col_type:'text_2',url:'hiker://empty',extra:{lineVisible:false}});d.push({title:'重置筛选',col_type:'text_2',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearAllFilters();refreshPage(false);return'toast://筛选已重置';}),extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'主分类','按内容类型快速定位');this.categories(items).forEach(function(c){d.push({title:(state.category===c.id?'● ':'')+c.name+' '+c.count,col_type:'text_3',url:$('#noLoading#').lazyRule(function(id){putMyVar('hc_repo_category',id);putMyVar('hc_repo_sub','all');putMyVar('hc_repo_tag','all');refreshPage(false);return'hiker://empty';},c.id),extra:{lineVisible:false}});});
var subs=this.subCategories(items,state.category);if(subs.length>1){this.pushSpacer(d);this.pushSection(d,'子分类',state.category==='all'?'全部程序':'当前：'+this.categoryName(state.category));subs.forEach(function(s){d.push({title:(state.subCategory===s.id?'● ':'')+s.name+' '+s.count,col_type:'text_3',url:$('#noLoading#').lazyRule(function(id){putMyVar('hc_repo_sub',id);putMyVar('hc_repo_tag','all');refreshPage(false);return'hiker://empty';},s.id),extra:{lineVisible:false}});});}
var fresh=this.filterState(),tags=this.tagsFor(items,fresh);if(tags.length){this.pushSpacer(d);this.pushSection(d,'标签','高频能力标签');d.push({title:(fresh.tag==='all'?'● ':'')+'全部标签',col_type:'flex_button',url:$('#noLoading#').lazyRule(function(){putMyVar('hc_repo_tag','all');refreshPage(false);return'hiker://empty';})});tags.slice(0,12).forEach(function(t){d.push({title:(fresh.tag===t.name?'● ':'')+'#'+t.name+' '+t.count,col_type:'flex_button',url:$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_tag',v);refreshPage(false);return'hiker://empty';},t.name)});});}
this.pushSpacer(d);this.pushSection(d,'模式与排序','低频筛选');[['全部模式','all'],['远程','remote'],['本地','local']].forEach(function(x){d.push({title:(fresh.mode===x[1]?'● ':'')+x[0],col_type:'flex_button',url:$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_mode',v);refreshPage(false);return'hiker://empty';},x[1])});});[['默认排序','default'],['最近更新','updated'],['名称','name'],['版本','version']].forEach(function(x){d.push({title:(fresh.sort===x[1]?'● ':'')+x[0],col_type:'flex_button',url:$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_sort',v);refreshPage(false);return'hiker://empty';},x[1])});});
var result=this.applyFilters(items,this.filterState());this.pushSpacer(d);this.pushSection(d,'筛选结果','共 '+result.length+' 个程序');result.forEach(function(x){d.push(R.itemCard(x));});if(!result.length)this.pushEmpty(d,'没有匹配的程序','可以重置筛选条件后再试。');setResult(d);};
})(HikerRuleRepo);
