/* 我的规则仓库 v3.4.0 - grouped settings/about center */
(function(R){
R.settingsPage=function(){setPageTitle('设置');var d=[],cache=this.cacheMs();this.pushNav(d,'settings');
this.pushSection(d,'仓库','索引、缓存与 Core 管理');d.push({title:'索引缓存',desc:Math.round(cache/1000)+' 秒 · 降低重复读取云端索引的频率',url:$('0秒,30秒,60秒,180秒,600秒','选择缓存时间').select(function(){var n=Number(String(input||'60').replace(/\D/g,''));var r=$.require('hiker://page/ruleRepoCore');r.setSetting('cache_ms',n*1000);r.clearManifestCache();refreshPage(false);return'toast://已设置';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'刷新云端索引',desc:'清空 manifest 缓存，下次读取立即拉取最新索引。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearManifestCache();return'toast://云端索引缓存已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'Core 更新与回退',desc:'检查 Core、重新加载当前版本或回退上一稳定版。',url:'hiker://page/ruleRepoUpdate?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'记录','这些操作不会删除海阔里已安装的小程序');d.push({title:'导入记录',desc:'查看最近导入 / 更新过的程序。',url:'hiker://page/ruleRepoHistory?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空搜索历史',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearSearchHistory();return'toast://搜索历史已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空最近使用',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearRecent();return'toast://最近使用已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空导入历史',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearImportHistory();refreshPage(false);return'toast://导入历史已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空版本记录',desc:'清除“已记录 / 可更新”判断依据。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearInstalled();refreshPage(false);return'toast://版本记录已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空收藏',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearFavorites();refreshPage(false);return'toast://收藏已清空';}),col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'筛选','恢复默认浏览状态');d.push({title:'重置全部筛选',desc:'重置分类、子分类、标签、排序、模式、首页状态与搜索关键词。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearAllFilters();clearMyVar('hc_repo_home_view');clearMyVar('hc_repo_search_kw');refreshPage(false);return'toast://筛选状态已重置';}),col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'关于','版本与架构');d.push({title:'版本与更新日志',desc:'Core '+this.version+' · build '+this.build,url:'hiker://page/ruleRepoAbout?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'架构',desc:'Repository / Filter / UI / Home / Category / Search / Updates / Detail / History / Settings 模块隔离。',url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);};
R.aboutPage=function(){setPageTitle('关于');var d=[];d.push({title:'我的规则仓库',desc:'Core '+this.version+' · build '+this.build+'\n管理台增强版',img:this.iconOf(this.findById('rule-repo')||{}),pic_url:this.iconOf(this.findById('rule-repo')||{}),url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});var log='';try{log=this.apiText('apps/tools/rule-repo/CHANGELOG.md');}catch(e){log='更新日志读取失败：'+String(e.message||e);}d.push({title:'更新日志',desc:log,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);};
})(HikerRuleRepo);
