/* JavMenu Remote Test Bootstrap 0.1.0-test.3 - recovery patch loader */
var JAVMENU_BOOT_CONFIG={id:'javmenu-test',version:'0.1.0-test.3',build:10103,repoCdnRoot:'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/',modules:[
{name:'coreBase',path:'apps/video/javmenu/releases/0.1.0-test.2/core.js',key:10102},
{name:'parserPatch',path:'apps/video/javmenu/releases/0.1.0-test.3/parser_patch.js',key:10103},
{name:'playbackBase',path:'apps/video/javmenu/releases/0.1.0-test.2/playback_adapter.js',key:10102},
{name:'runtimeBase',path:'apps/video/javmenu/releases/0.1.0-test.2/runtime.js',key:10102},
{name:'runtimeListPatch',path:'apps/video/javmenu/releases/0.1.0-test.3/runtime_list_patch.js',key:10103}
]};
var JavMenuBoot={loadOnly:function(){var root=JAVMENU_BOOT_CONFIG.repoCdnRoot,i,m,url,loaded=[];for(i=0;i<JAVMENU_BOOT_CONFIG.modules.length;i++){m=JAVMENU_BOOT_CONFIG.modules[i];url=root+m.path+'?jm_release=10103&module='+i;require(url,{headers:{'Cache-Control':'no-cache'}},m.key);loaded.push({name:m.name,url:url});}if(typeof JavMenuCore==='undefined'||!JavMenuCore.test3ParserPatch||String(JavMenuCore.version)!=='0.1.0-test.3'||Number(JavMenuCore.build)!==10103)throw new Error('JavMenu Test3 Parser Patch 校验失败');if(typeof JavMenuPlayback==='undefined')throw new Error('JavMenu Test3 Playback Base 未加载');JavMenuPlayback.version='0.1.0-test.3';JavMenuPlayback.build=10103;if(typeof JavMenuRuntime==='undefined'||!JavMenuRuntime.test3ListPatch||String(JavMenuRuntime.version)!=='0.1.0-test.3'||Number(JavMenuRuntime.build)!==10103)throw new Error('JavMenu Test3 Runtime Patch 校验失败');return{ok:true,release:{id:'javmenu-test',version:'0.1.0-test.3',build:10103},loaded:loaded,transport:'jsdelivr',recoveryBase:'0.1.0-test.2'};},module:function(){this.loadOnly();return JavMenuRuntime;},info:function(){return{managerVersion:'direct-loader-cdn',current:{id:'javmenu-test',version:'0.1.0-test.3',build:10103},transport:'jsdelivr',recoveryBase:'0.1.0-test.2'};},check:function(){return{ok:true,current:{id:'javmenu-test',version:'0.1.0-test.3',build:10103},hasUpdate:false};},update:function(){return{ok:false,changed:false,error:'Test3 使用恢复型不可变加载；请从“我的规则仓库”覆盖新测试版'};},rollback:function(){return{ok:false,error:'Test2 已冻结为列表解析回归版本；如需回退请重新导入 Test1'};},reinstall:function(){return this.loadOnly();}};
