/* Hanime1 2.0.0-test.6 - simplified Hiker-native UI */
(function(C,P,E){
var BUILD='2.0.0-test.6';
function dec(v){v=String(v==null?'':v);for(var i=0;i<2;i++){try{var n=decodeURIComponent(v);if(n===v)break;v=n;}catch(e){break;}}return v;}
function pv(k,d){try{var x=getParam(k);if(x!==undefined&&x!==null&&String(x)!=='')return dec(x);}catch(e){}try{if(MY_PARAMS&&MY_PARAMS[k]!==undefined)return dec(MY_PARAMS[k]);}catch(y){}return d||'';}
function route(p,o){var q=[];Object.keys(o||{}).forEach(function(k){if(o[k]!==undefined&&o[k]!==null&&String(o[k])!=='')q.push(encodeURIComponent(k)+'='+encodeURIComponent(String(o[k])));});return 'hiker://page/'+p+'?rule=&simple=true'+(q.length?'&'+q.join('&'):'');}
function sec(t,d){return {title:t,desc:d||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}};}
function btn(t,u,c){return {title:t,url:u,col_type:c||'text_3',extra:{lineVisible:false}};}
function vin(x,c){return {title:x.title||'未命名',desc:[x.duration,x.views,x.rating,x.artist,x.upload].filter(Boolean).join(' · '),pic_url:x.img||x.cover||'',url:route('hanimeDetail',{id:x.id,title:x.title}),col_type:c||'movie_3',extra:{lineVisible:false}};}
function input(v,h,js){return 'input://'+JSON.stringify({value:v||'',hint:h||'',js:js});}
E.renderExplore=function(d){var mode=getMyVar('hanime2_content','video');d.push({title:(mode==='video'?'● ':'')+'视频',url:$('#noLoading#').lazyRule(function(){putMyVar('hanime2_content','video');refreshPage(false);return 'hiker://empty';}),col_type:'scroll_button'});d.push({title:(mode==='comic'?'● ':'')+'漫画',url:$('#noLoading#').lazyRule(function(){putMyVar('hanime2_content','comic');refreshPage(false);return 'hiker://empty';}),col_type:'scroll_button'});d.push({title:'预告',url:route('hanimePreviews',{}),col_type:'scroll_button'});if(mode==='comic'){var ch=P.comicHome();if(ch.hot.length){d.push(sec('热门漫画'));ch.hot.slice(0,12).forEach(function(x){d.push({title:x.title,pic_url:x.img,url:route('hanimeComicDetail',{id:x.id,title:x.title}),col_type:'movie_3'});});}if(ch.latest.length){d.push(sec('最新漫画'));ch.latest.slice(0,30).forEach(function(x){d.push({title:x.title,pic_url:x.img,url:route('hanimeComicDetail',{id:x.id,title:x.title}),col_type:'movie_3'});});}if(!ch.hot.length&&!ch.latest.length)d.push(sec('漫画站已访问，但暂未解析到列表'));return;}var h=P.home();if(h.featured&&h.featured.id)d.push({title:h.featured.title,desc:h.featured.meta||'推荐',pic_url:h.featured.img,url:route('hanimeDetail',{id:h.featured.id,title:h.featured.title}),col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false}});h.sections.forEach(function(s){d.push(sec(s.title,s.items.length+' 部'));s.items.slice(0,12).forEach(function(x){d.push(vin(x,'movie_3'));});});};
E.detail=function(){try{var id=pv('id','');if(!id)throw new Error('缺少视频 ID');var v=P.video(id),d=[],top=(v.sources&&v.sources.length)?String(v.sources[0].quality||'最高'):'待解析';setPageTitle(v.title);d.push({title:v.title,desc:[v.artist,v.views?('观看 '+v.views):'',v.upload,v.duration].filter(Boolean).join('\n'),pic_url:v.cover||'',url:$('#noLoading#').lazyRule(function(x){return $.require('hanime').play(x);},id),col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false}});d.push(btn('播放 · '+top,$('#noLoading#').lazyRule(function(x){return $.require('hanime').play(x);},id)));d.push(btn('稍后看',$('#noLoading#').lazyRule(function(x){try{$.require('hanime').provider().saveToPlaylist(x,'save',true);return 'toast://已加入稍后看';}catch(e){return 'toast://'+String(e.message||e);}},id)));d.push(btn('收藏',$('#noLoading#').lazyRule(function(x){try{$.require('hanime').provider().setFavorite(x,true);return 'toast://已收藏';}catch(e){return 'toast://'+String(e.message||e);}},id)));d.push(btn('加入片单',route('hanimePlaylistPicker',{id:id})));d.push(btn('评论',route('hanimeComments',{id:id,title:v.title})));if(v.download)d.push(btn('下载原片','download://'+v.download));if(v.sources&&v.sources.length)d.push(sec('画质','默认优先最高画质 · '+v.sources.map(function(s){return s.quality||'默认';}).join(' / ')));if(v.caption)d.push(sec('简介',v.caption));if(v.related&&v.related.length){d.push(sec('相关推荐'));v.related.slice(0,12).forEach(function(x){d.push(vin(x,'movie_3'));});}setResult(d);}catch(x){setResult([{title:'详情加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.play=function(id){try{return P.playModel(P.video(id));}catch(x){var m=String(x.message||x);if(m.indexOf('NEED_VERIFY|')===0)return route('hanimeVerify',{url:m.split('|')[1]||C.resolveHost(false)});return 'toast://播放解析失败：'+m;}};
E.previews=function(){try{setPageTitle('新番预告');var d=[],m=pv('month','');if(!m){var n=new Date(),mo=String(n.getMonth()+1);if(mo.length<2)mo='0'+mo;m=n.getFullYear()+'-'+mo;}d.push({title:'月份 · '+m,url:input(m,'YYYY-MM',"return '"+route('hanimePreviews',{})+"&month='+encodeURIComponent(input);"),col_type:'text_1'});var a=P.previews(m);for(var i=0;i<a.length;i++)d.push({title:a[i].title,desc:[a[i].brand,a[i].desc].filter(Boolean).join('\n'),pic_url:a[i].img,url:'hiker://empty',col_type:'movie_1_left_pic'});if(!a.length){d.push(sec('本月暂未解析到预告','可切换其它月份。'));d.push(btn('打开官网预告','x5://'+C.resolveHost(false)+'/previews/'+m,'text_center_1'));}setResult(d);}catch(x){setResult([{title:'预告加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.comicDetail=function(){try{var id=pv('id',''),c=P.comicDetail(id),d=[];setPageTitle(c.title);var u='pics://'+c.images.join('&&');d.push({title:c.title,desc:(c.desc||'')+'\n共 '+c.count+' 页',pic_url:c.cover,url:u,col_type:'movie_1_vertical_pic_blur'});d.push(btn('开始阅读',u,'text_center_1'));setResult(d);}catch(x){var m=String(x.message||x);if(m.indexOf('NEED_VERIFY|')===0)setResult([sec('漫画站需要验证'),btn('打开漫画站验证',route('hanimeVerify',{url:m.split('|')[1]||C.comicHost}),'text_center_1')]);else setResult([{title:'漫画详情失败',desc:m,url:'hiker://empty',col_type:'text_center_1'}]);}};
E.comicBrowse=function(){try{var path=pv('path','/comics'),page=Number(pv('page',String(MY_PAGE||1))||1),r=P.comicBrowse(path,page),d=[];setPageTitle('漫画列表');r.items.forEach(function(x){d.push({title:x.title,pic_url:x.img,url:route('hanimeComicDetail',{id:x.id,title:x.title}),col_type:'movie_3'});});if(page<r.totalPages)d.push({title:'下一页',url:route('hanimeComicBrowse',{path:path,page:page+1}),col_type:'text_center_1'});setResult(d);}catch(x){setResult([{title:'漫画列表失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.commentsPage=function(){try{var id=pv('id',''),t=pv('title','视频'),r=P.comments(id),d=[];setPageTitle('评论');d.push(sec(t,'共 '+r.items.length+' 条'));d.push({title:'发表评论',url:input('','输入评论内容',"if(!input)return 'toast://评论不能为空';try{$.require('hanime').provider().postComment('"+id+"',input);refreshPage(false);return 'toast://评论已发布';}catch(e){return 'toast://'+String(e.message||e);}"),col_type:'text_center_1'});for(var i=0;i<r.items.length;i++){var c=r.items[i],tail=[c.time,c.replyCount?c.replyCount+' 回复':''].filter(Boolean).join(' · ');d.push({title:c.user,desc:c.content+(tail?'\n'+tail:''),pic_url:c.avatar||'',url:c.id?route('hanimeReplies',{id:c.id,user:c.user}):'hiker://empty',col_type:'avatar',extra:{lineVisible:false}});}if(!r.items.length)d.push(sec('暂无评论'));setResult(d);}catch(x){setResult([{title:'评论加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.repliesPage=function(){try{var id=pv('id',''),u=pv('user','回复'),a=P.replies(id),d=[];setPageTitle('回复 · '+u);d.push({title:'回复此评论',url:input('','输入回复内容',"if(!input)return 'toast://回复不能为空';try{$.require('hanime').provider().replyComment('"+id+"',input);refreshPage(false);return 'toast://回复已发布';}catch(e){return 'toast://'+String(e.message||e);}"),col_type:'text_center_1'});for(var i=0;i<a.length;i++)d.push({title:a[i].user,desc:a[i].content+(a[i].time?'\n'+a[i].time:''),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});if(!a.length)d.push(sec('暂无回复'));setResult(d);}catch(x){setResult([{title:'回复加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.renderLibrary=function(d){var p=null;try{p=P.profile();}catch(e){}if(!p){d.push(sec('片库','只需在官网 WebView 登录一次；之后直接用同一浏览器 Cookie 请求网页。'));d.push(btn('网页登录',route('hanimeLogin',{}),'text_center_1'));return;}d.push(sec('片库 · '+p.name,p.email||('账号 ID '+p.id)));var tabs=[['稍后看','watchLater'],['收藏','favorites'],['片单','playlists'],['订阅','subscriptions'],['历史','history']],cur=getMyVar('hanime2_libtab','watchLater');for(var i=0;i<tabs.length;i++)d.push({title:(cur===tabs[i][1]?'● ':'')+tabs[i][0],url:$('#noLoading#').lazyRule(function(v){putMyVar('hanime2_libtab',v);refreshPage(false);return 'hiker://empty';},tabs[i][1]),col_type:'scroll_button'});var r=P.librarySection(cur),list=r.items||[];if(cur==='playlists'){for(var j=0;j<list.length;j++)d.push({title:list[j].title,desc:list[j].count||'',pic_url:list[j].img||'',url:route('hanimePlaylist',{id:list[j].id}),col_type:'movie_1_left_pic'});}else for(var k=0;k<list.length;k++)d.push(vin(list[k],'movie_3'));if(!list.length)d.push(sec('暂无内容','官网当前栏目为空，或登录状态已过期。'));};
E.loginPage=function(){try{C.useBrowserSession();var base=C.resolveHost(false),d=[];setPageTitle('登录 Hanime1');d.push(sec('官网登录','WebView 仅用于登录/Cloudflare。登录完成后，首页、片库、评论等均直接请求官网。'));d.push(btn('检测登录状态',$('#noLoading#').lazyRule(function(){try{var p=$.require('hanime').provider().profile();return 'toast://已登录 '+p.name;}catch(e){return 'toast://未识别账号：'+String(e.message||e);}}),'text_center_1'));d.push(btn('保存为多账号',$('#noLoading#').lazyRule(function(){try{var a=$.require('hanime').provider().syncBrowserAccount();return 'toast://已保存 '+a.name;}catch(e){return 'toast://'+String(e.message||e);}}),'text_center_1'));d.push({title:'',url:base+'/login',col_type:'x5_webview_single',desc:'list&&screen-180',extra:{ua:C.ua,canBack:true,showProgress:true}});setResult(d);}catch(x){setResult([{title:'登录页失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.renderSettings=function(d){var base=C.resolveHost(false);d.push(sec('会话架构','WebView 只负责过验证/登录；通过后所有业务直接 fetch 官网 HTML/API。'));d.push(sec('视频站',base));d.push(btn('检查视频站会话',$('#noLoading#').lazyRule(function(u){try{var r=$.require('hanime').core().ensureSession(u);return 'toast://'+(r.ok?'视频站可直连':'仍需验证');}catch(e){return 'toast://'+String(e.message||e);}},base+'/')));d.push(btn('视频站浏览器验证',route('hanimeVerify',{url:base})));d.push(sec('漫画站',C.comicHost));d.push(btn('检查漫画站会话',$('#noLoading#').lazyRule(function(u){try{var r=$.require('hanime').core().ensureSession(u);return 'toast://'+(r.ok?'漫画站可直连':'仍需验证');}catch(e){return 'toast://'+String(e.message||e);}},C.comicHost+'/comics')));d.push(btn('漫画站浏览器验证',route('hanimeVerify',{url:C.comicHost+'/comics'})));d.push(btn('账号中心',route('hanimeAccount',{})));d.push(btn('网页登录',route('hanimeLogin',{})));d.push(sec('测试版本','2.0.0-test.6 · Build 20006'));d.push(btn('检查远程更新',$('#noLoading#').lazyRule(function(){try{var r=HanimeBoot.check();return 'toast://'+(r.hasUpdate?'发现 '+r.latest.version:'当前已是最新测试版');}catch(e){return 'toast://'+String(e.message||e);}})));};
E.build=BUILD;P.build=BUILD;C.build=BUILD;
})(HanimeCore,HanimeProvider,HanimePages);
