/* Hanime1 2.0.0-test.6 - direct official HTML provider */
var HanimeWeb6=(function(C,P,S){
var BUILD=S.build;
function dh(s){return String(s==null?'':s).replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;/gi,' ').replace(/&#x([0-9a-f]+);/gi,function(_,x){try{return String.fromCharCode(parseInt(x,16));}catch(e){return _;}}).replace(/&#(\d+);/g,function(_,x){try{return String.fromCharCode(parseInt(x,10));}catch(e){return _;}});}
function strip(s){return dh(String(s||'').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim();}
function esc(s){return String(s||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function attr(tag,n){var m=String(tag||'').match(new RegExp('\\b'+esc(n)+'\\s*=\\s*(["\\\'])([\\s\\S]*?)\\1','i'));return m?dh(m[2]).trim():'';}
function tag(html,name){var m=String(html||'').match(new RegExp('<'+name+'\\b[^>]*>','i'));return m?m[0]:'';}
function block(html,cls){var re=new RegExp('<([a-z0-9]+)\\b[^>]*class\\s*=\\s*(["\\\'])[^"\\\']*'+esc(cls)+'[^"\\\']*\\2[^>]*>([\\s\\S]*?)<\\/\\1>','i'),m=String(html||'').match(re);return m?m[3]:'';}
function textClass(html,cls){return strip(block(html,cls));}
function inputVal(html,n){var m=String(html||'').match(new RegExp('<input\\b[^>]*name\\s*=\\s*(["\\\'])'+esc(n)+'\\1[^>]*>','i'));return m?attr(m[0],'value'):'';}
function meta(html,n){var ts=String(html||'').match(/<meta\b[^>]*>/gi)||[];for(var i=0;i<ts.length;i++){if(String(attr(ts[i],'name')||attr(ts[i],'property')).toLowerCase()===String(n).toLowerCase())return attr(ts[i],'content');}return '';}
function abs(base,u){return C.abs(base,dh(u));}
function ok(r,l){if(r&&r.challenge){var e=new Error('NEED_VERIFY|'+String(r.url||'')+'|'+(l||'站点'));e.code='NEED_VERIFY';throw e;}if(!r||Number(r.statusCode||0)>=400||!String(r.body||''))throw new Error((l||'请求')+'失败：HTTP '+Number((r&&r.statusCode)||0));return r;}
function unique(a,key){var o=[],s={};for(var i=0;i<a.length;i++){var x=a[i],k=String(key?key(x):(x&&x.id)||'');if(!k||s[k])continue;s[k]=1;o.push(x);}return o;}
function idFrom(u){var m=String(u||'').match(/[?&]v=(\d+)/i);return m?m[1]:'';}
function mainImage(f){var m=String(f||'').match(/<img\b[^>]*class\s*=\s*(["'])[^"']*\bmain-thumb\b[^"']*\1[^>]*>/i);if(m){var u=attr(m[0],'src');if(u)return u;}var ts=String(f||'').match(/<img\b[^>]*>/gi)||[];for(var i=0;i<ts.length;i++){var u2=attr(ts[i],'src')||attr(ts[i],'data-srcset')||attr(ts[i],'data-src');if(u2&&!/home_poster_background|placeholder|loading|spinner|data:/i.test(u2))return u2.split(',')[0].replace(/\s+\d+[wx]$/i,'').trim();}return '';}
function titleIn(f){var a=['title','video-title','home-rows-videos-title','owl-home-rows-title'];for(var i=0;i<a.length;i++){var t=textClass(f,a[i]);if(t)return t;}var im=String(f||'').match(/<img\b[^>]*>/i);return im?attr(im[0],'alt'):'';}
function stats(f){var out=[],re=/<[^>]+class\s*=\s*(["'])[^"']*stat-item[^"']*\1[^>]*>([\s\S]*?)<\/[^>]+>/gi,m;while((m=re.exec(String(f||'')))!==null){var t=strip(m[2]);if(t)out.push(t);if(m.index===re.lastIndex)re.lastIndex++;}return out;}
function card(f,base){var m=String(f||'').match(/href\s*=\s*(["'])([^"']*watch\?[^"']*\bv=\d+[^"']*)\1/i),href=m?dh(m[2]):'',id=idFrom(href);if(!id)return null;var st=stats(f),im=mainImage(f);return {id:id,title:titleIn(f)||('影片 '+id),url:abs(base,href),img:abs(base,im),duration:textClass(f,'duration')||textClass(f,'card-mobile-duration'),rating:st[0]||'',views:st[1]||'',artist:textClass(f,'subtitle')||textClass(f,'meta-author'),upload:textClass(f,'meta-stats')||textClass(f,'card-mobile-meta')};}
function cards(html,base){html=String(html||'');var out=[],starts=[],re=/<div\b[^>]*class\s*=\s*(["'])[^"']*(?:horizontal-card|video-item-container|user-tab-item-wrapper)[^"']*\1[^>]*>/gi,m;while((m=re.exec(html))!==null){starts.push(m.index);if(m.index===re.lastIndex)re.lastIndex++;}for(var i=0;i<starts.length;i++){var c=card(html.slice(starts[i],i+1<starts.length?starts[i+1]:Math.min(html.length,starts[i]+18000)),base);if(c)out.push(c);}if(!out.length){var ar=[],rr=/href\s*=\s*(["'])[^"']*watch\?[^"']*\bv=\d+[^"']*\1/gi,mm;while((mm=rr.exec(html))!==null){ar.push(mm.index);if(mm.index===rr.lastIndex)rr.lastIndex++;}for(var j=0;j<ar.length;j++){var cc=card(html.slice(Math.max(0,ar[j]-3500),j+1<ar.length?ar[j+1]:Math.min(html.length,ar[j]+14000)),base);if(cc)out.push(cc);}}return unique(out);}
function rows(html){var out=[],re=/<a\b[^>]*class\s*=\s*(["'])[^"']*horizontal-row-title[^"']*\1[^>]*>([\s\S]*?)<\/a>/gi,m;while((m=re.exec(String(html||'')))!==null){var h=m[2].match(/<h3\b[^>]*>([\s\S]*?)<\/h3>/i),t=strip(h?h[1]:m[2]).replace(/更多[\s\S]*$/,'').replace(/arrow_forward_ios[\s\S]*$/i,'').trim();out.push({start:m.index,end:re.lastIndex,title:t||'推荐',href:attr(m[0],'href')});if(m.index===re.lastIndex)re.lastIndex++;}return out;}
function featured(html,base){var p=String(html||'').indexOf('home-banner-wrapper');if(p<0)return null;var f=String(html).slice(Math.max(0,p-1000),p+30000),h=f.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i),t=h?strip(h[1]):'';if(!t)return null;var imgs=f.match(/<img\b[^>]*>/gi)||[],im='';for(var i=0;i<imgs.length;i++){var u=attr(imgs[i],'src');if(u&&!/home_poster_background|placeholder|loading/i.test(u)){im=u;break;}}var href=(f.match(/href\s*=\s*(["'])([^"']*watch\?[^"']*\bv=\d+[^"']*)\1/i)||[])[2]||'',id=idFrom(href)||((im.match(/thumbnail\/(\d+)/)||[])[1]||'');var h4=f.match(/<h4\b[^>]*>([\s\S]*?)<\/h4>/i);return {id:id,title:t,img:abs(base,im),meta:h4?strip(h4[1]):''};}
P.home=function(){var r=ok(C.video('/'),'首页'),base=r.base||C.resolveHost(false),h=String(r.body||''),ms=rows(h),secs=[];for(var i=0;i<ms.length;i++){var e=i+1<ms.length?ms[i+1].start:h.length,list=cards(h.slice(ms[i].end,e),base);if(list.length)secs.push({title:ms[i].title,more:abs(base,ms[i].href),items:list});}if(!secs.length){var all=cards(h,base);if(all.length)secs.push({title:'全部视频',more:'',items:all});}return {base:base,featured:featured(h,base),sections:secs};};
function sources(h,base){var o=[],ts=String(h||'').match(/<source\b[^>]*>/gi)||[];for(var i=0;i<ts.length;i++){var u=attr(ts[i],'src')||attr(ts[i],'data-src'),q=attr(ts[i],'size')||attr(ts[i],'label')||attr(ts[i],'res')||'0';if(u)o.push({quality:q,url:abs(base,u),type:attr(ts[i],'type')});}if(!o.length){var v=String(h||'').match(/<video\b[^>]*id\s*=\s*(["'])player\1[^>]*>/i)||String(h||'').match(/<video\b[^>]*>/i);if(v){var u2=attr(v[0],'src');if(u2)o.push({quality:'0',url:abs(base,u2),type:attr(v[0],'type')});}}return unique(o,function(x){return x.url;}).sort(function(a,b){var aa=parseInt(String(a.quality).match(/\d+/)||[0],10),bb=parseInt(String(b.quality).match(/\d+/)||[0],10);return bb-aa;});}
P.video=function(id){var base=C.resolveHost(false),r=ok(C.video('/watch?v='+encodeURIComponent(id)),'视频详情'),h=String(r.body||''),src=sources(h,base),title=meta(h,'og:title')||strip((h.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||'');title=title.replace(/\s*-\s*Hanime1[\s\S]*$/i,'').trim();var vt=h.match(/<video\b[^>]*id\s*=\s*(["'])player\1[^>]*>/i),cover=vt?attr(vt[0],'poster'):'';if(!cover)cover=meta(h,'og:image');var an=h.match(/<[^>]+id\s*=\s*(["'])video-artist-name\1[^>]*>([\s\S]*?)<\/[^>]+>/i),artist=an?strip(an[2]):'';var desc=textClass(h,'video-caption-text'),views=(strip(h).match(/(?:觀看次數|观看次数)\s*[:：]?\s*([^\s]+)/)||[])[1]||'',date=(strip(h).match(/\d{4}-\d{2}-\d{2}/)||[])[0]||'';var artistId=inputVal(h,'subscribe-artist-id'),subUser=inputVal(h,'subscribe-user-id'),uid=inputVal(h,'like-user-id'),tags=[],tr=/<a\b([^>]*href\s*=\s*(["'])([^"']*(?:tags%5B%5D|tags\[\]|tag=)[^"']*)\2[^>]*)>([\s\S]*?)<\/a>/gi,tm;while((tm=tr.exec(h))!==null){var nt=strip(tm[4]).replace(/\s*\(\d+\)\s*$/,'').trim();if(nt)tags.push({name:nt,href:abs(base,dh(tm[3]))});if(tm.index===tr.lastIndex)tr.lastIndex++;}var rel='';var ri=h.indexOf('related-tabcontent');if(ri>=0)rel=h.slice(ri,Math.min(h.length,ri+180000));return {id:String(id),base:base,title:title||('影片 '+id),cover:abs(base,cover),duration:meta(h,'og:video:duration'),views:views,artist:artist,artistId:artistId,genre:'',upload:date,caption:desc,download:abs(base,((h.match(/<a\b[^>]*id\s*=\s*(["'])downloadBtn\1[^>]*>/i)||[])[0]?attr((h.match(/<a\b[^>]*id\s*=\s*(["'])downloadBtn\1[^>]*>/i)||[])[0],'href'):'')),csrf:meta(h,'csrf-token')||inputVal(h,'_token'),currentUserId:uid,subscriptionUserId:subUser,tags:unique(tags,function(x){return x.name;}),sources:src,related:cards(rel,base),raw:h};};
P.playModel=function(v){var a=(v.sources||[]).slice().sort(function(x,y){return (parseInt(String(y.quality).match(/\d+/)||[0],10)||0)-(parseInt(String(x.quality).match(/\d+/)||[0],10)||0);}),urls=[],names=[],headers=[];for(var i=0;i<a.length;i++){if(!a[i].url)continue;urls.push(a[i].url);names.push((a[i].quality||'默认')+(a[i].type?' · '+String(a[i].type).replace('video/',''):''));headers.push({'User-Agent':C.ua,'Referer':v.base+'/watch?v='+v.id});}if(!urls.length)throw new Error('未解析到可播放地址');return JSON.stringify({urls:urls,names:names,headers:headers});};
P.search=function(o){o=o||{};var base=C.resolveHost(false),url=C.query(base+'/search',{page:o.page||1,query:o.query||'',genre:o.genre||'',sort:o.sort||'',date:o.date||'',duration:o.duration||'',type:o.type||''}),r=ok(C.get(url,{base:base,referer:base+'/'}),'搜索'),list=cards(r.body,base),total=Number(o.page||1),pm=String(r.body).match(/page=(\d+)/g)||[];for(var i=0;i<pm.length;i++){var n=parseInt((pm[i].match(/\d+/)||[0])[0],10);if(n>total)total=n;}return {url:url,items:list,artists:[],page:Number(o.page||1),totalPages:total};};
P.previews=function(month){var base=C.resolveHost(false),r=ok(C.get(base+'/previews/'+encodeURIComponent(month),{base:base,referer:base+'/'}),'预告'),h=String(r.body||''),starts=[],re=/<div\b[^>]*\bid\s*=\s*(["'])[^"']+\1[^>]*>/gi,m;while((m=re.exec(h))!==null){starts.push(m.index);if(m.index===re.lastIndex)re.lastIndex++;}var out=[];for(var i=0;i<starts.length;i++){var f=h.slice(starts[i],i+1<starts.length?starts[i+1]:Math.min(h.length,starts[i]+30000));if(f.indexOf('preview-info-cover')<0)continue;var op=tag(f,'div'),id=attr(op,'id'),imBlock=block(f,'preview-info-cover'),im=mainImage(imBlock||f),hm=f.match(/<h4\b[^>]*>([\s\S]*?)<\/h4>/i)||f.match(/<h3\b[^>]*>([\s\S]*?)<\/h3>/i),t=hm?strip(hm[1]):'',brand='';var bi=f.match(/preview-info-content-padding[\s\S]{0,5000}?<a\b[^>]*>([\s\S]*?)<\/a>/i);if(bi)brand=strip(bi[1]);var cap=textClass(f,'caption');if(t&&im)out.push({id:id||String(i),title:t,img:abs(base,im),brand:brand,desc:cap});}return unique(out,function(x){return x.id+'|'+x.title;});};
return {build:BUILD,dh:dh,strip:strip,esc:esc,attr:attr,tag:tag,block:block,textClass:textClass,inputVal:inputVal,meta:meta,abs:abs,ok:ok,unique:unique,idFrom:idFrom,mainImage:mainImage,titleIn:titleIn,stats:stats,card:card,cards:cards};
})(HanimeCore,HanimeProvider,HanimeSession6);
