/* Hanime1 2.0.0-test.6 - comics/account/comments direct web */
(function(C,P,S,W){
var BUILD=S.build,dh=W.dh,strip=W.strip,attr=W.attr,textClass=W.textClass,inputVal=W.inputVal,meta=W.meta,abs=W.abs,ok=W.ok,unique=W.unique,mainImage=W.mainImage,cards=W.cards;
function comicImg(f){var ts=String(f||'').match(/<img\b[^>]*>/gi)||[];for(var i=0;i<ts.length;i++){var u=attr(ts[i],'data-srcset')||attr(ts[i],'data-src')||attr(ts[i],'src');if(u)return u.split(',')[0].replace(/\s+\d+[wx]$/i,'').trim();}return '';}
function comicCards(h){var out=[],re=/<a\b[^>]*href\s*=\s*(["'])([^"']*\/comic\/(\d+)[^"']*)\1[^>]*>([\s\S]*?)<\/a>/gi,m;while((m=re.exec(String(h||'')))!==null){var f=m[4],t=textClass(f,'comic-rows-videos-title')||strip(f),im=comicImg(f);if(t)out.push({id:m[3],title:t,img:abs(C.comicHost,im)});if(m.index===re.lastIndex)re.lastIndex++;}return unique(out);}
P.comicHome=function(){var r=ok(C.comic('/comics'),'漫画首页'),h=String(r.body||''),all=comicCards(h),out={hot:[],latest:all};var sec=[],rr=/<[^>]+class\s*=\s*(["'])[^"']*comic-rows-wrapper[^"']*\1[^>]*>/gi,mm;while((mm=rr.exec(h))!==null){sec.push(mm.index);if(mm.index===rr.lastIndex)rr.lastIndex++;}for(var i=0;i<sec.length;i++){var f=h.slice(sec[i],i+1<sec.length?sec[i+1]:h.length),tt=(f.match(/<h3\b[^>]*>([\s\S]*?)<\/h3>/i)||[])[1]||'',list=comicCards(f);if(/發燒|发烧|熱門|热门/.test(strip(tt)))out.hot=out.hot.concat(list);else if(/最新/.test(strip(tt)))out.latest=list;}out.hot=unique(out.hot);out.latest=unique(out.latest);return out;};
P.comicBrowse=function(path,page){var u=/^https?:/i.test(String(path||''))?String(path):C.comicHost+(String(path||'/comics').charAt(0)==='/'?'':'/')+String(path||'/comics'),r=ok(C.get(C.query(u,{page:page||1}),{base:C.comicHost,referer:C.comicHost+'/'}),'漫画列表'),items=comicCards(r.body),total=Number(page||1),ms=String(r.body).match(/page=(\d+)/g)||[];for(var i=0;i<ms.length;i++){var n=parseInt((ms[i].match(/\d+/)||[0])[0],10);if(n>total)total=n;}return {items:items,page:Number(page||1),totalPages:total};};
P.comicDetail=function(id){var a=ok(C.comic('/comic/'+id),'漫画详情'),b=ok(C.comic('/comic/'+id+'/1'),'漫画阅读'),h=String(a.body||''),hh=String(b.body||''),im=(hh.match(/<img\b[^>]*id\s*=\s*(["'])current-page-image\1[^>]*>/i)||[])[0]||'',nav=(hh.match(/<[^>]+class\s*=\s*(["'])[^"']*comic-show-content-nav[^"']*\1[^>]*>/i)||[])[0]||'',count=parseInt(attr(nav,'data-pages')||'1',10)||1,prefix=attr(im,'data-prefix'),fallback=attr(im,'data-extension')||'jpg',ext=[],em=hh.match(/extensions\.innerHTML\s*=\s*'([^']+)'/);if(em){try{ext=JSON.parse(em[1].replace(/&quot;/g,'"'));}catch(e){}}var imgs=[];for(var i=0;i<count;i++){var ex=String(ext[i]||fallback);if(ex==='w')ex='webp';if(ex==='j')ex='jpg';imgs.push(abs(C.comicHost,prefix+(i+1)+'.'+ex));}var tm=h.match(/<h3\b[^>]*class\s*=\s*(["'])[^"']*title[^"']*\1[^>]*>([\s\S]*?)<\/h3>/i),cover='',ci=h.match(/<div\b[^>]*class\s*=\s*(["'])[^"']*col-md-4[^"']*\1[^>]*>([\s\S]{0,12000})/i);if(ci)cover=comicImg(ci[2]);if(!cover)cover=attr(im,'src');return {id:String(id),title:tm?strip(tm[2]):(meta(hh,'og:title')||'漫画'),cover:abs(C.comicHost,cover),tags:[],images:imgs,count:count,desc:meta(h,'description')};};
P.profile=function(){var base=C.resolveHost(false),home=ok(C.get(base+'/',{base:base,referer:base+'/',timeout:12000}),'账号校验').body,ut=String(home).match(/<[^>]+id\s*=\s*(["'])user-modal-trigger\1[^>]*>/i),href=ut?attr(ut[0],'href'):'',id=(href.match(/\/user\/(\d+)/)||[])[1]||'';if(!id)throw new Error('未检测到官网登录会话');var edit=ok(C.get(base+'/user/'+id+'/edit',{base:base,referer:base+'/'}),'账号资料').body;return {id:id,name:inputVal(edit,'name')||('用户 '+id),email:inputVal(edit,'email'),avatar:'',csrf:meta(edit,'csrf-token')||inputVal(edit,'_token'),joined:'',cookie:C.accountCookie(base),base:base};};
P.syncBrowserAccount=function(){C.useBrowserSession();var p=P.profile(),raw=C.browserCookie(p.base);return C.saveAccount(p,raw);};
function fpost(path,data,label){var p=P.profile(),base=p.base;if(p.csrf)data._token=p.csrf;var r=ok(C.post(base+path,data,{base:base,referer:base+'/',headers:p.csrf?{'X-CSRF-TOKEN':p.csrf}:{}}),label);if(/\/login["'?<\s]/i.test(r.body))throw new Error('登录状态已失效');return r;}
P.updateProfile=function(name,email){var p=P.profile();fpost('/user/'+p.id,{_method:'patch',type:'profile',name:name,email:email},'修改资料');return P.profile();};
P.updatePassword=function(o,n,c){var p=P.profile();fpost('/user/'+p.id,{_method:'patch',type:'password',password_old:o,password_new:n,password_new_confirm:c},'修改密码');return true;};
function playlistCards(h,base){var out=[],re=/<a\b[^>]*href\s*=\s*(["'])([^"']*playlist\?list=([^&"']+)[^"']*)\1[^>]*>([\s\S]*?)<\/a>/gi,m;while((m=re.exec(String(h||'')))!==null){var f=m[4],t=textClass(f,'playlist-title')||textClass(f,'title')||strip(f),im=mainImage(f);if(t)out.push({id:dh(m[3]),title:t,count:'',img:abs(base,im)});if(m.index===re.lastIndex)re.lastIndex++;}return unique(out,function(x){return x.id;});}
P.librarySection=function(key){var p=P.profile(),base=p.base,map={watchLater:'/user/'+p.id+'/saves',favorites:'/user/'+p.id+'/likes',playlists:'/user/'+p.id+'/playlists',history:'/user/'+p.id+'/histories?sort=latest&page=1',subscriptions:'/subscriptions?page=1'},path=map[key]||map.watchLater,body=ok(C.get(base+path,{base:base,referer:base+'/',timeout:15000}),'片库').body;return {profile:p,key:key,items:key==='playlists'?playlistCards(body,base):cards(body,base)};};
P.library=function(){var keys=['watchLater','favorites','playlists','history','subscriptions'],o={profile:P.profile(),watchLater:[],favorites:[],playlists:[],history:[],subscriptions:[]};for(var i=0;i<keys.length;i++)o[keys[i]]=P.librarySection(keys[i]).items;return o;};
P.saveToPlaylist=function(v,l,en){fpost('/save',{input_id:l,video_id:v,is_checked:String(en!==false),user_id:''},'保存到片单');return true;};
P.createPlaylist=function(v,t,d){fpost('/createPlaylist',{'create-playlist-video-id':v,'playlist-title':t,'playlist-description':d||''},'创建片单');return true;};
P.setFavorite=function(v,en){var p=P.profile();fpost('/like',{'like-foreign-id':v,'like-status':en?'':'1','like-user-id':p.id,'like-is-positive':'1'},'收藏');return true;};
P.setSubscription=function(v,en){var p=P.profile();if(!v.artistId)throw new Error('当前视频没有作者订阅 ID');fpost('/subscribe',{'subscribe-user-id':v.subscriptionUserId||p.id,'subscribe-artist-id':v.artistId,'subscribe-status':en?'':'1'},'订阅');return true;};
P.deleteHistory=function(v){var p=P.profile(),r=ok(C.request(p.base+'/user/tab-item/'+v,{base:p.base,referer:p.base+'/',method:'DELETE',body:C.form({tab:'histories'}),headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8','X-CSRF-TOKEN':p.csrf}}),'删除历史');return !!r;};
P.playlist=function(id,sort){var p=P.profile(),u=p.base+'/playlist?list='+encodeURIComponent(id)+'&sort='+encodeURIComponent(sort||'latest')+'&page=1',body=ok(C.get(u,{base:p.base,referer:p.base+'/'}),'片单').body;return {id:id,title:textClass(body,'playlist-title')||'片单',desc:textClass(body,'playlist-description'),items:cards(body,p.base),csrf:meta(body,'csrf-token')||inputVal(body,'_token')};};
P.updatePlaylist=function(id,t,d,del){var x={_method:'PUT','playlist-title':t||'','playlist-description':d||''};if(del)x['playlist-delete']='on';fpost('/playlist/'+id,x,del?'删除片单':'修改片单');return true;};
function commentHtml(id){var base=C.resolveHost(false),r=ok(C.get(C.query(base+'/loadComment',{type:'video',id:id}),{base:base,referer:base+'/watch?v='+id}),'评论'),b=String(r.body||'');try{var j=JSON.parse(b);if(j&&typeof j.comments==='string')b=j.comments;}catch(e){}return {base:base,body:b};}
function commentFields(h){var o=[],re=/<([a-z0-9]+)\b[^>]*class\s*=\s*(["'])[^"']*comment-index-text[^"']*\2[^>]*>([\s\S]*?)<\/\1>/gi,m;while((m=re.exec(String(h||'')))!==null){o.push({index:m.index,inner:m[3]});if(m.index===re.lastIndex)re.lastIndex++;}return o;}
P.comments=function(id){var z=commentHtml(id),f=commentFields(z.body),ids=[],rm=/reply-section-wrapper-(\d+)/gi,m;while((m=rm.exec(z.body))!==null){ids.push(m[1]);if(m.index===rm.lastIndex)rm.lastIndex++;}var out=[];for(var i=0;i+1<f.length;i+=2){var am=f[i].inner.match(/<a\b[^>]*>([\s\S]*?)<\/a>/i),sm=f[i].inner.match(/<span\b[^>]*>([\s\S]*?)<\/span>/i),u=am?strip(am[1]):strip(f[i].inner),c=strip(f[i+1].inner);if(!u||!c)continue;var end=i+2<f.length?f[i+2].index:Math.min(z.body.length,f[i+1].index+6000),frag=z.body.slice(Math.max(0,f[i].index-1800),end),rc=(textClass(frag,'load-replies-btn').match(/\d+/)||[])[0]||'';out.push({id:ids[Math.floor(i/2)]||inputVal(frag,'foreign_id')||'',user:u,content:c,time:sm?strip(sm[1]):'',avatar:abs(z.base,mainImage(frag)),replyCount:rc});}return {items:out,csrf:inputVal(z.body,'_token'),userId:inputVal(z.body,'comment-user-id')};};
P.replies=function(cid){var base=C.resolveHost(false),r=ok(C.get(C.query(base+'/loadReplies',{id:cid}),{base:base,referer:base+'/'}),'回复'),b=String(r.body||'');try{var j=JSON.parse(b);if(j&&typeof j.replies==='string')b=j.replies;}catch(e){}var f=commentFields(b),o=[];for(var i=0;i+1<f.length;i+=2){var am=f[i].inner.match(/<a\b[^>]*>([\s\S]*?)<\/a>/i),sm=f[i].inner.match(/<span\b[^>]*>([\s\S]*?)<\/span>/i),u=am?strip(am[1]):strip(f[i].inner),c=strip(f[i+1].inner);if(u&&c)o.push({user:u,content:c,time:sm?strip(sm[1]):''});}return o;};
P.postComment=function(id,t){var p=P.profile();fpost('/createComment',{'comment-user-id':p.id,'comment-type':'video','comment-foreign-id':id,'comment-text':t,'comment-count':'1','comment-is-political':'0'},'发表评论');return true;};
P.replyComment=function(id,t){fpost('/replyComment',{'reply-comment-id':id,'reply-comment-text':t},'回复评论');return true;};
P.filters={genres:[['全部',''],['裏番','裏番'],['泡面番','泡麵番'],['Motion Anime','Motion Anime'],['3DCG','3DCG'],['2.5D','2.5D'],['2D动画','2D動畫'],['AI生成','AI生成'],['MMD','MMD'],['Cosplay','Cosplay']],sorts:[['默认',''],['最新上市','release_date'],['最新上传','upload_date'],['本日排行','today'],['本周排行','week'],['本月排行','month'],['总排行','views']],dates:[['不限',''],['24小时','1d'],['2天','2d'],['1周','1w'],['1月','1m'],['3月','3m']],durations:[['不限',''],['1分钟+','1'],['5分钟+','5'],['10分钟+','10'],['20分钟+','20']],types:[['视频',''],['作者','artist']]};
P.build=BUILD;
})(HanimeCore,HanimeProvider,HanimeSession6,HanimeWeb6);
