/* PikPak Test10 Android Auth Patch - current Android 1.53.2 contract */
(function(C){
    var A={
        name:'android',client_id:'YNxT9w7GMdWvEOKa',client_secret:'dbw2OtmV'+'EeuUvIptb1Coyg',client_version:'1.53.2',package_name:'com.pikcloud.pikpak',sdk_version:'2.0.6.206003',redirect_uri:'xlaccsdk01://xbase.cloud/callback?state=harbor',
        salts:['SOP04dGzk0TNO7t7t9ekDbAmx+eq0OI1ovEx','nVBjhYiND4hZ2NCGyV5beamIr7k6ifAsAbl','Ddjpt5B/Cit6EDq2a6cXgxY9lkEIOw4yC1GDF28KrA','VVCogcmSNIVvgV6U+AochorydiSymi68YVNGiz','u5ujk5sM62gpJOsB/1Gu/zsfgfZO','dXYIiBOAHZgzSruaQ2Nhrqc2im','z5jUTBSIpBN9g4qSJGlidNAutX6','KJE2oveZ34du/g1tiimm']
    };
    function hex32(n){var s=(n>>>0).toString(16);return '00000000'.slice(s.length)+s;}
    function sha1(msg){msg=unescape(encodeURIComponent(String(msg||'')));var ml=msg.length*8,words=[],i,j,t,w=new Array(80),a,b,c,d,e,f,k,tmp;for(i=0;i<msg.length;i++)words[i>>2]|=msg.charCodeAt(i)<<(24-(i%4)*8);words[ml>>5]|=0x80<<(24-ml%32);words[((ml+64>>9)<<4)+15]=ml;var h0=0x67452301,h1=0xEFCDAB89,h2=0x98BADCFE,h3=0x10325476,h4=0xC3D2E1F0;for(i=0;i<words.length;i+=16){for(j=0;j<16;j++)w[j]=words[i+j]||0;for(j=16;j<80;j++){t=w[j-3]^w[j-8]^w[j-14]^w[j-16];w[j]=(t<<1)|(t>>>31);}a=h0;b=h1;c=h2;d=h3;e=h4;for(j=0;j<80;j++){if(j<20){f=(b&c)|((~b)&d);k=0x5A827999;}else if(j<40){f=b^c^d;k=0x6ED9EBA1;}else if(j<60){f=(b&c)|(b&d)|(c&d);k=0x8F1BBCDC;}else{f=b^c^d;k=0xCA62C1D6;}tmp=((((a<<5)|(a>>>27))>>>0)+(f>>>0)+(e>>>0)+(k>>>0)+(w[j]>>>0))>>>0;e=d;d=c;c=((b<<30)|(b>>>2))>>>0;b=a;a=tmp;}h0=(h0+a)>>>0;h1=(h1+b)>>>0;h2=(h2+c)>>>0;h3=(h3+d)>>>0;h4=(h4+e)>>>0;}return hex32(h0)+hex32(h1)+hex32(h2)+hex32(h3)+hex32(h4);}
    function domain(){return C.item('api_domain','mypikpak.net')||'mypikpak.net';}
    function altDomain(d){return String(d||domain())==='mypikpak.net'?'mypikpak.com':'mypikpak.net';}
    function userBase(d){return 'https://user.'+(d||domain());}
    function driveBase(d){return 'https://api-drive.'+(d||domain());}
    function referralBase(d){return 'https://api-referral.'+(d||domain());}
    function normalize(v){return C.normalizePhoneAccount(String(v||'').trim());}
    function deviceId(user,pass){user=normalize(user);pass=String(pass||'');if(user&&pass){var d=md5(user+pass);C.set('device_id_android',d);return d;}var s=C.session(),old=String((s&&s._device_id)||C.item('device_id_android','')||'');if(old)return old;var seed=C.username()||String(new Date().getTime())+'|'+Math.random();var next=md5(seed);C.set('device_id_android',next);return next;}
    function deviceSign(did){return 'div101.'+did+md5(sha1(String(did)+A.package_name+'1appkey'));}
    function userAgent(uid,did){did=did||deviceId();uid=String(uid||'');return 'ANDROID-'+A.package_name+'/'+A.client_version+' '+'protocolVersion/200 accesstype/ clientid/'+A.client_id+' clientversion/'+A.client_version+' '+'action_type/ networktype/WIFI sessionid/ deviceid/'+did+' providername/NONE '+'devicesign/'+deviceSign(did)+' refresh_token/ sdkversion/'+A.sdk_version+' '+'datetime/'+String(new Date().getTime())+' usrno/'+uid+' appname/android-'+A.package_name+' '+'session_origin/ grant_type/ appid/ clientip/ devicename/Xiaomi_M2004j7ac '+'osversion/13 platformversion/10 accessmode/ devicemodel/M2004J7AC ';}
    function headers(did,token,uid,content){var h={'X-Device-ID':did,'User-Agent':userAgent(uid,did)};if(content!==false)h['Content-Type']='application/json; charset=utf-8';if(token)h['X-Captcha-Token']=String(token);return h;}
    function requestUserRaw(path,method,body,h,timeout){var first=domain(),r=C.raw(userBase(first)+path,method,body,h,timeout||10000);if(r&&r._network_error)r=C.raw(userBase(altDomain(first))+path,method,body,h,timeout||10000);return r;}
    function sign(ts,did){var s=A.client_id+A.client_version+A.package_name+String(did||'')+String(ts||'');for(var i=0;i<A.salts.length;i++)s=md5(s+A.salts[i]);return '1.'+s;}
    function identityMeta(user){var m={},u=normalize(user);if(/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(u))m.email=u;else if(u.length>=11&&u.length<=18&&/^\+?\d+$/.test(u))m.phone_number=u;else m.username=u;return m;}
    function verifyResult(res,did){if(!res)return null;if(res.captcha_token)C.set('captcha_token',String(res.captcha_token));if(res.url||res.verify_url)return {needsVerification:true,review:true,captcha_token:String(res.captcha_token||C.item('captcha_token','')||''),verify_url:String(res.url||res.verify_url||''),device_id:did,raw:res};return null;}
    function captchaLogin(user,oldToken,did){user=normalize(user);did=did||deviceId(user,'');var body={action:'POST:/v1/auth/signin',captcha_token:String(oldToken||''),client_id:A.client_id,device_id:did,meta:identityMeta(user),redirect_uri:A.redirect_uri};var r=requestUserRaw('/v1/shield/captcha/init?client_id='+A.client_id,'POST',body,headers(did,'','',true),10000),v=verifyResult(r,did);if(v)return v;if(!r||r.error||r.error_code||!r.captcha_token)return {error:'CAPTCHA_INIT_FAILED',error_description:'PikPak Android 登录验证初始化失败：'+C.errorText(r),raw:r};return {captcha_token:String(r.captcha_token),device_id:did,raw:r};}
    function captchaForAction(action,uid,oldToken,did){did=did||deviceId();uid=String(uid||'');var ts=String(new Date().getTime()),meta={client_version:A.client_version,package_name:A.package_name,user_id:uid,timestamp:ts,captcha_sign:sign(ts,did)},body={action:String(action||'GET:/drive/v1/files'),captcha_token:String(oldToken||C.item('captcha_token','')||''),client_id:A.client_id,device_id:did,meta:meta,redirect_uri:A.redirect_uri},h=headers(did,'',uid,true),s=C.session();if(s&&s.access_token)h.Authorization='Bearer '+s.access_token;var r=requestUserRaw('/v1/shield/captcha/init?client_id='+A.client_id,'POST',body,h,10000),v=verifyResult(r,did);if(v)return v;if(r&&r.captcha_token)C.set('captcha_token',String(r.captcha_token));return r;}
    function saveAndroidSession(res,did,user){if(!res)return res;res._auth_profile='android';res._device_id=did;C.setUsername(user||C.username());C.set('auth_profile','android');C.set('device_id_android',did);C.saveSession(res,A,did);return res;}
    function signIn(user,pass,token,did){user=normalize(user);pass=String(pass||'');token=String(token||'');did=did||deviceId(user,pass);if(!token)return {error:'CAPTCHA_TOKEN_EMPTY',error_description:'Android 验证令牌为空，请重新登录'};var body={captcha_token:token,client_id:A.client_id,client_secret:A.client_secret,password:pass,username:user};var r=requestUserRaw('/v1/auth/signin?client_id='+A.client_id,'POST',body,headers(did,token,'',true),12000);if(r&&!r.error&&!r.error_code&&r.access_token){saveAndroidSession(r,did,user);C.set('captcha_token',token);C.clear('last_login_issue');var after=captchaForAction('GET:/drive/v1/files',String(r.sub||''),token,did);if(after&&after.captcha_token)C.set('captcha_token',String(after.captcha_token));return r;}var v=verifyResult(r,did);if(v)return v;return r;}
    function begin(user,pass){user=normalize(user);pass=String(pass||'');if(!user||!pass)return {error:'EMPTY_ACCOUNT',error_description:'请输入账号和密码'};C.clear('last_login_issue');var did=deviceId(user,pass),cap=captchaLogin(user,'',did);if(!cap||cap.error||cap.needsVerification)return cap;return signIn(user,pass,cap.captcha_token,did);}
    function finish(user,pass,token){return signIn(user,pass,token,deviceId(user,pass));}
    function reload(user,pass,oldToken){return captchaLogin(user,oldToken||'',deviceId(user,pass));}
    function refreshAccess(){var s=C.session(),rt=String((s&&s.refresh_token)||C.item('refresh_token','')||'');if(!rt)return {error:'NO_REFRESH_TOKEN',error_description:'登录已失效，请重新登录'};var did=String((s&&s._device_id)||C.item('device_id_android','')||deviceId()),body={client_id:A.client_id,client_secret:A.client_secret,grant_type:'refresh_token',refresh_token:rt};var r=requestUserRaw('/v1/auth/token?client_id='+A.client_id,'POST',body,{'User-Agent':'','X-Device-ID':did,'Content-Type':'application/json; charset=utf-8'},10000);if(r&&!r.error&&!r.error_code&&r.access_token){if(!r.refresh_token)r.refresh_token=rt;saveAndroidSession(r,did,C.username());return r;}return r;}
    function authHeaders(){var s=C.session(),did=String((s&&s._device_id)||C.item('device_id_android','')||deviceId()),uid=String((s&&s.sub)||C.item('user_id','')||''),h=headers(did,C.item('captcha_token',''),uid,false);if(s&&s.access_token)h.Authorization='Bearer '+s.access_token;return h;}
    function publicHeaders(){var did=deviceId(),h=headers(did,C.item('captcha_token',''),'',false);return h;}
    function isFreq(o){var t=C.errorText(o);return String((o&&o.error_code)||'')==='10'||/operation is too frequent|too frequent|操作频繁/i.test(t);}
    function actionOf(method,url){var m=String(url||'').match(/^[a-z]+:\/\/[^/]+([^?#]*)/i);return String(method||'GET').toUpperCase()+':'+(m&&m[1]?m[1]:'/');}
    function request(method,url,body,opt){opt=opt||{};method=String(method||'GET').toUpperCase();var auth=opt.auth!==false,s,r,headers0;if(auth){s=C.session();if(!s.access_token){r=refreshAccess();if(!r||r.error||r.error_code||!r.access_token)return r;}}headers0=auth?authHeaders():publicHeaders();if(opt.headers){for(var k in opt.headers)headers0[k]=opt.headers[k];}r=C.raw(url,method,body,headers0,opt.timeout||8000);if(auth&&C.isAuthError(r)&&!opt._authRetried){var rr=refreshAccess();if(rr&&!rr.error&&!rr.error_code&&rr.access_token){opt._authRetried=true;return request(method,url,body,opt);}return rr;}if(C.isCaptchaError(r)&&!opt._captchaRetried&&!isFreq(r)){s=C.session();var cap=captchaForAction(actionOf(method,url),auth?String((s&&s.sub)||C.item('user_id','')||''):'',C.item('captcha_token',''),String((s&&s._device_id)||deviceId()));if(cap&&cap.captcha_token){opt._captchaRetried=true;return request(method,url,body,opt);}return cap||r;}if(r&&r._network_error&&!opt._domainRetried&&/mypikpak\.(com|net)/i.test(url)){opt._domainRetried=true;var alt=String(url).replace('.'+domain(),'.'+altDomain(domain()));if(alt!==url)return request(method,alt,body,opt);}return r;}
    C.clientId=A.client_id;C.clientVersion=A.client_version;C.packageName=A.package_name;C.userAgent=userAgent('',deviceId());C.domain=domain;C.userBase=userBase;C.driveBase=driveBase;C.referralBase=referralBase;C.getDeviceId=deviceId;C.beginPasswordLogin=begin;C.finishPasswordLogin=finish;C.refreshPasswordChallenge=reload;C.login=begin;C.refreshAccess=refreshAccess;C.authHeaders=authHeaders;C.publicHeaders=publicHeaders;C.refreshCaptcha=function(action,identity){var s=C.session(),r=captchaForAction(action,String(identity||((s&&s.sub)||C.item('user_id','')||'')),C.item('captcha_token',''),String((s&&s._device_id)||deviceId()));return r&&r.captcha_token?String(r.captcha_token):'';};C.request=request;C.requestDrive=function(method,path,body,opt){return request(method,driveBase()+path,body,opt||{});};C.requestPublic=function(method,path,body,opt){opt=opt||{};opt.auth=false;return request(method,driveBase()+path,body,opt);};C.requestUser=function(method,path,body,opt){opt=opt||{};opt.auth=false;return request(method,userBase()+path,body,opt);};C.androidAuthProfile=A;
})(PikPakCore);
