/* ACFun 0.5.0-test.2 Local-First overlay over Stable 0.4.9 */
(function(){
if(typeof ac!=='object')throw new Error('ACFun Stable 0.4.9 runtime missing');
var VERSION='0.5.0-test.2',BUILD=50002;
var ROOT='hiker://files/rules/asset-core-local/acfun-test/b50002/';
var META=ROOT+'bundle_meta.json',BUNDLE=ROOT+'runtime_bundle.js',TRAMP="var ac=$.require('acfun');";
function compat(k){try{clearItem(k);}catch(e){}try{setItem(k,TRAMP);return true;}catch(e2){return false;}}
compat('acfun_core_src_v018');compat('acfun_core_src_v019');compat('acfun_remote_bundle_src');
ac.localFirstVersion=VERSION;ac.localFirstBuild=BUILD;ac.build='2026.08.25-local-0.5.0-test.2';ac.runtimeMode='stable-049-local-first-storage-guard';
ac.localFirstInfo=function(){var m={};try{if(fileExist(META))m=JSON.parse(String(readFile(META)||'{}'));}catch(e){}return{version:VERSION,build:BUILD,ready:fileExist(BUNDLE),modules:Number(m.modules||0),bytes:Number(m.bytes||0),sourceRef:String(m.sourceRef||''),installedAt:Number(m.installedAt||0),imageDecoder:!!m.imageDecoder,storageGuard:String(ac.storageGuardVersion||'')};};
ac.localUpdatePage=function(){setPageTitle('ACFun 本地化版本');var d=[],m=ac.localFirstInfo();d.push({title:'ACFun '+VERSION,desc:'Build '+BUILD+' · Stable 0.4.9 业务基线 Local-First',col_type:'long_text',url:'hiker://empty'});d.push({title:'本地运行包',desc:(m.ready?'已就绪':'未完成')+' · '+m.modules+' 模块 · '+m.bytes+' B\nStorage Guard '+(m.storageGuard||'--'),col_type:'text_1',url:'hiker://empty'});d.push({title:'私有存储修复',desc:'大型 Remote Config / Frontend Discovery 已迁移到 hiker://files；启动会清理可重建旧大值，收藏/历史保留并仅在异常超大时备份压缩。',col_type:'long_text',url:'hiker://empty'});d.push({title:'检查更新',desc:'更新由“我的规则仓库”统一管理。',col_type:'text_1',url:$('hiker://empty#noLoading#').lazyRule(function(){var loading=false;try{showLoading('检查 ACFun 测试版…');loading=true;var repo='huoguotiankong/asset-core-7f3',h=JSON.parse(String(fetch('https://api.github.com/repos/'+repo+'/branches/main?_t='+Date.now(),{timeout:2600,headers:{'Cache-Control':'no-cache','Accept':'application/vnd.github+json'}})||'{}')),sha=String(h&&h.commit&&h.commit.sha||'');if(!/^[0-9a-f]{40}$/i.test(sha))throw new Error('main HEAD 无效');var c=JSON.parse(String(fetch('https://raw.githubusercontent.com/'+repo+'/'+sha+'/apps/video/acfun/channels.json',{timeout:3000,headers:{'Cache-Control':'no-cache'}})||'{}')),a=c&&c.channels||[],t=null;for(var i=0;i<a.length;i++)if(String(a[i]&&a[i].channel||'')==='test'){t=a[i];break;}hideLoading();loading=false;if(!t)return'toast://未发现测试通道';return Number(t.build||0)>50002?'toast://发现 '+String(t.version||'新测试版')+' / Build'+Number(t.build||0)+'，请从“我的规则仓库”覆盖更新':'toast://当前已是最新测试版 '+String(t.version||VERSION);}catch(e){if(loading)try{hideLoading();}catch(_e){}return'toast://检查失败：'+String(e.message||e);}})});d.push({title:'本地化诊断',desc:'只读本地 bundle / 文件缓存状态。',col_type:'text_1',url:$('hiker://empty#noLoading#').lazyRule(function(){try{var r='hiker://files/rules/asset-core-local/acfun-test/b50002/',p=r+'bundle_meta.json',m=fileExist(p)?JSON.parse(String(readFile(p)||'{}')):{};return'confirm://ACFun 0.5.0-test.2 / Build50002\nbundle '+(fileExist(r+'runtime_bundle.js')?'ready':'missing')+'\nmodules '+String(m.modules||0)+'\nbytes '+String(m.bytes||0)+'\nconfig-file '+(fileExist('hiker://files/rules/asset-core-local/acfun-test/shared/remote_config.json')?'ready':'empty')+'\ndiscovery-file '+(fileExist('hiker://files/rules/asset-core-local/acfun-test/shared/frontend_discovery.json')?'ready':'empty');}catch(e){return'toast://诊断失败：'+String(e.message||e);}})});d.push({title:'说明',desc:'首页/分类/搜索/详情/播放/漫画/封面解密继续沿用 Stable 0.4.9；本版只修 Local-First 交付与 ACFun 私有存储 1MB 风险。',col_type:'long_text',url:'hiker://empty'});setResult(d);};
})();
