/* ACFAN 0.1.0-test.1 protocol/auth */
var ACFANProtocol=(function(){
  var C=ACFANCore;
  function safeJson(v){if(v===undefined||v===null)return null;if(typeof v==='object')return v;var s=String(v).trim();if(!s)return null;try{return JSON.parse(s);}catch(e){return null;}}
  function md5(text){try{var md=java.security.MessageDigest.getInstance('MD5'),bytes=md.digest(new java.lang.String(String(text||'')).getBytes('UTF-8')),sb=new java.lang.StringBuilder();for(var i=0;i<bytes.length;i++){var v=bytes[i]&255;if(v<16)sb.append('0');sb.append(java.lang.Integer.toHexString(v));}return String(sb.toString());}catch(e){return'';}}
  function deviceId(){var d=getItem(C.K.device,'');if(d)return d;d=md5(String(Date.now())+'-'+String(Math.random())+'-acfan-clean')||('hk'+Date.now());setItem(C.K.device,d);return d;}
  function headers(noAuth,origin){var ts=String(Date.now()),sub=ts.length>=8?ts.substring(3,8):ts,base=origin||getItem(C.K.host,'')||C.staticApiHosts[0],h={'User-Agent':C.ua,'Accept':'application/json, text/plain, */*','Content-Type':'application/json;charset=UTF-8','deviceId':deviceId(),'t':ts,'s':md5(sub),'User-Mark':'acfun','Origin':base,'Referer':base.replace(/\/+$/,'')+'/'};var token=getItem(C.K.token,'');if(!noAuth&&token)h.aut=token;return h;}
  function aesDecrypt(src){src=C.s(src).trim();if(!src)return'';var token=C.s(getItem(C.K.token,''));if(token.length<18)throw new Error('响应需要游客令牌');var secret=token.substring(2,18),kb=new java.lang.String(secret).getBytes('UTF-8'),key=new javax.crypto.spec.SecretKeySpec(kb,'AES'),iv=new javax.crypto.spec.IvParameterSpec(kb),cipher=javax.crypto.Cipher.getInstance('AES/CBC/PKCS5Padding');cipher.init(javax.crypto.Cipher.DECRYPT_MODE,key,iv);var enc=java.util.Base64.getDecoder().decode(src.replace(/\s+/g,''));return String(new java.lang.String(cipher.doFinal(enc),'UTF-8'));}
  function storeSession(jr){if(!jr||typeof jr!=='object')return;var t=C.deep(jr,['token','userToken','accessToken'],0);if(typeof t==='string'&&t.length>16)setItem(C.K.token,t);var img=C.deep(jr,['imgDomain','imageDomain','cdnDomain'],0);if(typeof img==='string'&&/^https?:\/\//i.test(img))setItem(C.K.imgDomain,img.replace(/\/+$/,''));}
  function payload(body){var jr=safeJson(body);if(!jr)return null;storeSession(jr);if(jr.encData!==undefined&&C.s(jr.encData).trim()){var plain=aesDecrypt(jr.encData),j=safeJson(plain);jr.data=j===null?plain:j;}if(jr.data!==undefined)return jr.data;if(jr.result!==undefined&&typeof jr.result!=='string')return jr.result;if(jr.rows!==undefined)return jr.rows;return jr;}
  function normalizeHost(u){u=C.s(u).trim();var m=u.match(/^(https?:\/\/[^/?#]+)/i);return m?m[1].replace(/\/+$/,''):'';}
  function extractHosts(root){var out=[],seen={},count=0;function add(v){if(typeof v!=='string')return;var h=normalizeHost(v);if(!h||/\.work$/i.test(h)||seen[h])return;seen[h]=1;out.push(h);}function walk(v,d){if(!v||d>7||count++>1400)return;if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],d+1);return;}if(typeof v!=='object')return;for(var k in v){if(/baseurl|apiurl|apidomain|apihost|apibaseuri|host|domain/i.test(k)){if(Array.isArray(v[k]))for(var j=0;j<v[k].length;j++)add(v[k][j]);else add(v[k]);}}for(var k2 in v)if(v[k2]&&typeof v[k2]==='object')walk(v[k2],d+1);}walk(root,0);return out;}
  function discoverHosts(force){var ts=Number(getItem(C.K.hostsTs,'0')||0),cached=[];try{cached=JSON.parse(getItem(C.K.hosts,'[]')||'[]');}catch(e){}if(!force&&cached.length&&Date.now()-ts<6*3600e3)return cached;var out=[],seen={},i;function add(h){h=normalizeHost(h);if(!h||seen[h])return;seen[h]=1;out.push(h);}add(getItem(C.K.host,''));for(i=0;i<C.configUrls.length;i++){try{var raw=fetch(C.configUrls[i]+'?_='+Date.now(),{timeout:2500,headers:{'User-Agent':C.ua,'Accept':'application/json,*/*','Cache-Control':'no-cache'}}),j=safeJson(raw),hs=extractHosts(j||{});for(var x=0;x<hs.length;x++)add(hs[x]);}catch(e2){}}for(i=0;i<C.staticApiHosts.length;i++)add(C.staticApiHosts[i]);if(out.length){setItem(C.K.hosts,JSON.stringify(out.slice(0,10)));setItem(C.K.hostsTs,String(Date.now()));}return out.slice(0,10);}
  function rawRequest(host,path,params,opt){opt=opt||{};params=params||{};var p=C.s(path).replace(/^\/+/,''),method=C.s(opt.method||'GET').toUpperCase(),url=host.replace(/\/+$/,'')+'/api/'+p,target=url,options={timeout:Number(opt.timeout||3500),headers:headers(!!opt.noAuth,host),method:method,withStatusCode:true};if(method==='GET')target=buildUrl(url,params);else options.body=JSON.stringify(params);var got=fetch(target,options),wrap=safeJson(got);if(!wrap)return{ok:false,error:'EMPTY_WRAPPER',status:0};var status=Number(wrap.statusCode||wrap.status||0),body=wrap.body!==undefined?wrap.body:got;body=body===undefined||body===null?'':String(body);if(status<200||status>=300)return{ok:false,error:'HTTP_'+status,status:status,body:body};var jr=safeJson(body);if(!jr)return{ok:false,error:'NON_JSON',status:status,body:body};storeSession(jr);var code=jr.code!==undefined?Number(jr.code):(jr.statusCode!==undefined?Number(jr.statusCode):NaN);if([301,302,401,403,1001,1003].indexOf(code)>=0)return{ok:false,auth:true,error:'AUTH_'+code,status:status,body:body};if(!isNaN(code)&&code!==0&&code!==200)return{ok:false,error:'CODE_'+code+'_'+C.s(jr.message||jr.msg||''),status:status,body:body};return{ok:true,status:status,body:body,json:jr,url:target};}
  function ensureTraveler(force){if(!force&&getItem(C.K.token,''))return true;var hosts=discoverHosts(force),did=deviceId(),bodies=[{deviceId:did,chCode:'acfan'},{deviceId:did,chCode:'acfan',code:'',bza:'bza'},{deviceId:did,chCode:'acfan',ttb:'A'}],errs=[];for(var h=0;h<hosts.length;h++){for(var b=0;b<bodies.length;b++){try{var r=rawRequest(hosts[h],'user/traveler/',bodies[b],{method:'POST',noAuth:true,timeout:4200});if(r.ok){storeSession(r.json);if(getItem(C.K.token,'')){setItem(C.K.host,hosts[h]);C.diag('TRAVELER_OK',hosts[h]);return true;}}errs.push(hosts[h]+' '+r.error);}catch(e){errs.push(hosts[h]+' '+C.s(e.message||e));}}}C.diag('TRAVELER_FAIL',errs.slice(-8).join(' | '));return false;}
  function api(path,params,opt){opt=opt||{};params=params||{};if(!opt.noAuth&&!/^user\/traveler\/?$/i.test(C.s(path)))ensureTraveler(false);var hosts=discoverHosts(false),errs=[],auth=false;for(var i=0;i<hosts.length;i++){try{var r=rawRequest(hosts[i],path,params,opt);if(r.ok){setItem(C.K.host,hosts[i]);C.diag('API_OK',(opt.method||'GET')+' '+path,{host:hosts[i]});var data=payload(r.body);if(data!==null&&data!==undefined)return data;errs.push(hosts[i]+' EMPTY_DATA');}else{if(r.auth)auth=true;errs.push(hosts[i]+' '+r.error);}}catch(e){errs.push(hosts[i]+' '+C.s(e.message||e));}}if(auth&&!opt.__retry){setItem(C.K.token,'');if(ensureTraveler(true)){var nopt=C.merge(opt,{__retry:true});return api(path,params,nopt);}}C.diag('API_FAIL',path+' | '+errs.slice(-6).join(' | '));throw new Error('接口失败：'+path);}
  function tryApi(path,params,methods,opt){methods=methods||['GET'];var errs=[];for(var i=0;i<methods.length;i++){try{return api(path,params,C.merge(opt||{},{method:methods[i]}));}catch(e){errs.push(methods[i]+':'+C.s(e.message||e));}}throw new Error(errs.join(' | '));}
  return{safeJson:safeJson,md5:md5,deviceId:deviceId,headers:headers,aesDecrypt:aesDecrypt,payload:payload,normalizeHost:normalizeHost,discoverHosts:discoverHosts,rawRequest:rawRequest,ensureTraveler:ensureTraveler,api:api,tryApi:tryApi};
})();
