/* ACFAN 0.1.0-test.1 providers/models */
var ACFANProvider=(function(){
  var C=ACFANCore,P=ACFANProtocol;
  function mediaLike(v){var s=C.s(v).trim();return!!s&&(/\.(?:m3u8|mp4|m4v|flv|mp3|m4a|aac)(?:[?#]|$)/i.test(s)||/\/api\/m3u8\//i.test(s));}
  function mediaPath(root){root=root||{};var known=['videoUrl','playUrl','videoUri','m3u8Url','m3u8','playPath','sourcePath','audioUrl','audioPath'],containers=[root],i,j,v;if(root.video&&typeof root.video==='object')containers.push(root.video);if(root.videoInfo&&typeof root.videoInfo==='object')containers.push(root.videoInfo);if(root.content&&typeof root.content==='object')containers.push(root.content);for(i=0;i<containers.length;i++)for(j=0;j<known.length;j++){v=C.first(containers[i][known[j]]);if(v)return v;}for(j=0;j<known.length;j++){v=C.first(C.deep(root,[known[j]],0));if(v)return v;}return'';}
  function videoInfo(x){x=x||{};var v=x.video||x.videoInfo||x.content||x;if(v.video&&typeof v.video==='object')v=v.video;var u=x.user||x.userInfo||x.blogger||v.user||v.userInfo||{},id=C.pick(v,['videoId','id','vid','lsjVideoId'],C.pick(x,['videoId','id','vid'],C.deep(x,['videoId','lsjVideoId'],0))),title=C.pick(v,['videoTitle','title','name','video_title'],C.pick(x,['videoTitle','title','name'],'未命名视频')),cover=C.first(C.pick(v,['videoCover','coverImg','videoCoverImg','generatedCoverImg','templateCoverImg','defaultVideoPoster','cover','coverUrl','img','image','poster'],''));if(!cover)cover=C.first(C.deep(x,['videoCover','coverImg','generatedCoverImg','templateCoverImg','defaultVideoPoster','coverUrl'],0));return{kind:'video',id:C.s(id),title:C.s(title||'未命名视频'),img:C.s(cover),author:C.s(C.pick(u,['nickname','nickName','name','username','userName'],C.pick(v,['authorName','author','userName','nickname'],''))),duration:C.s(C.pick(v,['duration','videoDuration','playTime','video_duration'],C.deep(x,['duration','videoDuration'],0))),watch:C.s(C.pick(v,['watchNum','viewNum','playNum','fakeWatchNum','statisticsTimes'],C.deep(x,['watchNum','viewNum','statisticsTimes'],0))),like:C.s(C.pick(v,['likeNum','likes','favoriteNum','likeCount'],C.deep(x,['likeNum','likeCount'],0))),uri:mediaPath(x),desc:C.s(C.pick(v,['description','desc','introduction','videoDesc'],'')),raw:x};}
  function comicInfo(x){x=x||{};var id=C.pick(x,['comicsId','comicId','id','comic_id'],C.deep(x,['comicsId','comicId'],0)),title=C.pick(x,['comicsTitle','comicTitle','title','name','comic_title'],C.deep(x,['comicsTitle','comicTitle'],0)||'未命名漫画'),cover=C.first(C.pick(x,['coverImg','comicsCover','comicCover','verticalCover','cover','img','image','poster'],''));if(!cover)cover=C.first(C.deep(x,['coverImg','comicsCover','comicCover','verticalCover'],0));return{kind:'comic',id:C.s(id),title:C.s(title),img:C.s(cover),author:C.s(C.pick(x,['authorName','author','nickName','nickname'],'')),desc:C.s(C.pick(x,['subTitle','subtitle','description','desc','info','introduction'],'')),raw:x};}
  function fictionInfo(x,mode){x=x||{};var id=C.pick(x,['fictionId','bookId','novelId','id'],C.deep(x,['fictionId','bookId'],0)),title=C.pick(x,['fictionTitle','bookTitle','bookName','novelTitle','title','name'],C.deep(x,['fictionTitle','bookTitle'],0)||'未命名'),cover=C.first(C.pick(x,['fictionImg','fictionCover','fictionCoverImg','coverImg','verticalImg','cover','poster','img'],''));if(!cover)cover=C.first(C.deep(x,['fictionImg','fictionCover','fictionCoverImg','verticalImg'],0));return{kind:mode==='audio'?'audio':'fiction',id:C.s(id),title:C.s(title),img:C.s(cover),author:C.s(C.pick(x,['authorName','author','nickName','nickname'],'')),desc:C.s(C.pick(x,['description','desc','info','introduction'],'')),raw:x};}
  function dynamicInfo(x){x=x||{};var u=x.user||x.userInfo||x.blogger||{},id=C.pick(x,['dynamicId','postId','id'],C.deep(x,['dynamicId','postId'],0)),text=C.pick(x,['dynamicContent','content','contentText','text','title'],C.deep(x,['dynamicContent','contentText'],0)),img=C.first(C.pick(x,['dynamicImg','dynamicImage','cardImg','coverImg','imageUrl','imgUrl','backImg','images','pictures'],''));return{kind:'community',id:C.s(id),title:C.clean(text)||'社区动态',img:C.s(img),author:C.s(C.pick(u,['nickname','nickName','userName','name'],C.pick(x,['userName','nickname','authorName'],''))),like:C.s(C.pick(x,['likeNum','likeCount','likes'],'')),comment:C.s(C.pick(x,['commentNum','commentCount','comments'],'')),raw:x};}
  function namedRows(rows,idKeys,nameKeys){var out=[];for(var i=0;i<(rows||[]).length;i++){var x=rows[i]||{},id=C.pick(x,idKeys,''),name=C.pick(x,nameKeys,'');if(!id||!name||/(?:测试|test|ces\d*|竖版|横滑|宫格|专题\d)/i.test(C.s(name)))continue;out.push({id:C.s(id),name:C.s(name),raw:x});}return C.uniq(out,function(z){return z.id;});}
  function stations(restricted){var raw=P.tryApi('station/stations',{classifyId:4,page:1,pageSize:40,restricted:restricted?1:0},['GET','POST'],{timeout:3500});return namedRows(C.arr(raw),['stationId','stationID','id'],['stationName','stationTitle','title','name']);}
  function catalog(kind){var type=kind==='video'?4:2,raw=P.tryApi('video/classTypeList',{type:type,restricted:0},['GET','POST'],{timeout:3500});return namedRows(C.arr(raw),['classifyId','classTypeId','videoTypeId','typeId','id'],['classifyTitle','classTypeTitle','classifyName','classTypeName','videoTypeName','title','name']);}
  function zones(classId){var raw=P.tryApi('video/getZoneListByClassifyId',{classifyId:C.n(classId)},['GET','POST'],{timeout:3200}),out=namedRows(C.arr(raw),['zoneId','id'],['zoneTitle','zoneName','title','name']);for(var i=0;i<out.length;i++)out[i].mode='zone';if(out.length)return out;try{var tags=P.tryApi('video/tags/getTagsZ',{videoTypeId:C.n(classId),classifyId:C.n(classId),restricted:0},['GET','POST'],{timeout:3200}),rows=C.arr(tags),t=[];for(var j=0;j<rows.length;j++){var n=C.pick(rows[j],['videoTagName','videoTagValue','tagsTitle','tagTitle','tagName','name','title'],'');if(n)t.push({id:C.s(n),name:C.s(n),mode:'tag'});}return C.uniq(t,function(z){return z.id;});}catch(e){return[];}}
  function comicStations(){var raw=P.tryApi('comics/station/getComicsStations',{},['GET','POST'],{timeout:3500});return namedRows(C.arr(raw),['stationId','comicsStationId','id'],['stationName','stationTitle','name','title']);}
  function fictionTags(mode){var type=mode==='audio'?2:1,raw=P.tryApi('fiction/other/tagList',{fictionType:type,type:type},['POST','GET'],{timeout:3500});return namedRows(C.arr(raw),['fictionTagId','tagId','categoryId','id'],['fictionTagName','tagName','categoryName','name','title']);}
  function communityCategories(){try{var raw=P.tryApi('dynamic/category/tree',{},['GET','POST'],{timeout:3200});return namedRows(C.arr(raw),['categoryId','dynamicType','id'],['categoryName','dynamicTypeName','name','title']);}catch(e){return[];}}
  function findNamed(rows,id){id=C.s(id);for(var i=0;i<rows.length;i++)if(C.s(rows[i].id)===id)return rows[i];return rows[0]||null;}
  function list(section,page,state){page=Number(page||1);state=state||{};var size=C.pageSize(),sort=Number(state.sort||1);if(section==='featured'||section==='lifan'){var restricted=section==='lifan'?1:0,sts=stations(restricted),st=findNamed(sts,state.station);if(!st)return{filters:{stations:sts},items:[]};if(page===1&&st.raw&&Array.isArray(st.raw.videoList)&&st.raw.videoList.length)return{filters:{stations:sts,selectedStation:st},items:st.raw.videoList.slice(0,size)};var rows=C.arr(P.tryApi('station/getStationMore',{stationId:C.n(st.id),page:page,pageNum:page,pageSize:size,sortType:sort,restricted:restricted},['GET','POST'],{timeout:3800}));return{filters:{stations:sts,selectedStation:st},items:rows};}
    if(section==='anime'||section==='video'){var clsRows=catalog(section),cls=findNamed(clsRows,state.classId);if(!cls)return{filters:{classes:clsRows},items:[]};var zRows=zones(cls.id),z=findNamed(zRows,state.zoneId),route,p;if(z&&z.mode==='zone'){route='video/queryVideoByZone';p={page:page,pageNum:page,pageSize:size,zoneId:C.n(z.id),classifyId:C.n(cls.id),sortType:sort};}else if(z){route='video/tagTitleList';p={page:page,pageNum:page,pageSize:size,tagsTitle:z.name,classifyId:C.n(cls.id),sortType:sort,restricted:0};}else{route='video/getByClassify';p={classifyId:C.n(cls.id),page:page,pageNum:page,pageSize:size,sortType:sort,restricted:0};}return{filters:{classes:clsRows,selectedClass:cls,zones:zRows,selectedZone:z},items:C.arr(P.tryApi(route,p,['GET','POST'],{timeout:3800}))};}
    if(section==='short'){var lt=Number(state.shortType||2),rows2=C.arr(P.tryApi('video/list',{page:page,pageNum:page,pageSize:15,loadType:lt},['GET','POST'],{timeout:3800}));return{filters:{},items:rows2};}
    if(section==='comic'){var cs=comicStations(),cst=findNamed(cs,state.station);if(!cst)return{filters:{stations:cs},items:[]};if(page===1&&cst.raw&&Array.isArray(cst.raw.comicsBaseList)&&cst.raw.comicsBaseList.length)return{filters:{stations:cs,selectedStation:cst},items:cst.raw.comicsBaseList.slice(0,size)};return{filters:{stations:cs,selectedStation:cst},items:C.arr(P.tryApi('comics/station/getStationComicsMore',{stationId:C.n(cst.id),page:page,pageNum:page,pageSize:size,sortType:sort},['GET','POST'],{timeout:3800}))};}
    if(section==='fiction'||section==='audio'){var tags=fictionTags(section),tag=findNamed(tags,state.tagId),fp={page:page,pageNum:page,pageSize:size,limit:size,sortType:1,fictionType:section==='audio'?2:1};if(tag){fp.tagId=C.n(tag.id);fp.fictionTagId=C.n(tag.id);fp.categoryId=C.n(tag.id);}if(section==='audio')fp.isAudio=1;return{filters:{tags:tags,selectedTag:tag},items:C.arr(P.tryApi('fiction/base/findList',fp,['POST','GET'],{timeout:4000}))};}
    if(section==='community'){var cats=communityCategories(),cat=findNamed(cats,state.categoryId),cp={page:page,pageNum:page,pageSize:size,limit:size};if(cat){cp.categoryId=C.n(cat.id);cp.dynamicType=C.n(cat.id);}return{filters:{categories:cats,selectedCategory:cat},items:C.arr(P.tryApi('community/dynamic/list',cp,['GET','POST'],{timeout:4000}))};}
    return{filters:{},items:[]};}
  function search(kind,q,page){page=Number(page||1);var size=C.pageSize(),p={page:page,pageNum:page,pageSize:size,keyword:q,title:q};if(kind==='video'){var tries=[['video/queryVideoByTitle',{page:page,pageNum:page,pageSize:size,title:q,keyword:q,videoType:1}],['search/keyWordV2',{page:page,pageNum:page,pageSize:size,searchWord:q,keyword:q,keyWord:q,searchType:1}],['search/keyWord',{page:page,pageNum:page,pageSize:size,searchWord:q,keyword:q,keyWord:q,searchType:1}]];for(var i=0;i<tries.length;i++)try{var r=C.arr(P.tryApi(tries[i][0],tries[i][1],['GET','POST'],{timeout:3800}));if(r.length)return r;}catch(e){}return[];}if(kind==='comic'){p.comicsTitle=q;return C.arr(P.tryApi('comics/base/findList',p,['GET','POST'],{timeout:4000}));}if(kind==='fiction'||kind==='audio'){p.fictionTitle=q;p.fictionType=kind==='audio'?2:1;if(kind==='audio')p.isAudio=1;return C.arr(P.tryApi('fiction/base/findList',p,['POST','GET'],{timeout:4000}));}if(kind==='community'){p.content=q;return C.arr(P.tryApi('community/dynamic/list',p,['GET','POST'],{timeout:4000}));}return[];}
  function detail(kind,id){var params=[{id:C.n(id)}],path='';if(kind==='video'){path='video/getVideoById';params=[{videoId:C.n(id)},{id:C.n(id)}];}else if(kind==='comic'){path='comics/base/info';params=[{comicsId:C.n(id)},{comicId:C.n(id)},{id:C.n(id)}];}else if(kind==='fiction'||kind==='audio'){path='fiction/base/info';params=[{fictionId:C.n(id)},{bookId:C.n(id)},{id:C.n(id)}];}else if(kind==='community'){var eps=['community/dynamic/detail','community/dynamic/info'];for(var e=0;e<eps.length;e++)for(var q=0;q<params.length;q++)try{return P.tryApi(eps[e],{dynamicId:C.n(id),id:C.n(id)},['GET','POST'],{timeout:3600});}catch(ex){}return{};}for(var i=0;i<params.length;i++)try{return P.tryApi(path,params[i],['GET','POST'],{timeout:4000});}catch(err){}return{};}
  function chapterRows(root,type){var out=[],seen={},count=0;function walk(v,d){if(v===undefined||v===null||d>10||count>12000)return;if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],d+1);return;}if(typeof v!=='object')return;count++;var id=type==='comic'?C.pick(v,['chapterId','comicsChapterId','comicChapterId','id'],''):C.pick(v,['chapterId','fictionChapterId','id'],''),title=C.pick(v,['chapterTitle','chapterName','title','name'],'');if(id&&!seen[C.s(id)]){seen[C.s(id)]=1;out.push({id:C.s(id),title:C.s(title||('第'+(out.length+1)+'章')),raw:v});}for(var k in v)if(v[k]&&typeof v[k]==='object')walk(v[k],d+1);}walk(root,0);return out;}
  function comicChapter(comicId,chapterId){var ps=[{chapterId:C.n(chapterId)},{comicsId:C.n(comicId),chapterId:C.n(chapterId)},{comicId:C.n(comicId),chapterId:C.n(chapterId)}];for(var i=0;i<ps.length;i++)try{return P.tryApi('comics/base/chapterInfo',ps[i],['GET','POST'],{timeout:4200});}catch(e){}return{};}
  function comicImages(root){var out=[],seen={},domain=C.s(C.pick(root||{},['domain','imgDomain','imageDomain'],'')||''),count=0;function add(s){s=C.s(s).trim();if(!s||seen[s])return;if(!(/^(https?:)?\/\//i.test(s)||/\.(?:png|jpe?g|webp|gif)(?:[?#]|$)/i.test(s)||/^(?:jhimage|comic|comics|image|img)\//i.test(s)))return;seen[s]=1;out.push({url:s,domain:domain});}function walk(v,k,d){if(v===undefined||v===null||d>11||count>16000)return;if(typeof v==='string'){if(/img|image|pic|picture|url|path/i.test(C.s(k)))add(v);return;}if(Array.isArray(v)){for(var i=0;i<v.length;i++){if(typeof v[i]==='string')add(v[i]);else walk(v[i],k,d+1);}return;}if(typeof v!=='object')return;count++;for(var key in v)walk(v[key],key,d+1);}if(root&&Array.isArray(root.imgList))for(var i=0;i<root.imgList.length;i++)add(root.imgList[i]);walk(root,'',0);return out;}
  function fictionChapter(fid,cid){var ps=[{fictionId:C.n(fid),chapterId:C.n(cid)},{chapterId:C.n(cid)},{fictionId:C.n(fid),fictionChapterId:C.n(cid)}];for(var i=0;i<ps.length;i++)try{return P.tryApi('fiction/base/chapterInfo',ps[i],['POST','GET'],{timeout:4200});}catch(e){}return{};}
  function fictionPayload(root){var texts=[],audios=[],images=[],seenT={},seenA={},seenI={},count=0,base=C.s(C.pick(root||{},['playbackDomain','audioDomain','mediaDomain'],'')||''),auth=C.s(C.pick(root||{},['playbackAuthKey','authKey','auth_key'],'')||'');function add(a,seen,s){s=C.s(s).trim();if(s&&!seen[s]){seen[s]=1;a.push(s);}}function join(b,p){p=C.s(p).trim();if(!p)return'';if(p.indexOf('//')===0)return'https:'+p;if(/^https?:\/\//i.test(p))return p;if(b&&/^https?:\/\//i.test(b))return b.replace(/\/+$/,'')+'/'+p.replace(/^\/+/, '');return p;}function walk(v,key,d){if(v===undefined||v===null||d>11||count>16000)return;if(typeof v==='string'){var ss=v.trim(),low=C.s(key).toLowerCase();if(/content|text|body|paragraph/.test(low)&&ss&&!/^https?:\/\//i.test(ss)&&ss.length>1)add(texts,seenT,ss);if(/audio|sourcepath|playpath|audiourl|mediaurl|url|path/.test(low)&&(/\.(?:mp3|m4a|aac|wav|ogg|flac|m3u8)(?:[?#]|$)/i.test(ss)||/audio|sourcepath|playpath/.test(low))){var u=join(base,ss);if(auth&&u&&u.indexOf('auth_key=')<0&&u.indexOf('authKey=')<0)u+=(u.indexOf('?')>=0?'&':'?')+'auth_key='+encodeURIComponent(auth);add(audios,seenA,u);}if(/image|img|picture|pic/.test(low)&&(/^(https?:)?\/\//i.test(ss)||/\.(?:png|jpe?g|webp|gif)(?:[?#]|$)/i.test(ss)))add(images,seenI,ss);return;}if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],key,d+1);return;}if(typeof v!=='object')return;count++;for(var k in v)walk(v[k],k,d+1);}walk(root,'',0);return{texts:texts,audios:audios,images:images};}
  function comments(videoId,page,sort){return C.arr(P.tryApi('video/commentList',{videoId:C.n(videoId),page:page,pageNum:page,pageSize:20,sortType:sort==='new'?'new':'hot'},['GET','POST'],{timeout:3800}));}
  return{mediaLike:mediaLike,mediaPath:mediaPath,videoInfo:videoInfo,comicInfo:comicInfo,fictionInfo:fictionInfo,dynamicInfo:dynamicInfo,stations:stations,catalog:catalog,zones:zones,comicStations:comicStations,fictionTags:fictionTags,communityCategories:communityCategories,list:list,search:search,detail:detail,chapterRows:chapterRows,comicChapter:comicChapter,comicImages:comicImages,fictionChapter:fictionChapter,fictionPayload:fictionPayload,comments:comments};
})();
