/* 色花堂 Test16 forum/card polish */
var SeHuaTangV16Forum=(function(C){
function group(m,seed,name){var g=0;try{if(m._debug&&m._debug.groupFromCacheV15)g=Number(m._debug.groupFromCacheV15(seed,name))}catch(e){}name=C.trim(name);if(g===0&&/^(中文字幕|国产自拍|亚洲视频|经典三级|在线视频)$/i.test(name))g=1;return g}
function previews(a){var n=0,i;for(i=0;i<(a||[]).length;i++)n+=(a[i].imgs||[]).length;return n}
function merge(a,b){var mp={},i,j,x,seen;for(i=0;i<(b||[]).length;i++)mp[b[i].id]=b[i];for(i=0;i<(a||[]).length;i++){x=mp[a[i].id];if(!x)continue;if((!a[i].meta||!a[i].meta.author)&&x.meta)a[i].meta=x.meta;seen={};for(j=0;j<(a[i].imgs||[]).length;j++)seen[C.canonical(a[i].imgs[j])]=1;for(j=0;j<(x.imgs||[]).length&&a[i].imgs.length<2;j++)if(!seen[C.canonical(x.imgs[j])])a[i].imgs.push(x.imgs[j])}return a}
function stats(ctx,it){var t=C.strip(ctx),m,r='',l='',v='',all=[],re;if(it.title)t=t.replace(it.title,' ');if(it.meta&&it.meta.author)t=t.replace(it.meta.author,' ');m=t.match(/(?:回复|评论)[:：]?\s*(\d{1,7})/i);if(m)r=m[1];m=t.match(/(?:查看|浏览|观看)[:：]?\s*(\d{1,10})/i);if(m)v=m[1];m=t.match(/(?:点赞|赞)[:：]?\s*(\d{1,7})/i);if(m)l=m[1];if(!r||!v){re=/(?:^|\s)(\d{1,5})\s+(\d{1,5})\s+(\d{2,10})(?=\s|$)/g;while((m=re.exec(t))!==null)if(Number(m[3])>=Number(m[1]))all.push(m);if(all.length){m=all[all.length-1];if(!r)r=m[1];if(!l)l=m[2];if(!v)v=m[3]}}return{replies:r,likes:l,views:v}}
function attach(a,h){var i,x,st,en,ctx;for(i=0;i<(a||[]).length;i++){x=a[i];st=Number(x.titleIndex||0);en=i+1<a.length?Number(a[i+1].titleIndex||0):C.s(h).length;if(en<=st||en-st>90000)en=Math.min(C.s(h).length,st+65000);ctx=C.s(h).slice(st,en);x.stats=stats(ctx,x);x.summary=C.trim(C.s(x.summary).replace(/^(?:\d+\s+){2,4}/,'').replace(/(?:回复|评论|查看|浏览|观看)[:：]?\s*\d+/g,' ').replace(/\s+/g,' '))}return a}
function load(m,seed,p,g){var fn=m._debug&&m._debug.parseCardsV15,mu=C.withPage(C.toMobile(seed),p),pu=C.withPage(C.toPc(seed),p),h='',a=[],b=[];if(!fn)return{items:[],url:mu,diag:'missing parser'};h=C.renderList(mu);a=attach(fn(h,mu,g)||[],h);if(!a.length){h=C.fetchPage(mu,false);a=attach(fn(h,mu,g)||[],h)}if(a.length&&previews(a)<Math.max(2,Math.floor(a.length/4))){h=C.fetchPage(pu,true);b=attach(fn(h,pu,g)||[],h);a=merge(a,b)}if(!a.length){h=C.fetchPage(pu,true);a=attach(fn(h,pu,g)||[],h)}return{items:a,url:mu,diag:'items='+a.length+' img='+previews(a)}}
function key(seed){var f=C.forumId(seed);return'sht_forum_page_v16_'+(f||C.s(seed).replace(/[^a-z0-9]/ig,'').slice(-24)||'x')}
function btn(t,k,p,on){return{title:t,url:on?$('#noLoading#').lazyRule(function(a,b){putMyVar(a,String(b));refreshPage(false);return'hiker://empty';},k,p):'hiker://empty',col_type:'text_3',extra:{lineVisible:false}}}
function controls(k,p,n){return[btn(p>1?'上一页':'第一页',k,Math.max(1,p-1),p>1),btn(p>1?'回第1页':'第1页',k,1,p>1),btn(n?'下一页':'已到底',k,p+1,n)]}
function author(d,it,ref){var m=it.meta||{},av=m.avatar?C.imageUrl(m.avatar,ref):'';if(m.author||av)d.push({title:(m.author||'发布者')+(m.role?' · '+m.role:''),desc:m.time||'',img:av,pic_url:av,url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false}})}
function statRow(d,x){x=x||{};var a=[];if(x.replies)a.push('💬 '+x.replies);if(x.likes&&x.likes!=='0')a.push('👍 '+x.likes);if(x.views)a.push('👁 '+x.views);if(a.length)d.push({title:'<div style="text-align:right"><small><font color="#999999">'+a.join('　')+'</font></small></div>',url:'hiker://empty',col_type:'rich_text',extra:{lineVisible:false}})}
function videoDesc(it){var m=C.s(it.summary).match(/\b\d{1,2}:\d{2}:\d{2}\b/),a=[];if(m)a.push(m[0]);if(it.meta&&it.meta.time)a.push(it.meta.time);return a.join(' · ')}
function cards(d,a,ref,g){var i,j,it,u,p,ct;for(i=0;i<a.length;i++){it=a[i];u=C.route('shtThread',{sht_url:C.toMobile(it.url),sht_name:it.title,sht_group:g});if(g===1){p=(it.imgs||[]).length?C.imageUrl(it.imgs[0],ref):'';d.push({title:it.title,desc:videoDesc(it),img:p,pic_url:p,url:u,col_type:p?'movie_2':'text_2',extra:{lineVisible:false}});continue}author(d,it,ref);d.push({title:it.title,desc:it.summary||'查看帖子',url:u,col_type:'text_1',extra:{lineVisible:false}});ct=(it.imgs||[]).length===1?'pic_1_full':'pic_2';for(j=0;j<(it.imgs||[]).length&&j<2;j++){p=C.imageUrl(it.imgs[j],ref);d.push({title:'',img:p,pic_url:p,url:u,col_type:ct,extra:{lineVisible:false}})}statRow(d,it.stats);d.push(C.line())}}
function forum(m){var d=[],seed=C.pageParam('sht_url',''),name=C.pageParam('sht_name','主题列表'),g=group(m,seed,name),k=key(seed),pp=Number(C.pageParam('sht_p','0')||0),p,r,c;if(pp>0){putMyVar(k,String(pp));p=pp}else p=Math.max(1,Number(getMyVar(k,'1')||1));setPageTitle(name);r=load(m,seed,p,g);C.saveDiag('forum.mobile.v16','g='+g+' p='+p+' '+r.diag);if(p===1){d.push(C.quick('手机版','x5://'+C.withPage(C.toMobile(seed),1),'web.svg'));d.push(C.quick('搜索',C.route('shtSearch'),'search.svg'));d.push(C.line());d.push(C.section(name,(g===1?'在线视频双列卡片':'手机端帖子卡片')+' · 第 '+p+' 页 · '+r.items.length+' 条主题'))}else d.push(C.section(name,'第 '+p+' 页 · 页内刷新翻页'));c=controls(k,p,r.items.length>0);Array.prototype.push.apply(d,c);d.push(C.line());cards(d,r.items,r.url,g);if(r.items.length){c=controls(k,p,true);Array.prototype.push.apply(d,c)}else d.push(C.empty('本页没有解析到主题','可点上一页或回第1页'));setResult(d)}
return{forum:forum,stats:stats};
})(SeHuaTangV16Core);