/* 色花堂 Test16 thread/comments */
var SeHuaTangV16Thread=(function(C){
function floors(h){var out=[],seen={},ss=['body&&#postlist>div','body&&#postlist&&div[id^=post_]','body&&div.t_fsz','body&&div.t_f','body&&td.t_f','body&&[id^=postmessage_]','body&&.message'],i,j,n,b,a,k;for(i=0;i<ss.length;i++){try{n=pdfa(h,ss[i])||[]}catch(e){n=[]}for(j=0;j<n.length;j++){try{b=pdfh(n[j],'body&&div.t_fsz&&Html')||pdfh(n[j],'body&&div.t_f&&Html')||pdfh(n[j],'body&&td.t_f&&Html')||pdfh(n[j],'body&&.message&&Html')||pdfh(n[j],'body&&Html')||C.s(n[j])}catch(e2){b=C.s(n[j])}if(!C.trim(C.strip(b)))continue;try{a=C.trim(pdfh(n[j],'body&&.authi&&a&&Text')||pdfh(n[j],'body&&.xw1&&Text')||'')}catch(e3){a=''}k=C.strip(b).slice(0,220);if(k&&!seen[k]){seen[k]=1;out.push({body:b,author:a})}}if(out.length)break}return out}
function text(x){var y=C.s(x);y=y.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<iframe[\s\S]*?<\/iframe>/gi,'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p\s*>/gi,'\n').replace(/<\/div\s*>/gi,'\n').replace(/<[^>]+>/g,' ');return C.trim(y.replace(/[ \t\r]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n'))}
function esc(x){return C.s(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function emitText(d,t){t=C.trim(t);if(t)d.push({title:esc(t).replace(/\n/g,'<br>'),url:'hiker://empty',col_type:'rich_text',extra:{lineVisible:false}})}
function emitImg(d,u,ref){var p=C.imageUrl(u,ref);d.push({title:'',img:p,pic_url:p,url:'pics://'+p,col_type:'pic_1_full',extra:{lineVisible:false,imgLongClick:true}})}
function ordered(d,b,ref){var x=C.s(b),re=/<img\b[^>]*>/gi,m,last=0,u,t,n=0;while((m=re.exec(x))!==null){t=text(x.slice(last,m.index));if(t)emitText(d,t);u=C.imgFromTag(m[0],ref);if(u){emitImg(d,u,ref);n++}last=re.lastIndex}t=text(x.slice(last));if(t)emitText(d,t);return n}
function mags(x){var out=[],seen={},m,re=/magnet:\?xt=urn:btih:[a-z0-9]{32,40}(?:&[^\s"'<>]*)?/ig,v,k;while((m=re.exec(C.s(x)))!==null){v=m[0].replace(/[)\]}>，。；;]+$/g,'');k=(v.match(/btih:([a-z0-9]{32,40})/i)||[])[1]||v;if(!seen[k]){seen[k]=1;out.push(v)}if(out.length>=20)break}return out}
function replyUrl(h,b){var m=C.s(h).match(/href=["']([^"']*(?:mod=post[^"']*action=reply|action=reply[^"']*mod=post)[^"']*)["']/i);return m?C.abs(m[1],b):b}
function fetchThread(m,u){return m._debug&&m._debug.threadFetchMobileV12?m._debug.threadFetchMobileV12(u):{html:'',url:u,diag:'missing threadFetchMobileV12'}}
function media(d,b,u,ref){var m=C.s(b).match(/(https?:\/\/[^\s"'<>]+?\.(?:m3u8|mp4)(?:\?[^\s"'<>]*)?)/i);if(m)d.push({title:'▶ 直接播放',url:m[1]+'#isVideo=true#',col_type:'text_center_1',extra:{lineVisible:false}});else if(/<video\b|<iframe\b|视频加载中|在线播放|dplayer|ckplayer|jwplayer/i.test(C.s(b)))d.push({title:'▶ 嗅探播放',url:'video://'+u,col_type:'text_center_1',extra:{lineVisible:false,ua:C.UA_M,referer:u,cacheM3u8:true}})}
function magnetActions(d,b){var a=mags(b),i,x,h;for(i=0;i<a.length;i++){x=a[i];h=(x.match(/btih:([a-z0-9]{32,40})/i)||[])[1]||'';d.push({title:'磁链 '+(i+1),desc:h?h.slice(0,14)+'…':'已识别',url:'copy://'+x,col_type:'text_1',extra:{lineVisible:false}});d.push(C.quick('115','hiker://page/115Offline?rule=115.简&page=fypage&add='+encodeURIComponent(x),'cloud115.svg'));d.push(C.quick('迅雷','hiker://page/diaoyong?rule=迅雷&page=fypage#'+x,'thunder.svg'));d.push(C.quick('PikPak','pikpakapp://mypikpak.com/xpan/main_tab?tab=1&add_url='+x,'pikpak.svg'));d.push(C.quick('复制','copy://'+x,'copy.svg'))}}
function thread(m){var d=[],u=C.toMobile(C.pageParam('sht_url','')),title=C.pageParam('sht_name','帖子详情'),g=Number(C.pageParam('sht_group','-1')),r,f,b,ref,n,imgs,i;if(!u){setResult([C.empty('帖子参数缺失')]);return}setPageTitle(title);r=fetchThread(m,u);ref=r.url||u;f=floors(r.html);C.saveDiag('thread.mobile.v16',(r.diag||'')+' g='+g+' floors='+f.length);d.push(C.section(title,'正文与评论分离 · 手机端正文优先'));d.push(C.quick('手机版','x5://'+u,'web.svg'));d.push(C.quick('回复','x5://'+replyUrl(r.html,ref),'reply.svg'));d.push(C.quick('评论页',C.route('shtComments',{sht_url:u,sht_name:title,sht_group:g}),'comments.svg'));d.push(C.quick('设置',C.route('shtSettings'),'settings.svg'));d.push(C.line());if(!f.length){d.push(C.empty('未识别到帖子正文'));setResult(d);return}b=f[0].body;d.push(C.section('楼主'+(f[0].author?' · '+f[0].author:''),'正文'));n=ordered(d,b,ref);if(g===3&&n===0){imgs=C.allImages(r.html,ref,80);if(imgs.length){d.push(C.section('正文图片',imgs.length+' 张'));for(i=0;i<imgs.length;i++)emitImg(d,imgs[i],ref)}}media(d,b,u,ref);magnetActions(d,b);if(f.length>1){d.push(C.line());d.push({title:'💬 查看全部评论（'+(f.length-1)+'）',desc:'评论单独显示，不再打断正文图片',url:C.route('shtComments',{sht_url:u,sht_name:title,sht_group:g}),col_type:'text_center_1',extra:{lineVisible:false}})}setResult(d)}
function comments(m){var d=[],u=C.toMobile(C.pageParam('sht_url','')),title=C.pageParam('sht_name','评论'),r,f,ref,i;if(!u){setResult([C.empty('评论参数缺失')]);return}setPageTitle('评论 · '+title);r=fetchThread(m,u);ref=r.url||u;f=floors(r.html);d.push(C.quick('参与回复','x5://'+replyUrl(r.html,ref),'reply.svg'));d.push(C.quick('手机版','x5://'+u,'web.svg'));d.push(C.line());if(f.length<=1){d.push(C.empty('暂无评论','可以点“参与回复”进入官网回复页'));setResult(d);return}for(i=1;i<f.length&&i<60;i++){d.push(C.section('回复 '+i+(f[i].author?' · '+f[i].author:''),'评论'));ordered(d,f[i].body,ref);d.push(C.line())}setResult(d)}
return{thread:thread,comments:comments};
})(SeHuaTangV16Core);