/* 我的规则仓库 v3.5.0-rc5 - cleaner category center */
(function(R){
R.categoryPage=function(){
setPageTitle('分类');var d=[],items;try{items=this.items(false);}catch(e){setResult([{title:'分类暂时不可用',desc:String(e.message||e),url:'hiker://empty',col_type:'long_text'}]);return;}var state=this.filterState(),batch=this.batchMode(),result=this.applyFilters(items,state);this.pushNav(d,'category');
d.push({title:'分类与筛选',desc:this.filterSummary(state)+'\n当前 '+result.length+' 个程序',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
d.push(this.actionChip(batch?'退出批量管理':'批量管理',$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.setBatchMode(!r.batchMode());refreshPage(false);return'hiker://empty';})));d.push(this.actionChip('重置筛选',$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearAllFilters();refreshPage(false);return'toast://筛选已重置';})));
if(batch){var n=this.selectedIds().length;this.pushSpacer(d);this.pushSection(d,'批量管理','已选择 '+n+' 个；批量操作只处理仓库记录。');d.push(this.actionChip('收藏所选',$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore'),n=r.batchFavorite(true);refreshPage(false);return'toast://已处理 '+n+' 项';})));d.push(this.actionChip('取消收藏',$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore'),n=r.batchFavorite(false);refreshPage(false);return'toast://已处理 '+n+' 项';})));d.push(this.actionChip('清版本记录',$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore'),n=r.batchClearInstalled();refreshPage(false);return'toast://已清除 '+n+' 项';})));d.push(this.actionChip('清空选择',$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearSelection();refreshPage(false);return'toast://选择已清空';})));}
this.pushSpacer(d);this.pushSection(d,'主分类','');this.categories(items).forEach(function(c){d.push({title:(state.category===c.id?'● ':'')+c.name+' '+c.count,col_type:'scroll_button',url:$('#noLoading#').lazyRule(function(id){putMyVar('hc_repo_category',id);putMyVar('hc_repo_sub','all');putMyVar('hc_repo_tag','all');refreshPage(false);return'hiker://empty';},c.id),extra:{lineVisible:false}});});
var subs=this.subCategories(items,state.category);if(subs.length>1){this.pushSpacer(d);this.pushSection(d,'子分类','');subs.forEach(function(s){d.push(R.actionChip((state.subCategory===s.id?'● ':'')+s.name+' '+s.count,$('#noLoading#').lazyRule(function(id){putMyVar('hc_repo_sub',id);putMyVar('hc_repo_tag','all');refreshPage(false);return'hiker://empty';},s.id)));});}
var fresh=this.filterState(),tags=this.tagsFor(items,fresh);if(tags.length){this.pushSpacer(d);this.pushSection(d,'能力标签','');d.push(this.actionChip((fresh.tag==='all'?'● ':'')+'全部',$('#noLoading#').lazyRule(function(){putMyVar('hc_repo_tag','all');refreshPage(false);return'hiker://empty';})));tags.slice(0,12).forEach(function(t){d.push(R.actionChip((fresh.tag===t.name?'● ':'')+'#'+t.name,$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_tag',v);refreshPage(false);return'hiker://empty';},t.name)));});}
this.pushSpacer(d);this.pushSection(d,'更多筛选','运行模式与排序');[['全部模式','all'],['远程','remote'],['本地','local']].forEach(function(x){d.push(R.actionChip((fresh.mode===x[1]?'● ':'')+x[0],$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_mode',v);refreshPage(false);return'hiker://empty';},x[1])));});[['默认','default'],['最近更新','updated'],['名称','name'],['版本','version']].forEach(function(x){d.push(R.actionChip((fresh.sort===x[1]?'● ':'')+x[0],$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_sort',v);refreshPage(false);return'hiker://empty';},x[1])));});
result=this.applyFilters(items,this.filterState());this.pushSpacer(d);this.pushSection(d,batch?'选择程序':'筛选结果',result.length+' 个程序');result.forEach(function(x){d.push(batch?R.selectCard(x):R.itemCard(x));});if(!result.length)this.pushEmpty(d,'没有匹配的程序','可以减少筛选条件或重置筛选。');setResult(d);
};
})(HikerRuleRepo);
