/* 我的规则仓库 v3.5.0-rc5 - premium detail and channel experience */
(function(R){
R.channelMeta=function(parent){var path=String(parent&&parent.channelsPath||parent&&parent.raw&&parent.raw.channelsPath||'');if(path){try{var x=JSON.parse(this.apiText(path));if(x&&Array.isArray(x.channels)&&x.channels.length)return x;}catch(e){}}return null;};
R.channelPage=function(parent){
setPageTitle(parent.name);var d=[],meta=this.channelMeta(parent),self=this;if(!meta){setResult([{title:'版本信息暂时不可用',desc:'版本通道读取失败。可以先返回，稍后重试或在设置中同步云端索引。',url:'hiker://page/ruleRepoSettings?rule=&simple=true',col_type:'text_center_1'}]);return;}try{setPagePicUrl(this.iconOf(parent));}catch(e){}
var cs=meta.channels||[],stable=null,test=null;for(var i=0;i<cs.length;i++){if(cs[i].channel==='stable')stable=cs[i];if(cs[i].channel==='test')test=cs[i];}
d.push({title:parent.name,desc:'统一版本中心\n稳定使用与抢先体验互不干扰',img:this.iconOf(parent),pic_url:this.iconOf(parent),url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});
d.push(this.metric('版本通道',cs.length,'hiker://empty'));d.push(this.metric('正式版',stable?stable.version:'--','hiker://empty'));d.push(this.metric('测试版',test?test.version:'--','hiker://empty'));d.push(this.metric('策略','隔离','hiker://empty'));
this.pushSpacer(d);this.pushSection(d,'选择版本','两个版本使用不同规则名称，可同时安装。测试版出现问题不会影响正式版。');
cs.forEach(function(c){
  var raw={id:String(c.id||''),name:String(c.name||''),version:String(c.version||''),desc:String(c.desc||''),path:String(c.path||''),category:parent.category,categoryName:parent.categoryName,subCategory:parent.subCategory,tags:['远程',c.channel==='test'?'测试':'正式','管理','版本'],mode:String(c.mode||'remote'),updatedAt:String(c.updatedAt||meta.updatedAt||''),icon:String(c.icon||self.iconOf(parent)),openTitle:String(c.openTitle||c.name||'')};
  var item=self.normalizeItem(raw,0),status=self.statusOf(item),isStable=c.channel==='stable',badge=isStable?'正式版 · 推荐':'测试版 · 抢先体验',build=c.build!=null?'build '+c.build:'',date=String(c.updatedAt||meta.updatedAt||''),line=[String(c.displayVersion||c.version||''),build,date].filter(function(x){return !!x;}).join(' · ');
  d.push({title:badge,desc:line+'\n'+String(c.desc||'')+'\n仓库记录：'+status,img:String(c.icon||self.iconOf(parent)),pic_url:String(c.icon||self.iconOf(parent)),url:$('#noLoading#').lazyRule(function(x){return $.require('hiker://page/ruleRepoCore').importRule(x);},JSON.stringify(raw)),col_type:'movie_1_left_pic',extra:{lineVisible:false}});
  d.push({title:status==='未记录'?'导入 '+String(c.label||'版本'):(status==='可更新'?'更新 '+String(c.label||'版本'):'重新导入 / 覆盖'),url:$('#noLoading#').lazyRule(function(x){return $.require('hiker://page/ruleRepoCore').importRule(x);},JSON.stringify(raw)),col_type:'text_2',extra:{lineVisible:false}});
  d.push({title:'打开已安装版本',url:$('#noLoading#').lazyRule(function(x){var r=$.require('hiker://page/ruleRepoCore'),it=r.normalizeItem(x,0);return r.openRule(it);},JSON.stringify(raw)),col_type:'text_2',extra:{lineVisible:false}});
  if(Array.isArray(c.highlights)&&c.highlights.length)d.push({title:'本版重点',desc:c.highlights.map(function(x){return'• '+x;}).join('\n'),url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});
});
this.pushSpacer(d);this.pushSection(d,'发布策略','正式版只接收通过 Guard 与实机关键路径验证的版本；测试版用于验证新功能。测试通过后晋级 Stable，正式版再通过远程更新获得新功能。');
d.push({title:'Stable',desc:'适合日常使用 · 长期稳定 · 支持上一稳定版回退',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'Test / Candidate',desc:'优先体验新功能 · 独立更新与回退 · 状态与正式版隔离',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});setResult(d);
};
R.detailPage=function(){
var id=String((MY_PARAMS&&MY_PARAMS.hc_repo_item_id)||getParam('id')||''),item=this.findById(id,false),d=[];if(!item){setResult([{title:'程序不存在',desc:'云端索引可能已更新，请返回首页后重新进入。',url:'hiker://empty',col_type:'text_center_1'}]);return;}if(item.entryType==='channel-group'||item.channelsPath)return this.channelPage(item);
setPageTitle(item.name);try{setPagePicUrl(this.iconOf(item));}catch(e){}var st=this.statusOf(item),iv=this.installedVersion(item),modeDesc=item.mode==='remote'?'自用远程代码版':(item.mode==='share'?'纯本地分享版':'本地程序'),last=this.lastImportedTime(item),opened=this.lastOpenedTime(item);
d.push({title:item.name,desc:String(item.version||'未标记')+' · '+this.statusIcon(item)+' '+st+'\n'+(item.desc||modeDesc),img:this.iconOf(item),pic_url:this.iconOf(item),url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});
d.push({title:'打开',col_type:'text_2',url:$('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id);return x?r.openRule(x):'toast://程序不存在';},item.id),extra:{lineVisible:false}});d.push({title:st==='可更新'?'立即更新':'导入 / 覆盖',col_type:'text_2',url:$('#noLoading#').lazyRule(function(raw){return $.require('hiker://page/ruleRepoCore').importRule(raw);},JSON.stringify(item.raw)),extra:{lineVisible:false}});
d.push(this.metric('云端',item.version||'--','hiker://empty'));d.push(this.metric('记录',iv||'--','hiker://empty'));d.push(this.metric('状态',st,'hiker://empty'));d.push(this.metric('模式',this.modeText(item.mode),'hiker://empty'));
this.pushSpacer(d);this.pushSection(d,'快捷操作','高频操作集中展示');d.push(this.actionChip(this.isFav(item)?'★ 已收藏':'☆ 收藏',$('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id);if(!x)return'toast://程序不存在';var on=r.toggleFav(x);refreshPage(false);return'toast://'+(on?'已收藏':'已取消收藏');},item.id)));d.push(this.actionChip('检查更新',$('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id,true);if(!x)return'toast://程序不存在';return'toast://'+x.name+' · '+r.statusOf(x)+' · 云端 '+x.version;},item.id)));d.push(this.actionChip('导入记录','hiker://page/ruleRepoHistory?rule=&simple=true'));
this.pushSpacer(d);this.pushSection(d,'程序信息','');d.push({title:'分类',desc:item.categoryName+' / '+item.subCategory,url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行模式',desc:modeDesc,url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'更新时间',desc:item.updatedAt||'未标记',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'最近导入',desc:last?this.formatTime(last):'未记录',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'最近打开',desc:opened?this.formatTime(opened):'未通过仓库打开',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});if(item.bytes)d.push({title:'包体大小',desc:Math.round(Number(item.bytes)/1024)+' KB',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
if((item.tags||[]).length){this.pushSpacer(d);this.pushSection(d,'能力标签','');(item.tags||[]).forEach(function(t){d.push({title:'#'+t,col_type:'flex_button',url:'hiker://page/ruleRepoSearch?rule=&simple=true&kw='+encodeURIComponent(t)});});}
this.pushSpacer(d);this.pushSection(d,'管理','这些操作只处理仓库自己的记录，不伪装海阔系统级能力。');d.push({title:'复制云端路径',desc:item.path||'',url:'copy://'+(item.path||''),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清除版本记录',desc:'清除“已记录 / 可更新”的判断依据，不删除海阔中的程序。',url:$('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore');r.removeInstalled(id);refreshPage(false);return'toast://版本记录已清除';},item.id),col_type:'text_1',extra:{lineVisible:false}});setResult(d);
};
})(HikerRuleRepo);
