/* 我的规则仓库 v3.5.0-rc5 - focused search experience */
(function(R){
R.searchPage=function(){
setPageTitle('搜索');var d=[],items;try{items=this.items(false);}catch(e){setResult([{title:'搜索暂时不可用',desc:String(e.message||e),url:'hiker://empty',col_type:'long_text'}]);return;}var pkw=String(getParam('kw','')||getParam('s','')||'').trim(),kw=pkw||String(getMyVar('hc_repo_search_kw','')||'').trim(),scope=String(getMyVar('hc_repo_search_scope','all')||'all');if(pkw){putMyVar('hc_repo_search_kw',pkw);this.recordSearch(pkw);}this.pushNav(d,'search');
d.push({title:'搜索程序、分类、标签或版本',url:$.toString(function(){var q=String(input||'').trim();putMyVar('hc_repo_search_kw',q);var r=$.require('hiker://page/ruleRepoCore');r.recordSearch(q);refreshPage(false);return'hiker://empty';}),col_type:'input',extra:{titleVisible:false,defaultValue:kw,onChange:$.toString(function(){putMyVar('hc_repo_search_kw',String(input||''));})}});
[['全部','all'],['可更新','updates'],['收藏','favorites'],['远程','remote'],['本地','local']].forEach(function(x){d.push(R.actionChip((scope===x[1]?'● ':'')+x[0],$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_search_scope',v);refreshPage(false);return'hiker://empty';},x[1])));});
var hist=this.searchHistory();if(!kw&&hist.length){this.pushSpacer(d);this.pushSection(d,'最近搜索','');hist.slice(0,8).forEach(function(x){d.push(R.actionChip(x,$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_search_kw',v);var r=$.require('hiker://page/ruleRepoCore');r.recordSearch(v);refreshPage(false);return'hiker://empty';},x)));});d.push(R.actionChip('清空',$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearSearchHistory();refreshPage(false);return'toast://搜索历史已清空';})));}
if(!kw){var tags=this.popularTags(items,10);if(tags.length){this.pushSpacer(d);this.pushSection(d,'热门标签','快速发现常用能力');tags.forEach(function(t){d.push(R.actionChip('#'+t.name,$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_search_kw',v);var r=$.require('hiker://page/ruleRepoCore');r.recordSearch(v);refreshPage(false);return'hiker://empty';},t.name)));});}var rec=this.recentItems(items,4);if(rec.length){this.pushSpacer(d);this.pushSection(d,'最近使用','');rec.forEach(function(x){d.push(R.compactApp(x,R.formatTime(R.lastOpenedTime(x))));});}if(!hist.length&&!tags.length&&!rec.length)this.pushEmpty(d,'搜索你的程序','支持名称、描述、标签、分类和版本。');setResult(d);return;}
var a=items.filter(function(x){if(!R.matchKeyword(x,kw))return false;if(scope==='updates')return x.entryType!=='channel-group'&&R.statusOf(x)==='可更新';if(scope==='favorites')return R.isFav(x);if(scope==='remote')return x.mode==='remote';if(scope==='local')return x.mode!=='remote';return true;});this.pushSpacer(d);this.pushSection(d,'搜索结果','“'+kw+'” · '+a.length+' 个结果');d.push(R.actionChip('清除关键词',$('#noLoading#').lazyRule(function(){clearMyVar('hc_repo_search_kw');refreshPage(false);return'hiker://empty';})));a.forEach(function(x){d.push(R.itemCard(x));});if(!a.length)this.pushEmpty(d,'没有找到匹配程序','可以换一个关键词，或切换“全部”搜索范围。');setResult(d);
};
})(HikerRuleRepo);
