/* 我的规则仓库 v3.5.0-rc5 - product settings */
(function(R){
R.settingsPage=function(){
setPageTitle('设置');var d=[],cache=this.cacheMs(),probe=this.probeMs(),test=this.statePrefix.indexOf('test')>=0;this.pushNav(d,'settings');
d.push({title:'我的规则仓库',desc:(test?'测试版 Test':'正式版 Stable')+' · Core '+this.version+' · build '+this.build+'\n云端程序管理中心',img:this.iconOf(this.findById('rule-repo')||{}),pic_url:this.iconOf(this.findById('rule-repo')||{}),url:'hiker://page/ruleRepoAbout?rule=&simple=true',col_type:'movie_1_left_pic',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'云端同步','默认配置兼顾速度、实时性与网络异常可用性');d.push({title:'完整索引缓存',desc:Math.round(cache/60000)+' 分钟 · 缓存有效时优先秒开，网络异常使用最后一次有效索引',url:$('5分钟,15分钟,30分钟,60分钟','选择完整索引缓存').select(function(){var map={'5分钟':300000,'15分钟':900000,'30分钟':1800000,'60分钟':3600000},r=$.require('hiker://page/ruleRepoCore');r.setSetting('cache_ms',map[String(input||'30分钟')]||1800000);refreshPage(false);return'toast://已设置';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'轻量变更探测',desc:(probe<=0?'已关闭':Math.round(probe/1000)+' 秒')+' · 只检查 revision，变化时才刷新完整索引',url:$('关闭,30秒,60秒,180秒,300秒','选择探测频率').select(function(){var map={'关闭':0,'30秒':30000,'60秒':60000,'180秒':180000,'300秒':300000},r=$.require('hiker://page/ruleRepoCore');r.setSetting('probe_ms',map[String(input||'60秒')]);refreshPage(false);return'toast://已设置';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'立即同步程序库',desc:'清理 manifest / revision 缓存并重新读取云端。',url:$('#noLoading#').lazyRule(function(){showLoading('同步程序库…');try{var r=$.require('hiker://page/ruleRepoCore');r.clearManifestCache();r.manifest(true);hideLoading();refreshPage(false);return'toast://同步完成';}catch(e){hideLoading();return'toast://同步失败：'+String(e.message||e);}}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'Core 更新与回退',desc:'当前通道独立升级与回退；Test 不影响 Stable。',url:'hiker://page/ruleRepoUpdate?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'备份与恢复','状态备份不包含 Cookie、Token、账号或密码');d.push({title:'复制状态备份',desc:'收藏、版本记录、最近使用、打开记录、搜索/导入历史、筛选和同步设置。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');return'copy://'+r.exportState();}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'从备份恢复',desc:'仅接受本程序生成的 rule-repo-state JSON。',url:$('粘贴备份 JSON','').input(function(){try{var r=$.require('hiker://page/ruleRepoCore');r.restoreState(String(input||''));r.clearSelection();refreshPage(false);return'toast://备份已恢复';}catch(e){return'toast://恢复失败：'+String(e.message||e);}}),col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'使用记录','这些是仓库自己的辅助记录，不等同于海阔系统安装状态');d.push({title:'导入与使用记录',desc:'查看最近导入和最近打开过的程序。',url:'hiker://page/ruleRepoHistory?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空最近打开',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearOpenHistory();refreshPage(false);return'toast://最近打开已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空搜索历史',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearSearchHistory();return'toast://搜索历史已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空导入历史',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearImportHistory();refreshPage(false);return'toast://导入历史已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空版本记录',desc:'清除“已记录 / 可更新”判断依据，不删除海阔中的程序。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearInstalled();refreshPage(false);return'toast://版本记录已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空收藏',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearFavorites();refreshPage(false);return'toast://收藏已清空';}),col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'界面与筛选','首页保持轻量，复杂筛选集中到分类中心');d.push({title:'重置界面筛选',desc:'重置分类、标签、模式、排序和搜索范围。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearAllFilters();['hc_repo_home_view','hc_repo_home_category','hc_repo_home_sort','hc_repo_search_kw','hc_repo_search_scope'].forEach(clearMyVar);r.clearSelection();refreshPage(false);return'toast://界面状态已重置';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'主题适配',desc:'使用海阔原生组件与透明背景，自动跟随宿主浅色 / 深色主题。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'关于与质量','');d.push({title:'版本与更新日志',desc:'Core '+this.version+' · build '+this.build,url:'hiker://page/ruleRepoAbout?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'产品原则',desc:'一个程序一个入口 · 多版本通道 · 智能同步 · 模块化 · 可升级 · 可回退 · 不伪造系统级能力',url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);
};
R.aboutPage=function(){setPageTitle('关于');var d=[];d.push({title:'我的规则仓库',desc:'Core '+this.version+' · build '+this.build+'\n海阔视界专属 · 云端程序管理中心',img:this.iconOf(this.findById('rule-repo')||{}),pic_url:this.iconOf(this.findById('rule-repo')||{}),url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});this.pushSection(d,'核心能力','智能索引同步 · 分类搜索 · Stable/Test 多通道 · 更新回退 · 收藏 · 最近使用 · 状态备份 · 批量管理');d.push(this.actionChip('分类','hiker://page/ruleRepoCategory?rule=&simple=true'));d.push(this.actionChip('搜索','hiker://page/ruleRepoSearch?rule=&simple=true'));d.push(this.actionChip('更新','hiker://page/ruleRepoUpdates?rule=&simple=true'));this.pushSpacer(d);this.pushSection(d,'架构','Cloud Entry → Channel Selector → Shell → Bootstrap → Remote Manager → Versioned Release Modules。');var log='';try{log=this.apiText('apps/tools/rule-repo/CHANGELOG.md');}catch(e){log='更新日志读取失败：'+String(e.message||e);}d.push({title:'更新日志',desc:log,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);};
})(HikerRuleRepo);
