/* 我的规则仓库 v3.5.0-rc5 - release center */
(function(R){
R.updatesPage=function(){
setPageTitle('更新');var d=[],m,items;try{m=this.manifest(false);items=(m.items||[]).map(this.normalizeItem.bind(this));}catch(e){setResult([{title:'更新中心暂时不可用',desc:String(e.message||e),url:'hiker://empty',col_type:'long_text'}]);return;}this.pushNav(d,'updates');var info={};try{if(typeof RuleRepoBoot==='object')info=RuleRepoBoot.info()||{};}catch(e){}var cur=info.current||{version:this.version,build:this.build},prev=info.previous||null,stats=this.stats(items),last=Number(getItem('hc_repo_updates_last_check','0')||0),test=this.statePrefix.indexOf('test')>=0,edition=test?'Test / Candidate':'Stable',sum=this.actionSummary(items);
d.push({title:'版本与更新',desc:edition+' · Core '+cur.version+' · build '+cur.build+'\n'+(prev?'可回退 '+prev.version:'当前没有回退版本'),img:this.iconOf(this.findById('rule-repo')||{}),pic_url:this.iconOf(this.findById('rule-repo')||{}),url:'hiker://page/ruleRepoUpdate?rule=&simple=true',col_type:'movie_1_left_pic',extra:{lineVisible:false,pageTitle:'Core 更新'}});
d.push(this.actionChip('检查 Core',$('#noLoading#').lazyRule(function(){return'hiker://page/ruleRepoUpdate?rule=&simple=true';})));d.push(this.actionChip('同步程序库',$('#noLoading#').lazyRule(function(){showLoading('同步云端程序库…');try{var r=$.require('hiker://page/ruleRepoCore');r.clearManifestCache();r.manifest(true);setItem('hc_repo_updates_last_check',String(Date.now()));hideLoading();refreshPage(false);return'toast://程序库已同步';}catch(e){hideLoading();return'toast://同步失败：'+String(e.message||e);}})));d.push(this.actionChip('导入记录','hiker://page/ruleRepoHistory?rule=&simple=true'));
d.push(this.metric('可更新',stats.updates,'hiker://empty'));d.push(this.metric('已记录',stats.installed,'hiker://empty'));d.push(this.metric('远程',stats.remote,'hiker://empty'));d.push(this.metric('本地',stats.local,'hiker://empty'));
this.pushSpacer(d);this.pushSection(d,'同步状态','完整索引长缓存 + 轻量 revision 变更探测');d.push({title:'云端索引',desc:'revision '+(sum.revision||String(m.revision||'未标记'))+' · '+String(m.updated||m.updatedAt||'')+'\n上次读取 '+(sum.lastSync?this.formatTime(sum.lastSync):'未记录'),url:'hiker://page/ruleRepoSettings?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'上次手动同步',desc:this.formatTime(last),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
var updates=items.filter(function(x){return x.entryType!=='channel-group'&&R.statusOf(x)==='可更新';});this.pushSpacer(d);this.pushSection(d,'需要处理',updates.length?updates.length+' 个程序有新版本':'当前全部正常');if(updates.length){updates.forEach(function(x){d.push(R.itemCard(x));});}else this.pushEmpty(d,'已是最新记录','云端目录变化会自动探测，无需频繁手动刷新。');
var synced=items.filter(function(x){return x.entryType!=='channel-group'&&R.statusOf(x)==='已同步';});if(synced.length){this.pushSpacer(d);this.pushSection(d,'已同步','最近记录版本与云端一致');synced.slice(0,8).forEach(function(x){d.push(R.compactApp(x,'✓ '+String(x.version||'')));});if(synced.length>8)d.push({title:'还有 '+(synced.length-8)+' 个已同步程序',desc:'可在分类或搜索中查看全部程序。',url:'hiker://page/ruleRepoCategory?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});}
this.pushSpacer(d);this.pushSection(d,'更新原则','新 Core 先进入测试通道，经过 Release Guard 与实机关键路径验证后再晋级 Stable。程序更新逐项确认，不做不可逆的静默批量覆盖。');setResult(d);
};
})(HikerRuleRepo);
