/* 色花堂 0.1.0-test.8 / Build 10108 - forum grouping + previews + native image rendering */
var SeHuaTangPatchTest8=(function(){
  var BASE=SeHuaTangRemoteRuntime;
  var VERSION='0.1.0-test.8',BUILD=10108,RULE_NAME='色花堂';
  var DEFAULT_ORIGIN='https://sehuatang.org';
  var KEY_ORIGIN='sht_origin_v1',KEY_COOKIE='sht_web_cookie_v5',KEY_CAT='sht_cat_group_v6',KEY_ACCESS='sht_access_ok_v7';
  var KEY_GROUP_CACHE='sht_forum_groups_v8',KEY_DIAG='sht_diag_v1';
  var UA_M='Mozilla/5.0 (Linux; Android 13; zh-CN) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Mobile Safari/537.36';
  var UA_PC='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36';
  var LOGO='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/aggregate/sehuatang/assets/v1/logo.svg';
  var ROOTS=[
    {name:'原创BT电影',fid:'2',seed:'forum-2-1.html',icon:'🎬'},
    {name:'在线视频区',fid:'41',seed:'forum-41-1.html',icon:'▶️'},
    {name:'原档收藏',fid:'145',seed:'forum-145-1.html',icon:'💿'},
    {name:'色花图片',fid:'155',seed:'forum-155-1.html',icon:'🖼️'},
    {name:'色花文学',fid:'154',seed:'forum-154-1.html',icon:'✍️'},
    {name:'综合讨论区',fid:'95',seed:'forum-95-1.html',icon:'💬'}
  ];
  var ROOT_IDS={2:1,41:1,145:1,155:1,154:1,95:1};
  function s(v){return v==null?'':String(v)}
  function trim(v){return s(v).replace(/^\s+|\s+$/g,'')}
  function dec(v){v=s(v);try{return decodeURIComponent(v)}catch(e){return v}}
  function hdec(v){var x=s(v),i;for(i=0;i<2;i++)x=x.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;/gi,' ');return x}
  function strip(v){return trim(hdec(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/[\t\r]+/g,' ').replace(/\s+/g,' '))}
  function origin(){var o=trim(getItem(KEY_ORIGIN,DEFAULT_ORIGIN));return /^https?:\/\//i.test(o)?o.replace(/\/+$/,''):DEFAULT_ORIGIN}
  function abs(h,b){h=hdec(trim(h));if(!h)return'';if(/^https?:\/\//i.test(h))return h;if(/^\/\//.test(h))return'https:'+h;if(/^(javascript:|mailto:|tel:|#)/i.test(h))return'';var m=s(b).match(/^(https?:\/\/[^\/]+)/i),o=m?m[1]:origin();if(h.charAt(0)==='/')return o+h;var c=s(b).split('#')[0].split('?')[0];if(c.charAt(c.length-1)!=='/')c=c.replace(/\/[^\/]*$/,'/');return c+h.replace(/^\.\//,'')}
  function pageParam(n,d){var u=s(typeof MY_URL==='undefined'?'':MY_URL),m=u.match(new RegExp('[?&]'+n+'=([^&#]*)'));return m?dec(m[1]):(d==null?'':d)}
  function route(path,p){var u='hiker://page/'+path+'?rule='+RULE_NAME+'&simple=true',k;for(k in(p||{}))if(p.hasOwnProperty(k)&&p[k]!=null)u+='&'+k+'='+encodeURIComponent(s(p[k]));return u}
  function line(cls){return{col_type:'line',extra:{cls:cls||''}}}
  function section(t,d,cls){return{title:t,desc:d||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false,cls:cls||''}}}
  function empty(t,d){return{title:t,desc:d||'',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}}}
  function quick(t,u,cls){return{title:t,img:LOGO,pic_url:LOGO,url:u,col_type:'icon_small_4',extra:{lineVisible:false,cls:cls||''}}}
  function saveDiag(stage,msg){try{setItem(KEY_DIAG,JSON.stringify({stage:stage,origin:origin(),error:s(msg||'').slice(0,1200),time:new Date().getTime()}))}catch(e){}}
  function cookie(){var c='';try{c=getVar(KEY_COOKIE,'')||''}catch(e){}if(c)return c;try{c=getCookie(origin())||''}catch(e2){}return c}
  function headers(pc,ref){var c=cookie(),h={'User-Agent':pc?UA_PC:UA_M,'Referer':ref||origin()+'/'};if(c){h.Cookie=c;h.cookie=c}return h}
  function imageUrl(u,ref){u=abs(u,ref);if(!u)return'';return u+'@headers='+JSON.stringify(headers(false,ref||origin()+'/'))}
  function forumId(u){var m=s(u).match(/forum-(\d+)-\d+/i)||s(u).match(/[?&]fid=(\d+)/i);return m?m[1]:''}
  function threadId(u){var x=hdec(s(u)),m=x.match(/[?&]tid=(\d+)/i)||x.match(/[?&]ptid=(\d+)/i)||x.match(/\/thread-(\d+)-\d+-\d+\.html/i);return m?m[1]:''}
  function normalizeThread(u){var id=threadId(u);if(!id)return u;if(/[?&]ptid=\d+/i.test(u)&&!/[?&]tid=\d+/i.test(u))return origin()+'/forum.php?mod=viewthread&tid='+id+'&mobile=2';if(!/[?&]mobile=/.test(u))u+=(u.indexOf('?')>=0?'&':'?')+'mobile=2';return u}
  function anchors(html,base){var out=[],re=/<a\b([^>]*?)href\s*=\s*(?:["']([^"']+)["']|([^\s>]+))([^>]*)>([\s\S]*?)<\/a>/gi,m,a,t,tm;while((m=re.exec(s(html)))!==null){a=(m[1]||'')+' '+(m[4]||'');t=strip(m[5]||'');if(!t){tm=a.match(/\b(?:title|aria-label)\s*=\s*["']([^"']+)["']/i);if(tm)t=strip(tm[1])}out.push({href:abs(m[2]||m[3]||'',base),text:t,inner:m[5]||'',attrs:a,index:m.index});if(out.length>14000)break}return out}
  function fetchPage(u){var h='';try{h=s(fetchPC(u,{headers:headers(true,u),timeout:13000}))}catch(e){}if(h.length<600)try{h=s(fetchCodeByWebView(u,{headers:headers(false,u),timeout:18000,blockRules:['.mp4','.m3u8','.woff','.woff2','.ttf'],checkJs:$.toString(function(){var t=String((document.body&&document.body.innerText)||'');return t.length>700?'ready':null;})}))}catch(e2){}return h}
  function cleanForumTitle(t){t=trim(t).replace(/^[-–—·•\s]+|[-–—·•\s]+$/g,'');return t}
  function parseForums(html,base){var a=anchors(html,base),out=[],seen={},i,id,t;for(i=0;i<a.length;i++){id=forumId(a[i].href);t=cleanForumTitle(a[i].text);if(!id||seen[id]||!t)continue;if(/^(首页|论坛|返回|话题|板块|发帖|搜索|更多|社区版块)$/i.test(t))continue;seen[id]=1;out.push({id:id,title:t,url:a[i].href,index:a[i].index})}return out}
  function childrenFromRoot(root){var url=origin()+'/'+root.seed+(root.seed.indexOf('?')>=0?'&':'?')+'mobile=no',html=fetchPage(url),all=parseForums(html,url),out=[],seen={},i,x;for(i=0;i<all.length;i++){x=all[i];if(ROOT_IDS[x.id]||x.id===root.fid||seen[x.id])continue;seen[x.id]=1;out.push(x)}return{items:out,htmlLen:html.length,url:url}}
  function childrenFromIndex(root){var url=origin()+'/forum.php?mobile=no',html=fetchPage(url),all=parseForums(html,url),pos=-1,end=999999999,out=[],seen={},i,j,x;for(i=0;i<all.length;i++){if(all[i].id===root.fid&&pos<0){pos=all[i].index;continue}if(pos>=0&&ROOT_IDS[all[i].id]&&all[i].index>pos){end=all[i].index;break}}if(pos<0)return{items:[],htmlLen:html.length,url:url};for(j=0;j<all.length;j++){x=all[j];if(x.index<=pos||x.index>=end||ROOT_IDS[x.id]||seen[x.id])continue;seen[x.id]=1;out.push(x)}return{items:out,htmlLen:html.length,url:url}}
  function fallbackV7(rootIndex){var m=BASE.module(),g=[];try{if(m._debug&&m._debug.resolveGroupsV7)g=m._debug.resolveGroupsV7()[rootIndex]||[]}catch(e){}return g}
  function readGroupCache(){try{var x=JSON.parse(getItem(KEY_GROUP_CACHE,'{}')||'{}');if(x.groups&&new Date().getTime()-Number(x.time||0)<21600000)return x.groups}catch(e){}return null}
  function resolveGroups(){var c=readGroupCache(),groups=[[],[],[],[],[],[]],diag=[],i,r,fb;if(c)return c;try{fallbackV7(0)}catch(e0){}for(i=0;i<ROOTS.length;i++){r=childrenFromRoot(ROOTS[i]);diag.push(ROOTS[i].fid+':root='+r.items.length);if(r.items.length<2){r=childrenFromIndex(ROOTS[i]);diag.push(ROOTS[i].fid+':index='+r.items.length)}if(r.items.length<2){fb=fallbackV7(i);if(fb&&fb.length>1)r.items=fb;diag.push(ROOTS[i].fid+':v7='+(fb?fb.length:0))}if(!r.items.length)r.items=[{id:ROOTS[i].fid,title:ROOTS[i].name,url:origin()+'/'+ROOTS[i].seed}];groups[i]=r.items}
    try{setItem(KEY_GROUP_CACHE,JSON.stringify({time:new Date().getTime(),groups:groups}))}catch(e2){}saveDiag('groups.v8',diag.join('；')+'；final='+groups.map(function(x){return x.length}).join(','));return groups}
  function topicInput(cls){return{title:'搜索主题',desc:'搜索',col_type:'input',url:"(function(){var w=String(input||'').trim();if(!w)return 'toast://请输入关键词';putMyVar('sht_search_kw_v1',w);return 'hiker://page/shtSearch?rule=色花堂&simple=true&kw='+encodeURIComponent(w);})()",extra:{defaultValue:'',titleVisible:true,cls:cls||''}}}
  function home(){var d=[],idx=Number(getMyVar(KEY_CAT,'0')||0),groups,g,i,access='';if(idx<0||idx>5)idx=0;setPageTitle('色花堂');groups=resolveGroups();g=groups[idx]||[];try{access=getVar(KEY_ACCESS,'')||''}catch(e){}
    d.push(topicInput('sht_home_v8'));d.push(quick('👤 账号',route('shtVerify',{sht_mode:'login'}),'sht_home_v8'));d.push(quick('📅 签到',route('shtVerify',{sht_mode:'signin'}),'sht_home_v8'));d.push(quick('🔍 搜索',route('shtSearch'),'sht_home_v8'));d.push(quick('⚙️ 设置',route('shtSettings'),'sht_home_v8'));d.push(line('sht_home_v8'));
    d.push(section('话题',access==='1'?'站点可访问'+(cookie()?' · Cookie 已同步':' · Cookie 尚未同步'):'站点访问状态尚未建立，可点“账号”自动处理','sht_home_v8'));
    [['🆕 最新发表','latest'],['🔥 最新热门','hot'],['⭐ 最新精华','digest']].forEach(function(x){d.push({title:x[0],desc:'主题列表',url:route('shtForum',{sht_auto:x[1],sht_name:x[0].replace(/^[^\s]+\s*/, '')}),col_type:'text_3',extra:{lineVisible:false,cls:'sht_home_v8'}})});
    d.push(line('sht_home_v8'));d.push(section('论坛分类','六个一级分类；当前分类下显示真实子板块','sht_home_v8'));
    for(i=0;i<ROOTS.length;i++)d.push({title:(i===idx?'✓ ':'')+ROOTS[i].icon+' '+ROOTS[i].name,url:$('#noLoading#').lazyRule(function(k,v,cache){putMyVar(k,String(v));refreshPage(false);return'hiker://empty';},KEY_CAT,i,KEY_GROUP_CACHE),col_type:'text_3',extra:{lineVisible:false,cls:'sht_home_v8'}});
    d.push(section(ROOTS[idx].icon+' '+ROOTS[idx].name,g.length+' 个子板块','sht_home_v8'));
    for(i=0;i<g.length;i++)d.push({title:'▸ '+g[i].title,desc:'进入板块',img:LOGO,pic_url:LOGO,url:route('shtForum',{sht_url:g[i].url,sht_name:g[i].title}),col_type:'icon_2',extra:{lineVisible:false,cls:'sht_home_v8'}});setResult(d)}
  function badThreadText(t){t=trim(t);if(!t||t.length<2)return true;if(/^(回复|查看|查看帖子|查看全部|最后发表|最后回复|上一页|下一页|返回|详情|进入|播放)$/i.test(t))return true;if(/^\d{1,2}:\d{2}(?::\d{2})?$/.test(t))return true;if(/^\d{4}[-/.]\d{1,2}[-/.]\d{1,2}$/.test(t))return true;if(/^\d+$/.test(t))return true;return false}
  function threadScore(t){t=trim(t);if(badThreadText(t))return-999;var n=Math.min(t.length,120);if(/[\u4e00-\u9fffA-Za-z]{2,}/.test(t))n+=35;if(t.length>=8)n+=20;if(t.length>100)n-=20;if(/^(作者|回复|浏览|查看|发表于)/.test(t))n-=30;return n}
  function validImage(u,base){u=abs(u,base);if(!u)return'';if(/avatar\.php|noavatar|smiley|static\/image\/common|logo\.|none\.gif|loading|blank\.gif|emotion|face\//i.test(u))return'';if(/^data:/i.test(u))return'';return u}
  function imageCandidates(x,base){var out=[],seen={},re=/<img\b([^>]*)>/gi,m,a,names=['data-original','data-src','data-echo','data-lazy-src','zoomfile','file','src'],i,n,rr,mm,u,style;while((m=re.exec(s(x)))!==null){a=m[1]||'';u='';for(i=0;i<names.length;i++){n=names[i];rr=new RegExp('\\b'+n+'\\s*=\\s*(["\\\'])(.*?)\\1','i');mm=a.match(rr);if(mm){u=validImage(mm[2],base);if(u)break}}if(!u){style=a.match(/background(?:-image)?\s*:\s*url\((?:["']?)([^)"']+)/i);if(style)u=validImage(style[1],base)}if(u&&!seen[u]){seen[u]=1;out.push(u)}if(out.length>=20)break}return out}
  function contextAround(html,index){var x=s(html),start=x.lastIndexOf('<tbody',index),end=start>=0?x.indexOf('</tbody>',index):-1;if(start>=0&&end>=0&&end-start<30000)return x.slice(start,end+8);start=x.lastIndexOf('<li',index);end=start>=0?x.indexOf('</li>',index):-1;if(start>=0&&end>=0&&end-start<20000)return x.slice(start,end+5);start=Math.max(0,index-1800);end=Math.min(x.length,index+3600);return x.slice(start,end)}
  function parseThreads(html,base){var a=anchors(html,base),map={},order=[],i,x,id,t,sc,ctx,pics,out=[];for(i=0;i<a.length;i++){x=a[i];id=threadId(x.href);if(!id)continue;t=trim(x.text);sc=threadScore(t);if(!map[id]){map[id]={id:id,title:sc>-900?t:'',url:normalizeThread(x.href),score:sc,img:'',index:x.index};order.push(id)}else if(sc>map[id].score){map[id].title=t;map[id].score=sc;map[id].url=normalizeThread(x.href);map[id].index=x.index}}
    for(i=0;i<order.length;i++){id=order[i];x=map[id];if(!x||badThreadText(x.title))continue;ctx=contextAround(html,x.index);pics=imageCandidates(ctx,base);x.img=pics.length?pics[0]:'';out.push({id:id,title:x.title.slice(0,150),url:x.url,img:x.img});if(out.length>=100)break}return{items:out,anchors:a.length}}
  function withPage(u,p){p=Math.max(1,Number(p||1));u=s(u);if(/\/forum-\d+-\d+\.html(?:\?|$)/i.test(u))return u.replace(/\/forum-(\d+)-\d+\.html/i,'/forum-$1-'+p+'.html');if(/([?&])page=\d+/i.test(u))return u.replace(/([?&])page=\d+/i,'$1page='+p);return u+(u.indexOf('?')>=0?'&':'?')+'page='+p}
  function pcVariant(u){u=s(u);if(/[?&]mobile=2(?:&|$)/i.test(u))return u.replace(/([?&])mobile=2(?:&|$)/i,function(_,p){return p+'mobile=no&'}).replace(/&$/,'');if(/[?&]mobile=no(?:&|$)/i.test(u))return u;return u+(u.indexOf('?')>=0?'&':'?')+'mobile=no'}
  function loadThreadList(seed,pg){var urls=[],first=withPage(seed,pg),pc=pcVariant(first),i,u,h,p,steps=[];urls.push(first);if(pc!==first)urls.push(pc);for(i=0;i<urls.length;i++){u=urls[i];h=fetchPage(u);p=parseThreads(h,u);steps.push('v8-'+(i+1)+':'+h.length+'字/'+p.items.length+'主题/'+p.items.filter(function(x){return !!x.img}).length+'缩略图');if(p.items.length)return{items:p.items,url:u,source:'v8',diag:steps.join('；')}}return{items:[],url:first,source:'none',diag:steps.join('；')}}
  function forum(){var d=[],seed=pageParam('sht_url',''),kind=pageParam('sht_auto',''),name=pageParam('sht_name','主题列表'),pg=Math.max(1,Number(typeof MY_PAGE==='undefined'?1:MY_PAGE||1)),r,i,item,img,bm=BASE.module();setPageTitle(name);if(!seed&&kind)try{seed=bm._debug&&bm._debug.discoverGuideV7?bm._debug.discoverGuideV7(kind):''}catch(e){}if(!seed){bm.forum();return}r=loadThreadList(seed,pg);saveDiag('forum.v8',(kind||'forum')+' · '+r.url+' · '+r.diag);if(!r.items.length){bm.forum();return}if(pg===1){d.push(quick('🌐 网页版','x5://'+seed));d.push(quick('🔍 搜索',route('shtSearch')));d.push(line());d.push(section(name,'当前页 '+r.items.length+' 条主题 · '+r.items.filter(function(x){return !!x.img}).length+' 条带预览图'))}
    for(i=0;i<r.items.length;i++){item=r.items[i];img=item.img?imageUrl(item.img,r.url):'';d.push({title:item.title,desc:'查看帖子',img:img,pic_url:img,url:route('shtThread',{sht_url:item.url,sht_name:item.title}),col_type:img?'movie_1':'text_1',extra:{lineVisible:false}})}setResult(d)}
  function extractFloorImages(body,base){return imageCandidates(body,base)}
  function plainBodyHtml(x){x=s(x).replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<iframe[\s\S]*?<\/iframe>/gi,'').replace(/<img\b[^>]*>/gi,'');x=x.replace(/<div[^>]*class=["'][^"']*(?:sign|signature)[^"']*["'][^>]*>[\s\S]*?<\/div>/gi,'').replace(/<div class=["']xs0["'][\s\S]*?<\/div>/gi,'').replace(/<p class=["']mbn["'][\s\S]*?<\/p>/gi,'').replace(/<div class=["']tip tip_4["'][\s\S]*?<\/div>/gi,'');x=x.replace(/<[^>]*>[^<]*本帖最后由[\s\S]*?编辑[^<]*<\/[^>]+>/gi,'');x=x.replace(/(<br\s*\/?\s*>\s*){3,}/gi,'<br><br>');return x}
  function magnetList(x){var t=hdec(s(x)),out=[],seen={},m,re=/magnet:\?xt=urn:btih:[a-z0-9]{32,40}(?:&[^\s"'<>]*)?/ig,v,hm,key;while((m=re.exec(t))!==null){v=m[0].replace(/[)\]}>，。；;]+$/g,'');hm=v.match(/btih:([a-z0-9]{32,40})/i);key=hm?hm[1].toUpperCase():v.toLowerCase();if(!seen[key]){seen[key]=1;out.push({url:v,key:key,hash:hm?hm[1]:''})}if(out.length>=20)break}return out}
  function videoUrls(x){var out=[],seen={},m,re=/(https?:\/\/[^\s"'<>]+?\.(?:m3u8|mp4)(?:\?[^\s"'<>]*)?)/ig,u;while((m=re.exec(hdec(s(x))))!==null){u=m[1].replace(/[)\]}>，。；;]+$/g,'');if(!seen[u]){seen[u]=1;out.push(u)}if(out.length>=6)break}return out}
  function sniffSeed(x,base){var m=s(x).match(/<iframe\b[^>]*(?:src|data-src)\s*=\s*["']([^"']+)["']/i),u=m?abs(m[1],base):'';return u||base}
  function pcThreadUrl(u){u=s(u);if(/[?&]mobile=2/i.test(u))u=u.replace(/([?&])mobile=2(&|$)/i,function(_,p,q){return q?p+'mobile=no'+q:''});else if(u.indexOf('?')>=0)u+='&mobile=no';else if(/\.html(?:#|$)/i.test(u))u+='?mobile=no';return u}
  function threadHtml(u){var p=pcThreadUrl(u),h=fetchPage(p);return{html:h,url:p}}
  function replyUrl(html,base){var m=s(html).match(/href=["']([^"']*(?:mod=post[^"']*action=reply|action=reply[^"']*mod=post)[^"']*)["']/i);return m?abs(m[1],base):base}
  function cleanMagnetsFromHtml(x,hasNew){x=s(x);if(hasNew){x=x.replace(/<a\b[^>]*href\s*=\s*["']magnet:[^"']*["'][^>]*>[\s\S]*?<\/a>/gi,'').replace(/magnet:\?xt=urn:btih:[a-z0-9]{32,40}(?:&[^\s"'<>]*)?/ig,'');x='<b>【磁链已识别，云播入口见正文下方】</b><br>'+x}return x}
  function thread(){var d=[],url=pageParam('sht_url',''),title=pageParam('sht_name','帖子详情'),r,html,nodes=[],i,body,author,allMs,ms=[],j,valid=0,videos=[],videoHint=false,seenThreadMagnet={},seed,imgs=[],bodyHtml,ref;if(!url){BASE.module().thread();return}setPageTitle(title||'帖子详情');r=threadHtml(url);html=r.html;ref=r.url||url;saveDiag('thread.v8',(html?html.length:0)+'字');d.push(section(title||'帖子详情','原帖 / 回复 / 正文图片 / 磁链云播 / 视频嗅探'));d.push(quick('🌐 原帖','x5://'+url));d.push(quick('💬 回复','x5://'+replyUrl(html,ref)));d.push({title:'🔗 复制链接',img:LOGO,pic_url:LOGO,url:'copy://'+url,col_type:'icon_small_4'});d.push(quick('⚙️ 设置',route('shtSettings')));d.push(line());try{nodes=pdfa(html,'body&&#postlist>div')||[]}catch(e){nodes=[]}if(!nodes.length){BASE.module().thread();return}
    for(i=0;i<nodes.length&&valid<20;i++){try{body=pdfh(nodes[i],'body&&div.t_fsz&&Html')||pdfh(nodes[i],'body&&div.t_f&&Html')||''}catch(e2){body=''}if(!trim(strip(body)))continue;try{author=trim(pdfh(nodes[i],'body&&.authi&&a&&Text')||pdfh(nodes[i],'body&&.xw1&&Text')||'')}catch(e3){author=''}allMs=magnetList(body);ms=[];for(j=0;j<allMs.length;j++)if(!seenThreadMagnet[allMs[j].key]){seenThreadMagnet[allMs[j].key]=1;ms.push(allMs[j])}videos=videoUrls(body);videoHint=videos.length>0||/<video\b|<iframe\b|视频加载中|在线播放|dplayer|ckplayer|jwplayer|m3u8|\.mp4/i.test(body);seed=sniffSeed(body,ref);imgs=extractFloorImages(body,ref);valid++;d.push(section(valid===1?'楼主'+(author?' · '+author:''):'回复 '+(valid-1)+(author?' · '+author:''),[imgs.length?imgs.length+' 张图片':'',ms.length?ms.length+' 条磁链':'',videoHint?'检测到视频内容':''].filter(Boolean).join(' · ')));
      if(videos.length)d.push({title:'▶ 直接播放',desc:'已识别视频直链',url:videos[0]+'#isVideo=true#',col_type:'text_center_1',extra:{lineVisible:false}});if(videoHint)d.push({title:'▶ 嗅探播放',desc:'使用海阔自动提取网页视频',url:'video://'+seed,col_type:'text_center_1',extra:{lineVisible:false,ua:UA_M,referer:url,blockRules:['.jpg','.png','.gif','.woff','.woff2','.ttf'],cacheM3u8:true}});
      bodyHtml=plainBodyHtml(body);bodyHtml=cleanMagnetsFromHtml(bodyHtml,ms.length>0);if(trim(strip(bodyHtml)))d.push({title:bodyHtml,url:'hiker://empty',col_type:'rich_text',extra:{lineVisible:false}});
      for(j=0;j<imgs.length;j++){var pu=imageUrl(imgs[j],ref);d.push({title:'',desc:'',img:pu,pic_url:pu,url:'pics://'+pu,col_type:'pic_1_full',extra:{lineVisible:false,imgLongClick:true}})}
      for(j=0;j<ms.length;j++){var magnet=ms[j].url,hash=ms[j].hash;d.push({title:'磁链 '+(j+1),desc:hash?hash.slice(0,14)+'…':'已识别',url:'copy://'+magnet,col_type:'text_1',extra:{lineVisible:false}});d.push({title:'115',img:LOGO,pic_url:LOGO,url:'hiker://page/115Offline?rule=115.简&page=fypage&add='+encodeURIComponent(magnet),col_type:'icon_small_4'});d.push({title:'迅雷',img:LOGO,pic_url:LOGO,url:'hiker://page/diaoyong?rule=迅雷&page=fypage#'+magnet,col_type:'icon_small_4'});d.push({title:'PikPak',img:LOGO,pic_url:LOGO,url:'pikpakapp://mypikpak.com/xpan/main_tab?tab=1&add_url='+magnet,col_type:'icon_small_4'});d.push({title:'复制',img:LOGO,pic_url:LOGO,url:'copy://'+magnet,col_type:'icon_small_4'})}d.push(line())}setResult(d)}
  function settings(){var d=[],dg={};setPageTitle('色花堂设置');d.push(section('Test8 图片与分类增强','子板块按一级板块页面重新解析；主题缩略图从整行上下文提取；正文图片改为原生 pic_1_full 渲染'));d.push({title:'清空 Test8 分类缓存',desc:'分类仍缺失时先点这里，再返回首页重新读取',url:$('#noLoading#').lazyRule(function(k){setItem(k,'{}');refreshPage(false);return'toast://Test8 分类缓存已清空';},KEY_GROUP_CACHE),col_type:'text_1'});try{dg=JSON.parse(getItem(KEY_DIAG,'{}')||'{}')}catch(e){}d.push({title:'最近诊断',desc:(dg.stage||'暂无')+'\n'+(dg.error||''),url:'hiker://empty',col_type:'long_text'});d.push({title:'打开旧设置',desc:'访问状态 / Cookie / 旧分类缓存等兼容入口',url:route('shtSettingsLegacy'),col_type:'text_1'});setResult(d)}
  function module(){var m=BASE.module();m.version=VERSION;m.build=BUILD;m.home=home;m.forum=forum;m.thread=thread;m.settings=settings;m._debug=m._debug||{};m._debug.resolveGroupsV8=resolveGroups;m._debug.parseThreadsV8=parseThreads;return m}
  var PATCHED={version:VERSION,build:BUILD,module:module};SeHuaTangRemoteRuntime=PATCHED;return PATCHED;
})();
