/* 麻豆AI 2.9.0-test.1 - Detail + same-page Community tabs */
var MDAIDetailV290=(function(){
  var U=MDAIUIV290,D=U.design;
  function tabKey(type,id){return'mdai_detail_tab_v290_'+type+'_'+id;}
  function favAction(c,d,info){var on=c.isFav(info.id,info.type);d.push({title:on?'已收藏':'收藏到我的',desc:'本地收藏 · 不需要账号',url:$('#noLoading#').lazyRule(function(i){var x=$.require('mdai').toggleFav(i);refreshPage(false);return'toast://'+(x?'已加入收藏':'已取消收藏');},info),col_type:'text_1',extra:{lineVisible:false}});}
  function commentsPreview(c,community,d,target,id,title,cover){var list=[];try{list=community.list(c,target,id,1,8);}catch(e){d.push(U.empty('评论暂时加载失败',String(e.message||e)));return;}if(!list.length){d.push(U.empty('暂时没有评论','评论区为空或接口暂未返回内容'));return;}var items=community.render(c,list);for(var i=0;i<items.length;i++)d.push(items[i]);d.push({title:'查看全部评论  ›',desc:'继续浏览更多评论',url:U.page('mdaiComments',{target:target,id:id,title:title,cover:cover}),col_type:'text_1',extra:{lineVisible:false}});}
  function related(c,d,x,id,type){if(getItem('mdai_related','1')!=='1')return;try{var rel=[];if(type==='drama')rel=c.items(c.request('/api/v1/short-dramas?productId=1&sortBy=heat&page=1&size=9'));else if(type==='video'&&x.categoryId!=null)rel=c.items(c.request('/api/v1/videos?categoryId='+U.enc(x.categoryId)+'&page=1&size=9'));rel=rel.filter(function(z){return String(U.id(z))!==String(id);}).slice(0,6);if(rel.length){d.push(U.line());d.push(U.section(c,'猜你喜欢','相关内容'));for(var i=0;i<rel.length;i++)d.push(U.card(c,rel[i],type,type==='drama'?'movie_3':'movie_2'));}}catch(e){} }
  function video(c,pb,community,d,id,fallback,type){var path=type==='drama'?'/api/v1/short-dramas/'+U.enc(id)+'?productId=1':'/api/v1/videos/'+U.enc(id),x=c.payload(c.request(path))||{},title=c.cleanText(x.title||fallback||'详情'),isDrama=type==='drama'||Array.isArray(x.episodes),cv=U.cover(c,x),meta=U.meta(c,x,isDrama?'drama':'video'),info={id:id,type:isDrama?'drama':'video',title:title,cover:cv,desc:meta};setPageTitle(c.shortTitle(title,16));c.saveHistory(info);
    var eps=Array.isArray(x.episodes)?x.episodes.slice():[],lastKey='mdai_last_ep_no_'+id,lastNo=isDrama?parseInt(getItem(lastKey,'-1')):-1;
    if(isDrama)d.push(U.hero(c,x,'drama'));else d.push({title:title,desc:meta,img:cv,pic_url:cv,url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});
    if(isDrama&&eps.length){var target=eps[0];if(lastNo>0){for(var z=0;z<eps.length;z++){var nn=eps[z].episodeNo!=null?parseInt(eps[z].episodeNo):(z+1);if(nn===lastNo){target=eps[z];break;}}}var no=target.episodeNo!=null?target.episodeNo:1,ss=U.seed(target);d.push({title:lastNo>0?'继续第 '+no+' 集':'从第 1 集开始',url:$('#noLoading#').lazyRule(function(s,k,n){setItem(k,String(n));return $.require('mdai').play(s);},ss,lastKey,no),col_type:'text_center_1',extra:{backgroundColor:D.brandSoft,lineVisible:false}});}else{var vs=U.seed(x);if(pb.collect(c,vs).length)d.push({title:'立即播放',url:$('#noLoading#').lazyRule(function(s){return $.require('mdai').play(s);},vs),col_type:'text_center_1',extra:{backgroundColor:D.brandSoft,lineVisible:false}});}
    d.push(U.line());var key=tabKey(isDrama?'drama':'video',id),def=isDrama?'episodes':'intro',tab=getMyVar(key,def)||def;if(isDrama){d.push(U.chip('选集',tab==='episodes',U.stateUrl(key,'episodes'),'text_2'));d.push(U.chip('简介',tab==='intro',U.stateUrl(key,'intro'),'text_2'));}else{d.push(U.chip('简介',tab==='intro',U.stateUrl(key,'intro'),'text_2'));d.push(U.chip('评论',tab==='comments',U.stateUrl(key,'comments'),'text_2'));}d.push(U.line());
    if(tab==='comments'&&!isDrama){d.push(U.section(c,'评论区','只读浏览 · 无需账号'));commentsPreview(c,community,d,'video',id,title,cv);setResult(d);return;}
    if(tab==='episodes'&&isDrama){var reverse=getItem('mdai_episode_reverse','0')==='1';if(reverse)eps.reverse();var total=eps.length,rs=parseInt(getItem('mdai_episode_range','40'))||40;if(rs<20)rs=20;if(rs>60)rs=60,count=Math.ceil(total/rs),rk='mdai_ep_range_v290_'+id,sel=parseInt(getMyVar(rk,'0'))||0;if(sel<0||sel>=count)sel=0;d.push({title:'选集 · 共 '+total+' 集',desc:reverse?'当前倒序':'当前正序',url:$('#noLoading#').lazyRule(function(){var n=getItem('mdai_episode_reverse','0')==='1'?'0':'1';setItem('mdai_episode_reverse',n);refreshPage(false);return'hiker://empty';}),col_type:'text_1',extra:{lineVisible:false}});if(count>1){for(var r=0;r<count;r++){var a=r*rs+1,b=Math.min((r+1)*rs,total);d.push(U.chip(a+'-'+b,r===sel,U.stateUrl(rk,String(r)),'flex_button'));}d.push(U.blank());}var begin=sel*rs,end=Math.min(begin+rs,total);for(var i=begin;i<end;i++){var e=eps[i]||{},real=e.episodeNo!=null?parseInt(e.episodeNo):(reverse?(total-i):(i+1)),watched=lastNo>0&&real===lastNo,es=U.seed(e);d.push({title:watched?'▶ '+real:String(real),url:$().lazyRule(function(s,k,n){setItem(k,String(n));return $.require('mdai').play(s);},es,lastKey,real),col_type:'text_4',extra:{backgroundColor:watched?D.brandSoft:'',lineVisible:false}});}d.push(U.line());favAction(c,d,info);related(c,d,x,id,'drama');setResult(d);return;}
    var intro=c.cleanText(x.description||x.intro||x.summary||'');d.push(U.section(c,'剧情简介',meta));if(intro)d.push({title:intro,url:'hiker://empty',col_type:'long_text',extra:{textSize:17,lineVisible:false}});else d.push(U.empty('暂无简介'));d.push(U.line());favAction(c,d,info);related(c,d,x,id,isDrama?'drama':'video');setResult(d);
  }
  function post(c,pb,community,d,id,fallback){var p=c.payload(c.request('/api/v1/posts/'+U.enc(id)))||{},title=c.cleanText(p.title||fallback||'帖子详情'),cv=U.cover(c,p),meta=U.meta(c,p,'post'),info={id:id,type:'post',title:title,cover:cv,desc:meta};setPageTitle(c.shortTitle(title,16));c.saveHistory(info);d.push({title:title,desc:meta,img:cv,pic_url:cv,url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});var ps=U.seed(p);if(pb.collect(c,ps).length)d.push({title:'播放帖子视频',url:$('#noLoading#').lazyRule(function(s){return $.require('mdai').play(s);},ps),col_type:'text_center_1',extra:{backgroundColor:D.brandSoft,lineVisible:false}});d.push(U.line());var key=tabKey('post',id),tab=getMyVar(key,'body')||'body';d.push(U.chip('正文',tab==='body',U.stateUrl(key,'body'),'text_2'));d.push(U.chip('评论',tab==='comments',U.stateUrl(key,'comments'),'text_2'));d.push(U.line());if(tab==='comments'){d.push(U.section(c,'评论区','只读浏览 · 无需账号'));commentsPreview(c,community,d,'post',id,title,cv);setResult(d);return;}var body=c.cleanText(p.content||p.description||'');if(body)d.push({title:body,col_type:'long_text',extra:{textSize:17,lineVisible:false}});var imgs=Array.isArray(p.images)?p.images:[];for(var i=0;i<imgs.length;i++){var iu=c.image(imgs[i]);if(iu)d.push({img:iu,pic_url:iu,url:iu+'#.jpg#',col_type:'pic_1_full',extra:{lineVisible:false}});}d.push(U.line());favAction(c,d,info);setResult(d);}
  function detail(c,pb,community){var d=[],id=String(U.qp('id','')||''),type=String(U.qp('type','video')||'video'),fallback=String(U.qp('title','')||'');if(!id){setResult([U.empty('详情参数缺失','请返回上一页重新打开')]);return;}try{if(type==='post')return post(c,pb,community,d,id,fallback);return video(c,pb,community,d,id,fallback,type);}catch(e){d.push(U.empty('详情加载失败',String(e.message||e)));d.push({title:'重试',url:$('#noLoading#').lazyRule(function(){refreshPage(false);return'hiker://empty';}),col_type:'text_center_1'});setResult(d);}}
  function comments(c,community){var d=[],pg=MY_PAGE||1,target=String(U.qp('target','video')||'video'),id=String(U.qp('id','')||''),title=String(U.qp('title','评论')||'评论'),cover=String(U.qp('cover','')||'');if(pg===1){setPageTitle(c.shortTitle(title,14)+' · 评论');if(cover)d.push({title:title,desc:'只读评论区 · 无需账号',img:cover,pic_url:cover,url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});else d.push(U.section(c,'评论区',title));d.push(U.line());}try{var list=community.list(c,target,id,pg,20),items=community.render(c,list);for(var i=0;i<items.length;i++)d.push(items[i]);if(!list.length&&pg===1)d.push(U.empty('暂时没有评论'));}catch(e){if(pg===1)d.push(U.empty('评论加载失败',String(e.message||e)));}setResult(d);}
  return{version:'2.9.0-test.1',detail:detail,comments:comments};
})();
