/* 麻豆AI 2.9.0-test.1 - Search State Machine / Mine */
var MDAISearchMineV290=(function(){
  var U=MDAIUIV290,SEARCH='mdai_search_kw_v290',MINE='mdai_mine_tab_v290';
  function setWord(c,w){w=String(w||'').trim();if(!w)return;putMyVar(SEARCH,w);c.saveSearchWord(w);}
  function searchInput(d,c,kw){d.push({title:'搜索视频',col_type:'input',url:$.toString(function(){var w=String(input||'').trim();if(!w)return'toast://请输入关键词';putMyVar('mdai_search_kw_v290',w);try{$.require('mdai').saveSearchWord(w);}catch(e){}refreshPage(false);return'hiker://empty';}),extra:{defaultValue:kw||'',titleVisible:true,onChange:$.toString(function(){})}});}
  function idle(c,d){var hot=[];try{var h=c.payload(c.request('/api/v1/hot-searches?period=recent'));if(Array.isArray(h))hot=h;}catch(e){}if(hot.length){d.push(U.section(c,'热门搜索','官方近期热度'));for(var i=0;i<Math.min(8,hot.length);i++){var x=hot[i]||{},w=c.cleanText(x.name||'');if(!w)continue;d.push(U.chip(w+(x.heat?' · '+x.heat:''),false,$('#noLoading#').lazyRule(function(v){putMyVar('mdai_search_kw_v290',v);try{$.require('mdai').saveSearchWord(v);}catch(e){}refreshPage(false);return'hiker://empty';},w),'flex_button'));}d.push(U.line());}
    var his=c.readList(c.searchKey);if(his.length){d.push(U.section(c,'最近搜索','本地记录'));for(var j=0;j<his.length;j++)d.push(U.chip(c.maskText(his[j]),false,$('#noLoading#').lazyRule(function(v){putMyVar('mdai_search_kw_v290',v);refreshPage(false);return'hiker://empty';},String(his[j])),'flex_button'));d.push({title:'清空搜索记录',url:$('#noLoading#').lazyRule(function(k){setItem(k,'[]');refreshPage(false);return'toast://搜索记录已清空';},c.searchKey),col_type:'text_1',extra:{lineVisible:false}});}
    if(!hot.length&&!his.length)d.push(U.empty('搜索你想看的内容','输入片名或关键词开始搜索'));}
  function search(c){var d=[],pg=MY_PAGE||1,qp=U.qp('kw','');if(qp)setWord(c,qp);var kw=String(getMyVar(SEARCH,'')||'').trim();try{if(pg===1){setPageTitle('搜索');searchInput(d,c,kw);}if(!kw){if(pg===1)idle(c,d);setResult(d);return;}if(pg===1){d.push(U.section(c,'搜索结果','关键词：'+c.maskText(kw)));d.push({title:'清除关键词',url:$('#noLoading#').lazyRule(function(){clearMyVar('mdai_search_kw_v290');refreshPage(false);return'hiker://empty';}),col_type:'text_1',extra:{lineVisible:false}});}var list=c.items(c.request('/api/v1/videos/search?q='+encodeURIComponent(kw)+'&page='+pg+'&size='+c.pageSize()));for(var i=0;i<list.length;i++)d.push(U.card(c,list[i],'video','movie_2'));if(!list.length&&pg===1)d.push(U.empty('没有搜索到相关视频','可以换一个关键词试试'));}catch(e){d.push(U.empty('搜索失败',String(e.message||e)));}setResult(d);}
  function mine(c){var d=[],pg=MY_PAGE||1;try{var q=U.qp('mode','');if(q==='favorites'||q==='history')putMyVar(MINE,q);var tab=getMyVar(MINE,'favorites')||'favorites';if(pg===1){setPageTitle('我的');d.push(U.section(c,'我的内容','收藏与观看历史'));d.push(U.chip('收藏',tab==='favorites',U.stateUrl(MINE,'favorites'),'text_2'));d.push(U.chip('历史',tab==='history',U.stateUrl(MINE,'history'),'text_2'));d.push(U.line());}if(pg>1){setResult(d);return;}var a=c.readList(tab==='favorites'?c.favKey:c.historyKey);if(!a.length){d.push(U.empty(tab==='favorites'?'还没有收藏':'还没有观看记录',tab==='favorites'?'在详情页可以加入本地收藏':'播放过的内容会出现在这里'));}else{for(var i=0;i<a.length;i++)d.push(U.localCard(c,a[i]));if(tab==='history')d.push({title:'清空观看历史',url:$('#noLoading#').lazyRule(function(k){setItem(k,'[]');refreshPage(false);return'toast://观看历史已清空';},c.historyKey),col_type:'text_1',extra:{lineVisible:false}});}}catch(e){d.push(U.empty('加载失败',String(e.message||e)));}setResult(d);}
  return{version:'2.9.0-test.1',search:search,mine:mine};
})();
