/* 麻豆AI 2.9.0-test.1 - Catalog / Library */
var MDAILibraryV290=(function(){
  var U=MDAIUIV290,KEY={type:'mdai_library_type_v290',menu:'mdai_library_menu_v290',cat:'mdai_library_cat_v290',expand:'mdai_library_expand_v290',filters:'mdai_library_filters_v290',dramaSort:'mdai_library_drama_sort_v290'};
  var KNOWN=[{id:27,name:'每日更新',menuId:1,o:1},{id:10,name:'联合原创',menuId:1,o:2},{id:13,name:'清纯少女',menuId:1,o:3},{id:6,name:'麻豆原创 AI',menuId:1,o:4},{id:19,name:'黑料吃瓜',menuId:1,o:5},{id:14,name:'重口调教',menuId:1,o:6},{id:15,name:'直播大秀',menuId:1,o:7},{id:16,name:'网红主播',menuId:1,o:8},{id:9,name:'麻豆传媒',menuId:1,o:9},{id:17,name:'媚黑母狗',menuId:1,o:10},{id:18,name:'白虎少女',menuId:1,o:11},{id:1,name:'国产最新',menuId:2,o:1},{id:21,name:'反差母狗',menuId:2,o:2},{id:4,name:'探花大神',menuId:2,o:3},{id:7,name:'91大神',menuId:2,o:4},{id:20,name:'破解偷拍',menuId:2,o:5},{id:28,name:'世界杯专栏',menuId:2,o:6},{id:22,name:'白虎嫩妹',menuId:2,o:7},{id:23,name:'家庭乱伦',menuId:2,o:8},{id:24,name:'熟女偷情',menuId:2,o:9},{id:25,name:'网黄原创',menuId:2,o:10},{id:2,name:'中文字幕',menuId:3,o:1},{id:8,name:'无码流出',menuId:3,o:2}];
  function menuName(m){return String(m)==='2'?'国产':(String(m)==='3'?'字幕':'原创');}
  function cats(c,m){var map={},i,x,id;for(i=0;i<KNOWN.length;i++){x=KNOWN[i];map[String(x.id)]={id:x.id,name:x.name,menuId:x.menuId,o:x.o,enabled:true};}var r=[];try{r=c.getCategories('video')||[];}catch(e){}for(i=0;i<r.length;i++){x=r[i]||{};id=String(x.id==null?'':x.id);if(!id)continue;if(map[id]){if(x.name)map[id].name=x.name;if(x.enabled===false)map[id].enabled=false;}else{var mm=parseInt(x.menuId||0);if(mm>=1&&mm<=3)map[id]={id:x.id,name:x.name||('分类 '+id),menuId:mm,o:1000+parseInt(x.sortOrder||0),enabled:x.enabled!==false};}}
    var out=[];Object.keys(map).forEach(function(k){var q=map[k];if(String(q.menuId)===String(m)&&q.enabled!==false)out.push(q);});out.sort(function(a,b){return a.o-b.o;});return out;}
  function set(k,v,clearCat){return $('#noLoading#').lazyRule(function(key,val,cc){if(val==='')clearMyVar(key);else putMyVar(key,val);if(cc){clearMyVar('mdai_library_cat_v290');clearMyVar('mdai_library_expand_v290');}refreshPage(false);return'hiker://empty';},k,String(v),clearCat?1:0);}
  function applyQuery(){try{var t=getParam('type');if(t==='video'||t==='drama')putMyVar(KEY.type,t);var m=getParam('menu');if(m)putMyVar(KEY.menu,String(m));var cat=getParam('cat');if(cat)putMyVar(KEY.cat,String(cat));}catch(e){}}
  function library(c){applyQuery();var d=[],pg=MY_PAGE||1,type=getMyVar(KEY.type,'video')||'video';try{if(pg===1){setPageTitle('片库');d.push(U.section(c,'内容片库','按类型与分类浏览'));d.push(U.chip('视频',type==='video',set(KEY.type,'video',0),'text_2'));d.push(U.chip('短剧',type==='drama',set(KEY.type,'drama',0),'text_2'));d.push(U.line());}
    if(type==='drama'){var ds=getMyVar(KEY.dramaSort,'heat')||'heat';if(pg===1){d.push(U.section(c,'短剧排序',ds==='heat'?'当前：热播':'当前：最新'));d.push(U.chip('热播',ds==='heat',set(KEY.dramaSort,'heat',0),'text_2'));d.push(U.chip('最新',ds==='latest',set(KEY.dramaSort,'latest',0),'text_2'));d.push(U.line());}var dl=c.items(c.request('/api/v1/short-dramas?productId=1&sortBy='+U.enc(ds)+'&page='+pg+'&size='+Math.min(c.pageSize(),30)));for(var di=0;di<dl.length;di++)d.push(U.card(c,dl[di],'drama','movie_3'));if(!dl.length&&pg===1)d.push(U.empty('暂无短剧数据'));setResult(d);return;}
    var menu=getMyVar(KEY.menu,'1')||'1',cat=getMyVar(KEY.cat,''),all=cats(c,menu),sel=null;for(var ci=0;ci<all.length;ci++)if(String(all[ci].id)===String(cat)){sel=all[ci];break;}if(cat&&!sel){clearMyVar(KEY.cat);cat='';}
    if(pg===1){d.push(U.section(c,'视频分类',menuName(menu)+(sel?' · '+c.maskText(sel.name):'')));d.push(U.chip('原创',menu==='1',set(KEY.menu,'1',1),'text_3'));d.push(U.chip('国产',menu==='2',set(KEY.menu,'2',1),'text_3'));d.push(U.chip('字幕',menu==='3',set(KEY.menu,'3',1),'text_3'));d.push(U.blank());var exp=getMyVar(KEY.expand,'0')==='1',lim=exp?all.length:Math.min(6,all.length);d.push(U.chip('全部',!cat,set(KEY.cat,'',0),'flex_button'));for(var i=0;i<lim;i++)d.push(U.chip(c.maskText(all[i].name),String(cat)===String(all[i].id),set(KEY.cat,String(all[i].id),0),'flex_button'));if(all.length>6)d.push(U.chip(exp?'收起':'更多分类 · '+all.length,exp,U.stateUrl(KEY.expand,exp?'0':'1'),'flex_button'));d.push(U.line());
      var fp=getMyVar(KEY.filters,'0')==='1',ft=getMyVar('mdai_filter_time',''),fd=getMyVar('mdai_filter_duration',''),fs=getMyVar('mdai_filter_sort',''),sum=[ft==='1m'?'近1月':'',fd==='20'?'20分+':'',fs==='likes'?'点赞优先':''].filter(Boolean).join(' · ');d.push({title:'筛选与排序  ›',desc:sum||'默认',url:U.stateUrl(KEY.filters,fp?'0':'1'),col_type:'text_1',extra:{lineVisible:false}});if(fp){var any=!!(ft||fd||fs);d.push(U.chip('默认',!any,$('#noLoading#').lazyRule(function(){clearMyVar('mdai_filter_time');clearMyVar('mdai_filter_duration');clearMyVar('mdai_filter_sort');refreshPage(false);return'hiker://empty';}),'text_4'));d.push(U.chip('近1月',ft==='1m',U.toggleUrl('mdai_filter_time','1m'),'text_4'));d.push(U.chip('20分+',fd==='20',U.toggleUrl('mdai_filter_duration','20'),'text_4'));d.push(U.chip('点赞优先',fs==='likes',U.toggleUrl('mdai_filter_sort','likes'),'text_4'));}d.push(U.line());d.push(U.section(c,'内容结果',sel?c.maskText(sel.name):(menuName(menu)+' · 全部')));}
    var vl=c.items(c.request(c.buildVideoPath(cat,pg,c.pageSize(),true)));for(var vi=0;vi<vl.length;vi++)d.push(U.card(c,vl[vi],'video','movie_2'));if(!vl.length&&pg===1)d.push(U.empty('暂无视频数据','可以尝试清除筛选或切换分类'));
  }catch(e){d.push(U.empty('片库加载失败',String(e.message||e)));}setResult(d);}
  return{version:'2.9.0-test.1',library:library};
})();
