/* Hanime1 2.0.0-test.1 UI: Library/Playlist/Cache/Settings */
(function(E,C,P){
var route=E._route,param=E._param,section=E._section,button=E._button,input=E._input,item=E._videoItem,safe=E._safe;
E.renderLibrary=function(d){var active=C.activeAccount();if(!active){d.push(section('片库','登录并同步账号后，可读取官网稍后看、收藏、片单、订阅与历史。'));d.push(button('登录账号',route('hanimeLogin',{}),'text_center_1'));return;}var lib=P.library(),tabs=[['稍后看','watchLater'],['收藏','favorites'],['片单','playlists'],['订阅','subscriptions'],['历史','history']],cur=getMyVar('hanime2_libtab','watchLater');tabs.forEach(function(x){d.push({title:(cur===x[1]?'● ':'')+x[0],url:$('#noLoading#').lazyRule(function(v){putMyVar('hanime2_libtab',v);refreshPage(false);return 'hiker://empty';},x[1]),col_type:'scroll_button'});});if(cur==='playlists'){lib.playlists.forEach(function(p){d.push({title:p.title,desc:p.count||'',pic_url:p.img,url:route('hanimePlaylist',{id:p.id}),col_type:'movie_1_left_pic'});});return;}var list=lib[cur]||[];list.forEach(function(x){d.push(item(x));});if(!list.length)d.push(section('暂无内容','当前账号此栏目为空。'));};
E.playlistPage=function(){safe(function(){var id=param('id',''),p=P.playlist(id,'latest'),d=[];setPageTitle(p.title);d.push(section(p.title,p.desc||''));d.push(button('修改名称',input(p.title,'片单名称',"try{var m=$.require('hanime'),p=m.provider().playlist('"+id+"','latest');m.provider().updatePlaylist('"+id+"',input,p.desc||'',false);refreshPage(false);return 'toast://已修改';}catch(e){return 'toast://'+String(e.message||e);}")));d.push(button('删除片单','confirm://确认删除该片单？.js:'+$.toString(function(id){try{$.require('hanime').provider().updatePlaylist(id,'','',true);back(true);return 'toast://已删除';}catch(e){return 'toast://'+String(e.message||e);}},id)));p.items.forEach(function(x){d.push(item(x));});setResult(d);},'片单加载失败');};
E.playlistPicker=function(){safe(function(){var vid=param('id',''),lib=P.library(),d=[];setPageTitle('加入片单');d.push({title:'稍后看',url:$('#noLoading#').lazyRule(function(x){try{$.require('hanime').provider().saveToPlaylist(x,'save',true);back(false);return 'toast://已加入稍后看';}catch(e){return 'toast://'+String(e.message||e);}},vid),col_type:'text_1'});lib.playlists.forEach(function(pl){d.push({title:pl.title,desc:pl.count||'',url:$('#noLoading#').lazyRule(function(x,l){try{$.require('hanime').provider().saveToPlaylist(x,l,true);back(false);return 'toast://已加入片单';}catch(e){return 'toast://'+String(e.message||e);}},vid,pl.id),col_type:'text_1'});});var next=input('','片单说明（可留空)',"try{var n=getMyVar('hanime2_new_playlist_name','');if(!n)return 'toast://名称不能为空';$.require('hanime').provider().createPlaylist('"+vid+"',n,input);clearMyVar('hanime2_new_playlist_name');back(false);return 'toast://已创建';}catch(e){return 'toast://'+String(e.message||e);}");d.push({title:'新建片单',url:input('','新片单名称',"if(!input)return 'toast://名称不能为空';putMyVar('hanime2_new_playlist_name',input);return "+JSON.stringify(next)+";"),col_type:'text_1'});setResult(d);},'片单加载失败');};
E.renderCache=function(d){d.push(section('缓存','实际视频文件由海阔播放器与下载中心管理。'));d.push(button('打开下载中心','hiker://download','text_center_1'));d.push(button('观看历史','hiker://history?rule=Hanime1','text_center_1'));};
E.renderSettings=function(d){var st=C.state(),acc=C.activeAccount();d.push(section('账号',acc?(acc.name+(acc.email?' · '+acc.email:'')):'未使用已保存账号'));d.push(button(acc?'账号中心':'登录账号',route('hanimeAccount',{})));d.push(button('网页登录',route('hanimeLogin',{})));d.push(button('浏览器验证',route('hanimeVerify',{url:st.base})));d.push(section('网络','当前线路：'+st.base));d.push(button('重新检测线路',$('#noLoading#').lazyRule(function(){clearItem('hanime2_active_host');clearItem('hanime2_host_ts');try{var h=$.require('hanime').core().resolveHost(true);refreshPage(false);return 'toast://当前线路 '+h;}catch(e){return 'toast://'+String(e.message||e);}})));d.push(button('使用浏览器会话',$('#noLoading#').lazyRule(function(){$.require('hanime').core().useBrowserSession();refreshPage(false);return 'toast://已切换浏览器会话';})));d.push(section('测试版本','2.0.0-test.1 · Remote Test'));d.push(button('检查远程更新',$('#noLoading#').lazyRule(function(){try{var r=HanimeBoot.check();return 'toast://'+(r.hasUpdate?'发现新测试版 '+r.latest.version:'当前已是最新测试版');}catch(e){return 'toast://'+String(e.message||e);}})));d.push(button('更新测试版',$('#noLoading#').lazyRule(function(){try{var r=HanimeBoot.update();if(r.ok&&r.changed){refreshPage(false);return 'toast://已更新到 '+r.current.version;}return 'toast://'+(r.error||'暂无更新');}catch(e){return 'toast://'+String(e.message||e);}})));d.push(button('回退上一测试版',$('#noLoading#').lazyRule(function(){try{var r=HanimeBoot.rollback();if(r.ok){refreshPage(false);return 'toast://已回退 '+r.current.version;}return 'toast://'+r.error;}catch(e){return 'toast://'+String(e.message||e);}})));};
})(HanimePages,HanimeCore,HanimeProvider);
