/* Hanime1 2.0.0-test.1 UI: Auth/Account/Comments */
(function(E,C,P){
var route=E._route,param=E._param,section=E._section,button=E._button,input=E._input,safe=E._safe;
E.loginPage=function(){safe(function(){var base=C.resolveHost(false),d=[];setPageTitle('登录 Hanime1');d.push(section('网页登录','在下方官方页面完成登录；成功后点击“同步当前登录”。'));d.push(button('同步当前登录',$('#noLoading#').lazyRule(function(){try{var a=$.require('hanime').provider().syncBrowserAccount();back(true);return 'toast://已同步 '+a.name;}catch(e){return 'toast://'+String(e.message||e);}}),'text_center_1'));d.push({title:'',url:base+'/login',col_type:'x5_webview_single',desc:'list&&screen-150',extra:{ua:C.ua,canBack:true,showProgress:true}});setResult(d);},'登录页失败');};
E.verifyPage=function(){safe(function(){var url=param('url',C.resolveHost(false)),d=[];setPageTitle('浏览器验证');d.push(section('站点验证','测试版会先自动尝试 WebView 校验；若仍进入此页，请在下方完成站点要求的验证。'));d.push(button('检测验证状态',$('#noLoading#').lazyRule(function(u){try{var c=$.require('hanime').core(),r=c.get(u,{base:c.origin(u),verify:false});if(!c.challenge(r)){back(true);return 'toast://验证已通过';}return 'toast://仍需完成验证';}catch(e){return 'toast://'+String(e.message||e);}},url),'text_center_1'));d.push({title:'',url:url,col_type:'x5_webview_single',desc:'list&&screen-150',extra:{ua:C.ua,canBack:true,showProgress:true}});setResult(d);},'验证页失败');};
E.accountPage=function(){safe(function(){setPageTitle('账号中心');var d=[],active=C.activeAccount(),accounts=C.accounts();if(!active){d.push(section('未登录','先网页登录并同步 Cookie。'));d.push(button('登录',route('hanimeLogin',{}),'text_center_1'));}else{var p=P.profile();d.push({title:p.name,desc:[p.email,p.joined,'ID '+p.id].filter(Boolean).join('\n'),pic_url:p.avatar,url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false}});d.push(button('修改昵称',input(p.name,'新昵称',"try{var p=$.require('hanime').provider(),x=p.profile();p.updateProfile(input,x.email||'');refreshPage(false);return 'toast://资料已更新';}catch(e){return 'toast://'+String(e.message||e);}")));d.push(button('修改邮箱',input(p.email||'','新邮箱',"try{var p=$.require('hanime').provider(),x=p.profile();p.updateProfile(x.name||'',input);refreshPage(false);return 'toast://邮箱已更新';}catch(e){return 'toast://'+String(e.message||e);}")));d.push(button('修改密码',route('hanimePassword',{})));d.push(button('官网账号页面','x5://'+p.base+'/user/'+p.id+'/edit'));d.push(button('退出当前账号',$('#noLoading#').lazyRule(function(id){$.require('hanime').core().removeAccount(id);refreshPage(false);return 'toast://已退出当前账号';},active.id)));}d.push(section('已保存账号','多账号 Cookie 相互隔离；Cloudflare 验证 Cookie 单独复用。'));accounts.forEach(function(a){d.push({title:(active&&String(active.id)===String(a.id)?'● ':'')+a.name,desc:a.email||('ID '+a.id),pic_url:a.avatar||'',url:$('#noLoading#').lazyRule(function(id){$.require('hanime').core().activateAccount(id);refreshPage(false);return 'toast://已切换账号';},a.id),col_type:'avatar'});d.push({title:'移除 '+a.name,url:'confirm://确认移除此账号？.js:'+$.toString(function(id){$.require('hanime').core().removeAccount(id);refreshPage(false);return 'toast://已移除';},a.id),col_type:'text_1'});});d.push(button('添加其他账号',route('hanimeLogin',{}),'text_center_1'));setResult(d);},'账号中心失败');};
E.passwordPage=function(){safe(function(){setPageTitle('修改密码');var d=[],o=getMyVar('hanime2_pwd_old',''),n=getMyVar('hanime2_pwd_new',''),c=getMyVar('hanime2_pwd_confirm','');d.push(section('修改账号密码','密码只暂存在当前页面变量，提交后立即清除。'));d.push({title:'旧密码：'+(o?'已填写':'未填写'),url:input('','输入旧密码',"putMyVar('hanime2_pwd_old',input);refreshPage(false);return 'hiker://empty';"),col_type:'text_1'});d.push({title:'新密码：'+(n?'已填写':'未填写'),url:input('','输入新密码',"putMyVar('hanime2_pwd_new',input);refreshPage(false);return 'hiker://empty';"),col_type:'text_1'});d.push({title:'确认密码：'+(c?'已填写':'未填写'),url:input('','再次输入新密码',"putMyVar('hanime2_pwd_confirm',input);refreshPage(false);return 'hiker://empty';"),col_type:'text_1'});d.push({title:'提交修改',url:$('#noLoading#').lazyRule(function(){var o=getMyVar('hanime2_pwd_old',''),n=getMyVar('hanime2_pwd_new',''),c=getMyVar('hanime2_pwd_confirm','');if(!o||!n||!c)return 'toast://请完整填写三个密码项';if(n!==c)return 'toast://两次新密码不一致';try{$.require('hanime').provider().updatePassword(o,n,c);clearMyVar('hanime2_pwd_old');clearMyVar('hanime2_pwd_new');clearMyVar('hanime2_pwd_confirm');back(false);return 'toast://密码已修改';}catch(e){return 'toast://'+String(e.message||e);}}),col_type:'text_center_1'});setResult(d);},'修改密码失败');};
E.commentsPage=function(){safe(function(){var id=param('id',''),title=param('title','评论'),d=[],r=P.comments(id);setPageTitle(title+' · 评论');d.push({title:'发表评论',url:input('','输入评论内容',"if(!input)return 'toast://评论不能为空';try{$.require('hanime').provider().postComment('"+id+"',input);refreshPage(false);return 'toast://评论已发布';}catch(e){return 'toast://'+String(e.message||e);}"),col_type:'text_center_1'});r.items.forEach(function(c){d.push({title:c.user,desc:[c.content,c.time].filter(Boolean).join('\n'),pic_url:c.avatar||'',url:c.id?route('hanimeReplies',{id:c.id,user:c.user}):'hiker://empty',col_type:'avatar'});});if(!r.items.length)d.push(section('暂无评论'));setResult(d);},'评论加载失败');};
E.repliesPage=function(){safe(function(){var id=param('id',''),user=param('user','回复'),d=[],list=P.replies(id);setPageTitle(user+' · 回复');d.push({title:'回复此评论',url:input('','输入回复内容',"if(!input)return 'toast://回复不能为空';try{$.require('hanime').provider().replyComment('"+id+"',input);refreshPage(false);return 'toast://回复已发布';}catch(e){return 'toast://'+String(e.message||e);}"),col_type:'text_center_1'});list.forEach(function(x){d.push({title:x.user,desc:[x.content,x.time].filter(Boolean).join('\n'),url:'hiker://empty',col_type:'text_1'});});setResult(d);},'回复加载失败');};
E.provider=function(){return P;};E.core=function(){return C;};
})(HanimePages,HanimeCore,HanimeProvider);
