/* Hanime1 2.0.0-test.1 UI: Explore/Search/Video/Comic */
var HanimePages={build:HanimeCore.build};
(function(E,C,P){
function e(v){return encodeURIComponent(String(v==null?'':v));}
function route(p,o){var q=[];Object.keys(o||{}).forEach(function(k){if(o[k]!==undefined&&o[k]!==null&&String(o[k])!=='')q.push(e(k)+'='+e(o[k]));});return 'hiker://page/'+p+'?rule=&simple=true'+(q.length?'&'+q.join('&'):'');}
function param(k,d){try{var v=getParam(k);if(v!==undefined&&v!==null&&String(v)!=='')return String(v);}catch(x){}try{if(MY_PARAMS&&MY_PARAMS[k]!==undefined)return String(MY_PARAMS[k]);}catch(y){}return d||'';}
function section(t,s){return {title:t,desc:s||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}};}
function button(t,u,c){return {title:t,url:u,col_type:c||'text_3',extra:{lineVisible:false}};}
function input(v,h,js){return 'input://'+JSON.stringify({value:v||'',hint:h||'',js:js});}
function nav(d,t,id){var cur=getMyVar('hanime2_tab','explore');d.push({title:(cur===id?'● ':'')+t,url:$('#noLoading#').lazyRule(function(x){putMyVar('hanime2_tab',x);refreshPage(false);return 'hiker://empty';},id),col_type:'scroll_button'});}
function videoItem(v,c){return {title:v.title||'未命名',desc:[v.duration,v.views,v.rating,v.artist,v.upload].filter(Boolean).join(' · '),pic_url:v.img||v.cover||'',url:route('hanimeDetail',{id:v.id,title:v.title}),col_type:c||'movie_2',extra:{lineVisible:false}};}
function comicItem(v){return {title:v.title||'漫画',pic_url:v.img||v.cover||'',url:route('hanimeComicDetail',{id:v.id,title:v.title}),col_type:'movie_3',extra:{lineVisible:false}};}
function fail(x,t){var m=String(x&&x.message||x||'未知错误'),d=[];setPageTitle(t||'加载失败');if(m.indexOf('NEED_VERIFY|')===0){var a=m.split('|');d.push(section('需要浏览器验证','自动校验未完成，请完成一次站点验证后返回。'));d.push(button('打开验证页',route('hanimeVerify',{url:a[1]||C.resolveHost(false)}),'text_center_1'));}else d.push({title:t||'加载失败',desc:m,url:'hiker://empty',col_type:'text_center_1'});setResult(d);}
function safe(fn,t){try{fn();}catch(x){fail(x,t);}}
E.home=function(){safe(function(){setPageTitle('Hanime1 · Test');var d=[],page=Number(MY_PAGE||1);if(page===1){d.push({title:'搜索视频 / 作者',url:route('hanimeSearch',{}),col_type:'input',extra:{titleVisible:false,lineVisible:false}});nav(d,'探索','explore');nav(d,'片库','library');nav(d,'缓存','cache');nav(d,'设置','settings');d.push({col_type:'line_blank'});}var tab=getMyVar('hanime2_tab','explore');if(tab==='explore')E.renderExplore(d);else if(tab==='library')E.renderLibrary(d);else if(tab==='cache')E.renderCache(d);else E.renderSettings(d);setResult(d);},'Hanime1');};
E.renderExplore=function(d){var mode=getMyVar('hanime2_content','video');d.push({title:(mode==='video'?'● ':'')+'视频',url:$('#noLoading#').lazyRule(function(){putMyVar('hanime2_content','video');refreshPage(false);return 'hiker://empty';}),col_type:'scroll_button'});d.push({title:(mode==='comic'?'● ':'')+'漫画',url:$('#noLoading#').lazyRule(function(){putMyVar('hanime2_content','comic');refreshPage(false);return 'hiker://empty';}),col_type:'scroll_button'});d.push({title:'预告',url:route('hanimePreviews',{}),col_type:'scroll_button'});if(mode==='comic'){var ch=P.comicHome();d.push(section('热门漫画'));ch.hot.slice(0,12).forEach(function(x){d.push(comicItem(x));});d.push(section('最新漫画'));ch.latest.forEach(function(x){d.push(comicItem(x));});return;}var h=P.home();if(h.featured&&h.featured.id)d.push({title:h.featured.title,desc:h.featured.meta||'推荐',pic_url:h.featured.img,url:route('hanimeDetail',{id:h.featured.id}),col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false}});h.sections.forEach(function(s){d.push(section(s.title||'推荐'));s.items.slice(0,12).forEach(function(x){d.push(videoItem(x,'movie_3'));});});};
function filter(d,label,opts,key,cur){d.push(section(label));opts.forEach(function(o){d.push({title:(String(o[1])===String(cur)?'● ':'')+o[0],url:$('#noLoading#').lazyRule(function(k,v){putMyVar(k,v);refreshPage(false);return 'hiker://empty';},key,o[1]),col_type:'scroll_button'});});}
E.searchPage=function(){safe(function(){setPageTitle('搜索');var d=[],q=param('q',getMyVar('hanime2_search_q','')),page=Number(param('page',String(MY_PAGE||1))||1),genre=getMyVar('hanime2_search_genre',''),sort=getMyVar('hanime2_search_sort',''),date=getMyVar('hanime2_search_date',''),duration=getMyVar('hanime2_search_duration',''),type=getMyVar('hanime2_search_type','');d.push({title:'关键词：'+(q||'未输入'),url:input(q,'输入搜索关键词',"putMyVar('hanime2_search_q',input);refreshPage(false);return 'hiker://empty';"),col_type:'text_1'});filter(d,'类型',P.filters.types,'hanime2_search_type',type);filter(d,'分类',P.filters.genres,'hanime2_search_genre',genre);filter(d,'排序',P.filters.sorts,'hanime2_search_sort',sort);filter(d,'日期',P.filters.dates,'hanime2_search_date',date);filter(d,'时长',P.filters.durations,'hanime2_search_duration',duration);if(!q&&type!=='artist'){d.push(section('搜索提示','输入关键词后开始搜索。'));setResult(d);return;}var r=P.search({query:q,genre:genre,sort:sort,date:date,duration:duration,type:type,page:page});if(type==='artist'&&r.artists.length)r.artists.forEach(function(a){d.push({title:a.title,desc:a.meta||'作者',pic_url:a.img,url:$('#noLoading#').lazyRule(function(x){putMyVar('hanime2_search_q',x);putMyVar('hanime2_search_type','');refreshPage(false);return 'hiker://empty';},a.query),col_type:'avatar'});});else r.items.forEach(function(x){d.push(videoItem(x));});if(page<r.totalPages)d.push({title:'下一页 · '+(page+1)+' / '+r.totalPages,url:route('hanimeSearch',{page:page+1,q:q}),col_type:'text_center_1'});setResult(d);},'搜索失败');};
E.shellSearch=function(){var q='';try{q=getParam('kw')||(typeof KEY!=='undefined'?KEY:'')||'';}catch(x){}putMyVar('hanime2_search_q',String(q||''));E.searchPage();};
E.detail=function(){safe(function(){var id=param('id','');if(!id)throw new Error('缺少视频 ID');var v=P.video(id),d=[];setPageTitle(v.title);d.push({title:v.title,desc:[v.artist,v.genre,v.views,v.upload,v.duration].filter(Boolean).join('\n'),pic_url:v.cover,url:$('#noLoading#').lazyRule(function(x){return $.require('hanime').play(x);},id),col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false}});d.push(button('播放',$('#noLoading#').lazyRule(function(x){return $.require('hanime').play(x);},id)));d.push(button('稍后看',$('#noLoading#').lazyRule(function(x){try{$.require('hanime').provider().saveToPlaylist(x,'save',true);return 'toast://已加入稍后看';}catch(e){return 'toast://'+String(e.message||e);}},id)));d.push(button('收藏',$('#noLoading#').lazyRule(function(x){try{$.require('hanime').provider().setFavorite(x,true);return 'toast://已收藏';}catch(e){return 'toast://'+String(e.message||e);}},id)));d.push(button('加入片单',route('hanimePlaylistPicker',{id:id})));if(v.artistId)d.push(button('订阅作者',$('#noLoading#').lazyRule(function(x){try{var p=$.require('hanime').provider(),v=p.video(x);p.setSubscription(v,true);return 'toast://已订阅';}catch(e){return 'toast://'+String(e.message||e);}},id)));d.push(button('评论',route('hanimeComments',{id:id,title:v.title})));if(v.download)d.push(button('下载原片','download://'+v.download));if(v.caption)d.push(section('简介',v.caption));if(v.tags.length){d.push(section('标签'));v.tags.forEach(function(t){d.push({title:t.name,url:$('#noLoading#').lazyRule(function(q){putMyVar('hanime2_search_q',q);return 'hiker://page/hanimeSearch?rule=&simple=true';},t.name),col_type:'scroll_button'});});}if(v.related.length){d.push(section('相关推荐'));v.related.forEach(function(x){d.push(videoItem(x,'movie_3'));});}setResult(d);},'详情加载失败');};
E.play=function(id){try{return P.playModel(P.video(id));}catch(x){var m=String(x.message||x);if(m.indexOf('NEED_VERIFY|')===0)return route('hanimeVerify',{url:m.split('|')[1]||C.resolveHost(false)});return 'toast://播放解析失败：'+m;}};
E.previews=function(){safe(function(){setPageTitle('预告');var d=[],m=param('month','');if(!m){var n=new Date(),mo=String(n.getMonth()+1);if(mo.length<2)mo='0'+mo;m=n.getFullYear()+'-'+mo;}d.push({title:'月份：'+m,url:input(m,'YYYY-MM',"return '"+route('hanimePreviews',{})+"&month='+encodeURIComponent(input);"),col_type:'text_1'});P.previews(m).forEach(function(x){d.push({title:x.title,desc:[x.brand,x.desc].filter(Boolean).join('\n'),pic_url:x.img,url:'hiker://empty',col_type:'movie_2'});});setResult(d);},'预告加载失败');};
E.comicDetail=function(){safe(function(){var id=param('id',''),c=P.comicDetail(id),d=[];setPageTitle(c.title);d.push({title:c.title,desc:(c.desc||'')+'\n共 '+c.count+' 页',pic_url:c.cover,url:'pics://'+c.images.join('&&'),col_type:'movie_1_vertical_pic_blur'});d.push({title:'开始阅读',url:'pics://'+c.images.join('&&'),col_type:'text_center_1'});if(c.tags.length){d.push(section('作品信息'));c.tags.forEach(function(t){d.push({title:t.name,url:route('hanimeComicBrowse',{path:t.href}),col_type:'scroll_button'});});}setResult(d);},'漫画详情失败');};
E.comicBrowse=function(){safe(function(){var path=param('path','/comics'),page=Number(param('page',String(MY_PAGE||1))||1),r=P.comicBrowse(path,page),d=[];setPageTitle('漫画列表');r.items.forEach(function(x){d.push(comicItem(x));});if(page<r.totalPages)d.push({title:'下一页',url:route('hanimeComicBrowse',{path:path,page:page+1}),col_type:'text_center_1'});setResult(d);},'漫画列表失败');};
E._route=route;E._param=param;E._section=section;E._button=button;E._input=input;E._videoItem=videoItem;E._safe=safe;
})(HanimePages,HanimeCore,HanimeProvider);
