/* Hanime1 Remote Test 2.0.0-test.1 - Provider / Parser / Account */
var HanimeProvider=(function(){
  var C=HanimeCore;
  function nodes(html,sel){try{return pdfa(String(html||''),sel)||[];}catch(e){return [];}}
  function text(node,sel){try{return C.clean(pdfh(node,sel)||'');}catch(e){return '';}}
  function attr(node,sel){try{return String(pdfh(node,sel)||'').replace(/&amp;/g,'&').trim();}catch(e){return '';}}
  function firstText(node,sels){for(var i=0;i<sels.length;i++){var v=text(node,sels[i]);if(v)return v;}return '';}
  function firstAttr(node,sels){for(var i=0;i<sels.length;i++){var v=attr(node,sels[i]);if(v)return v;}return '';}
  function unique(list,key){var out=[],seen={};for(var i=0;i<list.length;i++){var x=list[i],k=String((key?key(x):x)||'');if(!k||seen[k])continue;seen[k]=1;out.push(x);}return out;}
  function assertResp(r,label){if(r&&r.challenge){var e=new Error('NEED_VERIFY|'+String(r.url||'')+'|'+(label||'站点'));e.code='NEED_VERIFY';e.url=r.url;throw e;}if(!r||Number(r.statusCode||0)>=400||!String(r.body||'')){throw new Error((label||'请求')+'失败：HTTP '+Number((r&&r.statusCode)||0));}return r;}
  function idFrom(u){var m=String(u||'').match(/[?&]v=(\d+)/);if(m)return m[1];m=String(u||'').match(/thumbnail\/(\d+)/);return m?m[1]:'';}
  function card(node,base){
    var href=firstAttr(node,['a.video-link&&href','a[href*=watch]&&href','a.overlay&&href','a&&href']);
    var img=firstAttr(node,['img.main-thumb&&src','img&&data-src','img&&src']);
    var title=firstText(node,['.title&&Text','.video-title&&Text','.home-rows-videos-title&&Text','.owl-home-rows-title&&Text','img&&alt']);
    var stats=nodes(node,'.stats-container .stat-item');
    return {id:idFrom(href)||idFrom(img),title:title||'未命名',url:C.abs(base,href),img:C.abs(base,img),rating:stats.length?text(stats[0],'Text'):'',views:stats.length>1?text(stats[1],'Text'):'',duration:firstText(node,['.duration&&Text','.card-mobile-duration&&Text']),artist:firstText(node,['.subtitle a&&Text','.meta-author a&&Text','.subtitle&&Text']),upload:firstText(node,['.meta-stats span&&Text','.card-mobile-meta&&Text'])};
  }
  function cards(html,base){
    var sels=['div.horizontal-card','div[class^=video-item-container]','.related-video-margin-bottom','.home-rows-videos-wrapper > *'],all=[];
    for(var s=0;s<sels.length;s++){var a=nodes(html,sels[s]);for(var i=0;i<a.length;i++){var c=card(a[i],base);if(c.id&&c.title)all.push(c);}}
    return unique(all,function(x){return x.id;});
  }
  function home(){
    var r=assertResp(C.video('/'),'首页');var base=r.base||C.resolveHost(false),html=r.body,sections=[],featured=null;
    var banner=nodes(html,'#home-banner-wrapper');if(banner.length){var b=banner[0],bi=firstAttr(b,['img&&src']),bt=firstText(b,['h1&&Text','.title&&Text']),meta=firstText(b,['h4&&Text']);if(bt)featured={id:idFrom(bi),title:bt,img:C.abs(base,bi),meta:meta};}
    var titles=nodes(html,'#home-rows-wrapper > a.horizontal-row-title');
    for(var i=0;i<titles.length;i++){
      var t=firstText(titles[i],['h3&&Text','Text']),href=firstAttr(titles[i],['a&&href','href']);
      var row='';try{row=pdfh(titles[i],'next&&Html')||'';}catch(e){}
      var list=cards(row,base);if(list.length)sections.push({title:t||'推荐',more:C.abs(base,href),items:list});
    }
    if(!sections.length){var all=cards(html,base);if(all.length)sections.push({title:'推荐',more:'',items:all});}
    return {base:base,featured:featured,sections:sections};
  }
  function search(opt){
    opt=opt||{};var base=C.resolveHost(false),params={page:opt.page||1,query:opt.query||'',genre:opt.genre||'',sort:opt.sort||'',date:opt.date||'',duration:opt.duration||'',type:opt.type||''};if(opt.broad)params.broad='on';if(opt.tags&&opt.tags.length)params['tags[]']=opt.tags;
    var url=C.query(base+'/search',params),r=assertResp(C.get(url,{base:base,referer:base+'/'}),'搜索'),list=cards(r.body,base),artist=[];
    if(String(opt.type||'')==='artist'){
      var aa=nodes(r.body,'.search-artist-card');for(var i=0;i<aa.length;i++){var name=firstText(aa[i],['.search-artist-title&&Text','.title&&Text']),img=firstAttr(aa[i],['img&&src']),href=firstAttr(aa[i],['a.overlay&&href','a&&href']),q='';try{q=decodeURIComponent((href.match(/[?&]query=([^&]+)/)||[])[1]||'');}catch(e){}if(name)artist.push({title:name,img:C.abs(base,img),query:q||name,meta:firstText(aa[i],['.search-artist-count&&Text'])});}
    }
    var total=Number(opt.page||1),pg=nodes(r.body,'ul.pagination li.page-item a.page-link');for(var j=0;j<pg.length;j++){var n=parseInt(text(pg[j],'Text'),10);if(n>total)total=n;}
    return {url:url,items:list,artists:artist,page:Number(opt.page||1),totalPages:total};
  }
  function previews(month){var base=C.resolveHost(false),m=month||'',r=assertResp(C.get(base+'/previews/'+m,{base:base,referer:base+'/'}),'预告'),rows=nodes(r.body,'.content-padding > div.row[id]'),out=[];for(var i=0;i<rows.length;i++){out.push({id:firstAttr(rows[i],['id']),title:firstText(rows[i],['h4&&Text','h3&&Text']),img:C.abs(base,firstAttr(rows[i],['.preview-info-cover img&&src','img&&src'])),brand:firstText(rows[i],['.preview-info-content-padding h5 a&&Text']),desc:firstText(rows[i],['.preview-info-content-padding .caption&&Text'])});}return out;}
  function video(id){
    var base=C.resolveHost(false),r=assertResp(C.video('/watch?v='+encodeURIComponent(id)),'视频详情'),h=r.body,player=nodes(h,'video#player'),p=player.length?player[0]:'',sources=[],ss=nodes(p||h,'source');
    for(var i=0;i<ss.length;i++){var u=attr(ss[i],'src'),q=attr(ss[i],'size')||attr(ss[i],'label')||'默认';if(u)sources.push({quality:q,url:C.abs(base,u),type:attr(ss[i],'type')});}
    var title=firstAttr(h,['meta[property="og:title"]&&content'])||firstText(h,['title&&Text']),cover=C.abs(base,firstAttr(p||h,['poster','meta[property="og:image"]&&content']));title=String(title||'').replace(/\s*-\s*Hanime1[\s\S]*$/i,'').trim();
    var descPanel=nodes(h,'.video-description-panel'),dp=descPanel.length?descPanel[0]:h,artist=firstText(h,['#video-artist-name&&Text','.video-description-panel a[href*=genre]&&parent&&Text','.subtitle a&&Text']),artistId=firstAttr(h,['#video-subscribe-form input[name=subscribe-artist-id]&&value']),userId=firstAttr(h,['input[name=like-user-id]&&value']),subUserId=firstAttr(h,['#video-subscribe-form input[name=subscribe-user-id]&&value']),csrf=firstAttr(h,['meta[name=csrf-token]&&content','input[name=_token]&&value']);
    var tagNodes=nodes(h,'.video-tags-wrapper .single-video-tag a'),tags=[];for(var j=0;j<tagNodes.length;j++){var tn=text(tagNodes[j],'Text').replace(/\s*\(\d+\)\s*$/,'').trim(),th=attr(tagNodes[j],'href');if(tn&&th)tags.push({name:tn,href:C.abs(base,th)});}
    var related=[],relNodes=nodes(h,'#related-tabcontent .horizontal-card');for(var k=0;k<relNodes.length;k++){var rc=card(relNodes[k],base);if(rc.id)related.push(rc);}related=unique(related,function(x){return x.id;});
    return {id:String(id),base:base,title:title||'未命名',cover:cover,duration:firstAttr(h,['meta[property="og:video:duration"]&&content'])||firstText(h,['.duration&&Text']),views:firstText(dp,['div.hidden-xs&&Text','.video-views&&Text']),artist:artist,artistId:artistId,artistAvatar:C.abs(base,firstAttr(h,['#video-user-avatar&&src','.video-description-panel a[href*=user] img&&src'])),genre:firstText(h,['.video-description-panel a[href*=genre]&&Text']),upload:firstText(dp,['.meta-stats&&Text']),caption:firstText(dp,['.video-caption-text&&Text','.caption&&Text']),download:C.abs(base,firstAttr(h,['#downloadBtn&&href'])),csrf:csrf,currentUserId:userId,subscriptionUserId:subUserId,commentCount:firstText(h,['#tab-comments-count&&Text']),tags:unique(tags,function(x){return x.name;}),sources:sources,related:related,raw:h};
  }
  function playModel(detail){var urls=[],names=[],headers=[];for(var i=0;i<(detail.sources||[]).length;i++){var s=detail.sources[i];if(!s.url)continue;urls.push(s.url);names.push(String(s.quality||'默认')+(s.type?' · '+s.type.replace('video/','') :''));headers.push({'User-Agent':C.ua,'Referer':detail.base+'/'});}if(!urls.length)throw new Error('未解析到可播放地址');return JSON.stringify({urls:urls,names:names,headers:headers});}
  function comicHome(){var r=assertResp(C.comic('/comics'),'漫画首页'),h=r.body,out={hot:[],latest:[]},sec=nodes(h,'.comic-rows-wrapper');for(var i=0;i<sec.length;i++){var title=firstText(sec[i],['h3&&Text']),list=comicCards(sec[i]);if(title.indexOf('發燒')>=0||title.indexOf('发烧')>=0)out.hot=out.hot.concat(list);else if(title.indexOf('最新')>=0)out.latest=out.latest.concat(list);else out.latest=out.latest.concat(list);}out.hot=unique(out.hot,function(x){return x.id;});out.latest=unique(out.latest,function(x){return x.id;});return out;}
  function comicCards(html){var a=nodes(html,'a[href*="/comic/"]'),out=[];for(var i=0;i<a.length;i++){var href=attr(a[i],'href'),m=href.match(/\/comic\/(\d+)/),title=firstText(a[i],['.comic-rows-videos-title&&Text','img&&alt']),img=firstAttr(a[i],['img&&data-srcset','img&&data-src','img&&src']);if(m&&title)out.push({id:m[1],title:title,img:C.abs(C.comicHost,img)});}return unique(out,function(x){return x.id;});}
  function comicBrowse(path,page){var url=C.query(/^https?:/.test(path||'')?path:C.comicHost+(String(path||'/comics').charAt(0)==='/'?'':'/')+String(path||'/comics'),{page:page||1}),r=assertResp(C.get(url,{base:C.comicHost,referer:C.comicHost+'/'}),'漫画列表'),list=comicCards(r.body),total=Number(page||1),pg=nodes(r.body,'.pagination .page-link');for(var i=0;i<pg.length;i++){var n=parseInt(text(pg[i],'Text'),10);if(n>total)total=n;}return {items:list,page:Number(page||1),totalPages:total};}
  function comicDetail(id){var a=assertResp(C.comic('/comic/'+id),'漫画详情'),b=assertResp(C.comic('/comic/'+id+'/1'),'漫画阅读'),h=a.body,hh=b.body,img=nodes(hh,'#current-page-image'),im=img.length?img[0]:'',nav=nodes(hh,'.comic-show-content-nav'),count=parseInt(nav.length?attr(nav[0],'data-pages'):'1',10)||1,prefix=attr(im,'data-prefix'),fallback=attr(im,'data-extension')||'jpg',exts=[],scripts=nodes(hh,'script');for(var s=0;s<scripts.length;s++){var st=text(scripts[s],'Html')||text(scripts[s],'Text'),m=st.match(/extensions\.innerHTML\s*=\s*'([^']+)'/);if(m){try{exts=JSON.parse(m[1].replace(/&quot;/g,'"'));}catch(e){}break;}}
    var images=[];for(var i=0;i<count;i++){var e=String(exts[i]||fallback);if(e==='w')e='webp';if(e==='j')e='jpg';images.push(C.abs(C.comicHost,prefix+(i+1)+'.'+e));}
    var tags=[],links=nodes(h,'.comics-metadata-margin-top h5 a[href]');for(var j=0;j<links.length;j++){var name=text(links[j],'Text'),href=attr(links[j],'href');if(name&&href)tags.push({name:name,href:C.abs(C.comicHost,href)});}
    return {id:String(id),title:firstText(h,['h3.title&&Text'])||firstAttr(hh,['meta[property="og:title"]&&content'])||'漫画',cover:C.abs(C.comicHost,firstAttr(h,['.col-md-4 img&&data-srcset','.col-md-4 img&&src','#current-page-image&&src'])),tags:tags,images:images,count:count,desc:firstAttr(h,['meta[name=description]&&content'])};
  }
  function csrf(base){var r=assertResp(C.get(base+'/',{base:base,referer:base+'/',timeout:12000}),'账号校验'),t=firstAttr(r.body,['meta[name=csrf-token]&&content','input[name=_token]&&value']);return {token:t,html:r.body};}
  function profile(){var base=C.resolveHost(false),s=csrf(base),home=s.html,href=firstAttr(home,['#user-modal-trigger&&href']),id=(href.match(/\/user\/(\d+)/)||[])[1]||((firstText(home,['.profile-sub-stats-id&&Text']).match(/\d+/)||[])[0]||'');if(!id)throw new Error('未检测到已登录账号，请先登录并同步');var r=assertResp(C.get(base+'/user/'+id+'/edit',{base:base,referer:base+'/'}),'账号资料'),h=r.body;return {id:id,name:firstAttr(h,['input[name=name]&&value'])||firstText(home,['#user-modal-name&&Text','.profile-display-name&&Text'])||('用户 '+id),email:firstAttr(h,['input[name=email]&&value']),avatar:C.abs(base,firstAttr(h,['img#playlist-avatar&&src','#user-modal-dp-wrapper img&&src','.profile-avatar-wrapper img&&src'])),csrf:firstAttr(h,['meta[name=csrf-token]&&content','input[name=_token]&&value'])||s.token,joined:firstText(home,['#user-modal-created&&Text']),cookie:C.accountCookie(base),base:base};}
  function syncBrowserAccount(){C.useBrowserSession();var p=profile(),raw=C.browserCookie(p.base);if(!C.withoutClearance(raw))throw new Error('浏览器登录 Cookie 为空，请先完成网页登录');return C.saveAccount(p,raw);}
  function formPost(path,data,label){var base=C.resolveHost(false),s=csrf(base),token=s.token;if(token)data._token=token;var r=assertResp(C.post(base+path,data,{base:base,referer:base+'/',headers:token?{'X-CSRF-TOKEN':token}:{}}),label||'账号操作');if(/\/login["'?<\s]/i.test(r.body)&&!/logout/i.test(path))throw new Error('账号登录状态已失效，请重新登录');return r;}
  function updateProfile(name,email){var p=profile();formPost('/user/'+p.id,{_method:'patch',type:'profile',name:name,email:email},'修改资料');return profile();}
  function updatePassword(oldPwd,newPwd,confirmPwd){var p=profile();formPost('/user/'+p.id,{_method:'patch',type:'password',password_old:oldPwd,password_new:newPwd,password_new_confirm:confirmPwd},'修改密码');return true;}
  function library(){var p=profile(),base=p.base,urls=[['watchLater','/user/'+p.id+'/saves'],['favorites','/user/'+p.id+'/likes'],['playlists','/user/'+p.id+'/playlists'],['history','/user/'+p.id+'/histories?sort=latest&page=1'],['subscriptions','/subscriptions?page=1']],out={profile:p,watchLater:[],favorites:[],playlists:[],history:[],subscriptions:[],artists:[],csrf:p.csrf};for(var i=0;i<urls.length;i++){var key=urls[i][0],r=assertResp(C.get(base+urls[i][1],{base:base,referer:base+'/'}),'片库 '+key);if(key==='playlists'){var ps=nodes(r.body,'.user-tab-item-wrapper,.playlist-item-wrapper,.playlist-card');for(var j=0;j<ps.length;j++){var href=firstAttr(ps[j],['a[href*=playlist]&&href','a&&href']),m=href.match(/[?&]list=([^&]+)/),title=firstText(ps[j],['.title&&Text','.playlist-title&&Text']);if(m&&title)out.playlists.push({id:m[1],title:title,count:firstText(ps[j],['.stat-item&&Text','.playlist-count&&Text']),img:C.abs(base,firstAttr(ps[j],['img&&src']))});}}else if(key==='subscriptions'){var vv=cards(r.body,base);out.subscriptions=vv;var aa=nodes(r.body,'.subscriptions-artist-card');for(var k=0;k<aa.length;k++){var nm=firstText(aa[k],['.card-mobile-title&&Text','.title&&Text']),imgs=nodes(aa[k],'img');var ai=imgs.length?firstAttr(imgs[imgs.length-1],['src']):'';if(nm)out.artists.push({name:nm,img:C.abs(base,ai)});}}else out[key]=cards(r.body,base);}return out;}
  function saveToPlaylist(videoId,listId,enabled){formPost('/save',{input_id:listId,video_id:videoId,is_checked:String(enabled!==false),user_id:''},'保存到片单');return true;}
  function createPlaylist(videoId,title,desc){formPost('/createPlaylist',{'create-playlist-video-id':videoId,'playlist-title':title,'playlist-description':desc||''},'创建片单');return true;}
  function setFavorite(videoId,enabled){var p=profile();formPost('/like',{'like-foreign-id':videoId,'like-status':enabled?'':'1','like-user-id':p.id,'like-is-positive':'1'},'收藏');return true;}
  function setSubscription(detail,enabled){var p=profile(),uid=detail.subscriptionUserId||p.id,aid=detail.artistId;if(!aid)throw new Error('当前视频未提供作者订阅 ID');formPost('/subscribe',{'subscribe-user-id':uid,'subscribe-artist-id':aid,'subscribe-status':enabled?'':'1'},'订阅作者');return true;}
  function deleteHistory(videoId){var base=C.resolveHost(false),s=csrf(base),r=C.request(base+'/user/tab-item/'+videoId,{base:base,referer:base+'/',method:'DELETE',body:C.form({tab:'histories'}),headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8','X-CSRF-TOKEN':s.token}});assertResp(r,'删除历史');return true;}
  function playlist(id,sort){var base=C.resolveHost(false),url=base+'/playlist?list='+encodeURIComponent(id)+'&sort='+encodeURIComponent(sort||'latest')+'&page=1',r=assertResp(C.get(url,{base:base,referer:base+'/'}),'片单详情'),items=cards(r.body,base);return {id:id,title:firstText(r.body,['.playlist-title&&Text'])||'片单',desc:firstText(r.body,['.playlist-description&&Text']),items:items,csrf:firstAttr(r.body,['meta[name=csrf-token]&&content','input[name=_token]&&value'])};}
  function updatePlaylist(id,title,desc,remove){var data={_method:'PUT','playlist-title':title||'','playlist-description':desc||''};if(remove)data['playlist-delete']='on';formPost('/playlist/'+id,data,remove?'删除片单':'修改片单');return true;}
  function comments(videoId){var base=C.resolveHost(false),url=C.query(base+'/loadComment',{type:'video',id:videoId}),r=assertResp(C.get(url,{base:base,referer:base+'/watch?v='+videoId}),'评论'),body=r.body;try{var j=JSON.parse(body);if(j&&typeof j.comments==='string')body=j.comments;}catch(e){}var root=nodes(body,'#comment-start'),rows=root.length?nodes(root[0],'.comment-index-text'):nodes(body,'.comment-index-text'),replyWrap=nodes(body,'div[id^=reply-section-wrapper]'),out=[];for(var i=0;i+1<rows.length;i+=2){var user=firstText(rows[i],['a&&Text','Text']),content=text(rows[i+1],'Text'),ri=Math.floor(i/2),rid=ri<replyWrap.length?String(attr(replyWrap[ri],'id')).split('-').pop():'';if(user&&content)out.push({id:rid||'',user:user,content:content,time:firstText(rows[i],['span&&Text']),avatar:C.abs(base,firstAttr(rows[i],['img&&src']))});}return {items:out,csrf:firstAttr(body,['input[name=_token]&&value']),userId:firstAttr(body,['input[name=comment-user-id]&&value'])};}
  function replies(commentId){var base=C.resolveHost(false),r=assertResp(C.get(C.query(base+'/loadReplies',{id:commentId}),{base:base,referer:base+'/'}),'回复'),body=r.body;try{var j=JSON.parse(body);if(j&&typeof j.replies==='string')body=j.replies;}catch(e){}var rows=nodes(body,'.comment-index-text'),out=[];for(var i=0;i+1<rows.length;i+=2){var u=firstText(rows[i],['a&&Text','Text']),c=text(rows[i+1],'Text');if(u&&c)out.push({user:u,content:c,time:firstText(rows[i],['span&&Text'])});}return out;}
  function postComment(videoId,content){var p=profile();formPost('/createComment',{'comment-user-id':p.id,'comment-type':'video','comment-foreign-id':videoId,'comment-text':content,'comment-count':'1','comment-is-political':'0'},'发表评论');return true;}
  function replyComment(commentId,content){formPost('/replyComment',{'reply-comment-id':commentId,'reply-comment-text':content},'回复评论');return true;}
  var filters={genres:[['全部',''],['里番','裏番'],['泡面番','泡麵番'],['Motion Anime','Motion Anime'],['3D动画','3D動畫']],sorts:[['默认',''],['最新上市','release_date'],['最新上传','upload_date'],['本日排行','today'],['本周排行','week'],['本月排行','month'],['总排行','views']],dates:[['不限',''],['24小时','1d'],['2天','2d'],['1周','1w'],['1月','1m'],['3月','3m']],durations:[['不限',''],['1分钟+','1'],['5分钟+','5'],['10分钟+','10'],['20分钟+','20']],types:[['视频',''],['作者','artist']]};
  return {build:C.build,home:home,search:search,previews:previews,video:video,playModel:playModel,comicHome:comicHome,comicBrowse:comicBrowse,comicDetail:comicDetail,profile:profile,syncBrowserAccount:syncBrowserAccount,updateProfile:updateProfile,updatePassword:updatePassword,library:library,saveToPlaylist:saveToPlaylist,createPlaylist:createPlaylist,setFavorite:setFavorite,setSubscription:setSubscription,deleteHistory:deleteHistory,playlist:playlist,updatePlaylist:updatePlaylist,comments:comments,replies:replies,postComment:postComment,replyComment:replyComment,filters:filters,card:card,cards:cards};
})();
