/* PikPak 0.1.0-test.5 Runtime Patch - automatic verification handoff + recycle cleanup */
(function(C,P,Pages,R){
    var baseModule=R.module;
    function put(k,v){try{putMyVar(k,String(v==null?'':v));}catch(e){}}
    function get(k){try{return String(getMyVar(k,'')||'');}catch(e){return '';}}
    function clearOne(k){try{clearMyVar(k);}catch(e){}}
    function clearVerify(clearPassword){clearOne('pikpak_v2_verify_url');clearOne('pikpak_v2_verify_token');clearOne('pikpak_v2_verify_user');clearOne('pikpak_v2_verified_captcha');clearOne('pikpak_v2_verify_handoff_done');if(clearPassword){clearOne('pikpak_v2_login_pass');clearOne('pikpak_v2_login_user');}try{clearVar('pikpak_review_orig_token');}catch(e){}}
    function saveChallenge(r,user){put('pikpak_v2_verify_user',user||'');put('pikpak_v2_verify_token',r&&r.captcha_token?r.captcha_token:'');put('pikpak_v2_verify_url',r&&r.verify_url?r.verify_url:(C.buildPasswordReviewUrl?C.buildPasswordReviewUrl(r):''));clearOne('pikpak_v2_verified_captcha');clearOne('pikpak_v2_verify_handoff_done');}
    function loginSuccess(){clearVerify(true);toast('PikPak 登录成功');try{refreshPage(false);}catch(e){try{refreshPage();}catch(e2){}}return 'hiker://empty';}
    function loginAction(user,pass){user=String(user||'').trim();pass=String(pass||'');put('pikpak_v2_login_user',user);put('pikpak_v2_login_pass',pass);showLoading('正在连接 PikPak…');var r=C.beginPasswordLogin(user,pass);hideLoading();if(r&&!r.error&&!r.error_code&&r.access_token)return loginSuccess();if(r&&r.needsVerification){saveChallenge(r,user);if(!get('pikpak_v2_verify_url')){clearOne('pikpak_v2_login_pass');return 'toast://PikPak 要求安全验证，但没有取得验证页面地址';}toast('需要完成 PikPak 安全验证');return 'hiker://page/pikpakVerify?rule=PikPak&simple=true';}clearOne('pikpak_v2_login_pass');return 'toast://'+C.errorText(r);}
    function finishWith(token){var user=get('pikpak_v2_verify_user')||get('pikpak_v2_login_user'),pass=get('pikpak_v2_login_pass'),tok=String(token||get('pikpak_v2_verified_captcha')||get('pikpak_v2_verify_token'));if(!user||!pass)return {error:'LOGIN_STATE_LOST',error_description:'登录临时信息已失效，请返回账号页重新输入'};if(!tok)return {error:'CAPTCHA_TOKEN_EMPTY',error_description:'验证令牌为空，请重新加载验证'};return C.finishPasswordLogin(user,pass,tok);}
    function verifyContinueAction(){showLoading('正在确认验证结果…');var r=finishWith('');hideLoading();if(r&&!r.error&&!r.error_code&&r.access_token){clearVerify(true);toast('验证通过，登录成功');return 'hiker://home@PikPak';}if(r&&r.needsVerification){saveChallenge(r,get('pikpak_v2_verify_user')||get('pikpak_v2_login_user'));toast('验证尚未通过或已刷新，请继续完成验证');try{refreshPage(false);}catch(e){try{refreshPage();}catch(e2){}}return 'hiker://empty';}return 'toast://'+C.errorText(r);}
    function verifyReloadAction(){var user=get('pikpak_v2_verify_user')||get('pikpak_v2_login_user'),pass=get('pikpak_v2_login_pass'),old=get('pikpak_v2_verify_token');if(!user||!pass)return 'toast://登录临时信息已失效，请返回账号页重新输入';showLoading('正在重新获取验证页面…');var r=C.refreshPasswordChallenge(user,pass,old);hideLoading();if(r&&r.captcha_token){saveChallenge(r,user);toast('验证页面已刷新');try{refreshPage(false);}catch(e){try{refreshPage();}catch(e2){}}return 'hiker://empty';}return 'toast://'+C.errorText(r);}
    function verifyCancelAction(){clearVerify(true);toast('已取消验证并清除临时密码');try{back(false);}catch(e){try{back();}catch(e2){}}return 'hiker://empty';}
    function verifyDone(){var token='';try{token=String(getParam('captcha_token','')||'');}catch(e){}if(token)put('pikpak_v2_verified_captcha',token);showLoading('验证完成，正在继续登录…');var r=finishWith(token);hideLoading();if(r&&!r.error&&!r.error_code&&r.access_token){clearVerify(true);setResult([{title:'✅ PikPak 登录成功',desc:'安全验证已完成，会话已经保存。',url:'hiker://home@PikPak',col_type:'text_center_1',extra:{lineVisible:false}},{title:'返回 PikPak 首页',url:'hiker://home@PikPak',col_type:'text_center_1'}]);return;}if(r&&r.needsVerification){saveChallenge(r,get('pikpak_v2_verify_user')||get('pikpak_v2_login_user'));setResult([{title:'安全验证仍未完成',desc:'PikPak 仍要求验证，请重新打开验证页。',url:'hiker://page/pikpakVerify?rule=PikPak&simple=true',col_type:'text_center_1'}]);return;}setResult([{title:'登录没有完成',desc:C.errorText(r),url:'hiker://page/pikpakAccount?rule=PikPak&simple=true',col_type:'text_1',extra:{lineVisible:false}}]);}
    function cleanupTempAction(){showLoading('正在把临时播放文件移入回收站…');var r=P.cleanupTemps(true)||{};hideLoading();if(r.error)return 'toast://临时文件清理失败：'+r.error;toast(r.moved>0?'已将 '+r.moved+' 个临时播放文件移入回收站':'没有需要清理的临时播放文件');return 'hiker://empty';}
    R.module=function(){var m=baseModule();m.version='0.1.0-test.5';m.build=10105;m.loginAction=loginAction;m.account=Pages.account;m.verify=Pages.verify;m.settings=Pages.settings;m.verifyContinueAction=verifyContinueAction;m.verifyReloadAction=verifyReloadAction;m.verifyCancelAction=verifyCancelAction;m.verifyDone=verifyDone;m.cleanupTempAction=cleanupTempAction;return m;};
    R.version='0.1.0-test.5';R.build=10105;
})(PikPakCore,PikPakProvider,PikPakPages,PikPakRemoteRuntime);
