/* 汤头条 0.1.0-test.14 Pages / restore large App feed + authorized reference compatibility */
var TangTouTiaoPagesV022=(function(){
  var B=TangTouTiaoPagesV021,P=TangTouTiaoProtocolV015,W=TangTouTiaoPwaV020,C=TangTouTiaoCoreV021,U=TangTouTiaoUIV015,O={};for(var k in B)if(B.hasOwnProperty(k))O[k]=B[k];
  var HOME='ttt_home_tab_v010';
  function searchInput(d){d.push({title:'搜索视频、创作者、关键词',col_type:'input',url:$.toString(function(){var w=String(input||'').trim();if(!w)return'toast://请输入搜索关键词';putMyVar('ttt_search_kw',w);return'hiker://page/tttSearch?rule=&simple=true&kw='+encodeURIComponent(w);}),extra:{defaultValue:'',titleVisible:true,onChange:$.toString(function(){})}});}
  function quick(d){var a=[['频道','channel',C.page('tttChannels')],['社区','community',C.page('tttCommunity')],['排行榜','rank',C.page('tttRank')],['我的','mine',C.page('tttMine')]];for(var i=0;i<a.length;i++)d.push(U.icon(a[i][0],a[i][1],a[i][2]));}
  function header(d){searchInput(d);var tab=getMyVar(HOME,'recommend')||'recommend',tabs=[['recommend','推荐'],['short','短视频'],['long','长视频'],['community','社区']];for(var i=0;i<tabs.length;i++)d.push(U.chip(tabs[i][1],tab===tabs[i][0],U.state(HOME,tabs[i][0])));d.push(U.blank());quick(d);d.push(U.line());return tab;}
  function appFeed(){var r=P.call('/api/MvList/featuredAv',{page:1,limit:30}),list=C.normalize(r,'featured')||[];return{res:r,list:list,provider:'app'};}
  function shortFeed(){try{var r=W.shortVideos(1,'recommend'),list=C.normalize(r,'short')||[];if(list.length){try{setItem('ttt_last_short_provider',JSON.stringify({time:Date.now(),provider:'pwa',count:list.length}));}catch(e0){}return{res:r,list:list,provider:'pwa'};}}catch(e1){}var ar=P.call('/api/MvList/smallVideoByTag',{page:1,tag:'recommend'}),al=C.normalize(ar,'short')||[];return{res:ar,list:al,provider:'app'};}
  function sec(s){s=String(s||'');var a=s.split(':').map(Number);if(a.some(function(x){return isNaN(x);} ))return 0;if(a.length===3)return a[0]*3600+a[1]*60+a[2];if(a.length===2)return a[0]*60+a[1];return a[0]||0;}
  function longList(all){var out=[];for(var i=0;i<all.length;i++){var it=all[i];if(sec(it.duration)>=180||it.source240||it.source480||it.source720||it.source1080)out.push(it);}return (out.length?out:all).slice(0,36);}
  function recList(all){return all.slice(0,36);}
  function record(it){return JSON.stringify(C.plainRecord?C.plainRecord(it):it);}
  function shortCard(it){var meta=[];if(it.author)meta.push(it.author);if(it.duration)meta.push(it.duration);if(it.plays)meta.push(it.plays);return{title:it.title||'未命名',desc:meta.join(' · '),img:it.cover||'',pic_url:it.cover||'',url:$('#noLoading#').lazyRule(function(x){try{return $.require('ttt').playShortReference(x);}catch(e){return'toast://播放失败：'+String(e.message||e);}},record(it)),col_type:'movie_2',extra:{lineVisible:false,inheritTitle:false,ttt_id:it.id,ttt_direct_play:true}};}
  function push(d,list,isShort){for(var i=0;i<list.length;i++)d.push(isShort?shortCard(list[i]):U.videoCard(C,list[i],'movie_2'));}
  function home(){var d=[],pg=Number(MY_PAGE||1);setPageTitle('汤头条');if(pg>1){setResult(d);return;}var tab=header(d);try{if(tab==='community'){B.home();return;}if(tab==='short'){var sf=shortFeed();d.push(U.section('热门短视频','视频 '+sf.list.length+' 条'));push(d,sf.list,true);setResult(d);return;}var af=appFeed(),list=tab==='long'?longList(af.list):recList(af.list);try{setItem('ttt_last_long_provider',JSON.stringify({time:Date.now(),provider:'app-featuredAv',total:af.list.length,shown:list.length,tab:tab}));}catch(e2){}d.push(U.section(tab==='long'?'精选长视频':'今日推荐','视频 '+list.length+' 条'));push(d,list,false);}catch(e){d.push(U.error('首页请求失败',e,C.page('tttSettings')));}setResult(d);}
  function channel(){var type=C.param('type','');if(type!=='short'){B.channel();return;}var d=[];setPageTitle(C.param('title','短视频'));try{var f=shortFeed();d.push(U.section('热门短视频','视频 '+f.list.length+' 条'));push(d,f.list,true);}catch(e){d.push(U.error('短视频加载失败',e,C.page('tttSettings')));}setResult(d);}
  function fallback(){return{id:C.param('id',''),title:C.param('title','视频详情'),coverRaw:C.param('coverRaw',''),author:C.param('author','')};}
  function historyPayload(it){return JSON.stringify(C.plainRecord(it));}
  function payload(it,sources,expected){return JSON.stringify({id:it.id,title:it.title,expectedDuration:expected==null?it.duration:expected,sources:sources||C.sources(it)});}
  function preferred(qsrc,all,id){var key='ttt_detail_quality_'+id,v=String(getMyVar(key,'240P')||'240P'),ok=false;for(var i=0;i<qsrc.length;i++)if(qsrc[i].name===v)ok=true;if(!ok){if(qsrc.length)v=qsrc[qsrc.length-1].name;else if(all.length)v=all[0].name;}return{key:key,value:v};}
  function qualityButton(name,on,key){return{title:(on?'● ':'')+name,url:U.state(key,name),col_type:'text_4',extra:{lineVisible:false}};}
  function fullPlayUrl(it,q){return $('#noLoading#').lazyRule(function(p,n){try{return $.require('ttt').playBest(p,n);}catch(e){return'toast://播放解析失败：'+String(e.message||e);}},payload(it),q);}
  function compatPlayUrl(it){return $('#noLoading#').lazyRule(function(x){try{return $.require('ttt').playAuthorizedReference(x);}catch(e){return'toast://兼容线路失败：'+String(e.message||e);}},historyPayload(it));}
  function previewPlayUrl(it){var s=it.preview?[{name:'预览',url:it.preview,fallback:true}]:[];return $('#noLoading#').lazyRule(function(h,p){try{return $.require('ttt').playPreview(h,p);}catch(e){return'toast://试看失败：'+String(e.message||e);}},historyPayload(it),payload(it,s,''));}
  function purchaseUrl(it){var js='$.require("ttt").purchaseAndPlay('+JSON.stringify(String(it.id))+','+JSON.stringify(String(it.title||''))+','+Number(it.coins||0)+','+JSON.stringify(String(it.duration||''))+')';return'confirm://确认使用 '+Number(it.coins||0)+' 汤币解锁完整版？.js:'+js;}
  function detail(){var d=[],fb=fallback(),id=fb.id;setPageTitle(fb.title||'视频详情');if(!id){d.push(U.empty('缺少视频 ID'));setResult(d);return;}try{var r=P.call('/api/MvDetail/detail',{id:id}),it=C.detailItem(r,fb),all=C.sources(it),qsrc=C.qualitySources(it),sel=preferred(qsrc,all,id),ac=C.accessState(it);setPageTitle(it.title||fb.title||'视频详情');C.addHistory(it);
    d.push({title:it.title,desc:[it.author,it.duration,it.plays].filter(Boolean).join('\n'),img:it.cover,pic_url:it.cover,url:'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});
    if(ac.locked){d.push(U.section('完整版',ac.coins+' 汤币'));if(it.preview)d.push({title:'▶ 试看',desc:'先试看当前视频',url:previewPlayUrl(it),col_type:'text_2',extra:{lineVisible:false,inheritTitle:false}});d.push({title:'解锁完整版',desc:'确认后扣除 '+ac.coins+' 汤币',url:purchaseUrl(it),col_type:'text_2',extra:{lineVisible:false,inheritTitle:false}});}else{d.push({title:all.length?'▶ 立即播放':'暂无可用线路',desc:ac.purchased?'已购买':'免费内容',url:all.length?fullPlayUrl(it,sel.value):'toast://当前详情没有可用播放线路',col_type:'text_2',extra:{lineVisible:false,inheritTitle:false}});if(it.preview)d.push({title:'兼容线路',desc:'免费/已购买内容使用参考规则的 long 主机兼容写法',url:compatPlayUrl(it),col_type:'text_2',extra:{lineVisible:false,inheritTitle:false}});}
    d.push(U.chip(C.isFav(id)?'★ 已收藏':'☆ 收藏',C.isFav(id),$('#noLoading#').lazyRule(function(x){var on=$.require('ttt').toggleFavFromDetail(x);refreshPage(false);return'toast://'+(on?'已收藏':'已取消收藏');},historyPayload(it)),'text_2'));
    if(!ac.locked&&qsrc.length){d.push(U.line());d.push(U.section('清晰度',''));for(var i=0;i<qsrc.length;i++)d.push(qualityButton(qsrc[i].name,sel.value===qsrc[i].name,sel.key));}
    if(it.desc){d.push(U.line());d.push(U.section('简介',''));d.push({title:it.desc,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});}try{setItem('ttt_last_access_state',JSON.stringify({time:Date.now(),id:id,kind:ac.kind,isFree:it.isFree,isPay:it.isPay,coins:it.coins,hasPreview:!!it.preview}));}catch(e2){}
  }catch(e){d.push(U.error('详情加载失败',e,C.page('tttSettings')));}setResult(d);}
  O.home=home;O.channel=channel;O.detail=detail;O.version='0.1.0-test.14';return O;
})();
