/* 汤头条 0.1.0-test.14 Runtime / reference URL compatibility only for free or purchased content */
var TangTouTiaoRemoteRuntime=(function(){
  var instance=null;
  function diagnosticsText(){var keys=['ttt_last_featured_exact','ttt_last_detail_exact','ttt_last_access_state','ttt_last_short_provider','ttt_last_short_play','ttt_last_reference_rewrite','ttt_last_long_provider','ttt_last_pwa','ttt_last_image_policy','ttt_last_image_diag','ttt_last_play_sources','ttt_last_source_probe','ttt_last_play_diag','ttt_last_purchase','ttt_last_community_home','ttt_last_community_list','ttt_last_player_cfg','ttt_last_version_info','ttt_last_comic_home','ttt_last_comic_list','ttt_last_rank_exact','ttt_last_probe','ttt_last_bootstrap'],a=[];for(var i=0;i<keys.length;i++){var v=getItem(keys[i],'');if(v)a.push(keys[i]+'\n'+v);}return a.join('\n\n')||'暂无诊断记录';}
  function settings(){var d=[],s=TangTouTiaoProtocolV015.sessionInfo();setPageTitle('设置与诊断');d.push({title:'汤头条 Test14',desc:'0.1.0-test.14 · Build 10114 · 大列表恢复 + 参考规则兼容线路',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行状态',desc:'设备 '+(s.deviceReady?'已建立':'未建立')+'｜Token '+(s.tokenReady?'已建立':'未建立')+'｜播放器 '+(s.playerReady?'已就绪':'未就绪'),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:diagnosticsText(),url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);}
  function parseRec(rec){try{return typeof rec==='string'?JSON.parse(rec):rec||{};}catch(e){return{};}}
  function referenceRewrite(u){u=String(u||'').trim();if(!/^https?:\/\//i.test(u))return'';var out=u.replace(/\/\/[^/?#]*play\./i,'//long.');out=out.replace(/([?&])seconds=30(?=(&|$))/i,function(_,p1,p2){return p2?p1:'';}).replace(/[?&]$/,'');return out;}
  function logRewrite(id,access,src,out,mode){try{setItem('ttt_last_reference_rewrite',JSON.stringify({time:Date.now(),id:String(id||''),access:access,mode:mode,changed:String(src)!==String(out),source:String(src).substring(0,220),rewritten:String(out).substring(0,220)}));}catch(e){}}
  function purchaseAndPlay(id,title,coins,duration){try{var r=TangTouTiaoProtocolV015.call('/api/user/watchingMvByCoins',{mvId:String(id)}),d=TangTouTiaoCoreV021.dataOf(r)||{},url=String(TangTouTiaoCoreV021.pick(d,['url','play_url','playUrl'],'')||''),msg=TangTouTiaoCoreV021.text(TangTouTiaoCoreV021.pick(d,['msg','message'],'')||'');if(!url)return'toast://'+(msg||'未取得解锁后的完整播放地址');return TangTouTiaoPlaybackV018.playBest(JSON.stringify({id:String(id),title:String(title||''),expectedDuration:String(duration||''),sources:[{name:'已解锁',url:url}]}),'已解锁');}catch(e){return'toast://解锁失败：'+String(e.message||e);}}
  function playShortReference(rec){var x=parseRec(rec),id=String(x.id||'');if(!id)return'toast://缺少视频ID';try{var r=TangTouTiaoProtocolV015.call('/api/MvDetail/detail',{id:id}),it=TangTouTiaoCoreV021.detailItem(r,x),ac=TangTouTiaoCoreV021.accessState(it);TangTouTiaoCoreV021.addHistory(it);if(ac.locked){if(it.preview)return TangTouTiaoPlaybackV018.playBest(JSON.stringify({id:id,title:it.title,expectedDuration:'',sources:[{name:'试看',url:it.preview}]}),'试看');return'toast://该视频需 '+ac.coins+' 汤币解锁完整版';}
      var pwaPreview=String(x.preview||it.preview||''),rw=referenceRewrite(pwaPreview);if(rw){logRewrite(id,ac.kind,pwaPreview,rw,'short-reference');try{setItem('ttt_last_short_play',JSON.stringify({time:Date.now(),id:id,mode:'reference-rewrite',url:rw.substring(0,220)}));}catch(e0){}return rw+'#isVideo=true#';}
      if(it.sourceOrigin){try{setItem('ttt_last_short_play',JSON.stringify({time:Date.now(),id:id,mode:'source-origin-fallback',url:String(it.sourceOrigin).substring(0,220)}));}catch(e1){}return String(it.sourceOrigin)+'#isVideo=true#';}
      var ss=TangTouTiaoCoreV021.sources(it);if(ss.length)return TangTouTiaoPlaybackV018.playBest(JSON.stringify({id:id,title:it.title,expectedDuration:'',sources:ss}),'短视频');
    }catch(e2){try{setItem('ttt_last_short_play',JSON.stringify({time:Date.now(),id:id,mode:'error',error:String(e2.message||e2)}));}catch(e3){}}
    var rw2=referenceRewrite(x.preview||'');if(rw2){logRewrite(id,'record-only',x.preview,rw2,'short-record-reference');return rw2+'#isVideo=true#';}return'toast://未取得短视频播放线路';}
  function playAuthorizedReference(rec){var x=parseRec(rec),id=String(x.id||'');if(!id)return'toast://缺少视频ID';try{var r=TangTouTiaoProtocolV015.call('/api/MvDetail/detail',{id:id}),it=TangTouTiaoCoreV021.detailItem(r,x),ac=TangTouTiaoCoreV021.accessState(it);if(ac.locked)return'toast://该兼容线路只用于免费或已购买内容';var src=String(it.preview||x.preview||''),rw=referenceRewrite(src);if(!rw)return'toast://当前详情没有可测试的兼容地址';logRewrite(id,ac.kind,src,rw,'long-authorized-reference');return rw+'#isVideo=true#';}catch(e){return'toast://兼容线路失败：'+String(e.message||e);}}
  function module(){if(instance)return instance;if(typeof TangTouTiaoPagesV022!=='object')throw new Error('汤头条 Test14 模块未完整加载');var base=TangTouTiaoPagesV022,m={version:'0.1.0-test.14',build:10114,home:base.home,channels:base.channels,channel:base.channel,community:base.community,search:base.search,detail:base.detail,mine:base.mine,rank:base.rank,settings:settings,protocolProbe:function(){return TangTouTiaoProtocolV015.probe();},resetSession:function(full){return TangTouTiaoProtocolV015.resetSession(!!full);},sessionInfo:function(){return TangTouTiaoProtocolV015.sessionInfo();},playBest:function(p,q){return TangTouTiaoPlaybackV018.playBest(p,q);},playShortReference:playShortReference,playShortById:playShortReference,playById:playShortReference,playAuthorizedReference:playAuthorizedReference,playPreview:function(h,p){return TangTouTiaoPlaybackV018.playBest(p,'预览');},playDirect:function(h,p,q){return TangTouTiaoPlaybackV018.playBest(p,q);},purchaseAndPlay:purchaseAndPlay,toggleFavFromDetail:function(s){var x=JSON.parse(String(s||'{}'));return TangTouTiaoCoreV021.toggleFav(x);}};instance=m;return m;}return{version:'0.1.0-test.14',build:10114,module:module};
})();
