/* 汤头条 0.1.0-test.2 Core / recursive response adapter */
var TangTouTiaoCoreV011=(function(){
  var V='0.1.0-test.2';
  function text(v){return String(v==null?'':v).replace(/<[^>]+>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').trim();}
  function maybeJson(v){if(typeof v!=='string')return v;var s=v.trim();if(!s)return v;if((s.charAt(0)==='{'&&s.charAt(s.length-1)==='}')||(s.charAt(0)==='['&&s.charAt(s.length-1)===']'))try{return JSON.parse(s);}catch(e){}return v;}
  function pick(o,keys,d){if(!o||typeof o!=='object')return d;for(var i=0;i<keys.length;i++){var v=o[keys[i]];if(v!==undefined&&v!==null&&String(v)!=='')return v;}return d;}
  function deepPick(o,keys,d,depth){depth=depth||0;o=maybeJson(o);if(depth>6||!o||typeof o!=='object')return d;var v=pick(o,keys,null);if(v!==null&&v!==undefined&&String(v)!=='')return v;if(Array.isArray(o)){for(var i=0;i<o.length&&i<8;i++){var a=deepPick(o[i],keys,null,depth+1);if(a!==null&&a!==undefined&&String(a)!=='')return a;}return d;}for(var k in o)if(o.hasOwnProperty(k)){var x=o[k];if((x&&typeof x==='object')||typeof x==='string'){var b=deepPick(x,keys,null,depth+1);if(b!==null&&b!==undefined&&String(b)!=='')return b;}}return d;}
  function dataOf(res){res=maybeJson(res);if(res==null)return null;var d=res.data!==undefined?res.data:res.result!==undefined?res.result:res;return maybeJson(d);}
  function objectScore(o){if(!o||typeof o!=='object'||Array.isArray(o))return 0;var score=0,ks=Object.keys(o),strong=['mv_id','mvId','video_id','videoId','id','title','mv_name','mv_title','name','thumb','thumb_url','cover','cover_url','pic','image','play_url','m3u8'];for(var i=0;i<strong.length;i++)if(o[strong[i]]!==undefined)score+=2;score+=Math.min(ks.length,12)*0.05;return score;}
  function arrayScore(a,path){if(!Array.isArray(a)||!a.length)return-1;var score=Math.min(a.length,30)*0.05;if(/list|mv|video|item|data|result|recommend|featured|small|rows|records/i.test(path||''))score+=3;var n=Math.min(a.length,5);for(var i=0;i<n;i++)score+=objectScore(a[i]);if(typeof a[0]==='string'||typeof a[0]==='number')score-=3;return score;}
  function collectArrays(v,path,depth,out,seen){depth=depth||0;out=out||[];seen=seen||[];v=maybeJson(v);if(depth>8||v==null)return out;if(typeof v==='object'){for(var q=0;q<seen.length;q++)if(seen[q]===v)return out;seen.push(v);}if(Array.isArray(v)){out.push({path:path||'$',value:v,score:arrayScore(v,path)});for(var i=0;i<v.length&&i<3;i++)collectArrays(v[i],(path||'$')+'['+i+']',depth+1,out,seen);return out;}if(typeof v==='object'){for(var k in v)if(v.hasOwnProperty(k))collectArrays(v[k],(path?path+'.':'')+k,depth+1,out,seen);}return out;}
  function listOf(res){var d=dataOf(res);if(Array.isArray(d))return d;var c=collectArrays(d,'data',0,[],[]);if(!c.length)c=collectArrays(res,'root',0,[],[]);if(!c.length)return[];c.sort(function(a,b){return b.score-a.score;});try{setItem('ttt_last_list_path',c[0].path+' score='+c[0].score.toFixed(2)+' len='+c[0].value.length);}catch(e){}return c[0].value;}
  function absImg(u){u=String(u||'').trim();if(!u)return'';if(/^\/\//.test(u))return'https:'+u;return u;}
  function item(x){x=maybeJson(x)||{};var id=deepPick(x,['id','mv_id','mvId','video_id','videoId','movie_id','movieId','vid','uuid','media_id','mediaId','av_id','aid'],'');var title=text(deepPick(x,['title','name','mv_name','mvName','mv_title','mvTitle','video_name','videoName','video_title','videoTitle','subject','caption'],'未命名'));var cover=absImg(deepPick(x,['cover','cover_url','coverUrl','pic','pic_url','picUrl','image','image_url','imageUrl','img','img_url','imgUrl','thumb','thumb_url','thumbUrl','thumbnail','poster','poster_url','posterUrl','mv_img','mvImg','face_thumb'],'')||'');var author=text(deepPick(x,['nickname','nick_name','nickName','user_name','userName','author','author_name','authorName','creator_name','creatorName','uper_name','username','member_name','memberName'],'')||'');var desc=text(deepPick(x,['desc','description','intro','summary','content','mv_desc','mvDesc','remark'],'')||'');var duration=text(deepPick(x,['duration','duration_str','durationStr','time_len','timeLen','play_time','playTime','video_time','videoTime'],'')||'');var play=deepPick(x,['play_url','playUrl','video_url','videoUrl','m3u8','url_play','urlPlay','media_url','mediaUrl','src','face_m3u8'],'')||'';return{id:String(id),title:title,cover:cover,author:author,desc:desc,duration:duration,play:String(play||''),raw:x};}
  function normalize(res){var a=listOf(res),out=[];for(var i=0;i<a.length;i++){var x=item(a[i]);if(x.id||x.title!=='未命名'||x.cover)out.push(x);}return out;}
  function deepMedia(v,depth){depth=depth||0;v=maybeJson(v);if(depth>8||v==null)return'';if(typeof v==='string'){var s=v.trim();if(/^https?:\/\//i.test(s)&&(/\.m3u8(?:\?|$)/i.test(s)||/\.mp4(?:\?|$)/i.test(s)||/\.flv(?:\?|$)/i.test(s)))return s;return'';}if(Array.isArray(v)){for(var i=0;i<v.length;i++){var a=deepMedia(v[i],depth+1);if(a)return a;}return'';}if(typeof v==='object'){var pr=['play_url','playUrl','video_url','videoUrl','m3u8','media_url','mediaUrl','url','src','file','face_m3u8'];for(var j=0;j<pr.length;j++)if(v[pr[j]]!=null){var b=deepMedia(v[pr[j]],depth+1);if(b)return b;}for(var k in v)if(v.hasOwnProperty(k)){var c=deepMedia(v[k],depth+1);if(c)return c;}}return'';}
  function deepImage(v,depth){depth=depth||0;v=maybeJson(v);if(depth>6||v==null)return'';if(typeof v==='string'){var s=v.trim();if(/^\/\//.test(s))return'https:'+s;if(/^https?:\/\//i.test(s)&&(/\.(?:jpe?g|png|webp|gif)(?:\?|$)/i.test(s)||/image|pic|cover|thumb/i.test(s)))return s;return'';}if(Array.isArray(v)){for(var i=0;i<v.length;i++){var a=deepImage(v[i],depth+1);if(a)return a;}return'';}if(typeof v==='object'){var pr=['cover','cover_url','coverUrl','pic','pic_url','picUrl','image','image_url','imageUrl','img','img_url','imgUrl','thumb','thumb_url','thumbUrl','thumbnail','poster','avatar'];for(var j=0;j<pr.length;j++)if(typeof v[pr[j]]==='string'&&v[pr[j]])return absImg(v[pr[j]]);for(var k in v)if(v.hasOwnProperty(k)){var b=deepImage(v[k],depth+1);if(b)return b;}}return'';}
  function enc(v){return encodeURIComponent(String(v==null?'':v));}
  function page(path,p){var u='hiker://page/'+path+'?rule=&simple=true',o=p||{};for(var k in o)if(o.hasOwnProperty(k)&&o[k]!=null)u+='&'+enc(k)+'='+enc(o[k]);return u;}
  function param(n,d){try{var v=getParam(n);return v==null||v===''?d:v;}catch(e){return d;}}
  function addHistory(it){if(!it)return;var a=[];try{a=JSON.parse(getItem('ttt_history','[]')||'[]');}catch(e){}if(!Array.isArray(a))a=[];a=a.filter(function(x){return String(x.id)!==String(it.id);});a.unshift({id:it.id,title:it.title,cover:it.cover,author:it.author,time:Date.now()});if(a.length>80)a=a.slice(0,80);setItem('ttt_history',JSON.stringify(a));}
  function histories(){try{var a=JSON.parse(getItem('ttt_history','[]')||'[]');return Array.isArray(a)?a:[];}catch(e){return[];}}
  function toggleFav(it){var a=[];try{a=JSON.parse(getItem('ttt_favs','[]')||'[]');}catch(e){}if(!Array.isArray(a))a=[];var id=String(it.id||''),idx=-1;for(var i=0;i<a.length;i++)if(String(a[i].id)===id){idx=i;break;}if(idx>=0){a.splice(idx,1);setItem('ttt_favs',JSON.stringify(a));return false;}a.unshift({id:id,title:it.title,cover:it.cover,author:it.author,time:Date.now()});setItem('ttt_favs',JSON.stringify(a));return true;}
  function favs(){try{var a=JSON.parse(getItem('ttt_favs','[]')||'[]');return Array.isArray(a)?a:[];}catch(e){return[];}}
  function isFav(id){var a=favs();for(var i=0;i<a.length;i++)if(String(a[i].id)===String(id))return true;return false;}
  return{version:V,text:text,pick:pick,deepPick:deepPick,dataOf:dataOf,listOf:listOf,item:item,normalize:normalize,deepMedia:deepMedia,deepImage:deepImage,page:page,param:param,addHistory:addHistory,histories:histories,toggleFav:toggleFav,favs:favs,isFav:isFav};
})();
