/* Hanime1 Test34 account: XPath-first profile/library/playlist parsing */
(function(C,P,E,H,L){
function clean(v){return C.clean(String(v==null?'':v));}
function nodes(html,sel){try{return pdfa(String(html||''),sel)||[];}catch(e){return [];}}
function text(node,sel){try{return clean(pdfh(node,sel)||'');}catch(e){return '';}}
function attr(node,sel){try{return String(pdfh(node,sel)||'').replace(/&amp;/g,'&').trim();}catch(e){return '';}}
function xa(html,path){try{if(typeof xpathArray==='function')return xpathArray(String(html||''),path)||[];if(typeof xpa==='function')return xpa(String(html||''),path)||[];}catch(e){}return [];}
function first(a){return a&&a.length?String(a[0]||'').replace(/&amp;/g,'&').trim():'';}
function abs(base,u){u=String(u||'').trim();return u?C.abs(base,u):'';}
function vid(u){var m=String(u||'').match(/[?&]v=(\d+)/);return m?m[1]:'';}
function pid(u){var m=String(u||'').match(/[?&]list=([^&"']+)/);if(!m)return '';try{return decodeURIComponent(m[1]);}catch(e){return m[1];}}
var oldProfile=P.profile;
P.profile=function(){var p=oldProfile();if(p&&p.avatar)return p;try{var base=(p&&p.base)||C.resolveHost(false),id=p&&p.id;if(!id)return p;var r=C.get(base+'/user/'+id+'/edit',{base:base,referer:base+'/',timeout:12000}),h=String(r&&r.body||''),av=first(xa(h,'//*[@id="playlist-avatar"]/@src'))||first(xa(h,'//img[contains(@class,"profile-avatar")]/@src'));if(!av){var home=C.get(base+'/',{base:base,referer:base+'/',timeout:12000}),hh=String(home&&home.body||'');av=first(xa(hh,'//*[@id="user-modal-dp-wrapper"]//img[1]/@src'))||first(xa(hh,'//*[contains(@class,"profile-avatar-wrapper")]//img[1]/@src'));}if(av)p.avatar=abs(base,av);}catch(e){}return p;};
function cardFromHtml(h,base){var href=first(xa(h,'//a[contains(@href,"watch?v=")][1]/@href'))||first(xa(h,'//*[@data-href][contains(@data-href,"watch?v=")][1]/@data-href')),id=vid(href),title=clean(first(xa(h,'//*[contains(concat(" ",normalize-space(@class)," ")," video-title ")][1]//text()')))||clean(first(xa(h,'//*[contains(concat(" ",normalize-space(@class)," ")," title ")][1]//text()')))||clean(first(xa(h,'//img[1]/@alt'))),img=first(xa(h,'//img[contains(@class,"main-thumb")][1]/@src'))||first(xa(h,'//img[1]/@data-src'))||first(xa(h,'//img[1]/@src'));if(!id)return null;return {id:id,title:title||('影片 '+id),img:abs(base,img),artist:clean(first(xa(h,'//*[contains(@class,"meta-author")]//a[1]//text()')))||clean(first(xa(h,'//*[contains(@class,"subtitle")]//a[1]//text()'))),duration:clean(first(xa(h,'//*[contains(@class,"duration")][1]//text()'))),views:'',upload:''};}
function videoList(h,base){var arr=xa(h,'//div[starts-with(@class,"user-tab-item-wrapper")] | //div[contains(concat(" ",normalize-space(@class)," ")," horizontal-card ")]'),out=[],seen={};for(var i=0;i<arr.length;i++){var x=cardFromHtml('<div>'+arr[i]+'</div>',base);if(x&&x.id&&!seen[x.id]){seen[x.id]=1;out.push(x);}}if(out.length)return out;var links=xa(h,'//a[contains(@href,"watch?v=")]');for(var j=0;j<links.length;j++){var y=cardFromHtml('<div>'+links[j]+'</div>',base);if(y&&y.id&&!seen[y.id]){seen[y.id]=1;out.push(y);}}return out;}
function playlistList(h,base){var cards=xa(h,'//*[contains(concat(" ",normalize-space(@class)," ")," user-tab-item-wrapper ")][.//a[contains(@href,"playlist?list=")]] | //*[contains(concat(" ",normalize-space(@class)," ")," playlist-item-wrapper ")] | //*[contains(concat(" ",normalize-space(@class)," ")," playlist-card ")]'),out=[],seen={};for(var i=0;i<cards.length;i++){var g='<div>'+cards[i]+'</div>',href=first(xa(g,'//a[contains(@href,"playlist?list=")][1]/@href')),id=pid(href);if(!id||seen[id])continue;var title=clean(first(xa(g,'//*[contains(concat(" ",normalize-space(@class)," ")," playlist-title ")][1]//text()')))||clean(first(xa(g,'//*[contains(concat(" ",normalize-space(@class)," ")," title ")][1]//text()')))||clean(first(xa(g,'//img[1]/@alt'))),img=first(xa(g,'//img[contains(@class,"main-thumb")][1]/@src'))||first(xa(g,'//img[1]/@src')),count=clean(first(xa(g,'//*[contains(@class,"playlist-count") or contains(@class,"stat-item")][1]//text()')));seen[id]=1;out.push({id:id,title:title||('片单 '+id),count:count,img:abs(base,img)});}var hrefs=xa(h,'//a[contains(@href,"playlist?list=")]/@href');for(var j=0;j<hrefs.length;j++){var id2=pid(hrefs[j]);if(id2&&!seen[id2]){seen[id2]=1;out.push({id:id2,title:'片单 '+id2,count:'',img:''});}}return out;}
P.librarySection30=function(kind){var a=P.sessionProfile32?P.sessionProfile32():C.activeAccount();if(!a||!a.id)throw new Error('请先登录');var base=C.resolveHost(false),id=String(a.id),path=kind==='watchLater'?('/user/'+id+'/saves'):kind==='favorites'?('/user/'+id+'/likes'):kind==='playlists'?('/user/'+id+'/playlists'):kind==='history'?('/user/'+id+'/histories?sort=latest&page=1'):'/subscriptions?page=1',r=C.get(base+path,{base:base,referer:base+'/',timeout:16000});if(!r||r.challenge||Number(r.statusCode||0)>=400)throw new Error('账号内容加载失败：HTTP '+Number((r&&r.statusCode)||0));var h=String(r.body||'');return kind==='playlists'?{playlists:playlistList(h,base),items:[]}:{playlists:[],items:videoList(h,base)};};
P.playlist=function(id,sort){id=String(id||'');var base=C.resolveHost(false),page=1,total=1,out=[],seen={},title='片单',desc='';do{var url=base+'/playlist?list='+encodeURIComponent(id)+'&sort='+encodeURIComponent(sort||'latest')+'&page='+page,r=C.get(url,{base:base,referer:base+'/',timeout:16000});if(!r||r.challenge||Number(r.statusCode||0)>=400)throw new Error('片单详情加载失败：HTTP '+Number((r&&r.statusCode)||0));var h=String(r.body||'');if(page===1){title=clean(first(xa(h,'//*[contains(concat(" ",normalize-space(@class)," ")," playlist-title ")][1]//text()')))||title;desc=clean(first(xa(h,'//*[contains(concat(" ",normalize-space(@class)," ")," playlist-description ")][1]//text()')));var nums=xa(h,'//ul[contains(@class,"pagination")]//a[contains(@class,"page-link")]/text()');for(var n=0;n<nums.length;n++){var z=parseInt(clean(nums[n]),10);if(z>total)total=z;}}var list=videoList(h,base);for(var i=0;i<list.length;i++)if(!seen[list[i].id]){seen[list[i].id]=1;out.push(list[i]);}page++;}while(page<=total&&page<=12);return {id:id,title:title,desc:desc,items:out};};
function renderSection(d,cur){var r=P.librarySection30(cur);if(cur==='playlists'){d.push(H.sec('我的片单',r.playlists.length+' 个'));for(var i=0;i<r.playlists.length;i++){var p=r.playlists[i];d.push({title:p.title,desc:p.count||'',pic_url:p.img||'',url:H.route('hanimePlaylist',{id:p.id}),col_type:'movie_1_left_pic',extra:{lineVisible:false}});}if(!r.playlists.length)d.push(H.sec('暂无片单','官网当前没有返回片单。'));return;}var names={favorites:'收藏',watchLater:'稍后看',subscriptions:'订阅',history:'观看历史'},list=r.items||[];d.push(H.sec(names[cur]||'账号内容',list.length+' 部'));for(var j=0;j<list.length;j++)d.push(L.video(list[j],'library'));if(!list.length)d.push(H.sec('暂无内容','当前栏目为空。'));}
E.accountPage=function(){try{setPageTitle('账号中心');var d=[],p=P.profile();d.push({title:p.name||('用户 '+p.id),desc:[p.email,p.joined,'ID '+p.id].filter(Boolean).join(' · '),pic_url:p.avatar||'',url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false}});var cur=getMyVar('hanime32_account_section','playlists'),tabs=[['片单','playlists'],['收藏','favorites'],['稍后看','watchLater'],['订阅','subscriptions'],['历史','history']];for(var i=0;i<tabs.length;i++)d.push({title:(cur===tabs[i][1]?'✓ ':'')+tabs[i][0],url:$('#noLoading#').lazyRule(function(v){putMyVar('hanime32_account_section',v);refreshPage(false);return 'hiker://empty';},tabs[i][1]),col_type:'scroll_button'});d.push({col_type:'line_blank'});renderSection(d,cur);d.push(H.sec('账号资料'));d.push(H.btn('修改密码',H.route('hanimePassword',{}),'text_2'));d.push(H.btn('官网账号页面','x5://'+(p.base||C.resolveHost(false))+'/user/'+p.id+'/edit','text_2'));setResult(d);}catch(x){setResult([{title:'账号中心失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);
