/* Hanime1 Test34 library: full inline compact filters, no hidden '>' category gate */
(function(P,E,H,L){
function setVar(key,val){return $('#noLoading#').lazyRule(function(k,v){if(v===''&&k!=='hanime8_sort')clearMyVar(k);else putMyVar(k,v);refreshPage(false);return 'hiker://empty';},key,String(val));}
function clear(){return $('#noLoading#').lazyRule(function(){putMyVar('hanime8_sort','最新上傳');clearMyVar('hanime8_genre');clearMyVar('hanime8_date');clearMyVar('hanime8_duration');clearMyVar('hanime8_tags');clearMyVar('hanime8_broad');refreshPage(false);return 'toast://筛选已清空';});}
function chip(t,u,on,label){return {title:(on?'✓ ':'')+t,url:u,col_type:'scroll_button',extra:{lineVisible:false,bold:!!label}};}
function uniquePairs(a){var out=[],seen={};for(var i=0;i<(a||[]).length;i++){var x=a[i];if(!x||x.length<2)continue;var k=String(x[1]);if(seen[k])continue;seen[k]=1;out.push([String(x[0]),String(x[1])]);}return out;}
function row(d,label,key,items,cur,isTag){items=uniquePairs(items);d.push(chip(label,'hiker://empty',false,true));for(var i=0;i<items.length;i++){var v=items[i][1],on=isTag?String(cur||'')===v:String(cur||'')===v;d.push(chip(items[i][0],setVar(key,v),on,false));}d.push({col_type:'line_blank'});}
function tagPairs(cat){var a=cat&&cat.tags||[];if(a&&a.length&&Array.isArray(a[0]))return [['全部','']].concat(a);return [['全部',''],['无码','無碼'],['中字','中文字幕'],['1080P','1080p'],['60FPS','60FPS']];}
E.renderLibrary=function(d,page){page=Number(page||1);var s=H.state(),cat=s.cat||{};if(page===1){var genres=[['全部','']].concat(cat.genres||[]),sorts=cat.sorts||[],dates=[['全部','']].concat(cat.dates||[]),durations=[['全部','']].concat(cat.durations||[]),tg=(s.tags&&s.tags[0])||'';row(d,'类型','hanime8_genre',genres,s.genre,false);row(d,'排序','hanime8_sort',sorts,s.sort,false);row(d,'日期','hanime8_date',dates,s.date,false);row(d,'时长','hanime8_duration',durations,s.duration,false);row(d,'标签','hanime8_tags',tagPairs(cat),tg,true);d.push({title:'清空筛选',url:clear(),col_type:'text_center_1',extra:{lineVisible:false}});}var r=P.publicLibrary({sort:s.sort,genre:s.genre,date:s.date,duration:s.duration,tags:s.tags,broad:s.broad,page:page}),list=r.items||[];if(page===1)d.push(H.sec('影片',H.summary(s)+' · '+list.length+' 部'));for(var j=0;j<list.length;j++)d.push(L.video(list[j],'library'));if(!list.length)d.push(H.sec('暂无结果','调整筛选条件后会立即刷新。'));};
})(HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);
