// ACFun v0.2.8 raw diagnostic + direct 0.2.9 bridge
(function(){
if(typeof ac!=='object')throw new Error('ACFun core missing');
ac.build='2026.08.20-v0.2.8';
ac.__v028Plain=function(u){u=String(u||'').trim();if(!u)return '';if(typeof ac.__v027Plain==='function')return ac.__v027Plain(u);['@js=','@headers=','@Referer='].forEach(function(t){var p=u.indexOf(t);if(p>=0)u=u.substring(0,p);});return u;};
ac.__v028DetectMagic=function(hex){hex=String(hex||'').toLowerCase();if(hex.indexOf('89504e470d0a1a0a')===0)return'PNG';if(hex.indexOf('ffd8ff')===0)return'JPEG';if(hex.indexOf('52494646')===0&&hex.substring(16,24)==='57454250')return'WEBP';return'UNKNOWN';};
ac.__v028Probe=function(url){var plain=ac.__v028Plain(url);try{var hex=String(fetch(plain,{toHex:true,timeout:12000,headers:(ac.__imageHeaders?ac.__imageHeaders():{})})||''),type=ac.__v028DetectMagic(hex);setItem('acfun_v028_hex_prefix',hex.substring(0,160));setItem('acfun_v028_magic',type);setItem('acfun_v028_bytes',String(Math.floor(hex.length/2)));setItem('acfun_v028_probe_err','');return{ok:true,type:type,bytes:Math.floor(hex.length/2)};}catch(e){var m=String(e.message||e);setItem('acfun_v028_probe_err',m);return{ok:false,error:m};}};
ac.__direct029=function(){
 try{
  var api='https://api.github.com/repos/huoguotiankong/asset-core-7f3/contents/apps/video/acfun/releases/0.2.9/release.json?ref=main&_='+new Date().getTime();
  var obj=JSON.parse(String(fetch(api,{timeout:12000,headers:{Accept:'application/vnd.github+json','Cache-Control':'no-cache'}})||''));
  var txt=String(new java.lang.String(java.util.Base64.getMimeDecoder().decode(String(obj.content||'')),'UTF-8')),rel=JSON.parse(txt);
  if(Number(rel.build)!==129||String(rel.version)!=='0.2.9')throw new Error('0.2.9 release校验失败');
  require('https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/bootstrap_v3.js?v=3',{headers:{'Cache-Control':'no-cache'}},300);
  var m=ACFunBoot.requireManager(),info=m.info(ACFUN_HC_CONFIG),cur=info.current||null;m.loadRelease(ACFUN_HC_CONFIG,rel,false);
  if(typeof ac!=='object'||String(ac.build)!=='2026.08.20-v0.2.9')throw new Error('0.2.9运行校验失败: '+(typeof ac==='object'?ac.build:'ac missing'));
  setItem('hc_remote_state_acfun',JSON.stringify({schema:2,current:rel,previous:cur,updatedAt:new Date().getTime(),lastFallbackError:''}));clearItem('hc_acfun_last_check');ACFunBoot.installCompatibility();return{ok:true,current:rel};
 }catch(e){return{ok:false,error:String(e.message||e)};}
};
var __v028Nav=ac.nav;if(typeof __v028Nav==='function'){ac.nav=function(d){__v028Nav.call(ac,d);d.push({title:'直升0.2.9',col_type:'scroll_button',url:$('hiker://empty#noLoading#').lazyRule(function(){showLoading('直升0.2.9…');try{require('https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/bootstrap_v3.js?v=3',{headers:{'Cache-Control':'no-cache'}},300);ACFunBoot.loadOnly();var r=ac.__direct029();hideLoading();if(r.ok){refreshPage(false);return'toast://已直升 0.2.9';}return'toast://直升失败：'+r.error;}catch(e){hideLoading();return'toast://异常：'+(e.message||e);}})});};}
ac.diag=function(){var d=[];setPageTitle('ACFun 0.2.8 诊断');var raw=getItem('acfun_last_cover_raw',''),plain=getItem('acfun_last_cover_plain_v027','')||ac.__v028Plain(raw);d.push(ac.diagBlock('运行状态','版本：'+ac.build+'\nPlain='+plain+'\nMagic='+getItem('acfun_v028_magic','未检测')+'\nBytes='+getItem('acfun_v028_bytes','未检测')+'\nHexPrefix='+getItem('acfun_v028_hex_prefix','未检测')));if(plain)d.push({title:'重新检查原始字节',col_type:'text_1',url:$('hiker://empty#noLoading#').lazyRule(function(url){showLoading('读取…');try{require('https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/bootstrap_v3.js?v=3',{headers:{'Cache-Control':'no-cache'}},300);ACFunBoot.loadOnly();var r=ac.__v028Probe(url);hideLoading();refreshPage(false);return'toast://'+(r.ok?(r.type+' / '+r.bytes):r.error);}catch(e){hideLoading();return'toast://'+(e.message||e);}},plain)});d.push({title:'直升 0.2.9（XOR图片解密）',desc:'直接读取固定 0.2.9 release，绕过 latest.json/旧更新管理器缓存。',col_type:'text_1',url:$('hiker://empty#noLoading#').lazyRule(function(){showLoading('直升0.2.9…');try{require('https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/bootstrap_v3.js?v=3',{headers:{'Cache-Control':'no-cache'}},300);ACFunBoot.loadOnly();var r=ac.__direct029();hideLoading();if(r.ok){refreshPage(false);return'toast://已直升 0.2.9';}return'toast://失败：'+r.error;}catch(e){hideLoading();return'toast://异常：'+(e.message||e);}})});setItem('acfun_runtime_version',ac.build);setResult(d);};
})();
