/* 色花堂 Test17 forum - compact cards + per-board category/sort filters */
var SeHuaTangV17Forum=(function(C){
function group(m,seed,name){var g=0;try{if(m._debug&&m._debug.groupFromCacheV15)g=Number(m._debug.groupFromCacheV15(seed,name))}catch(e){}name=C.trim(name);if(g===0&&/^(中文字幕|国产自拍|亚洲视频|经典三级|在线视频)$/i.test(name))g=1;return g}
function previews(a){var n=0,i;for(i=0;i<(a||[]).length;i++)n+=(a[i].imgs||[]).length;return n}
function merge(a,b){var mp={},i,j,x,seen;for(i=0;i<(b||[]).length;i++)mp[b[i].id]=b[i];for(i=0;i<(a||[]).length;i++){x=mp[a[i].id];if(!x)continue;if((!a[i].meta||!a[i].meta.author)&&x.meta)a[i].meta=x.meta;seen={};for(j=0;j<(a[i].imgs||[]).length;j++)seen[C.canonical(a[i].imgs[j])]=1;for(j=0;j<(x.imgs||[]).length&&a[i].imgs.length<2;j++)if(!seen[C.canonical(x.imgs[j])]){seen[C.canonical(x.imgs[j])]=1;a[i].imgs.push(x.imgs[j])}}return a}
function stats(ctx,it){var t=C.strip(ctx),m,r='',l='',v='',all=[],re;if(it.title)t=t.replace(it.title,' ');if(it.meta&&it.meta.author)t=t.replace(it.meta.author,' ');m=t.match(/(?:回复|评论)[:：]?\s*(\d{1,7})/i);if(m)r=m[1];m=t.match(/(?:查看|浏览|观看)[:：]?\s*(\d{1,10})/i);if(m)v=m[1];m=t.match(/(?:点赞|赞)[:：]?\s*(\d{1,7})/i);if(m)l=m[1];if(!r||!v){re=/(?:^|\s)(\d{1,5})\s+(\d{1,5})\s+(\d{2,10})(?=\s|$)/g;while((m=re.exec(t))!==null)if(Number(m[3])>=Number(m[1]))all.push(m);if(all.length){m=all[all.length-1];if(!r)r=m[1];if(!l)l=m[2];if(!v)v=m[3]}}return{replies:r,likes:l,views:v}}
function attach(a,h){var i,x,st,en,ctx;for(i=0;i<(a||[]).length;i++){x=a[i];st=Number(x.titleIndex||0);en=i+1<a.length?Number(a[i+1].titleIndex||0):C.s(h).length;if(en<=st||en-st>90000)en=Math.min(C.s(h).length,st+65000);ctx=C.s(h).slice(st,en);x.stats=stats(ctx,x);x.summary=C.trim(C.s(x.summary).replace(/^(?:\d+\s+){2,4}/,'').replace(/(?:回复|评论|查看|浏览|观看)[:：]?\s*\d+/g,' ').replace(/\s+/g,' '))}return a}
function anchors(html,base){var out=[],re=/<a\b([^>]*?)href\s*=\s*(?:["']([^"']+)["']|([^\s>]+))([^>]*)>([\s\S]*?)<\/a>/gi,m,a,t;while((m=re.exec(C.s(html)))!==null){a=(m[1]||'')+' '+(m[4]||'');t=C.trim(C.strip(m[5]||''));out.push({href:C.abs(m[2]||m[3]||'',base),text:t,attrs:a,index:m.index});if(out.length>18000)break}return out}
function cleanUrl(u){return C.s(u).replace(/([?&])page=\d+/ig,'$1').replace(/([?&])mobile=(?:2|no)(?=&|$)/ig,'$1').replace(/\?&/g,'?').replace(/&&+/g,'&').replace(/[?&]$/,'')}
function sameForum(u,fid){if(!u)return false;var f=C.forumId(u);if(f&&fid)return String(f)===String(fid);return !!(fid&&new RegExp('[?&]fid='+fid+'(?:&|$)','i').test(u))}
function uniqPush(a,o){var i,k=cleanUrl(o.url);for(i=0;i<a.length;i++)if(cleanUrl(a[i].url)===k||a[i].title===o.title)return;a.push(o)}
function sortLabel(t){return /^(全部主题|全部|最新|热门|精华|按发帖|按回复|最新发表|最新回复)$/i.test(C.trim(t))}
function filterState(u){u=C.s(u);var type=(u.match(/[?&]typeid=(\d+)/i)||[])[1]||'',sort=(u.match(/[?&]sortid=(\d+)/i)||[])[1]||'',filter=(u.match(/[?&]filter=([^&#]+)/i)||[])[1]||'',orderby=(u.match(/[?&]orderby=([^&#]+)/i)||[])[1]||'',digest=(u.match(/[?&]digest=(\d+)/i)||[])[1]||'';return{type:type,sort:sort,filter:filter,orderby:orderby,digest:digest}}
function activeOption(o,current,row,index){var a=filterState(o.url),b=filterState(current);if(row==='type'){if(a.type&&b.type)return a.type===b.type;if(a.sort&&b.sort)return a.sort===b.sort;if(index===0&&!b.type&&!b.sort)return true;return false}if(a.filter&&b.filter&&a.filter===b.filter){if(a.orderby&&b.orderby)return a.orderby===b.orderby;if(a.digest&&b.digest)return a.digest===b.digest;if(!a.orderby&&!a.digest)return true}if(a.orderby&&b.orderby)return a.orderby===b.orderby;if(a.digest&&b.digest)return a.digest===b.digest;if(index===0&&!b.filter&&!b.orderby&&!b.digest)return true;return cleanUrl(o.url)===cleanUrl(current)}
function filters(html,base,seed){var a=anchors(html,base),fid=C.forumId(seed)||C.forumId(base),types=[],sorts=[],i,x,t,u,isType,isSort;for(i=0;i<a.length;i++){x=a[i];t=C.trim(x.text);u=x.href;if(!t||t.length>18||!sameForum(u,fid)||C.threadId(u))continue;if(/^(返回|首页|论坛|社区版块|发帖|搜索|上一页|下一页|尾页)$/i.test(t))continue;isSort=sortLabel(t)&&(/filter=|orderby=|digest=|forumdisplay/i.test(u));isType=/[?&](?:typeid|sortid)=\d+/i.test(u)||/[?&]filter=(?:typeid|sortid)(?:&|$)/i.test(u);if(isType)uniqPush(types,{title:t,url:u});if(isSort)uniqPush(sorts,{title:t,url:u})}
  if(!types.length){for(i=0;i<a.length;i++){x=a[i];t=C.trim(x.text);u=x.href;if(!t||t.length>10||!sameForum(u,fid)||C.threadId(u))continue;if(/^(全部|全部分类)$/i.test(t)&&/[?&]fid=|forum-\d+-/i.test(u))uniqPush(types,{title:'全部',url:u})}}
  if(sorts.length){var preferred=['全部主题','最新','热门','精华','按发帖','按回复'],ordered=[],j;for(i=0;i<preferred.length;i++)for(j=0;j<sorts.length;j++)if(sorts[j].title===preferred[i])uniqPush(ordered,sorts[j]);for(j=0;j<sorts.length;j++)uniqPush(ordered,sorts[j]);sorts=ordered}
  return{types:types.slice(0,24),sorts:sorts.slice(0,12)}}
function load(m,base,p,g){var fn=m._debug&&m._debug.parseCardsV15,mu=C.withPage(C.toMobile(base),p),pu=C.withPage(C.toPc(base),p),h='',a=[],b=[],fs={types:[],sorts:[]};if(!fn)return{items:[],url:mu,diag:'missing parser',filters:fs};h=C.renderList(mu);a=attach(fn(h,mu,g)||[],h);fs=filters(h,mu,base);if(!a.length){h=C.fetchPage(mu,false);a=attach(fn(h,mu,g)||[],h);if(!fs.types.length&&!fs.sorts.length)fs=filters(h,mu,base)}if(a.length&&previews(a)<Math.max(2,Math.floor(a.length/4))){h=C.fetchPage(pu,true);b=attach(fn(h,pu,g)||[],h);a=merge(a,b)}if(!a.length){h=C.fetchPage(pu,true);a=attach(fn(h,pu,g)||[],h);if(!fs.types.length&&!fs.sorts.length)fs=filters(h,pu,base)}return{items:a,url:mu,diag:'items='+a.length+' img='+previews(a)+' type='+fs.types.length+' sort='+fs.sorts.length,filters:fs}}
function pageKey(seed){var f=C.forumId(seed);return'sht_forum_page_v17_'+(f||C.s(seed).replace(/[^a-z0-9]/ig,'').slice(-24)||'x')}
function filterKey(seed){var f=C.forumId(seed);return'sht_forum_filter_v17_'+(f||C.s(seed).replace(/[^a-z0-9]/ig,'').slice(-24)||'x')}
function btn(t,k,p,on){return{title:t,url:on?$('#noLoading#').lazyRule(function(a,b){putMyVar(a,String(b));refreshPage(false);return'hiker://empty';},k,p):'hiker://empty',col_type:'text_3',extra:{lineVisible:false}}}
function controls(k,p,n){return[btn(p>1?'上一页':'第一页',k,Math.max(1,p-1),p>1),btn(p>1?'回第1页':'第1页',k,1,p>1),btn(n?'下一页':'已到底',k,p+1,n)]}
function filterBtn(o,fk,pk,on){return{title:(on?'✓ ':'')+o.title,url:$('#noLoading#').lazyRule(function(a,b,c){putMyVar(a,b);putMyVar(c,'1');refreshPage(false);return'hiker://empty';},fk,o.url,pk),col_type:'scroll_button',extra:{lineVisible:false}}}
function filterRows(d,fs,current,fk,pk){var i;if(fs.types&&fs.types.length>1){for(i=0;i<fs.types.length;i++)d.push(filterBtn(fs.types[i],fk,pk,activeOption(fs.types[i],current,'type',i)));d.push(C.line())}if(fs.sorts&&fs.sorts.length>1){for(i=0;i<fs.sorts.length;i++)d.push(filterBtn(fs.sorts[i],fk,pk,activeOption(fs.sorts[i],current,'sort',i)));d.push(C.line())}}
function author(d,it,ref){var m=it.meta||{},av=m.avatar?C.imageUrl(m.avatar,ref):'';if(m.author||av)d.push({title:(m.author||'发布者')+(m.role?' · '+m.role:''),desc:m.time||'',img:av,pic_url:av,url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false,cls:'sht_v17_author'}})}
function statRow(d,x){x=x||{};var a=[];if(x.replies)a.push('💬 '+x.replies);if(x.likes&&x.likes!=='0')a.push('👍 '+x.likes);if(x.views)a.push('👁 '+x.views);if(!a.length)return;d.push({title:'',url:'hiker://empty',col_type:'text_3',extra:{lineVisible:false,cls:'sht_v17_stat'}});d.push({title:'',url:'hiker://empty',col_type:'text_3',extra:{lineVisible:false,cls:'sht_v17_stat'}});d.push({title:'<small><font color="#999999">'+a.join('　')+'</font></small>',url:'hiker://empty',col_type:'text_3',extra:{lineVisible:false,cls:'sht_v17_stat'}})}
function videoDesc(it){var m=C.s(it.summary).match(/\b\d{1,2}:\d{2}:\d{2}\b/),a=[];if(m)a.push(m[0]);if(it.meta&&it.meta.time)a.push(it.meta.time);return a.join(' · ')}
function cards(d,a,ref,g){var i,j,it,u,p,ct;for(i=0;i<a.length;i++){it=a[i];u=C.route('shtThread',{sht_url:C.toMobile(it.url),sht_name:it.title,sht_group:g});if(g===1){p=(it.imgs||[]).length?C.imageUrl(it.imgs[0],ref):'';d.push({title:it.title,desc:videoDesc(it),img:p,pic_url:p,url:u,col_type:p?'movie_2':'text_2',extra:{lineVisible:false,cls:'sht_v17_video'}});continue}author(d,it,ref);d.push({title:it.title,desc:it.summary||'查看帖子',url:u,col_type:'text_1',extra:{lineVisible:false,cls:'sht_v17_card'}});ct=(it.imgs||[]).length===1?'pic_1_full':'pic_2';for(j=0;j<(it.imgs||[]).length&&j<2;j++){p=C.imageUrl(it.imgs[j],ref);d.push({title:'',img:p,pic_url:p,url:u,col_type:ct,extra:{lineVisible:false,cls:'sht_v17_preview'}})}statRow(d,it.stats);d.push(C.line('sht_v17_sep'))}}
function forum(m){var d=[],seed=C.pageParam('sht_url',''),name=C.pageParam('sht_name','主题列表'),g=group(m,seed,name),pk=pageKey(seed),fk=filterKey(seed),stored=C.trim(getMyVar(fk,'')),base=stored||seed,pp=Number(C.pageParam('sht_p','0')||0),p,r,c;if(pp>0){putMyVar(pk,String(pp));p=pp}else p=Math.max(1,Number(getMyVar(pk,'1')||1));setPageTitle(name);r=load(m,base,p,g);C.saveDiag('forum.mobile.v17','g='+g+' p='+p+' '+r.diag+' base='+base);if(p===1){d.push(C.quick('手机版','x5://'+C.withPage(C.toMobile(base),1),'web.svg'));d.push(C.quick('搜索',C.route('shtSearch'),'search.svg'));d.push(C.line());filterRows(d,r.filters,base,fk,pk);d.push(C.section(name,(g===1?'在线视频双列卡片':'手机端紧凑卡片')+' · 第 '+p+' 页 · '+r.items.length+' 条主题'))}else{filterRows(d,r.filters,base,fk,pk);d.push(C.section(name,'第 '+p+' 页 · 页内刷新翻页'))}c=controls(pk,p,r.items.length>0);Array.prototype.push.apply(d,c);d.push(C.line());cards(d,r.items,r.url,g);if(r.items.length){c=controls(pk,p,true);Array.prototype.push.apply(d,c)}else d.push(C.empty('本页没有解析到主题','可切换分类/排序，或点上一页/回第1页'));setResult(d)}
return{forum:forum,filters:filters,stats:stats};
})(SeHuaTangV16Core);