/* Hanime1 Test13 account center + My */
(function(C,P,E,H,L){
var route=H.route,sec=H.sec,btn=H.btn;
function profileHero(p){return {title:p.name||'Hanime1 用户',desc:[p.email,p.joined,p.subscriberCount?('订阅者 '+p.subscriberCount):'',p.videoCount?('视频 '+p.videoCount):'',p.id?('ID '+p.id):''].filter(Boolean).join(' · '),pic_url:p.avatar||'',url:route('hanimeAccount',{}),col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false}};}
function tab(t,id,cur){return {title:(cur===id?'● ':'')+t,url:$('#noLoading#').lazyRule(function(v){putMyVar('hanime13_mytab',v);refreshPage(false);return 'hiker://empty';},id),col_type:'scroll_button',extra:{lineVisible:false}};}
function videoList(d,a){for(var i=0;i<(a||[]).length;i++)d.push(L.video(a[i],'library'));}
E.renderMy=function(d){var active=C.activeAccount();if(!active){d.push(sec('我的 Hanime1','登录后可同步官网稍后看、收藏、片单、订阅与历史。'));d.push(btn('登录 Hanime1',route('hanimeLogin',{}),'text_center_1'));d.push(btn('账号说明',route('hanimeAccount',{}),'text_center_1'));return;}var p=null;try{p=P.profile();}catch(e){d.push(sec('账号会话失效',String(e.message||e)));d.push(btn('重新登录',route('hanimeLogin',{}),'text_center_1'));return;}d.push(profileHero(p));d.push({title:'账号中心',url:route('hanimeAccount',{}),col_type:'text_3',extra:{lineVisible:false}});d.push({title:'我的主页',url:route('hanimeAuthor',{id:p.id,name:p.name,kind:'me'}),col_type:'text_3',extra:{lineVisible:false}});d.push({title:'刷新账号',url:$('#noLoading#').lazyRule(function(){try{$.require('hanime').provider().profile();refreshPage(false);return 'toast://账号资料已刷新';}catch(e){return 'toast://'+String(e.message||e);}}),col_type:'text_3',extra:{lineVisible:false}});d.push({col_type:'line_blank'});
var lib;try{lib=P.library();}catch(x){d.push(sec('账号内容读取失败',String(x.message||x)));return;}var cur=getMyVar('hanime13_mytab','watchLater');d.push(tab('稍后看','watchLater',cur));d.push(tab('收藏','favorites',cur));d.push(tab('片单','playlists',cur));d.push(tab('订阅','subscriptions',cur));d.push(tab('历史','history',cur));d.push({col_type:'line_blank'});
if(cur==='playlists'){d.push(sec('我的片单',(lib.playlists||[]).length+' 个'));for(var j=0;j<(lib.playlists||[]).length;j++){var pl=lib.playlists[j];d.push({title:pl.title,desc:pl.count||'',pic_url:pl.img||'',url:route('hanimePlaylist',{id:pl.id}),col_type:'movie_2',extra:{lineVisible:false}});}if(!(lib.playlists||[]).length)d.push(sec('暂无片单'));return;}
if(cur==='subscriptions'){var aa=lib.artists||[];if(aa.length){d.push(sec('订阅作者',aa.length+' 位'));for(var k=0;k<aa.length;k++)d.push({title:aa[k].name,desc:'查看作者作品',pic_url:aa[k].img||'',url:route('hanimeVideoResults',{query:aa[k].name}),col_type:'avatar',extra:{lineVisible:false}});}d.push(sec('订阅内容',(lib.subscriptions||[]).length+' 部'));videoList(d,lib.subscriptions);if(!aa.length&&!(lib.subscriptions||[]).length)d.push(sec('暂无订阅内容'));return;}
var list=lib[cur]||[];d.push(sec(cur==='watchLater'?'稍后看':cur==='favorites'?'收藏':'观看历史',list.length+' 部'));videoList(d,list);if(!list.length)d.push(sec('暂无内容','官网当前栏目为空。'));};

E.accountPage=function(){try{setPageTitle('账号中心');var d=[],active=C.activeAccount(),accounts=C.accounts();if(!active){d.push(sec('未登录','Test12 的网页登录桥接已经通过实机验证。'));d.push(btn('登录 Hanime1',route('hanimeLogin',{}),'text_center_1'));setResult(d);return;}var p=P.profile();d.push(profileHero(p));d.push({title:'我的公开主页',url:route('hanimeAuthor',{id:p.id,name:p.name,kind:'me'}),col_type:'text_2',extra:{lineVisible:false}});d.push({title:'官网登录资料',url:'x5://'+p.base+'/user/'+p.id+'/edit',col_type:'text_2',extra:{lineVisible:false}});d.push(sec('账号资料','通过官网接口修改，操作后会重新读取资料确认。'));
d.push({title:'修改昵称',url:'input://'+JSON.stringify({value:p.name||'',hint:'新昵称',js:"if(!input)return 'toast://昵称不能为空';try{var m=$.require('hanime').provider(),x=m.profile();m.updateProfile(input,x.email||'');refreshPage(false);return 'toast://昵称已更新';}catch(e){return 'toast://'+String(e.message||e);}"}),col_type:'text_2',extra:{lineVisible:false}});d.push({title:'修改邮箱',url:'input://'+JSON.stringify({value:p.email||'',hint:'新邮箱',js:"if(!input)return 'toast://邮箱不能为空';try{var m=$.require('hanime').provider(),x=m.profile();m.updateProfile(x.name||'',input);refreshPage(false);return 'toast://邮箱已更新';}catch(e){return 'toast://'+String(e.message||e);}"}),col_type:'text_2',extra:{lineVisible:false}});d.push({title:'修改密码',url:route('hanimePassword',{}),col_type:'text_2',extra:{lineVisible:false}});d.push({title:'重新网页登录',url:route('hanimeLogin',{}),col_type:'text_2',extra:{lineVisible:false}});
d.push(sec('多账号','账号 Cookie 独立保存；Cloudflare 验证会话继续复用。'));for(var i=0;i<accounts.length;i++){var a=accounts[i],on=String(active.id)===String(a.id);d.push({title:(on?'● ':'')+(a.name||('用户 '+a.id)),desc:a.email||('ID '+a.id),pic_url:a.avatar||'',url:$('#noLoading#').lazyRule(function(id){$.require('hanime').core().activateAccount(id);refreshPage(false);return 'toast://已切换账号';},a.id),col_type:'avatar',extra:{lineVisible:false}});}d.push({title:'添加其他账号',url:route('hanimeLogin',{}),col_type:'text_2',extra:{lineVisible:false}});d.push({title:'退出当前账号',url:'confirm://确认退出当前账号？.js:'+$.toString(function(id){$.require('hanime').core().removeAccount(id);back(true);return 'toast://已退出账号';},active.id),col_type:'text_2',extra:{lineVisible:false}});setResult(d);}catch(x){setResult([{title:'账号中心加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);
