/* Hanime1 Test13 author directory + public author/uploader profile */
(function(C,P,E,H,L){
var pv=H.pv,route=H.route,sec=H.sec,btn=H.btn;
function authorCard(a){var url=a.id?route('hanimeAuthor',{id:a.id,name:a.name,kind:'author'}):route('hanimeVideoResults',{query:a.query||a.name});return {title:a.name||'作者',desc:a.meta||'查看作者作品',pic_url:a.img||'',url:url,col_type:'movie_3',extra:{lineVisible:false}};}
function pageButtons(d,page,total,q){if(total<=1)return;var start=Math.max(1,page-2),end=Math.min(total,start+4);if(end-start<4)start=Math.max(1,end-4);if(page>1)d.push({title:'‹',url:route('hanimeArtists',{page:page-1,q:q}),col_type:'scroll_button'});for(var i=start;i<=end;i++)d.push({title:(i===page?'● ':'')+i,url:route('hanimeArtists',{page:i,q:q}),col_type:'scroll_button'});if(end<total)d.push({title:'… '+total,url:route('hanimeArtists',{page:total,q:q}),col_type:'scroll_button'});if(page<total)d.push({title:'›',url:route('hanimeArtists',{page:page+1,q:q}),col_type:'scroll_button'});d.push({col_type:'line_blank'});}
E.artistsPage=function(){try{var page=Number(pv('page','1')||1),q=pv('q',''),d=[],r=P.artistDirectory13(page,q);setPageTitle('作者');d.push({title:'搜索作者',url:"if(!input)return 'hiker://page/hanimeArtists?rule=&simple=true';return 'hiker://page/hanimeArtists?rule=&simple=true&q='+encodeURIComponent(input);",col_type:'input',extra:{hint:'搜索作者 / 品牌',defaultValue:q,lineVisible:false}});d.push(sec('作者目录',(q?'“'+q+'” · ':'')+'第 '+page+' / '+r.totalPages+' 页 · '+r.items.length+' 位'));pageButtons(d,page,r.totalPages,q);for(var i=0;i<r.items.length;i++)d.push(authorCard(r.items[i]));if(!r.items.length)d.push(sec('暂无作者','尝试其它关键词或页码。'));setResult(d);}catch(x){setResult([{title:'作者目录加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
function tab(d,title,path,id,cur,name,kind){if(!path)return;d.push({title:(String(cur)===String(path)?'● ':'')+title,url:route('hanimeAuthor',{id:id,path:path,name:name,kind:kind}),col_type:'scroll_button',extra:{lineVisible:false}});}
E.authorPage=function(){try{var id=pv('id',''),path=pv('path',''),name=pv('name',''),kind=pv('kind','author'),page=Number(pv('page','1')||1),u=P.publicUser13(id,path,page),d=[];setPageTitle(u.name||name||(kind==='uploader'?'上传者':'作者'));d.push({title:u.name,desc:[u.handle,(u.subscriberCount?String(u.subscriberCount)+' 位订阅者':''),(u.videoCount?String(u.videoCount)+' 个视频':'')].filter(Boolean).join(' · '),pic_url:u.avatar||'',url:'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false}});if(u.bio)d.push({title:'简介',desc:u.bio,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false,textSize:15}});
var active=C.activeAccount(),sub=false;if(active&&kind!=='uploader'){try{var lib=P.library(),aa=lib.artists||[];for(var z=0;z<aa.length;z++)if(String(aa[z].name)===String(u.name)){sub=true;break;}}catch(e){}}
if(kind!=='uploader'&&active)d.push({title:sub?'已订阅':'订阅作者',url:$('#noLoading#').lazyRule(function(aid,on){try{$.require('hanime').provider().setSubscription({artistId:aid},!on);refreshPage(false);return 'toast://'+(!on?'已订阅':'已取消订阅');}catch(e){return 'toast://'+String(e.message||e);}},id,sub),col_type:'text_2',extra:{lineVisible:false}});d.push({title:'官网主页',url:'x5://'+u.base+'/user/'+id,col_type:'text_2',extra:{lineVisible:false}});d.push({col_type:'line_blank'});
var cur=u.path||u.tabs.home;tab(d,'首页',u.tabs.home,id,cur,u.name,kind);tab(d,'影片',u.tabs.videos,id,cur,u.name,kind);tab(d,'播放清单',u.tabs.playlists,id,cur,u.name,kind);d.push({col_type:'line_blank'});
if(u.playlists&&u.playlists.length){d.push(sec('播放清单',u.playlists.length+' 个'));for(var p=0;p<u.playlists.length;p++){var pl=u.playlists[p];d.push({title:pl.title,desc:pl.count||'',pic_url:pl.img||'',url:route('hanimePlaylist',{id:pl.id}),col_type:'movie_2',extra:{lineVisible:false}});}}
if(u.videos&&u.videos.length){d.push(sec('影片',u.videos.length+' 部'));for(var i=0;i<u.videos.length;i++)d.push(L.video(u.videos[i],'results'));}
if(!(u.videos&&u.videos.length)&&!(u.playlists&&u.playlists.length))d.push(sec('暂无公开内容','当前标签页没有解析到公开内容。'));
if(page>1)d.push(btn('‹ 上一页',route('hanimeAuthor',{id:id,path:path,name:u.name,kind:kind,page:page-1})));if(page<u.totalPages)d.push(btn('下一页 ›',route('hanimeAuthor',{id:id,path:path,name:u.name,kind:kind,page:page+1})));setResult(d);}catch(x){setResult([{title:'作者主页加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);
