/* 汤头条 0.1.0-test.6 Pages - official image helper + app-default playback + dynamic comic routing */
var TangTouTiaoPagesV015=(function(){
  var HOME='ttt_home_tab_v010',P=TangTouTiaoProtocolV015,C=TangTouTiaoCoreV015,U=TangTouTiaoUIV015,PB=TangTouTiaoPlaybackV015;
  function searchInput(d){d.push({title:'搜索视频、创作者、关键词',col_type:'input',url:$.toString(function(){var w=String(input||'').trim();if(!w)return'toast://请输入搜索关键词';putMyVar('ttt_search_kw',w);return'hiker://page/tttSearch?rule=&simple=true&kw='+encodeURIComponent(w);}),extra:{defaultValue:'',titleVisible:true,onChange:$.toString(function(){})}});}
  function quick(d){var a=[['频道','channel',C.page('tttChannels')],['社区','community',C.page('tttCommunity')],['排行榜','rank',C.page('tttRank')],['我的','mine',C.page('tttMine')]];for(var i=0;i<a.length;i++)d.push(U.icon(a[i][0],a[i][1],a[i][2]));}
  function fetchFeed(path,payload,kind){var r=P.call(path,payload||{}),list=C.normalize(r,kind||''),m=P.meta(r,path);return{res:r,list:list,meta:m};}
  function header(d){searchInput(d);var tab=getMyVar(HOME,'recommend')||'recommend',tabs=[['recommend','推荐'],['short','短视频'],['long','长视频'],['community','社区']];for(var i=0;i<tabs.length;i++)d.push(U.chip(tabs[i][1],tab===tabs[i][0],U.state(HOME,tabs[i][0])));d.push(U.blank());quick(d);d.push(U.line());return tab;}
  function responseHint(d,f){var m=f&&f.meta||{},bits=[];if(m.code!=='')bits.push('code '+m.code);if(m.msg)bits.push(m.msg);d.push(U.empty('当前列表暂无可显示内容',bits.join(' · ')||('结构 '+String(m.schema||'未知'))));if(m.schema)d.push({title:'响应结构：'+m.schema,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});}
  function home(){var d=[],pg=Number(MY_PAGE||1);setPageTitle('汤头条');if(pg>1){setResult(d);return;}var tab=header(d);try{if(tab==='community'){communityBody(d);setResult(d);return;}var path=tab==='short'?'/api/MvList/small':'/api/MvList/featuredAv',kind=tab==='short'?'short':'featured',f=fetchFeed(path,{page:1,limit:30},kind);d.push(U.section(tab==='short'?'热门短视频':tab==='long'?'精选长视频':'今日推荐',f.list.length?'视频 '+f.list.length+' 条':(f.meta.code!==''?'接口状态 '+f.meta.code:'')));for(var i=0;i<f.list.length;i++)d.push(U.videoCard(C,f.list[i],'movie_2'));if(!f.list.length)responseHint(d,f);}catch(e){d.push(U.error('首页请求失败',e,C.page('tttSettings')));}setResult(d);}
  function channelsBody(d){d.push(U.section('内容中心','按原 APP 功能域组织'));var a=[['长视频','video'],['短视频','short'],['创作者','creator'],['排行榜','rank'],['社区','community'],['话题','topic'],['图集','picture'],['小说','novel'],['有声','audio'],['漫画','comic'],['求片','find'],['合集','compilation'],['粉丝团','club'],['消息','message'],['AI 创作','ai'],['游戏','game']];for(var i=0;i<a.length;i++)d.push({title:a[i][0],url:C.page('tttChannel',{type:a[i][1],title:a[i][0]}),col_type:'text_4',extra:{lineVisible:false}});}
  function channels(){var d=[];setPageTitle('内容频道');channelsBody(d);setResult(d);}
  function comicHome(d){var r=P.call('/api/comic/home',{}),cats=C.comicCategories(r);d.push(U.section('漫画分类',cats.length+' 个分类'));for(var i=0;i<cats.length;i++){var c=cats[i],api=String(c.apiList||''),params=JSON.stringify(c.params||{});d.push(U.category(c.name,C.page('tttChannel',{type:'comicList',title:c.name,comic_api:api,comic_params:params}),!!c.current));}if(!cats.length)responseHint(d,{meta:P.meta(r,'/api/comic/home')});}
  function comicListPage(d,title){var api=String(C.param('comic_api','')||''),raw=String(C.param('comic_params','{}')||'{}'),pg=Number(C.param('p','1')||1),params={};try{params=JSON.parse(raw);}catch(e){}if(!params||typeof params!=='object'||Array.isArray(params))params={};if(params.page==null)params.page=pg;if(!api)api='/api//book/list_filter';var r=P.call(api,params),list=C.comicList(r);try{setItem('ttt_last_comic_list',JSON.stringify({time:Date.now(),api:api,params:params,count:list.length,schema:P.schema(C.dataOf(r))}));}catch(e2){}d.push(U.section(title,list.length+' 部'));for(var i=0;i<list.length;i++)d.push(U.comicCard(C,list[i]));if(!list.length){var m=P.meta(r,api);d.push(U.empty('该分类暂未解析到漫画',(m.code!==''?'code '+m.code+' ':'')+(m.msg||m.schema||'')));}}
  function channelConfig(type){var m={picture:['/api/picture/home',{},''],novel:['/api/novel/home',{},''],audio:['/api/audio/home',{},''],community:['/api/community/home',{page:1},''],rank:['/api/RankList/getPlayRank',{type:'all'},''],creator:['/api/Creator/featured',{page:1,limit:30},''],video:['/api/MvList/featuredAv',{page:1,limit:30},'featured'],short:['/api/MvList/small',{page:1,limit:30},'short'],find:['/api/find/list',{page:1,limit:30},''],compilation:['/api/compilation/list',{page:1,limit:30},''],club:['/api/club/items',{page:1,limit:30},'']};return m[type]||null;}
  function channel(){var d=[],type=C.param('type',''),title=C.param('title','内容频道');setPageTitle(title);try{if(type==='comic'){comicHome(d);setResult(d);return;}if(type==='comicList'){comicListPage(d,title);setResult(d);return;}var cfg=channelConfig(type);if(!cfg){d.push(U.empty(title+' 已纳入架构','后续按原 APP 独立数据模型接入，不使用伪数据'));setResult(d);return;}var f=fetchFeed(cfg[0],cfg[1],cfg[2]);d.push(U.section(title,f.list.length+' 条'));for(var i=0;i<f.list.length;i++)d.push(U.videoCard(C,f.list[i],type==='picture'||type==='novel'?'movie_3':'movie_2'));if(!f.list.length)responseHint(d,f);}catch(e){d.push(U.error(title+' 加载失败',e,C.page('tttSettings')));}setResult(d);}
  function communityBody(d){try{var f=fetchFeed('/api/community/home',{page:1},'');d.push(U.section('社区动态',f.list.length?'已加载 '+f.list.length+' 条':''));for(var i=0;i<f.list.length;i++)d.push(U.videoCard(C,f.list[i],'movie_2'));if(!f.list.length)responseHint(d,f);}catch(e){d.push(U.error('社区加载失败',e,C.page('tttSettings')));}}
  function community(){var d=[];setPageTitle('社区');communityBody(d);setResult(d);}
  function search(){var d=[],kw=String(C.param('kw',getMyVar('ttt_search_kw',''))||'').trim();setPageTitle('搜索');d.push({title:'搜索视频、创作者、关键词',col_type:'input',url:$.toString(function(){var w=String(input||'').trim();if(!w)return'toast://请输入关键词';putMyVar('ttt_search_kw',w);refreshPage(false);return'hiker://empty';}),extra:{defaultValue:kw,titleVisible:true,onChange:$.toString(function(){})}});if(!kw){d.push(U.empty('输入关键词开始搜索'));setResult(d);return;}try{var f=fetchFeed('/api/MvSearch/video',{keyword:kw,page:1,limit:30},'search');d.push(U.section('搜索结果',f.list.length+' 条'));for(var i=0;i<f.list.length;i++)d.push(U.videoCard(C,f.list[i],'movie_2'));if(!f.list.length)responseHint(d,f);}catch(e){d.push(U.error('搜索失败',e,C.page('tttSettings')));}setResult(d);}
  function fallbackFromParams(){return{id:C.param('id',''),title:C.param('title','视频详情'),coverRaw:C.param('coverRaw',''),author:C.param('author','')};}
  function payload(it){return JSON.stringify({title:it.title,sources:C.sources(it)});}
  function bestPlayUrl(it){var src=C.sources(it);if(!src.length)return'';return $('#noLoading#').lazyRule(function(p){try{return $.require('ttt').playBest(p);}catch(e){return'toast://播放解析失败：'+String(e.message||e);}},payload(it));}
  function multiPlayUrl(it){var src=C.sources(it);if(!src.length)return'';return $('#noLoading#').lazyRule(function(p){try{return $.require('ttt').playMulti(p);}catch(e){return'toast://多清晰度解析失败：'+String(e.message||e);}},payload(it));}
  function qualityPlayUrl(it,name){return $('#noLoading#').lazyRule(function(p,n){try{return $.require('ttt').playQuality(p,n);}catch(e){return'toast://播放解析失败：'+String(e.message||e);}},payload(it),name);}
  function detail(){var d=[],fb=fallbackFromParams(),id=fb.id;setPageTitle(fb.title||'视频详情');if(!id){d.push(U.empty('缺少视频 ID'));setResult(d);return;}try{var r=P.call('/api/MvDetail/detail',{id:id}),it=C.detailItem(r,fb),src=C.sources(it),pbest=bestPlayUrl(it);setPageTitle(it.title||fb.title||'视频详情');C.addHistory(it);d.push({title:it.title,desc:[it.author,it.duration,it.plays,it.desc].filter(Boolean).join('\n'),img:it.cover,pic_url:it.cover,url:pbest||'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});d.push(U.chip(src.length?'▶ 立即播放（'+src[src.length-1].name+'）':'未解析到播放线路',src.length>0,pbest||'toast://当前详情没有 source_*','text_2'));d.push(U.chip(C.isFav(id)?'★ 已收藏':'☆ 收藏',C.isFav(id),$('#noLoading#').lazyRule(function(x){var on=$.require('ttt').toggleFavFromDetail(x);refreshPage(false);return'toast://'+(on?'已收藏':'已取消收藏');},JSON.stringify(it)),'text_2'));if(src.length){d.push(U.line());d.push(U.section('清晰度','默认播放按原 APP 使用 240P；需要时可手动切换更高画质'));for(var i=0;i<src.length;i++)d.push(U.chip(src[i].name,false,qualityPlayUrl(it,src[i].name)));if(src.length>1)d.push(U.chip('播放器内切换',false,multiPlayUrl(it)));}d.push(U.line());d.push(U.section('详情信息','ID '+id+(src.length?' · '+src.map(function(x){return x.name;}).join('/'):' · 无播放线路')));if(it.desc)d.push({title:it.desc,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});try{setItem('ttt_last_detail_exact',JSON.stringify({time:Date.now(),id:id,coverRawType:typeof(it.coverRaw),coverCandidate:String(C.imageCandidate(it.coverRaw)||'').substring(0,160),sources:src.map(function(x){return x.name;}),schema:P.schema(C.dataOf(r))}));}catch(e2){}}catch(e){d.push(U.error('详情加载失败',e,C.page('tttSettings')));}setResult(d);}
  function mine(){var d=[],tab=C.param('tab',getMyVar('ttt_mine_tab','fav')||'fav');setPageTitle('我的');d.push(U.chip('收藏',tab==='fav',U.state('ttt_mine_tab','fav'),'text_2'));d.push(U.chip('历史',tab==='history',U.state('ttt_mine_tab','history'),'text_2'));d.push(U.line());var a=tab==='history'?C.histories():C.favs();d.push(U.section(tab==='history'?'观看历史':'我的收藏',a.length+' 条'));for(var i=0;i<a.length;i++)d.push(U.videoCard(C,C.item(a[i]),'movie_2'));if(!a.length)d.push(U.empty(tab==='history'?'还没有观看记录':'还没有收藏'));d.push(U.line());d.push(U.icon('设置','settings',C.page('tttSettings')));setResult(d);}
  function rank(){var d=[],type=C.param('type',getMyVar('ttt_rank_type','all')||'all');setPageTitle('排行榜');var tabs=[['all','总榜'],['daily','日榜'],['weekly','周榜'],['monthly','月榜']];for(var i=0;i<tabs.length;i++)d.push(U.chip(tabs[i][1],type===tabs[i][0],C.page('tttRank',{type:tabs[i][0]})));d.push(U.line());try{var f=fetchFeed('/api/RankList/getPlayRank',{type:type},'');d.push(U.section('播放榜',f.list.length+' 条'));for(var j=0;j<f.list.length;j++)d.push(U.videoCard(C,f.list[j],'movie_2'));if(!f.list.length)responseHint(d,f);}catch(e){d.push(U.error('排行榜加载失败',e,C.page('tttSettings')));}setResult(d);}
  function diagnosticsText(){var keys=['ttt_last_featured_exact','ttt_last_detail_exact','ttt_last_image_link','ttt_last_image_diag','ttt_last_play_sources','ttt_last_play_diag','ttt_last_player_cfg','ttt_last_version_info','ttt_last_comic_home','ttt_last_comic_list','ttt_last_probe','ttt_last_bootstrap'],a=[];for(var i=0;i<keys.length;i++){var v=getItem(keys[i],'');if(v)a.push(keys[i]+'\n'+v);}return a.join('\n\n')||'暂无诊断记录';}
  function settings(){var d=[],s=P.sessionInfo();setPageTitle('设置与诊断');d.push(U.section('汤头条 Test','0.1.0-test.6 · APK 基线 9.6.2'));d.push({title:'运行状态',desc:'设备 '+(s.deviceReady?'已建立':'未建立')+'｜Token '+(s.tokenReady?'已建立':'未建立')+'｜播放器密钥 '+(s.playerReady?'已取得':'未取得')+'｜模拟版本 '+s.version+(s.serverVersion?' / 服务端 '+s.serverVersion:''),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行协议诊断',desc:'启动握手 + 推荐 + 短视频 + 排行榜',url:$('#noLoading#').lazyRule(function(){try{var a=$.require('ttt').protocolProbe();refreshPage(false);return'toast://诊断完成：'+a.filter(function(x){return x.ok;}).length+'/'+a.length+' 成功';}catch(e){return'toast://诊断失败：'+e;} }),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'最近诊断（直接显示）',desc:'图片入口 / 版本握手 / 播放 / 漫画动态路由 / 会话',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:diagnosticsText(),url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});d.push({title:'重新初始化匿名身份',desc:'清 Token/设备身份/播放器配置/版本覆盖并重新握手',url:$('#noLoading#').lazyRule(function(){try{$.require('ttt').resetSession(true);return'toast://已重建，返回首页会自动重新握手';}catch(e){return'toast://重建失败：'+e;} }),col_type:'text_1',extra:{lineVisible:false}});d.push(U.line());d.push(U.section('Test6 主链','封面改用海阔官方 $(url,headers).image + $.require 解密入口；启动后自动跟随 versionMsg.version 再握手，默认播放回归 APP 的 source_240；漫画完全使用服务器 api_list/params_list；排行榜补齐 type。'));setResult(d);}
  return{home:home,channels:channels,channel:channel,community:community,search:search,detail:detail,mine:mine,rank:rank,settings:settings};
})();
