/* Hanime1 Test31 selector hardening before device validation */
(function(C,P){
function clean(v){return C.clean(String(v==null?'':v));}
function nodes(html,sel){try{return pdfa(String(html||''),sel)||[];}catch(e){return [];}}
function text(node,sel){try{return clean(pdfh(node,sel)||'');}catch(e){return '';}}
function attr(node,sel){try{return String(pdfh(node,sel)||'').replace(/&amp;/g,'&').trim();}catch(e){return '';}}
function firstText(node,sels){for(var i=0;i<sels.length;i++){var v=text(node,sels[i]);if(v)return v;}return '';}
function firstAttr(node,sels){for(var i=0;i<sels.length;i++){var v=attr(node,sels[i]);if(v)return v;}return '';}
function abs(base,u){u=String(u||'').trim();return u?C.abs(base,u):'';}
function replyId(w){var m=String(w||'').match(/\bid\s*=\s*(["'])reply-section-wrapper-([^"']+)\1/i);return m?m[2]:'';}
function replyCount(w){var s=firstText(w,['div.load-replies-btn&&Text','.load-replies-btn&&Text']),m=String(s||'').match(/\d+/);return m?parseInt(m[0],10)||0:0;}
var baseComments=P.comments;
P.comments=function(videoId){var r=baseComments(videoId),items=(r&&r.items)||[];if(!items.length)return r;try{var base=C.resolveHost(false),x=C.get(C.query(base+'/loadComment',{type:'video',id:videoId}),{base:base,referer:base+'/watch?v='+videoId,timeout:14000});if(x&&!x.challenge&&Number(x.statusCode||0)<400&&String(x.body||'')){var raw=String(x.body||''),body=raw;try{var j=JSON.parse(raw);if(j&&typeof j.comments==='string')body=j.comments;}catch(e){}var children=nodes(body,'#comment-start > *'),groups=[];for(var i=0;i<children.length;i+=4){var g=children.slice(i,i+4);if(g.length)groups.push('<div>'+g.join('')+'</div>');}if(groups.length===items.length){for(var k=0;k<items.length;k++){var id=replyId(groups[k]);if(id)items[k].id=id;var rc=replyCount(groups[k]);if(rc||items[k].replyCount)items[k].replyCount=rc;}}}}catch(e){}return r;};
function videoId(u){var m=String(u||'').match(/[?&]v=(\d+)/);return m?m[1]:'';}
function videoCard(n,base){var href=firstAttr(n,['a[href*=watch]&&href','[data-href]&&data-href']),id=videoId(href),title=firstText(n,['.video-title&&Text','.title&&Text','img.main-thumb&&alt','img&&alt']),img=firstAttr(n,['img.main-thumb&&src','img&&data-src','img&&src']);if(!id)return null;return {id:id,title:title||('影片 '+id),img:abs(base,img),artist:firstText(n,['.meta-author a&&Text','.subtitle a&&Text']),duration:firstText(n,['.duration&&Text']),views:firstText(n,['.stats-container&&Text']),upload:firstText(n,['.meta-stats span&&Text'])};}
function videoList(h,base){var a=nodes(h,'.playlist-video-list > div.user-tab-item-wrapper'),out=[],seen={};if(!a.length)a=nodes(h,'.user-tab-item-wrapper');for(var i=0;i<a.length;i++){var x=videoCard(a[i],base);if(x&&x.id&&!seen[x.id]){seen[x.id]=1;out.push(x);}}return out;}
function playlistCards(h,base){var a=nodes(h,'.user-tab-item-wrapper,.playlist-item-wrapper,.playlist-card'),out=[],seen={};for(var i=0;i<a.length;i++){var href=firstAttr(a[i],['a.video-link&&href','a[href*="playlist?list="]&&href','a[href*=playlist]&&href']),m=String(href||'').match(/[?&]list=([^&]+)/),id=m?m[1]:'',title=firstText(a[i],['.title&&Text','.playlist-title&&Text']);if(!id||!title||seen[id])continue;seen[id]=1;out.push({id:id,title:title,count:firstText(a[i],['.stat-item&&Text','.playlist-count&&Text']),img:abs(base,firstAttr(a[i],['img.main-thumb&&src','img&&src']))});}return out;}
P.playlist=function(id,sort){var base=C.resolveHost(false),url=C.query(base+'/playlist',{list:id,sort:sort||'latest',page:1}),r=C.get(url,{base:base,referer:base+'/',timeout:15000});if(!r||r.challenge||Number(r.statusCode||0)>=400)throw new Error('片单详情请求失败：HTTP '+Number((r&&r.statusCode)||0));var h=String(r.body||'');return {id:String(id),title:firstText(h,['.playlist-title&&Text'])||'片单',desc:firstText(h,['.playlist-description&&Text']),author:firstText(h,['.playlist-author-info a&&Text']),cover:abs(base,firstAttr(h,['.playlist-main-thumbnail&&src'])),count:firstText(h,['#sidebar-video-count&&Text']),views:firstText(h,['.playlist-stats&&Text']),items:videoList(h,base),csrf:firstAttr(h,['meta[name=csrf-token]&&content','input[name=_token]&&value'])};};
var baseSection=P.librarySection30;
P.librarySection30=function(kind){if(kind!=='playlists')return baseSection(kind);var a=C.activeAccount();if(!a)throw new Error('请先登录');var base=C.resolveHost(false),url=base+'/user/'+String(a.id||'')+'/playlists',r=C.get(url,{base:base,referer:base+'/',timeout:15000});if(!r||r.challenge||Number(r.statusCode||0)>=400)throw new Error('账号片单加载失败：HTTP '+Number((r&&r.statusCode)||0));return {playlists:playlistCards(String(r.body||''),base),items:[]};};
})(HanimeCore,HanimeProvider);