/* MDAI content pages 2.7.0-test.1 */
var MDAIContentPagesV270=(function(){
  var U=MDAIUIBaseV270,D=U.design;
  function header(c,d){
    d.push({title:'搜索',col_type:'input',url:$.toString(function(){var w=String(input||'').trim();if(!w)return'toast://请输入关键词';putMyVar('keyword',w);$.require('mdai').saveSearchWord(w);return'hiker://page/mdaiSearch?rule=&simple=true&kw='+encodeURIComponent(w);}),extra:{defaultValue:'',titleVisible:true,onChange:$.toString(function(){})}});
    U.nav(c,d,'短剧','drama');U.nav(c,d,'最新','recent');U.nav(c,d,'原创','menu1');U.nav(c,d,'国产','menu2');U.nav(c,d,'社区','posts');d.push(U.blank());
    U.quick(d,'片库',D.icons.library,U.page('mdaiLibrary'));U.quick(d,'收藏',D.icons.fav,U.page('mdaiMine',{mode:'favorites'}));U.quick(d,'历史',D.icons.history,U.page('mdaiMine',{mode:'history'}));U.quick(d,'设置',D.icons.settings,U.page('mdaiSettings'));d.push(U.line());
  }
  function dramas(c,d,pg){if(pg>1)return;var h=c.payload(c.request('/api/v1/short-dramas/home?productId=1'))||{},banner=Array.isArray(h.banner)?h.banner:[],chase=Array.isArray(h.chaseRank)?h.chaseRank:[],featured=Array.isArray(h.featured)?h.featured:[];
    if(banner.length){d.push(U.section(c,'今日精选','AI 短剧'));var x=banner[0],cv=U.cover(c,x);d.push({title:U.title(c,x),desc:U.meta(c,x,'drama'),img:cv,pic_url:cv,url:U.detailUrl(c,x,'drama'),col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false}});banner.slice(1,4).forEach(function(v){d.push(U.card(c,v,'drama','movie_3'));});d.push(U.line());}
    if(chase.length){d.push(U.section(c,'热门追剧','热度上升',U.page('mdaiLibrary',{type:'drama',sort:'heat'})));chase.slice(0,6).forEach(function(v){d.push(U.card(c,v,'drama','movie_3'));});d.push(U.line());}
    if(featured.length){d.push(U.section(c,'编辑精选','近期推荐'));featured.slice(0,6).forEach(function(v){d.push(U.card(c,v,'drama','movie_3'));});}
    if(!banner.length&&!chase.length&&!featured.length)d.push(U.empty('暂时没有短剧推荐','可以进入片库查看完整内容'));
  }
  function recent(c,d,pg){if(pg===1)d.push(U.section(c,'最近更新','按发布时间'));var a=c.items(c.request(c.buildVideoPath('',pg,c.pageSize(),false)));a.forEach(function(x){d.push(U.card(c,x,'video','movie_2'));});if(!a.length&&pg===1)d.push(U.empty('暂无最近更新'));}
  function channel(c,d,menu,pg){if(pg>1)return;var cats=c.getCategories('video').filter(function(x){return parseInt(x.menuId)===parseInt(menu);}),shown=0;d.push(U.section(c,menu===1?'原创精选':'国产视频','按主题浏览',U.page('mdaiLibrary',{menu:String(menu)})));for(var i=0;i<cats.length&&shown<4;i++){var cat=cats[i],a=[];try{a=c.items(c.request('/api/v1/videos?categoryId='+U.enc(cat.id)+'&page=1&size=4'));}catch(e){}if(!a.length)continue;d.push(U.section(c,cat.name,'精选 '+a.length+' 条',U.page('mdaiLibrary',{menu:String(menu),cat:String(cat.id)})));a.slice(0,4).forEach(function(x){d.push(U.card(c,x,'video','movie_2'));});shown++;if(shown<4)d.push(U.blank());}if(!shown)d.push(U.empty('当前频道暂无内容'));}
  function posts(c,d,pg){if(pg===1)d.push(U.section(c,'社区动态','最新帖子'));var a=c.items(c.request('/api/v1/posts?page='+pg+'&size=20&sort=latest'));a.forEach(function(x){var imgs=Array.isArray(x.images)?x.images:[],cv=c.image(x.coverUrl||x.cover||(imgs[0]||'')),desc=c.cleanText(x.content||x.description||'').replace(/\n+/g,' ');if(desc.length>46)desc=desc.slice(0,46)+'…';d.push({title:U.title(c,x),desc:desc,img:cv,pic_url:cv,url:U.detailUrl(c,x,'post'),col_type:'movie_1_left_pic',extra:{lineVisible:false}});});if(!a.length&&pg===1)d.push(U.empty('暂无社区内容'));}
  function home(c){var d=[],pg=MY_PAGE||1;try{if(pg===1)header(c,d);var t=getMyVar('mdai_home_tab_v270','drama');if(t==='drama')dramas(c,d,pg);else if(t==='recent')recent(c,d,pg);else if(t==='menu1')channel(c,d,1,pg);else if(t==='menu2')channel(c,d,2,pg);else posts(c,d,pg);}catch(e){d.push(U.empty('页面加载失败',String(e.message||e)));if(pg===1)d.push({title:'打开设置',url:U.page('mdaiSettings'),col_type:'text_center_1'});}setResult(d);}
  function library(c){var d=[],pg=MY_PAGE||1,type=U.qp('type','video');try{if(type==='drama'){var sort=U.qp('sort','heat');if(pg===1){setPageTitle('短剧片库');d.push(U.section(c,'短剧片库','完整内容'));['heat','latest'].forEach(function(v){var on=sort===v;d.push({title:on?'““'+(v==='heat'?'热播':'最新')+'””':(v==='heat'?'热播':'最新'),url:U.page('mdaiLibrary',{type:'drama',sort:v}),col_type:'scroll_button',extra:{backgroundColor:on?D.brand:'',lineVisible:false}});});d.push(U.line());}var dl=c.items(c.request('/api/v1/short-dramas?productId=1&sortBy='+U.enc(sort)+'&page='+pg+'&size='+Math.min(c.pageSize(),30)));dl.forEach(function(x){d.push(U.card(c,x,'drama','movie_3'));});if(!dl.length&&pg===1)d.push(U.empty('暂无短剧数据'));setResult(d);return;}
      var menu=U.qp('menu','1'),cat=U.qp('cat','');if(pg===1){setPageTitle('视频片库');d.push(U.section(c,'视频片库','分类浏览'));[['1','原创'],['2','国产'],['3','字幕']].forEach(function(a){var on=String(menu)===a[0];d.push({title:on?'““'+a[1]+'””':a[1],url:U.page('mdaiLibrary',{menu:a[0]}),col_type:'scroll_button',extra:{backgroundColor:on?D.brand:'',lineVisible:false}});});d.push(U.blank());var cats=c.getCategories('video').filter(function(x){return String(x.menuId)===String(menu);});d.push({title:!cat?'““全部””':'全部',url:U.page('mdaiLibrary',{menu:menu}),col_type:'flex_button',extra:{backgroundColor:!cat?D.brand:'',lineVisible:false}});cats.forEach(function(x){var on=String(cat)===String(x.id);d.push({title:on?'““'+x.name+'””':x.name,url:U.page('mdaiLibrary',{menu:menu,cat:String(x.id)}),col_type:'flex_button',extra:{backgroundColor:on?D.brand:'',lineVisible:false}});});d.push(U.line());}
      var a=c.items(c.request(c.buildVideoPath(cat,pg,c.pageSize(),true)));a.forEach(function(x){d.push(U.card(c,x,'video','movie_2'));});if(!a.length&&pg===1)d.push(U.empty('当前筛选暂无内容','切换分类后再试'));}catch(e){d.push(U.empty('片库加载失败',String(e.message||e)));}setResult(d);}
  function search(c){var d=[],pg=MY_PAGE||1,kw=String(U.qp('kw',getMyVar('keyword',''))||'').trim();if(kw)putMyVar('keyword',kw);try{if(pg===1){setPageTitle('搜索');d.push({title:'搜索',col_type:'input',url:$.toString(function(){var w=String(input||'').trim();if(!w)return'toast://请输入关键词';putMyVar('keyword',w);$.require('mdai').saveSearchWord(w);return'hiker://page/mdaiSearch?rule=&simple=true&kw='+encodeURIComponent(w);}),extra:{defaultValue:kw,titleVisible:true,onChange:$.toString(function(){})}});}if(!kw){if(pg===1){try{var hot=c.payload(c.request('/api/v1/hot-searches?period=recent'));if(Array.isArray(hot)&&hot.length){d.push(U.section(c,'热门搜索','官方趋势'));hot.slice(0,10).forEach(function(x){d.push({title:c.cleanText(x.name),url:U.page('mdaiSearch',{kw:x.name}),col_type:'flex_button'});});d.push(U.line());}}catch(e){}var his=c.readList(c.searchKey);if(his.length){d.push(U.section(c,'最近搜索','本地记录'));his.slice(0,10).forEach(function(w){d.push({title:c.maskText(w),url:U.page('mdaiSearch',{kw:w}),col_type:'flex_button'});});}else d.push(U.empty('输入关键词开始搜索'));}setResult(d);return;}if(pg===1){c.saveSearchWord(kw);d.push(U.section(c,'搜索结果','“'+c.maskText(kw)+'”'));}var a=c.items(c.request('/api/v1/videos/search?q='+U.enc(kw)+'&page='+pg+'&size='+c.pageSize()));a.forEach(function(x){d.push(U.card(c,x,'video','movie_2'));});if(!a.length&&pg===1)d.push(U.empty('没有找到相关内容','尝试更短的关键词'));}catch(e){d.push(U.empty('搜索失败',String(e.message||e)));}setResult(d);}
  function mine(c){var d=[],mode=U.qp('mode','favorites');setPageTitle('我的');['favorites','history'].forEach(function(v){var on=mode===v;d.push({title:on?'““'+(v==='favorites'?'收藏':'历史')+'””':(v==='favorites'?'收藏':'历史'),url:U.page('mdaiMine',{mode:v}),col_type:'text_2',extra:{backgroundColor:on?D.brand:'',lineVisible:false}});});d.push(U.line());var key=mode==='favorites'?c.favKey:c.historyKey,a=c.readList(key);d.push(U.section(c,mode==='favorites'?'我的收藏':'观看历史',a.length+' 条'));if(!a.length)d.push(U.empty(mode==='favorites'?'还没有收藏内容':'还没有观看记录'));else{d.push({title:'清空'+(mode==='favorites'?'收藏':'历史'),url:'confirm://确认清空吗？.js:'+$.toString(function(k){setItem(k,'[]');refreshPage(false);return'toast://已清空';},key),col_type:'scroll_button'});d.push(U.blank());a.forEach(function(x){d.push(U.localCard(c,x));});}setResult(d);}
  function comments(c){var d=[],pg=MY_PAGE||1,target=U.qp('target','video'),id=U.qp('id',''),title=U.qp('title','评论');if(pg===1){setPageTitle(c.shortTitle(title,14)+' · 评论');d.push(U.section(c,'评论区',target==='post'?'帖子讨论':'视频讨论'));}try{var p=target==='post'?'/api/v1/comments?postId='+U.enc(id)+'&page='+pg+'&size=20':'/api/v1/comments?videoId='+U.enc(id)+'&page='+pg+'&size=20',a=c.items(c.request(p));a.forEach(function(x){d.push({title:c.cleanText(x.authorName||x.username||'匿名用户'),desc:c.fmtDate(x.createdAt||''),img:D.icons.user,url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false}});d.push({title:c.cleanText(x.content||''),url:'hiker://empty',col_type:'rich_text',extra:{lineVisible:false,textSize:16,lineSpacing:5}});});if(!a.length&&pg===1)d.push(U.empty('暂无评论'));}catch(e){d.push(U.empty('评论加载失败',String(e.message||e)));}setResult(d);}
  return{version:'2.7.0-test.1',home:home,library:library,search:search,mine:mine,comments:comments};
})();
