/* Hanime1 Test14 detail and comments without backslash syntax */
(function(C,P,E,H,U,L){
var pv=H.pv,route=H.route,sec=H.sec,chip=H.chip,btn=H.btn;
function playUrl(id){return $('#noLoading#').lazyRule(function(x){return $.require('hanime').play(x);},id);}
function person(d,title,name,id,img,kind){if(!name)return;var u=id?route('hanimeAuthor',{id:id,name:name,kind:kind}):route('hanimeVideoResults',{query:name});d.push({title:name,desc:title+' · 点击查看主页/作品',pic_url:img||'',url:u,col_type:'avatar',extra:{lineVisible:false}});}
E.detail=function(){try{var id=pv('id','');if(!id)throw new Error('缺少视频 ID');var v=P.video(id),d=[],top=(v.sources&&v.sources.length)?String(v.sources[0].quality||'最高'):'待解析',nl=String.fromCharCode(10);setPageTitle(v.title);d.push({title:v.title,desc:[v.genre,v.views?('观看 '+v.views):'',v.upload].filter(Boolean).join(nl),pic_url:v.cover||'',url:playUrl(id),col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false,inheritTitle:false,pageTitle:v.title}});d.push({title:'播放 · '+top,url:playUrl(id),col_type:'text_3',extra:{lineVisible:false,pageTitle:v.title}});d.push({title:'评论'+(v.commentCount!==undefined?' · '+v.commentCount:''),url:route('hanimeComments',{id:id,title:v.title}),col_type:'text_3',extra:{lineVisible:false}});d.push({title:v.download?'下载原片':'更多信息',url:v.download?('download://'+v.download):'hiker://empty',col_type:'text_3',extra:{lineVisible:false}});var pl=v.playlist||[];if(pl.length>1){d.push(sec('选集 · '+pl.length,'点击集数直接播放'));for(var p=0;p<pl.length;p++){var x=pl[p],sel=String(x.id)===String(id);d.push({title:(sel?'▶ ':'')+U.epLabel(x,p),url:playUrl(x.id),col_type:'scroll_button',extra:{lineVisible:false,pageTitle:x.title||v.title}});}d.push({col_type:'line_blank'});}d.push(sec('作者与上传者','官网将作者与实际上传账号分开显示'));person(d,'作者',v.artist,v.artistId,v.artistAvatar,'author');if(v.uploader&&String(v.uploader)!==String(v.artist))person(d,'上传者',v.uploader,v.uploaderId,v.uploaderAvatar,'uploader');d.push(sec('作品信息'));if(v.genre)d.push(chip('类型 · '+v.genre,route('hanimeVideoResults',{genre:v.genre})));if(v.views)d.push(chip('观看 · '+v.views,'hiker://empty'));if(v.upload)d.push(chip('上传 · '+v.upload,'hiker://empty'));if(v.duration)d.push(chip('时长 · '+v.duration,'hiker://empty'));if(v.commentCount!==undefined)d.push(chip('评论 · '+v.commentCount,route('hanimeComments',{id:id,title:v.title})));if(v.caption)d.push({title:'作品简介',desc:v.caption,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false,textSize:16}});if(v.tags&&v.tags.length){d.push(sec('内容标签',v.tags.length+' 个 · 点击直接筛选同标签影片'));for(var i=0;i<v.tags.length;i++){var tg=v.tags[i];d.push(chip(tg.name+(tg.count?' · '+tg.count:''),route('hanimeVideoResults',{tag:tg.name})));}}if(v.sources&&v.sources.length)d.push(sec('可用画质','默认优先最高画质 · '+v.sources.map(function(s){return s.quality||'默认';}).join(' / ')));if(v.related&&v.related.length){d.push(sec('相关推荐',v.related.length+' 部'));for(var j=0;j<v.related.length;j++)d.push(L.video(v.related[j],'related'));}setResult(d);}catch(x){setResult([{title:'详情加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
function compose(id,logged){if(!logged)return route('hanimeLogin',{});var q=String.fromCharCode(39),js='if(!input)return '+q+'toast://评论不能为空'+q+';try{$.require('+q+'hanime'+q+').provider().postComment('+q+id+q+',input);refreshPage(false);return '+q+'toast://评论已发布'+q+';}catch(e){return '+q+'toast://'+q+'+String(e.message||e);}';return 'input://'+JSON.stringify({value:'',hint:'写下你的评论',js:js});}
function commentCard(d,c){var meta=[c.time,c.likes?('赞 '+c.likes):'',c.replyCount?('回复 '+c.replyCount):''].filter(Boolean).join(' · '),u=c.id?route('hanimeReplies',{id:c.id,user:c.user}):'hiker://empty';d.push({title:c.user||'匿名用户',desc:meta,pic_url:c.avatar||'',url:u,col_type:'avatar',extra:{lineVisible:false}});d.push({title:c.content||'',url:u,col_type:'long_text',extra:{lineVisible:false,textSize:16}});if(c.replyCount)d.push({title:'查看 '+c.replyCount+' 条回复',url:u,col_type:'text_1',extra:{lineVisible:false}});d.push({col_type:'line'});}
E.commentsPage=function(){try{var id=pv('id',''),t=pv('title','视频'),r=P.comments(id),d=[],logged=false,page=Number(pv('page','1')||1),size=15;try{logged=!!P.profile();}catch(e){}setPageTitle('评论');d.push(sec(t,'共 '+r.items.length+' 条 · 第 '+page+' 页'));d.push(btn(logged?'发表评论':'登录后发表评论',compose(id,logged),'text_center_1'));var start=(page-1)*size,end=Math.min(r.items.length,start+size);for(var i=start;i<end;i++)commentCard(d,r.items[i]);if(page>1)d.push(btn('上一页',route('hanimeComments',{id:id,title:t,page:page-1})));if(end<r.items.length)d.push(btn('下一页',route('hanimeComments',{id:id,title:t,page:page+1})));if(!r.items.length)d.push(sec('暂无评论'));setResult(d);}catch(x){setResult([{title:'评论加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
function replyInput(id,logged){if(!logged)return route('hanimeLogin',{});var q=String.fromCharCode(39),js='if(!input)return '+q+'toast://回复不能为空'+q+';try{$.require('+q+'hanime'+q+').provider().replyComment('+q+id+q+',input);refreshPage(false);return '+q+'toast://回复已发布'+q+';}catch(e){return '+q+'toast://'+q+'+String(e.message||e);}';return 'input://'+JSON.stringify({value:'',hint:'输入回复内容',js:js});}
E.repliesPage=function(){try{var id=pv('id',''),u=pv('user','回复'),a=P.replies(id),d=[],logged=false;try{logged=!!P.profile();}catch(e){}setPageTitle(u+' · 回复');d.push(sec(u,'共 '+a.length+' 条回复'));d.push(btn(logged?'回复此评论':'登录后回复',replyInput(id,logged),'text_center_1'));for(var i=0;i<a.length;i++)commentCard(d,a[i]);if(!a.length)d.push(sec('暂无回复'));setResult(d);}catch(x){setResult([{title:'回复加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeUI10,HanimeLayout12);
