/* Hanime1 Test37 creator: square 3-column directory + text row, stronger image parsing */
(function(C,P,E,H){
var oldResults=E.videoResultsPage;
function clean(v){return C.clean(String(v==null?'':v));}
function xa(html,path){try{if(typeof xpathArray==='function')return xpathArray(String(html||''),path)||[];if(typeof xpa==='function')return xpa(String(html||''),path)||[];}catch(e){}return [];}
function first(a){return a&&a.length?String(a[0]||'').replace(/&amp;/g,'&').trim():'';}
function abs(base,u){return u?C.abs(base,String(u).trim()):'';}
function route(type,o){o=o||{};o.creatorType=type;return H.route('hanimeVideoResults',o);}
function fallback(){return 'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/hanime1/assets/hanime1_official.svg';}
function parseArtists(h,base){var cards=xa(h,'//*[contains(concat(" ",normalize-space(@class)," ")," search-artist-card ")]'),out=[],seen={};for(var i=0;i<cards.length;i++){var g='<div>'+cards[i]+'</div>',name=clean(first(xa(g,'//*[contains(concat(" ",normalize-space(@class)," ")," search-artist-title ")][1]//text()'))),img=first(xa(g,'//img[1]/@src'))||first(xa(g,'//img[1]/@data-src'))||first(xa(g,'//img[1]/@data-original')),href=first(xa(g,'//a[contains(@href,"type=artist") or contains(@href,"query=")][1]/@href')),q='';try{q=decodeURIComponent((String(href).match(/[?&]query=([^&]+)/)||[])[1]||'');}catch(e){}var cnt=clean(first(xa(g,'//*[contains(concat(" ",normalize-space(@class)," ")," search-artist-count ")][1]//text()')));if(name&&!seen[name]){seen[name]=1;out.push({name:name,avatar:abs(base,img),query:q||name,count:cnt});}}return out;}
var oldDir=P.artistDirectory28;
P.artistDirectory28=function(query,page){var q=clean(query),p=Number(page||1);if(q){try{var base=C.resolveHost(false),url=C.query(base+'/search',{page:p,query:q,type:'artist'}),r=C.get(url,{base:base,referer:base+'/',timeout:15000});if(r&&!r.challenge&&Number(r.statusCode||0)<400){var items=parseArtists(String(r.body||''),base);if(items.length)return {items:items,page:p,totalPages:p,query:q};}}catch(e){}}return oldDir(query,page);};
function videoCard(x){return {title:x.title||'未命名',desc:[x.duration,x.views,x.artist].filter(Boolean).join(' · '),pic_url:x.img||x.cover||'',url:H.route('hanimeDetail',{id:x.id,title:x.title||''}),col_type:'movie_2',extra:{lineVisible:false}};}
function header(d,name,avatar,role,meta,url){d.push({title:name||role,desc:[role,meta].filter(Boolean).join(' · '),pic_url:avatar||fallback(),url:url||'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false,inheritTitle:false}});}
function inputUrl(q){return 'input://'+JSON.stringify({value:q||'',hint:'输入作者 / 制作商名称',js:"putMyVar('hanime37_artist_q',input);refreshPage(false);return 'hiker://empty';"});}
function directory(){var q=H.pv('query',getMyVar('hanime37_artist_q','')),page=Number(H.pv('page','1')||1),r=P.artistDirectory28(q,page),list=r.items||[],d=[];setPageTitle('作者目录');d.push({title:'搜索作者',url:inputUrl(q),col_type:'input',extra:{hint:'输入作者 / 制作商名称',defaultValue:q,lineVisible:false}});d.push(H.sec(q?('作者搜索 · '+q):'作者目录','第 '+page+' 页 · '+list.length+' 位'));for(var i=0;i<list.length;i+=3){var row=list.slice(i,i+3),j;for(j=0;j<3;j++){var x=row[j];if(x)d.push({title:'',pic_url:x.avatar||fallback(),url:route('artist',{creatorName:x.name,creatorQuery:x.query||x.name,creatorAvatar:x.avatar||'',creatorCount:x.count||''}),col_type:'pic_3_square',extra:{lineVisible:false}});else d.push({title:'',url:'hiker://empty',col_type:'pic_3_square'});}for(j=0;j<3;j++){var y=row[j];if(y)d.push({title:y.name,desc:y.count||'查看作品',url:route('artist',{creatorName:y.name,creatorQuery:y.query||y.name,creatorAvatar:y.avatar||'',creatorCount:y.count||''}),col_type:'text_3',extra:{lineVisible:false}});else d.push({title:'',url:'hiker://empty',col_type:'text_3'});}}if(page>1)d.push(H.btn('‹ 上一页',route('directory',{query:q,page:page-1})));if(page<Number(r.totalPages||page))d.push(H.btn('下一页 ›',route('directory',{query:q,page:page+1})));setResult(d);}
function artist(){var page=Number(H.pv('page','1')||1),name=H.pv('creatorName',''),query=H.pv('creatorQuery','')||name,avatar=H.pv('creatorAvatar',''),count=H.pv('creatorCount','');if(!name)throw new Error('缺少作者名称');var r=P.search({query:query,page:page,type:''}),list=r.items||[],d=[];setPageTitle(name);header(d,name,avatar,'作者',count||('第 '+page+' 页'));d.push(H.sec('影片',list.length?('第 '+page+' 页 · '+list.length+' 部'):'暂无作品'));for(var i=0;i<list.length;i++)d.push(videoCard(list[i]));if(page>1)d.push(H.btn('‹ 上一页',route('artist',{creatorName:name,creatorQuery:query,creatorAvatar:avatar,creatorCount:count,page:page-1})));if(page<Number(r.totalPages||page))d.push(H.btn('下一页 ›',route('artist',{creatorName:name,creatorQuery:query,creatorAvatar:avatar,creatorCount:count,page:page+1})));setResult(d);}
function uploader(){var page=Number(H.pv('page','1')||1),id=H.pv('userId',''),seed=H.pv('creatorName','')||H.pv('userName',''),seedAvatar=H.pv('creatorAvatar','');if(!id)throw new Error('缺少上传者 ID');var r=P.userUploads17(id,seed,page),name=r.name||seed||('用户 '+id),avatar=r.avatar||seedAvatar,d=[],list=r.items||[];setPageTitle(name);header(d,name,avatar,'上传者','公开上传 · 第 '+page+' 页',r.url);d.push(H.sec('影片',list.length?('第 '+page+' 页 · '+list.length+' 部'):'暂无公开作品'));for(var i=0;i<list.length;i++)d.push(videoCard(list[i]));if(page>1)d.push(H.btn('‹ 上一页',route('uploader',{userId:id,creatorName:name,creatorAvatar:avatar,page:page-1})));if(page<Number(r.totalPages||page))d.push(H.btn('下一页 ›',route('uploader',{userId:id,creatorName:name,creatorAvatar:avatar,page:page+1})));setResult(d);}
E.videoResultsPage=function(){var type=H.pv('creatorType','');try{if(type==='directory')return directory();if(type==='artist')return artist();if(type==='uploader')return uploader();return oldResults();}catch(x){setResult([{title:'创作者页面加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9);
