/* Hanime1 Test37 search: compact home + fixed native search handoff */
(function(P,E,H,L){
var ROOT='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/hanime1/assets/icons/';
function icon(n,on){return ROOT+n+(on?'_active':'')+'.svg?v=37';}
function tab(title,id,cur,ico){return {title:title,pic_url:icon(ico,cur===id),url:$('#noLoading#').lazyRule(function(v){putMyVar('hanime10_tab',v);refreshPage(false);return 'hiker://empty';},id),col_type:'icon_5_no_crop',extra:{lineVisible:false}};}
function featured(d,x){if(!x||!x.id)return;d.push(H.sec('精选推荐'));d.push({title:x.title||'推荐影片',desc:x.meta||[x.artist,x.views].filter(Boolean).join(' · '),pic_url:x.img||x.cover||'',url:H.route('hanimeDetail',{id:x.id,title:x.title}),col_type:'movie_1_left_pic',extra:{lineVisible:false}});}
function feed(d){var h=P.home();featured(d,h.featured);for(var i=0;i<h.sections.length;i++){var s=h.sections[i],list=s.items||[];d.push(H.sec(s.title||'推荐',list.length+' 部'));for(var j=0;j<Math.min(12,list.length);j++)d.push(L.video(list[j],'home'));if(i<h.sections.length-1)d.push({col_type:'line_blank'});}}
function comics(d){d.push({title:'标签',url:H.route('hanimeComicFilter',{path:'/comics/tags'}),col_type:'scroll_button'});d.push({title:'作者',url:H.route('hanimeComicFilter',{path:'/comics/artists'}),col_type:'scroll_button'});d.push({title:'角色',url:H.route('hanimeComicFilter',{path:'/comics/characters'}),col_type:'scroll_button'});d.push({title:'同人',url:H.route('hanimeComicFilter',{path:'/comics/parodies'}),col_type:'scroll_button'});d.push({title:'社团',url:H.route('hanimeComicFilter',{path:'/comics/groups'}),col_type:'scroll_button'});d.push({col_type:'line_blank'});var h=P.comicHome();d.push(H.sec('热门漫画',(h.hot||[]).length+' 部'));for(var i=0;i<Math.min(12,(h.hot||[]).length);i++)d.push(L.comic(h.hot[i],'comicHome'));d.push(H.sec('最新漫画',(h.latest||[]).length+' 部'));for(var j=0;j<(h.latest||[]).length;j++)d.push(L.comic(h.latest[j],'comicHome'));}
E.home=function(){try{setPageTitle('Hanime1');var d=[],page=Number(MY_PAGE||1),cur=getMyVar('hanime10_tab','home');if(page===1){d.push({title:'搜索',url:"if(!input)return 'hiker://empty';putMyVar('hanime2_search_q',String(input));return 'hiker://page/hanimeSearch?rule=&simple=true';",col_type:'input',extra:{hint:'搜索影片 / 作者',defaultValue:'',lineVisible:false}});d.push(tab('推荐','home',cur,'recommend'));d.push(tab('片库','library',cur,'library'));d.push(tab('漫画','comic',cur,'comic'));d.push(tab('我的','my',cur,'account'));d.push(tab('设置','settings',cur,'settings'));d.push({col_type:'line_blank'});}if(cur==='home')feed(d);else if(cur==='library')E.renderLibrary(d,page);else if(cur==='comic')comics(d);else if(cur==='my')E.renderMy(d);else E.renderSettings(d);setResult(d);}catch(x){setResult([{title:'Hanime1 加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.shellSearch=function(){try{var q='';try{q=getParam('kw')||getParam('q')||'';}catch(e){}try{if(!q&&typeof KEY!=='undefined')q=KEY||'';}catch(e2){}q=String(q||'').trim();if(q)putMyVar('hanime2_search_q',q);return E.searchPage();}catch(x){setResult([{title:'搜索失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);
