/* 麻豆AI Bootstrap 2.9.0-test.2 - Native Local-First */
var MDAI_BOOT_VERSION='2.9.0-test.2';
var MDAIBoot=(function(){
  var MANAGER_URLS=[
    'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/e06542e60677d5505e7383435b17cb69ec7a21ba/libs/updater/v2.2.0/local_module_manager.js',
    'https://github.com/huoguotiankong/asset-core-7f3/raw/e06542e60677d5505e7383435b17cb69ec7a21ba/libs/updater/v2.2.0/local_module_manager.js',
    'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@e06542e60677d5505e7383435b17cb69ec7a21ba/libs/updater/v2.2.0/local_module_manager.js'
  ];
  var C={id:'mdai-test',timeout:8000,repoTemplates:[
    'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/{ref}/{path}',
    'https://github.com/huoguotiankong/asset-core-7f3/raw/{ref}/{path}',
    'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@{ref}/{path}'
  ]};
  var R={"schema":1,"id":"mdai-test","name":"麻豆AI","version":"2.9.0-test.2","build":29002,"ref":"032a7ff165fc602583d0606bdd9eff4500851253","baseStable":{"version":"2.8.0","build":28003,"release":"apps/video/mdai/releases/2.8.0/release.json"},"previousTest":{"version":"2.9.0-test.1","build":29001,"release":"apps/video/mdai/releases/2.9.0-test.1/release.json","status":"frozen-short-drama-detail-sel-scope-regression"},"modules":[{"name":"core","path":"apps/video/mdai/releases/2.9.0-test.1/core.js"},{"name":"playback-adapter","path":"apps/video/mdai/releases/2.7.0-test.1/playback.js"},{"name":"ui","path":"apps/video/mdai/releases/2.9.0-test.1/ui.js"},{"name":"community","path":"apps/video/mdai/releases/2.9.0-test.1/community.js"},{"name":"home","path":"apps/video/mdai/releases/2.9.0-test.1/pages_home.js"},{"name":"library","path":"apps/video/mdai/releases/2.9.0-test.1/pages_library.js"},{"name":"search-mine","path":"apps/video/mdai/releases/2.9.0-test.1/pages_search_mine.js"},{"name":"detail","path":"apps/video/mdai/releases/2.9.0-test.2/pages_detail.js"},{"name":"settings","path":"apps/video/mdai/releases/2.9.0-test.1/settings.js"},{"name":"runtime","path":"apps/video/mdai/releases/2.9.0-test.2/runtime.js"}],"verify":{"global":"MDAIRemoteRuntime","property":"build","equals":"2.9.0-test.2"},"delivery":{"mode":"local-first-native","moduleManager":"2.2.0","execution":"require(file://)","code":"hiker-files-rules","assets":"hiker-files-rules","controlPlane":"remote-on-install-update-only"},"notes":"Test2 冻结 Test1 并修复短剧详情选集范围变量作用域；其余 2.9 UI/评论/搜索/片库/播放保持不变。"};
  var ASSET_REF='032a7ff165fc602583d0606bdd9eff4500851253';
  var ROOT='hiker://files/rules/asset-core-local/mdai-test/assets/';
  function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Request\s+(?:failed|error)|Fetch\s+(?:failed|error)|Network\s+(?:failed|error)|Timeout\b|ETIMEDOUT\b|ECONN|ENOTFOUND\b|Forbidden\b|Unauthorized\b|Rate\s*limit\b)/i.test(t);}
  function fetchAny(path,check,label){var us=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/'+ASSET_REF+'/'+path,'https://github.com/huoguotiankong/asset-core-7f3/raw/'+ASSET_REF+'/'+path,'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@'+ASSET_REF+'/'+path],es=[];for(var i=0;i<us.length;i++)try{var t=String(fetch(us[i],{timeout:8000,headers:{'Cache-Control':'no-cache'}})||'');if(bad(t)||!check(t))throw new Error('内容校验失败');return t;}catch(e){es.push((i+1)+':'+String(e.message||e));}throw new Error(String(label||path)+' 全部镜像失败：'+es.join(' | '));}
  function writeAsset(name,text,check){var p=ROOT+name;writeFile(p,String(text));if(!fileExist(p))throw new Error('本地资产写入失败：'+name);var back=String(fetch(p)||'');if(!check(back)||String(md5(back))!==String(md5(text)))throw new Error('本地资产回读校验失败：'+name);return p;}
  function installAssets(force){var defs=[['library.svg','apps/video/mdai/assets/v270/library.svg'],['favorite.svg','apps/video/mdai/assets/v270/favorite.svg'],['history.svg','apps/video/mdai/assets/v270/history.svg'],['settings.svg','apps/video/mdai/assets/v270/settings.svg']],ok=0;for(var i=0;i<defs.length;i++){var d=defs[i],p=ROOT+d[0],cur='';try{if(!force&&fileExist(p))cur=String(fetch(p)||'');}catch(e){cur='';}if(!cur||!/<svg\b/i.test(cur))writeAsset(d[0],fetchAny(d[1],function(t){return /<svg\b/i.test(t);},d[0]),function(t){return /<svg\b/i.test(t);});ok++;}return ok;}
  function manager(){var es=[];for(var i=0;i<MANAGER_URLS.length;i++)try{var src=String(fetch(MANAGER_URLS[i],{timeout:8000,headers:{'Cache-Control':'no-cache'}})||'');if(bad(src))throw new Error('无效响应');var HikerLocalModules;eval(src);if(typeof HikerLocalModules!=='object'||String(HikerLocalModules.version)!=='2.2.0')throw new Error('导出校验失败');return HikerLocalModules;}catch(e){es.push((i+1)+':'+String(e.message||e));}throw new Error('Local Module Manager 2.2.0 全部镜像失败：'+es.join(' | '));}
  function release(){return JSON.parse(JSON.stringify(R));}
  function installLocal(force){installAssets(!!force);var m=manager(),x=m.install(C,R,!!force);if(!x||!x.ok)throw new Error(x&&x.error?x.error:'麻豆AI本地模块包安装失败');return x;}
  function loadLocal(){var m=manager();m.load(C,R);if(typeof MDAIRemoteRuntime!=='object'||String(MDAIRemoteRuntime.build)!=='2.9.0-test.2')throw new Error('麻豆AI 2.9 Test2 Local-First Runtime 校验失败');return MDAIRemoteRuntime.module();}
  return{version:MDAI_BOOT_VERSION,config:C,release:release,manager:manager,installAssets:installAssets,installLocal:installLocal,loadLocal:loadLocal};
})();
