/* 我的规则仓库 RC34 - Flat Entry 2.0 */
var RuleRepoFlatEntry=(function(){
var VERSION='2.0.0',ROOT='hiker://files/rules/asset-core-local/rule-repo-test/';
var SELF=ROOT+'flat_entry_v2.js',ALIAS=ROOT+'flat_entry_v1.js',BUNDLE=ROOT+'flat_runtime_b424.js',BUILDER=ROOT+'flat_builder_v2.js',CONTROL=ROOT+'flat_control_v2.js';
var BUILDER_REF='84528416cebabde5259d2afb939578c4795dd056',BUILDER_PATH='apps/tools/rule-repo/releases/test-3.5.6-rc34/flat_builder_v2.js';
var CONTROL_REF='d2379e0e2852325d55660aff6a69614fe95ee603',CONTROL_PATH='apps/tools/rule-repo/releases/test-3.5.6-rc34/flat_control_v2.js';
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function urls(ref,path){return['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/'+ref+'/'+path,'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@'+ref+'/'+path,'https://github.com/huoguotiankong/asset-core-7f3/raw/'+ref+'/'+path];}
function ensure(path,ref,src,label){if(fileExist(path))return path;var us=urls(ref,src),es=[];for(var i=0;i<us.length;i++){try{var s=String(fetch(us[i],{timeout:4200,headers:{'Cache-Control':'public, max-age=31536000, immutable'}})||'');if(bad(s))throw new Error('无效响应');writeFile(path,s);if(!fileExist(path))throw new Error('写入失败');return path;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(label+'下载失败：'+es.join(' | '));}
function req(path){var u=getPath(path);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}}
function aliases(){try{if(fileExist(SELF)){writeFile(ALIAS,String(readFile(SELF)||''));try{deleteCache(getPath(ALIAS));}catch(_e){}}}catch(e){}try{if(fileExist(CONTROL)){writeFile(ROOT+'flat_control_v1.js',String(readFile(CONTROL)||''));try{deleteCache(getPath(ROOT+'flat_control_v1.js'));}catch(_e2){}}}catch(e2){}}
function load(){ensure(CONTROL,CONTROL_REF,CONTROL_PATH,'RC34 Control');if(!fileExist(BUNDLE)){ensure(BUILDER,BUILDER_REF,BUILDER_PATH,'RC34 Builder');req(BUILDER);if(typeof RuleRepoFlatBuilder!=='object'||typeof RuleRepoFlatBuilder.build!=='function')throw new Error('RC34 Builder 未导出');RuleRepoFlatBuilder.build(false);}aliases();req(BUNDLE);if(typeof HikerRuleRepo!=='object'||Number(HikerRuleRepo.build||0)!==424||!HikerRuleRepo.__flat424){try{deleteCache(getPath(BUNDLE));}catch(e1){}req(BUNDLE);}if(typeof HikerRuleRepo!=='object'||Number(HikerRuleRepo.build||0)!==424||!HikerRuleRepo.__flat424)throw new Error('Flat Runtime Build424 未加载');return HikerRuleRepo;}
function run(name){var R=load();name=String(name||'home');if(name==='home')return R.home();if(name==='category')return R.categoryPage();if(name==='search')return R.searchPage();if(name==='updates')return R.updatesPage();if(name==='detail')return R.detailPage();if(name==='history')return R.historyPage();if(name==='settings')return R.settingsPage();if(name==='about')return R.aboutPage();if(name==='filters')return typeof R.filtersPage==='function'?R.filtersPage():R.categoryPage();if(name==='versions')return R.channelPage();if(name==='update'){setPageTitle('测试版更新');setResult([{title:'我的规则仓库·测试版',desc:'3.5.6-rc34 · Build424\nMutable Catalog Live-File',col_type:'text_1',url:'hiker://empty'},{title:'版本目录实时读取',desc:'版本详情不再使用长生命周期 _catalog 内存快照；检查版本/同步写入本地 snapshot 后当前页面立即读取新 revision。',col_type:'text_2',url:'hiker://empty'},{title:'正常启动仍纯本地',desc:'没有用户主动检查/同步时不访问 GitHub 控制面；正常启动仍只加载单一本地 Runtime Bundle。',col_type:'text_2',url:'hiker://empty'},{title:'兼容旧页面回调',desc:'RC34 会把 Entry/Control 同步写入旧 v1 本地别名，防止旧页面模块缓存重新进入 RC33 控制面。',col_type:'text_2',url:'hiker://empty'}]);return;}throw new Error('未知页面：'+name);}
return{version:VERSION,load:load,run:run};
})();
