/* 我的规则仓库 v3.5.0-rc6 - cleaner category center */
(function(R){
R.categoryPage=function(){
setPageTitle('分类');var d=[],items;try{items=this.items(false);}catch(e){setResult([{title:'暂时无法读取分类',desc:String(e.message||e),url:'hiker://empty',col_type:'text_center_1'}]);return;}var state=this.filterState(),batch=this.batchMode(),result=this.applyFilters(items,state);this.pushNav(d,'category');
this.pushSection(d,'浏览分类','先选主分类，再按需要细化');this.categories(items).forEach(function(c){d.push(R.scopeChip(c.name+' '+c.count,c.id,state.category,'hc_repo_category'));});
var subs=this.subCategories(items,state.category);if(subs.length>1){this.pushSpacer(d);this.pushSection(d,'子分类','');subs.forEach(function(s){d.push(R.scopeChip(s.name+' '+s.count,s.id,state.subCategory,'hc_repo_sub'));});}
var fresh=this.filterState(),tags=this.tagsFor(items,fresh);if(tags.length){this.pushSpacer(d);this.pushSection(d,'能力标签','');d.push(R.scopeChip('全部','all',fresh.tag,'hc_repo_tag'));tags.slice(0,12).forEach(function(t){d.push(R.scopeChip(t.name+' '+t.count,t.name,fresh.tag,'hc_repo_tag'));});}
this.pushSpacer(d);this.pushSection(d,'筛选','');[['全部','all'],['远程','remote'],['本地','local']].forEach(function(x){d.push(R.scopeChip(x[0],x[1],fresh.mode,'hc_repo_mode'));});[['默认','default'],['最近更新','updated'],['名称','name'],['版本','version']].forEach(function(x){d.push(R.scopeChip(x[0],x[1],fresh.sort,'hc_repo_sort'));});d.push({title:'重置',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearAllFilters();refreshPage(false);return'toast://筛选已重置';}),col_type:'flex_button',extra:{lineVisible:false}});d.push({title:batch?'退出批量':'批量管理',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.setBatchMode(!r.batchMode());refreshPage(false);return'hiker://empty';}),col_type:'flex_button',extra:{lineVisible:false}});
if(batch){var n=this.selectedIds().length;this.pushSpacer(d);d.push({title:'已选择 '+n+' 个程序',desc:'批量操作只修改规则仓库自己的收藏与版本记录。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'收藏',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore'),n=r.batchFavorite(true);refreshPage(false);return'toast://已处理 '+n+' 项';}),col_type:'text_3'});d.push({title:'取消收藏',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore'),n=r.batchFavorite(false);refreshPage(false);return'toast://已处理 '+n+' 项';}),col_type:'text_3'});d.push({title:'清空选择',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearSelection();refreshPage(false);return'toast://已清空';}),col_type:'text_3'});}
this.pushSpacer(d);this.pushSection(d,batch?'选择程序':'筛选结果','共 '+result.length+' 个');result.forEach(function(x){d.push(batch?R.selectCard(x):R.itemCard(x));});if(!result.length)this.pushEmpty(d,'没有匹配结果','调整分类或重置筛选后再试。');setResult(d);
};
})(HikerRuleRepo);
