/* 我的规则仓库 v3.5.0-rc6 - polished version center and app detail */
(function(R){
R.channelMeta=function(parent){var path=String(parent&&parent.channelsPath||parent&&parent.raw&&parent.raw.channelsPath||'');if(path){try{var x=JSON.parse(this.apiText(path));if(x&&Array.isArray(x.channels)&&x.channels.length)return x;}catch(e){}}return null;};
R.channelPage=function(parent){
setPageTitle(parent.name);var d=[],meta=this.channelMeta(parent),self=this;if(!meta){setResult([{title:'暂时无法读取版本信息',desc:'请稍后重试或在设置中同步云端目录。',url:'hiker://page/ruleRepoSettings?rule=&simple=true',col_type:'text_center_1'}]);return;}try{setPagePicUrl(this.iconOf(parent));}catch(e){}
d.push(this.hero(parent.name,'一个程序 · 一个入口\n正式版用于日常使用，测试版用于体验新功能',this.iconOf(parent),'hiker://empty'));
this.pushSection(d,'选择版本','点击整张卡片直接导入对应版本');
(meta.channels||[]).forEach(function(c){var recommended=!!c.recommended,badge=c.channel==='stable'?'正式版':'测试版',raw={id:String(c.id||''),name:String(c.name||''),version:String(c.version||''),desc:String(c.desc||''),path:String(c.path||''),category:parent.category,categoryName:parent.categoryName,subCategory:parent.subCategory,tags:['远程',c.channel==='test'?'测试':'正式','管理','版本'],mode:String(c.mode||'remote'),updatedAt:String(c.updatedAt||meta.updatedAt||''),icon:String(c.icon||self.iconOf(parent)),openTitle:String(c.openTitle||c.name||'')},item=self.normalizeItem(raw,0),status=self.displayStatus(item),hl=Array.isArray(c.highlights)?c.highlights.slice(0,3).join(' · '):'';d.push({title:badge+(recommended?' · 推荐':' · 抢先体验'),desc:String(c.displayVersion||c.version||'')+(c.build!=null?' · build '+c.build:'')+'\n'+String(c.desc||'')+(hl?'\n'+hl:'')+'\n'+status+' · 点击导入',img:String(c.icon||self.iconOf(parent)),pic_url:String(c.icon||self.iconOf(parent)),url:$('#noLoading#').lazyRule(function(x){return $.require('hiker://page/ruleRepoCore').importRule(x);},JSON.stringify(raw)),col_type:'icon_1_left_pic',extra:{lineVisible:false}});});
this.pushSpacer(d);d.push({title:'版本策略',desc:'正式版经过实机验证后发布；测试版与正式版可以同时安装，更新状态和本地记录互相隔离。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});setResult(d);
};
R.detailPage=function(){
var id=String((MY_PARAMS&&MY_PARAMS.hc_repo_item_id)||getParam('id')||''),item=this.findById(id,false),d=[];if(!item){setResult([{title:'这个程序暂时不可用',desc:'云端目录可能已经更新，请返回首页重新同步。',url:'hiker://page/ruleRepoHome?rule=&simple=true',col_type:'text_center_1'}]);return;}if(item.entryType==='channel-group'||item.channelsPath)return this.channelPage(item);setPageTitle(item.name);try{setPagePicUrl(this.iconOf(item));}catch(e){}
var st=this.displayStatus(item),iv=this.installedVersion(item),lastImport=this.lastImportedTime(item),lastOpen=this.lastOpenedTime?this.lastOpenedTime(item):0;
d.push(this.hero(item.name,this.cleanVersion(item.version)+' · '+st+'\n'+String(item.desc||''),this.iconOf(item),'hiker://empty'));
d.push({title:'打开',url:$('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id);return x?r.openRule(x):'toast://程序不存在';},item.id),col_type:'text_2',extra:{lineVisible:false}});
d.push({title:st==='有新版本'?'更新到最新版':'导入 / 覆盖',url:$('#noLoading#').lazyRule(function(raw){return $.require('hiker://page/ruleRepoCore').importRule(raw);},JSON.stringify(item.raw)),col_type:'text_2',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'快捷操作','');d.push(this.actionIcon(this.isFav(item)?'已收藏':'收藏','favorite',$('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id);if(!x)return'toast://程序不存在';var on=r.toggleFav(x);refreshPage(false);return'toast://'+(on?'已收藏':'已取消收藏');},item.id)));d.push(this.actionIcon('检查更新','updates',$('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id,true);if(!x)return'toast://程序不存在';return'toast://'+r.displayStatus(x)+' · 云端 '+r.cleanVersion(x.version);},item.id)));d.push(this.actionIcon('活动记录','history','hiker://page/ruleRepoHistory?rule=&simple=true'));d.push(this.actionIcon('设置','settings','hiker://page/ruleRepoSettings?rule=&simple=true'));
this.pushSpacer(d);this.pushSection(d,'程序信息','');d.push({title:'版本  '+this.cleanVersion(item.version),url:'hiker://empty',col_type:'text_2',extra:{lineVisible:false}});d.push({title:'状态  '+st,url:'hiker://empty',col_type:'text_2',extra:{lineVisible:false}});d.push({title:'分类  '+item.categoryName+' / '+item.subCategory,url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'最近导入  '+(lastImport?this.formatTime(lastImport):'未记录'),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'最近打开  '+(lastOpen?this.formatTime(lastOpen):'未记录'),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});if(iv)d.push({title:'仓库记录版本  '+iv,desc:'仅表示曾通过本仓库导入，不代表读取了海阔系统安装数据库。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
if((item.tags||[]).length){this.pushSpacer(d);this.pushSection(d,'能力标签','');(item.tags||[]).slice(0,8).forEach(function(t){d.push({title:'#'+t,col_type:'flex_button',url:'hiker://page/ruleRepoSearch?rule=&simple=true&kw='+encodeURIComponent(t)});});}
setResult(d);
};
})(HikerRuleRepo);
