/* 我的规则仓库 v3.5.0-rc6 - focused search experience */
(function(R){
R.searchPage=function(){
setPageTitle('搜索');var d=[],items;try{items=this.items(false);}catch(e){setResult([{title:'暂时无法搜索',desc:String(e.message||e),url:'hiker://empty',col_type:'text_center_1'}]);return;}var pkw=String(getParam('kw','')||getParam('s','')||'').trim(),kw=pkw||String(getMyVar('hc_repo_search_kw','')||'').trim(),scope=String(getMyVar('hc_repo_search_scope','all')||'all');if(pkw){putMyVar('hc_repo_search_kw',pkw);this.recordSearch(pkw);}this.pushNav(d,'search');
d.push({title:'搜索程序名称、功能或标签',url:$.toString(function(){var q=String(input||'').trim();putMyVar('hc_repo_search_kw',q);var r=$.require('hiker://page/ruleRepoCore');r.recordSearch(q);refreshPage(false);return'hiker://empty';}),col_type:'input',extra:{titleVisible:false,defaultValue:kw,onChange:$.toString(function(){putMyVar('hc_repo_search_kw',String(input||''));})}});
d.push(this.scopeChip('全部','all',scope,'hc_repo_search_scope'));d.push(this.scopeChip('有更新','updates',scope,'hc_repo_search_scope'));d.push(this.scopeChip('收藏','favorites',scope,'hc_repo_search_scope'));d.push(this.scopeChip('远程','remote',scope,'hc_repo_search_scope'));d.push(this.scopeChip('本地','local',scope,'hc_repo_search_scope'));
var pool=items.slice();if(scope==='updates')pool=pool.filter(function(x){return x.entryType!=='channel-group'&&R.statusOf(x)==='可更新';});else if(scope==='favorites')pool=pool.filter(function(x){return R.isFav(x);});else if(scope==='remote')pool=pool.filter(function(x){return x.mode==='remote';});else if(scope==='local')pool=pool.filter(function(x){return x.mode!=='remote';});
if(kw){var a=pool.filter(function(x){return R.matchKeyword(x,kw);});this.pushSpacer(d);this.pushSection(d,'搜索结果',a.length+' 个');a.forEach(function(x){d.push(R.itemCard(x));});if(!a.length)this.pushEmpty(d,'没有找到相关程序','换一个名称、功能或标签试试。');}
else{var recent=this.recentItems?this.recentItems(items,4):[],hist=this.searchHistory(),tags=this.popularTags(items,8);if(recent.length){this.pushSpacer(d);this.pushSection(d,'最近使用','');recent.forEach(function(x){d.push(R.recentTile(x));});}if(hist.length){this.pushSpacer(d);this.pushSection(d,'最近搜索','');hist.slice(0,8).forEach(function(x){d.push({title:x,col_type:'flex_button',url:$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_search_kw',v);var r=$.require('hiker://page/ruleRepoCore');r.recordSearch(v);refreshPage(false);return'hiker://empty';},x)});});d.push({title:'清空',col_type:'flex_button',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearSearchHistory();refreshPage(false);return'toast://已清空';})});}if(tags.length){this.pushSpacer(d);this.pushSection(d,'热门标签','');tags.forEach(function(t){d.push({title:'#'+t.name,col_type:'flex_button',url:$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_search_kw',v);refreshPage(false);return'hiker://empty';},t.name)});});}if(!recent.length&&!hist.length&&!tags.length)this.pushEmpty(d,'搜索你的程序','支持名称、描述、标签、分类和版本。');}
setResult(d);
};
})(HikerRuleRepo);
