/* 我的规则仓库 v3.5.0-rc6 - user-facing settings */
(function(R){
R.settingsPage=function(){
setPageTitle('设置');var d=[],cache=this.cacheMs(),probe=this.probeMs();this.pushNav(d,'settings');
this.pushSection(d,'云端同步','默认设置已经兼顾速度与实时性');d.push({title:'自动检查云端变化',desc:(probe<=0?'已关闭':'每 '+Math.round(probe/1000)+' 秒轻量检查一次')+' · 只有目录变化时才重新下载完整索引',url:$('关闭,30秒,60秒,180秒,300秒','自动检查频率').select(function(){var map={'关闭':0,'30秒':30000,'60秒':60000,'180秒':180000,'300秒':300000},r=$.require('hiker://page/ruleRepoCore');r.setSetting('probe_ms',map[String(input||'60秒')]);refreshPage(false);return'toast://已设置';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'离线缓存',desc:Math.round(cache/60000)+' 分钟 · 网络异常时继续使用最近一次有效目录',url:$('5分钟,15分钟,30分钟,60分钟','离线缓存时间').select(function(){var map={'5分钟':300000,'15分钟':900000,'30分钟':1800000,'60分钟':3600000},r=$.require('hiker://page/ruleRepoCore');r.setSetting('cache_ms',map[String(input||'30分钟')]||1800000);refreshPage(false);return'toast://已设置';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'立即同步',desc:'清理目录缓存并重新读取云端',url:$('#noLoading#').lazyRule(function(){showLoading('正在同步…');try{var r=$.require('hiker://page/ruleRepoCore');r.clearManifestCache();r.manifest(true);hideLoading();refreshPage(false);return'toast://已同步';}catch(e){hideLoading();return'toast://同步失败';}}),col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'数据与备份','只保存规则仓库自己的记录');d.push({title:'备份当前状态',desc:'包含收藏、导入记录、最近使用、搜索历史和筛选设置，不包含账号凭据',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');return'copy://'+r.exportState();}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'恢复状态备份',desc:'粘贴由本程序生成的备份 JSON',url:$('粘贴备份 JSON','').input(function(){try{var r=$.require('hiker://page/ruleRepoCore');r.restoreState(String(input||''));r.clearSelection();refreshPage(false);return'toast://已恢复';}catch(e){return'toast://恢复失败';}}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'活动记录',desc:'查看最近导入和最近打开',url:'hiker://page/ruleRepoHistory?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'清理','以下操作不会删除海阔里已经安装的小程序');d.push({title:'清空最近打开',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearOpenHistory();refreshPage(false);return'toast://已清空';}),col_type:'text_2',extra:{lineVisible:false}});d.push({title:'清空搜索历史',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearSearchHistory();refreshPage(false);return'toast://已清空';}),col_type:'text_2',extra:{lineVisible:false}});d.push({title:'清空收藏',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearFavorites();refreshPage(false);return'toast://已清空';}),col_type:'text_2',extra:{lineVisible:false}});d.push({title:'清空导入记录',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearImportHistory();r.clearInstalled();refreshPage(false);return'toast://已清空';}),col_type:'text_2',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'关于','');d.push({title:'版本与更新',desc:'当前 '+this.version+' · '+(this.isTestChannel()?'测试通道':'正式通道'),url:'hiker://page/ruleRepoUpdate?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'产品与架构信息',desc:'查看版本说明、模块架构和更新日志',url:'hiker://page/ruleRepoAbout?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'高级信息',desc:'build '+this.build+' · revision '+String(getItem(this.manifestRevisionKey,'--')||'--')+' · schema 8',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});setResult(d);
};
R.aboutPage=function(){setPageTitle('关于');var d=[];d.push(this.hero('我的规则仓库','海阔视界专属 · 云端程序管理中心\n稳定、清晰、可升级、可回退',this.iconOf(this.findById('rule-repo')||{}),'hiker://empty'));this.pushSection(d,'产品原则','一个程序一个入口 · Stable/Test 双通道 · 常用操作优先 · 技术信息后置 · 异常可恢复');d.push(this.actionIcon('分类','category','hiker://page/ruleRepoCategory?rule=&simple=true'));d.push(this.actionIcon('搜索','search','hiker://page/ruleRepoSearch?rule=&simple=true'));d.push(this.actionIcon('更新','updates','hiker://page/ruleRepoUpdates?rule=&simple=true'));d.push(this.actionIcon('记录','history','hiker://page/ruleRepoHistory?rule=&simple=true'));var log='';try{log=this.apiText('apps/tools/rule-repo/CHANGELOG.md');}catch(e){log='更新日志读取失败';}this.pushSpacer(d);d.push({title:'更新日志',desc:log,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);};
})(HikerRuleRepo);
