/* PikPak Test20 Build10122 - native search UI and fresh-account web flow */
(function(C,P,UI,Pages){
    var HANDOFF='pikpak_web_handoff_v15';
    function page(){try{return Number(MY_PAGE||1)||1;}catch(e){return 1;}}
    function raw(k,d){try{return getParam(k,d==null?'':String(d));}catch(e){return d==null?'':String(d);}}
    function param(k,d){var v=String(raw(k,d)||'');try{return decodeURIComponent(v);}catch(e){return v;}}
    function title(v){try{setPageTitle(String(v||''));}catch(e){}}
    function payload(){var s='';try{s=String(getVar(HANDOFF,'')||'');}catch(e){}try{return s?JSON.parse(s):null;}catch(e2){return null;}}
    function image(f){var m=String(f&&f.mime_type||'').toLowerCase(),n=String(f&&f.name||'').toLowerCase();return m.indexOf('image')>=0||/\.(jpg|jpeg|png|gif|webp|bmp|avif|heic)(\?|$)/i.test(n);}
    function typeMatch(f,type){if(type==='video')return P.isVideo(f);if(type==='folder')return P.isFolder(f);if(type==='image')return image(f);return true;}
    function fileUrl(f){if(P.isFolder(f))return UI.route('pikpakDrive',{parent_id:f.id||'',name:f.name||'文件夹'});return $("#noLoading#").lazyRule(function(x){return $.require('pikpak').playPersonal(x.id,x.mime,false);},{id:String(f.id||''),mime:String(f.mime_type||'')});}
    function tokenKey(q,type,n){return 'pikpak_v20_search_'+md5(q+'|'+type)+'_'+n;}
    function typeName(v){return v==='video'?'视频':v==='folder'?'文件夹':v==='image'?'图片':'项目';}
    Pages.cloudSearch=function(opt){
        opt=opt||{};var q=String(opt.q!=null?opt.q:param('q','')).trim(),type=String(opt.type||param('type','all')),n=opt.external?1:page(),d=[],types=[['全部','all'],['视频','video'],['图片','image'],['文件夹','folder']];
        if(!opt.external){title('云盘搜索');if(n===1){d.push({title:q,desc:'输入文件名搜索整个个人网盘',url:$.toString(function(){return $.require('pikpak').searchRoute(input);}),col_type:'input',extra:{inheritTitle:false}});for(var z=0;z<types.length;z++)d.push({title:(type===types[z][1]?'● ':'')+types[z][0],url:UI.route('pikpakSearch',{q:q,type:types[z][1]}),col_type:'scroll_button'});}}
        if(!C.loggedIn()){d.push(UI.error('搜索个人网盘前请先登录 PikPak'));setResult(d);return;}if(!q){d.push(UI.empty('输入文件名关键词开始搜索'));setResult(d);return;}
        var tok='';if(n>1){try{tok=getMyVar(tokenKey(q,type,n),'');}catch(e){}if(!tok){setResult(d);return;}}var r=P.searchFiles(q,tok,200);if(!r||r.error||r.error_code){d.push(UI.error('PikPak 搜索失败：'+C.errorText(r)));setResult(d);return;}if(!opt.external)try{putMyVar(tokenKey(q,type,n+1),String(r.next_page_token||''));}catch(e2){}var a=r.files instanceof Array?r.files:[],count=0;if(!opt.external&&n===1)d.push({title:'搜索“'+q+'”',desc:'PikPak 原生全盘文件名搜索 · '+typeName(type)+'筛选',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});for(var i=0;i<a.length;i++)if(typeMatch(a[i],type)){d.push(UI.fileCard(a[i],fileUrl(a[i])));count++;}if(!count)d.push(UI.empty('没有匹配“'+q+'”的'+typeName(type)));setResult(d);
    };
    Pages.account=function(){
        var d=[],a=C.accounts?C.accounts():[],cur=C.currentAccountId?C.currentAccountId():'',cap=payload();title('PikPak 多账号');
        if(cap&&(cap.access_token||cap.refresh_token))d.push({title:'✅ 发现新的网页登录会话',desc:'点此接入并保存为另一个本机账号',url:UI.route('pikpakWebDone',{bridge:'v15'}),col_type:'text_1',extra:{lineVisible:false}});
        d.push({title:C.loggedIn()?'Web Session 已连接':'当前未启用账号',desc:C.loggedIn()?'已保存 '+a.length+' 个本机会话；点击下方账号即可切换':'可切换已保存账号，或添加新的官方网页登录会话',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
        d.push({title:'＋ 添加其他账号',desc:'先退出官方网页中的旧账号，再登录新账号',url:UI.route('pikpakWebReset'),col_type:'text_1',extra:{lineVisible:false}});
        if(C.loggedIn())d.push({title:'刷新当前会话',url:$("#noLoading#").lazyRule(function(){return $.require('pikpak').refreshSessionAction();}),col_type:'scroll_button'});
        for(var i=0;i<a.length;i++){var x=a[i],active=x.id===cur,label=String(x.label||('PikPak 账号 '+(i+1)));d.push({title:(active?'✓ ':'')+label,desc:(active?'当前账号 · ':'点击切换 · ')+'官方 Web Session\n本机保存：'+C.formatDate(x.savedAt||''),url:active?'hiker://empty':$("#noLoading#").lazyRule(function(id){return $.require('pikpak').switchAccountAction(id);},String(x.id||'')),col_type:'text_1',extra:{lineVisible:false,longClick:[{title:'重命名账号',js:$.toString(function(v){return $.require('pikpak').renameAccountPrompt(v.id,v.label);},{id:String(x.id||''),label:label})},{title:'移除本机账号',js:$.toString(function(id){return $.require('pikpak').removeAccountPrompt(id);},String(x.id||''))}]}});}
        if(!a.length)d.push(UI.empty('还没有保存的账号，请使用“添加其他账号”完成官方网页登录'));
        d.push({title:'说明',desc:'“添加其他账号”只清理官方网页里的登录状态，不会退出或删除小程序已保存的旧账号。新账号接入后，可在这里直接切换。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});setResult(d);
    };
    Pages.webReset=function(){
        title('添加其他 PikPak 账号');try{clearVar(HANDOFF);}catch(e){}
        var d=[],inject="(function(){try{var M='__pikpak_hiker_fresh20__';if(String(window.name||'').indexOf(M)<0){window.name=String(window.name||'')+'|'+M;var jobs=[];try{localStorage.clear();}catch(e){}try{sessionStorage.clear();}catch(e){}try{document.cookie.split(';').forEach(function(c){var n=c.split('=')[0].replace(/^\\s+|\\s+$/g,'');if(n){document.cookie=n+'=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/';document.cookie=n+'=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/;domain=.mypikpak.com';}});}catch(e){}try{if(window.indexedDB&&typeof indexedDB.databases==='function')jobs.push(indexedDB.databases().then(function(ds){return Promise.all(ds.map(function(x){return x.name?new Promise(function(ok){var r=indexedDB.deleteDatabase(x.name);r.onsuccess=r.onerror=r.onblocked=ok;}):Promise.resolve();}));}));}catch(e){}try{if(window.caches)jobs.push(caches.keys().then(function(keys){return Promise.all(keys.map(function(k){return caches.delete(k);}));}));}catch(e){}Promise.all(jobs).then(function(){setTimeout(function(){location.replace('https://mypikpak.com/drive/all');},300);});}}catch(e){}})();";
        d.push({title:'第 1 步：退出旧网页账号',desc:'页面会自动清理官方网页的本地登录状态。若仍显示旧账号，请在网页左上角菜单中手动退出，然后登录需要新增的账号。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
        d.push({title:'第 2 步：已登录新账号，读取会话',desc:'确认下面网页已显示新账号文件后再点这里',url:UI.route('pikpakWebLogin'),col_type:'text_center_1',extra:{lineVisible:false}});
        d.push({title:'PikPak 官方网页',url:'https://mypikpak.com/drive/all',col_type:'x5_webview_single',desc:'list&&screen-230',extra:{canBack:true,showProgress:true,ua:'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0 Mobile Safari/537.36',js:inject,jsLoadingInject:true}});setResult(d);
    };
    Pages.settings=function(){var d=[];title('PikPak 设置');var sort=C.item('sort','name_asc'),filter=C.item('drive_filter','all'),auto=C.item('handoff_auto_trash','on')!=='off',count=C.accounts?C.accounts().length:0;d.push({title:'账号与 Session',desc:(C.loggedIn()?'当前已连接':'当前未连接')+' · 本机保存 '+count+' 个账号',url:UI.route('pikpakAccount'),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'云盘搜索',desc:'PikPak 原生全盘文件名搜索，可筛选视频、图片和文件夹',url:UI.route('pikpakSearch'),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'跨小程序 Magnet 退出自动回收',desc:auto?'已开启：关闭调用页后，本次临时播放文件移入回收站':'已关闭：退出后保留 My Pack 中的播放文件',url:$(['开启','关闭']).select(function(){return $.require('pikpak').setHandoffCleanupAction(input);}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'目录筛选',desc:filter==='video'?'仅视频':filter==='folder'?'仅文件夹':'全部',url:$(['全部','仅视频','仅文件夹']).select(function(){return $.require('pikpak').setDriveFilterAction(input);}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'文件排序',desc:sort==='time_desc'?'最近修改':sort==='size_desc'?'文件大小':sort==='name_desc'?'名称倒序':'名称正序',url:$(['名称正序','名称倒序','最近修改','文件大小']).select(function(){return $.require('pikpak').setSortAction(input);}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'星标文件',url:UI.route('pikpakStarred'),col_type:'scroll_button'});d.push({title:'回收站',url:UI.route('pikpakRecycle'),col_type:'scroll_button'});d.push({title:'清理当前账号临时文件',desc:'只把当前账号下由本程序登记的临时对象移入回收站',url:'confirm://确定清理当前账号的临时播放文件？.js:'+$.toString(function(){return $.require('pikpak').cleanupTempAction();}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行信息',desc:'Test20 · Build 10122\n搜索：PikPak 原生 name.contains\n多账号：先清理网页旧登录态，再接入新账号\n小程序已保存账号不会被网页退出影响',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});setResult(d);};
})(PikPakCore,PikPakProvider,PikPakUI,PikPakPages);
