/* ACFAN 0.1.0-test.5 playback - native first, H5 bridge fallback */
var ACFANPlayback=(function(){
  var C=ACFANCore,P=ACFANProtocol;
  function host(){return C.s(getItem(C.K.host,'')||C.staticApiHosts[0]).replace(/\/+$/,'');}
  function playerHeaders(){var h=host();return{'User-Agent':'Mozilla/5.0 (Linux; Android 12; SM-G9750 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.72 Mobile Safari/537.36','Referer':h+'/', 'Origin':h};}
  function firstPath(root){return C.s(P.mediaPath(root)||C.first(C.deep(root||{},['path','videoUrl','playUrl','videoUri','m3u8','playPath','previewUrl'],0)));}
  function decodeUrl(path){path=C.s(path).trim();if(!path)return'';if(/^https?:\/\//i.test(path)&&(/\/api\/m3u8\//i.test(path)||/\.(?:m3u8|mp4)(?:[?#]|$)/i.test(path)))return path;return host()+'/api/m3u8/h5/decode?path='+encodeURIComponent(path);}
  function nativePlay(id,seed,title){id=C.s(id);var path=firstPath(seed||{}),used=path?'seed':'';if(!path&&id){try{var w=P.tryApi('video/can/watch',{videoId:C.n(id)},['GET','POST'],{timeout:4200});path=firstPath(w);used='can-watch';}catch(e){C.diag('PLAY_WATCH_FAIL',String(e.message||e),{id:id});}}var u=decodeUrl(path);if(!u){C.diag('PLAY_NO_PATH','id='+id,{seedPath:firstPath(seed||{})});return'toast://未获取到原生播放地址，可使用网页播放';}C.diag('PLAY_NATIVE',used+' '+u.slice(0,600),{id:id,path:path});var playUrl=/\.mp4(?:[?#]|$)/i.test(u)?u:(u+'#isM3u8#');return JSON.stringify({urls:[playUrl],names:[title||'播放'],headers:[playerHeaders()]});}
  function bridgeUrl(kind,id,title,chapter){return C.page('acfanT5Bridge',{acf_kind:kind||'video',acf_id:id||'',acf_title:title||'',acf_chapter:chapter||''});}
  function bridgeScript(kind,id,title,chapter){var cfg={kind:C.s(kind),id:C.s(id),title:C.s(title),chapter:C.s(chapter)};return '('+function(c){function txt(e){return String(e&&e.innerText||'').replace(/\s+/g,' ').trim();}function vis(e){if(!e)return false;var r=e.getBoundingClientRect();return r.width>0&&r.height>0;}function clk(e){try{if(e&&vis(e)){e.click();return true;}}catch(x){}return false;}function setv(e,v){try{var d=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value');if(d&&d.set)d.set.call(e,v);else e.value=v;}catch(x){e.value=v;}try{e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));}catch(x2){}}var n=0,last=0;function input(){return document.querySelector('input[type=search],input[placeholder*=搜索],input[placeholder*=搜],input[name*=search],input[name*=keyword],input[type=text]');}function hit(){var q=String(c.title||'').trim(),keys=[q,q.slice(0,20),q.slice(0,12),q.slice(0,8)].filter(function(x){return x.length>=4;}),a=document.querySelectorAll('a,article,li,[role=button],div');for(var k=0;k<keys.length;k++)for(var i=0;i<a.length;i++){var s=txt(a[i]);if(s&&s.indexOf(keys[k])>=0&&vis(a[i]))return a[i].closest&&a[i].closest('a')||a[i];}return null;}function ready(){if(c.kind==='video'){var v=document.querySelector('video');if(v&&vis(v)){try{v.scrollIntoView({block:'start'});v.play();}catch(x){}return true;}}if(c.kind==='comic'){var z=document.querySelectorAll('main img,[class*=reader] img,[class*=comic] img');if(z.length>5)return true;}return false;}function tick(){n++;if(ready())return;var h=hit();if(h&&clk(h))return;var i=input();if(i&&c.title){setv(i,c.title);if(Date.now()-last>3000){last=Date.now();try{i.focus();i.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));}catch(x){}var f=i.closest&&i.closest('form');try{if(f&&f.requestSubmit)f.requestSubmit();else if(f)f.submit();}catch(x2){}}}if(n>60)clearInterval(timer);}var timer=setInterval(tick,700);setTimeout(tick,300);}+')('+JSON.stringify(cfg)+');';}
  function directAudio(url,title){url=C.s(url).trim();if(!url)return'toast://没有可用音频';return JSON.stringify({urls:[url],names:[title||'播放'],headers:[{'User-Agent':C.ua}]});}
  return{nativePlay:nativePlay,bridgeUrl:bridgeUrl,bridgeScript:bridgeScript,directAudio:directAudio};
})();
