/* ACFAN 0.1.0-test.5 provider - restore Stable 0.4.7/0.4.8 verified contracts */
var ACFANProvider=(function(){
  var C=ACFANCore,P=ACFANProtocol;
  C.version='0.1.0-test.5';C.build=10105;
  C.diag=function(stage,msg,extra){var x={time:Date.now(),version:C.version,build:C.build,stage:C.s(stage),msg:C.s(msg).slice(0,2200),extra:extra||{}};try{setItem(C.K.diag,JSON.stringify(x));}catch(e){}return x;};
  function deepFirst(root,keys){return C.first(C.deep(root||{},keys,0));}
  function cover(root){root=root||{};return deepFirst(root,['coverImg','videoCover','videoCoverImg','generatedCoverImg','templateCoverImg','defaultVideoPoster','coverUrl','horizontalCover','verticalCover','imageUrl','imgUrl','thumbUrl','thumbURL','posterMainUrl','posterDownloadUrl','verticalImg','backImg','cardImg','dynamicImg','comicsCover','comicCover','fictionImg','fictionCover','fictionCoverImg','cover','poster','img','image','images','picture','pictures']);}
  function mediaPath(root){root=root||{};var v=deepFirst(root,['videoUrl','playUrl','videoUri','m3u8Url','m3u8','playPath','sourcePath','audioUrl','audioPath']);if(v)return C.s(v);var g=deepFirst(root,['path','url']);return /(?:\.m3u8|\.mp4|\/api\/m3u8\/|^(?:jpc|jpd|hls|video|media)\/)/i.test(C.s(g))?C.s(g):'';}
  function userName(root){var u=C.deep(root||{},['user','userInfo','blogger','authorInfo'],0)||{};return C.s(C.pick(u,['nickname','nickName','userName','username','name'],C.deep(root||{},['nickname','nickName','userName','authorName'],0)));}
  function videoInfo(x){x=x||{};var v=x.video||x.videoInfo||x.content||x;if(v&&v.video&&typeof v.video==='object')v=v.video;return{kind:'video',id:C.s(C.pick(v,['videoId','id','vid','lsjVideoId'],C.deep(x,['videoId','lsjVideoId','vid'],0))),title:C.clean(C.pick(v,['videoTitle','title','name','video_title'],C.deep(x,['videoTitle','title','name'],0)||'未命名视频')),img:C.s(cover(v)||cover(x)),author:userName(x)||C.clean(C.pick(v,['authorName','author'],'')||''),duration:C.s(C.deep(x,['duration','videoDuration','playTime','video_duration'],0)),watch:C.s(C.deep(x,['watchNum','viewNum','playNum','fakeWatchNum','statisticsTimes'],0)),like:C.s(C.deep(x,['likeNum','likes','favoriteNum','likeCount'],0)),uri:mediaPath(x),desc:C.clean(C.deep(x,['description','desc','introduction','videoDesc'],0)),raw:x};}
  function comicInfo(x){x=x||{};return{kind:'comic',id:C.s(C.pick(x,['comicsId','comicId','id','comic_id'],C.deep(x,['comicsId','comicId'],0))),title:C.clean(C.pick(x,['comicsTitle','comicTitle','title','name','comic_title'],C.deep(x,['comicsTitle','comicTitle','title'],0)||'未命名漫画')),img:C.s(cover(x)),author:C.clean(C.deep(x,['authorName','author','nickName','nickname'],0)),desc:C.clean(C.deep(x,['subTitle','subtitle','description','desc','info','introduction'],0)),raw:x};}
  function fictionInfo(x,mode){x=x||{};return{kind:mode==='audio'?'audio':'fiction',id:C.s(C.pick(x,['fictionId','bookId','novelId','id'],C.deep(x,['fictionId','bookId'],0))),title:C.clean(C.pick(x,['fictionTitle','bookTitle','bookName','novelTitle','title','name'],C.deep(x,['fictionTitle','bookTitle','title'],0)||'未命名')),img:C.s(cover(x)),author:C.clean(C.deep(x,['authorName','author','nickName','nickname'],0)),desc:C.clean(C.deep(x,['description','desc','info','introduction'],0)),raw:x};}
  function dynamicInfo(x){x=x||{};return{kind:'community',id:C.s(C.pick(x,['dynamicId','postId','id'],C.deep(x,['dynamicId','postId'],0))),title:C.clean(C.deep(x,['dynamicContent','content','contentText','text','title'],0)||'社区动态'),img:C.s(cover(x)),author:userName(x),like:C.s(C.deep(x,['likeNum','likeCount','likes'],0)),comment:C.s(C.deep(x,['commentNum','commentCount','comments'],0)),raw:x};}
  function namedRows(rows,idKeys,nameKeys){var out=[];for(var i=0;i<(rows||[]).length;i++){var x=rows[i]||{},id=C.pick(x,idKeys,''),name=C.pick(x,nameKeys,'');if(!id||!name||/(?:测试|test|comicsclass|ces\d*|罗峰测试|竖版|竖横|横滑|六宫格|四宫格|两格|专题\d|^2026\d+)/i.test(C.s(name)))continue;out.push({id:C.s(id),name:C.clean(name),raw:x});}return C.uniq(out,function(z){return z.id;});}
  function tryData(path,params,methods,timeout){try{return P.tryApi(path,params,methods||['GET','POST'],{timeout:timeout||3200});}catch(e){C.diag('PROVIDER_SKIP',path+' | '+String(e.message||e));return null;}}
  function tryRows(path,params,methods,timeout){return C.arr(tryData(path,params,methods,timeout));}
  function stations(restricted){return namedRows(tryRows('station/stations',{classifyId:4,page:1,pageSize:40,restricted:restricted?1:0},['GET','POST'],3600),['stationId','stationID','id'],['stationName','stationTitle','title','name']);}
  function catalog(kind){var type=kind==='video'?4:2,rows=tryRows('video/classTypeList',{type:type,restricted:0},['GET','POST'],3400);if(!rows.length)rows=tryRows('video/classifyList',{type:type,restricted:0},['GET','POST'],3400);return namedRows(rows,['classifyId','classTypeId','videoTypeId','typeId','id'],['classifyTitle','classTypeTitle','classifyName','classTypeName','videoTypeName','title','name']);}
  function tags(classId){var cid=C.n(classId),rows=tryRows('video/tags/getTagsZ',{videoTypeId:cid,classifyId:cid,restricted:0},['GET','POST'],3200),out=[],seen={};function add(x,mode){var name=C.s(C.pick(x,['videoTagName','tagName','tagsTitle','tagTitle','name','title'],'')||''),value=C.s(C.pick(x,['videoTagValue','tagValue','videoTagKey','tagKey','value','id'],name)||name);if(!name)name=value;if(name&&!seen[value+'|'+name]){seen[value+'|'+name]=1;out.push({id:value,name:C.clean(name),value:value,mode:mode,raw:x});}}for(var i=0;i<rows.length;i++)add(rows[i],'apkTag');if(!out.length){var z=tryRows('video/getZoneListByClassifyId',{classifyId:cid},['GET','POST'],2600);for(var j=0;j<z.length;j++){var zid=C.s(C.pick(z[j],['zoneId','id'],'')),zn=C.s(C.pick(z[j],['zoneTitle','zoneName','title','name'],''));if(zid&&zn)out.push({id:zid,name:C.clean(zn),value:zid,mode:'zone',raw:z[j]});}}if(!out.length){var n=tryRows('video/tags/getTags',{videoTypeId:cid,classifyId:cid,restricted:0},['GET','POST'],2400);for(var k=0;k<n.length;k++)add(n[k],'tag');}return C.uniq(out,function(z){return z.id+'|'+z.name;});}
  function comicStations(){return namedRows(tryRows('comics/station/getComicsStations',{page:1,pageNum:1,pageSize:40},['GET','POST'],3600),['stationId','comicsStationId','id'],['stationName','stationTitle','name','title']);}
  function fictionTags(mode){var type=mode==='audio'?2:1;return namedRows(tryRows('fiction/other/tagList',{fictionType:type,type:type},['POST','GET'],3600),['fictionTagId','tagId','categoryId','id'],['fictionTagName','tagName','categoryName','name','title']);}
  function communityCategories(){return namedRows(tryRows('dynamic/category/tree',{},['GET','POST'],3200),['categoryId','dynamicType','id'],['categoryName','dynamicTypeName','name','title']);}
  function select(rows,id){id=C.s(id);for(var i=0;i<rows.length;i++)if(C.s(rows[i].id)===id)return rows[i];return rows[0]||null;}
  function list(section,page,state){page=Math.max(1,Number(page||1));state=state||{};var size=C.pageSize(),sort=Number(state.sort||1);
    if(section==='featured'||section==='lifan'){var restricted=section==='lifan'?1:0,ss=stations(restricted),st=select(ss,state.station);if(!st)return{filters:{stations:ss},items:[]};if(page===1&&st.raw&&Array.isArray(st.raw.videoList)&&st.raw.videoList.length)return{filters:{stations:ss,selectedStation:st},items:st.raw.videoList.slice(0,size)};return{filters:{stations:ss,selectedStation:st},items:tryRows('station/getStationMore',{stationId:C.n(st.id),page:page,pageNum:page,pageSize:size,sortType:sort,restricted:restricted},['GET','POST'],3800)};}
    if(section==='anime'||section==='video'){var cs=catalog(section),cl=select(cs,state.classId);if(!cl)return{filters:{classes:cs},items:[]};var ts=tags(cl.id),tg=null;for(var t=0;t<ts.length;t++)if(C.s(ts[t].id)===C.s(state.zoneId)){tg=ts[t];break;}var cid=C.n(cl.id),rows=[];
      if(tg&&tg.mode==='zone')rows=tryRows('video/queryVideoByZone',{page:page,pageNum:page,pageSize:size,zoneId:C.n(tg.id),classifyId:cid,sortType:sort},['GET','POST'],3600);
      if(tg&&!rows.length){var name=C.s(tg.name),value=C.s(tg.value||tg.id||name),tries=[{tagsTitle:value,tagTitle:value,videoTagValue:value,classifyId:cid,videoTypeId:cid,page:page,pageNum:page,pageSize:size,limit:size,sortType:sort,restricted:0},{tagsTitle:name,tagTitle:name,videoTagName:name,videoTagValue:value,classifyId:cid,videoTypeId:cid,page:page,pageNum:page,pageSize:size,limit:size,sortType:sort,restricted:0},{tagsTitle:name,classifyId:cid,page:page,pageNum:page,pageSize:size,limit:size,sortType:sort,restricted:0}];for(var ti=0;ti<tries.length&&!rows.length;ti++)rows=tryRows('video/tagTitleList',tries[ti],['GET','POST'],3600);if(!rows.length)rows=tryRows('video/queryVideoByTag',{page:page,pageNum:page,pageSize:size,tagTitle:name,tagsTitle:name,classifyId:cid,videoTypeId:cid,sortType:sort},['GET','POST'],3200);}
      if(!rows.length)rows=tryRows('video/getByClassify',{classifyId:cid,page:page,pageNum:page,pageSize:size,limit:size,sortType:sort,restricted:0},['GET','POST'],3600);return{filters:{classes:cs,selectedClass:cl,zones:ts,selectedZone:tg},items:rows};}
    if(section==='short'){var lt=Number(state.shortType||3);return{filters:{},items:tryRows('video/list',{page:page,pageNum:page,pageSize:15,loadType:lt},['GET','POST'],3800)};}
    if(section==='comic'){var cst=comicStations(),sel=select(cst,state.station);if(!sel)return{filters:{stations:cst},items:[]};if(page===1&&sel.raw&&Array.isArray(sel.raw.comicsBaseList)&&sel.raw.comicsBaseList.length)return{filters:{stations:cst,selectedStation:sel},items:sel.raw.comicsBaseList.slice(0,size)};return{filters:{stations:cst,selectedStation:sel},items:tryRows('comics/station/getStationComicsMore',{stationId:C.n(sel.id),comicsStationId:C.n(sel.id),page:page,pageNum:page,pageSize:size,sortType:sort},['GET','POST'],4000)};}
    if(section==='fiction'||section==='audio'){var ft=fictionTags(section),tag=select(ft,state.tagId),fp={page:page,pageNum:page,pageSize:size,limit:size,sortType:1,fictionType:section==='audio'?2:1};if(tag){fp.tagId=C.n(tag.id);fp.fictionTagId=C.n(tag.id);fp.categoryId=C.n(tag.id);}if(section==='audio')fp.isAudio=1;return{filters:{tags:ft,selectedTag:tag},items:tryRows('fiction/base/findList',fp,['POST','GET'],4200)};}
    if(section==='community'){var cats=communityCategories(),cat=select(cats,state.categoryId),cp={page:page,pageNum:page,pageSize:size,limit:size};if(cat){cp.categoryId=C.n(cat.id);cp.dynamicType=C.n(cat.id);}return{filters:{categories:cats,selectedCategory:cat},items:tryRows('community/dynamic/list',cp,['GET','POST'],4200)};}
    return{filters:{},items:[]};}
  function search(kind,q,page){page=Math.max(1,Number(page||1));var size=C.pageSize(),p={page:page,pageNum:page,pageSize:size,limit:size,keyword:q,title:q};if(kind==='video'){var tries=[['video/queryVideoByTitle',{page:page,pageNum:page,pageSize:size,title:q,videoType:1}],['search/keyWordV2',{page:page,pageNum:page,pageSize:size,searchWord:q,keyword:q,keyWord:q,searchType:1}],['search/keyWord',{page:page,pageNum:page,pageSize:size,searchWord:q,keyword:q,keyWord:q,searchType:1}]];for(var i=0;i<tries.length;i++){var r=tryRows(tries[i][0],tries[i][1],['GET','POST'],3800);if(r.length)return r;}return[];}if(kind==='comic'){p.comicsTitle=q;return tryRows('comics/base/findList',p,['GET','POST'],4200);}if(kind==='fiction'||kind==='audio'){p.fictionTitle=q;p.fictionType=kind==='audio'?2:1;if(kind==='audio')p.isAudio=1;return tryRows('fiction/base/findList',p,['POST','GET'],4200);}if(kind==='community'){p.content=q;return tryRows('community/dynamic/list',p,['GET','POST'],4200);}return[];}
  function detail(kind,id){id=C.n(id);var path='',ps=[];if(kind==='video'||kind==='short'){path='video/getVideoById';ps=[{videoId:id},{id:id}];}else if(kind==='comic'){path='comics/base/info';ps=[{comicsId:id},{comicId:id},{id:id}];}else if(kind==='fiction'||kind==='audio'){path='fiction/base/info';ps=[{fictionId:id},{bookId:id},{id:id}];}else if(kind==='community'){path='community/dynamic/dynamicInfo';ps=[{dynamicId:id},{id:id}];}for(var i=0;i<ps.length;i++){var x=tryData(path,ps[i],['GET','POST'],4200);if(x)return x;}return{};}
  function comicChapters(root){var a=root&&Array.isArray(root.chapterList)?root.chapterList:[];var out=[];for(var i=0;i<a.length;i++){var x=a[i]||{},id=C.pick(x,['chapterId','id'],''),title=C.pick(x,['chapterTitle','title','name'],'第'+(i+1)+'话');if(id)out.push({id:C.s(id),title:C.clean(title),raw:x});}return out;}
  function comicChapter(comicId,chapterId){return tryData('comics/base/chapterInfo',{chapterId:C.n(chapterId)},['GET','POST'],4400)||{};}
  function comicImages(root){root=root||{};var domain=C.s(C.pick(root,['domain','imgDomain'],'')||''),a=Array.isArray(root.imgList)?root.imgList:[],out=[];for(var i=0;i<a.length;i++){var s=C.s(a[i]).trim();if(s)out.push({url:s,domain:domain});}return out;}
  function fictionChapters(root){var a=C.arr(C.deep(root||{},['chapterList','chapters'],0)),out=[];for(var i=0;i<a.length;i++){var x=a[i]||{},id=C.pick(x,['chapterId','fictionChapterId','id'],''),title=C.pick(x,['chapterTitle','chapterName','title','name'],'第'+(i+1)+'章');if(id)out.push({id:C.s(id),title:C.clean(title),raw:x});}return out;}
  function fictionChapter(fid,cid){return tryData('fiction/base/chapterInfo',{fictionId:C.n(fid),chapterId:C.n(cid)},['POST','GET'],4400)||tryData('fiction/base/chapterInfo',{chapterId:C.n(cid)},['POST','GET'],4400)||{};}
  function fictionPayload(root){var texts=[],audios=[],images=[],seenT={},seenA={},seenI={},count=0,base=C.s(C.deep(root||{},['playbackDomain','audioDomain','mediaDomain'],0)||''),auth=C.s(C.deep(root||{},['playbackAuthKey','authKey','auth_key'],0)||'');function add(a,sn,s){s=C.s(s).trim();if(s&&!sn[s]){sn[s]=1;a.push(s);}}function join(b,p){p=C.s(p).trim();if(!p)return'';if(p.indexOf('//')===0)return'https:'+p;if(/^https?:\/\//i.test(p))return p;if(b&&/^https?:\/\//i.test(b))return b.replace(/\/+$/,'')+'/'+p.replace(/^\/+/, '');return p;}function walk(v,key,d){if(v===undefined||v===null||d>11||count>16000)return;if(typeof v==='string'){var s=v.trim(),low=C.s(key).toLowerCase();if(/content|text|body|paragraph/.test(low)&&s&&!/^https?:\/\//i.test(s)&&s.length>1)add(texts,seenT,s);if(/audio|sourcepath|playpath|audiourl|mediaurl/.test(low)||/\.(?:mp3|m4a|aac|wav|ogg|flac|m3u8)(?:[?#]|$)/i.test(s)){var u=join(base,s);if(auth&&u&&u.indexOf('auth_key=')<0&&u.indexOf('authKey=')<0)u+=(u.indexOf('?')>=0?'&':'?')+'auth_key='+encodeURIComponent(auth);add(audios,seenA,u);}if(/image|img|picture|pic/.test(low)&&(/^(https?:)?\/\//i.test(s)||/\.(?:png|jpe?g|webp|gif)(?:[?#]|$)/i.test(s)))add(images,seenI,s);return;}if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],key,d+1);return;}if(typeof v!=='object')return;count++;for(var k in v)walk(v[k],k,d+1);}walk(root,'',0);return{texts:texts,audios:audios,images:images};}
  function comments(videoId,page,sort){return tryRows('video/commentList',{videoId:C.n(videoId),page:page,pageNum:page,pageSize:20,sortType:sort==='new'?'new':'hot'},['GET','POST'],4000);}
  function debugSnapshot(section){var st={sort:'1',shortType:'3'},r=list(section,1,st),rows=r.items||[],out={version:C.version,section:section,host:getItem(C.K.host,''),imgDomain:getItem(C.K.imgDomain,''),filters:r.filters||{},samples:[]};for(var i=0;i<rows.length&&i<6;i++){var info=section==='comic'?comicInfo(rows[i]):(section==='fiction'||section==='audio'?fictionInfo(rows[i],section):(section==='community'?dynamicInfo(rows[i]):videoInfo(rows[i])));out.samples.push({id:info.id,title:info.title,img:info.img,coverFields:{coverImg:C.deep(rows[i],['coverImg'],0),videoCover:C.deep(rows[i],['videoCover'],0),imageUrl:C.deep(rows[i],['imageUrl'],0),imgUrl:C.deep(rows[i],['imgUrl'],0),thumbUrl:C.deep(rows[i],['thumbUrl','thumbURL'],0),posterMainUrl:C.deep(rows[i],['posterMainUrl'],0),verticalImg:C.deep(rows[i],['verticalImg'],0),backImg:C.deep(rows[i],['backImg'],0),cardImg:C.deep(rows[i],['cardImg'],0)}});}return out;}
  function debugAnime(){var cs=catalog('anime'),cl=cs[0]||null,tg=cl?tags(cl.id):[];return{host:getItem(C.K.host,''),classCount:cs.length,firstClass:cl,tags:tg.slice(0,12),diag:C.getDiag()};}
  function debugComic(){var ss=comicStations(),st=ss[0]||null,rows=st?list('comic',1,{station:st.id,sort:'1'}).items:[],ci=rows.length?comicInfo(rows[0]):null,det=ci?detail('comic',ci.id):{},ch=comicChapters(det);return{stationCount:ss.length,firstStation:st,firstComic:ci,detailKeys:det&&typeof det==='object'?Object.keys(det).slice(0,60):[],chapterCount:ch.length,firstChapter:ch[0]||null,domain:C.s(C.pick(det||{},['domain','imgDomain'],'')||'')};}
  return{cover:cover,mediaPath:mediaPath,videoInfo:videoInfo,comicInfo:comicInfo,fictionInfo:fictionInfo,dynamicInfo:dynamicInfo,stations:stations,catalog:catalog,tags:tags,comicStations:comicStations,fictionTags:fictionTags,list:list,search:search,detail:detail,comicChapters:comicChapters,comicChapter:comicChapter,comicImages:comicImages,fictionChapters:fictionChapters,fictionChapter:fictionChapter,fictionPayload:fictionPayload,comments:comments,debugSnapshot:debugSnapshot,debugAnime:debugAnime,debugComic:debugComic};
})();
