/* Hanime1 Test9 filter state */
(function(H,P){
function tags(){try{var a=JSON.parse(getMyVar('hanime8_tags','[]'));return Array.isArray(a)?a:[];}catch(e){return [];}}
H.state=function(){var c=P.filterCatalog||{};return {sort:getMyVar('hanime8_sort','最新上傳'),genre:getMyVar('hanime8_genre',''),date:getMyVar('hanime8_date',''),duration:getMyVar('hanime8_duration',''),tags:tags(),broad:getMyVar('hanime8_broad','0')==='1',cat:c};};
H.selectUrl=function(title,key,arr){var opts=(arr||[]).map(function(x){return x[0];}),js="var a="+JSON.stringify(arr||[])+";for(var i=0;i<a.length;i++){if(String(a[i][0])===String(input)){putMyVar('"+key+"',String(a[i][1]));break;}}refreshPage(false);return 'hiker://empty';";return 'select://'+JSON.stringify({title:title,options:opts,col:3,js:js});};
H.selectTagUrl=function(){var a=[['全部标签',''],['无码','無碼'],['中文字幕','中文字幕'],['1080P','1080p'],['60FPS','60FPS'],['AI解码','AI解碼'],['中文配音','中文配音'],['同人作品','同人作品'],['ASMR','ASMR']],o=a.map(function(x){return x[0];}),js="var a="+JSON.stringify(a)+";for(var i=0;i<a.length;i++){if(String(a[i][0])===String(input)){putMyVar('hanime8_tags',a[i][1]?JSON.stringify([a[i][1]]):'[]');break;}}refreshPage(false);return 'hiker://empty';";return 'select://'+JSON.stringify({title:'标签',options:o,col:3,js:js});};
H.toggleTag=function(t){return $('#noLoading#').lazyRule(function(x){var a=[];try{a=JSON.parse(getMyVar('hanime8_tags','[]'));if(!Array.isArray(a))a=[];}catch(e){}var i=a.indexOf(x);if(i>=0)a.splice(i,1);else a.push(x);putMyVar('hanime8_tags',JSON.stringify(a));refreshPage(false);return 'hiker://empty';},t);};
H.clearFilters=function(){return $('#noLoading#').lazyRule(function(){putMyVar('hanime8_sort','最新上傳');clearMyVar('hanime8_genre');clearMyVar('hanime8_date');clearMyVar('hanime8_duration');clearMyVar('hanime8_tags');clearMyVar('hanime8_broad');refreshPage(false);return 'hiker://empty';});};
H.summary=function(s){var a=[];if(s.genre)a.push(H.label(s.cat.genres,s.genre));if(s.sort)a.push(H.label(s.cat.sorts,s.sort));if(s.date)a.push(H.label(s.cat.dates,s.date));if(s.duration)a.push(H.label(s.cat.durations,s.duration));if(s.tags.length)a.push(s.tags.join(' / '));return a.join(' · ')||'全部影片';};
})(HanimeUI9,HanimeProvider);
