/* JavBus Remote Runtime 2.0.0-alpha1 - native Hiker product/UI layer */
var JavBusRemoteRuntime=(function(){
  var R={version:'2.0.0-alpha1',build:'2.0.0-alpha1'};
  function C(){if(typeof JavBusCore!=='object')throw new Error('JavBusCore 未加载');return JavBusCore;}
  function section(title,desc){return{title:'▌ '+title,desc:desc||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}};}
  function activeTitle(name,on){return on?'““””<b><font color=#E75480>'+name+'</font></b>':name;}
  function page(path,params){return C().page(path,params);}
  function movieUrl(m){return page('javbusDetail',{id:m.id,type:m.type||'normal'});}
  function actorUrl(a){return page('javbusActor',{id:a.id,type:a.type||'normal'});}
  function movieCard(m){var tags=(m.tags||[]).join(' · '),desc=[m.id,m.date,tags].filter(function(x){return !!x;}).join(' · ');return{title:m.title||m.id,desc:desc,img:m.img,pic_url:m.img,url:movieUrl(m),col_type:'movie_3',extra:{pageTitle:m.id||m.title,lineVisible:false,longClick:[{title:'收藏/取消收藏',js:$.toString(function(m){var J=$.require('javbus');return J.toggleVideoFavorite(m);},m)},{title:'复制番号',js:$.toString(function(id){return'copy://'+id;},m.id)},{title:'云盘君搜番号',js:$.toString(function(id){if(fetch('hiker://home@云盘君.简')==='null')return'toast://未安装 云盘君.简';return'hiker://page/sou?rule=云盘君.简&p=fypage&hideSetting=true&searchTerms='+encodeURIComponent(id);},m.id)}]}};}
  function actorCard(a){return{title:a.name||a.id,desc:C().typeName(a.type),img:a.img,pic_url:a.img,url:actorUrl(a),col_type:'card_pic_3',extra:{pageTitle:a.name||a.id,lineVisible:false}};}
  function listError(d,msg,url){d.push(section('暂时无法读取',''));d.push({title:'页面读取失败',desc:msg||'JavBus 当前连接失败',url:url?'web://'+url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}});}
  function renderMovies(d,html,type,emptyText){var a=C().parseMovies(html,type),i;for(i=0;i<a.length;i++)d.push(movieCard(a[i]));if(!a.length)d.push({title:emptyText||'没有解析到影片',desc:'可尝试刷新、切换磁力筛选，或从原站网页打开确认',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}});return a.length;}
  function typeTabs(d,current,refreshMode){['normal','uncensored','western'].forEach(function(t){d.push({title:activeTitle(C().typeName(t),current===t),url:$('#noLoading#').lazyRule(function(t,mode){if(mode==='home'){putMyVar('javbus_home_type',t);refreshPage(false);return'hiker://empty';}return'hiker://page/'+mode+'?rule='+MY_RULE.title+'&simple=true&type='+encodeURIComponent(t);},t,refreshMode||'home'),col_type:'scroll_button',extra:{lineVisible:false}});});}
  function magnetToggle(d){var on=C().magMode();d.push({title:activeTitle(on==='all'?'全部影片':'只看有磁力',true),url:'select://'+JSON.stringify({title:'影片范围',options:['全部影片','只看有磁力'],col:2,js:$.toString(function(){setItem('javbus_mag_mode',input==='只看有磁力'?'exist':'all');refreshPage(false);return'toast://已切换 '+input;})}),col_type:'scroll_button',extra:{lineVisible:false}});}
  function topSearch(d,type){d.push({title:'搜索番号 / 标题 / 演员 / 厂商',url:$.toString(function(type){var kw=String(input||'').trim();if(!kw)return'toast://请输入关键词';return'hiker://page/javbusSearch?rule='+MY_RULE.title+'&simple=true&type='+encodeURIComponent(type)+'&kw='+encodeURIComponent(kw);},type),col_type:'input',extra:{titleVisible:false,lineVisible:false,hint:'搜索番号、标题、演员、厂商…'}});}
  function quickTools(d,type){d.push({title:'演员',img:'hiker://images/icon_people',url:page('javbusActors',{type:type}),col_type:'icon_small_4',extra:{lineVisible:false}});d.push({title:'分类',img:'hiker://images/icon_menu5',url:page('javbusGenres',{type:type}),col_type:'icon_small_4',extra:{lineVisible:false}});d.push({title:'收藏',img:'hiker://images/icon_star',url:page('javbusFav',{}),col_type:'icon_small_4',extra:{lineVisible:false}});d.push({title:'更多',img:'hiker://images/icon_menu6',url:page('javbusMore',{}),col_type:'icon_small_4',extra:{lineVisible:false}});}

  R.home=function(){var d=[],type=getMyVar('javbus_home_type',getItem('javbus_default_type','normal')||'normal'),pg=Number(MY_PAGE||1),url=C().listUrl(type,pg,'',''),html='';if(pg===1){setPageTitle('JavBus');typeTabs(d,type,'home');magnetToggle(d);topSearch(d,type);quickTools(d,type);d.push(section(C().typeName(type)+' · 最新影片',C().magMode()==='exist'?'仅显示有磁力资源':'显示全部影片'));}html=C().fetchHtml(url);if(!html){if(pg===1)listError(d,'无法连接 JavBus；旧版仍可从正式通道恢复',url);setResult(d);return;}renderMovies(d,html,type,'本页暂无影片');setResult(d);};

  R.search=function(){var d=[],kw=decodeURIComponent(getParam('kw','')||getMyVar('javbus_search_kw','')||''),type=getParam('type','normal')||'normal',pg=Number(MY_PAGE||1);if(!kw&&typeof MY_KEYWORD!=='undefined')kw=String(MY_KEYWORD||'');kw=String(kw||'').trim();if(pg===1){setPageTitle('搜索 · '+kw);typeTabs(d,type,'javbusSearch');magnetToggle(d);d.push(section('搜索结果',kw||'未输入关键词'));}if(!kw){d.push({title:'请输入搜索关键词',url:'hiker://empty',col_type:'text_center_1'});setResult(d);return;}putMyVar('javbus_search_kw',kw);var url=C().searchUrl(type,kw,pg),html=C().fetchHtml(url);if(!html){listError(d,'搜索请求失败',url);setResult(d);return;}renderMovies(d,html,type,'没有找到匹配影片');setResult(d);};

  R.filter=function(){var d=[],type=getParam('type','normal')||'normal',kind=getParam('kind','genre')||'genre',id=getParam('id',''),name=decodeURIComponent(getParam('name','')||id),pg=Number(MY_PAGE||1),url=C().listUrl(type,pg,kind,id),html=C().fetchHtml(url);if(pg===1){setPageTitle(name);d.push(section(name,C().typeName(type)+' · '+kind));}if(!html){listError(d,'筛选页面读取失败',url);setResult(d);return;}renderMovies(d,html,type,'暂无相关影片');setResult(d);};

  R.genres=function(){var d=[],type=getParam('type','normal')||'normal',html='',url=C().genreUrl(type);setPageTitle('分类');typeTabs(d,type,'javbusGenres');d.push(section(C().typeName(type)+'分类','来自 JavBus 分类页'));html=C().fetchHtml(url);if(!html){listError(d,'分类页读取失败',url);setResult(d);return;}var a=C().parseGenres(html,type);for(var i=0;i<a.length;i++){var g=a[i];d.push({title:g.name,url:page('javbusFilter',{type:g.type||type,kind:'genre',id:g.id,name:g.name}),col_type:'flex_button',extra:{lineVisible:false}});}if(!a.length)d.push({title:'未解析到分类',desc:'当前网站结构可能已经变化，保留网页入口便于核对',url:'web://'+url,col_type:'text_center_1'});setResult(d);};

  R.actors=function(){var d=[],type=getParam('type','normal')||'normal',pg=Number(MY_PAGE||1),url=C().actressUrl(type,pg),html='';if(pg===1){setPageTitle('演员');typeTabs(d,type,'javbusActors');d.push(section(C().typeName(type)+'演员','点击演员进入资料与作品页'));}html=C().fetchHtml(url);if(!html){if(pg===1)listError(d,'演员页读取失败',url);setResult(d);return;}var a=C().parseActors(html,type);for(var i=0;i<a.length;i++)d.push(actorCard(a[i]));if(!a.length&&pg===1)d.push({title:'未解析到演员列表',desc:'可先从影片详情点击演员进入个人页',url:'web://'+url,col_type:'text_center_1'});setResult(d);};

  R.actor=function(){var d=[],id=getParam('id',''),type=getParam('type','normal')||'normal',pg=Number(MY_PAGE||1),url=C().listUrl(type,pg,'star',id),html=C().fetchHtml(url);if(!html){listError(d,'演员页面读取失败',url);setResult(d);return;}if(pg===1){var a=C().parseActorProfile(html,id,type),saved=C().isFav('actor',id);setPageTitle(a.name||id);d.push({title:a.name||id,desc:(a.fields||[]).join('\n')||C().typeName(type)+'演员',img:a.img,pic_url:a.img,url:'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});d.push({title:saved?'已收藏':'收藏演员',url:$('#noLoading#').lazyRule(function(a){var J=$.require('javbus'),r=J.toggleActorFavorite(a);refreshPage(false);return'toast://'+(r?'已收藏演员':'已取消演员收藏');},a),col_type:'text_3',extra:{lineVisible:false}});d.push({title:'复制姓名',url:'copy://'+(a.name||id),col_type:'text_3',extra:{lineVisible:false}});d.push({title:'原站页面',url:'web://'+url,col_type:'text_3',extra:{lineVisible:false}});d.push(section('出演作品',''));}renderMovies(d,html,type,'暂无出演作品');setResult(d);};

  function clickableProp(d,label,p,type){if(!p||!p.name)return;var pi=p.path||C().pathInfo(p.href);d.push({title:label+' · '+p.name,url:page('javbusFilter',{type:pi.type||type,kind:pi.kind,id:pi.id,name:p.name}),col_type:'flex_button',extra:{lineVisible:false}});}
  function playbackButtons(d,code){var ps=[{id:'missav',name:'MissAV',icon:'https://missav.live/favicon.ico'},{id:'123av',name:'123AV',icon:'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/shared/jav-playback/assets/123av.svg'},{id:'jable',name:'Jable',icon:'https://jable.tv/favicon.ico'}];for(var i=0;i<ps.length;i++){var p=ps[i];d.push({title:p.name,img:p.icon,pic_url:p.icon,url:C().playbackUrl(p.id,code),col_type:'icon_1_left_pic',extra:{lineVisible:false,pageTitle:p.name+' · '+code}});}}
  function magnetRows(d,detail){var sort=getMyVar('javbus_mag_sort','size_desc');d.push({title:activeTitle('大小↓',sort==='size_desc'),url:$('#noLoading#').lazyRule(function(){putMyVar('javbus_mag_sort','size_desc');refreshPage(false);return'hiker://empty';}),col_type:'scroll_button'});d.push({title:activeTitle('大小↑',sort==='size_asc'),url:$('#noLoading#').lazyRule(function(){putMyVar('javbus_mag_sort','size_asc');refreshPage(false);return'hiker://empty';}),col_type:'scroll_button'});d.push({title:activeTitle('日期↓',sort==='date_desc'),url:$('#noLoading#').lazyRule(function(){putMyVar('javbus_mag_sort','date_desc');refreshPage(false);return'hiker://empty';}),col_type:'scroll_button'});d.push({title:activeTitle('日期↑',sort==='date_asc'),url:$('#noLoading#').lazyRule(function(){putMyVar('javbus_mag_sort','date_asc');refreshPage(false);return'hiker://empty';}),col_type:'scroll_button'});var ms=C().magnets(detail,sort);if(!ms.length){d.push({title:'暂无磁力资源',desc:detail.gid?'当前影片未返回磁力，或 AJAX 接口暂不可用':'详情页未取得 GID/UC，磁力接口无法请求',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}});return;}for(var i=0;i<ms.length;i++){var m=ms[i],tag=(m.hd?'高清 ': '')+(m.sub?'字幕 ': '');d.push({title:(tag?'【'+tag.trim()+'】 ':'')+(m.title||detail.id),desc:[m.size,m.date].filter(function(x){return!!x;}).join(' · ')+'\n长按可调用 123云盘 / 磁力君 / 云盘君',url:'copy://'+m.link,col_type:'text_1',extra:{lineVisible:false,longClick:C().magnetLongClicks(m.link,detail.id)}});}}

  R.detail=function(){var d=[],id=decodeURIComponent(getParam('id','')||''),type=getParam('type','normal')||'normal';if(!id){d.push({title:'缺少影片番号',url:'hiker://empty',col_type:'text_center_1'});setResult(d);return;}var url=C().detailUrl(id),html=C().fetchHtml(url);if(!html){listError(d,'影片详情读取失败',url);setResult(d);return;}var x=C().parseDetail(html,id),saved=C().isFav('video',id);setPageTitle(id);var desc=[x.date,x.length?x.length+' 分钟':'',C().typeName(type)].filter(function(v){return!!v;}).join(' · ');d.push({title:x.title||id,desc:desc,img:x.img,pic_url:x.img,url:'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});
    d.push({title:'在线播放',url:'select://'+JSON.stringify({title:'选择播放站点',options:['MissAV','123AV','Jable'],col:3,js:$.toString(function(id){var map={'MissAV':'missav','123AV':'123av','Jable':'jable'};var J=$.require('javbus');return J.play(map[input],id);},id)}),col_type:'text_4',extra:{lineVisible:false}});
    d.push({title:saved?'已收藏':'收藏',url:$('#noLoading#').lazyRule(function(x,type){var J=$.require('javbus'),ok=J.toggleVideoFavorite({id:x.id,title:x.title,img:x.img,url:'https://www.javbus.com/'+x.id,type:type});refreshPage(false);return'toast://'+(ok?'影片已收藏':'已取消收藏');},x,type),col_type:'text_4',extra:{lineVisible:false}});
    d.push({title:'复制番号',url:'copy://'+id,col_type:'text_4',extra:{lineVisible:false}});d.push({title:'原站',url:'web://'+url,col_type:'text_4',extra:{lineVisible:false}});
    d.push(section('影片资料','点击人物、厂商、系列或类别可继续筛选'));clickableProp(d,'导演',x.director,type);clickableProp(d,'制作商',x.studio,type);clickableProp(d,'发行商',x.label,type);clickableProp(d,'系列',x.series,type);for(var i=0;i<x.stars.length;i++){var s=x.stars[i],pi=s.path||C().pathInfo(s.href);d.push({title:'演员 · '+s.name,url:actorUrl({id:pi.id,name:s.name,type:pi.type||type}),col_type:'flex_button',extra:{lineVisible:false}});}for(i=0;i<x.genres.length;i++){var g=x.genres[i],gp=g.path||C().pathInfo(g.href);d.push({title:g.name,url:page('javbusFilter',{type:gp.type||type,kind:'genre',id:gp.id,name:g.name}),col_type:'flex_button',extra:{lineVisible:false}});}
    d.push(section('第三方在线播放','共用已实机验证的 JAV Playback Stable'));playbackButtons(d,id);
    if(x.samples.length){d.push(section('样品图',x.samples.length+' 张'));for(i=0;i<x.samples.length;i++){var sm=x.samples[i];d.push({title:sm.title,img:sm.thumb,pic_url:sm.thumb,url:'pics://'+sm.src,col_type:'pic_2',extra:{lineVisible:false}});}}
    d.push(section('磁力资源','点击复制；长按调用云盘/磁力工具'));magnetRows(d,x);
    if(x.related.length){d.push(section('相似影片',''));for(i=0;i<x.related.length;i++)d.push(movieCard({id:x.related[i].id,title:x.related[i].title,img:x.related[i].img,date:'',tags:[],href:x.related[i].href,type:type}));}
    setResult(d);
  };

  R.favorites=function(){var d=[],kind=getMyVar('javbus_fav_kind','video'),list=C().favs(kind);setPageTitle('本地收藏');d.push({title:activeTitle('影片',kind==='video'),url:$('#noLoading#').lazyRule(function(){putMyVar('javbus_fav_kind','video');refreshPage(false);return'hiker://empty';}),col_type:'text_2',extra:{lineVisible:false}});d.push({title:activeTitle('演员',kind==='actor'),url:$('#noLoading#').lazyRule(function(){putMyVar('javbus_fav_kind','actor');refreshPage(false);return'hiker://empty';}),col_type:'text_2',extra:{lineVisible:false}});d.push(section(kind==='actor'?'演员收藏':'影片收藏',list.length+' 条'));if(!list.length){d.push({title:'暂无收藏',desc:'在影片详情或演员页点击收藏后会出现在这里',url:'hiker://empty',col_type:'text_center_1'});setResult(d);return;}for(var i=0;i<list.length;i++){var x=list[i];if(kind==='actor'){d.push(actorCard({id:x.id,name:x.name||x.title||x.id,img:x.img||'',type:x.type||'normal'}));}else{d.push(movieCard({id:x.id,title:x.title||x.id,img:x.img||'',date:'',tags:[],type:x.type||'normal'}));}}setResult(d);};

  R.more=function(){var d=[];setPageTitle('更多');d.push(section('JavBus',''));d.push({title:'本地收藏',desc:'影片与演员独立管理，首次会兼容迁移旧 Apollo 收藏',url:page('javbusFav',{}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'设置',desc:'默认分区、磁力筛选、测试版更新与恢复',url:page('javbusSettings',{}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'JavBus 论坛',desc:'网站社区功能保留网页入口',url:'web://'+C().base+'/forum',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'JavBus 官网',desc:C().base,url:'web://'+C().base,col_type:'text_1',extra:{lineVisible:false}});d.push(section('联动工具',''));d.push({title:'磁力君.简',desc:'磁力查询 / 云盘与播放器打开方式',url:'hiker://home@磁力君.简',col_type:'text_1'});d.push({title:'云盘君.简',desc:'按番号聚合搜索云盘资源',url:'hiker://home@云盘君.简',col_type:'text_1'});d.push({title:'123云盘',desc:'磁力离线下载与盘内播放',url:'hiker://home@123云盘',col_type:'text_1'});setResult(d);};

  function bootAction(action){var boot='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/javbus/bootstrap_test_v1.js?v=20001';return $('#noLoading#').lazyRule(function(boot,action){try{require(boot,{headers:{'Cache-Control':'no-cache'}},20001);var r=JavBusBoot[action]();if(action==='check')return'toast://当前 '+r.current.version+' / 最新 '+r.latest.version+(r.hasUpdate?' · 有更新':' · 已最新');if(action==='update')return'toast://'+(r.ok?(r.changed?'已切换到 '+r.current.version:'已经是最新版'):'更新失败：'+r.error);if(action==='rollback')return'toast://'+(r.ok?'已回退到 '+r.current.version:'回退失败：'+r.error);if(action==='reinstall')return'toast://'+(r.ok?'当前测试版已重新加载':'重装失败：'+r.error);return'toast://操作完成';}catch(e){return'toast://操作失败：'+String(e.message||e);}},boot,action);}
  R.settings=function(){var d=[],def=getItem('javbus_default_type','normal')||'normal',mag=C().magMode();setPageTitle('JavBus 设置');d.push(section('浏览偏好',''));d.push({title:'默认首页 · '+C().typeName(def),url:'select://'+JSON.stringify({title:'默认首页',options:['有码','无码','欧美'],col:3,js:$.toString(function(){var m={'有码':'normal','无码':'uncensored','欧美':'western'};setItem('javbus_default_type',m[input]);putMyVar('javbus_home_type',m[input]);return'toast://默认首页已设为 '+input;})}),col_type:'text_1'});d.push({title:'影片范围 · '+(mag==='exist'?'只看有磁力':'全部影片'),url:'select://'+JSON.stringify({title:'影片范围',options:['全部影片','只看有磁力'],col:2,js:$.toString(function(){setItem('javbus_mag_mode',input==='只看有磁力'?'exist':'all');return'toast://已保存';})}),col_type:'text_1'});d.push(section('测试版维护','当前 2.0.0-alpha1 / Build 20001'));d.push({title:'检查更新',url:bootAction('check'),col_type:'text_1'});d.push({title:'更新到最新 Test',url:bootAction('update'),col_type:'text_1'});d.push({title:'回退上一 Test',url:bootAction('rollback'),col_type:'text_1'});d.push({title:'重新加载当前 Test',url:bootAction('reinstall'),col_type:'text_1'});d.push(section('说明',''));d.push({title:'解析架构',desc:'JavBus 网页 Parser / UI / 收藏 / 磁力由本程序维护；在线播放复用共享 JAV Playback Stable；旧 2026081903 仍保留为正式恢复基线。',url:'hiker://empty',col_type:'long_text'});setResult(d);};

  R.toggleVideoFavorite=function(m){return C().toggleFav('video',{id:m.id,title:m.title||m.id,img:m.img||'',url:m.url||C().detailUrl(m.id),type:m.type||'normal'});};
  R.toggleActorFavorite=function(a){return C().toggleFav('actor',{id:a.id,name:a.name||a.id,title:a.name||a.id,img:a.img||'',url:C().base+C().typePrefix(a.type)+'/star/'+a.id,type:a.type||'normal'});};
  R.play=function(provider,code){try{return C().loadPlayback('stable').resolve(provider,code);}catch(e){return'toast://播放解析失败：'+String(e.message||e);}};
  R.module=function(){return{home:R.home,search:R.search,detail:R.detail,filter:R.filter,genres:R.genres,actors:R.actors,actor:R.actor,favorites:R.favorites,more:R.more,settings:R.settings,toggleVideoFavorite:R.toggleVideoFavorite,toggleActorFavorite:R.toggleActorFavorite,play:R.play};};
  return R;
})();
