/* 汤头条 0.1.0-test.13 Runtime / dedicated short-video playback */
var TangTouTiaoRemoteRuntime=(function(){
  var instance=null;
  function diagnosticsText(){var keys=['ttt_last_featured_exact','ttt_last_detail_exact','ttt_last_access_state','ttt_last_short_provider','ttt_last_short_play','ttt_last_long_provider','ttt_last_pwa','ttt_last_image_policy','ttt_last_image_diag','ttt_last_play_sources','ttt_last_source_probe','ttt_last_play_diag','ttt_last_purchase','ttt_last_community_home','ttt_last_community_list','ttt_last_player_cfg','ttt_last_version_info','ttt_last_comic_home','ttt_last_comic_list','ttt_last_rank_exact','ttt_last_probe','ttt_last_bootstrap'],a=[];for(var i=0;i<keys.length;i++){var v=getItem(keys[i],'');if(v)a.push(keys[i]+'\n'+v);}return a.join('\n\n')||'暂无诊断记录';}
  function settings(){var d=[],s=TangTouTiaoProtocolV015.sessionInfo();setPageTitle('设置与诊断');d.push({title:'汤头条 Test13',desc:'0.1.0-test.13 · Build 10113 · 短视频专用播放 + 自适应图片',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行状态',desc:'设备 '+(s.deviceReady?'已建立':'未建立')+'｜Token '+(s.tokenReady?'已建立':'未建立')+'｜播放器 '+(s.playerReady?'已就绪':'未就绪'),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行协议诊断',url:$('#noLoading#').lazyRule(function(){try{var a=$.require('ttt').protocolProbe();refreshPage(false);return'toast://诊断完成：'+a.filter(function(x){return x.ok;}).length+'/'+a.length+' 成功';}catch(e){return'toast://诊断失败：'+e;}}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:diagnosticsText(),url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});d.push({title:'重新初始化匿名身份',desc:'仅在 Token/会话异常时使用',url:$('#noLoading#').lazyRule(function(){try{$.require('ttt').resetSession(true);return'toast://已清理，返回首页会重新握手';}catch(e){return'toast://失败：'+e;}}),col_type:'text_1',extra:{lineVisible:false}});setResult(d);}
  function purchaseAndPlay(id,title,coins,duration){try{var r=TangTouTiaoProtocolV015.call('/api/user/watchingMvByCoins',{mvId:String(id)}),d=TangTouTiaoCoreV021.dataOf(r)||{},url=String(TangTouTiaoCoreV021.pick(d,['url','play_url','playUrl'],'')||''),msg=TangTouTiaoCoreV021.text(TangTouTiaoCoreV021.pick(d,['msg','message'],'')||'');if(!url)return'toast://'+(msg||'未取得解锁后的完整播放地址');return TangTouTiaoPlaybackV018.playBest(JSON.stringify({id:String(id),title:String(title||''),expectedDuration:String(duration||''),sources:[{name:'已解锁',url:url}]}),'已解锁');}catch(e){return'toast://解锁失败：'+String(e.message||e);}}
  function parseRec(rec){try{return typeof rec==='string'?JSON.parse(rec):rec||{};}catch(e){return{};}}
  function isMp4(u){return /^https?:\/\//i.test(String(u||''))&&/\.mp4(?:\?|$)/i.test(String(u||''));}
  function direct(u,id,title,via){try{setItem('ttt_last_short_play',JSON.stringify({time:Date.now(),id:String(id||''),mode:'direct-mp4',via:via,url:String(u).substring(0,220)}));}catch(e){}return String(u)+'#isVideo=true#';}
  function shortHls(id,title,url,via){try{setItem('ttt_last_short_play',JSON.stringify({time:Date.now(),id:String(id||''),mode:'short-hls',via:via,url:String(url).substring(0,220)}));}catch(e){}return TangTouTiaoPlaybackV018.playBest(JSON.stringify({id:String(id||''),title:String(title||''),expectedDuration:'',sources:[{name:'短视频',url:String(url)}]}),'短视频');}
  function playShortById(rec){var x=parseRec(rec),id=String(x.id||'');if(!id)return'toast://缺少视频ID';try{var r=TangTouTiaoProtocolV015.call('/api/MvDetail/detail',{id:id}),it=TangTouTiaoCoreV021.detailItem(r,x),ac=TangTouTiaoCoreV021.accessState(it);TangTouTiaoCoreV021.addHistory(it);if(ac.locked){if(it.preview)return shortHls(id,it.title,it.preview,'locked-preview');return'toast://该视频需 '+ac.coins+' 汤币解锁完整版';}if(isMp4(it.sourceOrigin))return direct(it.sourceOrigin,id,it.title,'app-source-origin');if(isMp4(x.sourceOrigin))return direct(x.sourceOrigin,id,it.title,'pwa-source-origin');if(it.source240)return shortHls(id,it.title,it.source240,'app-source-240');if(it.preview)return shortHls(id,it.title,it.preview,'app-preview');}catch(e1){try{setItem('ttt_last_short_play',JSON.stringify({time:Date.now(),id:id,mode:'app-detail-error',error:String(e1.message||e1)}));}catch(e2){}}if(isMp4(x.sourceOrigin))return direct(x.sourceOrigin,id,x.title,'record-source-origin');if(x.preview)return shortHls(id,x.title,x.preview,'record-preview');return'toast://未取得短视频播放线路';}
  function module(){if(instance)return instance;if(typeof TangTouTiaoPwaV020!=='object'||typeof TangTouTiaoCoreV021!=='object'||typeof TangTouTiaoPagesV021!=='object')throw new Error('汤头条 Test13 模块未完整加载');var m={version:'0.1.0-test.13',build:10113,home:TangTouTiaoPagesV021.home,channels:TangTouTiaoPagesV021.channels,channel:TangTouTiaoPagesV021.channel,community:TangTouTiaoPagesV021.community,search:TangTouTiaoPagesV021.search,detail:TangTouTiaoPagesV021.detail,mine:TangTouTiaoPagesV021.mine,rank:TangTouTiaoPagesV021.rank,settings:settings,protocolProbe:function(){return TangTouTiaoProtocolV015.probe();},resetSession:function(full){return TangTouTiaoProtocolV015.resetSession(!!full);},sessionInfo:function(){return TangTouTiaoProtocolV015.sessionInfo();},playBest:function(p,q){return TangTouTiaoPlaybackV018.playBest(p,q);},playShortById:playShortById,playById:playShortById,playPreview:function(h,p){return TangTouTiaoPlaybackV018.playBest(p,'预览');},playDirect:function(h,p,q){return TangTouTiaoPlaybackV018.playBest(p,q);},purchaseAndPlay:purchaseAndPlay,toggleFavFromDetail:function(s){var x=JSON.parse(String(s||'{}'));return TangTouTiaoCoreV021.toggleFav(x);}};instance=m;return m;}return{version:'0.1.0-test.13',build:10113,module:module};
})();
