/* 我的规则仓库 3.5.6-rc36 - Stable-derived Fast Hybrid Control */
(function(R){
var VERSION='3.5.6-rc36',BUILD=426;
var ROOT='hiker://files/rules/asset-core-local/rule-repo-test-fast/';
var ID_KEY='hc_repo_v3_fast_channel_identity_v1';
var META_TTL=300000;
var baseManifest=R.manifest,baseImport=R.importRule,baseWorkspaceData=R.workspaceData,baseWorkspaceAction=R.workspaceAction,baseChannelInstallRaw=R.channelInstallRaw;
function parse(s){try{return JSON.parse(String(s||''));}catch(e){return null;}}
function clone(x){try{return JSON.parse(JSON.stringify(x));}catch(e){return x||{};}}
function safeId(x){return String(x||'').replace(/[^0-9A-Za-z_.-]/g,'_');}
function metaFile(id){return ROOT+'channels_'+safeId(id)+'.json';}
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Request\s+(?:failed|error)|Fetch\s+(?:failed|error)|Network\s+(?:failed|error)|Timeout\b|ETIMEDOUT\b|ECONN|ENOTFOUND\b|Forbidden\b|Unauthorized\b|Rate\s*limit\b)/i.test(t)||/^\{\s*"(?:message|error)"\s*:/i.test(t);}
function urls(path){var p=String(path||'').replace(/^\/+/,''),ts=Date.now();return[
 'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/'+p+'?_rc36='+ts,
 'https://github.com/huoguotiankong/asset-core-7f3/raw/refs/heads/main/'+p+'?_rc36='+ts,
 'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/'+p+'?_rc36='+ts
];}
function fetchText(path){var us=urls(path),es=[];for(var i=0;i<us.length;i++){try{var s=String(fetch(us[i],{timeout:i===0?2200:1800,headers:{'Cache-Control':'no-cache, no-store, max-age=0',Pragma:'no-cache'}})||'');if(bad(s))throw new Error('无效响应');return s;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error('读取失败 '+String(path||'')+'：'+es.join(' | '));}
function readMeta(id){try{var p=metaFile(id);if(!fileExist(p))return null;var x=parse(readFile(p));return x&&Array.isArray(x.channels)&&x.channels.length?x:null;}catch(e){return null;}}
function writeMeta(id,x){if(!x||!Array.isArray(x.channels)||!x.channels.length)throw new Error('channels 无效');x=clone(x);x._fastFetchedAt=Date.now();writeFile(metaFile(id),JSON.stringify(x));return x;}
function channelPath(item){return String(item&&item.channelsPath||item&&item.raw&&item.raw.channelsPath||'');}
function refreshMeta(item){var p=channelPath(item);if(!p)throw new Error('channelsPath 为空');var x=parse(fetchText(p));if(!x||!Array.isArray(x.channels)||!x.channels.length)throw new Error('channels.json 无有效通道');return writeMeta(String(item&&item.id||''),x);}
function selfMeta(){return{schema:4,id:'rule-repo',name:'我的规则仓库',updatedAt:'2026-08-25 22:10',channels:[
 {channel:'stable',label:'正式版',id:'rule-repo',name:'我的规则仓库',version:'3.5.5',build:389,displayVersion:'Stable 3.5.5 · Build 389 · 救援基线',path:'apps/tools/rule-repo/rule_repo_remote_v355.txt',mode:'remote',updatedAt:'2026-08-24',recommended:true,desc:'已验证稳定救援基线'},
 {channel:'test',label:'测试版',id:'rule-repo-test',name:'我的规则仓库·测试版',version:VERSION,baseVersion:'3.5.5',targetVersion:'3.5.6',build:BUILD,displayVersion:'Test '+VERSION+' · Build '+BUILD+' · Stable-derived Fast Hybrid',path:'apps/tools/rule-repo/rule_repo_test_v173.txt',mode:'remote-cache-first',updatedAt:'2026-08-25',recommended:false,desc:'回到 Stable 3.5.5 快启动模型；只保留 per-app channels 与安装身份修复'}
]};}
function identities(){var x=parse(getItem(ID_KEY,''));if(x&&x.schema===1&&x.apps)return x;var out={schema:1,time:Date.now(),apps:{}};try{var old=parse(getItem('hc_repo_v3_verified_install_index_v1',''));if(old&&old.apps){for(var k in old.apps)if(old.apps.hasOwnProperty(k)){var r=old.apps[k]||{};if(r.installed&&r.recognized)out.apps[k]={channel:String(r.channel||''),version:String(r.installedVersion||''),build:Number(r.installedBuild||0),ruleVersion:Number(r.ruleVersion||0),time:Number(r.verifiedAt||old.time||Date.now()),source:'migrated-verified-index'};}}}catch(e){}try{setItem(ID_KEY,JSON.stringify(out));}catch(e2){}return out;}
function saveIdentity(id,r){var x=identities();x.apps=x.apps||{};x.apps[String(id||'')]=r;x.time=Date.now();try{setItem(ID_KEY,JSON.stringify(x));}catch(e){}return r;}
function identity(id){var x=identities();return x.apps&&x.apps[String(id||'')]||null;}
function bestRemote(meta){var a=meta&&meta.channels||[],t=null;for(var i=0;i<a.length;i++){var c=a[i]||{},ch=String(c.channel||'');if(ch!=='stable'&&ch!=='test'&&ch!=='candidate')continue;if(!t||Number(c.build||0)>Number(t.build||0))t=c;}return t;}
function extractRuleVersion(text){text=String(text||'');var mark='海阔视界，首页频道￥home_rule￥',p=text.indexOf(mark),o=null;if(p>=0){try{o=JSON.parse(text.substring(p+mark.length));}catch(e){}if(o&&Number(o.version||0)>0)return Number(o.version);}var m=text.match(/["']version["']\s*:\s*(\d{6,})/i);return m?Number(m[1]):0;}
function deviceRuleVersion(title){title=String(title||'').replace(/\|/g,'').trim();if(!title)return 0;var raw=[],count=64;try{count=Math.max(64,Number(getRuleCount()||0));}catch(e){}try{raw=getLastRules(count);}catch(e2){raw=[];}if(typeof raw==='string'){try{raw=JSON.parse(raw);}catch(e3){raw=[raw];}}if(raw&&typeof raw.toArray==='function')try{raw=raw.toArray();}catch(e4){}if(!raw||raw.length===undefined)raw=[];
 function rec(v){if(v==null)return null;if(typeof v==='string'){var s=String(v).trim(),mark='海阔视界，首页频道￥home_rule￥',p=s.indexOf(mark),o=null;if(p>=0)try{o=JSON.parse(s.substring(p+mark.length));}catch(_e){}if(!o&&s.charAt(0)==='{')try{o=JSON.parse(s);}catch(_e2){}if(o)return rec(o);return null;}if(typeof v==='object'){var o=v;if(o.rule!==undefined&&o.rule!==v){var q=rec(o.rule);if(q)return q;}var name=String(o.title||o.name||o.ruleTitle||'').replace(/\|/g,'').trim(),rv=Number(o.version||o.ruleVersion||o.ver||0);if(name)return{title:name,ruleVersion:isNaN(rv)?0:rv};var ks=['content','source','ruleText','data'];for(var i=0;i<ks.length;i++)if(o[ks[i]]!==undefined&&o[ks[i]]!==v){var z=rec(o[ks[i]]);if(z)return z;}}return null;}
 for(var i=0;i<raw.length;i++){var r=rec(raw[i]);if(r&&r.title===title&&Number(r.ruleVersion||0)>0)return Number(r.ruleVersion);}return 0;}
function channelRuleVersion(c){var n=Number(c&&c.ruleVersion||c&&c.localRuleVersion||c&&c.forcedRuleVersion||0);if(n)return n;var p=String(c&&c.path||'');if(!p)return 0;var key=ROOT+'fingerprint_'+safeId(p)+'.txt';try{if(fileExist(key)){n=Number(String(readFile(key)||0));if(n)return n;}}catch(e){}try{n=extractRuleVersion(fetchText(p));if(n)writeFile(key,String(n));}catch(e2){}return Number(n||0);}
function repairIdentity(R,item){if(!item||String(item.id||'')==='rule-repo')return null;var meta=readMeta(item.id);if(!meta)return null;var rv=deviceRuleVersion(String(item.name||'')),a=meta.channels||[],matches=[];if(!rv)return null;for(var i=0;i<a.length;i++){var c=a[i]||{},crv=channelRuleVersion(c);if(crv&&crv===rv)matches.push(c);}if(matches.length!==1)return null;var c=matches[0],r={channel:String(c.channel||''),version:String(c.version||''),build:Number(c.build||0),ruleVersion:rv,time:Date.now(),source:'detail-device-repair'};saveIdentity(item.id,r);try{var m=R.installedMap();m[item.id]={version:r.version,time:Date.now(),name:item.name};setItem(R.installedKey,JSON.stringify(m));}catch(e){}return r;}
R.version=VERSION;R.build=BUILD;R.channel='test';R.baseStableVersion='3.5.5';R.baseStableBuild=389;R.targetVersion='3.5.6';R.releaseLabel='Stable-derived Fast Hybrid 22.0';R.updatedAt='2026-08-25';R.isTestChannel=function(){return true;};
R.workspaceBootstrapUrl=typeof RULE_REPO_TEST_BOOTSTRAP_URL==='string'?RULE_REPO_TEST_BOOTSTRAP_URL:'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/apps/tools/rule-repo/bootstrap_test_v173.js';R.workspaceBootstrapCache=173;
R.ruleRepoChannelFallback=function(){return selfMeta();};
R.manifest=function(force){if(force)return baseManifest.call(this,true);try{var x=this._readManifestCache?this._readManifestCache():parse(getItem(this.cacheKey,''));if(x&&Array.isArray(x.items))return x;}catch(e){}return baseManifest.call(this,true);};
R.channelMeta=function(item){if(String(item&&item.id||'')==='rule-repo')return selfMeta();return readMeta(String(item&&item.id||''));};
R.loadChannelMetaLive=function(item){if(String(item&&item.id||'')==='rule-repo')return selfMeta();return refreshMeta(item);};
R.fastChannelCache=function(item){var m=this.channelMeta(item);return m?{schema:36,time:Number(m._fastFetchedAt||0),revision:String(m._fastFetchedAt||''),sig:'rc36:'+String(item&&item.id||''),meta:m}:null;};
R.refreshFastChannelCache=function(item){var m=this.loadChannelMetaLive(item);return{schema:36,time:Number(m._fastFetchedAt||Date.now()),revision:String(m._fastFetchedAt||''),sig:'rc36:'+String(item&&item.id||''),meta:m};};
R.repairInstalledIdentityFast=function(item){return repairIdentity(this,item);};
R.actualInstalled=function(item){if(!item)return false;if(String(item.id||'')==='rule-repo')return true;if(identity(item.id))return true;try{return !!this.installedVersion(item);}catch(e){return false;}};
R.actualStatus=function(item){var installed=this.actualInstalled(item);if(item&&item.entryType==='channel-group'){if(!installed)return'版本中心';var r=identity(item.id),m=this.channelMeta(item),t=bestRemote(m);return r&&t&&Number(t.build||0)>Number(r.build||0)?'可更新':'已安装';}var v='';try{v=this.installedVersion(item);}catch(e){}if(!installed)return'未安装';return v&&this.versionCmp(String(item.version||''),v)>0?'可更新':'已安装';};
R.channelInstallRaw=function(parent,c){var x=baseChannelInstallRaw.call(this,parent,c);x.__repoParentId=String(parent&&parent.id||'');x.__repoChannel=String(c&&c.channel||'');x.__repoBuild=Number(c&&c.build||0);x.__repoRuleVersion=Number(c&&c.ruleVersion||c&&c.localRuleVersion||c&&c.forcedRuleVersion||0);return x;};
R.importRule=function(raw){var x=null;try{x=typeof raw==='string'?JSON.parse(raw):raw;x=x&&x.raw?x.raw:x;}catch(e){}var ret=baseImport.call(this,raw);if(x&&String(ret||'').indexOf('海阔视界，首页频道￥home_rule￥')===0&&String(x.__repoParentId||'')){var r={channel:String(x.__repoChannel||''),version:String(x.version||''),build:Number(x.__repoBuild||0),ruleVersion:Number(x.__repoRuleVersion||extractRuleVersion(ret)||0),time:Date.now(),source:'repo-import-rc36'};saveIdentity(x.__repoParentId,r);try{var p=this.findById(x.__repoParentId,false),m=this.installedMap();m[x.__repoParentId]={version:r.version,time:Date.now(),name:p&&p.name||x.name||x.__repoParentId};setItem(this.installedKey,JSON.stringify(m));}catch(e2){}}return ret;};
R.workspaceData=function(items,initialView,initialId){var pending='';try{pending=String(getVar('hc_repo_hybrid_pending_detail','')||'');}catch(_pe){}var view=String(initialView||''),id=String(initialId||pending||''),want=view==='detail'||!!pending;if(want&&id){try{var it=this.findById(id,false);if(it&&(String(it.entryType||'')==='channel-group'||channelPath(it))){var m=readMeta(id),age=m?Date.now()-Number(m._fastFetchedAt||0):1e15;if(!m||age>META_TTL)try{refreshMeta(it);}catch(_e){}if(!identity(id))try{repairIdentity(this,it);}catch(_e2){}}}catch(e){}}return baseWorkspaceData.call(this,items,initialView,initialId);};
R.workspaceAction=function(kind,item){if(String(kind||'')!=='check')return baseWorkspaceAction.call(this,kind,item);var seed=this.workspaceActionUrl('check'),spec=this.workspaceCoreSpec(),id=String(item&&item.id||''),path=channelPath(item);return $(seed).lazyRule(function(appId,cp,s){function core(raw){var c=JSON.parse(raw||'{}'),r=null,first='';try{r=$.require(String(c.page||''));}catch(e){first=String(e.message||e);}if(!r||typeof r.refreshFastChannelCache!=='function'){try{require(String(c.bootstrap||''),{headers:{'Cache-Control':'no-cache'}},Number(c.cache||173));RuleRepoBoot.load();r=HikerRuleRepo;}catch(e2){throw new Error('动作 Core 加载失败'+(first?'（'+first+'）':'')+'；'+String(e2.message||e2));}}return r;}var loading=false;try{showLoading('正在读取当前程序版本…');loading=true;var r=core(s),it=r.findById(appId,false);if(!it)throw new Error('程序不存在');if(appId==='rule-repo'){hideLoading();loading=false;refreshPage(false);return'toast://当前测试仓 '+r.version+' / Build'+r.build;}r.refreshFastChannelCache(it);try{r.repairInstalledIdentityFast(it);}catch(_e){}hideLoading();loading=false;refreshPage(false);var m=r.channelMeta(it),n=m&&m.channels?m.channels.length:0;return'toast://版本已刷新 · '+n+' 个通道';}catch(e){if(loading)try{hideLoading();}catch(_e2){}return'toast://检查失败：'+String(e.message||e);}},id,path,spec);};
if(typeof R.assertRuntimeContract==='function')R.assertRuntimeContract();
})(HikerRuleRepo);
