/* 汤头条 0.1.0-test.3 Pages - startup session + cleaner navigation */
var TangTouTiaoPagesV012=(function(){
  var HOME='ttt_home_tab_v010',P=TangTouTiaoProtocolV012,C=TangTouTiaoCoreV011,U=TangTouTiaoUIV012;
  function searchInput(d){d.push({title:'搜索视频、创作者、关键词',col_type:'input',url:$.toString(function(){var w=String(input||'').trim();if(!w)return'toast://请输入搜索关键词';putMyVar('ttt_search_kw',w);return'hiker://page/tttSearch?rule=&simple=true&kw='+encodeURIComponent(w);}),extra:{defaultValue:'',titleVisible:true,onChange:$.toString(function(){})}});}
  function quick(d){var a=[['频道','channel',C.page('tttChannels')],['社区','community',C.page('tttCommunity')],['排行榜','rank',C.page('tttRank')],['我的','mine',C.page('tttMine')]];for(var i=0;i<a.length;i++)d.push(U.icon(a[i][0],a[i][1],a[i][2]));}
  function fetchFeed(path,payload){var r=P.call(path,payload||{}),list=C.normalize(r),m=P.meta(r,path);return{res:r,list:list,meta:m};}
  function header(d){searchInput(d);var tab=getMyVar(HOME,'recommend')||'recommend',tabs=[['recommend','推荐'],['short','短视频'],['long','长视频'],['community','社区']];for(var i=0;i<tabs.length;i++)d.push(U.chip(tabs[i][1],tab===tabs[i][0],U.state(HOME,tabs[i][0])));d.push(U.blank());quick(d);d.push(U.line());return tab;}
  function responseHint(d,f){var m=f&&f.meta||{},bits=[];if(m.code!=='')bits.push('code '+m.code);if(m.msg)bits.push(m.msg);var lp=getItem('ttt_last_list_path','');if(lp)bits.push(lp);d.push(U.empty('暂未识别到视频',bits.join(' · ')||('结构 '+String(m.schema||'未知'))));if(m.schema)d.push({title:'响应结构：'+m.schema,url:C.page('tttSettings'),col_type:'long_text',extra:{lineVisible:false}});}
  function home(){var d=[],pg=Number(MY_PAGE||1);setPageTitle('汤头条');if(pg>1){setResult(d);return;}var tab=header(d);try{if(tab==='community'){communityBody(d);setResult(d);return;}var path=tab==='short'?'/api/MvList/small':'/api/MvList/featuredAv',f=fetchFeed(path,{page:1,limit:30});d.push(U.section(tab==='short'?'热门短视频':tab==='long'?'精选长视频':'今日推荐',f.list.length?'已加载 '+f.list.length+' 条':(f.meta.code!==''?'接口状态 '+f.meta.code:'')));for(var i=0;i<f.list.length;i++)d.push(U.videoCard(C,f.list[i],'movie_2'));if(!f.list.length)responseHint(d,f);}catch(e){d.push(U.error('首页请求失败',e,C.page('tttSettings')));}setResult(d);}
  function channelsBody(d){d.push(U.section('内容中心','按原 APP 功能域重组，逐模块接入真实接口'));var a=[['长视频','video'],['短视频','short'],['创作者','creator'],['排行榜','rank'],['社区','community'],['话题','topic'],['图集','picture'],['小说','novel'],['有声','audio'],['漫画','comic'],['求片','find'],['合集','compilation'],['粉丝团','club'],['消息','message'],['AI 创作','ai'],['游戏','game']];for(var i=0;i<a.length;i++)d.push({title:a[i][0],url:C.page('tttChannel',{type:a[i][1],title:a[i][0]}),col_type:'text_4',extra:{lineVisible:false}});}
  function channels(){var d=[];setPageTitle('内容频道');channelsBody(d);setResult(d);}
  function channelConfig(type){var m={picture:['/api/picture/home',{}],novel:['/api/novel/home',{}],audio:['/api/audio/home',{}],comic:['/api/comic/home',{}],community:['/api/community/home',{page:1}],rank:['/api/RankList/getPlayRank',{page:1,limit:30}],creator:['/api/Creator/featured',{page:1,limit:30}],video:['/api/MvList/featuredAv',{page:1,limit:30}],short:['/api/MvList/small',{page:1,limit:30}],find:['/api/find/list',{page:1,limit:30}],compilation:['/api/compilation/list',{page:1,limit:30}],club:['/api/club/items',{page:1,limit:30}]};return m[type]||null;}
  function channel(){var d=[],type=C.param('type',''),title=C.param('title','内容频道');setPageTitle(title);var cfg=channelConfig(type);if(!cfg){d.push(U.empty(title+' 已纳入架构','该功能会在后续 Test 中接入原 APP 真实协议，不做伪数据'));setResult(d);return;}try{var f=fetchFeed(cfg[0],cfg[1]);d.push(U.section(title,f.list.length+' 条'));for(var i=0;i<f.list.length;i++)d.push(U.videoCard(C,f.list[i],type==='picture'||type==='comic'||type==='novel'?'movie_3':'movie_2'));if(!f.list.length)responseHint(d,f);}catch(e){d.push(U.error(title+' 加载失败',e,C.page('tttSettings')));}setResult(d);}
  function communityBody(d){try{var f=fetchFeed('/api/community/home',{page:1});d.push(U.section('社区动态',f.list.length?'已加载 '+f.list.length+' 条':''));for(var i=0;i<f.list.length;i++)d.push(U.videoCard(C,f.list[i],'movie_2'));if(!f.list.length)responseHint(d,f);}catch(e){d.push(U.error('社区加载失败',e,C.page('tttSettings')));}}
  function community(){var d=[];setPageTitle('社区');communityBody(d);setResult(d);}
  function search(){var d=[],kw=String(C.param('kw',getMyVar('ttt_search_kw',''))||'').trim();setPageTitle('搜索');d.push({title:'搜索视频、创作者、关键词',col_type:'input',url:$.toString(function(){var w=String(input||'').trim();if(!w)return'toast://请输入关键词';putMyVar('ttt_search_kw',w);refreshPage(false);return'hiker://empty';}),extra:{defaultValue:kw,titleVisible:true,onChange:$.toString(function(){})}});if(!kw){d.push(U.empty('输入关键词开始搜索'));setResult(d);return;}try{var f=fetchFeed('/api/MvSearch/video',{keyword:kw,page:1,limit:30});d.push(U.section('搜索结果',f.list.length+' 条'));for(var i=0;i<f.list.length;i++)d.push(U.videoCard(C,f.list[i],'movie_2'));if(!f.list.length)responseHint(d,f);}catch(e){d.push(U.error('搜索失败',e,C.page('tttSettings')));}setResult(d);}
  function detail(){var d=[],id=C.param('id',''),title=C.param('title','视频详情'),cover=C.param('cover',''),author=C.param('author','');setPageTitle(title);if(!id){d.push(U.empty('缺少视频 ID'));setResult(d);return;}try{var r=P.call('/api/MvDetail/detail',{id:id}),data=C.dataOf(r)||{},it=C.item(data);if(!it.id)it.id=id;if(!it.title||it.title==='未命名')it.title=title;if(!it.cover)it.cover=cover||C.deepImage(data);if(!it.author)it.author=author;C.addHistory(it);var media=it.play||C.deepMedia(data);d.push({title:it.title,desc:[it.author,it.desc].filter(Boolean).join('\n'),img:it.cover,pic_url:it.cover,url:media?$('#noLoading#').lazyRule(function(u){return String(u);},media):'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});d.push(U.chip(media?'▶ 立即播放':'未解析到播放地址',!!media,media?$('#noLoading#').lazyRule(function(u){return String(u);},media):'toast://当前详情未识别到真实媒体地址','text_2'));d.push(U.chip(C.isFav(id)?'★ 已收藏':'☆ 收藏',C.isFav(id),$('#noLoading#').lazyRule(function(x){var on=$.require('ttt').toggleFavFromDetail(x);refreshPage(false);return'toast://'+(on?'已收藏':'已取消收藏');},JSON.stringify(it)),'text_2'));d.push(U.line());d.push(U.section('详情信息','ID '+id));if(it.desc)d.push({title:it.desc,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});if(!media)d.push(U.empty('播放地址暂未识别','当前详情结构：'+P.schema(data)));}catch(e){d.push(U.error('详情加载失败',e,C.page('tttSettings')));}setResult(d);}
  function mine(){var d=[],tab=C.param('tab',getMyVar('ttt_mine_tab','fav')||'fav');setPageTitle('我的');d.push(U.chip('收藏',tab==='fav',U.state('ttt_mine_tab','fav'),'text_2'));d.push(U.chip('历史',tab==='history',U.state('ttt_mine_tab','history'),'text_2'));d.push(U.line());var a=tab==='history'?C.histories():C.favs();d.push(U.section(tab==='history'?'观看历史':'我的收藏',a.length+' 条'));for(var i=0;i<a.length;i++)d.push(U.videoCard(C,C.item(a[i]),'movie_2'));if(!a.length)d.push(U.empty(tab==='history'?'还没有观看记录':'还没有收藏'));d.push(U.line());d.push(U.icon('设置','settings',C.page('tttSettings')));setResult(d);}
  function rank(){var d=[];setPageTitle('排行榜');try{var f=fetchFeed('/api/RankList/getPlayRank',{page:1,limit:30});d.push(U.section('播放榜',f.list.length+' 条'));for(var i=0;i<f.list.length;i++)d.push(U.videoCard(C,f.list[i],'movie_2'));if(!f.list.length)responseHint(d,f);}catch(e){d.push(U.error('排行榜加载失败',e,C.page('tttSettings')));}setResult(d);}
  function settings(){var d=[],s=P.sessionInfo();setPageTitle('设置与诊断');d.push(U.section('汤头条 Test','0.1.0-test.3 · APK 9.6.2'));d.push({title:'会话状态',desc:'设备身份 '+(s.deviceReady?'已建立 · '+s.deviceTail:'未建立')+'｜Token '+(s.tokenReady?'已建立':'未建立'),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行协议诊断',desc:'先执行启动握手，再检测推荐 / 短视频 / 分类',url:$('#noLoading#').lazyRule(function(){try{var a=$.require('ttt').protocolProbe();return'toast://诊断完成：'+a.filter(function(x){return x.ok;}).length+'/'+a.length+' 成功';}catch(e){return'toast://诊断失败：'+e;} }),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'查看上次诊断',desc:'显示 code/msg/schema 与会话状态，不显示 Token 内容',url:$('#noLoading#').rule(function(){var d=[],s=getItem('ttt_last_probe',''),m=getItem('ttt_last_schema',''),b=getItem('ttt_last_bootstrap',''),p=getItem('ttt_last_list_path','');d.push({title:[s,b,m,p].filter(Boolean).join('\n\n')||'暂无诊断记录',url:'hiker://empty',col_type:'long_text'});setResult(d);}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'重新初始化匿名身份',desc:'清 Token/设备身份并按 APK 首次启动流程重新建立',url:$('#noLoading#').lazyRule(function(){try{$.require('ttt').resetSession(true);return'toast://匿名身份已重建，返回首页会自动重新握手';}catch(e){return'toast://重建失败：'+e;}}),col_type:'text_1',extra:{lineVisible:false}});d.push(U.line());d.push(U.section('本轮修复','根据实机 401 与 APK 反编译确认：system_oauth_id 与 system_iid 必须共用同一设备 ID；内容接口前必须先启动握手取得 AppConfigBean.token。'));setResult(d);}
  return{home:home,channels:channels,channel:channel,community:community,search:search,detail:detail,mine:mine,rank:rank,settings:settings};
})();
