/* 汤头条 0.1.0-test.3 Protocol / APK startup-session handshake */
var TangTouTiaoProtocolV012=(function(){
  var VERSION='0.1.0-test.3';
  var SECRET='132f1537f85scxpcm59f7e318b9epa51';
  var SIGN_SALT='e79465cfbb39ckcusimcuekd3b066a6e';
  var DOMAINS=['https://api1.wiimrdys.com/api.php','https://api2.wiimrdys.com/api.php'];
  var START='/api/home/getOpenAdsAndVersion';
  var UA='Mozilla/5.0 (Linux; Android 13; HikerView) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Mobile Safari/537.36';
  function jstr(s){return new java.lang.String(String(s==null?'':s));}
  function bytes(s){return jstr(s).getBytes('UTF-8');}
  function newBytes(n){return java.lang.reflect.Array.newInstance(java.lang.Byte.TYPE,n);}
  function copy(src,srcPos,dst,dstPos,len){java.lang.System.arraycopy(src,srcPos,dst,dstPos,len);}
  function concat(a,b){var o=newBytes(a.length+b.length);copy(a,0,o,0,a.length);copy(b,0,o,a.length,b.length);return o;}
  function hexUpper(a){var s='';for(var i=0;i<a.length;i++){var v=a[i];if(v<0)v+=256;var h=v.toString(16);if(h.length<2)h='0'+h;s+=h;}return s.toUpperCase();}
  function hexBytes(s){s=String(s||'');if(!s||s.length%2!==0)return null;var a=newBytes(s.length/2);for(var i=0;i<a.length;i++){var v=parseInt(s.substr(i*2,2),16);if(isNaN(v))return null;a[i]=v>127?v-256:v;}return a;}
  function digestBytes(name,a){var md=java.security.MessageDigest.getInstance(name);md.update(a);return md.digest();}
  function digestHex(name,s){var a=digestBytes(name,bytes(s)),out='';for(var i=0;i<a.length;i++){var v=a[i];if(v<0)v+=256;var h=v.toString(16);if(h.length<2)h='0'+h;out+=h;}return out;}
  function md5(s){return digestHex('MD5',s);}
  function sha256(s){return digestHex('SHA-256',s);}
  function evp(secret,keyLen,ivLen){var pass=bytes(secret),md=java.security.MessageDigest.getInstance('MD5'),need=keyLen+ivLen,all=newBytes(need),pos=0,prev=null;while(pos<need){md.reset();if(prev)md.update(prev);md.update(pass);prev=md.digest();var n=Math.min(prev.length,need-pos);copy(prev,0,all,pos,n);pos+=n;}var key=newBytes(keyLen),iv=newBytes(ivLen);copy(all,0,key,0,keyLen);copy(all,keyLen,iv,0,ivLen);return{key:key,iv:iv};}
  function encryptText(text){var p=evp(SECRET,32,16),cipher=javax.crypto.Cipher.getInstance('AES/CFB/NoPadding'),key=new javax.crypto.spec.SecretKeySpec(p.key,'AES'),iv=new javax.crypto.spec.IvParameterSpec(p.iv);cipher.init(1,key,iv);var encrypted=cipher.doFinal(bytes(text)),joined=concat(cipher.getIV(),encrypted);return hexUpper(joined);}
  function decryptText(cipherHex){var all=hexBytes(cipherHex);if(!all||all.length<17)throw new Error('响应密文长度异常');var iv=newBytes(16),body=newBytes(all.length-16);copy(all,0,iv,0,16);copy(all,16,body,0,body.length);var p=evp(SECRET,32,16),cipher=javax.crypto.Cipher.getInstance('AES/CFB/NoPadding'),key=new javax.crypto.spec.SecretKeySpec(p.key,'AES');cipher.init(2,key,new javax.crypto.spec.IvParameterSpec(iv));return String(new java.lang.String(cipher.doFinal(body),'UTF-8'));}
  function ts(){var s=String(Math.floor(Date.now()/1000));while(s.length<10)s='0'+s;return s;}
  function wrap(plain){var timestamp=ts(),data=encryptText(plain),src='_ver=v0&data='+data+'&timestamp='+timestamp+SIGN_SALT,sign=md5(sha256(src));return{timestamp:timestamp,data:data,sign:sign,_ver:'v0'};}
  function randomDeviceId(){var seed='';try{seed=String(java.util.UUID.randomUUID().toString()).replace(/-/g,'');}catch(e){seed=String(Math.random()).replace('.','')+String(Math.random()).replace('.','');}seed+=String(Date.now());return md5(seed).toLowerCase();}
  function deviceId(force){var v=force?'':String(getItem('ttt_device_id','')||'');if(!v){v=randomDeviceId();setItem('ttt_device_id',v);clearItem('ttt_token');}setItem('ttt_oauth_id',v);setItem('ttt_iid',v);return v;}
  function common(){var token=String(getItem('ttt_token','')||''),did=deviceId(false),brand='Android',model='HikerView';try{brand=String(android.os.Build.BRAND||brand);model=String(android.os.Build.MODEL||model);}catch(e){}return{system_oauth_id:did,system_oauth_type:'android',system_app_type:'local',system_token:token,system_version:'9.6.2',app_status:'',new_player:'fx',system_build_aff:'',system_build_id:'a1000',bundle_id:'com.tencent.mm',system_iid:did,device_brand:brand,device_model:model};}
  function plainBody(payload){var x={},c=common(),k;for(k in payload||{})if(payload.hasOwnProperty(k)&&payload[k]!=null)x[k]=String(payload[k]);for(k in c)if(c.hasOwnProperty(k)&&x[k]==null)x[k]=String(c[k]);return JSON.stringify(x);}
  function maybeJson(v,depth){depth=depth||0;if(depth>3||typeof v!=='string')return v;var s=v.trim();if(!s)return v;if((s.charAt(0)==='{'&&s.charAt(s.length-1)==='}')||(s.charAt(0)==='['&&s.charAt(s.length-1)===']')){try{return maybeJson(JSON.parse(s),depth+1);}catch(e){return v;}}return v;}
  function decodeResponse(raw){raw=String(raw==null?'':raw).trim();if(!raw)throw new Error('服务器返回空响应');var outer;try{outer=JSON.parse(raw);}catch(e){throw new Error('响应不是JSON：'+raw.substring(0,120));}if(outer&&typeof outer.data==='string'&&/^[0-9A-Fa-f]{34,}$/.test(outer.data)){var dec=decryptText(outer.data),parsed=maybeJson(dec);if(typeof parsed==='string')return{code:0,data:parsed,rawDecrypted:parsed};return parsed;}if(outer&&outer.data!=null)outer.data=maybeJson(outer.data);return outer;}
  function url(base,path){return String(base).replace(/\/$/,'')+'/'+String(path||'').replace(/^\//,'');}
  function typeName(v){if(v===null)return'null';if(Array.isArray(v))return'array['+v.length+']';return typeof v;}
  function schema(v,depth){depth=depth||0;if(depth>3)return typeName(v);v=maybeJson(v);if(Array.isArray(v)){var s='array['+v.length+']';if(v.length)s+='>'+schema(v[0],depth+1);return s;}if(v&&typeof v==='object'){var ks=Object.keys(v).filter(function(k){return k!=='__ttt';}).slice(0,16),parts=[];for(var i=0;i<ks.length;i++){var k=ks[i],x=v[k];if(Array.isArray(x))parts.push(k+'['+x.length+']');else if(x&&typeof x==='object')parts.push(k+'{'+Object.keys(x).slice(0,6).join(',')+'}');else parts.push(k+':'+typeof x);}return'{'+parts.join(',')+'}';}return typeName(v);}
  function codeOf(res){if(!res)return'';var c=res.code;if(c==null)c=res.status;return c==null?'':String(c);}
  function messageOf(res){return String((res&&(res.msg||res.message||res.info))||'');}
  function ok(res){var c=codeOf(res);if(c==='')return !!(res&&(res.data||res.result));return c==='0'||c==='1'||c==='200'||c==='1000';}
  function expired(res){var c=codeOf(res),m=messageOf(res);return c==='401'||/用户已过期|重新进入app|重新进入APP|重新进入 App/i.test(m);}
  function tokenOf(res){if(!res)return'';var d=res.data!==undefined?maybeJson(res.data):null;if(d&&typeof d==='object'&&!Array.isArray(d)&&typeof d.token==='string'&&d.token)return String(d.token);if(typeof res.token==='string'&&res.token)return String(res.token);function walk(v,depth){v=maybeJson(v);if(depth>4||v==null)return'';if(Array.isArray(v)){for(var i=0;i<v.length&&i<5;i++){var a=walk(v[i],depth+1);if(a)return a;}return'';}if(typeof v==='object'){if(typeof v.token==='string'&&v.token.length>=8)return String(v.token);var ks=Object.keys(v);for(var j=0;j<ks.length;j++){var k=ks[j];if(k==='__ttt')continue;var b=walk(v[k],depth+1);if(b)return b;}}return'';}return walk(d||res,0);}
  function meta(res,path){var d=res&&res.data!==undefined?res.data:res&&res.result!==undefined?res.result:res;return{path:path||'',code:codeOf(res),msg:messageOf(res).substring(0,160),schema:schema(d)};}
  function saveMeta(res,path){try{setItem('ttt_last_schema',JSON.stringify({time:Date.now(),meta:meta(res,path)}));}catch(e){}}
  function postOnce(base,path,payload){var u=url(base,path),plain=plainBody(payload),body=JSON.stringify(wrap(plain));var raw=fetch(u,{method:'POST',timeout:15000,body:body,headers:{'Content-Type':'application/json; charset=utf-8','User-Agent':UA,Accept:'application/json','Cache-Control':'no-cache'}});var res=decodeResponse(raw);if(res&&typeof res==='object')res.__ttt={url:u,domain:base,path:path,requestKeys:Object.keys(payload||{})};return res;}
  function rawCall(path,payload){var preferred=getItem('ttt_domain',''),ds=DOMAINS.slice();if(preferred){ds=ds.filter(function(x){return x!==preferred;});ds.unshift(preferred);}var errs=[];for(var i=0;i<ds.length;i++)try{var r=postOnce(ds[i],path,payload||{});setItem('ttt_domain',ds[i]);saveMeta(r,path);return r;}catch(e){errs.push(ds[i]+' → '+String(e.message||e));}throw new Error(errs.join('\n'));}
  function bootstrapSession(force){if(force)clearItem('ttt_token');var cached=String(getItem('ttt_token','')||'');if(cached&&!force)return{ok:true,cached:true,token:true};deviceId(false);var r=rawCall(START,{});if(expired(r)){deviceId(true);clearItem('ttt_token');r=rawCall(START,{});}var token=tokenOf(r);if(token)setItem('ttt_token',token);setItem('ttt_last_bootstrap',JSON.stringify({time:Date.now(),code:codeOf(r),msg:messageOf(r).substring(0,120),token:!!token,schema:schema(r&&r.data)}));if(!ok(r))throw new Error('启动握手失败：code '+codeOf(r)+' '+messageOf(r));if(!token)throw new Error('启动握手成功但未取得 token：'+schema(r&&r.data));return r;}
  function call(path,payload,opt){opt=opt||{};if(path===START){var sr=rawCall(path,payload||{}),st=tokenOf(sr);if(st)setItem('ttt_token',st);return sr;}if(!opt.skipBootstrap&&!String(getItem('ttt_token','')||''))bootstrapSession(false);var r=rawCall(path,payload||{});if(!opt.skipRefresh&&expired(r)){bootstrapSession(true);r=rawCall(path,payload||{});}if(opt.requireOk&&!ok(r))throw new Error(String(messageOf(r)||('业务状态 '+codeOf(r))));return r;}
  function resetSession(full){clearItem('ttt_token');clearItem('ttt_domain');clearItem('ttt_last_schema');clearItem('ttt_last_list_path');clearItem('ttt_last_bootstrap');if(full){clearItem('ttt_device_id');clearItem('ttt_oauth_id');clearItem('ttt_iid');deviceId(true);}return true;}
  function sessionInfo(){var d=String(getItem('ttt_device_id','')||''),t=String(getItem('ttt_token','')||'');return{deviceReady:!!d,deviceTail:d?d.slice(-6):'',tokenReady:!!t,domain:String(getItem('ttt_domain','')||'')};}
  function probe(){var out=[],t=Date.now();try{var s=bootstrapSession(false);out.push({name:'启动握手',ok:true,ms:Date.now()-t,code:codeOf(s),token:!!getItem('ttt_token',''),schema:schema(s&&s.data)});}catch(e){out.push({name:'启动握手',ok:false,ms:Date.now()-t,error:String(e.message||e)});}var checks=[['推荐视频','/api/MvList/featuredAv',{page:1,limit:12}],['短视频','/api/MvList/small',{page:1,limit:12}],['视频分类','/api/MvList/style',{}]];for(var i=0;i<checks.length;i++){var c=checks[i],x=Date.now();try{var r=call(c[1],c[2]),m=meta(r,c[1]);out.push({name:c[0],ok:ok(r),ms:Date.now()-x,path:c[1],code:m.code,msg:m.msg,schema:m.schema});}catch(e2){out.push({name:c[0],ok:false,ms:Date.now()-x,path:c[1],error:String(e2.message||e2)});}}setItem('ttt_last_probe',JSON.stringify({time:Date.now(),domain:getItem('ttt_domain',''),session:sessionInfo(),results:out}));return out;}
  return{version:VERSION,domains:DOMAINS,encryptText:encryptText,decryptText:decryptText,wrap:wrap,common:common,call:call,ok:ok,expired:expired,bootstrapSession:bootstrapSession,resetSession:resetSession,sessionInfo:sessionInfo,probe:probe,meta:meta,schema:schema};
})();
