/* 911爆料 Remote Core 0.1.0-test.1 */
var Bl911Core=(function(){
  var C={};
  C.version='0.1.0-test.1';
  C.build=10101;
  C.defaultBase='https://begin.mrbyudbq.com';
  C.bootstrap='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/911baoliao/bootstrap_test_v1_b10101.js?v=10101';
  C.ua='Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/139.0 Mobile Safari/537.36';
  C.baseKey='bl911_base_v1';
  C.favoriteKey='bl911_favorites_v1';
  C.historyKey='bl911_history_v1';
  C.diagKey='bl911_diag_v1';
  C.maxHistory=80;
  C.maxFavorites=120;
  C.schema='1';
  C.brand='#E53935';

  C.s=function(v){return v===undefined||v===null?'':String(v);};
  C.trim=function(v){return C.s(v).replace(/^\s+|\s+$/g,'');};
  C.clean=function(v){var s=C.trim(v);return s==='null'||s==='undefined'?'':s;};
  C.decode=function(v){return C.s(v).replace(/\\u0026/ig,'&').replace(/\\\//g,'/').replace(/&amp;/ig,'&').replace(/&#38;/ig,'&').replace(/&quot;/ig,'"').replace(/&#39;|&apos;|&#x27;/ig,"'").replace(/&nbsp;/ig,' ').replace(/&lt;/ig,'<').replace(/&gt;/ig,'>');};
  C.strip=function(v){return C.trim(C.decode(C.s(v).replace(/<br\s*\/?\s*>/ig,'\n').replace(/<script\b[\s\S]*?<\/script>/ig,' ').replace(/<style\b[\s\S]*?<\/style>/ig,' ').replace(/<[^>]+>/g,' ')).replace(/[\t\r ]+/g,' ').replace(/\n\s+/g,'\n'));};
  C.hash=function(s){s=C.s(s);var h=0,i;for(i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return Math.abs(h);};
  C.q=function(v){return encodeURIComponent(C.s(v));};
  C.origin=function(u){var m=C.s(u).match(/^(https?:\/\/[^\/]+)/i);return m?m[1]:'';};
  C.pathOf=function(u){var m=C.s(u).match(/^https?:\/\/[^\/]+(\/[^?#]*)?(\?[^#]*)?/i);return m?(m[1]||'/')+(m[2]||''):C.s(u);};
  C.abs=function(u,base){u=C.decode(C.trim(u));base=base||C.base();if(!u||/^data:|^javascript:|^#/.test(u))return'';if(/^https?:\/\//i.test(u))return u;if(/^\/\//.test(u))return'https:'+u;var o=C.origin(base)||C.base();if(u.charAt(0)==='/')return o+u;if(u.charAt(0)==='?')return C.s(base).replace(/[?#].*$/,'')+u;return C.s(base).replace(/[?#].*$/,'').replace(/[^\/]*$/,'')+u;};
  C.canonical=function(u,ref){return C.abs(u,ref||C.base());};
  C.ruleTitle=function(){try{return MY_RULE&&MY_RULE.title?MY_RULE.title:'911爆料';}catch(e){return'911爆料';}};
  C.param=function(name,def){var u='';try{u=C.s(MY_URL);}catch(e){}var re=new RegExp('[?&]'+name+'=([^&#]*)'),m=u.match(re);if(!m)return def===undefined?'':def;try{return decodeURIComponent(m[1]);}catch(e2){return m[1];}};
  C.pageNo=function(){var p=1;try{p=parseInt(MY_PAGE||1,10)||1;}catch(e){p=parseInt(C.param('page','1'),10)||1;}return p<1?1:p;};
  C.page=function(path,params){var a=['rule='+encodeURIComponent(C.ruleTitle()),'simple=true'],k;params=params||{};for(k in params)if(params.hasOwnProperty(k)&&params[k]!==undefined&&params[k]!==null&&C.s(params[k])!=='')a.push(encodeURIComponent(k)+'='+encodeURIComponent(C.s(params[k])));return'hiker://page/'+path+'?'+a.join('&');};
  C.headers=function(ref,accept){return{'User-Agent':C.ua,'Referer':ref||C.base()+'/','Accept':accept||'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Accept-Language':'zh-CN,zh;q=0.9,en;q=0.6'};};
  C.image=function(u,ref){u=C.abs(u,ref||C.base());if(!u)return'';return u+'@headers='+JSON.stringify({'User-Agent':C.ua,'Referer':ref||C.base()+'/'});};
  C.video=function(u,ref){u=C.clean(u);if(!u)return'';return u+';{Referer@'+(ref||C.base()+'/')+'&&User-Agent@'+C.ua+'}#isVideo=true#';};
  C.attr=function(tag,name){var m=C.s(tag).match(new RegExp('(?:^|\\s)'+name+'\\s*=\\s*["\\\']([^"\\\']*)["\\\']','i'));return m?C.decode(m[1]):'';};
  C.meta=function(html,key){var k=C.s(key).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),m=C.s(html).match(new RegExp('<meta[^>]+(?:property|name)=["\\\']'+k+'["\\\'][^>]+content=["\\\']([^"\\\']+)["\\\']','i'));if(!m)m=C.s(html).match(new RegExp('<meta[^>]+content=["\\\']([^"\\\']+)["\\\'][^>]+(?:property|name)=["\\\']'+k+'["\\\']','i'));return m?C.decode(m[1]):'';};
  C.context=function(html,index,before,after){html=C.s(html);return html.substring(Math.max(0,index-(before||900)),Math.min(html.length,index+(after||2100)));};
  C.unique=function(arr,keyFn){var out=[],seen={},i,k;for(i=0;i<(arr||[]).length;i++){k=keyFn?keyFn(arr[i]):C.s(arr[i]);if(!k||seen[k])continue;seen[k]=1;out.push(arr[i]);}return out;};
  C.readList=function(key){var raw=getItem(key,'[]'),a=[];try{a=JSON.parse(raw);}catch(e){a=[];}return Object.prototype.toString.call(a)==='[object Array]'?a:[];};
  C.writeList=function(key,a){try{setItem(key,JSON.stringify(a||[]));}catch(e){}return a||[];};
  C.diag=function(stage,route,url,error,extra){var x={time:new Date().getTime(),stage:C.clean(stage),route:C.clean(route),url:C.clean(url),error:C.clean(error),base:C.base(),version:C.version,build:C.build,extra:extra||{}};try{setItem(C.diagKey,JSON.stringify(x));}catch(e){}return x;};
  C.lastDiag=function(){try{return JSON.parse(getItem(C.diagKey,'{}'))||{};}catch(e){return{};}};

  C.restrictedText=function(v){var s=C.strip(v).toLowerCase();if(!s)return false;var patterns=[/未成年|未滿18|未满18|幼女|幼童|小学生|小學生|初中生|國中生|国中生|高中生|萝莉|蘿莉|兒童色情|儿童色情|童顏|童颜/,/偷拍|迷奸|迷姦|強姦|强奸|私密(?:照|视频|影片|影像).*?(?:泄露|外流|流出)|(?:泄露|外流|流出).*?私密|報復性色情|报复性色情|裸照(?:泄露|外流)|開盒|开盒/];for(var i=0;i<patterns.length;i++)if(patterns[i].test(s))return true;return false;};
  C.safeItem=function(x){return x&&!C.restrictedText([x.title||'',x.category||'',x.desc||''].join(' '));};
  C.safeList=function(a){var out=[],i;for(i=0;i<(a||[]).length;i++)if(C.safeItem(a[i]))out.push(a[i]);return out;};

  C.base=function(){var b=C.trim(getItem(C.baseKey,C.defaultBase));if(!/^https?:\/\//i.test(b))b=C.defaultBase;return b.replace(/\/+$/,'');};
  C.setBase=function(b){b=C.trim(b).replace(/\/+$/,'');if(/^https?:\/\//i.test(b)&&!/^https?:\/\/(?:127\.|10\.|192\.168\.|172\.(?:1[6-9]|2\d|3[01])\.)/i.test(b))setItem(C.baseKey,b);return b;};
  C.seedBases=function(){return C.unique([C.base(),C.defaultBase]);};
  C.isValidSiteHtml=function(body){var s=C.s(body),l=s.toLowerCase();if(s.length<500)return false;if(l.indexOf('just a moment')>=0||l.indexOf('cf-chl-')>=0||l.indexOf('captcha')>=0&&s.length<7000)return false;if(/911\s*(?:爆料|bl|曝光)/i.test(s))return true;if(/<article\b/i.test(s)&&/<(?:video|source|img)\b/i.test(s))return true;if(/(?:category|article|post|video)[\/-][a-z0-9_-]+/i.test(s)&&/<a\b/i.test(s))return true;return false;};
  C.rawFetch=function(url,opt){opt=opt||{};try{return C.s(fetch(url,{timeout:opt.timeout||9000,headers:C.headers(opt.ref||url,opt.accept),redirect:true}));}catch(e){C.diag('request','fetch',url,C.s(e));return'';}};
  C.probe=function(b){var h=C.rawFetch(b+'/',{timeout:5500,ref:b+'/'});if(C.isValidSiteHtml(h)){C.setBase(C.origin(b)||b);return{ok:true,base:C.origin(b)||b,html:h};}return{ok:false,base:b,html:h};};
  C.extractCandidateBases=function(html){var s=C.decode(html),re=/https?:\/\/[a-z0-9.-]+/ig,m,out=[];while((m=re.exec(s))&&out.length<20){var o=C.origin(m[0]);if(o&&!/google|facebook|twitter|telegram|t\.me|youtube|github|cloudflare|doubleclick|googlesyndication/i.test(o))out.push(o);}return C.unique(out);};
  C.discoverBase=function(force){var seeds=C.seedBases(),i,p,cands,j,q;if(!force){p=C.probe(C.base());if(p.ok)return p;}for(i=0;i<seeds.length;i++){p=C.probe(seeds[i]);if(!p.ok)continue;cands=C.extractCandidateBases(p.html);for(j=0;j<cands.length&&j<8;j++){if(cands[j]===p.base)continue;q=C.probe(cands[j]);if(q.ok)return q;}return p;}return{ok:false,base:C.base(),html:''};};
  C.request=function(pathOrUrl,opt){opt=opt||{};var b=C.base(),u=/^https?:\/\//i.test(pathOrUrl)?C.abs(pathOrUrl,b):b+(pathOrUrl.charAt(0)==='/'?pathOrUrl:'/'+pathOrUrl),h=C.rawFetch(u,{timeout:opt.timeout||10000,ref:opt.ref||u,accept:opt.accept});if(C.isValidSiteHtml(h)||opt.allowAny&&h.length>40){C.setBase(C.origin(u)||b);C.diag('ok',opt.route||'html',u,'',{len:h.length});return{ok:true,url:u,html:h,base:C.base()};}if(opt.noRetry){C.diag('request',opt.route||'html',u,'invalid html',{len:h.length});return{ok:false,url:u,html:h,base:b};}var d=C.discoverBase(true);if(d.ok){var u2=d.base+C.pathOf(u),h2=C.rawFetch(u2,{timeout:opt.timeout||10000,ref:opt.ref||u2,accept:opt.accept});if(C.isValidSiteHtml(h2)||opt.allowAny&&h2.length>40){C.diag('ok',(opt.route||'html')+'-failover',u2,'',{len:h2.length});return{ok:true,url:u2,html:h2,base:d.base};}}C.diag('request','domain-failover',u,'site html invalid',{len:h.length});return{ok:false,url:u,html:h,base:C.base()};};

  C.firstImage=function(raw,base){var re=/<img\b([^>]*)>/ig,m,u='';while((m=re.exec(C.s(raw)))){u=C.attr(m[1],'data-original')||C.attr(m[1],'data-src')||C.attr(m[1],'data-lazy-src')||C.attr(m[1],'data-echo')||C.attr(m[1],'src');u=C.abs(u,base);if(u&&!/logo|avatar|favicon|icon[-_.]|emoji|loading|placeholder/i.test(u))return u;}return'';};
  C.dateFrom=function(raw){var s=C.strip(raw),m=s.match(/20\d{2}[年\-\/.]\d{1,2}[月\-\/.]\d{1,2}(?:日)?(?:\s+\d{1,2}:\d{2})?/);if(!m)m=s.match(/\d{1,2}[月\-\/.]\d{1,2}(?:日)?\s+\d{1,2}:\d{2}/);return m?m[0]:'';};
  C.urlLooksContent=function(u){var p=C.pathOf(u).toLowerCase();if(!p||p==='/'||/[?&](?:s|q|keyword)=/.test(p))return false;if(/\/(?:category|categories|cate|tag|search|login|register|about|contact|submit|upload|download)(?:\/|\?|$)/i.test(p))return false;if(/\/(?:archives|archive|article|articles|post|posts|detail|video|videos|news|content)\//i.test(p))return true;if(/\/(?:p|v)\/\d+/i.test(p)||/\/\d{4,}(?:\/|\.html|$)/.test(p)||/\.html?(?:\?|$)/i.test(p))return true;return false;};
  C.categoryFrom=function(raw){var m=C.s(raw).match(/<a\b[^>]*href=["'][^"']*\/(?:category|categories|cate|class|type|channel)\/[^"']+["'][^>]*>([\s\S]*?)<\/a>/i);return m?C.strip(m[1]):'';};
  C.parsePosts=function(html,base){var s=C.s(html),re=/<a\b([^>]*)href\s*=\s*["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/ig,m,out=[],seen={},ctx,title,img,date,cat,u,inner,tm;while((m=re.exec(s))&&out.length<80){u=C.abs(m[2],base);if(!u||seen[u]||!C.urlLooksContent(u))continue;inner=m[4];ctx=C.context(s,m.index,1100,2300);title=C.clean(C.attr(m[1]+' '+m[3],'title')||C.attr(m[1]+' '+m[3],'aria-label')||C.strip(inner));if(!title||title.length<3||title.length>220){tm=ctx.match(/<(?:h1|h2|h3|h4)[^>]*>[\s\S]{0,420}?<a\b[^>]*href=["'][^"']+["'][^>]*>([\s\S]*?)<\/a>[\s\S]{0,160}?<\/(?:h1|h2|h3|h4)>/i);if(tm)title=C.strip(tm[1]);}if(!title||title.length<3){tm=ctx.match(/(?:title|alt)\s*=\s*["']([^"']{3,220})["']/i);if(tm)title=C.clean(tm[1]);}if(!title||/^(?:首页|返回|更多|阅读全文|详情|播放|上一页|下一页)$/i.test(title))continue;img=C.firstImage(inner,u)||C.firstImage(ctx,u);if(!img&&title.length<8)continue;date=C.dateFrom(ctx);cat=C.categoryFrom(ctx);var x={url:u,title:title,img:C.image(img,u),rawImg:img,date:date,category:cat,desc:[cat,date].filter(function(v){return!!v;}).join(' · ')};if(!C.safeItem(x))continue;seen[u]=1;out.push(x);}return C.unique(out,function(x){return C.pathOf(x.url).replace(/[?#].*$/,'');});};
  C.extractNavLinks=function(html,base){var s=C.s(html),blocks=[],bm,re,m,out=[],seen={},u,n,p;re=/<(?:nav|header)\b[\s\S]*?<\/(?:nav|header)>/ig;while((bm=re.exec(s))&&blocks.length<6)blocks.push(bm[0]);if(!blocks.length)blocks=[s.substring(0,Math.min(s.length,45000))];for(var b=0;b<blocks.length;b++){re=/<a\b([^>]*)href\s*=\s*["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/ig;while((m=re.exec(blocks[b]))&&out.length<60){u=C.abs(m[2],base);n=C.strip(m[4]);p=C.pathOf(u);if(!u||!n||n.length<2||n.length>24||seen[p])continue;if(!/\/(?:category|categories|cate|class|type|channel)\//i.test(p)&&!/cat(?:egory)?[_-]?id=/i.test(p))continue;var x={name:n,url:u};if(C.restrictedText(n))continue;seen[p]=1;out.push(x);}}return out;};
  C.categories=function(){var r=C.request('/',{route:'categories'}),a=r.ok?C.extractNavLinks(r.html,r.url):[];C.diag(r.ok?'ok':'parse','categories',r.url,r.ok?'':'home unavailable',{count:a.length});return a;};

  C.homePaths=function(page){page=parseInt(page,10)||1;return page<=1?['/']:['/page/'+page+'/','/?page='+page,'/?paged='+page];};
  C.categoryPaths=function(categoryUrl,page){var p=C.pathOf(categoryUrl),a=[],q=parseInt(page,10)||1;if(q<=1)return[p];if(p.indexOf('?')>=0){a.push(p+'&page='+q);a.push(p+'&paged='+q);}else{var clean=p.replace(/\/+$/,'');a.push(clean+'/page/'+q+'/');a.push(clean+'?page='+q);a.push(clean+'?paged='+q);}return a;};
  C.searchPaths=function(q,page){page=parseInt(page,10)||1;var e=C.q(q),a=[];if(page<=1){a.push('/?s='+e);a.push('/search/'+e+'/');a.push('/search?q='+e);a.push('/?q='+e);}else{a.push('/page/'+page+'/?s='+e);a.push('/?s='+e+'&paged='+page);a.push('/search/'+e+'/page/'+page+'/');a.push('/search?q='+e+'&page='+page);}return a;};
  C.tryList=function(paths,route){var last={ok:false,url:C.base(),html:'',posts:[]},i,r,p;for(i=0;i<paths.length;i++){r=C.request(paths[i],{route:route,noRetry:i<paths.length-1});p=r.ok?C.parsePosts(r.html,r.url):[];last={ok:r.ok,url:r.url,html:r.html,posts:p};if(p.length)return last;}return last;};
  C.home=function(page){return C.tryList(C.homePaths(page),'home');};
  C.category=function(categoryUrl,page){return C.tryList(C.categoryPaths(categoryUrl,page),'category');};
  C.search=function(q,page){return C.tryList(C.searchPaths(q,page),'search');};

  C.articleBlock=function(html){var s=C.s(html),m=s.match(/<article\b[\s\S]*?<\/article>/i);if(m)return m[0];m=s.match(/<div\b[^>]*class=["'][^"']*(?:entry-content|post-content|article-content|single-content|detail-content|content-main)[^"']*["'][^>]*>([\s\S]*?)(?:<div\b[^>]*class=["'][^"']*(?:post-navigation|comments|related|recommend)|<\/article>)/i);return m?m[1]:s;};
  C.extractImages=function(raw,base){var s=C.s(raw),re=/<img\b([^>]*)>/ig,m,out=[],seen={},u;while((m=re.exec(s))&&out.length<80){u=C.attr(m[1],'data-original')||C.attr(m[1],'data-src')||C.attr(m[1],'data-lazy-src')||C.attr(m[1],'data-echo')||C.attr(m[1],'src');u=C.abs(u,base);if(!u||seen[u]||/logo|avatar|favicon|icon[-_.]|emoji|loading|placeholder|qrcode|qr-code/i.test(u))continue;if(/^data:/i.test(u))continue;seen[u]=1;out.push(u);}return out;};
  C.extractParagraphs=function(raw){var s=C.s(raw),re=/<(?:p|h2|h3|h4|blockquote|figcaption)\b[^>]*>([\s\S]*?)<\/(?:p|h2|h3|h4|blockquote|figcaption)>/ig,m,out=[],seen={},t;while((m=re.exec(s))&&out.length<80){t=C.strip(m[1]);if(!t||t.length<2||t.length>1800||/^https?:\/\//i.test(t)||/下载APP|备用网址|广告合作|商务合作|官方.*群|投稿|上传/i.test(t))continue;if(C.restrictedText(t)||seen[t])continue;seen[t]=1;out.push(t);}return out;};
  C.extractMedia=function(html,base){var s=C.decode(html),out=[],seen={},i,re,m,u;var patterns=[/<(?:source|video)\b[^>]*\bsrc\s*=\s*["']([^"']+)["']/ig,/["'](?:file|src|url|video_url|videoUrl|play_url|playUrl|hls|m3u8)["']\s*[:=]\s*["']([^"']*(?:\.m3u8|\.mp4)(?:\?[^"']*)?)["']/ig,/data-(?:url|video|src|play)\s*=\s*["']([^"']*(?:\.m3u8|\.mp4)(?:\?[^"']*)?)["']/ig,/(https?:\\?\/\\?\/[^\s"'<>]+?(?:\.m3u8|\.mp4)(?:\?[^\s"'<>]*)?)/ig];for(i=0;i<patterns.length;i++){re=patterns[i];while((m=re.exec(s))&&out.length<12){u=C.decode(m[1]||m[0]).replace(/\\\//g,'/');u=C.abs(u,base);if(!u||seen[u]||/\.jpg|\.jpeg|\.png|\.gif|\.webp|logo|avatar/i.test(u))continue;seen[u]=1;out.push({url:u,ref:base,route:'direct'});}}var cfg=/data-config\s*=\s*["']([^"']+)["']/ig;while((m=cfg.exec(s))&&out.length<12){var decoded=C.decode(m[1]);try{decoded=decodeURIComponent(decoded);}catch(e){}var mm=decoded.match(/https?:\\?\/\\?\/[^\s"']+?(?:\.m3u8|\.mp4)(?:\?[^\s"']*)?/ig)||[];for(i=0;i<mm.length&&out.length<12;i++){u=C.decode(mm[i]).replace(/\\\//g,'/');if(!seen[u]){seen[u]=1;out.push({url:u,ref:base,route:'config'});}}}return out;};
  C.extractIframes=function(html,base){var re=/<iframe\b([^>]*)>/ig,m,out=[],seen={},u;while((m=re.exec(C.s(html)))&&out.length<5){u=C.attr(m[1],'src')||C.attr(m[1],'data-src');u=C.abs(u,base);if(!u||seen[u])continue;seen[u]=1;out.push(u);}return out;};
  C.extractCategories=function(h,base){var a=C.extractNavLinks(h,base),re=/<a\b[^>]*href\s*=\s*["']([^"']*\/(?:category|categories|cate|class|type|channel)\/[^"']+)["'][^>]*>([\s\S]*?)<\/a>/ig,m;while((m=re.exec(C.s(h)))&&a.length<30){var n=C.strip(m[2]);if(n&&!C.restrictedText(n))a.push({name:n,url:C.abs(m[1],base)});}return C.unique(a,function(x){return C.pathOf(x.url);});};
  C.detail=function(url){var r=C.request(url,{route:'detail',timeout:12000}),h=r.html||'',block=C.articleBlock(h),title=C.meta(h,'og:title'),m,x;if(!title){m=h.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i);title=m?C.strip(m[1]):'';}title=C.clean(title)||'911爆料';if(C.restrictedText(title))return{ok:false,blocked:true,url:r.url,title:title,cover:'',date:'',categories:[],images:[],paragraphs:[],media:[],iframes:[],related:[]};var cover=C.meta(h,'og:image')||C.firstImage(block,r.url),date=C.dateFrom(h),cats=C.extractCategories(h,r.url),imgs=C.extractImages(block,r.url),paras=C.extractParagraphs(block),media=C.extractMedia(h,r.url),ifr=C.extractIframes(h,r.url),related=C.parsePosts(h,r.url),i;related=related.filter(function(v){return C.pathOf(v.url)!==C.pathOf(r.url);});for(i=0;i<ifr.length&&media.length<10;i++){var ih=C.rawFetch(ifr[i],{timeout:7000,ref:r.url}),im=C.extractMedia(ih,ifr[i]),j;for(j=0;j<im.length;j++){im[j].route='iframe';media.push(im[j]);}}media=C.unique(media,function(v){return v.url;});x={ok:r.ok,url:r.url,title:title,cover:cover,date:date,categories:cats,images:imgs,paragraphs:paras,media:media,iframes:ifr,related:C.safeList(related).slice(0,16)};C.diag(r.ok?'ok':'parse','detail',r.url,r.ok?'':'detail invalid',{images:imgs.length,media:media.length,paragraphs:paras.length,categories:cats.length});return x;};
  C.resolvePlay=function(url){var x=C.detail(url),m=x.media||[],names=[],urls=[],headers=[],i;if(x.blocked){C.diag('blocked','content-filter',url,'restricted item');return'toast://该条目未在本程序中开放';}if(m.length===1){C.diag('play','direct-'+m[0].route,m[0].url,'');return C.video(m[0].url,m[0].ref||x.url);}if(m.length>1){for(i=0;i<m.length&&i<8;i++){urls.push(m[i].url);names.push((m[i].route==='iframe'?'内嵌':'线路')+' '+(i+1));headers.push({'Referer':m[i].ref||x.url,'User-Agent':C.ua});}C.diag('play','multi-direct',x.url,'',{count:urls.length});return JSON.stringify({urls:urls,names:names,headers:headers});}C.diag('play','video-sniff',x.url,'no structured media');return'video://'+x.url;};
  C.playMedia=function(media,ref){var m=media||[],names=[],urls=[],headers=[],i;if(m.length===1){C.diag('play','seed-'+(m[0].route||'direct'),m[0].url,'');return C.video(m[0].url,m[0].ref||ref);}if(m.length>1){for(i=0;i<m.length&&i<8;i++){urls.push(m[i].url);names.push((m[i].route==='iframe'?'内嵌':'线路')+' '+(i+1));headers.push({'Referer':m[i].ref||ref||C.base()+'/','User-Agent':C.ua});}C.diag('play','seed-multi',ref||C.base(),'',{count:urls.length});return JSON.stringify({urls:urls,names:names,headers:headers});}return'';};

  C.addHistory=function(p){if(!C.safeItem(p))return;var a=C.readList(C.historyKey),out=[p],i;for(i=0;i<a.length&&out.length<C.maxHistory;i++)if(C.pathOf(a[i].url)!==C.pathOf(p.url))out.push(a[i]);C.writeList(C.historyKey,out);};
  C.isFavorite=function(url){var a=C.readList(C.favoriteKey),i;for(i=0;i<a.length;i++)if(C.pathOf(a[i].url)===C.pathOf(url))return true;return false;};
  C.toggleFavorite=function(p){if(!C.safeItem(p))return false;var a=C.readList(C.favoriteKey),out=[],found=false,i;for(i=0;i<a.length;i++){if(C.pathOf(a[i].url)===C.pathOf(p.url)){found=true;continue;}out.push(a[i]);}if(!found)out.unshift(p);if(out.length>C.maxFavorites)out=out.slice(0,C.maxFavorites);C.writeList(C.favoriteKey,out);return!found;};
  C.clearHistory=function(){C.writeList(C.historyKey,[]);};
  C.clearFavorites=function(){C.writeList(C.favoriteKey,[]);};
  return C;
})();
