/* 911爆料 Remote Runtime 0.1.0-test.1 */
var Bl911RemoteRuntime=(function(){
  var R={version:'0.1.0-test.1',build:10101};
  var AS='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/911baoliao/assets/';
  function add(d,x){d.push(x);}
  function title(t){try{setPageTitle(t);}catch(e){}}
  function line(d){add(d,{col_type:'line'});}
  function heading(d,t,desc){add(d,{title:'‘‘’’<b>'+t+'</b>',desc:desc||'',col_type:'rich_text',url:'hiker://empty',extra:{lineVisible:false}});}
  function postCard(p){return{title:p.title||'911爆料',desc:p.desc||'热点事件',pic_url:p.img||AS+'icon.svg',url:Bl911Core.page('bl911Detail',{post_url:p.url}),col_type:'movie_2',extra:{id:'bl911_post_'+Bl911Core.hash(p.url),lineVisible:false}};}
  function renderPosts(d,a,limit){var i,n=limit||a.length;for(i=0;i<a.length&&i<n;i++)add(d,postCard(a[i]));}
  function empty(d,t,desc){add(d,{title:t,desc:desc||'',pic_url:AS+'icon.svg',col_type:'movie_1_left_pic',url:'hiker://empty',extra:{lineVisible:false}});}
  function searchInputUrl(q){return"(function(){var q=String(input||'').trim();return 'hiker://page/bl911Search?rule='+encodeURIComponent('"+Bl911Core.ruleTitle()+"')+'&simple=true&q='+encodeURIComponent(q);})()";}
  function safeSearch(q){return q&&!Bl911Core.restrictedText(q);}

  R.home=function(){var p=Bl911Core.pageNo(),d=[],r,cats=[],i;if(p===1){title('911爆料');add(d,{title:'911爆料',desc:'热点爆料 · 图文视频 · 本地收藏',pic_url:AS+'icon.svg',url:Bl911Core.page('bl911Settings'),col_type:'movie_1_left_pic',extra:{lineVisible:false}});add(d,{title:'🔎\n搜索',col_type:'text_4',url:Bl911Core.page('bl911Search')});add(d,{title:'🧭\n分类',col_type:'text_4',url:Bl911Core.page('bl911Hub')});add(d,{title:'⭐\n收藏',col_type:'text_4',url:Bl911Core.page('bl911Favorites')});add(d,{title:'🕘\n历史',col_type:'text_4',url:Bl911Core.page('bl911History')});}
    r=Bl911Core.home(p);if(p===1){cats=r.ok?Bl911Core.extractNavLinks(r.html,r.url):[];if(cats.length){heading(d,'快速分类','来自当前官网导航');for(i=0;i<cats.length&&i<8;i++)add(d,{title:cats[i].name,col_type:'scroll_button',url:Bl911Core.page('bl911Feed',{cat_url:cats[i].url,cat_name:cats[i].name})});}heading(d,'最新爆料',r.posts.length?'已识别 '+r.posts.length+' 条':'正在等待可识别内容');}
    renderPosts(d,r.posts);if(!r.posts.length&&p===1)empty(d,'暂未识别到内容','请进入“设置与诊断”查看当前域名、HTML 与 Parser 状态。');setResult(d);};

  R.categoryHub=function(){title('分类中心');var d=[],r=Bl911Core.request('/',{route:'hub'}),a=r.ok?Bl911Core.extractNavLinks(r.html,r.url):[],i;if(a.length){add(d,{title:'分类中心',desc:'从当前官网导航动态生成 · 不写死栏目',pic_url:AS+'icon.svg',col_type:'movie_1_left_pic',url:'hiker://empty',extra:{lineVisible:false}});for(i=0;i<a.length;i++)add(d,{title:a[i].name,desc:'进入 '+a[i].name,col_type:'text_2',url:Bl911Core.page('bl911Feed',{cat_url:a[i].url,cat_name:a[i].name}),extra:{lineVisible:false}});}else empty(d,'暂未解析到分类','首版不猜测站点栏目路径；实机确认 DOM 后再锁定专用分类 Adapter。');setResult(d);};
  R.categoryFeed=function(){var u=Bl911Core.param('cat_url',Bl911Core.base()+'/'),n=Bl911Core.param('cat_name','分类'),p=Bl911Core.pageNo(),d=[],r;if(Bl911Core.restrictedText(n)){title('内容不可用');empty(d,'该分类未在本程序开放','返回分类中心选择其它栏目。');setResult(d);return;}title(n);if(p===1){add(d,{title:'‹ 分类中心',col_type:'scroll_button',url:Bl911Core.page('bl911Hub')});heading(d,n,'按官网分页加载');}r=Bl911Core.category(u,p);renderPosts(d,r.posts);if(!r.posts.length&&p===1)empty(d,'该分类暂无可识别内容','可能是页面路径或卡片结构与通用 Parser 不同。');setResult(d);};

  R.searchPage=function(){var q=Bl911Core.param('q',''),p=Bl911Core.pageNo(),d=[],r;title(q?'搜索 · '+q:'搜索');if(p===1){add(d,{title:'搜索爆料',desc:q||'输入标题、人物或事件关键词',col_type:'input',url:searchInputUrl(q),extra:{defaultValue:q}});if(!q){heading(d,'站内搜索','搜索结果仍经过本程序内容过滤；不提供评论、投稿或下载入口。');setResult(d);return;}}if(!safeSearch(q)){empty(d,'该关键词未开放搜索','请换一个普通事件或人物关键词。');setResult(d);return;}r=Bl911Core.search(q,p);renderPosts(d,r.posts);if(!r.posts.length&&p===1)empty(d,'没有匹配结果','当前站点搜索路径可能需要针对性适配，可从诊断页确认。');setResult(d);};
  R.search=function(){var q='';try{q=String(MY_KEYWORD||'');}catch(e){q=Bl911Core.param('q','');}var d=[];if(!safeSearch(q)){empty(d,'该关键词未开放搜索','');setResult(d);return;}var r=Bl911Core.search(q,Bl911Core.pageNo());renderPosts(d,r.posts);if(!r.posts.length&&Bl911Core.pageNo()===1)empty(d,'没有匹配结果','');setResult(d);};

  R.detail=function(){var u=Bl911Core.param('post_url',''),d=[],x,i,ds,media;if(!u){empty(d,'缺少文章地址','请从列表重新进入。');setResult(d);return;}x=Bl911Core.detail(u);title(x.title||'911爆料');if(x.blocked){empty(d,'该条目未在本程序开放','返回列表继续浏览其它内容。');setResult(d);return;}if(!x.ok){empty(d,'详情读取失败','当前域名、页面验证或详情 Parser 暂未通过。');setResult(d);return;}ds=[x.categories.length?x.categories[0].name:'',x.date].filter(function(v){return!!v;}).join(' · ');Bl911Core.addHistory({url:x.url,title:x.title,img:Bl911Core.image(x.cover,x.url),rawImg:x.cover,desc:ds,category:x.categories.length?x.categories[0].name:''});add(d,{title:x.title,desc:ds||'911爆料',pic_url:Bl911Core.image(x.cover,x.url)||AS+'icon.svg',url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});
    if(x.media.length){media=JSON.stringify(x.media);add(d,{title:'▶ 立即播放',desc:x.media.length===1?'已提取结构化媒体':'已提取 '+x.media.length+' 条媒体线路',col_type:'text_center_1',url:$(media,x.url).lazyRule(function(boot,m,ref){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);Bl911Boot.loadOnly();var a=[];try{a=JSON.parse(m)||[];}catch(e){}var r=Bl911Core.playMedia(a,ref);return r||Bl911Core.resolvePlay(ref);},Bl911Core.bootstrap,media,x.url),extra:{id:'bl911_play_'+Bl911Core.hash(x.url),lineVisible:false}});}else if(x.iframes.length){add(d,{title:'▶ 尝试播放',desc:'检测到网页播放器，点击后使用结构化解析 → 嗅探兜底',col_type:'text_center_1',url:$(x.url).lazyRule(function(boot,target){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);Bl911Boot.loadOnly();return Bl911Core.resolvePlay(target);},Bl911Core.bootstrap,x.url),extra:{lineVisible:false}});}line(d);
    add(d,{title:Bl911Core.isFavorite(x.url)?'★ 已收藏':'☆ 收藏',col_type:'text_3',url:$(x.url,x.title,x.cover,ds,x.categories.length?x.categories[0].name:'').lazyRule(function(boot,target,tt,cv,desc,cat){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);Bl911Boot.loadOnly();var on=Bl911Core.toggleFavorite({url:target,title:tt,rawImg:cv,img:Bl911Core.image(cv,target),desc:desc,category:cat});refreshPage(false);return'toast://'+(on?'已加入收藏':'已取消收藏');},Bl911Core.bootstrap,x.url,x.title,x.cover,ds,x.categories.length?x.categories[0].name:''),extra:{lineVisible:false}});add(d,{title:'🌐 原文',col_type:'text_3',url:x.url,extra:{lineVisible:false}});add(d,{title:'⚙ 设置',col_type:'text_3',url:Bl911Core.page('bl911Settings'),extra:{lineVisible:false}});
    if(x.paragraphs.length){heading(d,'事件正文','');for(i=0;i<x.paragraphs.length&&i<50;i++)add(d,{title:x.paragraphs[i],col_type:'rich_text',url:'hiker://empty',extra:{lineVisible:false}});}
    if(x.images.length){heading(d,'现场图片','共 '+x.images.length+' 张');for(i=0;i<x.images.length&&i<60;i++)add(d,{title:'',pic_url:Bl911Core.image(x.images[i],x.url),col_type:'pic_1_full',url:x.images[i],extra:{lineVisible:false}});}
    if(x.categories.length){heading(d,'相关分类','');for(i=0;i<x.categories.length&&i<12;i++)if(!Bl911Core.restrictedText(x.categories[i].name))add(d,{title:x.categories[i].name,col_type:'scroll_button',url:Bl911Core.page('bl911Feed',{cat_url:x.categories[i].url,cat_name:x.categories[i].name})});}
    if(x.related.length){heading(d,'继续浏览','');renderPosts(d,x.related,12);}setResult(d);};

  R.favorites=function(){title('本地收藏');var d=[],a=Bl911Core.safeList(Bl911Core.readList(Bl911Core.favoriteKey));add(d,{title:'我的收藏',desc:a.length+' 项 · 仅保存在本机',pic_url:AS+'icon.svg',col_type:'movie_1_left_pic',url:'hiker://empty',extra:{lineVisible:false}});renderPosts(d,a);if(!a.length)empty(d,'还没有收藏','从详情页点击“收藏”。');setResult(d);};
  R.history=function(){title('浏览历史');var d=[],a=Bl911Core.safeList(Bl911Core.readList(Bl911Core.historyKey));add(d,{title:'最近浏览',desc:a.length+' 项 · 自动记录详情页',pic_url:AS+'icon.svg',col_type:'movie_1_left_pic',url:'hiker://empty',extra:{lineVisible:false}});renderPosts(d,a);if(!a.length)empty(d,'暂无历史','进入详情页后会自动记录。');setResult(d);};

  R.settings=function(){title('设置与诊断');var d=[],b=Bl911Core.base(),probe=Bl911Core.request('/',{route:'settings-probe',noRetry:true}),posts=probe.ok?Bl911Core.parsePosts(probe.html,probe.url):[],cats=probe.ok?Bl911Core.extractNavLinks(probe.html,probe.url):[],diag=Bl911Core.lastDiag();add(d,{title:'911爆料 · Test',desc:R.version+' · Build '+R.build,pic_url:AS+'icon.svg',col_type:'movie_1_left_pic',url:'hiker://empty',extra:{lineVisible:false}});heading(d,'站点状态','');add(d,{title:'当前域名',desc:b,col_type:'text_1',url:'hiker://empty'});add(d,{title:'首页探测',desc:(probe.ok?'可访问':'不可访问')+' · HTML '+(probe.html?probe.html.length:0)+' · 内容卡 '+posts.length+' · 分类 '+cats.length,col_type:'text_1',url:'hiker://empty'});add(d,{title:'重新探测站点',desc:'检查当前域名并验证可识别页面',col_type:'text_1',url:$(b).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);Bl911Boot.loadOnly();var x=Bl911Core.discoverBase(true);refreshPage(false);return'toast://'+(x.ok?'当前可用：'+x.base:'暂未找到可用域名');},Bl911Core.bootstrap)});heading(d,'功能边界','');add(d,{title:'评论 / 匿名投稿 / 下载',desc:'本程序不提供这些入口',col_type:'text_1',url:'hiker://empty'});add(d,{title:'内容过滤',desc:'已启用 · 首页、分类、搜索、详情统一执行',col_type:'text_1',url:'hiker://empty'});heading(d,'本地数据','');add(d,{title:'清空浏览历史',desc:Bl911Core.readList(Bl911Core.historyKey).length+' 项',col_type:'text_1',url:$(b).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);Bl911Boot.loadOnly();Bl911Core.clearHistory();refreshPage(false);return'toast://历史已清空';},Bl911Core.bootstrap)});add(d,{title:'清空本地收藏',desc:Bl911Core.readList(Bl911Core.favoriteKey).length+' 项',col_type:'text_1',url:$(b).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);Bl911Boot.loadOnly();Bl911Core.clearFavorites();refreshPage(false);return'toast://收藏已清空';},Bl911Core.bootstrap)});heading(d,'最近诊断','');add(d,{title:diag.stage||'暂无诊断',desc:[diag.route||'',diag.error||'',diag.extra?JSON.stringify(diag.extra):''].filter(function(v){return!!v;}).join(' · '),col_type:'long_text',url:'hiker://empty'});heading(d,'远程版本','');add(d,{title:'检查 Test 更新',desc:'只检查版本，不自动切换',col_type:'text_1',url:$(Bl911Core.bootstrap).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);var r=Bl911Boot.check();return'toast://'+(r&&r.message?r.message:'检查完成');},Bl911Core.bootstrap)});setResult(d);};

  R.module=function(){return R;};
  return R;
})();
