/* JavDB v3 3.9.51-test.1 · raw VIP HLS verification overlay */
var JavDBRaw3951=(function(){
var VERSION='3.9.51-test.1',BUILD=2026092205;
var ROOT='hiker://files/rules/asset-core-local/javdb-v3-test/b2026092205/';
var ENTRY=ROOT+'local_entry.js',BASE_ENTRY=ROOT+'base_3950_entry.js';
var BASE_REF='8474f9b758cff4141a4ab101c34e5eef42190a52';
var BASE_PATH='apps/video/javdb/releases/3.9.50-test.1/local_entry.js';
var BASE_CACHE=null;
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function urls(ref,path){return['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/'+ref+'/'+path,'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@'+ref+'/'+path,'https://github.com/huoguotiankong/asset-core-7f3/raw/'+ref+'/'+path];}
function ensureFile(local,ref,path,marker){if(fileExist(local)){try{var old=String(readFile(local)||'');if(!bad(old)&&old.indexOf(marker)>=0)return local;}catch(_e){}try{deleteFile(local);}catch(_e2){}}var us=urls(ref,path),es=[],i,s='';for(i=0;i<us.length;i++){try{s=String(fetch(us[i],{timeout:6500,headers:{'Cache-Control':'public, max-age=31536000, immutable'}})||'');if(bad(s)||s.indexOf(marker)<0)throw new Error('无效响应');writeFile(local,s);if(!fileExist(local))throw new Error('写入失败');return local;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(path+' 下载失败：'+es.join(' | '));}
function base(){if(BASE_CACHE&&typeof BASE_CACHE.module==='function')return BASE_CACHE;ensureFile(BASE_ENTRY,BASE_REF,BASE_PATH,'3.9.50-test.1');var src=String(readFile(BASE_ENTRY)||''),JavDBLocal=null;if(bad(src)||src.indexOf('3.9.50-test.1')<0)throw new Error('JavDB 3.9.50 Base Entry 内容无效');eval(src);if(!JavDBLocal||typeof JavDBLocal.module!=='function')throw new Error('JavDB 3.9.50 Base Entry 未导出');BASE_CACHE=JavDBLocal;return BASE_CACHE;}
function stripNoPreUrl(u){return String(u==null?'':u).replace(/#noPre#/gi,'');}
function restoreRaw(items){if(!(items instanceof Array))return items;for(var i=0;i<items.length;i++){var x=items[i];if(!x||typeof x!=='object'||typeof x.url!=='string')continue;var u=String(x.url||'');if(u.charAt(0)==='{'){try{var o=JSON.parse(u),changed=false;if(o&&o.urls instanceof Array){for(var j=0;j<o.urls.length;j++){var v=String(o.urls[j]||''),n=stripNoPreUrl(v);if(n!==v){o.urls[j]=n;changed=true;}}if(changed)x.url=JSON.stringify(o);}}catch(_e){}}else if(u.indexOf('#noPre#')>=0){x.url=stripNoPreUrl(u);}}
return items;}
function capture(run,patch){var oldSet=null,got=null,hooked=false,err=null,ret=null;try{oldSet=setResult;var cap=function(v){got=v;};setResult=cap;hooked=(setResult===cap);}catch(e){hooked=false;}if(!hooked)return run();try{ret=run();}catch(e2){err=e2;}finally{try{setResult=oldSet;}catch(_e){}}if(err)throw err;if(got instanceof Array){got=patch(got);return oldSet(got);}if(got!=null)return oldSet(got);return ret;}
function module(){var b=base(),m=b.module();if(!m||typeof m.core!=='function')throw new Error('JavDB 3.9.50 Base Module 未就绪');var oldCore=m.core;m.core=function(call){var s=String(call||'').replace(/\s+/g,'');if(s==='JDB.playPage();'||s==='JDB.playPage()')return capture(function(){return oldCore.call(m,call);},restoreRaw);return oldCore.call(m,call);};m.version=VERSION;m.build=BUILD;m.rawVipHls=true;m.vipNoPre=false;m.vipAutoCache=false;return m;}
function info(){var b=base(),x={};try{x=b.info?b.info():{};}catch(e){x={ready:false,error:String(e.message||e)};}x.version=VERSION;x.build=BUILD;x.baseVersion='3.9.50-test.1';x.rawVipHls=true;x.vipNoPre=false;x.vipAutoCache=false;return x;}
function statusPage(){setPageTitle('JavDB · VIP播放诊断');var d=[],x=info();d.push({title:'JavDB v3 '+VERSION,desc:'Build '+BUILD+' · 原始实时 HLS 验证',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'默认 VIP 播放',desc:'完全保留站点原始播放 URL / headers；取消 #noPre#；不自动 cacheM3u8；不自动换本地索引。',url:'hiker://empty',col_type:'text_2',extra:{lineVisible:false}});d.push({title:'目的',desc:'把“首次起播”和“拖动后恢复”从海阔预处理/本地索引变量中隔离出来，确认真实瓶颈是否在原始 HLS/CDN/播放器 Seek。',url:'hiker://empty',col_type:'text_2',extra:{lineVisible:false}});setResult(d);}
return{version:VERSION,build:BUILD,module:module,info:info,statusPage:statusPage,entry:ENTRY,builder:function(){var b=base();return b.builder?b.builder():null;},patch:function(force){var b=base();return b.patch?b.patch(force):null;},upgrade:function(force){var b=base();return b.upgrade?b.upgrade(force):null;}};
})();
var JavDBLocal=JavDBRaw3951;
