/* 色花堂 0.1.0-test.9 / Build 10109 - validated forum/thread fetch + group reconstruction + real action icons */
var SeHuaTangPatchTest9=(function(){
  var BASE=SeHuaTangRemoteRuntime;
  var VERSION='0.1.0-test.9',BUILD=10109,RULE_NAME='色花堂';
  var DEFAULT_ORIGIN='https://sehuatang.org';
  var KEY_ORIGIN='sht_origin_v1',KEY_COOKIE='sht_web_cookie_v5',KEY_CAT='sht_cat_group_v6',KEY_ACCESS='sht_access_ok_v7';
  var KEY_GROUP_CACHE='sht_forum_groups_v9',KEY_FLAT_CACHE='sht_forum_flat_v9',KEY_DIAG='sht_diag_v1';
  var UA_M='Mozilla/5.0 (Linux; Android 13; zh-CN) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Mobile Safari/537.36';
  var UA_PC='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36';
  var RAW='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/aggregate/sehuatang/assets/icons/v1/';
  var ROOTS=[
    {name:'原创BT电影',fid:'2',seed:'forum-2-1.html',icon:'🎬'},
    {name:'在线视频区',fid:'41',seed:'forum-41-1.html',icon:'▶️'},
    {name:'原档收藏',fid:'145',seed:'forum-145-1.html',icon:'💿'},
    {name:'色花图片',fid:'155',seed:'forum-155-1.html',icon:'🖼️'},
    {name:'色花文学',fid:'154',seed:'forum-154-1.html',icon:'✍️'},
    {name:'综合讨论区',fid:'95',seed:'forum-95-1.html',icon:'💬'}
  ];
  var ROOT_IDS={2:1,41:1,145:1,155:1,154:1,95:1};
  var ICONS={account:'account.svg',signin:'signin.svg',search:'search.svg',settings:'settings.svg',web:'web.svg',original:'original.svg',reply:'reply.svg',copy:'copy.svg',board:'board.svg'};

  function s(v){return v==null?'':String(v)}
  function trim(v){return s(v).replace(/^\s+|\s+$/g,'')}
  function dec(v){v=s(v);try{return decodeURIComponent(v)}catch(e){return v}}
  function hdec(v){var x=s(v),i;for(i=0;i<2;i++)x=x.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;/gi,' ');return x}
  function strip(v){return trim(hdec(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/[\t\r]+/g,' ').replace(/\s+/g,' '))}
  function origin(){var o=trim(getItem(KEY_ORIGIN,DEFAULT_ORIGIN));return /^https?:\/\//i.test(o)?o.replace(/\/+$/,''):DEFAULT_ORIGIN}
  function abs(h,b){h=hdec(trim(h));if(!h)return'';if(/^https?:\/\//i.test(h))return h;if(/^\/\//.test(h))return'https:'+h;if(/^(javascript:|mailto:|tel:|#)/i.test(h))return'';var m=s(b).match(/^(https?:\/\/[^\/]+)/i),o=m?m[1]:origin();if(h.charAt(0)==='/')return o+h;var c=s(b).split('#')[0].split('?')[0];if(c.charAt(c.length-1)!=='/')c=c.replace(/\/[^\/]*$/,'/');return c+h.replace(/^\.\//,'')}
  function pageParam(n,d){var u=s(typeof MY_URL==='undefined'?'':MY_URL),m=u.match(new RegExp('[?&]'+n+'=([^&#]*)'));return m?dec(m[1]):(d==null?'':d)}
  function route(path,p){var u='hiker://page/'+path+'?rule='+RULE_NAME+'&simple=true',k;for(k in(p||{}))if(p.hasOwnProperty(k)&&p[k]!=null)u+='&'+k+'='+encodeURIComponent(s(p[k]));return u}
  function line(cls){return{col_type:'line',extra:{cls:cls||''}}}
  function section(t,d,cls){return{title:t,desc:d||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false,cls:cls||''}}}
  function empty(t,d){return{title:t,desc:d||'',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}}}
  function icon(n){return RAW+(ICONS[n]||ICONS.board)}
  function quick(t,u,ico,cls){var p=icon(ico);return{title:t,img:p,pic_url:p,url:u,col_type:'icon_small_4',extra:{lineVisible:false,cls:cls||''}}}
  function saveDiag(stage,msg){try{setItem(KEY_DIAG,JSON.stringify({stage:stage,origin:origin(),error:s(msg||'').slice(0,1800),time:new Date().getTime()}))}catch(e){}}
  function cookie(){var c='';try{c=getVar(KEY_COOKIE,'')||''}catch(e){}if(c)return c;try{c=getCookie(origin())||''}catch(e2){}return c}
  function headers(pc,ref){var c=cookie(),h={'User-Agent':pc?UA_PC:UA_M,'Referer':ref||origin()+'/'};if(c){h.Cookie=c;h.cookie=c}return h}
  function imageUrl(u,ref){u=abs(u,ref);if(!u)return'';return u+'@headers='+JSON.stringify(headers(false,ref||origin()+'/'))+'#originalSize#'}
  function forumId(u){var m=s(u).match(/forum-(\d+)-\d+/i)||s(u).match(/[?&]fid=(\d+)/i);return m?m[1]:''}
  function threadId(u){var x=hdec(s(u)),m=x.match(/[?&]tid=(\d+)/i)||x.match(/[?&]ptid=(\d+)/i)||x.match(/\/thread-(\d+)-\d+-\d+\.html/i);return m?m[1]:''}
  function normalizeThread(u){var id=threadId(u);if(!id)return u;if(/[?&]ptid=\d+/i.test(u)&&!/[?&]tid=\d+/i.test(u))return origin()+'/forum.php?mod=viewthread&tid='+id+'&mobile=2';if(!/[?&]mobile=/.test(u))u+=(u.indexOf('?')>=0?'&':'?')+'mobile=2';return u}
  function anchors(html,base){var out=[],re=/<a\b([^>]*?)href\s*=\s*(?:["']([^"']+)["']|([^\s>]+))([^>]*)>([\s\S]*?)<\/a>/gi,m,a,t,tm;while((m=re.exec(s(html)))!==null){a=(m[1]||'')+' '+(m[4]||'');t=strip(m[5]||'');if(!t){tm=a.match(/\b(?:title|aria-label)\s*=\s*["']([^"']+)["']/i);if(tm)t=strip(tm[1])}out.push({href:abs(m[2]||m[3]||'',base),text:t,inner:m[5]||'',attrs:a,index:m.index});if(out.length>16000)break}return out}
  function fetchPc(u){try{return s(fetchPC(u,{headers:headers(true,u),timeout:14000}))}catch(e){return''}}
  function render(u,kind){try{return s(fetchCodeByWebView(u,{headers:headers(false,u),timeout:19000,blockRules:['.woff','.woff2','.ttf'],checkJs:$.toString(function(kind){var t=String((document.body&&document.body.innerText)||'');if(kind==='thread')return document.querySelector('#postlist .t_fsz,#postlist .t_f,[id^="postmessage_"],.message')?'ready':null;if(kind==='list')return document.querySelector('a[href*="tid="],a[href*="thread-"]')?'ready':null;if(kind==='forum')return document.querySelector('a[href*="forum-"],a[href*="fid="]')?'ready':null;return t.length>900?'ready':null;},kind)}))}catch(e){return''}}
  function cleanForumTitle(t){return trim(t).replace(/^[-–—·•\s]+|[-–—·•\s]+$/g,'')}
  function parseForums(html,base){var a=anchors(html,base),out=[],seen={},i,id,t;for(i=0;i<a.length;i++){id=forumId(a[i].href);t=cleanForumTitle(a[i].text);if(!id||seen[id]||!t)continue;if(/^(首页|论坛|返回|话题|板块|发帖|搜索|更多|社区版块|查看帖子)$/i.test(t))continue;seen[id]=1;out.push({id:id,title:t,url:a[i].href,index:a[i].index})}return out}
  function forumCacheV4(){try{var x=JSON.parse(getItem('sht_forum_cache_v4','{}')||'{}');if(x.items&&x.items.length>=8)return x.items}catch(e){}return[]}
  function readFlatCache(){try{var x=JSON.parse(getItem(KEY_FLAT_CACHE,'{}')||'{}');if(x.items&&x.items.length>=8&&new Date().getTime()-Number(x.time||0)<21600000)return x.items}catch(e){}return[]}
  function writeFlatCache(a){try{if(a&&a.length>=8)setItem(KEY_FLAT_CACHE,JSON.stringify({time:new Date().getTime(),items:a.slice(0,100)}))}catch(e){}}
  function resolveAllForums(){var c=readFlatCache(),old=forumCacheV4(),urls=[],best=[],bestSrc='',i,u,h,p;if(c.length)return{items:c,source:'v9-cache'};if(old.length>=8){writeFlatCache(old);return{items:old,source:'v4-device-cache'}}urls=[origin()+'/forum.php?mobile=2',origin()+'/forum.php?mobile=no',origin()+'/forum.php'];for(i=0;i<urls.length;i++){u=urls[i];h=fetchPc(u);p=parseForums(h,u);if(p.length>best.length){best=p;bestSrc='fetch:'+u}h=render(u,'forum');p=parseForums(h,u);if(p.length>best.length){best=p;bestSrc='webview:'+u}}if(best.length)writeFlatCache(best);return{items:best,source:bestSrc||'none'}}
  function uniqForums(a){var out=[],seen={},i,x;for(i=0;i<(a||[]).length;i++){x=a[i];if(!x||!x.id||ROOT_IDS[x.id]||seen[x.id])continue;seen[x.id]=1;out.push(x)}return out}
  function groupsFromFlat(flat){var groups=[[],[],[],[],[],[]],pos=[],i,j,start,end,x;for(i=0;i<ROOTS.length;i++){pos[i]=-1;for(j=0;j<flat.length;j++)if(flat[j].id===ROOTS[i].fid||trim(flat[j].title)===ROOTS[i].name){pos[i]=j;break}}for(i=0;i<ROOTS.length;i++){if(pos[i]<0)continue;start=pos[i]+1;end=flat.length;for(j=i+1;j<ROOTS.length;j++)if(pos[j]>=0){end=pos[j];break}for(j=start;j<end;j++){x=flat[j];if(x&&!ROOT_IDS[x.id])groups[i].push(x)}groups[i]=uniqForums(groups[i])}return groups}
  function blockCandidates(html,base,root){var sels=['body&&div.bmw','body&&div.bm','body&&div.bm_c','body&&table.fl_tb'],best=[],si,bs=[],i,b,txt,as;for(si=0;si<sels.length;si++){try{bs=pdfa(html,sels[si])||[]}catch(e){bs=[]}for(i=0;i<bs.length;i++){b=s(bs[i]);txt=strip(b);if(txt.indexOf(root.name)<0&&b.indexOf('forum-'+root.fid+'-')<0&&b.indexOf('fid='+root.fid)<0)continue;as=uniqForums(parseForums(b,base));if(as.length>best.length)best=as}}return best}
  function markerCandidates(html,base,index){var root=ROOTS[index],next=index+1<ROOTS.length?ROOTS[index+1]:null,x=s(html),starts=[],p=0,end,i,seg,as,best=[];while((p=x.indexOf(root.name,p))>=0){starts.push(p);p+=root.name.length;if(starts.length>10)break}for(i=0;i<starts.length;i++){end=next?x.indexOf(next.name,starts[i]+root.name.length):-1;if(end<0||end-starts[i]>350000)end=Math.min(x.length,starts[i]+260000);seg=x.slice(starts[i],end);as=uniqForums(parseForums(seg,base));if(as.length>best.length)best=as}return best}
  function rootPageCandidates(root){var urls=[origin()+'/'+root.seed+'?mobile=no',origin()+'/forum.php?mod=forumdisplay&fid='+root.fid+'&mobile=no',origin()+'/forum.php?mod=forumdisplay&fid='+root.fid+'&mobile=2'],best=[],bestLen=0,i,u,h,a;for(i=0;i<urls.length;i++){u=urls[i];h=fetchPc(u);a=uniqForums(parseForums(h,u));if(a.length>best.length){best=a;bestLen=h.length}h=render(u,'forum');a=uniqForums(parseForums(h,u));if(a.length>best.length){best=a;bestLen=h.length}}return{items:best,htmlLen:bestLen}}
  function readGroupCache(){try{var x=JSON.parse(getItem(KEY_GROUP_CACHE,'{}')||'{}');if(x.groups&&new Date().getTime()-Number(x.time||0)<21600000)return x.groups}catch(e){}return null}
  function plausible(a){return a&&a.length>=2&&a.length<=20}
  function resolveGroups(){var c=readGroupCache(),rf,flat,flatGroups,groups=[[],[],[],[],[],[]],diag=[],indexHtml='',indexUrl=origin()+'/forum.php?mobile=no',i,a,b,r,cands,j,best;if(c)return c;rf=resolveAllForums();flat=rf.items||[];flatGroups=groupsFromFlat(flat);indexHtml=fetchPc(indexUrl);if(parseForums(indexHtml,indexUrl).length<8)indexHtml=render(indexUrl,'forum');for(i=0;i<ROOTS.length;i++){a=blockCandidates(indexHtml,indexUrl,ROOTS[i]);b=markerCandidates(indexHtml,indexUrl,i);r=rootPageCandidates(ROOTS[i]);cands=[flatGroups[i]||[],a,b,r.items||[]];best=[];for(j=0;j<cands.length;j++){cands[j]=uniqForums(cands[j]);if(plausible(cands[j])&&(!best.length||cands[j].length>best.length))best=cands[j]}if(!best.length){for(j=0;j<cands.length;j++)if(cands[j].length&&(!best.length||cands[j].length<best.length))best=cands[j]}groups[i]=best;if(!groups[i].length)groups[i]=[{id:ROOTS[i].fid,title:ROOTS[i].name,url:origin()+'/'+ROOTS[i].seed}];diag.push(ROOTS[i].fid+'='+groups[i].length+'(flat '+(flatGroups[i]||[]).length+',block '+a.length+',mark '+b.length+',root '+r.items.length+')')}try{setItem(KEY_GROUP_CACHE,JSON.stringify({time:new Date().getTime(),groups:groups}))}catch(e2){}saveDiag('groups.v9',rf.source+'；flat='+flat.length+'；'+diag.join('；'));return groups}

  function topicInput(cls){return{title:'搜索主题',desc:'搜索',col_type:'input',url:"(function(){var w=String(input||'').trim();if(!w)return 'toast://请输入关键词';putMyVar('sht_search_kw_v1',w);return 'hiker://page/shtSearch?rule=色花堂&simple=true&kw='+encodeURIComponent(w);})()",extra:{defaultValue:'',titleVisible:true,cls:cls||''}}}
  function home(){var d=[],idx=Number(getMyVar(KEY_CAT,'0')||0),groups,g,i,access='';if(idx<0||idx>5)idx=0;setPageTitle('色花堂');groups=resolveGroups();g=groups[idx]||[];try{access=getVar(KEY_ACCESS,'')||''}catch(e){}d.push(topicInput('sht_home_v9'));d.push(quick('账号',route('shtVerify',{sht_mode:'login'}),'account','sht_home_v9'));d.push(quick('签到',route('shtVerify',{sht_mode:'signin'}),'signin','sht_home_v9'));d.push(quick('搜索',route('shtSearch'),'search','sht_home_v9'));d.push(quick('设置',route('shtSettings'),'settings','sht_home_v9'));d.push(line('sht_home_v9'));d.push(section('话题',access==='1'?'站点可访问'+(cookie()?' · Cookie 已同步':' · Cookie 尚未同步'):'站点访问状态尚未建立，可点“账号”自动处理','sht_home_v9'));[['最新发表','latest'],['最新热门','hot'],['最新精华','digest']].forEach(function(x){d.push({title:x[0],desc:'主题列表',url:route('shtForum',{sht_auto:x[1],sht_name:x[0]}),col_type:'text_3',extra:{lineVisible:false,cls:'sht_home_v9'}})});d.push(line('sht_home_v9'));d.push(section('论坛分类','六个一级分类；当前分类下显示真实子板块','sht_home_v9'));for(i=0;i<ROOTS.length;i++)d.push({title:(i===idx?'✓ ':'')+ROOTS[i].icon+' '+ROOTS[i].name,url:$('#noLoading#').lazyRule(function(k,v){putMyVar(k,String(v));refreshPage(false);return'hiker://empty';},KEY_CAT,i),col_type:'text_3',extra:{lineVisible:false,cls:'sht_home_v9'}});d.push(section(ROOTS[idx].icon+' '+ROOTS[idx].name,g.length+' 个子板块','sht_home_v9'));for(i=0;i<g.length;i++)d.push({title:g[i].title,desc:'进入板块',img:icon('board'),pic_url:icon('board'),url:route('shtForum',{sht_url:g[i].url,sht_name:g[i].title}),col_type:'icon_2',extra:{lineVisible:false,cls:'sht_home_v9'}});setResult(d)}

  function badThreadText(t){t=trim(t);if(!t||t.length<2)return true;if(/本帖最后由.+编辑|^(作者|回复于|发表于|查看|回复|最后发表|最后回复|上一页|下一页|返回|详情|进入|播放)/i.test(t))return true;if(/^\d{1,2}:\d{2}(?::\d{2})?$/.test(t))return true;if(/^\d{4}[-/.]\d{1,2}[-/.]\d{1,2}$/.test(t))return true;if(/^\d+$/.test(t))return true;return false}
  function threadScore(t){t=trim(t);if(badThreadText(t))return-999;var n=Math.min(t.length,140);if(/[\u4e00-\u9fffA-Za-z]{2,}/.test(t))n+=35;if(t.length>=8)n+=20;if(/\【|\[|影片名称|原创|中文字幕|无码|有码|写真|视频/i.test(t))n+=12;if(t.length>130)n-=15;return n}
  function validImage(u,base){u=abs(u,base);if(!u||/^data:/i.test(u))return'';if(/avatar\.php|noavatar|smiley|static\/image\/common|logo\.|none\.gif|loading|blank\.gif|emotion|face\//i.test(u))return'';return u}
  function imageCandidates(x,base){var out=[],seen={},re=/<img\b([^>]*)>/gi,m,a,names=['data-original','data-src','data-echo','data-lazy-src','zoomfile','file','src'],i,n,rr,mm,u,style;while((m=re.exec(s(x)))!==null){a=m[1]||'';u='';for(i=0;i<names.length;i++){n=names[i];rr=new RegExp('\\b'+n+'\\s*=\\s*(["\\\'])(.*?)\\1','i');mm=a.match(rr);if(mm){u=validImage(mm[2],base);if(u)break}}if(!u){style=a.match(/background(?:-image)?\s*:\s*url\((?:["']?)([^)"']+)/i);if(style)u=validImage(style[1],base)}if(u&&!seen[u]){seen[u]=1;out.push(u)}if(out.length>=30)break}return out}
  function contextAround(html,index){var x=s(html),start=x.lastIndexOf('<tbody',index),end=start>=0?x.indexOf('</tbody>',index):-1;if(start>=0&&end>=0&&end-start<40000)return x.slice(start,end+8);start=x.lastIndexOf('<li',index);end=start>=0?x.indexOf('</li>',index):-1;if(start>=0&&end>=0&&end-start<25000)return x.slice(start,end+5);start=Math.max(0,index-2200);end=Math.min(x.length,index+4400);return x.slice(start,end)}
  function parseThreads(html,base){var a=anchors(html,base),map={},order=[],i,x,id,t,sc,ctx,pics,out=[];for(i=0;i<a.length;i++){x=a[i];id=threadId(x.href);if(!id)continue;t=trim(x.text);sc=threadScore(t);if(!map[id]){map[id]={id:id,title:sc>-900?t:'',url:normalizeThread(x.href),score:sc,img:'',index:x.index};order.push(id)}else if(sc>map[id].score){map[id].title=t;map[id].score=sc;map[id].url=normalizeThread(x.href);map[id].index=x.index}}for(i=0;i<order.length;i++){id=order[i];x=map[id];if(!x||badThreadText(x.title))continue;ctx=contextAround(html,x.index);pics=imageCandidates(ctx,base);x.img=pics.length?pics[0]:'';out.push({id:id,title:x.title.slice(0,150),url:x.url,img:x.img});if(out.length>=100)break}return{items:out,anchors:a.length}}
  function withPage(u,p){p=Math.max(1,Number(p||1));u=s(u);if(/\/forum-\d+-\d+\.html(?:\?|$)/i.test(u))return u.replace(/\/forum-(\d+)-\d+\.html/i,'/forum-$1-'+p+'.html');if(/([?&])page=\d+/i.test(u))return u.replace(/([?&])page=\d+/i,'$1page='+p);return u+(u.indexOf('?')>=0?'&':'?')+'page='+p}
  function addVariant(list,u){if(!u)return;var i;for(i=0;i<list.length;i++)if(list[i]===u)return;list.push(u)}
  function mobileVariant(u,mob){u=s(u);if(/[?&]mobile=(?:2|no)(?:&|$)/i.test(u))return u.replace(/([?&])mobile=(?:2|no)(?=&|$)/i,'$1mobile='+mob);return u+(u.indexOf('?')>=0?'&':'?')+'mobile='+mob}
  function guideWords(kind){if(kind==='latest')return['最新发表','最新主题','最新帖子'];if(kind==='hot')return['最新热门','热门主题','热门帖子'];if(kind==='digest')return['最新精华','精华主题','精华帖子'];return[]}
  function discoverGuide(kind){var u=origin()+'/forum.php?mobile=no',h=fetchPc(u),a,words=guideWords(kind),i,j,t;if(parseForums(h,u).length<5)h=render(u,'forum');a=anchors(h,u);for(i=0;i<a.length;i++){t=trim(a[i].text);for(j=0;j<words.length;j++)if(t===words[j]||t.indexOf(words[j])>=0)return a[i].href}return''}
  function guideCandidates(kind){var out=[],d=discoverGuide(kind),v=kind==='latest'?'newthread':kind==='hot'?'hot':kind==='digest'?'digest':'';if(d)addVariant(out,d);if(v){addVariant(out,origin()+'/forum.php?mod=guide&view='+v+'&mobile=no');addVariant(out,origin()+'/forum.php?mod=guide&view='+v+'&mobile=2');addVariant(out,origin()+'/forum.php?mod=guide&view='+v)}return out}
  function loadThreadList(seed,kind,pg){var urls=[],bases=[],i,u,h,p,steps=[];if(seed)bases=[seed];else if(kind)bases=guideCandidates(kind);for(i=0;i<bases.length;i++){addVariant(urls,withPage(bases[i],pg));addVariant(urls,withPage(mobileVariant(bases[i],'no'),pg));addVariant(urls,withPage(mobileVariant(bases[i],'2'),pg))}for(i=0;i<urls.length;i++){u=urls[i];h=fetchPc(u);p=parseThreads(h,u);steps.push('fetch'+(i+1)+':'+h.length+'/'+p.items.length);if(p.items.length)return{items:p.items,url:u,source:'fetch',diag:steps.join('；')};h=render(u,'list');p=parseThreads(h,u);steps.push('web'+(i+1)+':'+h.length+'/'+p.items.length);if(p.items.length)return{items:p.items,url:u,source:'webview',diag:steps.join('；')}}return{items:[],url:urls[0]||seed||'',source:'none',diag:steps.join('；')}}
  function forum(){var d=[],seed=pageParam('sht_url',''),kind=pageParam('sht_auto',''),name=pageParam('sht_name','主题列表'),pg=Math.max(1,Number(typeof MY_PAGE==='undefined'?1:MY_PAGE||1)),r,i,item,img;setPageTitle(name);r=loadThreadList(seed,kind,pg);saveDiag('forum.v9',(kind||'forum')+' · '+r.url+' · '+r.diag);if(pg===1){d.push(quick('网页版','x5://'+(r.url||seed||origin()+'/forum.php'),'web'));d.push(quick('搜索',route('shtSearch'),'search'));d.push(line());d.push(section(name,r.items.length?'当前页 '+r.items.length+' 条主题 · '+r.source:'未取得可解析主题'))}for(i=0;i<r.items.length;i++){item=r.items[i];img=item.img?imageUrl(item.img,r.url):'';d.push({title:item.title,desc:'查看帖子',img:img,pic_url:img,url:route('shtThread',{sht_url:item.url,sht_name:item.title}),col_type:img?'movie_1':'text_1',extra:{lineVisible:false}})}if(!r.items.length){d.push(empty('仍没有解析到主题','Test9 已强制执行 fetch + WebView 双链，不再因 HTML 很长就提前停止'));d.push({title:'诊断信息',desc:r.diag||'无诊断',url:'hiker://empty',col_type:'long_text'});d.push({title:'打开当前网页版',desc:r.url||seed,url:'x5://'+(r.url||seed),col_type:'text_1'})}setResult(d)}

  function pcThreadUrl(u){u=s(u);if(/[?&]mobile=2(?:&|$)/i.test(u))return u.replace(/([?&])mobile=2(?=&|$)/i,'$1mobile=no');if(/[?&]mobile=no(?:&|$)/i.test(u))return u;return u+(u.indexOf('?')>=0?'&':'?')+'mobile=no'}
  function hasThreadDom(h){return /id=["']postlist["']|class=["'][^"']*\bt_fsz\b|class=["'][^"']*\bt_f\b|id=["']postmessage_\d+|class=["'][^"']*\bmessage\b/i.test(s(h))}
  function stripMobile(u){u=s(u);u=u.replace(/([?&])mobile=(?:2|no)(?=&|$)/i,'$1').replace(/\?&/g,'?').replace(/&&+/g,'&').replace(/[?&]$/,'');return u}
  function threadHtml(u){var urls=[],i,x,h,steps=[];addVariant(urls,pcThreadUrl(u));addVariant(urls,mobileVariant(u,'2'));addVariant(urls,stripMobile(u));for(i=0;i<urls.length;i++){x=urls[i];h=fetchPc(x);steps.push('fetch'+(i+1)+':'+h.length+'/'+(hasThreadDom(h)?'dom':'no'));if(hasThreadDom(h))return{html:h,url:x,source:'fetch',diag:steps.join('；')};h=render(x,'thread');steps.push('web'+(i+1)+':'+h.length+'/'+(hasThreadDom(h)?'dom':'no'));if(hasThreadDom(h))return{html:h,url:x,source:'webview',diag:steps.join('；')}}return{html:'',url:urls[0]||u,source:'none',diag:steps.join('；')}}
  function extractFloors(html){var out=[],seen={},nodes=[],i,body,author,key,selectors=['body&&#postlist>div','body&&#postlist&&div[id^=post_]'];for(i=0;i<selectors.length&&!out.length;i++){try{nodes=pdfa(html,selectors[i])||[]}catch(e){nodes=[]}for(var j=0;j<nodes.length;j++){try{body=pdfh(nodes[j],'body&&div.t_fsz&&Html')||pdfh(nodes[j],'body&&div.t_f&&Html')||pdfh(nodes[j],'body&&td.t_f&&Html')||pdfh(nodes[j],'body&&.message&&Html')||''}catch(e2){body=''}if(!trim(strip(body)))continue;try{author=trim(pdfh(nodes[j],'body&&.authi&&a&&Text')||pdfh(nodes[j],'body&&.xw1&&Text')||'')}catch(e3){author=''}key=strip(body).slice(0,180);if(key&&!seen[key]){seen[key]=1;out.push({body:body,author:author})}}}
    if(out.length)return out;selectors=['body&&div.t_fsz','body&&div.t_f','body&&td.t_f','body&&[id^=postmessage_]','body&&.message'];for(i=0;i<selectors.length&&out.length<2;i++){try{nodes=pdfa(html,selectors[i])||[]}catch(e4){nodes=[]}for(var k=0;k<nodes.length;k++){try{body=pdfh(nodes[k],'body&&Html')||s(nodes[k])}catch(e5){body=s(nodes[k])}if(!trim(strip(body)))continue;key=strip(body).slice(0,180);if(key&&!seen[key]){seen[key]=1;out.push({body:body,author:''})}}}return out}
  function magnetList(x){var t=hdec(s(x)),out=[],seen={},m,re=/magnet:\?xt=urn:btih:[a-z0-9]{32,40}(?:&[^\s"'<>]*)?/ig,v,hm,key;while((m=re.exec(t))!==null){v=m[0].replace(/[)\]}>，。；;]+$/g,'');hm=v.match(/btih:([a-z0-9]{32,40})/i);key=hm?hm[1].toUpperCase():v.toLowerCase();if(!seen[key]){seen[key]=1;out.push({url:v,key:key,hash:hm?hm[1]:''})}if(out.length>=20)break}return out}
  function videoUrls(x){var out=[],seen={},m,re=/(https?:\/\/[^\s"'<>]+?\.(?:m3u8|mp4)(?:\?[^\s"'<>]*)?)/ig,u;while((m=re.exec(hdec(s(x))))!==null){u=m[1].replace(/[)\]}>，。；;]+$/g,'');if(!seen[u]){seen[u]=1;out.push(u)}if(out.length>=6)break}return out}
  function sniffSeed(x,base){var m=s(x).match(/<iframe\b[^>]*(?:src|data-src)\s*=\s*["']([^"']+)["']/i),u=m?abs(m[1],base):'';return u||base}
  function plainBodyHtml(x){x=s(x).replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<iframe[\s\S]*?<\/iframe>/gi,'').replace(/<img\b[^>]*>/gi,'');x=x.replace(/<div[^>]*class=["'][^"']*(?:sign|signature)[^"']*["'][^>]*>[\s\S]*?<\/div>/gi,'').replace(/<div class=["']xs0["'][\s\S]*?<\/div>/gi,'').replace(/<p class=["']mbn["'][\s\S]*?<\/p>/gi,'').replace(/<div class=["']tip tip_4["'][\s\S]*?<\/div>/gi,'');x=x.replace(/<[^>]*>[^<]*本帖最后由[\s\S]*?编辑[^<]*<\/[^>]+>/gi,'');x=x.replace(/(<br\s*\/?\s*>\s*){3,}/gi,'<br><br>');return x}
  function cleanMagnetsFromHtml(x,hasNew){x=s(x);if(hasNew){x=x.replace(/<a\b[^>]*href\s*=\s*["']magnet:[^"']*["'][^>]*>[\s\S]*?<\/a>/gi,'').replace(/magnet:\?xt=urn:btih:[a-z0-9]{32,40}(?:&[^\s"'<>]*)?/ig,'');x='<b>【磁链已识别，云播入口见正文下方】</b><br>'+x}return x}
  function replyUrl(html,base){var m=s(html).match(/href=["']([^"']*(?:mod=post[^"']*action=reply|action=reply[^"']*mod=post)[^"']*)["']/i);return m?abs(m[1],base):base}
  function thread(){var d=[],url=pageParam('sht_url',''),title=pageParam('sht_name','帖子详情'),r,floors=[],i,body,author,allMs,ms=[],j,valid=0,videos=[],videoHint=false,seenThreadMagnet={},seed,imgs=[],bodyHtml,ref;if(!url){setResult([empty('帖子参数缺失')]);return}setPageTitle(title||'帖子详情');r=threadHtml(url);ref=r.url||url;saveDiag('thread.v9',r.diag);d.push(section(title||'帖子详情','原帖 / 回复 / 正文图片 / 磁链云播 / 视频嗅探'));d.push(quick('原帖','x5://'+url,'original'));d.push(quick('回复','x5://'+replyUrl(r.html,ref),'reply'));d.push(quick('复制链接','copy://'+url,'copy'));d.push(quick('设置',route('shtSettings'),'settings'));d.push(line());floors=extractFloors(r.html);if(!floors.length){d.push(empty('未识别到帖子正文','Test9 已按内容结构强制切换 PC / mobile / WebView；当前仍未取得真实正文 DOM'));d.push({title:'诊断',desc:r.diag||'无诊断',url:'hiker://empty',col_type:'long_text'});d.push({title:'打开原帖网页版',desc:url,url:'x5://'+url,col_type:'text_1'});setResult(d);return}for(i=0;i<floors.length&&valid<20;i++){body=floors[i].body;author=floors[i].author||'';if(!trim(strip(body)))continue;allMs=magnetList(body);ms=[];for(j=0;j<allMs.length;j++)if(!seenThreadMagnet[allMs[j].key]){seenThreadMagnet[allMs[j].key]=1;ms.push(allMs[j])}videos=videoUrls(body);videoHint=videos.length>0||/<video\b|<iframe\b|视频加载中|在线播放|dplayer|ckplayer|jwplayer|m3u8|\.mp4/i.test(body);seed=sniffSeed(body,ref);imgs=imageCandidates(body,ref);valid++;d.push(section(valid===1?'楼主'+(author?' · '+author:''):'回复 '+(valid-1)+(author?' · '+author:''),[imgs.length?imgs.length+' 张图片':'',ms.length?ms.length+' 条磁链':'',videoHint?'检测到视频内容':''].filter(Boolean).join(' · ')));if(videos.length)d.push({title:'▶ 直接播放',desc:'已识别视频直链',url:videos[0]+'#isVideo=true#',col_type:'text_center_1',extra:{lineVisible:false}});if(videoHint)d.push({title:'▶ 嗅探播放',desc:'使用海阔自动提取网页视频',url:'video://'+seed,col_type:'text_center_1',extra:{lineVisible:false,ua:UA_M,referer:url,blockRules:['.jpg','.png','.gif','.woff','.woff2','.ttf'],cacheM3u8:true}});bodyHtml=cleanMagnetsFromHtml(plainBodyHtml(body),ms.length>0);if(trim(strip(bodyHtml)))d.push({title:bodyHtml,url:'hiker://empty',col_type:'rich_text',extra:{lineVisible:false}});for(j=0;j<imgs.length;j++){var pu=imageUrl(imgs[j],ref);d.push({title:'',desc:'',img:pu,pic_url:pu,url:'pics://'+pu,col_type:'pic_1_full',extra:{lineVisible:false,imgLongClick:true}})}for(j=0;j<ms.length;j++){var magnet=ms[j].url,hash=ms[j].hash;d.push({title:'磁链 '+(j+1),desc:hash?hash.slice(0,14)+'…':'已识别',url:'copy://'+magnet,col_type:'text_1',extra:{lineVisible:false}});d.push({title:'115',url:'hiker://page/115Offline?rule=115.简&page=fypage&add='+encodeURIComponent(magnet),col_type:'icon_small_4'});d.push({title:'迅雷',url:'hiker://page/diaoyong?rule=迅雷&page=fypage#'+magnet,col_type:'icon_small_4'});d.push({title:'PikPak',url:'pikpakapp://mypikpak.com/xpan/main_tab?tab=1&add_url='+magnet,col_type:'icon_small_4'});d.push({title:'复制',img:icon('copy'),pic_url:icon('copy'),url:'copy://'+magnet,col_type:'icon_small_4'})}d.push(line())}setResult(d)}

  function settings(){var d=[],dg={};setPageTitle('色花堂设置');d.push(section('Test9 运行链修复','子板块优先复用曾成功取得约45板块的设备缓存，再用 forum.php 多链重建；主题/帖子改为“解析失败就继续 WebView”，不再只看 HTML 长度。'));d.push({title:'清空 Test9 分类缓存',desc:'只清 Test9 分组/平铺缓存，不动 Cookie 和旧已验证缓存',url:$('#noLoading#').lazyRule(function(a,b){setItem(a,'{}');setItem(b,'{}');refreshPage(false);return'toast://Test9 分类缓存已清空';},KEY_GROUP_CACHE,KEY_FLAT_CACHE),col_type:'text_1'});try{dg=JSON.parse(getItem(KEY_DIAG,'{}')||'{}')}catch(e){}d.push({title:'最近诊断',desc:(dg.stage||'暂无')+'\n'+(dg.error||''),url:'hiker://empty',col_type:'long_text'});d.push({title:'打开旧设置',desc:'访问状态 / Cookie / 旧兼容入口',url:route('shtSettingsLegacy'),col_type:'text_1'});setResult(d)}
  function module(){var m=BASE.module();m.version=VERSION;m.build=BUILD;m.home=home;m.forum=forum;m.thread=thread;m.settings=settings;m._debug=m._debug||{};m._debug.resolveGroupsV9=resolveGroups;m._debug.parseThreadsV9=parseThreads;m._debug.threadHtmlV9=threadHtml;return m}
  var PATCHED={version:VERSION,build:BUILD,module:module};SeHuaTangRemoteRuntime=PATCHED;return PATCHED;
})();