/* 汤头条 0.1.0-test.10 PlaybackAdapter / content-type sniff + wrapped-source HLS + duration validation */
var TangTouTiaoPlaybackV018=(function(){
  var V='0.1.0-test.10';
  function compactUrl(u){u=String(u||'');return u.length>180?u.substring(0,90)+'…'+u.substring(u.length-70):u;}
  function jstr(s){return new java.lang.String(String(s==null?'':s));}function bytes(s){return jstr(s).getBytes('UTF-8');}function newBytes(n){return java.lang.reflect.Array.newInstance(java.lang.Byte.TYPE,n);}function copy(src,sp,dst,dp,len){java.lang.System.arraycopy(src,sp,dst,dp,len);}
  function hexBytes(s){s=String(s||'').trim();if(!s||s.length%2!==0||!/^[0-9A-Fa-f]+$/.test(s))return null;var a=newBytes(s.length/2);for(var i=0;i<a.length;i++){var v=parseInt(s.substr(i*2,2),16);a[i]=v>127?v-256:v;}return a;}
  function evp(secret,keyLen,ivLen){var pass=bytes(secret),md=java.security.MessageDigest.getInstance('MD5'),need=keyLen+ivLen,all=newBytes(need),pos=0,prev=null;while(pos<need){md.reset();if(prev)md.update(prev);md.update(pass);prev=md.digest();var n=Math.min(prev.length,need-pos);copy(prev,0,all,pos,n);pos+=n;}var key=newBytes(keyLen),iv=newBytes(ivLen);copy(all,0,key,0,keyLen);copy(all,keyLen,iv,0,ivLen);return{key:key,iv:iv};}
  function decrypt(hex,secret){var all=hexBytes(hex);if(!all||all.length<17)throw new Error('m3u8密文不是合法HEX');var iv=newBytes(16),body=newBytes(all.length-16);copy(all,0,iv,0,16);copy(all,16,body,0,body.length);var p=evp(secret,32,16),cipher=javax.crypto.Cipher.getInstance('AES/CFB/NoPadding'),key=new javax.crypto.spec.SecretKeySpec(p.key,'AES');cipher.init(2,key,new javax.crypto.spec.IvParameterSpec(iv));return String(new java.lang.String(cipher.doFinal(body),'UTF-8'));}
  function headers(){var h={'User-Agent':'Mozilla/5.0 (Linux; Android 13; HikerView) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Mobile Safari/537.36','Accept':'*/*','Cache-Control':'no-cache'},r=String(getItem('ttt_player_refer','')||''),x=String(getItem('ttt_player_xauth','')||'');if(r)h.Referer=r;if(x)h['X-Auth']=x;return h;}
  function headerValue(h,n){if(!h)return'';n=String(n||'').toLowerCase();for(var k in h)if(h.hasOwnProperty(k)&&String(k).toLowerCase()===n){var v=h[k];return Array.isArray(v)?String(v[0]||''):String(v||'');}return'';}
  function headProbe(u){var out={status:0,type:'',length:0,location:'',error:''};try{var r=fetch(u,{timeout:8000,headers:headers(),onlyHeaders:true,withStatusCode:true});if(typeof r==='string'){try{r=JSON.parse(r);}catch(e0){r={headers:{raw:r}};}}r=r||{};var hs=r.headers||r;out.status=Number(r.statusCode||r.status||0);out.type=headerValue(hs,'content-type').toLowerCase();out.length=Number(headerValue(hs,'content-length')||0);out.location=headerValue(hs,'location');}catch(e){out.error=String(e.message||e);}return out;}
  function decodeM3u8(remote){var raw=String(fetch(remote,{timeout:12000,headers:headers()})||''),trim=raw.trim(),plain=trim,mode='plain',dekey=String(getItem('ttt_player_dekey','')||'');if(trim.indexOf('#EXTM3U')!==0){if(!dekey)throw new Error('播放器配置缺少 dekey');plain=decrypt(trim,dekey).trim();mode='aes-cfb';}if(plain.indexOf('#EXTM3U')!==0)throw new Error('响应不是可解密 M3U8');return{plain:plain,mode:mode};}
  function durationOf(s){var dur=0,m=String(s||'').match(/#EXTINF:([0-9.]+)/g)||[];for(var i=0;i<m.length;i++){var x=m[i].match(/([0-9.]+)/);if(x)dur+=Number(x[1]||0);}return Math.round(dur*10)/10;}
  function durationSeconds(v){if(typeof v==='number'&&isFinite(v))return Number(v);v=String(v||'').trim();if(!v)return 0;if(/^\d+(?:\.\d+)?$/.test(v))return Number(v);var p=v.split(':').map(function(x){return Number(x||0);});if(p.some(function(x){return !isFinite(x);}))return 0;if(p.length===3)return p[0]*3600+p[1]*60+p[2];if(p.length===2)return p[0]*60+p[1];return 0;}
  function childOf(remote,plain){if(!/#EXT-X-STREAM-INF/i.test(plain))return'';var fixed=String(fixM3u8(remote,plain)||''),ls=fixed.split('\n');for(var i=0;i<ls.length;i++){var l=String(ls[i]||'').trim();if(l&&l.charAt(0)!=='#'&&/^https?:\/\//i.test(l))return l;}return'';}
  function badDuration(dur,expected){if(!(dur>0))return false;if(dur<4)return true;if(expected>=30&&dur<expected*0.70)return true;return false;}
  function wrappedInner(u){var m=String(u||'').match(/^https?:\/\/[^\/]+\/(https?:\/\/.+)$/i);if(!m)return'';var x=m[1];try{x=decodeURIComponent(x);}catch(e){}return x;}
  function variants(u){u=String(u||'').trim();var a=[];function add(x,label){x=String(x||'').trim();if(!/^https?:\/\//i.test(x))return;for(var i=0;i<a.length;i++)if(a[i].url===x)return;a.push({url:x,label:label});}add(u,'api-source');add(wrappedInner(u),'inner-source');return a;}
  function likelyHls(u,h){var ct=String(h.type||'').toLowerCase();if(/\.m3u8(?:\?|$)/i.test(u))return true;if(/mpegurl|m3u8|application\/vnd\.apple/i.test(ct))return true;if(/text\/plain|text\/html/i.test(ct)&&(!h.length||h.length<2*1024*1024))return true;if(/octet-stream/i.test(ct)&&h.length>0&&h.length<2*1024*1024)return true;if(/\/https?:\/\//i.test(u)||/yd-(?:long|short)\.|utxxds\./i.test(u))return true;return false;}
  function inspectHls(remote,expected,depth){try{var d=decodeM3u8(remote),dur=durationOf(d.plain),child=dur<=0&&depth<2?childOf(remote,d.plain):'';if(child){var c=inspectVariant(child,expected,(depth||0)+1);if(c.ok&&c.kind==='hls')return{ok:true,kind:'hls',duration:c.duration,mode:d.mode+'+master',remote:remote,playRemote:c.playRemote||child,suspicious:!!c.suspicious,ratio:c.ratio,head:c.head};}var ratio=expected>0&&dur>0?Math.round((dur/expected)*1000)/1000:null;return{ok:true,kind:'hls',duration:dur,mode:d.mode,remote:remote,playRemote:remote,suspicious:badDuration(dur,expected),ratio:ratio};}catch(e){return{ok:false,error:String(e.message||e),remote:remote};}}
  function inspectVariant(remote,expected,depth){remote=String(remote||'').trim();if(!remote)return{ok:false,error:'empty'};var hp=headProbe(remote),ct=String(hp.type||'').toLowerCase();if(likelyHls(remote,hp)){var hls=inspectHls(remote,expected,depth||0);hls.head={status:hp.status,type:hp.type,length:hp.length,error:hp.error};return hls;}if(/video\/(?:mp4|webm|quicktime|x-m4v)/i.test(ct)||/\.(?:mp4|m4v|webm)(?:\?|$)/i.test(remote)){return{ok:true,kind:'direct',duration:null,mode:'direct-video',remote:remote,playRemote:remote,suspicious:false,head:{status:hp.status,type:hp.type,length:hp.length,error:hp.error}};}return{ok:false,error:'未知媒体类型 '+(hp.type||'no-content-type'),remote:remote,head:{status:hp.status,type:hp.type,length:hp.length,error:hp.error}};}
  function inspectSource(source,expected){var vs=variants(source.url),errs=[];for(var i=0;i<vs.length;i++){var r=inspectVariant(vs[i].url,expected,0);r.variant=vs[i].label;if(r.ok)return r;errs.push(vs[i].label+':'+String(r.error||'失败'));}return{ok:false,error:errs.join(' | '),remote:source.url};}
  function makeProxy(){var code=$.toString(function(){
      function jstr(s){return new java.lang.String(String(s==null?'':s));}function bytes(s){return jstr(s).getBytes('UTF-8');}function newBytes(n){return java.lang.reflect.Array.newInstance(java.lang.Byte.TYPE,n);}function copy(src,sp,dst,dp,len){java.lang.System.arraycopy(src,sp,dst,dp,len);}function hexBytes(s){s=String(s||'').trim();if(!s||s.length%2!==0)return null;var a=newBytes(s.length/2);for(var i=0;i<a.length;i++){var v=parseInt(s.substr(i*2,2),16);if(isNaN(v))return null;a[i]=v>127?v-256:v;}return a;}function evp(secret,keyLen,ivLen){var pass=bytes(secret),md=java.security.MessageDigest.getInstance('MD5'),need=keyLen+ivLen,all=newBytes(need),pos=0,prev=null;while(pos<need){md.reset();if(prev)md.update(prev);md.update(pass);prev=md.digest();var n=Math.min(prev.length,need-pos);copy(prev,0,all,pos,n);pos+=n;}var key=newBytes(keyLen),iv=newBytes(ivLen);copy(all,0,key,0,keyLen);copy(all,keyLen,iv,0,ivLen);return{key:key,iv:iv};}function decrypt(hex,secret){var all=hexBytes(hex);if(!all||all.length<17)throw new Error('m3u8密文不是合法HEX');var iv=newBytes(16),body=newBytes(all.length-16);copy(all,0,iv,0,16);copy(all,16,body,0,body.length);var p=evp(secret,32,16),cipher=javax.crypto.Cipher.getInstance('AES/CFB/NoPadding'),key=new javax.crypto.spec.SecretKeySpec(p.key,'AES');cipher.init(2,key,new javax.crypto.spec.IvParameterSpec(iv));return String(new java.lang.String(cipher.doFinal(body),'UTF-8'));}
      function childProxy(u,base){if(!base)return u;return base+'?m3u8=1&u='+encodeURIComponent(base64Encode(u))+'&p='+encodeURIComponent(base64Encode(base))+'&_t='+Date.now();}
      try{var remote=base64Decode(decodeURIComponent(String(MY_PARAMS.u||''))),base=base64Decode(decodeURIComponent(String(MY_PARAMS.p||''))),refer=String(getItem('ttt_player_refer','')||''),xauth=String(getItem('ttt_player_xauth','')||''),dekey=String(getItem('ttt_player_dekey','')||''),h={'User-Agent':'Mozilla/5.0 (Linux; Android 13; HikerView) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Mobile Safari/537.36','Accept':'*/*','Cache-Control':'no-cache'};if(refer)h.Referer=refer;if(xauth)h['X-Auth']=xauth;var raw=String(fetch(remote,{timeout:15000,headers:h})||''),trim=raw.trim(),plain=trim,mode='plain';if(trim.indexOf('#EXTM3U')!==0){if(!dekey)throw new Error('播放器配置缺少 dekey');plain=decrypt(trim,dekey).trim();mode='aes-cfb';}if(plain.indexOf('#EXTM3U')!==0)throw new Error('解密结果不是 M3U8');var fixed=fixM3u8(remote,plain),lines=String(fixed).split('\n');for(var i=0;i<lines.length;i++){var line=String(lines[i]||'').trim();if(line.indexOf('#')===0)lines[i]=lines[i].replace(/URI="(https?:\/\/[^\"]+)"/ig,function(_,u){return/\.m3u8(?:\?|$)/i.test(u)?'URI="'+childProxy(u,base)+'"':'URI="'+u+'"';});else if(/^https?:\/\//i.test(line)&&(/\.m3u8(?:\?|$)/i.test(line)||/#EXT-X-STREAM-INF/i.test(plain)))lines[i]=childProxy(line,base);}setItem('ttt_last_play_diag',JSON.stringify({time:Date.now(),ok:true,mode:mode,remote:String(remote).substring(0,220)}));return lines.join('\n');}catch(e){setItem('ttt_last_play_diag',JSON.stringify({time:Date.now(),ok:false,error:String(e.message||e)}));return'#EXTM3U\n#EXT-X-VERSION:3\n#EXT-X-ENDLIST';}
    });return startProxyServer(code);}
  function proxyUrl(proxy,u,i){return proxy+'?m3u8=1&u='+encodeURIComponent(base64Encode(u))+'&p='+encodeURIComponent(base64Encode(proxy))+'&_t='+Date.now()+'_'+(i||0)+'#isVideo=true#';}
  function parse(payload){var x=typeof payload==='string'?JSON.parse(payload):payload||{};return{x:x,src:Array.isArray(x.sources)?x.sources:[],expected:durationSeconds(x.expectedDuration||0)};}
  function ordered(src,preferred){var order=[],seen={};function add(s){if(!s||seen[s.name+'|'+s.url])return;seen[s.name+'|'+s.url]=1;order.push(s);}preferred=String(preferred||'240P');for(var i=0;i<src.length;i++)if(String(src[i].name)===preferred)add(src[i]);var names=['240P','480P','720P','1080P','原始','预览'];for(var n=0;n<names.length;n++)for(var j=0;j<src.length;j++)if(String(src[j].name)===names[n])add(src[j]);for(var k=0;k<src.length;k++)add(src[k]);return order;}
  function choose(payload,preferred){var p=parse(payload);if(!p.src.length)return{error:'没有可用播放线路'};try{if(typeof TangTouTiaoProtocolV015==='object')TangTouTiaoProtocolV015.bootstrapSession(false);}catch(e){}var q=ordered(p.src,preferred),checks=[];for(var i=0;i<q.length;i++){var r=inspectSource(q[i],p.expected),h=r.head||{};checks.push({name:q[i].name,ok:r.ok,variant:r.variant||'',kind:r.kind||'',duration:r.duration,expected:p.expected,ratio:r.ratio,mode:r.mode||'',suspicious:!!r.suspicious,status:h.status||0,type:h.type||'',length:h.length||0,error:r.error||'',url:compactUrl(q[i].url)});if(r.ok&&!r.suspicious){try{setItem('ttt_last_source_probe',JSON.stringify({time:Date.now(),preferred:String(preferred||''),expected:p.expected,chosen:q[i].name,checks:checks}));}catch(e1){}return{source:q[i],probe:r,index:i,checks:checks};}}try{setItem('ttt_last_source_probe',JSON.stringify({time:Date.now(),preferred:String(preferred||''),expected:p.expected,chosen:'',checks:checks}));}catch(e2){}return{error:'未找到完整可播放线路',checks:checks};}
  function playBest(payload,preferred){var c=choose(payload,preferred||'240P');if(c.error)return'toast://'+c.error;var playRemote=c.probe.playRemote||c.source.url,u;if(c.probe.kind==='hls'){var proxy=makeProxy();u=proxyUrl(proxy,playRemote,c.index);}else{u=playRemote+'#isVideo=true#';}setItem('ttt_last_play_sources',JSON.stringify({time:Date.now(),mode:'sniffed-single',preferred:String(preferred||'240P'),name:c.source.name,kind:c.probe.kind,variant:c.probe.variant||'',url:compactUrl(playRemote)}));return u;}
  return{version:V,playBest:playBest};
})();
