/* Hanime1 2.0.2-test.1 - Local-First final overlay over Stable 2.0.1 business chain */
(function(C,P,E,H,L){
var VERSION='2.0.2-test.1',BUILD=20101;
var BUNDLE='hiker://files/rules/asset-core-local/hanime1-test/b20101/runtime_bundle.js';
var META='hiker://files/rules/asset-core-local/hanime1-test/b20101/bundle_meta.json';
function safeJson(s,d){try{return JSON.parse(String(s||''));}catch(e){return d;}}
function localInfo(){var m={};try{if(fileExist(META))m=safeJson(readFile(META),'')||{};}catch(e){}return{version:VERSION,build:BUILD,bundleReady:fileExist(BUNDLE),modules:Number(m.modules||0),sourceRef:String(m.sourceRef||''),installedAt:Number(m.installedAt||0),bytes:Number(m.bytes||0)};}
function checkRemote(){return $('#noLoading#').lazyRule(function(){var loading=false;try{showLoading('正在检查 Hanime1 测试版…');loading=true;var repo='huoguotiankong/asset-core-7f3',p='apps/video/hanime1/channels.json',head='',a=['https://api.github.com/repos/'+repo+'/branches/main?_t='+Date.now(),'https://api.github.com/repos/'+repo+'/commits/main?_t='+Date.now()];for(var i=0;i<a.length&&!head;i++){try{var x=JSON.parse(String(fetch(a[i],{timeout:2600,headers:{'Cache-Control':'no-cache','Accept':'application/vnd.github+json'}})||'{}'));head=String(x&&x.commit&&x.commit.sha||'');if(!/^[0-9a-f]{40}$/i.test(head))head='';}catch(_e){}}if(!head)throw new Error('无法取得 main HEAD');var u='https://raw.githubusercontent.com/'+repo+'/'+head+'/'+p,s=String(fetch(u,{timeout:3000,headers:{'Cache-Control':'no-cache'}})||''),m=JSON.parse(s),cs=m&&m.channels||[],t=null;for(i=0;i<cs.length;i++)if(String(cs[i]&&cs[i].channel||'')==='test'){t=cs[i];break;}hideLoading();loading=false;if(!t)return'toast://未发现测试通道';var b=Number(t.build||0),v=String(t.version||'');return b>20101?'toast://发现新测试版 '+v+' / Build'+b+'，请在“我的规则仓库”中覆盖更新':'toast://当前已是最新测试版 '+VERSION;}catch(e){if(loading)try{hideLoading();}catch(_e2){}return'toast://检查失败：'+String(e.message||e);}});}
function rebuild(){return $('#noLoading#').lazyRule(function(){try{var files=['hiker://files/rules/asset-core-local/hanime1-test/b20101/runtime_bundle.js','hiker://files/rules/asset-core-local/hanime1-test/b20101/bundle_meta.json'];for(var i=0;i<files.length;i++)try{deleteFile(files[i]);}catch(e){}return'toast://本地运行包已标记重建，请退出 Hanime1 后重新打开';}catch(e){return'toast://重建标记失败：'+String(e.message||e);}});}
function diag(){return $('#noLoading#').lazyRule(function(){try{var m={},p='hiker://files/rules/asset-core-local/hanime1-test/b20101/bundle_meta.json';if(fileExist(p))m=JSON.parse(String(readFile(p)||'{}'));var a=[];a.push('Hanime1 '+String(m.version||'2.0.2-test.1')+' / Build '+String(m.build||20101));a.push('Local-First bundle '+(fileExist('hiker://files/rules/asset-core-local/hanime1-test/b20101/runtime_bundle.js')?'ready':'missing'));a.push('modules '+String(m.modules||0));a.push('bytes '+String(m.bytes||0));a.push('source '+String(m.sourceRef||'--'));a.push('installed '+String(m.installedAt||0));return'confirm://'+a.join('\n');}catch(e){return'toast://诊断失败：'+String(e.message||e);}});}
E.renderSettings=function(d){var st=C.state(),acc=null,li=localInfo();try{acc=C.activeAccount();}catch(e){}d.push(H.sec('账号',acc?(acc.name+(acc.email?' · '+acc.email:'')):'未同步账号资料'));d.push(H.btn(acc?'账号中心':'到“我的”同步账号',acc?H.route('hanimeAccount',{}):'hiker://empty','text_center_1'));d.push(H.sec('界面','Stable 2.0.1 已验证业务链原样本地化；账号、搜索、评论、播放逻辑不因本次迁移改写。'));d.push(H.btn('页面封面布局',H.route('hanimeLayoutSettings',{}),'text_center_1'));d.push(H.sec('网络','当前线路 · '+st.base));d.push(H.btn('重新检测线路',$('#noLoading#').lazyRule(function(){clearItem('hanime2_active_host');clearItem('hanime2_host_ts');try{var h=$.require('hanime').core().resolveHost(true);refreshPage(false);return'toast://当前线路 '+h;}catch(e){return'toast://'+String(e.message||e);}}),'text_2'));d.push(H.btn('浏览器验证',H.route('hanimeVerify',{url:st.base}),'text_2'));d.push(H.sec('测试版本',VERSION+' · Build '+BUILD+' · Native Local-First'));d.push(H.btn('检查测试版更新',checkRemote(),'text_2'));d.push(H.btn('更新方式','toast://请在“我的规则仓库”中选择 Hanime1 测试版覆盖更新','text_2'));d.push(H.sec('本地运行包',(li.bundleReady?'已安装':'未完成')+' · '+li.modules+' 模块 · '+li.bytes+' B'));d.push(H.btn('本地化诊断',diag(),'text_2'));d.push(H.btn('重建本地运行包',rebuild(),'text_2'));d.push(H.sec('说明','正常启动只读取本地 bundle；GitHub 仅在首次安装/重建或显式检查更新时访问。'));
};
E.localFirstInfo=localInfo;
E.build=VERSION;C.build=VERSION;P.build=VERSION;
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);
