/* Hanime1 Test30 account hub + exact playlist parsing */
(function(C,P,E,H,L){
function clean(v){return C.clean(String(v==null?'':v));}
function nodes(html,sel){try{return pdfa(String(html||''),sel)||[];}catch(e){return [];}}
function text(node,sel){try{return clean(pdfh(node,sel)||'');}catch(e){return '';}}
function attr(node,sel){try{return String(pdfh(node,sel)||'').replace(/&amp;/g,'&').trim();}catch(e){return '';}}
function firstText(node,sels){for(var i=0;i<sels.length;i++){var v=text(node,sels[i]);if(v)return v;}return '';}
function firstAttr(node,sels){for(var i=0;i<sels.length;i++){var v=attr(node,sels[i]);if(v)return v;}return '';}
function abs(base,u){u=String(u||'').trim();return u?C.abs(base,u):'';}
function videoId(u){var m=String(u||'').match(/[?&]v=(\d+)/);return m?m[1]:'';}
function videoCard(n,base){var href=firstAttr(n,['a[href*=watch]&&href','[data-href]&&data-href']),id=videoId(href),title=firstText(n,['.video-title&&Text','.title&&Text','img.main-thumb&&alt','img&&alt']),img=firstAttr(n,['img.main-thumb&&src','img&&data-src','img&&src']);if(!id)return null;return {id:id,title:title||('影片 '+id),img:abs(base,img),artist:firstText(n,['.meta-author a&&Text','.subtitle a&&Text']),duration:firstText(n,['.duration&&Text']),views:firstText(n,['.stats-container .stat-item,1&&Text','.stats-container&&Text']),upload:firstText(n,['.meta-stats span&&Text'])};}
function videoList(h,base){var a=nodes(h,'.playlist-video-list > div.user-tab-item-wrapper'),out=[],seen={};if(!a.length)a=nodes(h,'.user-tab-item-wrapper');for(var i=0;i<a.length;i++){var x=videoCard(a[i],base);if(x&&x.id&&!seen[x.id]){seen[x.id]=1;out.push(x);}}return out;}
function playlistCards(h,base){var a=nodes(h,'.user-tab-item-wrapper,.playlist-item-wrapper,.playlist-card'),out=[],seen={};for(var i=0;i<a.length;i++){var href=firstAttr(a[i],['a.video-link&&href','a[href*=playlist?list=]&&href','a[href*=playlist]&&href']),m=String(href||'').match(/[?&]list=([^&]+)/),id=m?m[1]:'',title=firstText(a[i],['.title&&Text','.playlist-title&&Text']);if(!id||!title||seen[id])continue;seen[id]=1;out.push({id:id,title:title,count:firstText(a[i],['.stat-item&&Text','.playlist-count&&Text']),img:abs(base,firstAttr(a[i],['img.main-thumb&&src','img&&src']))});}return out;}
P.playlist=function(id,sort){var base=C.resolveHost(false),url=C.query(base+'/playlist',{list:id,sort:sort||'latest',page:1}),r=C.get(url,{base:base,referer:base+'/',timeout:15000});if(!r||r.challenge||Number(r.statusCode||0)>=400)throw new Error('片单详情请求失败：HTTP '+Number((r&&r.statusCode)||0));var h=String(r.body||''),items=videoList(h,base);return {id:String(id),title:firstText(h,['.playlist-title&&Text'])||'片单',desc:firstText(h,['.playlist-description&&Text']),author:firstText(h,['.playlist-author-info a&&Text']),cover:abs(base,firstAttr(h,['.playlist-main-thumbnail&&src'])),count:firstText(h,['#sidebar-video-count&&Text']),views:firstText(h,['.playlist-stats&&Text']),items:items,csrf:firstAttr(h,['meta[name=csrf-token]&&content','input[name=_token]&&value'])};};
P.librarySection30=function(kind){var a=C.activeAccount();if(!a)throw new Error('请先登录');var base=C.resolveHost(false),id=String(a.id||''),path=kind==='watchLater'?('/user/'+id+'/saves'):kind==='favorites'?('/user/'+id+'/likes'):kind==='playlists'?('/user/'+id+'/playlists'):kind==='history'?('/user/'+id+'/histories?sort=latest&page=1'):'/subscriptions?page=1',r=C.get(base+path,{base:base,referer:base+'/',timeout:15000});if(!r||r.challenge||Number(r.statusCode||0)>=400)throw new Error('账号内容加载失败：HTTP '+Number((r&&r.statusCode)||0));var h=String(r.body||'');return kind==='playlists'?{playlists:playlistCards(h,base),items:[]}:{playlists:[],items:videoList(h,base)};};
E.playlistPage=function(){try{var id=H.pv('id',''),p=P.playlist(id,'latest'),d=[];setPageTitle(p.title);d.push({title:p.title,desc:[p.author,p.count?('共 '+p.count+' 部'):'',p.desc].filter(Boolean).join(' · '),pic_url:p.cover||'',url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});d.push(H.btn('修改名称','input://'+JSON.stringify({value:p.title||'',hint:'片单名称',js:"try{var m=$.require('hanime'),x=m.provider().playlist('"+id+"','latest');m.provider().updatePlaylist('"+id+"',input,x.desc||'',false);refreshPage(false);return 'toast://已修改';}catch(e){return 'toast://'+String(e.message||e);}"}),'text_2'));d.push(H.btn('删除片单','confirm://确认删除该片单？.js:'+$.toString(function(pid){try{$.require('hanime').provider().updatePlaylist(pid,'','',true);back(true);return 'toast://已删除';}catch(e){return 'toast://'+String(e.message||e);}},id),'text_2'));d.push(H.sec('影片',p.items.length+' 部'));for(var i=0;i<p.items.length;i++)d.push(L.video(p.items[i],'library'));if(!p.items.length)d.push(H.sec('暂无影片','片单存在，但当前没有解析到影片卡片。'));setResult(d);}catch(x){setResult([{title:'片单加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
function choose(kind){return $('#noLoading#').lazyRule(function(k){putMyVar('hanime30_my_section',k);refreshPage(false);return 'hiker://empty';},kind);}
E.renderMy=function(d){var acc=C.activeAccount();if(!acc){d.push(H.sec('我的','登录后查看片单、收藏、稍后看、订阅和历史。'));d.push(H.btn('登录 Hanime1',H.route('hanimeLogin',{}),'text_center_1'));return;}d.push({title:acc.name||('用户 '+acc.id),desc:acc.email||('账号 ID '+acc.id),pic_url:acc.avatar||'',url:H.route('hanimeAccount',{}),col_type:'avatar',extra:{lineVisible:false}});var cur=getMyVar('hanime30_my_section','playlists'),tabs=[['片单','playlists'],['收藏','favorites'],['稍后看','watchLater'],['订阅','subscriptions'],['历史','history']];for(var i=0;i<tabs.length;i++)d.push({title:(cur===tabs[i][1]?'✓ ':'')+tabs[i][0],url:choose(tabs[i][1]),col_type:'scroll_button'});d.push({col_type:'line_blank'});try{var r=P.librarySection30(cur);if(cur==='playlists'){d.push(H.sec('我的片单',r.playlists.length+' 个'));for(var j=0;j<r.playlists.length;j++){var p=r.playlists[j];d.push({title:p.title,desc:p.count||'',pic_url:p.img||'',url:H.route('hanimePlaylist',{id:p.id}),col_type:'movie_1_left_pic',extra:{lineVisible:false}});}if(!r.playlists.length)d.push(H.sec('暂无片单'));}else{var labels={favorites:'收藏',watchLater:'稍后看',subscriptions:'订阅',history:'观看历史'},list=r.items||[];d.push(H.sec(labels[cur]||'账号内容',list.length+' 部'));for(var k=0;k<list.length;k++)d.push(L.video(list[k],'library'));if(!list.length)d.push(H.sec('暂无内容','当前栏目为空，或官网未返回可解析影片。'));}}catch(e){d.push(H.sec('账号内容加载失败',String(e.message||e)));d.push(H.btn('重新登录',H.route('hanimeLogin',{}),'text_center_1'));}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);