/* Hanime1 Test30 replies: exact reply-start child pairs + resilient fallback */
(function(C,P,E,H){
var PREFIX='hanime_reply_cache30_',TTL=60000;
function clean(v){return C.clean(String(v==null?'':v));}
function abs(base,u){u=String(u||'').replace(/&amp;/g,'&').trim();return u?C.abs(base,u):'';}
function nodes(html,sel){try{return pdfa(String(html||''),sel)||[];}catch(e){return [];}}
function text(node,sel){try{return clean(pdfh(node,sel)||'');}catch(e){return '';}}
function attr(node,sel){try{return String(pdfh(node,sel)||'').replace(/&amp;/g,'&').trim();}catch(e){return '';}}
function firstText(node,sels){for(var i=0;i<sels.length;i++){var v=text(node,sels[i]);if(v)return v;}return '';}
function firstAttr(node,sels){for(var i=0;i<sels.length;i++){var v=attr(node,sels[i]);if(v)return v;}return '';}
function jsonPart(body){try{var j=JSON.parse(String(body||''));if(j&&typeof j.replies==='string')return j.replies;}catch(e){}return String(body||'');}
function cacheKey(id){return PREFIX+String(id||'');}
function read(id){try{var r=getItem(cacheKey(id),'');if(!r)return null;var x=JSON.parse(r);if(!x||!Array.isArray(x.items)||!x.items.length||Date.now()-Number(x.ts||0)>TTL){clearItem(cacheKey(id));return null;}return x.items;}catch(e){return null;}}
function write(id,a){if(!a||!a.length)return;try{setItem(cacheKey(id),JSON.stringify({ts:Date.now(),items:a}));}catch(e){}}
function clear(id){try{clearItem(cacheKey(id));}catch(e){}}
function norm(x){x=x||{};x.user=String(x.user||'').replace(/\s+/g,' ').trim()||'匿名用户';x.time=String(x.time||'').replace(/\s+/g,' ').replace(/\s*[·•|]?\s*\d+\s*回(?:复|覆)[\s\S]*$/i,'').trim();return x;}
function parseDirect(body,base){var out=[],children=nodes(body,'div[id^=reply-start] > *');for(var i=0;i+1<children.length;i+=2){var b=children[i],f=nodes(b,'.comment-index-text');if(f.length<2)continue;var u=firstText(f[0],['a&&Text','Text']),c=text(f[1],'Text');if(!u||!c)continue;out.push(norm({user:u,content:c,time:firstText(f[0],['span&&Text']),avatar:abs(base,firstAttr(b,['img&&src','img&&data-src','img&&data-original']))}));}return out;}
function parseRows(body,base){var out=[],rows=nodes(body,'.comment-index-text');for(var i=0;i+1<rows.length;i+=2){var u=firstText(rows[i],['a&&Text','Text']),c=text(rows[i+1],'Text');if(!u||!c)continue;out.push(norm({user:u,content:c,time:firstText(rows[i],['span&&Text']),avatar:abs(base,firstAttr(rows[i],['img&&src','img&&data-src','img&&data-original']))}));}return out;}
P.replies=function(commentId){commentId=String(commentId||'');if(!commentId)throw new Error('缺少评论 ID');var cached=read(commentId);if(cached)return cached;var base=C.resolveHost(false),url=C.query(base+'/loadReplies',{id:commentId}),r=C.get(url,{base:base,referer:base+'/',timeout:12000});if(!r||r.challenge||Number(r.statusCode||0)>=400||!String(r.body||''))throw new Error('回复加载失败：HTTP '+Number((r&&r.statusCode)||0));var body=jsonPart(r.body),out=parseDirect(body,base);if(!out.length)out=parseRows('<div id="hanime-r30-wrap">'+body+'</div>',base);if(!out.length)out=parseRows(body,base);write(commentId,out);return out;};
var baseComments=P.comments;
function digits(v){var m=String(v||'').match(/\d+/);return m?parseInt(m[0],10)||0:0;}
function commentIdFrom(wrapper){var w=nodes(wrapper,'div[id^=reply-section-wrapper]');if(!w.length)return '';var id=firstAttr(w[0],['id']);return id?String(id).split('-').pop():'';}
function parseComments(body,base){var children=nodes(body,'#comment-start > *'),out=[];for(var i=0;i<children.length;i+=4){var g=children.slice(i,i+4);if(!g.length)continue;var wrap='<div>'+g.join('')+'</div>',f=nodes(wrap,'.comment-index-text');if(f.length<2)continue;var u=firstText(f[0],['a&&Text','Text']),c=text(f[1],'Text');if(!u||!c)continue;var rc=digits(firstText(wrap,['div.load-replies-btn&&Text','.load-replies-btn&&Text']));out.push({id:commentIdFrom(wrap),user:u,content:c,time:firstText(f[0],['span&&Text']),avatar:abs(base,firstAttr(wrap,['img&&src','img&&data-src','img&&data-original'])),replyCount:rc});}return out;}
P.comments=function(videoId){var base=C.resolveHost(false),url=C.query(base+'/loadComment',{type:'video',id:videoId});try{var r=C.get(url,{base:base,referer:base+'/watch?v='+videoId,timeout:14000});if(r&&!r.challenge&&Number(r.statusCode||0)<400&&String(r.body||'')){var raw=String(r.body||''),body=raw;try{var j=JSON.parse(raw);if(j&&typeof j.comments==='string')body=j.comments;}catch(e){}var items=parseComments(body,base);if(items.length)return {items:items,csrf:firstAttr(body,['input[name=_token]&&value']),userId:firstAttr(body,['input[name=comment-user-id]&&value'])};}}catch(e){}return baseComments(videoId);};
var baseReply=P.replyComment;P.replyComment=function(id,content){var r=baseReply(id,content);clear(id);return r;};P.clearReplyCache30=clear;
function logged(){try{return !!C.activeAccount();}catch(e){return false;}}
function compose(id,ok){return ok?('input://'+JSON.stringify({value:'',hint:'输入回复内容',js:"if(!input)return 'toast://回复不能为空';try{var p=$.require('hanime').provider();p.replyComment('"+id+"',input);if(p.clearReplyCache30)p.clearReplyCache30('"+id+"');refreshPage(false);return 'toast://回复已发布';}catch(e){return 'toast://'+String(e.message||e);}"})):H.route('hanimeLogin',{});}
E.repliesPage=function(){try{var id=H.pv('id',''),u=H.pv('user','回复'),a=P.replies(id),d=[],ok=logged();setPageTitle(u+' · 回复');d.push(H.sec(u,'共 '+a.length+' 条回复'));d.push(H.btn(ok?'回复此评论':'登录后回复',compose(id,ok),'text_center_1'));for(var i=0;i<a.length;i++){var x=a[i];d.push({title:x.user||'匿名用户',desc:x.time||'',pic_url:x.avatar||'',url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false}});d.push({title:x.content||'',url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false,textSize:16}});d.push({col_type:'line'});}if(!a.length)d.push(H.sec('暂未取得回复','不会缓存空结果；返回评论页后可再次打开。'));setResult(d);}catch(x){setResult([{title:'回复加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9);