/* Shared JAV Playback SDK 1.0.0-test.1 - Hiker ES5 runtime */
(function(global){
var SDK={
version:'1.0.0-test.1',managerUrl:'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/shared/jav-playback/manager.js',channel:'test',ua:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
providers:function(){return[{id:'missav',name:'MissAV',icon:'https://missav.ws/favicon.ico'},{id:'123av',name:'123AV',icon:'https://123av.com/favicon.ico'},{id:'jable',name:'Jable',icon:'https://jable.tv/favicon.ico'}];},
normalizeCode:function(code){var s=String(code||'').trim().toLowerCase().replace(/[＿_\s]+/g,'-'),fm=s.match(/fc2[^0-9]*(?:ppv[^0-9]*)?(\d+)/i);if(fm)return'fc2-ppv-'+fm[1];return s.replace(/--+/g,'-');},
origin:function(url){var m=String(url||'').match(/^(https?:\/\/[^\/]+)/i);return m?m[1]:'';},
cleanUrl:function(url){return String(url||'').replace(/\\u002[fF]/g,'/').replace(/\\\//g,'/').replace(/&amp;/g,'&').trim();},
hls:function(url,referer,origin){var u=this.cleanUrl(url);if(!u)return'';var hs=[];if(referer)hs.push('Referer@'+String(referer).replace(/;/g,'；；'));if(origin)hs.push('Origin@'+String(origin).replace(/;/g,'；；'));hs.push('User-Agent@'+this.ua.replace(/;/g,'；；'));return u+'#isVideo=true#;{'+hs.join('&&')+'}';},
html:function(url,referer,timeout){var h={'User-Agent':this.ua};if(referer)h.Referer=referer;return String(fetch(url,{headers:h,timeout:timeout||8000})||'');},
webHtml:function(url,referer){try{return String(fetchCodeByWebView(url,{headers:{'User-Agent':this.ua,'Referer':referer||this.origin(url)+'/'},timeout:12000})||'');}catch(e){return'';}},
findM3u8:function(text){var s=this.cleanUrl(text),m=s.match(/https?:\/\/[^\s"'<>]+?\.m3u8(?:\?[^\s"'<>]*)?/ig);return m&&m.length?m:[];},
absolute:function(base,u){u=this.cleanUrl(u);if(!u)return'';if(/^https?:\/\//i.test(u))return u;if(u.indexOf('//')===0)return'https:'+u;var o=this.origin(base);if(u.charAt(0)==='/')return o+u;return String(base).replace(/[^\/]*(?:\?.*)?$/,'')+u;},
highest:function(master,headers){var txt='';try{txt=String(fetch(master,{headers:headers||{},timeout:7500})||'');}catch(e){return master;}if(txt.indexOf('#EXT-X-STREAM-INF')<0)return master;var lines=txt.replace(/\r/g,'').split('\n'),best=null,i,j,inf,u,rm,bm,h,b;for(i=0;i<lines.length;i++){if(lines[i].indexOf('#EXT-X-STREAM-INF:')!==0)continue;inf=lines[i];j=i+1;while(j<lines.length&&(!String(lines[j]).trim()||String(lines[j]).trim().charAt(0)==='#'))j++;if(j>=lines.length)continue;u=this.absolute(master,String(lines[j]).trim());rm=inf.match(/RESOLUTION=\d+x(\d+)/i);bm=inf.match(/BANDWIDTH=(\d+)/i);h=rm?parseInt(rm[1],10):0;b=bm?parseInt(bm[1],10):0;if(!best||h>best.h||(h===best.h&&b>best.b))best={url:u,h:h,b:b};}return best&&best.url?best.url:master;},
missavVariants:function(code){var lc=this.normalizeCode(code),roots=['https://missav.ws/dm247/cn','https://missav.ws/cn','https://missav.ai/cn'];function defs(root){return[{name:'默认视频',url:root+'/'+lc},{name:'中文字幕',url:root+'/'+lc+'-chinese-subtitle'},{name:'无码流出',url:root+'/'+lc+'-uncensored-leak'},{name:'无码版',url:root+'/'+lc+'-uncensored'},{name:'流出版',url:root+'/'+lc+'-leaked'}];}function valid(html){var s=String(html||''),l=s.toLowerCase();if(s.length<500)return false;var hit=l.indexOf(lc)>=0||l.indexOf(lc.replace(/-/g,''))>=0,media=/m3u8|playlist|video|player|source/.test(l),bad=/(404|page not found|video not found|not found<\/title>)/i.test(l);return hit&&media&&!bad;}var ri,a,req,res,out,i;for(ri=0;ri<roots.length;ri++){a=defs(roots[ri]);req=[];for(i=0;i<a.length;i++)req.push({url:a[i].url,options:{headers:{'User-Agent':this.ua,'Referer':this.origin(roots[ri])+'/'},timeout:5200}});res=[];try{res=batchFetch(req)||[];}catch(e){res=[];}out=[];for(i=0;i<a.length;i++)if(valid(res[i]))out.push(a[i]);if(out.length)return out;}return[];},
resolveMissavVariant:function(item,code){var detail=String(item&&item.url||''),origin=this.origin(detail),headers={'User-Agent':this.ua,'Referer':detail,'Origin':origin};if(!detail)return'toast://MissAV 线路无效';try{var html=String(fetch(detail,{headers:headers,timeout:8500})||''),s=this.cleanUrl(html),master='',pm=html.match(/'m3u8([\s\S]*?)video/);if(pm){var pp=String(pm[1]||'').split('|').reverse();if(pp.length>=9)master=pp[1]+'://'+pp[2]+'.'+pp[3]+'/'+pp[4]+'-'+pp[5]+'-'+pp[6]+'-'+pp[7]+'-'+pp[8]+'/playlist.m3u8';}if(!master){var ms=this.findM3u8(s);if(ms.length)master=ms[0];}if(!master){var wh=this.webHtml(detail,origin+'/'),wm=this.findM3u8(wh);if(wm.length)master=wm[0];}if(!master)return'video://'+detail;return this.hls(this.highest(master,headers),detail,origin);}catch(e){return'video://'+detail;}},
resolveMissav:function(code){var items=this.missavVariants(code),manager=this.managerUrl,channel=this.channel;if(!items.length)return'toast://MissAV 暂无该番号视频';return $(items.map(function(x){return x.name;}),1,'MissAV').select(function(items,code,manager,channel){var i=-1,j;for(j=0;j<items.length;j++)if(items[j].name===input){i=j;break;}if(i<0)return'hiker://empty';eval(fetch(manager,{timeout:10000,headers:{'Cache-Control':'no-cache'}}));var sdk=JAVPlaybackManager.load(channel);return sdk.resolveMissavVariant(items[i],code);},items,code,manager,channel);},
decodePlayerObject:function(html){var s=String(html||''),m=s.match(/JSON\.parse\(\s*'((?:\\.|[^'])*)'\s*\)/i);if(!m)m=s.match(/JSON\.parse\(\s*"((?:\\.|[^"])*)"\s*\)/i);if(!m)return null;var raw=String(m[1]||'');raw=raw.replace(/\\u([0-9a-fA-F]{4})/g,function(_,h){return String.fromCharCode(parseInt(h,16));}).replace(/\\\//g,'/').replace(/\\"/g,'"').replace(/\\'/g,"'");try{return JSON.parse(raw);}catch(e1){try{return JSON.parse(raw.replace(/\\/g,''));}catch(e2){return null;}}},
urlsFromObject:function(obj){var text='';try{text=JSON.stringify(obj||{});}catch(e){}return this.findM3u8(text);},
parse123Player:function(html){var obj=this.decodePlayerObject(html),urls=obj?this.urlsFromObject(obj):[];return urls.length?urls:this.findM3u8(html);},
find123Detail:function(code){var lc=this.normalizeCode(code),langs=['zh','cn','en'],suffix=['-uncensored-leaked',''],i,j,url,h;for(i=0;i<langs.length;i++)for(j=0;j<suffix.length;j++){url='https://123av.com/'+langs[i]+'/v/'+lc+suffix[j];try{h=this.html(url,'https://123av.com/',6500);if(h&&h.length>500&&!/(404|not found|请检查地址栏中的URL)/i.test(h))return{url:url,html:h,lang:langs[i]};}catch(e){}}for(i=0;i<langs.length;i++){url='https://123av.com/'+langs[i]+'/search?keyword='+encodeURIComponent(lc);try{h=this.html(url,'https://123av.com/',6500);var re=/href=["']([^"']*\/v\/[^"']+)["']/ig,m;while((m=re.exec(h))){var du=this.absolute(url,m[1]);if(String(du).toLowerCase().indexOf(lc)>=0){return{url:du,html:this.html(du,url,6500),lang:langs[i]};}}}catch(e2){}}return null;},
follow123Continue:function(detail){var h=String(detail.html||'');if(!/click here to continue/i.test(h))return detail;var m=h.match(/href=["']([^"']+)["']/i);if(!m)return detail;var u=this.absolute(detail.url,m[1]);try{return{url:u,html:this.html(u,detail.url,6500),lang:detail.lang};}catch(e){return detail;}},
resolve123:function(code){var detail=this.find123Detail(code);if(!detail)return'toast://123AV 暂无该番号视频';detail=this.follow123Continue(detail);var direct=this.parse123Player(detail.html),i,playPages=[],names=[],headers=[],urls=[];if(direct.length){for(i=0;i<direct.length;i++){urls.push(this.cleanUrl(direct[i]));names.push('线路'+(i+1));headers.push({Referer:detail.url,'User-Agent':this.ua});}return this.playlistOrOne(urls,names,headers);}var idm=String(detail.html||'').match(/(?:\bid\b|videoId|video_id)\s*[:=]\s*["']?(\d{2,})/i);if(!idm)idm=String(detail.html||'').match(/v-scope[^>]*[^\n]{0,500}?id\s*:\s*(\d+)/i);if(idm){try{var ajax='https://123av.com/'+(detail.lang||'zh')+'/ajax/v/'+idm[1]+'/videos',raw=String(fetch(ajax,{headers:{'User-Agent':this.ua,'Referer':detail.url,'Accept':'application/json'},timeout:7500})||''),j=JSON.parse(raw),watch=j&&j.result&&j.result.watch||[];for(i=0;i<watch.length;i++)if(watch[i]&&watch[i].url)playPages.push(String(watch[i].url));}catch(e3){}}for(i=0;i<playPages.length;i++){try{var ph=this.html(playPages[i],detail.url,7500),pu=this.parse123Player(ph),k;for(k=0;k<pu.length;k++){urls.push(this.cleanUrl(pu[k]));names.push('线路'+(urls.length));var ref=this.origin(playPages[i]);if(/javplayer\.me/i.test(playPages[i]))ref='https://javplayer.me';headers.push({Referer:ref+'/' ,'User-Agent':this.ua});}}catch(e4){}}if(urls.length)return this.playlistOrOne(urls,names,headers);return'video://'+detail.url;},
playlistOrOne:function(urls,names,headers){var clean=[],cn=[],ch=[],seen={},i,u;for(i=0;i<urls.length;i++){u=this.cleanUrl(urls[i]);if(!u||seen[u])continue;seen[u]=1;clean.push(u+'#isVideo=true#');cn.push(names[i]||('线路'+clean.length));ch.push(headers[i]||{});}if(!clean.length)return'';if(clean.length===1){var h=ch[0]||{};return this.hls(clean[0].replace('#isVideo=true#',''),h.Referer||'',h.Origin||'');}return JSON.stringify({urls:clean,names:cn,headers:ch});},
resolveJable:function(code){var lc=this.normalizeCode(code).replace(/^fc2-ppv-/,'fc2ppv-'),detail='https://jable.tv/videos/'+lc+'/',h,urls;try{h=this.html(detail,'https://jable.tv/',8000);urls=this.findM3u8(h);if(urls.length)return this.hls(urls[0],detail,this.origin(detail));}catch(e){}h=this.webHtml(detail,'https://jable.tv/');urls=this.findM3u8(h);if(urls.length)return this.hls(urls[0],detail,this.origin(detail));return'video://'+detail;},
resolve:function(id,code){id=String(id||'').toLowerCase();if(!code)return'toast://缺少番号';if(id==='missav')return this.resolveMissav(code);if(id==='123av')return this.resolve123(code);if(id==='jable')return this.resolveJable(code);return'toast://未知播放站点';},
providerUrl:function(id,code){var manager=this.managerUrl,channel=this.channel;return $('#noLoading#').lazyRule(function(manager,channel,id,code){try{eval(fetch(manager,{timeout:10000,headers:{'Cache-Control':'no-cache'}}));var sdk=JAVPlaybackManager.load(channel);return sdk.resolve(id,code);}catch(e){return'toast://'+id+' 解析失败：'+String(e.message||e);}},manager,channel,id,code);},
renderInto:function(d,opt){opt=opt||{};var code=String(opt.code||'').trim().toUpperCase(),ps=this.providers(),i,p;for(i=0;i<ps.length;i++){p=ps[i];d.push({title:p.name,pic_url:p.icon,img:p.icon,url:this.providerUrl(p.id,code),col_type:'icon_1_left_pic',extra:{lineVisible:false,pageTitle:p.name+' · '+code}});}}
};
global.JAVPlayback=SDK;if(typeof $!=='undefined')$.exports=SDK;
})(this);
