/* Hanime1 Test40 performance: break profile recursion, stale-first account cache, one-request account sections */
(function(C,P,E,H,L){
var oldProfile=P.profile,oldActive=C.activeAccount,oldSection=P.librarySection30,oldAccountPage=E.accountPage;
var PROFILE_KEY='hanime40_profile',PROFILE_TTL=180000,LIB_PREFIX='hanime40_lib_',LIB_TTL=90000,activeGuard=false;
function clean(v){var s=String(v==null?'':v).trim();if(!s||s==='null'||s==='undefined')return '';try{s=C.clean(s);}catch(e){}s=String(s==null?'':s).trim();return (s==='null'||s==='undefined')?'':s;}
function nodes(h,s){try{return pdfa(String(h||''),s)||[];}catch(e){return [];}}
function text(n,s){try{return clean(pdfh(n,s)||'');}catch(e){return '';}}
function attr(n,s){try{var v=String(pdfh(n,s)||'').replace(/&amp;/g,'&').trim();return (v==='null'||v==='undefined')?'':v;}catch(e){return '';}}
function firstText(n,a){for(var i=0;i<a.length;i++){var v=text(n,a[i]);if(v)return v;}return '';}
function firstAttr(n,a){for(var i=0;i<a.length;i++){var v=attr(n,a[i]);if(v)return v;}return '';}
function abs(base,u){u=String(u||'').replace(/&amp;/g,'&').trim();return u?C.abs(base,u):'';}
function decodeHtml(s){return String(s||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
function strip(s){return clean(decodeHtml(String(s||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' '));}
function pid(u){var m=String(u||'').match(/[?&]list=([^&"']+)/);if(!m)return '';try{return decodeURIComponent(m[1]);}catch(e){return m[1];}}
function readPack(k){try{return JSON.parse(getItem(k,'')||'null');}catch(e){return null;}}
function readProfileAny(){var x=readPack(PROFILE_KEY);if(x&&x.data&&x.data.id)return x.data;x=readPack('hanime39_profile');if(x&&x.data&&x.data.id)return x.data;x=readPack('hanime38_profile_cache');if(x&&x.item&&x.item.id)return x.item;return null;}
function writeProfile(p){if(!p||!p.id)return;try{setItem(PROFILE_KEY,JSON.stringify({ts:Date.now(),data:p}));}catch(e){}}
function profileFresh(){var x=readPack(PROFILE_KEY);return !!(x&&x.ts&&x.data&&x.data.id&&Date.now()-Number(x.ts)<PROFILE_TTL);}
function mergeProfile(a,b){a=a||{};b=b||{};return {id:clean(b.id||a.id),name:clean(b.name||a.name),email:clean(b.email||a.email),avatar:clean(b.avatar||b.avatarUrl||a.avatar||a.avatarUrl),csrf:clean(b.csrf||a.csrf),joined:clean(b.joined||a.joined),cookie:b.cookie||a.cookie||'',base:clean(b.base||a.base)||C.resolveHost(false),browserSession:true};}
function homeProfile(){var old=readProfileAny()||{},base=clean(old.base)||C.resolveHost(false),r=C.get(base+'/',{base:base,referer:base+'/',timeout:6500});if(!r||r.challenge||Number(r.statusCode||0)>=400||!String(r.body||''))return old;var h=String(r.body||''),href=firstAttr(h,['#user-modal-trigger&&href','a[href*="/user/"]&&href']),m=String(href||'').match(/\/user\/(\d+)/),id=m?m[1]:clean(old.id),name=firstText(h,['#user-modal-name&&Text','.profile-display-name&&Text']),avatar=abs(base,firstAttr(h,['#user-modal-dp-wrapper img&&src','.profile-avatar-wrapper img&&src','.profile-avatar-wrapper img&&data-src'])),joined=firstText(h,['#user-modal-created&&Text']);var p=mergeProfile(old,{id:id,name:name,avatar:avatar,joined:joined,base:base});if(p.id)writeProfile(p);return p;}
function fullProfile(force){var p=readProfileAny()||{};if((!p.id||force)&&!profileFresh())p=homeProfile()||p;if(!p||!p.id)return p;var base=clean(p.base)||C.resolveHost(false);try{var r=C.get(base+'/user/'+p.id+'/edit',{base:base,referer:base+'/',timeout:6500}),h=String(r&&r.body||'');if(r&&!r.challenge&&Number(r.statusCode||0)<400&&h){p=mergeProfile(p,{name:firstAttr(h,['input[name=name]&&value'])||p.name,email:firstAttr(h,['input[name=email]&&value'])||p.email,avatar:abs(base,firstAttr(h,['img#playlist-avatar&&src','img#playlist-avatar&&data-src','img#playlist-avatar&&data-original']))||p.avatar,csrf:firstAttr(h,['meta[name=csrf-token]&&content','input[name=_token]&&value'])||p.csrf,base:base});writeProfile(p);}}catch(e){}return p;}
P.profile=function(){return readProfileAny();};
P.profile40Refresh=function(force){if(force)try{clearItem(PROFILE_KEY);}catch(e){}var p=homeProfile();if(p&&p.id&&force)p=fullProfile(true);return p;};
C.activeAccount=function(){var c=readProfileAny();if(c&&c.id)return c;if(activeGuard)return null;activeGuard=true;try{var a=oldActive?oldActive():null;if(a&&a.id){writeProfile(mergeProfile(c,a));return mergeProfile(c,a);}return null;}catch(e){return null;}finally{activeGuard=false;}};
function cacheRead(k){var x=readPack(LIB_PREFIX+k);if(x&&x.ts&&x.data&&Date.now()-Number(x.ts)<LIB_TTL)return x.data;return null;}
function cacheWrite(k,v){try{setItem(LIB_PREFIX+k,JSON.stringify({ts:Date.now(),data:v}));}catch(e){}}
function fetchPath(path){var p=readProfileAny();if(!p||!p.id)p=homeProfile();if(!p||!p.id)throw new Error('未检测到已登录账号');var base=clean(p.base)||C.resolveHost(false),r=C.get(base+path,{base:base,referer:base+'/',timeout:7500});if(!r||r.challenge||Number(r.statusCode||0)>=400)throw new Error('账号内容加载失败：HTTP '+Number((r&&r.statusCode)||0));return {base:base,html:String(r.body||''),profile:p};}
function segmentForLink(src,pos){var candidates=['user-tab-item-wrapper','playlist-item-wrapper','playlist-card'];var best=-1;for(var i=0;i<candidates.length;i++){var cp=src.lastIndexOf(candidates[i],pos);if(cp>best&&pos-cp<7000)best=cp;}var start=best>=0?src.lastIndexOf('<',best):Math.max(0,pos-3500);if(start<0)start=Math.max(0,pos-3500);var next=src.length;for(var j=0;j<candidates.length;j++){var np=src.indexOf(candidates[j],pos+1);if(np>pos&&np<next){var tag=src.lastIndexOf('<',np);if(tag>pos)next=tag;}}if(next===src.length)next=Math.min(src.length,pos+7000);return src.slice(start,next);}
function playlistCardsFast(h,base){var out=[],seen={},allIds={},sels=['.user-tab-item-wrapper','.playlist-item-wrapper','.playlist-card'];for(var s=0;s<sels.length;s++){var a=nodes(h,sels[s]);for(var i=0;i<a.length;i++){var href=firstAttr(a[i],['a.video-link&&href','a[href*=playlist]&&href','a&&href']),id=pid(href);if(!id)continue;allIds[id]=1;var title=firstText(a[i],['.title&&Text','.playlist-title&&Text','img&&alt']),img=abs(base,firstAttr(a[i],['img.main-thumb&&src','img&&src','img&&data-src'])),count=firstText(a[i],['.stat-item&&Text','.playlist-count&&Text']);if(title&&!seen[id]){seen[id]=1;out.push({id:id,title:title,count:count,img:img});}}}
var src=String(h||''),re=/(?:href|data-href)\s*=\s*(["'])([^"']*playlist\?[^"']*list=[^"']+)\1/gi,m;while((m=re.exec(src))!==null){var href2=decodeHtml(m[2]),id2=pid(href2);if(!id2)continue;allIds[id2]=1;if(seen[id2])continue;var seg=segmentForLink(src,m.index),title='',img='',count='';var tm=seg.match(/class\s*=\s*(["'])[^"']*(?:playlist-title|(?:^|\s)title(?:\s|$)|card-mobile-title)[^"']*\1[^>]*>([\s\S]*?)<\//i);if(tm)title=strip(tm[2]);if(!title){var alt=seg.match(/<img\b[^>]*\balt\s*=\s*(["'])([^"']+)\1/i);if(alt)title=clean(decodeHtml(alt[2]));}if(!title){var ar=seg.match(/<a\b[^>]*(?:href|data-href)\s*=\s*(["'])[^"']*playlist\?[^"']*list=[^"']+\1[^>]*(?:title|aria-label)\s*=\s*(["'])([^"']+)\2/i);if(ar)title=clean(decodeHtml(ar[3]));}var im=seg.match(/<img\b[^>]*(?:data-src|src)\s*=\s*(["'])([^"']+)\1/i);if(im)img=abs(base,decodeHtml(im[2]));var cm=seg.match(/class\s*=\s*(["'])[^"']*(?:playlist-count|stat-item)[^"']*\1[^>]*>([\s\S]*?)<\//i);if(cm)count=strip(cm[2]);if(title){seen[id2]=1;out.push({id:id2,title:title,count:count,img:img});}}
var total=0;for(var k in allIds)if(allIds.hasOwnProperty(k))total++;return {playlists:out,items:[],totalIds:total,pending:Math.max(0,total-out.length)};}
function playlistSection(){var c=cacheRead('playlists');if(c)return c;var p=readProfileAny();if(!p||!p.id)p=homeProfile();if(!p||!p.id)throw new Error('请先登录');var x=fetchPath('/user/'+p.id+'/playlists'),r=playlistCardsFast(x.html,x.base);cacheWrite('playlists',r);return r;}
P.librarySection30=function(kind){kind=String(kind||'playlists');var c=cacheRead(kind);if(c)return c;if(kind==='playlists')return playlistSection();var r=oldSection(kind);cacheWrite(kind,r);return r;};
P.completePlaylists40=function(){try{clearItem(LIB_PREFIX+'playlists');}catch(e){}var r=oldSection('playlists');cacheWrite('playlists',r);return r;};
P.clearAccountCache40=function(){try{clearItem(PROFILE_KEY);clearItem(LIB_PREFIX+'playlists');clearItem(LIB_PREFIX+'favorites');clearItem(LIB_PREFIX+'watchLater');clearItem(LIB_PREFIX+'subscriptions');clearItem(LIB_PREFIX+'history');}catch(e){}};
function choose(k){return $('#noLoading#').lazyRule(function(v){putMyVar('hanime39_my_section',v);refreshPage(false);return 'hiker://empty';},k);}
function syncAction(){return $('#noLoading#').lazyRule(function(){try{var p=$.require('hanime').provider();if(p.clearAccountCache40)p.clearAccountCache40();p.profile40Refresh(true);refreshPage(false);return 'toast://账号资料已同步';}catch(e){return 'toast://'+String(e.message||e);}});}
function completeAction(){return $('#noLoading#').lazyRule(function(){try{$.require('hanime').provider().completePlaylists40();refreshPage(false);return 'toast://片单资料已补全';}catch(e){return 'toast://'+String(e.message||e);}});}
function tabs(d,cur){var a=[['片单','playlists'],['收藏','favorites'],['稍后看','watchLater'],['订阅','subscriptions'],['历史','history']];for(var i=0;i<a.length;i++)d.push({title:(cur===a[i][1]?'✓ ':'')+a[i][0],url:choose(a[i][1]),col_type:'text_3',extra:{lineVisible:false}});d.push({title:'账号中心',url:H.route('hanimeAccount',{}),col_type:'text_3',extra:{lineVisible:false}});d.push({col_type:'line_blank'});}
function renderSection(d,cur){var r=P.librarySection30(cur);if(cur==='playlists'){d.push(H.sec('我的片单',(r.playlists||[]).length+' 个'+(r.totalIds&&r.totalIds>(r.playlists||[]).length?(' · 官网检测 '+r.totalIds+' 个'):'')));for(var i=0;i<(r.playlists||[]).length;i++){var p=r.playlists[i];d.push({title:p.title,desc:p.count?('共 '+p.count+' 部'):'查看片单',pic_url:p.img||'',url:H.route('hanimePlaylist',{id:p.id}),col_type:'movie_1_left_pic',extra:{lineVisible:false}});}if(r.pending>0){d.push(H.sec('还有 '+r.pending+' 个片单名称未解析','为避免打开“我的”时逐个联网阻塞，默认不自动串行请求。'));d.push(H.btn('补全片单资料',completeAction(),'text_center_1'));}if(!(r.playlists||[]).length&&!r.pending)d.push(H.sec('暂无片单','官网当前没有返回可解析片单。'));return;}var names={favorites:'收藏',watchLater:'稍后看',subscriptions:'订阅',history:'观看历史'},list=r.items||[];d.push(H.sec(names[cur]||'账号内容',list.length+' 部'));for(var j=0;j<list.length;j++)d.push(L.video(list[j],'library'));if(!list.length)d.push(H.sec('暂无内容','官网当前没有返回可解析影片，或该栏目为空。'));}
E.renderMy=function(d){var p=P.profile();if(!p||!p.id){try{p=homeProfile();}catch(e){}}if(!p||!p.id){d.push(H.sec('我的','检测到网页登录后会在这里显示账号内容。'));d.push(H.btn('同步网页登录',syncAction(),'text_2'));d.push(H.btn('登录 Hanime1',H.route('hanimeLogin',{}),'text_2'));return;}d.push({title:p.name||('用户 '+p.id),desc:[p.email,p.id?('ID '+p.id):''].filter(Boolean).join(' · '),pic_url:p.avatar?(p.avatar+'@Referer='+(p.base||C.resolveHost(false))+'/'):'',url:H.route('hanimeAccount',{}),col_type:'avatar',extra:{lineVisible:false}});var cur=getMyVar('hanime39_my_section','playlists');tabs(d,cur);try{renderSection(d,cur);}catch(e){d.push(H.sec('账号内容加载失败',String(e.message||e)));}d.push(H.btn('同步账号资料',syncAction(),'text_center_1'));};
E.accountPage=function(){try{fullProfile(false);}catch(e){}return oldAccountPage();};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);
