/* 色花堂 0.1.0-test.4 / Build 10104 - forum product recovery patch */
var SeHuaTangPatchTest4 = (function () {
    var BASE = SeHuaTangRemoteRuntime;
    var VERSION = '0.1.0-test.4', BUILD = 10104, RULE_NAME = '色花堂';
    var DEFAULT_ORIGIN = 'https://sehuatang.org';
    var UA = 'Mozilla/5.0 (Linux; Android 13; zh-CN) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Mobile Safari/537.36';
    var KEY_ORIGIN = 'sht_origin_v1', KEY_DIAG = 'sht_diag_v1', KEY_FORUM_CACHE = 'sht_forum_cache_v4';
    var LOGO = 'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/aggregate/sehuatang/assets/v1/logo.svg';

    function s(v){return v==null?'':String(v)}
    function trim(v){return s(v).replace(/^\s+|\s+$/g,'')}
    function dec(v){v=s(v);try{return decodeURIComponent(v)}catch(e){return v}}
    function hdec(v){var x=s(v),i;for(i=0;i<2;i++)x=x.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;/gi,' ').replace(/&#(\d+);/g,function(_,n){try{return String.fromCharCode(Number(n))}catch(e){return _}});return x}
    function strip(v){return trim(hdec(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/\s+/g,' '))}
    function origin(){var o=trim(getItem(KEY_ORIGIN,DEFAULT_ORIGIN));return /^https?:\/\//i.test(o)?o.replace(/\/+$/,''):DEFAULT_ORIGIN}
    function originOf(u){var m=s(u).match(/^(https?:\/\/[^\/]+)/i);return m?m[1]:origin()}
    function abs(h,b){h=hdec(trim(h));if(!h)return'';if(/^https?:\/\//i.test(h))return h;if(/^\/\//.test(h))return'https:'+h;if(/^(javascript:|mailto:|tel:|#)/i.test(h))return'';var o=(s(b).match(/^(https?:\/\/[^\/]+)/i)||[])[1]||origin();if(h.charAt(0)==='/')return o+h;var c=s(b).split('#')[0].split('?')[0];if(c.charAt(c.length-1)!=='/')c=c.replace(/\/[^\/]*$/,'/');return c+h.replace(/^\.\//,'')}
    function addMobile(u){u=s(u);if(!u||/[?&]mobile=(?:\d+|yes|no)(?:&|$)/i.test(u))return u;return u+(u.indexOf('?')>=0?'&':'?')+'mobile=2'}
    function pageParam(n,d){var u=s(typeof MY_URL==='undefined'?'':MY_URL),m=u.match(new RegExp('[?&]'+n+'=([^&#]*)'));return m?dec(m[1]):(d==null?'':d)}
    function headers(u){var o=originOf(u),c='';try{c=getCookie(o)||''}catch(e){}var h={'User-Agent':UA,'Referer':o+'/'};if(c)h.Cookie=c;return h}
    function saveDiag(stage,u,msg){try{setItem(KEY_DIAG,JSON.stringify({stage:stage,origin:originOf(u),error:s(msg||'').slice(0,420),time:new Date().getTime()}))}catch(e){}}
    function titleOf(html){var m=s(html).match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?strip(m[1]).slice(0,90):''}
    function req(u){try{return s(fetch(u,{headers:headers(u),timeout:10000}))}catch(e){return''}}
    function rendered(u){try{return s(fetchCodeByWebView(u,{headers:headers(u),timeout:18000,blockRules:['.mp4','.m3u8','.woff','.woff2','.ttf'],checkJs:$.toString(function(){var body=document.body&&document.body.innerText?document.body.innerText.length:0;return body>600?'ready':null;})}))}catch(e){return''}}
    function anchors(html,base){var out=[],re=/<a\b([^>]*?)href\s*=\s*(?:["']([^"']+)["']|([^\s>]+))([^>]*)>([\s\S]*?)<\/a>/gi,m,a,t,tm;while((m=re.exec(s(html)))!==null){a=(m[1]||'')+' '+(m[4]||'');t=strip(m[5]||'');if(!t){tm=a.match(/\b(?:title|aria-label)\s*=\s*["']([^"']+)["']/i);if(tm)t=strip(tm[1])}out.push({href:abs(m[2]||m[3]||'',base),text:t,attrs:a,inner:m[5]||'',index:m.index});if(out.length>12000)break}return out}
    function imgFrom(v,base){var x=s(v),m=x.match(/<img\b[^>]*?(?:data-original|data-src|zoomfile|file|src)\s*=\s*["']([^"']+)["']/i);if(!m)return'';var u=abs(m[1],base);if(!u||/avatar\.php|noavatar|smiley|loading|logo|static\/image\/common/i.test(u))return'';return u}
    function forumId(u){var m=s(u).match(/[?&]fid=(\d+)/i)||s(u).match(/\/forum-(\d+)-\d+\.html/i);return m?m[1]:''}
    function threadId(u){var x=hdec(s(u)),m=x.match(/[?&]tid=(\d+)/i)||x.match(/[?&]ptid=(\d+)/i)||x.match(/\/thread-(\d+)-\d+-\d+\.html/i);return m?m[1]:''}
    function isForum(u){return !!forumId(u) && (/forum\.php\?/i.test(s(u))||/\/forum-\d+-\d+\.html/i.test(s(u)))}
    function isThread(u){return !!threadId(u) && (/forum\.php\?/i.test(s(u))||/\/thread-\d+-\d+-\d+\.html/i.test(s(u)))}
    function normalizeThread(u){var id=threadId(u);if(!id)return addMobile(u);if(/[?&]ptid=\d+/i.test(u)&&!/[?&]tid=\d+/i.test(u))return originOf(u)+'/forum.php?mod=viewthread&tid='+id+'&mobile=2';return addMobile(u)}
    function badForumText(t){return !t||/^(首页|论坛|返回|更多|发帖|登录|注册|话题|板块|搜索)$/i.test(t)}
    function forumScore(t){t=trim(t);if(badForumText(t))return-999;var n=Math.min(t.length,24);if(/原创|字幕|写真|视频|收藏|图片|文学|讨论|无码|有码|国产|三级/.test(t))n+=20;if(t.length>=4)n+=8;return n}
    function parseForums(html,base){var a=anchors(html,base),map={},order=[],i,x,id,t,sc,k,out=[];for(i=0;i<a.length;i++){x=a[i];if(!isForum(x.href))continue;id=forumId(x.href);if(!id)continue;t=trim(x.text);sc=forumScore(t);if(sc<0)continue;if(!map[id]){map[id]={id:id,title:t,url:addMobile(x.href),score:sc};order.push(id)}else if(sc>map[id].score){map[id].title=t;map[id].url=addMobile(x.href);map[id].score=sc}}for(i=0;i<order.length;i++){k=order[i];if(map[k])out.push({id:k,title:map[k].title,url:map[k].url})}return{items:out.slice(0,80),anchors:a.length}}
    function badThreadText(t){t=trim(t);if(!t||t.length<2)return true;if(/^(回复|查看|查看帖子|查看全部|最后发表|最后回复|上一页|下一页|返回|详情|进入|播放)$/i.test(t))return true;if(/^\d{1,2}:\d{2}(?::\d{2})?$/.test(t))return true;if(/^\d{4}[-/.]\d{1,2}[-/.]\d{1,2}$/.test(t))return true;if(/^\d+$/.test(t))return true;return false}
    function threadScore(t){t=trim(t);if(badThreadText(t))return-999;var n=Math.min(t.length,120);if(/[\u4e00-\u9fffA-Za-z]{2,}/.test(t))n+=35;if(t.length>=8)n+=20;if(t.length>100)n-=20;if(/^(作者|回复|浏览|查看|发表于)/.test(t))n-=30;return n}
    function parseThreads(html,base){var a=anchors(html,base),map={},order=[],i,x,id,t,sc,pic,out=[];for(i=0;i<a.length;i++){x=a[i];if(!isThread(x.href))continue;id=threadId(x.href);if(!id)continue;t=trim(x.text);sc=threadScore(t);pic=imgFrom(x.inner,base);if(!map[id]){map[id]={id:id,title:sc>-900?t:'',url:normalizeThread(x.href),score:sc,img:pic};order.push(id)}else{if(sc>map[id].score){map[id].title=t;map[id].score=sc;map[id].url=normalizeThread(x.href)}if(!map[id].img&&pic)map[id].img=pic}}for(i=0;i<order.length;i++){id=order[i];x=map[id];if(!x||badThreadText(x.title))continue;out.push({id:id,title:x.title.slice(0,150),url:x.url,img:x.img||''});if(out.length>=100)break}return{items:out,anchors:a.length}}
    function route(path,p){var u='hiker://page/'+path+'?rule='+RULE_NAME+'&simple=true',k;for(k in(p||{}))if(p.hasOwnProperty(k)&&p[k]!=null)u+='&'+k+'='+encodeURIComponent(s(p[k]));return u}
    function section(t,d){return{title:t,desc:d||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}}}
    function line(){return{col_type:'line'}}
    function empty(t,d){return{title:t,desc:d||'',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}}}
    function web(u){return'x5://'+addMobile(u)}
    function quick(t,u){return{title:t,img:LOGO,url:u,col_type:'icon_small_4',extra:{lineVisible:false}}}
    function withPage(u,p){p=Math.max(1,Number(p||1));u=s(u);if(/\/forum-\d+-\d+\.html(?:\?|$)/i.test(u))return u.replace(/\/forum-(\d+)-\d+\.html/i,'/forum-$1-'+p+'.html');if(/([?&])page=\d+/i.test(u))return u.replace(/([?&])page=\d+/i,'$1page='+p);return u+(u.indexOf('?')>=0?'&':'?')+'page='+p}
    function pcVariant(u){u=s(u);if(/[?&]mobile=2(?:&|$)/i.test(u))return u.replace(/([?&])mobile=2(?:&|$)/i,function(_,p){return p+'mobile=no&'}).replace(/&$/,'');return u+(u.indexOf('?')>=0?'&':'?')+'mobile=no'}
    function cacheRead(){try{var x=JSON.parse(getItem(KEY_FORUM_CACHE,'{}')||'{}');if(x.items&&x.items.length&&new Date().getTime()-Number(x.time||0)<21600000)return x.items}catch(e){}return[]}
    function cacheWrite(a){try{if(a&&a.length)setItem(KEY_FORUM_CACHE,JSON.stringify({time:new Date().getTime(),items:a.slice(0,80)}))}catch(e){}}
    function resolveForums(){var c=cacheRead(),o=origin(),urls=[o+'/forum.php?mobile=2',o+'/forum.php?mobile=no',o+'/portal.php?mod=index&mobile=2'],i,u,h,p,steps=[];if(c.length)return{items:c,source:'cache',diag:'cache:'+c.length};for(i=0;i<urls.length;i++){u=urls[i];h=req(u);p=parseForums(h,u);steps.push('fetch'+(i+1)+':'+h.length+'字/'+p.items.length+'板块');if(p.items.length>=5){cacheWrite(p.items);return{items:p.items,source:'fetch',diag:steps.join('；')}}h=rendered(u);p=parseForums(h,u);steps.push('webview'+(i+1)+':'+h.length+'字/'+p.items.length+'板块');if(p.items.length>=5){cacheWrite(p.items);return{items:p.items,source:'webview',diag:steps.join('；')}}}return{items:[],source:'none',diag:steps.join('；')}}
    function findAnchorByText(html,base,words){var a=anchors(html,base),i,j,t;for(i=0;i<a.length;i++){t=trim(a[i].text);for(j=0;j<words.length;j++)if(t===words[j]||t.indexOf(words[j])>=0)return a[i].href}return''}
    function guideWords(kind){if(kind==='latest')return['最新发表','最新主题'];if(kind==='hot')return['最新热门','热门主题'];if(kind==='digest')return['最新精华','精华主题'];if(kind==='mine')return['我的话题'];return[]}
    function guideFallback(kind){var o=origin();if(kind==='latest')return o+'/forum.php?mod=guide&view=newthread&mobile=2';if(kind==='hot')return o+'/forum.php?mod=guide&view=hot&mobile=2';if(kind==='digest')return o+'/forum.php?mod=guide&view=digest&mobile=2';return o+'/forum.php?mobile=2'}
    function discoverGuide(kind){var o=origin(),u=o+'/forum.php?mobile=2',h=req(u),href=findAnchorByText(h,u,guideWords(kind));if(href)return{url:addMobile(href),source:'forum-fetch'};h=rendered(u);href=findAnchorByText(h,u,guideWords(kind));if(href)return{url:addMobile(href),source:'forum-webview'};return{url:guideFallback(kind),source:'fallback'}}
    function loadThreadList(seed,pg){var u=withPage(seed,pg),h,p,steps=[],alt;h=req(u);p=parseThreads(h,u);steps.push('fetch:'+h.length+'字/'+p.anchors+'链接/'+p.items.length+'主题'+(titleOf(h)?'/'+titleOf(h):''));if(p.items.length)return{items:p.items,source:'fetch',url:u,diag:steps.join('；')};h=rendered(u);p=parseThreads(h,u);steps.push('webview:'+h.length+'字/'+p.anchors+'链接/'+p.items.length+'主题'+(titleOf(h)?'/'+titleOf(h):''));if(p.items.length)return{items:p.items,source:'webview',url:u,diag:steps.join('；')};alt=pcVariant(u);if(alt!==u){h=req(alt);p=parseThreads(h,alt);steps.push('pc-fetch:'+h.length+'字/'+p.anchors+'链接/'+p.items.length+'主题');if(p.items.length)return{items:p.items,source:'pc-fetch',url:alt,diag:steps.join('；')};h=rendered(alt);p=parseThreads(h,alt);steps.push('pc-webview:'+h.length+'字/'+p.anchors+'链接/'+p.items.length+'主题');if(p.items.length)return{items:p.items,source:'pc-webview',url:alt,diag:steps.join('；')}}return{items:[],source:'none',url:u,diag:steps.join('；')}}
    function home(){var d=[],o=origin(),r,fs,i;setPageTitle('色花堂');d.push({title:'搜索主题',desc:'搜索',col_type:'input',url:"(function(){var w=String(input||'').trim();if(!w)return 'toast://请输入关键词';putMyVar('sht_search_kw_v1',w);return 'hiker://page/shtSearch?rule=色花堂&simple=true&kw='+encodeURIComponent(w);})()",extra:{defaultValue:'',titleVisible:true}});d.push(quick('账号',route('shtSettings',{sht_account:'1'})));d.push(quick('签到',web(o+'/plugin.php?id=dd_sign:index')));d.push(quick('搜索',route('shtSearch')));d.push(quick('设置',route('shtSettings')));d.push(line());d.push(section('话题','按色花堂当前移动端入口解析'));[['最新发表','latest'],['最新热门','hot'],['最新精华','digest']].forEach(function(x){d.push({title:x[0],desc:'原生主题列表',url:route('shtForum',{sht_auto:x[1],sht_name:x[0]}),col_type:'text_1',extra:{lineVisible:false}})});d.push(line());r=resolveForums();fs=r.items||[];saveDiag('home.test4',o,r.diag);d.push(section('论坛板块',fs.length?'识别到 '+fs.length+' 个板块 · '+r.source:'论坛板块仍未识别'));for(i=0;i<fs.length;i++)d.push({title:fs[i].title,desc:'进入板块',url:route('shtForum',{sht_url:fs[i].url,sht_name:fs[i].title}),col_type:'text_1',extra:{lineVisible:false}});if(!fs.length)d.push(empty('没有取得论坛板块','请先打开“账号”完成首次访问/年龄确认，再返回刷新'));setResult(d)}
    function forum(){var d=[],seed=pageParam('sht_url',''),kind=pageParam('sht_auto',''),name=pageParam('sht_name','主题列表'),pg=Math.max(1,Number(typeof MY_PAGE==='undefined'?1:MY_PAGE||1)),g,r,i,item,img;setPageTitle(name);if(!seed&&kind){g=discoverGuide(kind);seed=g.url}if(!seed){setResult([empty('主题入口缺失')]);return}r=loadThreadList(seed,pg);if(kind&&r.items.length===0){g=discoverGuide(kind);if(g.url&&g.url!==seed){seed=g.url;r=loadThreadList(seed,pg)}}saveDiag('forum.test4',r.url,r.diag);if(pg===1){d.push(quick('网页版',web(seed)));d.push(quick('搜索',route('shtSearch')));d.push(line());d.push(section(name,r.items.length?'当前页 '+r.items.length+' 条主题 · '+r.source:'未取得可解析主题'))}for(i=0;i<r.items.length;i++){item=r.items[i];img=item.img?item.img+'@headers='+JSON.stringify(headers(r.url)):'';d.push({title:item.title,desc:'查看帖子',img:img,url:route('shtThread',{sht_url:item.url,sht_name:item.title}),col_type:img?'movie_1':'text_1',extra:{lineVisible:false}})}if(!r.items.length){d.push(empty('仍没有解析到主题','请先确认网页登录入口是否已经通过年龄确认'));d.push({title:'诊断信息',desc:r.diag||'无诊断数据',url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});d.push({title:'打开当前网页版',desc:seed,url:web(seed),col_type:'text_1'})}setResult(d)}
    function settings(){var d=[],o=origin(),cookie='';try{cookie=getCookie(o)||''}catch(e){}setPageTitle('色花堂设置');d.push(section('账号访问','站点首次访问有 18+ 确认页，先确认后再登录；不会自动绕过'));d.push({title:'① 首次访问 / 年龄确认',desc:'打开官网并由你手动点击“满18岁，请点此进入”',url:web(o+'/portal.php?mod=index'),col_type:'text_1'});d.push({title:'② 网页登录',desc:'年龄确认完成后再进入登录；验证码/安全验证继续由官网处理',url:web(o+'/member.php?mod=logging&action=login'),col_type:'text_1'});d.push({title:'③ 每日签到',desc:'登录成功后进入官方签到页',url:web(o+'/plugin.php?id=dd_sign:index'),col_type:'text_1'});d.push({title:'Cookie 状态',desc:cookie?'当前请求容器检测到 Cookie':'当前请求容器未检测到 Cookie（X5 与请求 Cookie 是否共享继续以实机为准）',url:'hiker://empty',col_type:'text_1'});d.push(line());d.push(section('访问线路',o));d.push({title:'切换域名',desc:'仅当前线路不可用时切换',url:'select://'+JSON.stringify({title:'访问域名',options:['sehuatang.org','sehuatang.net','sehuatang.com'],col:1,js:"var v=String(input||'').trim();if(v){setItem('"+KEY_ORIGIN+"','https://'+v);setItem('"+KEY_FORUM_CACHE+"','{}');refreshPage(false);} 'hiker://empty'"}),col_type:'text_1'});d.push({title:'清空论坛缓存并刷新',desc:'板块结构更新或标题异常时使用',url:$('#noLoading#').lazyRule(function(k){setItem(k,'{}');refreshPage(false);return'toast://论坛缓存已清空';},KEY_FORUM_CACHE),col_type:'text_1'});d.push(line());var dg={};try{dg=JSON.parse(getItem(KEY_DIAG,'{}')||'{}')}catch(e){}d.push(section('最近诊断',dg.stage||'暂无'));d.push({title:'详情',desc:(dg.error||'无错误信息')+(dg.origin?'\n'+dg.origin:''),url:'hiker://empty',col_type:'long_text'});setResult(d)}
    function module(){var m=BASE.module();m.version=VERSION;m.build=BUILD;m.home=home;m.forum=forum;m.settings=settings;m._debug=m._debug||{};m._debug.parseThreadsTest4=function(html,base){return parseThreads(html,base).items};m._debug.parseForumsTest4=function(html,base){return parseForums(html,base).items};return m}
    var PATCHED={version:VERSION,build:BUILD,module:module};SeHuaTangRemoteRuntime=PATCHED;return PATCHED;
})();
