/* JavMenu Test3 parser recovery patch - applies to Test2 immutable Core */
(function(){
  if(typeof JavMenuCore!=='object')throw new Error('JavMenu Test3 parser patch: Core 未加载');
  var C=JavMenuCore;
  C.srcsetFirst=function(v){var s=C.trim(v),p=s.split(',')[0]||'';return C.trim(p.split(/\s+/)[0]||'');};
  C.imageCandidateScore=function(u,attr,tag,code){u=C.abs(u,C.base);if(!u||C.badImage(u))return-999;var x=C.s(u).toLowerCase(),t=C.s(tag).toLowerCase(),score=0;if(attr==='data-src'||attr==='data-original'||attr==='data-lazy-src'||attr==='data-poster')score+=36;else if(attr==='srcset'||attr==='data-srcset')score+=30;else if(attr==='src'||attr==='poster')score+=18;if(/\.(?:jpe?g|png|webp)(?:[?#]|$)/i.test(u))score+=20;if(/cover|poster|thumb|image|photo|video/i.test(x))score+=12;if(code&&new RegExp(code.replace(/[-]/g,'[-_]?'),'i').test(t+' '+u))score+=8;if(/width=["']?(?:[3-9]\d\d|\d{4,})/i.test(t)||/height=["']?(?:[2-9]\d\d|\d{4,})/i.test(t))score+=5;if(/icon|avatar|brand|sprite|badge|flag|qr|qrcode|ads?|banner/i.test(x+' '+t))score-=35;return score;};
  C.bestImageIn=function(fragment,ref,code){var best='',bestScore=-999,re=/<img\b[^>]*>/ig,m,tag,attrs=['data-src','data-original','data-lazy-src','data-poster','data-srcset','srcset','src','poster'],i,u,score;while((m=re.exec(C.s(fragment)))){tag=m[0];for(i=0;i<attrs.length;i++){u=C.attr(tag,attrs[i]);if(!u)continue;if(attrs[i].indexOf('srcset')>=0)u=C.srcsetFirst(u);u=C.abs(u,ref||C.base);score=C.imageCandidateScore(u,attrs[i],tag,code);if(score>bestScore){bestScore=score;best=u;}}}re=/background(?:-image)?\s*:\s*url\((?:['"])?([^)'";]+)(?:['"])?\)/ig;while((m=re.exec(C.s(fragment)))){u=C.abs(m[1],ref||C.base);score=C.imageCandidateScore(u,'style',m[0],code)+8;if(score>bestScore){bestScore=score;best=u;}}return bestScore>0?best:'';};
  C.itemImage=function(item,ref,code){return C.bestImageIn(item,ref,code||'');};
  C.cleanMovieTitle=function(v,code){var t=C.strip(v);if(!t)return'';t=t.replace(/^(?:NEW|HD|FHD|4K)\s+/i,'');if(t.length>180)return'';if(/^(?:JAV|JAVMENU|首页|首頁|有码|有码在线|无码|无码视频|FC2|国产|欧美|成人动画|女优榜|女優榜|详情|詳情|播放)$/i.test(t))return'';if(code&&t.toUpperCase()===code.toUpperCase())return code;return t;};
  C.bestTitleIn=function(open,body,code){var cands=[],i,t,re,m,tag;function add(v,w){v=C.cleanMovieTitle(v,code);if(!v)return;cands.push({v:v,s:w+(code&&v.toUpperCase().indexOf(code.toUpperCase())>=0?24:0)+(v.length>=8&&v.length<=120?8:0)});}add(C.attr(open,'title'),34);re=/<img\b[^>]*>/ig;while((m=re.exec(C.s(body)))){tag=m[0];add(C.attr(tag,'alt'),32);add(C.attr(tag,'title'),25);}re=/<(?:h[1-6]|div|span|p)\b[^>]*class=["'][^"']*(?:title|name)[^"']*["'][^>]*>([\s\S]*?)<\/(?:h[1-6]|div|span|p)>/ig;while((m=re.exec(C.s(body))))add(m[1],38);t=C.strip(body);if(t&&t.length<=180)add(t,12);cands.sort(function(a,b){return b.s-a.s;});return cands.length?cands[0].v:(code||'');};
  C.itemTitle=function(item,code){var a=(C.s(item).match(/<a\b([^>]*)>([\s\S]*?)<\/a>/i)||[]);if(a.length)return C.bestTitleIn(a[1],a[2],code||'');var t=C.pdfh(item,'.card-title&&Text')||C.pdfh(item,'img&&alt')||C.pdfh(item,'a&&title');return C.cleanMovieTitle(t,code)||code||'';};
  C.itemRemark=function(item){var t=C.pdfh(item,'.label&&Text')||C.pdfh(item,'.text-muted&&Text')||C.pdfh(item,'.badge&&Text');if(!t){var m=C.s(item).match(/<(?:span|div)\b[^>]*class=["'][^"']*(?:label|text-muted|badge)[^"']*["'][^>]*>([\s\S]*?)<\/(?:span|div)>/i);t=m?m[1]:'';}return C.strip(t);};
  C.nearbyFragment=function(html,href){var s=C.s(html),raw=C.s(href),path=raw.replace(/^https?:\/\/[^/]+/i,''),idx=s.indexOf(raw);if(idx<0&&path)idx=s.indexOf(path);if(idx<0)return'';return s.slice(Math.max(0,idx-900),Math.min(s.length,idx+1800));};
  C.parseMovies=function(html,ref){var out=[],map={},order=[],s=C.s(html),re=/<a\b([^>]*)>([\s\S]*?)<\/a>/ig,m,href,code,rec,img,title,remark,frag,anchors=0,i;while((m=re.exec(s))){href=C.abs(C.attr(m[1],'href'),ref||C.base);if(!href||!C.isDetailHref(href))continue;anchors++;code=C.codeFromHref(href)||C.extractCode(m[2]);if(!code)continue;rec=map[href];if(!rec){rec=map[href]={id:code,code:code,title:code,href:href,rawImg:'',img:'',remark:'',date:'',badge:'',source:'javmenu'};order.push(href);}frag=m[0];img=C.bestImageIn(frag,href,code);if(img&&!rec.rawImg)rec.rawImg=img;else if(img&&C.imageCandidateScore(img,'merge',frag,code)>C.imageCandidateScore(rec.rawImg,'merge',frag,code))rec.rawImg=img;title=C.bestTitleIn(m[1],m[2],code);if(title&&title!==code&&(rec.title===code||title.length>rec.title.length))rec.title=title;remark=C.itemRemark(frag);if(remark&&!rec.remark)rec.remark=remark;}
    for(i=0;i<order.length;i++){rec=map[order[i]];if(!rec.rawImg){frag=C.nearbyFragment(s,rec.href);img=C.bestImageIn(frag,rec.href,rec.code);if(img)rec.rawImg=img;if(rec.title===rec.code){title=C.bestTitleIn('',frag,rec.code);if(title)rec.title=title;}}rec.img=C.image(rec.rawImg,rec.href);out.push(rec);if(out.length>=90)break;}
    C.diag('parse-movies',ref,out.length>0,'movies='+out.length+' detailAnchors='+anchors+' videoListClass='+(s.match(/video-list-item/ig)||[]).length+' images='+(s.match(/<img\b/ig)||[]).length);return out;};
  C.version='0.1.0-test.3'; C.build=10103; C.test3ParserPatch=true;
})();
if(typeof $!=='undefined')$.exports=JavMenuCore;
