/* JavMenu Test3 list runtime recovery patch - keeps Test2 detail/playback UI */
(function(){
  if(typeof JavMenuRuntime!=='object'||typeof JavMenuCore!=='object')throw new Error('JavMenu Test3 runtime patch: base runtime/core 未加载');
  var R=JavMenuRuntime,C=JavMenuCore;
  var ROOT='https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/';
  var BOOT=ROOT+'apps/video/javmenu/bootstrap_test_v3_b10103.js?v=10103';
  var BRAND=ROOT+'apps/video/javmenu/assets/icon.svg?v=10103';
  function section(title,desc){return{title:'““””<b><font color=#7057D9>▌ '+title+'</font></b>',desc:desc||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}};}
  function empty(title,desc,url){return{title:title||'暂无内容',desc:desc||'',url:url||'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}};}
  function movieCard(m){var code=m.code||'',sub=[],title=C.strip(m.title||'');if(title&&title!==code)sub.push(title);if(m.remark)sub.push(m.remark);return{title:code||title,desc:sub.join(' · '),img:m.img||'',pic_url:m.img||'',url:C.page('detail',{code:code}),col_type:'movie_3',extra:{pageTitle:code,lineVisible:false,longClick:[{title:'收藏 / 取消收藏',js:$.toString(function(boot,m){require(boot,{headers:{'Cache-Control':'no-cache'}},10103);return JavMenuBoot.module().invoke('toggleVideo',[m]);},BOOT,m)},{title:'复制番号',js:$.toString(function(code){return'copy://'+code;},code)},{title:'原站详情',js:$.toString(function(href){return href;},m.href||C.detailUrl(code))}]}};}
  function renderMovies(d,html,ref,emptyText){var a=C.parseMovies(html,ref),i;for(i=0;i<a.length;i++)d.push(movieCard(a[i]));if(!a.length)d.push(empty(emptyText||'没有解析到影片','Test3 已执行详情链接多结构扫描；可从“设置 → 诊断”查看 movies / detailAnchors / images。','web://'+ref));return a.length;}
  function searchInput(d,kw){d.push({title:kw||'搜索番号 / 标题 / 演员',url:"(function(){var q=String(input||'').trim();if(!q)return 'toast://请输入关键词';return '"+C.page('search',{kw:'__KW__'}).replace('__KW__','')+"'+encodeURIComponent(q);})()",col_type:'input',extra:{titleVisible:false,lineVisible:false,hint:'输入番号、标题、演员关键词…'}});}
  function quick(d){d.push({title:'发现',img:'hiker://images/icon_menu5',url:C.page('discover',{}),col_type:'icon_small_4',extra:{lineVisible:false}});d.push({title:'收藏',img:'hiker://images/icon_star',url:C.page('favorites',{}),col_type:'icon_small_4',extra:{lineVisible:false}});d.push({title:'历史',img:'hiker://images/icon_history',url:'hiker://history?rule='+MY_RULE.title,col_type:'icon_small_4',extra:{lineVisible:false}});d.push({title:'设置',img:'hiker://images/icon_setting',url:C.page('settings',{}),col_type:'icon_small_4',extra:{lineVisible:false}});}
  function categoryUrl(x){return x.kind==='people-index'?C.page('peopleIndex',{path:x.path,name:x.name}):C.page('list',{path:x.path,name:x.name});}
  function personCard(x){var pic=x.img||BRAND;return{title:x.name||'人物',desc:'JavMenu 女优 / 演员',img:pic,pic_url:pic,url:C.page('person',{path:x.href,name:x.name}),col_type:'avatar',extra:{lineVisible:false,longClick:[{title:'收藏 / 取消收藏人物',js:$.toString(function(boot,x){require(boot,{headers:{'Cache-Control':'no-cache'}},10103);return JavMenuBoot.module().invoke('togglePeople',[x]);},BOOT,x)}]}};}
  R.home=function(){var d=[],pg=Number(MY_PAGE||1),url=C.homeUrl(pg),html;if(pg===1){setPageTitle('JavMenu');d.push({title:'JavMenu',desc:'原站影片 · 本地收藏 · 多源播放',img:BRAND,pic_url:BRAND,url:'web://'+C.base+C.homePath,col_type:'avatar',extra:{lineVisible:false}});searchInput(d,'');quick(d);d.push(section('最近更新','详情链接多结构恢复解析 · Test 0.1.0-test.3'));}html=C.fetchHtml(url);if(C.isBadHtml(html)){if(pg===1)d.push(empty('JavMenu 暂时无法读取','已尝试 javmenu.com / javmenu.org 与当前请求策略。','web://'+url));setResult(d);return;}renderMovies(d,html,url,'本页没有解析到影片');setResult(d);};
  R.search=function(){var d=[],kw=C.get('kw','');if(!kw&&typeof MY_KEYWORD!=='undefined')kw=String(MY_KEYWORD||'');kw=C.trim(kw);var pg=Number(MY_PAGE||1),url=C.searchUrl(kw,pg),html;if(pg===1){setPageTitle('搜索 · '+kw);searchInput(d,kw);d.push(section('搜索结果',kw||'请输入关键词'));}if(!kw){d.push(empty('请输入关键词','支持番号、标题、演员等官网可搜索字段'));setResult(d);return;}html=C.fetchHtml(url);if(C.isBadHtml(html)){if(pg===1)d.push(empty('搜索请求失败','可打开原站搜索页核对当前站点状态。','web://'+url));setResult(d);return;}renderMovies(d,html,url,'没有找到匹配影片');setResult(d);};
  R.discover=function(){var d=[],a=C.categories(),groups=['在线分类','排行榜','资源分类'],g,i,x;setPageTitle('发现');d.push(section('JavMenu 分类','Test3 保留已确认分类路由；影片列表改为详情链接多结构解析'));for(g=0;g<groups.length;g++){d.push(section(groups[g],g===0?'有码 / 无码 / FC2 / 国产 / 欧美 / 动画':g===1?'日榜 / 周榜 / 月榜 / 女优榜':'有码 / 无码磁力'));for(i=0;i<a.length;i++){x=a[i];if(x.group!==groups[g])continue;d.push({title:x.name,url:categoryUrl(x),col_type:'flex_button',extra:{lineVisible:false}});}}setResult(d);};
  R.list=function(){var d=[],raw=C.get('path',''),name=C.get('name','列表'),pg=Number(MY_PAGE||1),url=C.listUrl(raw,pg),html;if(pg===1){setPageTitle(name);d.push(section(name,'JavMenu 影片列表 · Test3 多结构解析'));}if(!raw){d.push(empty('缺少分类地址','返回发现页重新选择。'));setResult(d);return;}html=C.fetchHtml(url);if(C.isBadHtml(html)){if(pg===1)d.push(empty('页面读取失败','当前分类地址暂不可用。','web://'+url));setResult(d);return;}renderMovies(d,html,url,'当前分类没有解析到影片');setResult(d);};
  R.peopleIndex=function(){var d=[],raw=C.get('path','/zh/rank/censored/actress'),name=C.get('name','女优榜'),pg=Number(MY_PAGE||1),url=C.listUrl(raw,pg),html,a,i;if(pg===1){setPageTitle(name);d.push(section(name,'JavMenu 当前女优 / 演员索引'));}html=C.fetchHtml(url);if(C.isBadHtml(html)){if(pg===1)d.push(empty('女优榜读取失败','可打开原站核对当前页面。','web://'+url));setResult(d);return;}a=C.parseActressIndex(html,url);if(!a.length){d.push(empty('当前页没有解析到人物','人物索引使用独立 /actor/ Adapter；若仍为空请继续截图。','web://'+url));setResult(d);return;}for(i=0;i<a.length;i++)d.push(personCard(a[i]));setResult(d);};
  R.person=function(){var d=[],raw=C.get('path',''),fallback=C.get('name','女优'),pg=Number(MY_PAGE||1),url=C.listUrl(raw,pg),html,name;if(!raw){d.push(empty('缺少人物地址','请从女优榜或详情演员重新进入。'));setResult(d);return;}html=C.fetchHtml(url);if(C.isBadHtml(html)){setPageTitle(fallback);d.push(empty('人物页面读取失败','可打开原站核对。','web://'+url));setResult(d);return;}name=C.personName(html,fallback);if(pg===1){setPageTitle(name);d.push(section(name+' · 作品','Test3 多结构影片解析'));}renderMovies(d,html,url,'该人物当前没有解析到作品');setResult(d);};
  R.version='0.1.0-test.3'; R.build=10103; R.test3ListPatch=true;
})();
if(typeof $!=='undefined')$.exports=JavMenuRuntime;
