/* xChina Remote Runtime Pages 0.1.0-test.9 */
(function(K){
  if(!K||String(K.version)!=='0.1.0-test.9'||Number(K.build)!==10109)throw new Error('Test9 Core 未加载');
  var R={version:K.version,build:K.build},C=K.C,CATEGORY_GROUPS=K.CATEGORY_GROUPS;
  var s=K.s,trim=K.trim,decode=K.decode,strip=K.strip,safeDecode=K.safeDecode,origin=K.origin,abs=K.abs,badHtml=K.badHtml,cookieFor=K.cookieFor,headersFor=K.headersFor,coverImage=K.coverImage,contentImage=K.contentImage,domArray=K.domArray,domHtml=K.domHtml,domUrl=K.domUrl,attr=K.attr,cssUrl=K.cssUrl,og=K.og,getFixedBase=K.getFixedBase,getLastBase=K.getLastBase,setLastBase=K.setLastBase,fetchPage=K.fetchPage,param=K.param,currentPage=K.currentPage,page=K.page,section=K.section,empty=K.empty,btn=K.btn,active=K.active,refreshType=K.refreshType,typeName=K.typeName,typeIcon=K.typeIcon,tabs=K.tabs,listPath=K.listPath,searchPath=K.searchPath,cardBlocks=K.cardBlocks,cardFromBlock=K.cardFromBlock,parseCards=K.parseCards,detailPage=K.detailPage,card=K.card,listResult=K.listResult,detailInfo=K.detailInfo,chapterLinks=K.chapterLinks,pagerMax=K.pagerMax,extractImages=K.extractImages,mediaFromHtml=K.mediaFromHtml,directPlayer=K.directPlayer,headerPlayer=K.headerPlayer;
  R.home=function(){var d=[],p=currentPage(),type=getMyVar('xc_home_type','photo'),res=listResult(type,listPath(type,p));if(p===1){d.push({title:'🟣 小黄书',desc:'📕 小说 · 🖼️ 套图 · 🎨 漫画 · 💽 视频',img:C.publish+'/favicon.ico',pic_url:C.publish+'/favicon.ico',url:'web://'+C.publish,col_type:'avatar',extra:{lineVisible:false}});tabs(d,'xc_home_type',type);d.push(btn('🔎 搜索',page('xchinaSearch',{})));d.push(btn('🗂 分类',page('xchinaCategories',{t:type})));d.push(btn('👩 模特',page('xchinaCatalog',{t:'model',name:'模特'})));d.push(btn('⚙️ 设置',page('xchinaSettings',{})));d.push(section(typeIcon(type)+' '+typeName(type)+'最新','按阅读源 2025-11-13 结构解析'));}if(!res.items.length)d.push(empty('没有解析到内容',(res.r.ok?'页面已取得，但目标卡片为空':'站点验证/网络未通过')+'\n'+res.r.url));else{for(var i=0;i<res.items.length;i++)d.push(card(res.items[i]));}setResult(d);};
  R.list=function(){var d=[],p=currentPage(),type=param('t','photo'),name=safeDecode(param('name',typeName(type))),tpl=safeDecode(param('xc_path','')),path=tpl||listPath(type,p);if(path.indexOf('{page}')>=0)path=path.replace('{page}',String(p));var res=listResult(type,path);if(p===1){setPageTitle(name);d.push(section(typeIcon(type)+' '+name,'原站分页'));}if(!res.items.length)d.push(empty('当前列表为空或解析失败',res.r.url));else for(var i=0;i<res.items.length;i++)d.push(card(res.items[i]));setResult(d);};
  R.categories=function(){var d=[],type=getMyVar('xc_category_type',param('t','photo')),groups=CATEGORY_GROUPS[type]||{},g,items,i,x,actual;setPageTitle(typeName(type)+'分类');tabs(d,'xc_category_type',type);for(g in groups){if(!groups.hasOwnProperty(g))continue;d.push(section('🔖 '+g,''));items=groups[g];for(i=0;i<items.length;i++){x=items[i];actual=x[2]||type;d.push({title:x[0],url:page('xchinaCatalog',{t:actual,name:x[0],xc_path:x[1]}),col_type:'flex_button',extra:{lineVisible:false}});}}setResult(d);};
  R.search=function(){var d=[],p=currentPage(),type=getMyVar('xc_search_type','fiction'),kw=getMyVar('xc_search_kw','');try{if(MY_KEYWORD)kw=s(MY_KEYWORD);}catch(e){}kw=trim(kw);if(p===1){setPageTitle('搜索');tabs(d,'xc_search_type',type);d.push({title:kw||'输入关键词',desc:'按阅读源搜索路由查询 '+typeIcon(type)+typeName(type),url:"(function(){var q=String(input||'').trim();putMyVar('xc_search_kw',q);refreshPage(false);return 'hiker://empty';})()",col_type:'input',extra:{defaultValue:kw,hint:'输入关键词',lineVisible:false}});if(kw)d.push(section('🔎 '+typeName(type)+'搜索结果',kw));}if(!kw){d.push(empty('请输入关键词','上方可切换小说 / 套图 / 漫画 / 视频'));setResult(d);return;}var res=listResult(type,searchPath(type,kw,p));if(!res.items.length)d.push(empty('没有搜索到内容',res.r.url));else for(var i=0;i<res.items.length;i++)d.push(card(res.items[i]));setResult(d);};
  R.detail=function(){var d=[],url=safeDecode(param('xc_url','')),type=param('t','');if(!url){d.push(empty('缺少详情地址',''));setResult(d);return;}if(!type){type=/\/fiction\//.test(url)?'fiction':/\/comic\//.test(url)?'comic':/\/photo\//.test(url)?'photo':/\/amateur\//.test(url)?'amateur':/\/model\//.test(url)?'model':'video';}var res=fetchPage(url,type),info=detailInfo(res.html,url,type),media=mediaFromHtml(res.html,url,type),chapters=(type==='fiction'||type==='comic')?chapterLinks(res.html,url,type):[],max=pagerMax(res.html),meta=[typeIcon(type)+' '+typeName(type)],i;setPageTitle(info.title);if(media.length)meta.push(media.length+' 个视频');if(chapters.length)meta.push(chapters.length+' 章');if((type==='photo'||type==='amateur')&&max>1)meta.push(max+' 页');d.push({title:info.title,desc:meta.join(' · '),img:info.img,pic_url:info.img,url:'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});
    if(type==='model'){var works=parseCards(res.html,url,'video'),photos=parseCards(res.html,url,'photo');if(info.intro)d.push({title:info.intro,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});if(works.length){d.push(section('💽 影片作品',works.length+' 条'));for(i=0;i<works.length;i++)d.push(card(works[i]));}if(photos.length){d.push(section('🖼️ 写真作品',photos.length+' 条'));for(i=0;i<photos.length;i++)d.push(card(photos[i]));}if(!works.length&&!photos.length)d.push(empty('当前页没有解析到关联作品','可打开原站核对页面'));}
    else if(type==='fiction'||type==='comic'){if(chapters.length)d.push({title:type==='fiction'?'📖 开始阅读 · '+chapters.length+' 章':'🎨 查看章节 · '+chapters.length,url:page('xchinaChapters',{xc_url:url,t:type,title:info.title}),col_type:'text_center_1',extra:{lineVisible:false}});else d.push({title:type==='fiction'?'📖 阅读正文':'🎨 阅读本章',url:page('xchinaReader',{xc_url:url,t:type,title:info.title}),col_type:'text_center_1',extra:{lineVisible:false}});}
    else if(type==='video'){if(media.length)d.push({title:'▶️ 免嗅直连',desc:(/m3u8/i.test(media[0])?'HLS':'直链')+' · 按阅读源原始媒体地址交付',url:directPlayer(media[0]),col_type:'text_center_1',extra:{lineVisible:false,id:url}});else d.push({title:'🧪 嗅探兜底',desc:'页面未按阅读源契约解析到媒体直链',url:'video://'+url,col_type:'text_center_1',extra:{lineVisible:false}});if(media.length>1)d.push(btn('🎞️ 视频 '+media.length,page('xchinaMedia',{xc_url:url,t:type})));}
    else{d.push(btn('🖼️ 看图',page('xchinaReader',{xc_url:url,t:type})));if(media.length)d.push(btn('▶️ 视频 '+media.length,page('xchinaMedia',{xc_url:url,t:type})));if(max>1)d.push(btn('📄 分页 '+max,page('xchinaChapters',{xc_url:url,t:type,title:info.title})));}
    d.push(btn('🌐 原站','web://'+url));if(info.intro&&type!=='model'){d.push(section('📝 简介',''));d.push({title:info.intro,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});}if(!res.ok)d.push(empty('当前页面可能被验证页拦截','进入设置页完成 X5 验证后返回刷新'));setResult(d);};
  R.chapters=function(){var d=[],url=safeDecode(param('xc_url','')),type=param('t','fiction'),title=safeDecode(param('title','目录')),res=fetchPage(url,type),i,x;setPageTitle(title);if(type==='photo'||type==='amateur'){var max=pagerMax(res.html),base=url.replace(/\.html(?:[?#].*)?$/,''),target;d.push(section('📄 分页','共 '+max+' 页'));for(i=1;i<=max;i++){target=i===1?url:base+'/'+i+'.html';d.push({title:'第 '+i+' 页',url:page('xchinaReader',{xc_url:target,t:type}),col_type:'flex_button',extra:{lineVisible:false}});}}else{var xs=chapterLinks(res.html,url,type);d.push(section(type==='comic'?'🎨 章节':'📕 章节','共 '+xs.length+' 项'));for(i=0;i<xs.length;i++){x=xs[i];d.push({title:x.name,url:page('xchinaReader',{xc_url:x.href,t:type}),col_type:'text_1',extra:{lineVisible:false}});}if(!xs.length)d.push(empty('未解析到章节','页面可能本身就是正文页'));}setResult(d);};
  R.reader=function(){var d=[],url=safeDecode(param('xc_url','')),type=param('t',''),res=fetchPage(url,type),i;setPageTitle(type==='fiction'?'📖 正文':'🖼️ 图片');if(type==='fiction'){var ps=domArray(res.html,'.fiction-body&&p'),txt;if(ps.length){for(i=0;i<ps.length;i++){txt=strip(domHtml(ps[i],'p&&Html')||domHtml(ps[i],'p&&Text')||ps[i]);if(txt)d.push({title:txt,url:'hiker://empty',col_type:'rich_text',extra:{lineVisible:false}});}}else{txt=strip(domHtml(res.html,'.fiction-body&&Html')||'');if(txt)d.push({title:txt,url:'hiker://empty',col_type:'rich_text',extra:{lineVisible:false}});else d.push(empty('未解析到正文',url));}}else{var imgs=extractImages(res.html,url,type);if(!imgs.length)d.push(empty('未解析到图片','按阅读源目标容器未找到图片'));else for(i=0;i<imgs.length;i++){var pi=contentImage(imgs[i],type);d.push({title:'',img:pi,pic_url:pi,url:pi,col_type:'pic_1_full',extra:{lineVisible:false}});}}setResult(d);};
  R.media=function(){var d=[],url=safeDecode(param('xc_url','')),type=param('t','video'),res=fetchPage(url,type),xs=mediaFromHtml(res.html,url,type),i,u;setPageTitle('🎬 播放线路');if(!xs.length){d.push(empty('未按阅读源契约解析到媒体地址','可测试网页嗅探兜底'));d.push({title:'🧪 网页嗅探兜底',url:'video://'+url,col_type:'text_center_1',extra:{lineVisible:false}});}else{d.push(section('▶️ 免嗅线路','读取 main-container；m3u8 优先，套图视频回退 var domain + var videos'));for(i=0;i<xs.length;i++){u=xs[i];d.push({title:'▶️ 免嗅 '+(i+1),desc:/m3u8/i.test(u)?'HLS 原始直链':'MP4 原始直链',url:directPlayer(u),col_type:'text_1',extra:{lineVisible:false,id:url+'#'+i}});d.push({title:'🧩 Header 兼容 '+(i+1),desc:'仅当原始直链失败时测试',url:headerPlayer(u,url),col_type:'text_1',extra:{lineVisible:false,id:url+'#h'+i}});}d.push({title:'🧪 网页嗅探兜底',desc:'免嗅均失败时用于判断页面实际资源是否变化',url:'video://'+url,col_type:'text_1',extra:{lineVisible:false}});}setResult(d);};
  R.settings=function(){var d=[],fixed=getFixedBase(),last=getLastBase(),b=fixed||last||C.primary;setPageTitle('⚙️ 小黄书设置');d.push(section('🌐 线路','当前 '+b));d.push({title:'🔄 自动线路',desc:'最近成功线路 → xchina.co → xchina001.ink',url:$('#noLoading#').lazyRule(function(k){clearItem(k);refreshPage(false);return'toast://已恢复自动线路';},C.baseKey),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'📌 固定 xchina.co',desc:C.primary,url:$('#noLoading#').lazyRule(function(k,v){setItem(k,v);refreshPage(false);return'toast://已固定主域';},C.baseKey,C.primary),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'📌 固定备用线路',desc:C.fallback,url:$('#noLoading#').lazyRule(function(k,v){setItem(k,v);refreshPage(false);return'toast://已固定备用域';},C.baseKey,C.fallback),col_type:'text_1',extra:{lineVisible:false}});d.push(section('🧩 网站验证','阅读源 loginCheck：遇到 Just a moment 时清 Cookie → 浏览器验证 → 重新连接；海阔侧保留 X5 同会话验证入口'));d.push({title:'✅ 打开当前线路验证',desc:b,url:'x5://'+b+'/',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'🎨 打开漫画线路',desc:C.comic,url:'x5://'+C.comic+'/',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'🍪 Cookie 状态',desc:(cookieFor(b)?'主站：已读取':'主站：未读取')+' · '+(cookieFor(C.comic)?'漫画：已读取':'漫画：未读取'),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push(section('ℹ️ 状态','Test 0.1.0-test.9 · Build 10109'));d.push({title:'🧹 清理页面缓存',desc:'新 Test9 使用独立缓存命名空间',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'📢 发布页',desc:C.publish,url:'web://'+C.publish,col_type:'text_1',extra:{lineVisible:false}});d.push(section('📝 说明','Test9 不再沿用 Test7 的通用邻域猜测封面/播放链；列表封面严格优先 `.img@style`，封面 Referer 按阅读源固定主站；漫画正文 Referer 固定 litu100；视频按阅读源 main-container 直接取真实 m3u8 / domain+videos，默认免嗅原始直链。'));setResult(d);};
  R.module=function(){return{home:R.home,catalog:R.list,list:R.list,categories:R.categories,search:R.search,searchPage:R.search,detail:R.detail,videoDetail:R.detail,photoDetail:R.detail,fictionDetail:R.detail,comicDetail:R.detail,modelDetail:R.detail,chapters:R.chapters,reader:R.reader,media:R.media,settings:R.settings};};
  XChinaRemoteRuntime=R;
})(XChinaTest9Core);
