/* JavDB v3 3.9.46-test.1 Playback Expansion Local-First entry */
var JavDBLocal=(function(){
var VERSION='3.9.46-test.1',BUILD=2026082905;
var ROOT='hiker://files/rules/asset-core-local/javdb-v3-test/b2026082905/';
var ENTRY=ROOT+'local_entry.js',UI=ROOT+'product_ui_patch7.js',UPFILE=ROOT+'jav_playback_upgrade_11001.js';
var BASE_ROOT='hiker://files/rules/asset-core-local/javdb-v3-test/b2026082501/';
var BASE_BUILDER=BASE_ROOT+'local_bundle_builder.js';
var BASE_BREF='2361fbbfc21c540191495b979b30a6828adfe9c1';
var BASE_BPATH='apps/video/javdb/releases/3.9.44-test.1/local_bundle_builder.js';
var UI_REF='10f182e75bbfd0ee89cb4f41c2f0606a678a05e0';
var UI_PATH='apps/video/javdb/releases/3.9.45-test.7/product_ui_patch7.js';
var UP_REF='8a8a3ead9dc234bb26bd9251907ae2794a0e65c5';
var UP_PATH='shared/jav-playback/releases/1.1.0-test.1/upgrade.js';
var CACHE_UI='',CACHE_UP=null;
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function urls(ref,path){return['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/'+ref+'/'+path,'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@'+ref+'/'+path,'https://github.com/huoguotiankong/asset-core-7f3/raw/'+ref+'/'+path];}
function ensureFile(local,ref,path,marker){if(fileExist(local)){try{var old=String(readFile(local)||'');if(!bad(old)&&old.indexOf(marker)>=0)return local;}catch(_e){}try{deleteFile(local);}catch(_e2){}}var us=urls(ref,path),es=[];for(var i=0;i<us.length;i++){try{var s=String(fetch(us[i],{timeout:6500,headers:{'Cache-Control':'public, max-age=31536000, immutable'}})||'');if(bad(s)||s.indexOf(marker)<0)throw new Error('无效响应');writeFile(local,s);if(!fileExist(local))throw new Error('写入失败');return local;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(path+' 下载失败：'+es.join(' | '));}
function req(p){var u=getPath(p),r=null;try{r=require(u);}catch(e0){try{deleteCache(u);}catch(e1){}r=require(u);}return r;}
function builder(){ensureFile(BASE_BUILDER,BASE_BREF,BASE_BPATH,'3.9.44-test.1');req(BASE_BUILDER);if(typeof JavDBLocalBuilder!=='object'||typeof JavDBLocalBuilder.load!=='function')throw new Error('JavDB Base Builder 未导出');return JavDBLocalBuilder;}
function uiPatch(force){if(force){try{if(fileExist(UI))deleteFile(UI);}catch(_e){}CACHE_UI='';}if(CACHE_UI)return CACHE_UI;ensureFile(UI,UI_REF,UI_PATH,'3.9.45-test.7');CACHE_UI=String(readFile(UI)||'');if(bad(CACHE_UI)||CACHE_UI.indexOf('3.9.45-test.7')<0)throw new Error('JavDB UI7 校验失败');return CACHE_UI;}
function upgrade(force){if(force){try{if(fileExist(UPFILE))deleteFile(UPFILE);}catch(_e){}CACHE_UP=null;}if(CACHE_UP)return CACHE_UP;ensureFile(UPFILE,UP_REF,UP_PATH,'1.1.0-test.1');CACHE_UP=req(UPFILE);if(!CACHE_UP||typeof CACHE_UP.apply!=='function'||String(CACHE_UP.version||'')!=='1.1.0-test.1')throw new Error('JAV Playback Upgrade 1.1.0-test.1 校验失败');return CACHE_UP;}
function baseLoad(){var b=builder(),x=b.load(),r=x&&x.runtime;if(!r||typeof r.core!=='function'||String(r.localFirstVersion||'')!=='3.9.44-test.1')throw new Error('JavDB 3.9.44 Local-First Base Runtime 未就绪');return{builder:b,pack:x,runtime:r};}
function module(){var base=baseLoad(),r=base.runtime,p=uiPatch(false),play=null;function playback(){if(play)return play;var up=upgrade(false),baseSdk=r.playback();play=up.apply(baseSdk,{localReentry:true,icon123:String(base.builder.icon123||'')});if(!play||String(play.version||'')!=='1.1.0-test.1'||play.providers().length<6)throw new Error('JAV Playback 1.1.0-test.1 preflight failed');return play;}function core(call){playback();return r.core('eval('+JSON.stringify(p)+');'+String(call||''));}return{version:VERSION,build:BUILD,localFirstVersion:VERSION,localFirstBuild:BUILD,productUiVersion:'3.9.45-test.7',productUiBuild:2026082904,playbackVersion:'1.1.0-test.1',playbackBuild:11001,baseVersion:String(r.localFirstVersion||''),baseBuild:Number(r.localFirstBuild||0),core:core,custom:function(key){if(key==='javdb3ExternalPlay')return core('JDB.externalPlayPage();');return r.custom(key);},playback:playback,customData:function(){return r.customData();},localBundleMeta:base.pack&&base.pack.meta?base.pack.meta:null};}
function info(){try{var b=builder(),m=b.meta(),u=false,pb=false;try{u=fileExist(UI)&&String(readFile(UI)||'').indexOf('3.9.45-test.7')>=0;}catch(_e){}try{pb=fileExist(UPFILE)&&String(readFile(UPFILE)||'').indexOf('1.1.0-test.1')>=0;}catch(_e2){}return{version:VERSION,build:BUILD,ready:!!m&&u&&pb,ui:u,playback:pb,baseReady:!!m,baseMeta:m||{},uiRef:UI_REF,playbackRef:UP_REF};}catch(e){return{version:VERSION,build:BUILD,ready:false,error:String(e.message||e),uiRef:UI_REF,playbackRef:UP_REF};}}
function rebuild(){uiPatch(true);upgrade(true);var b=builder(),m=b.meta();if(!m)m=b.install(false);return{ui:true,playback:true,base:m};}
function statusPage(){setPageTitle('JavDB · 本地化诊断');var d=[],x=info(),m=x.baseMeta||{};d.push({title:'JavDB v3 '+VERSION,desc:'Build '+BUILD+' · JAV Playback Expansion',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:x.playback?'Playback 1.1.0-test.1 已就绪':'Playback 1.1.0-test.1 未就绪',desc:'MissAV / 123AV / Jable / AV01 / TKTUBE / JavGuru',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:x.ui?'UI7 已就绪':'UI7 未就绪',desc:'复用 3.9.45-test.7 Product UI，不重写详情/账号/API',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:x.baseReady?'基础 Runtime 已就绪':'基础 Runtime 未就绪',desc:x.baseReady?('Base '+String(m.version||'3.9.44-test.1')+' · '+String(m.sources||0)+' 源 · '+String(m.bytes||0)+' bytes'):String(x.error||'首次打开会自动安装'),url:'hiker://empty',col_type:'text_2',extra:{lineVisible:false}});d.push({title:'稳定保护',desc:'Stable 3.9.42 / Shared Playback Stable 1.0.0-test.4 均未修改',url:'hiker://empty',col_type:'text_2',extra:{lineVisible:false}});d.push({col_type:'line_blank'});d.push({title:'重建播放测试层',desc:'重新拉取固定 UI7 + Playback Upgrade，不重建已就绪 Base Runtime',url:$('#noLoading#').lazyRule(function(){try{var E='hiker://files/rules/asset-core-local/javdb-v3-test/b2026082905/local_entry.js',u=getPath(E);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}JavDBLocal.rebuild();refreshPage(false);return'toast://JavDB 播放测试层已重建';}catch(e){return'toast://重建失败：'+String(e.message||e);}}),col_type:'text_1',extra:{lineVisible:false}});setResult(d);}
return{version:VERSION,build:BUILD,module:module,info:info,rebuild:rebuild,statusPage:statusPage,builder:builder,patch:uiPatch,upgrade:upgrade,entry:ENTRY};
})();
