/* 色花堂 0.1.0-test.12 / Build 10112 - mobile-first forum preview + ordered thread media */
var SeHuaTangPatchTest12=(function(){
  var BASE=SeHuaTangRemoteRuntime;
  var VERSION='0.1.0-test.12',BUILD=10112,RULE_NAME='色花堂';
  var DEFAULT_ORIGIN='https://sehuatang.org';
  var KEY_ORIGIN='sht_origin_v1',KEY_COOKIE='sht_web_cookie_v5',KEY_ACCESS='sht_access_ok_v7',KEY_DIAG='sht_diag_v1';
  var UA_M='Mozilla/5.0 (Linux; Android 13; zh-CN) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Mobile Safari/537.36';
  var UA_PC='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36';
  var RAW='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/aggregate/sehuatang/assets/icons/v1/';
  function s(v){return v==null?'':String(v)}
  function trim(v){return s(v).replace(/^\s+|\s+$/g,'')}
  function dec(v){v=s(v);try{return decodeURIComponent(v)}catch(e){return v}}
  function hdec(v){var x=s(v),i;for(i=0;i<2;i++)x=x.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;/gi,' ');return x}
  function strip(v){return trim(hdec(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/[\t\r]+/g,' ').replace(/\s+/g,' '))}
  function origin(){var o=trim(getItem(KEY_ORIGIN,DEFAULT_ORIGIN));return /^https?:\/\//i.test(o)?o.replace(/\/+$/,''):DEFAULT_ORIGIN}
  function abs(h,b){h=hdec(trim(h));if(!h)return'';if(/^https?:\/\//i.test(h))return h;if(/^\/\//.test(h))return'https:'+h;if(/^(javascript:|mailto:|tel:|#)/i.test(h))return'';var m=s(b).match(/^(https?:\/\/[^\/]+)/i),o=m?m[1]:origin();if(h.charAt(0)==='/')return o+h;var c=s(b).split('#')[0].split('?')[0];if(c.charAt(c.length-1)!=='/')c=c.replace(/\/[^\/]*$/,'/');return c+h.replace(/^\.\//,'')}
  function pageParam(n,d){var u=s(typeof MY_URL==='undefined'?'':MY_URL),m=u.match(new RegExp('[?&]'+n+'=([^&#]*)'));return m?dec(m[1]):(d==null?'':d)}
  function route(path,p){var u='hiker://page/'+path+'?rule='+RULE_NAME+'&simple=true',k;for(k in(p||{}))if(p.hasOwnProperty(k)&&p[k]!=null)u+='&'+k+'='+encodeURIComponent(s(p[k]));return u}
  function line(){return{col_type:'line'}}
  function section(t,d){return{title:t,desc:d||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}}}
  function empty(t,d){return{title:t,desc:d||'',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}}}
  function quick(t,u,ico){var p=RAW+ico;return{title:t,img:p,pic_url:p,url:u,col_type:'icon_small_4',extra:{lineVisible:false}}}
  function saveDiag(stage,msg){try{setItem(KEY_DIAG,JSON.stringify({stage:stage,origin:origin(),error:s(msg||'').slice(0,2600),time:new Date().getTime()}))}catch(e){}}
  function cookie(){var c='';try{c=getVar(KEY_COOKIE,'')||''}catch(e){}if(c)return c;try{c=getCookie(origin())||''}catch(e2){}return c}
  function headers(pc,ref){var c=cookie(),h={'User-Agent':pc?UA_PC:UA_M,'Referer':ref||origin()+'/'};if(c){h.Cookie=c;h.cookie=c}return h}
  function imageUrl(u,ref){u=abs(u,ref);if(!u)return'';return u+'@headers='+JSON.stringify(headers(false,ref||origin()+'/'))+'#originalSize#'}
  function threadId(u){var x=hdec(s(u)),m=x.match(/[?&]tid=(\d+)/i)||x.match(/[?&]ptid=(\d+)/i)||x.match(/\/thread-(\d+)-\d+-\d+\.html/i);return m?m[1]:''}
  function toMobile(u){u=s(u);if(!u)return u;if(/[?&]mobile=(?:2|no)(?=&|$)/i.test(u))return u.replace(/([?&])mobile=(?:2|no)(?=&|$)/i,'$1mobile=2');return u+(u.indexOf('?')>=0?'&':'?')+'mobile=2'}
  function toPc(u){u=s(u);if(!u)return u;if(/[?&]mobile=(?:2|no)(?=&|$)/i.test(u))return u.replace(/([?&])mobile=(?:2|no)(?=&|$)/i,'$1mobile=no');return u+(u.indexOf('?')>=0?'&':'?')+'mobile=no'}
  function withPage(u,p){p=Math.max(1,Number(p||1));u=s(u);if(/\/forum-\d+-\d+\.html(?:\?|$)/i.test(u))return u.replace(/\/forum-(\d+)-\d+\.html/i,'/forum-$1-'+p+'.html');if(/([?&])page=\d+/i.test(u))return u.replace(/([?&])page=\d+/i,'$1page='+p);return u+(u.indexOf('?')>=0?'&':'?')+'page='+p}
  function canonical(u){return s(u).replace(/@headers=.*$/,'').replace(/#originalSize#.*$/,'').replace(/[?#].*$/,'')}
  function validImage(u,base,attrs){u=abs(u,base);if(!u||/^data:/i.test(u))return'';if(/avatar|uc_server|ucenter|noavatar|smiley|static\/image|logo\.|none\.gif|loading|blank\.gif|emotion|face\/|emoji|icon\//i.test(u))return'';return u}
  function attrVal(a,n){var r=new RegExp('\\b'+n+'\\s*=\\s*(["\\\'])(.*?)\\1','i'),m=s(a).match(r);return m?m[2]:''}
  function imgFromTag(tag,base){var a=s(tag),names=['zoomfile','file','data-original','data-src','data-echo','data-lazy-src','data-url','data-actual','data-cfsrc','src'],i,u,ss,st;for(i=0;i<names.length;i++){u=validImage(attrVal(a,names[i]),base,a);if(u)return u}ss=attrVal(a,'srcset');if(ss){u=validImage(trim(ss.split(',')[0].split(/\s+/)[0]),base,a);if(u)return u}st=a.match(/background(?:-image)?\s*:\s*url\((?:["']?)([^)"']+)/i);if(st){u=validImage(st[1],base,a);if(u)return u}return''}
  function allImages(x,base,max){var out=[],seen={},re=/<img\b[^>]*>/gi,m,u,gre,gm,a;while((m=re.exec(s(x)))!==null){u=imgFromTag(m[0],base);if(u&&!seen[canonical(u)]){seen[canonical(u)]=1;out.push(u)}if(out.length>=(max||30))return out}
    gre=/<(?:a|div|span|li)\b([^>]*(?:data-original|data-src|data-bg|style\s*=)[^>]*)>/gi;while((gm=gre.exec(s(x)))!==null){a=gm[1]||'';u=validImage(attrVal(a,'data-original')||attrVal(a,'data-src')||attrVal(a,'data-bg'),base,a);if(!u){var mm=a.match(/background(?:-image)?\s*:\s*url\((?:["']?)([^)"']+)/i);if(mm)u=validImage(mm[1],base,a)}if(u&&!seen[canonical(u)]){seen[canonical(u)]=1;out.push(u)}if(out.length>=(max||30))break}return out}
  function anchors(html,base){var out=[],re=/<a\b([^>]*?)href\s*=\s*(?:["']([^"']+)["']|([^\s>]+))([^>]*)>([\s\S]*?)<\/a>/gi,m,a,t,tm;while((m=re.exec(s(html)))!==null){a=(m[1]||'')+' '+(m[4]||'');t=strip(m[5]||'');if(!t){tm=a.match(/\b(?:title|aria-label)\s*=\s*["']([^"']+)["']/i);if(tm)t=strip(tm[1])}out.push({href:abs(m[2]||m[3]||'',base),text:t,inner:m[5]||'',attrs:a,index:m.index});if(out.length>18000)break}return out}
  function badThreadText(t){t=trim(t);if(!t||t.length<2)return true;if(/本帖最后由.+编辑|^(作者|回复于|发表于|查看|查看帖子|回复|最后发表|最后回复|上一页|下一页|返回|详情|进入|播放)/i.test(t))return true;if(/^\d{1,2}:\d{2}(?::\d{2})?$/.test(t)||/^\d+$/.test(t))return true;return false}
  function threadScore(t){t=trim(t);if(badThreadText(t))return-999;var n=Math.min(t.length,150);if(/[\u4e00-\u9fffA-Za-z]{2,}/.test(t))n+=35;if(t.length>=8)n+=20;if(/影片名称|原创|中文字幕|无码|有码|写真|视频|FC2|IPX|SSIS|JUL|MIDE|ROE/i.test(t))n+=14;if(t.length>140)n-=12;return n}
  function contextAround(html,index){var x=s(html),start,end;start=x.lastIndexOf('<li',index);end=start>=0?x.indexOf('</li>',index):-1;if(start>=0&&end>=0&&end-start<60000)return x.slice(start,end+5);start=x.lastIndexOf('<tbody',index);end=start>=0?x.indexOf('</tbody>',index):-1;if(start>=0&&end>=0&&end-start<80000)return x.slice(start,end+8);start=x.lastIndexOf('<div',index);end=start>=0?x.indexOf('</div>',index):-1;if(start>=0&&end>=0&&end-start<45000)return x.slice(start,end+6);return x.slice(Math.max(0,index-5000),Math.min(x.length,index+12000))}
  function rowSummary(ctx,title){var t=strip(ctx),q=trim(title);if(q)t=t.replace(q,' ');t=t.replace(/查看帖子|查看全部|最后发表|最后回复|主题|回复|浏览|隐藏置顶帖/g,' ').replace(/\s+/g,' ').trim();if(t.length>230)t=t.slice(0,230)+'…';return t}
  function parseCards(html,base){var a=anchors(html,base),map={},order=[],out=[],freq={},i,x,id,t,sc,ctx,imgs,j,c;for(i=0;i<a.length;i++){x=a[i];id=threadId(x.href);if(!id)continue;t=trim(x.text);sc=threadScore(t);if(!map[id]){map[id]={id:id,title:sc>-900?t:'',url:toMobile(x.href),score:sc,index:x.index};order.push(id)}else if(sc>map[id].score){map[id].title=t;map[id].score=sc;map[id].url=toMobile(x.href);map[id].index=x.index}}
    for(i=0;i<order.length;i++){id=order[i];x=map[id];if(!x||badThreadText(x.title))continue;ctx=contextAround(html,x.index);imgs=allImages(ctx,base,8);x.imgs=imgs;x.summary=rowSummary(ctx,x.title);for(j=0;j<imgs.length;j++){c=canonical(imgs[j]);freq[c]=(freq[c]||0)+1}out.push(x);if(out.length>=100)break}
    for(i=0;i<out.length;i++){imgs=[];for(j=0;j<(out[i].imgs||[]).length;j++){c=canonical(out[i].imgs[j]);if((freq[c]||0)>=3)continue;imgs.push(out[i].imgs[j]);if(imgs.length>=6)break}out[i].imgs=imgs}return out}
  function fetchPage(u,pc){try{return s(fetchPC(u,{headers:headers(!!pc,u),timeout:15000}))}catch(e){return''}}
  function renderList(u){try{return s(fetchCodeByWebView(u,{headers:headers(false,u),timeout:22000,blockRules:['.woff','.woff2','.ttf'],checkJs:$.toString(function(ckKey,accessKey){var body=String((document.body&&document.body.innerText)||'').replace(/\s+/g,' ');if(/满\s*18\s*岁|年满\s*18|over\s*18|18\s*years|please\s*click\s*here/i.test(body)){var ns=document.querySelectorAll('a,button,input[type="button"],input[type="submit"],[onclick],[role="button"],div');for(var i=0;i<ns.length;i++){var t=String((ns[i].innerText||ns[i].textContent||ns[i].value||'')).replace(/\s+/g,' ').trim();if(/满\s*18\s*岁|over\s*18|please\s*click\s*here/i.test(t)){try{ns[i].click();return null}catch(e){}}}return null}try{var c=fba.getCookie(location.origin)||'';if(c)fba.putVar(ckKey,c);fba.putVar(accessKey,'1')}catch(e2){}return document.querySelector('a[href*="tid="],a[href*="thread-"]')?'ready':null},KEY_COOKIE,KEY_ACCESS)}))}catch(e){return''}}
  function previewCount(items){var n=0,i;for(i=0;i<(items||[]).length;i++)n+=(items[i].imgs||[]).length;return n}
  function mergePreview(primary,extra){var map={},i,j,x,seen;for(i=0;i<(extra||[]).length;i++)map[extra[i].id]=extra[i];for(i=0;i<(primary||[]).length;i++){x=map[primary[i].id];if(!x||!(x.imgs||[]).length)continue;seen={};for(j=0;j<(primary[i].imgs||[]).length;j++)seen[canonical(primary[i].imgs[j])]=1;for(j=0;j<x.imgs.length&&primary[i].imgs.length<6;j++)if(!seen[canonical(x.imgs[j])]){seen[canonical(x.imgs[j])]=1;primary[i].imgs.push(x.imgs[j])}}return primary}
  function loadBoardMobile(seed,pg){var mu=withPage(toMobile(seed),pg),pu=withPage(toPc(seed),pg),h,items,pcItems=[],diag=[];h=renderList(mu);items=parseCards(h,mu);diag.push('m-web:'+h.length+'/'+items.length+'/'+previewCount(items)+'img');if(!items.length){h=fetchPage(mu,false);items=parseCards(h,mu);diag.push('m-fetch:'+h.length+'/'+items.length+'/'+previewCount(items)+'img')}
    if(items.length&&previewCount(items)<Math.max(2,Math.floor(items.length/5))){h=fetchPage(pu,true);pcItems=parseCards(h,pu);diag.push('pc-enrich:'+h.length+'/'+pcItems.length+'/'+previewCount(pcItems)+'img');items=mergePreview(items,pcItems);if(previewCount(items)<2){h=renderList(pu);pcItems=parseCards(h,pu);diag.push('pc-web-enrich:'+h.length+'/'+pcItems.length+'/'+previewCount(pcItems)+'img');items=mergePreview(items,pcItems)}}
    if(!items.length){h=fetchPage(pu,true);items=parseCards(h,pu);diag.push('pc-fallback:'+h.length+'/'+items.length+'/'+previewCount(items)+'img')}return{items:items,url:mu,source:'mobile-first',diag:diag.join('；')}}
  function pageControls(path,params,pg,hasNext){var d=[],p1={},p3={},k;for(k in params){p1[k]=params[k];p3[k]=params[k]}p1.sht_p=Math.max(1,pg-1);p3.sht_p=pg+1;d.push({title:pg>1?'上一页':'第一页',url:pg>1?route(path,p1):'hiker://empty',col_type:'text_3',extra:{lineVisible:false}});d.push({title:'第 '+pg+' 页',url:'hiker://empty',col_type:'text_3',extra:{lineVisible:false}});d.push({title:hasNext?'下一页':'已到底',url:hasNext?route(path,p3):'hiker://empty',col_type:'text_3',extra:{lineVisible:false}});return d}
  function renderCards(d,items,ref){var i,j,it,u,p;for(i=0;i<items.length;i++){it=items[i];u=route('shtThread',{sht_url:toMobile(it.url),sht_name:it.title});d.push({title:it.title,desc:it.summary||'查看帖子',url:u,col_type:'text_1',extra:{lineVisible:false}});for(j=0;j<(it.imgs||[]).length;j++){p=imageUrl(it.imgs[j],ref);d.push({title:'',desc:'',img:p,pic_url:p,url:u,col_type:'pic_3',extra:{lineVisible:false}})}d.push(line())}}
  function forumBoard(){var d=[],seed=pageParam('sht_url',''),name=pageParam('sht_name','主题列表'),pg=Math.max(1,Number(pageParam('sht_p',typeof MY_PAGE==='undefined'?1:MY_PAGE||1))),r,params={sht_url:seed,sht_name:name},ctrl;setPageTitle(name);r=loadBoardMobile(seed,pg);saveDiag('forum.mobile.v12','p='+pg+' · '+r.diag);if(pg===1){d.push(quick('手机版','x5://'+withPage(toMobile(seed),1),'web.svg'));d.push(quick('搜索',route('shtSearch'),'search.svg'));d.push(line());d.push(section(name,'手机端优先 · 当前页 '+r.items.length+' 条主题 · '+previewCount(r.items)+' 张列表预览图'))}ctrl=pageControls('shtForum',params,pg,r.items.length>0);Array.prototype.push.apply(d,ctrl);d.push(line());renderCards(d,r.items,r.url);if(r.items.length){ctrl=pageControls('shtForum',params,pg,true);Array.prototype.push.apply(d,ctrl)}else d.push(empty('本页没有解析到主题','可打开手机版确认'));setResult(d)}
  function threadFetchMobile(url){var mu=toMobile(url),pu=toPc(url),h='',diag=[];h=renderThread(mu);diag.push('m-web:'+h.length+'/'+(hasThread(h)?'dom':'no'));if(hasThread(h))return{html:h,url:mu,diag:diag.join('；')};h=fetchPage(mu,false);diag.push('m-fetch:'+h.length+'/'+(hasThread(h)?'dom':'no'));if(hasThread(h))return{html:h,url:mu,diag:diag.join('；')};h=fetchPage(pu,true);diag.push('pc-fetch:'+h.length+'/'+(hasThread(h)?'dom':'no'));if(hasThread(h))return{html:h,url:pu,diag:diag.join('；')};h=renderThread(pu);diag.push('pc-web:'+h.length+'/'+(hasThread(h)?'dom':'no'));return{html:h,url:pu,diag:diag.join('；')}}
  function hasThread(h){return /id=["']postlist["']|class=["'][^"']*\bt_fsz\b|class=["'][^"']*\bt_f\b|id=["']postmessage_\d+|class=["'][^"']*\bmessage\b/i.test(s(h))}
  function renderThread(u){try{return s(fetchCodeByWebView(u,{headers:headers(false,u),timeout:24000,blockRules:['.woff','.woff2','.ttf'],checkJs:$.toString(function(ckKey,accessKey){var body=String((document.body&&document.body.innerText)||'').replace(/\s+/g,' ');if(/满\s*18\s*岁|年满\s*18|over\s*18|18\s*years|please\s*click\s*here/i.test(body)){var ns=document.querySelectorAll('a,button,input[type="button"],input[type="submit"],[onclick],[role="button"],div');for(var i=0;i<ns.length;i++){var t=String((ns[i].innerText||ns[i].textContent||ns[i].value||'')).replace(/\s+/g,' ').trim();if(/满\s*18\s*岁|over\s*18|please\s*click\s*here/i.test(t)){try{ns[i].click();return null}catch(e){}}}return null}try{var c=fba.getCookie(location.origin)||'';if(c)fba.putVar(ckKey,c);fba.putVar(accessKey,'1')}catch(e2){}return document.querySelector('#postlist .t_fsz,#postlist .t_f,[id^="postmessage_"],.message')?'ready':null},KEY_COOKIE,KEY_ACCESS)}))}catch(e){return''}}
  function extractFloors(html){var out=[],seen={},selectors=['body&&#postlist>div','body&&#postlist&&div[id^=post_]','body&&div.t_fsz','body&&div.t_f','body&&td.t_f','body&&[id^=postmessage_]','body&&.message'],i,j,nodes,body,author,key;for(i=0;i<selectors.length;i++){try{nodes=pdfa(html,selectors[i])||[]}catch(e){nodes=[]}for(j=0;j<nodes.length;j++){try{body=pdfh(nodes[j],'body&&div.t_fsz&&Html')||pdfh(nodes[j],'body&&div.t_f&&Html')||pdfh(nodes[j],'body&&td.t_f&&Html')||pdfh(nodes[j],'body&&.message&&Html')||pdfh(nodes[j],'body&&Html')||s(nodes[j])}catch(e2){body=s(nodes[j])}if(!trim(strip(body)))continue;try{author=trim(pdfh(nodes[j],'body&&.authi&&a&&Text')||pdfh(nodes[j],'body&&.xw1&&Text')||'')}catch(e3){author=''}key=strip(body).slice(0,220);if(key&&!seen[key]){seen[key]=1;out.push({body:body,author:author})}}if(out.length)break}return out}
  function textBlock(x){var y=s(x);y=y.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<iframe[\s\S]*?<\/iframe>/gi,'');y=y.replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/(?:p|div|li|tr|table|blockquote)>/gi,'\n').replace(/<[^>]+>/g,' ');y=hdec(y).replace(/\r/g,'').replace(/[ \t]+/g,' ').replace(/\n[ \t]+/g,'\n').replace(/\n{3,}/g,'\n\n').trim();return y}
  function escHtml(x){return s(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
  function emitText(d,t){t=trim(t);if(!t)return;d.push({title:escHtml(t).replace(/\n/g,'<br>'),url:'hiker://empty',col_type:'rich_text',extra:{lineVisible:false}})}
  function emitImages(d,buf,ref){var i,p,ct=buf.length===1?'pic_1_full':'pic_3';for(i=0;i<buf.length;i++){p=imageUrl(buf[i],ref);d.push({title:'',desc:'',img:p,pic_url:p,url:'pics://'+p,col_type:ct,extra:{lineVisible:false,imgLongClick:true}})}}
  function orderedBody(d,body,ref){var x=s(body),re=/<img\b[^>]*>/gi,m,last=0,buf=[],gap,u,t,parts=0;function flush(){if(buf.length){emitImages(d,buf,ref);parts+=buf.length;buf=[]}}while((m=re.exec(x))!==null){gap=x.slice(last,m.index);t=textBlock(gap);if(t){flush();emitText(d,t);parts++}u=imgFromTag(m[0],ref);if(u){if(!buf.some(function(z){return canonical(z)===canonical(u)}))buf.push(u)}last=re.lastIndex}t=textBlock(x.slice(last));if(t){flush();emitText(d,t);parts++}flush();return parts}
  function magnetList(x){var t=hdec(s(x)),out=[],seen={},m,re=/magnet:\?xt=urn:btih:[a-z0-9]{32,40}(?:&[^\s"'<>]*)?/ig,v,hm,key;while((m=re.exec(t))!==null){v=m[0].replace(/[)\]}>，。；;]+$/g,'');hm=v.match(/btih:([a-z0-9]{32,40})/i);key=hm?hm[1].toUpperCase():v.toLowerCase();if(!seen[key]){seen[key]=1;out.push({url:v,key:key,hash:hm?hm[1]:''})}if(out.length>=20)break}return out}
  function videoUrls(x){var out=[],seen={},m,re=/(https?:\/\/[^\s"'<>]+?\.(?:m3u8|mp4)(?:\?[^\s"'<>]*)?)/ig,u;while((m=re.exec(hdec(s(x))))!==null){u=m[1].replace(/[)\]}>，。；;]+$/g,'');if(!seen[u]){seen[u]=1;out.push(u)}if(out.length>=6)break}return out}
  function sniffSeed(x,base){var m=s(x).match(/<iframe\b[^>]*(?:src|data-src)\s*=\s*["']([^"']+)["']/i),u=m?abs(m[1],base):'';return u||base}
  function replyUrl(html,base){var m=s(html).match(/href=["']([^"']*(?:mod=post[^"']*action=reply|action=reply[^"']*mod=post)[^"']*)["']/i);return m?abs(m[1],base):base}
  function thread(){var d=[],url=toMobile(pageParam('sht_url','')),title=pageParam('sht_name','帖子详情'),r,floors,i,j,body,author,ms,allMs,seenMag={},videos,videoHint,seed,ref,parts;if(!url){setResult([empty('帖子参数缺失')]);return}setPageTitle(title||'帖子详情');r=threadFetchMobile(url);ref=r.url||url;floors=extractFloors(r.html);saveDiag('thread.mobile.v12',r.diag+' · floors='+floors.length);d.push(section(title||'帖子详情','手机端正文优先 · 图片按原文顺序穿插显示'));d.push(quick('手机版','x5://'+toMobile(url),'web.svg'));d.push(quick('回复','x5://'+replyUrl(r.html,ref),'reply.svg'));d.push(quick('复制链接','copy://'+url,'copy.svg'));d.push(quick('设置',route('shtSettings'),'settings.svg'));d.push(line());if(!floors.length){d.push(empty('未识别到帖子正文','已先尝试手机端，再回退电脑端'));setResult(d);return}for(i=0;i<floors.length&&i<20;i++){body=floors[i].body;author=floors[i].author||'';d.push(section(i===0?'楼主'+(author?' · '+author:''):'回复 '+i+(author?' · '+author:''),'按原文顺序显示文字与图片'));parts=orderedBody(d,body,ref);allMs=magnetList(body);ms=[];for(j=0;j<allMs.length;j++)if(!seenMag[allMs[j].key]){seenMag[allMs[j].key]=1;ms.push(allMs[j])}videos=videoUrls(body);videoHint=videos.length>0||/<video\b|<iframe\b|视频加载中|在线播放|dplayer|ckplayer|jwplayer|m3u8|\.mp4/i.test(body);seed=sniffSeed(body,ref);if(videos.length)d.push({title:'▶ 直接播放',desc:'已识别视频直链',url:videos[0]+'#isVideo=true#',col_type:'text_center_1',extra:{lineVisible:false}});if(videoHint)d.push({title:'▶ 嗅探播放',desc:'使用海阔自动提取网页视频',url:'video://'+seed,col_type:'text_center_1',extra:{lineVisible:false,ua:UA_M,referer:toMobile(url),blockRules:['.jpg','.png','.gif','.woff','.woff2','.ttf'],cacheM3u8:true}});for(j=0;j<ms.length;j++){var magnet=ms[j].url,hash=ms[j].hash;d.push({title:'磁链 '+(j+1),desc:hash?hash.slice(0,14)+'…':'已识别',url:'copy://'+magnet,col_type:'text_1',extra:{lineVisible:false}});d.push(quick('115','hiker://page/115Offline?rule=115.简&page=fypage&add='+encodeURIComponent(magnet),'cloud115.svg'));d.push(quick('迅雷','hiker://page/diaoyong?rule=迅雷&page=fypage#'+magnet,'thunder.svg'));d.push(quick('PikPak','pikpakapp://mypikpak.com/xpan/main_tab?tab=1&add_url='+magnet,'pikpak.svg'));d.push(quick('复制','copy://'+magnet,'copy.svg'))}if(!parts&&!ms.length&&!videoHint)d.push(empty('本层没有可显示正文'));d.push(line())}setResult(d)}
  function settings(){var d=[],dg={};setPageTitle('色花堂设置');d.push(section('Test12 手机端优先与图片顺序','板块列表/帖子正文优先 mobile=2；电脑端只在手机端缺预览或正文失败时兜底。帖子正文不再把图片集中到末尾，而是按原文顺序穿插。'));try{dg=JSON.parse(getItem(KEY_DIAG,'{}')||'{}')}catch(e){}d.push({title:'最近诊断',desc:(dg.stage||'暂无')+'\n'+(dg.error||''),url:'hiker://empty',col_type:'long_text'});d.push({title:'打开旧设置',desc:'分类缓存 / 访问状态 / Cookie',url:route('shtSettingsLegacy'),col_type:'text_1'});setResult(d)}
  function module(){var m=BASE.module(),prevForum=m.forum;m.version=VERSION;m.build=BUILD;m.forum=function(){var kind=pageParam('sht_auto','');if(kind)return prevForum();return forumBoard()};m.thread=thread;m.settings=settings;m._debug=m._debug||{};m._debug.parseCardsV12=parseCards;m._debug.threadFetchMobileV12=threadFetchMobile;return m}
  var PATCHED={version:VERSION,build:BUILD,module:module};SeHuaTangRemoteRuntime=PATCHED;return PATCHED;
})();