/* MyAv 0.1.1-test.5 · JavDB-style custom search UI + icons */
var MyAvSearchUi10205=(function(){
var VERSION='0.1.1-test.5',BUILD=10205;
var ROOT='hiker://files/rules/asset-core-local/myav-test/b10205/';
var BASE_ENTRY=ROOT+'base_011t4_entry.js';
var BASE_REF='83d59bc3eadc1ed3c56bae50d9a6e8e4bac2d03a';
var BASE_PATH='apps/video/myav/releases/0.1.1-test.4/local_entry.js';
var SEARCH_KEY='myav_external_search_targets_v1';
var STYLE_KEY='myav_external_search_style_v1';
var SELECT_KEY='myav_external_search_selected_v1';
var BASE_CACHE=null;
function S(v){return v==null?'':String(v);}
function bad(t){t=S(t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function urls(ref,path){return['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/'+ref+'/'+path,'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@'+ref+'/'+path,'https://github.com/huoguotiankong/asset-core-7f3/raw/'+ref+'/'+path];}
function ensureFile(local,ref,path,marker){if(fileExist(local)){try{var old=S(readFile(local));if(!bad(old)&&old.indexOf(marker)>=0)return local;}catch(_e){}try{deleteFile(local);}catch(_e2){}}var us=urls(ref,path),es=[],i,s='';for(i=0;i<us.length;i++){try{s=S(fetch(us[i],{timeout:6500,headers:{'Cache-Control':'public, max-age=31536000, immutable'}}));if(bad(s)||s.indexOf(marker)<0)throw new Error('无效响应');writeFile(local,s);if(!fileExist(local))throw new Error('写入失败');return local;}catch(e){es.push((i+1)+':'+S(e.message||e));}}throw new Error(path+' 下载失败：'+es.join(' | '));}
function base(){if(BASE_CACHE&&typeof BASE_CACHE.module==='function')return BASE_CACHE;ensureFile(BASE_ENTRY,BASE_REF,BASE_PATH,'0.1.1-test.4');var src=S(readFile(BASE_ENTRY)),MyAvLocal=null;if(bad(src)||src.indexOf('0.1.1-test.4')<0)throw new Error('MyAv Test4 Base Entry 内容无效');eval(src);if(!MyAvLocal||typeof MyAvLocal.module!=='function')throw new Error('MyAv Test4 Base Entry 未导出');BASE_CACHE=MyAvLocal;return BASE_CACHE;}
function parseJson(s,d){try{return JSON.parse(S(s));}catch(e){return d;}}
function targets(){var a=parseJson(getItem(SEARCH_KEY,'[]'),[]),out=[],seen={},i,x,n,r,ic;if(!(a instanceof Array))a=[];for(i=0;i<a.length;i++){x=a[i]||{};r=S(x.rule||x.name).trim();n=S(x.name||r).trim();ic=S(x.icon||x.pic||x.img||x.pic_url||x.image).trim();if(!r||seen[r.toLowerCase()])continue;seen[r.toLowerCase()]=1;out.push({name:n||r,rule:r,icon:ic});}return out;}
function saveTargets(a){setItem(SEARCH_KEY,JSON.stringify(a||[]));return a||[];}
function parseHome(raw){var s=S(raw).trim(),p=s.indexOf('￥home_rule￥');if(p>=0)s=s.substring(p+'￥home_rule￥'.length);else{p=s.indexOf('{');if(p>=0)s=s.substring(p);}try{return JSON.parse(s);}catch(e){return null;}}
function ruleInfo(rule){var raw='';try{raw=S(request('hiker://home@'+rule));}catch(e){try{raw=S(fetch('hiker://home@'+rule));}catch(_e){raw='';}}return raw&&raw!=='null'?parseHome(raw):null;}
function iconCacheKey(rule){var s=S(rule),h=0,i;for(i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return'myav_ext_icon_'+Math.abs(h);}
function targetIcon(t,fallback){if(t&&t.icon)return t.icon;var rule=S(t&&t.rule),k=iconCacheKey(rule),c=getItem(k,'');if(c)return c;var o=ruleInfo(rule),ic=S(o&&(o.icon||o.pic_url||o.img||o.pic)).trim();if(ic){setItem(k,ic);return ic;}if(/磁力|magnet/i.test(rule))return'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/myav/assets/magnet.svg';return fallback||'hiker://images/icon_search';}
function displayStyle(){var s=getItem(STYLE_KEY,'icon_round_small_4');return s==='icon_small_4'?'icon_small_4':'icon_round_small_4';}
function section(title,desc){return{title:'▌ '+title,desc:desc||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}};}
function isSection(x){return /^▌\s*/.test(S(x&&x.title));}
function isCustomSection(x){return /^▌\s*自定义搜索/.test(S(x&&x.title));}
function detailKeyword(items){var i,t,m;for(i=0;i<items.length;i++){t=S(items[i]&&items[i].title);m=t.match(/^番号\s*[·・:]\s*(.+)$/);if(m)return S(m[1]).trim();}for(i=0;i<items.length;i++){t=S(items[i]&&items[i].desc);m=t.match(/\b(?:FC2[-_ ]?(?:PPV[-_ ]?)?\d{4,}|[A-Za-z]{2,12}[-_. ]?\d{2,6}(?:[-_.][A-Za-z0-9]+)*)\b/i);if(m)return S(m[0]).trim().replace(/[ _]+/g,'-');}try{var u=S(MY_PARAMS&&MY_PARAMS.code);if(u)return u;}catch(e){}return'';}
function capture(run,patch){var oldSet=null,got=null,hooked=false,err=null,ret=null;try{oldSet=setResult;var cap=function(v){got=v;};setResult=cap;hooked=(setResult===cap);}catch(e){hooked=false;}if(!hooked){ret=run();return ret instanceof Array?patch(ret):ret;}try{ret=run();}catch(e2){err=e2;}finally{try{setResult=oldSet;}catch(_e){}}if(err)throw err;if(got instanceof Array)return oldSet(patch(got));if(got!=null)return oldSet(got);return ret instanceof Array?patch(ret):ret;}
function stripCustom(items){if(!(items instanceof Array))return items;var out=[],i=0,j;while(i<items.length){if(isCustomSection(items[i])){j=i+1;while(j<items.length&&!isSection(items[j]))j++;i=j;continue;}out.push(items[i]);i++;}return out;}
function searchBlock(C,kw,fallbackIcon){var a=targets(),d=[section('自定义搜索',a.length?'用当前番号调用其它小程序搜索':'还没有配置搜索站点')],i,t,ic,style=displayStyle();if(!a.length){d.push({title:'添加搜索站点',pic_url:'hiker://images/icon_add',img:'hiker://images/icon_add',url:'hiker://page/myavExternalSearch?rule=MyAv&simple=true',col_type:style,extra:{lineVisible:false}});return d;}for(i=0;i<a.length;i++){t=a[i];ic=targetIcon(t,fallbackIcon);d.push({title:t.name,pic_url:ic,img:ic,url:C.externalSearchUrl(t.rule,kw),col_type:style,extra:{lineVisible:false,pageTitle:t.name+' · '+kw}});}return d;}
function patchDetail(items,C){if(!(items instanceof Array))return items;var kw=detailKeyword(items),clean=stripCustom(items),blk=searchBlock(C,kw,C.appIcon||''),i,at=-1;if(!kw)return clean;for(i=0;i<clean.length;i++){if(/^▌\s*快捷操作/.test(S(clean[i]&&clean[i].title))){at=i+1;while(at<clean.length&&!isSection(clean[at]))at++;break;}}if(at<0){for(i=0;i<clean.length;i++){if(/^▌\s*(简介|原站预览视频|影片资料|档案)/.test(S(clean[i]&&clean[i].title))){at=i;break;}}}if(at<0)at=clean.length;Array.prototype.splice.apply(clean,[at,0].concat(blk));return clean;}
function patchSearch(items,C,kw){if(!(items instanceof Array)||!kw)return items;var start=-1,end=-1,i;for(i=0;i<items.length;i++){if(isCustomSection(items[i])){start=i;end=i+1;while(end<items.length&&!isSection(items[end]))end++;break;}}if(start<0)return items;var blk=searchBlock(C,kw,C.appIcon||'');items.splice(start,end-start);Array.prototype.splice.apply(items,[start,0].concat(blk));return items;}
function selectedIndex(a){var n=parseInt(getMyVar(SELECT_KEY,'0'),10);if(isNaN(n)||n<0)n=0;if(a.length&&n>=a.length)n=a.length-1;if(!a.length)n=0;return n;}
function managerPage(C){var d=[],a=targets(),idx=selectedIndex(a),cur=a[idx]||null,i,t,style=displayStyle();setPageTitle('自定义搜索');d.push({title:'自定义搜索',desc:'当前 '+a.length+' 个\n展示样式：'+style,url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});if(a.length){for(i=0;i<a.length;i++){t=a[i];d.push({title:(i+1)+'. '+t.name,desc:(i===idx?'● 当前编辑项 · ':'')+'规则：'+t.rule,pic_url:targetIcon(t,C.appIcon||''),img:targetIcon(t,C.appIcon||''),url:$('#noLoading#').lazyRule(function(n){putMyVar('myav_external_search_selected_v1',String(n));refreshPage(false);return'hiker://empty';},i),col_type:'text_icon',extra:{lineVisible:false}});}}else d.push({title:'还没有自定义搜索站点',desc:'点击“＋ 添加”配置第一个目标',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}});
d.push({title:'＋ 添加',url:$('','显示名@@小程序名@@图片链接').input(function(key){var s=String(input||'').trim(),p=s.indexOf('@@')>=0?s.split('@@'):s.split('|'),name=String(p[0]||'').trim(),rule=String(p[1]||p[0]||'').trim(),icon=String(p[2]||'').trim(),a=[];if(!rule)return'toast://请输入小程序名';try{a=JSON.parse(getItem(key,'[]'));}catch(e){a=[];}if(!(a instanceof Array))a=[];for(var i=0;i<a.length;i++)if(String(a[i]&&a[i].rule||'')===rule)return'toast://已存在 '+rule;if(!icon){var raw='';try{raw=String(request('hiker://home@'+rule)||'');}catch(e2){try{raw=String(fetch('hiker://home@'+rule)||'');}catch(_e){raw='';}}if(raw&&raw!=='null'){var x=raw.indexOf('￥home_rule￥');if(x>=0)raw=raw.substring(x+'￥home_rule￥'.length);else{x=raw.indexOf('{');if(x>=0)raw=raw.substring(x);}try{var o=JSON.parse(raw);icon=String(o.icon||o.pic_url||o.img||o.pic||'').trim();}catch(_e2){}}}a.push({name:name||rule,rule:rule,icon:icon});setItem(key,JSON.stringify(a));putMyVar('myav_external_search_selected_v1',String(a.length-1));refreshPage(false);return'toast://已添加 '+(name||rule);},SEARCH_KEY),col_type:'flex_button',extra:{lineVisible:false}});
if(cur){var pre=cur.name+'@@'+cur.rule+'@@'+(cur.icon||'');d.push({title:'✎ 修改',url:$(pre,'显示名@@小程序名@@图片链接').input(function(key,idx){var s=String(input||'').trim(),p=s.indexOf('@@')>=0?s.split('@@'):s.split('|'),name=String(p[0]||'').trim(),rule=String(p[1]||p[0]||'').trim(),icon=String(p[2]||'').trim(),a=[];if(!rule)return'toast://请输入小程序名';try{a=JSON.parse(getItem(key,'[]'));}catch(e){a=[];}if(!(a instanceof Array)||!a[idx])return'toast://目标不存在';a[idx]={name:name||rule,rule:rule,icon:icon};setItem(key,JSON.stringify(a));refreshPage(false);return'toast://已修改 '+(name||rule);},SEARCH_KEY,idx),col_type:'flex_button',extra:{lineVisible:false}});
d.push({title:'− 删除',url:$(['取消','删除 '+cur.name],1,'确认删除').select(function(key,idx){if(String(input||'').indexOf('删除 ')!==0)return'hiker://empty';var a=[];try{a=JSON.parse(getItem(key,'[]'));}catch(e){a=[];}if(!(a instanceof Array)||!a[idx])return'toast://目标不存在';var n=String(a[idx].name||a[idx].rule||'目标');a.splice(idx,1);setItem(key,JSON.stringify(a));var ni=Math.max(0,Math.min(idx,a.length-1));putMyVar('myav_external_search_selected_v1',String(ni));refreshPage(false);return'toast://已删除 '+n;},SEARCH_KEY,idx),col_type:'flex_button',extra:{lineVisible:false}});
d.push({title:'↕ 排序',url:$(['移到最前','上移','下移','移到最后'],1,'调整 '+cur.name).select(function(key,idx){var op=String(input||''),a=[];try{a=JSON.parse(getItem(key,'[]'));}catch(e){a=[];}if(!(a instanceof Array)||!a[idx])return'toast://目标不存在';var to=idx;if(op==='移到最前')to=0;else if(op==='上移')to=Math.max(0,idx-1);else if(op==='下移')to=Math.min(a.length-1,idx+1);else if(op==='移到最后')to=a.length-1;var x=a.splice(idx,1)[0];a.splice(to,0,x);setItem(key,JSON.stringify(a));putMyVar('myav_external_search_selected_v1',String(to));refreshPage(false);return'toast://已调整顺序';},SEARCH_KEY,idx),col_type:'flex_button',extra:{lineVisible:false}});}else{d.push({title:'✎ 修改',url:'toast://请先添加搜索站点',col_type:'flex_button',extra:{lineVisible:false}});d.push({title:'− 删除',url:'toast://请先添加搜索站点',col_type:'flex_button',extra:{lineVisible:false}});d.push({title:'↕ 排序',url:'toast://请先添加搜索站点',col_type:'flex_button',extra:{lineVisible:false}});}
d.push({title:'显示样式 · '+style,url:$(['icon_round_small_4','icon_small_4'],1,'自定义搜索展示样式').select(function(key){setItem(key,String(input||'icon_round_small_4'));refreshPage(false);return'toast://已切换 '+String(input||'');},STYLE_KEY),col_type:'flex_button',extra:{lineVisible:false}});
d.push({title:'清空自定义搜索',url:$(['取消','确认清空'],1,'清空全部自定义搜索').select(function(key){if(String(input||'')!=='确认清空')return'hiker://empty';setItem(key,'[]');clearMyVar('myav_external_search_selected_v1');refreshPage(false);return'toast://已清空';},SEARCH_KEY),col_type:'text_center_1',extra:{lineVisible:false}});
d.push({title:'配置格式',desc:'显示名@@小程序名@@图片链接\n图片链接可留空：优先自动读取目标小程序图标；旧版“显示名|规则名”配置继续兼容。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});setResult(d);}
function module(){var b=base(),m=b.module();if(!m||typeof m.core!=='function')throw new Error('MyAv Test4 Module 未就绪');var C=m.core();if(typeof m.detail==='function'){var od=m.detail;m.detail=function(){return capture(function(){return od.call(m);},function(items){return patchDetail(items,C);});};}if(typeof m.search==='function'){var os=m.search;m.search=function(){var kw='';try{kw=S(getMyVar('myav_search_kw','')).trim();}catch(e){}return capture(function(){return os.call(m);},function(items){return patchSearch(items,C,kw);});};}m.externalSearch=function(){managerPage(C);};m.version=VERSION;m.build=BUILD;m.baseVersion='0.1.1-test.4';m.externalSearchUi='javdb-style-icon-v2';return m;}
function info(){var x={};try{x=base().info?base().info():{};}catch(e){x={};}x.version=VERSION;x.build=BUILD;x.baseVersion='0.1.1-test.4';x.externalSearchUi='javdb-style-icon-v2';x.externalSearchStyle=displayStyle();x.externalSearchTargets=targets().length;return x;}
function statusPage(){setPageTitle('MyAv · Test5 自定义搜索');setResult([{title:VERSION+' / Build '+BUILD,desc:'继承 Test4 搜索适配与 Test3 已验证磁链云盘调用；本轮只调整自定义搜索 UI/配置',url:'hiker://empty',col_type:'text_1'},{title:'详情位置',desc:'自定义搜索移动到“快捷操作”图标组之后',url:'hiker://empty',col_type:'text_1'},{title:'图标',desc:'默认 icon_round_small_4；配置格式：显示名@@小程序名@@图片链接',url:'hiker://empty',col_type:'text_1'},{title:'兼容',desc:'旧 myav_external_search_targets_v1 配置继续读取；图片链接为空时尝试读取目标规则 icon',url:'hiker://empty',col_type:'text_1'}]);}
return{version:VERSION,build:BUILD,module:module,info:info,statusPage:statusPage};
})();
var MyAvLocal=MyAvSearchUi10205;
