/* xChina Remote Runtime 0.1.0-test.1 - multi-content HTML implementation */
var XChinaRemoteRuntime=(function(){
  var X={};
  X.version='0.1.0-test.1';
  X.build=10101;
  X.ua='Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/139.0 Mobile Safari/537.36';
  X.defaultBase='https://xchina.co';
  X.latestBase='https://xchina001.ink';
  X.baseKey='xc_base_v1';
  X.lastBaseKey='xc_last_good_base_v1';
  X.cachePrefix='xc_t1_';
  X.brand='#f3a6c8';

  function s(v){return v===undefined||v===null?'':String(v);}
  function trim(v){return s(v).replace(/^\s+|\s+$/g,'');}
  function decode(v){return s(v).replace(/&amp;/ig,'&').replace(/&quot;/ig,'"').replace(/&#39;|&apos;/ig,"'").replace(/&nbsp;/ig,' ').replace(/&lt;/ig,'<').replace(/&gt;/ig,'>').replace(/&#x27;/ig,"'");}
  function strip(v){return trim(decode(s(v).replace(/<br\s*\/?\s*>/ig,'\n').replace(/<script\b[\s\S]*?<\/script>/ig,' ').replace(/<style\b[\s\S]*?<\/style>/ig,' ').replace(/<[^>]+>/g,' ')).replace(/[\t\r ]+/g,' ').replace(/\n\s+/g,'\n'));}
  function esc(v){return s(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
  function q(v){return encodeURIComponent(s(v));}
  function uniq(a,key){var o=[],seen={},i,k;for(i=0;i<(a||[]).length;i++){k=key?key(a[i]):s(a[i]);if(!k||seen[k])continue;seen[k]=1;o.push(a[i]);}return o;}
  function hash(v){v=s(v);var h=0,i;for(i=0;i<v.length;i++)h=((h<<5)-h+v.charCodeAt(i))|0;return Math.abs(h);}
  function ruleTitle(){try{return MY_RULE&&MY_RULE.title?MY_RULE.title:'小黄书';}catch(e){return'小黄书';}}
  function param(name,def){var u='';try{u=s(MY_URL);}catch(e){}var m=u.match(new RegExp('[?&]'+esc(name)+'=([^&#]*)'));if(!m)return def===undefined?'':def;try{return decodeURIComponent(m[1]);}catch(e2){return m[1];}}
  function page(path,p){var a=['rule='+encodeURIComponent(ruleTitle()),'simple=true'];p=p||{};for(var k in p)if(p.hasOwnProperty(k)&&p[k]!==undefined&&p[k]!==null&&s(p[k])!=='')a.push(encodeURIComponent(k)+'='+encodeURIComponent(s(p[k])));return'hiker://page/'+path+'?'+a.join('&');}
  function origin(u){var m=s(u).match(/^(https?:\/\/[^\/]+)/i);return m?m[1]:base();}
  function abs(u,b){u=decode(trim(u));b=b||base();if(!u)return'';if(/^https?:\/\//i.test(u))return u;if(/^\/\//.test(u))return'https:'+u;if(/^data:|^javascript:|^#/.test(u))return'';var o=origin(b);if(u.charAt(0)==='/')return o+u;if(u.charAt(0)==='?')return s(b).replace(/[?#].*$/,'')+u;return s(b).replace(/[?#].*$/,'').replace(/[^\/]*$/,'')+u;}
  function base(){var b=trim(getItem(X.baseKey,''));if(/^https?:\/\//i.test(b))return b.replace(/\/+$/,'');b=trim(getItem(X.lastBaseKey,''));if(/^https?:\/\//i.test(b))return b.replace(/\/+$/,'');return X.defaultBase;}
  function domains(){var out=[],custom=trim(getItem(X.baseKey,'')),last=trim(getItem(X.lastBaseKey,''));if(custom)out.push(custom);if(last)out.push(last);out.push(X.defaultBase,X.latestBase);return uniq(out,function(v){return s(v).replace(/\/+$/,'');});}
  function headers(ref,accept){return{'User-Agent':X.ua,'Referer':origin(ref||base())+'/','Origin':origin(ref||base()),'Accept':accept||'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Accept-Language':'zh-CN,zh;q=0.9,en;q=0.7'};}
  function isBlocked(body){var z=s(body),l=z.toLowerCase();return !z||z.length<100||l.indexOf('just a moment')>=0||l.indexOf('cf-chl-')>=0||l.indexOf('attention required')>=0||l.indexOf('checking your browser')>=0||l.indexOf('captcha')>=0&&z.length<5000;}
  function sameSite(u){return /https?:\/\/(?:[^\/]*\.)?(?:xchina\.[^\/]+|xchina\d*\.[^\/]+)/i.test(s(u));}
  function pathOf(u){var m=s(u).match(/^https?:\/\/[^\/]+(\/[^#]*)?/i);return m?(m[1]||'/'):s(u);}
  function fetchPage(input,opt){opt=opt||{};var raw=s(input||'/'),candidates=[],i,d,u,body='',best='',bestUrl='';if(/^https?:\/\//i.test(raw)&&!sameSite(raw)){try{body=s(fetch(raw,{timeout:opt.timeout||12000,headers:headers(opt.ref||raw,opt.accept)}));}catch(e0){body='';}return{body:body,url:raw,blocked:isBlocked(body),domain:origin(raw)};}
    var p=/^https?:\/\//i.test(raw)?pathOf(raw):raw;if(p.charAt(0)!=='/')p='/'+p;d=domains();for(i=0;i<d.length;i++)candidates.push(d[i].replace(/\/+$/,'')+p);
    for(i=0;i<candidates.length;i++){u=candidates[i];var ck=X.cachePrefix+hash(u),tk=ck+'_t',now=Date.now(),ttl=opt.ttl===undefined?180000:opt.ttl,old=getItem(ck,''),ts=parseInt(getItem(tk,'0'),10)||0;if(!opt.force&&old&&now-ts<ttl)return{body:old,url:u,blocked:false,domain:origin(u),cache:true};try{body=s(fetch(u,{timeout:opt.timeout||12000,headers:headers(opt.ref||u,opt.accept)}));}catch(e1){body='';}if(body.length>best.length){best=body;bestUrl=u;}if(!isBlocked(body)){try{setItem(X.lastBaseKey,origin(u));if(body.length<350000){setItem(ck,body);setItem(tk,String(now));}}catch(e2){}return{body:body,url:u,blocked:false,domain:origin(u),cache:false};}}
    return{body:best,url:bestUrl||candidates[0],blocked:true,domain:origin(bestUrl||candidates[0])};}
  function attr(tag,name){var m=s(tag).match(new RegExp('(?:^|\\s)'+esc(name)+'\\s*=\\s*["\\\']([^"\\\']*)["\\\']','i'));return m?decode(m[1]):'';}
  function meta(html,key){var k=esc(key),m=s(html).match(new RegExp('<meta[^>]+(?:property|name)=["\\\']'+k+'["\\\'][^>]+content=["\\\']([^"\\\']+)["\\\']','i'));if(!m)m=s(html).match(new RegExp('<meta[^>]+content=["\\\']([^"\\\']+)["\\\'][^>]+(?:property|name)=["\\\']'+k+'["\\\']','i'));return m?decode(m[1]):'';}
  function titleOf(html,fallback){var t=meta(html,'og:title')||meta(html,'twitter:title'),m;if(t)return strip(t).replace(/\s*-\s*小黄书.*$/,'');m=s(html).match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i);if(m)return strip(m[1]);m=s(html).match(/<title\b[^>]*>([\s\S]*?)<\/title>/i);return m?strip(m[1]).replace(/\s*-\s*小黄书.*$/,''):(fallback||'详情');}
  function imgFrom(raw,b){var re=/<img\b[^>]*(?:data-poster|data-original|data-src|src)\s*=\s*["']([^"']+)["'][^>]*>/ig,m;while((m=re.exec(s(raw)))){var u=abs(m[1],b);if(u&&!/logo|avatar-default|poster\.jpg/i.test(u))return u;}return'';}
  function image(u,ref){u=abs(u,ref||base());if(!u)return'';return u+'@headers='+JSON.stringify({'User-Agent':X.ua,'Referer':origin(ref||base())+'/'});}
  function anchors(html,b){var out=[],re=/<a\b([^>]*)href\s*=\s*["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/ig,m;while((m=re.exec(s(html)))){var href=abs(m[2],b),raw=m[0];if(!href)continue;out.push({href:href,raw:raw,text:strip(m[4]),title:attr(m[1]+' '+m[3],'title'),img:imgFrom(raw,href),index:m.index,cls:attr(m[1]+' '+m[3],'class')});}return out;}
  function ctx(html,index,before,after){html=s(html);return html.substring(Math.max(0,index-(before||500)),Math.min(html.length,index+(after||1200)));}
  function cardTitle(a,c){var t=trim(a.title||a.text);if(t&&t.length<180)return t;var m=s(c).match(/(?:alt|title)=["']([^"']{2,180})["']/i);return m?strip(m[1]):'未命名';}
  function duration(c){var m=s(c).match(/class=["'][^"']*duration[^"']*["'][^>]*>([\s\S]{0,80}?)<\//i)||s(c).match(/\b(\d{1,2}:\d{2}(?::\d{2})?)\b/);return m?strip(m[1]||m[0]):'';}
  function parseBy(html,b,re,type){var a=anchors(html,b),out=[],seen={},i,it,c,t,img,desc;for(i=0;i<a.length;i++){it=a[i];if(!re.test(it.href)||seen[it.href])continue;c=ctx(html,it.index,700,1400);t=cardTitle(it,c);img=it.img||imgFrom(c,it.href);desc=duration(c);seen[it.href]=1;out.push({type:type,url:it.href,title:t,img:image(img,it.href),rawImg:img,desc:desc});}return out;}
  function parseVideos(html,b){return parseBy(html,b,/\/video\/id-[^\/?#]+\.html/i,'video');}
  function parsePhotos(html,b){return parseBy(html,b,/\/(?:photo|amateur)\/id-[^\/?#]+\.html/i,'photo');}
  function parseFictions(html,b){return parseBy(html,b,/\/fiction\/id-[^\/?#]+\.html/i,'fiction');}
  function parseModels(html,b){return parseBy(html,b,/\/model\/id-[^\/?#]+\.html/i,'model');}
  function parseAny(html,b,kind){if(kind==='video')return parseVideos(html,b);if(kind==='photo')return parsePhotos(html,b);if(kind==='fiction')return parseFictions(html,b);if(kind==='model')return parseModels(html,b);return[];}
  function nextUrl(html,b){var a=anchors(html,b),i,t;for(i=0;i<a.length;i++){t=(a[i].text+' '+a[i].cls).toLowerCase();if(/下一页|next/.test(t)||/\bnext\b/.test(a[i].cls||''))return a[i].href;}return'';}
  function kindRoot(kind){return kind==='photo'?'/photos.html':kind==='fiction'?'/fictions.html':kind==='model'?'/models.html':'/videos.html';}
  function kindName(kind){return kind==='photo'?'套图写真':kind==='fiction'?'成人小说':kind==='model'?'模特人物':'成人影片';}
  function detailRoute(it){if(it.type==='photo')return page('xchinaPhoto',{url:it.url,title:it.title});if(it.type==='fiction')return page('xchinaFiction',{url:it.url,title:it.title});if(it.type==='model')return page('xchinaModel',{url:it.url,title:it.title});return page('xchinaVideo',{url:it.url,title:it.title});}
  function pushCards(d,list,limit){var n=Math.min(list.length,limit||list.length),i,it;for(i=0;i<n;i++){it=list[i];d.push({title:it.title,desc:it.desc||kindName(it.type),img:it.img||'',pic_url:it.img||'',url:detailRoute(it),col_type:it.type==='fiction'?'text_2':'movie_2',extra:{lineVisible:false}});}}
  function section(t,desc){return{title:'““””<b>'+t+'</b>',desc:desc||'',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}};}
  function text(t,desc,url){return{title:t,desc:desc||'',url:url||'hiker://empty',col_type:'text_1',extra:{lineVisible:false}};}
  function nav(t,sub,ico,url){return{title:t,desc:sub||'',img:ico||'',url:url,col_type:'icon_4',extra:{lineVisible:false}};}
  function empty(t,desc){return{text:t,title:t,desc:desc||'',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}};}
  function web(u){return'web://'+u;}

  function home(){var d=[],r,list;setPageTitle('小黄书 · Test');d.push({title:'小黄书 xChina',desc:'Test 0.1.0-test.1 · 多内容类型 · '+base().replace(/^https?:\/\//,''),url:page('xchinaSettings'),col_type:'avatar',img:'https://xchina.co/favicon.ico',extra:{lineVisible:false}});d.push(nav('影片','分类/搜索','',page('xchinaCatalog',{kind:'video'})));d.push(nav('套图','图片/附带视频','',page('xchinaCatalog',{kind:'photo'})));d.push(nav('小说','独立阅读页','',page('xchinaCatalog',{kind:'fiction'})));d.push(nav('模特','人物/作品','',page('xchinaCatalog',{kind:'model'})));d.push({col_type:'line'});d.push(section('最新影片','优先加载站点视频首页'));
    r=fetchPage('/videos.html',{ttl:120000});list=parseVideos(r.body,r.url);if(list.length)pushCards(d,list,12);else{d.push(empty('暂未解析到影片',r.blocked?'当前线路被 Cloudflare/网络拦截，可进设置切换域名。':'页面结构可能变化，先用网页入口继续访问。'));d.push(text('🌐 打开网站视频页','网页兜底',web(r.url||base()+'/videos.html')));}d.push({col_type:'line'});d.push(text('🔎 搜索全部内容','海阔顶部搜索也可直接使用',page('xchinaSearch')));d.push(text('⚙ 设置与线路诊断','切换域名 / 查看当前线路',page('xchinaSettings')));setResult(d);}

  function catalog(){var kind=param('kind','video'),u=param('url',''),d=[],r,list,next;setPageTitle(kindName(kind));u=u||kindRoot(kind);r=fetchPage(u,{ttl:120000});list=parseAny(r.body,r.url,kind);d.push(section(kindName(kind),(list.length?list.length+' 条':'当前页')+' · '+origin(r.url||base()).replace(/^https?:\/\//,'')));if(list.length)pushCards(d,list,60);else{d.push(empty('当前页暂无可显示条目',r.blocked?'线路被拦截/需要代理，建议切换域名或网页验证。':'可能是页面结构变化。'));d.push(text('🌐 网页打开当前页','用于实机核对真实页面',web(r.url||abs(u,base()))));}next=nextUrl(r.body,r.url);if(next)d.push(text('下一页  ›','继续浏览',page('xchinaCatalog',{kind:kind,url:next})));d.push({col_type:'line'});d.push(text('分类与筛选','读取当前栏目真实分类链接',page('xchinaCategories',{kind:kind})));setResult(d);}

  function categories(){var kind=param('kind','video'),d=[],root=kindRoot(kind),r=fetchPage(root,{ttl:600000}),a=anchors(r.body,r.url),out=[],seen={},i,it,n,re;if(kind==='video')out=[{name:'中文AV',url:abs('/videos/series-63824a975d8ae.html',r.url)},{name:'日本AV',url:abs('/videos/series-6206216719462.html',r.url)},{name:'模特私拍',url:abs('/videos/series-6030196781d85.html',r.url)},{name:'业余拍摄',url:abs('/videos/series-617d3e7acdcc8.html',r.url)},{name:'情色电影',url:abs('/videos/series-61c4d9b653b6d.html',r.url)},{name:'其他影片',url:abs('/videos/series-60192e83c9e05.html',r.url)}];
    if(kind==='photo')out=[{name:'有视频',url:abs('/photos/album-11.html',r.url)},{name:'秀人网',url:abs('/photos/album-1.html',r.url)},{name:'大尺度主题',url:abs('/photos/album-2.html',r.url)},{name:'性爱主题',url:abs('/photos/album-3.html',r.url)},{name:'露出主题',url:abs('/photos/album-4.html',r.url)},{name:'Cosplay主题',url:abs('/photos/album-5.html',r.url)},{name:'道具主题',url:abs('/photos/album-6.html',r.url)},{name:'捆绑主题',url:abs('/photos/album-7.html',r.url)},{name:'白虎主题',url:abs('/photos/album-8.html',r.url)},{name:'女同主题',url:abs('/photos/album-9.html',r.url)},{name:'丝袜主题',url:abs('/photos/album-10.html',r.url)}];
    re=kind==='video'?/\/videos\/(?:series|type)-[^\/?#]+(?:\/\d+)?\.html/i:kind==='photo'?/\/photos\/(?:album|type)-[^\/?#]+(?:\/\d+)?\.html/i:kind==='fiction'?/\/fictions\/(?:type|tag|series)-[^\/?#]+(?:\/\d+)?\.html/i:/\/models\/type-[^\/?#]+(?:\/sort-[^\/]+)?(?:\/\d+)?\.html/i;for(i=0;i<a.length;i++){it=a[i];if(!re.test(it.href))continue;n=trim(it.text||it.title);if(!n||n.length>40||seen[it.href])continue;seen[it.href]=1;out.push({name:n,url:it.href});}out=uniq(out,function(v){return v.url;});setPageTitle(kindName(kind)+' · 分类');d.push(section('分类',out.length+' 个'));for(i=0;i<out.length;i++)d.push(text(out[i].name,'',page('xchinaCatalog',{kind:kind,url:out[i].url})));if(!out.length)d.push(empty('未读取到分类','可返回栏目首页继续浏览'));setResult(d);}

  function searchItems(kind,kw){var p='/' +(kind==='photo'?'photos':kind==='fiction'?'fictions':kind==='model'?'models':'videos')+'/keyword-'+q(kw)+'/1.html',r=fetchPage(p,{ttl:60000}),list=parseAny(r.body,r.url,kind);return{result:r,list:list};}
  function search(){var kw='';try{kw=trim(param('kw','')||param('q','')||MY_URL.match(/[?&](?:wd|key|keyword)=([^&#]+)/i)[1]);}catch(e){}if(!kw){try{kw=trim(MY_URL.replace(/^.*kw=/,''));}catch(e2){}}renderSearch(kw,true);}
  function searchPage(){renderSearch(trim(param('q','')),false);}
  function renderSearch(kw,fromGlobal){var d=[],kinds=['video','photo','fiction','model'],i,x,total=0;if(!kw){setPageTitle('搜索');d.push(empty('请输入关键词','可直接使用海阔顶部搜索；也可以从栏目进入搜索。'));d.push(text('打开网站搜索页','网页兜底',web(base()+'/videos.html')));setResult(d);return;}setPageTitle('搜索 · '+kw);for(i=0;i<kinds.length;i++){x=searchItems(kinds[i],kw);if(x.list.length){d.push(section(kindName(kinds[i]),x.list.length+' 条'));pushCards(d,x.list,fromGlobal?8:20);total+=x.list.length;}}if(!total)d.push(empty('没有解析到结果','可能是线路限制或该关键词无结果。'));setResult(d);}

  function mediaCandidates(html,b){var out=[],seen={},m,re,domain='',u;var dm=s(html).match(/\b(?:var\s+)?domain\s*=\s*["']([^"']+)["']/i);if(dm)domain=abs(dm[1],b);re=/["']([^"']+\.(?:m3u8|mp4)(?:\?[^"']*)?)["']/ig;while((m=re.exec(s(html)))){u=m[1];if(/^\//.test(u)&&domain)u=domain.replace(/\/+$/,'')+u;u=abs(u,b);if(u&&!seen[u]){seen[u]=1;out.push(u);}}re=/["']url["']\s*:\s*["']([^"']+)["']/ig;while((m=re.exec(s(html)))){u=m[1];if(!/\.(?:m3u8|mp4)(?:\?|$)/i.test(u)&&!/^\//.test(u))continue;if(/^\//.test(u)&&domain)u=domain.replace(/\/+$/,'')+u;u=abs(u,b);if(u&&!seen[u]){seen[u]=1;out.push(u);}}return out;}
  function videoPlay(u,ref){var h='Referer@'+origin(ref||base())+'/&&User-Agent@'+X.ua;var hm=s(u).match(/^https?:\/\/([^\/]+)/i);if(hm&&/playhls\.com$/i.test(hm[1]))h+='&&Host@'+hm[1];return u+';{'+h+'}#isVideo=true#';}
  function videoDetail(){var u=param('url',''),d=[],r=fetchPage(u,{ttl:120000}),html=r.body,title=titleOf(html,param('title','影片详情')),poster=meta(html,'og:image')||imgFrom(html,r.url),media=mediaCandidates(html,r.url),models=parseModels(html,r.url),related=parseVideos(html,r.url),i;setPageTitle(title);d.push({title:title,desc:'成人影片',img:image(poster,r.url),pic_url:image(poster,r.url),url:web(r.url),col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});if(media.length){d.push(section('播放','解析到 '+media.length+' 条媒体地址'));for(i=0;i<media.length;i++)d.push({title:'▶ 播放'+(media.length>1?' '+(i+1):''),desc:media[i].replace(/^https?:\/\/[^\/]+/,'').substring(0,90),url:videoPlay(media[i],r.url),col_type:'text_1',extra:{lineVisible:false}});}else{d.push(empty('暂未解析到直链','站点可能改了脚本结构或需要浏览器 Cookie。'));d.push(text('🌐 网页播放','使用站点原播放器',web(r.url)));}if(models.length){d.push({col_type:'line'});d.push(section('相关人物',models.length+' 位'));pushCards(d,models,10);}related=related.filter(function(v){return v.url!==u;});if(related.length){d.push({col_type:'line'});d.push(section('相关影片',''));pushCards(d,related,12);}setResult(d);}

  function allImages(html,b){var out=[],seen={},re=/<img\b[^>]*>/ig,m,tag,u,cl;while((m=re.exec(s(html)))){tag=m[0];cl=attr(tag,'class');u=attr(tag,'data-original')||attr(tag,'data-src')||attr(tag,'src');u=abs(u,b);if(!u||seen[u]||/logo|avatar|favicon|poster\.jpg/i.test(u))continue;if(/cr_only|photo|gallery|lazy/i.test(cl)||/\/uploads?\/|\/photo\/|\/images?\//i.test(u)){seen[u]=1;out.push(u);}}return out;}
  function photoDetail(){var u=param('url',''),d=[],r=fetchPage(u,{ttl:180000}),title=titleOf(r.body,param('title','套图')),imgs=allImages(r.body,r.url),media=mediaCandidates(r.body,r.url),next=nextUrl(r.body,r.url),i;setPageTitle(title);d.push(section(title,imgs.length+' 张'+(media.length?' · '+media.length+' 段视频':'')));if(media.length)for(i=0;i<media.length;i++)d.push({title:'▶ 播放附带视频'+(media.length>1?' '+(i+1):''),url:videoPlay(media[i],r.url),col_type:'text_1',extra:{lineVisible:false}});for(i=0;i<imgs.length;i++)d.push({title:(i+1)+' / '+imgs.length,img:image(imgs[i],r.url),pic_url:image(imgs[i],r.url),url:'pics://'+image(imgs[i],r.url),col_type:'pic_1_full',extra:{lineVisible:false}});if(!imgs.length)d.push(empty('当前页未解析到图片','可用网页入口核对页面结构。'));if(next)d.push(text('加载下一页图片  ›','',page('xchinaPhoto',{url:next,title:title})));d.push(text('🌐 网页查看原页','',web(r.url)));setResult(d);}

  function articleBlock(html){var cands=[],re=/<(?:div|article|section)\b[^>]*(?:id|class)=["'][^"']*(?:content|article|fiction|chapter|read|text)[^"']*["'][^>]*>([\s\S]*?)<\/(?:div|article|section)>/ig,m,t;while((m=re.exec(s(html)))){t=strip(m[1]);if(t.length>200)cands.push(t);}cands.sort(function(a,b){return b.length-a.length;});if(cands.length)return cands[0];var body=s(html).replace(/<script\b[\s\S]*?<\/script>/ig,'').replace(/<style\b[\s\S]*?<\/style>/ig,'');return strip(body).substring(0,25000);}
  function findChapterNav(html,b,which){var a=anchors(html,b),i,t;for(i=0;i<a.length;i++){t=trim(a[i].text);if(which==='prev'&&/上一章|上一个/.test(t))return a[i].href;if(which==='next'&&/下一章|下一个/.test(t))return a[i].href;}return'';}
  function fictionDetail(){var u=param('url',''),d=[],r=fetchPage(u,{ttl:180000}),title=titleOf(r.body,param('title','小说')),content=articleBlock(r.body),prev=findChapterNav(r.body,r.url,'prev'),next=findChapterNav(r.body,r.url,'next');setPageTitle(title);d.push(section(title,'小说阅读'));if(content)d.push({title:content,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});else d.push(empty('正文解析为空','页面结构可能变化。'));d.push({col_type:'line'});if(prev)d.push(text('‹ 上一章','',page('xchinaFiction',{url:prev})));if(next)d.push(text('下一章 ›','',page('xchinaFiction',{url:next})));d.push(text('🌐 网页原文','',web(r.url)));setResult(d);}

  function modelDetail(){var u=param('url',''),d=[],r=fetchPage(u,{ttl:180000}),title=titleOf(r.body,param('title','模特')),poster=meta(r.body,'og:image')||imgFrom(r.body,r.url),desc='',m,works=parseVideos(r.body,r.url),photos=parsePhotos(r.body,r.url);m=s(r.body).match(/<p\b[^>]*>([\s\S]{30,1200}?)<\/p>/i);if(m)desc=strip(m[1]);setPageTitle(title);d.push({title:title,desc:desc||'人物资料',img:image(poster,r.url),pic_url:image(poster,r.url),url:web(r.url),col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});if(desc)d.push({title:desc,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});if(works.length){d.push({col_type:'line'});d.push(section('影片作品',works.length+' 条'));pushCards(d,works,30);}if(photos.length){d.push({col_type:'line'});d.push(section('写真作品',photos.length+' 条'));pushCards(d,photos,24);}if(!works.length&&!photos.length)d.push(empty('当前页没有解析到作品','可网页查看详情'));setResult(d);}

  function settings(){var d=[],cur=base(),last=getItem(X.lastBaseKey,''),custom=getItem(X.baseKey,'');setPageTitle('小黄书 · 设置');d.push(section('线路','当前 '+cur));d.push(text('自动线路','主域名 → 最新域名；失败自动切换',$('hiker://empty').lazyRule(function(){clearItem('xc_base_v1');refreshPage(false);return'toast://已切换自动线路';})));d.push(text('xchina.co','官方主域名',$('hiker://empty').lazyRule(function(){setItem('xc_base_v1','https://xchina.co');refreshPage(false);return'toast://已切换 xchina.co';})));d.push(text('xchina001.ink','发布页标记的最新域名',$('hiker://empty').lazyRule(function(){setItem('xc_base_v1','https://xchina001.ink');refreshPage(false);return'toast://已切换 xchina001.ink';})));d.push({col_type:'line'});d.push(section('状态','Test 0.1.0-test.1 · Build 10101'));d.push(text('当前固定线路',custom||'自动'));d.push(text('最近成功线路',last||'暂无'));d.push(text('网站登录','浏览器打开登录页；账号桥接后续版本再做',web(cur+'/login.html')));d.push(text('网页首页','用于线路/Cloudflare诊断',web(cur+'/')));setResult(d);}

  X.module=function(){return{home:home,catalog:catalog,categories:categories,search:search,searchPage:searchPage,videoDetail:videoDetail,photoDetail:photoDetail,fictionDetail:fictionDetail,modelDetail:modelDetail,settings:settings};};
  return X;
})();
