/* PikPak Test13 Build10115 - pass current official Web access token */
(function(C,UI,Pages){
    function param(k){try{return String(getParam(k,'')||'');}catch(e){return '';}}
    Pages.webLogin=function(){
        var d=[];try{setPageTitle('PikPak 官方登录');}catch(e){}
        d.push({title:'在下面完成 PikPak 官方登录',desc:'登录成功进入 PikPak 文件页后，Test13 会读取官方网页 credentials 中当前 Access Token + Refresh Token。优先直接复用网页已经登录成功的 Access Token，不再额外发起一次 refresh/captcha 请求。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
        var inject="(function(){try{if(window.__pikpakWebAccessBridge12)return;window.__pikpakWebAccessBridge12=1;var sent='';function txt(v){return String(v==null?'':v);}function parse(v){if(!v)return null;if(typeof v==='object')return v;try{return JSON.parse(txt(v));}catch(e){return null;}}function find(o,depth){if(!o||depth>6)return null;if(typeof o==='string'){var p=parse(o);return p?find(p,depth+1):null;}if(typeof o!=='object')return null;var at=txt(o.access_token||o.accessToken||''),rt=txt(o.refresh_token||o.refreshToken||'');if(at||rt)return {access_token:at,refresh_token:rt,sub:txt(o.sub||o.user_id||o.userId||''),token_type:txt(o.token_type||'Bearer'),expires_in:txt(o.expires_in||'')};for(var k in o){try{var r=find(o[k],depth+1);if(r&&(r.access_token||r.refresh_token))return r;}catch(e){}}return null;}function scanStore(s){try{for(var i=0;i<s.length;i++){var k=txt(s.key(i)),v=txt(s.getItem(k));if(!k&&!v)continue;var hit=/^credentials(?:_|$)/i.test(k)||/access_token|refresh_token/i.test(v);if(!hit)continue;var r=find(v,0);if(r&&(r.access_token||r.refresh_token))return r;}}catch(e){}return null;}function aux(nameRe,valueRe){var stores=[localStorage,sessionStorage];for(var z=0;z<stores.length;z++){var s=stores[z];try{for(var i=0;i<s.length;i++){var k=txt(s.key(i)),v=txt(s.getItem(k));if(nameRe.test(k)){var m=v.match(valueRe);if(m)return m[0];}}}catch(e){}}return '';}function scan(){try{if(!/mypikpak\\.(com|net)$/i.test(txt(location.hostname)))return;var r=scanStore(localStorage)||scanStore(sessionStorage);if(!r)return;var did=aux(/device.?id/i,/[0-9a-f]{32}/i),cap='';var stores=[localStorage,sessionStorage];for(var z=0;z<stores.length&&!cap;z++){var s=stores[z];try{for(var i=0;i<s.length;i++){var k=txt(s.key(i)),v=txt(s.getItem(k));if(!/^captcha_/i.test(k)&&v.indexOf('captcha_token')<0)continue;var o=parse(v);if(o&&typeof o==='object')cap=txt(o.captcha_token||o.captchaToken||o.token||'');if(!cap){var m=v.match(/ck[0-9A-Za-z._-]{20,}/);if(m)cap=m[0];}}}catch(e){}}var mark=(r.access_token||'').slice(-24)+'|'+(r.refresh_token||'').slice(-24);if(!mark||mark===sent)return;sent=mark;var u='hiker://page/pikpakWebDone?rule=PikPak&simple=true&access_token='+encodeURIComponent(r.access_token||'')+'&refresh_token='+encodeURIComponent(r.refresh_token||'')+'&device_id='+encodeURIComponent(did)+'&captcha_token='+encodeURIComponent(cap)+'&sub='+encodeURIComponent(r.sub||'')+'&token_type='+encodeURIComponent(r.token_type||'Bearer')+'&expires_in='+encodeURIComponent(r.expires_in||'');fy_bridge_app.open(u);}catch(e){}}scan();window.__pikpakWebAccessTimer12=setInterval(scan,700);try{window.addEventListener('storage',scan);window.addEventListener('focus',scan);window.addEventListener('hashchange',scan);window.addEventListener('popstate',scan);document.addEventListener('visibilitychange',scan);document.addEventListener('readystatechange',scan);}catch(e2){}}catch(e){}})();";
        d.push({title:'PikPak 官方网页',url:'https://mypikpak.com/drive/all',col_type:'x5_webview_single',desc:'list&&screen-170',extra:{canBack:true,showProgress:true,ua:'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0 Mobile Safari/537.36',js:inject,jsLoadingInject:true}});
        d.push({title:'没有自动返回？',desc:'确认网页版已经真正进入网盘首页后停留几秒，或重新加载上方网页。若网页已登录，通常无需再次输入账号。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
        setResult(d);
    };
    Pages.webDone=function(){
        var at=param('access_token'),rt=param('refresh_token'),did=param('device_id'),cap=param('captcha_token'),sub=param('sub'),tt=param('token_type'),exp=param('expires_in');try{setPageTitle('PikPak 登录接管');}catch(e){}
        if(!at&&!rt){setResult([UI.error('没有从官方网页读取到有效登录凭据，请返回重新登录')]);return;}
        showLoading(at?'正在接入 PikPak 官方网页当前会话…':'正在用官方 Refresh Token 恢复会话…');
        var r=C.importWebCredential({access_token:at,refresh_token:rt,device_id:did,captcha_token:cap,sub:sub,token_type:tt,expires_in:exp});hideLoading();
        if(r&&!r.error&&!r.error_code&&r.access_token){setResult([{title:'✅ PikPak 登录成功',desc:at?'已直接接入官方网页当前 Access Token；后续过期时再自动使用 Refresh Token。':'已使用官方网页 Refresh Token 恢复 API 会话。',url:'hiker://home@PikPak',col_type:'text_center_1',extra:{lineVisible:false}},{title:'返回 PikPak 首页',url:'hiker://home@PikPak',col_type:'text_center_1'}]);return;}
        setResult([{title:'Web 会话接管失败',desc:C.errorText(r),url:'hiker://page/pikpakWebLogin?rule=PikPak&simple=true',col_type:'text_1',extra:{lineVisible:false}}]);
    };
})(PikPakCore,PikPakUI,PikPakPages);
