/* JavBus 2.0.0-alpha2 - device feedback fixes: actress list, in-page tabs, detail UI, magnet entry, search action */
(function(){
  if(typeof JavBusCore!=='object'||typeof JavBusRemoteRuntime!=='object')throw new Error('JavBus alpha2 base runtime missing');
  var C=JavBusCore,R=JavBusRemoteRuntime;
  var OFFICIAL_ICON='https://www.javbus.com/favicon.ico';
  R.version='2.0.0-alpha2';R.build='2.0.0-alpha2';R.officialIcon=OFFICIAL_ICON;

  function s(v){return v===undefined||v===null?'':String(v);}
  function section(title,desc){return{title:'▌ '+title,desc:desc||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}};}
  function activeTitle(name,on){return on?'““””<b><font color=#E75480>'+name+'</font></b>':name;}
  function page(path,params){return C.page(path,params||{});}
  function typeKey(scope){return'javbus_'+scope+'_type';}
  function currentType(scope,fallback){return getMyVar(typeKey(scope),getParam('type',fallback||'normal')||fallback||'normal');}
  function typeTabsInline(d,scope,current){
    var types=['normal','uncensored','western'];
    for(var i=0;i<types.length;i++)(function(t){d.push({title:activeTitle(C.typeName(t),current===t),url:$('#noLoading#').lazyRule(function(scope,t){putMyVar('javbus_'+scope+'_type',t);refreshPage(false);return'hiker://empty';},scope,t),col_type:'scroll_button',extra:{lineVisible:false}});})(types[i]);
  }
  function magnetToggle(d){var on=C.magMode();d.push({title:activeTitle(on==='all'?'全部影片':'只看有磁力',true),url:'select://'+JSON.stringify({title:'影片范围',options:['全部影片','只看有磁力'],col:2,js:$.toString(function(){setItem('javbus_mag_mode',input==='只看有磁力'?'exist':'all');refreshPage(false);return'toast://已切换 '+input;})}),col_type:'scroll_button',extra:{lineVisible:false}});}
  function searchBar(d,type){
    d.push({title:'搜索',url:$.toString(function(type){var kw=String(input||'').trim();if(!kw)return'toast://请输入内容';putMyVar('javbus_search_kw',kw);putMyVar('javbus_search_type',type);return'hiker://page/javbusSearch?rule='+MY_RULE.title+'&simple=true&kw='+encodeURIComponent(kw);},type),col_type:'input',extra:{titleVisible:true,lineVisible:false,hint:'请输入内容'}});
  }
  function quickTools(d,type){
    d.push({title:'👤 演员',url:page('javbusActors',{type:type}),col_type:'text_4',extra:{lineVisible:false}});
    d.push({title:'🏷 分类',url:page('javbusGenres',{type:type}),col_type:'text_4',extra:{lineVisible:false}});
    d.push({title:'★ 收藏',url:page('javbusFav',{}),col_type:'text_4',extra:{lineVisible:false}});
    d.push({title:'⚙ 更多',url:page('javbusMore',{}),col_type:'text_4',extra:{lineVisible:false}});
  }
  function movieUrl(m){return page('javbusDetail',{id:m.id,type:m.type||'normal'});}
  function actorUrl(a){return page('javbusActor',{id:a.id,type:a.type||'normal'});}
  function movieCard(m){var tags=(m.tags||[]).join(' · '),desc=[m.id,m.date,tags].filter(function(x){return!!x;}).join(' · ');return{title:m.title||m.id,desc:desc,img:m.img,pic_url:m.img,url:movieUrl(m),col_type:'movie_3',extra:{pageTitle:m.id||m.title,lineVisible:false,longClick:[{title:'收藏/取消收藏',js:$.toString(function(m){var J=$.require('javbus');return J.toggleVideoFavorite(m);},m)},{title:'复制番号',js:$.toString(function(id){return'copy://'+id;},m.id)},{title:'云盘君搜番号',js:$.toString(function(id){if(fetch('hiker://home@云盘君.简')==='null')return'toast://未安装 云盘君.简';return'hiker://page/sou?rule=云盘君.简&p=fypage&hideSetting=true&searchTerms='+encodeURIComponent(id);},m.id)}]}};}
  function renderMovies(d,html,type,emptyText){var a=C.parseMovies(html,type),i;for(i=0;i<a.length;i++)d.push(movieCard(a[i]));if(!a.length)d.push({title:emptyText||'没有解析到影片',desc:'可尝试刷新，或从原站网页核对',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}});return a.length;}
  function listError(d,msg,url){d.push(section('暂时无法读取',''));d.push({title:'页面读取失败',desc:msg||'JavBus 当前连接失败',url:url?'web://'+url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}});}
  function actorCard(a){return{title:a.name||a.id,desc:C.typeName(a.type),img:a.img,pic_url:a.img,url:actorUrl(a),col_type:'card_pic_3',extra:{pageTitle:a.name||a.id,lineVisible:false}};}
  function clickableProp(d,icon,label,p,type){if(!p||!p.name)return;var pi=p.path||C.pathInfo(p.href);d.push({title:icon+' '+label+' · '+p.name,url:page('javbusFilter',{type:pi.type||type,kind:pi.kind,id:pi.id,name:p.name}),col_type:'flex_button',extra:{lineVisible:false}});}
  function playbackButtons(d,code){var ps=[{id:'missav',name:'MissAV'},{id:'123av',name:'123AV'},{id:'jable',name:'Jable'}];for(var i=0;i<ps.length;i++){var p=ps[i];d.push({title:'▶ '+p.name,url:C.playbackUrl(p.id,code),col_type:'text_3',extra:{lineVisible:false,pageTitle:p.name+' · '+code}});}}
  function sortTabs(d,sort){var xs=[['大小↓','size_desc'],['大小↑','size_asc'],['日期↓','date_desc'],['日期↑','date_asc']];for(var i=0;i<xs.length;i++)(function(x){d.push({title:activeTitle(x[0],sort===x[1]),url:$('#noLoading#').lazyRule(function(v){putMyVar('javbus_mag_sort',v);refreshPage(false);return'hiker://empty';},x[1]),col_type:'scroll_button',extra:{lineVisible:false}});})(xs[i]);}
  function magnetRows(d,detail){var sort=getMyVar('javbus_mag_sort','size_desc');sortTabs(d,sort);var ms=C.magnets(detail,sort);if(!ms.length){d.push({title:'暂无磁力资源',desc:detail.gid?'当前影片未返回磁力，或 AJAX 接口暂不可用':'详情页未取得 GID/UC，磁力接口无法请求',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}});return 0;}for(var i=0;i<ms.length;i++){var m=ms[i],tag=(m.hd?'高清 ':'')+(m.sub?'字幕 ':'');d.push({title:'🧲 '+(tag?'【'+tag.replace(/\s+$/,'')+'】 ':'')+(m.title||detail.id),desc:[m.size,m.date].filter(function(x){return!!x;}).join(' · ')+'\n点击复制磁力 · 长按调用 123云盘 / 磁力君 / 云盘君',url:'copy://'+m.link,col_type:'text_1',extra:{lineVisible:false,longClick:C.magnetLongClicks(m.link,detail.id)}});}return ms.length;}

  /* Verified JavBus actress list contract: /actresses/{page}, .item a, .photo-info span, .photo-frame img. */
  C.actressUrl=function(type,pageNo){var p=C.typePrefix(type),n=Number(pageNo||1);return C.base+p+'/actresses/'+n;};
  C.parseActors=function(html,type){var nodes=[],out=[],seen={};try{nodes=pdfa(html,'#waterfall&&.item')||[];}catch(e){nodes=[];}if(!nodes.length){try{nodes=pdfa(html,'.item')||[];}catch(e2){nodes=[];}}for(var i=0;i<nodes.length;i++){var href='',img='',name='';try{href=C.abs(pdfh(nodes[i],'a&&href')||'',C.base);img=pdfh(nodes[i],'.photo-frame&&img&&src')||pdfh(nodes[i],'img&&src')||'';name=C.strip(pdfh(nodes[i],'.photo-info&&span&&Text')||pdfh(nodes[i],'.photo-info&&Text')||pdfh(nodes[i],'img&&title')||'');}catch(e3){}var pi=C.pathInfo(href);if(pi.kind!=='star'||!pi.id||seen[href])continue;seen[href]=1;out.push({id:pi.id,name:name||pi.id,img:C.image(img,href),href:href,type:pi.type||type||'normal'});}return out;};
  var oldActorProfile=C.parseActorProfile;
  C.parseActorProfile=function(html,id,type){var a=oldActorProfile(html,id,type)||{id:id,type:type||'normal',name:id,img:'',fields:[]};var ref=C.base+C.typePrefix(type)+'/star/'+id;if(!a.img)a.img=C.image(C.base+'/pics/actress/'+id+'_a.jpg',ref);if(!a.name||a.name===id){try{a.name=C.strip(pdfh(html,'#waterfall&&.avatar-box&&.photo-info&&.pb10&&Text')||pdfh(html,'.photo-info&&span&&Text')||id);}catch(e){a.name=id;}}if(!a.fields||!a.fields.length){a.fields=[];var labels=['生日','年齡','身高','胸圍','腰圍','臀圍','出生地','愛好'];for(var i=0;i<labels.length;i++){var re=new RegExp(labels[i]+'\\s*[:：]\\s*([^<\\r\\n]+)','i'),m=s(html).match(re);if(m&&m[1])a.fields.push(labels[i]+'：'+C.strip(m[1]));}}return a;};

  R.home=function(){var d=[],type=getMyVar('javbus_home_type',getItem('javbus_default_type','normal')||'normal'),pg=Number(MY_PAGE||1),url=C.listUrl(type,pg,'',''),html='';if(pg===1){setPageTitle('JavBus');typeTabsInline(d,'home',type);magnetToggle(d);searchBar(d,type);quickTools(d,type);d.push(section(C.typeName(type)+' · 最新影片',C.magMode()==='exist'?'仅显示有磁力资源':'显示全部影片'));}html=C.fetchHtml(url);if(!html){if(pg===1)listError(d,'无法连接 JavBus；旧版仍可从正式通道恢复',url);setResult(d);return;}renderMovies(d,html,type,'本页暂无影片');setResult(d);};

  R.search=function(){var d=[],kw=decodeURIComponent(getParam('kw','')||getMyVar('javbus_search_kw','')||''),type=currentType('search',getParam('type','normal')||'normal'),pg=Number(MY_PAGE||1);if(!kw&&typeof MY_KEYWORD!=='undefined')kw=String(MY_KEYWORD||'');kw=String(kw||'').trim();if(pg===1){setPageTitle('搜索');typeTabsInline(d,'search',type);magnetToggle(d);searchBar(d,type);d.push(section('搜索结果',kw||'未输入关键词'));}if(!kw){d.push({title:'请输入搜索关键词',url:'hiker://empty',col_type:'text_center_1'});setResult(d);return;}putMyVar('javbus_search_kw',kw);var url=C.searchUrl(type,kw,pg),html=C.fetchHtml(url);if(!html){listError(d,'搜索请求失败',url);setResult(d);return;}renderMovies(d,html,type,'没有找到匹配影片');setResult(d);};

  R.genres=function(){var d=[],type=currentType('genres',getParam('type','normal')||'normal'),url=C.genreUrl(type),html='';setPageTitle('分类');typeTabsInline(d,'genres',type);d.push(section(C.typeName(type)+'分类','切换有码 / 无码 / 欧美在当前页面刷新，不再叠加新页面'));html=C.fetchHtml(url);if(!html){listError(d,'分类页读取失败',url);setResult(d);return;}var a=C.parseGenres(html,type);for(var i=0;i<a.length;i++){var g=a[i];d.push({title:g.name,url:page('javbusFilter',{type:g.type||type,kind:'genre',id:g.id,name:g.name}),col_type:'flex_button',extra:{lineVisible:false}});}if(!a.length)d.push({title:'未解析到分类',desc:'当前网站结构可能已经变化，保留网页入口便于核对',url:'web://'+url,col_type:'text_center_1'});setResult(d);};

  R.actors=function(){var d=[],type=currentType('actors',getParam('type','normal')||'normal'),pg=Number(MY_PAGE||1),url=C.actressUrl(type,pg),html='';if(pg===1){setPageTitle('演员');typeTabsInline(d,'actors',type);d.push(section(C.typeName(type)+'演员','当前页切换分类；演员列表使用 JavBus /actresses/{page}'));}html=C.fetchHtml(url);if(!html){if(pg===1)listError(d,'演员页读取失败',url);setResult(d);return;}var a=C.parseActors(html,type);for(var i=0;i<a.length;i++)d.push(actorCard(a[i]));if(!a.length&&pg===1)d.push({title:'未解析到演员列表',desc:'可先从影片详情点击演员进入个人页',url:'web://'+url,col_type:'text_center_1'});setResult(d);};

  R.actor=function(){var d=[],id=getParam('id',''),type=getParam('type','normal')||'normal',pg=Number(MY_PAGE||1),url=C.listUrl(type,pg,'star',id),html=C.fetchHtml(url);if(!html){listError(d,'演员页面读取失败',url);setResult(d);return;}if(pg===1){var a=C.parseActorProfile(html,id,type),saved=C.isFav('actor',id),info=(a.fields||[]).join(' · ');setPageTitle(a.name||id);d.push({title:'👤 '+(a.name||id),desc:(C.typeName(type)+'演员')+(info?'\n'+info:''),img:a.img,pic_url:a.img,url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});d.push({title:saved?'★ 已收藏':'☆ 收藏演员',url:$('#noLoading#').lazyRule(function(a){var J=$.require('javbus'),r=J.toggleActorFavorite(a);refreshPage(false);return'toast://'+(r?'已收藏演员':'已取消演员收藏');},a),col_type:'text_3',extra:{lineVisible:false}});d.push({title:'⧉ 复制姓名',url:'copy://'+(a.name||id),col_type:'text_3',extra:{lineVisible:false}});d.push({title:'🌐 原站页面',url:'web://'+url,col_type:'text_3',extra:{lineVisible:false}});d.push(section('出演作品','共用同一演员筛选结果，继续向下翻页'));}renderMovies(d,html,type,'暂无出演作品');setResult(d);};

  R.detail=function(){var d=[],id=decodeURIComponent(getParam('id','')||''),type=getParam('type','normal')||'normal';if(!id){d.push({title:'缺少影片番号',url:'hiker://empty',col_type:'text_center_1'});setResult(d);return;}var url=C.detailUrl(id),html=C.fetchHtml(url);if(!html){listError(d,'影片详情读取失败',url);setResult(d);return;}var x=C.parseDetail(html,id),saved=C.isFav('video',id),desc=[x.date,x.length?x.length+' 分钟':'',C.typeName(type)].filter(function(v){return!!v;}).join(' · ');setPageTitle(id);d.push({title:x.title||id,desc:desc,img:x.img,pic_url:x.img,url:'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});
    d.push({title:'▶ 在线播放',url:'select://'+JSON.stringify({title:'选择播放站点',options:['MissAV','123AV','Jable'],col:3,js:$.toString(function(id){var map={'MissAV':'missav','123AV':'123av','Jable':'jable'},J=$.require('javbus');return J.play(map[input],id);},id)}),col_type:'text_4',extra:{lineVisible:false}});
    d.push({title:'🧲 磁力资源',url:page('javbusMagnets',{id:id,type:type}),col_type:'text_4',extra:{lineVisible:false}});
    d.push({title:saved?'★ 已收藏':'☆ 收藏',url:$('#noLoading#').lazyRule(function(x,type){var J=$.require('javbus'),ok=J.toggleVideoFavorite({id:x.id,title:x.title,img:x.img,url:'https://www.javbus.com/'+x.id,type:type});refreshPage(false);return'toast://'+(ok?'影片已收藏':'已取消收藏');},x,type),col_type:'text_4',extra:{lineVisible:false}});
    d.push({title:'🌐 原站',url:'web://'+url,col_type:'text_4',extra:{lineVisible:false}});
    d.push({title:'⧉ '+id,url:'copy://'+id,col_type:'scroll_button',extra:{lineVisible:false}});if(x.date)d.push({title:'📅 '+x.date,url:'hiker://empty',col_type:'scroll_button',extra:{lineVisible:false}});if(x.length)d.push({title:'⏱ '+x.length+' 分钟',url:'hiker://empty',col_type:'scroll_button',extra:{lineVisible:false}});
    d.push(section('核心资料','点击厂商、系列、演员或标签继续筛选'));clickableProp(d,'🎥','导演',x.director,type);clickableProp(d,'🎬','制作商',x.studio,type);clickableProp(d,'🏷','发行商',x.label,type);clickableProp(d,'📚','系列',x.series,type);
    if(x.stars&&x.stars.length){d.push(section('演员',''));for(var i=0;i<x.stars.length;i++){var st=x.stars[i],pi=st.path||C.pathInfo(st.href);d.push({title:'👤 '+st.name,url:actorUrl({id:pi.id,name:st.name,type:pi.type||type}),col_type:'flex_button',extra:{lineVisible:false}});}}
    if(x.genres&&x.genres.length){d.push(section('标签',''));for(i=0;i<x.genres.length;i++){var g=x.genres[i],gp=g.path||C.pathInfo(g.href);d.push({title:'# '+g.name,url:page('javbusFilter',{type:gp.type||type,kind:'genre',id:gp.id,name:g.name}),col_type:'flex_button',extra:{lineVisible:false}});}}
    d.push(section('第三方在线播放','MissAV / 123AV / Jable 共用 JAV Playback Stable'));playbackButtons(d,id);
    if(x.samples&&x.samples.length){d.push(section('样品图',x.samples.length+' 张'));for(i=0;i<x.samples.length;i++){var sm=x.samples[i];d.push({title:sm.title,img:sm.thumb,pic_url:sm.thumb,url:'pics://'+sm.src,col_type:'pic_2',extra:{lineVisible:false}});}}
    d.push(section('磁力资源','顶部“🧲 磁力资源”可直接进入完整磁力页；这里保留快速预览'));var preview=C.magnets(x,'size_desc');if(preview.length){for(i=0;i<Math.min(preview.length,3);i++){var m=preview[i];d.push({title:'🧲 '+(m.title||id),desc:[m.size,m.date].filter(function(v){return!!v;}).join(' · ')+'\n点击复制 · 长按调用云盘工具',url:'copy://'+m.link,col_type:'text_1',extra:{lineVisible:false,longClick:C.magnetLongClicks(m.link,id)}});}if(preview.length>3)d.push({title:'查看全部 '+preview.length+' 条磁力 ›',url:page('javbusMagnets',{id:id,type:type}),col_type:'text_center_1',extra:{lineVisible:false}});}else d.push({title:'当前未取得磁力',desc:x.gid?'可进入磁力页重试并查看诊断':'详情未解析到 GID/UC',url:page('javbusMagnets',{id:id,type:type}),col_type:'text_center_1',extra:{lineVisible:false}});
    if(x.related&&x.related.length){d.push(section('相似影片',''));for(i=0;i<x.related.length;i++)d.push(movieCard({id:x.related[i].id,title:x.related[i].title,img:x.related[i].img,date:'',tags:[],href:x.related[i].href,type:type}));}
    setResult(d);
  };

  R.magnets=function(){var d=[],id=decodeURIComponent(getParam('id','')||''),type=getParam('type','normal')||'normal';setPageTitle('磁力 · '+id);if(!id){d.push({title:'缺少影片番号',url:'hiker://empty',col_type:'text_center_1'});setResult(d);return;}var url=C.detailUrl(id),html=C.fetchHtml(url);if(!html){listError(d,'影片详情读取失败，无法取得磁力参数',url);setResult(d);return;}var x=C.parseDetail(html,id);d.push(section('🧲 '+id,'点击磁力复制；长按可调用 123云盘 / 磁力君 / 云盘君'));magnetRows(d,x);setResult(d);};

  function bootAction(action){return $('#noLoading#').lazyRule(function(action){try{require('https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/javbus/bootstrap_test_v2.js?v=20002',{headers:{'Cache-Control':'no-cache'}},20002);var r=JavBusBoot[action]();if(action==='check')return'toast://'+(r.hasUpdate?('发现新版本 '+r.latest.version):('当前已是最新 '+r.current.version));if(r&&r.ok){refreshPage(false);return'toast://操作完成';}return'toast://'+String(r&&r.error||'操作失败');}catch(e){return'toast://'+String(e.message||e);}},action);}
  R.settings=function(){var d=[],def=getItem('javbus_default_type','normal')||'normal',mag=C.magMode();setPageTitle('JavBus 设置');d.push(section('浏览偏好',''));d.push({title:'默认首页 · '+C.typeName(def),url:'select://'+JSON.stringify({title:'默认首页',options:['有码','无码','欧美'],col:3,js:$.toString(function(){var m={'有码':'normal','无码':'uncensored','欧美':'western'};setItem('javbus_default_type',m[input]);putMyVar('javbus_home_type',m[input]);return'toast://默认首页已设为 '+input;})}),col_type:'text_1'});d.push({title:'影片范围 · '+(mag==='exist'?'只看有磁力':'全部影片'),url:'select://'+JSON.stringify({title:'影片范围',options:['全部影片','只看有磁力'],col:2,js:$.toString(function(){setItem('javbus_mag_mode',input==='只看有磁力'?'exist':'all');return'toast://已保存';})}),col_type:'text_1'});d.push(section('测试版维护','当前 2.0.0-alpha2 / Build 20002'));d.push({title:'检查更新',url:bootAction('check'),col_type:'text_1'});d.push({title:'更新到最新 Test',url:bootAction('update'),col_type:'text_1'});d.push({title:'回退上一 Test',url:bootAction('rollback'),col_type:'text_1'});d.push({title:'重新加载当前 Test',url:bootAction('reinstall'),col_type:'text_1'});d.push(section('说明',''));d.push({title:'alpha2 修复重点',desc:'演员列表按 /actresses/{page} 重新解析；有码/无码/欧美标签改为当前页刷新；搜索框显示右侧“搜索”；影片详情新增显眼磁力入口并重排；演员详情头像增加官网路径兜底；易失效图片图标改为文字/Emoji 原生按钮。',url:'hiker://empty',col_type:'long_text'});setResult(d);};

  R.module=function(){return{home:R.home,search:R.search,detail:R.detail,filter:R.filter,genres:R.genres,actors:R.actors,actor:R.actor,magnets:R.magnets,favorites:R.favorites,more:R.more,settings:R.settings,toggleVideoFavorite:R.toggleVideoFavorite,toggleActorFavorite:R.toggleActorFavorite,play:R.play};};
})();
