/* 我的规则仓库 3.5.6-rc29 - Self Update Probe */
var RuleRepoRC29=(function(){
var VERSION='3.5.6-rc29',BUILD=419,RULE='apps/tools/rule-repo/rule_repo_test_v166.txt';
function clone(x){try{return JSON.parse(JSON.stringify(x));}catch(e){return x||{};}}
function testOf(x){var a=x&&x.channels||[];for(var i=0;i<a.length;i++)if(String(a[i]&&a[i].channel||'')==='test')return a[i];return null;}
function buildOf(x){var t=testOf(x);return Number(t&&t.build||0);}
function currentMeta(){return{schema:4,id:'rule-repo',name:'我的规则仓库',namingPolicy:'rule-repo-split-name-exception',versionPolicy:'stable-test-local-lineage-v1',updatedAt:'2026-08-25 09:02',channels:[{channel:'stable',label:'正式版',id:'rule-repo',name:'我的规则仓库',version:'3.5.5',build:389,displayVersion:'Stable 3.5.5 · Build 389 · 恢复稳定推荐',path:'apps/tools/rule-repo/rule_repo_remote_v355.txt',mode:'remote',updatedAt:'2026-08-24',recommended:true,desc:'已验证稳定基线'},{channel:'test',label:'测试版',id:'rule-repo-test',name:'我的规则仓库·测试版',version:VERSION,baseVersion:'3.5.5',targetVersion:'3.5.6',build:BUILD,displayVersion:'Test '+VERSION+' · Build '+BUILD+' · Self Update Probe',path:RULE,mode:'remote-local-first-native-require',updatedAt:'2026-08-25',recommended:false,desc:'RC28→RC29 测试仓自更新闭环探针'}]};}
function effective(){var cur=currentMeta(),feed=null;try{if(typeof RuleRepoRC28==='object'&&typeof RuleRepoRC28.current==='function')feed=RuleRepoRC28.current();}catch(e){}return feed&&buildOf(feed)>BUILD?clone(feed):cur;}
function refresh(){if(typeof RuleRepoRC28!=='object'||typeof RuleRepoRC28.refresh!=='function')throw new Error('RC28 自更新 feed 不可用');var x=RuleRepoRC28.refresh();return{ok:!!(x&&x.ok),build:buildOf(effective()),meta:effective()};}
function apply(R){if(!R||typeof R.fastItemState!=='function')throw new Error('规则仓 Runtime 不完整');if(R.__rc29SelfProbe){R.version=VERSION;R.build=BUILD;return R;}var baseFast=R.fastItemState,baseCache=R.fastChannelCache,baseChannel=R.channelMeta,baseAction=R.workspaceAction;R.__rc29SelfProbe=true;R.version=VERSION;R.build=BUILD;R.channel='test';R.releaseLabel='Single Workspace 18.1 · Self Update Probe';R.localFirstRuntimeVersion='18.1';R.fastHomeVersion='18.1.0';R.isTestChannel=function(){return true;};R.ruleRepoChannelFallback=function(){return effective();};R.fastChannelCache=function(item){if(String(item&&item.id||'')==='rule-repo')return{schema:14,time:Date.now(),revision:'self-probe-'+buildOf(effective()),sig:'rule-repo-self-probe',meta:effective()};return baseCache.call(this,item);};R.channelMeta=function(item){if(String(item&&item.id||'')==='rule-repo')return effective();return typeof baseChannel==='function'?baseChannel.call(this,item):null;};R.fastItemState=function(item){if(String(item&&item.id||'')!=='rule-repo')return baseFast.call(this,item);var m=effective(),t=testOf(m),tb=Number(t&&t.build||0);return{group:true,installed:true,channel:'test',installedVersion:VERSION,installedBuild:BUILD,targetChannel:'test',targetVersion:String(t&&t.version||VERSION),targetBuild:tb||BUILD,update:tb>BUILD,updateKnown:true,recognized:true,ruleVersion:0};};R.workspaceAction=function(kind,item){if(String(kind||'')==='check'&&String(item&&item.id||'')==='rule-repo')return $('#noLoading#').lazyRule(function(){var loading=false;try{showLoading('正在检查测试仓新版本…');loading=true;var F='hiker://files/rules/asset-core-local/rule-repo-test/rc29_self_update_probe_patch.js',u=getPath(F);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}if(typeof RuleRepoRC29!=='object')throw new Error('RC29 自更新探针未导出');var x=RuleRepoRC29.refresh(),m=x&&x.meta,t=m&&m.channels||[],v='',b=0;for(var i=0;i<t.length;i++)if(String(t[i]&&t[i].channel||'')==='test'){v=String(t[i].version||'');b=Number(t[i].build||0);break;}hideLoading();loading=false;try{refreshPage(false);}catch(_e){}return'toast://测试仓版本已刷新 · '+(v||'--')+' / Build'+b;}catch(e){if(loading)try{hideLoading();}catch(_e2){}return'toast://检查失败，继续使用当前版本：'+String(e.message||e);}});return baseAction.call(this,kind,item);};return R;}
return{version:'1.0.0',apply:apply,refresh:refresh,current:effective,selfMeta:currentMeta};
})();
