/** ACFun Next 1.0.0-alpha10 - client-side CDN auth_key repair + robust first-page crop */
(function(){
if(typeof ACFunNext!=='object')throw new Error('ACFunNext alpha9 base missing');
var A=ACFunNext;
A.version='1.0.0-alpha10';
A.buildNumber=10010;
A.build='2026.08.23-v1.0.0-alpha10';
A.runtimeMode='clean-next+a10-client-cdn-sign-repair-comic-crop2';
A.bootUrl='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/bootstrap_test_v089.js?v=8900';
A.bootVer=8900;

A.__a10Origin=function(u){var m=A.s(u).match(/^(https?:\/\/[^/?#]+)/i);return m?m[1].replace(/\/+$/,''):'';};
A.__a10Path=function(u){var s=A.s(u),m=s.match(/^https?:\/\/[^/?#]+([^?#]*)/i);return m?(m[1]||'/'):'';};
A.__a10AuthParts=function(u){var m=A.s(u).match(/[?&]auth_key=([^&#]+)/i);if(!m)return null;var v='';try{v=decodeURIComponent(m[1]);}catch(e){v=m[1];}var p=v.split('-');if(p.length<4||!/^\d{8,}$/.test(p[0]))return null;return{ts:p[0],rand:p[1],uid:p[2],sig:p.slice(3).join('-'),raw:v};};
A.__a10Sign=function(path,ts,rand,uid,key,mode){path=A.s(path)||'/';var no=path.replace(/^\//,''),src='';if(mode==='aliyunA-noSlash')src=no+'-'+ts+'-'+rand+'-'+uid+'-'+key;else if(mode==='time-first')src=ts+'-'+rand+'-'+uid+'-'+path+'-'+key;else if(mode==='key-first')src=key+'-'+path+'-'+ts+'-'+rand+'-'+uid;else src=path+'-'+ts+'-'+rand+'-'+uid+'-'+key;return A.md5(src);};
A.__a10SignedUrl=function(url,key,mode,domain,tsOverride,seedParts){url=A.s(url).trim();if(!/^https?:\/\//i.test(url))return'';var ap=A.__a10AuthParts(url)||seedParts||null;if(!ap)return'';var path=A.__a10Path(url),ts=A.s(tsOverride||ap.ts),rand=A.s(ap.rand),uid=A.s(ap.uid||'0');if(!path||!ts||!rand)return'';var sig=A.__a10Sign(path,ts,rand,uid,key,mode),val=ts+'-'+rand+'-'+uid+'-'+sig,out=url;if(/[?&]auth_key=/i.test(out))out=out.replace(/([?&])auth_key=[^&#]*/i,'$1auth_key='+encodeURIComponent(val));else out+=(out.indexOf('?')>=0?'&':'?')+'auth_key='+encodeURIComponent(val);if(domain){var old=A.__a10Origin(out);if(old)out=A.s(domain).replace(/\/+$/,'')+out.substring(old.length);}return out;};
A.__a10CollectPlaybackConfig=function(refresh){var roots=[],keys=[],domains=[],seenK={},seenD={},count=0;try{roots.push(A.remoteConfig(true)||{});}catch(e0){}if(refresh)roots.push(refresh);function addKey(v){v=A.s(v).trim();if(!v||/^https?:\/\//i.test(v)||/^\d{8,}-[^-]+-[^-]+-/i.test(v)||v.length<6||seenK[v])return;seenK[v]=1;keys.push(v);}function addDomain(v){v=A.s(v).trim();if(!/^https?:\/\//i.test(v))return;var d=A.__a10Origin(v);if(d&&!seenD[d]){seenD[d]=1;domains.push(d);}}function walk(v,d){if(!v||d>9||count++>3500)return;if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],d+1);return;}if(typeof v!=='object')return;for(var k in v){var lk=A.s(k).toLowerCase();if(lk==='playbackauthkey'||lk==='playback_auth_key'||lk==='mediaauthkey'||lk==='media_auth_key')addKey(v[k]);if(lk==='playbackdomain'||lk==='playback_domain'||lk==='mediadomain'||lk==='media_domain')addDomain(v[k]);}for(var k2 in v)if(v[k2]&&typeof v[k2]==='object')walk(v[k2],d+1);}for(var r=0;r<roots.length;r++)walk(roots[r],0);var pub={keyCount:keys.length,keys:[],domains:domains.slice(0,8)};for(var j=0;j<keys.length;j++)pub.keys.push({len:keys[j].length,md5:A.md5(keys[j]).substring(0,10)});A.setDiag('play_sign_config',JSON.stringify(pub));return{keys:keys.slice(0,3),domains:domains.slice(0,8)};};
A.__a10ProbeBinary=function(url,label){var o={label:label,url:url,status:0,ct:'',hexLen:0,first:'',body:'',error:''};if(!url)return o;var r=A.__a9Fetch(url,{},1500);o.status=r.status;o.ct=r.ct;o.body=(r.status>=200&&r.status<300)?'':A.__a9BodySnippet(r.body);o.error=r.error||'';if(o.status>=200&&o.status<300){try{var hx=A.s(fetch(url,{timeout:1700,toHex:true,headers:{}})).replace(/\s+/g,'');o.hexLen=hx.length;o.first=hx.substring(0,32);}catch(e){o.error=A.s(e.message||e);}}return o;};
A.__a10FindSigner=function(segment,keyUrl,cfg,extraDomains){var sp=A.__a10AuthParts(segment),kp=A.__a10AuthParts(keyUrl),domains=[],seen={},logs=[],tries=0;if(!sp||!cfg.keys.length)return{chosen:null,logs:['missing auth parts or playbackAuthKey']};function addD(d){d=A.__a10Origin(d)||A.s(d).replace(/\/+$/,'');if(d&&!seen[d]){seen[d]=1;domains.push(d);}}addD(segment);for(var i=0;i<(extraDomains||[]).length;i++)addD(extraDomains[i]);for(var j=0;j<cfg.domains.length;j++)addD(cfg.domains[j]);domains=domains.slice(0,6);var modes=['aliyunA','aliyunA-noSlash','time-first','key-first'],now=String(Math.floor(Date.now()/1000));for(var k=0;k<cfg.keys.length&&tries<18;k++){var key=cfg.keys[k];for(var d=0;d<domains.length&&tries<18;d++){var modeList=d===0?modes:['aliyunA','aliyunA-noSlash'];for(var m=0;m<modeList.length&&tries<18;m++){var mode=modeList[m],tsList=d===0?[sp.ts,now]:[now];for(var t=0;t<tsList.length&&tries<18;t++){var ts=tsList[t],su=A.__a10SignedUrl(segment,key,mode,domains[d],ts,sp);tries++;var pr=A.__a10ProbeBinary(su,'seg');logs.push('k'+k+' '+mode+' '+(ts===sp.ts?'server-ts':'fresh-ts')+' '+domains[d]+' => '+pr.status+'/'+pr.ct+'/hex'+pr.hexLen+(pr.body?('/'+pr.body):''));if(pr.status>=200&&pr.status<300&&pr.hexLen>0){var ku=A.__a10SignedUrl(keyUrl,key,mode,domains[d],ts,kp||sp),kr=A.__a10ProbeBinary(ku,'key');logs.push('  key => '+kr.status+'/'+kr.ct+'/hex'+kr.hexLen+(kr.body?('/'+kr.body):''));if(kr.status>=200&&kr.status<300&&kr.hexLen>=32)return{chosen:{key:key,keyIndex:k,mode:mode,domain:domains[d],ts:ts,segment:su,keyUrl:ku},logs:logs};}}}}}return{chosen:null,logs:logs};};
A.__a10RewriteManifest=function(body,ch){if(!body||!ch)return'';return A.s(body).replace(/https?:\/\/[^\s"'<>]+/g,function(u){var ap=A.__a10AuthParts(u);if(!ap)return u;return A.__a10SignedUrl(u,ch.key,ch.mode,ch.domain,ch.ts,ap)||u;});};
A.__a10WriteManifest=function(id,body){try{var uri='hiker://files/cache/acfun_a10_resigned_'+A.s(id).replace(/[^A-Za-z0-9_-]/g,'_')+'_'+A.md5(body).substring(0,8)+'.m3u8';writeFile(uri,body);return getPath(uri);}catch(e){A.setDiag('play_resign_write','ERR '+A.s(e.message||e));return'';}};

A.play=function(id,raw,direct){id=A.s(id);var obj=A.safeJson(raw)||raw||{},seed='';if(A.mediaLike(direct))seed=A.s(direct);if(!seed)seed=A.mediaPath(obj);var wr=A.__a9Watch(id),wm=wr.meta||{},basePath=wm.videoUrl||seed||wm.playPath||'',refresh={};try{refresh=A.__a4CdnRefresh(id,basePath,true)||{};}catch(e0){}var host=A.__a9Host(),decode='';if(basePath){decode=/^https?:\/\//i.test(basePath)?basePath:(host+'/api/m3u8/h5/decode?path='+encodeURIComponent(basePath));}var manifest=decode?A.__a9ResolveManifest(decode,A.__a9SimpleHeaders(),0):{ok:false},res=manifest.ok?A.__a8Resources(manifest.body||''):{key:'',segment:''},cfg=A.__a10CollectPlaybackConfig(refresh),extra=[];if(wm.playPath)extra.push(wm.playPath);try{var ents=A.__a4CdnEntries(refresh);for(var ei=0;ei<ents.length;ei++)if(ents[ei].domain)extra.push(ents[ei].domain);}catch(e1){}var sign=A.__a10FindSigner(res.segment,res.key,cfg,extra),chosen=sign.chosen,out={urls:[],names:[],headers:[]};A.setDiag('play_resign_probe',sign.logs.join('\n').slice(0,6000));if(chosen){var fixed=A.__a10RewriteManifest(manifest.body,chosen),local=A.__a10WriteManifest(id,fixed);if(local){out.urls.push(local+'#isM3u8#');out.names.push('本地重签HLS');out.headers.push({});}A.setDiag('play',JSON.stringify({id:id,seed:seed,watch:wm,selected:{mode:'client-resign',formula:chosen.mode,domain:chosen.domain,keyIndex:chosen.keyIndex,ts:chosen.ts},names:out.names,candidates:out.urls}));}else{var paths=A.__a9UniquePaths(wm,seed),ev=A.__a9EvaluateRoutes(paths,wr.cookie||''),ch=ev.chosen;if(ch){var cached=A.__a9Cache(id,ch.manifestUrl,ch.manifestHeaders);if(cached){out.urls.push(cached);out.names.push('原生矩阵缓存');out.headers.push(ch.segmentHeaders||{});}out.urls.push(ch.manifestUrl+'#isM3u8#');out.names.push('原生矩阵实时');out.headers.push(ch.manifestHeaders||{});}else if(decode){var cached2=A.__a9Cache(id,decode,A.__a9SimpleHeaders());if(cached2){out.urls.push(cached2);out.names.push('诊断回退缓存');out.headers.push({});}out.urls.push(decode+'#isM3u8#');out.names.push('诊断回退实时');out.headers.push(A.__a9SimpleHeaders());}A.setDiag('play',JSON.stringify({id:id,seed:seed,watch:wm,selected:null,signKeyAvailable:cfg.keys.length>0,names:out.names,candidates:out.urls}));}if(!out.urls.length)return'toast://未找到可播放线路';return JSON.stringify(out);};

A.__a10ComicRender=function(url,first){if(!first)return A.__a5ComicRender(url);var plain=A.s(url).trim();if(!plain)return'';plain=plain.replace(/_480(?=([?#]|$))/,'');var cache='hiker://files/cache/acfun_next_comic_first_trim_a10/'+A.md5(plain)+'.png',abs='';try{if(fileExist(cache))return getPath(cache);abs=getPath(cache);}catch(e0){}var headers={'User-Agent':'Dalvik/2.1.0 (Linux; U; Android 11; M2012K10C Build/RP1A.200720.011)','Referer':''};try{return $(plain,headers).image(function(cacheAbs){return $.require('acfunComicTrim?rule=ACFun').trimTop(cacheAbs);},abs);}catch(e){A.setDiag('comic_trim_error',plain+'\n'+A.s(e.message||e));return A.__a5ComicRender(plain);}};
A.comicReader=function(){var fid=A.param('comics_id'),cid=A.param('chapter_id'),cnum=A.param('chapter_num'),d=[];try{setPageTitle('');}catch(e0){}var obj=A.comicChapter(fid,cid,cnum);if(obj&&obj.canWatch===false){setResult([{title:'当前章节暂不可阅读',desc:A.s(A.pick(obj,['info','message','msg'],'需要权限或购买')),col_type:'long_text',url:'hiker://empty'}]);return;}var imgs=A.__a5ComicImageCandidates(obj),shape='keys='+Object.keys(obj||{}).slice(0,80).join(',')+'\ncount='+imgs.length+'\nfirst='+A.s(imgs[0]||'')+'\nraw='+JSON.stringify(obj||{}).slice(0,4500);A.setDiag('comic_payload_shape',shape);for(var i=0;i<imgs.length;i++){var pic=A.__a10ComicRender(imgs[i],i===0);if(pic)d.push({title:'',pic_url:pic,img:pic,col_type:'pic_1_full',url:'hiker://empty',extra:{lineVisible:false}});}if(!d.length)d.push({title:'章节没有可显示图片',col_type:'long_text',url:'hiker://empty'});setResult(d);};

A.diag=function(){setPageTitle('ACFun 资源诊断');var d=[];var text='版本：'+A.version+' / Build '+A.buildNumber+'\n运行：'+A.build+'\n接口：'+getItem('acfun_next_good_host','未建立')+'\n令牌：'+(getItem('acfun_next_token','')?'已建立':'无')+'\n图片域：'+getItem('acfun_next_img_domain','未记录')+'\n\n播放：\n'+A.getDiag('play')+'\n\ncan/watch：\n'+A.getDiag('play_watch')+'\nCDN刷新：\n'+A.getDiag('cdn_refresh')+'\n\n播放签名配置：\n'+A.getDiag('play_sign_config')+'\n\n播放重签探针：\n'+A.getDiag('play_resign_probe')+'\n\n播放路由矩阵：\n'+A.getDiag('play_route_matrix')+'\n\n漫画解密结构：\n'+A.getDiag('comic_payload_shape')+'\n漫画首图裁白：\n'+A.getDiag('comic_trim')+'\n漫画首图裁白错误：\n'+A.getDiag('comic_trim_error')+'\n漫画图片错误：\n'+A.getDiag('comic_image_error')+'\n\n最近接口：\n'+A.getDiag('last_api')+'\n\n请求错误：\n'+A.getDiag('api_error')+'\n\nProvider：\n'+A.getDiag('provider_error')+'\n\n游客：\n'+A.getDiag('traveler_error');d.push({title:text,col_type:'long_text',url:'hiker://empty'});d.push({title:'复制诊断',col_type:'text_1',url:'copy://'+text,extra:{lineVisible:false}});setResult(d);};
})();
