/** ACFun Next 1.0.0-alpha4 - CDN refresh + playback preflight + comic exact chapter model */
(function(){
if(typeof ACFunNext!=='object')throw new Error('ACFunNext alpha3 base missing');
var A=ACFunNext;
A.version='1.0.0-alpha4';
A.buildNumber=10004;
A.build='2026.08.23-v1.0.0-alpha4';
A.runtimeMode='clean-next+a4-cdn-chapter-model';
A.bootUrl='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/bootstrap_test_v083.js?v=8300';
A.bootVer=8300;
A.__a4Obj=function(v){return v&&typeof v==='object'?v:{};};
A.__a4CodeOk=function(jr){if(!jr||typeof jr!=='object')return false;if(jr.code===undefined&&jr.statusCode===undefined)return true;var c=Number(jr.code!==undefined?jr.code:jr.statusCode);return isNaN(c)||c===0||c===200;};
A.__a4Origin=function(u){var m=A.s(u).match(/^(https?:\/\/[^/]+)/i);return m?m[1]:'';};
A.__a4SignedHeaders=function(mode,host){
 host=A.s(host||getItem('acfun_next_good_host','')||A.staticApiHosts[0]).replace(/\/+$/,'');var h=A.headers(false,host),cred={};try{cred=A.__a2Credential(false)||{};}catch(e){}var literal=A.s(A.deep(cred,['referer','playerReferer','xReferer'],0)||'').trim();var h5=A.__a4Origin(A.h5Base)||A.__a4Origin(A.webBase)||host,ref='';if(mode==='literal'&&literal)ref=literal;else if(mode==='h5')ref=h5+'/';else if(mode==='host')ref=host+'/';h['User-Agent']='Mozilla/5.0 (Linux; Android 12; SM-G9750 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.72 Mobile Safari/537.36';if(ref){h.Referer=ref;h['X-Referer']=ref;}else{delete h.Referer;delete h['X-Referer'];}h.Origin=h5;return h;
};
A.__a4Hls=function(u){u=A.s(u).trim();return u&&u.indexOf('#isM3u8#')<0?u+'#isM3u8#':u;};
A.__a4Add=function(out,name,url,headers){url=A.s(url).trim();if(!url)return;var sig=name+'|'+url+'|'+JSON.stringify(headers||{});if(out.seen[sig])return;out.seen[sig]=1;out.urls.push(A.__a4Hls(url));out.names.push(name);out.headers.push(headers||{});};
A.__a4CdnRefresh=function(id,path,force){
 var ck='acfun_next_cdn_refresh',ts=Number(getItem(ck+'_ts','0')),old={};try{old=JSON.parse(getItem(ck,'{}'))||{};}catch(e){}if(!force&&ts&&Date.now()-ts<5*60*1000&&Object.keys(old).length)return old;
 var params=[{videoId:A.n(id),path:A.s(path)},{videoId:A.n(id)},{path:A.s(path)},{}],methods=['GET','POST'],attempts=[];
 for(var i=0;i<params.length;i++)for(var j=0;j<methods.length;j++){try{var o=A.api('video/cdn/refresh',params[i],{method:methods[j],timeout:1800});attempts.push(methods[j]+' '+JSON.stringify(params[i])+' OK '+JSON.stringify(o).slice(0,500));if(o&&typeof o==='object'){setItem(ck,JSON.stringify(o));setItem(ck+'_ts',String(Date.now()));A.setDiag('cdn_refresh',attempts.join('\n'));return o;}}catch(e2){attempts.push(methods[j]+' '+JSON.stringify(params[i])+' '+A.s(e2.message||e2));}}
 A.setDiag('cdn_refresh',attempts.slice(-12).join('\n'));return old;
};
A.__a4CdnEntries=function(root){var out=[],seen={},count=0;function add(v){if(!v||typeof v!=='object')return;var domain=A.s(A.pick(v,['playbackDomain','mediaDomain','m3u8Domain','domain','host'],'')).replace(/\/+$/,''),mp4=A.s(A.pick(v,['mp4Domain'],'')).replace(/\/+$/,''),auth=A.s(A.pick(v,['playbackAuthKey','authKey','auth_key'],'')).trim();if(domain||mp4||auth){var k=domain+'|'+mp4+'|'+auth;if(!seen[k]){seen[k]=1;out.push({domain:domain,mp4:mp4,auth:auth,raw:v});}}}function walk(v,d){if(!v||d>8||count++>2000)return;if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],d+1);return;}if(typeof v!=='object')return;add(v);for(var k in v)if(v[k]&&typeof v[k]==='object')walk(v[k],d+1);}walk(root,0);return out;};
A.__a4ProbeMedia=function(url,headers){url=A.s(url).replace(/#isM3u8#/g,'');if(!url)return{};try{var got=fetch(url,{timeout:2200,method:'GET',withStatusCode:true,headers:headers||{}}),w=A.safeJson(got),status=w?Number(w.statusCode||w.status||0):0,body=w&&w.body!==undefined?String(w.body||''):'',ct='';try{ct=A.s(w.headers&&((w.headers['Content-Type'])||(w.headers['content-type']))||'');}catch(e0){}var lines=body.split(/\r?\n/).slice(0,28).join('\n');A.setDiag('play_probe','HTTP '+status+' CT='+ct+'\n'+lines.slice(0,2600));return{status:status,body:body,contentType:ct};}catch(e){A.setDiag('play_probe','ERR '+A.s(e.message||e));return{};}};
A.play=function(id,raw,direct){
 id=A.s(id);var obj=A.safeJson(raw)||raw||{},path='';if(A.mediaLike(direct))path=A.s(direct);if(!path)path=A.mediaPath(obj);var used=path?'seed':'';
 if(!path&&id)try{var g=A.tryApi('video/can/watch',{videoId:A.n(id)},['GET'],{timeout:1800});path=A.mediaPath(g)||A.first(g&&g.path!==undefined?g.path:g);if(path)used='watch-get';}catch(e0){}if(!path&&id)try{var p=A.tryApi('video/can/watch',{videoId:A.n(id)},['POST'],{timeout:1800});path=A.mediaPath(p)||A.first(p&&p.path!==undefined?p.path:p);if(path)used='watch-post';}catch(e1){}if(!path){A.setDiag('play',JSON.stringify({id:id,used:used,path:''}));return'toast://未获取到播放地址';}
 var host=getItem('acfun_next_good_host','')||A.staticApiHosts[0],decode=A.decodePlayUrl(path),out={urls:[],names:[],headers:[],seen:{}},cred={};try{cred=A.__a2Credential(false)||{};}catch(e2){}var literal=A.s(A.deep(cred,['referer','playerReferer','xReferer'],0)||'').trim(),cdn=A.__a4CdnRefresh(id,path,false),entries=A.__a4CdnEntries(cdn);
 for(var i=0;i<entries.length;i++){var e=entries[i],dom=e.domain||e.mp4;if(!dom)continue;var u=dom+'/'+A.s(path).replace(/^\/+/, '');if(e.auth)u+=(u.indexOf('?')>=0?'&':'?')+'auth_key='+encodeURIComponent(e.auth);A.__a4Add(out,'CDN直连'+(i?String(i+1):''),u,A.__a4SignedHeaders(literal?'literal':'h5',host));if(e.domain){var q=encodeURIComponent(path);A.__a4Add(out,'APP播放'+(i?String(i+1):''),e.domain+'/api/m3u8/play?path='+q+(e.auth?'&authKey='+encodeURIComponent(e.auth):''),A.__a4SignedHeaders(literal?'literal':'h5',host));}}
 if(decode){var full=A.__a4SignedHeaders(literal?'literal':'h5',host);A.__a4Add(out,'解码·完整头',decode,full);A.__a4Add(out,'解码·H5头',decode,A.__a4SignedHeaders('h5',host));A.__a4Add(out,'解码·接口头',decode,A.__a4SignedHeaders('host',host));A.__a4ProbeMedia(decode,full);}
 delete out.seen;if(!out.urls.length)return'toast://未生成播放线路';A.setDiag('play',JSON.stringify({id:id,used:used,path:path,decode:decode,credentialReferer:literal,cdnEntries:entries.map(function(x){return{domain:x.domain,mp4:x.mp4,hasAuth:!!x.auth};}),names:out.names,candidates:out.urls,headers:out.headers}));return JSON.stringify(out);
};
A.__a4ChapterRows=function(root){root=root||{};var list=Array.isArray(root.chapterList)?root.chapterList:(Array.isArray(root.chapters)?root.chapters:[]),out=[];for(var i=0;i<list.length;i++){var x=list[i]||{},cid=A.pick(x,['chapterId','chapter_id'],''),generic=A.pick(x,['id'],'');if(!cid)cid=generic;var num=A.pick(x,['chapterNum','chapterNo','chapterIndex','sortNum'],''),title=A.pick(x,['chapterTitle','chapter_name','chapterName','title','name'],'第'+(i+1)+'章');if(cid||num)out.push({id:A.s(cid),num:A.s(num),title:A.s(title),raw:x});}if(list.length)A.setDiag('comic_detail_shape','rootKeys='+Object.keys(root).slice(0,80).join(',')+'\nchapterCount='+list.length+'\nfirst='+JSON.stringify(list[0]||{}).slice(0,3000));return out;};
A.comicDetail=function(seed){var obj=A.comicObject(seed.id,seed.raw),i=A.comicInfo(obj);if(!i.id)i.id=seed.id;if(!i.title&&seed.title)i.title=seed.title;if(!i.img&&seed.img)i.img=seed.img;setPageTitle(i.title||'漫画详情');var d=[];d.push({title:i.title,desc:[i.author,i.desc].join('\n').trim(),pic_url:A.image(i.img),img:A.image(i.img),col_type:'movie_1_vertical_pic_blur',url:'hiker://empty',extra:{gradient:true,lineVisible:false}});var favItem={kind:'comic',id:i.id,title:i.title,img:i.img,data:JSON.stringify(obj||{})};d.push({title:A.isFavorite(i.id)?'已收藏':'收藏漫画',col_type:'scroll_button',url:A.favoriteLazy(favItem),extra:{lineVisible:false}});d.push({title:'复制标题',col_type:'scroll_button',url:'copy://'+i.title,extra:{lineVisible:false}});var ch=A.__a4ChapterRows(obj);d.push({title:'章节目录 · '+ch.length,col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}});for(var c=0;c<ch.length;c++)d.push({title:ch[c].title,col_type:'text_2',url:A.page('acfun_next_comic_reader',{comics_id:i.id,chapter_id:ch[c].id,chapter_num:ch[c].num,chapter_title:ch[c].title}),extra:{inheritTitle:false,pageTitle:ch[c].title,lineVisible:false}});if(!ch.length)d.push({title:'暂未解析到章节目录',desc:'只读取真实 chapterList/chapters，不再递归误抓其它对象 id。',col_type:'long_text',url:'hiker://empty'});setResult(d);};
A.__a4ComicTransport=function(params,label){var hosts=A.apiHosts(false),attempts=[];for(var hi=0;hi<hosts.length;hi++){var host=hosts[hi].replace(/\/+$/,''),base=host+'/api/comics/base/chapterInfo';for(var mode=0;mode<2;mode++){var front=mode===1,target=buildUrl(base,params),headers=front?A.__a3FrontendHeaders(host):A.headers(false,host);try{var got=fetch(target,{timeout:2200,method:'GET',withStatusCode:true,headers:headers}),w=A.safeJson(got),status=w?Number(w.statusCode||w.status||0):0,body=w&&w.body!==undefined?String(w.body||''):'',jr=A.safeJson(body),code=jr&&jr.code!==undefined?Number(jr.code):NaN;attempts.push(label+' '+(front?'GET_FRONT':'GET_API')+' '+host+' HTTP_'+status+(isNaN(code)?'':' code='+code));if(status>=200&&status<300&&body.trim()&&(!jr||A.__a4CodeOk(jr))){var data=null;try{data=A.payload(body);}catch(e0){}if(data&&typeof data==='object'){var imgs=A.comicImages(data);if(imgs.length||data.canWatch===false||Array.isArray(data.imgList)){setItem('acfun_next_good_host',host);A.setDiag('comic_probe',attempts.join('\n')+'\nSUCCESS '+label+' '+target+'\nBODY '+body.slice(0,2200));return data;}}}}catch(e){attempts.push(label+' '+(front?'GET_FRONT':'GET_API')+' '+host+' '+A.s(e.message||e));}}}A.setDiag('comic_probe',A.getDiag('comic_probe')+'\n'+attempts.slice(-16).join('\n'));return{};};
A.comicChapter=function(comicsId,chapterId,chapterNum){comicsId=A.s(comicsId);chapterId=A.s(chapterId);chapterNum=A.s(chapterNum);var key='detail|comic-chapter-a4|'+comicsId+'|'+chapterId+'|'+chapterNum,c=A.cacheRead(key,600e3,86400e3);if(c.fresh&&c.data&&typeof c.data==='object')return c.data;A.setDiag('comic_probe','chapterId='+chapterId+' chapterNum='+chapterNum+' comicsId='+comicsId);var variants=[];function add(label,p){variants.push({label:label,p:p});}if(chapterId){add('chapterId',{chapterId:A.n(chapterId)});add('chapter_id',{chapter_id:A.n(chapterId)});add('id',{id:A.n(chapterId)});if(comicsId){add('comic+chapterId',{comicsId:A.n(comicsId),chapterId:A.n(chapterId)});add('comic+chapter_id',{comicsId:A.n(comicsId),chapter_id:A.n(chapterId)});}}if(chapterNum){add('chapterNum-as-id',{chapterId:A.n(chapterNum)});add('chapterNum',{chapterNum:A.n(chapterNum)});if(comicsId)add('comic+chapterNum',{comicsId:A.n(comicsId),chapterNum:A.n(chapterNum)});}for(var i=0;i<variants.length;i++){var o=A.__a4ComicTransport(variants[i].p,variants[i].label);if(o&&Object.keys(o).length){A.cacheWrite(key,o);return o;}}return c.hit&&c.data&&typeof c.data==='object'?c.data:{};};
A.comicReader=function(){var fid=A.param('comics_id'),cid=A.param('chapter_id'),cnum=A.param('chapter_num'),title=A.param('chapter_title')||'漫画章节',d=[];setPageTitle(title);var obj=A.comicChapter(fid,cid,cnum);if(obj&&obj.canWatch===false){setResult([{title:'当前章节暂不可阅读',desc:A.s(A.pick(obj,['info','message','msg'],'需要权限或购买')),col_type:'long_text',url:'hiker://empty'}]);return;}var imgs=A.comicImages(obj);for(var i=0;i<imgs.length;i++)d.push({title:'',pic_url:A.image(imgs[i]),img:A.image(imgs[i]),col_type:'pic_1_full',url:'hiker://empty',extra:{lineVisible:false}});if(!imgs.length)d.push({title:'章节没有返回图片',desc:'已尝试 chapterId / chapter_id / id / chapterNum 多种当前 APP 合同；请复制资源诊断中的漫画详情结构与章节探针。',col_type:'long_text',url:'hiker://empty'});setResult(d);};
A.diag=function(){setPageTitle('ACFun 资源诊断');var d=[];var text='版本：'+A.version+' / Build '+A.buildNumber+'\n运行：'+A.build+'\n接口：'+getItem('acfun_next_good_host','未建立')+'\n令牌：'+(getItem('acfun_next_token','')?'已建立':'无')+'\n图片域：'+getItem('acfun_next_img_domain','未记录')+'\n\n图片原始：\n'+A.getDiag('image_raw')+'\n图片解析：\n'+A.getDiag('image_resolved')+'\n图片渲染：\n'+A.getDiag('image_rendered')+'\n图片错误：\n'+A.getDiag('image_error')+'\n\n最近接口：\n'+A.getDiag('last_api')+'\n\n播放：\n'+A.getDiag('play')+'\n\n播放预检：\n'+A.getDiag('play_probe')+'\n\n播放凭据：\n'+A.getDiag('player_credential')+'\n\nCDN刷新：\n'+A.getDiag('cdn_refresh')+'\n\n漫画详情结构：\n'+A.getDiag('comic_detail_shape')+'\n\n漫画章节探针：\n'+A.getDiag('comic_probe')+'\n\n请求错误：\n'+A.getDiag('api_error')+'\n\nProvider：\n'+A.getDiag('provider_error')+'\n\n游客：\n'+A.getDiag('traveler_error');d.push({title:text,col_type:'long_text',url:'hiker://empty'});d.push({title:'复制诊断',col_type:'text_1',url:'copy://'+text,extra:{lineVisible:false}});setResult(d);};
})();
