/* 色花堂 0.1.0-test.10 / Build 10110 - guide age bridge + website-like thread preview gallery + cloud-play icons */
var SeHuaTangPatchTest10=(function(){
  var BASE=SeHuaTangRemoteRuntime;
  var VERSION='0.1.0-test.10',BUILD=10110,RULE_NAME='色花堂';
  var DEFAULT_ORIGIN='https://sehuatang.org';
  var KEY_ORIGIN='sht_origin_v1',KEY_COOKIE='sht_web_cookie_v5',KEY_ACCESS='sht_access_ok_v7',KEY_DIAG='sht_diag_v1';
  var UA_M='Mozilla/5.0 (Linux; Android 13; zh-CN) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Mobile Safari/537.36';
  var UA_PC='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36';
  var RAW='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/aggregate/sehuatang/assets/icons/v1/';
  var ICONS={web:'web.svg',search:'search.svg',original:'original.svg',reply:'reply.svg',copy:'copy.svg',settings:'settings.svg',cloud115:'cloud115.svg',thunder:'thunder.svg',pikpak:'pikpak.svg'};
  function s(v){return v==null?'':String(v)}
  function trim(v){return s(v).replace(/^\s+|\s+$/g,'')}
  function dec(v){v=s(v);try{return decodeURIComponent(v)}catch(e){return v}}
  function hdec(v){var x=s(v),i;for(i=0;i<2;i++)x=x.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;/gi,' ');return x}
  function strip(v){return trim(hdec(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/[\t\r]+/g,' ').replace(/\s+/g,' '))}
  function origin(){var o=trim(getItem(KEY_ORIGIN,DEFAULT_ORIGIN));return /^https?:\/\//i.test(o)?o.replace(/\/+$/,''):DEFAULT_ORIGIN}
  function abs(h,b){h=hdec(trim(h));if(!h)return'';if(/^https?:\/\//i.test(h))return h;if(/^\/\//.test(h))return'https:'+h;if(/^(javascript:|mailto:|tel:|#)/i.test(h))return'';var m=s(b).match(/^(https?:\/\/[^\/]+)/i),o=m?m[1]:origin();if(h.charAt(0)==='/')return o+h;var c=s(b).split('#')[0].split('?')[0];if(c.charAt(c.length-1)!=='/')c=c.replace(/\/[^\/]*$/,'/');return c+h.replace(/^\.\//,'')}
  function pageParam(n,d){var u=s(typeof MY_URL==='undefined'?'':MY_URL),m=u.match(new RegExp('[?&]'+n+'=([^&#]*)'));return m?dec(m[1]):(d==null?'':d)}
  function route(path,p){var u='hiker://page/'+path+'?rule='+RULE_NAME+'&simple=true',k;for(k in(p||{}))if(p.hasOwnProperty(k)&&p[k]!=null)u+='&'+k+'='+encodeURIComponent(s(p[k]));return u}
  function line(){return{col_type:'line'}}
  function section(t,d){return{title:t,desc:d||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}}}
  function empty(t,d){return{title:t,desc:d||'',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}}}
  function icon(n){return RAW+(ICONS[n]||ICONS.copy)}
  function quick(t,u,ico){var p=icon(ico);return{title:t,img:p,pic_url:p,url:u,col_type:'icon_small_4',extra:{lineVisible:false}}}
  function saveDiag(stage,msg){try{setItem(KEY_DIAG,JSON.stringify({stage:stage,origin:origin(),error:s(msg||'').slice(0,1800),time:new Date().getTime()}))}catch(e){}}
  function cookie(){var c='';try{c=getVar(KEY_COOKIE,'')||''}catch(e){}if(c)return c;try{c=getCookie(origin())||''}catch(e2){}return c}
  function headers(pc,ref){var c=cookie(),h={'User-Agent':pc?UA_PC:UA_M,'Referer':ref||origin()+'/'};if(c){h.Cookie=c;h.cookie=c}return h}
  function imageUrl(u,ref){u=abs(u,ref);if(!u)return'';return u+'@headers='+JSON.stringify(headers(false,ref||origin()+'/'))+'#originalSize#'}
  function threadId(u){var x=hdec(s(u)),m=x.match(/[?&]tid=(\d+)/i)||x.match(/[?&]ptid=(\d+)/i)||x.match(/\/thread-(\d+)-\d+-\d+\.html/i);return m?m[1]:''}
  function anchors(html,base){var out=[],re=/<a\b([^>]*?)href\s*=\s*(?:["']([^"']+)["']|([^\s>]+))([^>]*)>([\s\S]*?)<\/a>/gi,m,a,t,tm;while((m=re.exec(s(html)))!==null){a=(m[1]||'')+' '+(m[4]||'');t=strip(m[5]||'');if(!t){tm=a.match(/\b(?:title|aria-label)\s*=\s*["']([^"']+)["']/i);if(tm)t=strip(tm[1])}out.push({href:abs(m[2]||m[3]||'',base),text:t,inner:m[5]||'',attrs:a,index:m.index});if(out.length>16000)break}return out}
  function badThreadText(t){t=trim(t);if(!t||t.length<2)return true;if(/本帖最后由.+编辑|^(作者|回复于|发表于|查看|回复|最后发表|最后回复|上一页|下一页|返回|详情|进入|播放)/i.test(t))return true;if(/^\d{1,2}:\d{2}(?::\d{2})?$/.test(t)||/^\d+$/.test(t))return true;return false}
  function threadScore(t){t=trim(t);if(badThreadText(t))return-999;var n=Math.min(t.length,140);if(/[\u4e00-\u9fffA-Za-z]{2,}/.test(t))n+=35;if(t.length>=8)n+=20;if(/影片名称|原创|中文字幕|无码|有码|写真|视频/i.test(t))n+=12;return n}
  function validImage(u,base,attrs){u=abs(u,base);if(!u||/^data:/i.test(u))return'';if(/avatar\.php|noavatar|smiley|static\/image|logo\.|none\.gif|loading|blank\.gif|emotion|face\/|emoji|icon\//i.test(u))return'';var a=s(attrs),wm=a.match(/\bwidth\s*=\s*["']?(\d+)/i),hm=a.match(/\bheight\s*=\s*["']?(\d+)/i);if(wm&&hm&&Number(wm[1])<=96&&Number(hm[1])<=96)return'';return u}
  function imageCandidates(x,base){var out=[],seen={},re=/<img\b([^>]*)>/gi,m,a,names=['data-original','data-src','data-echo','data-lazy-src','zoomfile','file','src'],i,n,rr,mm,u,style;while((m=re.exec(s(x)))!==null){a=m[1]||'';u='';for(i=0;i<names.length;i++){n=names[i];rr=new RegExp('\\b'+n+'\\s*=\\s*(["\\\'])(.*?)\\1','i');mm=a.match(rr);if(mm){u=validImage(mm[2],base,a);if(u)break}}if(!u){style=a.match(/background(?:-image)?\s*:\s*url\((?:["']?)([^)"']+)/i);if(style)u=validImage(style[1],base,a)}if(u&&!seen[u]){seen[u]=1;out.push(u)}if(out.length>=60)break}return out}
  function contextAround(html,index){var x=s(html),start=x.lastIndexOf('<tbody',index),end=start>=0?x.indexOf('</tbody>',index):-1;if(start>=0&&end>=0&&end-start<40000)return x.slice(start,end+8);start=x.lastIndexOf('<li',index);end=start>=0?x.indexOf('</li>',index):-1;if(start>=0&&end>=0&&end-start<25000)return x.slice(start,end+5);return x.slice(Math.max(0,index-2200),Math.min(x.length,index+4400))}
  function parseThreads(html,base){var a=anchors(html,base),map={},order=[],i,x,id,t,sc,ctx,pics,out=[];for(i=0;i<a.length;i++){x=a[i];id=threadId(x.href);if(!id)continue;t=trim(x.text);sc=threadScore(t);if(!map[id]){map[id]={id:id,title:sc>-900?t:'',url:x.href,score:sc,index:x.index};order.push(id)}else if(sc>map[id].score){map[id].title=t;map[id].score=sc;map[id].url=x.href;map[id].index=x.index}}for(i=0;i<order.length;i++){id=order[i];x=map[id];if(!x||badThreadText(x.title))continue;ctx=contextAround(html,x.index);pics=imageCandidates(ctx,base);out.push({id:id,title:x.title.slice(0,150),url:x.url,img:pics.length?pics[0]:''});if(out.length>=100)break}return out}
  function guideView(kind){return kind==='latest'?'newthread':kind==='hot'?'hot':kind==='digest'?'digest':''}
  function guideUrl(kind,mobile){var v=guideView(kind);return origin()+'/forum.php?mod=guide&view='+v+(mobile?'&mobile='+mobile:'')}
  function ageAwareGuideHtml(u,kind){var needle='view='+guideView(kind),html='';try{html=s(fetchCodeByWebView(u,{headers:headers(false,u),timeout:22000,blockRules:['.woff','.woff2','.ttf'],checkJs:$.toString(function(target,needle,ckKey,accessKey){
      function txt(el){return String((el&&(el.innerText||el.textContent||el.value||el.getAttribute&&el.getAttribute('aria-label')))||'').replace(/\s+/g,' ').trim()}
      function age(t){return /满\s*18\s*岁|年满\s*18|over\s*18|18\s*years|please\s*click\s*here/i.test(t)}
      function save(){var c='';try{c=fba.getCookie(location.origin)||''}catch(e){}if(c)try{fba.putVar(ckKey,c)}catch(e2){}try{fba.putVar(accessKey,'1')}catch(e3){}}
      var body=String((document.body&&document.body.innerText)||'').replace(/\s+/g,' ');
      if(age(body)){var ns=document.querySelectorAll('a,button,input[type="button"],input[type="submit"],[onclick],[role="button"],div');for(var i=0;i<ns.length;i++){var t=txt(ns[i]);if(/满\s*18\s*岁|over\s*18|please\s*click\s*here/i.test(t)){try{ns[i].click();return null}catch(e4){}}}return null}
      save();
      if(location.href.indexOf(needle)<0&&document.querySelector('a[href*="forum-"],a[href*="forumdisplay"]')){location.href=target;return null}
      if(document.querySelector('a[href*="tid="],a[href*="thread-"]'))return'ready';
      return null;
    },u,needle,KEY_COOKIE,KEY_ACCESS)}))}catch(e){}return html}
  function renderGuide(kind,name){var d=[],urls=[guideUrl(kind,'no'),guideUrl(kind,'2'),guideUrl(kind,'')],i,u,h,items=[],img;setPageTitle(name);for(i=0;i<urls.length&&!items.length;i++){u=urls[i];h=ageAwareGuideHtml(u,kind);items=parseThreads(h,u);saveDiag('guide.v10',kind+' · '+u+' · html='+h.length+' · topics='+items.length)}d.push(quick('网页版','x5://'+(u||urls[0]),'web'));d.push(quick('搜索',route('shtSearch'),'search'));d.push(line());d.push(section(name,items.length?'已通过独立年龄确认链取得 '+items.length+' 条主题':'仍未取得主题'));for(i=0;i<items.length;i++){img=items[i].img?imageUrl(items[i].img,u):'';d.push({title:items[i].title,desc:'查看帖子',img:img,pic_url:img,url:route('shtThread',{sht_url:items[i].url,sht_name:items[i].title}),col_type:img?'movie_1':'text_1',extra:{lineVisible:false}})}if(!items.length){d.push(empty('三个话题入口仍未解析成功','Test10 已对 guide 页面单独执行 18+ 自动确认并回写 Cookie；若站点限制 guide 权限，可先点网页版确认'));d.push({title:'打开当前网页版',desc:urls[0],url:'x5://'+urls[0],col_type:'text_1'})}setResult(d)}

  function extractFloors(html){var out=[],seen={},nodes=[],i,j,k,body,author,key,selectors=['body&&#postlist>div','body&&#postlist&&div[id^=post_]'];for(i=0;i<selectors.length&&!out.length;i++){try{nodes=pdfa(html,selectors[i])||[]}catch(e){nodes=[]}for(j=0;j<nodes.length;j++){try{body=pdfh(nodes[j],'body&&div.t_fsz&&Html')||pdfh(nodes[j],'body&&div.t_f&&Html')||pdfh(nodes[j],'body&&td.t_f&&Html')||pdfh(nodes[j],'body&&.message&&Html')||''}catch(e2){body=''}if(!trim(strip(body)))continue;try{author=trim(pdfh(nodes[j],'body&&.authi&&a&&Text')||pdfh(nodes[j],'body&&.xw1&&Text')||'')}catch(e3){author=''}key=strip(body).slice(0,180);if(key&&!seen[key]){seen[key]=1;out.push({body:body,author:author})}}}if(out.length)return out;selectors=['body&&div.t_fsz','body&&div.t_f','body&&td.t_f','body&&[id^=postmessage_]','body&&.message'];for(i=0;i<selectors.length&&out.length<2;i++){try{nodes=pdfa(html,selectors[i])||[]}catch(e4){nodes=[]}for(k=0;k<nodes.length;k++){try{body=pdfh(nodes[k],'body&&Html')||s(nodes[k])}catch(e5){body=s(nodes[k])}if(!trim(strip(body)))continue;key=strip(body).slice(0,180);if(key&&!seen[key]){seen[key]=1;out.push({body:body,author:''})}}}return out}
  function plainBodyHtml(x){x=s(x).replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<iframe[\s\S]*?<\/iframe>/gi,'').replace(/<img\b[^>]*>/gi,'');x=x.replace(/<div[^>]*class=["'][^"']*(?:sign|signature)[^"']*["'][^>]*>[\s\S]*?<\/div>/gi,'').replace(/<div class=["']xs0["'][\s\S]*?<\/div>/gi,'').replace(/<p class=["']mbn["'][\s\S]*?<\/p>/gi,'').replace(/<div class=["']tip tip_4["'][\s\S]*?<\/div>/gi,'');x=x.replace(/<[^>]*>[^<]*本帖最后由[\s\S]*?编辑[^<]*<\/[^>]+>/gi,'');return x.replace(/(<br\s*\/?\s*>\s*){3,}/gi,'<br><br>')}
  function magnetList(x){var t=hdec(s(x)),out=[],seen={},m,re=/magnet:\?xt=urn:btih:[a-z0-9]{32,40}(?:&[^\s"'<>]*)?/ig,v,hm,key;while((m=re.exec(t))!==null){v=m[0].replace(/[)\]}>，。；;]+$/g,'');hm=v.match(/btih:([a-z0-9]{32,40})/i);key=hm?hm[1].toUpperCase():v.toLowerCase();if(!seen[key]){seen[key]=1;out.push({url:v,key:key,hash:hm?hm[1]:''})}if(out.length>=20)break}return out}
  function cleanMagnetsFromHtml(x,hasNew){x=s(x);if(hasNew){x=x.replace(/<a\b[^>]*href\s*=\s*["']magnet:[^"']*["'][^>]*>[\s\S]*?<\/a>/gi,'').replace(/magnet:\?xt=urn:btih:[a-z0-9]{32,40}(?:&[^\s"'<>]*)?/ig,'');x='<b>【磁链已识别，云播入口见预览图下方】</b><br>'+x}return x}
  function replyUrl(html,base){var m=s(html).match(/href=["']([^"']*(?:mod=post[^"']*action=reply|action=reply[^"']*mod=post)[^"']*)["']/i);return m?abs(m[1],base):base}
  function videoUrls(x){var out=[],seen={},m,re=/(https?:\/\/[^\s"'<>]+?\.(?:m3u8|mp4)(?:\?[^\s"'<>]*)?)/ig,u;while((m=re.exec(hdec(s(x))))!==null){u=m[1].replace(/[)\]}>，。；;]+$/g,'');if(!seen[u]){seen[u]=1;out.push(u)}if(out.length>=6)break}return out}
  function sniffSeed(x,base){var m=s(x).match(/<iframe\b[^>]*(?:src|data-src)\s*=\s*["']([^"']+)["']/i),u=m?abs(m[1],base):'';return u||base}
  function gallery(d,imgs,ref){var i,pu;for(i=0;i<imgs.length;i++){pu=imageUrl(imgs[i],ref);d.push({title:'',desc:'',img:pu,pic_url:pu,url:'pics://'+pu,col_type:'pic_3',extra:{lineVisible:false,imgLongClick:true}})}}
  function thread(){var m=BASE.module(),url=pageParam('sht_url',''),title=pageParam('sht_name','帖子详情'),r,floors,d=[],i,j,body,author,imgs,allMs,ms,seenMag={},bodyHtml,videos,videoHint,seed,ref;if(!url){setResult([empty('帖子参数缺失')]);return}setPageTitle(title||'帖子详情');r=m._debug&&m._debug.threadHtmlV9?m._debug.threadHtmlV9(url):{html:'',url:url,diag:'missing threadHtmlV9'};ref=r.url||url;floors=extractFloors(r.html);saveDiag('thread.visual.v10',(r.diag||'')+' · floors='+floors.length);d.push(section(title||'帖子详情','正文信息 + 三列预览图 + 磁链云播 + 回复'));d.push(quick('原帖','x5://'+url,'original'));d.push(quick('回复','x5://'+replyUrl(r.html,ref),'reply'));d.push(quick('复制链接','copy://'+url,'copy'));d.push(quick('设置',route('shtSettings'),'settings'));d.push(line());if(!floors.length){d.push(empty('未识别到帖子正文','请把设置 → 最近诊断截图发来'));setResult(d);return}for(i=0;i<floors.length&&i<20;i++){body=floors[i].body;author=floors[i].author||'';imgs=imageCandidates(body,ref);allMs=magnetList(body);ms=[];for(j=0;j<allMs.length;j++)if(!seenMag[allMs[j].key]){seenMag[allMs[j].key]=1;ms.push(allMs[j])}videos=videoUrls(body);videoHint=videos.length>0||/<video\b|<iframe\b|视频加载中|在线播放|dplayer|ckplayer|jwplayer|m3u8|\.mp4/i.test(body);seed=sniffSeed(body,ref);d.push(section(i===0?'楼主'+(author?' · '+author:''):'回复 '+i+(author?' · '+author:''),[imgs.length?imgs.length+' 张预览图':'',ms.length?ms.length+' 条磁链':'',videoHint?'检测到视频内容':''].filter(Boolean).join(' · ')));bodyHtml=cleanMagnetsFromHtml(plainBodyHtml(body),ms.length>0);if(trim(strip(bodyHtml)))d.push({title:bodyHtml,url:'hiker://empty',col_type:'rich_text',extra:{lineVisible:false}});if(imgs.length)gallery(d,imgs,ref);if(videos.length)d.push({title:'▶ 直接播放',desc:'已识别视频直链',url:videos[0]+'#isVideo=true#',col_type:'text_center_1',extra:{lineVisible:false}});if(videoHint)d.push({title:'▶ 嗅探播放',desc:'使用海阔自动提取网页视频',url:'video://'+seed,col_type:'text_center_1',extra:{lineVisible:false,ua:UA_M,referer:url,blockRules:['.jpg','.png','.gif','.woff','.woff2','.ttf'],cacheM3u8:true}});for(j=0;j<ms.length;j++){var magnet=ms[j].url,hash=ms[j].hash;d.push({title:'磁链 '+(j+1),desc:hash?hash.slice(0,14)+'…':'已识别',url:'copy://'+magnet,col_type:'text_1',extra:{lineVisible:false}});d.push(quick('115','hiker://page/115Offline?rule=115.简&page=fypage&add='+encodeURIComponent(magnet),'cloud115'));d.push(quick('迅雷','hiker://page/diaoyong?rule=迅雷&page=fypage#'+magnet,'thunder'));d.push(quick('PikPak','pikpakapp://mypikpak.com/xpan/main_tab?tab=1&add_url='+magnet,'pikpak'));d.push(quick('复制','copy://'+magnet,'copy'))}d.push(line())}setResult(d)}
  function settings(){var m=BASE.module(),prev=m.settings,d=[],dg={};setPageTitle('色花堂设置');d.push(section('Test10 话题验证与帖子预览布局','三个 guide 入口单独执行 18+ 自动确认；帖子图片改成三列预览图库；115/迅雷/PikPak 增加独立图标。'));try{dg=JSON.parse(getItem(KEY_DIAG,'{}')||'{}')}catch(e){}d.push({title:'最近诊断',desc:(dg.stage||'暂无')+'\n'+(dg.error||''),url:'hiker://empty',col_type:'long_text'});d.push({title:'打开 Test9 设置',desc:'分类缓存与旧诊断入口',url:route('shtSettingsLegacy'),col_type:'text_1'});setResult(d)}
  function module(){var m=BASE.module(),prevForum=m.forum;m.version=VERSION;m.build=BUILD;m.forum=function(){var kind=pageParam('sht_auto',''),name=pageParam('sht_name','主题列表');if(kind==='latest'||kind==='hot'||kind==='digest')return renderGuide(kind,name);return prevForum()};m.thread=thread;m.settings=settings;return m}
  var PATCHED={version:VERSION,build:BUILD,module:module};SeHuaTangRemoteRuntime=PATCHED;return PATCHED;
})();