/* Hanime1 Test18: real author/comment avatars + round fallback */
(function(C,P,E,H){
var oldVideo=P.video,oldComments=P.comments,oldReplies=P.replies;
var FALLBACK='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/hanime1/assets/avatar_default.svg';
function clean(v){return C.clean(String(v==null?'':v));}
function nodes(h,s){try{return pdfa(String(h||''),s)||[];}catch(e){return [];}}
function text(h,s){try{return clean(pdfh(h,s)||'');}catch(e){return '';}}
function attr(h,s){try{return String(pdfh(h,s)||'').trim();}catch(e){return '';}}
function firstText(h,a){for(var i=0;i<a.length;i++){var v=text(h,a[i]);if(v)return v;}return '';}
function firstAttr(h,a){for(var i=0;i<a.length;i++){var v=attr(h,a[i]);if(v)return v;}return '';}
function good(u){var s=String(u||'').toLowerCase();if(!s)return false;if(s.indexOf('data:image')===0)return false;if(s.indexOf('placeholder')>=0)return false;if(s.indexOf('loading')>=0)return false;if(s.indexOf('spinner')>=0)return false;if(s.indexOf('transparent')>=0)return false;if(s.indexOf('blank.')>=0)return false;return true;}
function abs(base,u){return good(u)?C.abs(base,u):'';}
function srcset(u){u=String(u||'').trim();if(!u)return '';var x=u.split(',')[0].trim().split(' ')[0];return x;}
function image(h,base){var a=['img[style*=object-fit]&&data-src','img[style*=object-fit]&&src','img&&data-src','img&&src','img&&data-srcset','img&&srcset'];for(var i=0;i<a.length;i++){var u=attr(h,a[i]);if(a[i].indexOf('srcset')>=0)u=srcset(u);if(good(u))return C.abs(base,u);}return '';}
function quoted(tag,key){var p=tag.indexOf(key);if(p<0)return '';p=tag.indexOf('=',p+key.length);if(p<0)return '';p++;while(p<tag.length&&tag.charAt(p)===' ')p++;var q=tag.charAt(p);if(q!=='"'&&q!=="'")return '';var e=tag.indexOf(q,p+1);return e>p?tag.slice(p+1,e):'';}
function firstImgTag(s,base){var p=s.indexOf('<img');while(p>=0){var e=s.indexOf('>',p);if(e<0)break;var tag=s.slice(p,e+1),u=quoted(tag,'data-src')||quoted(tag,'src')||quoted(tag,'data-srcset')||quoted(tag,'srcset');if(u.indexOf(',')>=0)u=srcset(u);if(good(u))return C.abs(base,u);p=s.indexOf('<img',e+1);}return '';}
function nearArtist(h,base){h=String(h||'');var p=h.indexOf('video-user-avatar');if(p<0)return '';var after=h.slice(p,Math.min(h.length,p+3200)),u=firstImgTag(after,base);if(u)return u;var before=h.slice(Math.max(0,p-1800),p);return firstImgTag(before,base);}
function artistSearch(name){name=clean(name);if(!name)return '';var base=C.resolveHost(false),url=C.query(base+'/search',{type:'artist',query:name,page:1}),r=C.get(url,{base:base,referer:base+'/',timeout:16000});if(!r||r.challenge||Number(r.statusCode||0)>=400)return '';var a=nodes(r.body,'.search-artist-card'),fallback='';for(var i=0;i<a.length;i++){var n=firstText(a[i],['.search-artist-title&&Text','.title&&Text']),u=image(a[i],base);if(!u)continue;if(!fallback)fallback=u;if(clean(n)===name)return u;}return fallback;}
function digits(s){s=String(s||'');var out='';for(var i=0;i<s.length;i++){var c=s.charAt(i);if(c>='0'&&c<='9')out+=c;else if(out)break;}return out?parseInt(out,10)||0:0;}
function jsonHtml(body,key){try{var j=JSON.parse(String(body||''));if(j&&typeof j[key]==='string')return j[key];}catch(e){}return String(body||'');}
function commentGroup(group,base){var f=nodes(group,'.comment-index-text');if(f.length<2)return null;var user=firstText(f[0],['a&&Text','Text']),content=text(f[1],'Text');if(!user||!content)return null;var rw=nodes(group,'div[id^=reply-section-wrapper]'),rid=rw.length?String(attr(rw[0],'id')).split('-').pop():'',reply=firstText(group,['div.load-replies-btn&&Text','div[class^=load-replies-btn]&&Text']);return {id:rid,user:user,content:content,time:firstText(f[0],['span&&Text']),avatar:image(group,base)||FALLBACK,replyCount:digits(reply)};}
P.video=function(id){var v=oldVideo(id),base=v.base||C.resolveHost(false);if(!good(v.artistAvatar)){var u=nearArtist(v.raw,base);if(!u)u=artistSearch(v.artist);v.artistAvatar=u||FALLBACK;}if(v.uploader&&v.uploader.name&&!good(v.uploader.avatar))v.uploader.avatar=FALLBACK;return v;};
P.comments=function(videoId){var base=C.resolveHost(false),url=C.query(base+'/loadComment',{type:'video',id:videoId}),r=C.get(url,{base:base,referer:base+'/watch?v='+videoId,timeout:16000});if(!r||r.challenge||Number(r.statusCode||0)>=400)return oldComments(videoId);var body=jsonHtml(r.body,'comments'),children=nodes(body,'#comment-start > *');if(!children.length)children=nodes(body,'#comment-start>*');var out=[];for(var i=0;i+1<children.length;i+=4){var group='';for(var j=i;j<Math.min(i+4,children.length);j++)group+=String(children[j]||'');var c=commentGroup(group,base);if(c)out.push(c);}if(!out){var old=oldComments(videoId);if(old&&old.items){for(i=0;i<old.items.length;i++)if(!good(old.items[i].avatar))old.items[i].avatar=FALLBACK;}return old;}return {items:out,csrf:firstAttr(body,['input[name=_token]&&value']),userId:firstAttr(body,['input[name=comment-user-id]&&value'])};};
P.replies=function(commentId){var base=C.resolveHost(false),r=C.get(C.query(base+'/loadReplies',{id:commentId}),{base:base,referer:base+'/',timeout:16000});if(!r||r.challenge||Number(r.statusCode||0)>=400)return oldReplies(commentId);var body=jsonHtml(r.body,'replies'),children=nodes(body,'div[id^=reply-start] > *');if(!children.length)children=nodes(body,'div[id^=reply-start]>*');var out=[];for(var i=0;i+1<children.length;i+=2){var group=String(children[i]||'')+String(children[i+1]||''),c=commentGroup(group,base);if(c)out.push(c);}if(!out){out=oldReplies(commentId)||[];for(i=0;i<out.length;i++)if(!good(out[i].avatar))out[i].avatar=FALLBACK;}return out;};
HanimePages.build='2.0.0-test.18';HanimeCore.build='2.0.0-test.18';HanimeProvider.build='2.0.0-test.18';
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9);
