/* PikPak Remote Test Bootstrap 0.1.0-test.19 Build10121 - cloud search and multi-account sessions */
var PIKPAK_BOOT_CONFIG={id:'pikpak-test',branch:'main',repoRawRoot:'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/',version:'0.1.0-test.19',build:10121,modules:[
{name:"core-base",path:"apps/cloud/pikpak/releases/0.1.0-test.3/core.js"},
{name:"core-test10-current-android-auth",path:"apps/cloud/pikpak/releases/0.1.0-test.10-b10112/core_android_patch.js"},
{name:"core-test10-android-migration",path:"apps/cloud/pikpak/releases/0.1.0-test.10-b10112/auth_migration_patch.js"},
{name:"core-test11-web-token-handoff",path:"apps/cloud/pikpak/releases/0.1.0-test.11-b10113/core_web_token_patch.js"},
{name:"core-test12-access-first",path:"apps/cloud/pikpak/releases/0.1.0-test.12-b10114/core_access_first_patch.js"},
{name:"core-test19-multi-account",path:"apps/cloud/pikpak/releases/0.1.0-test.19-b10121/core_accounts_patch.js"},
{name:"provider",path:"apps/cloud/pikpak/releases/0.1.0-test.1/provider.js"},
{name:"provider-test5-safe-cleanup",path:"apps/cloud/pikpak/releases/0.1.0-test.5/provider_patch.js"},
{name:"provider-test6-handoff",path:"apps/cloud/pikpak/releases/0.1.0-test.6/provider_patch.js"},
{name:"provider-test16-drive-management",path:"apps/cloud/pikpak/releases/0.1.0-test.16-b10118/provider_drive_patch.js"},
{name:"provider-test17-library",path:"apps/cloud/pikpak/releases/0.1.0-test.17-b10119/provider_library_patch.js"},
{name:"provider-test18-cleanup-setting",path:"apps/cloud/pikpak/releases/0.1.0-test.18-b10120/provider_cleanup_setting_patch.js"},
{name:"provider-test19-account-temp-scope",path:"apps/cloud/pikpak/releases/0.1.0-test.19-b10121/provider_account_temp_patch.js"},
{name:"playback",path:"apps/cloud/pikpak/releases/0.1.0-test.1/playback.js"},
{name:"playback-test16-my-pack",path:"apps/cloud/pikpak/releases/0.1.0-test.16-b10118/playback_drive_patch.js"},
{name:"playback-test18-image-preview",path:"apps/cloud/pikpak/releases/0.1.0-test.18-b10120/playback_image_patch.js"},
{name:"ui",path:"apps/cloud/pikpak/releases/0.1.0-test.1/ui.js"},
{name:"ui-test16-drive",path:"apps/cloud/pikpak/releases/0.1.0-test.16-b10118/ui_drive_patch.js"},
{name:"ui-test17-library",path:"apps/cloud/pikpak/releases/0.1.0-test.17-b10119/ui_library_patch.js"},
{name:"ui-test18-image",path:"apps/cloud/pikpak/releases/0.1.0-test.18-b10120/ui_image_patch.js"},
{name:"ui-test19-search-accounts",path:"apps/cloud/pikpak/releases/0.1.0-test.19-b10121/ui_accounts_search_patch.js"},
{name:"pages-base",path:"apps/cloud/pikpak/releases/0.1.0-test.1/pages.js"},
{name:"pages-test5-verification-runtime-contract",path:"apps/cloud/pikpak/releases/0.1.0-test.5/pages_patch.js"},
{name:"pages-test7-cleanup-semantics",path:"apps/cloud/pikpak/releases/0.1.0-test.7/pages_patch.js"},
{name:"pages-test10-android-auth",path:"apps/cloud/pikpak/releases/0.1.0-test.10-b10112/pages_android_patch.js"},
{name:"pages-test11-web-token-handoff",path:"apps/cloud/pikpak/releases/0.1.0-test.11-b10113/pages_web_token_patch.js"},
{name:"pages-test15-web-session-bridge",path:"apps/cloud/pikpak/releases/0.1.0-test.15-b10117/pages_web_session_bridge.js"},
{name:"pages-test16-drive",path:"apps/cloud/pikpak/releases/0.1.0-test.16-b10118/pages_drive_patch.js"},
{name:"pages-test17-library",path:"apps/cloud/pikpak/releases/0.1.0-test.17-b10119/pages_library_patch.js"},
{name:"pages-test18-settings",path:"apps/cloud/pikpak/releases/0.1.0-test.18-b10120/pages_settings_patch.js"},
{name:"pages-test19-search-accounts",path:"apps/cloud/pikpak/releases/0.1.0-test.19-b10121/pages_accounts_search_patch.js"},
{name:"runtime-base",path:"apps/cloud/pikpak/releases/0.1.0-test.1/runtime.js"},
{name:"runtime-test5-verification",path:"apps/cloud/pikpak/releases/0.1.0-test.5/runtime_patch.js"},
{name:"runtime-test6-handoff",path:"apps/cloud/pikpak/releases/0.1.0-test.6/runtime_patch.js"},
{name:"runtime-test10-android-auth",path:"apps/cloud/pikpak/releases/0.1.0-test.10-b10112/runtime_android_patch.js"},
{name:"runtime-test11-web-token-handoff",path:"apps/cloud/pikpak/releases/0.1.0-test.11-b10113/runtime_web_token_patch.js"},
{name:"runtime-test16-drive",path:"apps/cloud/pikpak/releases/0.1.0-test.16-b10118/runtime_drive_patch.js"},
{name:"runtime-test17-library",path:"apps/cloud/pikpak/releases/0.1.0-test.17-b10119/runtime_library_patch.js"},
{name:"runtime-test18-settings",path:"apps/cloud/pikpak/releases/0.1.0-test.18-b10120/runtime_settings_patch.js"},
{name:"runtime-test19-search-accounts",path:"apps/cloud/pikpak/releases/0.1.0-test.19-b10121/runtime_accounts_search_patch.js"},
{name:"runtime-test19-identity",path:"apps/cloud/pikpak/releases/0.1.0-test.19-b10121/runtime_version_patch.js"}
]};
var PikPakBoot={
loadOnly:function(){var root=PIKPAK_BOOT_CONFIG.repoRawRoot+PIKPAK_BOOT_CONFIG.branch+'/',loaded=[],i,m,url;for(i=0;i<PIKPAK_BOOT_CONFIG.modules.length;i++){m=PIKPAK_BOOT_CONFIG.modules[i];url=root+m.path+'?pikpak_release=0.1.0-test.19-b10121';require(url,{headers:{'Cache-Control':'no-cache'}},10121);loaded.push({name:m.name,url:url});}if(typeof PikPakRemoteRuntime==='undefined'||String(PikPakRemoteRuntime.version)!=='0.1.0-test.19'||Number(PikPakRemoteRuntime.build)!==10121)throw new Error('PikPak Test19 Build10121 运行时校验失败');return {ok:true,release:{id:'pikpak-test',version:'0.1.0-test.19',build:10121,variant:'cloud-search-multi-account-session'},loaded:loaded};},
module:function(){this.loadOnly();return PikPakRemoteRuntime.module();},
info:function(){return {managerVersion:'direct-loader',current:{id:'pikpak-test',version:'0.1.0-test.19',build:10121,variant:'cloud-search-multi-account-session'}};},
check:function(){return {ok:true,current:{id:'pikpak-test',version:'0.1.0-test.19',build:10121},hasUpdate:false};},
update:function(){return {ok:false,changed:false,error:'测试版采用完整导入口令覆盖更新'};},
rollback:function(){return {ok:false,error:'需要时覆盖导入上一版本'};},
reinstall:function(){return this.loadOnly();}
};
