/* XVideos Remote Core 0.1.0-test.1 - clean architecture */
var XVideosCore=(function(){
  var C={};
  C.version='0.1.0-test.1';
  C.build=10101;
  C.defaultBase='https://www.xvideos.com';
  C.bootstrap='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/xvideos/bootstrap_test_v1_b10101.js?v=10101';
  C.ua='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36';
  C.cachePrefix='xv_v1_';
  C.baseKey='xv_base_v1';
  C.authCookieKey='xv_auth_cookie_v1';
  C.authEnabledKey='xv_auth_enabled_v1';
  C.accountNameKey='xv_account_name_v1';
  C.favoriteKey='xv_local_favorites_v1';
  C.historyKey='xv_local_history_v1';
  C.maxLocalItems=100;
  C.brand='#e31b23';

  C.s=function(v){return v===undefined||v===null?'':String(v);};
  C.trim=function(v){return C.s(v).replace(/^\s+|\s+$/g,'');};
  C.clean=function(v){var s=C.s(v);if(s==='null'||s==='undefined')return'';return C.trim(s);};
  C.decode=function(v){return C.s(v).replace(/&amp;/ig,'&').replace(/&#38;/ig,'&').replace(/&quot;/ig,'"').replace(/&#39;|&#039;|&apos;/ig,"'").replace(/&#x27;/ig,"'").replace(/&nbsp;/ig,' ').replace(/&lt;/ig,'<').replace(/&gt;/ig,'>').replace(/&#(\d+);/g,function(_,n){var x=parseInt(n,10);return x?String.fromCharCode(x):_;});};
  C.strip=function(v){return C.trim(C.decode(C.s(v).replace(/<br\s*\/?\s*>/ig,'\n').replace(/<script\b[\s\S]*?<\/script>/ig,' ').replace(/<style\b[\s\S]*?<\/style>/ig,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' '));};
  C.base=function(){var b=C.trim(getItem(C.baseKey,C.defaultBase));if(!/^https?:\/\//i.test(b))b=C.defaultBase;return b.replace(/\/+$/,'');};
  C.origin=function(u){var m=C.s(u).match(/^(https?:\/\/[^\/]+)/i);return m?m[1]:C.base();};
  C.abs=function(u,base){u=C.decode(C.trim(u));base=base||C.base();if(!u)return'';u=u.replace(/\\\//g,'/');if(/^https?:\/\//i.test(u))return u;if(/^\/\//.test(u))return'https:'+u;if(/^data:/i.test(u)||/^javascript:/i.test(u)||u.charAt(0)==='#')return'';var o=C.origin(base);if(u.charAt(0)==='/')return o+u;if(u.charAt(0)==='?')return C.s(base).replace(/[?#].*$/,'')+u;return C.s(base).replace(/[?#].*$/,'').replace(/[^\/]*$/,'')+u;};
  C.q=function(v){return encodeURIComponent(C.s(v));};
  C.hash=function(s){s=C.s(s);var h=0,i;for(i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return Math.abs(h);};
  C.cacheKey=function(s){return C.cachePrefix+C.hash(s);};
  C.ruleTitle=function(){try{return MY_RULE&&MY_RULE.title?MY_RULE.title:'XVideos';}catch(e){return'XVideos';}};
  C.param=function(name,def){var u='';try{u=C.s(MY_URL);}catch(e){}var m=u.match(new RegExp('[?&]'+name+'=([^&#]*)'));if(!m)return def===undefined?'':def;try{return decodeURIComponent(m[1]);}catch(e2){return m[1];}};
  C.page=function(path,params){var a=['rule='+encodeURIComponent(C.ruleTitle()),'simple=true'];params=params||{};for(var k in params)if(params.hasOwnProperty(k)&&params[k]!==undefined&&params[k]!==null&&C.s(params[k])!=='')a.push(encodeURIComponent(k)+'='+encodeURIComponent(C.s(params[k])));return'hiker://page/'+path+'?'+a.join('&');};
  C.pageNo=function(){var p=1;try{p=parseInt(MY_PAGE||1,10)||1;}catch(e){p=parseInt(C.param('page','1'),10)||1;}return p;};
  C.queryPage=function(url,page){page=parseInt(page,10)||1;var n=Math.max(0,page-1);if(n<=0)return url;if(/[?&]p=\d+/i.test(url))return url.replace(/([?&]p=)\d+/i,'$1'+n);return url+(url.indexOf('?')>=0?'&':'?')+'p='+n;};
  C.form=function(o){var a=[];for(var k in o)if(o.hasOwnProperty(k)&&o[k]!==undefined&&o[k]!==null)a.push(encodeURIComponent(k)+'='+encodeURIComponent(C.s(o[k])));return a.join('&');};

  C.authEnabled=function(){return getItem(C.authEnabledKey,'0')==='1';};
  C.savedCookie=function(){return C.authEnabled()?C.clean(getItem(C.authCookieKey,'')):'';};
  C.headers=function(ref,auth,accept){var h={'User-Agent':C.ua,'Referer':ref||C.base()+'/','Accept':accept||'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Accept-Language':'en-US,en;q=0.9'};var cookie=auth?C.savedCookie():'';if(cookie)h.Cookie=cookie;return h;};
  C.image=function(u,ref){u=C.abs(u,ref||C.base());if(!u)return'';return u+'@headers='+JSON.stringify({'User-Agent':C.ua,'Referer':ref||C.base()+'/'});};
  C.videoUrl=function(u,ref){u=C.clean(u);if(!u)return'';return u+';{Referer@'+(ref||C.base()+'/')+'&&User-Agent@Mozilla/5.0}#isVideo=true#';};
  C.isBad=function(body){var s=C.s(body),l=s.toLowerCase();return s.length<120||l.indexOf('just a moment')>=0||l.indexOf('cf-chl-')>=0||l.indexOf('attention required')>=0||(l.indexOf('captcha')>=0&&s.length<8000);};
  C.fetchText=function(url,opt){opt=opt||{};var key=C.cacheKey((opt.auth?'auth:':'anon:')+url),tsKey=key+'_ts',now=new Date().getTime(),ttl=opt.ttl===undefined?3*60*1000:opt.ttl,old=getItem(key,''),ts=parseInt(getItem(tsKey,'0'),10)||0;if(!opt.force&&old&&now-ts<ttl)return old;var body='';try{body=C.s(fetch(url,{timeout:opt.timeout||12000,headers:C.headers(opt.ref||url,!!opt.auth,opt.accept)}));}catch(e){body='';}if(!C.isBad(body)){if(body.length<240000){try{setItem(key,body);setItem(tsKey,String(now));}catch(e2){}}return body;}return old||body;};
  C.fetchJson=function(url,opt){var s=C.fetchText(url,opt||{});try{return JSON.parse(s);}catch(e){return null;}};
  C.clearCache=function(){try{deleteCache();}catch(e){}return true;};

  C.attr=function(tag,name){var m=C.s(tag).match(new RegExp('(?:^|\\s)'+name+'\\s*=\\s*["\\\']([^"\\\']*)["\\\']','i'));return m?C.decode(m[1]):'';};
  C.meta=function(html,key){var s=C.s(html),k=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),re=new RegExp('<meta[^>]+(?:property|name)=["\\\']'+k+'["\\\'][^>]+content=["\\\']([^"\\\']+)["\\\']','i'),m=s.match(re);if(!m){re=new RegExp('<meta[^>]+content=["\\\']([^"\\\']+)["\\\'][^>]+(?:property|name)=["\\\']'+k+'["\\\']','i');m=s.match(re);}return m?C.decode(m[1]):'';};
  C.imgFrom=function(raw,base){var m=C.s(raw).match(/<img\b[^>]*(?:data-src|data-original|data-lazy-src|data-thumb|data-poster|src)\s*=\s*["']([^"']+)["'][^>]*>/i);return m?C.abs(m[1],base):'';};
  C.context=function(html,index,before,after){html=C.s(html);return html.substring(Math.max(0,index-(before||500)),Math.min(html.length,index+(after||1200)));};
  C.unique=function(items,key){var out=[],seen={},i,k;for(i=0;i<items.length;i++){k=key?key(items[i]):C.s(items[i]);if(!k||seen[k])continue;seen[k]=1;out.push(items[i]);}return out;};
  C.allAnchors=function(html,base){var s=C.s(html),out=[],re=/<a\b([^>]*)href\s*=\s*["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/ig,m;while((m=re.exec(s))){var href=C.abs(m[2],base||C.base());if(!href)continue;out.push({href:href,raw:m[0],text:C.strip(m[4]),title:C.attr(m[1]+' '+m[3],'title'),index:m.index});}return out;};
  C.isVideoLink=function(u){u=C.s(u);return /\/video(?:\.|-)?\d+[\/_-]/i.test(u)||/\/video\d+\//i.test(u);};
  C.videoId=function(u){var m=C.s(u).match(/\/video(?:\.|-)?(\d+)/i);return m?m[1]:'';};

  C.parseVideoCards=function(html,base){var s=C.s(html),a=C.allAnchors(s,base||C.base()),out=[],seen={},i,it,ctx,title,img,dur,views,u,id,pv;for(i=0;i<a.length;i++){it=a[i];u=it.href;if(!C.isVideoLink(u)||seen[u])continue;ctx=C.context(s,it.index,900,2200);title=C.clean(it.title||it.text);if(!title||title.length<2||title.length>220){var tm=ctx.match(/<div[^>]+class=["'][^"']*thumb-under[^"']*["'][\s\S]{0,900}?<a[^>]*>([\s\S]*?)<\/a>/i)||ctx.match(/(?:title|alt)\s*=\s*["']([^"']{2,220})["']/i);if(tm)title=C.strip(tm[1]);}
    img=C.imgFrom(ctx,u);if(!img){var im=ctx.match(/(?:data-src|data-original|src)=["']([^"']+)["']/i);if(im)img=C.abs(im[1],u);}dur='';var dm=ctx.match(/<span[^>]+class=["'][^"']*duration[^"']*["'][^>]*>([^<]+)<\/span>/i)||ctx.match(/\b(\d{1,2}:\d{2}(?::\d{2})?)\b/);if(dm)dur=C.strip(dm[1]||dm[0]);views='';var vm=ctx.match(/class=["'][^"']*metadata[^"']*["'][\s\S]{0,700}?([\d,.]+\s*[KMB]?)\s*(?:views?|vues|vistas)?/i);if(vm)views=C.strip(vm[1]);id=C.videoId(u);pv='';var pvm=ctx.match(/data-pvv=["']([^"']+)["']/i);if(pvm)pv=C.abs(pvm[1],u);if(!title)title=id?'Video #'+id:'Video';seen[u]=1;out.push({url:u,title:title,img:C.image(img,u),rawImg:img,duration:dur,views:views,preview:pv,desc:[dur,views?views+' views':''].filter(function(x){return!!x;}).join(' · ')});}return out;};

  C.searchUrl=function(q,page,opt){opt=opt||{};var u=C.base()+'/?k='+C.q(q||'');if(opt.sort)u+='&sort='+C.q(opt.sort);if(opt.datef)u+='&datef='+C.q(opt.datef);if(opt.durf)u+='&durf='+C.q(opt.durf);if(opt.quality)u+='&quality='+C.q(opt.quality);return C.queryPage(u,page||1);};
  C.searchVideos=function(q,page,opt){var u=C.searchUrl(q,page,opt),h=C.fetchText(u,{ttl:2*60*1000,auth:C.authEnabled()}),cards=C.parseVideoCards(h,u);return{url:u,cards:cards,html:h};};
  C.homeVideos=function(mode,page){var b=C.base(),u=b+'/';if(mode==='best')u=b+'/best';else if(mode==='new')u=b+'/new';else if(mode==='rated')u=b+'/?sort=rating';else if(mode==='views')u=b+'/?sort=views';u=C.queryPage(u,page||1);var h=C.fetchText(u,{ttl:3*60*1000,auth:C.authEnabled()}),cards=C.parseVideoCards(h,u);if(!cards.length&&mode!=='home'){u=C.searchUrl('',page||1,{sort:mode==='new'?'uploaddate':mode==='rated'?'rating':mode==='views'?'views':'relevance'});h=C.fetchText(u,{ttl:3*60*1000,auth:C.authEnabled()});cards=C.parseVideoCards(h,u);}return{url:u,cards:cards,html:h};};

  C.tagList=function(force){var b=C.base(),u=b+'/tags',h=C.fetchText(u,{force:!!force,ttl:60*60*1000}),a=C.allAnchors(h,u),out=[],seen={},i,it,n;for(i=0;i<a.length;i++){it=a[i];if(C.isVideoLink(it.href)||/\/(?:profiles|channels|pornstars)\//i.test(it.href))continue;if(!(/\/tags?\//i.test(it.href)||/\/c\//i.test(it.href)||/[?&]k=/.test(it.href)))continue;n=C.clean(it.text||it.title);if(!n||n.length<2||n.length>55||seen[n.toLowerCase()])continue;seen[n.toLowerCase()]=1;out.push({name:n,url:it.href});}return out.slice(0,350);};
  C.tagVideos=function(url,page){url=C.queryPage(url,page||1);var h=C.fetchText(url,{ttl:4*60*1000}),cards=C.parseVideoCards(h,url);return{url:url,cards:cards};};

  C.profileType=function(u){u=C.s(u);if(/\/pornstars\//i.test(u))return'pornstar';if(/\/channels\//i.test(u))return'channel';if(/\/profiles\//i.test(u))return'profile';return'';};
  C.parseProfiles=function(html,base,onlyType){var s=C.s(html),a=C.allAnchors(s,base||C.base()),out=[],seen={},i,it,typ,ctx,name,img,desc;for(i=0;i<a.length;i++){it=a[i];typ=C.profileType(it.href);if(!typ||(onlyType&&typ!==onlyType)||seen[it.href])continue;ctx=C.context(s,it.index,800,1600);name=C.clean(it.title||it.text);if(!name||name.length<2||name.length>90){var nm=ctx.match(/(?:title|alt)\s*=\s*["']([^"']{2,90})["']/i);name=nm?C.clean(C.decode(nm[1])):'';}img=C.imgFrom(ctx,it.href);if(!name||!img)continue;desc=typ==='pornstar'?'演员':typ==='channel'?'频道':'用户';var sm=ctx.match(/([\d,.]+\s*(?:subscribers?|videos?|views?))/i);if(sm)desc+=' · '+C.strip(sm[1]);seen[it.href]=1;out.push({url:it.href,title:name,img:C.image(img,it.href),rawImg:img,type:typ,desc:desc});}return out;};
  C.creatorList=function(kind,page,q){var b=C.base(),path=kind==='channels'?'channels':kind==='profiles'?'profiles':'pornstars',u=b+'/'+path;if(q)u+='?k='+C.q(q);u=C.queryPage(u,page||1);var h=C.fetchText(u,{ttl:5*60*1000,auth:C.authEnabled()}),type=kind==='channels'?'channel':kind==='profiles'?'profile':'pornstar',profiles=C.parseProfiles(h,u,q?'':type);return{url:u,profiles:profiles,html:h};};

  C.jsonLd=function(html){var out={},re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/ig,m,j;while((m=re.exec(C.s(html)))){try{j=JSON.parse(C.trim(m[1]));if(j&&typeof j==='object'){if(Object.prototype.toString.call(j)==='[object Array]'){for(var i=0;i<j.length;i++)if(j[i]&&typeof j[i]==='object')for(var k in j[i])if(j[i].hasOwnProperty(k))out[k]=j[i][k];}else for(var k2 in j)if(j.hasOwnProperty(k2))out[k2]=j[k2];}}catch(e){}}return out;};
  C.jsArg=function(html,name){var re=new RegExp('html5player\\.'+name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\(["\\\']([^"\\\']+)["\\\']\\)','i'),m=C.s(html).match(re);return m?C.decode(m[1]):'';};
  C.playSources=function(html,url){var out=[],seen={},push=function(name,u){u=C.clean(C.decode(u));if(!u||seen[u])return;seen[u]=1;out.push({name:name,url:C.abs(u,url)});};var hls=C.jsArg(html,'setVideoHLS');if(hls)push('HLS 自动',hls);var p1080=C.jsArg(html,'setVideoUrl1080p');if(p1080)push('1080P',p1080);var high=C.jsArg(html,'setVideoUrlHigh');if(high)push('高清 MP4',high);var low=C.jsArg(html,'setVideoUrlLow');if(low)push('流畅 MP4',low);var data=C.jsonLd(html),cu=data.contentUrl||data.contentURL||'';if(cu)push('原始视频',cu);return out;};
  C.expandHls=function(src,ref){if(!src||!/\.m3u8(?:$|\?)/i.test(src))return[];var h=C.fetchText(src,{force:true,ttl:0,timeout:10000,ref:ref,accept:'application/vnd.apple.mpegurl,application/x-mpegURL,*/*'});if(h.indexOf('#EXT-X-STREAM-INF')<0)return[];var lines=h.replace(/\r/g,'').split('\n'),out=[],i,info,m,name,u;for(i=0;i<lines.length;i++){if(lines[i].indexOf('#EXT-X-STREAM-INF:')!==0)continue;info=lines[i];m=info.match(/RESOLUTION=\d+x(\d+)/i);name=m?m[1]+'P':'HLS';u='';for(var j=i+1;j<lines.length;j++){if(lines[j]&&lines[j].charAt(0)!=='#'){u=C.abs(lines[j],src);break;}}if(u)out.push({name:name,url:u});}return C.unique(out,function(v){return v.url;});};
  C.authorFrom=function(html,url){var s=C.s(html),m=s.match(/<li[^>]+class=["'][^"']*main-uploader[^"']*["'][\s\S]{0,1200}?<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i);if(!m)return null;var u=C.abs(m[1],url),name=C.strip(m[2]),ctx=C.context(s,m.index,400,1400),img=C.imgFrom(ctx,u);return{url:u,name:name||'上传者',img:C.image(img,u),type:C.profileType(u)||'channel'};};
  C.modelLinks=function(html,url){var a=C.allAnchors(html,url),out=[],i,n,t;for(i=0;i<a.length;i++){t=C.profileType(a[i].href);if(t!=='pornstar')continue;n=C.clean(a[i].text||a[i].title);if(!n||n.length>80)continue;out.push({name:n,url:a[i].href});}return C.unique(out,function(v){return v.url;}).slice(0,25);};
  C.keywordLinks=function(html,url){var s=C.s(html),out=[],re=/<a\b([^>]*)href=["']([^"']+)["']([^>]*)class=["'][^"']*(?:is-keyword|keyword)[^"']*["']([^>]*)>([\s\S]*?)<\/a>/ig,m;while((m=re.exec(s))){var n=C.strip(m[5]),u=C.abs(m[2],url);if(n&&u)out.push({name:n,url:u});}return C.unique(out,function(v){return v.url;}).slice(0,40);};
  C.detail=function(html,url){var d=C.jsonLd(html),title=C.decode(d.name||C.meta(html,'og:title')||'Video'),desc=C.clean(d.description||C.meta(html,'description')||''),cover=d.thumbnailUrl||C.meta(html,'og:image')||'',date=d.uploadDate||'',duration='',views='',likes='',dislikes='',commentCount='',m;title=C.clean(title.replace(/\s*[-|｜]\s*XVideos.*$/i,''));if(Object.prototype.toString.call(cover)==='[object Array]')cover=cover[0]||'';m=C.s(html).match(/<span[^>]+class=["'][^"']*duration[^"']*["'][^>]*>([^<]+)<\/span>/i);if(m)duration=C.strip(m[1]);m=C.s(html).match(/<span[^>]+class=["'][^"']*icf-eye[^"']*["'][^>]*><\/span>\s*([^<]+)/i);if(m)views=C.strip(m[1]);m=C.s(html).match(/<span[^>]+class=["'][^"']*rating-good-nbr[^"']*["'][^>]*>([^<]+)<\/span>/i);if(m)likes=C.strip(m[1]);m=C.s(html).match(/<span[^>]+class=["'][^"']*rating-bad-nbr[^"']*["'][^>]*>([^<]+)<\/span>/i);if(m)dislikes=C.strip(m[1]);m=C.s(html).match(/<button[^>]+class=["'][^"']*comments[^"']*tab-button[^"']*["'][^>]*>[\s\S]{0,260}?(\d[\d,.]*)/i);if(m)commentCount=C.strip(m[1]);var sources=C.playSources(html,url),author=C.authorFrom(html,url),models=C.modelLinks(html,url),tags=C.keywordLinks(html,url),related=C.parseVideoCards(html,url).filter(function(v){return v.url!==url;}).slice(0,20);return{title:title||'Video',desc:desc,cover:C.abs(cover,url),date:date,duration:duration,views:views,likes:likes,dislikes:dislikes,commentCount:commentCount,sources:sources,author:author,models:models,tags:tags,related:related};};
  C.resolvePlay=function(url){var h=C.fetchText(url,{force:true,ttl:0,auth:C.authEnabled(),timeout:14000}),x=C.detail(h,url),src=x.sources,out=[],i,j,variants,seen={};for(i=0;i<src.length;i++){if(src[i].name.indexOf('HLS')===0){variants=C.expandHls(src[i].url,url);for(j=0;j<variants.length;j++)if(!seen[variants[j].url]){seen[variants[j].url]=1;out.push(variants[j]);}}if(!seen[src[i].url]){seen[src[i].url]=1;out.push(src[i]);}}if(out.length===1)return C.videoUrl(out[0].url,url);if(out.length>1){var urls=[],names=[],headers=[];for(i=0;i<out.length;i++){urls.push(out[i].url);names.push(out[i].name);headers.push({'Referer':url,'User-Agent':'Mozilla/5.0'});}return JSON.stringify({urls:urls,names:names,headers:headers});}return'video://'+url;};

  C.profile=function(url){var h=C.fetchText(url,{ttl:10*60*1000,auth:C.authEnabled()}),name=C.meta(h,'og:title')||'',img=C.meta(h,'og:image')||'',desc=C.meta(h,'og:description')||'',videos=C.parseVideoCards(h,url),m;if(!name){m=C.s(h).match(/<h2[^>]*>[\s\S]{0,120}?<strong[^>]*>([^<]+)<\/strong>/i);if(m)name=C.strip(m[1]);}if(!img){m=C.s(h).match(/class=["'][^"']*profile-pic[^"']*["'][\s\S]{0,500}?<img[^>]+src=["']([^"']+)["']/i);if(m)img=C.abs(m[1],url);}if(!videos.length){var vu=url.replace(/\/+$/,'')+'/videos/best/0',vh=C.fetchText(vu,{ttl:5*60*1000,auth:C.authEnabled()});videos=C.parseVideoCards(vh,vu);}var stats=[];var ids=[['pinfo-profile-hits','浏览'],['pinfo-subscribers','订阅'],['pinfo-videos-views','播放'],['pinfo-signedup','加入'],['pinfo-lastactivity','活跃']];for(var i=0;i<ids.length;i++){m=C.s(h).match(new RegExp('id=["\\\']'+ids[i][0]+'["\\\'][\\s\\S]{0,220}?<span[^>]*>([^<]+)<\\/span>','i'));if(m)stats.push(ids[i][1]+' '+C.strip(m[1]));}return{name:C.clean(name.replace(/\s*[-|｜]\s*XVideos.*$/i,''))||'Creator',img:C.image(img,url),rawImg:img,desc:C.clean(desc),stats:stats,videos:videos};};

  C.detectAccountName=function(html){var s=C.s(html),m=s.match(/href=["']\/profiles\/([^"'\/?#]+)["'][^>]*(?:class=["'][^"']*(?:profile|user|account)[^"']*["'])?/i);return m?decodeURIComponent(m[1]):'';};
  C.syncWebCookie=function(){var cookie='';try{cookie=C.clean(getCookie(C.base()));}catch(e){cookie='';}if(!cookie)return{ok:false,message:'未读取到网页登录 Cookie。请先用 X5 打开官网并完成登录，再回来同步。'};setItem(C.authCookieKey,cookie);setItem(C.authEnabledKey,'1');var h=C.fetchText(C.base()+'/',{force:true,ttl:0,auth:true}),name=C.detectAccountName(h);if(name)setItem(C.accountNameKey,name);return{ok:true,message:name?'已同步账号：'+name:'Cookie 已同步；账号名尚未识别，但账号列表可继续验证。',name:name};};
  C.accountName=function(){return C.clean(getItem(C.accountNameKey,''));};
  C.setAccountName=function(n){n=C.clean(n);if(n)setItem(C.accountNameKey,n);return n;};
  C.logoutLocal=function(){setItem(C.authEnabledKey,'0');setItem(C.authCookieKey,'');return true;};
  C.accountReady=function(){return C.authEnabled()&&!!C.savedCookie();};
  C.accountUrl=function(kind,page){var b=C.base(),n=Math.max(0,(parseInt(page,10)||1)-1);if(kind==='history')return b+'/history/'+n;if(kind==='liked')return b+'/videos-i-like/'+n;if(kind==='watchlater')return b+'/watch-later/'+n;if(kind==='home')return C.queryPage(b+'/',page||1);return'';};
  C.accountVideos=function(kind,page){var u=C.accountUrl(kind,page);if(!u)return{url:'',cards:[],error:'未知账号列表'};var h=C.fetchText(u,{ttl:90*1000,auth:true}),cards=C.parseVideoCards(h,u);return{url:u,cards:cards,error:C.isBad(h)?'账号页返回异常或登录态失效':''};};

  C.readList=function(key){try{var a=JSON.parse(getItem(key,'[]'));return Object.prototype.toString.call(a)==='[object Array]'?a:[];}catch(e){return[];}};
  C.sanitizeItem=function(x){return{url:C.clean(x.url),title:C.clean(x.title).slice(0,180),img:C.clean(x.img).slice(0,900),rawImg:C.clean(x.rawImg).slice(0,900),desc:C.clean(x.desc).slice(0,180),time:new Date().getTime()};};
  C.writeList=function(key,a){a=(a||[]).slice(0,C.maxLocalItems);try{setItem(key,JSON.stringify(a));return true;}catch(e){try{setItem(key,JSON.stringify(a.slice(0,30)));return true;}catch(e2){return false;}}};
  C.addHistory=function(x){x=C.sanitizeItem(x);if(!x.url)return;var a=C.readList(C.historyKey),out=[x],i;for(i=0;i<a.length;i++)if(a[i].url!==x.url)out.push(a[i]);C.writeList(C.historyKey,out);};
  C.isFav=function(url){var a=C.readList(C.favoriteKey),i;for(i=0;i<a.length;i++)if(a[i].url===url)return true;return false;};
  C.toggleFav=function(x){x=C.sanitizeItem(x);var a=C.readList(C.favoriteKey),out=[],found=false,i;for(i=0;i<a.length;i++){if(a[i].url===x.url){found=true;continue;}out.push(a[i]);}if(!found)out.unshift(x);C.writeList(C.favoriteKey,out);return!found;};

  C.parseFavoriteLists=function(html,base){var a=C.allAnchors(html,base||C.base()),out=[],seen={},i,n,ctx,img;for(i=0;i<a.length;i++){if(!/\/favorite\/\d+/i.test(a[i].href)||seen[a[i].href])continue;n=C.clean(a[i].text||a[i].title);ctx=C.context(html,a[i].index,500,1100);img=C.imgFrom(ctx,a[i].href);if(!n||n.length>100)n='收藏夹';seen[a[i].href]=1;out.push({url:a[i].href,title:n,img:C.image(img,a[i].href),desc:'公开收藏夹'});}return out;};
  C.favoriteLists=function(page){var u=C.queryPage(C.base()+'/',page||1),h=C.fetchText(u,{ttl:5*60*1000,auth:C.authEnabled()}),lists=C.parseFavoriteLists(h,u);if(!lists.length&&C.accountReady()){var ah=C.fetchText(C.accountUrl('liked',1),{ttl:3*60*1000,auth:true});lists=C.parseFavoriteLists(ah,C.accountUrl('liked',1));}return{url:u,lists:lists};};
  C.favoriteDetail=function(url,page){var u=url.replace(/\/+$/,'')+'/'+Math.max(0,(parseInt(page,10)||1)-1),h=C.fetchText(u,{ttl:5*60*1000,auth:C.authEnabled()}),cards=C.parseVideoCards(h,u);return{url:u,cards:cards};};

  C.parseComments=function(html,url){var s=C.s(html),out=[],seen={},re=/<(?:div|li)[^>]+class=["'][^"']*comment[^"']*["'][^>]*>/ig,m,idx,ctx,user,text,time,img,pm,tm,dm;while((m=re.exec(s))&&out.length<80){idx=m.index;ctx=C.context(s,idx,100,2200);pm=ctx.match(/<a[^>]+href=["']([^"']*\/profiles\/[^"']+)["'][^>]*>([\s\S]*?)<\/a>/i);user=pm?C.strip(pm[2]):'';if(!user)continue;tm=ctx.match(/<(?:p|div|span)[^>]+class=["'][^"']*(?:comment-text|comment-body|text)[^"']*["'][^>]*>([\s\S]*?)<\/(?:p|div|span)>/i);text=tm?C.strip(tm[1]):'';if(!text||text.length<2||text.length>1200)continue;dm=ctx.match(/<(?:span|small|time)[^>]+class=["'][^"']*(?:date|time|ago)[^"']*["'][^>]*>([^<]+)</i);time=dm?C.strip(dm[1]):'';img=C.imgFrom(ctx,url);var key=user+'|'+text;if(seen[key])continue;seen[key]=1;out.push({user:user,text:text,time:time,img:C.image(img,url),url:pm?C.abs(pm[1],url):''});}return out;};

  return C;
})();
