/* XVideos Remote Runtime 0.1.0-test.1 */
var XVideosRemoteRuntime=(function(){
  var R={version:'0.1.0-test.1',build:10101};
  var A='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/xvideos/assets/';
  function add(d,x){d.push(x);}
  function title(t){try{setPageTitle(t);}catch(e){}}
  function section(d,t,desc){add(d,{title:t,desc:desc||'',col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}});}
  function icon(d,t,desc,ico,url){add(d,{title:t,desc:desc||'',pic_url:A+ico+'.svg',col_type:'icon_small_4',url:url,extra:{lineVisible:false}});}
  function btn(d,t,url,on){add(d,{title:(on?'● ':'')+t,col_type:'flex_button',url:url,extra:{lineVisible:false}});}
  function videoCard(c){return{title:c.title||'Video',desc:c.desc||'',pic_url:c.img||'',url:XVideosCore.page('xvideosDetail',{u:c.url}),col_type:'movie_2',extra:{id:'xv_video_'+XVideosCore.hash(c.url),lineVisible:false}};}
  function renderVideos(d,a,limit){limit=limit||a.length;for(var i=0;i<a.length&&i<limit;i++)add(d,videoCard(a[i]));}
  function renderProfiles(d,a){for(var i=0;i<a.length;i++){var p=a[i];add(d,{title:p.title,desc:p.desc||'',pic_url:p.img||'',url:XVideosCore.page('xvideosProfile',{u:p.url}),col_type:'avatar',extra:{id:'xv_profile_'+XVideosCore.hash(p.url),lineVisible:false}});}}
  function empty(d,t,desc,url){section(d,t,desc);if(url)add(d,{title:'在官网网页打开',desc:url,col_type:'text_1',url:'web://'+url,extra:{lineVisible:false}});}
  function searchInputUrl(){return'input://'+JSON.stringify({value:'',hint:'搜索视频、演员、频道',js:"'hiker://page/xvideosSearch?rule='+encodeURIComponent('"+XVideosCore.ruleTitle()+"')+'&simple=true&q='+encodeURIComponent(input)"});}

  R.home=function(){title('XVideos');var d=[],mode=getMyVar('xv_home_mode',XVideosCore.accountReady()?'home':'best');add(d,{title:'',desc:'',pic_url:A+'banner.svg',col_type:'pic_1_full',url:'hiker://empty',extra:{lineVisible:false}});
    icon(d,'搜索','多条件筛选','search',searchInputUrl());icon(d,'分类','标签 / 主题','categories',XVideosCore.page('xvideosCategories'));icon(d,'演员','Pornstars','creators',XVideosCore.page('xvideosCreators',{kind:'pornstars'}));icon(d,'频道','Channels','channels',XVideosCore.page('xvideosCreators',{kind:'channels'}));
    icon(d,'最佳','热门精选','best',XVideosCore.page('xvideosCatalog',{m:'best',n:'最佳视频'}));icon(d,'最新','最新上传','new',XVideosCore.page('xvideosCatalog',{m:'new',n:'最新视频'}));icon(d,'高分','评分排序','rating',XVideosCore.page('xvideosCatalog',{m:'rated',n:'高分视频'}));icon(d,XVideosCore.accountReady()?'我的':'登录','账号空间','account',XVideosCore.accountReady()?XVideosCore.page('xvideosAccount'):XVideosCore.page('xvideosLogin'));
    icon(d,'喜欢','站内点赞','favorite',XVideosCore.page('xvideosAccountList',{kind:'liked',n:'喜欢的视频'}));icon(d,'稍后看','站内 Watch Later','watchlater',XVideosCore.page('xvideosAccountList',{kind:'watchlater',n:'稍后观看'}));icon(d,'观看历史','站内 History','history',XVideosCore.page('xvideosAccountList',{kind:'history',n:'观看历史'}));icon(d,'本地收藏','本机独立','localfav',XVideosCore.page('xvideosLocalFavorites'));
    section(d,XVideosCore.accountReady()?'你的首页':'精选视频',XVideosCore.accountReady()?'已携带账号 Cookie 请求首页；内容以当前账号实际返回为准':'匿名公开内容');var r=XVideosCore.homeVideos(mode,1);renderVideos(d,r.cards,20);if(!r.cards.length)empty(d,'首页暂未解析到视频','可能是区域访问、验证页或官网 DOM 已变化。',r.url);
    section(d,'更多','用户 / 公开收藏夹 / 本地足迹 / 设置');icon(d,'用户','Profiles','profiles',XVideosCore.page('xvideosCreators',{kind:'profiles'}));icon(d,'收藏夹','公开 Favorite','playlist',XVideosCore.page('xvideosFavorites'));icon(d,'本地足迹','本机详情历史','localhistory',XVideosCore.page('xvideosLocalHistory'));icon(d,'设置','域名 / 缓存 / 更新','settings',XVideosCore.page('xvideosSettings'));setResult(d);};

  R.catalog=function(){var mode=XVideosCore.param('m','best'),name=XVideosCore.param('n','视频'),page=XVideosCore.pageNo();title(name);var d=[],r=XVideosCore.homeVideos(mode,page);if(page===1){btn(d,'最佳',XVideosCore.page('xvideosCatalog',{m:'best',n:'最佳视频'}),mode==='best');btn(d,'最新',XVideosCore.page('xvideosCatalog',{m:'new',n:'最新视频'}),mode==='new');btn(d,'最多观看',XVideosCore.page('xvideosCatalog',{m:'views',n:'最多观看'}),mode==='views');btn(d,'最高评分',XVideosCore.page('xvideosCatalog',{m:'rated',n:'最高评分'}),mode==='rated');}renderVideos(d,r.cards);if(!r.cards.length&&page===1)empty(d,'没有解析到视频','可打开官网确认当前页面结构。',r.url);setResult(d);};

  R.categories=function(){title('分类');var d=[],a=XVideosCore.tagList(false);section(d,'标签分类',a.length?'已从官网标签页恢复 '+a.length+' 个分类':'当前官网标签页未解析成功');for(var i=0;i<a.length;i++)add(d,{title:a[i].name,col_type:'flex_button',url:XVideosCore.page('xvideosCategory',{u:a[i].url,n:a[i].name})});if(!a.length)empty(d,'分类暂不可用','Test1 不会伪造分类；请用官网页辅助确认 DOM。',XVideosCore.base()+'/tags');setResult(d);};
  R.category=function(){var u=XVideosCore.param('u',''),n=XVideosCore.param('n','分类'),page=XVideosCore.pageNo();title(n);var d=[],r=XVideosCore.tagVideos(u,page);if(page===1)add(d,{title:'← 全部分类',col_type:'scroll_button',url:XVideosCore.page('xvideosCategories')});renderVideos(d,r.cards);if(!r.cards.length&&page===1)empty(d,'该分类暂无可识别视频','当前链接没有解析出 frame-block 视频实体。',r.url);setResult(d);};

  R.searchPage=function(){var q=XVideosCore.param('q',''),sort=XVideosCore.param('sort','relevance'),datef=XVideosCore.param('datef','all'),durf=XVideosCore.param('durf','allduration'),quality=XVideosCore.param('quality','all'),page=XVideosCore.pageNo();title(q?'搜索 · '+q:'搜索');var d=[];add(d,{title:'搜索关键词',desc:q||'点击输入',col_type:'input',url:"(function(){var q=String(input||'').trim();return 'hiker://page/xvideosSearch?rule='+encodeURIComponent('"+XVideosCore.ruleTitle()+"')+'&simple=true&q='+encodeURIComponent(q);})()",extra:{defaultValue:q}});if(!q){section(d,'筛选能力','支持相关度、上传时间、评分、时长、观看量、随机；日期、视频时长和画质也可组合过滤。');setResult(d);return;}
    section(d,'排序','');var sorts=[['相关','relevance'],['最新','uploaddate'],['评分','rating'],['时长','length'],['观看量','views'],['随机','random']],i,x;for(i=0;i<sorts.length;i++){x=sorts[i];btn(d,x[0],XVideosCore.page('xvideosSearch',{q:q,sort:x[1],datef:datef,durf:durf,quality:quality}),sort===x[1]);}
    section(d,'日期','');var dates=[['全部','all'],['近3天','today'],['本周','week'],['本月','month'],['近3月','3month'],['近6月','6month']];for(i=0;i<dates.length;i++){x=dates[i];btn(d,x[0],XVideosCore.page('xvideosSearch',{q:q,sort:sort,datef:x[1],durf:durf,quality:quality}),datef===x[1]);}
    section(d,'时长','');var ds=[['全部','allduration'],['1–3分','1-3min'],['3–10分','3-10min'],['10分+','10min_more'],['10–20分','10-20min'],['20分+','20min_more']];for(i=0;i<ds.length;i++){x=ds[i];btn(d,x[0],XVideosCore.page('xvideosSearch',{q:q,sort:sort,datef:datef,durf:x[1],quality:quality}),durf===x[1]);}
    section(d,'画质','');var qs=[['全部','all'],['720P+','hd'],['1080P+','1080P']];for(i=0;i<qs.length;i++){x=qs[i];btn(d,x[0],XVideosCore.page('xvideosSearch',{q:q,sort:sort,datef:datef,durf:durf,quality:x[1]}),quality===x[1]);}
    var r=XVideosCore.searchVideos(q,page,{sort:sort,datef:datef,durf:durf,quality:quality});section(d,'结果',r.cards.length?r.cards.length+' 项':'未识别到结果');renderVideos(d,r.cards);if(!r.cards.length&&page===1)empty(d,'没有匹配结果','可换关键词或打开官网搜索。',r.url);setResult(d);};
  R.search=function(){var q='';try{q=String(MY_KEYWORD||'');}catch(e){q=XVideosCore.param('q','');}var page=XVideosCore.pageNo(),d=[],r=XVideosCore.searchVideos(q,page,{sort:'relevance',datef:'all',durf:'allduration',quality:'all'});renderVideos(d,r.cards);if(!r.cards.length&&page===1)empty(d,'没有匹配结果','本次搜索未返回可识别视频。',r.url);setResult(d);};

  R.detail=function(){var u=XVideosCore.param('u',''),d=[];if(!u){empty(d,'缺少视频地址','请从列表重新进入。');setResult(d);return;}var h=XVideosCore.fetchText(u,{force:true,ttl:0,auth:XVideosCore.authEnabled(),timeout:14000});if(XVideosCore.isBad(h)){title('视频详情');empty(d,'详情加载失败','官网返回验证页、空页面或当前网络异常。',u);setResult(d);return;}var x=XVideosCore.detail(h,u);title(x.title);XVideosCore.addHistory({url:u,title:x.title,img:XVideosCore.image(x.cover,u),rawImg:x.cover,desc:[x.duration,x.views?x.views+' views':''].filter(function(v){return!!v;}).join(' · ')});add(d,{title:x.title,desc:[x.duration,x.views?x.views+' views':'',x.date].filter(function(v){return!!v;}).join(' · '),pic_url:XVideosCore.image(x.cover,u),url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});
    add(d,{title:'▶ 立即播放',desc:x.sources.length?x.sources.length+' 条官网媒体源；HLS 会继续展开清晰度':'未发现直链，将回退网页媒体提取',pic_url:A+'play.svg',col_type:'text_1',url:$(u).lazyRule(function(boot,target){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);XVideosBoot.loadOnly();return XVideosCore.resolvePlay(target);},XVideosCore.bootstrap,u),extra:{id:'xv_play_'+XVideosCore.hash(u),lineVisible:false}});
    var fav=XVideosCore.isFav(u);add(d,{title:fav?'取消本地收藏':'加入本地收藏',desc:'独立于 XVideos 账号，仅保存在本机',pic_url:A+'localfav.svg',col_type:'text_1',url:$(u).lazyRule(function(boot,target,tt,cv,ds){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);XVideosBoot.loadOnly();var on=XVideosCore.toggleFav({url:target,title:tt,rawImg:cv,img:XVideosCore.image(cv,target),desc:ds});refreshPage(false);return'toast://'+(on?'已加入本地收藏':'已取消本地收藏');},XVideosCore.bootstrap,u,x.title,x.cover,[x.duration,x.views].filter(function(v){return!!v;}).join(' · ')),extra:{lineVisible:false}});
    add(d,{title:'评论'+(x.commentCount?' · '+x.commentCount:''),desc:'读取官网评论；若当前 DOM 不暴露正文则保留官网入口',pic_url:A+'comments.svg',col_type:'text_1',url:XVideosCore.page('xvideosComments',{u:u,n:x.title}),extra:{lineVisible:false}});add(d,{title:'官网详情与互动',desc:'点赞、回复、账号写操作继续由官网页面完成',col_type:'text_1',url:'web://'+u,extra:{lineVisible:false}});
    if(x.author){section(d,'上传者','');add(d,{title:x.author.name,desc:x.author.type,pic_url:x.author.img||A+'account.svg',col_type:'avatar',url:XVideosCore.page('xvideosProfile',{u:x.author.url}),extra:{lineVisible:false}});}if(x.models.length){section(d,'出演者','');for(var i=0;i<x.models.length;i++)add(d,{title:x.models[i].name,col_type:'flex_button',url:XVideosCore.page('xvideosProfile',{u:x.models[i].url})});}if(x.desc){section(d,'简介','');add(d,{title:x.desc,col_type:'rich_text',url:'hiker://empty'});}if(x.tags.length){section(d,'标签','');for(var j=0;j<x.tags.length;j++)add(d,{title:x.tags[j].name,col_type:'flex_button',url:XVideosCore.page('xvideosCategory',{u:x.tags[j].url,n:x.tags[j].name})});}if(x.related.length){section(d,'相关推荐','');renderVideos(d,x.related,18);}setResult(d);};

  R.comments=function(){var u=XVideosCore.param('u',''),n=XVideosCore.param('n','视频评论');title('评论');var d=[],h=XVideosCore.fetchText(u,{force:true,ttl:0,auth:XVideosCore.authEnabled()}),a=XVideosCore.parseComments(h,u);section(d,n,a.length?'已解析 '+a.length+' 条评论':'当前 HTML 未恢复到稳定评论实体');for(var i=0;i<a.length;i++){var c=a[i];add(d,{title:c.user+(c.time?' · '+c.time:''),desc:c.text,pic_url:c.img||A+'account.svg',col_type:'avatar',url:c.url?XVideosCore.page('xvideosProfile',{u:c.url}):'hiker://empty',extra:{lineVisible:false}});}if(!a.length){add(d,{title:'Test1 评论说明',desc:'现行公开解析项目确认详情页存在 comment_count，但没有提供稳定评论列表接口；因此本版只解析官网 HTML 中真实 comment DOM，不制造伪评论。后续以实机页面为准继续适配。',col_type:'long_text',url:'hiker://empty'});add(d,{title:'打开官网评论',desc:'使用当前登录态进行查看/回复',col_type:'text_1',url:'web://'+u,extra:{lineVisible:false}});}setResult(d);};

  R.creators=function(){var kind=XVideosCore.param('kind','pornstars'),q=XVideosCore.param('q',''),page=XVideosCore.pageNo();title('创作者');var d=[];btn(d,'演员',XVideosCore.page('xvideosCreators',{kind:'pornstars'}),kind==='pornstars');btn(d,'频道',XVideosCore.page('xvideosCreators',{kind:'channels'}),kind==='channels');btn(d,'用户',XVideosCore.page('xvideosCreators',{kind:'profiles'}),kind==='profiles');add(d,{title:'搜索创作者',desc:q||'输入名字',col_type:'input',url:"(function(){var q=String(input||'').trim();return 'hiker://page/xvideosCreators?rule='+encodeURIComponent('"+XVideosCore.ruleTitle()+"')+'&simple=true&kind='+encodeURIComponent('"+kind+"')+'&q='+encodeURIComponent(q);})()",extra:{defaultValue:q}});var r=XVideosCore.creatorList(kind,page,q);renderProfiles(d,r.profiles);if(!r.profiles.length&&page===1)empty(d,'暂未识别到创作者','可从官网确认该区域结构。',r.url);setResult(d);};
  R.profile=function(){var u=XVideosCore.param('u',''),d=[];if(!u){empty(d,'缺少创作者地址','请重新进入。');setResult(d);return;}var x=XVideosCore.profile(u);title(x.name);add(d,{title:x.name,desc:x.stats.length?x.stats.join(' · '):(x.desc||XVideosCore.profileType(u)),pic_url:x.img||A+'account.svg',col_type:'movie_1_left_pic',url:'web://'+u,extra:{lineVisible:false}});if(x.desc)add(d,{title:x.desc,col_type:'rich_text',url:'hiker://empty'});section(d,'视频',x.videos.length?x.videos.length+' 项':'未解析到视频');renderVideos(d,x.videos);if(!x.videos.length)add(d,{title:'打开官网主页',desc:u,col_type:'text_1',url:'web://'+u,extra:{lineVisible:false}});setResult(d);};

  R.login=function(){title('登录 XVideos');var d=[];section(d,'账号登录','账号会话采用 X5 官方网页 Cookie，同 Pornhub 的账号策略一样：不在规则里保存密码。');add(d,{title:'① 打开 XVideos 官网登录',desc:'在 X5 页面点击 Login 并完成官方登录',pic_url:A+'account.svg',col_type:'text_1',url:'x5://'+XVideosCore.base()+'/',extra:{lineVisible:false}});add(d,{title:'② 同步当前登录 Cookie',desc:'完成登录后返回这里点击',col_type:'text_1',url:$(XVideosCore.base()).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);XVideosBoot.loadOnly();var r=XVideosCore.syncWebCookie();refreshPage(false);return'toast://'+r.message;},XVideosCore.bootstrap),extra:{lineVisible:false}});add(d,{title:'当前状态',desc:XVideosCore.accountReady()?('已同步'+(XVideosCore.accountName()?' · '+XVideosCore.accountName():'')):'未同步',col_type:'text_1',url:XVideosCore.accountReady()?XVideosCore.page('xvideosAccount'):'hiker://empty',extra:{lineVisible:false}});setResult(d);};
  R.account=function(){title('我的 XVideos');var d=[];section(d,XVideosCore.accountReady()?'账号已连接':'未登录',XVideosCore.accountReady()?(XVideosCore.accountName()||'Cookie 会话已保存'):'请先从登录页同步官方 Cookie');if(!XVideosCore.accountReady()){add(d,{title:'去登录',pic_url:A+'account.svg',col_type:'text_1',url:XVideosCore.page('xvideosLogin'),extra:{lineVisible:false}});setResult(d);return;}icon(d,'首页','账号 Cookie 首页','best',XVideosCore.page('xvideosAccountList',{kind:'home',n:'账号首页'}));icon(d,'喜欢','Videos I Like','favorite',XVideosCore.page('xvideosAccountList',{kind:'liked',n:'喜欢的视频'}));icon(d,'稍后看','Watch Later','watchlater',XVideosCore.page('xvideosAccountList',{kind:'watchlater',n:'稍后观看'}));icon(d,'历史','History','history',XVideosCore.page('xvideosAccountList',{kind:'history',n:'观看历史'}));add(d,{title:'重新同步 Cookie',desc:'X5 登录状态变化后使用',col_type:'text_1',url:$(XVideosCore.base()).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);XVideosBoot.loadOnly();var r=XVideosCore.syncWebCookie();refreshPage(false);return'toast://'+r.message;},XVideosCore.bootstrap),extra:{lineVisible:false}});add(d,{title:'清除小程序账号会话',desc:'只清除本小程序保存的 Cookie，不修改官网账号',col_type:'text_1',url:$(XVideosCore.base()).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);XVideosBoot.loadOnly();XVideosCore.logoutLocal();refreshPage(false);return'toast://已清除小程序账号会话';},XVideosCore.bootstrap),extra:{lineVisible:false}});setResult(d);};
  R.accountList=function(){var kind=XVideosCore.param('kind','history'),n=XVideosCore.param('n','账号视频'),page=XVideosCore.pageNo();title(n);var d=[];if(!XVideosCore.accountReady()){empty(d,'需要登录','请先同步 XVideos 官方 Cookie。',XVideosCore.base()+'/');setResult(d);return;}var r=kind==='home'?XVideosCore.homeVideos('home',page):XVideosCore.accountVideos(kind,page);renderVideos(d,r.cards);if(!r.cards.length&&page===1)empty(d,'该账号列表暂未解析到视频',r.error||'账号 Cookie 可能失效，或当前列表 DOM 已变化。',r.url);setResult(d);};

  R.favorites=function(){title('公开收藏夹');var page=XVideosCore.pageNo(),d=[],r=XVideosCore.favoriteLists(page);section(d,'Favorites',r.lists.length?'识别到 '+r.lists.length+' 个公开收藏夹链接':'当前页面未发现公开收藏夹实体');for(var i=0;i<r.lists.length;i++){var x=r.lists[i];add(d,{title:x.title,desc:x.desc,pic_url:x.img||A+'playlist.svg',col_type:'movie_2',url:XVideosCore.page('xvideosFavoriteDetail',{u:x.url,n:x.title}),extra:{lineVisible:false}});}if(!r.lists.length)empty(d,'暂无可识别收藏夹','XVideos 的公开收藏链接通常形如 /favorite/<id>/...；Test1 只展示真实发现的实体。',r.url);setResult(d);};
  R.favoriteDetail=function(){var u=XVideosCore.param('u',''),n=XVideosCore.param('n','收藏夹'),page=XVideosCore.pageNo();title(n);var d=[],r=XVideosCore.favoriteDetail(u,page);renderVideos(d,r.cards);if(!r.cards.length&&page===1)empty(d,'收藏夹未解析到视频','请从官网打开确认当前链接是否仍公开。',r.url);setResult(d);};

  function renderLocal(d,a,none){if(!a.length){section(d,none,'暂无记录');return;}for(var i=0;i<a.length;i++){var x=a[i];add(d,{title:x.title||'Video',desc:x.desc||'',pic_url:x.img||'',col_type:'movie_2',url:XVideosCore.page('xvideosDetail',{u:x.url}),extra:{lineVisible:false}});}}
  R.localFavorites=function(){title('本地收藏');var d=[];renderLocal(d,XVideosCore.readList(XVideosCore.favoriteKey),'暂无本地收藏');setResult(d);};
  R.localHistory=function(){title('本地足迹');var d=[];renderLocal(d,XVideosCore.readList(XVideosCore.historyKey),'暂无浏览足迹');setResult(d);};

  R.settings=function(){title('XVideos 设置');var d=[];section(d,'运行信息',R.version+' · Build '+R.build+' · Test');add(d,{title:'当前站点域名',desc:XVideosCore.base(),col_type:'text_1',url:'input://'+JSON.stringify({value:XVideosCore.base(),hint:'https://www.xvideos.com',js:"var v=String(input||'').trim().replace(/\\/+$/,'');if(!/^https?:\\/\\//i.test(v))return 'toast://请输入完整 http(s) 地址';setItem('"+XVideosCore.baseKey+"',v);refreshPage(false);return 'toast://已保存域名';"}),extra:{lineVisible:false}});add(d,{title:'清理页面缓存',desc:'不清账号 Cookie / 本地收藏 / 本地足迹',col_type:'text_1',url:$(XVideosCore.base()).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);XVideosBoot.loadOnly();XVideosCore.clearCache();return'toast://缓存已清理';},XVideosCore.bootstrap),extra:{lineVisible:false}});add(d,{title:'检查远程更新',desc:'当前 Test 通道',col_type:'text_1',url:$(XVideosCore.base()).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);return XVideosBoot.check();},XVideosCore.bootstrap),extra:{lineVisible:false}});add(d,{title:'安装/切换更新',desc:'由 Remote Manager 预加载并验证 release',col_type:'text_1',url:$(XVideosCore.base()).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);return XVideosBoot.update();},XVideosCore.bootstrap),extra:{lineVisible:false}});add(d,{title:'回退上一版',desc:'仅在存在 previous release 时有效',col_type:'text_1',url:$(XVideosCore.base()).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);return XVideosBoot.rollback();},XVideosCore.bootstrap),extra:{lineVisible:false}});section(d,'Test1 验收重点','首页与搜索视频卡、分类、详情封面与标题、HLS/MP4 播放、X5 登录 Cookie、喜欢/稍后看/历史、演员/频道页、评论页。');setResult(d);};

  R.module=function(){return{home:R.home,catalog:R.catalog,categories:R.categories,category:R.category,searchPage:R.searchPage,search:R.search,detail:R.detail,comments:R.comments,creators:R.creators,profile:R.profile,login:R.login,account:R.account,accountList:R.accountList,favorites:R.favorites,favoriteDetail:R.favoriteDetail,localFavorites:R.localFavorites,localHistory:R.localHistory,settings:R.settings};};
  return R;
})();
