/* Hanime1 Test38 account: authoritative avatar + robust playlist/library raw fallback + complete native account center */
(function(C,P,E,H,L){
var baseProfile=P.profile,PROFILE_KEY='hanime38_profile_cache',PROFILE_TTL=45000;
function clean(v){return C.clean(String(v==null?'':v));}
function nodes(h,s){try{return pdfa(String(h||''),s)||[];}catch(e){return [];}}
function text(n,s){try{return clean(pdfh(n,s)||'');}catch(e){return '';}}
function attr(n,s){try{return String(pdfh(n,s)||'').replace(/&amp;/g,'&').trim();}catch(e){return '';}}
function firstText(n,a){for(var i=0;i<a.length;i++){var v=text(n,a[i]);if(v)return v;}return '';}
function firstAttr(n,a){for(var i=0;i<a.length;i++){var v=attr(n,a[i]);if(v)return v;}return '';}
function any(h,a){var out=[],seen={};for(var s=0;s<a.length;s++){var x=nodes(h,a[s]);for(var i=0;i<x.length;i++){var k=String(x[i]||'');if(!seen[k]){seen[k]=1;out.push(x[i]);}}}return out;}
function xa(h,path){try{if(typeof xpathArray==='function')return xpathArray(String(h||''),path)||[];if(typeof xpa==='function')return xpa(String(h||''),path)||[];}catch(e){}return [];}
function first(a){return a&&a.length?String(a[0]||'').replace(/&amp;/g,'&').trim():'';}
function abs(base,u){u=String(u||'').replace(/&amp;/g,'&').trim();return u?C.abs(base,u):'';}
function vid(u){var m=String(u||'').match(/[?&]v=(\d+)/);return m?m[1]:'';}
function pid(u){var m=String(u||'').match(/[?&]list=([^&"']+)/);if(!m)return '';try{return decodeURIComponent(m[1]);}catch(e){return m[1];}}
function digits(s){var m=String(s||'').match(/\d+/);return m?m[0]:'';}
function decodeHtml(s){return String(s||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
function strip(s){return clean(decodeHtml(String(s||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' '));}
function fetchPath(path){var base=C.resolveHost(false),r=C.get(base+path,{base:base,referer:base+'/',timeout:16000});if(!r||r.challenge||Number(r.statusCode||0)>=400)throw new Error('账号内容加载失败：HTTP '+Number((r&&r.statusCode)||0));return {base:base,html:String(r.body||''),url:base+path};}
function avatarFrom(h,base){var paths=['//*[@id="playlist-avatar"]/@src','//*[@id="user-modal-dp-wrapper"]//img[1]/@src','//*[contains(@class,"profile-avatar-wrapper")]//img[1]/@src','//img[contains(@class,"profile-avatar")][1]/@src'],u='';for(var i=0;i<paths.length;i++){u=abs(base,first(xa(h,paths[i])));if(u)return u;}u=abs(base,firstAttr(h,['#playlist-avatar&&src','img#playlist-avatar&&src','#user-modal-dp-wrapper img&&src','.profile-avatar-wrapper img&&src']));return u;}
function readProfileCache(){try{var raw=getItem(PROFILE_KEY,'');if(!raw)return null;var x=JSON.parse(raw);if(!x||!x.ts||!x.item||Date.now()-Number(x.ts)>PROFILE_TTL){clearItem(PROFILE_KEY);return null;}return x.item;}catch(e){return null;}}
function writeProfileCache(p){try{setItem(PROFILE_KEY,JSON.stringify({ts:Date.now(),item:p}));}catch(e){}}
P.clearProfile38=function(){try{clearItem(PROFILE_KEY);}catch(e){}if(P.clearSessionProfile32)try{P.clearSessionProfile32();}catch(e2){}};
P.profile=function(){var c=readProfileCache();if(c&&c.id)return c;var p=baseProfile();if(!p||!p.id)return p;try{var base=p.base||C.resolveHost(false),r=C.get(base+'/user/'+p.id+'/edit',{base:base,referer:base+'/',timeout:12000}),h=String(r&&r.body||''),av=avatarFrom(h,base);if(!av){var h0=C.get(base+'/',{base:base,referer:base+'/',timeout:12000}),hh=String(h0&&h0.body||'');av=avatarFrom(hh,base);}if(av)p.avatar=av;}catch(e){}writeProfileCache(p);return p;};
function videoCard(n,base){var href=firstAttr(n,['a[href*=watch]&&href','a.video-link&&href','[data-href]&&data-href','a&&href']),id=vid(href);if(!id)return null;var image=firstAttr(n,['img.main-thumb&&src','img&&data-src','img&&src']),title=firstText(n,['.video-title&&Text','.title&&Text','.card-mobile-title&&Text','img.main-thumb&&alt','img&&alt']);return {id:id,title:title||('影片 '+id),img:abs(base,image),artist:firstText(n,['.subtitle a&&Text','.meta-author a&&Text']),duration:firstText(n,['.duration&&Text','.card-mobile-duration&&Text']),views:firstText(n,['.stats-container&&Text','.card-mobile-meta&&Text']),rating:'',upload:firstText(n,['.meta-stats span&&Text','.card-mobile-meta&&Text'])};}
function rawVideoCards(h,base,scope){var src=String(h||''),start=0,end=src.length;if(scope){var p=src.indexOf(scope);if(p>=0){start=p;var e=src.indexOf('playlist-sidebar',p);if(e<0)e=src.indexOf('sidebar-video-count',p);if(e>p)end=e+6000;}}src=src.slice(start,end);var re=/(?:href|data-href)\s*=\s*(["'])([^"']*watch\?[^"']*v=\d+[^"']*)\1/gi,m,out=[],seen={};while((m=re.exec(src))!==null){var href=decodeHtml(m[2]),id=vid(href);if(!id||seen[id])continue;seen[id]=1;var a=Math.max(0,m.index-3500),b=Math.min(src.length,m.index+7000),chunk=src.slice(a,b),title='',img='',artist='',duration='';var tm=chunk.match(/class\s*=\s*(["'])[^"']*(?:video-title|card-mobile-title|\btitle\b)[^"']*\1[^>]*>([\s\S]*?)<\//i);if(tm)title=strip(tm[2]);if(!title){var alt=chunk.match(/<img\b[^>]*\balt\s*=\s*(["'])([^"']+)\1/i);if(alt)title=decodeHtml(alt[2]).trim();}var im=chunk.match(/<img\b[^>]*(?:data-src|src)\s*=\s*(["'])([^"']+)\1/i);if(im)img=abs(base,decodeHtml(im[2]));var am=chunk.match(/class\s*=\s*(["'])[^"']*(?:meta-author|subtitle)[^"']*\1[\s\S]{0,1200}?<a\b[^>]*>([\s\S]*?)<\/a>/i);if(am)artist=strip(am[2]);var dm=chunk.match(/class\s*=\s*(["'])[^"']*duration[^"']*\1[^>]*>([\s\S]*?)<\//i);if(dm)duration=strip(dm[2]);out.push({id:id,title:title||('影片 '+id),img:img,artist:artist,duration:duration,views:'',rating:'',upload:''});if(m.index===re.lastIndex)re.lastIndex++;}return out;}
function libraryVideos(h,base,subscription){var sels=subscription?['.content-padding-new div[class^=video-item-container]','div[class^=video-item-container]']:['div[class^=user-tab-item-wrapper]','.user-tab-item-wrapper'],a=any(h,sels),out=[],seen={};for(var i=0;i<a.length;i++){var x=videoCard(a[i],base);if(x&&x.id&&!seen[x.id]){seen[x.id]=1;out.push(x);}}if(!out.length){var raw=rawVideoCards(h,base,'');for(var j=0;j<raw.length;j++)if(!seen[raw[j].id]){seen[raw[j].id]=1;out.push(raw[j]);}}return out;}
function playlistCards(h,base){var a=any(h,['.user-tab-item-wrapper','.playlist-item-wrapper','.playlist-card','div[class^=user-tab-item-wrapper]']),out=[],seen={};for(var i=0;i<a.length;i++){var href=firstAttr(a[i],['a.video-link&&href','a[href*="playlist?list="]&&href','a[href*=playlist]&&href']),id=pid(href),title=firstText(a[i],['.title&&Text','.playlist-title&&Text','.card-mobile-title&&Text','img&&alt']);if(!id||!title||seen[id])continue;seen[id]=1;out.push({id:id,title:title,count:firstText(a[i],['.stat-item&&Text','.playlist-count&&Text']),img:abs(base,firstAttr(a[i],['img.main-thumb&&src','img&&src']))});}if(!out.length){var src=String(h||''),re=/href\s*=\s*(["'])([^"']*playlist\?[^"']*list=[^"']+)\1/gi,m;while((m=re.exec(src))!==null){var href2=decodeHtml(m[2]),id2=pid(href2);if(!id2||seen[id2])continue;var c=src.slice(Math.max(0,m.index-2500),Math.min(src.length,m.index+5000)),tm=c.match(/class\s*=\s*(["'])[^"']*(?:playlist-title|\btitle\b|card-mobile-title)[^"']*\1[^>]*>([\s\S]*?)<\//i),im=c.match(/<img\b[^>]*(?:data-src|src)\s*=\s*(["'])([^"']+)\1/i),cm=c.match(/class\s*=\s*(["'])[^"']*(?:playlist-count|stat-item)[^"']*\1[^>]*>([\s\S]*?)<\//i),title2=tm?strip(tm[2]):'';if(!title2)continue;seen[id2]=1;out.push({id:id2,title:title2,count:cm?strip(cm[2]):'',img:im?abs(base,decodeHtml(im[2])):''});if(m.index===re.lastIndex)re.lastIndex++;}}return out;}
function pageCount(h){var total=1,a=nodes(h,'ul.pagination li.page-item a.page-link');for(var i=0;i<a.length;i++){var n=parseInt(text(a[i],'Text'),10);if(n>total)total=n;}var mm=String(h||'').match(/[?&]page=(\d+)/g)||[];for(var j=0;j<mm.length;j++){var k=parseInt((mm[j].match(/\d+/)||['0'])[0],10);if(k>total)total=k;}return total;}
P.librarySection30=function(kind){var a=P.sessionProfile32?P.sessionProfile32():C.activeAccount();if(!a||!a.id)throw new Error('请先登录');var id=String(a.id),path=kind==='watchLater'?('/user/'+id+'/saves'):kind==='favorites'?('/user/'+id+'/likes'):kind==='playlists'?('/user/'+id+'/playlists'):kind==='history'?('/user/'+id+'/histories?sort=latest&page=1'):'/subscriptions?page=1',x=fetchPath(path);if(kind==='playlists')return {playlists:playlistCards(x.html,x.base),items:[]};return {playlists:[],items:libraryVideos(x.html,x.base,kind==='subscriptions')};};
P.playlist=function(id,sort){id=String(id||'');var firstPage=fetchPath('/playlist?list='+encodeURIComponent(id)+'&sort='+encodeURIComponent(sort||'latest')+'&page=1'),h=firstPage.html,base=firstPage.base,out=[],seen={},dom=any(h,['.playlist-video-list > div.user-tab-item-wrapper','.playlist-video-list .user-tab-item-wrapper']);for(var i=0;i<dom.length;i++){var v=videoCard(dom[i],base);if(v&&v.id&&!seen[v.id]){seen[v.id]=1;out.push(v);}}var raw=rawVideoCards(h,base,'playlist-video-list');for(var r=0;r<raw.length;r++)if(!seen[raw[r].id]){seen[raw[r].id]=1;out.push(raw[r]);}var pages=Math.min(12,pageCount(h));for(var p=2;p<=pages;p++){try{var xp=fetchPath('/playlist?list='+encodeURIComponent(id)+'&sort='+encodeURIComponent(sort||'latest')+'&page='+p),rr=rawVideoCards(xp.html,base,'playlist-video-list');if(!rr.length){var nd=any(xp.html,['.playlist-video-list > div.user-tab-item-wrapper','.playlist-video-list .user-tab-item-wrapper']);for(var n=0;n<nd.length;n++){var vv=videoCard(nd[n],base);if(vv&&vv.id&&!seen[vv.id]){seen[vv.id]=1;out.push(vv);}}}else for(var q=0;q<rr.length;q++)if(!seen[rr[q].id]){seen[rr[q].id]=1;out.push(rr[q]);}}catch(e){break;}}return {id:id,title:firstText(h,['.playlist-title&&Text'])||strip(first(xa(h,'//*[contains(@class,"playlist-title")][1]//text()')))||'片单',desc:firstText(h,['.playlist-description&&Text']),author:firstText(h,['.playlist-author-info a&&Text']),cover:abs(base,firstAttr(h,['.playlist-main-thumbnail&&src']))||abs(base,first(xa(h,'//*[contains(@class,"playlist-main-thumbnail")][1]/@src'))),count:digits(firstText(h,['#sidebar-video-count&&Text'])||first(xa(h,'//*[@id="sidebar-video-count"][1]//text()'))),views:firstText(h,['.playlist-stats&&Text']),items:out,csrf:firstAttr(h,['meta[name=csrf-token]&&content','input[name=_token]&&value']),base:base};};
function choose(k){return $('#noLoading#').lazyRule(function(v){putMyVar('hanime38_my_section',v);refreshPage(false);return 'hiker://empty';},k);}
function accountTabs(d,cur){var tabs=[['片单','playlists'],['收藏','favorites'],['稍后看','watchLater'],['订阅','subscriptions'],['历史','history']];for(var i=0;i<tabs.length;i++)d.push({title:(cur===tabs[i][1]?'✓ ':'')+tabs[i][0],url:choose(tabs[i][1]),col_type:'text_3',extra:{lineVisible:false}});d.push({title:'账号中心',url:H.route('hanimeAccount',{}),col_type:'text_3',extra:{lineVisible:false}});d.push({col_type:'line_blank'});}
function renderSection(d,cur){var r=P.librarySection30(cur);if(cur==='playlists'){d.push(H.sec('我的片单',r.playlists.length+' 个'));for(var i=0;i<r.playlists.length;i++){var p=r.playlists[i];d.push({title:p.title,desc:p.count||'查看片单',pic_url:p.img||'',url:H.route('hanimePlaylist',{id:p.id}),col_type:'movie_1_left_pic',extra:{lineVisible:false}});}if(!r.playlists.length)d.push(H.sec('暂无片单','官网当前没有返回可解析片单。'));return;}var names={favorites:'收藏',watchLater:'稍后看',subscriptions:'订阅',history:'观看历史'},list=r.items||[];d.push(H.sec(names[cur]||'账号内容',list.length+' 部'));for(var j=0;j<list.length;j++)d.push(L.video(list[j],'library'));if(!list.length)d.push(H.sec('暂无内容','官网当前没有返回可解析影片，或该栏目为空。'));}
E.renderMy=function(d){var p=null;try{p=P.profile();}catch(e){}if(!p||!p.id){d.push(H.sec('我的','登录后查看片单、收藏、稍后看、订阅和历史。'));d.push(H.btn('登录 Hanime1',H.route('hanimeLogin',{}),'text_center_1'));return;}d.push({title:p.name||('用户 '+p.id),desc:[p.email,'ID '+p.id].filter(Boolean).join(' · '),pic_url:p.avatar||'',url:H.route('hanimeAccount',{}),col_type:'avatar',extra:{lineVisible:false}});var cur=getMyVar('hanime38_my_section',getMyVar('hanime30_my_section','playlists'));accountTabs(d,cur);try{renderSection(d,cur);}catch(e){d.push(H.sec('账号内容加载失败',String(e.message||e)));d.push(H.btn('刷新账号资料',$('#noLoading#').lazyRule(function(){try{var p=$.require('hanime').provider();if(p.clearProfile38)p.clearProfile38();refreshPage(false);return 'toast://已刷新账号资料';}catch(e){return 'toast://'+String(e.message||e);}}),'text_center_1'));}};
E.accountPage=function(){try{setPageTitle('账号中心');var d=[],p=P.profile();if(!p||!p.id){d.push(H.sec('未登录','请先完成 Hanime1 登录。'));d.push(H.btn('登录 Hanime1',H.route('hanimeLogin',{}),'text_center_1'));setResult(d);return;}d.push({title:p.name||('用户 '+p.id),desc:[p.email,p.joined,'ID '+p.id].filter(Boolean).join(' · '),pic_url:p.avatar||'',url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false}});var cur=getMyVar('hanime38_my_section','playlists');accountTabs(d,cur);try{renderSection(d,cur);}catch(e){d.push(H.sec('账号内容加载失败',String(e.message||e)));}d.push(H.sec('账号资料'));d.push(H.btn('修改昵称','input://'+JSON.stringify({value:p.name||'',hint:'新昵称',js:"try{var p=$.require('hanime').provider(),x=p.profile();p.updateProfile(input,x.email||'');if(p.clearProfile38)p.clearProfile38();refreshPage(false);return 'toast://资料已更新';}catch(e){return 'toast://'+String(e.message||e);}"}),'text_2'));d.push(H.btn('修改邮箱','input://'+JSON.stringify({value:p.email||'',hint:'新邮箱',js:"try{var p=$.require('hanime').provider(),x=p.profile();p.updateProfile(x.name||'',input);if(p.clearProfile38)p.clearProfile38();refreshPage(false);return 'toast://邮箱已更新';}catch(e){return 'toast://'+String(e.message||e);}"}),'text_2'));d.push(H.btn('修改密码',H.route('hanimePassword',{}),'text_2'));d.push(H.btn('刷新账号资料',$('#noLoading#').lazyRule(function(){try{var p=$.require('hanime').provider();if(p.clearProfile38)p.clearProfile38();refreshPage(false);return 'toast://已刷新';}catch(e){return 'toast://'+String(e.message||e);}}),'text_2'));d.push(H.btn('官网账号页面','x5://'+(p.base||C.resolveHost(false))+'/user/'+p.id+'/edit','text_2'));d.push(H.btn('重新登录',H.route('hanimeLogin',{}),'text_2'));if(typeof P.syncBrowserAccount==='function')d.push(H.btn('同步当前网页登录',$('#noLoading#').lazyRule(function(){try{var p=$.require('hanime').provider(),a=p.syncBrowserAccount();if(p.clearProfile38)p.clearProfile38();refreshPage(false);return 'toast://已同步 '+(a.name||'账号');}catch(e){return 'toast://'+String(e.message||e);}}),'text_center_1'));setResult(d);}catch(x){setResult([{title:'账号中心失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.playlistPage=function(){try{var id=H.pv('id',''),p=P.playlist(id,'latest'),d=[];setPageTitle(p.title);d.push({title:p.title,desc:[p.author,p.count?('共 '+p.count+' 部'):'',p.desc].filter(Boolean).join(' · '),pic_url:p.cover||'',url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});d.push(H.btn('修改名称','input://'+JSON.stringify({value:p.title||'',hint:'片单名称',js:"try{var m=$.require('hanime'),x=m.provider().playlist('"+id+"','latest');m.provider().updatePlaylist('"+id+"',input,x.desc||'',false);refreshPage(false);return 'toast://已修改';}catch(e){return 'toast://'+String(e.message||e);}"}),'text_3'));d.push(H.btn('官网片单','x5://'+(p.base||C.resolveHost(false))+'/playlist?list='+encodeURIComponent(id),'text_3'));d.push(H.btn('删除片单','confirm://确认删除该片单？.js:'+$.toString(function(pid){try{$.require('hanime').provider().updatePlaylist(pid,'','',true);back(true);return 'toast://已删除';}catch(e){return 'toast://'+String(e.message||e);}},id),'text_3'));d.push(H.sec('影片',p.items.length+' 部'+(p.count&&String(p.count)!==String(p.items.length)?(' · 官网标记 '+p.count+' 部'):'')));for(var i=0;i<p.items.length;i++)d.push(L.video(p.items[i],'library'));if(!p.items.length)d.push(H.sec('暂无影片','片单存在，但当前页面仍没有解析到影片；可先点“官网片单”直接查看，下一版再根据实机结果继续收敛。'));setResult(d);}catch(x){setResult([{title:'片单加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);
