/* Pornhub Remote Core 0.1.0-test.1 - clean rewrite */
var PornhubCore=(function(){
  var C={};
  C.version='0.1.0-test.1';
  C.build=10101;
  C.defaultBase='https://www.pornhub.com';
  C.bootstrap='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/pornhub/bootstrap_test_v1_b10101.js?v=10101';
  C.ua='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/139.0 Safari/537.36';
  C.cachePrefix='ph_v1_';
  C.authCookieKey='ph_auth_cookie_v1';
  C.authEnabledKey='ph_auth_enabled_v1';
  C.accountNameKey='ph_account_name_v1';
  C.favoriteKey='ph_local_favorites_v1';
  C.historyKey='ph_local_history_v1';
  C.baseKey='ph_base_v1';
  C.maxLocalItems=80;
  C.brand='#ff9000';

  C.s=function(v){return v===undefined||v===null?'':String(v);};
  C.trim=function(v){return C.s(v).replace(/^\s+|\s+$/g,'');};
  C.clean=function(v){var s=C.s(v);if(s==='null'||s==='undefined')return'';return C.trim(s);};
  C.decode=function(v){return C.s(v).replace(/&amp;/ig,'&').replace(/&#38;/ig,'&').replace(/&quot;/ig,'"').replace(/&#39;|&apos;/ig,"'").replace(/&nbsp;/ig,' ').replace(/&lt;/ig,'<').replace(/&gt;/ig,'>').replace(/&#x27;/ig,"'");};
  C.strip=function(v){return C.trim(C.decode(C.s(v).replace(/<br\s*\/?\s*>/ig,'\n').replace(/<script\b[\s\S]*?<\/script>/ig,' ').replace(/<style\b[\s\S]*?<\/style>/ig,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' '));};
  C.base=function(){var b=C.trim(getItem(C.baseKey,C.defaultBase));if(!/^https?:\/\//i.test(b))b=C.defaultBase;return b.replace(/\/+$/,'');};
  C.origin=function(u){var m=C.s(u).match(/^(https?:\/\/[^\/]+)/i);return m?m[1]:C.base();};
  C.abs=function(u,base){u=C.decode(C.trim(u));base=base||C.base();if(!u)return'';u=u.replace(/\\\//g,'/');if(/^https?:\/\//i.test(u))return u;if(/^\/\//.test(u))return'https:'+u;if(/^data:/i.test(u)||/^javascript:/i.test(u)||u.charAt(0)==='#')return'';var o=C.origin(base);if(u.charAt(0)==='/')return o+u;if(u.charAt(0)==='?')return C.s(base).replace(/[?#].*$/,'')+u;return C.s(base).replace(/[?#].*$/,'').replace(/[^\/]*$/,'')+u;};
  C.q=function(v){return encodeURIComponent(C.s(v));};
  C.hash=function(s){s=C.s(s);var h=0,i;for(i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return Math.abs(h);};
  C.cacheKey=function(s){return C.cachePrefix+C.hash(s);};
  C.ruleTitle=function(){try{return MY_RULE&&MY_RULE.title?MY_RULE.title:'Pornhub';}catch(e){return'Pornhub';}};
  C.param=function(name,def){var u='';try{u=C.s(MY_URL);}catch(e){}var m=u.match(new RegExp('[?&]'+name+'=([^&#]*)'));if(!m)return def===undefined?'':def;try{return decodeURIComponent(m[1]);}catch(e2){return m[1];}};
  C.page=function(path,params){var a=['rule='+encodeURIComponent(C.ruleTitle()),'simple=true'];params=params||{};for(var k in params)if(params.hasOwnProperty(k)&&params[k]!==undefined&&params[k]!==null&&C.s(params[k])!=='')a.push(encodeURIComponent(k)+'='+encodeURIComponent(C.s(params[k])));return'hiker://page/'+path+'?'+a.join('&');};
  C.pageNo=function(){var p=1;try{p=parseInt(MY_PAGE||1,10)||1;}catch(e){p=parseInt(C.param('page','1'),10)||1;}return p;};
  C.queryPage=function(url,page){page=parseInt(page,10)||1;if(page<=1)return url;if(/[?&]page=\d+/i.test(url))return url.replace(/([?&]page=)\d+/i,'$1'+page);return url+(url.indexOf('?')>=0?'&':'?')+'page='+page;};
  C.form=function(o){var a=[];for(var k in o)if(o.hasOwnProperty(k)&&o[k]!==undefined&&o[k]!==null)a.push(encodeURIComponent(k)+'='+encodeURIComponent(C.s(o[k])));return a.join('&');};

  C.authEnabled=function(){return getItem(C.authEnabledKey,'0')==='1';};
  C.savedCookie=function(){return C.authEnabled()?C.clean(getItem(C.authCookieKey,'')):'';};
  C.headers=function(ref,auth,accept){var h={'User-Agent':C.ua,'Referer':ref||C.base()+'/','Accept':accept||'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Accept-Language':'en-US,en;q=0.9'};var cookie=auth?C.savedCookie():'';h.Cookie=cookie||'platform=pc';return h;};
  C.image=function(u,ref){u=C.abs(u,ref||C.base());if(!u)return'';return u+'@headers='+JSON.stringify({'User-Agent':C.ua,'Referer':ref||C.base()+'/'});};
  C.videoUrl=function(u,ref){u=C.clean(u);if(!u)return'';return u+';{Referer@'+(ref||C.base()+'/')+'&&User-Agent@Mozilla/5.0}#isVideo=true#';};
  C.isBad=function(body){var s=C.s(body),l=s.toLowerCase();return s.length<120||l.indexOf('just a moment')>=0||l.indexOf('cf-chl-')>=0||l.indexOf('attention required')>=0||l.indexOf('captcha')>=0&&s.length<5000;};
  C.fetchText=function(url,opt){opt=opt||{};var key=C.cacheKey((opt.auth?'auth:':'anon:')+url),tsKey=key+'_ts',now=new Date().getTime(),ttl=opt.ttl===undefined?5*60*1000:opt.ttl,old=getItem(key,''),ts=parseInt(getItem(tsKey,'0'),10)||0;if(!opt.force&&old&&now-ts<ttl)return old;var body='';try{body=C.s(fetch(url,{timeout:opt.timeout||10000,headers:C.headers(opt.ref||url,!!opt.auth,opt.accept)}));}catch(e){body='';}if(!C.isBad(body)){if(body.length<280000){setItem(key,body);setItem(tsKey,String(now));}return body;}return old||body;};
  C.fetchJson=function(url,opt){var s=C.fetchText(url,opt||{});try{return JSON.parse(s);}catch(e){return null;}};
  C.clearCache=function(){try{deleteCache();}catch(e){} return true;};

  C.meta=function(html,key){var s=C.s(html),k=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),re=new RegExp('<meta[^>]+(?:property|name)=["\\\']'+k+'["\\\'][^>]+content=["\\\']([^"\\\']+)["\\\']','i'),m=s.match(re);if(!m){re=new RegExp('<meta[^>]+content=["\\\']([^"\\\']+)["\\\'][^>]+(?:property|name)=["\\\']'+k+'["\\\']','i');m=s.match(re);}return m?C.decode(m[1]):'';};
  C.attr=function(tag,name){var m=C.s(tag).match(new RegExp('(?:^|\\s)'+name+'\\s*=\\s*["\\\']([^"\\\']*)["\\\']','i'));return m?C.decode(m[1]):'';};
  C.imgFrom=function(raw,base){var m=C.s(raw).match(/<img\b[^>]*(?:data-mediumthumb|data-thumb_url|data-src|data-original|data-lazy-src|src)\s*=\s*["']([^"']+)["'][^>]*>/i);return m?C.abs(m[1],base):'';};
  C.allAnchors=function(html,base){var s=C.s(html),out=[],re=/<a\b([^>]*)href\s*=\s*["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/ig,m;while((m=re.exec(s))){var href=C.abs(m[2],base||C.base()),raw=m[0],text=C.strip(m[4]);if(!href)continue;out.push({href:href,raw:raw,text:text,title:C.attr(m[1]+' '+m[3],'title'),img:C.imgFrom(raw,href),index:m.index});}return out;};
  C.context=function(html,index,before,after){html=C.s(html);return html.substring(Math.max(0,index-(before||500)),Math.min(html.length,index+(after||1000)));};
  C.unique=function(items,key){var out=[],seen={},i,k;for(i=0;i<items.length;i++){k=key?key(items[i]):C.s(items[i]);if(!k||seen[k])continue;seen[k]=1;out.push(items[i]);}return out;};

  C.parseVideoCards=function(html,base){var s=C.s(html),a=C.allAnchors(s,base||C.base()),out=[],seen={},i,it,ctx,title,img,dur,views,u;for(i=0;i<a.length;i++){it=a[i];u=it.href;if(!/\/view_video\.php\?[^#]*viewkey=/i.test(u)||seen[u])continue;ctx=C.context(s,it.index,700,1500);title=C.clean(it.title||it.text);if(!title){var tm=ctx.match(/(?:title|alt)\s*=\s*["']([^"']{2,220})["']/i);if(tm)title=C.clean(C.decode(tm[1]));}img=it.img||C.imgFrom(ctx,u);if(!img){var im=ctx.match(/(?:data-mediumthumb|data-src|src)=["']([^"']+)["']/i);if(im)img=C.abs(im[1],u);}dur='';var dm=ctx.match(/<var[^>]+class=["'][^"']*duration[^"']*["'][^>]*>([^<]+)<\/var>/i)||ctx.match(/\b(\d{1,2}:\d{2}(?::\d{2})?)\b/);if(dm)dur=C.strip(dm[1]||dm[0]);views='';var vm=ctx.match(/class=["'][^"']*views[^"']*["'][\s\S]{0,180}?<var[^>]*>([^<]+)<\/var>/i);if(vm)views=C.strip(vm[1]);if(!title)title='Video';seen[u]=1;out.push({url:u,title:title,img:C.image(img,u),rawImg:img,duration:dur,views:views,desc:[dur,views?views+' views':''].filter(function(x){return!!x;}).join(' · ')});}return out;};
  C.parseShortCards=function(html,base){var s=C.s(html),a=C.allAnchors(s,base||C.base()),out=[],seen={},i,it,ctx,title,img;for(i=0;i<a.length;i++){it=a[i];if(!/\/short\//i.test(it.href)||seen[it.href])continue;ctx=C.context(s,it.index,500,1000);title=C.clean(it.title||it.text)||'Short';img=it.img||C.imgFrom(ctx,it.href);seen[it.href]=1;out.push({url:it.href,title:title,img:C.image(img,it.href),rawImg:img,desc:'Short'});}return out;};
  C.parseGifCards=function(html,base){var s=C.s(html),a=C.allAnchors(s,base||C.base()),out=[],seen={},i,it,ctx,title,img;for(i=0;i<a.length;i++){it=a[i];if(!/\/gif\/\d+/i.test(it.href)||seen[it.href])continue;ctx=C.context(s,it.index,500,1100);title=C.clean(it.title||it.text)||'GIF';img=it.img||C.imgFrom(ctx,it.href);seen[it.href]=1;out.push({url:it.href,title:title,img:C.image(img,it.href),rawImg:img,desc:'GIF'});}return out;};
  C.profileType=function(u){if(/\/pornstar\//i.test(u))return'pornstar';if(/\/model\//i.test(u))return'model';if(/\/channels\//i.test(u))return'channel';if(/\/users\//i.test(u))return'user';return'';};
  C.parseProfiles=function(html,base,onlyType){var s=C.s(html),a=C.allAnchors(s,base||C.base()),out=[],seen={},i,it,typ,ctx,name,img,desc;for(i=0;i<a.length;i++){it=a[i];typ=C.profileType(it.href);if(!typ||(onlyType&&typ!==onlyType)||seen[it.href])continue;ctx=C.context(s,it.index,600,1200);name=C.clean(it.title||it.text);if(!name||name.length>80){var nm=ctx.match(/(?:title|alt)\s*=\s*["']([^"']{2,100})["']/i);name=nm?C.clean(nm[1]):'';}img=it.img||C.imgFrom(ctx,it.href);if(!name||!img)continue;desc=typ;var sm=ctx.match(/([\d,.]+\s*(?:subscribers?|videos?|views?))/i);if(sm)desc+=' · '+C.strip(sm[1]);seen[it.href]=1;out.push({url:it.href,title:name,img:C.image(img,it.href),rawImg:img,type:typ,desc:desc});}return out;};
  C.parseGenericLinks=function(html,reFilter){var a=C.allAnchors(html,C.base()),out=[],seen={},i,n;for(i=0;i<a.length;i++){if(!reFilter.test(a[i].href))continue;n=C.clean(a[i].text||a[i].title);if(!n||n.length>60||seen[a[i].href])continue;seen[a[i].href]=1;out.push({name:n,url:a[i].href});}return out;};

  C.categories=function(force){var b=C.base(),j=C.fetchJson(b+'/webmasters/categories',{force:!!force,ttl:12*60*60*1000,accept:'application/json'}),out=[],i,x;if(j&&Object.prototype.toString.call(j.categories)==='[object Array]'){for(i=0;i<j.categories.length;i++){x=j.categories[i]||{};if(x.id!==undefined&&x.category)out.push({id:C.s(x.id),name:C.clean(x.category),url:b+'/video?c='+C.q(x.id)});}}if(out.length)return C.unique(out,function(v){return v.id||v.name;});var h=C.fetchText(b+'/categories',{force:!!force,ttl:60*60*1000}),a=C.allAnchors(h,b);for(i=0;i<a.length;i++){var m=a[i].href.match(/[?&]c=(\d+)/);var n=C.clean(a[i].text||a[i].title);if(m&&n&&n.length<80)out.push({id:m[1],name:n,url:a[i].href});else if(/\/categories\//i.test(a[i].href)&&n&&n.length<80)out.push({id:a[i].href,name:n,url:a[i].href});}return C.unique(out,function(v){return v.id+'|'+v.name;});};

  C.searchUrl=function(q,page,opt){opt=opt||{};var u=C.base()+'/video/search?search='+C.q(q);if(opt.o)u+='&o='+C.q(opt.o);if(opt.p)u+='&p='+C.q(opt.p);if(opt.min)u+='&duration_min='+C.q(opt.min);if(opt.max)u+='&duration_max='+C.q(opt.max);return C.queryPage(u,page);};
  C.searchVideos=function(q,page,opt){var u=C.searchUrl(q,page,opt),h=C.fetchText(u,{ttl:2*60*1000}),cards=C.parseVideoCards(h,u);if(cards.length)return{url:u,cards:cards,route:'html'};var api=C.base()+'/webmasters/search?search='+C.q(q)+'&thumbsize=medium&page='+(page||1);if(opt&&opt.o){var map={mr:'newest',mv:'mostviewed',tr:'rating'};if(map[opt.o])api+='&ordering='+map[opt.o];}var j=C.fetchJson(api,{ttl:2*60*1000,accept:'application/json'}),out=[],i,v;if(j&&Object.prototype.toString.call(j.videos)==='[object Array]'){for(i=0;i<j.videos.length;i++){v=j.videos[i]||{};out.push({url:C.clean(v.url),title:C.clean(v.title)||'Video',rawImg:C.clean(v.default_thumb||v.thumb),img:C.image(v.default_thumb||v.thumb,v.url||C.base()),duration:C.clean(v.duration),views:C.clean(v.views),desc:[C.clean(v.duration),C.clean(v.views)?C.clean(v.views)+' views':''].filter(function(z){return!!z;}).join(' · ')});}}return{url:u,cards:out,route:out.length?'webmasters':'empty'};};

  C.jsonBlock=function(s,start){s=C.s(s);var i=start;if(i<0)return'';while(i<s.length&&s.charAt(i)!=='[')i++;if(i>=s.length)return'';var depth=0,quote='',esc=false,j,ch;for(j=i;j<s.length;j++){ch=s.charAt(j);if(quote){if(esc)esc=false;else if(ch==='\\')esc=true;else if(ch===quote)quote='';continue;}if(ch==='"'||ch==="'"){quote=ch;continue;}if(ch==='[')depth++;else if(ch===']'){depth--;if(depth===0)return s.substring(i,j+1);}}return'';};
  C.mediaDefinitions=function(html){var s=C.s(html),keys=['"mediaDefinitions"','mediaDefinitions'],i,k,p,raw,j;for(i=0;i<keys.length;i++){k=keys[i];p=s.indexOf(k);if(p<0)continue;raw=C.jsonBlock(s,p+k.length);if(!raw)continue;try{j=JSON.parse(raw);if(Object.prototype.toString.call(j)==='[object Array]')return j;}catch(e){}}return[];};
  C.playSources=function(html){var defs=C.mediaDefinitions(html),out=[],seen={},i,x,u,q,f;for(i=0;i<defs.length;i++){x=defs[i]||{};u=C.clean(x.videoUrl||x.video_url||x.url);f=C.clean(x.format).toLowerCase();q=C.clean(x.quality||x.height);if(!u||seen[u])continue;if(f&&f!=='hls'&&u.indexOf('.m3u8')<0)continue;seen[u]=1;out.push({url:u,name:q?(q+'P'):'HLS',quality:parseInt(q,10)||0});}out.sort(function(a,b){return(b.quality||0)-(a.quality||0);});return out;};
  C.authorFrom=function(html){var a=C.allAnchors(html,C.base()),i,t;for(i=0;i<a.length;i++){t=C.profileType(a[i].href);if(t){var n=C.clean(a[i].text||a[i].title);if(n&&n.length<100)return{url:a[i].href,name:n,type:t,img:C.image(a[i].img,a[i].href)};}}return null;};
  C.detail=function(html,url){var title=C.meta(html,'og:title')||C.meta(html,'twitter:title')||'',cover=C.meta(html,'og:image')||C.meta(html,'twitter:image')||'',desc=C.meta(html,'og:description')||C.meta(html,'description')||'',duration='',views='',date='',sources=C.playSources(html),tags=[],cats=[],related=C.parseVideoCards(html,url),a=C.authorFrom(html),m;title=C.clean(title.replace(/\s*[-|｜]\s*Pornhub.*$/i,''));m=C.s(html).match(/(?:video_duration|duration)["']?\s*[:=]\s*["']?(\d{2,5})/i);if(m){var sec=parseInt(m[1],10)||0,d=Math.floor(sec/60),r=sec%60;duration=d+':'+(r<10?'0':'')+r;}if(!duration){m=C.s(html).match(/class=["'][^"']*duration[^"']*["'][^>]*>([^<]+)</i);if(m)duration=C.strip(m[1]);}m=C.s(html).match(/class=["'][^"']*views[^"']*["'][\s\S]{0,160}?([\d,.]+)\s*(?:views)?/i);if(m)views=C.clean(m[1]);m=C.s(html).match(/(?:publish|upload|added)[^<]{0,60}<[^>]*>([^<]{2,50})</i);if(m)date=C.strip(m[1]);var links=C.allAnchors(html,url),i,n;for(i=0;i<links.length;i++){n=C.clean(links[i].text||links[i].title);if(!n||n.length>50)continue;if(/\/categories\//i.test(links[i].href)||/[?&]c=\d+/i.test(links[i].href))cats.push({name:n,url:links[i].href});else if(/\/tags\//i.test(links[i].href)||/[?&](?:tag|search)=/i.test(links[i].href)&&n.length<30)tags.push({name:n,url:links[i].href});}cats=C.unique(cats,function(v){return v.url;}).slice(0,20);tags=C.unique(tags,function(v){return v.url;}).slice(0,30);related=related.filter(function(v){return v.url!==url;}).slice(0,20);return{title:title||'Video',cover:cover,desc:C.clean(desc),duration:duration,views:views,date:date,sources:sources,categories:cats,tags:tags,author:a,related:related};};
  C.resolvePlay=function(url){var h=C.fetchText(url,{force:true,ttl:0,timeout:12000}),x=C.detail(h,url),s=x.sources;if(s.length===1)return C.videoUrl(s[0].url,url);if(s.length>1){var urls=[],names=[],headers=[],i;for(i=0;i<s.length;i++){urls.push(s[i].url);names.push(s[i].name);headers.push({'Referer':url,'User-Agent':'Mozilla/5.0'});}return JSON.stringify({urls:urls,names:names,headers:headers});}return'video://'+url;};

  C.profile=function(url){var h=C.fetchText(url,{ttl:10*60*1000,auth:C.authEnabled()}),name=C.meta(h,'og:title')||'',img=C.meta(h,'og:image')||'',desc=C.meta(h,'og:description')||'',videos=C.parseVideoCards(h,url);name=C.clean(name.replace(/\s*[-|｜]\s*Pornhub.*$/i,''));if(!videos.length){var vu=url.replace(/\/+$/,'')+'/videos';var vh=C.fetchText(vu,{ttl:5*60*1000,auth:C.authEnabled()});videos=C.parseVideoCards(vh,vu);}return{name:name||'Creator',img:C.image(img,url),rawImg:img,desc:C.clean(desc),videos:videos};};

  C.detectAccountName=function(html){var s=C.s(html),m=s.match(/href=["']\/users\/([^"'\/?#]+)["'][^>]*class=["'][^"']*(?:username|user)/i)||s.match(/class=["'][^"']*(?:username|profileUserName)[^"']*["'][\s\S]{0,250}?href=["']\/users\/([^"'\/?#]+)/i)||s.match(/href=["']\/users\/([^"'\/?#]+)["']/i);return m?decodeURIComponent(m[1]):'';};
  C.syncWebCookie=function(){var cookie='';try{cookie=C.clean(getCookie(C.base()));}catch(e){cookie='';}if(!cookie)return{ok:false,message:'未读取到网页登录 Cookie，请先在上方网页完成登录。'};setItem(C.authCookieKey,cookie);setItem(C.authEnabledKey,'1');var h=C.fetchText(C.base()+'/',{force:true,ttl:0,auth:true}),name=C.detectAccountName(h);if(name)setItem(C.accountNameKey,name);return{ok:true,message:name?'已同步账号：'+name:'Cookie 已同步；若账号名未识别，可手动填写。',name:name};};
  C.accountName=function(){return C.clean(getItem(C.accountNameKey,''));};
  C.setAccountName=function(n){n=C.clean(n);if(n)setItem(C.accountNameKey,n);return n;};
  C.logoutLocal=function(){setItem(C.authEnabledKey,'0');setItem(C.authCookieKey,'');return true;};
  C.accountReady=function(){return C.authEnabled()&&!!C.savedCookie();};
  C.accountUrl=function(kind,page){var name=C.accountName(),b=C.base(),u='';if(kind==='recommended')u=b+'/recommended';else if(kind==='feed')u=b+'/feeds?section=videos';else if(kind==='subscriptions')u=name?b+'/users/'+C.q(name)+'/subscriptions':'';else if(kind==='history')u=name?b+'/users/'+C.q(name)+'/videos/recent':'';else if(kind==='favorites')u=name?b+'/users/'+C.q(name)+'/videos/favorites':'';return u?C.queryPage(u,page||1):'';};
  C.accountVideos=function(kind,page){var u=C.accountUrl(kind,page);if(!u)return{url:'',cards:[],error:'账号用户名缺失'};var h=C.fetchText(u,{ttl:90*1000,auth:true}),cards=C.parseVideoCards(h,u);return{url:u,cards:cards,error:C.isBad(h)?'账号页返回异常或登录态失效':''};};
  C.subscriptions=function(page){var u=C.accountUrl('subscriptions',page);if(!u)return{url:'',profiles:[],error:'账号用户名缺失'};var h=C.fetchText(u,{ttl:3*60*1000,auth:true});return{url:u,profiles:C.parseProfiles(h,u),error:C.isBad(h)?'订阅页返回异常或登录态失效':''};};

  C.readList=function(key){try{var a=JSON.parse(getItem(key,'[]'));return Object.prototype.toString.call(a)==='[object Array]'?a:[];}catch(e){return[];}};
  C.sanitizeItem=function(x){return{url:C.clean(x.url),title:C.clean(x.title).slice(0,180),img:C.clean(x.img).slice(0,900),rawImg:C.clean(x.rawImg).slice(0,900),desc:C.clean(x.desc).slice(0,180),time:new Date().getTime()};};
  C.writeList=function(key,a){a=(a||[]).slice(0,C.maxLocalItems);try{setItem(key,JSON.stringify(a));return true;}catch(e){try{setItem(key,JSON.stringify(a.slice(0,30)));return true;}catch(e2){return false;}}};
  C.addHistory=function(x){x=C.sanitizeItem(x);if(!x.url)return;var a=C.readList(C.historyKey),out=[x],i;for(i=0;i<a.length;i++)if(a[i].url!==x.url)out.push(a[i]);C.writeList(C.historyKey,out);};
  C.isFav=function(url){var a=C.readList(C.favoriteKey),i;for(i=0;i<a.length;i++)if(a[i].url===url)return true;return false;};
  C.toggleFav=function(x){x=C.sanitizeItem(x);var a=C.readList(C.favoriteKey),out=[],found=false,i;for(i=0;i<a.length;i++){if(a[i].url===x.url){found=true;continue;}out.push(a[i]);}if(!found)out.unshift(x);C.writeList(C.favoriteKey,out);return!found;};

  C.creatorUrl=function(kind,page,q){var b=C.base(),u='';if(q){if(kind==='users')u=b+'/user/search?username='+C.q(q);else u=b+'/pornstars/search?search='+C.q(q);}else if(kind==='pornstars')u=b+'/pornstars';else if(kind==='channels')u=b+'/channels';else if(kind==='models')u=b+'/model';else u=b+'/pornstars';return C.queryPage(u,page||1);};
  C.creatorList=function(kind,page,q){var u=C.creatorUrl(kind,page,q),h=C.fetchText(u,{ttl:5*60*1000,auth:C.authEnabled()}),typ=kind==='pornstars'?'pornstar':kind==='channels'?'channel':kind==='models'?'model':'user',profiles=C.parseProfiles(h,u,q&&kind==='users'?'user':(!q?typ:''));return{url:u,profiles:profiles,html:h};};
  C.gifList=function(page,q){var u=q?C.base()+'/gifs/search?search='+C.q(q):C.base()+'/gifs';u=C.queryPage(u,page||1);var h=C.fetchText(u,{ttl:5*60*1000}),cards=C.parseGifCards(h,u);return{url:u,cards:cards};};
  C.shortList=function(page){var u=C.queryPage(C.base()+'/shorties',page||1),h=C.fetchText(u,{ttl:4*60*1000}),cards=C.parseShortCards(h,u);return{url:u,cards:cards};};
  C.playlistList=function(page){var u=C.queryPage(C.base()+'/playlists',page||1),h=C.fetchText(u,{ttl:5*60*1000}),links=C.parseGenericLinks(h,/\/playlist\//i);return{url:u,links:links};};

  return C;
})();
