/* Pornhub Remote Runtime 0.1.0-test.1 */
var PornhubRemoteRuntime=(function(){
  var R={version:'0.1.0-test.1',build:10101};
  var A='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/pornhub/assets/';
  function add(d,x){d.push(x);}
  function title(t){try{setPageTitle(t);}catch(e){}}
  function section(d,t,desc){add(d,{title:t,desc:desc||'',col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}});}
  function icon(d,t,desc,ico,url){add(d,{title:t,desc:desc||'',pic_url:A+ico+'.svg',col_type:'icon_4',url:url,extra:{lineVisible:false}});}
  function videoCard(c){return{title:c.title||'Video',desc:c.desc||'',pic_url:c.img||'',url:PornhubCore.page('pornhubDetail',{u:c.url}),col_type:'movie_2',extra:{id:'ph_video_'+PornhubCore.hash(c.url),lineVisible:false}};}
  function renderVideos(d,a,limit){limit=limit||a.length;for(var i=0;i<a.length&&i<limit;i++)add(d,videoCard(a[i]));}
  function renderProfiles(d,a){for(var i=0;i<a.length;i++){var p=a[i];add(d,{title:p.title,desc:p.desc||p.type||'',pic_url:p.img||'',url:PornhubCore.page('pornhubProfile',{u:p.url}),col_type:'avatar',extra:{id:'ph_profile_'+PornhubCore.hash(p.url),lineVisible:false}});}}
  function empty(d,t,desc,url){section(d,t,desc);if(url)add(d,{title:'在原站网页打开',desc:url,col_type:'text_1',url:'web://'+url,extra:{lineVisible:false}});}
  function searchInputUrl(){return'input://'+JSON.stringify({value:'',hint:'搜索视频、演员、频道',js:"'hiker://page/pornhubSearch?rule='+encodeURIComponent('"+PornhubCore.ruleTitle()+"')+'&simple=true&q='+encodeURIComponent(input)"});}

  R.home=function(){title('Pornhub');var d=[],b=PornhubCore.base();add(d,{title:'',desc:'',pic_url:A+'banner.svg',col_type:'pic_1_full',url:'hiker://empty',extra:{lineVisible:false}});
    icon(d,'搜索','视频 / 创作者','search',searchInputUrl());
    icon(d,'分类','同步站点分类','categories',PornhubCore.page('pornhubCategories'));
    icon(d,'创作者','Pornstars / Channels','creators',PornhubCore.page('pornhubCreators'));
    icon(d,PornhubCore.accountReady()?'我的账号':'登录','推荐 / 历史 / 订阅','account',PornhubCore.accountReady()?PornhubCore.page('pornhubAccount'):PornhubCore.page('pornhubLogin'));
    add(d,{title:'推荐',col_type:'scroll_button',url:PornhubCore.page('pornhubCatalog',{m:'home',n:'推荐'})});
    add(d,{title:'最新',col_type:'scroll_button',url:PornhubCore.page('pornhubCatalog',{m:'recent',n:'最新'})});
    add(d,{title:'最多观看',col_type:'scroll_button',url:PornhubCore.page('pornhubCatalog',{m:'viewed',n:'最多观看'})});
    add(d,{title:'最高评分',col_type:'scroll_button',url:PornhubCore.page('pornhubCatalog',{m:'rated',n:'最高评分'})});
    var h=PornhubCore.fetchText(b+'/video',{ttl:3*60*1000}),cards=PornhubCore.parseVideoCards(h,b+'/video');section(d,'首页视频',cards.length?'匿名公开内容 · '+cards.length+' 项':'当前网络未解析到公开列表');renderVideos(d,cards,18);
    if(!cards.length)add(d,{title:'打开原站首页',desc:b,col_type:'text_1',url:'web://'+b+'/',extra:{lineVisible:false}});
    section(d,'更多内容','GIF / Shorts / Playlists 与本地数据');
    icon(d,'GIF','站点 GIF 区','gifs',PornhubCore.page('pornhubGifs'));
    icon(d,'Shorts','短视频入口','shorts',PornhubCore.page('pornhubShorts'));
    icon(d,'本地收藏','本机独立收藏','favorite',PornhubCore.page('pornhubLocalFavorites'));
    icon(d,'浏览历史','本机详情历史','history',PornhubCore.page('pornhubLocalHistory'));
    add(d,{title:'播放列表',desc:'站点公开 Playlists',col_type:'text_1',url:PornhubCore.page('pornhubPlaylists'),extra:{lineVisible:false}});
    add(d,{title:'设置与诊断',desc:R.version+' · Build '+R.build,col_type:'text_1',url:PornhubCore.page('pornhubSettings'),extra:{lineVisible:false}});setResult(d);
  };

  R.catalog=function(){var mode=PornhubCore.param('m','home'),name=PornhubCore.param('n','视频'),page=PornhubCore.pageNo(),b=PornhubCore.base(),u=b+'/video';if(mode==='recent')u+='?o=mr';else if(mode==='viewed')u+='?o=mv';else if(mode==='rated')u+='?o=tr';u=PornhubCore.queryPage(u,page);title(name);var d=[],h=PornhubCore.fetchText(u,{ttl:3*60*1000}),cards=PornhubCore.parseVideoCards(h,u);if(page===1){add(d,{title:'推荐',col_type:'scroll_button',url:PornhubCore.page('pornhubCatalog',{m:'home',n:'推荐'})});add(d,{title:'最新',col_type:'scroll_button',url:PornhubCore.page('pornhubCatalog',{m:'recent',n:'最新'})});add(d,{title:'最多观看',col_type:'scroll_button',url:PornhubCore.page('pornhubCatalog',{m:'viewed',n:'最多观看'})});add(d,{title:'最高评分',col_type:'scroll_button',url:PornhubCore.page('pornhubCatalog',{m:'rated',n:'最高评分'})});}renderVideos(d,cards);if(!cards.length&&page===1)empty(d,'没有解析到视频','可能是区域访问、验证页或站点 DOM 变化。',u);setResult(d);};

  R.categories=function(){title('分类');var d=[],a=PornhubCore.categories(false);section(d,'全部分类',a.length?'已同步 '+a.length+' 个站点分类':'结构化分类接口与网页分类均未解析成功');for(var i=0;i<a.length;i++)add(d,{title:a[i].name,col_type:'flex_button',url:PornhubCore.page('pornhubCategory',{u:a[i].url,n:a[i].name})});if(!a.length)empty(d,'分类暂不可用','可以打开原站分类页确认当前网络状态。',PornhubCore.base()+'/categories');setResult(d);};
  R.category=function(){var u=PornhubCore.param('u',PornhubCore.base()+'/video'),n=PornhubCore.param('n','分类'),page=PornhubCore.pageNo();u=PornhubCore.queryPage(u,page);title(n);var d=[],h=PornhubCore.fetchText(u,{ttl:4*60*1000}),cards=PornhubCore.parseVideoCards(h,u);if(page===1)add(d,{title:'全部分类',col_type:'scroll_button',url:PornhubCore.page('pornhubCategories')});renderVideos(d,cards);if(!cards.length&&page===1)empty(d,'该分类暂无结果','当前页面未识别到视频卡片。',u);setResult(d);};

  R.searchPage=function(){var q=PornhubCore.param('q',''),o=PornhubCore.param('o',''),p=PornhubCore.param('p',''),min=PornhubCore.param('min',''),max=PornhubCore.param('max',''),page=PornhubCore.pageNo();title(q?'搜索 · '+q:'搜索');var d=[];add(d,{title:'搜索关键词',desc:q||'点击输入',col_type:'input',url:"(function(){var q=String(input||'').trim();return 'hiker://page/pornhubSearch?rule='+encodeURIComponent('"+PornhubCore.ruleTitle()+"')+'&simple=true&q='+encodeURIComponent(q);})()",extra:{defaultValue:q,onChange:"putMyVar('ph_search_input',String(input||''))"}});if(!q){section(d,'开始搜索','输入关键词后可继续按排序、制作类型和时长过滤。');setResult(d);return;}
    section(d,'排序','');var sorts=[['相关',''],['最新','mr'],['最多观看','mv'],['最高评分','tr']],i,x;for(i=0;i<sorts.length;i++){x=sorts[i];add(d,{title:(o===x[1]?'● ':'')+x[0],col_type:'scroll_button',url:PornhubCore.page('pornhubSearch',{q:q,o:x[1],p:p,min:min,max:max})});}
    section(d,'制作类型','');var prods=[['全部',''],['专业','professional'],['自制','homemade']];for(i=0;i<prods.length;i++){x=prods[i];add(d,{title:(p===x[1]?'● ':'')+x[0],col_type:'scroll_button',url:PornhubCore.page('pornhubSearch',{q:q,o:o,p:x[1],min:min,max:max})});}
    section(d,'时长','');var ds=[['全部','',''],['<10分钟','','10'],['10–20','10','20'],['20–30','20','30'],['30+','30','']];for(i=0;i<ds.length;i++){x=ds[i];add(d,{title:(min===x[1]&&max===x[2]?'● ':'')+x[0],col_type:'scroll_button',url:PornhubCore.page('pornhubSearch',{q:q,o:o,p:p,min:x[1],max:x[2]})});}
    var r=PornhubCore.searchVideos(q,page,{o:o,p:p,min:min,max:max});section(d,'搜索结果',r.cards.length?r.cards.length+' 项 · '+r.route:'未识别到结果');renderVideos(d,r.cards);if(!r.cards.length&&page===1)empty(d,'没有匹配结果','可换关键词或打开原站搜索。',r.url);setResult(d);};
  R.search=function(){var q='';try{q=String(MY_KEYWORD||'');}catch(e){q=PornhubCore.param('q','');}var page=PornhubCore.pageNo(),d=[],r=PornhubCore.searchVideos(q,page,{});renderVideos(d,r.cards);if(!r.cards.length&&page===1)empty(d,'没有匹配结果','本次搜索未返回可识别视频。',r.url);setResult(d);};

  R.detail=function(){var u=PornhubCore.param('u',''),d=[];if(!u){empty(d,'缺少视频地址','请从列表重新进入。');setResult(d);return;}var h=PornhubCore.fetchText(u,{force:true,ttl:0,auth:PornhubCore.authEnabled(),timeout:12000});if(PornhubCore.isBad(h)){title('视频详情');empty(d,'详情加载失败','原站返回验证页、空页面或网络异常。',u);setResult(d);return;}var x=PornhubCore.detail(h,u);title(x.title);PornhubCore.addHistory({url:u,title:x.title,img:PornhubCore.image(x.cover,u),rawImg:x.cover,desc:[x.duration,x.views?x.views+' views':''].filter(function(v){return!!v;}).join(' · ')});add(d,{title:x.title,desc:[x.duration,x.views?x.views+' views':'',x.date].filter(function(v){return!!v;}).join(' · '),pic_url:PornhubCore.image(x.cover,u),url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});
    add(d,{title:'▶ 立即播放',desc:x.sources.length?(x.sources.length+' 个可用 HLS 画质'):'未发现直链，点击后使用网页媒体提取',col_type:'text_1',url:$(u).lazyRule(function(boot,target){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);PornhubBoot.loadOnly();return PornhubCore.resolvePlay(target);},PornhubCore.bootstrap,u),extra:{id:'ph_play_'+PornhubCore.hash(u),lineVisible:false}});
    var fav=PornhubCore.isFav(u);add(d,{title:fav?'取消本地收藏':'加入本地收藏',desc:'独立于 Pornhub 账号收藏，仅保存在本机',col_type:'text_1',url:$(u).lazyRule(function(boot,target,tt,cv,ds){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);PornhubBoot.loadOnly();var on=PornhubCore.toggleFav({url:target,title:tt,rawImg:cv,img:PornhubCore.image(cv,target),desc:ds});refreshPage(false);return'toast://'+(on?'已加入本地收藏':'已取消本地收藏');},PornhubCore.bootstrap,u,x.title,x.cover,[x.duration,x.views].filter(function(v){return!!v;}).join(' · ')),extra:{lineVisible:false}});
    add(d,{title:'原站详情 / 评论 / 互动',desc:'站内点赞、评论等写操作先交给官方网页',col_type:'text_1',url:'web://'+u,extra:{lineVisible:false}});
    if(x.author){section(d,'创作者','');add(d,{title:x.author.name,desc:x.author.type,pic_url:x.author.img||'',col_type:'avatar',url:PornhubCore.page('pornhubProfile',{u:x.author.url}),extra:{lineVisible:false}});}if(x.desc){section(d,'简介','');add(d,{title:x.desc,col_type:'rich_text',url:'hiker://empty'});}if(x.categories.length){section(d,'分类','');for(var i=0;i<x.categories.length;i++)add(d,{title:x.categories[i].name,col_type:'scroll_button',url:PornhubCore.page('pornhubCategory',{u:x.categories[i].url,n:x.categories[i].name})});}if(x.tags.length){section(d,'标签','');for(var j=0;j<x.tags.length;j++)add(d,{title:x.tags[j].name,col_type:'flex_button',url:PornhubCore.page('pornhubCategory',{u:x.tags[j].url,n:x.tags[j].name})});}if(x.related.length){section(d,'相关推荐','');renderVideos(d,x.related,16);}setResult(d);};

  R.creators=function(){var kind=PornhubCore.param('kind','pornstars'),q=PornhubCore.param('q',''),page=PornhubCore.pageNo();title('创作者');var d=[];add(d,{title:'Pornstars',col_type:'scroll_button',url:PornhubCore.page('pornhubCreators',{kind:'pornstars'})});add(d,{title:'Channels',col_type:'scroll_button',url:PornhubCore.page('pornhubCreators',{kind:'channels'})});add(d,{title:'Models',col_type:'scroll_button',url:PornhubCore.page('pornhubCreators',{kind:'models'})});add(d,{title:'用户搜索',col_type:'scroll_button',url:PornhubCore.page('pornhubCreators',{kind:'users'})});add(d,{title:'搜索创作者',desc:q||'输入名字',col_type:'input',url:"(function(){var q=String(input||'').trim();return 'hiker://page/pornhubCreators?rule='+encodeURIComponent('"+PornhubCore.ruleTitle()+"')+'&simple=true&kind='+encodeURIComponent('"+kind+"')+'&q='+encodeURIComponent(q);})()",extra:{defaultValue:q}});var r=PornhubCore.creatorList(kind,page,q);renderProfiles(d,r.profiles);if(!r.profiles.length&&page===1)empty(d,'暂未识别到创作者','站点此区域可能变更结构；可从原站网页继续。',r.url);setResult(d);};
  R.profile=function(){var u=PornhubCore.param('u',''),d=[];if(!u){empty(d,'缺少创作者地址','请重新进入。');setResult(d);return;}var x=PornhubCore.profile(u);title(x.name);add(d,{title:x.name,desc:x.desc||PornhubCore.profileType(u),pic_url:x.img||'',col_type:'movie_1_left_pic',url:'hiker://empty',extra:{lineVisible:false}});add(d,{title:'原站主页',desc:u,col_type:'text_1',url:'web://'+u,extra:{lineVisible:false}});section(d,'公开视频',x.videos.length?x.videos.length+' 项':'当前页未解析到视频');renderVideos(d,x.videos);if(!x.videos.length)empty(d,'暂无可展示视频','可打开原站主页查看其他标签页。',u);setResult(d);};

  R.gifs=function(){var q=PornhubCore.param('q',''),page=PornhubCore.pageNo();title('GIF');var d=[];add(d,{title:'搜索 GIF',desc:q||'输入关键词',col_type:'input',url:"(function(){var q=String(input||'').trim();return 'hiker://page/pornhubGifs?rule='+encodeURIComponent('"+PornhubCore.ruleTitle()+"')+'&simple=true&q='+encodeURIComponent(q);})()",extra:{defaultValue:q}});var r=PornhubCore.gifList(page,q);for(var i=0;i<r.cards.length;i++){var c=r.cards[i];add(d,{title:c.title,desc:'GIF · 点击媒体提取',pic_url:c.img||'',col_type:'movie_2',url:'video://'+c.url,extra:{id:'ph_gif_'+PornhubCore.hash(c.url),lineVisible:false}});}if(!r.cards.length&&page===1)empty(d,'GIF 暂不可用','本版未从当前页面识别到 GIF 卡片。',r.url);setResult(d);};
  R.shorts=function(){var page=PornhubCore.pageNo();title('Shorts');var d=[],r=PornhubCore.shortList(page);for(var i=0;i<r.cards.length;i++){var c=r.cards[i];add(d,{title:c.title,desc:'Short',pic_url:c.img||'',col_type:'movie_2',url:'video://'+c.url,extra:{id:'ph_short_'+PornhubCore.hash(c.url),lineVisible:false}});}if(!r.cards.length&&page===1)empty(d,'Shorts 暂不可用','当前站点入口或 DOM 可能发生变化。',r.url);setResult(d);};
  R.playlists=function(){var page=PornhubCore.pageNo();title('Playlists');var d=[],r=PornhubCore.playlistList(page);section(d,'公开播放列表',r.links.length?r.links.length+' 项':'当前页面未识别到播放列表');for(var i=0;i<r.links.length;i++)add(d,{title:r.links[i].name,col_type:'text_1',url:'web://'+r.links[i].url,extra:{lineVisible:false}});if(!r.links.length)empty(d,'Playlists 暂不可用','先保留原站入口；后续根据实机结构继续原生化。',r.url);setResult(d);};

  R.login=function(){title('Pornhub 登录');var d=[];section(d,'网页登录','不保存密码。请在下方官方页面完成登录、验证码或二次验证，然后点击“同步登录状态”。');add(d,{title:'',desc:'list&&screen-300',col_type:'x5_webview_single',url:PornhubCore.base()+'/login',extra:{ua:PornhubCore.ua,canBack:true,showProgress:true}});add(d,{title:'同步网页登录状态',desc:PornhubCore.accountReady()?'当前已保存 Cookie':'读取官方网页 Cookie 并保存到本小程序账号会话',col_type:'text_1',url:$(PornhubCore.base()).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);PornhubBoot.loadOnly();var r=PornhubCore.syncWebCookie();if(r.ok){refreshPage(false);return'toast://'+r.message;}return'toast://'+r.message;},PornhubCore.bootstrap),extra:{lineVisible:false}});add(d,{title:'账号用户名',desc:PornhubCore.accountName()||'若自动识别失败，点此手动填写',col_type:'text_1',url:'input://'+JSON.stringify({value:PornhubCore.accountName(),hint:'Pornhub 用户名',js:"(function(){var n=String(input||'').trim();require('"+PornhubCore.bootstrap+"',{headers:{'Cache-Control':'no-cache'}},10101);PornhubBoot.loadOnly();PornhubCore.setAccountName(n);refreshPage(false);return 'toast://用户名已保存';})()"}),extra:{lineVisible:false}});add(d,{title:'进入我的账号',desc:'推荐 / Feed / 历史 / 站内收藏 / 订阅',col_type:'text_1',url:PornhubCore.page('pornhubAccount'),extra:{lineVisible:false}});setResult(d);};
  R.account=function(){title('我的账号');var d=[],ready=PornhubCore.accountReady(),name=PornhubCore.accountName();add(d,{title:ready?(name||'已登录'):'未同步登录',desc:ready?'Pornhub Cookie 会话已启用':'请先完成网页登录并同步 Cookie',pic_url:A+'account.svg',col_type:'avatar',url:ready?'hiker://empty':PornhubCore.page('pornhubLogin'),extra:{lineVisible:false}});if(!ready){add(d,{title:'前往登录',col_type:'text_1',url:PornhubCore.page('pornhubLogin'),extra:{lineVisible:false}});setResult(d);return;}icon(d,'为你推荐','账号推荐','home',PornhubCore.page('pornhubAccountList',{kind:'recommended',n:'为你推荐'}));icon(d,'Feed','订阅动态','feed',PornhubCore.page('pornhubAccountList',{kind:'feed',n:'Feed'}));icon(d,'观看历史','站内账号历史','history',PornhubCore.page('pornhubAccountList',{kind:'history',n:'观看历史'}));icon(d,'站内收藏','Pornhub 账号收藏','favorite',PornhubCore.page('pornhubAccountList',{kind:'favorites',n:'站内收藏'}));add(d,{title:'订阅的创作者',desc:'账号 subscriptions',col_type:'text_1',url:PornhubCore.page('pornhubSubscriptions'),extra:{lineVisible:false}});add(d,{title:'重新同步 Cookie',desc:'网页登录状态有变化时使用',col_type:'text_1',url:PornhubCore.page('pornhubLogin'),extra:{lineVisible:false}});add(d,{title:'退出本小程序账号会话',desc:'仅停用本小程序保存的 Cookie，不删除官方网页 Cookie',col_type:'text_1',url:$(PornhubCore.authEnabledKey).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);PornhubBoot.loadOnly();PornhubCore.logoutLocal();refreshPage(false);return'toast://已退出本小程序账号会话';},PornhubCore.bootstrap),extra:{lineVisible:false}});setResult(d);};
  R.accountList=function(){var kind=PornhubCore.param('kind','recommended'),n=PornhubCore.param('n','账号内容'),page=PornhubCore.pageNo();title(n);var d=[];if(!PornhubCore.accountReady()){empty(d,'登录状态不可用','请先登录并同步 Cookie。');add(d,{title:'去登录',col_type:'text_1',url:PornhubCore.page('pornhubLogin')});setResult(d);return;}var r=PornhubCore.accountVideos(kind,page);renderVideos(d,r.cards);if(!r.cards.length&&page===1)empty(d,r.error||'账号页没有可展示视频','若官方网页能正常查看，请把实机截图发来继续适配。',r.url);setResult(d);};
  R.subscriptions=function(){var page=PornhubCore.pageNo();title('订阅的创作者');var d=[],r=PornhubCore.subscriptions(page);renderProfiles(d,r.profiles);if(!r.profiles.length&&page===1)empty(d,r.error||'暂无订阅列表','如果账号名未自动识别，可在登录页手动填写。',r.url);setResult(d);};

  R.localFavorites=function(){title('本地收藏');var d=[],a=PornhubCore.readList(PornhubCore.favoriteKey);section(d,'本地收藏',a.length+' 项 · 与 Pornhub 账号收藏相互独立');renderVideos(d,a);if(!a.length)section(d,'还没有本地收藏','在视频详情页点击“加入本地收藏”。');setResult(d);};
  R.localHistory=function(){title('浏览历史');var d=[],a=PornhubCore.readList(PornhubCore.historyKey);section(d,'最近浏览',a.length+' 项');renderVideos(d,a);if(!a.length)section(d,'暂无历史','打开视频详情后会自动记录。');setResult(d);};

  R.settings=function(){title('设置与诊断');var d=[],b=PornhubCore.base(),h=PornhubCore.fetchText(b+'/video',{force:true,ttl:0}),cards=PornhubCore.parseVideoCards(h,b+'/video'),cats=PornhubCore.categories(false);section(d,'运行信息','');add(d,{title:'版本',desc:R.version+' · Build '+R.build,col_type:'text_1',url:'hiker://empty'});add(d,{title:'当前站点',desc:b,col_type:'text_1',url:'input://'+JSON.stringify({value:b,hint:'https://www.pornhub.com',js:"(function(){var v=String(input||'').trim().replace(/\\/+$/,'');if(!/^https?:\\/\\//i.test(v))return 'toast://请输入完整 https:// 地址';setItem('"+PornhubCore.baseKey+"',v);refreshPage(false);return 'toast://站点地址已更新';})()"})});add(d,{title:'账号状态',desc:PornhubCore.accountReady()?'已启用 · '+(PornhubCore.accountName()||'用户名待确认'):'未启用',col_type:'text_1',url:PornhubCore.page('pornhubLogin')});section(d,'实时诊断','');add(d,{title:'公开列表',desc:'HTML '+h.length+' 字符 · 视频卡 '+cards.length,col_type:'text_1',url:'hiker://empty'});add(d,{title:'分类接口',desc:cats.length+' 个分类',col_type:'text_1',url:'hiker://empty'});add(d,{title:'重新请求首页',desc:'绕过短缓存重新请求匿名列表',col_type:'text_1',url:$(b).lazyRule(function(boot,u){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);PornhubBoot.loadOnly();PornhubCore.fetchText(u+'/video',{force:true,ttl:0});refreshPage(false);return'toast://已重新请求';},PornhubCore.bootstrap,b)});section(d,'本地数据','');add(d,{title:'清空本地浏览历史',col_type:'text_1',url:$(PornhubCore.historyKey).lazyRule(function(boot,key){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);PornhubBoot.loadOnly();PornhubCore.writeList(key,[]);refreshPage(false);return'toast://历史已清空';},PornhubCore.bootstrap,PornhubCore.historyKey)});add(d,{title:'清空本地收藏',col_type:'text_1',url:$(PornhubCore.favoriteKey).lazyRule(function(boot,key){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);PornhubBoot.loadOnly();PornhubCore.writeList(key,[]);refreshPage(false);return'toast://本地收藏已清空';},PornhubCore.bootstrap,PornhubCore.favoriteKey)});section(d,'远程版本','');add(d,{title:'检查更新',desc:'只检查，不自动切版本',col_type:'text_1',url:$(PornhubCore.bootstrap).lazyRule(function(boot){require(boot,{headers:{'Cache-Control':'no-cache'}},10101);var r=PornhubBoot.check();return'toast://'+(r&&r.message?r.message:'检查完成');},PornhubCore.bootstrap)});add(d,{title:'原站网页',desc:b,col_type:'text_1',url:'web://'+b+'/'});setResult(d);};

  R.module=function(){return{home:R.home,catalog:R.catalog,categories:R.categories,category:R.category,search:R.search,searchPage:R.searchPage,detail:R.detail,creators:R.creators,profile:R.profile,gifs:R.gifs,shorts:R.shorts,playlists:R.playlists,login:R.login,account:R.account,accountList:R.accountList,subscriptions:R.subscriptions,localFavorites:R.localFavorites,localHistory:R.localHistory,settings:R.settings};};
  return R;
})();
