/* 色花堂 0.1.0-test.28 / Build 10128 - Guide card-boundary parser: first tid anchor owns the whole mobile card */
var SeHuaTangPatchTest28=(function(){
var BASE=SeHuaTangRemoteRuntime,C=SeHuaTangV16Core,CACHE_TTL=180000;
function s(v){return v==null?'':String(v)}
function trim(v){return C.trim(v)}
function guideUrl(mode,p){var view=mode==='latest'?'newthread':(mode==='digest'?'digest':'hot');return C.origin()+'/forum.php?mod=guide&view='+view+'&mobile=2&page='+Math.max(1,Number(p||1))}
function pageKey(mode){return'sht_guide_page_v28_'+mode}
function cacheKey(mode,p){return'sht_guide_cards_v28_'+mode+'_'+Math.max(1,Number(p||1))}
function pbtn(t,key,p,on){return{title:t,url:on?$('#noLoading#').lazyRule(function(k,v){putMyVar(k,String(v));refreshPage(false);return'hiker://empty';},key,p):'hiker://empty',col_type:'text_3',extra:{lineVisible:false}}}
function goodTitle(t){t=trim(t);return !!t&&t.length>=4&&t.length<=220&&!/本帖最后由.+编辑|^(查看帖子|查看|回复|最后发表|最后回复|上一页|下一页|返回|首页|论坛|社区版块|搜索|发帖|更多|我的话题)$/i.test(t)&&!/^#.+#$/.test(t)&&!/^\d+$/.test(t)}
function anchors(html,base){var out=[],re=/<a\b([^>]*?)href\s*=\s*(?:["']([^"']+)["']|([^\s>]+))([^>]*)>([\s\S]*?)<\/a>/gi,m,a,t,u;while((m=re.exec(s(html)))!==null){a=(m[1]||'')+' '+(m[4]||'');u=C.abs(m[2]||m[3]||'',base);t=trim(C.strip(m[5]||''));out.push({href:u,text:t,attrs:a,inner:m[5]||'',index:m.index});if(out.length>22000)break}return out}
function titleRank(a,first){var t=trim(a.text),r=0;if(!goodTitle(t))return-99999;if(/\b(?:xst|thread_subject|subject|thread-title|title)\b/i.test(a.attrs||''))r+=120;if(/[【\[][^】\]]+[】\]]/.test(t))r+=18;if(/NTR|FC2|FANZA|无码|有码|字幕|写真|原创|小说|视频|自拍|资源|AI|VR|4K/i.test(t))r+=12;if(t.length>=10&&t.length<=120)r+=20;if(t.length>160)r-=20;r-=Math.max(0,Number(a.index||0)-Number(first||0))/5000;return r}
function baseMap(m,html,base){var mp={},a=[],fn=m._debug&&m._debug.parseCardsV15,i;try{if(fn)a=fn(html,base,0)||[]}catch(e){a=[]}for(i=0;i<a.length;i++)mp[String(a[i].id||C.threadId(a[i].url)||'')]=a[i];return mp}
function cleanSummary(ctx,title,meta,fallback){var f=trim(fallback||'');if(f&&f!==title&&!/^#.+#$/.test(f)&&f.length>=10&&f.length<=190)return f;var x=s(ctx).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<img\b[^>]*>/gi,' '),t=C.strip(x);if(title)while(t.indexOf(title)>=0)t=t.replace(title,' ');if(meta&&meta.author)while(t.indexOf(meta.author)>=0)t=t.replace(meta.author,' ');t=t.replace(/本帖最后由[^。\n]{0,120}编辑/gi,' ').replace(/#([^#]{1,30})#/g,' ').replace(/(?:回复|评论|查看|浏览|观看|点赞|赞)[:：]?\s*\d+/g,' ').replace(/\b\d{4}-\d{1,2}-\d{1,2}(?:\s+\d{1,2}:\d{2})?\b/g,' ').replace(/\d+\s*(?:分钟|小时|天)前(?:发布)?/g,' ').replace(/隐藏置顶帖|全部主题|最新|热门|精华|按发帖|按回复|发表于|发布|版主|管理员|楼主/g,' ').replace(/\s+/g,' ').trim();if(t.length>180)t=t.slice(0,180)+'…';return t}
function parseGuide(m,html,base){var aa=anchors(html,base),bm=baseMap(m,html,base),map={},order=[],i,a,id,k,x,j,en,ctx,imgs,c,freq={},best,bestR,r,meta,stats;
  for(i=0;i<aa.length;i++){a=aa[i];id=C.threadId(a.href);if(!id)continue;k=String(id);if(!map[k]){map[k]={id:k,url:C.toMobile(a.href),start:a.index,cands:[]};order.push(k)}if(goodTitle(a.text))map[k].cands.push(a)}
  order.sort(function(a1,b1){return map[a1].start-map[b1].start});
  for(i=0;i<order.length;i++){k=order[i];x=map[k];en=i+1<order.length?map[order[i+1]].start:s(html).length;if(en<=x.start||en-x.start>130000)en=Math.min(s(html).length,x.start+100000);ctx=s(html).slice(x.start,en);best=null;bestR=-99999;for(j=0;j<x.cands.length;j++){r=titleRank(x.cands[j],x.start);if(r>bestR){bestR=r;best=x.cands[j]}}if(!best&&x.cands.length)best=x.cands[0];x.title=best?best.text:(bm[k]&&bm[k].title||'帖子');x.titleIndex=x.start;x.score=bestR;x.url=best?C.toMobile(best.href):x.url;meta=bm[k]&&bm[k].meta?bm[k].meta:{};x.meta=meta;imgs=C.allImages(ctx,base,10);x.imgs=imgs;x.summary=cleanSummary(ctx,x.title,meta,bm[k]&&bm[k].summary||'');try{stats=(typeof SeHuaTangV19Forum!=='undefined'&&SeHuaTangV19Forum.stats)?SeHuaTangV19Forum.stats(ctx,x):null}catch(e2){stats=null}x.stats=stats||{};for(j=0;j<imgs.length;j++){c=C.canonical(imgs[j]);freq[c]=(freq[c]||0)+1}}
  var out=[],seenImg,u;for(i=0;i<order.length&&out.length<100;i++){x=map[order[i]];seenImg={};imgs=[];for(j=0;j<(x.imgs||[]).length&&imgs.length<3;j++){u=x.imgs[j];c=C.canonical(u);if(!c||seenImg[c]||(freq[c]||0)>=3)continue;if(/avatar|uc_server|ucenter|noavatar|smiley|static\/image|logo\.|none\.gif|loading|blank\.gif|emotion|face\/|emoji|icon\/|placeholder|transparent|spacer/i.test(u))continue;seenImg[c]=1;imgs.push(u)}x.imgs=imgs;out.push(x)}return out}
function previewCount(a){var n=0,i;for(i=0;i<(a||[]).length;i++)n+=(a[i].imgs||[]).length;return n}
function cacheRead(mode,p){var x='';try{x=getItem(cacheKey(mode,p),'')||''}catch(e){}if(!x)return null;try{var o=JSON.parse(x);if(!o||!o.ts||!o.items||new Date().getTime()-Number(o.ts)>CACHE_TTL)return null;return o.items}catch(e2){return null}}
function cacheWrite(mode,p,items){try{setItem(cacheKey(mode,p),JSON.stringify({ts:new Date().getTime(),items:items}))}catch(e){}}
function load(m,url,mode,p){var c=cacheRead(mode,p),html='',items=[],source='mobile-render';if(c&&c.length)return{items:c,source:'cache'};html=C.renderList(url);items=parseGuide(m,html,url);if(!items.length){html=C.fetchPage(url,false);items=parseGuide(m,html,url);source='mobile-fetch-fallback'}if(!items.length){var pc=C.toPc(url);html=C.fetchPage(pc,true);items=parseGuide(m,html,pc);source='pc-fallback'}if(items.length)cacheWrite(mode,p,items);return{items:items,source:source}}
function statText(x){x=x||{};var a=[];if(x.replies)a.push('💬 '+x.replies);if(x.likes)a.push('👍 '+x.likes);if(x.views)a.push('👁 '+x.views);return a.join('　')}
function authorRow(d,it,ref){var m=it.meta||{},av=m.avatar?C.imageUrl(m.avatar,ref):'',title=(m.author||'发布者')+(m.role?' · '+m.role:''),desc=m.time||'';if(m.author||av||desc)d.push({title:title,desc:desc,img:av,pic_url:av,url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false,cls:'sht_v28_guide_author'}})}
function previewRows(d,it,ref,u){var imgs=it.imgs||[],j,p,ct;if(!imgs.length)return;ct=imgs.length>=3?'pic_3':(imgs.length===2?'pic_2':'pic_1_full');for(j=0;j<imgs.length&&j<3;j++){p=C.imageUrl(imgs[j],ref);if(p)d.push({title:'',img:p,pic_url:p,url:u,col_type:ct,extra:{lineVisible:false,cls:'sht_v28_guide_preview'}})}}
function statRow(d,it){var t=statText(it.stats);if(t)d.push({title:'',desc:t,url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false,cls:'sht_v28_guide_stat'}})}
function guideNative(m){var d=[],mode=C.pageParam('sht_auto','hot'),name=C.pageParam('sht_name',mode==='latest'?'最新发表':(mode==='digest'?'最新精华':'最新热门')),key=pageKey(mode),p=Math.max(1,Number(getMyVar(key,'1')||1)),url=guideUrl(mode,p),r=load(m,url,mode,p),items=r.items||[],i,it,u,pc=previewCount(items);setPageTitle(name);C.saveDiag('guide.native.v28',mode+' p='+p+' items='+items.length+' previews='+pc+' source='+r.source);
  d.push(C.quick('手机版','x5://'+url,'web.svg'));d.push(C.quick('搜索',C.route('shtSearch'),'search.svg'));d.push(C.line());d.push(C.section(name,'第 '+p+' 页 · '+items.length+' 条主题'+(pc?' · '+pc+' 张预览图':'')));
  d.push(pbtn(p>1?'上一页':'第一页',key,Math.max(1,p-1),p>1));d.push(pbtn(p>1?'回第1页':'第1页',key,1,p>1));d.push(pbtn(items.length?'下一页':'已到底',key,p+1,items.length>0));d.push(C.line());if(!items.length){d.push(C.empty('本页没有解析到主题','可点“手机版”确认官网页面状态'));setResult(d);return}
  for(i=0;i<items.length;i++){it=items[i];u=C.route('shtThread',{sht_url:C.toMobile(it.url),sht_name:it.title});authorRow(d,it,url);d.push({title:it.title,desc:it.summary||'',url:u,col_type:'text_1',extra:{lineVisible:false,cls:'sht_v28_guide_card'}});previewRows(d,it,url,u);statRow(d,it);d.push(C.line('sht_v28_guide_sep'))}
  d.push(pbtn('上一页',key,Math.max(1,p-1),p>1));d.push(pbtn('回第1页',key,1,p>1));d.push(pbtn('下一页',key,p+1,true));setResult(d)}
function module(){var m=BASE.module(),oldForum=m.forum;m.version='0.1.0-test.28';m.build=10128;m.forum=function(){if(C.pageParam('sht_auto',''))return guideNative(m);return oldForum()};m._debug=m._debug||{};m._debug.guideNativeV28=guideNative;m._debug.parseGuideV28=parseGuide;return m}
var P={version:'0.1.0-test.28',build:10128,module:module};SeHuaTangRemoteRuntime=P;return P;
})();
