/* 汤头条 0.1.0-test.9 PlaybackAdapter / expected-duration validation + source failover */
var TangTouTiaoPlaybackV017=(function(){
  var V='0.1.0-test.9';
  function compactUrl(u){u=String(u||'');return u.length>160?u.substring(0,80)+'…'+u.substring(u.length-60):u;}
  function jstr(s){return new java.lang.String(String(s==null?'':s));}function bytes(s){return jstr(s).getBytes('UTF-8');}function newBytes(n){return java.lang.reflect.Array.newInstance(java.lang.Byte.TYPE,n);}function copy(src,sp,dst,dp,len){java.lang.System.arraycopy(src,sp,dst,dp,len);}
  function hexBytes(s){s=String(s||'').trim();if(!s||s.length%2!==0||!/^[0-9A-Fa-f]+$/.test(s))return null;var a=newBytes(s.length/2);for(var i=0;i<a.length;i++){var v=parseInt(s.substr(i*2,2),16);a[i]=v>127?v-256:v;}return a;}
  function evp(secret,keyLen,ivLen){var pass=bytes(secret),md=java.security.MessageDigest.getInstance('MD5'),need=keyLen+ivLen,all=newBytes(need),pos=0,prev=null;while(pos<need){md.reset();if(prev)md.update(prev);md.update(pass);prev=md.digest();var n=Math.min(prev.length,need-pos);copy(prev,0,all,pos,n);pos+=n;}var key=newBytes(keyLen),iv=newBytes(ivLen);copy(all,0,key,0,keyLen);copy(all,keyLen,iv,0,ivLen);return{key:key,iv:iv};}
  function decrypt(hex,secret){var all=hexBytes(hex);if(!all||all.length<17)throw new Error('m3u8密文不是合法HEX');var iv=newBytes(16),body=newBytes(all.length-16);copy(all,0,iv,0,16);copy(all,16,body,0,body.length);var p=evp(secret,32,16),cipher=javax.crypto.Cipher.getInstance('AES/CFB/NoPadding'),key=new javax.crypto.spec.SecretKeySpec(p.key,'AES');cipher.init(2,key,new javax.crypto.spec.IvParameterSpec(iv));return String(new java.lang.String(cipher.doFinal(body),'UTF-8'));}
  function headers(){var h={'User-Agent':'Mozilla/5.0 (Linux; Android 13; HikerView) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Mobile Safari/537.36','Accept':'*/*','Cache-Control':'no-cache'},r=String(getItem('ttt_player_refer','')||''),x=String(getItem('ttt_player_xauth','')||'');if(r)h.Referer=r;if(x)h['X-Auth']=x;return h;}
  function decodeM3u8(remote){var raw=String(fetch(remote,{timeout:12000,headers:headers()})||''),trim=raw.trim(),plain=trim,mode='plain',dekey=String(getItem('ttt_player_dekey','')||'');if(trim.indexOf('#EXTM3U')!==0){if(!dekey)throw new Error('播放器配置缺少 dekey');plain=decrypt(trim,dekey).trim();mode='aes-cfb';}if(plain.indexOf('#EXTM3U')!==0)throw new Error('解密结果不是 M3U8');return{plain:plain,mode:mode};}
  function durationOf(s){var dur=0,m=String(s||'').match(/#EXTINF:([0-9.]+)/g)||[];for(var i=0;i<m.length;i++){var x=m[i].match(/([0-9.]+)/);if(x)dur+=Number(x[1]||0);}return Math.round(dur*10)/10;}
  function durationSeconds(v){if(typeof v==='number'&&isFinite(v))return Number(v);v=String(v||'').trim();if(!v)return 0;if(/^\d+(?:\.\d+)?$/.test(v))return Number(v);var p=v.split(':').map(function(x){return Number(x||0);});if(p.some(function(x){return !isFinite(x);}))return 0;if(p.length===3)return p[0]*3600+p[1]*60+p[2];if(p.length===2)return p[0]*60+p[1];return 0;}
  function childOf(remote,plain){if(!/#EXT-X-STREAM-INF/i.test(plain))return'';var fixed=String(fixM3u8(remote,plain)||''),ls=fixed.split('\n');for(var i=0;i<ls.length;i++){var l=String(ls[i]||'').trim();if(l&&l.charAt(0)!=='#'&&/^https?:\/\//i.test(l)&&/\.m3u8(?:\?|$)/i.test(l))return l;}return'';}
  function badDuration(dur,expected){if(!(dur>0))return false;if(dur<4)return true;if(expected>=120&&dur<Math.max(45,expected*0.55))return true;if(expected>=30&&expected<120&&dur<expected*0.35)return true;return false;}
  function inspect(remote,depth,expected){remote=String(remote||'').trim();if(!remote)return{ok:false,error:'empty'};if(!/\.m3u8(?:\?|$)/i.test(remote))return{ok:true,duration:null,mode:'direct',remote:remote,suspicious:false};try{var d=decodeM3u8(remote),dur=durationOf(d.plain),child=dur<=0&&depth<1?childOf(remote,d.plain):'';if(child){var c=inspect(child,(depth||0)+1,expected);if(c.ok&&c.duration!=null)return{ok:true,duration:c.duration,mode:d.mode+'+master',remote:remote,child:compactUrl(child),suspicious:!!c.suspicious,ratio:c.ratio};}var ratio=expected>0&&dur>0?Math.round((dur/expected)*1000)/1000:null;return{ok:true,duration:dur,mode:d.mode,remote:remote,suspicious:badDuration(dur,expected),ratio:ratio};}catch(e){return{ok:false,error:String(e.message||e),remote:remote};}}
  function makeProxy(){var code=$.toString(function(){
      function jstr(s){return new java.lang.String(String(s==null?'':s));}function bytes(s){return jstr(s).getBytes('UTF-8');}function newBytes(n){return java.lang.reflect.Array.newInstance(java.lang.Byte.TYPE,n);}function copy(src,sp,dst,dp,len){java.lang.System.arraycopy(src,sp,dst,dp,len);}function hexBytes(s){s=String(s||'').trim();if(!s||s.length%2!==0)return null;var a=newBytes(s.length/2);for(var i=0;i<a.length;i++){var v=parseInt(s.substr(i*2,2),16);if(isNaN(v))return null;a[i]=v>127?v-256:v;}return a;}function evp(secret,keyLen,ivLen){var pass=bytes(secret),md=java.security.MessageDigest.getInstance('MD5'),need=keyLen+ivLen,all=newBytes(need),pos=0,prev=null;while(pos<need){md.reset();if(prev)md.update(prev);md.update(pass);prev=md.digest();var n=Math.min(prev.length,need-pos);copy(prev,0,all,pos,n);pos+=n;}var key=newBytes(keyLen),iv=newBytes(ivLen);copy(all,0,key,0,keyLen);copy(all,keyLen,iv,0,ivLen);return{key:key,iv:iv};}
      function decrypt(hex,secret){var all=hexBytes(hex);if(!all||all.length<17)throw new Error('m3u8密文不是合法HEX');var iv=newBytes(16),body=newBytes(all.length-16);copy(all,0,iv,0,16);copy(all,16,body,0,body.length);var p=evp(secret,32,16),cipher=javax.crypto.Cipher.getInstance('AES/CFB/NoPadding'),key=new javax.crypto.spec.SecretKeySpec(p.key,'AES');cipher.init(2,key,new javax.crypto.spec.IvParameterSpec(iv));return String(new java.lang.String(cipher.doFinal(body),'UTF-8'));}
      function childProxy(u,base){if(!base||!/\.m3u8(?:\?|$)/i.test(u))return u;return base+'?m3u8=1&u='+encodeURIComponent(base64Encode(u))+'&p='+encodeURIComponent(base64Encode(base))+'&_t='+Date.now();}
      try{var remote=base64Decode(decodeURIComponent(String(MY_PARAMS.u||''))),base=base64Decode(decodeURIComponent(String(MY_PARAMS.p||''))),refer=String(getItem('ttt_player_refer','')||''),xauth=String(getItem('ttt_player_xauth','')||''),dekey=String(getItem('ttt_player_dekey','')||''),h={'User-Agent':'Mozilla/5.0 (Linux; Android 13; HikerView) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Mobile Safari/537.36','Accept':'*/*','Cache-Control':'no-cache'};if(refer)h.Referer=refer;if(xauth)h['X-Auth']=xauth;var raw=String(fetch(remote,{timeout:15000,headers:h})||''),trim=raw.trim(),plain=trim;if(trim.indexOf('#EXTM3U')!==0){if(!dekey)throw new Error('播放器配置缺少 dekey');plain=decrypt(trim,dekey).trim();}if(plain.indexOf('#EXTM3U')!==0)throw new Error('解密结果不是 M3U8');var fixed=fixM3u8(remote,plain),lines=String(fixed).split('\n');for(var i=0;i<lines.length;i++){var line=lines[i];if(line.indexOf('#')===0)lines[i]=line.replace(/URI="(https?:\/\/[^\"]+\.m3u8[^\"]*)"/ig,function(_,u){return'URI="'+childProxy(u,base)+'"';});else if(/^https?:\/\//i.test(line)&&/\.m3u8(?:\?|$)/i.test(line))lines[i]=childProxy(line,base);}return lines.join('\n');}catch(e){setItem('ttt_last_play_diag',JSON.stringify({time:Date.now(),ok:false,error:String(e.message||e)}));return'#EXTM3U\n#EXT-X-VERSION:3\n#EXT-X-ENDLIST';}
    });return startProxyServer(code);}
  function proxyUrl(proxy,u,i){u=String(u||'').trim();if(!u)return'';if(/\.m3u8(?:\?|$)/i.test(u))return proxy+'?m3u8=1&u='+encodeURIComponent(base64Encode(u))+'&p='+encodeURIComponent(base64Encode(proxy))+'&_t='+Date.now()+'_'+(i||0)+'#isVideo=true#';return u+'#isVideo=true#';}
  function parse(payload){var x=typeof payload==='string'?JSON.parse(payload):payload||{};return{x:x,src:Array.isArray(x.sources)?x.sources:[],expected:durationSeconds(x.expectedDuration||0)};}
  function ordered(src,preferred){var order=[],seen={};function add(s){if(!s||seen[s.name])return;seen[s.name]=1;order.push(s);}preferred=String(preferred||'240P');for(var i=0;i<src.length;i++)if(String(src[i].name)===preferred)add(src[i]);var names=['240P','480P','720P','1080P','原始','预览'];for(var n=0;n<names.length;n++)for(var j=0;j<src.length;j++)if(String(src[j].name)===names[n])add(src[j]);for(var k=0;k<src.length;k++)add(src[k]);return order;}
  function choose(payload,preferred){var p=parse(payload);if(!p.src.length)return{error:'没有可用播放线路'};try{if(typeof TangTouTiaoProtocolV015==='object')TangTouTiaoProtocolV015.bootstrapSession(false);}catch(e){}var q=ordered(p.src,preferred),checks=[];for(var i=0;i<q.length;i++){var r=inspect(q[i].url,0,p.expected);checks.push({name:q[i].name,ok:r.ok,duration:r.duration,expected:p.expected,ratio:r.ratio,mode:r.mode||'',suspicious:!!r.suspicious,error:r.error||''});if(r.ok&&!r.suspicious){try{setItem('ttt_last_source_probe',JSON.stringify({time:Date.now(),preferred:String(preferred||''),expected:p.expected,chosen:q[i].name,checks:checks}));}catch(e1){}return{source:q[i],index:i,checks:checks};}}try{setItem('ttt_last_source_probe',JSON.stringify({time:Date.now(),preferred:String(preferred||''),expected:p.expected,chosen:'',checks:checks}));}catch(e2){}return{error:'未找到与视频时长匹配的完整可用线路',checks:checks};}
  function playBest(payload,preferred){var c=choose(payload,preferred||'240P');if(c.error)return'toast://'+c.error;var proxy=makeProxy(),u=proxyUrl(proxy,c.source.url,c.index);setItem('ttt_last_play_sources',JSON.stringify({time:Date.now(),mode:'duration-aware-single',preferred:String(preferred||'240P'),name:c.source.name,url:compactUrl(c.source.url)}));return u;}
  return{version:V,playBest:playBest};
})();
