/* Hanime1 Test33 account: restore playlist cards with selector-safe parsing */
(function(C,P,E,H,L){
function clean(v){return C.clean(String(v==null?'':v));}
function nodes(html,sel){try{return pdfa(String(html||''),sel)||[];}catch(e){return [];}}
function nodesAny(html,sels){var out=[],seen={};for(var s=0;s<sels.length;s++){var a=nodes(html,sels[s]);for(var i=0;i<a.length;i++){var k=String(a[i]||'');if(!seen[k]){seen[k]=1;out.push(a[i]);}}}return out;}
function text(node,sel){try{return clean(pdfh(node,sel)||'');}catch(e){return '';}}
function attr(node,sel){try{return String(pdfh(node,sel)||'').replace(/&amp;/g,'&').trim();}catch(e){return '';}}
function firstText(node,sels){for(var i=0;i<sels.length;i++){var v=text(node,sels[i]);if(v)return v;}return '';}
function firstAttr(node,sels){for(var i=0;i<sels.length;i++){var v=attr(node,sels[i]);if(v)return v;}return '';}
function abs(base,u){u=String(u||'').trim();return u?C.abs(base,u):'';}
function playlistId(href){var m=String(href||'').match(/[?&]list=([^&"']+)/);return m?decodeURIComponent(m[1]):'';}
function fromWrapper(n,base){var href=firstAttr(n,['a.video-link&&href','a[href*="playlist?list="]&&href','a[href*=playlist]&&href','a&&href']),id=playlistId(href),title=firstText(n,['.title&&Text','.playlist-title&&Text','img&&alt','a&&title']),img=firstAttr(n,['img.main-thumb&&src','img&&data-src','img&&src']),count=firstText(n,['.stat-item&&Text','.playlist-count&&Text']);if(!id)return null;return {id:id,title:title||('片单 '+id),count:count,img:abs(base,img)};}
function playlistCards33(h,base){var out=[],seen={},wraps=nodesAny(h,['.user-tab-item-wrapper','.playlist-item-wrapper','.playlist-card','div[class^=user-tab-item-wrapper]']);for(var i=0;i<wraps.length;i++){var p=fromWrapper(wraps[i],base);if(p&&p.id&&!seen[p.id]){seen[p.id]=1;out.push(p);}}if(out.length)return out;var links=nodesAny(h,['a[href*="playlist?list="]','a[href*=playlist]']);for(var j=0;j<links.length;j++){var a=links[j],href=attr(a,'href'),id=playlistId(href);if(!id||seen[id])continue;var ctx=a;try{ctx=pdfh(a,'parent&&Html')||a;}catch(e){}var p2=fromWrapper(ctx,base);if(!p2){var title=firstText(ctx,['.title&&Text','.playlist-title&&Text','img&&alt','Text']);p2={id:id,title:title||('片单 '+id),count:'',img:abs(base,firstAttr(ctx,['img.main-thumb&&src','img&&src']))};}seen[id]=1;out.push(p2);}if(out.length)return out;var src=String(h||''),re=/href\s*=\s*(["'])([^"']*playlist\?list=([^&"']+)[^"']*)\1/gi,m;while((m=re.exec(src))!==null){var rid='';try{rid=decodeURIComponent(m[3]);}catch(e){rid=m[3];}if(!rid||seen[rid])continue;var start=Math.max(0,m.index-2500),frag=src.slice(start,Math.min(src.length,m.index+5000)),tm=frag.match(/class\s*=\s*(["'])[^"']*(?:playlist-title|\btitle\b)[^"']*\1[^>]*>([\s\S]*?)<\//i),im=frag.match(/<img\b[^>]*(?:data-src|src)\s*=\s*(["'])([^"']+)\1/i);seen[rid]=1;out.push({id:rid,title:tm?clean(tm[2]):('片单 '+rid),count:'',img:abs(base,im?im[2]:'')});if(m.index===re.lastIndex)re.lastIndex++;}return out;}
var oldSection=P.librarySection30;
P.librarySection30=function(kind){if(kind!=='playlists')return oldSection(kind);var a=P.sessionProfile32?P.sessionProfile32():C.activeAccount();if(!a||!a.id)throw new Error('请先登录');var base=C.resolveHost(false),url=base+'/user/'+String(a.id)+'/playlists',r=C.get(url,{base:base,referer:base+'/',timeout:16000});if(!r||r.challenge||Number(r.statusCode||0)>=400)throw new Error('账号片单加载失败：HTTP '+Number((r&&r.statusCode)||0));return {playlists:playlistCards33(String(r.body||''),base),items:[]};};
P.playlistCards33=playlistCards33;
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);
