/* Hanime1 Test33 creator UI: website-inspired directory + profile pages */
(function(C,P,E,H){
var oldResults=E.videoResultsPage;
function clean(v){return C.clean(String(v==null?'':v));}
function text(node,sel){try{return clean(pdfh(node,sel)||'');}catch(e){return '';}}
function attr(node,sel){try{return String(pdfh(node,sel)||'').replace(/&amp;/g,'&').trim();}catch(e){return '';}}
function firstText(node,sels){for(var i=0;i<sels.length;i++){var v=text(node,sels[i]);if(v)return v;}return '';}
function firstAttr(node,sels){for(var i=0;i<sels.length;i++){var v=attr(node,sels[i]);if(v)return v;}return '';}
function route(type,o){o=o||{};o.creatorType=type;return H.route('hanimeVideoResults',o);}
function videoCard(x){return {title:x.title||'未命名',desc:[x.duration,x.views,x.artist].filter(Boolean).join(' · '),pic_url:x.img||x.cover||'',url:H.route('hanimeDetail',{id:x.id,title:x.title||''}),col_type:'movie_2',extra:{lineVisible:false}};}
function header(d,name,avatar,role,meta,url){d.push({title:name||role,desc:[role,meta].filter(Boolean).join(' · '),pic_url:avatar||'',url:url||'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false,inheritTitle:false}});}
function directory(){var q=H.pv('query',getMyVar('hanime33_artist_q','')),page=Number(H.pv('page','1')||1),r=P.artistDirectory28(q,page),list=r.items||[],d=[];setPageTitle('作者目录');d.push({title:'搜索作者',url:"putMyVar('hanime33_artist_q',input);refreshPage(false);return 'hiker://empty';",col_type:'input',extra:{hint:'输入作者 / 制作商名称',defaultValue:q,lineVisible:false}});d.push({title:'影片筛选',url:H.route('hanimeVideoFilter',{}),col_type:'text_2',extra:{lineVisible:false}});d.push({title:'综合搜索',url:H.route('hanimeSearch',{}),col_type:'text_2',extra:{lineVisible:false}});d.push(H.sec(q?('作者搜索 · '+q):'作者目录',list.length?('第 '+page+' 页 · '+list.length+' 位'):'暂无作者'));for(var i=0;i<list.length;i++){var x=list[i];d.push({title:x.name,desc:x.count||'查看作品',pic_url:x.avatar||'',url:route('artist',{creatorName:x.name,creatorQuery:x.query||x.name,creatorAvatar:x.avatar||'',creatorCount:x.count||''}),col_type:'pic_3_square',extra:{lineVisible:false}});}if(page>1)d.push(H.btn('‹ 上一页',route('directory',{query:q,page:page-1})));if(page<Number(r.totalPages||page))d.push(H.btn('下一页 ›',route('directory',{query:q,page:page+1})));setResult(d);}
function artist(){var page=Number(H.pv('page','1')||1),name=H.pv('creatorName',''),query=H.pv('creatorQuery','')||name,avatar=H.pv('creatorAvatar',''),count=H.pv('creatorCount','');if(!name)throw new Error('缺少作者名称');try{var m=P.artistMeta28(name);if(m){avatar=avatar||m.avatar||'';count=count||m.count||'';query=m.query||query;}}catch(e){}var r=P.search({query:query,page:page,type:''}),list=(r&&r.items)||[],d=[];setPageTitle(name);header(d,name,avatar,'作者',count||('第 '+page+' 页'));d.push({title:'✓ 影片',url:'hiker://empty',col_type:'scroll_button'});d.push({title:'作者目录',url:route('directory',{query:name}),col_type:'scroll_button'});d.push({title:'官网搜索',url:'x5://'+C.query(C.resolveHost(false)+'/search',{query:query,type:'artist'}),col_type:'scroll_button'});d.push({col_type:'line_blank'});d.push(H.sec('影片',list.length?('第 '+page+' 页 · '+list.length+' 部'):'暂无作品'));for(var i=0;i<list.length;i++)d.push(videoCard(list[i]));if(page>1)d.push(H.btn('‹ 上一页',route('artist',{creatorName:name,creatorQuery:query,creatorAvatar:avatar,creatorCount:count,page:page-1})));if(page<Number(r.totalPages||page))d.push(H.btn('下一页 ›',route('artist',{creatorName:name,creatorQuery:query,creatorAvatar:avatar,creatorCount:count,page:page+1})));setResult(d);}
function uploaderMeta(id){var base=C.resolveHost(false),url=base+'/user/'+id,r=C.get(url,{base:base,referer:base+'/',timeout:15000});if(!r||r.challenge||Number(r.statusCode||0)>=400)return {};var h=String(r.body||''),stats=firstText(h,['.profile-sub-stats-new-line&&Text','.profile-sub-stats&&Text']),handle=firstText(h,['.profile-sub-stats-id&&Text']),avatar=firstAttr(h,['.profile-avatar-wrapper img&&src','#user-modal-dp-wrapper img&&src','img#playlist-avatar&&src']),name=firstText(h,['.profile-display-name&&Text','#user-modal-name&&Text','h1&&Text']);return {name:name,avatar:avatar?C.abs(base,avatar):'',stats:stats,handle:handle,url:url};}
function uploader(){var page=Number(H.pv('page','1')||1),id=H.pv('userId',''),seed=H.pv('creatorName','')||H.pv('userName',''),seedAvatar=H.pv('creatorAvatar','');if(!id)throw new Error('缺少上传者 ID');var r=P.userUploads17(id,seed,page),m=uploaderMeta(id),name=m.name||r.name||seed||('用户 '+id),avatar=m.avatar||r.avatar||seedAvatar,d=[],list=r.items||[];setPageTitle(name);header(d,name,avatar,'上传者',[m.handle,m.stats].filter(Boolean).join(' · ')||('公开上传 · 第 '+page+' 页'),m.url||r.url);d.push({title:'✓ 影片',url:'hiker://empty',col_type:'scroll_button'});d.push({title:'官网主页',url:'x5://'+(m.url||r.url),col_type:'scroll_button'});d.push({title:'搜索同名',url:H.route('hanimeVideoResults',{query:name}),col_type:'scroll_button'});d.push({col_type:'line_blank'});d.push(H.sec('影片',list.length?('第 '+page+' 页 · '+list.length+' 部'):'暂无公开作品'));for(var i=0;i<list.length;i++)d.push(videoCard(list[i]));if(page>1)d.push(H.btn('‹ 上一页',route('uploader',{userId:id,creatorName:name,creatorAvatar:avatar,page:page-1})));if(page<Number(r.totalPages||page))d.push(H.btn('下一页 ›',route('uploader',{userId:id,creatorName:name,creatorAvatar:avatar,page:page+1})));setResult(d);}
E.videoResultsPage=function(){var type=H.pv('creatorType','');try{if(type==='directory')return directory();if(type==='artist')return artist();if(type==='uploader')return uploader();return oldResults();}catch(x){setResult([{title:'创作者页面加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9);
