/* Hanime1 Test33 library: Netflav-style five compact rows */
(function(P,E,H,U,L){
function setVar(key,val){return $('#noLoading#').lazyRule(function(k,v){if(v===''&&k!=='hanime8_sort')clearMyVar(k);else putMyVar(k,v);refreshPage(false);return 'hiker://empty';},key,String(val));}
function clear(){return $('#noLoading#').lazyRule(function(){putMyVar('hanime8_sort','最新上傳');clearMyVar('hanime8_genre');clearMyVar('hanime8_date');clearMyVar('hanime8_duration');clearMyVar('hanime8_tags');clearMyVar('hanime8_broad');refreshPage(false);return 'toast://筛选已清空';});}
function btn(t,u,on){return {title:(on?'✓ ':'')+t,url:u,col_type:'scroll_button',extra:{lineVisible:false}};}
function br(d){d.push({col_type:'line_blank'});}
function row(d,label,key,items,cur,more){d.push(btn(label,'hiker://empty',false));for(var i=0;i<items.length;i++)d.push(btn(items[i][0],setVar(key,items[i][1]),String(cur)===String(items[i][1])));d.push(btn('›',more,false));br(d);}
E.renderLibrary=function(d,page){page=Number(page||1);var s=H.state(),cat=s.cat||{};if(page===1){row(d,'类型','hanime8_genre',[['全部',''],['里番','裏番'],['泡面番','泡麵番'],['Motion','Motion Anime'],['3D','3DCG']],s.genre,H.route('hanimeVideoFilter',{section:'genre'}));row(d,'排序','hanime8_sort',[['最新上传','最新上傳'],['最新上市','最新上市'],['本日排行','本日排行'],['本周排行','本週排行']],s.sort,H.route('hanimeVideoFilter',{section:'sort'}));row(d,'日期','hanime8_date',[['全部',''],['24小时','過去 24 小時'],['2天','過去 2 天'],['1周','過去 1 週'],['1月','過去 1 個月']],s.date,H.route('hanimeVideoFilter',{section:'date'}));row(d,'时长','hanime8_duration',[['全部',''],['1分+','1 分鐘 +'],['5分+','5 分鐘 +'],['10分+','10 分鐘 +'],['20分+','20 分鐘 +']],s.duration,H.route('hanimeVideoFilter',{section:'duration'}));var tg=(s.tags&&s.tags[0])||'';row(d,'标签','hanime8_tags',[['全部',''],['无码','無碼'],['中字','中文字幕'],['1080P','1080p'],['60FPS','60FPS']],tg,H.route('hanimeVideoFilter',{section:'tags'}));d.push({title:'全部筛选',url:H.route('hanimeVideoFilter',{}),col_type:'text_2',extra:{lineVisible:false}});d.push({title:'清空筛选',url:clear(),col_type:'text_2',extra:{lineVisible:false}});}var r=P.publicLibrary({sort:s.sort,genre:s.genre,date:s.date,duration:s.duration,tags:s.tags,broad:s.broad,page:page}),list=r.items||[];if(page===1)d.push(H.sec('影片',H.summary(s)+' · '+list.length+' 部'));for(var j=0;j<list.length;j++)d.push(L.video(list[j],'library'));if(!list.length)d.push(H.sec('暂无结果','调整筛选条件后会立即刷新。'));};
})(HanimeProvider,HanimePages,HanimeUI9,HanimeUI10,HanimeLayout12);
