/* Hanime1 Remote Stable Bootstrap 2.0.1 / promoted Test40 */
var HANIME_BOOT_MANAGER='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/libs/updater/remote_manager.js?v=201';
var HANIME_BOOT_CONFIG={id:'hanime1',branch:'main',repoRawRoot:'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/',latestPath:'apps/video/hanime1/latest.json',moduleHeaders:{'Cache-Control':'no-cache'},minBuild:20040,defaultRelease:{"schema":1,"id":"hanime1","name":"Hanime1","version":"2.0.1","build":20040,"ref":"main","promotedFrom":{"channel":"test","version":"2.0.0-test.40","build":20040,"release":"apps/video/hanime1/releases/2.0.0-test.40/release.json"},"modules":[{"name":"stable-recovery","path":"apps/video/hanime1/releases/2.0.1/recovery_loader.js"}],"verify":{"global":"HanimePages","property":"build","equals":"2.0.1"},"notes":"Stable 2.0.1 is the user-approved promotion of Test40. It keeps the recovered search path and the Test40 performance isolation while preserving known account/reply/UI issues for later test-channel work."}};
var HanimeBoot={
manager:function(){require(HANIME_BOOT_MANAGER,{headers:{'Cache-Control':'no-cache'}},201);if(typeof HikerCloudRemote!=='object')throw new Error('远程模块管理器加载失败');return HikerCloudRemote;},
loadOnly:function(){var r=this.manager().load(HANIME_BOOT_CONFIG);if(!r||!r.ok||typeof HanimePages!=='object')throw new Error('Hanime1 Stable runtime load failed');return r;},
module:function(){this.loadOnly();return HanimePages;},
info:function(){return this.manager().info(HANIME_BOOT_CONFIG);},check:function(){return this.manager().check(HANIME_BOOT_CONFIG);},update:function(){return this.manager().update(HANIME_BOOT_CONFIG);},rollback:function(){return this.manager().rollback(HANIME_BOOT_CONFIG);},reinstall:function(){return this.manager().reinstall(HANIME_BOOT_CONFIG);}
};
