/* 汤头条 0.1.0-test.8 Core / split-image + creator-rank adapters */
var TangTouTiaoCoreV016=(function(){
  var V='0.1.0-test.8';
  var IMG_MOD='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/tangtoutiao/releases/0.1.0-test.6/image.js?v=10106';
  function text(v){return String(v==null?'':v).replace(/<[^>]+>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').trim();}
  function maybeJson(v){if(typeof v!=='string')return v;var s=v.trim();if(!s)return v;if((s.charAt(0)==='{'&&s.charAt(s.length-1)==='}')||(s.charAt(0)==='['&&s.charAt(s.length-1)===']'))try{return JSON.parse(s);}catch(e){}return v;}
  function pick(o,keys,d){o=maybeJson(o);if(!o||typeof o!=='object')return d;for(var i=0;i<keys.length;i++){var v=o[keys[i]];if(v!==undefined&&v!==null&&String(v)!=='')return v;}return d;}
  function dataOf(res){res=maybeJson(res);if(res==null)return null;return maybeJson(res.data!==undefined?res.data:res.result!==undefined?res.result:res);}
  function abs(u){u=String(u||'').trim();if(/^\/\//.test(u))return'https:'+u;return u;}
  function imageCandidate(v){v=maybeJson(v);if(!v)return'';if(typeof v==='string')return abs(v);if(Array.isArray(v)){for(var i=0;i<v.length;i++){var a=imageCandidate(v[i]);if(a)return a;}return'';}if(typeof v==='object'){var keys=['720','720p','360','ori','original','url','src','image','img'];for(var j=0;j<keys.length;j++){var x=v[keys[j]];if(x){var b=imageCandidate(x);if(b)return b;}}for(var k in v)if(v.hasOwnProperty(k)){var c=imageCandidate(v[k]);if(c)return c;}}return'';}
  function imageUrl(raw){
    var u=imageCandidate(raw);if(!u)return'';if(!/^https?:\/\//i.test(u))return u;
    var host=(u.match(/^https?:\/\/([^\/]+)/i)||[])[1]||'',plainExt=/\.(?:jpe?g|png|gif|webp|bmp)(?:\?|$)/i.test(u);
    if(plainExt&&/^(?:picx\.)?yrfmba\.cn$/i.test(host)){
      try{setItem('ttt_last_image_policy',JSON.stringify({time:Date.now(),host:host,mode:'direct-public-image',url:u.substring(0,180)}));}catch(e0){}
      return u;
    }
    try{
      var headers={'User-Agent':'Mozilla/5.0 (Linux; Android 13; HikerView) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Mobile Safari/537.36','Accept':'image/avif,image/webp,image/apng,image/*,*/*;q=0.8'},ref=String(getItem('ttt_player_refer','')||'');if(ref)headers.Referer=ref;
      var link=$(u,headers).image(function(mod){return $.require(mod).decrypt(input);},IMG_MOD);
      try{setItem('ttt_last_image_link',JSON.stringify({time:Date.now(),host:host,helper:true,hasJs:String(link).indexOf('@js=')>=0,hasHeaders:String(link).indexOf('@headers=')>=0}));}catch(e1){}
      return link;
    }catch(e){try{setItem('ttt_last_image_link',JSON.stringify({time:Date.now(),host:host,helper:false,error:String(e.message||e)}));}catch(e2){}return u;}
  }
  function memberOf(x){var m=x&&x.member;return m&&typeof m==='object'?m:{};}
  function item(x){x=maybeJson(x)||{};var m=memberOf(x),cr=pick(x,['coverRaw','thumb_cover','thumb_cover_str','thumb','cover','cover_url','coverUrl','img_url','imgUrl'],'')||'';return{
    id:String(pick(x,['id','mv_id','mvId','video_id','videoId','aid'],'')||''),title:text(pick(x,['title','mv_title','mvTitle','name'],'未命名')),coverRaw:cr,cover:imageUrl(cr),author:text(pick(m,['nickname','username'],pick(x,['nickname','author','creator_name'],'')||'')),avatar:imageUrl(pick(m,['thumb','thumb_url'],pick(x,['member_thumb','avatar'],'')||'')||''),desc:text(pick(x,['desc','description','intro'],'')||''),duration:text(pick(x,['duration_str','durationStr','duration'],'')||''),plays:text(pick(x,['count_play_str','views_count_str','count_play'],'')||''),comments:text(pick(x,['count_comment_str','count_comment'],'')||''),source240:abs(pick(x,['source_240','source240'],'')||''),source480:abs(pick(x,['source_480','source480'],'')||''),source720:abs(pick(x,['source_720','source720'],'')||''),source1080:abs(pick(x,['source_1080','source1080'],'')||''),preview:abs(pick(x,['preview_video','previewVideo'],'')||''),sourceOrigin:abs(pick(x,['source_origin','sourceOrigin'],'')||''),isPay:!!pick(x,['is_pay','isPay'],false),isFree:Number(pick(x,['isfree','is_free','isFree'],0)||0),raw:x};}
  function looksVideo(x){return !!(x&&typeof x==='object'&&(x.id!=null||x.mv_id!=null)&&(x.title||x.thumb_cover||x.source_240));}
  function exactFeatured(res){var d=dataOf(res)||{},groups=Array.isArray(d.list)?d.list:[],out=[];for(var i=0;i<groups.length;i++){var g=maybeJson(groups[i])||{},list=Array.isArray(g.list)?g.list:[];if(!list.length&&looksVideo(g))list=[g];for(var j=0;j<list.length;j++){var it=item(list[j]);if(it.id&&it.title&&it.title!=='未命名')out.push(it);}}try{var first=out[0]||{};setItem('ttt_last_featured_exact',JSON.stringify({groups:groups.length,videos:out.length,firstId:first.id||'',coverRawType:typeof(first.coverRaw),coverCandidate:String(imageCandidate(first.coverRaw)||'').substring(0,140),sources:[!!first.source240,!!first.source480,!!first.source720,!!first.source1080]}));}catch(e){}return out;}
  function directList(res){var d=dataOf(res)||{},list=Array.isArray(d.list)?d.list:Array.isArray(d.items)?d.items:Array.isArray(d)?d:[],out=[];for(var i=0;i<list.length;i++){var x=list[i];if(x&&Array.isArray(x.list)){for(var j=0;j<x.list.length;j++){var a=item(x.list[j]);if(a.id||a.title!=='未命名')out.push(a);}}else{var it=item(x);if(it.id||it.title!=='未命名')out.push(it);}}return out;}
  function recursiveList(res){var root=dataOf(res),best=[];function walk(v,depth){v=maybeJson(v);if(depth>7||v==null)return;if(Array.isArray(v)){var score=0;for(var i=0;i<Math.min(v.length,5);i++)if(looksVideo(v[i]))score++;if(score&&v.length>best.length)best=v;for(var j=0;j<Math.min(v.length,3);j++)walk(v[j],depth+1);return;}if(typeof v==='object'){var ks=Object.keys(v);for(var k=0;k<ks.length;k++){var key=ks[k];if(/banner|ads|advert|widget/i.test(key))continue;walk(v[key],depth+1);}}}walk(root,0);var out=[];for(var i=0;i<best.length;i++){var it=item(best[i]);if(it.id||it.title!=='未命名')out.push(it);}return out;}
  function normalize(res,kind){if(kind==='featured'||kind==='video')return exactFeatured(res);if(kind==='search')return directList(res);var d=directList(res);return d.length?d:recursiveList(res);}
  function detailItem(res,fallback){var d=dataOf(res)||{},raw=d&&d.detail&&typeof d.detail==='object'?d.detail:d&&d.mv&&typeof d.mv==='object'?d.mv:d,it=item(raw);fallback=fallback||{};if(!it.id)it.id=String(fallback.id||'');if(!it.title||it.title==='未命名')it.title=text(fallback.title||'视频详情');if(!it.coverRaw&&fallback.coverRaw){it.coverRaw=fallback.coverRaw;it.cover=imageUrl(fallback.coverRaw);}if(!it.author)it.author=text(fallback.author||'');return it;}
  function sources(it){var a=[];function add(name,u){u=String(u||'').trim();if(u)a.push({name:name,url:u});}add('1080P',it.source1080);add('720P',it.source720);add('480P',it.source480);add('240P',it.source240);if(!a.length)add('预览',it.preview);return a;}
  function comicCategories(res){var d=dataOf(res),list=Array.isArray(d)?d:(d&&Array.isArray(d.list)?d.list:[]),out=[];for(var i=0;i<list.length;i++){var x=maybeJson(list[i])||{},name=text(pick(x,['name','title'],'')||'');if(!name)continue;var params=maybeJson(pick(x,['params_list','paramsList'],{})||{});if(!params||typeof params!=='object'||Array.isArray(params))params={};out.push({id:String(pick(x,['id'],'')||''),name:name,current:!!pick(x,['current'],false),showStyle:Number(pick(x,['show_style','showStyle'],0)||0),type:String(pick(x,['type'],'')||''),apiList:String(pick(x,['api_list','apiList'],'')||''),params:params,raw:x});}try{setItem('ttt_last_comic_home',JSON.stringify({time:Date.now(),count:out.length,first:out[0]?{name:out[0].name,api:out[0].apiList,params:out[0].params}:null}));}catch(e){}return out;}
  function comicList(res){var d=dataOf(res)||{},list=Array.isArray(d)?d:Array.isArray(d.list)?d.list:Array.isArray(d.data)?d.data:Array.isArray(d.items)?d.items:[],out=[];for(var i=0;i<list.length;i++){var x=maybeJson(list[i])||{},rawCover=pick(x,['thumb','thumb_url','img_url','cover'],'')||'';out.push({id:String(pick(x,['id','book_id'],'')||''),title:text(pick(x,['title','name'],'未命名')),coverRaw:rawCover,cover:imageUrl(rawCover),desc:text(pick(x,['categories','tags','series','update_time'],'')||''),raw:x});}return out.filter(function(x){return x.id||x.title!=='未命名';});}
  function rankCreators(res){var d=dataOf(res),list=Array.isArray(d)?d:(d&&Array.isArray(d.list)?d.list:[]),out=[];for(var i=0;i<list.length;i++){var x=maybeJson(list[i])||{},name=text(pick(x,['nickname','name'],'')||'');if(!name)continue;var cr=pick(x,['thumb_url','thumb','avatar'],'')||'';out.push({rank:Number(pick(x,['num'],i+1)||i+1),uuid:String(pick(x,['owner_uuid','uuid'],'')||''),nickname:name,coverRaw:cr,cover:imageUrl(cr),videos:Number(pick(x,['videos_count'],0)||0),followers:Number(pick(x,['followed_count'],0)||0),vip:text(pick(x,['vip_level_str','role_id_str'],'')||''),auth:text(pick(x,['auth_status_str'],'')||''),raw:x});}return out;}
  function enc(v){return encodeURIComponent(String(v==null?'':v));}function dec(v){v=String(v==null?'':v);try{if(/%[0-9A-Fa-f]{2}/.test(v))return decodeURIComponent(v);}catch(e){}return v;}
  function page(path,p){var u='hiker://page/'+path+'?rule=&simple=true',o=p||{};for(var k in o)if(o.hasOwnProperty(k)&&o[k]!=null&&String(o[k])!=='')u+='&'+enc(k)+'='+enc(o[k]);return u;}function param(n,d){try{var v=getParam(n);return v==null||v===''?d:dec(v);}catch(e){return d;}}
  function routeParams(it){return{id:it.id,title:it.title,coverRaw:typeof it.coverRaw==='string'?it.coverRaw:JSON.stringify(it.coverRaw||''),author:it.author};}
  function addHistory(it){if(!it)return;var a=[];try{a=JSON.parse(getItem('ttt_history','[]')||'[]');}catch(e){}if(!Array.isArray(a))a=[];a=a.filter(function(x){return String(x.id)!==String(it.id);});a.unshift({id:it.id,title:it.title,coverRaw:it.coverRaw,author:it.author,source240:it.source240,source480:it.source480,source720:it.source720,source1080:it.source1080,time:Date.now()});if(a.length>80)a=a.slice(0,80);setItem('ttt_history',JSON.stringify(a));}
  function histories(){try{var a=JSON.parse(getItem('ttt_history','[]')||'[]');return Array.isArray(a)?a:[];}catch(e){return[];}}
  function toggleFav(it){var a=[];try{a=JSON.parse(getItem('ttt_favs','[]')||'[]');}catch(e){}if(!Array.isArray(a))a=[];var id=String(it.id||''),idx=-1;for(var i=0;i<a.length;i++)if(String(a[i].id)===id){idx=i;break;}if(idx>=0){a.splice(idx,1);setItem('ttt_favs',JSON.stringify(a));return false;}a.unshift({id:id,title:it.title,coverRaw:it.coverRaw,author:it.author,source240:it.source240,source480:it.source480,source720:it.source720,source1080:it.source1080,time:Date.now()});setItem('ttt_favs',JSON.stringify(a));return true;}
  function favs(){try{var a=JSON.parse(getItem('ttt_favs','[]')||'[]');return Array.isArray(a)?a:[];}catch(e){return[];}}function isFav(id){var a=favs();for(var i=0;i<a.length;i++)if(String(a[i].id)===String(id))return true;return false;}
  return{version:V,text:text,pick:pick,dataOf:dataOf,imageCandidate:imageCandidate,imageUrl:imageUrl,item:item,normalize:normalize,exactFeatured:exactFeatured,directList:directList,detailItem:detailItem,sources:sources,comicCategories:comicCategories,comicList:comicList,rankCreators:rankCreators,page:page,param:param,routeParams:routeParams,addHistory:addHistory,histories:histories,toggleFav:toggleFav,favs:favs,isFav:isFav};
})();
