/** ACFun 0.6.0-alpha15 / Build 166
 * CLEAN REBASE on Stable 0.4.9 only.
 * Goals:
 * - keep Stable video itemInfo/image/playback untouched
 * - keep Stable v047 APP taxonomy/comics/short foundation
 * - add community/fiction/audio as isolated adapters
 * - one coherent native UI, no Alpha3~14 overlay chain
 */
(function(){
if(typeof ac!=='object')throw new Error('ACFun core missing');
var stableDetail=ac.detail, stableSettings=ac.settings, stableComments=ac.comments, stableFav=ac.favorites, stableHist=ac.history;
var BOOT='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/bootstrap_test_v071.js?v=7100',BVER=7100;
var BASE='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/assets/';
function S(v){return String(v===undefined||v===null?'':v)}
function N(v){var s=S(v);return /^\d+$/.test(s)?Number(s):s}
function P(){try{return Math.max(1,Number(MY_PAGE||1)||1)}catch(e){return 1}}
function I(n){return BASE+n+'.svg'}
function pick(o,ks,d){try{return ac.pick(o||{},ks,d)}catch(e){return d}}
function first(v){try{return ac.__v042FirstMedia?S(ac.__v042FirstMedia(v)||''):S(v)}catch(e){return S(v)}}
function param(k){try{return S(getParam(k,''))}catch(e){return''}}
function cleanText(v){return S(v).replace(/\r/g,'').replace(/\n{3,}/g,'\n\n').trim()}
function html(v){return cleanText(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'<br>')}
function copy(o){var x={};for(var k in(o||{}))x[k]=o[k];return x}
function join(base,p){base=S(base).trim();p=S(p).trim();if(!p)return'';if(p.indexOf('//')===0)return'https:'+p;if(/^https?:\/\//i.test(p))return p;if(base&&/^https?:\/\//i.test(base))return base.replace(/\/+$/,'')+'/'+p.replace(/^\/+/, '');return p}
function uniq(rows,idfn){var out=[],seen={};for(var i=0;i<(rows||[]).length;i++){var x=rows[i],k=S(idfn(x));if(!k||seen[k])continue;seen[k]=1;out.push(x)}return out}
function cacheRead(k,ttl,stale){try{return ac.__v042Read?ac.__v042Read('a15|'+k,ttl||180,stale||3600):{hit:false,fresh:false,stale:false,data:null}}catch(e){return{hit:false,fresh:false,stale:false,data:null}}}
function cacheWrite(k,v){try{if(v&&(!Array.isArray(v)||v.length)&&ac.__v042Write)return ac.__v042Write('a15|'+k,v)}catch(e){}return false}
function arr(v){if(Array.isArray(v))return v;if(!v||typeof v!=='object')return[];var ks=['list','items','records','rows','data','content','videoList','fictionList','dynamicList','categoryList','tagList'];for(var i=0;i<ks.length;i++)if(Array.isArray(v[ks[i]]))return v[ks[i]];for(var j=0;j<ks.length;j++)if(v[ks[j]]&&typeof v[ks[j]]==='object'){var a=arr(v[ks[j]]);if(a.length)return a}return[]}
function apiOne(path,params,method,timeout){var opt={timeout:timeout||1600,maxAttempts:1};if(method==='POST'){opt.method='POST';opt.write=true;opt.allowGet=false}return ac.__v043Api(path,params||{},opt)}
function apiMatrix(path,params,methods,kind,key,ttl,stale){
    var c=cacheRead(key,ttl,stale),old=c.hit&&Array.isArray(c.data)?c.data:[];if(c.fresh&&old.length)return old;
    var errs=[];for(var m=0;m<methods.length;m++)try{var raw=apiOne(path,params,methods[m],1700),a=arr(raw);if(a.length){cacheWrite(key,a);try{setItem('acfun_a15_last_route',key+' -> '+methods[m]+' '+path+' ('+a.length+')');setItem('acfun_a15_last_error','')}catch(e0){}return a}}catch(e){errs.push(methods[m]+' '+path+': '+S(e.message||e))}
    if(errs.length)try{setItem('acfun_a15_last_error',errs.slice(0,4).join('\n'))}catch(e1){}return old
}
function apiObject(path,paramList,methods,key){
    var c=cacheRead('obj|'+key,600,86400),old=c.hit&&c.data&&typeof c.data==='object'?c.data:{};if(c.fresh&&Object.keys(old).length)return old;
    var errs=[];for(var i=0;i<paramList.length;i++)for(var m=0;m<methods.length;m++)try{var o=apiOne(path,paramList[i],methods[m],1900);if(o&&typeof o==='object'){cacheWrite('obj|'+key,o);try{setItem('acfun_a15_last_route','obj|'+key+' -> '+methods[m]+' '+path)}catch(e0){}return o}}catch(e){errs.push(methods[m]+' '+path+': '+S(e.message||e))}
    if(errs.length)try{setItem('acfun_a15_last_error',errs.slice(0,4).join('\n'))}catch(e1){}return old
}

var SECTIONS=[['featured','精选'],['comic','漫画'],['anime','动漫'],['video','视频'],['lifan','里番'],['short','短视频'],['community','社区'],['fiction','小说'],['audio','有声']];
function section(){var s=S(getMyVar('acfun_a15_section','')||getItem('acfun_a15_section','featured')||'featured'),ok=false;for(var i=0;i<SECTIONS.length;i++)if(SECTIONS[i][0]===s)ok=true;if(!ok)s='featured';return s}
function setSectionUrl(s){return $('hiker://empty#noLoading#').lazyRule(function(v){putMyVar('acfun_a15_section',v);setItem('acfun_a15_section',v);putMyVar('acfun_native_section',v);refreshPage(false);return'hiker://empty'},s)}
function secIcon(s,on){var n=({featured:'featured',comic:'comic',anime:'anime',video:'video',lifan:'lifan',short:'short',community:'community',fiction:'novel',audio:'audio'})[s]||'featured';return I(n+(on?'':'_off'))}
function selectUrl(title,rows,current,onSelect){var opts=[],vals=[];for(var i=0;i<(rows||[]).length;i++){opts.push(S(rows[i].name));vals.push(S(rows[i].id!==undefined?rows[i].id:rows[i].value))}if(!opts.length)return'toast://暂无可选项';return 'select://'+JSON.stringify({title:title,options:opts,selectedIndex:Math.max(0,vals.indexOf(S(current))),col:3,js:$.toString(onSelect,opts,vals)})}
function sortRows(){return[{name:'全部',value:'0'},{name:'最新',value:'1'},{name:'最多观看',value:'2'},{name:'最多点赞',value:'3'}]}
function sortName(){var v=S(getMyVar('acfun_native_sort','1')||'1'),r=sortRows();for(var i=0;i<r.length;i++)if(r[i].value===v)return r[i].name;return'最新'}
function top(d){var s=section();d.push({title:'搜索视频、漫画、小说与社区',pic_url:I('search'),img:I('search'),col_type:'text_icon',url:'hiker://page/acfun_search_center?rule=ACFun&simple=true#noRecordHistory#',extra:{inheritTitle:false,pageTitle:'ACFun 全站搜索',lineVisible:false}});for(var i=0;i<5;i++){var x=SECTIONS[i];d.push({title:x[1],pic_url:secIcon(x[0],s===x[0]),img:secIcon(x[0],s===x[0]),col_type:'icon_5',url:setSectionUrl(x[0]),extra:{lineVisible:false}})}for(var j=5;j<SECTIONS.length;j++){var y=SECTIONS[j];d.push({title:y[1],pic_url:secIcon(y[0],s===y[0]),img:secIcon(y[0],s===y[0]),col_type:'icon_small_4',url:setSectionUrl(y[0]),extra:{lineVisible:false}})}[['收藏','favorite_off','acfun_favorites'],['历史','history_off','acfun_history'],['设置','settings_off','acfun_settings']].forEach(function(x){d.push({title:x[0],pic_url:I(x[1]),img:I(x[1]),col_type:'icon_small_3',url:'hiker://page/'+x[2]+'?rule=ACFun&simple=true#noRecordHistory#',extra:{inheritTitle:false,pageTitle:x[0],lineVisible:false}})})}

function currentBy(rows,key){var id=S(getMyVar(key,'')||''),hit=null;for(var i=0;i<(rows||[]).length;i++)if(S(rows[i].id)===id)hit=rows[i];if(!hit&&rows&&rows.length){hit=rows[0];putMyVar(key,S(hit.id))}return hit}
function filters(d){
    var s=section(),sort=S(getMyVar('acfun_native_sort','1')||'1'),rows=[],cur=null,key='';
    if(s==='featured'||s==='lifan'){
        rows=ac.__v047Stations?ac.__v047Stations(s==='lifan'?1:0):[];key=s==='lifan'?'acfun_native_station_lifan':'acfun_native_station_featured';cur=currentBy(rows,key);d.push({title:'频道 · '+(cur?cur.name:'暂无')+' ▾',col_type:'scroll_button',url:selectUrl('选择频道',rows,cur?cur.id:'',function(os,vs,k){var i=os.indexOf(input);if(i<0)return;putMyVar(k,String(vs[i]));refreshPage(false)},key),extra:{lineVisible:false}})
    }else if(s==='comic'){
        rows=ac.__v047ComicStations?ac.__v047ComicStations():[];key='acfun_native_comic_station';cur=currentBy(rows,key);d.push({title:'漫画 · '+(cur?cur.name:'暂无')+' ▾',col_type:'scroll_button',url:selectUrl('选择漫画分类',rows,cur?cur.id:'',function(os,vs){var i=os.indexOf(input);if(i<0)return;putMyVar('acfun_native_comic_station',String(vs[i]));refreshPage(false)}),extra:{lineVisible:false}})
    }else if(s==='anime'||s==='video'){
        rows=ac.__v047Catalog?ac.__v047Catalog(s):[];key=s==='video'?'acfun_native_video_class':'acfun_native_anime_class';cur=currentBy(rows,key);d.push({title:'分类 · '+(cur?cur.name:'暂无')+' ▾',col_type:'scroll_button',url:selectUrl('选择分类',rows,cur?cur.id:'',function(os,vs,k,zk){var i=os.indexOf(input);if(i<0)return;putMyVar(k,String(vs[i]));clearMyVar(zk);refreshPage(false)},key,s==='video'?'acfun_native_zone_video':'acfun_native_zone_anime'),extra:{lineVisible:false}});if(cur&&ac.__v047Zones){var zs=ac.__v047Zones(cur)||[],zk=s==='video'?'acfun_native_zone_video':'acfun_native_zone_anime',zcur=currentBy([{id:'',name:'全部'}].concat(zs),zk);d.push({title:'标签 · '+(zcur?zcur.name:'全部')+' ▾',col_type:'scroll_button',url:selectUrl('选择标签',[{id:'',name:'全部'}].concat(zs),zcur?zcur.id:'',function(os,vs,k){var i=os.indexOf(input);if(i<0)return;if(vs[i])putMyVar(k,String(vs[i]));else clearMyVar(k);refreshPage(false)},zk),extra:{lineVisible:false}})}
    }else if(s==='short'){
        var sr=[{id:'1',name:'同城'},{id:'2',name:'关注'},{id:'3',name:'最新'},{id:'4',name:'最热'}],sv=S(getMyVar('acfun_short_load_type','3')||'3'),sn='最新';for(var si=0;si<sr.length;si++)if(sr[si].id===sv)sn=sr[si].name;d.push({title:'短视频 · '+sn+' ▾',col_type:'scroll_button',url:selectUrl('选择短视频流',sr,sv,function(os,vs){var i=os.indexOf(input);if(i<0)return;putMyVar('acfun_short_load_type',String(vs[i]));refreshPage(false)}),extra:{lineVisible:false}})
    }else if(s==='community'){
        var cr=communityCategories(),cv=S(getMyVar('acfun_a15_dynamic_cat','')||''),cn='全部';for(var ci=0;ci<cr.length;ci++)if(S(cr[ci].id)===cv)cn=cr[ci].name;d.push({title:'社区 · '+cn+' ▾',col_type:'scroll_button',url:selectUrl('选择社区分类',[{id:'',name:'全部'}].concat(cr),cv,function(os,vs){var i=os.indexOf(input);if(i<0)return;if(vs[i])putMyVar('acfun_a15_dynamic_cat',String(vs[i]));else clearMyVar('acfun_a15_dynamic_cat');refreshPage(false)}),extra:{lineVisible:false}})
    }else if(s==='fiction'||s==='audio'){
        var fr=fictionTags(s),fk='acfun_a15_fiction_tag_'+s,fv=S(getMyVar(fk,'')||''),fn='全部';for(var fi=0;fi<fr.length;fi++)if(S(fr[fi].id)===fv)fn=fr[fi].name;d.push({title:(s==='audio'?'有声':'小说')+' · '+fn+' ▾',col_type:'scroll_button',url:selectUrl('选择分类',[{id:'',name:'全部'}].concat(fr),fv,function(os,vs,k){var i=os.indexOf(input);if(i<0)return;if(vs[i])putMyVar(k,String(vs[i]));else clearMyVar(k);refreshPage(false)},fk),extra:{lineVisible:false}})
    }
    if(s!=='short'&&s!=='community'&&s!=='fiction'&&s!=='audio')d.push({title:'排序 · '+sortName()+' ▾',col_type:'scroll_button',url:selectUrl('选择排序',sortRows().map(function(x){return{id:x.value,name:x.name}}),sort,function(os,vs){var i=os.indexOf(input);if(i<0)return;putMyVar('acfun_native_sort',String(vs[i]));refreshPage(false)}),extra:{lineVisible:false}});d.push({col_type:'line'})
}

function fictionInfo(x){x=x||{};var id=pick(x,['fictionId','bookId','novelId','id'],''),title=pick(x,['fictionTitle','bookTitle','bookName','novelTitle','title','name'],'未命名'),im=first(x.fictionImg)||first(x.fictionCover)||first(x.fictionCoverImg)||first(x.coverImg)||first(x.cover)||first(x.verticalImg)||first(x.poster),author=pick(x,['authorName','author','nickName','nickname'],'');return{id:S(id),title:S(title),img:S(im),author:S(author),desc:S(pick(x,['description','desc','info','introduction'],'')),raw:x}}
function dynamicInfo(x){x=x||{};var id=pick(x,['dynamicId','postId','id'],''),content=S(pick(x,['dynamicContent','content','contentText','text','title'],'')||''),im=first(x.dynamicImg)||first(x.dynamicImage)||first(x.cardImg)||first(x.coverImg)||first(x.imageUrl)||first(x.imgUrl)||first(x.backImg),u=x.user||x.userInfo||x.blogger||{};return{id:S(id),title:content||'社区动态',img:S(im),author:S(pick(u,['nickname','nickName','userName','name'],pick(x,['userName','nickname','authorName'],''))),raw:x}}
function fictionTags(mode){var type=mode==='audio'?2:1,key='fiction-tags|'+mode,c=cacheRead(key,21600,604800);if(c.stale&&Array.isArray(c.data)&&c.data.length)return c.data;var rows=[],tries=[{fictionType:type},{type:type},{}];for(var i=0;i<tries.length&&!rows.length;i++)rows=apiMatrix('fiction/other/tagList',tries[i],['POST','GET'],'fiction',key+'|'+i,21600,604800);var out=[];for(var j=0;j<rows.length;j++){var x=rows[j]||{},id=pick(x,['fictionTagId','tagId','categoryId','id'],''),name=pick(x,['fictionTagName','tagName','categoryName','name','title'],'');if(id&&name)out.push({id:S(id),name:S(name),raw:x})}out=uniq(out,function(x){return x.id});if(out.length)cacheWrite(key,out);return out}
function fictionList(page,mode){mode=mode==='audio'?'audio':'fiction';var size=Number(getItem('acfun_page_size','8'))||8,tag=S(getMyVar('acfun_a15_fiction_tag_'+mode,'')||''),base={page:page,pageNum:page,pageSize:size,limit:size,sortType:1},tries=[];if(tag){base.tagId=N(tag);base.fictionTagId=N(tag);base.categoryId=N(tag)}if(mode==='audio'){var a=copy(base);a.fictionType=2;a.isAudio=1;tries.push(a);var b=copy(base);b.fictionType=2;b.longFormAudio=1;tries.push(b)}else{var c=copy(base);c.fictionType=1;tries.push(c);tries.push(base)}for(var i=0;i<tries.length;i++){var r=apiMatrix('fiction/base/findList',tries[i],['POST','GET'],'fiction','fiction-list|'+mode+'|'+tag+'|'+page+'|'+i,120,3600);if(r.length)return r}return[]}
function communityCategories(){var rows=apiMatrix('dynamic/category/tree',{},['GET','POST'],'category','dynamic-cats',21600,604800),out=[];for(var i=0;i<rows.length;i++){var x=rows[i]||{},id=pick(x,['categoryId','dynamicType','id'],''),name=pick(x,['categoryName','dynamicTypeName','name','title'],'');if(id&&name)out.push({id:S(id),name:S(name),raw:x})}return uniq(out,function(x){return x.id})}
function dynamicList(page){var size=Number(getItem('acfun_page_size','8'))||8,cat=S(getMyVar('acfun_a15_dynamic_cat','')||''),p={page:page,pageNum:page,pageSize:size,limit:size};if(cat){p.categoryId=N(cat);p.dynamicType=N(cat)}var rows=apiMatrix('community/dynamic/list',p,['GET','POST'],'dynamic','dynamic-list|'+cat+'|'+page,90,1800);return rows}

function currentBootPlay(info,short){var raw=info.raw||{};return $('hiker://empty#noLoading#').lazyRule(function(id,r,uri,boot,ver){try{require(boot,{headers:{'Cache-Control':'no-cache'}},ver);ACFunBoot.loadOnly();return ac.play(String(id),String(r),String(uri||''))}catch(e){return'toast://播放失败：'+String(e.message||e)}},S(info.id),JSON.stringify(raw),S(info.uri||''),BOOT,BVER)}
function videoCard(d,x,short){var info=ac.itemInfo(x);if(!info||!info.id)return;var meta=[];if(info.watch)meta.push('▶ '+ac.fmtNum(info.watch));if(info.duration)meta.push(info.duration);if(!meta.length&&info.author)meta.push(info.author);var pic=ac.image(info.img);try{if(info.img)setItem('acfun_a15_cover_sample',S(info.img));if(pic)setItem('acfun_a15_cover_rendered',S(pic).slice(0,800))}catch(e){}if(short)d.push({title:info.title,desc:meta.join(' · '),pic_url:pic,img:pic,col_type:'movie_3',url:currentBootPlay(info,true),extra:{lineVisible:false,video_id:info.id,video_title:info.title,video_img:info.img,video_uri:info.uri,video_data:JSON.stringify(info.raw||{})}});else ac.addVideoCard(d,x,'movie_2')}
function comicCard(d,x){var ci=ac.__v047ComicInfo?ac.__v047ComicInfo(x):{};if(!ci.id)return;var pic=ac.image(ci.img);d.push({title:ci.title,desc:ci.desc,pic_url:pic,img:pic,col_type:'movie_3',url:'hiker://page/acfun_detail?rule=ACFun&simple=true#noRecordHistory#',extra:{inheritTitle:false,pageTitle:ci.title,content_kind:'comic',comics_id:ci.id,comics_title:ci.title}})}
function fictionCard(d,x,mode){var i=fictionInfo(x);if(!i.id)return;var pic=i.img?ac.image(i.img):I(mode==='audio'?'audio':'novel');try{setItem('acfun_a15_fiction_seed_'+i.id,JSON.stringify(x||{}))}catch(e){}d.push({title:i.title,desc:[i.author,mode==='audio'?'有声':'小说'].filter(function(v){return!!v}).join(' · '),pic_url:pic,img:pic,col_type:'movie_3',url:'hiker://page/acfun_detail?rule=ACFun&simple=true&content_kind=fiction&fiction_id='+encodeURIComponent(i.id)+'&fiction_mode='+mode+'#noRecordHistory#',extra:{content_kind:'fiction',fiction_id:i.id,fiction_title:i.title,fiction_mode:mode,lineVisible:false}})}
function dynamicCard(d,x){var i=dynamicInfo(x);if(!i.id)return;try{setItem('acfun_a15_dynamic_seed_'+i.id,JSON.stringify(x||{}))}catch(e){}var pic=i.img?ac.image(i.img):'';d.push({title:i.title.length>46?i.title.slice(0,46)+'…':i.title,desc:i.author||'社区动态',pic_url:pic,img:pic,col_type:pic?'movie_1_left_pic':'text_1',url:'hiker://page/acfun_detail?rule=ACFun&simple=true&content_kind=dynamic&dynamic_id='+encodeURIComponent(i.id)+'#noRecordHistory#',extra:{content_kind:'dynamic',dynamic_id:i.id,lineVisible:false}})}
function listFor(s,page){putMyVar('acfun_native_section',s);if(s==='featured')return ac.__v047StationList?ac.__v047StationList(page,0):[];if(s==='lifan')return ac.__v047StationList?ac.__v047StationList(page,1):[];if(s==='comic')return ac.__v047ComicList?ac.__v047ComicList(page):[];if(s==='short')return ac.__v047ShortList?ac.__v047ShortList(page):[];if(s==='anime'||s==='video')return ac.__v047CatalogList?ac.__v047CatalogList(page,s):[];if(s==='community')return dynamicList(page);if(s==='fiction'||s==='audio')return fictionList(page,s);return[]}
ac.home=function(){var d=[],page=P(),s=section();if(page===1){top(d);filters(d);d.push({title:({featured:'精选',comic:'漫画',anime:'动漫',video:'视频',lifan:'里番',short:'短视频',community:'社区',fiction:'小说',audio:'有声'})[s],col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}})}var list=[];try{list=listFor(s,page)||[]}catch(e){try{setItem('acfun_a15_home_error',S(e.message||e))}catch(e0){}}if(s==='comic')for(var i=0;i<list.length;i++)comicCard(d,list[i]);else if(s==='short')for(var j=0;j<list.length;j++)videoCard(d,list[j],true);else if(s==='community')for(var k=0;k<list.length;k++)dynamicCard(d,list[k]);else if(s==='fiction'||s==='audio')for(var q=0;q<list.length;q++)fictionCard(d,list[q],s);else for(var z=0;z<list.length;z++)videoCard(d,list[z],false);if(!list.length&&page===1)d.push({title:'当前栏目暂未返回内容',desc:'栏目：'+s+'\n'+S(getItem('acfun_a15_last_error','')).slice(0,500),col_type:'long_text',url:'hiker://empty'});setResult(d)};

function videoSearch(q,page){var size=Number(getItem('acfun_page_size','8'))||8,tries=[['video/queryVideoByTitle',{page:page,pageNum:page,pageSize:size,title:q,keyword:q,videoType:1}],['search/keyWordV2',{page:page,pageNum:page,pageSize:size,limit:size,searchWord:q,keyword:q,keyWord:q,searchType:1}],['search/keyWord',{page:page,pageNum:page,pageSize:size,limit:size,searchWord:q,keyword:q,keyWord:q,searchType:1}]];for(var i=0;i<tries.length;i++){var r=apiMatrix(tries[i][0],tries[i][1],['GET','POST'],'video','search-video|'+q+'|'+page+'|'+i,120,900);if(r.length)return r}return[]}
function typedSearch(kind,q,page){if(kind==='video')return videoSearch(q,page);if(kind==='comic'){var p={page:page,pageNum:page,pageSize:10,comicsTitle:q,title:q,keyword:q};return apiMatrix('comics/base/findList',p,['GET','POST'],'comic','search-comic|'+q+'|'+page,120,900)}if(kind==='fiction'||kind==='audio'){var p2={page:page,pageNum:page,pageSize:10,fictionTitle:q,title:q,keyword:q};if(kind==='audio'){p2.fictionType=2;p2.isAudio=1}else p2.fictionType=1;return apiMatrix('fiction/base/findList',p2,['POST','GET'],'fiction','search-'+kind+'|'+q+'|'+page,120,900)}if(kind==='dynamic'){return apiMatrix('community/dynamic/list',{page:page,pageNum:page,pageSize:10,keyword:q,content:q},['GET','POST'],'dynamic','search-dynamic|'+q+'|'+page,120,900)}return[]}
ac.search=function(){var d=[],q=param('kw')||param('s')||S(getMyVar('acfun_a15_search_kw',''));if(!q){try{q=decodeURIComponent(param('q'))}catch(e){}}var list=videoSearch(q,P());for(var i=0;i<list.length;i++)videoCard(d,list[i],false);if(!list.length&&P()===1)d.push({title:'没有搜索到视频',desc:'关键词：'+q,col_type:'long_text',url:'hiker://empty'});setResult(d)};
ac.searchCenter=function(){var d=[],q=param('kw')||S(getMyVar('acfun_a15_search_kw','')),kind=S(getMyVar('acfun_a15_search_kind','video')||'video');if(P()===1){d.push({title:'输入关键词',desc:q||'搜索视频、漫画、小说、有声、社区',pic_url:I('search'),img:I('search'),col_type:'input',url:"(function(){var q=String(input||'').trim();if(!q)return 'hiker://empty';putMyVar('acfun_a15_search_kw',q);return 'hiker://page/acfun_search_center?rule=ACFun&simple=true&kw='+encodeURIComponent(q)+'#noRecordHistory#';})()",extra:{defaultValue:q,lineVisible:false}});var kinds=[['video','视频'],['comic','漫画'],['fiction','小说'],['audio','有声'],['dynamic','社区']];for(var k=0;k<kinds.length;k++)(function(x){d.push({title:(kind===x[0]?'✓ ':'')+x[1],col_type:'scroll_button',url:$('hiker://empty#noLoading#').lazyRule(function(v){putMyVar('acfun_a15_search_kind',v);refreshPage(false);return'hiker://empty'},x[0]),extra:{lineVisible:false}})})(kinds[k]);d.push({col_type:'line'})}if(q){var list=typedSearch(kind,q,P());if(kind==='comic')for(var i=0;i<list.length;i++)comicCard(d,list[i]);else if(kind==='dynamic')for(var j=0;j<list.length;j++)dynamicCard(d,list[j]);else if(kind==='fiction'||kind==='audio')for(var n=0;n<list.length;n++)fictionCard(d,list[n],kind);else for(var v=0;v<list.length;v++)videoCard(d,list[v],false);if(!list.length&&P()===1)d.push({title:'没有搜索到结果',desc:'类型：'+kind+' · 关键词：'+q,col_type:'long_text',url:'hiker://empty'})}setResult(d)};
ac.category=function(){var d=[];setPageTitle('分类与筛选');top(d);filters(d);d.push({title:'当前栏目：'+section(),desc:'选择后返回首页即可看到结果。',col_type:'long_text',url:'hiker://home@ACFun'});setResult(d)};

function fictionObj(id){var seed={};try{seed=JSON.parse(getItem('acfun_a15_fiction_seed_'+S(id),'{}'))||{}}catch(e){}var api=apiObject('fiction/base/info',[{fictionId:N(id)},{id:N(id)},{bookId:N(id)}],['POST','GET'],'fiction|'+id),o=copy(seed);for(var k in api)if(api[k]!==undefined&&api[k]!==null)o[k]=api[k];return o}
function chapterRows(root){var out=[],seen={},count=0;function walk(v,d){if(v===undefined||v===null||d>9||count>10000)return;if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],d+1);return}if(typeof v!=='object')return;count++;var id=pick(v,['chapterId','fictionChapterId','id'],''),title=pick(v,['chapterTitle','chapterName','title','name'],'');if(id&&!seen[S(id)]){seen[S(id)]=1;out.push({id:S(id),title:S(title||('第 '+(out.length+1)+' 章')),raw:v})}for(var k in v)if(v[k]&&typeof v[k]==='object')walk(v[k],d+1)}walk(root,0);return out}
function chapterObj(fid,cid){return apiObject('fiction/base/chapterInfo',[{fictionId:N(fid),chapterId:N(cid)},{chapterId:N(cid)},{fictionId:N(fid),fictionChapterId:N(cid)}],['POST','GET'],'chapter|'+fid+'|'+cid)}
function payload(root){var texts=[],audios=[],images=[],seenT={},seenA={},seenI={},count=0;var base=S(pick(root,['playbackDomain','audioDomain','mediaDomain'],'')||''),auth=S(pick(root,['playbackAuthKey','authKey','auth_key'],'')||'');function add(a,seen,s){s=S(s).trim();if(s&&!seen[s]){seen[s]=1;a.push(s)}}function walk(v,key,d){if(v===undefined||v===null||d>11||count>16000)return;if(typeof v==='string'){var s=v.trim(),low=S(key).toLowerCase();if(/content|text|body|paragraph/.test(low)&&s&&!/^https?:\/\//i.test(s)&&s.length>1)add(texts,seenT,s);if(/audio|sourcepath|playpath|audiourl|url|path/.test(low)&&(/\.(?:mp3|m4a|aac|wav|ogg|flac|m3u8)(?:[?#]|$)/i.test(s)||/audio|sourcepath|playpath/.test(low))){var u=join(base,s);if(auth&&u&&u.indexOf('auth_key=')<0&&u.indexOf('authKey=')<0)u=u+(u.indexOf('?')>=0?'&':'?')+'auth_key='+encodeURIComponent(auth);add(audios,seenA,u)}if(/image|img|picture|pic/.test(low)&&(/^(https?:)?\/\//i.test(s)||/\.(?:png|jpe?g|webp|gif)(?:[?#]|$)/i.test(s)))add(images,seenI,join(S(pick(root,['imgDomain','imageDomain'],'')||''),s));return}if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],key,d+1);return}if(typeof v!=='object')return;count++;for(var k in v)walk(v[k],k,d+1)}walk(root,'',0);return{texts:texts,audios:audios,images:images}}
function playAudio(url){return S(url)+'#isMusic=true#'}
function fictionDetail(id,mode){var obj=fictionObj(id),info=fictionInfo(obj);if(!info.id)info.id=S(id);setPageTitle(info.title);var d=[],pic=info.img?ac.image(info.img):I(mode==='audio'?'audio':'novel');d.push({title:info.title,desc:[info.author,mode==='audio'?'有声':'小说'].filter(function(v){return!!v}).join(' · '),pic_url:pic,img:pic,col_type:'movie_1_left_pic',url:'hiker://empty',extra:{lineVisible:false}});if(info.desc)d.push({title:html(info.desc),col_type:'rich_text',url:'hiker://empty',extra:{textSize:14,lineVisible:false}});var p=payload(obj);if(mode==='audio'&&p.audios.length)d.push({title:'▶ 播放作品音频',desc:p.audios.length>1?'检测到备用音频源':'',col_type:'text_1',url:playAudio(p.audios[0]),extra:{lineVisible:false}});var ch=chapterRows(obj);d.push({col_type:'line'});d.push({title:'章节目录',desc:ch.length+' 章',col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}});for(var i=0;i<ch.length;i++)d.push({title:ch[i].title,col_type:'text_2',url:'hiker://page/acfun_detail?rule=ACFun&simple=true&content_kind=fiction_chapter&fiction_id='+encodeURIComponent(info.id)+'&fiction_chapter_id='+encodeURIComponent(ch[i].id)+'&fiction_chapter_title='+encodeURIComponent(ch[i].title)+'&fiction_mode='+mode+'#noRecordHistory#',extra:{lineVisible:false}});if(!ch.length)d.push({title:'暂未解析到章节目录',col_type:'text_center_1',url:'hiker://empty'});setResult(d)}
function fictionChapter(fid,cid,mode){var obj=chapterObj(fid,cid),p=payload(obj),title=param('fiction_chapter_title')||S(pick(obj,['chapterTitle','chapterName','title','name'],'章节'));setPageTitle(title);var d=[];if(mode==='audio'&&p.audios.length)d.push({title:'▶ 播放本章音频',desc:p.audios.length>1?'含备用音频源':'',col_type:'text_1',url:playAudio(p.audios[0]),extra:{lineVisible:false}});if(p.texts.length)d.push({title:html(p.texts.join('\n\n')),col_type:'rich_text',url:'hiker://empty',extra:{textSize:16,lineVisible:false}});for(var i=0;i<p.images.length;i++){var im=ac.image(p.images[i]);if(im)d.push({title:'',pic_url:im,img:im,col_type:'pic_1_full',url:'hiker://empty',extra:{lineVisible:false}})}if(!d.length)d.push({title:mode==='audio'?'本章暂未解析到音频':'本章暂未解析到正文',desc:S(getItem('acfun_a15_last_error','')).slice(0,600),col_type:'long_text',url:'hiker://empty'});setResult(d)}
function dynamicDetail(id){var seed={};try{seed=JSON.parse(getItem('acfun_a15_dynamic_seed_'+S(id),'{}'))||{}}catch(e){}var api=apiObject('community/dynamic/dynamicInfo',[{dynamicId:N(id)},{id:N(id)}],['GET','POST'],'dynamic|'+id),obj=copy(seed);for(var k in api)if(api[k]!==undefined&&api[k]!==null)obj[k]=api[k];var info=dynamicInfo(obj),d=[];setPageTitle('社区动态');if(info.author)d.push({title:info.author,col_type:'text_1',url:'hiker://empty'});if(info.title)d.push({title:html(info.title),col_type:'rich_text',url:'hiker://empty',extra:{textSize:16,lineVisible:false}});var p=payload(obj);for(var i=0;i<p.images.length;i++){var im=ac.image(p.images[i]);if(im)d.push({title:'',pic_url:im,img:im,col_type:'pic_1_full',url:'hiker://empty',extra:{lineVisible:false}})}if(!d.length)d.push({title:'动态详情暂未解析完整',col_type:'long_text',url:'hiker://empty'});setResult(d)}
ac.detail=function(){var p=typeof MY_PARAMS==='object'?MY_PARAMS:{},kind=S(p.content_kind||param('content_kind')||'');if(kind==='fiction'){var id=S(p.fiction_id||param('fiction_id')||param('content_id'));return fictionDetail(id,S(p.fiction_mode||param('fiction_mode')||'fiction'))}if(kind==='fiction_chapter'){return fictionChapter(S(p.fiction_id||param('fiction_id')),S(p.fiction_chapter_id||param('fiction_chapter_id')),S(p.fiction_mode||param('fiction_mode')||'fiction'))}if(kind==='dynamic')return dynamicDetail(S(p.dynamic_id||param('dynamic_id')||param('content_id')));return typeof stableDetail==='function'?stableDetail.call(ac):setResult([{title:'详情不可用',col_type:'long_text',url:'hiker://empty'}])};

var stableDiag=ac.diag;
ac.diag=function(){var d=[];setPageTitle('ACFun 资源诊断');d.push({title:'运行状态',desc:'版本：2026.08.23-v0.6.0-alpha15\n模式：clean-rebase-stable049\nHost：'+S(getItem('acfun_good_host','')||ac.frontendBase||'')+'\nToken：'+(getItem('acfun_token','')?'YES':'NO'),col_type:'long_text',url:'hiker://empty'});d.push({title:'当前栏目',desc:section()+'\n最近路由：'+S(getItem('acfun_a15_last_route','暂无'))+'\n最近错误：'+S(getItem('acfun_a15_last_error','无')).slice(0,800),col_type:'long_text',url:'hiker://empty'});d.push({title:'图片链',desc:'原始封面：'+S(getItem('acfun_a15_cover_sample','暂无')).slice(0,600)+'\n渲染地址：'+S(getItem('acfun_a15_cover_rendered','暂无')).slice(0,800)+'\nimgDomain：'+S(getItem('acfun_img_domain','')||getMyVar('acfun_v042_img_domain','')),col_type:'long_text',url:'hiker://empty'});d.push({title:'最近真实 API',desc:'Last='+S(getItem('acfun_last_api','暂无'))+'\nHTTP='+S(getItem('acfun_last_status',''))+'\nDirectErr='+S(getItem('acfun_last_direct_error','')).slice(0,700),col_type:'long_text',url:'hiker://empty'});d.push({title:'复制诊断摘要',col_type:'text_1',url:'copy://ACFun 2026.08.23-v0.6.0-alpha15 | '+S(getItem('acfun_a15_last_route','no-route'))+' | '+S(getItem('acfun_a15_last_error','no-error')).slice(0,220)});d.push({title:'清空诊断并刷新',col_type:'text_1',url:$('hiker://empty#noLoading#').lazyRule(function(){['acfun_a15_last_route','acfun_a15_last_error','acfun_a15_cover_sample','acfun_a15_cover_rendered'].forEach(function(k){clearItem(k)});refreshPage(false);return'hiker://empty'})});setResult(d)};

ac.build='2026.08.23-v0.6.0-alpha15';ac.runtimeMode='clean-rebase-stable049';try{setItem('acfun_test_runtime','0.6.0-alpha15 clean rebase');setItem('acfun_a15_loaded','1')}catch(e){}
})();
