// ACFun v0.4.7 - APP source taxonomy / zones / comics / short feed
(function(){
if(typeof ac!=='object')throw new Error('ACFun core missing');
ac.build='2026.08.20-v0.4.7';
ac.runtimeMode='app-source-047';
try{if(!getItem('acfun_migrated_047','')){['acfun_native_station_featured','acfun_native_station_lifan','acfun_native_zone_anime','acfun_native_zone_video','acfun_native_comic_station','acfun_short_load_type'].forEach(function(k){try{clearMyVar(k);}catch(e){}});try{if(typeof ac.__v042ClearDataCache==='function')ac.__v042ClearDataCache();}catch(e0){}setItem('acfun_migrated_047','1');}}catch(e){}
var oldDetail=ac.detail;
ac.__v047Sections=[{key:'featured',name:'精选'},{key:'comic',name:'漫画'},{key:'anime',name:'动漫'},{key:'video',name:'视频'},{key:'short',name:'短视频'},{key:'lifan',name:'里番'}];
ac.__v047Sorts=[{name:'全部',value:'0'},{name:'最新上传',value:'1'},{name:'最多观看',value:'2'},{name:'最多点赞',value:'3'}];
ac.__v047ShortTabs=[{name:'同城',value:'1'},{name:'关注',value:'2'},{name:'最新',value:'3'},{name:'最热',value:'4'}];
ac.__v047Internal=function(s){return /(?:测试|test|comicsclass|ces\d*|罗峰测试|竖版|竖横|横滑|六宫格|四宫格|两格|专题\d|^2026\d+)/i.test(String(s||''));};
ac.__v047Sel=function(n,on){return on?'““””<b><font color="#E0A800">'+n+'</font></b>':n;};
ac.__v047Section=function(){var s=String(getMyVar('acfun_native_section','featured')||'featured');for(var i=0;i<ac.__v047Sections.length;i++)if(ac.__v047Sections[i].key===s)return s;return 'featured';};
ac.__v047Sort=function(){return String(getMyVar('acfun_native_sort','1')||'1');};
ac.__v047Read=function(k,ttl,stale){return typeof ac.__v042Read==='function'?ac.__v042Read('v047|'+k,ttl,stale):{hit:false,fresh:false,stale:false,data:null};};
ac.__v047Write=function(k,v){try{if(typeof ac.__v042Write==='function')return ac.__v042Write('v047|'+k,v);}catch(e){}return false;};
ac.__v047Arr=function(v){if(Array.isArray(v))return v;if(!v||typeof v!=='object')return [];var ks=['data','list','items','records','rows','stations','stationList','classTypeList','classifyList','videoList','videos','comicsBaseList','comicsList','content'];for(var i=0;i<ks.length;i++)if(Array.isArray(v[ks[i]]))return v[ks[i]];for(var j=0;j<ks.length;j++)if(v[ks[j]]&&typeof v[ks[j]]==='object'){var a=ac.__v047Arr(v[ks[j]]);if(a.length)return a;}return [];};
ac.__v047ReqList=function(path,params,key){var ttl=Number(getItem('acfun_page_cache_seconds','300'))||300,stale=Number(getItem('acfun_stale_cache_seconds','3600'))||3600,c=ac.__v047Read(key,ttl,stale);if((c.fresh||(getItem('acfun_instant_switch','1')==='1'&&c.stale))&&Array.isArray(c.data))return c.data;var list=[];try{var d=ac.__v043Api(path,params||{},{timeout:1200,maxAttempts:2});list=ac.flattenVideos?ac.flattenVideos(d):ac.__v047Arr(d);if(!list.length)list=ac.__v047Arr(d);}catch(e){try{setItem('acfun_last_list_error',String(e.message||e));}catch(e0){}}if(list.length){ac.__v047Write(key,list);return list;}return c.hit&&Array.isArray(c.data)?c.data:[];};

// 精选/里番：APP station/stations；restricted=0/1。
ac.__v047Stations=function(restricted){var r=restricted?1:0,key='stations|'+r,c=ac.__v047Read(key,21600,172800);if(c.stale&&Array.isArray(c.data)&&c.data.length)return c.data;var out=[];try{var d=ac.__v043Api('station/stations',{classifyId:4,page:1,pageSize:30,restricted:r},{timeout:1200,maxAttempts:2}),a=ac.__v047Arr(d);for(var i=0;i<a.length;i++){var x=a[i]||{},id=String(ac.pick(x,['stationId','stationID','id'],'')||''),name=String(ac.pick(x,['stationName','stationTitle','title','name'],'')||'');if(id&&name&&!ac.__v047Internal(name))out.push({id:id,name:name,raw:x});}}catch(e){try{setItem('acfun_last_station_error',String(e.message||e));}catch(e0){}}if(out.length)ac.__v047Write(key,out);return out.length?out:(c.hit&&Array.isArray(c.data)?c.data:[]);};
ac.__v047Station=function(restricted){var a=ac.__v047Stations(restricted),k=restricted?'acfun_native_station_lifan':'acfun_native_station_featured',sel=String(getMyVar(k,'')||''),hit=null;for(var i=0;i<a.length;i++)if(String(a[i].id)===sel){hit=a[i];break;}if(!hit&&a.length){hit=a[0];putMyVar(k,String(hit.id));}return hit;};
ac.__v047StationList=function(page,restricted){page=Number(page||1);var st=ac.__v047Station(restricted);if(!st)return [];var size=Number(getItem('acfun_page_size','8'))||8,sort=Number(ac.__v047Sort());if(page===1&&st.raw&&Array.isArray(st.raw.videoList)&&st.raw.videoList.length)return st.raw.videoList.slice(0,size);return ac.__v047ReqList('station/getStationMore',{stationId:(/^\d+$/.test(st.id)?Number(st.id):st.id),page:page,pageNum:page,pageSize:size,sortType:sort},'station-more|'+restricted+'|'+st.id+'|'+sort+'|'+page);};

// 动漫/视频：分类完全来自 APP classTypeList(type=2/4)。
ac.__v047Catalog=function(kind){kind=kind==='video'?'video':'anime';var type=kind==='video'?4:2,key='catalog|'+kind,c=ac.__v047Read(key,21600,172800);if(c.stale&&Array.isArray(c.data)&&c.data.length)return c.data;var out=[];try{var d=ac.__v043Api('video/classTypeList',{type:type,restricted:0},{timeout:1100,maxAttempts:2}),a=ac.__v047Arr(d);for(var i=0;i<a.length;i++){var x=a[i]||{},id=String(ac.pick(x,['classifyId','classTypeId','videoTypeId','typeId','id'],'')||''),name=String(ac.pick(x,['classifyTitle','classTypeTitle','classifyName','classTypeName','videoTypeName','title','name'],'')||'');if(id&&name&&!ac.__v047Internal(name))out.push({id:id,name:name,raw:x});}}catch(e){try{setItem('acfun_last_catalog_error',String(e.message||e));}catch(e0){}}if(!out.length&&kind==='video'&&ac.__v045VideoGroups)for(var j=0;j<ac.__v045VideoGroups.length;j++)out.push({id:String(ac.__v045VideoGroups[j].id),name:ac.__v045VideoGroups[j].name});if(!out.length&&kind==='anime')out.push({id:'2',name:'动漫'});if(out.length)ac.__v047Write(key,out);return out.length?out:(c.hit&&Array.isArray(c.data)?c.data:[]);};
ac.__v047Class=function(kind){var a=ac.__v047Catalog(kind),k=kind==='video'?'acfun_native_video_class':'acfun_native_anime_class',sel=String(getMyVar(k,'')||''),hit=null;for(var i=0;i<a.length;i++)if(String(a[i].id)===sel){hit=a[i];break;}if(!hit&&a.length){hit=a[0];putMyVar(k,String(hit.id));}return hit;};

// APP 的“标签”是 Zone：getZoneListByClassifyId -> queryVideoByZone。
ac.__v047Zones=function(cls){if(!cls||!cls.id)return [];var id=String(cls.id),key='zones|'+id,c=ac.__v047Read(key,21600,172800);if(c.stale&&Array.isArray(c.data))return c.data;var out=[],seen={};try{var d=ac.__v043Api('video/getZoneListByClassifyId',{classifyId:(/^\d+$/.test(id)?Number(id):id)},{timeout:1000,maxAttempts:2}),a=ac.__v047Arr(d);for(var i=0;i<a.length;i++){var x=a[i]||{},zid=String(ac.pick(x,['zoneId','id'],'')||''),name=String(ac.pick(x,['zoneTitle','zoneName','title','name'],'')||'');if(zid&&name&&!ac.__v047Internal(name)&&!seen[zid]){seen[zid]=1;out.push({id:zid,name:name,mode:'zone'});}}}catch(e){}if(!out.length)try{var d2=ac.__v043Api('video/tags/getTagsZ',{videoTypeId:(/^\d+$/.test(id)?Number(id):id),classifyId:(/^\d+$/.test(id)?Number(id):id),restricted:0},{timeout:1000,maxAttempts:1}),b=ac.__v047Arr(d2);for(var j=0;j<b.length;j++){var nm=String(ac.pick(b[j],['videoTagName','videoTagValue','tagsTitle','tagTitle','tagName','name','title'],'')||'');if(nm&&!ac.__v047Internal(nm)&&!seen[nm]){seen[nm]=1;out.push({id:nm,name:nm,mode:'tag'});}}}catch(e2){}if(out.length)ac.__v047Write(key,out);return out;};
ac.__v047Zone=function(kind,cls){var a=ac.__v047Zones(cls),k=kind==='video'?'acfun_native_zone_video':'acfun_native_zone_anime',sel=String(getMyVar(k,'')||'');for(var i=0;i<a.length;i++)if(String(a[i].id)===sel)return a[i];return null;};
ac.__v047CatalogList=function(page,kind){page=Number(page||1);var cls=ac.__v047Class(kind);if(!cls)return [];var size=Number(getItem('acfun_page_size','8'))||8,sort=Number(ac.__v047Sort()),zone=ac.__v047Zone(kind,cls),cid=(/^\d+$/.test(cls.id)?Number(cls.id):cls.id);if(zone&&zone.mode==='zone')return ac.__v047ReqList('video/queryVideoByZone',{page:page,pageNum:page,pageSize:size,zoneId:(/^\d+$/.test(zone.id)?Number(zone.id):zone.id),classifyId:cid,sortType:sort},'zone|'+kind+'|'+cls.id+'|'+zone.id+'|'+sort+'|'+page);if(zone){var l=ac.__v047ReqList('video/queryVideoByTag',{page:page,pageNum:page,pageSize:size,tagTitle:zone.name,tagsTitle:zone.name,classifyId:cid,sortType:sort},'tag|'+kind+'|'+cls.id+'|'+zone.name+'|'+sort+'|'+page);if(l.length)return l;return ac.__v047ReqList('video/tagTitleList',{page:page,pageNum:page,pageSize:size,tagsTitle:zone.name,classifyId:cid,sortType:sort,restricted:0},'tag2|'+kind+'|'+cls.id+'|'+zone.name+'|'+sort+'|'+page);}return ac.__v047ReqList('video/getByClassify',{classifyId:cid,page:page,pageNum:page,pageSize:size,sortType:sort,restricted:0},'class|'+kind+'|'+cls.id+'|'+sort+'|'+page);};

// 短视频 Feed：video/list 是 APP 短视频接口。
ac.__v047ShortList=function(page){page=Number(page||1);var lt=String(getMyVar('acfun_short_load_type','3')||'3');return ac.__v047ReqList('video/list',{page:page,pageNum:page,pageSize:15,loadType:Number(lt)},'short|'+lt+'|'+page);};

// 漫画：直接使用 APP 返回的顶层 station，截图不再作为白名单。
ac.__v047ComicStations=function(){var key='comic-stations',c=ac.__v047Read(key,21600,172800);if(c.stale&&Array.isArray(c.data)&&c.data.length)return c.data;var out=[],seen={};try{var d=ac.__v043Api('comics/station/getComicsStations',{}, {timeout:1200,maxAttempts:2}),a=ac.__v047Arr(d);for(var i=0;i<a.length;i++){var x=a[i]||{},id=String(ac.pick(x,['stationId','comicsStationId','id'],'')||''),name=String(ac.pick(x,['stationName','stationTitle','name','title'],'')||'');if(id&&name&&!ac.__v047Internal(name)&&!seen[id]){seen[id]=1;out.push({id:id,name:name,raw:x});}}}catch(e){try{setItem('acfun_last_comic_station_error',String(e.message||e));}catch(e0){}}if(out.length)ac.__v047Write(key,out);return out.length?out:(c.hit&&Array.isArray(c.data)?c.data:[]);};
ac.__v047ComicStation=function(){var a=ac.__v047ComicStations(),sel=String(getMyVar('acfun_native_comic_station','')||''),hit=null;for(var i=0;i<a.length;i++)if(String(a[i].id)===sel){hit=a[i];break;}if(!hit&&a.length){hit=a[0];putMyVar('acfun_native_comic_station',String(hit.id));}return hit;};
ac.__v047ComicList=function(page){page=Number(page||1);var st=ac.__v047ComicStation();if(!st)return [];var size=Number(getItem('acfun_page_size','8'))||8,sort=Number(ac.__v047Sort()),key='comic-list|'+st.id+'|'+sort+'|'+page,c=ac.__v047Read(key,300,3600);if(c.fresh&&Array.isArray(c.data))return c.data;var list=[];if(page===1&&st.raw&&Array.isArray(st.raw.comicsBaseList)&&st.raw.comicsBaseList.length)list=st.raw.comicsBaseList.slice(0,size);if(!list.length)try{var d=ac.__v043Api('comics/station/getStationComicsMore',{stationId:(/^\d+$/.test(st.id)?Number(st.id):st.id),page:page,pageNum:page,pageSize:size,sortType:sort},{timeout:1200,maxAttempts:2});list=ac.__v047Arr(d);}catch(e){try{setItem('acfun_last_comic_list_error',String(e.message||e));}catch(e0){}}if(list.length){ac.__v047Write(key,list);return list;}return c.hit&&Array.isArray(c.data)?c.data:[];};
ac.__v047ComicInfo=function(x){x=x||{};return {id:String(ac.pick(x,['comicsId','comicId','id'],'')||''),title:String(ac.pick(x,['comicsTitle','comicTitle','title','name'],'未命名漫画')||''),img:String(ac.__v042FirstMedia?(ac.__v042FirstMedia(x.coverImg)||ac.__v042FirstMedia(x.cover)||ac.__v042FirstMedia(x.comicsCover)||ac.__v042FirstMedia(x.img)||ac.__v042FirstMedia(x.image)):ac.pick(x,['coverImg','cover','img','image'],'')||''),desc:String(ac.pick(x,['authorName','nickName','info','description','desc'],'')||'')};};
ac.__v047ComicUrl=function(){return 'hiker://page/acfun_detail?rule=ACFun&simple=true#noRecordHistory#';};
ac.__v047ComicImage=function(domain,p){p=String(p||'').trim();domain=String(domain||'').trim();if(!p)return '';if(/^https?:\/\//i.test(p))return p;if(domain)return domain.replace(/\/+$/,'')+'/'+p.replace(/^\/+/, '');return p;};
ac.__v047ComicDetail=function(id,title){var d=[],data=null;try{data=ac.__v043Api('comics/base/info',{comicsId:(/^\d+$/.test(String(id))?Number(id):id)},{timeout:1300,maxAttempts:2});}catch(e){setResult([{title:'漫画详情加载失败',desc:String(e.message||e),col_type:'long_text',url:'hiker://empty'}]);return;}data=data||{};var ci=ac.__v047ComicInfo(data),chap=Array.isArray(data.chapterList)?data.chapterList:[],domain=String(ac.pick(data,['domain','imgDomain'],'')||'');setPageTitle(ci.title||title||'漫画详情');d.push({title:'<b>'+String(ci.title||title||'漫画')+'</b>',desc:String(ac.pick(data,['authorName','nickName'],'')||'')+'\n'+String(ac.pick(data,['info','description','desc'],'')||''),img:ac.image(ci.img),col_type:'movie_1_left_pic',url:'hiker://empty'});if(chap.length)d.push({title:'章节 · '+chap.length,col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}});for(var i=0;i<chap.length;i++){var x=chap[i]||{},cid=String(ac.pick(x,['chapterId','id'],'')||''),ct=String(ac.pick(x,['chapterTitle','title','name'],'第'+(i+1)+'话')||'');if(cid)d.push({title:ct,col_type:'text_2',url:ac.__v047ComicUrl(),extra:{inheritTitle:false,pageTitle:ct,comics_id:String(id),comics_title:ci.title,comic_chapter_id:cid,comic_chapter_title:ct,comic_domain:domain}});}setResult(d);};
ac.__v047ComicReader=function(comicsId,chapterId,chapterTitle){var d=[],data=null;try{data=ac.__v043Api('comics/base/chapterInfo',{chapterId:(/^\d+$/.test(String(chapterId))?Number(chapterId):chapterId)},{timeout:1400,maxAttempts:2});}catch(e){setResult([{title:'章节加载失败',desc:String(e.message||e),col_type:'long_text',url:'hiker://empty'}]);return;}data=data||{};var title=String(ac.pick(data,['chapterTitle'],'')||chapterTitle||'漫画章节'),domain=String(ac.pick(data,['domain'],'')||''),imgs=Array.isArray(data.imgList)?data.imgList:[];setPageTitle(title);if(data.canWatch===false){setResult([{title:'当前章节暂不可阅读',desc:String(ac.pick(data,['info'],'')||'需要权限或购买'),col_type:'long_text',url:'hiker://empty'}]);return;}for(var i=0;i<imgs.length;i++){var u=ac.__v047ComicImage(domain,imgs[i]);if(u)d.push({title:'',img:ac.image?ac.image(u):u,col_type:'pic_1_full',url:'hiker://empty',extra:{lineVisible:false}});}if(!imgs.length)d.push({title:'章节没有返回图片',col_type:'long_text',url:'hiker://empty'});setResult(d);};

ac.__v047Top=function(d){var cur=ac.__v047Section();for(var i=0;i<ac.__v047Sections.length;i++)(function(x){d.push({title:ac.__v047Sel(x.name,cur===x.key),col_type:'flex_button',url:$('hiker://empty#noLoading#').lazyRule(function(k){putMyVar('acfun_native_section',k);putMyVar('acfun_native_sort','1');refreshPage(false);return 'hiker://empty';},x.key)});})(ac.__v047Sections[i]);};
ac.__v047SortBar=function(d){var cur=ac.__v047Sort();for(var i=0;i<ac.__v047Sorts.length;i++)(function(x){d.push({title:ac.__v047Sel(x.name,cur===x.value),col_type:'text_4',url:$('hiker://empty#noLoading#').lazyRule(function(v){putMyVar('acfun_native_sort',v);refreshPage(false);return 'hiker://empty';},x.value)});})(ac.__v047Sorts[i]);};
ac.__v047Bars=function(d){var s=ac.__v047Section();if(s==='featured'||s==='lifan'){var r=s==='lifan'?1:0,a=ac.__v047Stations(r),k=r?'acfun_native_station_lifan':'acfun_native_station_featured',sel=String(getMyVar(k,'')||'');if(!sel&&a.length)sel=String(a[0].id);for(var i=0;i<a.length;i++)(function(x){d.push({title:ac.__v047Sel(x.name,sel===String(x.id)),col_type:'flex_button',url:$('hiker://empty#noLoading#').lazyRule(function(v,key){putMyVar(key,String(v));refreshPage(false);return 'hiker://empty';},x.id,k)});})(a[i]);ac.__v047SortBar(d);return;}if(s==='anime'||s==='video'){var a2=ac.__v047Catalog(s),k2=s==='video'?'acfun_native_video_class':'acfun_native_anime_class',sel2=String(getMyVar(k2,'')||'');if(!sel2&&a2.length)sel2=String(a2[0].id);for(var j=0;j<a2.length;j++)(function(x){d.push({title:ac.__v047Sel(x.name,sel2===String(x.id)),col_type:'flex_button',url:$('hiker://empty#noLoading#').lazyRule(function(v,key,zkey){putMyVar(key,String(v));clearMyVar(zkey);refreshPage(false);return 'hiker://empty';},x.id,k2,s==='video'?'acfun_native_zone_video':'acfun_native_zone_anime')});})(a2[j]);var cls=ac.__v047Class(s),zones=ac.__v047Zones(cls),zk=s==='video'?'acfun_native_zone_video':'acfun_native_zone_anime',zs=String(getMyVar(zk,'')||'');if(zones.length){d.push({title:ac.__v047Sel('全部',!zs),col_type:'text_4',url:$('hiker://empty#noLoading#').lazyRule(function(key){clearMyVar(key);refreshPage(false);return 'hiker://empty';},zk)});for(var z=0;z<zones.length;z++)(function(x){d.push({title:ac.__v047Sel(x.name,zs===String(x.id)),col_type:'text_4',url:$('hiker://empty#noLoading#').lazyRule(function(v,key){putMyVar(key,String(v));refreshPage(false);return 'hiker://empty';},x.id,zk)});})(zones[z]);}ac.__v047SortBar(d);return;}if(s==='comic'){var cs=ac.__v047ComicStations(),selc=String(getMyVar('acfun_native_comic_station','')||'');if(!selc&&cs.length)selc=String(cs[0].id);for(var c=0;c<cs.length;c++)(function(x){d.push({title:ac.__v047Sel(x.name,selc===String(x.id)),col_type:'flex_button',url:$('hiker://empty#noLoading#').lazyRule(function(v){putMyVar('acfun_native_comic_station',String(v));refreshPage(false);return 'hiker://empty';},x.id)});})(cs[c]);ac.__v047SortBar(d);return;}if(s==='short'){var st=String(getMyVar('acfun_short_load_type','3')||'3');for(var q=0;q<ac.__v047ShortTabs.length;q++)(function(x){d.push({title:ac.__v047Sel(x.name,st===x.value),col_type:'flex_button',url:$('hiker://empty#noLoading#').lazyRule(function(v){putMyVar('acfun_short_load_type',String(v));refreshPage(false);return 'hiker://empty';},x.value)});})(ac.__v047ShortTabs[q]);}};
ac.__v047Utility=function(d){[['收藏','acfun_favorites'],['历史','acfun_history'],['设置','acfun_settings']].forEach(function(t){d.push({title:t[0],col_type:'text_4',url:'hiker://page/'+t[1]+'?rule=ACFun&simple=true#noRecordHistory#',extra:{inheritTitle:false,pageTitle:t[0]}});});d.push({title:'↻ 刷新',col_type:'text_4',url:$('hiker://empty#noLoading#').lazyRule(function(){putMyVar('acfun_native_refresh',String(Date.now()));refreshPage(false);return 'hiker://empty';})});};
ac.home=function(){var d=[],page=typeof MY_PAGE==='undefined'?1:Number(MY_PAGE||1),s=ac.__v047Section();if(page===1){d.push({title:'搜索',desc:'搜索视频 / UP / 标签',col_type:'input',url:$.toString(function(){if(!input)return 'hiker://empty';return 'hiker://search?s='+encodeURIComponent(input)+'&rule=ACFun';}),extra:{defaultValue:''}});ac.__v047Top(d);ac.__v047Bars(d);ac.__v047Utility(d);}var list=[];try{if(s==='featured')list=ac.__v047StationList(page,0);else if(s==='lifan')list=ac.__v047StationList(page,1);else if(s==='comic')list=ac.__v047ComicList(page);else if(s==='short')list=ac.__v047ShortList(page);else list=ac.__v047CatalogList(page,s);}catch(e){try{setItem('acfun_last_home_error',String(e.message||e));}catch(e0){}}if(s==='comic'){for(var i=0;i<list.length;i++){var ci=ac.__v047ComicInfo(list[i]);if(ci.id)d.push({title:ci.title,desc:ci.desc,img:ac.image(ci.img),col_type:'movie_2',url:ac.__v047ComicUrl(),extra:{inheritTitle:false,pageTitle:ci.title,comics_id:ci.id,comics_title:ci.title,content_kind:'comic'}});}}else for(var j=0;j<list.length;j++)ac.addVideoCard(d,list[j],'movie_2');if(!list.length&&page===1)d.push({title:'暂未获取到内容',desc:'当前分类：'+s+'\n可切换分类或刷新重试。',col_type:'long_text',url:'hiker://empty'});setResult(d);};
ac.detail=function(){var p=(typeof MY_PARAMS==='object'&&MY_PARAMS)||{},chapterId=String(p.comic_chapter_id||''),comicsId=String(p.comics_id||'');if(chapterId)return ac.__v047ComicReader(comicsId,chapterId,String(p.comic_chapter_title||''));if(comicsId)return ac.__v047ComicDetail(comicsId,String(p.comics_title||''));if(typeof oldDetail==='function')return oldDetail.call(ac);setResult([{title:'详情页不可用',col_type:'long_text',url:'hiker://empty'}]);};
})();