/**
 * ACFun 0.6.0-alpha7 / Build 158
 * Interaction rebuild: list-style filter center, direct-play short feed,
 * compact community/fiction filtering.
 */
(function(){
if(typeof ac!=='object')throw new Error('ACFun core missing');
var A='#FF4D4F',M='#8A8A8A',BASE='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/assets/';
var BOOT='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/bootstrap_test_v063.js?v=6300',BVER=6300;
function S(v){return String(v===undefined||v===null?'':v)}
function E(v){return S(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function P(){try{return Math.max(1,Number(MY_PAGE||1)||1)}catch(e){return 1}}
function I(n){return BASE+n+'.svg'}
function nameOf(s){return({featured:'精选',comic:'漫画',anime:'动漫',video:'视频',lifan:'里番',short:'短视频',community:'社区',fiction:'小说',audio:'有声'})[s]||'内容'}
function rich(t,sub){return'<b>'+E(t)+'</b>'+(sub?'  <font color="'+M+'">'+E(sub)+'</font>':'')}
function section(d,t,sub){d.push({title:rich(t,sub||''),col_type:'rich_text',extra:{textSize:15,lineVisible:false}})}
function infoLine(a){return a.filter(function(v){return!!S(v)}).join(' · ')}
function routeView(v){return'hiker://page/acfun_category?rule=ACFun&simple=true&view='+encodeURIComponent(v)+'#noRecordHistory#'}
function state(k,def){var v=S(getMyVar(k,'')||'');if(!v)v=S(getItem('acfun_v060_state_'+k,def||'')||'');if(v)putMyVar(k,v);return v}
function extra(info){info=info||{};var kind=S(info.kind||'video'),x={content_kind:kind,content_id:info.id,pageTitle:info.title,lineVisible:false};if(kind==='comic'){x.comics_id=info.id;x.comics_title=info.title;x.comics_img=info.img}else if(kind==='fiction'){x.fiction_id=info.id;x.fiction_title=info.title;x.fiction_img=info.img}else if(kind==='dynamic'){x.dynamic_id=info.id;x.dynamic_title=info.title}else{x.video_id=info.id;x.video_title=info.title;x.video_img=info.img;x.video_uri=info.uri;x.video_data=JSON.stringify(info.raw||{})}return x}
function selectUrl(title,options,ids,current,key,clearKey,col){
    options=options||[];ids=ids||[];var idx=0;for(var i=0;i<ids.length;i++)if(S(ids[i])===S(current)){idx=i;break}
    return'select://'+JSON.stringify({title:title,options:options,selectedIndex:idx,col:col||1,js:$.toString(function(opts,vals,k,ck){var i=opts.indexOf(input);if(i<0)return;var v=vals[i];if(k==='__section__'){putMyVar('acfun_v050_section',String(v));setItem('acfun_v060_section',String(v))}else{if(v){putMyVar(k,String(v));setItem('acfun_v060_state_'+k,String(v))}else{clearMyVar(k);setItem('acfun_v060_state_'+k,'')}if(ck){clearMyVar(ck);setItem('acfun_v060_state_'+ck,'')}}refreshPage(false)},options,ids,key,clearKey||'')})
}
function selectRow(d,title,value,options,ids,current,key,clearKey){d.push({title:title,desc:value||'请选择',col_type:'text_1',url:selectUrl(title,options,ids,current,key,clearKey,1),extra:{lineVisible:false}})}
function rowNames(rows){var a=[],b=[];for(var i=0;i<(rows||[]).length;i++){a.push(S(rows[i].name));b.push(S(rows[i].id))}return{names:a,ids:b}}
function currentName(rows,id,def){for(var i=0;i<(rows||[]).length;i++)if(S(rows[i].id)===S(id))return S(rows[i].name);return def||''}
function clearCurrentUrl(sec){return $('hiker://empty#noLoading#').lazyRule(function(s){function c(k){clearMyVar(k);setItem('acfun_v060_state_'+k,'')}if(s==='featured')c('acfun_v050_station_featured');else if(s==='lifan')c('acfun_v050_station_lifan');else if(s==='comic')c('acfun_v050_comic_station');else if(s==='anime'){c('acfun_v050_class_anime');c('acfun_v050_tag_anime')}else if(s==='video'){c('acfun_v050_class_video');c('acfun_v050_tag_video')}else if(s==='short'){putMyVar('acfun_v050_short_load_type','2');setItem('acfun_v060_state_acfun_v050_short_load_type','2')}clearMyVar('acfun_v050_sort_'+s);setItem('acfun_v060_sort_'+s,'1');refreshPage(false);return'toast://已恢复默认筛选'},sec)}
function mainIcon(s,on){var n=({featured:'featured',comic:'comic',anime:'anime',video:'video',lifan:'lifan'})[s]||'featured';return I(n+(on?'':'_off'))}
function extIcon(s,on){var n=({community:'community',fiction:'novel',audio:'audio',short:'short'})[s]||'more';return I(n+(on?'':'_off'))}
function setSectionUrl(sec){return $('hiker://empty#noLoading#').lazyRule(function(s){putMyVar('acfun_v050_section',s);setItem('acfun_v060_section',s);refreshPage(false);return'hiker://empty'},sec)}
function top(d){
    d.push({title:'搜索视频、漫画、小说与社区',pic_url:I('search'),img:I('search'),col_type:'text_icon',url:'hiker://page/acfun_search_center?rule=ACFun&simple=true#noRecordHistory#',extra:{inheritTitle:false,pageTitle:'ACFun 全站搜索',lineVisible:false}});
    var cur=ac.__v050Section();ac.__v060Sections.forEach(function(x){d.push({title:x.name,pic_url:mainIcon(x.key,cur===x.key),img:mainIcon(x.key,cur===x.key),col_type:'icon_5',url:setSectionUrl(x.key),extra:{lineVisible:false}})});
    if(getItem('acfun_v060_show_extensions','1')==='1')[{key:'short',name:'短视频'},{key:'community',name:'社区'},{key:'fiction',name:'小说'},{key:'audio',name:'有声'}].forEach(function(x){d.push({title:x.name,pic_url:extIcon(x.key,cur===x.key),img:extIcon(x.key,cur===x.key),col_type:'icon_small_4',url:x.key==='short'?setSectionUrl('short'):routeView(x.key),extra:{inheritTitle:false,pageTitle:x.name,lineVisible:false}})});
    if(getItem('acfun_v060_show_personal','1')==='1')[{name:'筛选',icon:'filter',page:'acfun_category'},{name:'收藏',icon:'favorite_off',page:'acfun_favorites'},{name:'历史',icon:'history_off',page:'acfun_history'},{name:'设置',icon:'settings_off',page:'acfun_settings'}].forEach(function(x){d.push({title:x.name,pic_url:I(x.icon),img:I(x.icon),col_type:'icon_small_4',url:'hiker://page/'+x.page+'?rule=ACFun&simple=true#noRecordHistory#',extra:{inheritTitle:false,pageTitle:x.name,lineVisible:false}})})
}
function videoCard(d,x,col){var info=ac.itemInfo(x),m=[];if(!info.id)return;info.kind='video';if(info.watch)m.push('▶ '+ac.fmtNum(info.watch));if(info.like)m.push('♥ '+ac.fmtNum(info.like));if(info.duration)m.push(info.duration);if(!m.length&&info.author)m.push(info.author);d.push({title:info.title||('视频 '+info.id),desc:m.join('  '),pic_url:ac.image(info.img),img:ac.image(info.img),url:ac.__v060a4Route(info),col_type:col||getItem('acfun_v060_video_layout','movie_2'),extra:extra(info)})}
function shortCard(d,x){var info=ac.itemInfo(x),m=[];if(!info.id)return;if(info.author)m.push(info.author);if(info.watch)m.push('▶ '+ac.fmtNum(info.watch));if(info.duration)m.push(info.duration);d.push({title:info.title||'短视频',desc:m.join(' · '),pic_url:ac.image(info.img),img:ac.image(info.img),col_type:'movie_3',url:$('hiker://empty').lazyRule(function(id,raw,uri,boot,ver){try{require(boot,{headers:{'Cache-Control':'no-cache'}},ver);ACFunBoot.loadOnly();return ac.play(id,raw,uri)}catch(e){return'toast://播放失败：'+String(e.message||e)}},info.id,JSON.stringify(info.raw||{}),info.uri||'',BOOT,BVER),extra:extra(info)})}
function comicCard(d,x){var info=ac.__v060a4ComicInfo(x);if(!info.id)return;d.push({title:info.title,desc:infoLine([info.author,info.desc]),pic_url:ac.image(info.img),img:ac.image(info.img),url:ac.__v060a4Route(info),col_type:'movie_3',extra:extra(info)})}
function fictionCard(d,x){var info=ac.__v060a4FictionInfo(x);if(!info.id)return;d.push({title:info.title,desc:infoLine([info.author,info.status]),pic_url:ac.image(info.img),img:ac.image(info.img),url:ac.__v060a4Route(info),col_type:'movie_3',extra:extra(info)})}
function dynamicCard(d,x){var info=ac.__v060a4DynamicInfo(x);if(!info.id)return;var t=info.content||info.title||'社区动态';if(t.length>56)t=t.slice(0,56)+'…';var meta=[];if(info.author)meta.push(info.author);if(info.comment)meta.push('评论 '+ac.fmtNum(info.comment));if(info.time)meta.push(info.time);d.push({title:t,desc:meta.join(' · '),pic_url:info.img?ac.image(info.img):'',img:info.img?ac.image(info.img):'',url:ac.__v060a4Route(info),col_type:info.img?'movie_1_left_pic':'text_1',extra:extra(info)})}
ac.home=function(){
    var d=[],p=P(),s=ac.__v050Section();ac.__v060Hydrate(s);if(p===1){top(d);d.push({title:'筛选 · '+ac.__v060Summary(s)+(s==='short'?'':' · '+ac.__v060SortName(s)),pic_url:I('filter'),img:I('filter'),col_type:'text_icon',url:'hiker://page/acfun_category?rule=ACFun&simple=true#noRecordHistory#',extra:{inheritTitle:false,pageTitle:'筛选',lineVisible:false}});d.push({col_type:'line'});section(d,nameOf(s),ac.__v060Summary(s)+(s==='short'?'':' · '+ac.__v060SortName(s)))}
    var list=[];try{if(s==='featured')list=ac.__v050StationList(p,0);else if(s==='lifan')list=ac.__v050StationList(p,1);else if(s==='comic')list=ac.__v050ComicList(p);else if(s==='short')list=ac.__v050ShortList(p);else list=ac.__v050CatalogList(p,s)}catch(e){try{setItem('acfun_v060_a7_home_error',S(e.message||e))}catch(e0){}}
    if(s==='comic')for(var i=0;i<list.length;i++)comicCard(d,list[i]);else if(s==='short')for(var j=0;j<list.length;j++)shortCard(d,list[j]);else{var start=0;if(p===1&&getItem('acfun_v060_hero','1')==='1'&&list.length){var hi=ac.itemInfo(list[0]);if(hi.id){hi.kind='video';d.push({title:hi.title,desc:infoLine([hi.author,hi.watch?('▶ '+ac.fmtNum(hi.watch)):'']),pic_url:ac.image(hi.img),img:ac.image(hi.img),url:ac.__v060a4Route(hi),col_type:'card_pic_1',extra:extra(hi)});start=1}}for(var q=start;q<list.length;q++)videoCard(d,list[q])}
    if(!list.length&&p===1){d.push({title:s==='short'?'短视频暂时没有返回内容':'当前筛选暂时没有内容',desc:s==='short'?'已保留 APK 短视频接口兼容链；点击筛选可切换推荐/发现。':'可以换一个分类，或恢复默认筛选。',col_type:'long_text',url:'hiker://empty'});d.push({title:'调整筛选',pic_url:I('filter'),img:I('filter'),col_type:'text_icon',url:'hiker://page/acfun_category?rule=ACFun&simple=true#noRecordHistory#',extra:{lineVisible:false}})}setResult(d)
};
ac.__v060a7MainCategory=function(){
    var d=[],s=ac.__v050Section();setPageTitle('筛选');ac.__v060Hydrate(s);d.push({title:'当前条件',desc:nameOf(s)+' · '+ac.__v060Summary(s)+(s==='short'?'':' · '+ac.__v060SortName(s)),col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}});d.push({col_type:'line'});
    var secs=ac.__v060Sections,sm=rowNames(secs);selectRow(d,'栏目',nameOf(s),sm.names,sm.ids,s,'__section__','');s=ac.__v050Section();ac.__v060Hydrate(s);
    if(s==='short'){var tabs=ac.__v050ShortTabs||[],tm=rowNames(tabs),sv=state('acfun_v050_short_load_type','2');selectRow(d,'短视频流',currentName(tabs,sv,'推荐'),tm.names,tm.ids,sv,'acfun_v050_short_load_type','')}
    else if(s==='featured'||s==='lifan'){var r=s==='lifan'?1:0,key=r?'acfun_v050_station_lifan':'acfun_v050_station_featured',rows=ac.__v050Stations(r)||[],rm=rowNames(rows),cur=state(key,'');if(!cur&&rows.length)cur=S(rows[0].id);selectRow(d,s==='lifan'?'里番频道':'精选频道',currentName(rows,cur,'默认'),rm.names,rm.ids,cur,key,'')}
    else if(s==='comic'){var comics=ac.__v050ComicStations()||[],cm=rowNames(comics),cc=state('acfun_v050_comic_station','');if(!cc&&comics.length)cc=S(comics[0].id);selectRow(d,'漫画分类',currentName(comics,cc,'默认'),cm.names,cm.ids,cc,'acfun_v050_comic_station','')}
    else if(s==='anime'||s==='video'){var ck=s==='video'?'acfun_v050_class_video':'acfun_v050_class_anime',tk=s==='video'?'acfun_v050_tag_video':'acfun_v050_tag_anime',classes=ac.__v050Catalog(s)||[],clm=rowNames(classes),cv=state(ck,'');if(!cv&&classes.length)cv=S(classes[0].id);selectRow(d,'分类',currentName(classes,cv,'默认'),clm.names,clm.ids,cv,ck,tk);var cls=ac.__v050Class(s),tags=ac.__v050Tags(s,cls)||[],tn=['全部'],ti=[''];for(var t=0;t<tags.length;t++){tn.push(S(tags[t].name));ti.push(S(tags[t].id))}var tv=state(tk,'');selectRow(d,'标签',currentName(tags,tv,'全部'),tn,ti,tv,tk,'')}
    if(s!=='short'){var sorts=ac.__v050Sorts||[],sn=[],si=[];for(var z=0;z<sorts.length;z++){sn.push(S(sorts[z].name));si.push(S(sorts[z].value))}var sv2=ac.__v050Sort(s);selectRow(d,'排序',ac.__v060SortName(s),sn,si,sv2,'acfun_v050_sort_'+s,'')}
    d.push({col_type:'line'});d.push({title:'返回首页查看结果',col_type:'text_2',url:'hiker://home@ACFun',extra:{lineVisible:false}});d.push({title:'恢复默认',col_type:'text_2',url:clearCurrentUrl(s),extra:{lineVisible:false}});setResult(d)
};
function extensionTabs(d,active){var xs=[{key:'short',name:'短视频'},{key:'community',name:'社区'},{key:'fiction',name:'小说'},{key:'audio',name:'有声'}];for(var i=0;i<xs.length;i++){var x=xs[i],u=x.key==='short'?$('hiker://empty#noLoading#').lazyRule(function(){putMyVar('acfun_v050_section','short');setItem('acfun_v060_section','short');return'hiker://home@ACFun'}):routeView(x.key);d.push({title:(active===x.key?'✓ ':'')+x.name,col_type:'scroll_button',url:u,extra:{lineVisible:false}})}d.push({col_type:'line'})}
ac.__v060a7CommunityPage=function(){
    var d=[],p=P();setPageTitle('ACFun 社区');if(p===1){extensionTabs(d,'community');var ups=ac.__v060a4HotBloggers();if(ups.length){section(d,'热门 UP');for(var i=0;i<Math.min(ups.length,8);i++){var u=ac.__v060a4BloggerInfo(ups[i]),pic=u.img?ac.image(u.img):I('community_off');d.push({title:u.name,pic_url:pic,img:pic,col_type:'icon_small_4',url:'hiker://search?s='+encodeURIComponent(u.name)+'&rule=ACFun&scope=dynamic',extra:{lineVisible:false}})}}var cats=ac.__v060a4CommunityCategories()||[],cm=rowNames(cats),cur=state('acfun_v060_dynamic_category',''),names=['全部'].concat(cm.names),ids=[''].concat(cm.ids);selectRow(d,'动态分类',currentName(cats,cur,'全部'),names,ids,cur,'acfun_v060_dynamic_category','');var ds=state('acfun_v060_dynamic_sort','hot');selectRow(d,'排序',ds==='new'?'最新':'热门',['热门','最新'],['hot','new'],ds,'acfun_v060_dynamic_sort','');d.push({col_type:'line'});section(d,'社区动态',cur?'已按分类筛选':'全部动态')}
    var list=ac.__v060a4DynamicList(p);for(var j=0;j<list.length;j++)dynamicCard(d,list[j]);if(!list.length&&p===1)d.push({title:'暂时没有动态',desc:'已过滤明显测试/机器分类，可切换“全部 + 最新”重试。',col_type:'long_text',url:'hiker://empty'});setResult(d)
};
ac.__v060a7FictionPage=function(mode){
    mode=mode==='audio'?'audio':'fiction';var d=[],p=P();setPageTitle(mode==='audio'?'ACFun 有声':'ACFun 小说');if(p===1){extensionTabs(d,mode);var tags=ac.__v060a4FictionTags()||[],tm=rowNames(tags),tk='acfun_v060_fiction_tag_'+mode,cur=state(tk,''),names=['全部'].concat(tm.names),ids=[''].concat(tm.ids);selectRow(d,'分类',currentName(tags,cur,'全部'),names,ids,cur,tk,'');var sk='acfun_v060_fiction_sort_'+mode,sv=state(sk,'1'),sortName=sv==='2'?'热门':(sv==='3'?'完结':'最新');selectRow(d,'排序',sortName,['最新','热门','完结'],['1','2','3'],sv,sk,'');d.push({col_type:'line'});section(d,mode==='audio'?'有声书库':'小说书库',cur?'分类无结果时自动回退全部':'全部内容')}
    var list=ac.__v060a4FictionList(p,mode);for(var i=0;i<list.length;i++)fictionCard(d,list[i]);if(!list.length&&p===1)d.push({title:mode==='audio'?'暂时没有可确认的有声内容':'暂时没有返回小说',desc:'Alpha7 已扩大 findList 参数组合，并在分类无结果时自动回退全部。',col_type:'long_text',url:'hiker://empty'});setResult(d)
};
ac.categoryCenter=function(){var view=S(getParam('view','')||(typeof MY_PARAMS==='object'&&MY_PARAMS.view)||'');if(view==='community')return ac.__v060a7CommunityPage();if(view==='fiction'||view==='audio')return ac.__v060a7FictionPage(view);return ac.__v060a7MainCategory()};
ac.build='2026.08.22-v0.6.0-alpha7';ac.runtimeMode='test-ui-v060-alpha7';try{setItem('acfun_test_runtime','0.6.0-alpha7 interaction-ui')}catch(e){}
})();
