/** ACFun 0.6.0-alpha1 / Build 152 - APP-like home + taxonomy + search */
(function(){
if(typeof ac!=='object')throw new Error('ACFun core missing');
ac.build='2026.08.21-v0.6.0-alpha1';ac.runtimeMode='test-ui-v060-alpha1';
var A='#FF4D4F',T='#333333',M='#999999',BASE='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/assets/';
function S(v){return String(v===undefined||v===null?'':v)}function E(v){return S(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}function P(){try{return Math.max(1,Number(MY_PAGE||1)||1)}catch(e){return 1}}function I(n){return BASE+n+'.svg'}function PK(k){return'acfun_v060_state_'+k}function H(k){var v=S(getMyVar(k,'')||'');if(!v){v=S(getItem(PK(k),'')||'');if(v)putMyVar(k,v)}return v}function C(n,on){return on?'<b><font color="'+A+'">'+E(n)+'</font></b>':'<font color="'+T+'">'+E(n)+'</font>'}function SN(s){return({featured:'精选',comic:'漫画',anime:'动漫',video:'视频',lifan:'里番',short:'短视频'})[s]||'内容'}function SI(s){return({featured:'featured',comic:'comic',anime:'anime',video:'video',lifan:'lifan',short:'short'})[s]||'featured'}
function clean(a){var o=[],seen={};(a||[]).forEach(function(x){x=x||{};var id=S(x.id),n=S(x.name).replace(/\s+/g,' ').trim();if(!id||!n||/^[>›»→▶]+$/.test(n))return;var k=id+'|'+n;if(seen[k])return;seen[k]=1;o.push({id:id,name:n,value:x.value,raw:x.raw})});return o}
function extra(info){return{video_id:info.id,video_title:info.title,video_img:info.img,video_uri:info.uri,video_data:JSON.stringify(info.raw||{}),pageTitle:info.title,lineVisible:false,longClick:[{title:'加入本地收藏',js:$.toString(function(){var s=getItem('acfun_core_src_v018','');if(!s)return'toast://核心缓存不存在';eval(s);return ac.favoriteFromParams()})},{title:'复制标题',js:$.toString(function(){return'copy://'+String(MY_PARAMS.video_title||'')})}]}}
function age(ts){var d=Math.max(0,Date.now()-Number(ts||0));if(d<60000)return'刚刚';if(d<3600000)return Math.floor(d/60000)+'分钟前';if(d<86400000)return Math.floor(d/3600000)+'小时前';if(d<604800000)return Math.floor(d/86400000)+'天前';var x=new Date(Number(ts||0));return(x.getMonth()+1)+'/'+x.getDate()}
ac.__v060Sections=[{key:'featured',name:'精选',icon:'featured'},{key:'comic',name:'漫画',icon:'comic'},{key:'anime',name:'动漫',icon:'anime'},{key:'video',name:'视频',icon:'video'},{key:'lifan',name:'里番',icon:'lifan'}];
ac.__v050Section=function(){var v=S(getMyVar('acfun_v050_section','')||'');if(!v&&getItem('acfun_v060_remember_section','1')==='1')v=S(getItem('acfun_v060_section','featured')||'featured');if(!v)v='featured';var ok=v==='short';ac.__v060Sections.forEach(function(x){if(x.key===v)ok=true});if(!ok)v='featured';putMyVar('acfun_v050_section',v);return v};
ac.__v050Sorts=[{name:'综合',value:'0'},{name:'最新',value:'1'},{name:'最多观看',value:'2'},{name:'最多点赞',value:'3'}];
ac.__v050Sort=function(s){s=s||ac.__v050Section();var v=S(getMyVar('acfun_v050_sort_'+s,'')||getItem('acfun_v060_sort_'+s,'1')||'1');putMyVar('acfun_v050_sort_'+s,v);return v};
ac.__v060SortName=function(s){var v=ac.__v050Sort(s),n='最新';ac.__v050Sorts.forEach(function(x){if(S(x.value)===v)n=x.name});return n};
ac.__v060Hydrate=function(s){if(s==='featured')H('acfun_v050_station_featured');else if(s==='lifan')H('acfun_v050_station_lifan');else if(s==='comic')H('acfun_v050_comic_station');else if(s==='anime'){H('acfun_v050_class_anime');H('acfun_v050_tag_anime')}else if(s==='video'){H('acfun_v050_class_video');H('acfun_v050_tag_video')}else if(s==='short')H('acfun_v050_short_load_type')};
ac.__v060Summary=function(s){s=s||ac.__v050Section();ac.__v060Hydrate(s);try{if(s==='featured'||s==='lifan'){var st=ac.__v050Station(s==='lifan'?1:0);return st?S(st.name):SN(s)}if(s==='comic'){var c=ac.__v050ComicStation();return c?S(c.name):'漫画'}if(s==='anime'||s==='video'){var cl=ac.__v050Class(s),tg=ac.__v050Tag(s,cl),a=[];if(cl)a.push(S(cl.name));if(tg)a.push(S(tg.name));return a.length?a.join(' · '):SN(s)}if(s==='short')return S(getMyVar('acfun_v050_short_load_type','3'))==='4'?'发现':'推荐'}catch(e){}return SN(s)};
ac.__v060SearchCenterUrl=function(){return $('hiker://empty#noHistory##noRecordHistory#').rule(function(){require('https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/bootstrap_test_v050.js?v=5120',{headers:{'Cache-Control':'no-cache'}},5120);ACFunBoot.loadOnly();ac.searchCenter()})};
function nav(d){d.push({title:'搜索视频 / UP / 标签',img:I('search'),col_type:'icon_1_search',url:ac.__v060SearchCenterUrl(),extra:{lineVisible:false}});var cur=ac.__v050Section();ac.__v060Sections.forEach(function(x){d.push({title:C(x.name,cur===x.key),img:I(x.icon),col_type:'icon_5',url:$('hiker://empty#noLoading#').lazyRule(function(k){putMyVar('acfun_v050_section',k);setItem('acfun_v060_section',k);refreshPage(false);return'hiker://empty'},x.key),extra:{lineVisible:false}})});[{name:'短视频',icon:'short',section:'short'},{name:'收藏',icon:'favorite',page:'acfun_favorites'},{name:'历史',icon:'history',page:'acfun_history'},{name:'设置',icon:'settings',page:'acfun_settings'}].forEach(function(x){var u=x.section?$('hiker://empty#noLoading#').lazyRule(function(k){putMyVar('acfun_v050_section',k);setItem('acfun_v060_section',k);refreshPage(false);return'hiker://empty'},x.section):'hiker://page/'+x.page+'?rule=ACFun&simple=true#noRecordHistory#';d.push({title:x.name,img:I(x.icon),col_type:'icon_small_4',url:u,extra:{lineVisible:false}})})}
function cont(d){if(getItem('acfun_v060_continue','1')!=='1')return;var h=ac.historyList();if(!h.length)return;var it=h[0],raw=ac.safeJson(it.data)||{},info=ac.itemInfo({videoId:it.id,title:it.title,cover:it.img,videoUri:it.uri,video:raw});if(!info.id)return;d.push({title:'<b>继续观看</b>  <font color="'+M+'">'+E(age(it.time))+'</font>',img:I('history'),col_type:'text_icon',url:'hiker://page/acfun_history?rule=ACFun&simple=true#noRecordHistory#',extra:{lineVisible:false}});d.push({title:info.title,desc:'继续观看'+(info.author?' · '+info.author:''),img:ac.image(info.img),url:ac.detailUrl(info),col_type:'movie_1_left_pic',extra:extra(info)});d.push({col_type:'line'})}
function row(d,a,cur,key,clearKey){clean(a).forEach(function(x){d.push({title:C(x.name,S(cur)===S(x.id)),col_type:'scroll_button',url:$('hiker://empty#noLoading#').lazyRule(function(v,k,ck){putMyVar(k,String(v));setItem('acfun_v060_state_'+k,String(v));if(ck){clearMyVar(ck);setItem('acfun_v060_state_'+ck,'')}refreshPage(false);return'hiker://empty'},x.id,key,clearKey||''),extra:{lineVisible:false}})})}
function allTag(d,key,cur){d.push({title:C('全部',!cur),col_type:'scroll_button',url:$('hiker://empty#noLoading#').lazyRule(function(k){clearMyVar(k);setItem('acfun_v060_state_'+k,'');refreshPage(false);return'hiker://empty'},key),extra:{lineVisible:false}})}
ac.__v060FilterMenu=function(){return $('hiker://empty#noLoading#').lazyRule(function(){var s=getItem('acfun_core_src_v018','');if(s)eval(s);var sec=ac.__v050Section(),ops=['排序方式','重置当前筛选','刷新分类与列表缓存'];return $(ops,2).select(function(){var s2=getItem('acfun_core_src_v018','');if(s2)eval(s2);var sec2=ac.__v050Section();if(String(input)==='排序方式')return $(['综合','最新','最多观看','最多点赞'],2).select(function(){var sec3=getMyVar('acfun_v050_section',getItem('acfun_v060_section','featured')),m={'综合':'0','最新':'1','最多观看':'2','最多点赞':'3'},v=m[String(input)]||'1';putMyVar('acfun_v050_sort_'+sec3,v);setItem('acfun_v060_sort_'+sec3,v);refreshPage(false);return'hiker://empty'});if(String(input)==='重置当前筛选'){function r(k){clearMyVar(k);setItem('acfun_v060_state_'+k,'')}if(sec2==='featured')r('acfun_v050_station_featured');else if(sec2==='lifan')r('acfun_v050_station_lifan');else if(sec2==='comic')r('acfun_v050_comic_station');else if(sec2==='anime'){r('acfun_v050_class_anime');r('acfun_v050_tag_anime')}else if(sec2==='video'){r('acfun_v050_class_video');r('acfun_v050_tag_video')}putMyVar('acfun_v050_sort_'+sec2,'1');setItem('acfun_v060_sort_'+sec2,'1');refreshPage(false);return'toast://已重置当前栏目'}if(String(input)==='刷新分类与列表缓存'){try{if(ac.__v042ClearDataCache)ac.__v042ClearDataCache()}catch(e){}refreshPage(false);return'toast://缓存已刷新'}return'hiker://empty'})})};
function taxonomy(d){var s=ac.__v050Section();ac.__v060Hydrate(s);if(s==='short'){var sv=H('acfun_v050_short_load_type')||'3';row(d,ac.__v050ShortTabs,sv,'acfun_v050_short_load_type','');return}d.push({title:'<b>频道筛选</b>  <font color="'+M+'">'+E(ac.__v060Summary(s)+' · '+ac.__v060SortName(s))+'</font>',img:I('filter'),col_type:'text_icon',url:ac.__v060FilterMenu(),extra:{lineVisible:false}});if(s==='featured'||s==='lifan'){var rr=s==='lifan'?1:0,k=rr?'acfun_v050_station_lifan':'acfun_v050_station_featured',a=clean(ac.__v050Stations(rr)),v=H(k);if(!v&&a.length)v=S(a[0].id);row(d,a,v,k,'')}else if(s==='comic'){var ca=clean(ac.__v050ComicStations()),cv=H('acfun_v050_comic_station');if(!cv&&ca.length)cv=S(ca[0].id);row(d,ca,cv,'acfun_v050_comic_station','')}else if(s==='anime'||s==='video'){var ck=s==='video'?'acfun_v050_class_video':'acfun_v050_class_anime',tk=s==='video'?'acfun_v050_tag_video':'acfun_v050_tag_anime',cl=clean(ac.__v050Catalog(s)),c=H(ck);if(!c&&cl.length)c=S(cl[0].id);row(d,cl,c,ck,tk);var cls=ac.__v050Class(s),tags=clean(ac.__v050Tags(s,cls)),tv=H(tk);if(tags.length){allTag(d,tk,tv);row(d,tags,tv,tk,'')}}}
function head(d,s){d.push({title:'<b>'+E(SN(s)+(s==='short'?'':'推荐'))+'</b>  <font color="'+M+'">'+E(ac.__v060Summary(s))+'</font>',img:I(SI(s)),col_type:'text_icon',url:'hiker://empty',extra:{lineVisible:false}})}
function hero(d,x){var info=ac.itemInfo(x);if(!info.id)return false;d.push({title:info.title,desc:'0',img:ac.image(info.img),url:ac.detailUrl(info),col_type:'card_pic_1',extra:extra(info)});var m=[];if(info.author)m.push(info.author);if(info.watch)m.push('▶ '+ac.fmtNum(info.watch));if(info.duration)m.push(info.duration);if(m.length)d.push({title:'<font color="'+M+'">'+E(m.join('  ·  '))+'</font>',col_type:'rich_text',extra:{textSize:12,lineVisible:false}});return true}
ac.addVideoCard=function(d,x,col){var info=ac.itemInfo(x),m=[];if(info.author)m.push(info.author);if(info.watch)m.push('▶ '+ac.fmtNum(info.watch));if(info.like)m.push('♥ '+ac.fmtNum(info.like));if(info.duration)m.push(info.duration);d.push({title:info.title||'未命名视频',desc:m.join('  '),img:ac.image(info.img),url:ac.detailUrl(info),col_type:col||getItem('acfun_v060_video_layout','movie_2'),extra:extra(info)})};
ac.home=function(){var d=[],p=P(),s=ac.__v050Section();ac.__v060Hydrate(s);if(p===1){nav(d);cont(d);taxonomy(d);d.push({col_type:'line'});head(d,s)}var list=[];try{if(s==='featured')list=ac.__v050StationList(p,0);else if(s==='lifan')list=ac.__v050StationList(p,1);else if(s==='comic')list=ac.__v050ComicList(p);else if(s==='short')list=ac.__v050ShortList(p);else list=ac.__v050CatalogList(p,s)}catch(e){setItem('acfun_v060_home_error',String(e.message||e))}var st=0;if(p===1&&getItem('acfun_v060_hero','1')==='1'&&s!=='comic'&&s!=='short'&&list.length)if(hero(d,list[0]))st=1;if(s==='comic'){list.forEach(function(x){var ci=ac.__v047ComicInfo(x);if(ci.id)d.push({title:ci.title,desc:ci.desc,img:ac.image(ci.img),col_type:'movie_3',url:ac.__v047ComicUrl(),extra:{inheritTitle:false,pageTitle:ci.title,comics_id:ci.id,comics_title:ci.title,content_kind:'comic',lineVisible:false}})})}else{var style=s==='short'?getItem('acfun_v060_short_layout','movie_2'):getItem('acfun_v060_video_layout','movie_2');for(var i=st;i<list.length;i++)ac.addVideoCard(d,list[i],style)}if(!list.length&&p===1)d.push({title:'暂时没有内容',desc:'可切换频道/标签，或刷新分类与列表缓存。',col_type:'long_text',url:ac.__v060FilterMenu()});setResult(d)};
ac.__v060SearchHistory=function(){try{return JSON.parse(getItem('acfun_v060_search_history','[]'))||[]}catch(e){return[]}};ac.__v060SaveSearch=function(q){q=S(q).trim();if(!q)return;var a=ac.__v060SearchHistory().filter(function(x){return S(x)!==q});a.unshift(q);setItem('acfun_v060_search_history',JSON.stringify(a.slice(0,20)))};
ac.searchCenter=function(){var d=[];setPageTitle('ACFun 搜索');d.push({title:'搜索视频 / UP / 标签',img:I('search'),col_type:'icon_1_search',url:$('输入关键词').input(function(){var q=String(input||'').trim();if(!q)return'toast://请输入关键词';var s=getItem('acfun_core_src_v018','');if(s)eval(s);if(ac.__v060SaveSearch)ac.__v060SaveSearch(q);return'hiker://search?s='+encodeURIComponent(q)+'&rule=ACFun'}),extra:{lineVisible:false}});var h=ac.__v060SearchHistory();if(h.length){d.push({title:'<b>最近搜索</b>  <font color="'+M+'">点击标题可清空</font>',img:I('history'),col_type:'text_icon',url:$('hiker://empty#noLoading#').lazyRule(function(){setItem('acfun_v060_search_history','[]');refreshPage(false);return'toast://已清空'}),extra:{lineVisible:false}});h.forEach(function(q){d.push({title:q,col_type:'flex_button',url:'hiker://search?s='+encodeURIComponent(q)+'&rule=ACFun',extra:{lineVisible:false}})})}else d.push({title:'还没有搜索记录',desc:'搜索记录只保存在本机。',col_type:'long_text',url:'hiker://empty'});setResult(d)};
ac.search=function(){var d=[],kw=getParam('kw','')||getParam('s','')||getMyVar('acfun_search_kw','');if(!kw)try{kw=decodeURIComponent(getParam('q',''))}catch(e){}kw=S(kw).trim();putMyVar('acfun_search_kw',kw);if(kw)ac.__v060SaveSearch(kw);if(P()===1){d.push({title:'重新搜索 · '+kw,img:I('search'),col_type:'icon_1_search',url:ac.__v060SearchCenterUrl(),extra:{lineVisible:false}});d.push({title:'<b>搜索结果</b>  <font color="'+M+'">'+E(kw)+'</font>',col_type:'rich_text',extra:{lineVisible:false}})}var size=Number(getItem('acfun_page_size','8'))||8,key='search|'+kw+'|'+P()+'|'+size,c=ac.__v042Read?ac.__v042Read(key,120,900):{},list=[];if(c.stale&&Array.isArray(c.data))list=c.data;if(!list.length&&kw){var p={keyword:kw,keyWord:kw,name:kw,pageNum:P(),page:P(),pageSize:size,limit:size,searchType:'video'};try{list=ac.arr(ac.api('search/keyWordV2',p,{timeout:800,maxAttempts:4}))}catch(e1){}if(!list.length)try{list=ac.arr(ac.api('search/keyWord',p,{timeout:800,maxAttempts:4}))}catch(e2){}if(list.length&&ac.__v042Write)ac.__v042Write(key,list)}list.forEach(function(x){ac.addVideoCard(d,x,getItem('acfun_v060_video_layout','movie_2'))});if(!list.length&&P()===1)d.push({title:'没有搜索到结果',desc:'尝试缩短关键词或改用标签名。',col_type:'long_text',url:ac.__v060SearchCenterUrl()});setResult(d)};
try{setItem('acfun_test_runtime','0.6.0-alpha1 home/taxonomy/search')}catch(e){}
})();
