/** ACFun alpha17 / Build168 - short feed current-bootstrap renderer */
(function(){
if(typeof ac!=='object'||!ac.__a17)throw new Error('ACFun alpha17 base missing');var R=ac.__a17,BASE='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/assets/';
try{if(!getItem('acfun_a17_short_migrated','')){putMyVar('acfun_short_load_type','2');setItem('acfun_a17_short_migrated','1')}}catch(e){}
ac.__v047ShortList=function(page){page=Number(page||1);var current=R.S(getMyVar('acfun_short_load_type','2')||'2'),modes=[current,'2','3','4','1'],seen={},size=30,errs=[];for(var i=0;i<modes.length;i++){var m=R.S(modes[i]);if(seen[m])continue;seen[m]=1;var vs=[{page:page,pageNum:page,pageSize:size,limit:size,loadType:R.N(m)},{page:page,pageNum:page,pageSize:size,limit:size,loadType:R.N(m),videoContentType:'shortVideo',contentType:'shortVideo',videoType:'shortVideo'}];for(var j=0;j<vs.length;j++)try{var raw=ac.__v043Api('video/list',vs[j],{timeout:1700,maxAttempts:1}),list=ac.flattenVideos?ac.flattenVideos(raw):(ac.__v047Arr?ac.__v047Arr(raw):[]);if(!list.length&&ac.__v047Arr)list=ac.__v047Arr(raw);if(list.length){var si=ac.itemInfo(list[0]||{}),keys=[];try{keys=Object.keys(list[0]||{}).slice(0,20)}catch(e0){}try{setItem('acfun_a17_short_probe',JSON.stringify({loadType:m,variant:j,count:list.length,id:si.id,title:si.title,img:si.img,uri:si.uri,keys:keys}))}catch(e1){}return list}}catch(e){errs.push('m'+m+'v'+j+':'+R.S(e.message||e))}}try{setItem('acfun_a17_short_probe','empty '+errs.slice(0,4).join(' | '))}catch(e2){}return[]};
var SECS=[['featured','精选'],['comic','漫画'],['anime','动漫'],['video','视频'],['lifan','里番'],['short','短视频'],['community','社区'],['fiction','小说'],['audio','有声']];
function section(){return R.S(getMyVar('acfun_a15_section','')||getItem('acfun_a15_section','featured')||'featured')};function icon(s,on){var n=({featured:'featured',comic:'comic',anime:'anime',video:'video',lifan:'lifan',short:'short',community:'community',fiction:'novel',audio:'audio'})[s]||'featured';return BASE+n+(on?'':'_off')+'.svg'}
function sw(s){return $('hiker://empty#noLoading#').lazyRule(function(v){putMyVar('acfun_a15_section',v);setItem('acfun_a15_section',v);putMyVar('acfun_native_section',v);refreshPage(false);return'hiker://empty'},s)}
function top(d){d.push({title:'搜索视频、漫画、小说与社区',pic_url:BASE+'search.svg',img:BASE+'search.svg',col_type:'text_icon',url:'hiker://page/acfun_search_center?rule=ACFun&simple=true#noRecordHistory#',extra:{inheritTitle:false,pageTitle:'ACFun 全站搜索',lineVisible:false}});for(var i=0;i<5;i++){var x=SECS[i];d.push({title:x[1],pic_url:icon(x[0],x[0]==='short'),img:icon(x[0],x[0]==='short'),col_type:'icon_5',url:sw(x[0]),extra:{lineVisible:false}})}for(var j=5;j<SECS.length;j++){var y=SECS[j];d.push({title:y[1],pic_url:icon(y[0],y[0]==='short'),img:icon(y[0],y[0]==='short'),col_type:'icon_small_4',url:sw(y[0]),extra:{lineVisible:false}})}[['收藏','favorite_off','acfun_favorites'],['历史','history_off','acfun_history'],['设置','settings_off','acfun_settings']].forEach(function(x){d.push({title:x[0],pic_url:BASE+x[1]+'.svg',img:BASE+x[1]+'.svg',col_type:'icon_small_3',url:'hiker://page/'+x[2]+'?rule=ACFun&simple=true#noRecordHistory#',extra:{inheritTitle:false,pageTitle:x[0],lineVisible:false}})})}
function sel(){var rows=[['2','推荐'],['3','发现'],['4','热门'],['1','同城']],o=[],v=[];for(var i=0;i<rows.length;i++){v.push(rows[i][0]);o.push(rows[i][1])}var c=R.S(getMyVar('acfun_short_load_type','2')||'2');return'select://'+JSON.stringify({title:'短视频流',options:o,selectedIndex:Math.max(0,v.indexOf(c)),col:2,js:$.toString(function(os,vs){var i=os.indexOf(input);if(i<0)return;putMyVar('acfun_short_load_type',String(vs[i]));refreshPage(false)},o,v)})};function nm(){var c=R.S(getMyVar('acfun_short_load_type','2')||'2');return c==='3'?'发现':c==='4'?'热门':c==='1'?'同城':'推荐'}
function card(d,x){var i=ac.itemInfo(x||{});if(!i||!i.id)return;var pic=i.img?ac.image(i.img):'',m=[];if(i.watch)m.push('▶ '+ac.fmtNum(i.watch));if(i.duration)m.push(i.duration);if(!m.length&&i.author)m.push(i.author);var u=$('hiker://empty#noLoading#').lazyRule(function(vid,raw,uri,title,img,boot,ver){try{require(boot,{headers:{'Cache-Control':'no-cache'}},ver);ACFunBoot.loadOnly();return ac.__v060a17Play(String(vid),String(raw),String(uri||''))}catch(e){return'toast://播放失败：'+String(e.message||e)}},i.id,JSON.stringify(i.raw||x||{}),i.uri||'',i.title,i.img,R.BOOT,R.BVER);d.push({title:i.title,desc:m.join(' · '),pic_url:pic,img:pic,col_type:'movie_3',url:u,extra:{lineVisible:false,id:'acfun-short-'+i.id}})}
function home(){var d=[],p=1;try{p=Math.max(1,Number(MY_PAGE||1)||1)}catch(e){}if(p===1){top(d);d.push({title:'短视频 · '+nm()+' ▾',col_type:'scroll_button',url:sel(),extra:{lineVisible:false}});d.push({col_type:'line'});d.push({title:'短视频',desc:'点击卡片直接播放',col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}})}var a=[];try{a=ac.__v047ShortList(p)||[]}catch(e){try{setItem('acfun_a17_short_home_error',R.S(e.message||e))}catch(e0){}}for(var i=0;i<a.length;i++)card(d,a[i]);if(!a.length&&p===1)d.push({title:'短视频接口返回但当前没有可渲染条目',desc:R.S(getItem('acfun_a17_short_probe','暂无'))+'\n'+R.S(getItem('acfun_a17_short_home_error','')),col_type:'long_text',url:'hiker://empty'});setResult(d)}
ac.home=function(){if(section()==='short')return home();return typeof R.prevHome==='function'?R.prevHome.call(ac):undefined};
})();
