/** ACFun alpha17 / Build168 - explicit comic routing + diagnostics */
(function(){
if(typeof ac!=='object'||!ac.__a17)throw new Error('ACFun alpha17 base missing');var R=ac.__a17;
function parse(v){if(typeof v!=='string')return v;var s=R.S(v).trim();if(!s)return v;try{if((s[0]==='['&&s[s.length-1]===']')||(s[0]==='{'&&s[s.length-1]==='}'))return JSON.parse(s)}catch(e){}return v}
function images(root){var out=[],seen={},dom=R.S(R.deep(root,['domain','imgDomain','imageDomain'])||'');function add(v){v=parse(v);if(Array.isArray(v)){for(var i=0;i<v.length;i++)add(v[i]);return}if(v&&typeof v==='object'){var p=R.pick(v,['imgUrl','imageUrl','url','path','src','value'],'');if(p!==undefined&&p!==null&&p!==''){add(p);return}for(var k in v)if(/img|image|pic|page/i.test(k)&&!/domain|host/i.test(k))add(v[k]);return}var u=R.S(v).trim();if(!u)return;if(u.indexOf('//')===0)u='https:'+u;else if(!/^https?:\/\//i.test(u)&&dom)u=dom.replace(/\/+$/,'')+'/'+u.replace(/^\/+/, '');if(!/^https?:\/\//i.test(u)&&R.isJh(u))u=R.jhAbs(u);if(/^https?:\/\//i.test(u)&&!seen[u]){seen[u]=1;out.push(u)}}var ks=['imgList','imageList','chapterImgList','images','pageList','pics','pictures'];for(var i=0;i<ks.length;i++)try{var v=R.deep(root,[ks[i]]);if(v!==undefined&&v!==null)add(v)}catch(e){}if(!out.length){function walk(v,k,d){if(v===undefined||v===null||d>12)return;if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],k,d+1);return}if(typeof v==='string'){if(/img|image|pic|page/i.test(k)&&!/domain|host/i.test(k))add(v);return}if(typeof v!=='object')return;for(var x in v)walk(v[x],x,d+1)}walk(root,'',0)}return out}
function chapter(cid,ch){var t=[{p:{chapterId:R.N(ch)},m:'GET',n:'chapterId-GET'},{p:{chapterId:R.N(ch)},m:'POST',n:'chapterId-POST'},{p:{comicsId:R.N(cid),chapterId:R.N(ch)},m:'GET',n:'comicsId-GET'},{p:{comicsId:R.N(cid),chapterId:R.N(ch)},m:'POST',n:'comicsId-POST'}],best={};for(var i=0;i<t.length;i++)try{var o=ac.__v043Api('comics/base/chapterInfo',t[i].p,t[i].m==='POST'?{method:'POST',write:true,allowGet:false,timeout:1900,maxAttempts:1}:{timeout:1900,maxAttempts:1});if(o&&typeof o==='object'){best=o;var a=images(o),cw=R.pick(o,['canWatch'],'');if(a.length||cw===false){try{setItem('acfun_a17_comic_probe',JSON.stringify({route:t[i].n,cid:R.S(cid),ch:R.S(ch),images:a.length,canWatch:cw}))}catch(e0){}return o}}}catch(e){try{setItem('acfun_a17_comic_error',t[i].n+': '+R.S(e.message||e))}catch(e1){}}try{setItem('acfun_a17_comic_probe',JSON.stringify({route:'none',cid:R.S(cid),ch:R.S(ch),images:0}))}catch(e2){}return best}
function url(cid,ch,t){return'hiker://page/acfun_detail?rule=ACFun&simple=true&content_kind=comic_chapter&comics_id='+encodeURIComponent(R.S(cid))+'&comic_chapter_id='+encodeURIComponent(R.S(ch))+'&comic_chapter_title='+encodeURIComponent(R.S(t||''))+'#fullTheme#noRecordHistory#'}
R.comicDetail=function(id,title){var data=null;try{data=ac.__v043Api('comics/base/info',{comicsId:R.N(id)},{timeout:1500,maxAttempts:2})}catch(e){setResult([{title:'漫画详情加载失败',desc:R.S(e.message||e),col_type:'long_text',url:'hiker://empty'}]);return}data=data||{};var ci=ac.__v047ComicInfo?ac.__v047ComicInfo(data):{id:R.S(id),title:R.S(title||'漫画'),img:'',desc:''},ch=Array.isArray(data.chapterList)?data.chapterList:[];if(!ch.length){var v=R.deep(data,['chapterList','chapters','chapterInfoList']);if(Array.isArray(v))ch=v}setPageTitle(ci.title||title||'漫画详情');var d=[],pic=ci.img?ac.image(ci.img):'';d.push({title:ci.title||title||'漫画',desc:R.S(ci.desc||R.pick(data,['authorName','nickName','info','description','desc'],'')),pic_url:pic,img:pic,col_type:'movie_1_left_pic',url:'hiker://empty',extra:{lineVisible:false}});for(var i=0;i<ch.length;i++){var x=ch[i]||{},cid=R.S(R.pick(x,['chapterId','id'],'')),ct=R.S(R.pick(x,['chapterTitle','title','name'],'第'+(i+1)+'话'));if(cid)d.push({title:ct,col_type:'text_2',url:url(id,cid,ct),extra:{lineVisible:false}})}if(!ch.length)d.push({title:'暂未返回章节目录',col_type:'text_center_1',url:'hiker://empty'});setResult(d)};
R.comicReader=function(cid,ch){var o=chapter(cid,ch),a=images(o),d=[];if(R.pick(o,['canWatch'],'')===false){setResult([{title:'当前章节暂不可阅读',desc:R.S(R.pick(o,['info','message'],'需要权限或购买')),col_type:'long_text',url:'hiker://empty'}]);return}for(var i=0;i<a.length;i++){var u=ac.image?ac.image(a[i]):a[i];if(u)d.push({title:'',pic_url:u,img:u,col_type:'pic_1_full',url:'hiker://empty',extra:{lineVisible:false}})}if(!d.length)d.push({title:'本章未解析到图片',desc:'漫画诊断：'+R.S(getItem('acfun_a17_comic_probe','暂无'))+'\n'+R.S(getItem('acfun_a17_comic_error','')),col_type:'long_text',url:'hiker://empty'});setResult(d)};
ac.detail=function(){var p=typeof MY_PARAMS==='object'?MY_PARAMS:{},kind=R.S(p.content_kind||R.param('content_kind')||''),ch=R.S(p.comic_chapter_id||R.param('comic_chapter_id')),cid=R.S(p.comics_id||R.param('comics_id'));if(kind==='comic_chapter'||ch)return R.comicReader(cid,ch);if(kind==='comic'||cid)return R.comicDetail(cid,R.S(p.comics_title||R.param('comics_title')||''));if(kind==='video'||p.video_id||R.param('video_id'))return R.videoDetail();return typeof R.prevDetail==='function'?R.prevDetail.call(ac):undefined};
ac.diag=function(){var d=[];setPageTitle('ACFun 资源诊断');d.push({title:'Alpha17 设备链诊断',desc:'封面原始：'+R.S(getItem('acfun_a17_cover_raw','暂无')).slice(0,500)+'\n封面解析：'+R.S(getItem('acfun_a17_cover_resolved','暂无')).slice(0,700)+'\n封面渲染：'+R.S(getItem('acfun_a17_cover_rendered','暂无')).slice(0,700)+'\n封面错误：'+R.S(getItem('acfun_a17_cover_error','无')).slice(0,400)+'\n\n播放：'+R.S(getItem('acfun_a17_play_probe','暂无')).slice(0,1000)+'\n\n短视频：'+R.S(getItem('acfun_a17_short_probe','暂无')).slice(0,1200)+'\n\n漫画：'+R.S(getItem('acfun_a17_comic_probe','暂无')).slice(0,700)+'\n漫画错误：'+R.S(getItem('acfun_a17_comic_error','无')).slice(0,500)+'\n\n小说/有声最近路由：'+R.S(getItem('acfun_a15_last_route','暂无')).slice(0,500),col_type:'long_text',url:'hiker://empty'});d.push({title:'复制 Alpha17 诊断',col_type:'text_1',url:'copy://ACFun 2026.08.23-v0.6.0-alpha17 | cover='+R.S(getItem('acfun_a17_cover_resolved','none')).slice(0,180)+' | play='+R.S(getItem('acfun_a17_play_probe','none')).slice(0,300)+' | short='+R.S(getItem('acfun_a17_short_probe','none')).slice(0,300)+' | comic='+R.S(getItem('acfun_a17_comic_probe','none')).slice(0,220)});setResult(d)};
ac.build='2026.08.23-v0.6.0-alpha17';ac.runtimeMode='clean-rebase+a17-device-chain';try{setItem('acfun_test_runtime','0.6.0-alpha17 device-chain repair')}catch(e){}
})();
