/** ACFun 0.6.0-alpha8 / Build 159 - native comic reader + richer community detail. */
(function(){
if(typeof ac!=='object')throw new Error('ACFun core missing');
var oldRoute=ac.__v060a4Route,oldDetail=ac.detail,BOOT='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/bootstrap_test_v064.js?v=6400',BVER=6400,BASE='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/acfun/assets/';
function S(v){return String(v===undefined||v===null?'':v)}
function N(v){var s=S(v);return /^\d+$/.test(s)?Number(s):s}
function param(k){try{return S(getParam(k,''))}catch(e){return''}}
function I(n){return BASE+n+'.svg'}
function first(v){return Array.isArray(v)?(v.length?v[0]:''):v}
function joinUrl(domain,path){path=S(path).trim();domain=S(domain).trim();if(!path)return'';if(/^https?:\/\//i.test(path))return path;if(!domain)return path;return domain.replace(/\/+$/,'')+'/'+path.replace(/^\/+/, '')}
function esc(v){return S(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\r?\n/g,'<br>')}
function cleanText(v){var s=S(v);s=s.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,function(_,t,u){return t===u?u:(t+'\n'+u)});s=s.replace(/(https?:\/\/\S+)\s*\(\1\)/g,'$1').replace(/\n{3,}/g,'\n\n');return s.trim()}
function chapterImages(obj){var domain=S(ac.pick(obj,['domain','imgDomain','imageDomain'],'')||''),raw=ac.pick(obj,['imgList','imageList','chapterImgList','images'],[]),imgs=[],seen={};if(!Array.isArray(raw))raw=[raw];for(var i=0;i<raw.length;i++){var x=raw[i],u=typeof x==='string'?x:first(ac.pick(x||{},['imgUrl','imageUrl','url','path','src'],'')||'');u=joinUrl(domain,u);if(u&&!seen[u]){seen[u]=1;imgs.push(u)}}if(!imgs.length)try{var a=ac.__v060a4Media(obj,'image')||[];for(var j=0;j<a.length;j++)if(!seen[a[j]]){seen[a[j]]=1;imgs.push(a[j])}}catch(e){}return imgs}
function nativeComicUrl(comicsId,chapterId,title){return $('hiker://empty').lazyRule(function(cid,ch,ct,boot,ver){try{require(boot,{headers:{'Cache-Control':'no-cache'}},ver);ACFunBoot.loadOnly();var obj=ac.__v060a4Detail('comics/base/chapterInfo',{comicsId:/^\d+$/.test(String(cid))?Number(cid):cid,chapterId:/^\d+$/.test(String(ch))?Number(ch):ch},'chapter','comic-chapter|'+ch),domain=String(ac.pick(obj,['domain','imgDomain','imageDomain'],'')||''),raw=ac.pick(obj,['imgList','imageList','chapterImgList','images'],[]),arr=[],seen={};if(!Array.isArray(raw))raw=[raw];for(var i=0;i<raw.length;i++){var x=raw[i],u=typeof x==='string'?x:(Array.isArray(ac.pick(x||{},['imgUrl','imageUrl','url','path','src'],''))?ac.pick(x||{},['imgUrl','imageUrl','url','path','src'],'')[0]:ac.pick(x||{},['imgUrl','imageUrl','url','path','src'],''));u=String(u||'').trim();if(u&&!/^https?:\/\//i.test(u)&&domain)u=domain.replace(/\/+$/,'')+'/'+u.replace(/^\/+/, '');if(u&&!seen[u]){seen[u]=1;arr.push(ac.image(u))}}if(!arr.length){var m=ac.__v060a4Media(obj,'image')||[];for(var j=0;j<m.length;j++)if(!seen[m[j]]){seen[m[j]]=1;arr.push(ac.image(m[j]))}}if(!arr.length)return'toast://本章没有返回漫画图片';return'pics://'+arr.join('&&')}catch(e){return'toast://漫画加载失败：'+String(e.message||e)}},comicsId,chapterId,title||'',BOOT,BVER)}
ac.__v060a8ComicChapterUrl=nativeComicUrl;
ac.__v060a4Route=function(info){info=info||{};if(S(info.kind)==='comic_chapter')return nativeComicUrl(info.comicsId||info.id,info.chapterId,info.title);return typeof oldRoute==='function'?oldRoute.call(ac,info):'hiker://empty'};
ac.__v060DetailUrl=ac.__v060a4Route;ac.detailUrl=function(info){return ac.__v060a4Route(info)};

function dynamicDetail(id){
    var d=[],obj=ac.__v060a4Detail('community/dynamic/dynamicInfo',{dynamicId:N(id)},'dynamic','dynamic|'+id),info=ac.__v060a4DynamicInfo(obj);if(!info.id)info.id=id;var payload=ac.__v060a8DynamicPayload?ac.__v060a8DynamicPayload(obj):{texts:[info.content||info.title||''],images:ac.__v060a4Media(obj,'image')||[],videos:[],links:[]},tm=ac.__v060a7HumanTime?ac.__v060a7HumanTime(ac.pick(obj,['createTime','publishTime','time'],'')||info.time):S(info.time||'');setPageTitle('社区动态');
    d.push({title:info.author||'ACFun 用户',desc:tm,col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}});
    var shown={};for(var i=0;i<payload.texts.length;i++){var t=cleanText(payload.texts[i]);if(!t||shown[t])continue;shown[t]=1;d.push({title:esc(t),col_type:'rich_text',url:'hiker://empty',extra:{textSize:15,lineVisible:false}})}
    for(var j=0;j<payload.images.length;j++)d.push({title:'',pic_url:ac.image(payload.images[j]),img:ac.image(payload.images[j]),col_type:'pic_1_full',url:'hiker://empty',extra:{lineVisible:false}});
    if(payload.videos.length){d.push({title:'帖子视频',desc:payload.videos.length+' 个媒体源',col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}});for(var v=0;v<payload.videos.length;v++)d.push({title:'播放视频 '+(v+1),pic_url:I('video'),img:I('video'),col_type:'text_icon',url:payload.videos[v]+'#isVideo=true#',extra:{lineVisible:false}})}
    if(payload.links.length){var linked={};for(var l=0;l<payload.links.length;l++){var u=S(payload.links[l]);if(!u||linked[u])continue;linked[u]=1;d.push({title:'打开链接',desc:u,col_type:'text_1',url:u,extra:{lineVisible:false}})}}
    d.push({col_type:'line'});d.push({title:'评论',pic_url:I('comment'),img:I('comment'),col_type:'icon_small_3',url:ac.__v060a4CommentsUrl('dynamic',info.id,info.title),extra:{lineVisible:false}});d.push({title:'复制正文',pic_url:I('more'),img:I('more'),col_type:'icon_small_3',url:'copy://'+(payload.texts.join('\n\n')||info.content||info.title||''),extra:{lineVisible:false}});d.push({title:'搜索',pic_url:I('search'),img:I('search'),col_type:'icon_small_3',url:'hiker://page/acfun_search_center?rule=ACFun&simple=true#noRecordHistory#',extra:{lineVisible:false}});
    if(!payload.texts.length&&!payload.images.length&&!payload.videos.length)d.push({title:'动态详情暂未返回完整正文',desc:'Alpha8 已递归解析 content/dynamicContent/markdown/body、嵌套 JSON、图片、视频和链接字段。',col_type:'long_text',url:'hiker://empty'});setResult(d)
}
ac.detail=function(){var p=typeof MY_PARAMS==='object'?MY_PARAMS:{},kind=S(p.content_kind||param('content_kind')||'video');if(kind==='comic_chapter'){var cid=S(p.comics_id||param('comics_id')||param('content_id')),ch=S(p.comic_chapter_id||param('comic_chapter_id'));setPageTitle('漫画阅读');setResult([{title:'使用海阔原生漫画模式打开',desc:'Alpha8 已将新章节点击直接切到 pics:// 多图阅读；旧页面入口可点此继续。',col_type:'text_center_1',url:nativeComicUrl(cid,ch,S(p.comic_chapter_title||param('comic_chapter_title')))}]);return}if(kind==='dynamic'){var id=S(p.dynamic_id||param('dynamic_id')||param('content_id'));return dynamicDetail(id)}return typeof oldDetail==='function'?oldDetail.call(ac):undefined};
ac.build='2026.08.22-v0.6.0-alpha8';try{setItem('acfun_v060_detail_a8','native pics reader + complete dynamic payload')}catch(e){}
})();
