// ACFun 0.5.0-rc1 - Native UI Test / strict APP taxonomy
(function(){
if(typeof ac!=='object')throw new Error('ACFun core missing');
ac.build='2026.08.21-v0.5.0-rc1';
ac.runtimeMode='native-ui-050rc1';

var oldDetail=ac.detail;
function sel(name,on){return on?'● '+name:name;}
function page(){return typeof MY_PAGE==='undefined'?1:Number(MY_PAGE||1);}
function n(v){var s=String(v===undefined||v===null?'':v);return /^\d+$/.test(s)?Number(s):s;}
function uniqueRows(rows){var out=[],seen={};for(var i=0;i<(rows||[]).length;i++){var x=rows[i];if(!x||!x.id||!x.name)continue;var k=String(x.id)+'|'+String(x.name);if(seen[k])continue;seen[k]=1;out.push(x);}return out;}

ac.__v050MainSections=[{key:'featured',name:'精选'},{key:'comic',name:'漫画'},{key:'anime',name:'动漫'},{key:'video',name:'视频'},{key:'lifan',name:'里番'}];
ac.__v050Sorts=[{name:'全部',value:'0'},{name:'最新',value:'1'},{name:'最多观看',value:'2'},{name:'最多点赞',value:'3'}];
ac.__v050ShortTabs=[{name:'发现',id:'4'},{name:'推荐',id:'3'}];
ac.__v050Section=function(){var s=String(getMyVar('acfun_v050_section','featured')||'featured');if(s==='short')return s;for(var i=0;i<ac.__v050MainSections.length;i++)if(ac.__v050MainSections[i].key===s)return s;return 'featured';};
ac.__v050Sort=function(){return String(getMyVar('acfun_v050_sort','1')||'1');};
ac.__v050Read=function(key,ttl,stale){return ac.__v042Read?ac.__v042Read('v050|'+key,ttl,stale):{hit:false,fresh:false,stale:false,data:null};};
ac.__v050Write=function(key,data){try{return ac.__v042Write?ac.__v042Write('v050|'+key,data):false;}catch(e){return false;}};

ac.__v050Stations=function(restricted){var r=restricted?1:0,key='stations|'+r,c=ac.__v050Read(key,21600,172800);if(c.stale&&Array.isArray(c.data)&&c.data.length)return c.data;var src=[];try{src=ac.__v047Stations?ac.__v047Stations(r):[];}catch(e){}var out=[];for(var i=0;i<src.length;i++)if(src[i]&&src[i].id&&src[i].name)out.push(src[i]);out=uniqueRows(out);if(out.length)ac.__v050Write(key,out);return out.length?out:(c.hit&&Array.isArray(c.data)?c.data:[]);};
ac.__v050Station=function(restricted){var a=ac.__v050Stations(restricted),key=restricted?'acfun_v050_station_lifan':'acfun_v050_station_featured',id=String(getMyVar(key,'')||''),hit=null;for(var i=0;i<a.length;i++)if(String(a[i].id)===id){hit=a[i];break;}if(!hit&&a.length){hit=a[0];putMyVar(key,String(hit.id));}return hit;};
ac.__v050StationList=function(p,restricted){p=Number(p||1);var st=ac.__v050Station(restricted);if(!st)return [];var size=Number(getItem('acfun_page_size','8'))||8,sort=Number(ac.__v050Sort());if(p===1&&st.raw&&Array.isArray(st.raw.videoList)&&st.raw.videoList.length)return st.raw.videoList.slice(0,size);return ac.__v047ReqList('station/getStationMore',{stationId:n(st.id),page:p,pageNum:p,pageSize:size,sortType:sort},'v050-station|'+(restricted?1:0)+'|'+st.id+'|'+sort+'|'+p);};

ac.__v050Catalog=function(kind){kind=kind==='video'?'video':'anime';var key='catalog|'+kind,c=ac.__v050Read(key,21600,172800);if(c.stale&&Array.isArray(c.data)&&c.data.length)return c.data;var type=kind==='video'?4:2,out=[];try{var d=ac.__v043Api('video/classTypeList',{type:type,restricted:0},{timeout:1100,maxAttempts:2}),a=ac.__v047Arr(d);for(var i=0;i<a.length;i++){var x=a[i]||{},id=String(ac.pick(x,['classifyId','classTypeId','videoTypeId','typeId','id'],'')||''),name=String(ac.pick(x,['classifyTitle','classTypeTitle','classifyName','classTypeName','videoTypeName','title','name'],'')||'');if(id&&name&&!ac.__v047Internal(name))out.push({id:id,name:name,raw:x});}}catch(e){try{setItem('acfun_v050_catalog_error',String(e.message||e));}catch(e0){}}out=uniqueRows(out);if(out.length)ac.__v050Write(key,out);return out.length?out:(c.hit&&Array.isArray(c.data)?c.data:[]);};
ac.__v050Class=function(kind){var a=ac.__v050Catalog(kind),key=kind==='video'?'acfun_v050_class_video':'acfun_v050_class_anime',id=String(getMyVar(key,'')||''),hit=null;for(var i=0;i<a.length;i++)if(String(a[i].id)===id){hit=a[i];break;}if(!hit&&a.length){hit=a[0];putMyVar(key,String(hit.id));}return hit;};

function collectTagObjects(v,out,depth){if(depth>6||v===undefined||v===null)return;if(Array.isArray(v)){for(var i=0;i<v.length;i++)collectTagObjects(v[i],out,depth+1);return;}if(typeof v!=='object')return;var nm=ac.pick(v,['videoTagName','tagName','tagsTitle','tagTitle'],''),val=ac.pick(v,['videoTagValue','tagValue','videoTagKey','tagKey','value','id'],'');if(nm||val)out.push(v);var keys=['data','list','items','rows','tags','tagList','videoTags','videoTagList','content'];for(var j=0;j<keys.length;j++)if(v[keys[j]]!==undefined)collectTagObjects(v[keys[j]],out,depth+1);}
ac.__v050Tags=function(kind,cls){if(!cls||!cls.id)return [];var cid=String(cls.id),key='tags|'+kind+'|'+cid,c=ac.__v050Read(key,21600,172800);if(c.stale&&Array.isArray(c.data))return c.data;var raw=[],out=[],seen={};try{var d=ac.__v043Api('video/tags/getTagsZ',{videoTypeId:n(cid),classifyId:n(cid),restricted:0},{timeout:1100,maxAttempts:2});collectTagObjects(d,raw,0);for(var i=0;i<raw.length;i++){var x=raw[i]||{},name=String(ac.pick(x,['videoTagName','tagName','tagsTitle','tagTitle','name','title'],'')||''),value=String(ac.pick(x,['videoTagValue','tagValue','videoTagKey','tagKey','value','id'],name)||name),parent=String(ac.pick(x,['classifyId','videoTypeId','classTypeId','parentId'],'')||'');if(!name)name=value;if(!name||ac.__v047Internal(name))continue;if(parent&&parent!==cid)continue;var k=value+'|'+name;if(seen[k])continue;seen[k]=1;out.push({id:value,name:name,value:value,raw:x});}}catch(e){try{setItem('acfun_v050_tag_error',String(e.message||e));}catch(e0){}}if(out.length)ac.__v050Write(key,out);return out.length?out:(c.hit&&Array.isArray(c.data)?c.data:[]);};
ac.__v050Tag=function(kind,cls){var a=ac.__v050Tags(kind,cls),key=kind==='video'?'acfun_v050_tag_video':'acfun_v050_tag_anime',id=String(getMyVar(key,'')||'');for(var i=0;i<a.length;i++)if(String(a[i].id)===id)return a[i];return null;};
ac.__v050ListByTag=function(p,kind,cls,tag){var size=Number(getItem('acfun_page_size','8'))||8,sort=Number(ac.__v050Sort()),cid=String(cls.id),name=String(tag.name||''),value=String(tag.value||tag.id||name),base={classifyId:n(cid),videoTypeId:n(cid),page:p,pageNum:p,pageSize:size,limit:size,sortType:sort,restricted:0},tries=[];var p1={};for(var k in base)p1[k]=base[k];p1.tagsTitle=value;p1.tagTitle=value;p1.videoTagValue=value;p1.videoTagName=name;tries.push(p1);if(name&&name!==value){var p2={};for(var k2 in base)p2[k2]=base[k2];p2.tagsTitle=name;p2.tagTitle=name;p2.videoTagValue=value;p2.videoTagName=name;tries.push(p2);}for(var i=0;i<tries.length;i++){var l=ac.__v047ReqList('video/tagTitleList',tries[i],'v050-tag-list|'+kind+'|'+cid+'|'+value+'|'+name+'|'+i+'|'+sort+'|'+p);if(l.length)return l;}return [];};
ac.__v050CatalogList=function(p,kind){p=Number(p||1);var cls=ac.__v050Class(kind);if(!cls)return [];var tag=ac.__v050Tag(kind,cls),size=Number(getItem('acfun_page_size','8'))||8,sort=Number(ac.__v050Sort()),cid=String(cls.id);if(tag)return ac.__v050ListByTag(p,kind,cls,tag);return ac.__v047ReqList('video/getByClassify',{classifyId:n(cid),page:p,pageNum:p,pageSize:size,limit:size,sortType:sort,restricted:0},'v050-class|'+kind+'|'+cid+'|'+sort+'|'+p);};

ac.__v050ComicStations=function(){var key='comic-stations',c=ac.__v050Read(key,21600,172800);if(c.stale&&Array.isArray(c.data)&&c.data.length)return c.data;var src=[];try{src=ac.__v047ComicStations?ac.__v047ComicStations():[];}catch(e){}var out=[];for(var i=0;i<src.length;i++)if(src[i]&&src[i].id&&src[i].name)out.push(src[i]);out=uniqueRows(out);if(out.length)ac.__v050Write(key,out);return out.length?out:(c.hit&&Array.isArray(c.data)?c.data:[]);};
ac.__v050ComicStation=function(){var a=ac.__v050ComicStations(),id=String(getMyVar('acfun_v050_comic_station','')||''),hit=null;for(var i=0;i<a.length;i++)if(String(a[i].id)===id){hit=a[i];break;}if(!hit&&a.length){hit=a[0];putMyVar('acfun_v050_comic_station',String(hit.id));}return hit;};
ac.__v050ComicList=function(p){p=Number(p||1);var st=ac.__v050ComicStation();if(!st)return [];var size=Number(getItem('acfun_page_size','8'))||8,sort=Number(ac.__v050Sort()),key='comic-list|'+st.id+'|'+sort+'|'+p,c=ac.__v050Read(key,300,3600);if(c.fresh&&Array.isArray(c.data))return c.data;var list=[];if(p===1&&st.raw&&Array.isArray(st.raw.comicsBaseList)&&st.raw.comicsBaseList.length)list=st.raw.comicsBaseList.slice(0,size);if(!list.length)try{list=ac.__v047Arr(ac.__v043Api('comics/station/getStationComicsMore',{stationId:n(st.id),page:p,pageNum:p,pageSize:size,sortType:sort},{timeout:1200,maxAttempts:2}));}catch(e){try{setItem('acfun_v050_comic_error',String(e.message||e));}catch(e0){}}if(list.length){ac.__v050Write(key,list);return list;}return c.hit&&Array.isArray(c.data)?c.data:[];};
ac.__v050ShortList=function(p){p=Number(p||1);var lt=String(getMyVar('acfun_v050_short_load_type','3')||'3');return ac.__v047ReqList('video/list',{page:p,pageNum:p,pageSize:15,loadType:Number(lt)},'v050-short|'+lt+'|'+p);};

ac.addVideoCard=function(d,x,col){var info=ac.itemInfo(x),meta=[];if(info.watch)meta.push('▶ '+ac.fmtNum(info.watch));if(info.duration)meta.push(info.duration);if(!meta.length&&info.author)meta.push(info.author);var pic=ac.image(info.img);d.push({title:info.title,desc:meta.join('  '),img:pic,url:ac.detailUrl(info),col_type:col||'movie_2',extra:{video_id:info.id,video_title:info.title,video_img:info.img,video_uri:info.uri,video_data:JSON.stringify(info.raw||{}),pageTitle:info.title,longClick:[{title:'加入本地收藏',js:$.toString(function(){var s=getItem('acfun_core_src_v018','');if(!s)return 'toast://核心缓存不存在';eval(s);return ac.favoriteFromParams();})},{title:'复制标题',js:$.toString(function(){return 'copy://'+String(MY_PARAMS.video_title||'');})}]}});};

ac.__v050Top=function(d){var cur=ac.__v050Section();for(var i=0;i<ac.__v050MainSections.length;i++)(function(x){d.push({title:sel(x.name,cur===x.key),col_type:'text_5',url:$('hiker://empty#noLoading#').lazyRule(function(k){putMyVar('acfun_v050_section',k);putMyVar('acfun_v050_sort','1');refreshPage(false);return 'hiker://empty';},x.key),extra:{lineVisible:false}});})(ac.__v050MainSections[i]);};
ac.__v050Quick=function(d){var cur=ac.__v050Section(),items=[{name:'短视频',key:'short'},{name:'收藏',page:'acfun_favorites'},{name:'历史',page:'acfun_history'},{name:'设置',page:'acfun_settings'}];for(var i=0;i<items.length;i++)(function(x){if(x.key)d.push({title:sel(x.name,cur===x.key),col_type:'text_4',url:$('hiker://empty#noLoading#').lazyRule(function(){putMyVar('acfun_v050_section','short');refreshPage(false);return 'hiker://empty';}),extra:{lineVisible:false}});else d.push({title:x.name,col_type:'text_4',url:'hiker://page/'+x.page+'?rule=ACFun&simple=true#noRecordHistory#',extra:{inheritTitle:false,pageTitle:x.name,lineVisible:false}});})(items[i]);};
function addScroll(d,rows,selected,key,clearKey){for(var i=0;i<rows.length;i++)(function(x){d.push({title:sel(x.name,String(selected)===String(x.id)),col_type:'scroll_button',url:$('hiker://empty#noLoading#').lazyRule(function(v,k,ck){putMyVar(k,String(v));if(ck)clearMyVar(ck);refreshPage(false);return 'hiker://empty';},x.id,key,clearKey||''),extra:{lineVisible:false}});})(rows[i]);}
ac.__v050Bars=function(d){var s=ac.__v050Section();if(s==='featured'||s==='lifan'){var r=s==='lifan'?1:0,rows=ac.__v050Stations(r),key=r?'acfun_v050_station_lifan':'acfun_v050_station_featured',cur=String(getMyVar(key,'')||'');if(!cur&&rows.length)cur=String(rows[0].id);addScroll(d,rows,cur,key,'');}else if(s==='comic'){var comics=ac.__v050ComicStations(),cc=String(getMyVar('acfun_v050_comic_station','')||'');if(!cc&&comics.length)cc=String(comics[0].id);addScroll(d,comics,cc,'acfun_v050_comic_station','');}else if(s==='anime'||s==='video'){var classes=ac.__v050Catalog(s),ck=s==='video'?'acfun_v050_class_video':'acfun_v050_class_anime',tk=s==='video'?'acfun_v050_tag_video':'acfun_v050_tag_anime',cs=String(getMyVar(ck,'')||'');if(!cs&&classes.length)cs=String(classes[0].id);addScroll(d,classes,cs,ck,tk);var cls=ac.__v050Class(s),tags=ac.__v050Tags(s,cls),ts=String(getMyVar(tk,'')||'');if(tags.length){d.push({title:sel('全部',!ts),col_type:'scroll_button',url:$('hiker://empty#noLoading#').lazyRule(function(k){clearMyVar(k);refreshPage(false);return 'hiker://empty';},tk),extra:{lineVisible:false}});addScroll(d,tags,ts,tk,'');}}else if(s==='short'){var st=String(getMyVar('acfun_v050_short_load_type','3')||'3');addScroll(d,ac.__v050ShortTabs,st,'acfun_v050_short_load_type','');}if(s!=='short'){var sort=ac.__v050Sort();for(var q=0;q<ac.__v050Sorts.length;q++)(function(x){d.push({title:sel(x.name,sort===x.value),col_type:'text_4',url:$('hiker://empty#noLoading#').lazyRule(function(v){putMyVar('acfun_v050_sort',v);refreshPage(false);return 'hiker://empty';},x.value),extra:{lineVisible:false}});})(ac.__v050Sorts[q]);}};
ac.__v050SectionTitle=function(){var s=ac.__v050Section();if(s==='short')return '短视频';var base={featured:'精选推荐',comic:'漫画',anime:'动漫',video:'视频',lifan:'里番'}[s]||'内容';try{if(s==='featured'||s==='lifan'){var st=ac.__v050Station(s==='lifan'?1:0);if(st)base+=' · '+st.name;}else if(s==='comic'){var c=ac.__v050ComicStation();if(c)base+=' · '+c.name;}else if(s==='anime'||s==='video'){var cl=ac.__v050Class(s),tg=ac.__v050Tag(s,cl);if(cl)base+=' · '+cl.name;if(tg)base+=' · '+tg.name;}}catch(e){}return base;};

ac.home=function(){var d=[],p=page(),s=ac.__v050Section();if(p===1){d.push({title:'搜索',desc:'视频 / UP / 标签',col_type:'input',url:$.toString(function(){if(!input)return 'hiker://empty';return 'hiker://search?s='+encodeURIComponent(input)+'&rule=ACFun';}),extra:{defaultValue:'',lineVisible:false}});ac.__v050Top(d);ac.__v050Quick(d);ac.__v050Bars(d);d.push({title:ac.__v050SectionTitle(),col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}});}var list=[];try{if(s==='featured')list=ac.__v050StationList(p,0);else if(s==='lifan')list=ac.__v050StationList(p,1);else if(s==='comic')list=ac.__v050ComicList(p);else if(s==='short')list=ac.__v050ShortList(p);else list=ac.__v050CatalogList(p,s);}catch(e){try{setItem('acfun_v050_home_error',String(e.message||e));}catch(e0){}}if(s==='comic'){for(var i=0;i<list.length;i++){var ci=ac.__v047ComicInfo(list[i]);if(!ci.id)continue;d.push({title:ci.title,desc:ci.desc,img:ac.image(ci.img),col_type:'movie_3',url:ac.__v047ComicUrl(),extra:{inheritTitle:false,pageTitle:ci.title,comics_id:ci.id,comics_title:ci.title,content_kind:'comic'}});}}else for(var j=0;j<list.length;j++)ac.addVideoCard(d,list[j],'movie_2');if(!list.length&&p===1)d.push({title:'这里暂时没有内容',desc:'可以切换上方分类或稍后再试',col_type:'text_center_1',url:'hiker://empty'});setResult(d);};

ac.detail=function(){return oldDetail.call(ac);};
try{setItem('acfun_test_runtime','0.5.0-rc1 native UI + strict parent taxonomy');}catch(e){}
})();
