/* ACFun 0.5.0-test.1 Local-First final overlay over Stable 0.4.9 */
(function(){
if(typeof ac!=='object')throw new Error('ACFun Stable 0.4.9 runtime missing');
var VERSION='0.5.0-test.1',BUILD=50001;
var ROOT='hiker://files/rules/asset-core-local/acfun-test/b50001/';
var META=ROOT+'bundle_meta.json';
var BUNDLE=ROOT+'runtime_bundle.js';
var TRAMP="var ac=$.require('acfun');";
try{setItem('acfun_core_src_v018',TRAMP);setItem('acfun_core_src_v019',TRAMP);setItem('acfun_remote_bundle_src',TRAMP);}catch(e){}
ac.localFirstVersion=VERSION;ac.localFirstBuild=BUILD;ac.build='2026.08.25-local-0.5.0-test.1';ac.runtimeMode='stable-049-local-first';
ac.localFirstInfo=function(){var m={};try{if(fileExist(META))m=JSON.parse(String(readFile(META)||'{}'));}catch(e){}return{version:VERSION,build:BUILD,ready:fileExist(BUNDLE),modules:Number(m.modules||0),bytes:Number(m.bytes||0),sourceRef:String(m.sourceRef||''),installedAt:Number(m.installedAt||0),imageDecoder:!!m.imageDecoder};};
ac.localUpdatePage=function(){setPageTitle('ACFun 本地化版本');var d=[],m=ac.localFirstInfo();d.push({title:'ACFun '+VERSION,desc:'Build '+BUILD+' · Stable 0.4.9 业务基线 Local-First',col_type:'long_text',url:'hiker://empty'});d.push({title:'本地运行包',desc:(m.ready?'已就绪':'未完成')+' · '+m.modules+' 模块 · '+m.bytes+' B\nsource '+(m.sourceRef||'--'),col_type:'text_1',url:'hiker://empty'});d.push({title:'检查更新',desc:'更新由“我的规则仓库”统一管理；本程序不再通过 Remote Manager 自行切 release。',col_type:'text_1',url:$('hiker://empty#noLoading#').lazyRule(function(){var loading=false;try{showLoading('检查 ACFun 测试版…');loading=true;var repo='huoguotiankong/asset-core-7f3',h=JSON.parse(String(fetch('https://api.github.com/repos/'+repo+'/branches/main?_t='+Date.now(),{timeout:2600,headers:{'Cache-Control':'no-cache','Accept':'application/vnd.github+json'}})||'{}')),sha=String(h&&h.commit&&h.commit.sha||'');if(!/^[0-9a-f]{40}$/i.test(sha))throw new Error('main HEAD 无效');var c=JSON.parse(String(fetch('https://raw.githubusercontent.com/'+repo+'/'+sha+'/apps/video/acfun/channels.json',{timeout:3000,headers:{'Cache-Control':'no-cache'}})||'{}')),a=c&&c.channels||[],t=null;for(var i=0;i<a.length;i++)if(String(a[i]&&a[i].channel||'')==='test'){t=a[i];break;}hideLoading();loading=false;if(!t)return'toast://未发现测试通道';return Number(t.build||0)>50001?'toast://发现 '+String(t.version||'新测试版')+' / Build'+Number(t.build||0)+'，请从“我的规则仓库”覆盖更新':'toast://当前已是最新测试版 '+String(t.version||'0.5.0-test.1');}catch(e){if(loading)try{hideLoading();}catch(_e){}return'toast://检查失败：'+String(e.message||e);}})});d.push({title:'本地化诊断',desc:'只读取本地 bundle 状态，不重新加载远程 Bootstrap。',col_type:'text_1',url:$('hiker://empty#noLoading#').lazyRule(function(){try{var p='hiker://files/rules/asset-core-local/acfun-test/b50001/bundle_meta.json',m=fileExist(p)?JSON.parse(String(readFile(p)||'{}')):{};return'confirm://ACFun 0.5.0-test.1 / Build50001\nbundle '+(fileExist('hiker://files/rules/asset-core-local/acfun-test/b50001/runtime_bundle.js')?'ready':'missing')+'\nmodules '+String(m.modules||0)+'\nbytes '+String(m.bytes||0)+'\nimage decoder '+(m.imageDecoder?'ready':'missing')+'\nsource '+String(m.sourceRef||'--');}catch(e){return'toast://诊断失败：'+String(e.message||e);}})});d.push({title:'说明',desc:'首页/分类/搜索/详情/播放/漫画/封面解密均沿用 Stable 0.4.9；本版只迁移代码交付、启动与点击 Runtime 入口。',col_type:'long_text',url:'hiker://empty'});setResult(d);};
})();
