/* 我的规则仓库 v3.5.0 - app style program detail */
(function(R){
R.detailPage=function(){
var id=String((MY_PARAMS&&MY_PARAMS.hc_repo_item_id)||getParam('id')||''),item=this.findById(id,false),d=[];if(!item){setResult([{title:'程序不存在或云端索引已更新',url:'hiker://empty',col_type:'text_center_1'}]);return;}setPageTitle(item.name);try{setPagePicUrl(this.iconOf(item));}catch(e){}var st=this.statusOf(item),iv=this.installedVersion(item),modeDesc=item.mode==='remote'?'自用远程代码版':(item.mode==='share'?'纯本地分享版':'本地程序'),last=this.lastImportedTime(item);
d.push({title:item.name,desc:'v'+(item.version||'未标记')+' · '+modeDesc+'\n'+this.statusMark(item),img:this.iconOf(item),pic_url:this.iconOf(item),url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});
d.push({title:st==='可更新'?'立即更新':'导入 / 覆盖',col_type:'text_2',url:$('#noLoading#').lazyRule(function(raw){return $.require('hiker://page/ruleRepoCore').importRule(raw);},JSON.stringify(item.raw)),extra:{lineVisible:false}});d.push({title:this.isFav(item)?'★ 已收藏':'☆ 收藏',col_type:'text_2',url:$('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id);if(!x)return'toast://程序不存在';var on=r.toggleFav(x);refreshPage(false);return'toast://'+(on?'已收藏':'已取消收藏');},item.id),extra:{lineVisible:false}});
d.push(this.statCard('云端',item.version||'--','hiker://empty'));d.push(this.statCard('已记录',iv||'--','hiker://empty'));d.push(this.statCard('状态',st,'hiker://empty'));d.push(this.statCard('模式',this.modeText(item.mode),'hiker://empty'));
this.pushSpacer(d);this.pushSection(d,'程序信息',item.desc||'暂无说明');d.push({title:'分类',desc:item.categoryName+' / '+item.subCategory,url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行模式',desc:modeDesc,url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'更新时间',desc:item.updatedAt||'未标记',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'最近导入',desc:last?this.formatTime(last):'未记录',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});if(item.bytes)d.push({title:'包体大小',desc:Math.round(Number(item.bytes)/1024)+' KB',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
if((item.tags||[]).length){this.pushSpacer(d);this.pushSection(d,'标签','');(item.tags||[]).forEach(function(t){d.push({title:'#'+t,col_type:'flex_button',url:'hiker://page/ruleRepoSearch?rule=&simple=true&kw='+encodeURIComponent(t)});});}
this.pushSpacer(d);this.pushSection(d,'管理操作','只操作仓库状态，不伪造海阔系统级删除/打开能力。');d.push(this.quickCard('检查版本',$('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id,true);if(!x)return'toast://程序不存在';return'toast://'+x.name+'：'+r.statusOf(x)+' / 云端 '+x.version;},item.id)));d.push(this.quickCard('备份状态','hiker://page/ruleRepoSettings?rule=&simple=true'));d.push(this.quickCard('导入记录','hiker://page/ruleRepoHistory?rule=&simple=true'));
d.push({title:'复制仓库路径',desc:item.path||'',url:'copy://'+(item.path||''),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清除该程序版本记录',desc:'只清除“已记录 / 可更新”判断依据，不删除海阔里已安装的小程序。',url:$('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore');r.removeInstalled(id);refreshPage(false);return'toast://版本记录已清除';},item.id),col_type:'text_1',extra:{lineVisible:false}});setResult(d);
};
})(HikerRuleRepo);
