/* 我的规则仓库 v3.5.0 - settings, backup and about center */
(function(R){
R.settingsPage=function(){
setPageTitle('设置');var d=[],cache=this.cacheMs();this.pushNav(d,'settings');
this.pushSection(d,'仓库','索引、缓存与 Core 管理');d.push({title:'索引缓存',desc:Math.round(cache/1000)+' 秒 · 降低重复读取云端索引的频率',url:$('0秒,30秒,60秒,180秒,600秒','选择缓存时间').select(function(){var n=Number(String(input||'60').replace(/\D/g,''));var r=$.require('hiker://page/ruleRepoCore');r.setSetting('cache_ms',n*1000);r.clearManifestCache();refreshPage(false);return'toast://已设置';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'刷新云端索引',desc:'清空 manifest 缓存，下次读取立即拉取最新索引。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearManifestCache();return'toast://云端索引缓存已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'Core 更新与回退',desc:'稳定版入口只在 Candidate 实机验证通过后切换。',url:'hiker://page/ruleRepoUpdate?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'备份与恢复','备份收藏、版本记录、最近使用、搜索/导入历史和筛选设置。');d.push({title:'复制状态备份',desc:'生成 JSON 并复制到剪贴板；不包含 Cookie、Token 或账号凭据。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');return'copy://'+r.exportState();}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'从备份恢复',desc:'粘贴由本程序生成的 rule-repo-state JSON。',url:$('粘贴备份 JSON','').input(function(){try{var r=$.require('hiker://page/ruleRepoCore');r.restoreState(String(input||''));r.clearSelection();refreshPage(false);return'toast://备份已恢复';}catch(e){return'toast://恢复失败：'+String(e.message||e);}}),col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'记录','这些操作不会删除海阔里已安装的小程序');d.push({title:'导入记录',desc:'查看最近导入 / 更新过的程序。',url:'hiker://page/ruleRepoHistory?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空搜索历史',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearSearchHistory();return'toast://搜索历史已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空最近使用',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearRecent();return'toast://最近使用已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空导入历史',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearImportHistory();refreshPage(false);return'toast://导入历史已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空版本记录',desc:'清除“已记录 / 可更新”判断依据。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearInstalled();refreshPage(false);return'toast://版本记录已清空';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空收藏',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearFavorites();refreshPage(false);return'toast://收藏已清空';}),col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'筛选与界面','首页保持轻量，复杂筛选集中到分类中心。');d.push({title:'重置全部筛选',desc:'重置分类、子分类、标签、排序、模式、首页状态与搜索关键词。',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearAllFilters();clearMyVar('hc_repo_home_view');clearMyVar('hc_repo_home_category');clearMyVar('hc_repo_home_sort');clearMyVar('hc_repo_search_kw');r.clearSelection();refreshPage(false);return'toast://筛选状态已重置';}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'界面模式',desc:'使用海阔原生组件与透明背景，自动跟随宿主浅色 / 深色主题。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});
this.pushSpacer(d);this.pushSection(d,'关于','版本与架构');d.push({title:'版本与更新日志',desc:'Core '+this.version+' · build '+this.build,url:'hiker://page/ruleRepoAbout?rule=&simple=true',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'模块架构',desc:'Repository / Filter / Management / UI / Home / Category / Search / Updates / Detail / History / Settings。',url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);
};
R.aboutPage=function(){setPageTitle('关于');var d=[];d.push({title:'我的规则仓库',desc:'Core '+this.version+' · build '+this.build+'\n海阔视界专属 · 规则管理中心',img:this.iconOf(this.findById('rule-repo')||{}),pic_url:this.iconOf(this.findById('rule-repo')||{}),url:'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});this.pushSection(d,'核心功能','分类管理 · 子分类 · 标签 · 搜索 · 版本记录 · 收藏 · 状态备份 · 批量管理');d.push(this.quickCard('分类管理','hiker://page/ruleRepoCategory?rule=&simple=true'));d.push(this.quickCard('搜索中心','hiker://page/ruleRepoSearch?rule=&simple=true'));d.push(this.quickCard('更新中心','hiker://page/ruleRepoUpdates?rule=&simple=true'));this.pushSpacer(d);this.pushSection(d,'架构','轻量 Shell → Bootstrap → Remote Manager → Release Modules → 海阔 require 缓存。');var log='';try{log=this.apiText('apps/tools/rule-repo/CHANGELOG.md');}catch(e){log='更新日志读取失败：'+String(e.message||e);}d.push({title:'更新日志',desc:log,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);};
})(HikerRuleRepo);
