/* MyAv 0.1.0-test.6 UI-A - home/search/actress hub */
(function(R,C){
if(!R||!C)throw new Error('MyAv runtime/core missing for Test6 UI-A');
R.version='0.1.0-test.6';R.build=10106;R.bootstrapUrl='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/myav/bootstrap_test_v6_b10106.js';
var A='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/myav/assets/';
function S(v){return v===undefined||v===null?'':String(v);}function P(n,d){var v='';try{v=getParam(n,'');}catch(e){}return v?v:(d||'');}function dec(v){try{return decodeURIComponent(S(v));}catch(e){return S(v);}}function pg(){try{return parseInt(MY_PAGE,10)||1;}catch(e){return 1;}}
function sec(t,d){return{title:'▌ '+t,desc:d||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}};}function emp(t,d){return{title:t,desc:d||'',url:'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}};}function chip(t,u){return{title:t,url:u,col_type:'scroll_button',extra:{lineVisible:false}};}function state(t,id,cur,k){return chip((id===cur?'● ':'')+t,$('#noLoading#').lazyRule(function(a,b){putMyVar(a,b);refreshPage(false);return'hiker://empty';},k,id));}function icon(t,img,u){return{title:t,img:img,pic_url:img,url:u,col_type:'icon_small_4',extra:{lineVisible:false}};}function col(k){return C.layoutGet(k,'2')==='3'?'movie_3':'movie_2';}
function card(m,s,k){var a=[];if(m.code)a.push(S(m.code).toUpperCase());if(m.date)a.push(m.date);if(m.flags&&m.flags.length)a.push(m.flags.join(' · '));return{title:m.title||m.code||'影片',desc:a.join(' · '),img:m.img||'',pic_url:m.img||'',url:C.page('myavDetail',{u:m.href,code:m.code||'',sec:s||m.section||'normal'}),col_type:col(k||'home'),extra:{lineVisible:false,pageTitle:m.code||m.title||'影片'}};}
function list(u,s,p){var f=C.fetchHtml(u),t=C.paginatedUrl(u,p,f),h=p===1?f:C.fetchHtml(t);return{url:t,items:C.parseMovies(h,s)};}function eroute(x,s,e){var p={u:x.href||x.key,name:x.name||x.text||'资料',sec:s||x.sec||x.section||'normal',etype:e||x.etype||'entity'};if(x.rawImg)p.img=x.rawImg;else if(x.img)p.img=x.img;return C.page('myavList',p);}
R.home=function(){var d=[],p=pg(),s=getMyVar('myav_home_section','normal'),u=C.sectionUrl(s),r=list(u,s,p),i;if(p===1){d.push({title:'MyAv',desc:C.sectionName(s)+'资料库 · 磁力 · 预览 · 第三方播放',img:C.appIcon,pic_url:C.appIcon,url:'hiker://empty',col_type:'icon_1_left_pic',extra:{lineVisible:false}});d.push(state('有码','normal',s,'myav_home_section'));d.push(state('欧美','western',s,'myav_home_section'));d.push(state('国产','domestic',s,'myav_home_section'));d.push(state('无码','uncensored',s,'myav_home_section'));d.push(icon('搜索',A+'search.svg',C.page('myavSearch',{})));d.push(icon('筛选',A+'filter.svg',C.page('myavFilters',{})));d.push(icon('女优',A+'actress.svg',C.page('myavActresses',{})));d.push(icon('分类',A+'category.svg',C.page('myavIndices',{})));d.push(icon('排行',A+'rank.svg',C.page('myavRankings',{})));d.push(icon('收藏',A+'favorite.svg',C.page('myavFavorites',{})));d.push(icon('历史',A+'history.svg',C.page('myavHistory',{})));d.push(icon('设置',A+'settings.svg',C.page('myavSettings',{})));d.push(sec(C.sectionName(s)+' · 最新更新','原站实时数据 · '+C.layoutGet('home','2')+' 列'));}if(!r.items.length)d.push(emp('当前频道暂无可显示内容',r.url));for(i=0;i<r.items.length;i++)d.push(card(r.items[i],s,'home'));setResult(d);};
R.search=function(){var d=[],p=pg(),k=getMyVar('myav_search_kind','normal'),q=getMyVar('myav_search_kw',''),xs=[['有码','normal'],['欧美','western'],['国产','domestic']],i,r,h;try{if(MY_KEYWORD)q=S(MY_KEYWORD);}catch(e){}q=S(q).trim();if(p===1){setPageTitle('搜索');for(i=0;i<xs.length;i++)d.push(state(xs[i][0],xs[i][1],k,'myav_search_kind'));d.push({title:q||'',desc:'',url:"(function(){var q=String(input||'').trim();putMyVar('myav_search_kw',q);try{$.require('myav').core().pushSearchHistory(q);}catch(e){}refreshPage(false);return 'hiker://empty';})()",col_type:'input',extra:{defaultValue:q,hint:'输入番号 / 名称',lineVisible:false}});d.push(chip('女优库',C.page('myavActresses',{})));if(q)d.push(chip('清空',$('#noLoading#').lazyRule(function(){putMyVar('myav_search_kw','');refreshPage(false);return'hiker://empty';})));h=C.searchHistory();if(h.length){d.push(sec('最近搜索','点击直接搜索'));for(i=0;i<Math.min(h.length,6);i++)d.push(chip(h[i],$('#noLoading#').lazyRule(function(v){putMyVar('myav_search_kw',v);refreshPage(false);return'hiker://empty';},h[i])));d.push(chip('清除记录',$('#noLoading#').lazyRule(function(){try{$.require('myav').core().clearSearchHistory();}catch(e){}refreshPage(false);return'hiker://empty';})));}d.push(sec('搜索范围','番号 / 标题 / 演员 / 片商 / TAG · '+C.layoutGet('search','2')+' 列'));}if(!q){d.push(emp('输入关键词开始搜索','女优资料请进入“女优库”'));setResult(d);return;}r=C.search(k,q,p);if(p===1)d.push(sec('搜索结果',q+' · 当前页 '+r.items.length+' 条'));if(!r.items.length)d.push(emp('没有搜索结果','可切换频道或进入女优库'));for(i=0;i<r.items.length;i++)d.push(card(r.items[i],k,'search'));setResult(d);};
R.actresses=function(){var d=[],p=pg(),ds=C.actorIndexDefs(),kid=getMyVar('myav_actor_index','normalActress'),q=getMyVar('myav_actor_filter',''),df=ds[0],i,u,f,t,h,it,x;for(i=0;i<ds.length;i++)if(ds[i].id===kid){df=ds[i];break;}u=C.indexUrlExact(df.label);if(!u){setPageTitle('女优');setResult([emp('未找到 '+df.label+' 入口','设置中重新发现导航后重试')]);return;}f=C.fetchHtml(u);t=C.paginatedUrl(u,p,f);h=p===1?f:C.fetchHtml(t);it=C.parseIndexEntries(h,t,df.label);q=S(q).trim();if(q){var z=[];for(i=0;i<it.length;i++)if(S(it[i].text).toLowerCase().indexOf(q.toLowerCase())>=0)z.push(it[i]);it=z;}if(p===1){setPageTitle('女优');d.push({title:'女优资料库',desc:'有码 / 欧美 / 国产女优与男优 · 原站分页索引',img:A+'actress.svg',pic_url:A+'actress.svg',url:'hiker://empty',col_type:'icon_1_left_pic',extra:{lineVisible:false}});for(i=0;i<ds.length;i++)d.push(state(ds[i].label,ds[i].id,kid,'myav_actor_index'));d.push({title:q||'',desc:'',url:"(function(){var q=String(input||'').trim();putMyVar('myav_actor_filter',q);refreshPage(false);return 'hiker://empty';})()",col_type:'input',extra:{defaultValue:q,hint:'筛选当前页姓名',lineVisible:false}});d.push(chip('演员收藏',$('#noLoading#').lazyRule(function(v){putMyVar('myav_fav_tab','actors');return v;},C.page('myavFavorites',{}))));d.push(sec(df.label,(q?'本页筛选：'+q+' · ':'')+C.layoutGet('actresses','2')+' 列'));}if(!it.length)d.push(emp(q?'当前页没有匹配姓名':'当前页未识别到演员','姓名筛选仅作用当前已加载页面'));for(i=0;i<it.length;i++){x=it[i];d.push({title:x.text,desc:df.etype==='actor'?'男优资料':'女优资料',img:x.img||A+'actress.svg',pic_url:x.img||A+'actress.svg',url:eroute({href:x.href,text:x.text,rawImg:x.rawImg},df.sec,df.etype),col_type:col('actresses'),extra:{lineVisible:false,pageTitle:x.text}});}setResult(d);};
R.indexList=function(){var d=[],p=pg(),u=dec(P('u','')),n=dec(P('name','分类索引')),s=P('sec','');if(!u){setResult([emp('缺少索引地址','')]);return;}if(!s)s=C.sectionForIndex(u,n);var f=C.fetchHtml(u),t=C.paginatedUrl(u,p,f),h=p===1?f:C.fetchHtml(t),it=C.parseIndexEntries(h,t,n),i,x,e=C.entityType(n);if(p===1){setPageTitle(n);d.push(sec(n,'原站分页索引 · 点击进入资料页'));}if(!it.length)d.push(emp('当前页未识别到索引条目',t));for(i=0;i<it.length;i++){x=it[i];d.push({title:x.text,desc:e==='actress'?'女优资料':e==='actor'?'男优资料':'查看资料与相关作品',img:x.img||'',pic_url:x.img||'',url:eroute({href:x.href,text:x.text,rawImg:x.rawImg},x.section||s,e),col_type:x.img?col('actresses'):'flex_button',extra:{lineVisible:false,pageTitle:x.text}});}setResult(d);};
})(MyAvRemoteRuntime,MyAvCore);
