/* 我的规则仓库 3.5.3-rc4 - app style version center */
(function(R){
R.channelPage=function(parent){
 setPageTitle(parent.name);var d=[],meta=this.channelMeta(parent),cs,i,stable=null,test=null,local=null;if(!meta){setResult([{title:'版本信息暂时不可用',desc:'请稍后重试，或返回首页执行一次同步。',url:'hiker://page/ruleRepoHome?rule=&simple=true',col_type:'text_center_1',extra:{lineVisible:false}}]);return;}try{setPagePicUrl(this.iconOf(parent));}catch(e){}
 cs=meta.channels||[];for(i=0;i<cs.length;i++){if(cs[i].channel==='stable')stable=cs[i];else if(cs[i].channel==='test')test=cs[i];else if(cs[i].channel==='local')local=cs[i];}
 var selfRepo=String(parent.id||'')==='rule-repo',coexist=selfRepo||!!(parent.raw&&parent.raw.allowCoexist),count=(stable?1:0)+(test?1:0)+(local?1:0),currentText=selfRepo?(this.isTestChannel()?'测试版 '+this.version:'正式版 '+this.version):'按版本卡选择需要的版本',openName=selfRepo&&this.isTestChannel()?'我的规则仓库·测试版':String(parent.name||'');
 d.push(this.hero(parent.name,'版本中心 · '+count+' 个可用版本\n'+(coexist?'稳定使用 / 抢先体验 / 独立本地':'正式与测试同名切换'),this.iconOf(parent),'hiker://empty'));
 d.push(this.primaryAction('打开程序','hiker://home@'+openName+'||hiker://home'));d.push(this.secondaryAction('返回程序库','hiker://page/ruleRepoHome?rule=&simple=true'));
 d.push(this.sectionLine());d.push(this.metricInfo('版本',count));d.push(this.metricInfo('正式',stable?'有':'无'));d.push(this.metricInfo('测试',test?'有':'无'));d.push(this.metricInfo('本地',local?'有':'无'));
 this.pushSection(d,'常用操作','');d.push(this.quickAction(this.isFav(parent)?'已收藏':'收藏','favorite',$('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id);if(!x)return'toast://程序不存在';var on=r.toggleFav(x);refreshPage(false);return'toast://'+(on?'已收藏':'已取消收藏');},parent.id)));d.push(this.quickAction('同步版本','updates',$('#noLoading#').lazyRule(function(){showLoading('正在同步…');try{var r=$.require('hiker://page/ruleRepoCore'),x=r.syncManifest();hideLoading();if(!x.ok)return'toast://同步失败，已保留当前目录';refreshPage(false);return x.fresh?'toast://版本信息已更新':'toast://当前已是最新信息';}catch(e){hideLoading();return'toast://同步失败';}})));d.push(this.quickAction('活动记录','history','hiker://page/ruleRepoHistory?rule=&simple=true'));d.push(this.quickAction('设置','settings','hiker://page/ruleRepoSettings?rule=&simple=true'));
 this.pushSection(d,'当前状态',currentText);this.pushSection(d,'选择版本','点击版本卡即可导入 / 覆盖');if(stable)d.push(this.channelProductCard(parent,stable,selfRepo&&!this.isTestChannel()));if(test)d.push(this.channelProductCard(parent,test,selfRepo&&this.isTestChannel()));if(local)d.push(this.channelProductCard(parent,local,false));
 d.push(this.sectionLine());this.pushSection(d,'程序信息','');d.push(this.compactInfo('分类',String(parent.categoryName||'--')+(parent.subCategory?' · '+parent.subCategory:''),'hiker://page/ruleRepoCategory?rule=&simple=true'));d.push(this.compactInfo('更新时间',String(parent.updatedAt||meta.updatedAt||'--'),'hiker://empty'));if((parent.tags||[]).length){(parent.tags||[]).slice(0,8).forEach(function(t){d.push({title:'#'+t,col_type:'scroll_button',url:'hiker://page/ruleRepoSearch?rule=&simple=true&kw='+encodeURIComponent(t),extra:{lineVisible:false}});});}
 this.pushSection(d,'版本关系','');if(coexist)d.push(this.compactInfo('恢复保障','规则仓库正式版与测试版分名并存。测试异常时可直接从正式版重新导入测试版。','hiker://empty'));else if(local)d.push(this.compactInfo('覆盖规则','正式版与测试版同名覆盖；本地版使用独立名称，可与远程版同时保留。','hiker://empty'));else d.push(this.compactInfo('覆盖规则','正式版与测试版同名覆盖。测试异常时重新导入正式版即可恢复。','hiker://empty'));
 d.push(this.sectionLine());this.pushNav(d,'home');setResult(d);
};
})(HikerRuleRepo);
