/* 我的规则仓库 3.5.3-rc4 - native search */
(function(R){
R.searchPage=function(){
 setPageTitle('搜索');var d=[],items;try{items=this.items(false);}catch(e){setResult([{title:'搜索暂时不可用',desc:this.friendlyError(e),url:'hiker://page/ruleRepoHome?rule=&simple=true',col_type:'text_center_1',extra:{lineVisible:false}}]);return;}
 var raw=String(getParam('kw','')||getParam('s','')||''),pkw=this.safeDecodeKeyword(raw),kw=pkw||this.safeDecodeKeyword(getMyVar('hc_repo_search_kw','')),scope=String(getMyVar('hc_repo_search_scope','all')||'all'),mode=String(getMyVar('hc_repo_search_mode','all')||'all');if(pkw){putMyVar('hc_repo_search_kw',pkw);this.recordSearch(pkw);}
 d.push({title:'搜索名称、功能或标签',url:$.toString(function(){var q=String(input||'').trim();putMyVar('hc_repo_search_kw',q);var r=$.require('hiker://page/ruleRepoCore');if(q)r.recordSearch(q);refreshPage(false);return'hiker://empty';}),col_type:'input',extra:{defaultValue:kw,titleVisible:false,onChange:$.toString(function(){putMyVar('hc_repo_search_kw',String(input||''));})}});
 d.push(this.scopeChip('全部','all',scope,'hc_repo_search_scope'));d.push(this.scopeChip('可更新','updates',scope,'hc_repo_search_scope'));d.push(this.scopeChip('收藏','favorites',scope,'hc_repo_search_scope'));d.push({title:mode==='all'?'运行方式':(mode==='remote'?'远程':'本地'),col_type:'scroll_button',url:$('全部,远程,本地','运行方式').select(function(){var map={'全部':'all','远程':'remote','本地':'local'};putMyVar('hc_repo_search_mode',map[String(input||'全部')]||'all');refreshPage(false);return'hiker://empty';}),extra:{lineVisible:false}});
 var pool=items.slice();if(scope==='updates')pool=pool.filter(function(x){return x.entryType!=='channel-group'&&R.statusOf(x)==='可更新';});else if(scope==='favorites')pool=pool.filter(function(x){return R.isFav(x);});if(mode==='remote')pool=pool.filter(function(x){return x.mode==='remote';});else if(mode==='local')pool=pool.filter(function(x){return x.mode!=='remote';});
 if(kw){var a=pool.filter(function(x){return R.matchKeyword(x,kw);});d.push(this.sectionLine());this.pushSection(d,'搜索结果',a.length+' 个结果 · '+kw);a.forEach(function(x){d.push(R.itemCard(x));});if(!a.length)this.pushEmpty(d,'没有找到相关程序','换一个名称、功能或标签试试。');}
 else{var hist=this.searchHistory(),tags=this.popularTags(items,8),recent=this.recentItems?this.recentItems(items,4):[];if(hist.length){d.push(this.sectionLine());this.pushSection(d,'最近搜索','');hist.slice(0,6).forEach(function(x){d.push({title:x,col_type:'flex_button',url:$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_search_kw',v);var r=$.require('hiker://page/ruleRepoCore');r.recordSearch(v);refreshPage(false);return'hiker://empty';},x)});});d.push({title:'清空',col_type:'flex_button',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearSearchHistory();refreshPage(false);return'toast://已清空';})});}if(tags.length){d.push(this.sectionLine());this.pushSection(d,'热门标签','');tags.forEach(function(t){d.push({title:'#'+t.name,col_type:'flex_button',url:$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_search_kw',v);refreshPage(false);return'hiker://empty';},t.name)});});}if(recent.length){d.push(this.sectionLine());this.pushSection(d,'最近使用','');recent.forEach(function(x){d.push(R.recentTile(x));});}if(!hist.length&&!tags.length&&!recent.length)this.pushEmpty(d,'搜索你的程序','支持名称、描述、标签、分类和版本。');}
 d.push(this.sectionLine());this.pushNav(d,'search');setResult(d);
};
})(HikerRuleRepo);
