/* MyAv 0.1.1-test.4 · external search adapter */
var MyAvSearchFix10204=(function(){
var VERSION='0.1.1-test.4',BUILD=10204;
var ROOT='hiker://files/rules/asset-core-local/myav-test/b10204/';
var BASE_ENTRY=ROOT+'base_011t3_entry.js';
var BASE_REF='9bce0b2471f58f73c5abc0b4484b022e808fb18a';
var BASE_PATH='apps/video/myav/releases/0.1.1-test.3/local_entry.js';
var SEARCH_KEY='myav_external_search_targets_v1';
var BASE_CACHE=null;
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function urls(ref,path){return['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/'+ref+'/'+path,'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@'+ref+'/'+path,'https://github.com/huoguotiankong/asset-core-7f3/raw/'+ref+'/'+path];}
function ensureFile(local,ref,path,marker){if(fileExist(local)){try{var old=String(readFile(local)||'');if(!bad(old)&&old.indexOf(marker)>=0)return local;}catch(_e){}try{deleteFile(local);}catch(_e2){}}var us=urls(ref,path),es=[],i,s='';for(i=0;i<us.length;i++){try{s=String(fetch(us[i],{timeout:6500,headers:{'Cache-Control':'public, max-age=31536000, immutable'}})||'');if(bad(s)||s.indexOf(marker)<0)throw new Error('无效响应');writeFile(local,s);if(!fileExist(local))throw new Error('写入失败');return local;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(path+' 下载失败：'+es.join(' | '));}
function base(){if(BASE_CACHE&&typeof BASE_CACHE.module==='function')return BASE_CACHE;ensureFile(BASE_ENTRY,BASE_REF,BASE_PATH,'0.1.1-test.3');var src=String(readFile(BASE_ENTRY)||''),MyAvLocal=null;if(bad(src)||src.indexOf('0.1.1-test.3')<0)throw new Error('MyAv Test3 Base Entry 内容无效');eval(src);if(!MyAvLocal||typeof MyAvLocal.module!=='function')throw new Error('MyAv Test3 Base Entry 未导出');BASE_CACHE=MyAvLocal;return BASE_CACHE;}
function parseJson(s,d){try{return JSON.parse(String(s||''));}catch(e){return d;}}
function targets(){var a=parseJson(getItem(SEARCH_KEY,'[]'),[]),out=[],seen={},i,x,n,r;if(!(a instanceof Array))a=[];for(i=0;i<a.length;i++){x=a[i]||{};r=String(x.rule||x.name||'').trim();n=String(x.name||r).trim();if(!r||seen[r.toLowerCase()])continue;seen[r.toLowerCase()]=1;out.push({name:n||r,rule:r});}return out;}
function smartSearch(rule,kw){return $('#noLoading#').lazyRule(function(rule,kw){rule=String(rule||'').trim();kw=String(kw||'').trim();if(!rule||!kw)return'toast://缺少搜索目标或关键词';function home(r){var raw='';try{raw=String(request('hiker://home@'+r)||'');}catch(e){try{raw=String(fetch('hiker://home@'+r)||'');}catch(_e){raw='';}}return raw;}function parse(raw){var s=String(raw||'').trim(),p=s.indexOf('￥home_rule￥');if(p>=0)s=s.substring(p+'￥home_rule￥'.length);else{p=s.indexOf('{');if(p>=0)s=s.substring(p);}try{return JSON.parse(s);}catch(e){return null;}}function pages(o){var p=o&&o.pages;if(!p)return[];if(p instanceof Array)return p;try{var a=JSON.parse(String(p));return a instanceof Array?a:[];}catch(e){return[];}}var raw=home(rule);if(!raw||raw==='null')return'toast://未安装 '+rule;var o=parse(raw),ps=pages(o),i,x,su=String(o&&o.search_url||''),sou=null;for(i=0;i<ps.length;i++){x=ps[i]||{};if(String(x.path||'')==='sou'||(/搜索/.test(String(x.name||''))&&String(x.path||''))){sou=x;break;}}if(rule==='磁力君.简'||(su.indexOf('searchTerms=**')>=0&&sou&&sou.path)){var path=(sou&&sou.path)||'sou';return'hiker://page/'+path+'?rule='+rule+'&p=fypage&searchTerms='+encodeURIComponent(kw);}return'hiker://search?s='+encodeURIComponent(kw)+'&rule='+rule;},rule,kw);}
function capture(run,patch){var oldSet=null,got=null,hooked=false,err=null,ret=null;try{oldSet=setResult;var cap=function(v){got=v;};setResult=cap;hooked=(setResult===cap);}catch(e){hooked=false;}if(!hooked){ret=run();return ret instanceof Array?patch(ret):ret;}try{ret=run();}catch(e2){err=e2;}finally{try{setResult=oldSet;}catch(_e){}}if(err)throw err;if(got instanceof Array)return oldSet(patch(got));if(got!=null)return oldSet(got);return ret instanceof Array?patch(ret):ret;}
function detailKeyword(items){var i,t,m;for(i=0;i<items.length;i++){t=String(items[i]&&items[i].title||'');m=t.match(/^番号\s*[·・:]\s*(.+)$/);if(m)return String(m[1]||'').trim();}for(i=0;i<items.length;i++){t=String(items[i]&&items[i].desc||'');m=t.match(/\b(?:FC2[-_ ]?(?:PPV[-_ ]?)?\d{4,}|[A-Za-z]{2,12}[-_. ]?\d{2,6}(?:[-_.][A-Za-z0-9]+)*)\b/i);if(m)return String(m[0]||'').trim().replace(/[ _]+/g,'-');}return'';}
function patchTargets(items,kw){if(!(items instanceof Array)||!kw)return items;var a=targets(),i,j,x,t;for(i=0;i<items.length;i++){x=items[i];if(!x||typeof x!=='object')continue;t=String(x.title||'');for(j=0;j<a.length;j++){if(t===a[j].name){x.url=smartSearch(a[j].rule,kw);break;}}}return items;}
function managerPage(){var d=[],a=targets(),i,t;setPageTitle('MyAv · 自定义搜索');d.push({title:'▌ 跨小程序搜索',desc:'优先识别目标小程序的真实搜索合同；磁力君.简直接进入 sou 并传 searchTerms',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'手动添加',desc:'输入“显示名|规则名”',url:$('','例如：磁力君.简|磁力君.简').input(function(key){var s=String(input||'').trim();if(!s)return'toast://请输入小程序名称';var p=s.split('|'),name=String(p[0]||'').trim(),rule=String(p[1]||p[0]||'').trim(),a=[];try{a=JSON.parse(getItem(key,'[]'));}catch(e){a=[];}if(!(a instanceof Array))a=[];for(var i=0;i<a.length;i++)if(String(a[i]&&a[i].rule||'')===rule)return'toast://已存在 '+rule;a.push({name:name||rule,rule:rule});setItem(key,JSON.stringify(a));refreshPage(false);return'toast://已添加 '+(name||rule);},SEARCH_KEY),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'▌ 已配置',desc:a.length?a.length+' 个目标':'暂无目标',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});for(i=0;i<a.length;i++){t=a[i];d.push({title:t.name,desc:'规则：'+t.rule+'\n点击输入关键词测试 · 长按删除',url:$('','输入测试关键词').input(function(rule){var q=String(input||'').trim();if(!q)return'toast://请输入关键词';function home(r){var raw='';try{raw=String(request('hiker://home@'+r)||'');}catch(e){try{raw=String(fetch('hiker://home@'+r)||'');}catch(_e){raw='';}}return raw;}function parse(raw){var s=String(raw||'').trim(),p=s.indexOf('￥home_rule￥');if(p>=0)s=s.substring(p+'￥home_rule￥'.length);else{p=s.indexOf('{');if(p>=0)s=s.substring(p);}try{return JSON.parse(s);}catch(e){return null;}}function pages(o){var p=o&&o.pages;if(!p)return[];if(p instanceof Array)return p;try{var a=JSON.parse(String(p));return a instanceof Array?a:[];}catch(e){return[];}}var raw=home(rule);if(!raw||raw==='null')return'toast://未安装 '+rule;var o=parse(raw),ps=pages(o),su=String(o&&o.search_url||''),sou=null;for(var i=0;i<ps.length;i++){var x=ps[i]||{};if(String(x.path||'')==='sou'||(/搜索/.test(String(x.name||''))&&String(x.path||''))){sou=x;break;}}if(rule==='磁力君.简'||(su.indexOf('searchTerms=**')>=0&&sou&&sou.path)){return'hiker://page/'+((sou&&sou.path)||'sou')+'?rule='+rule+'&p=fypage&searchTerms='+encodeURIComponent(q);}return'hiker://search?s='+encodeURIComponent(q)+'&rule='+rule;},t.rule),col_type:'text_1',extra:{lineVisible:false,longClick:[{title:'删除',js:$.toString(function(key,rule){var a=[];try{a=JSON.parse(getItem(key,'[]'));}catch(e){a=[];}var out=[];for(var i=0;i<a.length;i++)if(String(a[i]&&a[i].rule||'')!==String(rule||''))out.push(a[i]);setItem(key,JSON.stringify(out));refreshPage(false);return'toast://已删除 '+rule;},SEARCH_KEY,t.rule)}]}});}d.push({title:'搜索合同',desc:'磁力君.简：sou + searchTerms；其它目标默认 hiker://search',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});setResult(d);}
function module(){var b=base(),m=b.module();if(!m||typeof m.core!=='function')throw new Error('MyAv Test3 Module 未就绪');var C=m.core();C.externalSearchUrl=smartSearch;if(typeof m.detail==='function'){var od=m.detail;m.detail=function(){return capture(function(){return od.call(m);},function(items){return patchTargets(items,detailKeyword(items));});};}if(typeof m.search==='function'){var os=m.search;m.search=function(){var kw='';try{kw=String(getMyVar('myav_search_kw','')||'').trim();}catch(e){}return capture(function(){return os.call(m);},function(items){return patchTargets(items,kw);});};}m.externalSearch=managerPage;m.version=VERSION;m.build=BUILD;m.baseVersion='0.1.1-test.3';m.externalSearchAdapter='signature-aware-v1';return m;}
function info(){var x={};try{x=base().info?base().info():{};}catch(e){x={};}x.version=VERSION;x.build=BUILD;x.baseVersion='0.1.1-test.3';x.externalSearchAdapter='signature-aware-v1';x.magnetJun='page/sou?searchTerms=';return x;}
function statusPage(){setPageTitle('MyAv · Test4 搜索诊断');setResult([{title:VERSION+' / Build '+BUILD,desc:'磁链调用继承 Test3；本轮只修自定义跨小程序搜索',url:'hiker://empty',col_type:'text_1'},{title:'磁力君.简',desc:'直接调用 hiker://page/sou?rule=磁力君.简&p=fypage&searchTerms=<关键词>',url:'hiker://empty',col_type:'text_1'},{title:'自动识别',desc:'search_url 含 searchTerms=** 且 pages 存在 sou/搜索页时使用页面型搜索',url:'hiker://empty',col_type:'text_1'},{title:'其它小程序',desc:'继续使用 hiker://search?s=<关键词>&rule=<原始规则名>',url:'hiker://empty',col_type:'text_1'}]);}
return{version:VERSION,build:BUILD,module:module,info:info,statusPage:statusPage};
})();
var MyAvLocal=MyAvSearchFix10204;
