/* JavMenu Core 0.1.0-test.1 - site protocol/provider/adapter layer */
var JavMenuCore=(function(){
  var C={version:'0.1.0-test.1',build:10101};
  C.base='https://javmenu.com';
  C.homePath='/zh';
  C.ua='Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36';
  C.videoFavPath='hiker://files/rules/JavMenu/favorites_videos.json';
  C.peopleFavPath='hiker://files/rules/JavMenu/favorites_people.json';
  C.diagKey='javmenu_diag_last';

  C.s=function(v){return v===undefined||v===null?'':String(v);};
  C.trim=function(v){return C.s(v).replace(/^\s+|\s+$/g,'');};
  C.decodeHtml=function(v){return C.s(v).replace(/&nbsp;/ig,' ').replace(/&amp;/ig,'&').replace(/&quot;/ig,'"').replace(/&#39;|&apos;/ig,"'").replace(/&lt;/ig,'<').replace(/&gt;/ig,'>').replace(/&#x2F;|&#47;/ig,'/');};
  C.strip=function(v){return C.trim(C.decodeHtml(C.s(v).replace(/<br\s*\/?\s*>/ig,'\n').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' '));};
  C.safeDecode=function(v){try{return decodeURIComponent(C.s(v));}catch(e){return C.s(v);}};
  C.origin=function(u){var m=C.s(u).match(/^(https?:\/\/[^/]+)/i);return m?m[1]:C.base;};
  C.abs=function(u,base){u=C.decodeHtml(C.trim(u)).replace(/\\u002[fF]/g,'/').replace(/\\\//g,'/');base=base||C.base;if(!u||/^(javascript:|data:|#)/i.test(u))return'';if(/^https?:\/\//i.test(u))return u;if(/^\/\//.test(u))return'https:'+u;var o=C.origin(base);if(u.charAt(0)==='/')return o+u;return String(base).replace(/[?#].*$/,'').replace(/[^/]*$/,'')+u;};
  C.attr=function(tag,name){var re=new RegExp('\\b'+name+'\\s*=\\s*["\']([^"\']+)["\']','i'),m=C.s(tag).match(re);if(m)return C.decodeHtml(m[1]);re=new RegExp('\\b'+name+'\\s*=\\s*([^\\s>]+)','i');m=C.s(tag).match(re);return m?C.decodeHtml(m[1]):'';};
  C.meta=function(html,key,val){var re=/<meta\b[^>]*>/ig,m,t,a,b;while((m=re.exec(C.s(html)))){t=m[0];a=C.attr(t,key);if(C.s(a).toLowerCase()===C.s(val).toLowerCase()){b=C.attr(t,'content');if(b)return C.trim(b);}}return'';};
  C.canonical=function(html){var re=/<link\b[^>]*>/ig,m,t;while((m=re.exec(C.s(html)))){t=m[0];if(/\brel\s*=\s*["']canonical["']/i.test(t)){var h=C.attr(t,'href');if(h)return C.abs(h,C.base);}}return'';};
  C.image=function(u,ref){u=C.abs(u,ref||C.base);if(!u)return'';if(u.indexOf('@headers=')>=0)return u;return u+'@headers='+JSON.stringify({'User-Agent':C.ua,'Referer':ref||C.base+'/'});};
  C.page=function(view,params){var a=['rule='+MY_RULE.title,'simple=true','jm_view='+encodeURIComponent(view||'home')],k;params=params||{};for(k in params){if(params.hasOwnProperty(k)&&params[k]!==undefined&&params[k]!==null&&String(params[k])!=='')a.push('jm_'+encodeURIComponent(k)+'='+encodeURIComponent(String(params[k])));}return'hiker://page/javmenuPage?'+a.join('&');};
  C.get=function(name,def){var v='';try{v=getParam('jm_'+name,'');}catch(e){v='';}if(!v&&typeof MY_PARAMS==='object'&&MY_PARAMS){v=MY_PARAMS['jm_'+name]||'';}return v===undefined||v===null||String(v)===''?(def||''):C.safeDecode(v);};

  C.normalizeCode=function(v){var s=C.s(v).toUpperCase().replace(/[＿_\s]+/g,'-'),m=s.match(/FC2[^0-9]*(?:PPV[^0-9]*)?(\d{4,})/i);if(m)return'FC2-PPV-'+m[1];m=s.match(/([A-Z0-9]{2,14})[-](\d{2,8})/);if(m)return m[1]+'-'+m[2];m=s.match(/([A-Z]{2,10})(\d{3,7})/);if(m)return m[1]+'-'+m[2];return'';};
  C.codeFromHref=function(href){var u=C.safeDecode(C.s(href).replace(/[?#].*$/,'')),seg=u.split('/'),last='';while(seg.length&&!last)last=seg.pop();return C.normalizeCode(last);};
  C.extractCode=function(v){return C.normalizeCode(v)||C.codeFromHref(v);};
  C.isDetailHref=function(href){var u=C.abs(href,C.base),code=C.codeFromHref(u);if(!u||C.origin(u)!==C.base||!code)return false;return !/(\/search|\/assets|\/static|\/login|\/register)/i.test(u);};

  C.diag=function(stage,url,ok,extra){var x={time:new Date().getTime(),version:C.version,build:C.build,stage:stage||'',url:C.s(url).replace(/([?&](?:token|auth|key|cookie)=)[^&]+/ig,'$1***'),ok:!!ok,extra:C.s(extra||'').slice(0,500)};try{setItem(C.diagKey,JSON.stringify(x));}catch(e){}return x;};
  C.isBadHtml=function(h){var s=C.s(h),l=s.toLowerCase();if(s.length<180)return true;return l.indexOf('just a moment')>=0||l.indexOf('cf-chl-')>=0||l.indexOf('attention required')>=0||l.indexOf('cloudflare ray id')>=0;};
  C.headers=function(ref){return{'User-Agent':C.ua,'Referer':ref||C.base+'/','Accept-Language':'zh-CN,zh;q=0.9,en;q=0.6'};};
  C.fetchNetwork=function(url,timeout){try{return C.s(fetch(url,{timeout:timeout||9000,headers:C.headers(C.origin(url)+'/')}));}catch(e){C.diag('network',url,false,e.message||e);return'';}};
  C.fetchWeb=function(url){try{return C.s(fetchCodeByWebView(url,{timeout:13000,headers:C.headers(C.origin(url)+'/')}));}catch(e){C.diag('webview',url,false,e.message||e);return'';}};
  C.fetchHtml=function(url,opt){opt=opt||{};var mode=getItem('javmenu_request_mode','auto'),h='';if(mode!=='webview'&&!opt.webOnly){h=C.fetchNetwork(url,opt.timeout||9000);if(!C.isBadHtml(h)){C.diag('network',url,true,'len='+h.length);return h;}if(mode==='network')return h;}h=C.fetchWeb(url);if(!C.isBadHtml(h)){C.diag('webview',url,true,'len='+h.length);return h;}C.diag('fetch',url,false,'bad html len='+C.s(h).length);return h;};

  C.homeUrl=function(page){var u=C.base+C.homePath,p=Number(page||1);if(p>1)u+=(u.indexOf('?')>=0?'&':'?')+'page='+p;return u;};
  C.searchUrl=function(kw,page){var u=C.base+'/search?wd='+encodeURIComponent(C.trim(kw)),p=Number(page||1);if(p>1)u+='&page='+p;return u;};
  C.detailUrl=function(code){return C.base+'/'+encodeURIComponent(C.normalizeCode(code)||C.trim(code));};
  C.listUrl=function(raw,page){var u=C.abs(raw,C.base),p=Number(page||1);if(p<=1)return u;if(/[?&]page=\d+/i.test(u))return u.replace(/([?&]page=)\d+/i,'$1'+p);return u+(u.indexOf('?')>=0?'&':'?')+'page='+p;};

  C.parseMovies=function(html,ref){var out=[],seen={},s=C.s(html),re=/<a\b([^>]*)>([\s\S]*?)<\/a>/ig,m,open,body,href,imgTag,img,title,code,date,badge;while((m=re.exec(s))){open=m[1];body=m[2];href=C.attr(open,'href');href=C.abs(href,ref||C.base);if(!C.isDetailHref(href)||seen[href])continue;imgTag=(body.match(/<img\b[^>]*>/i)||[])[0]||'';if(!imgTag)continue;img=C.attr(imgTag,'data-src')||C.attr(imgTag,'data-lazy-src')||C.attr(imgTag,'src')||C.attr(imgTag,'data-original');title=C.attr(imgTag,'alt')||C.attr(open,'title')||C.strip(body);code=C.extractCode(title)||C.codeFromHref(href);if(!code)continue;title=C.trim(C.strip(title))||code;date='';badge='';var dm=body.match(/(?:\bdate\b[^>]*>|發行|发行|Date)[^<]{0,40}/i);if(dm)date=C.strip(dm[0]);var bm=body.match(/(?:badge|tag)[^>]*>([\s\S]*?)<\/[^>]+>/i);if(bm)badge=C.strip(bm[1]);seen[href]=1;out.push({id:code,code:code,title:title,href:href,img:C.image(img,href),rawImg:C.abs(img,href),date:date,badge:badge,source:'javmenu'});if(out.length>=60)break;}return out;};

  C.parseLinkGroup=function(html,kind){var out=[],seen={},re=/<a\b([^>]*)>([\s\S]*?)<\/a>/ig,m,href,name,imgTag,img,path,hit;while((m=re.exec(C.s(html)))){href=C.abs(C.attr(m[1],'href'),C.base);if(!href||C.origin(href)!==C.base||seen[href])continue;name=C.strip(m[2]);if(!name||name.length>40)continue;path=href.toLowerCase();hit=false;if(kind==='people')hit=/(\/actor(?:s)?\/|\/actress(?:es)?\/|\/star\/|\/performer\/)/i.test(path)||/(女优|女優|演员|演員|女优|Actor|Actress)/i.test(name);else if(kind==='tag')hit=/(\/tag(?:s)?\/|\/genre\/|\/category\/|\/maker\/|\/studio\/|\/label\/|\/series\/|\/director\/)/i.test(path);if(!hit)continue;imgTag=(m[2].match(/<img\b[^>]*>/i)||[])[0]||'';img=C.attr(imgTag,'data-src')||C.attr(imgTag,'src')||'';seen[href]=1;out.push({name:name,href:href,img:C.image(img,href),kind:kind});if(out.length>=80)break;}return out;};

  C.discoverNav=function(html){var out=[],seen={},re=/<a\b([^>]*)>([\s\S]*?)<\/a>/ig,m,href,name,path,known;while((m=re.exec(C.s(html)))){href=C.abs(C.attr(m[1],'href'),C.base);if(!href||C.origin(href)!==C.base||seen[href]||C.isDetailHref(href))continue;name=C.strip(m[2]);if(!name||name.length>20)continue;path=href.toLowerCase();if(/\/search|\/login|\/register|\/privacy|\/terms|\/assets|javascript:/i.test(path))continue;if(href===C.base+'/'||href===C.base+C.homePath||/^\/\w{2}\/?$/.test(path.replace(C.base,'')))continue;known=/(category|genre|tag|actor|actress|star|performer|series|maker|studio|label|director|latest|new|popular|rank|fc2|uncensored|subtitle|censored)/i.test(path)||/(最新|热门|排行|无码|有码|字幕|中文|FC2|演员|女优|女優|分类|類別|标签|標籤|系列|片商|导演|導演)/i.test(name);if(!known)continue;seen[href]=1;out.push({name:name,href:href,kind:/(actor|actress|star|performer)/i.test(path)?'people':'filter'});if(out.length>=48)break;}return out;};

  C.parseJsonLd=function(html){var out=[],re=/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/ig,m,j;while((m=re.exec(C.s(html)))){try{j=JSON.parse(C.decodeHtml(C.trim(m[1])));if(j)out.push(j);}catch(e){}}return out;};
  C.findVideoLd=function(list){var i,j,x,a=[];function walk(v){if(!v)return;if(Object.prototype.toString.call(v)==='[object Array]'){for(var z=0;z<v.length;z++)walk(v[z]);return;}if(typeof v==='object'){if(C.s(v['@type']).toLowerCase()==='videoobject')a.push(v);if(v['@graph'])walk(v['@graph']);}}for(i=0;i<list.length;i++)walk(list[i]);return a.length?a[0]:null;};
  C.parsePlayer=function(html,ref){var out=[],seen={},s=C.s(html),re,m,tag,url,name;function add(u,n){u=C.abs(C.decodeHtml(C.s(u).replace(/\\u002[fF]/g,'/').replace(/\\\//g,'/')),ref);if(!u||!/\.(?:m3u8|mp4)(?:[?#]|$)/i.test(u)||seen[u])return;seen[u]=1;out.push({url:u,name:C.strip(n)||(/\.m3u8/i.test(u)?'HLS':'MP4')+' '+(out.length+1)});}re=/<(?:a|button)\b([^>]*)data-m3u8=["']([^"']+)["']([^>]*)>([\s\S]*?)<\/(?:a|button)>/ig;while((m=re.exec(s)))add(m[2],C.strip(m[4])||C.attr(m[1]+m[3],'title'));re=/<(?:video|source)\b([^>]*)>/ig;while((m=re.exec(s))){tag=m[1];url=C.attr(tag,'src')||C.attr(tag,'data-src');name=C.attr(tag,'label')||C.attr(tag,'title')||C.attr(tag,'data-quality');add(url,name);}re=/https?:\\?\/\\?\/[^\s"'<>]+?\.(?:m3u8|mp4)(?:\?[^\s"'<>]*)?/ig;while((m=re.exec(s)))add(m[0],'');return out.slice(0,12);};

  C.parseImages=function(html,ref,poster){var out=[],seen={},re=/<a\b([^>]*)>([\s\S]*?)<\/a>/ig,m,href,imgTag,thumb,title;poster=C.abs(poster,ref);function add(src,th,t){src=C.abs(src,ref);th=C.abs(th||src,ref);if(!src||seen[src]||src===poster||!/(?:\.jpe?g|\.png|\.webp)(?:[?#]|$)/i.test(src)||/(logo|favicon|avatar|icon)/i.test(src))return;seen[src]=1;out.push({src:src,thumb:C.image(th,ref),title:t||('预览 '+(out.length+1))});}while((m=re.exec(C.s(html)))){href=C.attr(m[1],'href');imgTag=(m[2].match(/<img\b[^>]*>/i)||[])[0]||'';thumb=C.attr(imgTag,'data-src')||C.attr(imgTag,'src');title=C.attr(imgTag,'alt')||C.attr(m[1],'title');if(href&&imgTag)add(href,thumb,title);if(out.length>=18)break;}return out;};
  C.parseMagnets=function(html){var out=[],seen={},re=/<a\b([^>]*)>([\s\S]*?)<\/a>/ig,m,href,title;while((m=re.exec(C.s(html)))){href=C.decodeHtml(C.attr(m[1],'href'));if(!/^magnet:\?xt=urn:btih:/i.test(href)||seen[href])continue;seen[href]=1;title=C.strip(m[2])||('磁力 '+(out.length+1));out.push({url:href,title:title});}return out;};
  C.parseDetail=function(html,code,url){var ld=C.findVideoLd(C.parseJsonLd(html)),d={code:C.normalizeCode(code),url:url,title:'',desc:'',rawImg:'',img:'',date:'',duration:'',people:[],tags:[],samples:[],players:[],magnets:[],related:[]},t='',og='';try{t=C.strip(pdfh(html,'.code&&Text')||pdfh(html,'.display-5&&strong&&Text')||pdfh(html,'h1&&Text')||'');}catch(e){}d.code=C.normalizeCode(t)||d.code||C.codeFromHref(C.canonical(html))||C.normalizeCode(C.meta(html,'property','og:title'));
    og=C.meta(html,'property','og:title');d.title=(ld&&ld.name)?C.trim(ld.name):og||C.strip((C.s(html).match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||'')||d.code;d.desc=(ld&&ld.description)?C.strip(ld.description):C.meta(html,'name','description')||C.meta(html,'property','og:description');
    var raw=(ld&&ld.thumbnailUrl)?(Object.prototype.toString.call(ld.thumbnailUrl)==='[object Array]'?ld.thumbnailUrl[0]:ld.thumbnailUrl):C.meta(html,'property','og:image');d.rawImg=C.abs(raw,url);d.img=C.image(d.rawImg,url);d.date=C.s(ld&&ld.uploadDate||'');d.duration=C.s(ld&&ld.duration||'');d.people=C.parseLinkGroup(html,'people');d.tags=C.parseLinkGroup(html,'tag');d.samples=C.parseImages(html,url,d.rawImg);d.players=C.parsePlayer(html,url);d.magnets=C.parseMagnets(html);d.related=C.parseMovies(html,url).filter(function(x){return x.code!==d.code;}).slice(0,18);return d;};

  C.readJson=function(path){try{var raw=readFile(path);if(!raw)raw=fetch(path);var x=JSON.parse(raw||'[]');return Object.prototype.toString.call(x)==='[object Array]'?x:[];}catch(e){return[];}};
  C.saveJson=function(path,list){try{saveFile(path,JSON.stringify(list||[]));return true;}catch(e){try{writeFile(path,JSON.stringify(list||[]));return true;}catch(e2){return false;}}};
  C.favPath=function(kind){return kind==='people'?C.peopleFavPath:C.videoFavPath;};
  C.loadFav=function(kind){return C.readJson(C.favPath(kind));};
  C.isFav=function(kind,key){var a=C.loadFav(kind),k=C.s(key).toLowerCase(),i;for(i=0;i<a.length;i++)if(C.s(a[i].key||a[i].code||a[i].href).toLowerCase()===k)return true;return false;};
  C.toggleFav=function(kind,item){item=item||{};var a=C.loadFav(kind),key=C.s(kind==='people'?(item.key||item.href||item.name):(item.code||item.key)).toLowerCase(),i,found=-1;if(!key)return false;for(i=0;i<a.length;i++)if(C.s(a[i].key||a[i].code||a[i].href).toLowerCase()===key){found=i;break;}if(found>=0){a.splice(found,1);C.saveJson(C.favPath(kind),a);return false;}item.key=key;item.savedAt=new Date().getTime();a.unshift(item);if(a.length>500)a=a.slice(0,500);C.saveJson(C.favPath(kind),a);return true;};
  C.clearFav=function(kind){return C.saveJson(C.favPath(kind),[]);};
  C.lastDiag=function(){try{return JSON.parse(getItem(C.diagKey,'{}')||'{}');}catch(e){return{};}};
  return C;
})();
if(typeof $!=='undefined')$.exports=JavMenuCore;
