/* 51吃瓜 Core Patch 0.1.0-test.2 */
(function(){
  if(typeof Cg51Core==='undefined') throw new Error('Cg51Core missing');
  var C=Cg51Core;
  C.version='0.1.0-test.2';
  C.build=10102;
  C.bootstrap='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/video/51chigua/bootstrap_test_v2_b10102.js?v=10102';
  C.schema='2';
  C.page=function(path,params){var a=['rule='+C.ruleTitle(),'simple=true'],k;params=params||{};for(k in params)if(params.hasOwnProperty(k)&&params[k]!==undefined&&params[k]!==null&&C.s(params[k])!=='')a.push(encodeURIComponent(k)+'='+encodeURIComponent(C.s(params[k])));return'hiker://page/'+path+'?'+a.join('&');};
  var oldHeaders=C.headers;C.headers=function(ref,accept){var h=oldHeaders(ref,accept);h.Cookie='user-choose=true';return h;};
  C.isEncryptedImage=function(u){return /\/xiao\/|\/upload\/upload\//i.test(C.s(u));};
  C.imageSuffix=function(){return $('').image(function(){try{const CryptoUtil=$.require('hiker://assets/crypto-java.js');let key=CryptoUtil.Data.parseUTF8('f5d965df75336270');let iv=CryptoUtil.Data.parseUTF8('97b60394abc2fbe1');let textData=CryptoUtil.Data.parseInputStream(input);let encrypted=CryptoUtil.AES.decrypt(textData,key,{mode:'AES/CBC/PKCS7Padding',iv:iv});return encrypted.toInputStream();}catch(e){return input;}});};
  C.image=function(u,ref){u=C.abs(u,ref||C.base());if(!u)return'';var head='@headers='+JSON.stringify({'User-Agent':C.ua,'Referer':ref||C.base()+'/','Cookie':'user-choose=true'});return C.isEncryptedImage(u)?(u+head+C.imageSuffix()):(u+head);};
  C.firstImage=function(raw,base){var s=C.s(raw),m,u='',re;m=s.match(/(?:loadBannerDirect|loadImage)\s*\(\s*['\"]([^'\"]+)['\"]/i);if(m){u=C.abs(m[1],base);if(u&&!/logo|avatar|favicon|icon[-_.]/i.test(u))return u;}re=/<img\b([^>]*)>/ig;while((m=re.exec(s))){u=C.attr(m[1],'data-xkrkllgl')||C.attr(m[1],'data-original')||C.attr(m[1],'data-src')||C.attr(m[1],'data-lazy-src')||C.attr(m[1],'src');u=C.abs(u,base);if(u&&!/^data:/i.test(u)&&!/logo|avatar|favicon|icon[-_.]|emoji|loading/i.test(u))return u;}return'';};
  var oldParsePosts=C.parsePosts;C.parsePosts=function(html,base){var a=oldParsePosts(html,base),out=[],i,x;for(i=0;i<a.length;i++){x=a[i];if(/原创招募|百万现金扶持|往期活动/.test(C.s(x.title)))continue;if(!x.rawImg){var p=C.pathOf(x.url).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');var idx=C.s(html).search(new RegExp(p.replace(/\//g,'\\/'),'i'));if(idx>=0){var ctx=C.context(html,idx,1200,2200),im=C.firstImage(ctx,x.url);if(im){x.rawImg=im;x.img=C.image(im,x.url);}}}out.push(x);}return out;};
  C.staticCategories=function(){var b=C.base();return[{name:'今日吃瓜',url:b+'/category/wpcz/'},{name:'学生校园',url:b+'/category/xsxy/'},{name:'网红黑料',url:b+'/category/whhl/'},{name:'热门大瓜',url:b+'/category/rdsj/'},{name:'吃瓜榜单',url:b+'/category/mrdg/'},{name:'必看大瓜',url:b+'/category/bkdg/'},{name:'看片娱乐',url:b+'/category/ysyl/'},{name:'每日大赛',url:b+'/category/mrds/'},{name:'伦理道德',url:b+'/category/lldd/'},{name:'探花精选',url:b+'/category/thjx/'},{name:'网黄合集',url:b+'/category/whhj/'},{name:'免费短剧',url:b+'/category/cbdj/'},{name:'骚男骚女',url:b+'/category/snsn/'},{name:'明星黑料',url:b+'/category/whmx/'},{name:'海外吃瓜',url:b+'/category/hwcg/'},{name:'领导干部',url:b+'/category/ldcg/'},{name:'吃瓜看戏',url:b+'/category/qubk/'},{name:'擦边聊骚',url:b+'/category/dcbq/'},{name:'51涨知识',url:b+'/category/zzs/'},{name:'原创博主',url:b+'/category/yczq/'},{name:'51剧场',url:b+'/category/51djc/'}];};
  C.extractImages=function(raw,base){var s=C.s(raw),out=[],seen={},m,u,re;function add(u){u=C.abs(u,base);if(!u||seen[u]||/^data:/i.test(u)||/logo|avatar|favicon|icon[-_.]|emoji|loading/i.test(u))return;seen[u]=1;out.push(u);}re=/<img\b([^>]*)>/ig;while((m=re.exec(s))){u=C.attr(m[1],'data-xkrkllgl')||C.attr(m[1],'data-original')||C.attr(m[1],'data-src')||C.attr(m[1],'data-lazy-src')||C.attr(m[1],'src');add(u);}re=/(?:loadBannerDirect|loadImage)\s*\(\s*['\"]([^'\"]+)['\"]/ig;while((m=re.exec(s)))add(m[1]);return out;};
  var oldExtractMedia=C.extractMedia;C.extractMedia=function(html,base){var out=oldExtractMedia(html,base),seen={},i,m,s=C.decode(html),re,u;for(i=0;i<out.length;i++)seen[out[i].url]=1;re=/data-config\s*=\s*['\"]([^'\"]+)['\"]/ig;while((m=re.exec(s))){var cfg=C.decode(m[1]);var vm=cfg.match(/[\"']url[\"']\s*:\s*[\"']([^\"']+)[\"']/i);if(vm){u=C.abs(C.decode(vm[1]).replace(/\\\//g,'/'),base);if(u&&!seen[u]&&/\.m3u8|\.mp4/i.test(u)){seen[u]=1;out.push({url:u,ref:base,route:'dplayer'});}}}return out;};
})();