/* Hanime1 Test10 video detail + series */
(function(C,P,E,H,U){var BUILD='2.0.0-test.10',pv=H.pv,route=H.route,sec=H.sec,btn=H.btn,chip=H.chip,video=H.video;
function playUrl(id){return $('#noLoading#').lazyRule(function(x){return $.require('hanime').play(x);},id);}
E.detail=function(){try{var id=pv('id','');if(!id)throw new Error('缺少视频 ID');var v=P.video(id),d=[],top=(v.sources&&v.sources.length)?String(v.sources[0].quality||'最高'):'待解析';setPageTitle(v.title);d.push({title:v.title,desc:[v.artist,v.genre,v.views?('观看 '+v.views):'',v.upload].filter(Boolean).join('\n'),pic_url:v.cover||'',url:playUrl(id),col_type:'movie_1_vertical_pic_blur',extra:{gradient:true,lineVisible:false}});d.push(btn('播放 · '+top,playUrl(id)));d.push(btn('评论'+(v.commentCount!==undefined?' · '+v.commentCount:''),route('hanimeComments',{id:id,title:v.title})));d.push(btn(v.download?'下载原片':'更多信息',v.download?('download://'+v.download):'hiker://empty'));
var pl=v.playlist||[];if(pl.length>1){d.push(sec('选集 · '+pl.length,'当前：'+v.title));for(var p=0;p<pl.length;p++){var x=pl[p],sel=String(x.id)===String(id);d.push({title:U.active(U.epLabel(x,p),sel),url:sel?'hiker://empty':route('hanimeDetail',{id:x.id,title:x.title}),col_type:'scroll_button'});}d.push({col_type:'line_blank'});}
d.push(sec('作品信息'));if(v.artist)d.push(chip('作者 · '+v.artist,'hiker://empty'));if(v.genre)d.push(chip('类型 · '+v.genre,route('hanimeVideoResults',{genre:v.genre})));if(v.views)d.push(chip('观看 · '+v.views,'hiker://empty'));if(v.upload)d.push(chip('上传 · '+v.upload,'hiker://empty'));if(v.duration)d.push(chip('时长 · '+v.duration,'hiker://empty'));
if(v.tags&&v.tags.length){d.push(sec('内容标签','常用标签直接查看结果'));for(var i=0;i<Math.min(12,v.tags.length);i++){var tg=v.tags[i];d.push(chip(tg.name+(tg.count?' · '+tg.count:''),route('hanimeVideoResults',{tag:tg.name})));}if(v.tags.length>12)d.push({title:'全部标签 · '+v.tags.length,url:U.tagsSelect(v.tags,route('hanimeVideoResults',{})),col_type:'scroll_button'});}
if(v.caption)d.push({title:'简介',desc:v.caption,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false,textSize:16}});if(v.sources&&v.sources.length)d.push(sec('画质','默认最高画质 · '+v.sources.map(function(s){return s.quality||'默认';}).join(' / ')));if(v.related&&v.related.length){d.push(sec('相关推荐',v.related.length+' 部'));for(var j=0;j<v.related.length;j++)d.push(video(v.related[j]));}setResult(d);}catch(x){setResult([{title:'详情加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeUI10);
