/* 汤头条 0.1.0-test.11 ImageLoader / self-fetch candidate retry + decrypt */
var TangTouTiaoImageV019=(function(){
  var V='0.1.0-test.11';
  function newBytes(n){return java.lang.reflect.Array.newInstance(java.lang.Byte.TYPE,n);}
  function copy(src,sp,dst,dp,len){java.lang.System.arraycopy(src,sp,dst,dp,len);}
  function u8(v){return v<0?v+256:v;}
  function starts(a,b){if(!a||a.length<b.length)return false;for(var i=0;i<b.length;i++)if(u8(a[i])!==b[i])return false;return true;}
  function isImage(a){if(!a||a.length<4)return false;if(starts(a,[0xFF,0xD8,0xFF]))return true;if(starts(a,[0x89,0x50,0x4E,0x47]))return true;if(starts(a,[0x47,0x49,0x46,0x38]))return true;if(starts(a,[0x42,0x4D]))return true;if(a.length>=12&&starts(a,[0x52,0x49,0x46,0x46])&&u8(a[8])===0x57&&u8(a[9])===0x45&&u8(a[10])===0x42&&u8(a[11])===0x50)return true;return false;}
  function imageType(a){if(starts(a,[0xFF,0xD8,0xFF]))return'jpeg';if(starts(a,[0x89,0x50,0x4E,0x47]))return'png';if(starts(a,[0x47,0x49,0x46,0x38]))return'gif';if(starts(a,[0x42,0x4D]))return'bmp';if(a&&a.length>=12&&starts(a,[0x52,0x49,0x46,0x46])&&u8(a[8])===0x57&&u8(a[9])===0x45&&u8(a[10])===0x42&&u8(a[11])===0x50)return'webp';return'unknown';}
  function hexBytes(s){s=String(s||'').trim();if(!s||s.length%2!==0||!/^[0-9A-Fa-f]+$/.test(s))return null;var a=newBytes(s.length/2);for(var i=0;i<a.length;i++){var v=parseInt(s.substr(i*2,2),16);a[i]=v>127?v-256:v;}return a;}
  function fromHex(h){return hexBytes(h);}
  function evp(secret,keyLen,ivLen){var pass=new java.lang.String(String(secret)).getBytes('UTF-8'),md=java.security.MessageDigest.getInstance('MD5'),need=keyLen+ivLen,all=newBytes(need),pos=0,prev=null;while(pos<need){md.reset();if(prev)md.update(prev);md.update(pass);prev=md.digest();var n=Math.min(prev.length,need-pos);copy(prev,0,all,pos,n);pos+=n;}var key=newBytes(keyLen),iv=newBytes(ivLen);copy(all,0,key,0,keyLen);copy(all,keyLen,iv,0,ivLen);return{key:key,iv:iv};}
  function legacy(raw){var text=String(new java.lang.String(raw,'UTF-8')).trim(),enc=hexBytes(text);if(!enc||enc.length<17)return null;var iv=newBytes(16),body=newBytes(enc.length-16);copy(enc,0,iv,0,16);copy(enc,16,body,0,body.length);var p=evp('e79465cfbbimgkcusimcuekd3b066a6e',32,16),cipher=javax.crypto.Cipher.getInstance('AES/CFB/NoPadding'),key=new javax.crypto.spec.SecretKeySpec(p.key,'AES');cipher.init(2,key,new javax.crypto.spec.IvParameterSpec(iv));return cipher.doFinal(body);}
  function aesCbc(raw){var key=new javax.crypto.spec.SecretKeySpec(new java.lang.String('f5d965df75336270').getBytes('UTF-8'),'AES'),iv=new javax.crypto.spec.IvParameterSpec(new java.lang.String('97b60394abc2fbe1').getBytes('UTF-8')),cipher=javax.crypto.Cipher.getInstance('AES/CBC/PKCS5Padding');cipher.init(2,key,iv);return cipher.doFinal(raw);}
  function headers(mode){var h={Accept:'image/avif,image/webp,image/apng,image/*,*/*;q=0.8','Cache-Control':'no-cache'};if(mode==='okhttp')h['User-Agent']='okhttp/4.9.3';else if(mode==='browser')h['User-Agent']='Mozilla/5.0 (Linux; Android 13; HikerView) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Mobile Safari/537.36';else h['User-Agent']='Mozilla/5.0';if(mode==='refer'){var r=String(getItem('ttt_player_refer','')||'');if(r)h.Referer=r;}return h;}
  function modes(){var a=['okhttp','browser','minimal'];if(String(getItem('ttt_player_refer','')||''))a.push('refer');return a;}
  function fetchBytes(u,h){var x=fetch(u,{timeout:12000,headers:h,toHex:true});if(x==null)return null;return fromHex(String(x));}
  function inspect(raw){if(!raw||!raw.length)return null;if(isImage(raw))return{bytes:raw,mode:'plain'};try{var a=legacy(raw);if(a&&isImage(a))return{bytes:a,mode:'legacy-cfb'};}catch(e1){}try{var b=aesCbc(raw);if(b&&isImage(b))return{bytes:b,mode:'aes-cbc'};}catch(e2){}return null;}
  function fetchDecrypt(candidatesJson){var c=[];try{c=typeof candidatesJson==='string'?JSON.parse(candidatesJson):candidatesJson;}catch(e){}if(!Array.isArray(c))c=[];var ms=modes(),errs=[];for(var i=0;i<c.length;i++){var u=String(c[i]||'').trim();if(!/^https?:\/\//i.test(u))continue;for(var j=0;j<ms.length;j++){var raw=null;try{raw=fetchBytes(u,headers(ms[j]));var out=inspect(raw);if(out){try{setItem('ttt_last_image_diag',JSON.stringify({time:Date.now(),ok:true,candidate:i,headerMode:ms[j],input:raw.length,output:out.bytes.length,mode:out.mode,type:imageType(out.bytes),url:u.substring(0,180)}));}catch(e0){}return new java.io.ByteArrayInputStream(out.bytes);}errs.push('c'+i+'/'+ms[j]+':not-image len='+(raw?raw.length:0));}catch(e1){errs.push('c'+i+'/'+ms[j]+':'+String(e1.message||e1).substring(0,90));}}}try{setItem('ttt_last_image_diag',JSON.stringify({time:Date.now(),ok:false,candidates:c.length,errors:errs.slice(-8)}));}catch(e2){}return null;}
  return{version:V,fetchDecrypt:fetchDecrypt};
})();
try{$.exports=TangTouTiaoImageV019;}catch(e){}
