/* Hanime1 Test21: exact Han1mePlus DOM grouping for real author/comment/reply avatars */
(function(C,P,E){
var oldVideo=P.video;
var oldComments=P.comments;
var oldReplies=P.replies;
var VOID={area:1,base:1,br:1,col:1,embed:1,hr:1,img:1,input:1,link:1,meta:1,param:1,source:1,track:1,wbr:1};
function clean(v){return C.clean(String(v==null?'':v));}
function nodes(h,s){try{return pdfa(String(h||''),s)||[];}catch(e){return [];}}
function text(h,s){try{return clean(pdfh(h,s)||'');}catch(e){return '';}}
function attr(h,s){try{return String(pdfh(h,s)||'').replace(/&amp;/g,'&').trim();}catch(e){return '';}}
function good(u){var s=String(u||'').toLowerCase();if(!s)return false;if(s.indexOf('data:image')===0)return false;if(s.indexOf('placeholder')>=0)return false;if(s.indexOf('loading')>=0)return false;if(s.indexOf('spinner')>=0)return false;if(s.indexOf('transparent')>=0)return false;if(s.indexOf('blank.')>=0)return false;return true;}
function srcset(u){var s=String(u||'').trim();if(!s)return '';var p=s.split(',')[0].trim(),i=p.indexOf(' ');return i>0?p.slice(0,i):p;}
function htmlAttr(tag,name){tag=String(tag||'');var a=[' '+name+'="',' '+name+"='"];for(var i=0;i<a.length;i++){var p=tag.indexOf(a[i]);if(p<0)continue;p+=a[i].length;var q=tag.indexOf(i===0?'"':"'",p);if(q>p)return tag.slice(p,q).replace(/&amp;/g,'&');}return '';}
function imageFromTag(tag,base){var a=['data-src','data-original','data-lazy-src','src','data-srcset','srcset'];for(var i=0;i<a.length;i++){var u=htmlAttr(tag,a[i]);if(a[i].indexOf('srcset')>=0)u=srcset(u);if(good(u))return C.abs(base,u);}return '';}
function firstImg(raw,base){raw=String(raw||'');var re=/<img\b[^>]*>/ig,m;while((m=re.exec(raw))){var u=imageFromTag(m[0],base);if(good(u))return u;}return '';}
function tagName(tag){var m=String(tag||'').match(/^<\s*\/?\s*([A-Za-z0-9:_-]+)/);return m?String(m[1]).toLowerCase():'';}
function isClose(tag){return /^<\s*\//.test(String(tag||''));}
function selfClose(tag,name){return /\/\s*>$/.test(String(tag||''))||!!VOID[String(name||'').toLowerCase()];}
function openForId(raw,id){raw=String(raw||'');var a=['id="'+id+'"',"id='"+id+"'"],p=-1;for(var i=0;i<a.length;i++){var x=raw.indexOf(a[i]);if(x>=0&&(p<0||x<p))p=x;}if(p<0)return null;var s=raw.lastIndexOf('<',p),e=raw.indexOf('>',p);if(s<0||e<s)return null;return {start:s,openEnd:e+1,tag:raw.slice(s,e+1),name:tagName(raw.slice(s,e+1))};}
function bounds(raw,op){if(!op||!op.name)return null;if(selfClose(op.tag,op.name))return {start:op.start,openEnd:op.openEnd,end:op.openEnd,name:op.name,tag:op.tag};var re=/<\/?[A-Za-z][^>]*>/g,depth=1,m;re.lastIndex=op.openEnd;while((m=re.exec(raw))){var n=tagName(m[0]);if(n!==op.name)continue;if(isClose(m[0])){depth--;if(depth===0)return {start:op.start,openEnd:op.openEnd,end:re.lastIndex,name:op.name,tag:op.tag};}else if(!selfClose(m[0],n))depth++;}return {start:op.start,openEnd:op.openEnd,end:op.openEnd,name:op.name,tag:op.tag};}
function innerForId(raw,id){var b=bounds(String(raw||''),openForId(raw,id));if(!b||b.end<=b.openEnd)return '';var close=String(raw||'').lastIndexOf('</'+b.name,b.end);if(close<b.openEnd)return '';return String(raw||'').slice(b.openEnd,close);}
function innerForIdPrefix(raw,prefix){raw=String(raw||'');var re=/id\s*=\s*["']([^"']+)["']/ig,m;while((m=re.exec(raw))){if(String(m[1]).indexOf(prefix)!==0)continue;var s=raw.lastIndexOf('<',m.index),e=raw.indexOf('>',m.index);if(s<0||e<s)continue;var op={start:s,openEnd:e+1,tag:raw.slice(s,e+1),name:tagName(raw.slice(s,e+1))},b=bounds(raw,op);if(!b||b.end<=b.openEnd)return '';var close=raw.lastIndexOf('</'+b.name,b.end);if(close<b.openEnd)return '';return raw.slice(b.openEnd,close);}return '';}
function topChildren(inner){inner=String(inner||'');var out=[],stack=[],start=-1,re=/<\/?[A-Za-z][^>]*>/g,m;while((m=re.exec(inner))){var tag=m[0],name=tagName(tag);if(!name)continue;if(isClose(tag)){if(stack.length){stack.pop();if(!stack.length&&start>=0){out.push(inner.slice(start,re.lastIndex));start=-1;}}continue;}if(!stack.length)start=m.index;if(selfClose(tag,name)){if(!stack.length&&start>=0){out.push(inner.slice(start,re.lastIndex));start=-1;}}else stack.push(name);}return out;}
function commentGroups(body,base){var inner=innerForId(body,'comment-start'),ch=topChildren(inner),out=[];for(var i=0;i<ch.length;i+=4){var g=ch.slice(i,i+4).join(''),id='',m=g.match(/id\s*=\s*["']reply-section-wrapper-([^"']+)["']/i);if(m)id=String(m[1]);out.push({id:id,avatar:firstImg(g,base),raw:g});}return out;}
function replyGroups(body,base){var inner=innerForIdPrefix(body,'reply-start'),ch=topChildren(inner),out=[];for(var i=0;i+1<ch.length;i+=2){out.push({avatar:firstImg(ch[i],base),raw:ch[i]+ch[i+1]});}return out;}
function exactArtistSibling(raw,base){var op=openForId(raw,'video-user-avatar');if(!op)return '';var own=imageFromTag(op.tag,base);if(good(own))return own;var b=bounds(String(raw||''),op);if(!b)return '';var p=b.end,s=String(raw||''),limit=Math.min(s.length,p+12000);while(p<limit){var x=s.indexOf('<',p);if(x<0||x>=limit)break;if(s.slice(x,x+4)==='<!--'){var ce=s.indexOf('-->',x+4);p=ce>=0?ce+3:x+4;continue;}var e=s.indexOf('>',x);if(e<0||e>=limit)break;var tag=s.slice(x,e+1),name=tagName(tag);if(isClose(tag)){p=e+1;continue;}if(name==='img'){var u=imageFromTag(tag,base);if(good(u))return u;}if(name&&name!=='script'&&name!=='style'&&name!=='span'&&name!=='div'&&name!=='a')break;p=e+1;}return '';}
function artistSearchAvatar(name,base){name=clean(name);if(!name)return '';try{var url=C.query(base+'/search',{type:'artist',query:name,page:1}),r=C.get(url,{base:base,referer:base+'/',timeout:16000});if(!r||r.challenge||Number(r.statusCode||0)>=400)return '';var a=nodes(r.body,'.search-artist-card');for(var i=0;i<a.length;i++){var n=text(a[i],'.search-artist-title&&Text')||text(a[i],'.title&&Text');if(clean(n)!==name)continue;var u=attr(a[i],'img[style*=object-fit]&&src')||attr(a[i],'img&&src')||attr(a[i],'img&&data-src');if(good(u))return C.abs(base,u);}}catch(e){}return '';}
function imageUrl(u,base){u=String(u||'').trim();if(!good(u))return '';return C.abs(base,u);}
function plainUrl(u){return String(u||'').split('@headers=')[0].replace(/&amp;/g,'&').trim();}
var DIAG={build:'2.0.0-test.21',artistMethod:'',artistAvatar:'',commentGroups:0,commentGroupAvatars:0,commentMatchedAvatars:0,replyGroups:0,replyGroupAvatars:0};
P.video=function(id){var v=oldVideo(id),base=(v&&v.base)||C.resolveHost(false),u='';DIAG.artistMethod='';DIAG.artistAvatar='';if(v){u=exactArtistSibling(String(v.raw||''),base);if(good(u)&&v.uploader&&good(v.uploader.avatar)&&clean(v.artist)!==clean(v.uploader.name)&&plainUrl(u)===plainUrl(v.uploader.avatar))u='';if(good(u))DIAG.artistMethod='detail-sibling';if(!good(u)){u=artistSearchAvatar(v.artist,base);if(good(u))DIAG.artistMethod='artist-search';}if(good(u)){v.artistAvatar=imageUrl(u,base);DIAG.artistAvatar=v.artistAvatar;}else v.artistAvatar='';}return v;};
P.comments=function(videoId){var r=oldComments(videoId);if(!r||!r.items||!r.items.length)return r;var base=C.resolveHost(false);try{var x=C.get(C.query(base+'/loadComment',{type:'video',id:videoId}),{base:base,referer:base+'/watch?v='+videoId,timeout:16000});if(x&&!x.challenge&&Number(x.statusCode||0)<400){var body=String(x.body||'');try{var j=JSON.parse(body);if(j&&typeof j.comments==='string')body=j.comments;}catch(e){}var g=commentGroups(body,base),map={},found=0,matched=0;for(var i=0;i<g.length;i++){if(g[i].id)map[String(g[i].id)]=g[i];if(g[i].avatar)found++;}for(var k=0;k<r.items.length;k++){var it=r.items[k],z=it&&it.id?map[String(it.id)]:null;if(!z&&k<g.length)z=g[k];if(z&&good(z.avatar)){it.avatar=imageUrl(z.avatar,base);matched++;}else it.avatar='';}DIAG.commentGroups=g.length;DIAG.commentGroupAvatars=found;DIAG.commentMatchedAvatars=matched;}}catch(e){}return r;};
P.replies=function(commentId){var a=oldReplies(commentId)||[];if(!a.length)return a;var base=C.resolveHost(false);try{var x=C.get(C.query(base+'/loadReplies',{id:commentId}),{base:base,referer:base+'/',timeout:16000});if(x&&!x.challenge&&Number(x.statusCode||0)<400){var body=String(x.body||'');try{var j=JSON.parse(body);if(j&&typeof j.replies==='string')body=j.replies;}catch(e){}var g=replyGroups(body,base),found=0;for(var i=0;i<g.length;i++)if(g[i].avatar)found++;for(var k=0;k<a.length;k++){if(k<g.length&&good(g[k].avatar))a[k].avatar=imageUrl(g[k].avatar,base);else a[k].avatar='';}DIAG.replyGroups=g.length;DIAG.replyGroupAvatars=found;}}catch(e){}return a;};
P.avatarDiagnostic21=function(videoId){try{P.video(videoId);}catch(e){DIAG.videoError=String(e.message||e);}try{P.comments(videoId);}catch(e2){DIAG.commentError=String(e2.message||e2);}return JSON.parse(JSON.stringify(DIAG));};
HanimePages.build='2.0.0-test.21';HanimeCore.build='2.0.0-test.21';HanimeProvider.build='2.0.0-test.21';
})(HanimeCore,HanimeProvider,HanimePages);
