/* JavMenu Runtime 0.1.0-test.2 - semantic native Hiker UI */
var JavMenuRuntime=(function(){
  var R={version:'0.1.0-test.2',build:10102};
  var ROOT='https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/';
  var BOOT=ROOT+'apps/video/javmenu/bootstrap_test_v2_b10102.js?v=10102';
  var BRAND=ROOT+'apps/video/javmenu/assets/icon.svg?v=10102';
  var MISS=ROOT+'apps/video/javmenu/assets/missav.svg?v=10102';
  var JABLE=ROOT+'apps/video/javmenu/assets/jable.svg?v=10102';
  function C(){if(typeof JavMenuCore!=='object')throw new Error('JavMenuCore 未加载');return JavMenuCore;}
  function P(){if(typeof JavMenuPlayback!=='object')throw new Error('JavMenuPlayback 未加载');return JavMenuPlayback;}
  function section(title,desc){return{title:'““””<b><font color=#7057D9>▌ '+title+'</font></b>',desc:desc||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}};}
  function empty(title,desc,url){return{title:title||'暂无内容',desc:desc||'',url:url||'hiker://empty',col_type:'text_center_1',extra:{lineVisible:false}};}
  function bootLazy(method,args){args=args||[];return $('#noLoading#').lazyRule(function(boot,build,method,args){try{require(boot,{headers:{'Cache-Control':'no-cache'}},build);var m=JavMenuBoot.module();return m.invoke(method,args||[]);}catch(e){return'toast://JavMenu '+method+' 执行失败：'+String(e.message||e);}},BOOT,10102,method,args);}
  function titleLine(name,on){return on?'““””<b><font color=#7057D9>'+name+'</font></b>':name;}
  function movieCard(m){var code=m.code||'',sub=[],title=C().strip(m.title||'');if(title&&title!==code)sub.push(title);if(m.remark)sub.push(m.remark);return{title:code||title,desc:sub.join(' · '),img:m.img||'',pic_url:m.img||'',url:C().page('detail',{code:code}),col_type:'movie_3',extra:{pageTitle:code,lineVisible:false,longClick:[{title:'收藏 / 取消收藏',js:$.toString(function(boot,m){require(boot,{headers:{'Cache-Control':'no-cache'}},10102);return JavMenuBoot.module().invoke('toggleVideo',[m]);},BOOT,m)},{title:'复制番号',js:$.toString(function(code){return'copy://'+code;},code)},{title:'原站详情',js:$.toString(function(href){return href;},m.href||C().detailUrl(code))}]}};}
  function renderMovies(d,html,ref,emptyText){var a=C().parseMovies(html,ref),i;for(i=0;i<a.length;i++)d.push(movieCard(a[i]));if(!a.length)d.push(empty(emptyText||'没有解析到影片','当前页面没有识别到 .video-list-item；可从“设置 → 诊断”查看最近请求。','web://'+ref));return a.length;}
  function searchInput(d,kw){d.push({title:kw||'搜索番号 / 标题 / 演员',url:"(function(){var q=String(input||'').trim();if(!q)return 'toast://请输入关键词';return '"+C().page('search',{kw:'__KW__'}).replace('__KW__','')+"'+encodeURIComponent(q);})()",col_type:'input',extra:{titleVisible:false,lineVisible:false,hint:'输入番号、标题、演员关键词…'}});}
  function quick(d){d.push({title:'发现',img:'hiker://images/icon_menu5',url:C().page('discover',{}),col_type:'icon_small_4',extra:{lineVisible:false}});d.push({title:'收藏',img:'hiker://images/icon_star',url:C().page('favorites',{}),col_type:'icon_small_4',extra:{lineVisible:false}});d.push({title:'历史',img:'hiker://images/icon_history',url:'hiker://history?rule='+MY_RULE.title,col_type:'icon_small_4',extra:{lineVisible:false}});d.push({title:'设置',img:'hiker://images/icon_setting',url:C().page('settings',{}),col_type:'icon_small_4',extra:{lineVisible:false}});}
  function categoryUrl(x){return x.kind==='people-index'?C().page('peopleIndex',{path:x.path,name:x.name}):C().page('list',{path:x.path,name:x.name});}

  R.home=function(){var d=[],pg=Number(MY_PAGE||1),url=C().homeUrl(pg),html;if(pg===1){setPageTitle('JavMenu');d.push({title:'JavMenu',desc:'原站影片 · 本地收藏 · 多源播放',img:BRAND,pic_url:BRAND,url:'web://'+C().base+C().homePath,col_type:'avatar',extra:{lineVisible:false}});searchInput(d,'');quick(d);d.push(section('最近更新','当前官网影片列表 · Test 0.1.0-test.2'));}html=C().fetchHtml(url);if(C().isBadHtml(html)){if(pg===1)d.push(empty('JavMenu 暂时无法读取','已尝试 javmenu.com / javmenu.org 与当前请求策略。','web://'+url));setResult(d);return;}renderMovies(d,html,url,'本页没有解析到影片');setResult(d);};

  R.search=function(){var d=[],kw=C().get('kw','');if(!kw&&typeof MY_KEYWORD!=='undefined')kw=String(MY_KEYWORD||'');kw=C().trim(kw);var pg=Number(MY_PAGE||1),url=C().searchUrl(kw,pg),html;if(pg===1){setPageTitle('搜索 · '+kw);searchInput(d,kw);d.push(section('搜索结果',kw||'请输入关键词'));}if(!kw){d.push(empty('请输入关键词','支持番号、标题、演员等官网可搜索字段'));setResult(d);return;}html=C().fetchHtml(url);if(C().isBadHtml(html)){if(pg===1)d.push(empty('搜索请求失败','可打开原站搜索页核对当前站点状态。','web://'+url));setResult(d);return;}renderMovies(d,html,url,'没有找到匹配影片');setResult(d);};

  R.discover=function(){var d=[],a=C().categories(),groups=['在线分类','排行榜','资源分类'],g,i,x;setPageTitle('发现');d.push(section('JavMenu 分类','Test2 按当前官网已确认路由分组，不再扫描整页导航制造重复入口'));for(g=0;g<groups.length;g++){d.push(section(groups[g],g===0?'有码 / 无码 / FC2 / 国产 / 欧美 / 动画':g===1?'日榜 / 周榜 / 月榜 / 女优榜':'有码 / 无码磁力'));for(i=0;i<a.length;i++){x=a[i];if(x.group!==groups[g])continue;d.push({title:x.name,url:categoryUrl(x),col_type:'flex_button',extra:{lineVisible:false}});}}setResult(d);};

  R.list=function(){var d=[],raw=C().get('path',''),name=C().get('name','列表'),pg=Number(MY_PAGE||1),url=C().listUrl(raw,pg),html;if(pg===1){setPageTitle(name);d.push(section(name,'JavMenu 影片列表'));}if(!raw){d.push(empty('缺少分类地址','返回发现页重新选择。'));setResult(d);return;}html=C().fetchHtml(url);if(C().isBadHtml(html)){if(pg===1)d.push(empty('页面读取失败','当前分类地址暂不可用。','web://'+url));setResult(d);return;}renderMovies(d,html,url,'当前分类没有解析到影片');setResult(d);};

  function personCard(x){var pic=x.img||BRAND;return{title:x.name||'人物',desc:'JavMenu 女优 / 演员',img:pic,pic_url:pic,url:C().page('person',{path:x.href,name:x.name}),col_type:'avatar',extra:{lineVisible:false,longClick:[{title:'收藏 / 取消收藏人物',js:$.toString(function(boot,x){require(boot,{headers:{'Cache-Control':'no-cache'}},10102);return JavMenuBoot.module().invoke('togglePeople',[x]);},BOOT,x)}]}};}
  R.peopleIndex=function(){var d=[],raw=C().get('path','/zh/rank/censored/actress'),name=C().get('name','女优榜'),pg=Number(MY_PAGE||1),url=C().listUrl(raw,pg),html,a,i;if(pg===1){setPageTitle(name);d.push(section(name,'JavMenu 当前女优 / 演员索引'));}html=C().fetchHtml(url);if(C().isBadHtml(html)){if(pg===1)d.push(empty('女优榜读取失败','可打开原站核对当前页面。','web://'+url));setResult(d);return;}a=C().parseActressIndex(html,url);if(!a.length){d.push(empty('当前页没有解析到人物','Test2 已切换为独立人物索引 Adapter；若仍为空请继续截图。','web://'+url));setResult(d);return;}for(i=0;i<a.length;i++)d.push(personCard(a[i]));setResult(d);};
  R.person=function(){var d=[],raw=C().get('path',''),fallback=C().get('name','女优'),pg=Number(MY_PAGE||1),url=C().listUrl(raw,pg),html,name;if(!raw){d.push(empty('缺少人物地址','请从女优榜或详情演员重新进入。'));setResult(d);return;}html=C().fetchHtml(url);if(C().isBadHtml(html)){setPageTitle(fallback);d.push(empty('人物页面读取失败','可打开原站核对。','web://'+url));setResult(d);return;}name=C().personName(html,fallback);if(pg===1){setPageTitle(name);d.push(section(name+' · 作品','来自 JavMenu 当前人物页面'));}renderMovies(d,html,url,'该人物当前没有解析到作品');setResult(d);};

  function detailActions(d,x){d.push({title:'““””<b><font color=#7057D9>▶ 立即播放</font></b>',url:bootLazy('playSite',[x.code,x.url,'']),col_type:'text_center_1',extra:{lineVisible:false}});}
  function sharedPlay(d,code){if(getItem('javmenu_alt_play','1')==='0')return;var ps=[{id:'missav',name:'MissAV',img:MISS},{id:'123av',name:'123AV',img:ROOT+'shared/jav-playback/assets/123av.svg?v=10004'},{id:'jable',name:'Jable',img:JABLE}],i;d.push(section('备用播放','按番号调用 Shared JAV Playback；不影响 JavMenu 原站链'));for(i=0;i<ps.length;i++)d.push({title:ps[i].name,img:ps[i].img,pic_url:ps[i].img,url:bootLazy('playShared',[ps[i].id,code]),col_type:'icon_small_3',extra:{lineVisible:false}});}
  function magnetLong(url){return[{title:'复制磁力',js:$.toString(function(u){return'copy://'+u;},url)},{title:'PikPak',js:$.toString(function(u){if(fetch('hiker://home@PikPak')==='null')return'toast://未安装 PikPak';return'hiker://page/fxlj?rule=PikPak&realurl='+encodeURIComponent(u);},url)},{title:'123云盘',js:$.toString(function(u){if(fetch('hiker://home@123云盘')==='null')return'toast://未安装 123云盘';return'hiker://page/diaoyong?rule=123云盘&page=fypage&realurl='+encodeURIComponent(u);},url)},{title:'迅雷',js:$.toString(function(u){if(fetch('hiker://home@迅雷')==='null')return'toast://未安装 迅雷';return'hiker://page/diaoyong?rule=迅雷&page=fypage#'+u;},url)}];}

  R.detail=function(){var d=[],code=C().normalizeCode(C().get('code',''));if(!code){d.push(empty('缺少影片番号','请从影片卡片重新进入详情'));setResult(d);return;}var url=C().detailUrl(code),html=C().fetchHtml(url);if(C().isBadHtml(html)){setPageTitle(code);d.push(empty('详情读取失败','原站详情暂不可用；仍可尝试备用番号播放。','web://'+url));sharedPlay(d,code);setResult(d);return;}var x=C().parseDetail(html,code,url),i,p,desc=[x.code,x.date,x.duration].filter(function(v){return!!v;}).join(' · ');setPageTitle(x.code||code);d.push({title:x.title||x.code,desc:desc,img:x.img||BRAND,pic_url:x.img||BRAND,url:'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});detailActions(d,x);
    if(x.players.length){d.push(section('站内线路','只保留 JavMenu 正式播放字段；预览/试看媒体已排除'));for(i=0;i<x.players.length;i++){p=x.players[i];d.push({title:p.name||('线路 '+(i+1)),url:bootLazy('playSite',[x.code,x.url,p.url]),col_type:'scroll_button',extra:{lineVisible:false}});}}
    d.push(section('影片信息','JavMenu 当前详情页'));d.push({title:'番号 · '+x.code,url:'copy://'+x.code,col_type:'text_1',extra:{lineVisible:false}});if(x.desc)d.push({title:x.desc,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});
    if(x.people.length){d.push(section('演员 / 人物','仅识别详情页真实 /actor/ 链接'));for(i=0;i<x.people.length;i++)d.push(personCard(x.people[i]));}
    if(x.tags.length){d.push(section('标签 / 系列 / 制作信息','仅保留 genre / series / studio / maker / label / director / tag 元数据'));for(i=0;i<x.tags.length;i++){p=x.tags[i];d.push({title:p.name,url:C().page('list',{path:p.href,name:p.name}),col_type:'flex_button',extra:{lineVisible:false}});}}
    if(x.samples.length){d.push(section('预览图',x.samples.length+' 张'));for(i=0;i<x.samples.length;i++){p=x.samples[i];d.push({title:p.title||'',img:p.thumb,pic_url:p.thumb,url:'pics://'+p.src,col_type:'pic_3',extra:{lineVisible:false}});}}
    if(x.magnets.length){d.push(section('磁力资源','点击复制；长按调用已安装云盘小程序'));for(i=0;i<x.magnets.length;i++){p=x.magnets[i];d.push({title:p.title,desc:x.code,url:'copy://'+p.url,col_type:'text_1',extra:{lineVisible:false,longClick:magnetLong(p.url)}});}}
    sharedPlay(d,x.code);
    if(x.related.length){d.push(section('相关推荐','来自当前 JavMenu 详情页影片卡'));for(i=0;i<x.related.length;i++)d.push(movieCard(x.related[i]));}
    d.push(section('更多','低频详情动作'));d.push({title:C().isFav('video',x.code)?'已收藏':'收藏',url:bootLazy('toggleVideo',[{code:x.code,title:x.title,img:x.img,href:x.url}]),col_type:'text_3',extra:{lineVisible:false}});d.push({title:'复制番号',url:'copy://'+x.code,col_type:'text_3',extra:{lineVisible:false}});d.push({title:'原站',url:'web://'+x.url,col_type:'text_3',extra:{lineVisible:false}});setResult(d);};

  R.favorites=function(){var d=[],kind=getMyVar('javmenu_fav_kind','video'),a=C().loadFav(kind),i,x;setPageTitle('我的收藏');d.push({title:titleLine('影片',kind==='video'),url:$('#noLoading#').lazyRule(function(){putMyVar('javmenu_fav_kind','video');refreshPage(false);return'hiker://empty';}),col_type:'scroll_button'});d.push({title:titleLine('人物',kind==='people'),url:$('#noLoading#').lazyRule(function(){putMyVar('javmenu_fav_kind','people');refreshPage(false);return'hiker://empty';}),col_type:'scroll_button'});d.push(section(kind==='video'?'影片收藏':'人物收藏',a.length+' 项 · 仅保存在本机'));if(!a.length){d.push(empty('还没有收藏','在影片卡片/详情或人物卡片长按即可加入'));setResult(d);return;}for(i=0;i<a.length;i++){x=a[i];if(kind==='video')d.push(movieCard({code:x.code,title:x.title||x.code,img:x.img||'',href:x.href||C().detailUrl(x.code)}));else d.push(personCard(x));}setResult(d);};

  R.settings=function(){var d=[],mode=getItem('javmenu_request_mode','auto'),alt=getItem('javmenu_alt_play','1'),diag=C().lastDiag();setPageTitle('JavMenu 设置');d.push(section('体验','只保留直接影响运行的设置'));d.push({title:'网页请求 · '+(mode==='auto'?'自动':mode==='network'?'普通请求':'WebView'),desc:'自动：普通请求失败后再用 WebView；并尝试 .com / .org 备用域',url:'select://'+JSON.stringify({title:'网页请求方式',options:['自动','普通请求','WebView'],col:3,js:$.toString(function(){var m=input==='普通请求'?'network':input==='WebView'?'webview':'auto';setItem('javmenu_request_mode',m);refreshPage(false);return'toast://已切换 '+input;})}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'备用番号播放 · '+(alt==='1'?'开启':'关闭'),desc:'MissAV / 123AV / Jable；JavMenu 原站播放始终优先',url:$('#noLoading#').lazyRule(function(){var v=getItem('javmenu_alt_play','1')==='1'?'0':'1';setItem('javmenu_alt_play',v);refreshPage(false);return'toast://备用播放已'+(v==='1'?'开启':'关闭');}),col_type:'text_1',extra:{lineVisible:false}});d.push(section('诊断','不展示 Cookie / Token 等敏感信息'));d.push({title:'版本 · '+R.version+' / Build '+R.build,desc:'Core '+C().version+' · Playback '+P().version,url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'最近请求 · '+(diag.stage||'暂无'),desc:(diag.url||'尚无诊断记录')+'\n'+(diag.extra||''),url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});d.push({title:'原站首页',url:'web://'+C().base+C().homePath,col_type:'text_1',extra:{lineVisible:false}});setResult(d);};

  R.route=function(){var v=C().get('view','home');if(v==='detail')return R.detail();if(v==='search')return R.search();if(v==='discover')return R.discover();if(v==='list')return R.list();if(v==='peopleIndex')return R.peopleIndex();if(v==='person')return R.person();if(v==='favorites')return R.favorites();if(v==='settings')return R.settings();return R.home();};
  R.invoke=function(method,args){args=args||[];if(method==='playSite')return P().site(args[0],args[1],args[2]);if(method==='playShared')return P().shared(args[0],args[1]);if(method==='toggleVideo'){var on=C().toggleFav('video',args[0]||{});try{refreshPage(false);}catch(e){}return'toast://'+(on?'已收藏影片':'已取消影片收藏');}if(method==='togglePeople'){var on2=C().toggleFav('people',args[0]||{});try{refreshPage(false);}catch(e2){}return'toast://'+(on2?'已收藏人物':'已取消人物收藏');}return'toast://未知动作 '+method;};
  return R;
})();
if(typeof $!=='undefined')$.exports=JavMenuRuntime;
