(function(){
var d=[];
var api=$.require("115Api");
var client;
try{client=api.newClient();}catch(e){d.push({title:"115未登录",desc:String(e.message||e),col_type:"text_center_1",url:"hiker://page/115Account?rule=115.简&page=fypage"});setResult(d);return;}
function q(n,v){var x="";try{x=String(getParam(n,"")||"");}catch(e){}if(x){try{x=decodeURIComponent(x);}catch(e2){}return x;}try{if(typeof MY_PARAMS!=="undefined"&&MY_PARAMS&&MY_PARAMS[n]!=null)return String(MY_PARAMS[n]);}catch(e3){}return v||"";}
function fmtSize(n){try{return api.tool.formatSize(Number(n||0));}catch(e){return "";}}
function methodNames(o){var hit={},out=[],cur=o,depth=0;while(cur&&depth<4){try{var ns=Object.getOwnPropertyNames(cur);for(var i=0;i<ns.length;i++){var n=String(ns[i]||"");if(!n||hit[n])continue;hit[n]=1;if(/delete|remove|recycle|trash|request|file/i.test(n))out.push(n);}}catch(e){}try{cur=Object.getPrototypeOf(cur);}catch(e2){break;}depth++;}out.sort();return out.slice(0,24);}
function checkResp(r){if(r&&r.state===false)throw new Error(r.error||r.msg||"115返回失败");if(r&&r.code!==undefined&&Number(r.code)!==0&&Number(r.code)!==200)throw new Error(r.message||r.msg||("115返回code="+r.code));return r;}
function deleteToRecycle(c,id){var sid=String(id),last="";function run(name,args){try{if(c&&typeof c[name]==="function")return {ok:true,val:checkResp(c[name].apply(c,args))};}catch(e){last=name+"："+String(e.message||e);}return {ok:false};}var r;r=run("delete",[[sid]]);if(r.ok)return r.val;r=run("deleteFiles",[[sid]]);if(r.ok)return r.val;r=run("deleteFile",[sid]);if(r.ok)return r.val;r=run("removeFiles",[[sid]]);if(r.ok)return r.val;r=run("removeFile",[sid]);if(r.ok)return r.val;r=run("trashFiles",[[sid]]);if(r.ok)return r.val;r=run("trashFile",[sid]);if(r.ok)return r.val;try{if(c&&typeof c.fsDelete==="function")return checkResp(c.fsDelete({file_ids:sid}));}catch(e1){last="fsDelete："+String(e1.message||e1);}try{if(c&&typeof c.request==="function")return checkResp(c.request({path:"/open/ufile/delete",method:"POST",form:{file_ids:sid}}));}catch(e2){last="request/open/ufile/delete："+String(e2.message||e2);}var ms=methodNames(c);throw new Error((last?last+"；":"")+"当前115Api仍无可用删除入口"+(ms.length?"；相关方法："+ms.join(", "):""));}
var cid=q("cid","0"),cname=q("cname","我的文件"),pageNo=1;try{pageNo=parseInt(MY_PAGE||1,10)||1;}catch(e4){}
if(pageNo===1){d.push({title:"📁 "+cname,col_type:"text_1",extra:{lineVisible:false}});d.push({title:"🗑 回收站",col_type:"text_2",url:"hiker://page/115Recycle?rule=115.简&page=fypage"});d.push({title:"↻ 刷新",col_type:"text_2",url:$("刷新").lazyRule(function(){refreshPage(false);return false;})});}
var res;try{res=client.getFiles(String(cid),{offset:(pageNo-1)*50,pageSize:50,order:"file_name",asc:"1",showDir:"1"});}catch(e5){d.push({title:"读取文件失败",desc:String(e5.message||e5),col_type:"text_center_1"});setResult(d);return;}
var arr=(res&&res.files)||[];
for(var i=0;i<arr.length;i++){
 var f=arr[i]||{},fid=String(f.fileId||""),name=String(f.name||"未命名"),isDir=!!f.isDirectory;
 var item={title:(isDir?"📁 ":"📄 ")+name,desc:isDir?"":fmtSize(f.size),col_type:"text_1",url:"toast://长按可管理",extra:{longClick:[]}};
 if(isDir)item.url="hiker://page/115FileManage?rule=115.简&page=fypage&cid="+encodeURIComponent(fid)+"&cname="+encodeURIComponent(name);else{var kind="";try{kind=api.tool.fileKind(name);}catch(e6){}if(kind==="video")item.url=$().lazyRule(api.player.resolve,JSON.stringify({pc:f.pickCode||"",fid:fid,name:name,kind:"video"}));}
 item.extra.longClick.push({title:"删除到回收站",js:$.toString(function(id,nm){return $("确认删除「"+nm+"」？\n删除后可在回收站还原").confirm(function(fileId){try{var api2=$.require("115Api"),c=api2.newClient(),sid=String(fileId),last="";function ck(r){if(r&&r.state===false)throw new Error(r.error||r.msg||"115返回失败");if(r&&r.code!==undefined&&Number(r.code)!==0&&Number(r.code)!==200)throw new Error(r.message||r.msg||("115返回code="+r.code));return r;}function call(name,args){try{if(c&&typeof c[name]==="function"){ck(c[name].apply(c,args));return true;}}catch(e){last=name+"："+String(e.message||e);}return false;}if(!call("delete",[[sid]])&&!call("deleteFiles",[[sid]])&&!call("deleteFile",[sid])&&!call("removeFiles",[[sid]])&&!call("removeFile",[sid])&&!call("trashFiles",[[sid]])&&!call("trashFile",[sid])){var done=false;try{if(c&&typeof c.fsDelete==="function"){ck(c.fsDelete({file_ids:sid}));done=true;}}catch(e1){last="fsDelete："+String(e1.message||e1);}if(!done)try{if(c&&typeof c.request==="function"){ck(c.request({path:"/open/ufile/delete",method:"POST",form:{file_ids:sid}}));done=true;}}catch(e2){last="request/open/ufile/delete："+String(e2.message||e2);}if(!done){var out=[],hit={},cur=c,dep=0;while(cur&&dep<4){try{var ns=Object.getOwnPropertyNames(cur);for(var z=0;z<ns.length;z++){var n=String(ns[z]||"");if(!n||hit[n])continue;hit[n]=1;if(/delete|remove|recycle|trash|request|file/i.test(n))out.push(n);}}catch(ex0){}try{cur=Object.getPrototypeOf(cur);}catch(ex1){break;}dep++;}out.sort();return "toast://删除失败："+(last?last+"；":"")+"无可用删除入口"+(out.length?"；相关方法："+out.slice(0,18).join(", "):"");}}refreshPage(false);return "toast://已移入回收站";}catch(ex){return "toast://删除失败："+String(ex.message||ex);}},id);},fid,name)});
 d.push(item);
}
if(!arr.length&&pageNo===1)d.push({title:"这里是空的",col_type:"text_center_1"});
setResult(d);
})();