(function(){
var d=[];
var api=$.require("115Api"),client;
try{client=api.newClient();}catch(e){d.push({title:"115未登录",desc:String(e.message||e),col_type:"text_center_1"});setResult(d);return;}
function fmtSize(n){try{return api.tool.formatSize(Number(n||0));}catch(e){return"";}}
function listRecycle(c,offset,limit){var fn=null;try{if(c&&typeof c.listRecycleBin==="function")fn=c.listRecycleBin;}catch(e){}if(!fn)try{if(c&&typeof c.getRecycleBin==="function")fn=c.getRecycleBin;}catch(e2){}if(!fn)throw new Error("当前115Api未提供回收站列表方法");return fn.call(c,Number(offset||0),Number(limit||40));}
function methodNames(o){var hit={},out=[],cur=o,depth=0;while(cur&&depth<4){try{var ns=Object.getOwnPropertyNames(cur);for(var i=0;i<ns.length;i++){var n=String(ns[i]||"");if(!n||hit[n])continue;hit[n]=1;if(/delete|remove|recycle|trash|clean|request/i.test(n))out.push(n);}}catch(e){}try{cur=Object.getPrototypeOf(cur);}catch(e2){break;}depth++;}out.sort();return out.slice(0,24);}
function checkResp(r){if(r&&r.state===false)throw new Error(r.error||r.msg||"115返回失败");if(r&&r.code!==undefined&&Number(r.code)!==0&&Number(r.code)!==200)throw new Error(r.message||r.msg||("115返回code="+r.code));return r;}
function restoreRecycle(c,ids){var fn=null;try{if(c&&typeof c.revertRecycleBin==="function")fn=c.revertRecycleBin;}catch(e){}if(!fn)try{if(c&&typeof c.restoreRecycleBin==="function")fn=c.restoreRecycleBin;}catch(e2){}if(!fn)throw new Error("当前115Api未提供回收站还原方法");return checkResp(fn.call(c,ids));}
function permanentDelete(c,id){var sid=String(id),last="";try{if(c&&typeof c.cleanRecycleBin==="function")return checkResp(c.cleanRecycleBin("",[sid]));}catch(e0){last="cleanRecycleBin："+String(e0.message||e0);}try{if(c&&typeof c.deleteRecycleBin==="function")return checkResp(c.deleteRecycleBin([sid]));}catch(e1){last="deleteRecycleBin："+String(e1.message||e1);}try{if(c&&typeof c.removeRecycleBin==="function")return checkResp(c.removeRecycleBin([sid]));}catch(e2){last="removeRecycleBin："+String(e2.message||e2);}try{if(c&&typeof c.recyclebinClean==="function")return checkResp(c.recyclebinClean({recycle_item_ids:sid}));}catch(e3){last="recyclebinClean："+String(e3.message||e3);}try{if(c&&typeof c.request==="function")return checkResp(c.request({path:"/open/rb/del",method:"POST",form:{tid:sid}}));}catch(e4){last="request/open/rb/del："+String(e4.message||e4);}var ms=methodNames(c);throw new Error((last?last+"；":"")+"当前115Api仍无永久删除入口"+(ms.length?"；相关方法："+ms.join(", "):""));}
var p=1;try{p=parseInt(MY_PAGE||1,10)||1;}catch(e3){}
if(p===1){d.push({title:"🗑 回收站",desc:"点击条目还原 · 长按条目永久删除",col_type:"text_1",extra:{lineVisible:false}});d.push({title:"↻ 刷新",col_type:"text_2",url:$("刷新").lazyRule(function(){refreshPage(false);return false;})});d.push({title:"📁 文件管理",col_type:"text_2",url:"hiker://page/115FileManage?rule=115.简&page=fypage&cid=0&cname="+encodeURIComponent("我的文件")});}
var offset=(p-1)*40,raw;
try{raw=listRecycle(client,offset,40);}catch(e4){d.push({title:"读取回收站失败",desc:String(e4.message||e4),col_type:"text_center_1"});setResult(d);return;}
var a=[];if(raw instanceof Array)a=raw;else if(raw&&raw.data instanceof Array)a=raw.data;else if(raw&&raw.items instanceof Array)a=raw.items;else if(raw&&raw.list instanceof Array)a=raw.list;
for(var i=0;i<a.length;i++){
 var x=a[i]||{},rid=String(x.fileId||x.file_id||x.id||x.rid||""),name=String(x.fileName||x.file_name||x.name||"未命名"),size=Number(x.fileSize||x.file_size||x.size||0),parent=String(x.parentName||x.parent_name||"");
 var desc=fmtSize(size);if(parent)desc+=(desc?" · ":"")+"原位置："+parent;
 var item={title:"🗑 "+name,desc:desc,col_type:"text_1",url:$("还原「"+name+"」？").confirm(function(id){try{var api2=$.require("115Api"),c=api2.newClient(),fn=null,r;try{if(c&&typeof c.revertRecycleBin==="function")fn=c.revertRecycleBin;}catch(e0){}if(!fn)try{if(c&&typeof c.restoreRecycleBin==="function")fn=c.restoreRecycleBin;}catch(e1){}if(!fn)return "toast://当前115Api未提供回收站还原方法";r=fn.call(c,[String(id)]);if(r&&r.state===false)throw new Error(r.error||r.msg||"115返回失败");refreshPage(false);return "toast://已还原";}catch(ex){return "toast://还原失败："+String(ex.message||ex);}},rid),extra:{longClick:[]}};
 item.extra.longClick.push({title:"永久删除",js:$.toString(function(id,nm){return $("永久删除「"+nm+"」？\n此操作不可恢复").confirm(function(rid){try{var api2=$.require("115Api"),c=api2.newClient(),sid=String(rid),last="",done=false;function ck(v){if(v&&v.state===false)throw new Error(v.error||v.msg||"115返回失败");if(v&&v.code!==undefined&&Number(v.code)!==0&&Number(v.code)!==200)throw new Error(v.message||v.msg||("115返回code="+v.code));return v;}try{if(c&&typeof c.cleanRecycleBin==="function"){ck(c.cleanRecycleBin("",[sid]));done=true;}}catch(e0){last="cleanRecycleBin："+String(e0.message||e0);}if(!done)try{if(c&&typeof c.deleteRecycleBin==="function"){ck(c.deleteRecycleBin([sid]));done=true;}}catch(e1){last="deleteRecycleBin："+String(e1.message||e1);}if(!done)try{if(c&&typeof c.removeRecycleBin==="function"){ck(c.removeRecycleBin([sid]));done=true;}}catch(e2){last="removeRecycleBin："+String(e2.message||e2);}if(!done)try{if(c&&typeof c.recyclebinClean==="function"){ck(c.recyclebinClean({recycle_item_ids:sid}));done=true;}}catch(e3){last="recyclebinClean："+String(e3.message||e3);}if(!done)try{if(c&&typeof c.request==="function"){ck(c.request({path:"/open/rb/del",method:"POST",form:{tid:sid}}));done=true;}}catch(e4){last="request/open/rb/del："+String(e4.message||e4);}if(!done){var out=[],hit={},cur=c,dep=0;while(cur&&dep<4){try{var ns=Object.getOwnPropertyNames(cur);for(var z=0;z<ns.length;z++){var n=String(ns[z]||"");if(!n||hit[n])continue;hit[n]=1;if(/delete|remove|recycle|trash|clean|request/i.test(n))out.push(n);}}catch(ex0){}try{cur=Object.getPrototypeOf(cur);}catch(ex1){break;}dep++;}out.sort();return "toast://永久删除失败："+(last?last+"；":"")+"无可用入口"+(out.length?"；相关方法："+out.slice(0,18).join(", "):"");}refreshPage(false);return "toast://已永久删除";}catch(ex){return "toast://永久删除失败："+String(ex.message||ex);}},id);},rid,name)});
 d.push(item);
}
if(!a.length&&p===1)d.push({title:"回收站为空",col_type:"text_center_1"});
setResult(d);
})();