/* 911爆料 0.1.0-test.5 - native playback handoff + strict cards */
(function(C,R){
  R.version='0.1.0-test.5';R.build=10105;
  var AS='https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/apps/video/911baoliao/assets/';
  function add(d,x){d.push(x);}function title(t){try{setPageTitle(t);}catch(e){}}function heading(d,t,desc){add(d,{title:'‘‘’’<b>'+t+'</b>',desc:desc||'',col_type:'rich_text',url:'hiker://empty',extra:{lineVisible:false}});}function line(d){add(d,{col_type:'line'});}function empty(d,t,desc){add(d,{title:t,desc:desc||'',col_type:'text_1',url:'hiker://empty',extra:{lineVisible:false}});}
  function postCard(p){var has=!!p.img;return{title:p.title||'911爆料',desc:p.desc||'热点事件',pic_url:p.img||'',url:C.page('bl911Detail',{post_url:p.url}),col_type:has?'movie_2':'text_2',extra:{id:'bl911_post_'+C.hash(p.url),lineVisible:false}};}
  function renderPosts(d,a,limit){var i,n=limit||a.length;for(i=0;i<a.length&&i<n;i++)add(d,postCard(a[i]));}
  R.home=function(){var p=C.pageNo(),d=[],r,cats=[],i;if(p===1){title('911爆料');add(d,{title:'911爆料',desc:'热点资讯 · 图文视频 · 本地收藏',pic_url:AS+'icon.svg?v=10105',url:C.page('bl911Settings'),col_type:'movie_1_left_pic',extra:{lineVisible:false}});add(d,{title:'🔎\n搜索',col_type:'text_4',url:C.page('bl911Search')});add(d,{title:'🧭\n分类',col_type:'text_4',url:C.page('bl911Hub')});add(d,{title:'⭐\n收藏',col_type:'text_4',url:C.page('bl911Favorites')});add(d,{title:'🕘\n历史',col_type:'text_4',url:C.page('bl911History')});}r=C.home(p);if(p===1){cats=r.ok?C.extractNavLinks(r.html,r.url):[];if(cats.length){heading(d,'快速分类','官网内容栏目');for(i=0;i<cats.length&&i<8;i++)add(d,{title:cats[i].name,col_type:'scroll_button',url:C.page('bl911Feed',{cat_url:cats[i].url,cat_name:cats[i].name})});}heading(d,'最新爆料',r.posts.length?('真实文章 '+r.posts.length+' 条'):'暂无可识别文章');}renderPosts(d,r.posts);if(!r.posts.length&&p===1)empty(d,'暂未识别到真实文章','Test5 只接受 /archives/<数字>/ 正文页，不再把帮助、投稿、活动和广告页面当内容。');setResult(d);};
  R.categoryFeed=function(){var u=C.param('cat_url',C.base()+'/'),n=C.param('cat_name','分类'),p=C.pageNo(),d=[],r;title(n);if(C.restrictedText(n)){empty(d,'该分类未开放','请选择其它栏目。');setResult(d);return;}if(p===1){add(d,{title:'‹ 分类中心',col_type:'scroll_button',url:C.page('bl911Hub')});heading(d,n,'仅展示真实 /archives/ 文章');}r=C.category(u,p);renderPosts(d,r.posts);if(!r.posts.length&&p===1)empty(d,'该分类暂无可识别文章','已自动排除站点功能页、广告页和受限条目。');setResult(d);};
  R.searchPage=function(){var q=C.param('q',''),p=C.pageNo(),d=[],r,inputRule=String(C.ruleTitle()).replace(/[?&#]/g,'');title(q?'搜索 · '+q:'搜索');if(p===1){add(d,{title:'搜索爆料',desc:q||'输入事件关键词',col_type:'input',url:"(function(){var q=String(input||'').trim();return 'hiker://page/bl911Search?rule="+inputRule+"&simple=true&q='+encodeURIComponent(q);})()",extra:{defaultValue:q}});if(!q){heading(d,'站内搜索','仅展示真实文章页');setResult(d);return;}}if(!q||C.restrictedText(q)){empty(d,'该关键词未开放搜索','请换一个普通事件关键词。');setResult(d);return;}r=C.search(q,p);renderPosts(d,r.posts);if(!r.posts.length&&p===1)empty(d,'没有匹配结果','');setResult(d);};
  R.search=function(){var q='';try{q=String(MY_KEYWORD||'');}catch(e){q=C.param('q','');}var d=[];if(!q||C.restrictedText(q)){empty(d,'该关键词未开放搜索','');setResult(d);return;}var r=C.search(q,C.pageNo());renderPosts(d,r.posts);if(!r.posts.length&&C.pageNo()===1)empty(d,'没有匹配结果','');setResult(d);};
  R.detail=function(){var u=C.param('post_url',''),d=[],x,i,ds,playUrl,handoff;if(!u||!C.isArticleUrl(u)){empty(d,'文章地址无效','请从最新爆料或分类重新进入。');setResult(d);return;}x=C.detail(u);title(x.title||'911爆料');if(x.blocked){empty(d,'该条目未在本程序开放','返回列表继续浏览其它内容。');setResult(d);return;}if(!x.ok){empty(d,'详情读取失败','当前域名或详情结构暂未通过。');setResult(d);return;}ds=[x.categories.length?x.categories[0].name:'',x.date].filter(function(v){return!!v;}).join(' · ');C.addHistory({url:x.url,title:x.title,img:C.image(x.cover,x.url),rawImg:x.cover,desc:ds,category:x.categories.length?x.categories[0].name:''});add(d,{title:x.title,desc:ds||'911爆料',pic_url:C.image(x.cover,x.url)||'',url:'hiker://empty',col_type:x.cover?'movie_1_left_pic':'text_1',extra:{lineVisible:false}});playUrl=C.playMedia(x.media||[],x.url);if(playUrl){handoff=/^\s*\{/.test(playUrl)?$(x.url).lazyRule(function(play){return play;},playUrl):playUrl;add(d,{title:'▶ 立即播放',desc:x.media.length>1?('已提取 '+x.media.length+' 条媒体线路'):'已提取直连媒体',col_type:'text_center_1',url:handoff,extra:{id:'bl911_play_'+C.hash(x.url),lineVisible:false}});}else if(x.iframes&&x.iframes.length){add(d,{title:'▶ 尝试播放',desc:'未取得可验证直链 · 使用网页媒体嗅探',col_type:'text_center_1',url:'video://'+x.url,extra:{id:'bl911_play_'+C.hash(x.url),lineVisible:false}});}line(d);add(d,{title:C.isFavorite(x.url)?'★ 已收藏':'☆ 收藏',col_type:'text_3',url:$(x.url).lazyRule(function(boot,target,tt,cv,desc,cat){require(boot,{headers:{'Cache-Control':'no-cache'}},10105);Bl911Boot.loadOnly();var on=Bl911Core.toggleFavorite({url:target,title:tt,rawImg:cv,img:Bl911Core.image(cv,target),desc:desc,category:cat});refreshPage(false);return'toast://'+(on?'已加入收藏':'已取消收藏');},C.bootstrap,x.url,x.title,x.cover,ds,x.categories.length?x.categories[0].name:''),extra:{lineVisible:false}});add(d,{title:'🌐 原文',col_type:'text_3',url:x.url,extra:{lineVisible:false}});add(d,{title:'⚙ 设置',col_type:'text_3',url:C.page('bl911Settings'),extra:{lineVisible:false}});if(x.paragraphs.length){heading(d,'事件正文','');for(i=0;i<x.paragraphs.length&&i<50;i++)add(d,{title:x.paragraphs[i],col_type:'rich_text',url:'hiker://empty',extra:{lineVisible:false}});}if(x.images.length){heading(d,'现场图片','共 '+x.images.length+' 张');for(i=0;i<x.images.length&&i<60;i++)add(d,{title:'',pic_url:C.image(x.images[i],x.url),col_type:'pic_1_full',url:x.images[i],extra:{lineVisible:false}});}if(x.categories.length){heading(d,'相关分类','');for(i=0;i<x.categories.length&&i<12;i++)if(!C.restrictedText(x.categories[i].name))add(d,{title:x.categories[i].name,col_type:'scroll_button',url:C.page('bl911Feed',{cat_url:x.categories[i].url,cat_name:x.categories[i].name})});}if(x.related.length){heading(d,'继续浏览','');renderPosts(d,x.related,12);}setResult(d);};
  R.favorites=function(){title('本地收藏');var d=[],a=C.safeList(C.readList(C.favoriteKey));heading(d,'我的收藏',a.length+' 项 · 仅保存在本机');renderPosts(d,a);if(!a.length)empty(d,'还没有收藏','从详情页点击“收藏”。');setResult(d);};
  R.history=function(){title('浏览历史');var d=[],a=C.safeList(C.readList(C.historyKey));heading(d,'最近浏览',a.length+' 项');renderPosts(d,a);if(!a.length)empty(d,'暂无历史','进入详情页后会自动记录。');setResult(d);};
  R.settings=function(){title('设置与诊断');var d=[],b=C.base(),probe=C.request('/',{route:'settings-probe',noRetry:true}),posts=probe.ok?C.parsePosts(probe.html,probe.url):[],cats=probe.ok?C.extractNavLinks(probe.html,probe.url):[],diag=C.lastDiag();add(d,{title:'911爆料 · Test5',desc:R.version+' · Build '+R.build,pic_url:AS+'icon.svg?v=10105',col_type:'movie_1_left_pic',url:'hiker://empty',extra:{lineVisible:false}});heading(d,'站点状态','');add(d,{title:'当前域名',desc:b,col_type:'text_1',url:'hiker://empty'});add(d,{title:'首页探测',desc:(probe.ok?'可访问':'不可访问')+' · HTML '+(probe.html?probe.html.length:0)+' · 真实文章 '+posts.length+' · 分类 '+cats.length,col_type:'text_1',url:'hiker://empty'});heading(d,'Parser 合同','');add(d,{title:'文章路由',desc:'只接受 /archives/<数字>/',col_type:'text_1',url:'hiker://empty'});add(d,{title:'播放交付',desc:'详情已有媒体直接交付；多线路只在合法 article URL 上执行 lazyRule',col_type:'text_1',url:'hiker://empty'});heading(d,'最近诊断','');add(d,{title:diag.stage||'暂无诊断',desc:[diag.route||'',diag.error||'',diag.extra?JSON.stringify(diag.extra):''].filter(function(v){return!!v;}).join(' · '),col_type:'long_text',url:'hiker://empty'});setResult(d);};
  R.module=function(){return R;};
})(Bl911Core,Bl911RemoteRuntime.module());
