/* 911爆料 0.1.0-test.5 - strict archive/article adapter */
(function(C,R){
  C.version='0.1.0-test.5';C.build=10105;R.version='0.1.0-test.5';R.build=10105;R.siteAdapterContract='911-archives-strict-v1';
  var _restricted=C.restrictedText;
  C.restrictedText=function(v){var s=C.strip(v).replace(/\s+/g,' ');if(_restricted.call(C,s))return true;if(/(?:不雅|私密|裸照|裸聊|性爱|性交|约炮|开房|酒店).{0,28}(?:泄漏|泄露|流出|外流|曝光|偷拍视频|偷拍)/i.test(s))return true;if(/(?:泄漏|泄露|流出|外流|偷拍视频|偷拍).{0,28}(?:不雅|私密|裸照|性爱|性交|酒店)/i.test(s))return true;return false;};
  C.isArticleUrl=function(u){var p=C.pathOf(u).replace(/[?#].*$/,'');return /^\/archives\/\d+\/?$/i.test(p);};
  C.urlLooksContent=function(u){return C.isArticleUrl(u);};
  C.promoText=function(v){var s=C.strip(v).replace(/\s+/g,' ').toLowerCase();if(!s)return false;if(/^(?:回家的路|投稿方式|常见问题|所有标签|关于我们|加入911|加入我们|官方tg群|官方推特|广告商务|商务合作|官方推荐|往期吃瓜|往期内容|qq|fa-solid.*|911暑期活动|911爆料网|911爆料app|章鱼导航|看图找番|ai换脸脱衣|app|telegram|twitter)$/i.test(s))return true;return s.length<80&&/(?:回家的路|投稿方式|常见问题|所有标签|关于我们|加入911|官方tg群|官方推特|广告商务|商务合作|官方推荐|备用网址|永久地址|回家地址|app下载|广告投放)/i.test(s);};
  C.badImage=function(u){var s=C.clean(u).toLowerCase();if(!s||/^data:|^blob:|^javascript:/i.test(s))return true;if(/(?:^|\/)(?:logo|brand|favicon|icon|loading|loader|placeholder|default|error|404|qrcode|qr-code)(?:[._\/-]|$)/i.test(s))return true;return /(?:telegram|twitter|app[-_]?download|download[-_]?app|navigation|nav[-_]?banner|911[-_]?logo)/i.test(s);};
  C.imageCandidate=function(u,base){u=C.decode(C.clean(u)).replace(/\\\//g,'/').replace(/&amp;/ig,'&');if(!u)return'';if(/^\/\//.test(u))u='https:'+u;u=C.abs(u,base);if(!u||C.badImage(u))return'';if(!/\.(?:jpe?g|png|webp|gif|avif)(?:[?#]|$)/i.test(u)&&!/\/(?:image|images|img|upload|uploads|media)\//i.test(u))return'';return u;};
  C.imageFromAnyAttrs=function(attrs,base){var keys=['data-original','data-original-src','data-src','data-lazy-src','data-lazy','data-lazyload','data-url','data-image','data-img','data-echo','data-bg','data-background','data-background-image','data-thumb','poster','src'],i,u='';for(i=0;i<keys.length;i++){u=C.imageCandidate(C.attr(attrs,keys[i]),base);if(u)return u;}var ss=C.attr(attrs,'data-srcset')||C.attr(attrs,'data-lazy-srcset')||C.attr(attrs,'srcset');if(ss){var parts=ss.split(','),j,cand;for(j=parts.length-1;j>=0;j--){cand=C.imageCandidate(C.trim(parts[j]).split(/\s+/)[0],base);if(cand)return cand;}}var style=C.attr(attrs,'style'),m=style.match(/(?:background(?:-image)?|content)\s*:\s*url\((?:["']?)([^)"']+)(?:["']?)\)/i);return m?C.imageCandidate(m[1],base):'';};
  C.cardImage=function(raw,base){var s=C.s(raw),re=/<(?:img|source|video|div|a|figure|span)\b([^>]*)>/ig,m,u='';while((m=re.exec(s))){u=C.imageFromAnyAttrs(m[1],base);if(u)return u;}re=/(?:background(?:-image)?\s*:\s*url\(|["'])([^"'()\s<>]+\.(?:jpe?g|png|webp|gif|avif)(?:\?[^"'()\s<>]*)?)/ig;while((m=re.exec(s))){u=C.imageCandidate(m[1],base);if(u)return u;}re=/((?:https?:)?\\?\/\\?\/[^\s"'<>]+?\.(?:jpe?g|png|webp|gif|avif)(?:\?[^\s"'<>]*)?)/ig;while((m=re.exec(s))){u=C.imageCandidate(m[1],base);if(u)return u;}return'';};
  C.firstImage=function(raw,base){return C.cardImage(raw,base);};
  C.archiveCardBlock=function(html,index){var s=C.s(html),start=-1,end=-1,from=Math.max(0,index-7000),before=s.substring(from,index),tags=['article','li','div'],i,re,m,last=-1,tag='';for(i=0;i<tags.length;i++){re=new RegExp("<"+tags[i]+"\\b[^>]*class=[\"'][^\"']*(?:post|item|card|entry|archive|news|video|list|grid)[^\"']*[\"'][^>]*>","ig");last=-1;while((m=re.exec(before)))last=m.index;if(last>=0&&from+last>start){start=from+last;tag=tags[i];}}if(start<0)return C.context(s,index,900,2600);var tail=s.substring(start,Math.min(s.length,index+7000));re=new RegExp('<\\/'+tag+'>','i');m=re.exec(tail);end=m?m.index+m[0].length:Math.min(tail.length,5200);return tail.substring(0,end);};
  C.parsePosts=function(html,base){var s=C.s(html),re=/<a\b([^>]*)href\s*=\s*["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/ig,m,out=[],seen={},u,inner,block,title,img,date,cat,tm,key,x;while((m=re.exec(s))&&out.length<60){u=C.abs(m[2],base);if(!u||!C.isArticleUrl(u))continue;key=C.pathOf(u).replace(/[?#].*$/,'');if(seen[key])continue;inner=m[4];block=C.archiveCardBlock(s,m.index);title=C.clean(C.attr(m[1]+' '+m[3],'title')||C.attr(m[1]+' '+m[3],'aria-label')||C.strip(inner));if(!title||title.length<4||title.length>260){tm=block.match(/<(?:h1|h2|h3|h4)[^>]*>[\s\S]{0,700}?<a\b[^>]*href=["'][^"']*\/archives\/\d+\/?["'][^>]*>([\s\S]*?)<\/a>/i);if(tm)title=C.strip(tm[1]);}if(!title||title.length<4){tm=block.match(/(?:title|alt)\s*=\s*["']([^"']{4,260})["']/i);if(tm)title=C.clean(tm[1]);}if(!title||C.promoText(title)||C.restrictedText(title))continue;img=C.cardImage(inner,u)||C.cardImage(block,u);date=C.dateFrom(block);cat=C.categoryFrom(block);x={url:u,title:title,img:img?C.image(img,u):'',rawImg:img,date:date,category:cat,desc:[cat,date].filter(function(v){return!!v;}).join(' · ')};if(!C.safeItem(x))continue;seen[key]=1;out.push(x);}return out;};
  var _extractNav=C.extractNavLinks;
  C.extractNavLinks=function(html,base){var a=_extractNav.call(C,html,base),out=[],seen={},i,n,p;for(i=0;i<a.length;i++){n=C.strip(a[i].name);p=C.pathOf(a[i].url);if(!n||C.promoText(n)||C.restrictedText(n)||seen[p])continue;if(/\/(?:about|faq|contact|submit|contribute|join|tag|tags)(?:\/|$)/i.test(p))continue;seen[p]=1;out.push(a[i]);}return out;};
  C.extractParagraphs=function(raw){var s=C.s(raw),re=/<(?:p|h2|h3|h4|blockquote|figcaption)\b[^>]*>([\s\S]*?)<\/(?:p|h2|h3|h4|blockquote|figcaption)>/ig,m,out=[],seen={},t;while((m=re.exec(s))&&out.length<80){t=C.strip(m[1]);if(!t||t.length<2||t.length>1800||/^https?:\/\//i.test(t))continue;if(/911(?:bg|bla|bl)[a-z0-9.-]*\.com|回家邮箱|永久.*地址|最新.*地址|官方\s*app|app\s*点击下载|谷歌\/edge\/safari|广告合作|商务合作|投稿|上传|官方tg|官方推特/i.test(t))continue;if(C.restrictedText(t)||seen[t])continue;seen[t]=1;out.push(t);}return out;};
  C.seedBases=function(){return C.unique([C.base(),'https://911bl.com','https://911bla.com','https://911bg7.com','https://d10cq29fdobmmg.cloudfront.net',C.defaultBase]);};
  C.bootstrap='https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/apps/video/911baoliao/bootstrap_test_v5_b10105.js?v=10105';
})(Bl911Core,Bl911RemoteRuntime.module());
