/* 汤头条 0.1.0-test.15 ImageLoader / PWA thumb_cover_str priority + self-fetch headers */
var TangTouTiaoImageV023=(function(){
  var V='0.1.0-test.15';
  function newBytes(n){return java.lang.reflect.Array.newInstance(java.lang.Byte.TYPE,n);}function copy(a,ap,b,bp,n){java.lang.System.arraycopy(a,ap,b,bp,n);}function u8(v){return v<0?v+256:v;}
  function starts(a,b){if(!a||a.length<b.length)return false;for(var i=0;i<b.length;i++)if(u8(a[i])!==b[i])return false;return true;}
  function isImage(a){return !!(a&&a.length>=4&&(starts(a,[255,216,255])||starts(a,[137,80,78,71])||starts(a,[71,73,70,56])||starts(a,[66,77])||(a.length>=12&&starts(a,[82,73,70,70])&&u8(a[8])===87&&u8(a[9])===69&&u8(a[10])===66&&u8(a[11])===80)));}
  function type(a){if(starts(a,[255,216,255]))return'jpeg';if(starts(a,[137,80,78,71]))return'png';if(starts(a,[71,73,70,56]))return'gif';if(starts(a,[66,77]))return'bmp';if(a&&a.length>=12&&starts(a,[82,73,70,70]))return'webp';return'unknown';}
  function hexBytes(s){s=String(s||'').trim();if(!s||s.length%2||!/^[0-9a-f]+$/i.test(s))return null;var a=newBytes(s.length/2);for(var i=0;i<a.length;i++){var v=parseInt(s.substr(i*2,2),16);a[i]=v>127?v-256:v;}return a;}
  function evp(secret,keyLen,ivLen){var pass=new java.lang.String(secret).getBytes('UTF-8'),md=java.security.MessageDigest.getInstance('MD5'),need=keyLen+ivLen,all=newBytes(need),pos=0,prev=null;while(pos<need){md.reset();if(prev)md.update(prev);md.update(pass);prev=md.digest();var n=Math.min(prev.length,need-pos);copy(prev,0,all,pos,n);pos+=n;}var key=newBytes(keyLen),iv=newBytes(ivLen);copy(all,0,key,0,keyLen);copy(all,keyLen,iv,0,ivLen);return{key:key,iv:iv};}
  function legacy(raw){var text=String(new java.lang.String(raw,'UTF-8')).trim(),enc=hexBytes(text);if(!enc||enc.length<17)return null;var iv=newBytes(16),body=newBytes(enc.length-16);copy(enc,0,iv,0,16);copy(enc,16,body,0,body.length);var p=evp('e79465cfbbimgkcusimcuekd3b066a6e',32,16),c=javax.crypto.Cipher.getInstance('AES/CFB/NoPadding');c.init(2,new javax.crypto.spec.SecretKeySpec(p.key,'AES'),new javax.crypto.spec.IvParameterSpec(iv));return c.doFinal(body);}
  function cbc(raw){var c=javax.crypto.Cipher.getInstance('AES/CBC/PKCS5Padding');c.init(2,new javax.crypto.spec.SecretKeySpec(new java.lang.String('f5d965df75336270').getBytes('UTF-8'),'AES'),new javax.crypto.spec.IvParameterSpec(new java.lang.String('97b60394abc2fbe1').getBytes('UTF-8')));return c.doFinal(raw);}
  function inspect(raw){if(!raw||!raw.length)return null;if(isImage(raw))return{bytes:raw,mode:'plain'};try{var a=cbc(raw);if(a&&isImage(a))return{bytes:a,mode:'aes-cbc-pwa'};}catch(e1){}try{var b=legacy(raw);if(b&&isImage(b))return{bytes:b,mode:'legacy-cfb-app'};}catch(e2){}return null;}
  function modes(){var r=String(getItem('ttt_player_refer','')||''),a=[
    {name:'okhttp',h:{'User-Agent':'okhttp/4.9.3','Accept':'image/avif,image/webp,image/apng,image/*,*/*;q=0.8','Cache-Control':'no-cache'}},
    {name:'browser',h:{'User-Agent':'Mozilla/5.0 (Linux; Android 13; HikerView) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Mobile Safari/537.36','Accept':'image/avif,image/webp,image/apng,image/*,*/*;q=0.8','Cache-Control':'no-cache'}},
    {name:'pwa-ref',h:{'User-Agent':'Mozilla/5.0','Referer':'https://dpi4.tbrapi.org/','Origin':'https://dpi4.tbrapi.org','Accept':'image/*,*/*;q=0.8','Cache-Control':'no-cache'}},
    {name:'site-ref',h:{'User-Agent':'Mozilla/5.0','Referer':'https://ttt.tips/','Origin':'https://ttt.tips','Accept':'image/*,*/*;q=0.8','Cache-Control':'no-cache'}}
  ];if(r)a.push({name:'player-ref',h:{'User-Agent':'Mozilla/5.0','Referer':r,'Accept':'image/*,*/*;q=0.8','Cache-Control':'no-cache'}});return a;}
  function fetchBytes(u,h){var x=fetch(u,{timeout:12000,headers:h,toHex:true});return x==null?null:hexBytes(String(x));}
  function fetchDecrypt(cands){try{if(typeof cands==='string')cands=JSON.parse(cands);}catch(e){}if(!Array.isArray(cands))cands=[];var ms=modes(),errs=[];for(var i=0;i<cands.length;i++){var u=String(cands[i]||'');if(!/^https?:\/\//i.test(u))continue;for(var j=0;j<ms.length;j++){try{var raw=fetchBytes(u,ms[j].h),out=inspect(raw);if(out){setItem('ttt_last_image_diag',JSON.stringify({time:Date.now(),ok:true,candidate:i,headerMode:ms[j].name,input:raw.length,output:out.bytes.length,mode:out.mode,type:type(out.bytes),url:u.substring(0,180)}));return new java.io.ByteArrayInputStream(out.bytes);}errs.push(ms[j].name+':len='+(raw?raw.length:0));}catch(e1){errs.push(ms[j].name+':'+String(e1.message||e1).slice(0,90));}}}setItem('ttt_last_image_diag',JSON.stringify({time:Date.now(),ok:false,candidates:cands.length,errors:errs.slice(-10)}));return null;}
  return{version:V,fetchDecrypt:fetchDecrypt};
})();
try{$.exports=TangTouTiaoImageV023;}catch(e){}
