/* ACFAN 0.2.0-test.6 playback + H5 terminal */
var ACFAN6Playback=(function(){
  var C=ACFAN6Core,P=ACFAN6Protocol,V=ACFAN6Provider;
  function host(){return C.s(getItem(C.K.apiHost,'')||C.staticApiHosts[0]).replace(/\/+$/,'');}
  function playerHeaders(){var h=host();return{'User-Agent':'Mozilla/5.0 (Linux; Android 12; SM-G9750 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0 Mobile Safari/537.36','Referer':h+'/', 'Origin':h};}
  function collect(root){var out=[],seen={},count=0;function add(u,name){u=C.s(u).trim();if(!u||seen[u])return;if(!/^https?:\/\//i.test(u)&&!/^(?:jpc|jpd|hls|video|media)\//i.test(u)&&!/\.m3u8(?:[?#]|$)|\.mp4(?:[?#]|$)/i.test(u))return;seen[u]=1;out.push({url:u,name:C.clean(name)||''});}function walk(v,key,d){if(v===undefined||v===null||d>9||count++>6000)return;if(typeof v==='string'){if(/url|path|source|play|media|m3u8|preview/i.test(C.s(key)))add(v,key);return;}if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],key,d+1);return;}if(typeof v!=='object')return;var label=C.pick(v,['qualityName','clarityName','name','title','label','quality'],'');for(var k in v){if(typeof v[k]==='string'&&/url|path|source|play|media|m3u8|preview/i.test(k))add(v[k],label||k);else if(v[k]&&typeof v[k]==='object')walk(v[k],k,d+1);}}walk(root,'',0);return out;}
  function decodeUrl(path){path=C.s(path).trim();if(!path)return'';if(/^https?:\/\//i.test(path)&&(/\/api\/m3u8\//i.test(path)||/\.(?:m3u8|mp4)(?:[?#]|$)/i.test(path)))return path;return host()+'/api/m3u8/h5/decode?path='+encodeURIComponent(path);}
  function mark(u){if(/\.mp4(?:[?#]|$)/i.test(u))return u+'#isVideo=true#';return u+'#isM3u8#';}
  function nativePlay(id,seed,title){id=C.s(id);var root=seed||{},used='seed',lines=collect(root);if(!lines.length&&id){try{root=P.tryApi('video/can/watch',{videoId:C.n(id)},['GET'],{timeout:4800});used='can-watch-get';lines=collect(root);}catch(e){try{root=P.tryApi('video/can/watch',{videoId:C.n(id)},['POST'],{timeout:4200});used='can-watch-post';lines=collect(root);}catch(e2){C.diag('PLAY_WATCH_FAIL',C.s(e2.message||e2),{id:id});}}}if(!lines.length){C.diag('PLAY_NO_SOURCE','id='+id,{route:used});return'toast://未取得原生播放地址，请使用网页播放';}var urls=[],names=[],headers=[];for(var i=0;i<lines.length&&i<6;i++){var u=decodeUrl(lines[i].url);if(!u)continue;urls.push(mark(u));names.push(lines[i].name||('线路 '+(i+1)));headers.push(playerHeaders());}if(!urls.length)return'toast://播放地址转换失败，请使用网页播放';C.diag('PLAY_NATIVE',used,{id:id,count:urls.length});if(urls.length===1)return JSON.stringify({urls:urls,names:[title||'播放'],headers:headers});return JSON.stringify({urls:urls,names:names,headers:headers});}
  function bridgeUrl(kind,id,title,chapter){return C.page('acfanT6Bridge',{acf_kind:kind||'video',acf_id:id||'',acf_title:title||'',acf_chapter:chapter||''});}
  function bridgeScript(kind,id,title,chapter){var cfg={kind:C.s(kind),id:C.s(id),title:C.s(title),chapter:C.s(chapter)};return '('+function(c){function text(e){return String(e&&e.innerText||'').replace(/\s+/g,' ').trim();}function visible(e){if(!e)return false;var r=e.getBoundingClientRect();return r.width>0&&r.height>0;}function click(e){try{if(e&&visible(e)){e.click();return true;}}catch(x){}return false;}function setValue(e,v){try{var p=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value');if(p&&p.set)p.set.call(e,v);else e.value=v;}catch(x){e.value=v;}try{e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));}catch(x2){}}function searchInput(){return document.querySelector('input[type=search],input[placeholder*=搜索],input[placeholder*=搜],input[name*=search],input[name*=keyword],input[type=text]');}function target(){var q=String(c.title||'').trim(),keys=[q,q.slice(0,24),q.slice(0,16),q.slice(0,10)].filter(function(x){return x.length>=3;}),all=document.querySelectorAll('a,article,li,[role=button],[class*=card],[class*=item]');for(var k=0;k<keys.length;k++)for(var i=0;i<all.length;i++){var s=text(all[i]);if(s&&s.indexOf(keys[k])>=0&&visible(all[i]))return all[i].closest&&all[i].closest('a')||all[i];}return null;}function ready(){if(c.kind==='video'||c.kind==='short'||c.kind==='audio'){var v=document.querySelector('video,audio');if(v&&visible(v)){try{v.scrollIntoView({block:'start'});v.play();}catch(x){}return true;}}if(c.kind==='comic'){var z=document.querySelectorAll('main img,[class*=reader] img,[class*=comic] img');if(z.length>3)return true;}return false;}var loops=0,lastSubmit=0,timer=setInterval(function(){loops++;if(ready()){clearInterval(timer);return;}var hit=target();if(hit&&click(hit))return;var i=searchInput();if(i&&c.title){setValue(i,c.title);if(Date.now()-lastSubmit>2600){lastSubmit=Date.now();try{i.focus();i.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));}catch(x){}var f=i.closest&&i.closest('form');try{if(f&&f.requestSubmit)f.requestSubmit();else if(f)f.submit();}catch(x2){}}}if(loops>75)clearInterval(timer);},650);setTimeout(function(){try{document.documentElement.style.setProperty('--acfan-hiker','1');}catch(x){}},100);}+')('+JSON.stringify(cfg)+');';}
  function directAudio(url,title){url=C.s(url).trim();if(!url)return'toast://没有可用音频';return JSON.stringify({urls:[url+'#isMusic=true#'],names:[title||'播放'],headers:[{'User-Agent':C.ua}]});}
  return{nativePlay:nativePlay,bridgeUrl:bridgeUrl,bridgeScript:bridgeScript,directAudio:directAudio,collect:collect};
})();
