/* PikPak Test16 Build10118 - decoded folders, video-only Magnet list, recycle and folder picker */
(function(C,P,Play,UI,Pages){
    function page(){try{return Number(MY_PAGE||1)||1;}catch(e){return 1;}}
    function raw(k,d){try{return getParam(k,d==null?'':String(d));}catch(e){return d==null?'':String(d);}}
    function param(k,d){var v=String(raw(k,d)||'');try{return decodeURIComponent(v);}catch(e){return v;}}
    function title(v){try{setPageTitle(String(v||''));}catch(e){}}
    function pt(scope,n){return 'pikpak_v16_pt_'+md5(String(scope||'root'))+'_'+n;}
    function token(scope,n){if(n<=1)return '';try{return getMyVar(pt(scope,n),'');}catch(e){return '';}}
    function save(scope,n,v){try{putMyVar(pt(scope,n+1),String(v||''));}catch(e){}}
    function sorted(a,foldersFirst){a=(a instanceof Array?a:[]).slice(0);var mode=C.item('sort','name_asc');a.sort(function(x,y){var xf=P.isFolder(x),yf=P.isFolder(y);if(foldersFirst!==false&&xf!==yf)return xf?-1:1;if(mode==='time_desc')return String(y.modified_time||y.created_time||'').localeCompare(String(x.modified_time||x.created_time||''));if(mode==='size_desc')return Number(y.size||0)-Number(x.size||0);return String(x.name||'').toLowerCase().localeCompare(String(y.name||'').toLowerCase());});return a;}
    function fileUrl(f){if(P.isFolder(f))return UI.route('pikpakDrive',{parent_id:f.id||'',name:f.name||'文件夹'});return $("#noLoading#").lazyRule(function(x){return $.require('pikpak').playPersonal(x.id,x.mime,false);},{id:String(f.id||''),mime:String(f.mime_type||'')});}
    function listDrive(d,parentId,scope){var n=page(),tok=token(scope,n);if(n>1&&!tok)return;var r=P.listFiles(parentId||'',tok,200,'NAME_ASC');if(!r||r.error||r.error_code){if(n===1)d.push(UI.error(C.errorText(r)));return;}save(scope,n,r.next_page_token||'');var a=sorted(r.files||[],true);if(!a.length&&n===1)d.push(UI.empty('这个文件夹还是空的'));for(var i=0;i<a.length;i++)d.push(UI.fileCard(a[i],fileUrl(a[i])));}
    Pages.drive=function(){var parentId=param('parent_id',''),name=param('name','我的文件'),d=[],n=page();title(name);if(n===1){d.push({title:'＋ 新建文件夹',url:$("",'文件夹名称').input(function(pid){return $.require('pikpak').createFolderAction(pid,input);},parentId),col_type:'scroll_button'});d.push({title:'⇅ '+(C.item('sort','name_asc')==='time_desc'?'最近修改':C.item('sort','name_asc')==='size_desc'?'文件大小':'名称排序'),url:UI.route('pikpakSettings'),col_type:'scroll_button'});d.push({title:'♻ 回收站',url:UI.route('pikpakRecycle'),col_type:'scroll_button'});}listDrive(d,parentId,'drive-'+parentId);setResult(d);};
    Pages.magnet=function(opt){opt=opt||{};var magnet=String(opt.magnet||param('magnet','')),d=[];title('Magnet 视频');if(!magnet){setResult([UI.error('缺少 Magnet 链接')]);return;}d.push({title:'🧲 仅显示视频',desc:C.loggedIn()?'播放文件默认创建在 My Pack；退出跨小程序调用页后移入回收站':'可以预览视频列表；播放前需要登录 PikPak',url:'copy://'+magnet,col_type:'text_1',extra:{lineVisible:false}});if(!C.loggedIn())d.push({title:'👤 登录 PikPak',url:UI.route('pikpakAccount'),col_type:'scroll_button'});var r=P.resolveMagnet(magnet),all=r.files||[],videos=[];if(r.raw&&(r.raw.error||r.raw.error_code)){d.push(UI.error(C.errorText(r.raw)));setResult(d);return;}for(var i=0;i<all.length;i++)if(P.isVideo(all[i]))videos.push(all[i]);if(!videos.length){d.push(UI.empty(all.length?'该 Magnet 没有识别到视频文件':'PikPak 暂未解析出该 Magnet 的文件列表'));setResult(d);return;}d.push({title:'视频 '+videos.length+' 个',desc:all.length>videos.length?'已隐藏 '+(all.length-videos.length)+' 个文件夹或非视频文件':'播放列表只包含视频',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});for(i=0;i<videos.length;i++){(function(f){d.push(UI.magnetCard(f,$("#noLoading#").lazyRule(function(x){return $.require('pikpak').playMagnet(x.file,x.magnet);},{file:f,magnet:magnet})));})(videos[i]);}setResult(d);};
    Pages.recycle=function(){var d=[],n=page();title('PikPak 回收站');if(!C.loggedIn()){setResult([UI.error('请先登录 PikPak')]);return;}if(n===1){d.push({title:'♻ 回收站',desc:'点击文件可还原；长按可还原或永久删除',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清空回收站',url:'confirm://清空后无法恢复，确定继续？.js:'+$.toString(function(){return $.require('pikpak').emptyTrashAction();}),col_type:'scroll_button'});}var tok=token('recycle',n);if(n>1&&!tok){setResult(d);return;}var r=P.listTrash(tok,200,'MODIFY_TIME_DESC');if(!r||r.error||r.error_code){d.push(UI.error(C.errorText(r)));setResult(d);return;}save('recycle',n,r.next_page_token||'');var a=sorted(r.files||[],false);if(!a.length&&n===1)d.push(UI.empty('回收站是空的'));for(var i=0;i<a.length;i++)d.push(UI.recycleCard(a[i]));setResult(d);};
    Pages.folderPicker=function(){var mode=param('mode','move'),sourceId=param('source_id',''),sourceName=param('source_name',''),sourceKind=param('source_kind',''),parentId=param('parent_id',''),name=param('name','根目录'),d=[];title((mode==='copy'?'复制':'移动')+'到 · '+name);d.push({title:(mode==='copy'?'复制':'移动')+'到当前文件夹',desc:parentId?'当前：'+name:'当前：根目录',url:'confirm://确定'+(mode==='copy'?'复制':'移动')+'“'+sourceName+'”到这里？.js:'+$.toString(function(x){return x.mode==='copy'?$.require('pikpak').copyToAction(x.id,x.target):$.require('pikpak').moveToAction(x.id,x.target);},{mode:mode,id:sourceId,target:parentId}),col_type:'text_center_1',extra:{lineVisible:false}});var r=P.listFiles(parentId,'',500,'NAME_ASC');if(!r||r.error||r.error_code){d.push(UI.error(C.errorText(r)));setResult(d);return;}var a=sorted(r.files||[],true),count=0;for(var i=0;i<a.length;i++){var f=a[i];if(!P.isFolder(f)||String(f.id||'')===sourceId&&String(sourceKind).indexOf('folder')>=0)continue;count++;d.push({title:'📁 '+String(f.name||'未命名文件夹'),desc:'进入并选择目标位置',url:UI.route('pikpakFolderPicker',{mode:mode,source_id:sourceId,source_name:sourceName,source_kind:sourceKind,parent_id:f.id||'',name:f.name||'文件夹'}),col_type:'text_1',extra:{lineVisible:false}});}if(!count)d.push(UI.empty('当前目录没有子文件夹'));setResult(d);};
    Pages.settings=function(){var d=[];title('PikPak 设置');var sort=C.item('sort','name_asc');d.push({title:'API 会话',desc:C.isWebSession&&C.isWebSession()?'官方 Web Session · 已连接':'当前未接入 Web Session',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'文件排序',desc:sort==='time_desc'?'最近修改':sort==='size_desc'?'文件大小':'名称',url:$(['名称','最近修改','文件大小']).select(function(){return $.require('pikpak').setSortAction(input);}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'回收站',desc:'还原、永久删除或清空回收站',url:UI.route('pikpakRecycle'),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清理临时播放文件',desc:'仅把本程序登记的临时对象移入回收站',url:'confirm://确定清理临时播放文件？.js:'+$.toString(function(){return $.require('pikpak').cleanupTempAction();}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'清理最近输入',desc:'清除首页最近分享 / Magnet / 离线链接',url:'confirm://确定清理最近输入？.js:'+$.toString(function(){return $.require('pikpak').clearRecentAction();}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'收藏',url:'hiker://collection?rule=PikPak',col_type:'scroll_button'});d.push({title:'历史',url:'hiker://history?rule=PikPak',col_type:'scroll_button'});d.push({title:'下载',url:'hiker://download',col_type:'scroll_button'});d.push({title:'运行信息',desc:'Test16 · Build 10118\n登录：官方网页 Web Session\n播放队列：仅视频\nMagnet 目标：My Pack\n文件管理：移动 / 复制 / 回收站',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});setResult(d);};
})(PikPakCore,PikPakProvider,PikPakPlayback,PikPakUI,PikPakPages);

