/* Shise Test5 Pages */
(function(K){
if(!K)throw new Error('Shise Test5 Core missing');
var R={version:'0.1.0-test.5',build:10105},C=K.C,G=K.G;
function render(d,xs){for(var i=0;i<xs.length;i++)d.push(K.videoCard(xs[i]))}
R.home=function(){var d=[],p=K.pg(),r=K.fetchPage(K.listPath(p)),xs=K.cards(r.html,r.url),q=G['中文内容']||[],i;if(p===1){setPageTitle('视色');d.push({title:'视色',desc:'内容浏览 · 分类 · 搜索 · 人物',url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false}});d.push(K.btn('🔎 搜索',K.page('shiseSearch',{})));d.push(K.btn('🗂 分类',K.page('shiseCategories',{})));d.push(K.btn('👤 人物',K.pageP('shiseModels',{})));d.push(K.btn('⚙ 设置',K.page('shiseSettings',{})));d.push(K.section('快速分类','按站点阅读源分类契约'));d.push(K.small('全部内容',K.pageP('shiseCatalog',{ss_title:'全部内容',ss_path:'/videos/{page}.html'})));for(i=0;i<Math.min(q.length,7);i++)d.push(K.small(q[i][0],K.pageP('shiseCatalog',{ss_title:q[i][0],ss_path:q[i][1]})));d.push(K.section('最新内容',xs.length?'当前页 '+xs.length+' 条 · 向下继续加载':''))}if(xs.length)render(d,xs);else d.push(K.empty('没有解析到内容',r.url));setResult(d)};
R.catalog=function(){var d=[],p=K.pg(),name=K.param('ss_title','内容列表'),path=K.resolve(K.param('ss_path','/videos/{page}.html'),p),r=K.fetchPage(path),xs=K.cards(r.html,r.url);if(p===1){setPageTitle(name);d.push(K.section(name,'向下继续加载原站分页'))}if(xs.length)render(d,xs);else d.push(K.empty('当前分类没有更多内容',r.url));setResult(d)};
R.categories=function(){var d=[],g,a,i;setPageTitle('分类');d.push(K.section('全部内容',''));d.push({title:'全部内容',url:K.pageP('shiseCatalog',{ss_title:'全部内容',ss_path:'/videos/{page}.html'}),col_type:'flex_button',extra:{lineVisible:false}});for(g in G){if(!G.hasOwnProperty(g))continue;d.push(K.section(g,''));a=G[g];for(i=0;i<a.length;i++)d.push({title:a[i][0],url:K.pageP('shiseCatalog',{ss_title:a[i][0],ss_path:a[i][1]}),col_type:'flex_button',extra:{lineVisible:false}})}setResult(d)};
R.search=function(){var d=[],p=K.pg(),kw='';try{kw=K.s(MY_KEYWORD||'')}catch(e){}if(!kw)kw=K.param('kw','');kw=K.trim(kw);if(!kw){setResult([]);return}var r=K.fetchPage(K.searchPath(kw,p)),xs=K.cards(r.html,r.url);if(xs.length)render(d,xs);else d.push(K.empty('没有搜索到内容',r.url));setResult(d)};
R.searchPage=function(){setPageTitle('搜索');setResult([{title:'⌕ 打开搜索',desc:'片名 / 编号 / 关键词',url:'hiker://search?s=&rule='+encodeURIComponent(C.ruleTitle),col_type:'text_center_1',extra:{lineVisible:false}}])};
R.models=function(){var d=[],p=K.pg(),r=K.fetchPage(K.listPath(p)),xs=K.models(r.html,r.url),i,x;if(p===1){setPageTitle('人物');d.push(K.section('人物','从视频卡片 model-container 实时汇总 · 向下继续加载'))}if(!xs.length)d.push(K.empty('当前页没有解析到人物',r.url));else for(i=0;i<xs.length;i++){x=xs[i];d.push({title:'👤 '+x.title,desc:'查看相关作品',url:K.page('shiseModel',{ss_url:x.href,ss_title:x.title}),col_type:'text_2',extra:{lineVisible:false,pageTitle:x.title}})}setResult(d)};
R.model=function(){var d=[],u=K.norm(K.param('ss_url',''),C.primary+'/');if(!u){setResult([K.empty('人物地址无效','')]);return}var r=K.fetchPage(u),name=K.param('ss_title','')||K.detail(r.html,r.url).title,xs=K.cards(r.html,r.url);setPageTitle(name);d.push(K.section('👤 '+name,xs.length?'相关作品 '+xs.length+' 条':''));if(xs.length)render(d,xs);else d.push(K.empty('没有解析到关联内容',r.url));d.push(K.btn('原站','web://'+u));setResult(d)};
R.detail=function(){var d=[],u=K.norm(K.param('ss_url',''),C.primary+'/');if(!u){setResult([K.empty('详情地址无效','')]);return}var r=K.fetchPage(u),info=K.detail(r.html,r.url),ms=K.media(r.html,r.url),mods=K.modelsFromBlock(r.html,r.url),ts=K.tags(r.html,r.url),recs=K.cards(r.html,r.url),i,x,meta=[];setPageTitle(info.title);if(ms.length)meta.push(ms.length+' 条播放线路');if(ts.length)meta.push(ts.length+' 个标签');d.push({title:info.title,desc:meta.join(' · '),img:info.img,pic_url:info.img,url:'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});if(ms.length)d.push({title:'▶ 立即播放',desc:'main-container 原始 m3u8',url:K.direct(ms[0]),col_type:'text_center_1',extra:{lineVisible:false}});else d.push({title:'▶ 网页嗅探',desc:'未按阅读源契约解析到 m3u8',url:'video://'+u,col_type:'text_center_1',extra:{lineVisible:false}});if(ms.length)d.push(K.btn('播放线路与兼容模式',K.page('shiseMedia',{ss_url:u}),'原始直链 / Header 兼容 / 网页嗅探'));if(mods.length){d.push(K.section('相关人物',''));for(i=0;i<mods.length;i++)d.push(K.small(mods[i].title,K.page('shiseModel',{ss_url:mods[i].href,ss_title:mods[i].title})))}if(ts.length){d.push(K.section('标签',''));for(i=0;i<ts.length;i++){x=ts[i];d.push(K.small(x.title,x.href&&/\/videos\//.test(K.pathOnly(x.href))?K.pageP('shiseCatalog',{ss_title:x.title,ss_path:K.tpl(K.pathOnly(x.href))}):'hiker://empty'))}}if(info.intro){d.push(K.section('简介',''));d.push({title:info.intro,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}})}if(recs.length){d.push(K.section('相关推荐',recs.length+' 条'));render(d,recs)}d.push(K.btn('收藏','hiker://collection?rule='+encodeURIComponent(C.ruleTitle)));d.push(K.btn('原站','web://'+u));setResult(d)};
R.media=function(){var d=[],u=K.norm(K.param('ss_url',''),C.primary+'/');if(!u){setResult([K.empty('播放地址无效','')]);return}var r=K.fetchPage(u),xs=K.media(r.html,r.url),i;setPageTitle('播放线路');if(!xs.length){d.push(K.empty('未解析到 m3u8','阅读源对纯视频页只读取 main-container'));d.push({title:'网页嗅探',url:'video://'+u,col_type:'text_center_1',extra:{lineVisible:false}})}else{d.push(K.section('播放线路','优先原始直链；失败再试 Header 兼容'));for(i=0;i<xs.length;i++){d.push({title:'▶ 原始直链 '+(i+1),desc:'HLS · 不附加自定义 Header',url:K.direct(xs[i]),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'🧩 Header 兼容 '+(i+1),desc:'仅原始直链失败时测试',url:K.header(xs[i],u),col_type:'text_1',extra:{lineVisible:false}})}d.push({title:'🧪 网页嗅探兜底',url:'video://'+u,col_type:'text_1',extra:{lineVisible:false}})}setResult(d)};
R.settings=function(){var d=[],ck=K.cookie(C.primary);setPageTitle('视色设置');d.push(K.section('站点与验证',''));d.push({title:'打开当前线路完成 X5 验证',desc:'遇到 403 / Just a moment / 空列表时使用',url:'x5://'+C.primary+'/',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'Cookie 状态',desc:ck?'已读取浏览器会话 Cookie':'当前未读取到 Cookie',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push(K.section('版本状态','Test 0.1.0-test.5 · Build 10105'));d.push({title:'本版修复',desc:'纯视频只读取 main-container 原始 m3u8；分类启用 page=fypage 与明确 series 分页；人物从 model-container 汇总；详情读取 contentTag。',url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d)};
R.module=function(){return{home:R.home,catalog:R.catalog,categories:R.categories,search:R.search,searchPage:R.searchPage,models:R.models,model:R.model,detail:R.detail,media:R.media,settings:R.settings}};
ShiseRemoteRuntime=R;
})(ShiseTest5Core);
