/* PikPak 0.1.0-test.1 Core - compatibility-first protocol/auth layer */
var PikPakCore=(function(){
    var APP='pikpak';
    var PREFIX='pikpak_v2_';
    var CLIENT_ID='YNxT9w7GMdWvEOKa';
    var CLIENT_VERSION='1.23.0';
    var PACKAGE_NAME='com.pikcloud.pikpak';
    var USER_AGENT='ANDROID-com.pikcloud.pikpak/1.23.0';
    var CAPTCHA_ALGORITHMS=['x2RWyIBN4QB0+tbkp1XuZS8mnUKhtg/Fjq','ks1I9Ry1U2CyxXi85DCa5jPS','4Hkd','y/fL5IbophIsbW9QE9jBstB6oL6m6yK3rH','JSjHHuxT/uRU9DWWLa9FSVObIBNixk','wIwEm7WT3nmKEhG9IWygcjG/RYng0aWcVyd9t1JS','SXRYzSV3','ZS++tWVNw0+I+EoabY8Ijo4wrc','4H84+LMNuKmWjSQ68+n+J2pWrL4J9uD9','hmjPlHbqb9lzy6YOcI'];
    var DEFAULT_DOMAIN='mypikpak.com',ALT_DOMAIN='mypikpak.net';
    function item(k,d){return getItem(PREFIX+k,d==null?'':String(d));}
    function set(k,v){setItem(PREFIX+k,String(v==null?'':v));}
    function clear(k){try{clearItem(PREFIX+k);}catch(e){}}
    function readJsonItem(k,def){try{var x=JSON.parse(item(k,''));return x==null?def:x;}catch(e){return def;}}
    function writeJsonItem(k,v){set(k,JSON.stringify(v));}
    function migrateLegacySession(){var legacy={};try{legacy=storage0.getItem('signin')||{};}catch(e){}try{clearItem('password');clearItem('password_bak');}catch(e3){}if(legacy&&typeof legacy==='object'&&(legacy.access_token||legacy.refresh_token)){try{storage0.setItem(PREFIX+'session',legacy);}catch(e2){writeJsonItem('session',legacy);}var lu=getItem('username','');if(lu)set('username',lu);var lc=getItem('captcha_token','');if(lc)set('captcha_token',lc);return legacy;}return {};}
    function session(){var s={};try{s=storage0.getItem(PREFIX+'session')||{};}catch(e){s=readJsonItem('session',{});}if(s&&typeof s==='object'&&(s.access_token||s.refresh_token))return s;return migrateLegacySession();}
    function saveSession(s){s=s||{};try{storage0.setItem(PREFIX+'session',s);}catch(e){writeJsonItem('session',s);}if(s.sub)set('user_id',s.sub);if(s.refresh_token)set('refresh_token',s.refresh_token);return s;}
    function clearSession(){try{storage0.clearItem(PREFIX+'session');}catch(e){try{storage0.setItem(PREFIX+'session',{});}catch(e2){}}clear('session');clear('refresh_token');clear('user_id');clear('captcha_token');}
    function username(){var u=item('username','');if(!u){u=getItem('username','');if(u)set('username',u);}return u;}
    function setUsername(v){set('username',v||'');}
    function clientSecret(){return item('client_secret','');}
    function loggedIn(){var s=session();return !!(s&&((s.access_token&&s.access_token!=='undefined')||(s.refresh_token&&s.refresh_token!=='undefined')||item('refresh_token','')));}
    function getDeviceId(){var d=item('device_id','');if(!d){d=md5(String(new Date().getTime())+'|'+String(Math.random())+'|PikPak');set('device_id',d);}return d;}
    function domain(){return item('api_domain',DEFAULT_DOMAIN)||DEFAULT_DOMAIN;}
    function setDomain(v){set('api_domain',v||DEFAULT_DOMAIN);}
    function altDomain(){return domain()===DEFAULT_DOMAIN?ALT_DOMAIN:DEFAULT_DOMAIN;}
    function userBase(d){return 'https://user.'+(d||domain());}
    function driveBase(d){return 'https://api-drive.'+(d||domain());}
    function referralBase(d){return 'https://api-referral.'+(d||domain());}
    function normalizePhoneAccount(v){v=String(v||'').trim();if(!v)return v;if(v.indexOf('@')>=0||v.charAt(0)==='+')return v;if(/^1\d{10}$/.test(v))return '+86'+v;return v;}
    function safeJson(raw){if(raw==null)return {};if(typeof raw==='object')return raw;try{return JSON.parse(String(raw));}catch(e){return {_parse_error:String(e.message||e),_raw:String(raw).substring(0,300)};}}
    function errorText(o){if(!o)return '未知错误';if(typeof o==='string')return o;return String(o.error_description||o.errorDesc||o.error||o.message||o._network_error||o._parse_error||'请求失败');}
    function isAuthError(o){if(!o||typeof o!=='object')return false;var code=String(o.error_code==null?'':o.error_code),t=errorText(o);return o.error==='unauthenticated'||code==='16'||code==='4121'||code==='4122'||/unauthenticated|invalid.?token|token.*expired|认证失败|重新登录|未登录/i.test(t);}
    function isCaptchaError(o){if(!o||typeof o!=='object')return false;var code=String(o.error_code==null?'':o.error_code),t=errorText(o);return code==='9'||o.error==='captcha_invalid'||/captcha.*invalid|验证码无效/i.test(t);}
    function raw(url,method,body,headers,timeout){try{var opt={headers:headers||{},method:method||'GET',timeout:timeout||8000};if(body!=null)opt.body=typeof body==='string'?body:JSON.stringify(body);return safeJson(fetch(url,opt));}catch(e){return {_network_error:String(e.message||e)};}}
    function getCaptchaToken(){var c=item('captcha_token','');if(!c){c=getItem('captcha_token','');if(c)set('captcha_token',c);}return c;}
    function setCaptchaToken(v){if(v)set('captcha_token',v);else clear('captcha_token');}
    function captchaSign(ts){var str=CLIENT_ID+CLIENT_VERSION+PACKAGE_NAME+getDeviceId()+String(ts);for(var i=0;i<CAPTCHA_ALGORITHMS.length;i++)str=md5(str+CAPTCHA_ALGORITHMS[i]);return '1.'+str;}
    function actionOf(method,url){var m=String(url||'').match(/^[a-z]+:\/\/[^/]+([^?#]*)/i);return String(method||'GET').toUpperCase()+':'+(m&&m[1]?m[1]:'/');}
    function refreshCaptcha(action,identity){var ts=String(new Date().getTime());var meta={captcha_sign:captchaSign(ts),user_id:item('user_id',''),package_name:PACKAGE_NAME,client_version:CLIENT_VERSION,timestamp:ts};identity=String(identity||'');if(identity){if(identity.indexOf('@')>=0)meta.email=identity;else meta.phone_number=identity;}var body={action:action||'GET:/drive/v1/files',captcha_token:getCaptchaToken(),client_id:CLIENT_ID,device_id:getDeviceId(),meta:meta,redirect_uri:'xlaccsdk01://xunlei.com/callback?state=harbor'};var headers={'X-Device-Id':getDeviceId(),'User-Agent':USER_AGENT,'Content-Type':'application/json; charset=utf-8'};var res=raw(userBase()+'/v1/shield/captcha/init?client_id='+CLIENT_ID,'POST',body,headers,8000);if(res&&res.captcha_token){setCaptchaToken(res.captcha_token);return res.captcha_token;}return '';}
    function publicHeaders(){var h={'x-client-id':CLIENT_ID,'x-device-id':getDeviceId(),'User-Agent':'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/127.0 Mobile Safari/537.36'};var c=getCaptchaToken();if(c)h['x-captcha-token']=c;return h;}
    function authHeaders(){var s=session();var h={'X-Device-Id':getDeviceId(),'User-Agent':USER_AGENT,'Content-Type':'application/json; charset=utf-8'};if(getCaptchaToken())h['X-Captcha-Token']=getCaptchaToken();if(s&&s.access_token)h.Authorization='Bearer '+s.access_token;return h;}
    function refreshAccess(){var s=session(),rt=(s&&s.refresh_token)||item('refresh_token','');if(!rt)return {error:'NO_REFRESH_TOKEN',error_description:'登录已失效，请重新登录'};var body={client_id:CLIENT_ID,grant_type:'refresh_token',refresh_token:rt},cs=clientSecret();if(cs)body.client_secret=cs;var res=raw(userBase()+'/v1/auth/token?client_id='+CLIENT_ID,'POST',body,{'X-Device-Id':getDeviceId(),'User-Agent':USER_AGENT,'Content-Type':'application/json; charset=utf-8'},8000);if(res&&!res.error&&res.access_token){saveSession(res);return res;}return res;}
    function login(user,pass){user=normalizePhoneAccount(user);pass=String(pass||'');if(!user||!pass)return {error:'EMPTY_ACCOUNT',error_description:'请输入账号和密码'};var url=userBase()+'/v1/auth/signin?client_id='+CLIENT_ID,c=refreshCaptcha('POST:/v1/auth/signin',user),body={captcha_token:c,client_id:CLIENT_ID,password:pass,username:user},cs=clientSecret();if(cs)body.client_secret=cs;var res=raw(url,'POST',body,{'X-Device-Id':getDeviceId(),'User-Agent':USER_AGENT,'Content-Type':'application/json; charset=utf-8'},10000);if(isCaptchaError(res)){setCaptchaToken('');c=refreshCaptcha('POST:/v1/auth/signin',user);body.captcha_token=c;res=raw(url,'POST',body,{'X-Device-Id':getDeviceId(),'User-Agent':USER_AGENT,'Content-Type':'application/json; charset=utf-8'},10000);}if(res&&!res.error&&res.access_token){setUsername(user);saveSession(res);return res;}return res;}
    function logout(){clearSession();clear('quota_cache');clear('quota_ts');try{storage0.clearItem('signin');}catch(e){try{storage0.setItem('signin',{});}catch(e2){}}try{clearItem('captcha_token');clearItem('password');clearItem('password_bak');}catch(e3){}return true;}
    function request(method,url,body,opt){opt=opt||{};method=String(method||'GET').toUpperCase();var auth=opt.auth!==false;if(auth){var s=session();if(!s.access_token){var rr=refreshAccess();if(rr.error||!rr.access_token)return rr;}}var headers=auth?authHeaders():publicHeaders();if(opt.headers){for(var k in opt.headers)headers[k]=opt.headers[k];}var res=raw(url,method,body,headers,opt.timeout||8000);if(auth&&isAuthError(res)&&!opt._authRetried){var r=refreshAccess();if(r&&!r.error&&r.access_token){opt._authRetried=true;return request(method,url,body,opt);}return r;}if(isCaptchaError(res)&&!opt._captchaRetried){setCaptchaToken('');refreshCaptcha(actionOf(method,url),auth?item('user_id',''):'');opt._captchaRetried=true;return request(method,url,body,opt);}if(res&&res._network_error&&!opt._domainRetried&&/mypikpak\.(com|net)/i.test(url)){opt._domainRetried=true;var from='.'+domain(),to='.'+altDomain(),alt=String(url).replace(from,to);if(alt!==url)return request(method,alt,body,opt);}return res;}
    function requestDrive(method,path,body,opt){return request(method,driveBase()+path,body,opt||{});}
    function requestPublic(method,path,body,opt){opt=opt||{};opt.auth=false;return request(method,driveBase()+path,body,opt);}
    function requestUser(method,path,body,opt){opt=opt||{};opt.auth=false;return request(method,userBase()+path,body,opt);}
    function formatSize(size){size=Number(size||0);if(!isFinite(size)||size<=0)return '0 B';var units=['B','KB','MB','GB','TB','PB'],i=0;while(size>=1024&&i<units.length-1){size/=1024;i++;}return (i?Number(size.toFixed(size>=100?0:size>=10?1:2)):Math.round(size))+' '+units[i];}
    function formatDate(s){if(!s)return '';try{var d=new Date(s);if(isNaN(d.getTime()))return String(s);var p=function(n){return n<10?'0'+n:n;};return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())+' '+p(d.getHours())+':'+p(d.getMinutes());}catch(e){return String(s);}}
    function mimeKind(m){m=String(m||'').toLowerCase();if(m.indexOf('video')>=0)return '视频';if(m.indexOf('image')>=0)return '图片';if(m.indexOf('audio')>=0)return '音频';if(m.indexOf('pdf')>=0)return 'PDF';if(m.indexOf('text')>=0)return '文本';return m?'文件':'文件夹';}
    function encode(v){return encodeURIComponent(String(v==null?'':v));}
    function decode(v){try{return decodeURIComponent(String(v==null?'':v));}catch(e){return String(v==null?'':v);}}
    function cacheQuota(q){writeJsonItem('quota_cache',q||{});set('quota_ts',new Date().getTime());}
    function getQuotaCache(){return readJsonItem('quota_cache',{});}
    function quotaFresh(ms){var t=Number(item('quota_ts','0')||0);return t>0&&new Date().getTime()-t<(ms||600000);}
    function pushRecent(v){v=String(v||'').trim();if(!v)return;var a=readJsonItem('recent_inputs',[]);if(!(a instanceof Array))a=[];for(var i=a.length-1;i>=0;i--)if(a[i]===v)a.splice(i,1);a.unshift(v);if(a.length>6)a=a.slice(0,6);writeJsonItem('recent_inputs',a);}
    function recent(){var a=readJsonItem('recent_inputs',[]);return a instanceof Array?a:[];}
    return {app:APP,prefix:PREFIX,clientId:CLIENT_ID,clientSecret:clientSecret,clientVersion:CLIENT_VERSION,packageName:PACKAGE_NAME,userAgent:USER_AGENT,item:item,set:set,clear:clear,readJsonItem:readJsonItem,writeJsonItem:writeJsonItem,session:session,saveSession:saveSession,clearSession:clearSession,username:username,setUsername:setUsername,loggedIn:loggedIn,getDeviceId:getDeviceId,domain:domain,setDomain:setDomain,userBase:userBase,driveBase:driveBase,referralBase:referralBase,normalizePhoneAccount:normalizePhoneAccount,errorText:errorText,isAuthError:isAuthError,isCaptchaError:isCaptchaError,raw:raw,refreshCaptcha:refreshCaptcha,publicHeaders:publicHeaders,authHeaders:authHeaders,refreshAccess:refreshAccess,login:login,logout:logout,request:request,requestDrive:requestDrive,requestPublic:requestPublic,requestUser:requestUser,formatSize:formatSize,formatDate:formatDate,mimeKind:mimeKind,encode:encode,decode:decode,cacheQuota:cacheQuota,getQuotaCache:getQuotaCache,quotaFresh:quotaFresh,pushRecent:pushRecent,recent:recent};
})();