/* PikPak 0.1.0-test.4 Core Patch - official captcha verification handoff */
(function(C){
    var WEB={name:'web',client_id:'YUMx5nI8ZU8Ap8pm',client_secret:'dbw2OtmV'+'EeuUvIptb1Coyg',client_version:'2.0.0',package_name:'mypikpak.com',user_agent:'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0 Mobile Safari/537.36',redirect_uri:'xlaccsdk01://xbase.cloud/callback?state=harbor',salts:['C9qPpZLN8ucRTaTiUMWYS9cQvWOE','+r6CQVxjzJV6LCV','F','pFJRC','9WXYIDGrwTCz2OiVlgZa90qpECPD6olt','/750aCr4lm/Sly/c','RB+DT/gZCrbV','','CyLsf7hdkIRxRm215hl','7xHvLi2tOYP0Y92b','ZGTXXxu8E/MIWaEDB+Sm/','1UI3','E7fP5Pfijd+7K+t6Tg/NhuLq0eEUVChpJSkrKxpO','ihtqpG6FMt65+Xk+tWUH2','NhXXU9rg4XXdzo7u5o']};
    function normalize(user){return C.normalizePhoneAccount(String(user||'').trim());}
    function deviceId(user,pass){var d=md5(String(user||'')+String(pass||''));C.set('device_id_web',d);return d;}
    function captchaSign(did,ts){var s=WEB.client_id+WEB.client_version+WEB.package_name+String(did||'')+String(ts||'');for(var i=0;i<WEB.salts.length;i++)s=md5(s+WEB.salts[i]);return '1.'+s;}
    function headers(did,token){var h={'X-Device-Id':did,'User-Agent':WEB.user_agent,'Content-Type':'application/json; charset=utf-8','X-Client-ID':WEB.client_id,'X-Client-Version':WEB.client_version};if(token)h['X-Captcha-Token']=token;return h;}
    function stringify(o){try{return typeof o==='string'?o:JSON.stringify(o);}catch(e){return String(o||'');}}
    function verifyUrl(o){if(!o)return '';if(o.url)return String(o.url);if(o.verify_url)return String(o.verify_url);if(o.captcha_url)return String(o.captcha_url);var t=stringify(o),m=t.match(/https?:\\?\/\\?\/[^\"'\\s}]+/i);if(m&&m[0])return String(m[0]).replace(/\\\//g,'/');return '';}
    function needsReview(o){if(!o)return false;if(verifyUrl(o))return true;var t=stringify(o).toLowerCase();return t.indexOf('result:review')>=0||t.indexOf('value:\"review\"')>=0||t.indexOf('\"result\":\"review\"')>=0||t.indexOf('\"review\"')>=0||t.indexOf('spritepuzzle')>=0||t.indexOf('verification required')>=0;}
    function hostRequest(path,method,body,h,timeout){var r=C.raw('https://user.mypikpak.net'+path,method,body,h,timeout||10000);if(r&&r._network_error)r=C.raw('https://user.mypikpak.com'+path,method,body,h,timeout||10000);return r;}
    function initChallenge(user,pass,oldToken){user=normalize(user);pass=String(pass||'');if(!user||!pass)return {error:'EMPTY_ACCOUNT',error_description:'请输入账号和密码'};var did=deviceId(user,pass),ts=String(new Date().getTime()),meta={captcha_sign:captchaSign(did,ts),client_id:WEB.client_id,client_version:WEB.client_version,device_id:did,package_name:WEB.package_name,timestamp:ts,username:user};if(user.indexOf('@')>=0)meta.email=user;else meta.phone_number=user;var body={action:'POST:/v1/auth/signin',captcha_token:String(oldToken||''),client_id:WEB.client_id,device_id:did,meta:meta,redirect_uri:WEB.redirect_uri};var res=hostRequest('/v1/shield/captcha/init?client_id='+WEB.client_id,'POST',body,headers(did,''),10000);if(res&&res.captcha_token)C.set('captcha_token',String(res.captcha_token));if(needsReview(res))return {needsVerification:true,review:true,captcha_token:String((res&&res.captcha_token)||''),verify_url:verifyUrl(res),device_id:did,raw:res};if(!res||res.error||res.error_code||!res.captcha_token)return {error:'CAPTCHA_INIT_FAILED',error_description:'PikPak 登录验证初始化失败：'+C.errorText(res),raw:res};return {captcha_token:String(res.captcha_token),device_id:did,raw:res};}
    function signIn(user,pass,token,did){user=normalize(user);pass=String(pass||'');token=String(token||'');did=String(did||deviceId(user,pass));if(!token)return {error:'CAPTCHA_TOKEN_EMPTY',error_description:'验证令牌为空，请重新加载验证'};var body={captcha_token:token,client_id:WEB.client_id,client_secret:WEB.client_secret,password:pass,username:user};var res=hostRequest('/v1/auth/signin?client_id='+WEB.client_id,'POST',body,headers(did,token),12000);if(res&&!res.error&&!res.error_code&&res.access_token){C.set('captcha_token',token);C.setUsername(user);C.saveSession(res,{name:'web'},did);C.clear('last_login_issue');return res;}if(needsReview(res))return {needsVerification:true,review:true,captcha_token:token,verify_url:verifyUrl(res),device_id:did,raw:res};if(C.isCaptchaError(res)){var next=initChallenge(user,pass,'');if(next&&next.needsVerification)return next;if(next&&next.captcha_token)return {needsVerification:true,review:true,captcha_token:next.captcha_token,verify_url:next.verify_url||'',device_id:next.device_id||did,raw:next.raw};}return res;}
    function begin(user,pass){user=normalize(user);pass=String(pass||'');var cap=initChallenge(user,pass,'');if(!cap||cap.error||cap.needsVerification)return cap;return signIn(user,pass,cap.captcha_token,cap.device_id);}
    function finish(user,pass,token){user=normalize(user);pass=String(pass||'');return signIn(user,pass,token,deviceId(user,pass));}
    function reload(user,pass,oldToken){return initChallenge(user,pass,oldToken||'');}
    C.beginPasswordLogin=begin;C.finishPasswordLogin=finish;C.refreshPasswordChallenge=reload;C.login=begin;
})(PikPakCore);
