/* Hanime1 2.0.0-test.4 comments/replies raw parser patch */
(function(C,P,H){
  var BUILD=H.build, assertResp=H.assertResp, classBlock=H.classBlock, strip=H.strip, imageFrom=H.imageFrom, imageUrl=H.imageUrl, rawInput=H.rawInput, metaContent=H.metaContent;
  function commentBody(videoId){var base=C.resolveHost(false),url=C.query(base+'/loadComment',{type:'video',id:videoId}),r=assertResp(C.get(url,{base:base,referer:base+'/watch?v='+videoId,timeout:15000}),'评论'),body=String(r.body||'');try{var j=JSON.parse(body);if(j&&typeof j.comments==='string')body=j.comments;}catch(e){}return {base:base,body:body};}
  function fieldBlocks(html){return classBlock(html,'comment-index-text',true);}
  P.comments=function(videoId){var z=commentBody(videoId),body=z.body,base=z.base,fields=fieldBlocks(body),ids=[],rm=/reply-section-wrapper-(\d+)/gi,m;while((m=rm.exec(body))!==null){ids.push(m[1]);if(m.index===rm.lastIndex)rm.lastIndex++;}var out=[];for(var i=0;i+1<fields.length;i+=2){var f1=fields[i],f2=fields[i+1],user='';var am=f1.inner.match(/<a\b[^>]*>([\s\S]*?)<\/a>/i);user=am?strip(am[1]):strip(f1.inner);var sm=f1.inner.match(/<span\b[^>]*>([\s\S]*?)<\/span>/i),time=sm?strip(sm[1]):'',content=strip(f2.inner);if(!user||!content)continue;var start=Math.max(0,f1.index-2200),end=i+2<fields.length?fields[i+2].index:Math.min(body.length,f2.index+6000),frag=body.slice(start,end),avatar=C.abs(base,imageFrom(frag)),replyText=textClass(frag,'load-replies-btn'),rc=(replyText.match(/\d+/)||[])[0]||'';out.push({id:ids[Math.floor(i/2)]||rawInput(frag,'foreign_id')||'',user:user,content:content,time:time,avatar:imageUrl(avatar,base+'/watch?v='+videoId),replyCount:rc});}return {items:out,csrf:rawInput(body,'_token')||metaContent(body,'csrf-token'),userId:rawInput(body,'comment-user-id')};};
  P.replies=function(commentId){var base=C.resolveHost(false),r=assertResp(C.get(C.query(base+'/loadReplies',{id:commentId}),{base:base,referer:base+'/',timeout:15000}),'回复'),body=String(r.body||'');try{var j=JSON.parse(body);if(j&&typeof j.replies==='string')body=j.replies;}catch(e){}var f=fieldBlocks(body),out=[];for(var i=0;i+1<f.length;i+=2){var am=f[i].inner.match(/<a\b[^>]*>([\s\S]*?)<\/a>/i),sm=f[i].inner.match(/<span\b[^>]*>([\s\S]*?)<\/span>/i),u=am?strip(am[1]):strip(f[i].inner),c=strip(f[i+1].inner);if(u&&c)out.push({user:u,content:c,time:sm?strip(sm[1]):''});}return out;};
  P.build=BUILD;
})(HanimeCore,HanimeProvider,HanimePatch4Common);
