/* Hanime1 2.0.0-test.4 browser account + remote library provider patch */
(function(C,P,H){
  var BUILD=H.build, attr=H.attr, strip=H.strip, rawInput=H.rawInput, metaContent=H.metaContent, assertResp=H.assertResp, imageFrom=H.imageFrom, imageUrl=H.imageUrl, decodeHtml=H.decodeHtml, textClass=H.textClass, uniq=H.uniq, cardsRaw=H.cardsRaw;
  P.profile=function(){var base=C.resolveHost(false),home=assertResp(C.get(base+'/',{base:base,referer:base+'/',timeout:12000}),'账号校验').body;var ut=String(home).match(/<[^>]+id\s*=\s*(["'])user-modal-trigger\1[^>]*>/i),href=ut?attr(ut[0],'href'):'',hm=href.match(/\/user\/(\d+)/),id=hm?hm[1]:'';if(!id){var sm=strip(home).match(/ID\s*[:#]?\s*(\d+)/i);if(sm)id=sm[1];}if(!id)throw new Error('未检测到已登录账号，请先在登录页完成网页登录');var edit=assertResp(C.get(base+'/user/'+id+'/edit',{base:base,referer:base+'/',timeout:12000}),'账号资料').body;var name=rawInput(edit,'name')||('用户 '+id),email=rawInput(edit,'email'),csrf=metaContent(edit,'csrf-token')||rawInput(edit,'_token'),avatar='';var avatarMatch=String(edit).match(/<img\b[^>]*id\s*=\s*(["'])playlist-avatar\1[^>]*>/i);if(avatarMatch)avatar=attr(avatarMatch[0],'src');if(!avatar){var frag=String(home).match(/<[^>]+id\s*=\s*(["'])user-modal-dp-wrapper\1[^>]*>[\s\S]{0,4000}?<\/[^>]+>/i);if(frag)avatar=imageFrom(frag[0]);}return {id:id,name:name,email:email,avatar:imageUrl(C.abs(base,avatar),base+'/'),csrf:csrf,joined:'',cookie:C.accountCookie(base),base:base};};
  P.syncBrowserAccount=function(){C.useBrowserSession();var p=P.profile(),raw=C.browserCookie(p.base);if(!C.withoutClearance(raw))throw new Error('浏览器登录 Cookie 为空，请先在下方官网完成登录');return C.saveAccount(p,raw);};

  function rawPlaylists(html,base){var out=[],re=/<a\b[^>]*href\s*=\s*(["'])([^"']*playlist\?list=([^&"']+)[^"']*)\1[^>]*>/gi,m;while((m=re.exec(String(html||'')))!==null){var a=Math.max(0,m.index-3000),b=Math.min(String(html).length,m.index+6000),frag=String(html).slice(a,b),title=textClass(frag,'playlist-title')||textClass(frag,'title')||strip((frag.match(/<[^>]*class\s*=\s*(["'])[^"']*playlist[^"']*title[^"']*\1[^>]*>([\s\S]*?)<\//i)||[])[2]||'片单'),img=C.abs(base,imageFrom(frag)),count=textClass(frag,'playlist-count')||textClass(frag,'stat-item');out.push({id:decodeHtml(m[3]),title:title||'片单',count:count,img:imageUrl(img,base+'/')});if(m.index===re.lastIndex)re.lastIndex++;}return uniq(out,function(x){return x.id;});}
  P.library=function(){var p=P.profile(),base=p.base,urls=[['watchLater','/user/'+p.id+'/saves'],['favorites','/user/'+p.id+'/likes'],['playlists','/user/'+p.id+'/playlists'],['history','/user/'+p.id+'/histories?sort=latest&page=1'],['subscriptions','/subscriptions?page=1']],out={profile:p,watchLater:[],favorites:[],playlists:[],history:[],subscriptions:[],artists:[],csrf:p.csrf};for(var i=0;i<urls.length;i++){var key=urls[i][0],body=assertResp(C.get(base+urls[i][1],{base:base,referer:base+'/',timeout:15000}),'片库 '+key).body;if(key==='playlists')out.playlists=rawPlaylists(body,base);else out[key]=cardsRaw(body,base);}return out;};
  P.build=BUILD;
})(HanimeCore,HanimeProvider,HanimePatch4Common);
