/* ACFAN 0.2.1-test.7 playback + H5 terminal */
var ACFAN7Playback=(function(){
  var C=ACFAN7Core,P=ACFAN7Protocol;
  function host(){return C.s(getItem(C.K.apiHost,'')||C.staticApiHosts[0]).replace(/\/+$/,'');}
  function origin(u){var m=C.s(u).match(/^(https?:\/\/[^/?#]+)/i);return m?m[1]:'';}
  function headers(mode,literal){var api=host(),h5=origin(C.getH5())||api,ref=mode==='app'?(literal||'jhg_player'):(mode==='h5'?h5+'/':api+'/'),h={'User-Agent':'Mozilla/5.0 (Linux; Android 12; SM-G9750 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0 Mobile Safari/537.36','Referer':ref,'Origin':h5};if(mode==='app')h['X-Referer']=ref;return h;}
  function collect(root){var out=[],seen={},count=0,exact={videoUrl:1,previewUrl:1,playPath:1,videoUri:1,m3u8Url:1,m3u8:1,m3u8H:1,sourcePath:1,mediaUrl:1};function add(v,name){v=C.first(v);v=C.s(v).trim();if(!v||seen[v])return;seen[v]=1;out.push({path:v,name:C.clean(name)||'播放'});}function walk(v,key,d){if(v===undefined||v===null||d>9||count++>7000)return;if(typeof v==='string'||typeof v==='number'){var k=C.s(key);if(exact[k])add(v,k);else if(!/cover|image|img|avatar|poster|icon|domain|host|auth|referer|credential|key/i.test(k)&&(/(?:video|play|media|m3u8|preview|source)/i.test(k)||/^(?:jpc|jpd|hls|video|media)\//i.test(C.s(v))||/\.(?:m3u8|mp4)(?:[?#]|$)/i.test(C.s(v))))add(v,k);return;}if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],key,d+1);return;}if(typeof v!=='object')return;var label=C.pick(v,['qualityName','clarityName','name','title','label','quality'],'');for(var k in v){if(exact[k])add(v[k],label||k);else walk(v[k],k,d+1);}}walk(root,'',0);return out;}
  function config(root){root=root||{};return{domain:C.s(C.deep(root,['playbackDomain','mediaDomain','m3u8Domain','mp4Domain'],0)).replace(/\/+$/,''),auth:C.s(C.deep(root,['playbackAuthKey','authKey','auth_key'],0)).trim(),referer:C.s(C.deep(root,['playerReferer','xReferer','referer'],0)).trim()};}
  function credential(id,path){try{return P.tryApi('m3u8/player/referer',{videoId:C.n(id),path:C.s(path)},['GET'],{timeout:1600})||{};}catch(e){C.diag('PLAY_CREDENTIAL_SKIP',C.s(e.message||e),{id:id});return{};}}
  function appendAuth(u,auth,key){if(!auth||/[?&](?:authKey|auth_key)=/i.test(u))return u;return u+(u.indexOf('?')>=0?'&':'?')+(key||'authKey')+'='+encodeURIComponent(auth);}
  function join(domain,path,auth){if(!domain)return'';var u=domain.replace(/\/+$/,'')+'/'+C.s(path).replace(/^\/+/, '');return appendAuth(u,auth,'auth_key');}
  function mark(u){if(/\.mp4(?:[?#]|$)/i.test(u))return u+'#isVideo=true#';return u+'#isM3u8#';}
  function buildRoutes(paths,cfg){var api=host(),out=[],seen={};function add(name,u,h){u=C.s(u).trim();if(!u||seen[u])return;seen[u]=1;out.push({name:name,url:mark(u),headers:h||{}});}for(var i=0;i<paths.length;i++){var p=paths[i],v=C.s(p.path).trim(),q=encodeURIComponent(v),label=p.name||('线路 '+(i+1));if(/^https?:\/\//i.test(v))add(label+'·直连',appendAuth(v,cfg.auth,'auth_key'),headers('app',cfg.referer));if(cfg.domain){add(label+'·CDN',join(cfg.domain,v,cfg.auth),headers('app',cfg.referer));add(label+'·APP域',appendAuth(cfg.domain+'/api/m3u8/play?path='+q,cfg.auth,'authKey'),headers('app',cfg.referer));add(label+'·兼容域',appendAuth(cfg.domain+'/m3u8/play?path='+q,cfg.auth,'auth_key'),headers('app',cfg.referer));}add(label+'·网页解码',api+'/api/m3u8/h5/decode?path='+q,headers('h5',cfg.referer));add(label+'·原生接口',appendAuth(api+'/api/m3u8/play?path='+q,cfg.auth,'authKey'),headers('app',cfg.referer));add(label+'·根接口',appendAuth(api+'/m3u8/play?path='+q,cfg.auth,'auth_key'),headers('app',cfg.referer));}return out.slice(0,12);}
  function nativePlay(id,seed,title){id=C.s(id);var roots=[seed||{}],paths=collect(seed||{}),watch={},used=paths.length?'detail':'';if(id){try{watch=P.tryApi('video/can/watch',{videoId:C.n(id)},['GET'],{timeout:3200})||{};roots.push(watch);var fresh=collect(watch);for(var f=0;f<fresh.length;f++)paths.push(fresh[f]);if(fresh.length)used=used?used+'+watch':'watch';}catch(e){C.diag('PLAY_WATCH_FAIL',C.s(e.message||e),{id:id});}}var uniq=[],seen={};for(var i=0;i<paths.length;i++)if(paths[i].path&&!seen[paths[i].path]){seen[paths[i].path]=1;uniq.push(paths[i]);}paths=uniq;if(!paths.length){C.diag('PLAY_NO_SOURCE','id='+id,{route:used});return C.page('acfanT7Bridge',{acf_kind:'video',acf_id:id,acf_title:title||'ACFAN 视频'});}var cfg={domain:'',auth:'',referer:''};for(var r=0;r<roots.length;r++){var x=config(roots[r]);if(!cfg.domain&&x.domain)cfg.domain=x.domain;if(!cfg.auth&&x.auth)cfg.auth=x.auth;if(!cfg.referer&&x.referer)cfg.referer=x.referer;}if((!cfg.domain||!cfg.referer)&&paths.length){var cr=credential(id,paths[0].path),cx=config(cr);if(!cfg.domain)cfg.domain=cx.domain;if(!cfg.auth)cfg.auth=cx.auth;if(!cfg.referer)cfg.referer=cx.referer;}var routes=buildRoutes(paths,cfg),urls=[],names=[],hs=[];for(var j=0;j<routes.length;j++){urls.push(routes[j].url);names.push(routes[j].name);hs.push(routes[j].headers);}if(!urls.length)return C.page('acfanT7Bridge',{acf_kind:'video',acf_id:id,acf_title:title||'ACFAN 视频'});C.diag('PLAY_NATIVE',used,{id:id,pathCount:paths.length,routeCount:urls.length,playbackDomain:cfg.domain,hasAuth:!!cfg.auth,names:names});return JSON.stringify({urls:urls,names:names,headers:hs});}
  function bridgeUrl(kind,id,title,chapter){return C.page('acfanT7Bridge',{acf_kind:kind||'video',acf_id:id||'',acf_title:title||'',acf_chapter:chapter||''});}
  function bridgeScript(kind,id,title,chapter){var cfg={kind:C.s(kind),id:C.s(id),title:C.s(title),chapter:C.s(chapter)};return '('+function(c){function text(e){return String(e&&e.innerText||'').replace(/\s+/g,' ').trim();}function visible(e){if(!e)return false;var r=e.getBoundingClientRect();return r.width>0&&r.height>0;}function click(e){try{if(e&&visible(e)){e.click();return true;}}catch(x){}return false;}function setValue(e,v){try{var p=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value');if(p&&p.set)p.set.call(e,v);else e.value=v;}catch(x){e.value=v;}try{e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));}catch(x2){}}function searchInput(){return document.querySelector('input[type=search],input[placeholder*=搜索],input[placeholder*=搜],input[name*=search],input[name*=keyword],input[type=text]');}function target(){var q=String(c.title||'').trim(),keys=[q,q.slice(0,24),q.slice(0,16),q.slice(0,10)].filter(function(x){return x.length>=3;}),all=document.querySelectorAll('a,article,li,[role=button],[class*=card],[class*=item]');for(var k=0;k<keys.length;k++)for(var i=0;i<all.length;i++){var s=text(all[i]);if(s&&s.indexOf(keys[k])>=0&&visible(all[i]))return all[i].closest&&all[i].closest('a')||all[i];}return null;}function ready(){if(c.kind==='video'||c.kind==='short'||c.kind==='audio'){var v=document.querySelector('video,audio');if(v&&visible(v)){try{v.scrollIntoView({block:'start'});v.play();}catch(x){}return true;}}if(c.kind==='comic'){var z=document.querySelectorAll('main img,[class*=reader] img,[class*=comic] img');if(z.length>3)return true;}return false;}var loops=0,lastSubmit=0,timer=setInterval(function(){loops++;if(ready()){clearInterval(timer);return;}var hit=target();if(hit&&click(hit))return;var i=searchInput();if(i&&c.title){setValue(i,c.title);if(Date.now()-lastSubmit>2600){lastSubmit=Date.now();try{i.focus();i.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));}catch(x){}var f=i.closest&&i.closest('form');try{if(f&&f.requestSubmit)f.requestSubmit();else if(f)f.submit();}catch(x2){}}}if(loops>75)clearInterval(timer);},650);}+')('+JSON.stringify(cfg)+');';}
  function directAudio(url,title){url=C.s(url).trim();if(!url)return'toast://没有可用音频';return JSON.stringify({urls:[url+'#isMusic=true#'],names:[title||'播放'],headers:[{'User-Agent':C.ua}]});}
  return{nativePlay:nativePlay,bridgeUrl:bridgeUrl,bridgeScript:bridgeScript,directAudio:directAudio,collect:collect};
})();
