/* ACFAN 0.2.1-test.7 protocol/auth/domain discovery */
var ACFAN7Protocol=(function(){
  var C=ACFAN7Core;
  function safeJson(v){if(v===undefined||v===null)return null;if(typeof v==='object')return v;var x=String(v).trim();if(!x)return null;try{return JSON.parse(x);}catch(e){return null;}}
  function md5(text){try{var md=java.security.MessageDigest.getInstance('MD5'),bytes=md.digest(new java.lang.String(String(text||'')).getBytes('UTF-8')),sb=new java.lang.StringBuilder();for(var i=0;i<bytes.length;i++){var v=bytes[i]&255;if(v<16)sb.append('0');sb.append(java.lang.Integer.toHexString(v));}return String(sb.toString());}catch(e){return'';}}
  function deviceId(){var d=getItem(C.K.device,'');if(d)return d;d=md5(String(Date.now())+'-'+String(Math.random())+'-acfan-t6')||('hk'+Date.now());setItem(C.K.device,d);return d;}
  function normalizeOrigin(u){u=C.s(u).trim().replace(/\\\//g,'/');var m=u.match(/^(https?:\/\/[^/?#]+)/i);return m?m[1].replace(/\/+$/,''):'';}
  function headers(noAuth,origin){var ts=String(Date.now()),sub=ts.length>=8?ts.substring(3,8):ts,base=origin||getItem(C.K.apiHost,'')||C.staticApiHosts[0],h={'User-Agent':C.ua,'Accept':'application/json, text/plain, */*','Content-Type':'application/json;charset=UTF-8','deviceId':deviceId(),'t':ts,'s':md5(sub),'User-Mark':'acfun','Origin':base,'Referer':base.replace(/\/+$/,'')+'/'};var token=getItem(C.K.token,'');if(!noAuth&&token)h.aut=token;return h;}
  function aesDecrypt(src){src=C.s(src).trim();if(!src)return'';var token=C.s(getItem(C.K.token,''));if(token.length<18)throw new Error('响应需要游客令牌');var secret=token.substring(2,18),kb=new java.lang.String(secret).getBytes('UTF-8'),key=new javax.crypto.spec.SecretKeySpec(kb,'AES'),iv=new javax.crypto.spec.IvParameterSpec(kb),cipher=javax.crypto.Cipher.getInstance('AES/CBC/PKCS5Padding');cipher.init(javax.crypto.Cipher.DECRYPT_MODE,key,iv);var enc=java.util.Base64.getDecoder().decode(src.replace(/\s+/g,''));return String(new java.lang.String(cipher.doFinal(enc),'UTF-8'));}
  function storeSession(root,origin){if(!root||typeof root!=='object')return;var t=C.deep(root,['token','userToken','accessToken'],0);if(typeof t==='string'&&t.length>16)setItem(C.K.token,t);var img=C.deep(root,['imgDomain','imageDomain','cdnDomain'],0);if(typeof img==='string'&&/^https?:\/\//i.test(img))setItem(C.K.imgDomain,img.replace(/\/+$/,''));if(origin)setItem(C.K.apiHost,origin);}
  function payload(body,origin){var jr=safeJson(body);if(!jr)return null;storeSession(jr,origin);if(jr.encData!==undefined&&C.s(jr.encData).trim()){var plain=aesDecrypt(jr.encData),j=safeJson(plain);jr.data=j===null?plain:j;}if(jr.data!==undefined)return jr.data;if(jr.result!==undefined&&typeof jr.result!=='string')return jr.result;if(jr.rows!==undefined)return jr.rows;return jr;}
  function classifyConfig(root){var api=[],h5=[],seenA={},seenH={},count=0;function add(a,seen,v,mobile){var o=normalizeOrigin(v);if(!o||seen[o])return;seen[o]=1;a.push(mobile?o+'/mobile':o);}function walk(v,key,d){if(v===undefined||v===null||d>8||count++>1800)return;if(typeof v==='string'){if(/^https?:\/\//i.test(v)){if(/api|baseurl|apihost|apiurl|server/i.test(C.s(key)))add(api,seenA,v,false);else add(h5,seenH,v,true);}return;}if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],key,d+1);return;}if(typeof v!=='object')return;for(var k in v)walk(v[k],k,d+1);}walk(root,'root',0);return{api:api,h5:h5};}
  function loadConfig(force){var cached=C.readJson(C.K.h5Candidates,[]),now=Date.now(),ts=Number(getItem(C.K.apiHostsTs,'0')||0);if(!force&&cached.length&&now-ts<6*3600e3)return{api:C.readJson(C.K.apiHosts,[]),h5:cached};var api=[],h5=[],seenA={},seenH={};function add(a,seen,u){u=C.s(u);var o=normalizeOrigin(u);if(!o||seen[o])return;seen[o]=1;a.push(o);}for(var i=0;i<C.configUrls.length;i++){try{var raw=fetch(C.configUrls[i]+'?_='+now,{timeout:2500,headers:{'User-Agent':C.ua,'Accept':'application/json,*/*','Cache-Control':'no-cache'}}),cfg=classifyConfig(safeJson(raw)||{});for(var a=0;a<cfg.api.length;a++)add(api,seenA,cfg.api[a]);for(var h=0;h<cfg.h5.length;h++){var hu=C.s(cfg.h5[h]);if(hu&&!seenH[hu]){seenH[hu]=1;h5.push(hu);}}}catch(e){}}for(var j=0;j<C.staticApiHosts.length;j++)add(api,seenA,C.staticApiHosts[j]);var current=C.getH5();if(current&&!seenH[current])h5.unshift(current);C.writeJson(C.K.apiHosts,api);C.writeJson(C.K.h5Candidates,h5.slice(0,12));setItem(C.K.apiHostsTs,String(now));return{api:api,h5:h5.slice(0,12)};}
  function buildUrl(url,params){params=params||{};var q=[];for(var k in params)if(params[k]!==undefined&&params[k]!==null&&C.s(params[k])!=='')q.push(encodeURIComponent(k)+'='+encodeURIComponent(C.s(params[k])));return url+(q.length?(url.indexOf('?')>=0?'&':'?')+q.join('&'):'');}
  function rawRequest(origin,path,params,opt){opt=opt||{};params=params||{};var p=C.s(path).replace(/^\/+/,''),method=C.s(opt.method||'GET').toUpperCase(),url=origin.replace(/\/+$/,'')+'/api/'+p,target=url,options={timeout:Number(opt.timeout||3600),headers:headers(!!opt.noAuth,origin),method:method,withStatusCode:true};if(method==='GET')target=buildUrl(url,params);else options.body=JSON.stringify(params);var got=fetch(target,options),wrap=safeJson(got);if(!wrap)return{ok:false,error:'EMPTY_WRAPPER',status:0,url:target};var status=Number(wrap.statusCode||wrap.status||0),body=wrap.body!==undefined?wrap.body:got;body=body===undefined||body===null?'':String(body);if(status<200||status>=300)return{ok:false,error:'HTTP_'+status,status:status,body:body,url:target};var jr=safeJson(body);if(!jr)return{ok:false,error:'NON_JSON',status:status,body:body,url:target};storeSession(jr,origin);var code=jr.code!==undefined?Number(jr.code):(jr.statusCode!==undefined?Number(jr.statusCode):NaN);if([301,302,401,403,1001,1003].indexOf(code)>=0)return{ok:false,auth:true,error:'AUTH_'+code,status:status,body:body,url:target};if(!isNaN(code)&&code!==0&&code!==200)return{ok:false,error:'CODE_'+code+'_'+C.clean(jr.message||jr.msg||''),status:status,body:body,url:target};return{ok:true,status:status,body:body,json:jr,url:target};}
  function candidateHosts(force){var cfg=loadConfig(force),out=[],seen={};function add(h){h=normalizeOrigin(h);if(!h||seen[h])return;seen[h]=1;out.push(h);}add(getItem(C.K.apiHost,''));for(var i=0;i<cfg.api.length;i++)add(cfg.api[i]);for(var j=0;j<C.staticApiHosts.length;j++)add(C.staticApiHosts[j]);return out.slice(0,8);}
  function ensureTraveler(force){if(!force&&getItem(C.K.token,'')&&getItem(C.K.apiHost,''))return true;var hosts=candidateHosts(force),did=deviceId(),bodies=[{deviceId:did,chCode:'acfan',appVersion:'1.9.7'},{deviceId:did,chCode:'acfan'},{deviceId:did,chCode:'acfun',appVersion:'1.9.7'}],errs=[];for(var h=0;h<hosts.length;h++){for(var b=0;b<bodies.length;b++){try{var r=rawRequest(hosts[h],'user/traveler/',bodies[b],{method:'POST',noAuth:true,timeout:3200});if(r.ok){storeSession(r.json,hosts[h]);if(getItem(C.K.token,'')){C.diag('TRAVELER_OK',hosts[h],{attempt:b+1});return true;}}errs.push(hosts[h]+' '+r.error);}catch(e){errs.push(hosts[h]+' '+C.s(e.message||e));}}}C.diag('TRAVELER_FAIL',errs.slice(-12).join(' | '),{hosts:hosts});return false;}
  function api(path,params,opt){opt=opt||{};params=params||{};if(!opt.noAuth&&!/^user\/traveler\/?$/i.test(C.s(path)))ensureTraveler(false);var sticky=normalizeOrigin(getItem(C.K.apiHost,'')),hosts=candidateHosts(false),errs=[],auth=false,max=sticky?2:4;if(hosts.length>max)hosts=hosts.slice(0,max);for(var i=0;i<hosts.length;i++){try{var r=rawRequest(hosts[i],path,params,opt);if(r.ok){setItem(C.K.apiHost,hosts[i]);var data=payload(r.body,hosts[i]);if(data!==null&&data!==undefined){C.diag('API_OK',(opt.method||'GET')+' '+path,{host:hosts[i],status:r.status});return data;}errs.push(hosts[i]+' EMPTY_DATA');}else{if(r.auth)auth=true;errs.push(hosts[i]+' '+r.error);}}catch(e){errs.push(hosts[i]+' '+C.s(e.message||e));}}if(auth&&!opt.__retry){setItem(C.K.token,'');if(ensureTraveler(true))return api(path,params,C.merge(opt,{__retry:true}));}C.diag('API_FAIL',path+' | '+errs.slice(-8).join(' | '),{method:opt.method||'GET'});throw new Error('接口失败：'+path);}
  function tryApi(path,params,methods,opt){methods=methods||['GET'];var errs=[];for(var i=0;i<methods.length;i++){try{return api(path,params,C.merge(opt||{},{method:methods[i]}));}catch(e){errs.push(methods[i]+':'+C.s(e.message||e));}}throw new Error(errs.join(' | '));}
  function refreshH5(){var cfg=loadConfig(true),c=[C.getH5()].concat(cfg.h5||[]),seen={},valid=[];for(var i=0;i<c.length;i++){var u=C.s(c[i]);if(!u||seen[u])continue;seen[u]=1;valid.push(u);}C.writeJson(C.K.h5Candidates,valid.slice(0,12));return valid.slice(0,12);}
  return{safeJson:safeJson,md5:md5,deviceId:deviceId,normalizeOrigin:normalizeOrigin,headers:headers,aesDecrypt:aesDecrypt,payload:payload,classifyConfig:classifyConfig,loadConfig:loadConfig,buildUrl:buildUrl,rawRequest:rawRequest,candidateHosts:candidateHosts,ensureTraveler:ensureTraveler,api:api,tryApi:tryApi,refreshH5:refreshH5};
})();
