/* ACFAN 0.2.1-test.7 models + provider */
var ACFAN7Provider=(function(){
  var C=ACFAN7Core,P=ACFAN7Protocol;
  var CHANNELS=[
    {id:'featured',name:'精选',kind:'video',icon:'featured.svg'},
    {id:'lifan',name:'里番',kind:'video',icon:'featured.svg'},
    {id:'anime',name:'动漫',kind:'video',icon:'anime.svg'},
    {id:'video',name:'视频',kind:'video',icon:'video.svg'},
    {id:'short',name:'短视频',kind:'short',icon:'short.svg'},
    {id:'comic',name:'漫画',kind:'comic',icon:'comic.svg'},
    {id:'fiction',name:'小说',kind:'fiction',icon:'novel.svg'},
    {id:'audio',name:'有声',kind:'audio',icon:'audio.svg'},
    {id:'community',name:'社区',kind:'community',icon:'community.svg'},
    {id:'ai',name:'AI广场',kind:'ai',icon:'ai.svg'}
  ];
  function channel(id){for(var i=0;i<CHANNELS.length;i++)if(CHANNELS[i].id===id)return CHANNELS[i];return CHANNELS[0];}
  function cover(root){root=root||{};return C.first(C.deep(root,['coverImg','videoCover','videoCoverImg','coverPicture','videoImg','videoImage','mainImg','generatedCoverImg','templateCoverImg','defaultVideoPoster','coverUrl','horizontalCover','verticalCover','imageUrl','imgUrl','imagePath','thumbUrl','thumbURL','posterMainUrl','posterDownloadUrl','verticalImg','backImg','cardImg','dynamicImg','comicsCover','comicCover','fictionImg','fictionCover','fictionCoverImg','worksUrl','worksCover','cover','poster','img','image','picture','pictures'],0));}
  function mediaPath(root){root=root||{};var v=C.first(C.deep(root,['videoUrl','playUrl','videoUri','m3u8Url','m3u8','playPath','sourcePath','audioUrl','audioPath'],0));if(v)return C.s(v);var g=C.first(C.deep(root,['path','url'],0));return /(?:\.m3u8|\.mp4|\/api\/m3u8\/|^(?:jpc|jpd|hls|video|media)\/)/i.test(C.s(g))?C.s(g):'';}
  function author(root){root=root||{};var u=C.deep(root,['user','userInfo','blogger','authorInfo','movieUser','creator'],0)||{};return{id:C.s(C.pick(u,['userId','id','uid','authorId'],C.deep(root,['userId','authorId','bloggerId'],0))),name:C.clean(C.pick(u,['nickname','nickName','userName','username','name'],C.deep(root,['nickname','nickName','userName','authorName'],0))),avatar:C.s(cover(u))};}
  function entity(kind,x){x=x||{};var src=x,au=author(x),id='',title='',desc='',badge='',stats={};if(kind==='video'||kind==='short'){src=x.video||x.videoInfo||x.content||x;if(src&&src.video&&typeof src.video==='object')src=src.video;id=C.pick(src,['videoId','id','vid','lsjVideoId'],C.deep(x,['videoId','lsjVideoId','vid'],0));title=C.pick(src,['videoTitle','title','name','video_title'],C.deep(x,['videoTitle','title','name'],0));desc=C.deep(x,['description','desc','introduction','videoDesc'],0);stats={watch:C.deep(x,['watchNum','viewNum','playNum','fakeWatchNum','statisticsTimes'],0),like:C.deep(x,['likeNum','likes','favoriteNum','likeCount'],0),comment:C.deep(x,['commentNum','commentCount'],0),duration:C.deep(x,['duration','videoDuration','playTime','video_duration'],0)};badge=C.clean(C.deep(x,['label','badge','cornerTitle','serialText'],0));}
    else if(kind==='comic'){id=C.pick(x,['comicsId','comicId','id','comic_id'],C.deep(x,['comicsId','comicId'],0));title=C.pick(x,['comicsTitle','comicTitle','title','name','comic_title'],C.deep(x,['comicsTitle','comicTitle','title'],0));desc=C.deep(x,['subTitle','subtitle','description','desc','info','introduction'],0);stats={chapter:C.deep(x,['chapterNum','chapterCount','totalChapter'],0),like:C.deep(x,['likeNum','likeCount'],0)};}
    else if(kind==='fiction'||kind==='audio'){id=C.pick(x,['fictionId','bookId','novelId','id'],C.deep(x,['fictionId','bookId'],0));title=C.pick(x,['fictionTitle','bookTitle','bookName','novelTitle','title','name'],C.deep(x,['fictionTitle','bookTitle','title'],0));desc=C.deep(x,['description','desc','info','introduction'],0);stats={chapter:C.deep(x,['chapterNum','chapterCount','totalChapter'],0),like:C.deep(x,['likeNum','likeCount'],0)};}
    else if(kind==='community'){id=C.pick(x,['dynamicId','postId','id'],C.deep(x,['dynamicId','postId'],0));title=C.deep(x,['dynamicContent','content','contentText','text','title'],0)||'社区动态';desc=C.deep(x,['description','desc'],0);stats={like:C.deep(x,['likeNum','likeCount','likes'],0),comment:C.deep(x,['commentNum','commentCount','comments'],0),time:C.deep(x,['createTime','createdAt','publishTime'],0)};}
    else if(kind==='ai'){id=C.pick(x,['worksId','workId','aiBoxId','id'],C.deep(x,['worksId','workId'],0));title=C.pick(x,['worksName','workName','title','name','prompt'],C.deep(x,['title','name'],0))||'AI作品';desc=C.deep(x,['description','desc','prompt','content'],0);stats={like:C.deep(x,['likeNum','likeCount'],0),comment:C.deep(x,['commentNum','commentCount'],0)};}
    return{kind:kind,id:C.s(id),title:C.clean(title||'未命名'),img:C.s(cover(src)||cover(x)),imgDomain:C.s(C.deep(x,['__imageDomain','imgDomain','imageDomain','cdnDomain'],0)),author:au.name,authorId:au.id,avatar:au.avatar,desc:C.clean(desc),badge:badge,uri:mediaPath(x),stats:stats,raw:x};}
  function namedRows(rows,idKeys,nameKeys){var out=[];for(var i=0;i<(rows||[]).length;i++){var x=rows[i]||{},id=C.pick(x,idKeys,''),name=C.pick(x,nameKeys,'');if(!id||!name||/(?:测试|test|comicsclass|ces\d*|罗峰测试|竖版|竖横|横滑|六宫格|四宫格|两格|专题\d|^2026\d+)/i.test(C.s(name)))continue;out.push({id:C.s(id),name:C.clean(name),raw:x});}return C.uniq(out,function(z){return z.id;});}
  function cached(name,ttl,loader){var key='acfan_t7_tax_'+name,now=Date.now(),old=C.readJson(key,null),stale=old&&Array.isArray(old.data)?old.data:[];if(old&&now-Number(old.ts||0)<ttl&&stale.length)return stale;try{var fresh=loader()||[];if(fresh.length){C.writeJson(key,{ts:now,data:fresh});return fresh;}}catch(e){C.diag('CACHE_LOAD_FAIL',name+' | '+C.s(e.message||e));}return stale;}
  function tryData(path,params,methods,timeout){try{return P.tryApi(path,params,methods||['GET'],{timeout:timeout||3600});}catch(e){C.diag('PROVIDER_SKIP',path+' | '+C.s(e.message||e));return null;}}
  function tryRows(path,params,methods,timeout){var data=tryData(path,params,methods,timeout),rows=C.arr(data),domain=C.s(C.deep(data||{},['imgDomain','imageDomain','cdnDomain'],0));if(domain&&/^https?:\/\//i.test(domain)){setItem(C.K.imgDomain,domain.replace(/\/+$/,''));for(var i=0;i<rows.length;i++)if(rows[i]&&typeof rows[i]==='object'&&!rows[i].__imageDomain)rows[i].__imageDomain=domain;}return rows;}
  function stations(restricted){return cached('stations_'+(restricted?1:0),21600000,function(){return namedRows(tryRows('station/stations',{classifyId:4,page:1,pageSize:60,restricted:restricted?1:0},['GET','POST'],3200),['stationId','stationID','id'],['stationName','stationTitle','title','name']);});}
  function classes(section){return cached('classes_'+section,43200000,function(){var type=section==='video'?4:2,rows=tryRows('video/classTypeList',{type:type,restricted:0},['GET','POST'],3000);if(!rows.length)rows=tryRows('video/classifyList',{type:type,restricted:0},['GET','POST'],3000);return namedRows(rows,['classifyId','classTypeId','videoTypeId','typeId','id'],['classifyTitle','classTypeTitle','classifyName','classTypeName','videoTypeName','title','name']);});}
  function tags(classId){return cached('tags_'+C.s(classId),43200000,function(){var cid=C.n(classId),rows=tryRows('video/tags/getTagsZ',{videoTypeId:cid,classifyId:cid,restricted:0},['GET','POST'],2800),out=[],seen={};function add(x,mode){var name=C.s(C.pick(x,['videoTagName','tagName','tagsTitle','tagTitle','name','title'],'')||''),value=C.s(C.pick(x,['videoTagValue','tagValue','videoTagKey','tagKey','value','id'],name)||name);if(!name)name=value;if(name&&!seen[value+'|'+name]){seen[value+'|'+name]=1;out.push({id:value,name:C.clean(name),value:value,mode:mode,raw:x});}}for(var i=0;i<rows.length;i++)add(rows[i],'tag');if(!out.length){var z=tryRows('video/getZoneListByClassifyId',{classifyId:cid},['GET','POST'],2600);for(var j=0;j<z.length;j++){var zid=C.s(C.pick(z[j],['zoneId','id'],'')),zn=C.s(C.pick(z[j],['zoneTitle','zoneName','title','name'],''));if(zid&&zn)out.push({id:zid,name:C.clean(zn),value:zid,mode:'zone',raw:z[j]});}}if(!out.length){var n=tryRows('video/tags/getTags',{videoTypeId:cid,classifyId:cid,restricted:0},['GET','POST'],2600);for(var k=0;k<n.length;k++)add(n[k],'tag');}return C.uniq(out,function(z){return z.id+'|'+z.name;});});}
  function comicStations(){return cached('comic_stations',21600000,function(){return namedRows(tryRows('comics/station/getComicsStations',{page:1,pageNum:1,pageSize:60},['GET','POST'],3200),['stationId','comicsStationId','id'],['stationName','stationTitle','name','title']);});}
  function comicClasses(){return cached('comic_classes',43200000,function(){return namedRows(tryRows('comics/other/classList',{},['GET','POST'],2800),['classId','categoryId','id'],['className','categoryName','name','title']);});}
  function fictionTags(mode){return cached('fiction_tags_'+mode,43200000,function(){var type=mode==='audio'?2:1;return namedRows(tryRows('fiction/other/tagList',{fictionType:type,type:type},['POST','GET'],3200),['fictionTagId','tagId','categoryId','id'],['fictionTagName','tagName','categoryName','name','title']);});}
  function communityCategories(){return cached('community_categories',21600000,function(){return namedRows(tryRows('dynamic/category/tree',{},['GET','POST'],3000),['categoryId','dynamicType','id'],['categoryName','dynamicTypeName','name','title']);});}
  function select(rows,id){id=C.s(id);for(var i=0;i<rows.length;i++)if(C.s(rows[i].id)===id)return rows[i];return rows[0]||null;}
  function list(section,page,state){page=Math.max(1,Number(page||1));state=state||{};var size=C.pageSize(),sort=Number(state.sort||1),rows=[];
    if(section==='featured'||section==='lifan'){var restricted=section==='lifan'?1:0,ss=stations(restricted),st=select(ss,state.station);if(!st)return{filters:{stations:ss},entities:[]};if(page===1&&st.raw&&Array.isArray(st.raw.videoList)&&st.raw.videoList.length)rows=st.raw.videoList.slice(0,size);else rows=tryRows('station/getStationMore',{stationId:C.n(st.id),page:page,pageNum:page,pageSize:size,sortType:sort,restricted:restricted},['GET','POST'],4400);return{filters:{stations:ss,selectedStation:st},entities:rows.map(function(x){return entity('video',x);})};}
    if(section==='anime'||section==='video'){var cs=classes(section),cl=select(cs,state.classId);if(!cl)return{filters:{classes:cs},entities:[]};var ts=tags(cl.id),tg=null;for(var t=0;t<ts.length;t++)if(C.s(ts[t].id)===C.s(state.tagId)){tg=ts[t];break;}var cid=C.n(cl.id);if(tg&&tg.mode==='zone')rows=tryRows('video/queryVideoByZone',{page:page,pageNum:page,pageSize:size,zoneId:C.n(tg.id),classifyId:cid,sortType:sort},['GET','POST'],4200);if(tg&&!rows.length){var name=C.s(tg.name),value=C.s(tg.value||tg.id||name),tries=[{tagsTitle:value,tagTitle:value,videoTagValue:value,classifyId:cid,videoTypeId:cid,page:page,pageNum:page,pageSize:size,limit:size,sortType:sort,restricted:0},{tagsTitle:name,tagTitle:name,videoTagName:name,videoTagValue:value,classifyId:cid,videoTypeId:cid,page:page,pageNum:page,pageSize:size,limit:size,sortType:sort,restricted:0}];for(var ti=0;ti<tries.length&&!rows.length;ti++)rows=tryRows('video/tagTitleList',tries[ti],['GET','POST'],4200);}if(!rows.length)rows=tryRows('video/getByClassify',{classifyId:cid,page:page,pageNum:page,pageSize:size,limit:size,sortType:sort,restricted:0},['GET','POST'],4200);return{filters:{classes:cs,selectedClass:cl,tags:ts,selectedTag:tg},entities:rows.map(function(x){return entity('video',x);})};}
    if(section==='short'){var lt=Number(state.shortType||3);rows=tryRows('video/list',{page:page,pageNum:page,pageSize:size,loadType:lt},['GET','POST'],4400);return{filters:{},entities:rows.map(function(x){return entity('short',x);})};}
    if(section==='comic'){var cst=comicStations(),sel=select(cst,state.station);if(sel&&page===1&&sel.raw&&Array.isArray(sel.raw.comicsBaseList)&&sel.raw.comicsBaseList.length)rows=sel.raw.comicsBaseList.slice(0,size);else if(sel)rows=tryRows('comics/station/getStationComicsMore',{stationId:C.n(sel.id),comicsStationId:C.n(sel.id),page:page,pageNum:page,pageSize:size,sortType:sort},['GET','POST'],4500);if(!rows.length){var cc=comicClasses(),csel=select(cc,state.classId);rows=tryRows('comics/base/findList',{classId:csel?C.n(csel.id):'',page:page,pageNum:page,pageSize:size,sortType:sort},['GET','POST'],4500);return{filters:{stations:cst,selectedStation:sel,classes:cc,selectedClass:csel},entities:rows.map(function(x){return entity('comic',x);})};}return{filters:{stations:cst,selectedStation:sel},entities:rows.map(function(x){return entity('comic',x);})};}
    if(section==='fiction'||section==='audio'){var ft=fictionTags(section),tag=select(ft,state.tagId),fp={page:page,pageNum:page,pageSize:size,limit:size,sortType:sort,fictionType:section==='audio'?2:1};if(tag){fp.tagId=C.n(tag.id);fp.fictionTagId=C.n(tag.id);fp.categoryId=C.n(tag.id);}if(section==='audio')fp.isAudio=1;rows=tryRows('fiction/base/findList',fp,['POST','GET'],4800);return{filters:{tags:ft,selectedTag:tag},entities:rows.map(function(x){return entity(section,x);})};}
    if(section==='community'){var cats=communityCategories(),cat=select(cats,state.categoryId),cp={page:page,pageNum:page,pageSize:size,limit:size};if(cat){cp.categoryId=C.n(cat.id);cp.dynamicType=C.n(cat.id);}rows=tryRows('community/dynamic/list',cp,['GET','POST'],4800);return{filters:{categories:cats,selectedCategory:cat},entities:rows.map(function(x){return entity('community',x);})};}
    if(section==='ai'){rows=tryRows('aiboxNew/square/list',{page:page,pageNum:page,pageSize:size,limit:size,sortType:sort},['GET','POST'],4800);return{filters:{},entities:rows.map(function(x){return entity('ai',x);})};}
    return{filters:{},entities:[]};
  }
  function hotSearch(){var rows=tryRows('search/hot/list',{},['GET','POST'],3400),out=[];for(var i=0;i<rows.length;i++){var x=rows[i]||{},q=C.clean(C.pick(x,['keyword','searchWord','word','title','name'],''));if(q)out.push({title:q,rank:i+1,raw:x});}return out.slice(0,20);}
  function search(kind,q,page){page=Math.max(1,Number(page||1));var size=C.pageSize(),p={page:page,pageNum:page,pageSize:size,limit:size,keyword:q,title:q},rows=[];if(kind==='video'){var tries=[['video/queryVideoByTitle',{page:page,pageNum:page,pageSize:size,title:q,videoType:1}],['search/keyWordV2',{page:page,pageNum:page,pageSize:size,searchWord:q,keyword:q,keyWord:q,searchType:1}],['search/keyWord',{page:page,pageNum:page,pageSize:size,searchWord:q,keyword:q,keyWord:q,searchType:1}]];for(var i=0;i<tries.length&&!rows.length;i++)rows=tryRows(tries[i][0],tries[i][1],['GET','POST'],4400);}else if(kind==='comic'){p.comicsTitle=q;rows=tryRows('comics/base/findList',p,['GET','POST'],4600);}else if(kind==='fiction'||kind==='audio'){p.fictionTitle=q;p.fictionType=kind==='audio'?2:1;if(kind==='audio')p.isAudio=1;rows=tryRows('fiction/base/findList',p,['POST','GET'],4600);}else if(kind==='community'){p.content=q;rows=tryRows('community/dynamic/list',p,['GET','POST'],4600);}else if(kind==='ai'){p.keyword=q;rows=tryRows('aiboxNew/square/list',p,['GET','POST'],4600);}return rows.map(function(x){return entity(kind,x);});}
  function detail(kind,id){id=C.n(id);var tries=[];if(kind==='video'||kind==='short')tries=[['video/getVideoById',{videoId:id}],['video/getVideoById',{id:id}]];else if(kind==='comic')tries=[['comics/base/info',{comicsId:id}],['comics/base/info',{comicId:id}]];else if(kind==='fiction'||kind==='audio')tries=[['fiction/base/info',{fictionId:id}],['fiction/base/info',{bookId:id}]];else if(kind==='community')tries=[['community/dynamic/dynamicInfo',{dynamicId:id}],['community/dynamic/dynamicInfo',{id:id}]];else if(kind==='ai')tries=[['aiboxNew/square/detail',{worksId:id}],['aiboxNew/square/detail',{id:id}]];for(var i=0;i<tries.length;i++){var x=tryData(tries[i][0],tries[i][1],['GET','POST'],4800);if(x)return x;}return{};}
  function recommend(kind,id){id=C.n(id);var rows=[];if(kind==='video'||kind==='short'){var tries=[['video/guessLike',{videoId:id,page:1,pageSize:12}],['video/dataCenterMaybeLike',{videoId:id,page:1,pageSize:12}]];for(var i=0;i<tries.length&&!rows.length;i++)rows=tryRows(tries[i][0],tries[i][1],['GET','POST'],4000);return rows.map(function(x){return entity('video',x);});}if(kind==='comic'){rows=tryRows('comics/base/getRec',{comicsId:id,page:1,pageSize:12},['GET','POST'],4200);return rows.map(function(x){return entity('comic',x);});}return[];}
  function chapters(kind,root){root=root||{};var a=C.arr(C.deep(root,['chapterList','chapters'],0)),out=[];if(root.chapterList&&Array.isArray(root.chapterList))a=root.chapterList;for(var i=0;i<a.length;i++){var x=a[i]||{},id=C.pick(x,['chapterId','fictionChapterId','id'],''),title=C.pick(x,['chapterTitle','chapterName','title','name'],'第'+(i+1)+(kind==='comic'?'话':'章'));if(id)out.push({id:C.s(id),title:C.clean(title),index:i+1,raw:x});}return out;}
  function chapter(kind,parentId,chapterId){if(kind==='comic')return tryData('comics/base/chapterInfo',{chapterId:C.n(chapterId)},['GET','POST'],5000)||{};return tryData('fiction/base/chapterInfo',{fictionId:C.n(parentId),chapterId:C.n(chapterId)},['POST','GET'],5000)||tryData('fiction/base/chapterInfo',{chapterId:C.n(chapterId)},['POST','GET'],5000)||{};}
  function comicImages(root){root=root||{};var domain=C.s(C.pick(root,['domain','imgDomain'],'')||''),a=Array.isArray(root.imgList)?root.imgList:[],out=[];for(var i=0;i<a.length;i++){var u=C.s(a[i]).trim();if(u)out.push({url:u,domain:domain});}return out;}
  function fictionPayload(root){var texts=[],audios=[],images=[],seenT={},seenA={},seenI={},count=0,base=C.s(C.deep(root||{},['playbackDomain','audioDomain','mediaDomain'],0)||''),auth=C.s(C.deep(root||{},['playbackAuthKey','authKey','auth_key'],0)||'');function add(a,sn,v){v=C.s(v).trim();if(v&&!sn[v]){sn[v]=1;a.push(v);}}function join(b,p){p=C.s(p).trim();if(!p)return'';if(p.indexOf('//')===0)return'https:'+p;if(/^https?:\/\//i.test(p))return p;if(b&&/^https?:\/\//i.test(b))return b.replace(/\/+$/,'')+'/'+p.replace(/^\/+/, '');return p;}function walk(v,key,d){if(v===undefined||v===null||d>11||count>16000)return;if(typeof v==='string'){var z=v.trim(),low=C.s(key).toLowerCase();if(/content|text|body|paragraph/.test(low)&&z&&!/^https?:\/\//i.test(z)&&z.length>1)add(texts,seenT,z);if(/audio|sourcepath|playpath|audiourl|mediaurl/.test(low)||/\.(?:mp3|m4a|aac|wav|ogg|flac|m3u8)(?:[?#]|$)/i.test(z)){var u=join(base,z);if(auth&&u&&u.indexOf('auth_key=')<0&&u.indexOf('authKey=')<0)u+=(u.indexOf('?')>=0?'&':'?')+'auth_key='+encodeURIComponent(auth);add(audios,seenA,u);}if(/image|img|picture|pic/.test(low)&&(/^(https?:)?\/\//i.test(z)||/\.(?:png|jpe?g|webp|gif)(?:[?#]|$)/i.test(z)))add(images,seenI,z);return;}if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],key,d+1);return;}if(typeof v!=='object')return;count++;for(var k in v)walk(v[k],k,d+1);}walk(root,'',0);return{texts:texts,audios:audios,images:images};}
  function comments(kind,id,page,sort){var p={page:page,pageNum:page,pageSize:20,sortType:sort==='new'?'new':'hot'},path='';if(kind==='video'||kind==='short'){path='video/commentList';p.videoId=C.n(id);}else if(kind==='comic'){path='comics/comment/commentList';p.comicsId=C.n(id);}else if(kind==='fiction'||kind==='audio'){path='fiction/commentList';p.fictionId=C.n(id);}else if(kind==='community'){path='community/dynamic/commentList';p.dynamicId=C.n(id);}else if(kind==='ai'){path='aiboxNew/square/commentList';p.worksId=C.n(id);}return tryRows(path,p,['GET','POST'],4600);}
  function snapshot(section){var r=list(section,1,{sort:1,shortType:3}),a=[];for(var i=0;i<r.entities.length&&i<5;i++)a.push({id:r.entities[i].id,title:r.entities[i].title,img:r.entities[i].img,kind:r.entities[i].kind});return{section:section,apiHost:getItem(C.K.apiHost,''),imgDomain:getItem(C.K.imgDomain,''),filters:r.filters||{},samples:a,lastDiag:C.getDiag()};}
  return{channels:CHANNELS,channel:channel,cover:cover,mediaPath:mediaPath,author:author,entity:entity,stations:stations,classes:classes,tags:tags,comicStations:comicStations,comicClasses:comicClasses,fictionTags:fictionTags,communityCategories:communityCategories,list:list,hotSearch:hotSearch,search:search,detail:detail,recommend:recommend,chapters:chapters,chapter:chapter,comicImages:comicImages,fictionPayload:fictionPayload,comments:comments,snapshot:snapshot};
})();
