/* 我的规则仓库 v3.5.0-rc10 - resilient premium version center */
(function(R){
R.ruleRepoChannelFallback=function(){var icon='https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/apps/tools/rule-repo/assets/icon.svg';return{schema:3,id:'rule-repo',name:'我的规则仓库',updatedAt:'2026-08-20',channels:[{channel:'stable',label:'正式版',id:'rule-repo',name:'我的规则仓库',version:'3.5.1',build:360,displayVersion:'Stable 3.5.1 · Shell 1.5.1',path:'apps/tools/rule-repo/rule_repo_remote_v351.txt',mode:'remote',updatedAt:'2026-08-20',recommended:true,desc:'稳定日常使用 · 同时承担测试版恢复入口',highlights:['实机验证通过','安全同步与多镜像','测试版异常可从这里恢复'],icon:icon},{channel:'test',label:'测试版',id:'rule-repo-test',name:'我的规则仓库·测试版',version:'3.5.0-rc10',build:361,displayVersion:'Candidate 3.5.0-rc10 · Shell 1.0.9',path:'apps/tools/rule-repo/rule_repo_test_v109.txt',mode:'remote',updatedAt:'2026-08-20',recommended:false,desc:'新界面与交互优先验证',highlights:['双版本页重构','首页进一步降噪','安全更新中心','版本页离线兜底'],icon:icon}]};};
R.channelMeta=function(parent){var path=String(parent&&parent.channelsPath||parent&&parent.raw&&parent.raw.channelsPath||''),key=this.statePrefix+'channel_meta_'+String(parent&&parent.id||'default');if(path){try{var x=JSON.parse(this.apiText(path));if(x&&Array.isArray(x.channels)&&x.channels.length){setItem(key,JSON.stringify(x));return x;}}catch(e){}}try{var cached=JSON.parse(String(getItem(key,'')||''));if(cached&&Array.isArray(cached.channels)&&cached.channels.length)return cached;}catch(e){}if(String(parent&&parent.id||'')==='rule-repo')return this.ruleRepoChannelFallback();return null;};
R.channelPage=function(parent){
setPageTitle(parent.name);var d=[],meta=this.channelMeta(parent),self=this;if(!meta){setResult([{title:'版本信息暂时不可用',desc:'云端版本信息暂时无法读取，请稍后重试。',url:'hiker://page/ruleRepoHome?rule=&simple=true',col_type:'text_center_1',extra:{lineVisible:false}}]);return;}try{setPagePicUrl(this.iconOf(parent));}catch(e){}
var cs=meta.channels||[],stable=null,test=null;for(var i=0;i<cs.length;i++){if(cs[i].channel==='stable')stable=cs[i];if(cs[i].channel==='test')test=cs[i];}
d.push(this.hero(parent.name,'正式版负责日常与恢复 · 测试版负责新功能验证\n选择版本即可直接导入',this.iconOf(parent),'hiker://empty'));
this.pushSection(d,'选择版本','当前运行：'+(this.isTestChannel()?'测试版 '+this.version:'正式版 '+this.version));
if(stable)this.pushChannelCard(d,parent,stable,true);if(test)this.pushChannelCard(d,parent,test,false);
this.pushSpacer(d);d.push(this.compactInfo('恢复机制',this.isTestChannel()?'如果测试版以后异常，直接打开正式版 → 我的规则仓库 → 点击“测试版”重新覆盖导入。':'如果测试版异常，在这里点击“测试版”即可重新覆盖安装；正式版会始终保留。','hiker://empty'));
setResult(d);
};
R.pushChannelCard=function(d,parent,c,recommended){var self=this,current=(recommended&&!self.isTestChannel())||(!recommended&&self.isTestChannel()),raw={id:String(c.id||''),name:String(c.name||parent.name||''),version:String(c.version||''),desc:String(c.desc||''),path:String(c.path||''),category:parent.category,categoryName:parent.categoryName,subCategory:parent.subCategory,tags:['远程',recommended?'正式':'测试','版本'],mode:String(c.mode||'remote'),updatedAt:String(c.updatedAt||''),icon:String(c.icon||self.iconOf(parent)),openTitle:String(c.name||parent.name||'')},title=(recommended?'正式版 · 推荐':'测试版 · 抢先体验')+(current?' · 当前运行':'');d.push({title:title,desc:String(c.displayVersion||c.version||'')+'\n'+String(c.desc||'')+' · 点击导入',img:String(c.icon||self.iconOf(parent)),pic_url:String(c.icon||self.iconOf(parent)),url:$('#noLoading#').lazyRule(function(x){return $.require('hiker://page/ruleRepoCore').importRule(x);},JSON.stringify(raw)),col_type:'icon_1_left_pic',extra:{lineVisible:false}});};
})(HikerRuleRepo);
