/* Hanime1 2.0.0-test.7 - public library / my / login / previews / comments UI */
(function(C,P,E){
var BUILD='2.0.0-test.7';
function dec(v){v=String(v==null?'':v);for(var i=0;i<2;i++){try{var n=decodeURIComponent(v);if(n===v)break;v=n;}catch(e){break;}}return v;}
function pv(k,d){try{var x=getParam(k);if(x!==undefined&&x!==null&&String(x)!=='')return dec(x);}catch(e){}try{if(MY_PARAMS&&MY_PARAMS[k]!==undefined)return dec(MY_PARAMS[k]);}catch(y){}return d||'';}
function route(p,o){var q=[];Object.keys(o||{}).forEach(function(k){if(o[k]!==undefined&&o[k]!==null&&String(o[k])!=='')q.push(encodeURIComponent(k)+'='+encodeURIComponent(String(o[k])));});return 'hiker://page/'+p+'?rule=&simple=true'+(q.length?'&'+q.join('&'):'');}
function sec(t,d){return {title:t,desc:d||'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}};}
function btn(t,u,c){return {title:t,url:u,col_type:c||'text_3',extra:{lineVisible:false}};}
function vin(x,c){return {title:x.title||'未命名',desc:[x.duration,x.views,x.rating,x.artist,x.upload].filter(Boolean).join(' · '),pic_url:x.img||x.cover||'',url:route('hanimeDetail',{id:x.id,title:x.title}),col_type:c||'movie_3',extra:{lineVisible:false}};}
function tab(d,t,id,cur){d.push({title:(cur===id?'● ':'')+t,url:$('#noLoading#').lazyRule(function(v){putMyVar('hanime2_tab',v);refreshPage(false);return 'hiker://empty';},id),col_type:'scroll_button'});}
function choice(d,t,key,val,cur){d.push({title:(String(cur)===String(val)?'● ':'')+t,url:$('#noLoading#').lazyRule(function(k,v){putMyVar(k,v);refreshPage(false);return 'hiker://empty';},key,val),col_type:'scroll_button'});}
function hasLogin(){try{return !!P.profile();}catch(e){return false;}}
E.home=function(){try{setPageTitle('Hanime1 · Test');var d=[],page=Number(MY_PAGE||1),cur=getMyVar('hanime2_tab','explore');if(page===1){d.push({title:'搜索视频 / 作者',url:route('hanimeSearch',{}),col_type:'input',extra:{titleVisible:false,lineVisible:false}});tab(d,'探索','explore',cur);tab(d,'片库','library',cur);tab(d,'我的','my',cur);tab(d,'设置','settings',cur);d.push({col_type:'line_blank'});}if(cur==='explore')E.renderExplore(d);else if(cur==='library')E.renderLibrary(d,page);else if(cur==='my')E.renderMy(d);else E.renderSettings(d);setResult(d);}catch(x){setResult([{title:'Hanime1 加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.renderLibrary=function(d,page){page=Number(page||1);var sort=getMyVar('hanime2_lib_sort','upload_date'),genre=getMyVar('hanime2_lib_genre','');if(page===1){d.push(sec('公开片库','无需登录，直接浏览 Hanime1 官网公开影片。个人稍后看/收藏/片单已移动到“我的”。'));for(var i=0;i<P.librarySorts.length;i++)choice(d,P.librarySorts[i][0],'hanime2_lib_sort',P.librarySorts[i][1],sort);d.push({col_type:'line_blank'});var gs=P.filters&&P.filters.genres?P.filters.genres:[];for(var g=0;g<gs.length;g++)choice(d,gs[g][0],'hanime2_lib_genre',gs[g][1],genre);d.push({col_type:'line_blank'});}var r=P.publicLibrary({sort:sort,genre:genre,page:page}),list=r.items||[];for(var k=0;k<list.length;k++)d.push(vin(list[k],'movie_3'));if(!list.length)d.push(sec('暂无结果','当前筛选没有解析到影片。'));};
E.renderMy=function(d){var p=null;try{p=P.profile();}catch(e){}if(!p){d.push(sec('我的','稍后看、收藏、片单、订阅和观看历史属于 Hanime1 账号数据，因此这些栏目本身必须登录；公开浏览请使用“片库”。'));d.push(btn('官网登录',route('hanimeLogin',{}),'text_center_1'));return;}d.push(sec('我的 · '+p.name,p.email||('账号 ID '+p.id)));var tabs=[['稍后看','watchLater'],['收藏','favorites'],['片单','playlists'],['订阅','subscriptions'],['历史','history']],cur=getMyVar('hanime2_libtab','watchLater');for(var i=0;i<tabs.length;i++)choice(d,tabs[i][0],'hanime2_libtab',tabs[i][1],cur);var r=P.librarySection(cur),list=r.items||[];if(cur==='playlists'){for(var j=0;j<list.length;j++)d.push({title:list[j].title,desc:list[j].count||'',pic_url:list[j].img||'',url:route('hanimePlaylist',{id:list[j].id}),col_type:'movie_1_left_pic',extra:{lineVisible:false}});}else for(var k=0;k<list.length;k++)d.push(vin(list[k],'movie_3'));if(!list.length)d.push(sec('暂无内容','官网当前栏目为空，或登录状态已经失效。'));};
E.loginPage=function(){try{C.useBrowserSession();var base=C.resolveHost(false),d=[],cookie='';try{cookie=C.withoutClearance(C.browserCookie(base));}catch(e){}setPageTitle('登录 Hanime1');d.push(sec('官网登录','登录使用独立全屏 X5，避免复杂表单塞在 x5_webview_single 中导致交互异常。登录成功返回本页后，再点“检测登录状态 / 保存账号”。'));d.push(btn('① 打开独立官网登录','x5://'+base+'/login','text_center_1'));d.push(btn('② 检测登录状态',$('#noLoading#').lazyRule(function(){try{$.require('hanime').core().useBrowserSession();var p=$.require('hanime').provider().profile();return 'toast://已登录 '+p.name;}catch(e){return 'toast://未识别账号：'+String(e.message||e);}}),'text_center_1'));d.push(btn('③ 保存为多账号',$('#noLoading#').lazyRule(function(){try{$.require('hanime').core().useBrowserSession();var a=$.require('hanime').provider().syncBrowserAccount();return 'toast://已保存 '+a.name;}catch(e){return 'toast://'+String(e.message||e);}}),'text_center_1'));d.push(sec('Cookie 状态',cookie?'已检测到账号 Cookie，可尝试第②步。':'当前只有匿名/验证 Cookie，尚未识别账号登录。'));d.push(btn('官网注册','x5://'+base+'/register'));setResult(d);}catch(x){setResult([{title:'登录页失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
function fmtMonth(v){v=String(v||'').replace(/[^0-9]/g,'');if(v.length<6){var n=new Date(),m=String(n.getMonth()+1);if(m.length<2)m='0'+m;v=String(n.getFullYear())+m;}return v.slice(0,4)+'-'+v.slice(4,6);}
function shiftMonth(v,step){v=String(v||'').replace(/[^0-9]/g,'');if(v.length<6)return fmtMonth(v);var y=parseInt(v.slice(0,4),10),m=parseInt(v.slice(4,6),10)-1+step,n=new Date(y,m,1),mm=String(n.getMonth()+1);if(mm.length<2)mm='0'+mm;return n.getFullYear()+'-'+mm;}
E.previews=function(){try{setPageTitle('新番预告');var raw=pv('month',''),m=fmtMonth(raw),d=[];d.push(btn('‹ '+shiftMonth(m,-1),route('hanimePreviews',{month:shiftMonth(m,-1)})));d.push(btn('月份 · '+m,'hiker://empty'));var now=new Date(),cm=now.getFullYear()+'-'+String(now.getMonth()+1).replace(/^(\d)$/,'0$1');if(m<cm)d.push(btn(shiftMonth(m,1)+' ›',route('hanimePreviews',{month:shiftMonth(m,1)})));else d.push(btn('当前月','hiker://empty'));var a=P.previews(m);for(var i=0;i<a.length;i++){var it=a[i],u=/^\d+$/.test(String(it.id||''))?route('hanimeDetail',{id:it.id,title:it.title}):'hiker://empty';d.push({title:it.title,desc:[it.brand,it.desc].filter(Boolean).join('\n'),pic_url:it.img,url:u,col_type:'movie_1_left_pic',extra:{lineVisible:false}});}if(!a.length){d.push(sec('本月暂无可解析预告','已使用官网要求的 YYYYMM 请求格式。'));d.push(btn('打开官网预告','x5://'+C.resolveHost(false)+'/previews/'+P.previewMonth(m),'text_center_1'));}setResult(d);}catch(x){setResult([{title:'预告加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.commentsPage=function(){try{var id=pv('id',''),t=pv('title','视频'),r=P.comments(id),d=[],logged=hasLogin();setPageTitle('评论');d.push(sec(t,'已加载 '+r.items.length+' 条评论'));d.push(btn(logged?'发表评论':'登录后发表评论',logged?('input://'+JSON.stringify({value:'',hint:'输入评论内容',js:"if(!input)return 'toast://评论不能为空';try{$.require('hanime').provider().postComment('"+id+"',input);refreshPage(false);return 'toast://评论已发布';}catch(e){return 'toast://'+String(e.message||e);}"})):route('hanimeLogin',{}),'text_center_1'));for(var i=0;i<r.items.length;i++){var c=r.items[i],tail=[c.time,c.replyCount?c.replyCount+' 回复':''].filter(Boolean).join(' · ');d.push({title:c.user+(c.replyCount?'  ·  '+c.replyCount+'回复':''),desc:c.content+(tail?'\n'+tail:''),pic_url:c.avatar||'',url:c.id?route('hanimeReplies',{id:c.id,user:c.user}):'hiker://empty',col_type:'movie_1_left_pic',extra:{lineVisible:false}});}if(!r.items.length)d.push(sec('暂无评论'));setResult(d);}catch(x){setResult([{title:'评论加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.repliesPage=function(){try{var id=pv('id',''),u=pv('user','回复'),a=P.replies(id),d=[],logged=hasLogin();setPageTitle(u+' · 回复');d.push(btn(logged?'回复此评论':'登录后回复',logged?('input://'+JSON.stringify({value:'',hint:'输入回复内容',js:"if(!input)return 'toast://回复不能为空';try{$.require('hanime').provider().replyComment('"+id+"',input);refreshPage(false);return 'toast://回复已发布';}catch(e){return 'toast://'+String(e.message||e);}"})):route('hanimeLogin',{}),'text_center_1'));for(var i=0;i<a.length;i++)d.push({title:a[i].user,desc:a[i].content+(a[i].time?'\n'+a[i].time:''),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});if(!a.length)d.push(sec('暂无回复'));setResult(d);}catch(x){setResult([{title:'回复加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
E.renderSettings=function(d){var base=C.resolveHost(false);d.push(sec('会话','Cloudflare/登录只交给 WebView；验证后业务继续直接请求官网。'));d.push(btn('检查视频站会话',$('#noLoading#').lazyRule(function(u){try{var r=$.require('hanime').core().ensureSession(u);return 'toast://'+(r.ok?'视频站可直连':'仍需验证');}catch(e){return 'toast://'+String(e.message||e);}},base+'/')));d.push(btn('视频站验证',route('hanimeVerify',{url:base})));d.push(btn('官网登录',route('hanimeLogin',{})));d.push(btn('账号中心',route('hanimeAccount',{})));d.push(sec('本地工具'));d.push(btn('下载中心','hiker://download'));d.push(btn('本规则历史','hiker://history'));d.push(sec('测试版本','2.0.0-test.7 · Build 20007'));d.push(btn('检查远程更新',$('#noLoading#').lazyRule(function(){try{var r=HanimeBoot.check();return 'toast://'+(r.hasUpdate?'发现 '+r.latest.version:'当前已是最新测试版');}catch(e){return 'toast://'+String(e.message||e);}})));};
E.build=BUILD;P.build=BUILD;C.build=BUILD;
})(HanimeCore,HanimeProvider,HanimePages);
