/* PikPak Test19 Build10121 - paged cloud search and multi-account page */
(function(C,P,UI,Pages){
    var HANDOFF='pikpak_web_handoff_v15';
    function page(){try{return Number(MY_PAGE||1)||1;}catch(e){return 1;}}
    function raw(k,d){try{return getParam(k,d==null?'':String(d));}catch(e){return d==null?'':String(d);}}
    function param(k,d){var v=String(raw(k,d)||'');try{return decodeURIComponent(v);}catch(e){return v;}}
    function title(v){try{setPageTitle(String(v||''));}catch(e){}}
    function payload(){var s='';try{s=String(getVar(HANDOFF,'')||'');}catch(e){}try{return s?JSON.parse(s):null;}catch(e2){return null;}}
    function image(f){var m=String(f&&f.mime_type||'').toLowerCase(),n=String(f&&f.name||'').toLowerCase();return m.indexOf('image')>=0||/\.(jpg|jpeg|png|gif|webp|bmp|avif|heic)(\?|$)/i.test(n);}
    function matches(f,q,type){if(String(f&&f.name||'').toLowerCase().indexOf(q.toLowerCase())<0)return false;if(type==='video')return P.isVideo(f);if(type==='folder')return P.isFolder(f);if(type==='image')return image(f);return true;}
    function fileUrl(f){if(P.isFolder(f))return UI.route('pikpakDrive',{parent_id:f.id||'',name:f.name||'文件夹'});return $("#noLoading#").lazyRule(function(x){return $.require('pikpak').playPersonal(x.id,x.mime,false);},{id:String(f.id||''),mime:String(f.mime_type||'')});}
    function tokenKey(q,type,n){return 'pikpak_v19_search_'+md5(q+'|'+type)+'_'+n;}
    function searchTypeName(v){return v==='video'?'视频':v==='folder'?'文件夹':v==='image'?'图片':'全部';}
    Pages.cloudSearch=function(opt){opt=opt||{};var q=String(opt.q!=null?opt.q:param('q','')).trim(),type=String(opt.type||param('type','all')),n=opt.external?1:page(),d=[];if(!opt.external){title('云盘搜索');if(n===1){d.push({title:q,desc:'输入文件名搜索整个个人网盘',url:$.toString(function(){return $.require('pikpak').searchRoute(input);}),col_type:'input',extra:{inheritTitle:false}});var types=[['全部','all'],['视频','video'],['图片','image'],['文件夹','folder']];for(var z=0;z<types.length;z++)d.push({title:(type===types[z][1]?'● ':'')+types[z][0],url:UI.route('pikpakSearch',{q:q,type:types[z][1]}),col_type:'scroll_button'});}}
        if(!C.loggedIn()){d.push(UI.error('搜索个人网盘前请先登录 PikPak'));setResult(d);return;}if(!q){d.push(UI.empty('输入文件名关键词开始搜索'));setResult(d);return;}
        var tok='';if(n>1){try{tok=getMyVar(tokenKey(q,type,n),'');}catch(e){}if(!tok){setResult(d);return;}}var r=P.listAll(tok,200,'MODIFY_TIME_DESC');if(!r||r.error||r.error_code){d.push(UI.error('搜索失败：'+C.errorText(r)));setResult(d);return;}if(!opt.external)try{putMyVar(tokenKey(q,type,n+1),String(r.next_page_token||''));}catch(e2){}var a=r.files instanceof Array?r.files:[],count=0;for(var i=0;i<a.length;i++)if(matches(a[i],q,type)){d.push(UI.fileCard(a[i],fileUrl(a[i])));count++;}if(!count)d.push(UI.empty((n===1?'当前批次':'这一页')+'没有匹配“'+q+'”的'+searchTypeName(type)));if(!opt.external&&n===1)d.splice(types.length+1,0,{title:'搜索“'+q+'”',desc:'全盘分页检索 · 每页扫描 '+a.length+' 个项目 · 向下翻页继续',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});setResult(d);};
    Pages.account=function(){var d=[],a=C.accounts?C.accounts():[],cur=C.currentAccountId?C.currentAccountId():'',cap=payload();title('PikPak 多账号');if(cap&&(cap.access_token||cap.refresh_token))d.push({title:'✅ 发现新的网页登录会话',desc:'点此接入并保存为另一个本机账号',url:UI.route('pikpakWebDone',{bridge:'v15'}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:C.loggedIn()?'Web Session 已连接':'当前未启用账号',desc:C.loggedIn()?'已保存 '+a.length+' 个本机会话；点击下方账号即可切换':'可切换已保存账号，或添加新的官方网页登录会话',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'＋ 添加账号',url:UI.route('pikpakWebLogin'),col_type:'scroll_button'});if(C.loggedIn())d.push({title:'刷新当前会话',url:$("#noLoading#").lazyRule(function(){return $.require('pikpak').refreshSessionAction();}),col_type:'scroll_button'});for(var i=0;i<a.length;i++){var x=a[i],active=x.id===cur,label=String(x.label||('PikPak 账号 '+(i+1)));d.push({title:(active?'✓ ':'')+label,desc:(active?'当前账号 · ':'点击切换 · ')+'官方 Web Session\n本机保存：'+C.formatDate(x.savedAt||''),url:active?'hiker://empty':$("#noLoading#").lazyRule(function(id){return $.require('pikpak').switchAccountAction(id);},String(x.id||'')),col_type:'text_1',extra:{lineVisible:false,longClick:[{title:'重命名账号',js:$.toString(function(v){return $.require('pikpak').renameAccountPrompt(v.id,v.label);},{id:String(x.id||''),label:label})},{title:'移除本机账号',js:$.toString(function(id){return $.require('pikpak').removeAccountPrompt(id);},String(x.id||''))}]}});}if(!a.length)d.push(UI.empty('还没有保存的账号，请使用“添加账号”完成官方网页登录'));d.push({title:'多账号说明',desc:'切换只使用本机已保存的 Web Session，不触发账号密码登录。添加其他账号时，请先在官方网页切换到目标账号。移除只清除本小程序的本地会话，不会删除 PikPak 账号或云盘文件。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});setResult(d);};
    Pages.settings=function(){var d=[];title('PikPak 设置');var sort=C.item('sort','name_asc'),filter=C.item('drive_filter','all'),auto=C.item('handoff_auto_trash','on')!=='off',count=C.accounts?C.accounts().length:0;d.push({title:'账号与 Session',desc:(C.loggedIn()?'当前已连接':'当前未连接')+' · 本机保存 '+count+' 个账号',url:UI.route('pikpakAccount'),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'云盘搜索',desc:'按文件名全盘分页搜索，并可筛选视频、图片和文件夹',url:UI.route('pikpakSearch'),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'跨小程序 Magnet 退出自动回收',desc:auto?'已开启：关闭调用页后，本次临时播放文件移入回收站':'已关闭：退出后保留 My Pack 中的播放文件',url:$(['开启','关闭']).select(function(){return $.require('pikpak').setHandoffCleanupAction(input);}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'目录筛选',desc:filter==='video'?'仅视频':filter==='folder'?'仅文件夹':'全部',url:$(['全部','仅视频','仅文件夹']).select(function(){return $.require('pikpak').setDriveFilterAction(input);}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'文件排序',desc:sort==='time_desc'?'最近修改':sort==='size_desc'?'文件大小':sort==='name_desc'?'名称倒序':'名称正序',url:$(['名称正序','名称倒序','最近修改','文件大小']).select(function(){return $.require('pikpak').setSortAction(input);}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'星标文件',url:UI.route('pikpakStarred'),col_type:'scroll_button'});d.push({title:'回收站',url:UI.route('pikpakRecycle'),col_type:'scroll_button'});d.push({title:'清理当前账号临时文件',desc:'只把当前账号下由本程序登记的临时对象移入回收站',url:'confirm://确定清理当前账号的临时播放文件？.js:'+$.toString(function(){return $.require('pikpak').cleanupTempAction();}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行信息',desc:'Test19 · Build 10121\n云盘搜索：全盘分页 + 类型筛选\n多账号：本机 Web Session 保存与切换\n临时清理：按账号隔离',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});setResult(d);};
})(PikPakCore,PikPakProvider,PikPakUI,PikPakPages);
