/* 色花堂 0.1.0-test.22 / Build 10122 - guide preview DOM extraction */
var SeHuaTangPatchTest22=(function(){
var BASE=SeHuaTangRemoteRuntime,C=SeHuaTangV16Core;
var KEY_COOKIE='sht_web_cookie_v5',KEY_ACCESS='sht_access_ok_v7';
function s(v){return v==null?'':String(v)}
function trim(v){return C.trim(v)}
function hdec(v){var x=s(v),i;for(i=0;i<2;i++)x=x.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;/gi,' ');return x}
function guideUrl(mode,p){var view=mode==='latest'?'newthread':(mode==='digest'?'digest':'hot');return C.origin()+'/forum.php?mod=guide&view='+view+'&mobile=2&page='+Math.max(1,Number(p||1))}
function pageKey(mode){return'sht_guide_page_v22_'+mode}
function pbtn(t,key,p,on){return{title:t,url:on?$('#noLoading#').lazyRule(function(k,v){putMyVar(k,String(v));refreshPage(false);return'hiker://empty';},key,p):'hiker://empty',col_type:'text_3',extra:{lineVisible:false}}}
function goodTitle(t){t=trim(t);return !!t&&t.length>=4&&t.length<=180&&!/本帖最后由.+编辑|^(查看帖子|查看|回复|最后发表|最后回复|上一页|下一页|返回|首页|论坛|社区版块|搜索|发帖|更多)$/i.test(t)&&!/^\d+$/.test(t)}
function absImg(u,base,attrs){u=hdec(trim(u)).replace(/^['"]|['"]$/g,'');if(!u)return'';return C.validImage(u,base,attrs||'')||''}
function attr(a,n){return C.attrVal(a,n)||''}
function resolvedFromTag(tag,base){var a=s(tag),names=['data-sht-resolved-src','data-sht-bg','src','data-original','data-src','data-lazy-src','data-echo','data-url','data-actual','data-cfsrc','file','zoomfile'],i,u,ss,st;for(i=0;i<names.length;i++){u=absImg(attr(a,names[i]),base,a);if(u)return u}ss=attr(a,'srcset');if(ss){u=absImg(trim(ss.split(',')[0].split(/\s+/)[0]),base,a);if(u)return u}st=a.match(/(?:background(?:-image)?\s*:\s*url\(|data-sht-bg\s*=\s*["'])(?:["']?)([^)"']+)/i);if(st){u=absImg(st[1],base,a);if(u)return u}return''}
function previewImages(ctx,base,max){var x=s(ctx),out=[],seen={},m,u,re=/<img\b[^>]*>/gi,any=/<[^>]+>/gi,raw=/https?:\/\/[^\s"'<>]+?\.(?:jpe?g|png|webp)(?:\?[^\s"'<>]*)?/ig;function add(v,a){v=absImg(v,base,a);if(!v)return;var k=C.canonical(v);if(!seen[k]){seen[k]=1;out.push(v)}}while((m=re.exec(x))!==null){u=resolvedFromTag(m[0],base);if(u)add(u,m[0]);if(out.length>=max)return out}while((m=any.exec(x))!==null){var tag=m[0];u=attr(tag,'data-sht-bg')||attr(tag,'data-sht-resolved-src')||attr(tag,'data-original')||attr(tag,'data-src')||attr(tag,'data-lazy-src')||attr(tag,'data-url')||attr(tag,'file')||attr(tag,'zoomfile');if(u)add(u,tag);var bg=tag.match(/background(?:-image)?\s*:\s*url\((?:["']?)([^)"']+)/i);if(bg)add(bg[1],tag);if(out.length>=max)return out}while((m=raw.exec(hdec(x)))!==null){add(m[0],'');if(out.length>=max)return out}return out}
function renderGuide(u){try{return s(fetchCodeByWebView(u,{headers:C.headers(false,u),timeout:28000,blockRules:['.woff','.woff2','.ttf'],checkJs:$.toString(function(ck,ak){var t=String((document.body&&document.body.innerText)||'');function age(x){return /满\s*18\s*岁|年满\s*18|over\s*18|18\s*years|please\s*click\s*here/i.test(x)}function save(){try{var c=fba.getCookie(location.origin)||'';if(c)fba.putVar(ck,c);fba.putVar(ak,'1')}catch(e){}}function clickAge(){var n=document.querySelectorAll('a,button,input,[onclick],[role="button"],div');for(var i=0;i<n.length;i++){var z=String(n[i].innerText||n[i].textContent||n[i].value||'');if(/满\s*18\s*岁|over\s*18|please\s*click\s*here/i.test(z)){try{n[i].click();return true}catch(e){}}}return false}if(age(t)){clickAge();return null}save();var im=document.querySelectorAll('img');for(var j=0;j<im.length;j++){var q=im[j],src=String(q.currentSrc||q.src||q.getAttribute('src')||q.getAttribute('data-original')||q.getAttribute('data-src')||q.getAttribute('data-lazy-src')||q.getAttribute('file')||q.getAttribute('zoomfile')||'');if(src)try{q.setAttribute('data-sht-resolved-src',src)}catch(e2){}}var ns=document.querySelectorAll('*');for(var k=0;k<ns.length;k++){var el=ns[k];try{var bg=String((window.getComputedStyle?getComputedStyle(el).backgroundImage:'')||'');var mm=bg.match(/url\(["']?(.*?)["']?\)/i);if(mm&&mm[1]&&!/^data:/i.test(mm[1]))el.setAttribute('data-sht-bg',mm[1])}catch(e3){}}if(!document.querySelector('a[href*="tid="],a[href*="thread-"]'))return null;window.__shtGuideV22=(window.__shtGuideV22||0)+1;if(window.__shtGuideV22===1){window.scrollTo(0,Math.floor(document.body.scrollHeight*0.45));return null}if(window.__shtGuideV22===2){window.scrollTo(0,Math.floor(document.body.scrollHeight*0.82));return null}if(window.__shtGuideV22===3){window.scrollTo(0,document.body.scrollHeight);return null}return'ready';},KEY_COOKIE,KEY_ACCESS)}))}catch(e){return''}}
function anchors(html,base){var out=[],re=/<a\b([^>]*?)href\s*=\s*(?:["']([^"']+)["']|([^\s>]+))([^>]*)>([\s\S]*?)<\/a>/gi,m,t,u;while((m=re.exec(s(html)))!==null){u=C.abs(m[2]||m[3]||'',base);t=trim(C.strip(m[5]||''));out.push({href:u,text:t,index:m.index,inner:m[5]||'',attrs:(m[1]||'')+' '+(m[4]||'')});if(out.length>20000)break}return out}
function scoreTitle(t){if(!goodTitle(t))return-999;var n=Math.min(t.length,150)+(t.length>=10?30:0);if(/[【\[].+[】\]]|原创|写真|无码|有码|预览|FC2|IPX|ROE|SSIS|章节|字\)/i.test(t))n+=16;if(t.length>150)n-=20;return n}
function metaFrom(ctx,base){var as=anchors(ctx,base),i,a,author='',avatar='',time='',tag='',txt=C.strip(ctx),tm;for(i=0;i<as.length;i++){a=as[i];if(!author&&/home\.php\?mod=space.*uid=|space-uid-|[?&]uid=\d+/i.test(a.href)&&a.text&&a.text.length<32)author=a.text}var im=/<img\b[^>]*(?:avatar|uc_server|ucenter|space-uid|home\.php\?mod=space)[^>]*>/ig.exec(ctx);if(im){avatar=attr(im[0],'src')||attr(im[0],'data-src')||attr(im[0],'data-original')||'';avatar=C.abs(avatar,base)}tm=txt.match(/(\d+\s*(?:分钟|小时|天)前(?:发布)?|前天\s*\d{1,2}:\d{2}|昨天\s*\d{1,2}:\d{2}|\d{4}-\d{1,2}-\d{1,2}(?:\s+\d{1,2}:\d{2})?)/);if(tm)time=tm[1];tm=txt.match(/#([^#]{2,20})#/);if(tm)tag='#'+tm[1]+'#';return{author:author,avatar:avatar,time:time,tag:tag}}
function statsFrom(ctx){var t=C.strip(ctx),m,r={};m=t.match(/(?:回复|评论)\s*[:：]?\s*(\d+)/i);if(m)r.replies=m[1];m=t.match(/(?:查看|浏览|观看)\s*[:：]?\s*(\d+)/i);if(m)r.views=m[1];m=t.match(/(?:点赞|赞)\s*[:：]?\s*(\d+)/i);if(m)r.likes=m[1];if(!r.replies||!r.views){var nums=t.match(/\b\d{1,8}\b/g)||[];if(nums.length>=2){if(!r.replies)r.replies=nums[nums.length-2];if(!r.views)r.views=nums[nums.length-1]}}return r}
function parseGuide(html,base){var x=s(html),as=anchors(x,base),map={},order=[],i,a,id,sc,k,st,en,ctx,mt,imgs,summary;for(i=0;i<as.length;i++){a=as[i];id=C.threadId(a.href);if(!id)continue;sc=scoreTitle(a.text);if(sc<0)continue;k=String(id);if(!map[k]){map[k]={id:k,title:a.text,url:C.toMobile(a.href),score:sc,index:a.index,imgs:[],meta:{},summary:'',stats:{}};order.push(k)}else if(sc>map[k].score){map[k].title=a.text;map[k].url=C.toMobile(a.href);map[k].score=sc;map[k].index=a.index}}order.sort(function(a,b){return map[a].index-map[b].index});for(i=0;i<order.length;i++){var it=map[order[i]];st=it.index;en=i+1<order.length?map[order[i+1]].index:x.length;if(en<=st||en-st>120000)en=Math.min(x.length,st+90000);ctx=x.slice(st,en);imgs=previewImages(ctx,base,6);it.imgs=imgs.slice(0,3);it.meta=metaFrom(ctx,base);it.stats=statsFrom(ctx);mt=C.strip(ctx);summary=trim(mt.replace(it.title,' ').replace(/本帖最后由[^。\n]{0,100}编辑/gi,' ').replace(/查看帖子|查看全部|最后发表|最后回复|回复|浏览/g,' ').replace(/\s+/g,' '));if(it.meta.author)summary=trim(summary.replace(it.meta.author,' '));if(it.meta.time)summary=trim(summary.replace(it.meta.time,' '));if(summary.length>180)summary=summary.slice(0,180)+'…';if(summary===it.title)summary='';it.summary=summary}return order.map(function(q){return map[q]})}
function statText(x){x=x||{};var a=[];if(x.replies)a.push('💬 '+x.replies);if(x.likes)a.push('👍 '+x.likes);if(x.views)a.push('👁 '+x.views);return a.join('　')}
function authorRow(d,it,ref){var m=it.meta||{},av=m.avatar?C.imageUrl(m.avatar,ref):'',desc=[];if(m.time)desc.push(m.time);if(m.tag)desc.push(m.tag);if(m.author||av||desc.length)d.push({title:m.author||'发布者',desc:desc.join('　'),img:av,pic_url:av,url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false,cls:'sht_v22_guide_author'}})}
function previewUrl(u,ref){u=C.abs(u,ref);if(!u)return'';return u+'@headers='+JSON.stringify(C.headers(false,ref))}
function previewRows(d,it,ref,u){var imgs=it.imgs||[],j,p,ct;if(!imgs.length)return;ct=imgs.length>=3?'pic_3':'pic_2';for(j=0;j<imgs.length&&j<3;j++){p=previewUrl(imgs[j],ref);if(!p)continue;d.push({title:'',img:p,pic_url:p,url:u,col_type:ct,extra:{lineVisible:false,cls:'sht_v22_guide_preview'}})}}
function parseItems(m,html,base){var a=[],fn=m&&m._debug&&m._debug.parseCardsV15,i,it,st,en,ctx,ext;try{if(fn)a=fn(html,base,0)||[]}catch(e){a=[]}if(!a.length)return parseGuide(html,base);for(i=0;i<a.length;i++){it=a[i]||{};it.url=C.toMobile(it.url||'');st=Number(it.titleIndex||0);en=i+1<a.length?Number((a[i+1]||{}).titleIndex||0):s(html).length;if(st>0&&en>st&&en-st<120000){ctx=s(html).slice(st,en);ext=previewImages(ctx,base,6);if(ext.length)it.imgs=ext.slice(0,3)}if(it.imgs&&it.imgs.length>3)it.imgs=it.imgs.slice(0,3);if(!it.stats)try{if(typeof SeHuaTangV19Forum!=='undefined'&&SeHuaTangV19Forum.stats&&ctx)it.stats=SeHuaTangV19Forum.stats(ctx,it)}catch(e2){}if(!goodTitle(it.title))it.title='主题 '+(i+1)}return a}
function guide(m){var d=[],mode=C.pageParam('sht_auto','hot'),name=C.pageParam('sht_name',mode==='latest'?'最新发表':(mode==='digest'?'最新精华':'最新热门')),key=pageKey(mode),p=Math.max(1,Number(getMyVar(key,'1')||1)),url=guideUrl(mode,p),html='',items=[],i,it,u,st,imgCount=0;setPageTitle(name);html=renderGuide(url);items=parseItems(m,html,url);if(!items.length){html=C.fetchPage(url,false);items=parseItems(m,html,url)}if(!items.length){var pc=C.toPc(url);html=C.fetchPage(pc,true);items=parseItems(m,html,pc)}for(i=0;i<items.length;i++)imgCount+=(items[i].imgs||[]).length;C.saveDiag('guide.preview.v22',mode+' p='+p+' items='+items.length+' imgs='+imgCount+' url='+url);d.push(C.quick('手机版','x5://'+url,'web.svg'));d.push(C.quick('搜索',C.route('shtSearch'),'search.svg'));d.push(C.line());d.push(C.section(name,'手机端卡片 · 第 '+p+' 页 · '+items.length+' 条主题 · '+imgCount+' 张预览图'));d.push(pbtn(p>1?'上一页':'第一页',key,Math.max(1,p-1),p>1));d.push(pbtn(p>1?'回第1页':'第1页',key,1,p>1));d.push(pbtn(items.length?'下一页':'已到底',key,p+1,items.length>0));d.push(C.line());if(!items.length){d.push(C.empty('本页没有解析到主题','可点“手机版”确认官网页面状态'));setResult(d);return}for(i=0;i<items.length;i++){it=items[i];u=C.route('shtThread',{sht_url:C.toMobile(it.url),sht_name:it.title});authorRow(d,it,url);d.push({title:it.title,desc:it.summary||'',url:u,col_type:'text_1',extra:{lineVisible:false,cls:'sht_v22_guide_card'}});previewRows(d,it,url,u);st=statText(it.stats);if(st)d.push({title:'',desc:st,url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false,cls:'sht_v22_guide_stat'}});d.push(C.line('sht_v22_guide_sep'))}d.push(pbtn('上一页',key,Math.max(1,p-1),p>1));d.push(pbtn('回第1页',key,1,p>1));d.push(pbtn('下一页',key,p+1,true));setResult(d)}
function module(){var m=BASE.module(),oldForum=m.forum;m.version='0.1.0-test.22';m.build=10122;m.forum=function(){if(C.pageParam('sht_auto',''))return guide(m);return oldForum()};m.settings=(function(old){return function(){var d=[];setPageTitle('色花堂设置');d.push(C.section('Test22 话题预览图修复','三个话题直接从渲染后的 mobile=2 DOM 读取 img.currentSrc、lazy 属性和 CSS background-image；预览图片不再使用 #originalSize#，避免单张失效图片撑出大块空白。'));d.push({title:'打开旧设置',desc:'访问状态 / Cookie / 最近诊断',url:C.route('shtSettingsLegacy'),col_type:'text_1'});setResult(d)}})(m.settings);return m}
var P={version:'0.1.0-test.22',build:10122,module:module};SeHuaTangRemoteRuntime=P;return P;
})();
