/* 我的规则仓库 v3.2.0 - filter/search layer */
(function(R){
R.filterState=function(){return{keyword:String(getMyVar('hc_repo_kw','')||'').trim(),view:String(getMyVar('hc_repo_view','all')||'all'),category:String(getMyVar('hc_repo_category','all')||'all'),subCategory:String(getMyVar('hc_repo_sub','all')||'all'),tag:String(getMyVar('hc_repo_tag','all')||'all'),sort:String(getMyVar('hc_repo_sort','default')||'default'),mode:String(getMyVar('hc_repo_mode','all')||'all')};};
R.matchKeyword=function(item,kw){kw=String(kw||'').trim().toLowerCase();if(!kw)return true;var hay=[item.name,item.version,item.desc,item.categoryName,item.subCategory,(item.tags||[]).join(' '),item.mode].join(' ').toLowerCase(),p=kw.split(/\s+/).filter(Boolean);for(var i=0;i<p.length;i++)if(hay.indexOf(p[i])<0)return false;return true;};
R.applyFilters=function(items,state){state=state||this.filterState();var self=this,favs=this.favIds(),recent=this.recentIds(),installed=this.installedMap();var a=items.filter(function(x){if(state.view==='installed'&&!installed[x.id])return false;if(state.view==='updates'&&self.statusOf(x)!=='可更新')return false;if(state.view==='favorites'&&favs.indexOf(x.id)<0)return false;if(state.view==='recent'&&recent.indexOf(x.id)<0)return false;if(state.category!=='all'&&x.category!==state.category)return false;if(state.subCategory!=='all'&&x.subCategory!==state.subCategory)return false;if(state.tag!=='all'&&(x.tags||[]).indexOf(state.tag)<0)return false;if(state.mode!=='all'&&x.mode!==state.mode)return false;return self.matchKeyword(x,state.keyword);});if(state.view==='recent'){var order={};recent.forEach(function(id,i){order[id]=i;});a.sort(function(x,y){return(order[x.id]==null?9999:order[x.id])-(order[y.id]==null?9999:order[y.id]);});return a;}if(state.sort==='name')a.sort(function(x,y){return x.name.localeCompare(y.name);});else if(state.sort==='updated')a.sort(function(x,y){return String(y.updatedAt||'').localeCompare(String(x.updatedAt||''));});else if(state.sort==='version')a.sort(function(x,y){return self.versionCmp(y.version,x.version);});else a.sort(function(x,y){return x.sort-y.sort;});return a;};
R.categories=function(items){var b=[{id:'all',name:'全部'},{id:'video',name:'视频'},{id:'comic',name:'漫画'},{id:'cloud',name:'网盘'},{id:'tools',name:'工具'},{id:'aggregate',name:'聚合'}],p={};items.forEach(function(x){p[x.category]=1;});return b.filter(function(x){return x.id==='all'||p[x.id];});};
R.subCategories=function(items,category){var o={},a=['all'];items.forEach(function(x){if(category!=='all'&&x.category!==category)return;var s=String(x.subCategory||'其它');if(!o[s]){o[s]=1;a.push(s);}});return a;};
R.tagsFor=function(items,state){var c={};items.forEach(function(x){if(state.category!=='all'&&x.category!==state.category)return;if(state.subCategory!=='all'&&x.subCategory!==state.subCategory)return;if(state.mode!=='all'&&x.mode!==state.mode)return;(x.tags||[]).forEach(function(t){c[t]=(c[t]||0)+1;});});return Object.keys(c).sort(function(a,b){return c[b]-c[a]||a.localeCompare(b);}).slice(0,18);};
R.clearAdvancedFilters=function(){['hc_repo_sub','hc_repo_tag','hc_repo_sort','hc_repo_mode'].forEach(function(k){clearMyVar(k);});};
})(HikerRuleRepo);
