/* 我的规则仓库 v3.2.0 - minimalist home */
(function(R){
R.activeLabel=function(text,on){return on?'● '+text:text;};
R.modeText=function(mode){return mode==='remote'?'远程':(mode==='share'?'分享版':'本地');};
R.itemCard=function(item){var tags=(item.tags||[]).slice(0,2).map(function(t){return'#'+t;}).join('  '),st=this.statusOf(item),line1='v'+(item.version||'未标记')+' · '+this.modeText(item.mode)+' · '+st,line2=item.categoryName+' / '+item.subCategory+(tags?' · '+tags:'');return{title:item.name,desc:line1+'\n'+line2,img:this.iconOf(item),pic_url:this.iconOf(item),url:'hiker://page/ruleRepoDetail?rule=&simple=true',col_type:'movie_1_left_pic',extra:{lineVisible:false,pageTitle:item.name,hc_repo_item_id:item.id,longClick:[{title:'导入 / 更新',js:$.toString(function(raw){return $.require('hiker://page/ruleRepoCore').importRule(raw);},JSON.stringify(item.raw))},{title:this.isFav(item)?'取消收藏':'加入收藏',js:$.toString(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id);if(!x)return'toast://规则不存在';var on=r.toggleFav(x);refreshPage(false);return'toast://'+(on?'已收藏':'已取消收藏');},item.id)}]}};};
R.home=function(){setPageTitle('我的规则仓库');var d=[],m,items;try{m=this.manifest(false);items=(m.items||[]).map(this.normalizeItem.bind(this));}catch(e){setResult([{title:'仓库读取失败',desc:String(e.message||e),url:'hiker://empty',col_type:'long_text'}]);return;}var state=this.filterState(),stats=this.stats(items),repo=this.findById('rule-repo')||{name:'我的规则仓库',category:'tools'};
// Hero / overview
 d.push({title:'我的规则仓库',desc:'规则管理中心 · Core '+this.version+'\n'+stats.all+' 个程序 · 已记录 '+stats.installed+' · 可更新 '+stats.updates,img:this.iconOf(repo),pic_url:this.iconOf(repo),url:'hiker://page/ruleRepoVersions?rule=&simple=true',col_type:'movie_1_left_pic',extra:{lineVisible:false,pageTitle:'版本中心'}});
// Search
 d.push({title:'搜索程序',url:$.toString(function(){putMyVar('hc_repo_kw',String(input||'').trim());refreshPage(false);}),col_type:'input',extra:{titleVisible:false,defaultValue:state.keyword,onChange:$.toString(function(){putMyVar('hc_repo_kw',String(input||''));})}});
// Quick actions
 d.push({title:'更新中心',col_type:'text_3',url:'hiker://page/ruleRepoVersions?rule=&simple=true',extra:{lineVisible:false,pageTitle:'版本中心'}});d.push({title:'高级筛选',col_type:'text_3',url:'hiker://page/ruleRepoFilters?rule=&simple=true',extra:{lineVisible:false,pageTitle:'高级筛选'}});d.push({title:'设置',col_type:'text_3',url:'hiker://page/ruleRepoSettings?rule=&simple=true',extra:{lineVisible:false,pageTitle:'仓库设置'}});
// View state
 var views=[['全部','all',stats.all],['已记录','installed',stats.installed],['可更新','updates',stats.updates],['收藏','favorites',stats.favorites],['最近','recent','']];views.forEach(function(v){var t=v[0]+(v[2]!==''?' '+v[2]:'');d.push({title:R.activeLabel(t,state.view===v[1]),col_type:'scroll_button',url:$('#noLoading#').lazyRule(function(x){putMyVar('hc_repo_view',x);refreshPage(false);return'hiker://empty';},v[1])});});
// Category
 this.categories(items).forEach(function(c){d.push({title:R.activeLabel(c.name,state.category===c.id),col_type:'scroll_button',url:$('#noLoading#').lazyRule(function(id){putMyVar('hc_repo_category',id);putMyVar('hc_repo_sub','all');putMyVar('hc_repo_tag','all');refreshPage(false);return'hiker://empty';},c.id)});});
 var filtered=this.applyFilters(items,state);d.push({title:'我的程序  '+filtered.length,desc:state.keyword?'搜索：'+state.keyword:'',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});filtered.forEach(function(x){d.push(R.itemCard(x));});if(!filtered.length)d.push({title:'没有匹配的程序',desc:'试试清空搜索或切换筛选条件。',url:'hiker://empty',col_type:'text_center_1'});
 d.push({col_type:'blank_block'});d.push({title:'Core '+this.version+' · Schema '+(m.schema||'?'),desc:'高级筛选与排序已移到独立页面，首页只保留高频操作。',url:'hiker://empty',col_type:'text_center_1'});setResult(d);};
R.searchPage=function(){setPageTitle('搜索程序');var d=[],kw=String(getParam('kw','')||getParam('s','')||'').trim(),items;try{items=this.items(false);}catch(e){setResult([{title:'仓库读取失败',desc:String(e.message||e),url:'hiker://empty',col_type:'long_text'}]);return;}d.push({title:'搜索程序',url:$.toString(function(){return'hiker://search?s='+encodeURIComponent(input)+'&rule='+encodeURIComponent(MY_RULE.title);}),col_type:'input',extra:{titleVisible:false,defaultValue:kw}});var a=items.filter(function(x){return R.matchKeyword(x,kw);});d.push({title:'搜索结果  '+a.length,url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});a.forEach(function(x){d.push(R.itemCard(x));});if(!a.length)d.push({title:'没有匹配的程序',url:'hiker://empty',col_type:'text_center_1'});setResult(d);};
})(HikerRuleRepo);
