/* 我的规则仓库 RC33 - Flat Entry 1.0 */
var RuleRepoFlatEntry=(function(){
var VERSION='1.0.0',ROOT='hiker://files/rules/asset-core-local/rule-repo-test/';
var BUNDLE=ROOT+'flat_runtime_b423.js',BUILDER=ROOT+'flat_builder_v1.js',CONTROL=ROOT+'flat_control_v1.js';
var BUILDER_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/76599d39f81bd9780f88056320f34f993552e4ac/apps/tools/rule-repo/releases/test-3.5.6-rc33/flat_builder_v1.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@76599d39f81bd9780f88056320f34f993552e4ac/apps/tools/rule-repo/releases/test-3.5.6-rc33/flat_builder_v1.js','https://github.com/huoguotiankong/asset-core-7f3/raw/76599d39f81bd9780f88056320f34f993552e4ac/apps/tools/rule-repo/releases/test-3.5.6-rc33/flat_builder_v1.js'];
var CONTROL_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/50a4393df45377c5e18303f3bc7a1acdc4a39026/apps/tools/rule-repo/releases/test-3.5.6-rc33/flat_control_v1.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@50a4393df45377c5e18303f3bc7a1acdc4a39026/apps/tools/rule-repo/releases/test-3.5.6-rc33/flat_control_v1.js'];
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function ensure(path,urls,label){if(fileExist(path))return path;var es=[];for(var i=0;i<urls.length;i++){try{var s=String(fetch(urls[i],{timeout:4500,headers:{'Cache-Control':'public, max-age=31536000, immutable'}})||'');if(bad(s))throw new Error('无效响应');writeFile(path,s);if(!fileExist(path))throw new Error('写入失败');return path;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(label+'下载失败：'+es.join(' | '));}
function req(path){var u=getPath(path);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}}
function load(){if(!fileExist(CONTROL))ensure(CONTROL,CONTROL_URLS,'Flat Control');if(!fileExist(BUNDLE)){ensure(BUILDER,BUILDER_URLS,'Flat Builder');req(BUILDER);if(typeof RuleRepoFlatBuilder!=='object'||typeof RuleRepoFlatBuilder.build!=='function')throw new Error('Flat Builder 未导出');RuleRepoFlatBuilder.build(false);}req(BUNDLE);if(typeof HikerRuleRepo!=='object'||Number(HikerRuleRepo.build||0)!==423||!HikerRuleRepo.__flat423){try{deleteCache(getPath(BUNDLE));}catch(e1){}req(BUNDLE);}if(typeof HikerRuleRepo!=='object'||Number(HikerRuleRepo.build||0)!==423)throw new Error('Flat Runtime Build423 未加载');return HikerRuleRepo;}
function run(name){var R=load();name=String(name||'home');if(name==='home')return R.home();if(name==='category')return R.categoryPage();if(name==='search')return R.searchPage();if(name==='updates')return R.updatesPage();if(name==='detail')return R.detailPage();if(name==='history')return R.historyPage();if(name==='settings')return R.settingsPage();if(name==='about')return R.aboutPage();if(name==='filters')return typeof R.filtersPage==='function'?R.filtersPage():R.categoryPage();if(name==='versions')return R.channelPage();if(name==='update'){setPageTitle('测试版更新');setResult([{title:'我的规则仓库·测试版',desc:'3.5.6-rc33 · Build423\nFlat Runtime 19.0',col_type:'text_1',url:'hiker://empty'},{title:'单本地 Runtime',desc:'正常启动只加载 Flat Entry + flat_runtime_b423.js，不再经过 v6→v10 Bridge 链，也不再逐个 require 52 个 Build402 模块。',col_type:'text_2',url:'hiker://empty'},{title:'轻量控制面',desc:'检查版本、同步和诊断只加载 flat_control_v1.js；诊断不联网、不重建 Runtime。',col_type:'text_2',url:'hiker://empty'},{title:'导入快车道',desc:'普通 .txt 优先 fixed ref Raw，1.8 秒超时后才切 CDN/WebRaw；RC33 自身 Shell 同时大幅瘦身。',col_type:'text_2',url:'hiker://empty'}]);return;}throw new Error('未知页面：'+name);}
return{version:VERSION,load:load,run:run};
})();
