/* 我的规则仓库 RC33 - Flat Runtime Builder 1.0 */
var RuleRepoFlatBuilder=(function(){
var VERSION='1.0.0',PKG='__hclocal22_rule-repo-test_b402.json';
var ROOT='hiker://files/rules/asset-core-local/rule-repo-test/';
var BUNDLE=ROOT+'flat_runtime_b423.js',CONTROL=ROOT+'flat_control_v1.js',FINAL=ROOT+'flat_final_patch.js',RC27=ROOT+'flat_rc27_patch.js',REFS=ROOT+'import_ref_catalog_v1.json',LEGACY=ROOT+'flat_legacy_loader_v5.js';
var CONTROL_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/50a4393df45377c5e18303f3bc7a1acdc4a39026/apps/tools/rule-repo/releases/test-3.5.6-rc33/flat_control_v1.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@50a4393df45377c5e18303f3bc7a1acdc4a39026/apps/tools/rule-repo/releases/test-3.5.6-rc33/flat_control_v1.js','https://github.com/huoguotiankong/asset-core-7f3/raw/50a4393df45377c5e18303f3bc7a1acdc4a39026/apps/tools/rule-repo/releases/test-3.5.6-rc33/flat_control_v1.js'];
var FINAL_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/50a4393df45377c5e18303f3bc7a1acdc4a39026/apps/tools/rule-repo/releases/test-3.5.6-rc33/flat_final_patch.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@50a4393df45377c5e18303f3bc7a1acdc4a39026/apps/tools/rule-repo/releases/test-3.5.6-rc33/flat_final_patch.js','https://github.com/huoguotiankong/asset-core-7f3/raw/50a4393df45377c5e18303f3bc7a1acdc4a39026/apps/tools/rule-repo/releases/test-3.5.6-rc33/flat_final_patch.js'];
var RC27_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/0817d0f2ae8ab0dc5f7d8e2b9da0f241eec371b7/apps/tools/rule-repo/releases/test-3.5.6-rc27/channel_update_state_patch.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@0817d0f2ae8ab0dc5f7d8e2b9da0f241eec371b7/apps/tools/rule-repo/releases/test-3.5.6-rc27/channel_update_state_patch.js','https://github.com/huoguotiankong/asset-core-7f3/raw/0817d0f2ae8ab0dc5f7d8e2b9da0f241eec371b7/apps/tools/rule-repo/releases/test-3.5.6-rc27/channel_update_state_patch.js'];
var REF_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/3d9dd0bf17f186b88465fffa729c69efd5b24f53/apps/tools/rule-repo/releases/test-3.5.6-rc30/import_ref_catalog_v1.json','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@3d9dd0bf17f186b88465fffa729c69efd5b24f53/apps/tools/rule-repo/releases/test-3.5.6-rc30/import_ref_catalog_v1.json','https://github.com/huoguotiankong/asset-core-7f3/raw/3d9dd0bf17f186b88465fffa729c69efd5b24f53/apps/tools/rule-repo/releases/test-3.5.6-rc30/import_ref_catalog_v1.json'];
var LEGACY_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/6cc76aba3f8477361099208ad5b206d2e3e5430d/apps/tools/rule-repo/local_shell_loader_v5.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@6cc76aba3f8477361099208ad5b206d2e3e5430d/apps/tools/rule-repo/local_shell_loader_v5.js','https://github.com/huoguotiankong/asset-core-7f3/raw/6cc76aba3f8477361099208ad5b206d2e3e5430d/apps/tools/rule-repo/local_shell_loader_v5.js'];
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function ensure(path,urls,label){if(fileExist(path))return path;var es=[];for(var i=0;i<urls.length;i++){try{var s=String(fetch(urls[i],{timeout:4500,headers:{'Cache-Control':'public, max-age=31536000, immutable'}})||'');if(bad(s))throw new Error('无效响应');writeFile(path,s);if(!fileExist(path))throw new Error('写入失败');return path;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(label+'下载失败：'+es.join(' | '));}
function req(path){var u=getPath(path);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}}
function pkg(){try{if(!fileExist(PKG))return null;var p=JSON.parse(String(readFile(PKG,0)||'{}'));if(Number(p.build||0)!==402||!Array.isArray(p.files)||!p.files.length)return null;for(var i=0;i<p.files.length;i++)if(!p.files[i]||!p.files[i].file||!fileExist(String(p.files[i].file)))return null;return p;}catch(e){return null;}}
function ensurePkg(){var p=pkg();if(p)return p;ensure(LEGACY,LEGACY_URLS,'Build402 legacy loader');req(LEGACY);if(typeof RuleRepoLocal!=='object'||typeof RuleRepoLocal.load!=='function')throw new Error('Legacy Loader 未导出');RuleRepoLocal.load();p=pkg();if(!p)throw new Error('Build402 本地模块包安装后仍不可用');return p;}
function build(force){if(!force&&fileExist(BUNDLE))return{ok:true,built:false,file:BUNDLE};ensure(CONTROL,CONTROL_URLS,'Flat Control');ensure(FINAL,FINAL_URLS,'Flat Final Patch');ensure(RC27,RC27_URLS,'RC27 Update State');ensure(REFS,REF_URLS,'Import Ref Catalog');var p=ensurePkg(),a=['/* RULE_REPO_FLAT_B423 */\n'];for(var i=0;i<p.files.length;i++){var f=p.files[i],s=String(readFile(String(f.file),0)||'');if(bad(s))throw new Error('本地模块 '+String(f.name||i)+' 内容无效');a.push('\n/* FLAT MODULE '+String(f.name||i)+' */\n'+s+'\n;\n');}var s27=String(readFile(RC27,0)||''),sf=String(readFile(FINAL,0)||'');if(bad(s27)||bad(sf))throw new Error('Flat patch 内容无效');a.push('\n/* RC27 UPDATE STATE */\n'+s27+'\n;\nif(typeof RuleRepoRC27!=="object")throw new Error("RC27 missing");RuleRepoRC27.apply(HikerRuleRepo);\n');a.push('\n/* RC33 FINAL */\n'+sf+'\n;\nif(typeof RuleRepoRC33!=="object")throw new Error("RC33 missing");RuleRepoRC33.apply(HikerRuleRepo);\n');a.push('\nHikerRuleRepo.__flatBundleBuild=423;\n');writeFile(BUNDLE,a.join(''));if(!fileExist(BUNDLE))throw new Error('Flat Runtime 写入失败');try{req(CONTROL);if(typeof RuleRepoFlatControl==='object'){var cat=RuleRepoFlatControl.catalogFile,ic=RuleRepoFlatControl.iconFile;if(!fileExist(cat)||!fileExist(ic)||!getItem('hc_repo_manifest_v3',''))RuleRepoFlatControl.syncAll();}}catch(e2){}return{ok:true,built:true,file:BUNDLE,modules:p.files.length};}
return{version:VERSION,build:build,bundle:BUNDLE};
})();
