/* 我的规则仓库 RC35 - Flat Entry 3.0 */
var RuleRepoFlatEntry=(function(){
var VERSION='3.0.0',ROOT='hiker://files/rules/asset-core-local/rule-repo-test/';
var BUNDLE=ROOT+'flat_runtime_b425.js',BUILDER=ROOT+'flat_builder_v3.js',CONTROL=ROOT+'flat_control_v3.js';
var BUILDER_REF='69bc1f4cfbcfc63cbd0bcdff20c4a04c1132b04f',BUILDER_PATH='apps/tools/rule-repo/releases/test-3.5.6-rc35/flat_builder_v3.js';
var CONTROL_REF='3de9681c213d045af4f882474fdb3fd12e180621',CONTROL_PATH='apps/tools/rule-repo/releases/test-3.5.6-rc35/flat_control_v3.js';
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function urls(ref,path){return['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/'+ref+'/'+path,'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@'+ref+'/'+path,'https://github.com/huoguotiankong/asset-core-7f3/raw/'+ref+'/'+path];}
function ensure(path,ref,src,label){if(fileExist(path))return path;var us=urls(ref,src),es=[];for(var i=0;i<us.length;i++){try{var s=String(fetch(us[i],{timeout:4200,headers:{'Cache-Control':'public, max-age=31536000, immutable'}})||'');if(bad(s))throw new Error('无效响应');writeFile(path,s);if(!fileExist(path))throw new Error('写入失败');return path;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(label+'下载失败：'+es.join(' | '));}
function req(path){var u=getPath(path);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}}
function ensureControl(){ensure(CONTROL,CONTROL_REF,CONTROL_PATH,'RC35 Control');try{var s=String(readFile(CONTROL)||'');if(s){var a=[ROOT+'flat_control_v1.js',ROOT+'flat_control_v2.js'];for(var i=0;i<a.length;i++)if(!fileExist(a[i]))writeFile(a[i],s);}}catch(e){}return CONTROL;}
function load(){ensureControl();if(!fileExist(BUNDLE)){ensure(BUILDER,BUILDER_REF,BUILDER_PATH,'RC35 Builder');req(BUILDER);if(typeof RuleRepoFlatBuilder!=='object'||typeof RuleRepoFlatBuilder.build!=='function')throw new Error('RC35 Builder 未导出');RuleRepoFlatBuilder.build(false);}req(BUNDLE);if(typeof HikerRuleRepo!=='object'||Number(HikerRuleRepo.build||0)!==425||!HikerRuleRepo.__flat425){try{deleteCache(getPath(BUNDLE));}catch(e1){}req(BUNDLE);}if(typeof HikerRuleRepo!=='object'||Number(HikerRuleRepo.build||0)!==425)throw new Error('Flat Runtime Build425 未加载');return HikerRuleRepo;}
function run(name){var R=load();name=String(name||'home');if(name==='home')return R.home();if(name==='category')return R.categoryPage();if(name==='search')return R.searchPage();if(name==='updates')return R.updatesPage();if(name==='detail')return R.detailPage();if(name==='history')return R.historyPage();if(name==='settings')return R.settingsPage();if(name==='about')return R.aboutPage();if(name==='filters')return typeof R.filtersPage==='function'?R.filtersPage():R.categoryPage();if(name==='versions')return R.channelPage();if(name==='update'){setPageTitle('测试版更新');setResult([{title:'我的规则仓库·测试版',desc:'3.5.6-rc35 · Build425\nPer-App Channel Truth',col_type:'text_1',url:'hiker://empty'},{title:'每程序 channels.json 权威',desc:'统一 snapshot 只负责离线浏览；进入详情或检查版本直接读取程序自己的 channels.json。',col_type:'text_2',url:'hiker://empty'},{title:'不依赖 GitHub API HEAD',desc:'自更新与目录刷新直接读取 main 多源，并从有效结果中选择更高 Build/revision。',col_type:'text_2',url:'hiker://empty'},{title:'安装版本双重识别',desc:'导入时写入通道身份；旧安装再用手机规则 numeric version 与当前 Shell 指纹匹配。',col_type:'text_2',url:'hiker://empty'}]);return;}throw new Error('未知页面：'+name);}
return{version:VERSION,load:load,run:run};
})();