/* 我的规则仓库 RC35 - Direct Per-App Channel Truth Control 3.0 */
var RuleRepoFlatControl=(function(){
var VERSION='3.0.0',REPO='huoguotiankong/asset-core-7f3';
var ROOT='hiker://files/rules/asset-core-local/rule-repo-test/';
var MANIFEST_PATH='manifest.json',CATALOG_PATH='apps/tools/rule-repo/channel_catalog_snapshot.json',ICON_PATH='apps/tools/rule-repo/icon_catalog_snapshot.json',SELF_PATH='apps/tools/rule-repo/channels.json';
var CATALOG_FILE=ROOT+'channel_catalog_v3.json',ICON_FILE=ROOT+'icon_catalog_v1.json',SELF_FILE=ROOT+'self_channels_v5.json',BUNDLE=ROOT+'flat_runtime_b425.js';
var MANIFEST_KEY='hc_repo_manifest_v3',MANIFEST_TS_KEY='hc_repo_manifest_v3_ts',REV_KEY='hc_repo_v3_manifest_revision',PROBE_TS_KEY='hc_repo_v3_manifest_probe_ts';
var DIAG_KEY='hc_repo_flat_control_diag_v3',IMPORT_DIAG_KEY='hc_repo_import_diag_v3';
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Request\s+(?:failed|error)|Fetch\s+(?:failed|error)|Network\s+(?:failed|error)|Timeout\b|ETIMEDOUT\b|ECONN|ENOTFOUND\b|Forbidden\b|Unauthorized\b|Rate\s*limit\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t)||/^\{\s*"(?:message|error)"\s*:/i.test(t);}
function json(t){if(bad(t))return null;try{return JSON.parse(String(t));}catch(e){return null;}}
function readJsonFile(p){try{if(!fileExist(p))return null;return json(readFile(p));}catch(e){return null;}}
function safeId(id){return String(id||'').replace(/[^0-9A-Za-z_.-]/g,'_');}
function appFile(id){return ROOT+'app_channels_'+safeId(id)+'.json';}
function testOf(x){var a=x&&x.channels||[];for(var i=0;i<a.length;i++)if(String(a[i]&&a[i].channel||'')==='test')return a[i];return null;}
function maxBuild(x){var a=x&&x.channels||[],m=0;for(var i=0;i<a.length;i++)m=Math.max(m,Number(a[i]&&a[i].build||0));return m;}
function rankChannels(x){return maxBuild(x);}
function rankRevision(x){var s=String(x&&x.revision||'').replace(/\D/g,'');return Number(s||0);}
function mutableUrls(path){var p=String(path||'').replace(/^\/+/,'');var q='?_rr35='+Date.now();return['https://raw.githubusercontent.com/'+REPO+'/main/'+p+q,'https://github.com/'+REPO+'/raw/main/'+p+q,'https://cdn.jsdelivr.net/gh/'+REPO+'@main/'+p+q];}
function chooseBest(rs,validator,ranker){var best=null,bestRank=-1;for(var i=0;i<rs.length;i++){var x=null;try{x=validator(String(rs[i]==null?'':rs[i]));}catch(e){}if(!x)continue;var r=0;try{r=Number(ranker?ranker(x):0)||0;}catch(e2){}if(!best||r>bestRank){best=x;bestRank=r;}}return best;}
function fetchMutable(path,validator,ranker){var us=mutableUrls(path),rs=null,best=null,es=[];
 try{if(typeof batchFetch==='function'){var q=[];for(var i=0;i<us.length;i++)q.push({url:us[i],options:{timeout:2400,headers:{'Cache-Control':'no-cache, no-store, max-age=0'}}});rs=batchFetch(q)||[];best=chooseBest(rs,validator,ranker);if(best)return best;}}catch(e0){es.push('batch:'+String(e0.message||e0));}
 for(var j=0;j<us.length;j++){try{var t=String(fetch(us[j],{timeout:1800,headers:{'Cache-Control':'no-cache, no-store, max-age=0'}})||''),x=validator(t);if(x){if(!best||Number(ranker?ranker(x):0)>Number(ranker?ranker(best):0))best=x;}}catch(e1){es.push((j+1)+':'+String(e1.message||e1));}}
 if(best)return best;throw new Error(String(path||'')+' 多源读取失败'+(es.length?'：'+es.join(' | '):''));}
function validSelf(t){var x=json(t);return x&&String(x.id||'')==='rule-repo'&&Array.isArray(x.channels)&&maxBuild(x)>0?x:null;}
function validApp(expected){return function(t){var x=json(t);if(!x||!Array.isArray(x.channels)||!x.channels.length)return null;var id=String(x.id||'');return !expected||id===String(expected)?x:null;};}
function validManifest(t){var x=json(t);return x&&Array.isArray(x.items)?x:null;}
function validCatalog(t){var x=json(t);return x&&x.apps&&typeof x.apps==='object'?x:null;}
function validIcons(t){var x=json(t);return x&&x.icons&&typeof x.icons==='object'?x:null;}
function isRuleText(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !bad(t)&&t.indexOf('海阔视界，首页频道￥home_rule￥')===0;}
function ruleVersion(t){t=String(t||'');var mark='海阔视界，首页频道￥home_rule￥',p=t.indexOf(mark),o=null;if(p>=0){try{o=JSON.parse(t.substring(p+mark.length));}catch(e){}}if(o&&o.version!==undefined){var n=Number(o.version);if(!isNaN(n)&&n>0)return n;}var m=t.match(/["']version["']\s*:\s*(\d{3,})/i);return m?Number(m[1]):0;}
function fetchRuleVersion(path){if(!/\.txt(?:$|\?)/i.test(String(path||'')))return 0;var us=mutableUrls(path),es=[];for(var i=0;i<us.length;i++){try{var s=String(fetch(us[i],{timeout:1600,headers:{'Cache-Control':'no-cache, no-store, max-age=0'}})||'');if(isRuleText(s)){var v=ruleVersion(s);if(v)return v;}}catch(e){es.push((i+1)+':'+String(e.message||e));}}return 0;}
function enrichChannels(x){if(!x||!Array.isArray(x.channels))return x;for(var i=0;i<x.channels.length;i++){var c=x.channels[i]||{},rv=Number(c.ruleVersion||c.localRuleVersion||c.forcedRuleVersion||0);if(!rv&&c.path)rv=fetchRuleVersion(c.path);if(rv)c.ruleVersion=rv;}x._fetchedAt=Date.now();x._fingerprintReady=true;return x;}
function saveSelf(x){if(!x||!maxBuild(x))throw new Error('self channels 无效');writeFile(SELF_FILE,JSON.stringify(x));return x;}
function saveManifest(x){setItem(MANIFEST_KEY,JSON.stringify(x));setItem(MANIFEST_TS_KEY,String(Date.now()));if(x&&x.revision)setItem(REV_KEY,String(x.revision));setItem(PROBE_TS_KEY,String(Date.now()));}
function refreshSelf(){var st=Date.now(),x=fetchMutable(SELF_PATH,validSelf,rankChannels);saveSelf(x);var t=testOf(x),o={ok:true,source:'main-direct',build:Number(t&&t.build||0),version:String(t&&t.version||''),elapsed:Date.now()-st};try{setItem(DIAG_KEY,JSON.stringify({time:Date.now(),action:'self',result:o}));}catch(e){}return o;}
function refreshCatalog(){var st=Date.now(),c=fetchMutable(CATALOG_PATH,validCatalog,rankRevision);writeFile(CATALOG_FILE,JSON.stringify(c));var o={ok:true,source:'main-direct',revision:String(c.revision||''),elapsed:Date.now()-st};try{setItem(DIAG_KEY,JSON.stringify({time:Date.now(),action:'catalog',result:o}));}catch(e){}return o;}
function refreshApp(appId,path){appId=String(appId||'');path=String(path||'');if(!appId||!path)throw new Error('缺少程序 channelsPath');var st=Date.now(),x=fetchMutable(path,validApp(appId),rankChannels);x=enrichChannels(x);writeFile(appFile(appId),JSON.stringify(x));var o={ok:true,id:appId,versionCount:x.channels.length,maxBuild:maxBuild(x),elapsed:Date.now()-st,meta:x};try{setItem(DIAG_KEY,JSON.stringify({time:Date.now(),action:'app',result:{id:appId,maxBuild:o.maxBuild,elapsed:o.elapsed}}));}catch(e){}return o;}
function readApp(appId){return readJsonFile(appFile(appId));}
function syncAll(){var st=Date.now(),m=null,c=null,ic=null,self=null,errors=[];try{m=fetchMutable(MANIFEST_PATH,validManifest,rankRevision);saveManifest(m);}catch(e0){errors.push('manifest:'+String(e0.message||e0));}try{c=fetchMutable(CATALOG_PATH,validCatalog,rankRevision);writeFile(CATALOG_FILE,JSON.stringify(c));}catch(e1){errors.push('catalog:'+String(e1.message||e1));}try{ic=fetchMutable(ICON_PATH,validIcons,rankRevision);writeFile(ICON_FILE,JSON.stringify(ic));}catch(e2){errors.push('icons:'+String(e2.message||e2));}try{self=fetchMutable(SELF_PATH,validSelf,rankChannels);saveSelf(self);}catch(e3){errors.push('self:'+String(e3.message||e3));}var o={ok:!!(m||c||ic||self),source:'main-direct',manifest:!!m,catalog:!!c,icons:!!ic,selfBuild:maxBuild(self),revision:String(c&&c.revision||m&&m.revision||''),elapsed:Date.now()-st,errors:errors};try{setItem(DIAG_KEY,JSON.stringify({time:Date.now(),action:'sync',result:o}));}catch(e4){}return o;}
function diagnostics(){var self=readJsonFile(SELF_FILE),cat=readJsonFile(CATALOG_FILE),icons=readJsonFile(ICON_FILE),ctrl=null,imp=null;try{ctrl=json(getItem(DIAG_KEY,'{}'));}catch(e){}try{imp=json(getItem(IMPORT_DIAG_KEY,'{}'));}catch(e2){}var t=testOf(self);return 'Flat Runtime RC35 / Build425\n'+'bundle '+(fileExist(BUNDLE)?'ready':'missing')+'\n'+'self '+String(t&&t.version||'--')+' / Build'+Number(t&&t.build||0)+'\n'+'catalog '+String(cat&&cat.revision||'--')+' (offline summary)\n'+'channel truth per-app channels.json\n'+'GitHub API HEAD not required\n'+'icons '+String(icons&&icons.revision||'--')+'\n'+'last control '+String(ctrl&&ctrl.action||'--')+' '+String(ctrl&&ctrl.result&&ctrl.result.elapsed||'--')+'ms\n'+'last import '+String(imp&&imp.mode||'--')+' '+String(imp&&imp.networkMs||'--')+'ms / '+String(imp&&imp.bytes||0)+'B';}
return{version:VERSION,refreshSelf:refreshSelf,refreshCatalog:refreshCatalog,refreshApp:refreshApp,readApp:readApp,syncAll:syncAll,diagnostics:diagnostics,appFile:appFile,selfFile:SELF_FILE,catalogFile:CATALOG_FILE,iconFile:ICON_FILE,ruleVersion:ruleVersion};
})();