/* 我的规则仓库 3.5.6-rc35 - per-app channel truth + install identity repair */
var RuleRepoRC35=(function(){
var VERSION='3.5.6-rc35',BUILD=425,RULE='apps/tools/rule-repo/rule_repo_test_v172.txt';
var ROOT='hiker://files/rules/asset-core-local/rule-repo-test/',CATALOG_FILE=ROOT+'channel_catalog_v3.json',SELF_FILE=ROOT+'self_channels_v5.json',CONTROL=ROOT+'flat_control_v3.js',ENTRY=ROOT+'flat_entry_v3.js';
function parse(s){try{return JSON.parse(String(s||''));}catch(e){return null;}}
function fileJson(p){try{return fileExist(p)?parse(readFile(p)):null;}catch(e){return null;}}
function clone(x){try{return JSON.parse(JSON.stringify(x));}catch(e){return x||{};}}
function safeId(id){return String(id||'').replace(/[^0-9A-Za-z_.-]/g,'_');}
function appFile(id){return ROOT+'app_channels_'+safeId(id)+'.json';}
function testOf(x){var a=x&&x.channels||[];for(var i=0;i<a.length;i++)if(String(a[i]&&a[i].channel||'')==='test')return a[i];return null;}
function maxBuild(x){var a=x&&x.channels||[],m=0;for(var i=0;i<a.length;i++)m=Math.max(m,Number(a[i]&&a[i].build||0));return m;}
function currentMeta(){return{schema:4,id:'rule-repo',name:'我的规则仓库',updatedAt:'2026-08-25 21:45',channels:[{channel:'stable',label:'正式版',id:'rule-repo',name:'我的规则仓库',version:'3.5.5',build:389,displayVersion:'正式版 3.5.5 · Build 389',path:'apps/tools/rule-repo/rule_repo_remote_v355.txt',mode:'remote',recommended:true},{channel:'test',label:'测试版',id:'rule-repo-test',name:'我的规则仓库·测试版',version:VERSION,build:BUILD,displayVersion:'测试版 '+VERSION+' · Build '+BUILD,path:RULE,mode:'remote-local-first-flat',recommended:false,baseVersion:'3.5.5',targetVersion:'3.5.6'}]};}
function selfMeta(){var x=fileJson(SELF_FILE),cur=currentMeta();return x&&maxBuild(x)>=BUILD?clone(x):cur;}
function snapshotMeta(id){var c=fileJson(CATALOG_FILE),x=c&&c.apps&&c.apps[String(id||'')];return x&&Array.isArray(x.channels)?clone(x):null;}
function appMeta(id){var x=fileJson(appFile(id));return x&&Array.isArray(x.channels)&&x.channels.length?clone(x):null;}
function metaOf(item){var id=String(item&&item.id||'');if(id==='rule-repo')return selfMeta();return appMeta(id)||snapshotMeta(id);}
function channelsPath(item){return String(item&&item.channelsPath||item&&item.raw&&item.raw.channelsPath||'');}
function loadControl(){var u=getPath(CONTROL);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}if(typeof RuleRepoFlatControl!=='object')throw new Error('RC35 Control 未加载');return RuleRepoFlatControl;}
function remoteChannel(c){var ch=String(c&&c.channel||'').toLowerCase();return ch==='stable'||ch==='test'||ch==='candidate';}
function bestRemote(cs){var t=null;for(var i=0;i<(cs||[]).length;i++){var c=cs[i]||{};if(!remoteChannel(c))continue;if(!t||Number(c.build||0)>Number(t.build||0))t=c;}return t;}
function actualRule(R,item){var title=String(item&&item.name||'').replace(/\|/g,'').trim(),snap=null,r=null;try{snap=R.deviceRuleSnapshot();r=snap&&snap.byTitle&&snap.byTitle[title]||null;}catch(e){}return r;}
function mergeVerified(R,item,c,rv,source){var idx=null,id=String(item&&item.id||''),meta=metaOf(item),t=bestRemote(meta&&meta.channels||[]);try{idx=R.readVerifiedInstallIndex&&R.readVerifiedInstallIndex();}catch(e){}if(!idx||idx.schema!==1)idx={schema:1,time:Date.now(),revision:'',apps:{}};idx.apps=idx.apps||{};idx.apps[id]={installed:true,recognized:true,updateKnown:true,update:!!(t&&Number(t.build||0)>Number(c&&c.build||0)),channel:String(c&&c.channel||''),installedVersion:String(c&&c.version||''),installedBuild:Number(c&&c.build||0),targetChannel:String(t&&t.channel||''),targetVersion:String(t&&t.version||''),targetBuild:Number(t&&t.build||0),title:String(item&&item.name||''),ruleVersion:Number(rv||0),verifiedAt:Date.now(),source:String(source||'rc35')};idx.time=Date.now();try{R.saveVerifiedInstallIndex(idx);}catch(e2){}return idx.apps[id];}
function repair(R,item){var meta=metaOf(item),rec=actualRule(R,item),rv=Number(rec&&rec.ruleVersion||0),cs=meta&&meta.channels||[],matches=[];if(!rec||!rv||!cs.length)return null;for(var i=0;i<cs.length;i++){var c=cs[i]||{},crv=Number(c.ruleVersion||c.localRuleVersion||c.forcedRuleVersion||0);if(crv&&crv===rv)matches.push(c);}if(matches.length===1)return mergeVerified(R,item,matches[0],rv,'device-rule-version');return null;}
function inferParent(R,x){var items=[];try{items=R.items(false)||[];}catch(e){}for(var i=0;i<items.length;i++){var it=items[i],m=metaOf(it),cs=m&&m.channels||[];for(var j=0;j<cs.length;j++){var c=cs[j]||{};if(String(c.path||'')&&String(c.path||'')===String(x&&x.path||''))return{item:it,channel:c};if(String(c.id||'')&&String(c.id||'')===String(x&&x.id||''))return{item:it,channel:c};}}return null;}
function apply(R){
 if(!R||typeof R.home!=='function')throw new Error('规则仓 Runtime 不完整');
 var baseAction=R.workspaceAction,baseStatic=R.workspaceStaticAction,baseStatics=R.workspaceStaticActions,baseImport=R.importRule,baseFast=R.fastItemState;
 R.__flat425=true;R.version=VERSION;R.build=BUILD;R.channel='test';R.releaseLabel='Flat Runtime 21.0';R.localFirstRuntimeVersion='21.0';R.fastHomeVersion='21.0.0';R.isTestChannel=function(){return true;};
 R.ruleRepoChannelFallback=function(){return selfMeta();};
 R.fastChannelCache=function(item){var m=metaOf(item);return m?{schema:22,time:Date.now(),revision:String(m._fetchedAt||''),sig:'per-app:'+String(item&&item.id||''),meta:m}:null;};
 R.channelMeta=function(item){return metaOf(item);};
 R.loadChannelMetaLive=function(item){var m=metaOf(item);if(m)return m;throw new Error('暂无 '+String(item&&item.id||'')+' 版本信息，请点检查版本');};
 R.repairInstalledIdentity=function(appId){var it=this.findById(String(appId||''),false);return it?repair(this,it):null;};
 R.fastItemState=function(item){var s=baseFast.call(this,item);if(item&&(String(item.entryType||'')==='channel-group'||channelsPath(item))&&s&&s.installed&&!s.recognized){var z=repair(this,item);if(z)s=baseFast.call(this,item);}return s;};
 R.importRule=function(raw){var x=null,ret='';try{x=typeof raw==='string'?JSON.parse(raw):raw;x=x&&x.raw?x.raw:x;}catch(e){}ret=baseImport.call(this,raw);if(x&&String(ret||'').indexOf('海阔视界，首页频道￥home_rule￥')===0){try{var inf=inferParent(this,x),rv=loadControl().ruleVersion(ret);if(inf&&inf.item&&inf.channel)mergeVerified(this,inf.item,inf.channel,rv,'repo-import-rc35');}catch(e2){}}return ret;};
 R.workspaceAction=function(kind,item){var k=String(kind||''),id=String(item&&item.id||''),cp=channelsPath(item);
  if(k==='check')return $('#noLoading#').lazyRule(function(appId,path){var loading=false;try{showLoading(appId==='rule-repo'?'正在检查测试仓版本…':'正在读取程序 channels.json…');loading=true;var C='hiker://files/rules/asset-core-local/rule-repo-test/flat_control_v3.js',u=getPath(C);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}var x=appId==='rule-repo'?RuleRepoFlatControl.refreshSelf():RuleRepoFlatControl.refreshApp(appId,path);try{var E='hiker://files/rules/asset-core-local/rule-repo-test/flat_entry_v3.js',eu=getPath(E);try{require(eu);}catch(e2){try{deleteCache(eu);}catch(e3){}require(eu);}if(appId!=='rule-repo')RuleRepoFlatEntry.load().repairInstalledIdentity(appId);}catch(e4){}hideLoading();loading=false;refreshPage(false);return'toast://'+(appId==='rule-repo'?('测试仓已刷新 · '+x.version+' / Build'+x.build):('版本已刷新 · '+appId+' · '+x.versionCount+' 个通道 · max Build'+x.maxBuild));}catch(e){if(loading)try{hideLoading();}catch(_e){}return'toast://检查失败：'+String(e.message||e);}},id,cp);
  if(k==='load-channels')return $('#noLoading#').lazyRule(function(appId,path){try{var C='hiker://files/rules/asset-core-local/rule-repo-test/flat_control_v3.js',u=getPath(C);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}var m=RuleRepoFlatControl.readApp(appId),now=Date.now();if(!m||!m._fetchedAt||now-Number(m._fetchedAt)>300000){try{RuleRepoFlatControl.refreshApp(appId,path);}catch(e2){}}var E='hiker://files/rules/asset-core-local/rule-repo-test/flat_entry_v3.js',eu=getPath(E);try{require(eu);}catch(e3){try{deleteCache(eu);}catch(e4){}require(eu);}var r=RuleRepoFlatEntry.load();try{r.repairInstalledIdentity(appId);}catch(e5){}putVar('hc_repo_hybrid_pending_detail',appId);return'toast://版本信息已加载';}catch(e){putVar('hc_repo_hybrid_pending_detail',appId);return'toast://使用本地版本信息：'+String(e.message||e);}},id,cp);
  return typeof baseAction==='function'?baseAction.call(this,kind,item):'hiker://empty';
 };
 R.syncManifest=function(){return loadControl().syncAll();};R.lightSync=function(){return loadControl().syncAll();};
 R.workspaceStaticAction=function(kind){if(String(kind||'')!=='sync')return typeof baseStatic==='function'?baseStatic.call(this,kind):'hiker://empty';return $('#noLoading#').lazyRule(function(){var loading=false;try{showLoading('正在同步离线摘要…');loading=true;var C='hiker://files/rules/asset-core-local/rule-repo-test/flat_control_v3.js',u=getPath(C);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}var x=RuleRepoFlatControl.syncAll();hideLoading();loading=false;refreshPage(false);return x&&x.ok?'toast://同步完成 · revision '+String(x.revision||'--'):'toast://同步失败，保留本地数据';}catch(e){if(loading)try{hideLoading();}catch(_e){}return'toast://同步失败：'+String(e.message||e);}});};
 R.workspaceStaticActions=function(){var a=typeof baseStatics==='function'?baseStatics.call(this):{};a=a||{};a.sync=this.workspaceStaticAction('sync');return a;};
 R.settingsPage=function(){setPageTitle('设置');var d=[];d.push(this.hero('设置','RC35 · 每程序 channels.json 权威真相',this.uiIcon('settings'),'hiker://empty'));this.pushSection(d,'版本控制','首页快照只负责离线浏览；程序详情直接读取该程序 channels.json');d.push(this.quickAction('立即同步','sync',this.workspaceStaticAction('sync')));d.push(this.quickAction('版本更新','updates','hiker://page/ruleRepoUpdate?rule=&simple=true'));d.push(this.infoRow('自更新','不再依赖 GitHub API main HEAD'));d.push(this.infoRow('安装识别','导入记录 + 手机规则 numeric version 双重校验'));d.push(this.sectionLine());this.pushSection(d,'诊断','只读小控制面');d.push(this.quickAction('诊断信息','settings',$('#noLoading#').lazyRule(function(){try{var C='hiker://files/rules/asset-core-local/rule-repo-test/flat_control_v3.js',u=getPath(C);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}return'confirm://'+RuleRepoFlatControl.diagnostics();}catch(e){return'toast://诊断失败：'+String(e.message||e);}})));d.push(this.sectionLine());this.pushNav(d,'settings');setResult(d);};
 R.aboutPage=function(){setPageTitle('关于');var d=[],repo=this.findById('rule-repo')||{};d.push(this.hero('我的规则仓库','Flat Runtime · Per-App Channel Truth',this.iconOf(repo),'hiker://empty'));d.push(this.infoRow('当前 Core',VERSION));d.push(this.infoRow('Build',BUILD));d.push(this.infoRow('版本真相','per-app channels.json'));d.push(this.infoRow('自更新','main direct multi-source · no GitHub API HEAD'));d.push(this.infoRow('运行架构','single local bundle'));d.push(this.sectionLine());this.pushNav(d,'settings');setResult(d);};
 return R;
}
return{version:'1.0.0',apply:apply,selfMeta:currentMeta};
})();