/* 我的规则仓库 v3.3.0 - category management center */
(function(R){
R.categoryPage=function(){setPageTitle('分类管理');var d=[],items;try{items=this.items(false);}catch(e){setResult([{title:'仓库读取失败',desc:String(e.message||e),url:'hiker://empty',col_type:'long_text'}]);return;}var state=this.filterState();this.pushNav(d,'category');this.pushSection(d,'分类管理','按主分类、子分类、标签和运行模式定位程序。');
this.categories(items).forEach(function(c){d.push({title:(state.category===c.id?'● ':'')+c.name+' '+c.count,col_type:'text_3',url:$('#noLoading#').lazyRule(function(id){putMyVar('hc_repo_category',id);putMyVar('hc_repo_sub','all');putMyVar('hc_repo_tag','all');refreshPage(false);return'hiker://empty';},c.id),extra:{lineVisible:false}});});
var subs=this.subCategories(items,state.category);if(subs.length>1){this.pushSection(d,'子分类',state.category==='all'?'当前：全部程序':'当前：'+this.categoryName(state.category));subs.forEach(function(s){d.push({title:(state.subCategory===s.id?'● ':'')+s.name+' '+s.count,col_type:'text_3',url:$('#noLoading#').lazyRule(function(id){putMyVar('hc_repo_sub',id);putMyVar('hc_repo_tag','all');refreshPage(false);return'hiker://empty';},s.id),extra:{lineVisible:false}});});}
var fresh=this.filterState(),tags=this.tagsFor(items,fresh);if(tags.length){this.pushSection(d,'标签','高频标签');d.push({title:(fresh.tag==='all'?'● ':'')+'全部标签',col_type:'flex_button',url:$('#noLoading#').lazyRule(function(){putMyVar('hc_repo_tag','all');refreshPage(false);return'hiker://empty';})});tags.slice(0,12).forEach(function(t){d.push({title:(fresh.tag===t.name?'● ':'')+'#'+t.name+' '+t.count,col_type:'flex_button',url:$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_tag',v);refreshPage(false);return'hiker://empty';},t.name)});});}
this.pushSection(d,'筛选与排序','低频选项');[['全部模式','all'],['远程','remote'],['本地','local']].forEach(function(x){d.push({title:(fresh.mode===x[1]?'● ':'')+x[0],col_type:'flex_button',url:$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_mode',v);refreshPage(false);return'hiker://empty';},x[1])});});[['默认排序','default'],['最近更新','updated'],['名称','name'],['版本','version']].forEach(function(x){d.push({title:(fresh.sort===x[1]?'● ':'')+x[0],col_type:'flex_button',url:$('#noLoading#').lazyRule(function(v){putMyVar('hc_repo_sort',v);refreshPage(false);return'hiker://empty';},x[1])});});
var result=this.applyFilters(items,this.filterState());d.push({title:'程序  '+result.length,url:'hiker://empty',col_type:'text_2',extra:{lineVisible:false,textAlign:'left'}});d.push({title:'重置筛选',url:$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearAdvancedFilters();putMyVar('hc_repo_category','all');refreshPage(false);return'toast://分类筛选已重置';}),col_type:'text_2',extra:{lineVisible:false}});result.forEach(function(x){d.push(R.itemCard(x));});if(!result.length)this.pushEmpty(d,'没有匹配的程序','可以重置筛选条件后再试。');setResult(d);};
})(HikerRuleRepo);
