/* 我的规则仓库 Core v3.3.0 - repository/data/import layer */
var HikerRuleRepo={
version:'3.3.0',build:330,schema:7,title:'我的规则仓库',repo:'huoguotiankong/asset-core-7f3',branch:'main',manifestPath:'manifest.json',
cacheKey:'hc_repo_manifest_v3',cacheTsKey:'hc_repo_manifest_v3_ts',recentKey:'hc_repo_recent_v3',favKey:'hc_repo_favs_v3',installedKey:'hc_repo_installed_v3',searchHistoryKey:'hc_repo_search_history_v3',importHistoryKey:'hc_repo_import_history_v3',statePrefix:'hc_repo_v3_',defaultCacheMs:60000,iconRoot:'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/tools/rule-repo/assets/',
apiJson:function(path){var u='https://api.github.com/repos/'+this.repo+'/contents/'+String(path||'').replace(/^\/+/, '')+'?ref='+encodeURIComponent(this.branch)+'&_t='+Date.now();var t=fetch(u,{timeout:20000,headers:{Accept:'application/vnd.github+json','Cache-Control':'no-cache, no-store, max-age=0',Pragma:'no-cache'}});var j=JSON.parse(String(t||'{}'));if(!j||!j.content)throw new Error('GitHub读取失败：'+path);return j;},
apiText:function(path){return base64Decode(String(this.apiJson(path).content).replace(/\s+/g,''));},apiBytes:function(path){return java.util.Base64.getDecoder().decode(String(this.apiJson(path).content).replace(/\s+/g,''));},
sha256:function(bytes){var md=java.security.MessageDigest.getInstance('SHA-256'),a=md.digest(bytes),s='';for(var i=0;i<a.length;i++){var v=a[i];if(v<0)v+=256;var h=v.toString(16);if(h.length<2)h='0'+h;s+=h;}return s;},
unzipRule:function(bytes){var zis=new java.util.zip.ZipInputStream(new java.io.ByteArrayInputStream(bytes)),e,b=null;while((e=zis.getNextEntry())!==null){var n=String(e.getName()||'');if(n==='rule.json'||/\/rule\.json$/i.test(n)){b=new java.io.ByteArrayOutputStream();var buf=java.lang.reflect.Array.newInstance(java.lang.Byte.TYPE,4096),k;while((k=zis.read(buf))>0)b.write(buf,0,k);break;}}zis.close();if(b===null)throw new Error('hkzip中未找到rule.json');return String(new java.lang.String(b.toByteArray(),'UTF-8'));},
safeJson:function(s,f){try{return JSON.parse(String(s||''));}catch(e){return f;}},getSetting:function(k,d){return getItem(this.statePrefix+k,d==null?'':String(d));},setSetting:function(k,v){setItem(this.statePrefix+k,String(v==null?'':v));},cacheMs:function(){var n=Number(this.getSetting('cache_ms',this.defaultCacheMs));return n>=0?n:this.defaultCacheMs;},
manifest:function(force){var now=Date.now(),ts=Number(getItem(this.cacheTsKey,'0')||0);if(!force&&now-ts<this.cacheMs()){var c=getItem(this.cacheKey,'');if(c){var m=this.safeJson(c,null);if(m&&Array.isArray(m.items))return m;}}var x=JSON.parse(this.apiText(this.manifestPath));if(!x||!Array.isArray(x.items))throw new Error('manifest格式错误');setItem(this.cacheKey,JSON.stringify(x));setItem(this.cacheTsKey,String(now));return x;},clearManifestCache:function(){clearItem(this.cacheKey);clearItem(this.cacheTsKey);},lastManifestTime:function(){return Number(getItem(this.cacheTsKey,'0')||0);},
categoryName:function(id){var m={video:'视频',comic:'漫画',cloud:'网盘',tools:'工具',aggregate:'聚合',other:'其它'};return m[String(id||'')]||String(id||'其它');},normalizeItem:function(x,index){x=x||{};var c=String(x.category||'other');return{id:String(x.id||('item-'+index)),name:String(x.name||'未命名'),version:String(x.version||''),desc:String(x.desc||''),path:String(x.path||''),codec:String(x.codec||''),bytes:x.bytes,sha256:String(x.sha256||''),icon:String(x.icon||''),category:c,categoryName:String(x.categoryName||this.categoryName(c)),subCategory:String(x.subCategory||'其它'),tags:Array.isArray(x.tags)?x.tags.slice():[],mode:String(x.mode||'local'),updatedAt:String(x.updatedAt||''),sort:Number(x.sort==null?index:x.sort),featured:!!x.featured,raw:x};},items:function(force){var self=this,m=this.manifest(!!force);return(m.items||[]).map(function(x,i){return self.normalizeItem(x,i);});},
fallbackIcon:function(item){var m={video:'fallback_video.svg',comic:'fallback_comic.svg',cloud:'fallback_cloud.svg',tools:'fallback_tools.svg',aggregate:'fallback_aggregate.svg',other:'fallback_other.svg'};return this.iconRoot+(m[item&&item.category]||m.other);},iconOf:function(item){return item&&item.icon?String(item.icon):this.fallbackIcon(item);},
readList:function(k){var a=this.safeJson(getItem(k,'[]'),[]);return Array.isArray(a)?a:[];},writeList:function(k,a){setItem(k,JSON.stringify(a||[]));},
recordRecent:function(item){var a=this.readList(this.recentKey),id=String(item.id||item.name||'');a=a.filter(function(x){return String(x.id||'')!==id;});a.unshift({id:id,name:item.name,version:item.version,time:Date.now()});if(a.length>30)a=a.slice(0,30);this.writeList(this.recentKey,a);},recentIds:function(){return this.readList(this.recentKey).map(function(x){return String(x.id||'');});},clearRecent:function(){clearItem(this.recentKey);},
favIds:function(){return this.readList(this.favKey).map(String);},isFav:function(item){return this.favIds().indexOf(String(item.id||''))>=0;},toggleFav:function(item){var id=String(item.id||''),a=this.favIds(),i=a.indexOf(id),on;if(!id)return false;if(i>=0){a.splice(i,1);on=false;}else{a.unshift(id);on=true;}this.writeList(this.favKey,a);return on;},clearFavorites:function(){clearItem(this.favKey);},
installedMap:function(){var o=this.safeJson(getItem(this.installedKey,'{}'),{});return o&&typeof o==='object'?o:{};},recordInstalled:function(item){var o=this.installedMap();o[item.id]={version:item.version,time:Date.now(),name:item.name};setItem(this.installedKey,JSON.stringify(o));},installedVersion:function(item){var x=this.installedMap()[item.id];return x&&x.version?String(x.version):'';},clearInstalled:function(){clearItem(this.installedKey);},
versionCmp:function(a,b){a=String(a||'').replace(/^v/i,'').replace(/^remote-/,'');b=String(b||'').replace(/^v/i,'').replace(/^remote-/,'');var aa=a.split(/[^0-9A-Za-z]+/),bb=b.split(/[^0-9A-Za-z]+/),n=Math.max(aa.length,bb.length);for(var i=0;i<n;i++){var x=aa[i]||'0',y=bb[i]||'0',nx=Number(x),ny=Number(y);if(!isNaN(nx)&&!isNaN(ny)){if(nx!==ny)return nx>ny?1:-1;}else if(x!==y)return x>y?1:-1;}return 0;},statusOf:function(item){var v=this.installedVersion(item);if(!v)return'未记录';return this.versionCmp(item.version,v)>0?'可更新':'已同步';},findById:function(id,force){id=String(id||'');var a=this.items(!!force);for(var i=0;i<a.length;i++)if(a[i].id===id)return a[i];return null;},
recordSearch:function(kw){kw=String(kw||'').trim();if(!kw)return;var a=this.readList(this.searchHistoryKey).filter(function(x){return String(x)!==kw;});a.unshift(kw);if(a.length>12)a=a.slice(0,12);this.writeList(this.searchHistoryKey,a);},searchHistory:function(){return this.readList(this.searchHistoryKey).map(String);},clearSearchHistory:function(){clearItem(this.searchHistoryKey);},
recordImportHistory:function(item){var a=this.readList(this.importHistoryKey),id=String(item.id||'');a=a.filter(function(x){return String(x.id||'')!==id;});a.unshift({id:id,name:item.name,version:item.version,time:Date.now()});if(a.length>40)a=a.slice(0,40);this.writeList(this.importHistoryKey,a);},importHistory:function(){return this.readList(this.importHistoryKey);},clearImportHistory:function(){clearItem(this.importHistoryKey);},
importRule:function(raw){try{var x=typeof raw==='string'?JSON.parse(raw):raw;x=x&&x.raw?x.raw:x;if(!x)throw new Error('规则元数据为空');var item=this.normalizeItem(x,0);this.recordRecent(item);var ret;if(x.codec==='hkzip'){var b=this.apiBytes(x.path||'');if(x.bytes&&Number(x.bytes)!==b.length)return'toast://hkzip长度校验失败';if(x.sha256&&this.sha256(b).toLowerCase()!==String(x.sha256).toLowerCase())return'toast://hkzip SHA256校验失败';var o=JSON.parse(this.unzipRule(b));if(!o||!o.title)return'toast://rule.json内容无效';ret='海阔视界，首页频道￥home_rule￥'+JSON.stringify(o);}else{ret=this.apiText(x.path||'');if(!ret||ret.indexOf('海阔视界')!==0)return'toast://规则文件格式错误';}this.recordInstalled(item);this.recordImportHistory(item);return ret;}catch(e){return'toast://导入失败：'+String(e.message||e);}},
stats:function(items){var out={all:items.length,remote:0,local:0,installed:0,updates:0,favorites:this.favIds().length,recent:this.recentIds().length};for(var i=0;i<items.length;i++){var x=items[i];if(x.mode==='remote')out.remote++;else out.local++;var st=this.statusOf(x);if(st!=='未记录')out.installed++;if(st==='可更新')out.updates++;}return out;}
};
