/* 我的规则仓库 v3.3.0 - update center */
(function(R){
R.updatesPage=function(){setPageTitle('更新中心');var d=[],m,items;try{m=this.manifest(false);items=(m.items||[]).map(this.normalizeItem.bind(this));}catch(e){setResult([{title:'仓库读取失败',desc:String(e.message||e),url:'hiker://empty',col_type:'long_text'}]);return;}this.pushNav(d,'updates');var info={};try{if(typeof RuleRepoBoot==='object')info=RuleRepoBoot.info()||{};}catch(e){}var cur=info.current||{version:this.version,build:this.build},prev=info.previous||null,stats=this.stats(items),last=Number(getItem('hc_repo_updates_last_check','0')||0);
d.push({title:'规则仓库 Core '+cur.version,desc:'build '+cur.build+' · Schema '+(m.schema||'?')+'\n'+(prev?'上一稳定版 '+prev.version:'暂无回退记录'),img:this.iconOf(this.findById('rule-repo')||{}),pic_url:this.iconOf(this.findById('rule-repo')||{}),url:'hiker://page/ruleRepoUpdate?rule=&simple=true',col_type:'movie_1_left_pic',extra:{lineVisible:false,pageTitle:'Core 更新'}});
d.push({title:'Core 更新 / 回退',url:'hiker://page/ruleRepoUpdate?rule=&simple=true',col_type:'text_3',extra:{lineVisible:false}});d.push({title:'检查程序更新',url:$('#noLoading#').lazyRule(function(){showLoading('刷新云端索引…');try{var r=$.require('hiker://page/ruleRepoCore');r.clearManifestCache();r.manifest(true);setItem('hc_repo_updates_last_check',String(Date.now()));hideLoading();refreshPage(false);return'toast://程序版本状态已刷新';}catch(e){hideLoading();return'toast://检查失败：'+String(e.message||e);}}),col_type:'text_3',extra:{lineVisible:false}});d.push({title:'上次检查\n'+this.formatTime(last),url:'hiker://empty',col_type:'text_3',extra:{lineVisible:false}});
d.push(this.statCard('已记录',stats.installed,'hiker://empty'));d.push(this.statCard('可更新',stats.updates,'hiker://empty'));d.push(this.statCard('远程版',stats.remote,'hiker://empty'));d.push(this.statCard('本地版',stats.local,'hiker://empty'));
var updates=items.filter(function(x){return R.statusOf(x)==='可更新';});this.pushSection(d,'程序更新',updates.length?'发现 '+updates.length+' 个可更新程序':'当前没有可更新程序');updates.forEach(function(x){d.push(R.itemCard(x));});if(!updates.length)this.pushEmpty(d,'全部已是最新记录','点击“检查程序更新”可重新读取云端索引。');
var installed=items.filter(function(x){return R.statusOf(x)==='已同步';});if(installed.length){this.pushSection(d,'已同步','已记录且云端版本未变化');installed.forEach(function(x){d.push({title:x.name,desc:'v'+x.version,img:R.iconOf(x),pic_url:R.iconOf(x),url:'hiker://page/ruleRepoDetail?rule=&simple=true',col_type:'avatar',extra:{lineVisible:false,pageTitle:x.name,hc_repo_item_id:x.id}});});}
setResult(d);};
})(HikerRuleRepo);
