/* Hanime1 Test28 creator directory recovery: reuse Provider.search(type=artist) */
(function(C,P,E,H,L){
var RECENT='hanime_recent_artists28';
var oldResults=E.videoResultsPage;
function clean(v){return C.clean(String(v==null?'':v));}
function route(type,o){o=o||{};o.creatorType=type;return H.route('hanimeVideoResults',o);}
function remember(name,avatar,query,count){name=clean(name);if(!name)return;try{var a=JSON.parse(getItem(RECENT,'[]'));if(!Array.isArray(a))a=[];var out=[{name:name,avatar:avatar||'',query:query||name,count:count||''}];for(var i=0;i<a.length&&out.length<16;i++)if(clean(a[i].name)!==name)out.push(a[i]);setItem(RECENT,JSON.stringify(out));}catch(e){}}
function recents(){try{var a=JSON.parse(getItem(RECENT,'[]'));return Array.isArray(a)?a:[];}catch(e){return [];}}
P.artistDirectory28=function(query,page){var q=clean(query),p=Number(page||1);if(!q)return {items:recents(),page:1,totalPages:1,query:''};var r=P.search({query:q,type:'artist',page:p}),a=(r&&r.artists)||[],out=[];for(var i=0;i<a.length;i++){var x=a[i],it={name:x.title||x.name||q,avatar:x.img||x.avatar||'',query:x.query||x.title||q,count:x.meta||x.count||''};if(it.name){out.push(it);remember(it.name,it.avatar,it.query,it.count);}}return {items:out,page:p,totalPages:Number((r&&r.totalPages)||p),query:q};};
P.artistMeta28=function(name){name=clean(name);if(!name)return null;var a=P.artistDirectory28(name,1).items||[],pick=null;for(var i=0;i<a.length;i++){if(clean(a[i].name)===name){pick=a[i];break;}}if(!pick&&a.length)pick=a[0];return pick;};
function header(d,name,avatar,meta){d.push({title:name,desc:['作者',meta].filter(Boolean).join(' · '),pic_url:avatar||'',url:'hiker://empty',col_type:'avatar',extra:{lineVisible:false}});}
function directory(){var page=Number(H.pv('page','1')||1),q=H.pv('query',getMyVar('hanime28_artist_q','')),r=P.artistDirectory28(q,page),list=r.items||[],d=[];setPageTitle('作者目录');d.push({title:'搜索作者',url:"putMyVar('hanime28_artist_q',input);refreshPage(false);return 'hiker://empty';",col_type:'input',extra:{hint:'输入作者名并搜索',defaultValue:q,lineVisible:false}});d.push(H.btn('影片筛选',H.route('hanimeVideoFilter',{}),'text_2'));d.push(H.btn('综合搜索',H.route('hanimeSearch',{}),'text_2'));d.push(H.sec(q?('作者搜索 · '+q):'最近查看的作者',list.length?(q?('第 '+page+' 页 · '+list.length+' 位'):'点击作者进入作品页'):(q?'没有匹配作者':'先从视频详情打开作者，或在上方搜索。')));for(var i=0;i<list.length;i++){var x=list[i];d.push({title:x.name,desc:x.count||'查看作者作品',pic_url:x.avatar||'',url:route('artist',{creatorName:x.name,creatorQuery:x.query,creatorAvatar:x.avatar,creatorCount:x.count}),col_type:'avatar',extra:{lineVisible:false}});}if(q&&page>1)d.push(H.btn('‹ 上一页',route('directory',{query:q,page:page-1})));if(q&&page<Number(r.totalPages||page))d.push(H.btn('下一页 ›',route('directory',{query:q,page:page+1})));setResult(d);}
function artist(){var page=Number(H.pv('page','1')||1),name=H.pv('creatorName',''),query=H.pv('creatorQuery','')||name,avatar=H.pv('creatorAvatar',''),count=H.pv('creatorCount','');if(!name)throw new Error('缺少作者名称');if(!avatar||query===name){try{var m=P.artistMeta28(name);if(m){avatar=avatar||m.avatar||'';count=count||m.count||'';query=m.query||query;}}catch(e){}}remember(name,avatar,query,count);var r=P.search({query:query,page:page,type:''}),list=(r&&r.items)||[],d=[];setPageTitle(name);header(d,name,avatar,count||('第 '+page+' 页'));d.push(H.btn('搜索同名影片',H.route('hanimeVideoResults',{query:query}),'text_2'));d.push(H.btn('返回作者目录',route('directory',{query:name}),'text_2'));d.push(H.sec('作者作品',list.length?('第 '+page+' 页 · '+list.length+' 部'):'当前页暂无匹配作品'));for(var i=0;i<list.length;i++)d.push(L.video(list[i],'results'));if(page>1)d.push(H.btn('‹ 上一页',route('artist',{creatorName:name,creatorQuery:query,creatorAvatar:avatar,creatorCount:count,page:page-1})));if(page<Number(r.totalPages||page))d.push(H.btn('下一页 ›',route('artist',{creatorName:name,creatorQuery:query,creatorAvatar:avatar,creatorCount:count,page:page+1})));setResult(d);}
E.videoResultsPage=function(){var type=H.pv('creatorType','');try{if(type==='directory')return directory();if(type==='artist')return artist();return oldResults();}catch(x){setResult([{title:'创作者页面加载失败',desc:String(x.message||x),url:'hiker://empty',col_type:'text_center_1'}]);}};
P.rememberArtist28=remember;
})(HanimeCore,HanimeProvider,HanimePages,HanimeUI9,HanimeLayout12);
