/* JavDB v3 3.9.52-test.1 · magnet long-press menu cleanup */
var JavDBMagnet3952=(function(){
var VERSION='3.9.52-test.1',BUILD=2026092206;
var ROOT='hiker://files/rules/asset-core-local/javdb-v3-test/b2026092206/';
var ENTRY=ROOT+'local_entry.js',BASE_ENTRY=ROOT+'base_3951_entry.js';
var BASE_REF='763a164503a9593049dca9a3e35751ea39b5c26e';
var BASE_PATH='apps/video/javdb/releases/3.9.51-test.1/local_entry.js';
var BASE_CACHE=null;
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function urls(ref,path){return['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/'+ref+'/'+path,'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@'+ref+'/'+path,'https://github.com/huoguotiankong/asset-core-7f3/raw/'+ref+'/'+path];}
function ensureFile(local,ref,path,marker){if(fileExist(local)){try{var old=String(readFile(local)||'');if(!bad(old)&&old.indexOf(marker)>=0)return local;}catch(_e){}try{deleteFile(local);}catch(_e2){}}var us=urls(ref,path),es=[],i,s='';for(i=0;i<us.length;i++){try{s=String(fetch(us[i],{timeout:6500,headers:{'Cache-Control':'public, max-age=31536000, immutable'}})||'');if(bad(s)||s.indexOf(marker)<0)throw new Error('无效响应');writeFile(local,s);if(!fileExist(local))throw new Error('写入失败');return local;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(path+' 下载失败：'+es.join(' | '));}
function base(){if(BASE_CACHE&&typeof BASE_CACHE.module==='function')return BASE_CACHE;ensureFile(BASE_ENTRY,BASE_REF,BASE_PATH,'3.9.51-test.1');var src=String(readFile(BASE_ENTRY)||''),JavDBLocal=null;if(bad(src)||src.indexOf('3.9.51-test.1')<0)throw new Error('JavDB 3.9.51 Base Entry 内容无效');eval(src);if(!JavDBLocal||typeof JavDBLocal.module!=='function')throw new Error('JavDB 3.9.51 Base Entry 未导出');BASE_CACHE=JavDBLocal;return BASE_CACHE;}
function magnetFromString(v){var s=String(v==null?'':v).replace(/&amp;/gi,'&'),m=null,d='';m=s.match(/magnet:\?xt=urn:btih:[^\"'<>\\\s]+/i);if(m)return String(m[0]);if(/%3A|%3F|%3D/i.test(s)){try{d=decodeURIComponent(s);m=d.match(/magnet:\?xt=urn:btih:[^\"'<>\\\s]+/i);if(m)return String(m[0]).replace(/&amp;/gi,'&');}catch(_e){}}return'';}
function findMagnet(v,depth,seen){if(depth>6||v==null)return'';var t=typeof v,m='',i,k,keys;if(t==='string'||t==='number')return magnetFromString(v);if(t!=='object')return'';seen=seen||[];for(i=0;i<seen.length;i++)if(seen[i]===v)return'';seen.push(v);keys=['magnet','url','href','link','input','value','js'];for(i=0;i<keys.length;i++){k=keys[i];try{if(v[k]!=null){m=findMagnet(v[k],depth+1,seen);if(m)return m;}}catch(_e2){}}if(v instanceof Array){for(i=0;i<v.length;i++){m=findMagnet(v[i],depth+1,seen);if(m)return m;}return'';}for(k in v){if(!Object.prototype.hasOwnProperty.call(v,k)||keys.indexOf(k)>=0)continue;try{m=findMagnet(v[k],depth+1,seen);if(m)return m;}catch(_e3){}}return'';}
function copyObj(a,title){var b={},k;if(!a||typeof a!=='object')return null;for(k in a)if(Object.prototype.hasOwnProperty.call(a,k))b[k]=a[k];b.title=title;return b;}
function action115(magnet){return{title:'115',js:$.toString(function(m){m=String(m||'').replace(/&amp;/gi,'&').trim();if(!m||m.indexOf('magnet:?')!==0)return'toast://未识别到磁力链接';return'hiker://page/115Offline?rule=115.简&page=fypage&add='+encodeURIComponent(m);},magnet)};}
function actionCopy(magnet){return{title:'复制磁链',js:$.toString(function(m){m=String(m||'').replace(/&amp;/gi,'&').trim();if(!m)return'toast://未识别到磁力链接';return'copy://'+m;},magnet)};}
function actionKind(title){var t=String(title||'').replace(/\s+/g,' ').trim();if(!t)return'';if(/115/.test(t))return'115';if(/迅雷|xunlei|thunder/i.test(t))return'xunlei';if(/pik\s*pak|pikpak/i.test(t))return'pikpak';if(/光鸭|guang\s*ya|guangya/i.test(t))return'guangya';if(/123\s*(?:云盘|网盘|播放|av)?/i.test(t))return'123';if(/复制.*(?:磁链|磁力|magnet)|(?:磁链|磁力).*复制|copy.*magnet/i.test(t))return'copy';return'';}
function patchMagnetMenu(items){if(!(items instanceof Array))return items;var i,j,x,ex,old,m,a,k,slots,names={xunlei:'迅雷',pikpak:'PikPak',guangya:'光鸭','123':'123'};for(i=0;i<items.length;i++){x=items[i];if(!x||typeof x!=='object')continue;m=findMagnet(x,0,[]);if(!m)continue;ex=x.extra;if(!ex||typeof ex!=='object'){ex={};x.extra=ex;}old=ex.longClick instanceof Array?ex.longClick:[];slots={};for(j=0;j<old.length;j++){a=old[j];if(!a||typeof a!=='object')continue;k=actionKind(a.title);if(k&&!slots[k])slots[k]=a;}var out=[];out.push(slots['115']?copyObj(slots['115'],'115'):action115(m));if(slots.xunlei)out.push(copyObj(slots.xunlei,names.xunlei));if(slots.pikpak)out.push(copyObj(slots.pikpak,names.pikpak));if(slots.guangya)out.push(copyObj(slots.guangya,names.guangya));if(slots['123'])out.push(copyObj(slots['123'],names['123']));out.push(slots.copy?copyObj(slots.copy,'复制磁链'):actionCopy(m));ex.longClick=out;}return items;}
function capture(run,patch){var oldSet=null,got=null,hooked=false,err=null,ret=null;try{oldSet=setResult;var cap=function(v){got=v;};setResult=cap;hooked=(setResult===cap);}catch(e){hooked=false;}if(!hooked){ret=run();return ret instanceof Array?patch(ret):ret;}try{ret=run();}catch(e2){err=e2;}finally{try{setResult=oldSet;}catch(_e){}}if(err)throw err;if(got instanceof Array)return oldSet(patch(got));if(got!=null)return oldSet(got);return ret instanceof Array?patch(ret):ret;}
function module(){var b=base(),m=b.module();if(!m||typeof m.custom!=='function')throw new Error('JavDB 3.9.51 Base Module 未就绪');var oldCustom=m.custom;m.custom=function(key){if(key==='javdb3Magnets')return capture(function(){return oldCustom.call(m,key);},patchMagnetMenu);return oldCustom.call(m,key);};m.version=VERSION;m.build=BUILD;m.magnetLongPressMenu='115>xunlei>pikpak>guangya>123>copy';m.vipPlaybackBase='3.9.51-test.1';return m;}
function info(){var b=base(),x={};try{x=b.info?b.info():{};}catch(e){x={ready:false,error:String(e.message||e)};}x.version=VERSION;x.build=BUILD;x.baseVersion='3.9.51-test.1';x.magnetMenuClean=true;x.magnetMenuOrder=['115','迅雷','PikPak','光鸭','123','复制磁链'];x.vipPlaybackUnchanged=true;return x;}
function statusPage(){setPageTitle('JavDB · 磁链菜单诊断');var d=[];d.push({title:'JavDB v3 '+VERSION,desc:'Build '+BUILD+' · 磁链长按菜单收敛',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'保留并固定顺序',desc:'115 → 迅雷 → PikPak → 光鸭 → 123 → 复制磁链',url:'hiker://empty',col_type:'text_2',extra:{lineVisible:false}});d.push({title:'已移除',desc:'网盘播放中心及其它未指定长按项',url:'hiker://empty',col_type:'text_2',extra:{lineVisible:false}});d.push({title:'VIP 播放',desc:'本版不再修改播放链，完全继承 3.9.51-test.1；本轮只验证磁链长按交互。',url:'hiker://empty',col_type:'text_2',extra:{lineVisible:false}});setResult(d);}
return{version:VERSION,build:BUILD,module:module,info:info,statusPage:statusPage,entry:ENTRY,builder:function(){var b=base();return b.builder?b.builder():null;},patch:function(force){var b=base();return b.patch?b.patch(force):null;},upgrade:function(force){var b=base();return b.upgrade?b.upgrade(force):null;}};
})();
var JavDBLocal=JavDBMagnet3952;
