/* 汤头条 0.1.0-test.20 Pages / dynamic channel adapters + creator/rank/community + comic detail/read */
var TangTouTiaoPagesV027=(function(){
  var B=TangTouTiaoPagesV026,P=TangTouTiaoProtocolV015,C=TangTouTiaoCoreV024,U=TangTouTiaoUIV015,O={};for(var k in B)if(B.hasOwnProperty(k))O[k]=B[k];
  var NAV_TTL=600000;
  function txt(v){return C.text?C.text(v):String(v==null?'':v).replace(/<[^>]+>/g,'').trim();}
  function val(o,ks,d){return C.pick?C.pick(o,ks,d):d;}
  function js(v){if(typeof v!=='string')return v;var s=String(v||'').trim();if(!s)return v;if((s.charAt(0)==='{'&&s.charAt(s.length-1)==='}')||(s.charAt(0)==='['&&s.charAt(s.length-1)===']'))try{return JSON.parse(s);}catch(e){}return v;}
  function clone(o){var r={};o=js(o);if(o&&typeof o==='object'&&!Array.isArray(o))for(var k in o)if(o.hasOwnProperty(k))r[k]=o[k];return r;}
  function arr(v){v=js(v);return Array.isArray(v)?v:[];}
  function firstObj(root,keys){root=js(root);if(!root)return{};if(typeof root==='object'&&!Array.isArray(root)){for(var i=0;i<keys.length;i++){var x=root[keys[i]];if(x&&typeof x==='object'&&!Array.isArray(x))return x;}}return root&&typeof root==='object'&&!Array.isArray(root)?root:{};}
  function image(raw){return raw?C.imageUrl(raw):'';}
  function navCache(kind,path,payload){var key='ttt20_nav_'+kind;try{var s=getMyVar(key,'');if(s){var c=JSON.parse(s);if(c&&Date.now()-Number(c.time||0)<NAV_TTL&&Array.isArray(c.data)){return{tabs:C.comicCategories(c.data),res:null,cache:true};}}}catch(e0){}var r=P.call(path,payload||{}),data=C.dataOf(r),tabs=C.comicCategories(r);try{if(Array.isArray(data))putMyVar(key,JSON.stringify({time:Date.now(),data:data}));}catch(e1){}return{tabs:tabs,res:r,cache:false};}
  function renderTabs(d,kind,tabs){if(!tabs.length)return-1;var key='ttt20_'+kind+'_tab',cur=Number(getMyVar(key,'-1')),found=false;if(cur>=0&&cur<tabs.length)found=true;if(!found){cur=0;for(var i=0;i<tabs.length;i++)if(tabs[i].current){cur=i;break;}}for(var j=0;j<tabs.length;j++)d.push(U.chip(tabs[j].name,j===cur,U.state(key,String(j))));d.push(U.line());return cur;}
  function callTab(tab,page){if(!tab||!tab.apiList)return null;var p=clone(tab.params||{});if(p.page==null)p.page=page||1;return P.call(String(tab.apiList),p);}
  function walk(root,kind){var out=[],seen={};function add(x){x=js(x);if(!x||typeof x!=='object'||Array.isArray(x))return;var id=String(val(x,['id','_id','book_id','audio_id'],'')||''),name=txt(val(x,['name','title'],'')||'');var ok=false;if(kind==='novel')ok=!!(id&&name&&(x.thumbnail||x.chapter_count!==undefined||x.word_count!==undefined||x.author));else if(kind==='audio')ok=!!(id&&name&&(x.thumbnail||x.chapter_count!==undefined||x.cur_chapter||x.author));else if(kind==='community')ok=!!(id&&(x.title||x.content||x.txt)&&(x.user||x.uuid||x.imgs||x.videos||x.comment_num!==undefined||x.view_num!==undefined));else if(kind==='chapter')ok=!!(id&&name&&(x.chapter!==undefined||x.novel_id!==undefined||x.audio_id!==undefined));else if(kind==='episode')ok=!!((x.comic_id!==undefined||x.episode!==undefined)&&x.episode!==undefined);if(ok){var key=kind+'|'+id+'|'+(name||String(x.episode||''));if(!seen[key]){seen[key]=1;out.push(x);}}}
    function rec(v,depth){if(depth>8||v==null)return;v=js(v);if(Array.isArray(v)){for(var i=0;i<v.length;i++)rec(v[i],depth+1);return;}if(typeof v==='object'){add(v);for(var k in v)if(v.hasOwnProperty(k)&&!/banner|ads|advert|hot_conf/i.test(k))rec(v[k],depth+1);}}rec(C.dataOf(root),0);return out;}
  function nestedMedia(x){var sets=[x&&x.imgs,x&&x.medias,x&&x.videos];for(var s=0;s<sets.length;s++){var a=arr(sets[s]);for(var i=0;i<a.length;i++){var m=js(a[i]);if(typeof m==='string'&&/^https?:/i.test(m))return m;if(m&&typeof m==='object'){var u=val(m,['thumb','img_url','media_url','url','src'],'');if(u)return u;}}}return'';}
  function userOf(x){var u=x&&x.user&&typeof x.user==='object'?x.user:x&&x.member&&typeof x.member==='object'?x.member:{};return{nickname:txt(val(u,['nickname','username'],val(x||{},['nickname'],'')||'')),thumb:val(u,['thumb','thumb_url','avatar'],val(x||{},['thumb'],'')||'')||''};}
  function contentCard20(x,kind){var id=String(val(x,['id','_id'],'')||''),title=txt(val(x,['name','title'],'未命名')),desc=[],raw='';if(kind==='novel'||kind==='audio'){raw=val(x,['thumbnail','thumb','cover'],'')||'';var iu=image(raw);var au=txt(val(x,['author'],'')||'');if(au)desc.push(au);var cc=val(x,['chapter_count'],'');if(cc!==''&&cc!=null)desc.push(cc+' 章');var tg=txt(val(x,['tags'],'')||'');if(tg)desc.push(tg);return{title:title,desc:desc.join(' · '),img:iu,pic_url:iu,url:C.page('tttChannel',{type:'contentDetail20',kind:kind,id:id,title:title}),col_type:'movie_3',extra:{lineVisible:false}};}
    var u=userOf(x);title=txt(val(x,['title','content','txt'],'动态'));if(title.length>60)title=title.substring(0,60)+'…';raw=nestedMedia(x);if(u.nickname)desc.push(u.nickname);var cm=val(x,['comment_num'],'');if(cm!==''&&cm!=null)desc.push('评论 '+cm);var lk=val(x,['like_num'],'');if(lk!==''&&lk!=null)desc.push('赞 '+lk);var vw=val(x,['view_num'],'');if(vw!==''&&vw!=null)desc.push('浏览 '+vw);var pi=raw?image(raw):'';return{title:title,desc:desc.join(' · '),img:pi,pic_url:pi,url:C.page('tttChannel',{type:'communityDetail20',id:id,title:title}),col_type:raw?'pic_1_card':'text_1',extra:{lineVisible:false}};}
  function dynamicHome(d,kind,title,path,payload){var h=navCache(kind,path,payload),tabs=h.tabs||[];d.push(U.section(title,tabs.length+' 个频道'+(h.cache?' · 已缓存':'')));if(!tabs.length){var rr=h.res||{};var mm=P.meta(rr,path);d.push(U.empty('当前频道配置为空',(mm.code!==''?'code '+mm.code+' · ':'')+(mm.msg||mm.schema||'')));return;}var idx=renderTabs(d,kind,tabs),tab=tabs[idx],pg=Number(MY_PAGE||1),r=callTab(tab,pg);if(!r){d.push(U.empty('当前频道缺少 api_list'));return;}var list=walk(r,kind);d.push(U.section(tab.name,list.length+' 条'));for(var i=0;i<list.length;i++)d.push(contentCard20(list[i],kind));if(!list.length){var m=P.meta(r,tab.apiList);d.push(U.empty('当前频道暂无可显示内容',(m.code!==''?'code '+m.code+' · ':'')+(m.msg||m.schema||'')));}try{setItem('ttt_last_dynamic_channel',JSON.stringify({time:Date.now(),kind:kind,tab:tab.name,api:tab.apiList,params:tab.params,count:list.length,schema:P.schema(C.dataOf(r))}));}catch(e){}
  }
  function creatorCard20(x){var meta=['视频 '+Number(x.videos||0),'粉丝 '+Number(x.followers||0)];if(x.vip)meta.push(x.vip);if(x.auth)meta.push(x.auth);return{title:'#'+Number(x.rank||0)+'  '+String(x.nickname||'创作者'),desc:meta.join(' · '),img:x.cover||'',pic_url:x.cover||'',url:C.page('tttChannel',{type:'creatorDetail20',uuid:x.uuid,title:x.nickname}),col_type:'movie_1_left_pic',extra:{lineVisible:false,ttt_creator_uuid:x.uuid}};}
  function creatorDiscover(d){var r=P.call('/api/RankList/getPlayRank',{type:'all'}),list=C.rankCreators(r);d.push(U.section('精选创作者',list.length+' 位 · 来自总榜'));for(var i=0;i<list.length;i++)d.push(creatorCard20(list[i]));if(!list.length){var m=P.meta(r,'/api/RankList/getPlayRank');d.push(U.empty('暂未取得创作者列表',(m.code!==''?'code '+m.code+' · ':'')+(m.msg||m.schema||'')));}try{setItem('ttt_last_creator_discover',JSON.stringify({time:Date.now(),count:list.length,schema:P.schema(C.dataOf(r))}));}catch(e){}
  }
  function creatorDetail(d,uuid,title){if(!uuid){d.push(U.empty('缺少创作者 UUID'));return;}var r=P.call('/api/Creator/featured',{uuid:String(uuid),lastId:0,limit:10}),list=C.normalize(r,'')||[];d.push(U.section(title||'创作者作品','精选作品 '+list.length+' 条'));for(var i=0;i<list.length;i++)d.push(U.videoCard(C,list[i],'movie_2'));if(!list.length){var m=P.meta(r,'/api/Creator/featured');d.push(U.empty('当前创作者暂无可显示作品',(m.code!==''?'code '+m.code+' · ':'')+(m.msg||m.schema||'')));}try{setItem('ttt_last_creator_featured',JSON.stringify({time:Date.now(),uuid:uuid,count:list.length,schema:P.schema(C.dataOf(r))}));}catch(e){}
  }
  function rank20(){var d=[],key='ttt20_rank_type',type=String(getMyVar(key,'all')||'all'),allow={all:1,daily:1,weekly:1,monthly:1};if(!allow[type])type='all';setPageTitle('排行榜');var tabs=[['all','总榜'],['daily','日榜'],['weekly','周榜'],['monthly','月榜']];for(var i=0;i<tabs.length;i++)d.push(U.chip(tabs[i][1],type===tabs[i][0],U.state(key,tabs[i][0])));d.push(U.line());try{var r=P.call('/api/RankList/getPlayRank',{type:type}),list=C.rankCreators(r);d.push(U.section('创作者播放榜',list.length+' 位'));for(var j=0;j<list.length;j++)d.push(creatorCard20(list[j]));if(!list.length){var m=P.meta(r,'/api/RankList/getPlayRank');d.push(U.empty('当前榜单暂无内容',(m.code!==''?'code '+m.code+' · ':'')+(m.msg||m.schema||'')));}try{setItem('ttt_last_rank_exact',JSON.stringify({time:Date.now(),type:type,count:list.length,schema:P.schema(C.dataOf(r))}));}catch(e0){}}catch(e){d.push(U.error('排行榜加载失败',e,C.page('tttSettings')));}setResult(d);}
  function detailRecord(root,kind,id){var a=walk(root,kind);for(var i=0;i<a.length;i++)if(String(val(a[i],['id'],'')||'')===String(id))return a[i];var d=C.dataOf(root);if(d&&typeof d==='object'&&!Array.isArray(d)){var x=firstObj(d,['detail','data','audio','novel']);if(x&&typeof x==='object')return x;}return{};}
  function contentDetail20(d,kind,id,title){var ep=kind==='novel'?'/api/novel/detail':'/api/audio/detail',r=P.call(ep,{id:Number(id)}),x=detailRecord(r,kind,id),name=txt(val(x,['name','title'],title||'详情')),raw=val(x,['thumbnail','thumb','cover'],'')||'',hero=image(raw),desc=txt(val(x,['description','desc'],'')||''),meta=[];var au=txt(val(x,['author'],'')||'');if(au)meta.push(au);var cc=val(x,['chapter_count'],'');if(cc!==''&&cc!=null)meta.push(cc+' 章');var tg=txt(val(x,['tags'],'')||'');if(tg)meta.push(tg);d.push({title:name,desc:meta.join(' · '),img:hero,pic_url:hero,url:'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});if(desc){d.push(U.line());d.push(U.section('简介',''));d.push({title:desc,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});}var chRes=null,chs=[];if(kind==='novel'){chRes=P.call('/api/novel/chaptersList',{id:Number(id),limit:50,page:1});chs=walk(chRes,'chapter');}else{chRes=P.call('/api/audio/chaptersList',{id:Number(id),limit:50,page:1});chs=walk(chRes,'chapter');if(!chs.length){chRes=P.call('/api/audio/chaptersList',{audio_id:Number(id),limit:50,page:1});chs=walk(chRes,'chapter');}}d.push(U.line());d.push(U.section('章节',chs.length+' 章'));for(var i=0;i<chs.length;i++){var c=chs[i],cid=String(val(c,['id'],'')||''),ct=txt(val(c,['name','title'],'第 '+(i+1)+' 章')),money=Number(val(c,['coins'],0)||0),dur=txt(val(c,['duration_str'],'')||'');d.push({title:ct,desc:[dur,money>0?money+' 汤币':''].filter(Boolean).join(' · '),url:C.page('tttChannel',{type:kind==='novel'?'novelChapter20':'audioChapter20',parent_id:id,chapter_id:cid,title:ct}),col_type:'text_1',extra:{lineVisible:false}});}if(!chs.length){var mm=P.meta(chRes||{},'');d.push(U.empty('暂未取得章节',(mm.code!==''?'code '+mm.code+' · ':'')+(mm.msg||mm.schema||'')));}try{setItem('ttt_last_content_detail',JSON.stringify({time:Date.now(),kind:kind,id:id,chapters:chs.length,detailSchema:P.schema(C.dataOf(r)),chapterSchema:P.schema(C.dataOf(chRes||{}))}));}catch(e){}
  }
  function novelChapter(d,pid,cid,title){var r=P.call('/api/novel/chapterDetail',{novel_id:Number(pid),chapter_id:Number(cid)}),root=C.dataOf(r)||{},x=firstObj(root,['detail','data']),t=txt(val(x,['title','name'],title||'章节')),content=txt(val(x,['content','text'],'')||'');d.push(U.section(t,''));if(content)d.push({title:content,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});else{var m=P.meta(r,'');d.push(U.empty('正文暂未返回',(m.code!==''?'code '+m.code+' · ':'')+(m.msg||m.schema||'')));}}
  function audioChapter(d,pid,cid,title){var r=P.call('/api/audio/chapterDetail',{audio_id:Number(pid),chapter_id:Number(cid)}),root=C.dataOf(r)||{},x=firstObj(root,['detail','chapter','data']),m3u8=String(val(x,['m3u8','url','play_url'],'')||''),dur=txt(val(x,['duration_str'],'')||'');d.push(U.section(title||txt(val(x,['name'],'有声章节')),dur));if(m3u8)d.push({title:'▶ 播放本章',desc:'使用章节接口返回的原始音频线路',url:$('#noLoading#').lazyRule(function(u){return String(u||'')+'#isVideo=true#';},m3u8),col_type:'text_1',extra:{lineVisible:false}});else{var m=P.meta(r,'');d.push(U.empty('当前章节没有可播放线路',(m.code!==''?'code '+m.code+' · ':'')+(m.msg||m.schema||'')));}}
  function communityCardDetail(d,id,title){var r=P.call('/api/community/post_detail',{id:Number(id)}),root=C.dataOf(r)||{},post=firstObj(root,['detail','post','data']),t=txt(val(post,['title','content','txt'],title||'社区动态')),u=userOf(post),content=txt(val(post,['content','txt'],'')||'');d.push(U.section(t,u.nickname||''));if(content)d.push({title:content,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});var medias=[post.imgs,post.medias,post.videos];var n=0;for(var s=0;s<medias.length;s++){var aa=arr(medias[s]);for(var i=0;i<aa.length&&n<20;i++){var mm=js(aa[i]),raw=typeof mm==='string'?mm:val(mm,['img_url','media_url','thumb','url'],'')||'';if(!raw)continue;var iu=image(raw);d.push({title:'',img:iu,pic_url:iu,url:'hiker://empty',col_type:'pic_1_full',extra:{lineVisible:false}});n++;}}var comments=root.comment_list||root.comments||[];if(Array.isArray(comments)&&comments.length){d.push(U.line());d.push(U.section('评论',comments.length+' 条'));for(var j=0;j<comments.length&&j<30;j++){var c=js(comments[j])||{},cu=userOf(c),ct=txt(val(c,['comment','content'],'')||'');if(ct)d.push({title:cu.nickname?cu.nickname+'：'+ct:ct,desc:txt(val(c,['created_at','cityname'],'')||''),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});}}try{setItem('ttt_last_community_detail',JSON.stringify({time:Date.now(),id:id,medias:n,comments:Array.isArray(comments)?comments.length:0,schema:P.schema(root)}));}catch(e){}
  }
  function comicHome20(d){var r=P.call('/api/comic/home',{}),cats=C.comicCategories(r);d.push(U.section('漫画分类',cats.length+' 个分类'));for(var i=0;i<cats.length;i++){var c=cats[i];d.push(U.chip(c.name,!!c.current,C.page('tttChannel',{type:'comicList20',title:c.name,comic_api:String(c.apiList||''),comic_params:JSON.stringify(c.params||{})})));}if(!cats.length){var m=P.meta(r,'');d.push(U.empty('漫画分类为空',(m.code!==''?'code '+m.code+' · ':'')+(m.msg||m.schema||'')));}}
  function comicList20(d,title){var api=String(C.param('comic_api','')||''),raw=String(C.param('comic_params','{}')||'{}'),params={};try{params=JSON.parse(raw);}catch(e){}if(!params||typeof params!=='object'||Array.isArray(params))params={};if(params.page==null)params.page=Number(MY_PAGE||1);if(!api){d.push(U.empty('该漫画分类缺少 api_list'));return;}var r=P.call(api,params),list=C.comicList(r);d.push(U.section(title,list.length+' 部'));for(var i=0;i<list.length;i++){var x=list[i];d.push({title:x.title||'未命名',desc:x.desc||'',img:x.cover||'',pic_url:x.cover||'',url:C.page('tttChannel',{type:'comicDetail20',id:x.id,title:x.title}),col_type:'movie_3',extra:{lineVisible:false,ttt_comic_id:x.id}});}if(!list.length){var m=P.meta(r,'');d.push(U.empty('当前漫画分类暂无内容',(m.code!==''?'code '+m.code+' · ':'')+(m.msg||m.schema||'')));}}
  function comicDetail20(d,id,title){var r=P.call('/api//book/detail',{id:String(id)}),root=C.dataOf(r)||{},x=firstObj(root,['detail','data']),name=txt(val(x,['title','name'],title||'漫画详情')),raw=val(x,['thumb','re_thumb','cover'],'')||'',hero=image(raw),desc=txt(val(x,['description','desc'],'')||''),meta=[];var au=txt(val(x,['author'],'')||'');if(au)meta.push(au);var cats=txt(val(x,['categories','tags'],'')||'');if(cats)meta.push(cats);d.push({title:name,desc:meta.join(' · '),img:hero,pic_url:hero,url:'hiker://empty',col_type:'movie_1_vertical_pic_blur',extra:{lineVisible:false}});if(desc){d.push(U.line());d.push(U.section('简介',''));d.push({title:desc,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});}var er=P.call('/api/book/list_episode',{id:String(id),sort:'asc'}),eps=walk(er,'episode');d.push(U.line());d.push(U.section('章节',eps.length+' 话'));for(var i=0;i<eps.length;i++){var ep=eps[i],num=String(val(ep,['episode'],'')||''),et=txt(val(ep,['episode_title'],'')||('第 '+num+' 话')),money=Number(val(ep,['view_money'],0)||0);d.push({title:et,desc:money>0?money+' 汤币':'',url:C.page('tttChannel',{type:'comicRead20',book_id:id,chapter_id:num,title:et}),col_type:'text_3',extra:{lineVisible:false}});}if(!eps.length){var m=P.meta(er,'');d.push(U.empty('暂未取得漫画章节',(m.code!==''?'code '+m.code+' · ':'')+(m.msg||m.schema||'')));}try{setItem('ttt_last_comic_detail',JSON.stringify({time:Date.now(),id:id,episodes:eps.length,detailSchema:P.schema(root),episodeSchema:P.schema(C.dataOf(er))}));}catch(e){}
  }
  function comicRead20(d,bid,cid,title){var r=P.call('/api/book/read',{book_id:Number(bid),chapter_id:Number(cid)}),root=C.dataOf(r)||{},read=arr(root.read||root.list||root.data),shown=0;d.push(U.section(title||'漫画阅读',read.length+' 页'));for(var i=0;i<read.length;i++){var x=js(read[i]),raw=typeof x==='string'?x:val(x,['img_url','url','src'],'')||'';if(!raw)continue;var iu=image(raw);d.push({title:'',img:iu,pic_url:iu,url:'hiker://empty',col_type:'pic_1_full',extra:{lineVisible:false}});shown++;}if(!shown){var m=P.meta(r,'');d.push(U.empty('当前章节暂未返回漫画图片',(m.code!==''?'code '+m.code+' · ':'')+(m.msg||m.schema||'')));}try{setItem('ttt_last_comic_read',JSON.stringify({time:Date.now(),book_id:bid,chapter_id:cid,pages:shown,schema:P.schema(root)}));}catch(e){}
  }
  function searchInput(d){d.push({title:'搜索视频、创作者、关键词',col_type:'input',url:$.toString(function(){var w=String(input||'').trim();if(!w)return'toast://请输入搜索关键词';putMyVar('ttt_search_kw',w);return'hiker://page/tttSearch?rule=&simple=true&kw='+encodeURIComponent(w);}),extra:{defaultValue:'',titleVisible:true,onChange:$.toString(function(){})}});}
  function headerCommunity(d){searchInput(d);var key='ttt_home_tab_v010',tab='community',tabs=[['recommend','推荐'],['short','短视频'],['long','长视频'],['community','社区']];for(var i=0;i<tabs.length;i++)d.push(U.chip(tabs[i][1],tabs[i][0]===tab,U.state(key,tabs[i][0])));d.push(U.blank());var q=[['频道','channel',C.page('tttChannels')],['社区','community',C.page('tttCommunity')],['排行榜','rank',C.page('tttRank')],['我的','mine',C.page('tttMine')]];for(var j=0;j<q.length;j++)d.push(U.icon(q[j][0],q[j][1],q[j][2]));d.push(U.line());}
  function communityBody20(d){dynamicHome(d,'community','社区频道','/api/community/home',{p_type:0});}
  function home20(){var tab=String(getMyVar('ttt_home_tab_v010','recommend')||'recommend');if(tab!=='community')return B.home();var d=[];setPageTitle('汤头条');if(Number(MY_PAGE||1)>1){setResult(d);return;}headerCommunity(d);try{communityBody20(d);}catch(e){d.push(U.error('社区加载失败',e,C.page('tttSettings')));}setResult(d);}
  function community20(){var d=[];setPageTitle('社区');try{communityBody20(d);}catch(e){d.push(U.error('社区加载失败',e,C.page('tttSettings')));}setResult(d);}
  function channel20(){var d=[],type=C.param('type',''),title=C.param('title','内容频道');setPageTitle(title);try{if(type==='creator'){creatorDiscover(d);setResult(d);return;}if(type==='creatorDetail20'){creatorDetail(d,C.param('uuid',''),title);setResult(d);return;}if(type==='rank'){rank20();return;}if(type==='novel'){dynamicHome(d,'novel','小说频道','/api/novel/home',{});setResult(d);return;}if(type==='audio'){dynamicHome(d,'audio','有声频道','/api/audio/home',{});setResult(d);return;}if(type==='community'){communityBody20(d);setResult(d);return;}if(type==='contentDetail20'){contentDetail20(d,C.param('kind',''),C.param('id',''),title);setResult(d);return;}if(type==='novelChapter20'){novelChapter(d,C.param('parent_id',''),C.param('chapter_id',''),title);setResult(d);return;}if(type==='audioChapter20'){audioChapter(d,C.param('parent_id',''),C.param('chapter_id',''),title);setResult(d);return;}if(type==='communityDetail20'){communityCardDetail(d,C.param('id',''),title);setResult(d);return;}if(type==='comic'){comicHome20(d);setResult(d);return;}if(type==='comicList20'){comicList20(d,title);setResult(d);return;}if(type==='comicDetail20'){comicDetail20(d,C.param('id',''),title);setResult(d);return;}if(type==='comicRead20'){comicRead20(d,C.param('book_id',''),C.param('chapter_id',''),title);setResult(d);return;}B.channel();return;}catch(e){d.push(U.error(title+' 加载失败',e,C.page('tttSettings')));setResult(d);}}
  O.home=home20;O.community=community20;O.rank=rank20;O.channel=channel20;O.version='0.1.0-test.20';return O;
})();
