/* 我的规则仓库·测试版 Bootstrap v1.0.53 - RC17 Native Local Module Loader */
var RULE_REPO_BOOTSTRAP_VERSION='1.0.53-test';
var RuleRepoBoot=(function(){
var BOOT_VERSION='1.0.53-test',BASE_BUILD=402;
var MANAGER_URLS=['https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@e06542e60677d5505e7383435b17cb69ec7a21ba/libs/updater/v2.2.0/local_module_manager.js','https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/e06542e60677d5505e7383435b17cb69ec7a21ba/libs/updater/v2.2.0/local_module_manager.js','https://github.com/huoguotiankong/asset-core-7f3/raw/e06542e60677d5505e7383435b17cb69ec7a21ba/libs/updater/v2.2.0/local_module_manager.js'];
var RELEASE_URLS=['https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@8de620b5072f1cd0dfe230df5e4b2e582e8c4b9e/apps/tools/rule-repo/releases/test-3.5.6-rc12/release.json','https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/8de620b5072f1cd0dfe230df5e4b2e582e8c4b9e/apps/tools/rule-repo/releases/test-3.5.6-rc12/release.json','https://github.com/huoguotiankong/asset-core-7f3/raw/8de620b5072f1cd0dfe230df5e4b2e582e8c4b9e/apps/tools/rule-repo/releases/test-3.5.6-rc12/release.json'];
var C={id:'rule-repo-test',timeout:8000,repoTemplates:['https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@{ref}/{path}','https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/{ref}/{path}','https://github.com/huoguotiankong/asset-core-7f3/raw/{ref}/{path}']};
var ICON='hiker://files/rules/asset-core-local/rule-repo-test/icon.svg';
function valid(t){t=String(t==null?'':t);return !!t.trim()&&!/^\s*(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Request failed|Cannot\b)/i.test(t);}
function fetchAny(us,label){var es=[];for(var i=0;i<us.length;i++)try{var t=String(fetch(us[i],{timeout:8000,headers:{'Cache-Control':'no-cache'}})||'');if(!valid(t))throw new Error('无效响应');return t;}catch(e){es.push((i+1)+':'+String(e.message||e));}throw new Error(String(label||'资源')+'全部镜像失败：'+es.join(' | '));}
function manager(){var HikerLocalModules,src=fetchAny(MANAGER_URLS,'Local Module Manager 2.2.0');eval(src);if(typeof HikerLocalModules!=='object'||String(HikerLocalModules.version)!=='2.2.0')throw new Error('Local Module Manager 2.2.0 导出异常');return HikerLocalModules;}
function release(){var r=JSON.parse(fetchAny(RELEASE_URLS,'RC12 Runtime Release'));if(String(r.id)!=='rule-repo-test'||Number(r.build)!==BASE_BUILD)throw new Error('Runtime Release 身份异常');return r;}
function installIcon(){try{if(fileExist(ICON))return getPath(ICON);var u='https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@8de620b5072f1cd0dfe230df5e4b2e582e8c4b9e/apps/tools/rule-repo/assets/icon.svg';downloadFile(u,ICON);return fileExist(ICON)?getPath(ICON):'';}catch(e){return'';}}
function installLocal(force){var m=manager(),r=release();installIcon();var x=m.install(C,r,!!force);if(!x||!x.ok)throw new Error(x&&x.error?x.error:'本地模块包安装失败');return x;}
function loadLocal(){var m=manager(),r=release(),x=m.load(C,r);return x;}
function updatePage(){setPageTitle('测试版更新');var d=[];d.push({title:'我的规则仓库·测试版',desc:'3.5.6-rc17 · Build 407\nLocal-First Runtime 16.0',img:fileExist(ICON)?getPath(ICON):'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/apps/tools/rule-repo/assets/icon.svg',col_type:'icon_1_left_pic',url:'hiker://empty',extra:{lineVisible:false}});d.push({title:'本地执行方式',desc:'Public persistent JS + native require(file://)\n不再使用 readFile()+eval()',col_type:'text_1',url:'hiker://empty'});d.push({title:'重建本地运行包',col_type:'text_2',url:$('#noLoading#').lazyRule(function(){showLoading('正在重建本地运行包…');try{var us=['https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/apps/tools/rule-repo/bootstrap_test_v153.js?_t='+Date.now(),'https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/tools/rule-repo/bootstrap_test_v153.js?_t='+Date.now()],s='',RuleRepoBoot;for(var i=0;i<us.length;i++)try{s=fetch(us[i],{timeout:8000,headers:{'Cache-Control':'no-cache'}});if(String(s||'').trim())break;}catch(e){}if(!String(s||'').trim())throw new Error('Bootstrap读取失败');eval(String(s));RuleRepoBoot.installLocal(true);hideLoading();return'toast://本地运行包已重建';}catch(e){hideLoading();return'toast://重建失败：'+String(e.message||e);}})});d.push({col_type:'line'});d.push({title:'运行模式',desc:'RC17 首次安装先做 native require(file://) 探针。探针通过后，完整 Runtime 写入 hiker://files/rules/asset-core-local/ 持久目录；后续运行由海阔原生 require 执行本地文件。',col_type:'long_text',url:'hiker://empty'});setResult(d);}
return{version:BOOT_VERSION,config:C,release:release,installLocal:installLocal,loadLocal:loadLocal,updatePage:updatePage};
})();