/* 我的规则仓库·测试版 Bootstrap v1.0.54 - RC18 Verified Control Plane */
var RULE_REPO_BOOTSTRAP_VERSION='1.0.54-test';
var RuleRepoBoot=(function(){
var BOOT_VERSION='1.0.54-test',BASE_BUILD=402;
var MANAGER_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/e06542e60677d5505e7383435b17cb69ec7a21ba/libs/updater/v2.2.0/local_module_manager.js','https://github.com/huoguotiankong/asset-core-7f3/raw/e06542e60677d5505e7383435b17cb69ec7a21ba/libs/updater/v2.2.0/local_module_manager.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@e06542e60677d5505e7383435b17cb69ec7a21ba/libs/updater/v2.2.0/local_module_manager.js'];
var RELEASE_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/8de620b5072f1cd0dfe230df5e4b2e582e8c4b9e/apps/tools/rule-repo/releases/test-3.5.6-rc12/release.json','https://github.com/huoguotiankong/asset-core-7f3/raw/8de620b5072f1cd0dfe230df5e4b2e582e8c4b9e/apps/tools/rule-repo/releases/test-3.5.6-rc12/release.json','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@8de620b5072f1cd0dfe230df5e4b2e582e8c4b9e/apps/tools/rule-repo/releases/test-3.5.6-rc12/release.json'];
var C={id:'rule-repo-test',timeout:8000,repoTemplates:['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/{ref}/{path}','https://github.com/huoguotiankong/asset-core-7f3/raw/{ref}/{path}','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@{ref}/{path}']};
var ICON='hiker://files/rules/asset-core-local/rule-repo-test/icon.svg';
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Request\s+(?:failed|error)|Fetch\s+(?:failed|error)|Network\s+(?:failed|error)|Timeout\b|ETIMEDOUT\b|ECONN|ENOTFOUND\b|Forbidden\b|Unauthorized\b|Rate\s*limit\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t)||/^\{\s*"(?:message|error)"\s*:/i.test(t);}
function manager(){var es=[];for(var i=0;i<MANAGER_URLS.length;i++){try{var src=String(fetch(MANAGER_URLS[i],{timeout:8000,headers:{'Cache-Control':'no-cache'}})||'');if(bad(src))throw new Error('无效响应');var HikerLocalModules;eval(src);if(typeof HikerLocalModules!=='object'||String(HikerLocalModules.version)!=='2.2.0')throw new Error('导出校验失败');return HikerLocalModules;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error('Local Module Manager 2.2.0 全部镜像失败：'+es.join(' | '));}
function release(){var es=[];for(var i=0;i<RELEASE_URLS.length;i++){try{var txt=String(fetch(RELEASE_URLS[i],{timeout:8000,headers:{'Cache-Control':'no-cache'}})||'');if(bad(txt))throw new Error('无效响应');var r=JSON.parse(txt);if(!r||String(r.id)!=='rule-repo-test'||Number(r.build)!==BASE_BUILD||!Array.isArray(r.modules)||!r.modules.length)throw new Error('Release身份/模块校验失败');return r;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error('RC12 Runtime Release 全部镜像失败：'+es.join(' | '));}
function installIcon(){try{if(fileExist(ICON))return getPath(ICON);var us=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/8de620b5072f1cd0dfe230df5e4b2e582e8c4b9e/apps/tools/rule-repo/assets/icon.svg','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@8de620b5072f1cd0dfe230df5e4b2e582e8c4b9e/apps/tools/rule-repo/assets/icon.svg'];for(var i=0;i<us.length;i++){try{downloadFile(us[i],ICON);if(fileExist(ICON))return getPath(ICON);}catch(e){}}return'';}catch(e2){return'';}}
function installLocal(force){var m=manager(),r=release();installIcon();var x=m.install(C,r,!!force);if(!x||!x.ok)throw new Error(x&&x.error?x.error:'本地模块包安装失败');return x;}
function loadLocal(){var m=manager(),r=release();return m.load(C,r);}
function updatePage(){setPageTitle('测试版更新');var d=[];d.push({title:'我的规则仓库·测试版',desc:'3.5.6-rc18 · Build 408\nLocal-First Runtime 16.1',img:fileExist(ICON)?getPath(ICON):'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/apps/tools/rule-repo/assets/icon.svg',col_type:'icon_1_left_pic',url:'hiker://empty',extra:{lineVisible:false}});d.push({title:'本地执行方式',desc:'Public persistent JS + native require(file://)\n控制面下载改为逐镜像解析/导出验证',col_type:'text_1',url:'hiker://empty'});d.push({title:'重建本地运行包',col_type:'text_2',url:$('#noLoading#').lazyRule(function(){showLoading('正在重建本地运行包…');try{var us=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/apps/tools/rule-repo/bootstrap_test_v154.js?_t='+Date.now(),'https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/apps/tools/rule-repo/bootstrap_test_v154.js?_t='+Date.now()],s='',RuleRepoBoot;for(var i=0;i<us.length;i++)try{s=fetch(us[i],{timeout:8000,headers:{'Cache-Control':'no-cache'}});if(String(s||'').trim())break;}catch(e){}if(!String(s||'').trim())throw new Error('Bootstrap读取失败');eval(String(s));RuleRepoBoot.installLocal(true);hideLoading();return'toast://本地运行包已重建';}catch(e){hideLoading();return'toast://重建失败：'+String(e.message||e);}})});d.push({col_type:'line'});d.push({title:'运行模式',desc:'RC18 先验证控制面响应本身可解析，再进入 native require(file://) 探针。Couldn\'t / Cannot / Error / HTTP / JSON error 都不会再被当成源码。',col_type:'long_text',url:'hiker://empty'});setResult(d);}
return{version:BOOT_VERSION,config:C,release:release,manager:manager,installLocal:installLocal,loadLocal:loadLocal,updatePage:updatePage};
})();
