/* rule-repo Local Shell Loader v1 - RC17 */
var RuleRepoLocal=(function(){
var PKG='__hclocal22_rule-repo-test_b402.json',RuleRepoBoot;
var BOOT_URLS=['https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@a44ba727672ad2ad5142c53a5581a4f935fa044a/apps/tools/rule-repo/bootstrap_test_v153.js','https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/a44ba727672ad2ad5142c53a5581a4f935fa044a/apps/tools/rule-repo/bootstrap_test_v153.js','https://github.com/huoguotiankong/asset-core-7f3/raw/a44ba727672ad2ad5142c53a5581a4f935fa044a/apps/tools/rule-repo/bootstrap_test_v153.js'];
function rj(){try{if(!fileExist(PKG))return null;return JSON.parse(String(readFile(PKG,0)||'{}'));}catch(e){return null;}}
function ok(p){if(!p||Number(p.build||0)!==402||!Array.isArray(p.files)||!p.files.length)return false;for(var i=0;i<p.files.length;i++)if(!p.files[i]||!p.files[i].file||!fileExist(String(p.files[i].file)))return false;return true;}
function valid(t){t=String(t==null?'':t);return !!t.trim()&&!/^\s*(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Request failed|Cannot\b)/i.test(t);}
function boot(){var es=[];for(var i=0;i<BOOT_URLS.length;i++)try{var s=String(fetch(BOOT_URLS[i],{timeout:8000,headers:{'Cache-Control':'no-cache'}})||'');if(!valid(s))throw new Error('无效响应');eval(s);if(!RuleRepoBoot||typeof RuleRepoBoot.installLocal!=='function')throw new Error('RuleRepoBoot导出失败');return RuleRepoBoot;}catch(e){es.push((i+1)+':'+String(e.message||e));}throw new Error('Bootstrap全部镜像失败：'+es.join(' | '));}
function requireFiles(p,clear){for(var i=0;i<p.files.length;i++){var f=p.files[i],u=getPath(String(f.file));if(clear)try{deleteCache(u);}catch(e0){}putMyVar('__hc_local_module_loading',String(f.name||i));try{require(u);}catch(e){throw new Error('本地模块 '+String(f.name||i)+' require失败：'+String(e.message||e));}}clearMyVar('__hc_local_module_loading');}
function overlay(){if(typeof HikerRuleRepo!=='object'||typeof HikerRuleRepo.home!=='function')throw new Error('HikerRuleRepo未导出');HikerRuleRepo.version='3.5.6-rc17';HikerRuleRepo.build=407;HikerRuleRepo.channel='test';HikerRuleRepo.releaseLabel='Single Workspace 16.0 · Native Local Module Loader';HikerRuleRepo.localFirstRuntimeVersion='16.0';var w=HikerRuleRepo.workspaceData;if(typeof w==='function')HikerRuleRepo.workspaceData=function(){var d=w.apply(this,arguments);if(d)d.ui='Single Workspace 16.0';return d;};try{if(typeof HikerRuleRepo.ensureRuntimeStateMigration==='function')HikerRuleRepo.ensureRuntimeStateMigration();}catch(e){}return HikerRuleRepo;}
function load(){var p=rj(),err='';if(!ok(p)){try{boot().installLocal(false);p=rj();}catch(e1){err=String(e1.message||e1);}}if(!ok(p))throw new Error('本地运行包不可用'+(err?'：'+err:''));try{requireFiles(p,false);}catch(e2){try{boot().installLocal(true);p=rj();if(!ok(p))throw new Error('重建后本地包仍不完整');requireFiles(p,true);}catch(e3){throw new Error('本地运行包执行失败：'+String(e2.message||e2)+'；自动重建失败：'+String(e3.message||e3));}}return overlay();}
return{version:'1.0.0',load:load};
})();