/* rule-repo RC23 Shell Bridge 1.0 */
var RuleRepoBridge=(function(){
var F='hiker://files/rules/asset-core-local/rule-repo-test/shell_loader_v5.js';
var O='hiker://files/rules/asset-core-local/rule-repo-test/sync_scheduler_v3.js';
var LOADER_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/6cc76aba3f8477361099208ad5b206d2e3e5430d/apps/tools/rule-repo/local_shell_loader_v5.js','https://github.com/huoguotiankong/asset-core-7f3/raw/6cc76aba3f8477361099208ad5b206d2e3e5430d/apps/tools/rule-repo/local_shell_loader_v5.js'];
var SYNC_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/a652e01a6822c7ae046d61879ce714f1b54feeda/apps/tools/rule-repo/sync_scheduler_v3.js','https://github.com/huoguotiankong/asset-core-7f3/raw/a652e01a6822c7ae046d61879ce714f1b54feeda/apps/tools/rule-repo/sync_scheduler_v3.js'];
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Request\s+(?:failed|error)|Fetch\s+(?:failed|error)|Network\s+(?:failed|error)|Timeout\b|ETIMEDOUT\b|ECONN|ENOTFOUND\b|Forbidden\b|Unauthorized\b|Rate\s*limit\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function ensure(path,urls,label){if(fileExist(path))return path;var s='',es=[];for(var i=0;i<urls.length;i++){try{s=String(fetch(urls[i],{timeout:6000,headers:{'Cache-Control':'no-cache'}})||'');if(bad(s))throw new Error('无效响应');writeFile(path,s);if(!fileExist(path))throw new Error('写入失败');return path;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(label+'下载失败：'+es.join(' | '));}
function req(path){var u=getPath(path);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}}
function load(){ensure(F,LOADER_URLS,'本地启动器');req(F);if(typeof RuleRepoLocal!=='object'||typeof RuleRepoLocal.load!=='function')throw new Error('RuleRepoLocal未导出');RuleRepoLocal.load();ensure(O,SYNC_URLS,'独立同步调度器');req(O);if(typeof RuleRepoSyncV3!=='object'||typeof RuleRepoSyncV3.apply!=='function')throw new Error('RuleRepoSyncV3未导出');RuleRepoSyncV3.apply(HikerRuleRepo);return HikerRuleRepo;}
function updatePage(){var R=load();setPageTitle('测试版更新');var d=[];d.push({title:'我的规则仓库·测试版',desc:'3.5.6-rc23 · Build 413\nLocal-First 16.6',col_type:'text_1',url:'hiker://empty'});d.push({title:'轻同步',desc:'只更新根目录 + 统一版本目录；不加载 Runtime、不下载图标、不扫描安装状态；完成后不自动刷新页面',col_type:'text_2',url:$('#noLoading#').lazyRule(function(){var loading=false;try{showLoading('正在轻同步…');loading=true;var O='hiker://files/rules/asset-core-local/rule-repo-test/sync_scheduler_v3.js',u=getPath(O);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}if(typeof RuleRepoSyncV3!=='object')throw new Error('独立同步调度器未导出');var x=RuleRepoSyncV3.sync();hideLoading();loading=false;return x&&x.ok?'toast://轻同步完成；本地目录已更新，下次刷新页面生效':'toast://轻同步失败，继续使用本地目录';}catch(e){if(loading)try{hideLoading();}catch(_e){}return'toast://轻同步失败：'+String(e.message||e);}})});d.push({title:'版本中心',desc:'Stable / Test / Local 全部读取本地统一目录',col_type:'text_2',url:'hiker://page/ruleRepoVersions?rule=我的规则仓库·测试版&simple=true'});d.push({col_type:'line'});d.push({title:'同步策略',desc:'RC23 将同步动作与 Build402 Runtime 状态彻底解耦。普通同步不会调用 RuleRepoLocal.load()，不会检查/重建 Runtime，也不会写 __hclocal22 状态文件。',col_type:'long_text',url:'hiker://empty'});setResult(d);return R;}
function run(name){var R=load();name=String(name||'home');if(name==='home')return R.home();if(name==='category')return R.categoryPage();if(name==='search')return R.searchPage();if(name==='updates')return R.updatesPage();if(name==='detail')return R.detailPage();if(name==='history')return R.historyPage();if(name==='settings')return R.settingsPage();if(name==='about')return R.aboutPage();if(name==='filters')return typeof R.filtersPage==='function'?R.filtersPage():R.categoryPage();if(name==='versions')return R.channelPage();if(name==='update')return updatePage();throw new Error('未知页面：'+name);}
return{version:'1.0.0',load:load,run:run,updatePage:updatePage};
})();
