/* rule-repo RC26 Shell Bridge 4.0 - fast catalog check */
var RuleRepoBridge=(function(){
var F='hiker://files/rules/asset-core-local/rule-repo-test/shell_loader_v5.js';
var O='hiker://files/rules/asset-core-local/rule-repo-test/sync_scheduler_v4.js';
var P='hiker://files/rules/asset-core-local/rule-repo-test/rc25_native_import_patch.js';
var C='hiker://files/rules/asset-core-local/rule-repo-test/catalog_refresh_v1.js';
var X='hiker://files/rules/asset-core-local/rule-repo-test/rc26_catalog_refresh_patch.js';
var LOADER_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/6cc76aba3f8477361099208ad5b206d2e3e5430d/apps/tools/rule-repo/local_shell_loader_v5.js','https://github.com/huoguotiankong/asset-core-7f3/raw/6cc76aba3f8477361099208ad5b206d2e3e5430d/apps/tools/rule-repo/local_shell_loader_v5.js'];
var SYNC_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/0d87f0ad1796aeb0b90158ff3441b6c8784bbc15/apps/tools/rule-repo/sync_scheduler_v4.js','https://github.com/huoguotiankong/asset-core-7f3/raw/0d87f0ad1796aeb0b90158ff3441b6c8784bbc15/apps/tools/rule-repo/sync_scheduler_v4.js'];
var PATCH25_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/1e545fe16e294d386dd2f6d54bf66f9acb11f790/apps/tools/rule-repo/releases/test-3.5.6-rc25/native_import_handoff_patch.js','https://github.com/huoguotiankong/asset-core-7f3/raw/1e545fe16e294d386dd2f6d54bf66f9acb11f790/apps/tools/rule-repo/releases/test-3.5.6-rc25/native_import_handoff_patch.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@1e545fe16e294d386dd2f6d54bf66f9acb11f790/apps/tools/rule-repo/releases/test-3.5.6-rc25/native_import_handoff_patch.js'];
var REFRESH_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/catalog_refresh_v1.js','https://github.com/huoguotiankong/asset-core-7f3/raw/19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/catalog_refresh_v1.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/catalog_refresh_v1.js'];
var PATCH26_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/releases/test-3.5.6-rc26/catalog_refresh_patch.js','https://github.com/huoguotiankong/asset-core-7f3/raw/19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/releases/test-3.5.6-rc26/catalog_refresh_patch.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/releases/test-3.5.6-rc26/catalog_refresh_patch.js'];
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Request\s+(?:failed|error)|Fetch\s+(?:failed|error)|Network\s+(?:failed|error)|Timeout\b|ETIMEDOUT\b|ECONN|ENOTFOUND\b|Forbidden\b|Unauthorized\b|Rate\s*limit\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function ensure(path,urls,label){if(fileExist(path))return path;var s='',es=[];for(var i=0;i<urls.length;i++){try{s=String(fetch(urls[i],{timeout:6000,headers:{'Cache-Control':'no-cache'}})||'');if(bad(s))throw new Error('无效响应');writeFile(path,s);if(!fileExist(path))throw new Error('写入失败');return path;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(label+'下载失败：'+es.join(' | '));}
function req(path){var u=getPath(path);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}}
function load(){
 ensure(F,LOADER_URLS,'本地启动器');req(F);if(typeof RuleRepoLocal!=='object'||typeof RuleRepoLocal.load!=='function')throw new Error('RuleRepoLocal未导出');RuleRepoLocal.load();
 ensure(O,SYNC_URLS,'RC24同步与图标调度器');req(O);if(typeof RuleRepoSyncV4!=='object'||typeof RuleRepoSyncV4.apply!=='function')throw new Error('RuleRepoSyncV4未导出');RuleRepoSyncV4.apply(HikerRuleRepo);
 ensure(P,PATCH25_URLS,'RC25原生导入补丁');req(P);if(typeof RuleRepoRC25!=='object'||typeof RuleRepoRC25.apply!=='function')throw new Error('RuleRepoRC25未导出');RuleRepoRC25.apply(HikerRuleRepo);
 ensure(C,REFRESH_URLS,'RC26快速版本目录模块');req(C);if(typeof RuleRepoCatalogRefresh!=='object'||typeof RuleRepoCatalogRefresh.refresh!=='function')throw new Error('RuleRepoCatalogRefresh未导出');RuleRepoCatalogRefresh.ensureSelf();
 ensure(X,PATCH26_URLS,'RC26快速检查补丁');req(X);if(typeof RuleRepoRC26!=='object'||typeof RuleRepoRC26.apply!=='function')throw new Error('RuleRepoRC26未导出');RuleRepoRC26.apply(HikerRuleRepo);
 return HikerRuleRepo;
}
function updatePage(){var R=load();setPageTitle('测试版更新');var d=[];d.push({title:'我的规则仓库·测试版',desc:'3.5.6-rc26 · Build 416\nLocal-First 16.9',col_type:'text_1',url:'hiker://empty'});d.push({title:'快速检查版本',desc:'程序详情里的“检查版本”现在只刷新统一版本目录：Raw / GitHub Raw / jsDelivr 三镜像并行，选择 revision 最新有效结果；不再重新加载整套 Runtime 或安装状态。',col_type:'text_1',url:'hiker://empty'});d.push({title:'轻同步',desc:'保留 RC24 本地图标包与独立同步；目录同步后追加三镜像版本目录兜底，Raw 单路失败也不会继续长期停在旧目录。',col_type:'text_2',url:$('#noLoading#').lazyRule(function(){var loading=false;try{showLoading('正在轻同步目录与图标包…');loading=true;var B='hiker://files/rules/asset-core-local/rule-repo-test/shell_bridge_v4.js',u=getPath(B);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}var R=RuleRepoBridge.load(),x=R.lightSync();hideLoading();loading=false;return x&&x.ok?'toast://轻同步完成；版本目录已刷新':'toast://轻同步失败，继续使用现有本地数据';}catch(e){if(loading)try{hideLoading();}catch(_e){}return'toast://轻同步失败：'+String(e.message||e);}})});d.push({title:'版本中心',desc:'Stable / Test / Local 正常浏览仍只读本地统一目录；联网只发生在主动“检查版本/同步”时。',col_type:'text_2',url:'hiker://page/ruleRepoVersions?rule=我的规则仓库·测试版&simple=true'});d.push({col_type:'line'});d.push({title:'RC26 验收重点',desc:'打开任一程序详情应立即显示本地版本；点击“检查版本”应在短时间内返回并刷新页面。麻豆AI应从旧 Test 2.8.0-test.3 更新为 Test 2.8.1-test.1 / Build28101。',col_type:'long_text',url:'hiker://empty'});setResult(d);return R;}
function run(name){var R=load();name=String(name||'home');if(name==='home')return R.home();if(name==='category')return R.categoryPage();if(name==='search')return R.searchPage();if(name==='updates')return R.updatesPage();if(name==='detail')return R.detailPage();if(name==='history')return R.historyPage();if(name==='settings')return R.settingsPage();if(name==='about')return R.aboutPage();if(name==='filters')return typeof R.filtersPage==='function'?R.filtersPage():R.categoryPage();if(name==='versions')return R.channelPage();if(name==='update')return updatePage();throw new Error('未知页面：'+name);}
return{version:'4.0.0',load:load,run:run,updatePage:updatePage};
})();
