/* rule-repo RC32 Shell Bridge 10.0 - direct payload import */
var RuleRepoBridge=(function(){
var V9='hiker://files/rules/asset-core-local/rule-repo-test/shell_bridge_v9.js';
var P='hiker://files/rules/asset-core-local/rule-repo-test/rc32_direct_payload_import_patch.js';
var V9_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/d3b5e063106a9d900a0dad761c73ef846ed3b6a2/apps/tools/rule-repo/shell_bridge_v9.js','https://github.com/huoguotiankong/asset-core-7f3/raw/d3b5e063106a9d900a0dad761c73ef846ed3b6a2/apps/tools/rule-repo/shell_bridge_v9.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@d3b5e063106a9d900a0dad761c73ef846ed3b6a2/apps/tools/rule-repo/shell_bridge_v9.js'];
var P_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/d58fb37457f05fea2f11055c96f66c49bb8f478f/apps/tools/rule-repo/releases/test-3.5.6-rc32/direct_payload_import_patch.js','https://github.com/huoguotiankong/asset-core-7f3/raw/d58fb37457f05fea2f11055c96f66c49bb8f478f/apps/tools/rule-repo/releases/test-3.5.6-rc32/direct_payload_import_patch.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@d58fb37457f05fea2f11055c96f66c49bb8f478f/apps/tools/rule-repo/releases/test-3.5.6-rc32/direct_payload_import_patch.js'];
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function ensure(path,urls,label){if(fileExist(path))return path;var s='',es=[];for(var i=0;i<urls.length;i++){try{s=String(fetch(urls[i],{timeout:5000,headers:{'Cache-Control':'no-cache'}})||'');if(bad(s))throw new Error('无效响应');writeFile(path,s);if(!fileExist(path))throw new Error('写入失败');return path;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(label+'下载失败：'+es.join(' | '));}
function req(path){var u=getPath(path);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}}
function load(){var self=RuleRepoBridge;ensure(V9,V9_URLS,'RC31 Bridge');req(V9);var base=RuleRepoBridge;if(!base||typeof base.load!=='function')throw new Error('RC31 Bridge 未导出');var R=base.load();RuleRepoBridge=self;ensure(P,P_URLS,'RC32 直接导入层');req(P);if(typeof RuleRepoRC32!=='object'||typeof RuleRepoRC32.apply!=='function')throw new Error('RC32 直接导入层未导出');RuleRepoRC32.apply(R);RuleRepoBridge=self;return R;}
function updatePage(){var R=load();setPageTitle('测试版更新');var d=[];d.push({title:'我的规则仓库·测试版',desc:'3.5.6-rc32 · Build 422\nDirect Payload Import 18.4',col_type:'text_1',url:'hiker://empty'});d.push({title:'导入策略回到实机更快路径',desc:'普通 .txt 不再返回 home_rule_url。规则仓先用固定 commit 三镜像短超时读取规则正文，再直接把“海阔视界…”规则 payload 交给海阔导入。',col_type:'text_2',url:'hiker://empty'});d.push({title:'不恢复正式版的长等待',desc:'不是照搬 Stable 的 Raw 20s → API 20s 串行容错；RC32 优先 batchFetch 三镜像约 2.6 秒硬超时，失败后才短串行兜底。',col_type:'text_2',url:'hiker://empty'});d.push({title:'RC31 能力全部保留',desc:'Local-First 启动、HEAD-Pinned 自更新、轻同步修复、本地图标、版本目录和多版本更新状态都不回退。',col_type:'text_2',url:'hiker://empty'});setResult(d);return R;}
function run(name){var R=load();name=String(name||'home');if(name==='home')return R.home();if(name==='category')return R.categoryPage();if(name==='search')return R.searchPage();if(name==='updates')return R.updatesPage();if(name==='detail')return R.detailPage();if(name==='history')return R.historyPage();if(name==='settings')return R.settingsPage();if(name==='about')return R.aboutPage();if(name==='filters')return typeof R.filtersPage==='function'?R.filtersPage():R.categoryPage();if(name==='versions')return R.channelPage();if(name==='update')return updatePage();throw new Error('未知页面：'+name);}
return{version:'10.0.0',load:load,run:run,updatePage:updatePage};
})();
