/* rule-repo RC29 Shell Bridge 7.0 - self update probe */
var RuleRepoBridge=(function(){
var V6='hiker://files/rules/asset-core-local/rule-repo-test/shell_bridge_v6.js';
var Q='hiker://files/rules/asset-core-local/rule-repo-test/rc29_self_update_probe_patch.js';
var V6_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/ccdca5f5ba1f951f693a88925e45ee18f867ec28/apps/tools/rule-repo/shell_bridge_v6.js','https://github.com/huoguotiankong/asset-core-7f3/raw/ccdca5f5ba1f951f693a88925e45ee18f867ec28/apps/tools/rule-repo/shell_bridge_v6.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@ccdca5f5ba1f951f693a88925e45ee18f867ec28/apps/tools/rule-repo/shell_bridge_v6.js'];
var Q_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/de3e1014d16cdaeb8b98eab42395fd66f6e3d4d5/apps/tools/rule-repo/releases/test-3.5.6-rc29/self_update_probe_patch.js','https://github.com/huoguotiankong/asset-core-7f3/raw/de3e1014d16cdaeb8b98eab42395fd66f6e3d4d5/apps/tools/rule-repo/releases/test-3.5.6-rc29/self_update_probe_patch.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@de3e1014d16cdaeb8b98eab42395fd66f6e3d4d5/apps/tools/rule-repo/releases/test-3.5.6-rc29/self_update_probe_patch.js'];
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function ensure(path,urls,label){if(fileExist(path))return path;var s='',es=[];for(var i=0;i<urls.length;i++){try{s=String(fetch(urls[i],{timeout:6000,headers:{'Cache-Control':'no-cache'}})||'');if(bad(s))throw new Error('无效响应');writeFile(path,s);if(!fileExist(path))throw new Error('写入失败');return path;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(label+'下载失败：'+es.join(' | '));}
function req(path){var u=getPath(path);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}}
function load(){var self=RuleRepoBridge;ensure(V6,V6_URLS,'RC28 Bridge');req(V6);var base=RuleRepoBridge;if(!base||typeof base.load!=='function')throw new Error('RC28 Bridge 未导出');var R=base.load();RuleRepoBridge=self;ensure(Q,Q_URLS,'RC29 自更新探针');req(Q);if(typeof RuleRepoRC29!=='object'||typeof RuleRepoRC29.apply!=='function')throw new Error('RC29 自更新探针未导出');RuleRepoRC29.apply(R);RuleRepoBridge=self;return R;}
function updatePage(){var R=load();setPageTitle('测试版更新');var d=[];d.push({title:'我的规则仓库·测试版',desc:'3.5.6-rc29 · Build 419\nSelf Update Probe 18.1',col_type:'text_1',url:'hiker://empty'});d.push({title:'RC28 → RC29 自更新探针',desc:'本版不新增业务功能，只验证测试仓是否能在不打开正式仓的情况下自行发现、导入并切换到下一 Test。',col_type:'text_1',url:'hiker://empty'});d.push({title:'当前验收',desc:'若你是从 RC28 测试仓内部看到并导入本版，且这里显示 RC29 / Build419，则测试仓自更新闭环成立。',col_type:'text_2',url:'hiker://page/ruleRepoVersions?rule=我的规则仓库·测试版&simple=true'});d.push({title:'既有能力',desc:'RC24 图标 / RC25 原生导入 / RC26 快速目录 / RC27 更新统计 / RC28 独立 self feed 均保持。',col_type:'text_2',url:'hiker://empty'});setResult(d);return R;}
function run(name){var R=load();name=String(name||'home');if(name==='home')return R.home();if(name==='category')return R.categoryPage();if(name==='search')return R.searchPage();if(name==='updates')return R.updatesPage();if(name==='detail')return R.detailPage();if(name==='history')return R.historyPage();if(name==='settings')return R.settingsPage();if(name==='about')return R.aboutPage();if(name==='filters')return typeof R.filtersPage==='function'?R.filtersPage():R.categoryPage();if(name==='versions')return R.channelPage();if(name==='update')return updatePage();throw new Error('未知页面：'+name);}
return{version:'7.0.0',load:load,run:run,updatePage:updatePage};
})();
