/* rule-repo RC27 Shell Bridge 5.0 - channel update state */
var RuleRepoBridge=(function(){
var F='hiker://files/rules/asset-core-local/rule-repo-test/shell_loader_v5.js';
var O='hiker://files/rules/asset-core-local/rule-repo-test/sync_scheduler_v4.js';
var P='hiker://files/rules/asset-core-local/rule-repo-test/rc25_native_import_patch.js';
var C='hiker://files/rules/asset-core-local/rule-repo-test/catalog_refresh_v1.js';
var X='hiker://files/rules/asset-core-local/rule-repo-test/rc26_catalog_refresh_patch.js';
var Y='hiker://files/rules/asset-core-local/rule-repo-test/rc27_channel_update_patch.js';
var LOADER_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/6cc76aba3f8477361099208ad5b206d2e3e5430d/apps/tools/rule-repo/local_shell_loader_v5.js','https://github.com/huoguotiankong/asset-core-7f3/raw/6cc76aba3f8477361099208ad5b206d2e3e5430d/apps/tools/rule-repo/local_shell_loader_v5.js'];
var SYNC_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/0d87f0ad1796aeb0b90158ff3441b6c8784bbc15/apps/tools/rule-repo/sync_scheduler_v4.js','https://github.com/huoguotiankong/asset-core-7f3/raw/0d87f0ad1796aeb0b90158ff3441b6c8784bbc15/apps/tools/rule-repo/sync_scheduler_v4.js'];
var PATCH25_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/1e545fe16e294d386dd2f6d54bf66f9acb11f790/apps/tools/rule-repo/releases/test-3.5.6-rc25/native_import_handoff_patch.js','https://github.com/huoguotiankong/asset-core-7f3/raw/1e545fe16e294d386dd2f6d54bf66f9acb11f790/apps/tools/rule-repo/releases/test-3.5.6-rc25/native_import_handoff_patch.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@1e545fe16e294d386dd2f6d54bf66f9acb11f790/apps/tools/rule-repo/releases/test-3.5.6-rc25/native_import_handoff_patch.js'];
var REFRESH_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/catalog_refresh_v1.js','https://github.com/huoguotiankong/asset-core-7f3/raw/19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/catalog_refresh_v1.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/catalog_refresh_v1.js'];
var PATCH26_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/releases/test-3.5.6-rc26/catalog_refresh_patch.js','https://github.com/huoguotiankong/asset-core-7f3/raw/19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/releases/test-3.5.6-rc26/catalog_refresh_patch.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@19f53b91fc368dac9450cf0b4da8d67c9aa45560/apps/tools/rule-repo/releases/test-3.5.6-rc26/catalog_refresh_patch.js'];
var PATCH27_URLS=['https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/0817d0f2ae8ab0dc5f7d8e2b9da0f241eec371b7/apps/tools/rule-repo/releases/test-3.5.6-rc27/channel_update_state_patch.js','https://github.com/huoguotiankong/asset-core-7f3/raw/0817d0f2ae8ab0dc5f7d8e2b9da0f241eec371b7/apps/tools/rule-repo/releases/test-3.5.6-rc27/channel_update_state_patch.js','https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@0817d0f2ae8ab0dc5f7d8e2b9da0f241eec371b7/apps/tools/rule-repo/releases/test-3.5.6-rc27/channel_update_state_patch.js'];
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Request\s+(?:failed|error)|Fetch\s+(?:failed|error)|Network\s+(?:failed|error)|Timeout\b|ETIMEDOUT\b|ECONN|ENOTFOUND\b|Forbidden\b|Unauthorized\b|Rate\s*limit\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t);}
function ensure(path,urls,label){if(fileExist(path))return path;var s='',es=[];for(var i=0;i<urls.length;i++){try{s=String(fetch(urls[i],{timeout:6000,headers:{'Cache-Control':'no-cache'}})||'');if(bad(s))throw new Error('无效响应');writeFile(path,s);if(!fileExist(path))throw new Error('写入失败');return path;}catch(e){es.push((i+1)+':'+String(e.message||e));}}throw new Error(label+'下载失败：'+es.join(' | '));}
function req(path){var u=getPath(path);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}}
function load(){
 ensure(F,LOADER_URLS,'本地启动器');req(F);if(typeof RuleRepoLocal!=='object'||typeof RuleRepoLocal.load!=='function')throw new Error('RuleRepoLocal未导出');RuleRepoLocal.load();
 ensure(O,SYNC_URLS,'RC24同步与图标调度器');req(O);if(typeof RuleRepoSyncV4!=='object'||typeof RuleRepoSyncV4.apply!=='function')throw new Error('RuleRepoSyncV4未导出');RuleRepoSyncV4.apply(HikerRuleRepo);
 ensure(P,PATCH25_URLS,'RC25原生导入补丁');req(P);if(typeof RuleRepoRC25!=='object'||typeof RuleRepoRC25.apply!=='function')throw new Error('RuleRepoRC25未导出');RuleRepoRC25.apply(HikerRuleRepo);
 ensure(C,REFRESH_URLS,'RC26快速版本目录模块');req(C);if(typeof RuleRepoCatalogRefresh!=='object'||typeof RuleRepoCatalogRefresh.refresh!=='function')throw new Error('RuleRepoCatalogRefresh未导出');RuleRepoCatalogRefresh.ensureSelf();
 ensure(X,PATCH26_URLS,'RC26快速检查补丁');req(X);if(typeof RuleRepoRC26!=='object'||typeof RuleRepoRC26.apply!=='function')throw new Error('RuleRepoRC26未导出');RuleRepoRC26.apply(HikerRuleRepo);
 ensure(Y,PATCH27_URLS,'RC27多版本更新状态补丁');req(Y);if(typeof RuleRepoRC27!=='object'||typeof RuleRepoRC27.apply!=='function')throw new Error('RuleRepoRC27未导出');RuleRepoRC27.apply(HikerRuleRepo);
 return HikerRuleRepo;
}
function updatePage(){var R=load();setPageTitle('测试版更新');var d=[];d.push({title:'我的规则仓库·测试版',desc:'3.5.6-rc27 · Build 417\nLocal-First 17.0',col_type:'text_1',url:'hiker://empty'});d.push({title:'多版本更新状态',desc:'首页“可更新”现在按手机已安装远程通道与本地统一版本目录比较：Stable/Test 同一升级线按 Build 优先判断，Local/Web 保持独立。',col_type:'text_1',url:'hiker://empty'});d.push({title:'刷新版本目录',desc:'继续使用 RC26 三镜像快速目录刷新；正常浏览仍为本地零网络。',col_type:'text_2',url:R.workspaceStaticAction?R.workspaceStaticAction('sync'):'hiker://empty'});d.push({title:'更新中心',desc:'进入后应能列出真实可更新的多版本程序',col_type:'text_2',url:'hiker://page/ruleRepoUpdates?rule=我的规则仓库·测试版&simple=true'});d.push({col_type:'line'});d.push({title:'RC27 验收重点',desc:'当前目录下，若麻豆AI仍安装 Stable 2.8.0、麻豆传媒仍安装 Stable 0.1.0，而黄豆已安装 Test 1.9.1-test.3，则首页可更新数应至少显示 2；导入对应最新 Test 后应随安装记录归零。',col_type:'long_text',url:'hiker://empty'});setResult(d);return R;}
function run(name){var R=load();name=String(name||'home');if(name==='home')return R.home();if(name==='category')return R.categoryPage();if(name==='search')return R.searchPage();if(name==='updates')return R.updatesPage();if(name==='detail')return R.detailPage();if(name==='history')return R.historyPage();if(name==='settings')return R.settingsPage();if(name==='about')return R.aboutPage();if(name==='filters')return typeof R.filtersPage==='function'?R.filtersPage():R.categoryPage();if(name==='versions')return R.channelPage();if(name==='update')return updatePage();throw new Error('未知页面：'+name);}
return{version:'5.0.0',load:load,run:run,updatePage:updatePage};
})();
