/* rule-repo RC23 Standalone Light Sync 1.0 - sync never loads Runtime */
var RuleRepoSyncV3=(function(){
var VERSION='1.0.0';
var REPO='huoguotiankong/asset-core-7f3';
var CATALOG_FILE='hiker://files/rules/asset-core-local/rule-repo-test/channel_catalog_v2.json';
var MANIFEST_KEY='hc_repo_manifest_v3';
var MANIFEST_TS_KEY='hc_repo_manifest_v3_ts';
var REV_KEY='hc_repo_v3_manifest_revision';
var PROBE_TS_KEY='hc_repo_v3_manifest_probe_ts';
function clone(o){try{return JSON.parse(JSON.stringify(o));}catch(e){return o;}}
function selfMeta(){return{schema:4,id:'rule-repo',name:'我的规则仓库',updatedAt:'2026-08-24 22:05',channels:[{channel:'stable',label:'正式版',id:'rule-repo',name:'我的规则仓库',version:'3.5.5',build:389,displayVersion:'Stable 3.5.5 · Build 389',path:'apps/tools/rule-repo/rule_repo_remote_v355.txt',mode:'remote',updatedAt:'2026-08-24',recommended:true},{channel:'test',label:'测试版',id:'rule-repo-test',name:'我的规则仓库·测试版',version:'3.5.6-rc23',build:413,displayVersion:'Test 3.5.6-rc23 · Build 413 · Standalone Light Sync',path:'apps/tools/rule-repo/rule_repo_test_v160.txt',mode:'remote-local-first-native-require',updatedAt:'2026-08-24',recommended:false,baseVersion:'3.5.5',targetVersion:'3.5.6'}]};}
function bad(t){t=String(t==null?'':t).replace(/^\uFEFF/,'').trim();return !t||/^(?:<!doctype|<html|Bad Gateway|Too Many Requests|Service Unavailable|Gateway Timeout|Not Found|Error\b|Exception\b|HTTP\b|Request\s+(?:failed|error)|Fetch\s+(?:failed|error)|Network\s+(?:failed|error)|Timeout\b|ETIMEDOUT\b|ECONN|ENOTFOUND\b|Forbidden\b|Unauthorized\b|Rate\s*limit\b|Cannot\b|Couldn(?:'|’)t\b)/i.test(t)||/^\{\s*"(?:message|error)"\s*:/i.test(t);}
function parseManifest(t){if(bad(t))return null;try{var x=JSON.parse(String(t));return x&&Array.isArray(x.items)?x:null;}catch(e){return null;}}
function parseCatalog(t){if(bad(t))return null;try{var x=JSON.parse(String(t));return x&&x.apps&&typeof x.apps==='object'?x:null;}catch(e){return null;}}
function readCatalog(){try{if(!fileExist(CATALOG_FILE))return null;return parseCatalog(readFile(CATALOG_FILE));}catch(e){return null;}}
function catalogMeta(id){var c=readCatalog(),m=c&&c.apps&&c.apps[String(id||'')];return m&&Array.isArray(m.channels)&&m.channels.length?clone(m):null;}
function catalogRevision(){var c=readCatalog();return String(c&&c.revision||'');}
function normalizeManifest(m){if(!m)return m;try{var a=m.items||[];for(var i=0;i<a.length;i++)if(String(a[i]&&a[i].id||'')==='rule-repo'){a[i].version='Stable 3.5.5 / Test 3.5.6-rc23';a[i].desc='Stable 3.5.5 保持冻结；Test RC23 将同步动作与 Runtime 状态彻底解耦，普通同步不再检查/重建 Build402，也不自动刷新页面。';a[i].updatedAt='2026-08-24';break;}}catch(e){}return m;}
function saveManifest(m){if(!m)return false;try{m=normalizeManifest(m);setItem(MANIFEST_KEY,JSON.stringify(m));setItem(MANIFEST_TS_KEY,String(Date.now()));if(m.revision)setItem(REV_KEY,String(m.revision));setItem(PROBE_TS_KEY,String(Date.now()));return true;}catch(e){return false;}}
function saveCatalog(c){if(!c)return false;try{c.apps=c.apps||{};c.apps['rule-repo']=selfMeta();writeFile(CATALOG_FILE,JSON.stringify(c));if(!fileExist(CATALOG_FILE))return false;var b=parseCatalog(readFile(CATALOG_FILE));return !!b;}catch(e){return false;}}
function standaloneSync(){var ts=Date.now(),base='https://raw.githubusercontent.com/'+REPO+'/main/',reqs=[{url:base+'manifest.json?_s='+ts,options:{timeout:3800,headers:{'Cache-Control':'no-cache, no-store, max-age=0'}}},{url:base+'apps/tools/rule-repo/channel_catalog_snapshot.json?_s='+ts,options:{timeout:3800,headers:{'Cache-Control':'no-cache, no-store, max-age=0'}}}],rs=null,m=null,c=null,errors=[];try{if(typeof batchFetch==='function')rs=batchFetch(reqs);}catch(e0){errors.push('batch:'+String(e0.message||e0));}if(rs&&rs.length){m=parseManifest(rs[0]);c=parseCatalog(rs[1]);}else{errors.push('batchFetch unavailable');}var mo=saveManifest(m),co=saveCatalog(c);return{ok:!!(mo||co),mode:'standalone-light-sync',manifest:{ok:mo,revision:String(m&&m.revision||'')},channelCatalog:{ok:co,revision:String(c&&c.revision||catalogRevision())},errors:errors};}
function apply(R){if(!R||typeof R.home!=='function')throw new Error('HikerRuleRepo未导出');if(R.__rc23StandaloneSync){R.version='3.5.6-rc23';R.build=413;return R;}var baseFast=R.fastChannelCache,baseStatic=R.workspaceStaticAction,baseStatics=R.workspaceStaticActions;R.__rc23StandaloneSync=true;R.version='3.5.6-rc23';R.build=413;R.channel='test';R.releaseLabel='Single Workspace 16.6 · Standalone Light Sync';R.localFirstRuntimeVersion='16.6';R.fastHomeVersion='16.6.0';R.isTestChannel=function(){return true;};R.ruleRepoChannelFallback=function(){return selfMeta();};R.fastChannelCache=function(item){var id=String(item&&item.id||'');if(id==='rule-repo')return{schema:8,time:Date.now(),revision:'self-rc23',sig:this.channelCacheSignature?this.channelCacheSignature(item):id,meta:selfMeta()};var m=catalogMeta(id);if(m)return{schema:8,time:Date.now(),revision:catalogRevision(),sig:this.channelCacheSignature?this.channelCacheSignature(item):id,meta:m};return typeof baseFast==='function'?baseFast.call(this,item):null;};R.loadChannelMetaLive=function(item){var m=String(item&&item.id||'')==='rule-repo'?selfMeta():catalogMeta(item&&item.id);if(m)return m;throw new Error('本地版本目录暂无 '+String(item&&item.id||'')+'，请执行轻同步');};R.syncManifest=function(){return standaloneSync();};R.lightSync=function(){return standaloneSync();};R.workspaceStaticAction=function(kind){if(String(kind||'')!=='sync')return typeof baseStatic==='function'?baseStatic.call(this,kind):'hiker://empty';return $('#noLoading#').lazyRule(function(){var loading=false;try{showLoading('正在轻同步…');loading=true;var O='hiker://files/rules/asset-core-local/rule-repo-test/sync_scheduler_v3.js',u=getPath(O);try{require(u);}catch(e0){try{deleteCache(u);}catch(e1){}require(u);}if(typeof RuleRepoSyncV3!=='object')throw new Error('独立同步调度器未导出');var x=RuleRepoSyncV3.sync();hideLoading();loading=false;if(x&&x.ok)return'toast://轻同步完成；本地目录已更新，下次刷新页面生效';return'toast://轻同步失败，已保留现有本地目录';}catch(e){if(loading)try{hideLoading();}catch(e2){}return'toast://轻同步失败：'+String(e.message||e);}});};R.workspaceStaticActions=function(){var a=typeof baseStatics==='function'?baseStatics.call(this):{};a=a||{};a.sync=this.workspaceStaticAction('sync');return a;};return R;}
return{version:VERSION,apply:apply,sync:standaloneSync,selfMeta:selfMeta,catalogMeta:catalogMeta};
})();
