/* Hanime1 Test15 recovery loader: exact Test12 runtime chain */
(function(){
var ROOT='https://raw.githubusercontent.com/huoguotiankong/asset-core-7f3/main/';
var P=["apps/video/hanime1/releases/2.0.0-test.1/core.js","apps/video/hanime1/releases/2.0.0-test.1/provider.js","apps/video/hanime1/releases/2.0.0-test.6/patch_session.js","apps/video/hanime1/releases/2.0.0-test.6/patch_web_base.js","apps/video/hanime1/releases/2.0.0-test.6/patch_web_more.js","apps/video/hanime1/releases/2.0.0-test.1/pages_explore.js","apps/video/hanime1/releases/2.0.0-test.1/pages_library.js","apps/video/hanime1/releases/2.0.0-test.1/pages_account.js","apps/video/hanime1/releases/2.0.0-test.6/patch_ui.js","apps/video/hanime1/releases/2.0.0-test.7/patch_provider.js","apps/video/hanime1/releases/2.0.0-test.7/patch_ui.js","apps/video/hanime1/releases/2.0.0-test.8/patch_provider.js","apps/video/hanime1/releases/2.0.0-test.8/patch_comic.js","apps/video/hanime1/releases/2.0.0-test.9/account_common.js","apps/video/hanime1/releases/2.0.0-test.9/account_login.js","apps/video/hanime1/releases/2.0.0-test.9/account_cookie.js","apps/video/hanime1/releases/2.0.0-test.9/ui_common.js","apps/video/hanime1/releases/2.0.0-test.9/ui_state.js","apps/video/hanime1/releases/2.0.0-test.9/ui_library.js","apps/video/hanime1/releases/2.0.0-test.9/ui_results.js","apps/video/hanime1/releases/2.0.0-test.9/ui_detail.js","apps/video/hanime1/releases/2.0.0-test.9/ui_comments.js","apps/video/hanime1/releases/2.0.0-test.9/ui_comic_list.js","apps/video/hanime1/releases/2.0.0-test.9/ui_comic_detail.js","apps/video/hanime1/releases/2.0.0-test.9/ui_login.js","apps/video/hanime1/releases/2.0.0-test.9/ui_misc.js","apps/video/hanime1/releases/2.0.0-test.10/patch_provider.js","apps/video/hanime1/releases/2.0.0-test.10/ui_common.js","apps/video/hanime1/releases/2.0.0-test.10/ui_home.js","apps/video/hanime1/releases/2.0.0-test.10/ui_library.js","apps/video/hanime1/releases/2.0.0-test.10/ui_results.js","apps/video/hanime1/releases/2.0.0-test.10/ui_detail.js","apps/video/hanime1/releases/2.0.0-test.10/ui_comments.js","apps/video/hanime1/releases/2.0.0-test.10/ui_login.js","apps/video/hanime1/releases/2.0.0-test.10/ui_misc.js","apps/video/hanime1/releases/2.0.0-test.11/patch_provider.js","apps/video/hanime1/releases/2.0.0-test.11/ui_common.js","apps/video/hanime1/releases/2.0.0-test.11/ui_detail.js","apps/video/hanime1/releases/2.0.0-test.11/ui_comments.js","apps/video/hanime1/releases/2.0.0-test.11/ui_login.js","apps/video/hanime1/releases/2.0.0-test.11/ui_misc.js","apps/video/hanime1/releases/2.0.0-test.12/ui_layout.js","apps/video/hanime1/releases/2.0.0-test.12/ui_home.js","apps/video/hanime1/releases/2.0.0-test.12/ui_library.js","apps/video/hanime1/releases/2.0.0-test.12/ui_results.js","apps/video/hanime1/releases/2.0.0-test.12/ui_detail.js","apps/video/hanime1/releases/2.0.0-test.12/ui_comments.js","apps/video/hanime1/releases/2.0.0-test.12/ui_login.js","apps/video/hanime1/releases/2.0.0-test.12/ui_comic.js","apps/video/hanime1/releases/2.0.0-test.12/ui_settings.js"];
for(var i=0;i<P.length;i++){require(ROOT+P[i]+'?hanime_recovery=15',{headers:{'Cache-Control':'no-cache'}},20015);}
HanimePages.build='2.0.0-test.15';
HanimeCore.build='2.0.0-test.15';
HanimeProvider.build='2.0.0-test.15';
})();
