/* 汤头条 0.1.0-test.12 Runtime / App+PWA provider */
var TangTouTiaoRemoteRuntime=(function(){
  var instance=null;
  function diagnosticsText(){var keys=['ttt_last_featured_exact','ttt_last_detail_exact','ttt_last_access_state','ttt_last_short_provider','ttt_last_pwa','ttt_last_image_policy','ttt_last_image_diag','ttt_last_play_sources','ttt_last_source_probe','ttt_last_play_diag','ttt_last_purchase','ttt_last_community_home','ttt_last_community_list','ttt_last_player_cfg','ttt_last_version_info','ttt_last_comic_home','ttt_last_comic_list','ttt_last_rank_exact','ttt_last_probe','ttt_last_bootstrap'],a=[];for(var i=0;i<keys.length;i++){var v=getItem(keys[i],'');if(v)a.push(keys[i]+'\n'+v);}return a.join('\n\n')||'暂无诊断记录';}
  function settings(){var d=[],s=TangTouTiaoProtocolV015.sessionInfo();setPageTitle('设置与诊断');d.push({title:'汤头条 Test12',desc:'0.1.0-test.12 · Build 10112 · App + PWA 双 Provider',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行状态',desc:'设备 '+(s.deviceReady?'已建立':'未建立')+'｜Token '+(s.tokenReady?'已建立':'未建立')+'｜播放器 '+(s.playerReady?'已就绪':'未就绪'),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行协议诊断',url:$('#noLoading#').lazyRule(function(){try{var a=$.require('ttt').protocolProbe();refreshPage(false);return'toast://诊断完成：'+a.filter(function(x){return x.ok;}).length+'/'+a.length+' 成功';}catch(e){return'toast://诊断失败：'+e;}}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:diagnosticsText(),url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});d.push({title:'重新初始化匿名身份',desc:'仅在 Token/会话异常时使用',url:$('#noLoading#').lazyRule(function(){try{$.require('ttt').resetSession(true);return'toast://已清理，返回首页会重新握手';}catch(e){return'toast://失败：'+e;}}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'Test12 修复重点',desc:'参考汤头条2：引入同站 PWA Provider，短视频/搜索优先 PWA、App 详情负责播放与收费语义；图片采用参考规则已验证的 AES/CBC/PKCS5Padding 直接输入流解密；社区首页改为紧凑频道导航并尝试真实帖子接口。',url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);}
  function purchaseAndPlay(id,title,coins,duration){try{var r=TangTouTiaoProtocolV015.call('/api/user/watchingMvByCoins',{mvId:String(id)}),d=TangTouTiaoCoreV020.dataOf(r)||{},url=String(TangTouTiaoCoreV020.pick(d,['url','play_url','playUrl'],'')||''),msg=TangTouTiaoCoreV020.text(TangTouTiaoCoreV020.pick(d,['msg','message'],'')||'');if(!url)return'toast://'+(msg||'未取得解锁后的完整播放地址');return TangTouTiaoPlaybackV018.playBest(JSON.stringify({id:String(id),title:String(title||''),expectedDuration:String(duration||''),sources:[{name:'已解锁',url:url}]}),'已解锁');}catch(e){return'toast://解锁失败：'+String(e.message||e);}}
  function playById(rec){var x={};try{x=typeof rec==='string'?JSON.parse(rec):rec||{};}catch(e){}var id=String(x.id||'');if(!id)return'toast://缺少视频ID';try{var r=TangTouTiaoProtocolV015.call('/api/MvDetail/detail',{id:id}),it=TangTouTiaoCoreV020.detailItem(r,x),ac=TangTouTiaoCoreV020.accessState(it);TangTouTiaoCoreV020.addHistory(it);if(ac.locked){if(it.preview)return TangTouTiaoPlaybackV018.playBest(JSON.stringify({id:id,title:it.title,expectedDuration:'',sources:[{name:'预览',url:it.preview}]}),'预览');return'toast://该视频需 '+ac.coins+' 汤币解锁完整版';}var src=TangTouTiaoCoreV020.sources(it);if(src.length)return TangTouTiaoPlaybackV018.playBest(JSON.stringify({id:id,title:it.title,expectedDuration:it.duration,sources:src}),'240P');}catch(e1){}if(x.preview)return TangTouTiaoPlaybackV018.playBest(JSON.stringify({id:id,title:String(x.title||''),expectedDuration:'',sources:[{name:'预览',url:x.preview}]}),'预览');return'toast://未取得可播放线路';}
  function module(){if(instance)return instance;if(typeof TangTouTiaoPwaV020!=='object'||typeof TangTouTiaoCoreV020!=='object'||typeof TangTouTiaoPagesV020!=='object')throw new Error('汤头条 Test12 模块未完整加载');var m={version:'0.1.0-test.12',build:10112,home:TangTouTiaoPagesV020.home,channels:TangTouTiaoPagesV020.channels,channel:TangTouTiaoPagesV020.channel,community:TangTouTiaoPagesV020.community,search:TangTouTiaoPagesV020.search,detail:TangTouTiaoPagesV020.detail,mine:TangTouTiaoPagesV020.mine,rank:TangTouTiaoPagesV020.rank,settings:settings,protocolProbe:function(){return TangTouTiaoProtocolV015.probe();},resetSession:function(full){return TangTouTiaoProtocolV015.resetSession(!!full);},sessionInfo:function(){return TangTouTiaoProtocolV015.sessionInfo();},playBest:function(p,q){return TangTouTiaoPlaybackV018.playBest(p,q);},playById:playById,playPreview:function(h,p){return TangTouTiaoPlaybackV018.playBest(p,'预览');},playDirect:function(h,p,q){return TangTouTiaoPlaybackV018.playBest(p,q);},purchaseAndPlay:purchaseAndPlay,toggleFavFromDetail:function(s){var x=JSON.parse(String(s||'{}'));return TangTouTiaoCoreV020.toggleFav(x);}};instance=m;return m;}return{version:'0.1.0-test.12',build:10112,module:module};
})();
