/* 汤头条 0.1.0-test.18 Pages / APP-short exact provider + classification center phase 1 */
var TangTouTiaoPagesV026=(function(){
  var B=TangTouTiaoPagesV025,P=TangTouTiaoProtocolV015,W=TangTouTiaoPwaV020,C=TangTouTiaoCoreV024,U=TangTouTiaoUIV015,O={};for(var k in B)if(B.hasOwnProperty(k))O[k]=B[k];
  var HOME='ttt_home_tab_v010',FC='ttt17_featured_cache',SC='ttt18_short_app_cache_recommend',TTL=300000,STTL=180000;
  function txt(v){return C.text?C.text(v):String(v==null?'':v).replace(/<[^>]+>/g,'').trim();}
  function val(o,keys,d){return C.pick?C.pick(o,keys,d):d;}
  function safeJson(v){if(typeof v!=='string')return v;var s=String(v||'').trim();if(!s)return v;if((s.charAt(0)==='{'&&s.charAt(s.length-1)==='}')||(s.charAt(0)==='['&&s.charAt(s.length-1)===']'))try{return JSON.parse(s);}catch(e){}return v;}
  function searchInput(d){d.push({title:'搜索视频、创作者、关键词',col_type:'input',url:$.toString(function(){var w=String(input||'').trim();if(!w)return'toast://请输入搜索关键词';putMyVar('ttt_search_kw',w);return'hiker://page/tttSearch?rule=&simple=true&kw='+encodeURIComponent(w);}),extra:{defaultValue:'',titleVisible:true,onChange:$.toString(function(){})}});}
  function quick(d){var a=[['频道','channel',C.page('tttChannels')],['社区','community',C.page('tttCommunity')],['排行榜','rank',C.page('tttRank')],['我的','mine',C.page('tttMine')]];for(var i=0;i<a.length;i++)d.push(U.icon(a[i][0],a[i][1],a[i][2]));}
  function header(d){searchInput(d);var tab=getMyVar(HOME,'recommend')||'recommend',tabs=[['recommend','推荐'],['short','短视频'],['long','长视频'],['community','社区']];for(var i=0;i<tabs.length;i++)d.push(U.chip(tabs[i][1],tab===tabs[i][0],U.state(HOME,tabs[i][0])));d.push(U.blank());quick(d);d.push(U.line());return tab;}
  function snap(it){return{id:it.id,title:it.title,coverRaw:it.coverRaw,author:it.author,duration:it.duration,plays:it.plays,desc:it.desc,source240:it.source240,source480:it.source480,source720:it.source720,source1080:it.source1080,sourceOrigin:it.sourceOrigin,preview:it.preview,previewTip:it.previewTip,isPay:!!it.isPay,isFree:Number(it.isFree||0),coins:Number(it.coins||0),mvType:Number(it.mvType||0)};}
  function hydrate(x){x=x||{};x.cover=C.imageUrl(x.coverRaw||'');return x;}
  function cacheGet(key,ttl){try{var s=getMyVar(key,'');if(!s)return null;var o=JSON.parse(s);if(!o||!Array.isArray(o.list)||Date.now()-Number(o.time||0)>ttl)return null;var a=[];for(var i=0;i<o.list.length;i++)a.push(hydrate(o.list[i]));setItem('ttt_last_feed_cache',JSON.stringify({time:Date.now(),key:key,hit:true,count:a.length,age:Date.now()-Number(o.time||0)}));return a;}catch(e){return null;}}
  function cachePut(key,list){var a=[];for(var i=0;i<list.length;i++)a.push(snap(list[i]));try{putMyVar(key,JSON.stringify({time:Date.now(),list:a}));setItem('ttt_last_feed_cache',JSON.stringify({time:Date.now(),key:key,hit:false,count:a.length}));}catch(e){}return list;}
  function featured(){var c=cacheGet(FC,TTL);if(c)return c;var r=P.call('/api/MvList/featuredAv',{page:1,limit:30}),a=C.normalize(r,'featured')||[];return cachePut(FC,a);}
  function shortApp(){var r=P.call('/api/MvList/smallVideoByTag',{tag:'recommend',page:1,limit:20}),a=C.normalize(r,'short')||[];try{var f=a[0]||{};setItem('ttt_last_short_app_exact',JSON.stringify({time:Date.now(),count:a.length,firstId:f.id||'',duration:f.duration||'',hasSource240:!!f.source240,source240:String(f.source240||'').substring(0,220),schema:P.schema(C.dataOf(r))}));}catch(e){}return a;}
  function shorts(){var c=cacheGet(SC,STTL);if(c)return c;try{var a=shortApp();if(a.length){setItem('ttt_last_short_provider',JSON.stringify({time:Date.now(),provider:'app-smallVideoByTag-exact',count:a.length}));return cachePut(SC,a);}}catch(e0){try{setItem('ttt_last_short_app_exact',JSON.stringify({time:Date.now(),error:String(e0.message||e0)}));}catch(e1){}}
    try{var r=W.shortVideos(1,'recommend'),p=C.normalize(r,'short')||[];if(p.length){setItem('ttt_last_short_provider',JSON.stringify({time:Date.now(),provider:'pwa-fallback',count:p.length}));return cachePut(SC,p);}}catch(e2){}
    try{var ar=P.call('/api/MvList/small',{page:1,limit:20}),al=C.normalize(ar,'short')||[];setItem('ttt_last_short_provider',JSON.stringify({time:Date.now(),provider:'app-small-fallback',count:al.length}));return cachePut(SC,al);}catch(e3){return[];}}
  function sec(s){s=String(s||'');var a=s.split(':'),n=[];for(var i=0;i<a.length;i++){var v=Number(a[i]);if(isNaN(v))return 0;n.push(v);}if(n.length===3)return n[0]*3600+n[1]*60+n[2];if(n.length===2)return n[0]*60+n[1];return n[0]||0;}
  function longList(a){var o=[];for(var i=0;i<a.length;i++){var it=a[i];if(sec(it.duration)>=180||it.source240||it.source480||it.source720||it.source1080)o.push(it);}return(o.length?o:a).slice(0,36);}
  function record(it){var r=C.plainRecord?C.plainRecord(it):snap(it);r.preview=it.preview||r.preview||'';r.source240=it.source240||r.source240||'';return JSON.stringify(r);}
  function shortMeta(it){var a=[];if(it.author)a.push(it.author);var s=sec(it.duration);if(s>5&&it.duration)a.push(it.duration);if(it.plays)a.push(it.plays);return a.join(' · ');}
  function shortCard(it){return{title:it.title||'未命名',desc:shortMeta(it),img:it.cover||'',pic_url:it.cover||'',url:$('#noLoading#').lazyRule(function(x){try{return $.require('ttt').playShortStable(x);}catch(e){return'toast://播放失败：'+String(e.message||e);}},record(it)),col_type:'movie_2',extra:{lineVisible:false,inheritTitle:false,ttt_id:it.id,ttt_direct_play:true}};}
  function pushVideo(d,a){for(var i=0;i<a.length;i++)d.push(U.videoCard(C,a[i],'movie_2'));}
  function pushShort(d,a){for(var i=0;i<a.length;i++)d.push(shortCard(a[i]));}
  function home(){var d=[],pg=Number(MY_PAGE||1);setPageTitle('汤头条');if(pg>1){setResult(d);return;}var tab=header(d);try{if(tab==='community'){B.home();return;}if(tab==='short'){var s=shorts();d.push(U.section('热门短视频','视频 '+s.length+' 条 · APP原生列表优先'));pushShort(d,s);if(!s.length)d.push(U.empty('短视频暂时没有数据',''));setResult(d);return;}var all=featured(),list=tab==='long'?longList(all):all.slice(0,36);d.push(U.section(tab==='long'?'精选长视频':'今日推荐','视频 '+list.length+' 条 · 缓存快速切换'));pushVideo(d,list);if(!list.length)d.push(U.empty('当前列表暂无内容',''));}catch(e){d.push(U.error('首页请求失败',e,C.page('tttSettings')));}setResult(d);}
  function groupTitle(d,t,desc){d.push(U.section(t,desc||''));}
  function entry(t,sub,type){return{title:t,desc:sub||'',url:C.page('tttChannel',{type:type,title:t}),col_type:'text_2',extra:{lineVisible:false}};}
  function channels(){var d=[];setPageTitle('内容频道');groupTitle(d,'视频发现','先补原 APP 高频入口');d.push(entry('视频分类','动态口味/标签分类','videoStyles'));d.push(entry('短视频','APP smallVideoByTag','short'));d.push(entry('创作者','精选创作者/作品','creator'));d.push(entry('排行榜','播放、汤币、付费、关注','rank'));d.push(U.line());groupTitle(d,'社区互动','社区、合集与兴趣内容');d.push(entry('社区','关注/热门/发现/精选','community'));d.push(entry('话题','热门话题与专题','topic'));d.push(entry('合集','热门/最新合集','compilation'));d.push(entry('求片','求片广场','find'));d.push(entry('粉丝团','创作者粉丝团','club'));d.push(U.line());groupTitle(d,'阅读内容','图集、小说、有声、漫画');d.push(entry('图集','图片作品与系列','picture'));d.push(entry('小说','小说首页与基础详情','novel'));d.push(entry('有声','有声作品与基础详情','audio'));d.push(entry('漫画','动态分类与漫画列表','comic'));d.push(U.line());groupTitle(d,'创作与扩展','后续继续接入');d.push(entry('AI 创作','换脸/绘图/视频/小说','ai'));d.push(entry('游戏','原 APP 游戏中心','game'));setResult(d);}
  function objectWalk(root,kind){var out=[],seen={};function add(x){x=safeJson(x);if(!x||typeof x!=='object'||Array.isArray(x))return;var id=String(val(x,['id','book_id','audio_id','picture_id','topic_id','compilation_id','uuid','_id'],'')||''),name=txt(val(x,['title','name','nickname','text','notice'],'')||'');var ok=false;if(kind==='picture')ok=!!(id&&name&&(x.thumb||x.img||x.category_title!==undefined||x.is_gif!==undefined));else if(kind==='novel')ok=!!(id&&name&&(x.thumbnail||x.chapter_count!==undefined||x.word_count!==undefined));else if(kind==='audio')ok=!!(id&&name&&(x.thumbnail||x.cur_chapter||x.download_info||x.chapter_count!==undefined));else if(kind==='compilation')ok=!!(id&&name&&(x.image||x.count!==undefined||x.uuid!==undefined));else if(kind==='topic')ok=!!(id&&name&&(x.thumb||x.bg_thumb||x.post_num!==undefined||x.follow_num!==undefined));else if(kind==='find')ok=!!(id&&name&&(x.cover_thumb||x.cover_full||x.rating!==undefined));else if(kind==='club')ok=!!(id&&(name||x.items||x.notice));else if(kind==='creator')ok=!!((x.uuid||x.owner_uuid||x.uid)&&((x.nickname||x.name)||x.thumb||x.thumb_url));else if(kind==='chapter')ok=!!(id&&name&&(x.chapter!==undefined||x.novel_id!==undefined||x.audio_id!==undefined));if(ok){var key=kind+'|'+id+'|'+name;if(!seen[key]){seen[key]=1;out.push(x);}}}
    function walk(v,depth){if(depth>8||v==null)return;v=safeJson(v);if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],depth+1);return;}if(typeof v==='object'){add(v);for(var k in v)if(v.hasOwnProperty(k)&&!/banner|ads|advert|hot_conf/i.test(k))walk(v[k],depth+1);}}
    walk(C.dataOf(root),0);return out;}
  function imgOf(x,kind){var raw='';if(kind==='picture')raw=val(x,['thumb','cover','img_url'],'')||'';else if(kind==='novel'||kind==='audio')raw=val(x,['thumbnail','thumb','cover'],'')||'';else if(kind==='compilation')raw=val(x,['image','thumb'],'')||'';else if(kind==='topic')raw=val(x,['thumb','bg_thumb'],'')||'';else if(kind==='find')raw=val(x,['cover_thumb','cover_full'],'')||'';else raw=val(x,['thumb','thumb_url','avatar','image'],'')||'';return raw?C.imageUrl(raw):'';}
  function contentTitle(x){return txt(val(x,['title','name','nickname','text','notice'],'')||'未命名');}
  function contentDesc(x,kind){var a=[];if(kind==='picture'){var c=txt(val(x,['category_title','tags'],'')||'');if(c)a.push(c);var v=val(x,['real_view_num','view_count'],'');if(v!==''&&v!=null)a.push('浏览 '+v);}else if(kind==='novel'||kind==='audio'){var au=txt(val(x,['author'],'')||'');if(au)a.push(au);var cc=val(x,['chapter_count'],'');if(cc!==''&&cc!=null)a.push(cc+' 章');var tg=txt(val(x,['tags'],'')||'');if(tg)a.push(tg);}else if(kind==='compilation'){var n=val(x,['count'],'');if(n!==''&&n!=null)a.push(n+' 部');var dt=txt(val(x,['date'],'')||'');if(dt)a.push(dt);}else if(kind==='topic'){var p=val(x,['post_num'],'');if(p!==''&&p!=null)a.push('帖子 '+p);var f=val(x,['follow_num'],'');if(f!==''&&f!=null)a.push('关注 '+f);}else if(kind==='find'){var r=txt(val(x,['rating'],'')||'');if(r)a.push('评分 '+r);var dr=txt(val(x,['duration'],'')||'');if(dr)a.push(dr);}else if(kind==='club'){var n2=txt(val(x,['notice'],'')||'');if(n2)a.push(n2);}return a.join(' · ');}
  function contentCard(x,kind){var id=String(val(x,['id','book_id','audio_id','picture_id','topic_id','compilation_id','uuid','_id'],'')||''),t=contentTitle(x),img=imgOf(x,kind),url='hiker://empty';if(kind==='picture'||kind==='novel'||kind==='audio')url=C.page('tttChannel',{type:'contentDetail',kind:kind,id:id,title:t});else if(kind==='compilation')url=C.page('tttChannel',{type:'compilationDetail',id:id,title:t});return{title:t,desc:contentDesc(x,kind),img:img,pic_url:img,url:url,col_type:img?'movie_3':'text_1',extra:{lineVisible:false,ttt_content_kind:kind,ttt_content_id:id}};}
  function responseInfo(d,r,label){var m=P.meta(r,label);d.push(U.empty('当前接口暂未解析到可显示内容',(m.code!==''?'code '+m.code+' · ':'')+(m.msg||m.schema||'')));try{setItem('ttt_last_channel_diag',JSON.stringify({time:Date.now(),label:label,code:m.code,msg:m.msg,schema:m.schema}));}catch(e){}}
  function contentList(d,kind,title){var map={picture:['/api/picture/home',{}],novel:['/api/novel/home',{}],audio:['/api/audio/home',{}],compilation:['/api/compilation/list',{page:1,size:20,sort:'hot'}],find:['/api/find/list',{page:1,type:'',sort:'',has_coins:'',is_match:'',date_range:''}],club:['/api/club/items',{page:1}],topic:['/api/community/topics',{page:1}]},cfg=map[kind];if(!cfg){d.push(U.empty(title+' 尚未接入'));return;}var r=P.call(cfg[0],cfg[1]),a=objectWalk(r,kind);d.push(U.section(title,a.length+' 条'));for(var i=0;i<a.length;i++)d.push(contentCard(a[i],kind));if(!a.length)responseInfo(d,r,cfg[0]);try{setItem('ttt_last_channel_diag',JSON.stringify({time:Date.now(),kind:kind,path:cfg[0],count:a.length,schema:P.schema(C.dataOf(r))}));}catch(e){}
  }
  function findObject(v,kind,id,depth){if(depth>8||v==null)return null;v=safeJson(v);if(Array.isArray(v)){for(var i=0;i<v.length;i++){var a=findObject(v[i],kind,id,depth+1);if(a)return a;}return null;}if(typeof v==='object'){var xid=String(val(v,['id','book_id','audio_id','picture_id'],'')||'');if(xid===String(id))return v;for(var k in v)if(v.hasOwnProperty(k)){var b=findObject(v[k],kind,id,depth+1);if(b)return b;}}return null;}
  function contentDetail(d,kind,id,title){var ep={picture:'/api/picture/detail',novel:'/api/novel/detail',audio:'/api/audio/detail'}[kind];if(!ep){d.push(U.empty('未知内容类型'));return;}var r=P.call(ep,{id:id}),root=C.dataOf(r),x=findObject(root,kind,id,0)||safeJson(root)||{},img=imgOf(x,kind),desc=txt(val(x,['description','desc'],'')||'');d.push({title:contentTitle(x)||title,desc:contentDesc(x,kind),img:img,pic_url:img,url:'hiker://empty',col_type:img?'movie_1_vertical_pic_blur':'text_1',extra:{lineVisible:false}});if(desc){d.push(U.line());d.push(U.section('简介',''));d.push({title:desc,url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});}if(kind==='picture'){var imgs=Array.isArray(x.img)?x.img:[],shown=0;if(imgs.length){d.push(U.line());d.push(U.section('图集','图片 '+imgs.length+' 张'));for(var i=0;i<imgs.length&&i<30;i++){var u=String(val(imgs[i],['img_url','url','src'],'')||'');if(!u)continue;var iu=C.imageUrl(u);d.push({title:'',img:iu,pic_url:iu,url:'hiker://empty',col_type:'pic_1_full',extra:{lineVisible:false}});shown++;}if(!shown)d.push(U.empty('图片地址暂未返回'));}}
    if(kind==='novel'){try{var cr=P.call('/api/novel/chaptersList',{id:id,limit:3,page:1}),chs=objectWalk(cr,'chapter');if(chs.length){d.push(U.line());d.push(U.section('最近章节','先展示前 '+Math.min(3,chs.length)+' 章'));for(var j=0;j<chs.length&&j<3;j++)d.push({title:contentTitle(chs[j]),desc:Number(val(chs[j],['coins'],0)||0)>0?'付费章节':'',url:'toast://小说正文将在下一阶段接入',col_type:'text_1',extra:{lineVisible:false}});}}catch(e0){}}
    if(kind==='audio')d.push(U.empty('有声章节播放将在下一阶段接入','本轮先恢复首页、作品列表与详情信息'));try{setItem('ttt_last_content_detail',JSON.stringify({time:Date.now(),kind:kind,id:id,schema:P.schema(root)}));}catch(e1){}
  }
  function compilationDetail(d,id,title){var r=P.call('/api/compilation/mvlist',{compilation_id:id,page:1,limit:30}),a=C.normalize(r,'')||[];d.push(U.section(title,a.length+' 部视频'));for(var i=0;i<a.length;i++)d.push(U.videoCard(C,a[i],'movie_2'));if(!a.length)responseInfo(d,r,'/api/compilation/mvlist');}
  function styleNodes(r){var root=C.dataOf(r),out=[],seen={};function walk(v,depth){if(depth>6||v==null)return;v=safeJson(v);if(Array.isArray(v)){for(var i=0;i<v.length;i++)walk(v[i],depth+1);return;}if(typeof v==='object'){var id=val(v,['id','style_id','value'],'');var name=txt(val(v,['name','title','label'],'')||'');if(id!==''&&id!=null&&name&&!v.source_240&&!v.thumb_cover){var key=String(id)+'|'+name;if(!seen[key]){seen[key]=1;out.push({id:String(id),name:name});}}for(var k in v)if(v.hasOwnProperty(k))walk(v[k],depth+1);}}walk(root,0);return out;}
  function videoStyles(d){var r=P.call('/api/MvSearch/getStyle',{}),a=styleNodes(r);d.push(U.section('视频分类',a.length+' 个分类'));for(var i=0;i<a.length;i++)d.push(U.category(a[i].name,C.page('tttChannel',{type:'styleList',title:a[i].name,style_id:a[i].id}),false));if(!a.length)responseInfo(d,r,'/api/MvSearch/getStyle');try{setItem('ttt_last_style_home',JSON.stringify({time:Date.now(),count:a.length,schema:P.schema(C.dataOf(r))}));}catch(e){}
  }
  function styleList(d,id,title){var pg=Number(C.param('p','1')||1),r=P.call('/api/MvList/style',{id:Number(id),page:pg,size:30,orderBy:'id'}),a=C.normalize(r,'')||[];d.push(U.section(title,a.length+' 条'));for(var i=0;i<a.length;i++)d.push(U.videoCard(C,a[i],'movie_2'));if(!a.length)responseInfo(d,r,'/api/MvList/style');try{setItem('ttt_last_style_list',JSON.stringify({time:Date.now(),id:id,page:pg,count:a.length,schema:P.schema(C.dataOf(r))}));}catch(e){}
  }
  function creatorPage(d){var r=P.call('/api/Creator/featured',{limit:20}),a=C.normalize(r,'')||[];d.push(U.section('精选创作者','作品 '+a.length+' 条'));for(var i=0;i<a.length;i++)d.push(U.videoCard(C,a[i],'movie_2'));if(!a.length){var c=objectWalk(r,'creator');for(var j=0;j<c.length;j++)d.push(contentCard(c[j],'creator'));if(!c.length)responseInfo(d,r,'/api/Creator/featured');}try{setItem('ttt_last_creator_featured',JSON.stringify({time:Date.now(),videoCount:a.length,schema:P.schema(C.dataOf(r))}));}catch(e){}
  }
  function channel(){var d=[],type=C.param('type',''),title=C.param('title','内容频道');setPageTitle(title);try{if(type==='short'){var s=shorts();d.push(U.section('热门短视频','视频 '+s.length+' 条 · APP原生接口优先'));pushShort(d,s);if(!s.length)d.push(U.empty('短视频暂时没有数据'));setResult(d);return;}if(type==='videoStyles'){videoStyles(d);setResult(d);return;}if(type==='styleList'){styleList(d,C.param('style_id',''),title);setResult(d);return;}if(type==='creator'){creatorPage(d);setResult(d);return;}if(type==='picture'||type==='novel'||type==='audio'||type==='compilation'||type==='find'||type==='club'||type==='topic'){contentList(d,type,title);setResult(d);return;}if(type==='contentDetail'){contentDetail(d,C.param('kind',''),C.param('id',''),title);setResult(d);return;}if(type==='compilationDetail'){compilationDetail(d,C.param('id',''),title);setResult(d);return;}if(type==='ai'){d.push(U.section('AI 创作','原 APP 已发现换脸、绘图、视频、小说四套接口'));d.push(U.empty('下一阶段按独立工作流接入','不会把 AI 功能硬塞进普通视频 Adapter'));setResult(d);return;}if(type==='game'){d.push(U.section('游戏中心','原 APP /api/game/* 与 /api/porngame/*'));d.push(U.empty('下一阶段按游戏数据模型接入'));setResult(d);return;}B.channel();return;}catch(e){d.push(U.error(title+' 加载失败',e,C.page('tttSettings')));setResult(d);}}
  O.home=home;O.channels=channels;O.channel=channel;O.version='0.1.0-test.18';return O;
})();
