/* 汤头条 0.1.0-test.21 Local-First final overlay over Test20 */
var TangTouTiaoRuntimeV020=TangTouTiaoRemoteRuntime;
var TangTouTiaoRemoteRuntime=(function(){
  var VERSION='0.1.0-test.21',BUILD=10121,instance=null;
  var PACKAGE='__hclocal22_tangtoutiao-test_b10121.json';
  function cloneObj(o){var r={};if(o&&typeof o==='object')for(var k in o)if(o.hasOwnProperty(k))r[k]=o[k];return r;}
  function readPackage(){try{if(!fileExist(PACKAGE))return null;var p=JSON.parse(String(readFile(PACKAGE,0)||'{}'));if(Number(p.build||0)!==BUILD||String(p.manager||'')!=='2.2.0'||String(p.execution||'')!=='native-require-file'||!Array.isArray(p.files))return null;return p;}catch(e){return null;}}
  function localInfo(){var p=readPackage(),ready=!!p;if(ready){for(var i=0;i<p.files.length;i++){if(!p.files[i]||!p.files[i].file||!fileExist(String(p.files[i].file))){ready=false;break;}}}return{version:VERSION,build:BUILD,ready:ready,modules:p&&p.files?p.files.length:0,manager:p?String(p.manager||''):'',installedAt:p?Number(p.installedAt||0):0,ref:p?String(p.ref||''):''};}
  function diagnosticsText(){var keys=['ttt_last_featured_exact','ttt_last_detail_exact','ttt_last_image_policy','ttt_last_play_sources','ttt_last_short_app_exact','ttt_last_short_provider','ttt_last_creator_discover','ttt_last_creator_featured','ttt_last_rank_exact','ttt_last_dynamic_channel','ttt_last_content_detail','ttt_last_community_detail','ttt_last_comic_detail','ttt_last_comic_read'],a=[];for(var i=0;i<keys.length;i++){var v=getItem(keys[i],'');if(v)a.push(keys[i]+'\n'+v);}return a.join('\n\n')||'暂无诊断记录';}
  function settings(){var d=[],li=localInfo(),s={};try{s=TangTouTiaoProtocolV015.sessionInfo();}catch(e){}setPageTitle('设置与诊断');d.push({title:'汤头条 '+VERSION,desc:'Build '+BUILD+' · Test20 业务基线 Native Local-First',url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});d.push({title:'本地运行包',desc:(li.ready?'已就绪':'未完成')+' · '+li.modules+' 模块 · Manager '+(li.manager||'--')+'\nref '+(li.ref||'--'),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'运行状态',desc:'设备 '+(s.deviceReady?'已建立':'未建立')+'｜Token '+(s.tokenReady?'已建立':'未建立')+'｜播放器密钥 '+(s.playerReady?'已取得':'未取得')+'｜APP '+(s.version||'9.6.2'),url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'重新初始化匿名身份',desc:'仅当服务端会话异常时使用；不会删除本地程序包',url:$('#noLoading#').lazyRule(function(){try{$.require('ttt').resetSession(true);refreshPage(false);return'toast://已清理并重新建立会话';}catch(e){return'toast://重置失败：'+String(e.message||e);}}),col_type:'text_1',extra:{lineVisible:false}});d.push({title:'版本更新',desc:'程序代码更新由“我的规则仓库”统一管理；正常启动不再加载 Remote Manager/Bootstrap。',url:'hiker://empty',col_type:'text_1',extra:{lineVisible:false}});d.push({title:'已知边界',desc:'Test20 的免费长视频/官方试看与封面链保持原样；短视频约2–3秒仍是既有未解决问题，本地化版不宣称修复。',url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});d.push({title:'最近诊断',desc:diagnosticsText(),url:'hiker://empty',col_type:'long_text',extra:{lineVisible:false}});setResult(d);}
  function module(){if(instance)return instance;if(!TangTouTiaoRuntimeV020||typeof TangTouTiaoRuntimeV020.module!=='function')throw new Error('汤头条 Test20 Runtime 缺失');var base=TangTouTiaoRuntimeV020.module(),m=cloneObj(base);m.version=VERSION;m.build=BUILD;m.localFirstVersion=VERSION;m.localFirstBuild=BUILD;m.localFirstInfo=localInfo;m.settings=settings;instance=m;return m;}
  return{version:VERSION,build:BUILD,module:module};
})();
