/* 我的规则仓库 3.5.4-rc5 - Single Workspace 13.0 */
(function(R){
var fallback={home:R.home,category:R.categoryPage,search:R.searchPage,updates:R.updatesPage,detail:R.detailPage,channel:R.channelPage,history:R.historyPage,settings:R.settingsPage,about:R.aboutPage};
R.singleWorkspaceVersion='13.0.0';

R.hybridCanWeb=function(){
 try{var a=getColTypes();return !Array.isArray(a)||a.indexOf('x5_webview_single')>=0;}catch(e){return true;}
};

R.hybridRuleName=function(){
 try{var x=getRule();if(x&&x.title)return String(x.title);}catch(e){}
 try{if(typeof MY_RULE==='object'&&MY_RULE&&MY_RULE.title)return String(MY_RULE.title);}catch(e2){}
 return this.isTestChannel()?'我的规则仓库·测试版':'我的规则仓库';
};

R.hybridJson=function(value){return JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');};
R.hybridDataUrl=function(html){return'data:text/html;base64,'+base64Encode(String(html||''));};
R.hybridWebItem=function(html,id){
 return{title:'',url:this.hybridDataUrl(html),col_type:'x5_webview_single',desc:'float&&screen-100',extra:{id:'rule-repo-single13-'+String(id||'workspace'),canBack:true,showProgress:false,jsLoadingInject:false,lineVisible:false,imgLongClick:false}};
};

R.primaryAction=function(title,url){return{title:String(title||'确认'),url:url||'hiker://empty',col_type:'text_2',extra:{lineVisible:false,textAlign:'center',backgroundColor:'#1685F8'}};};
R.secondaryAction=function(title,url){return{title:String(title||'操作'),url:url||'hiker://empty',col_type:'text_2',extra:{lineVisible:false,textAlign:'center',backgroundColor:'#E8F2FF'}};};

R.workspaceAction=function(kind,item){
 if(kind==='open')return $('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id);if(!x)return'toast://程序不存在';if(String(x.id)==='rule-repo'&&r.isTestChannel()){r.recordOpen(x);return'hiker://home@我的规则仓库·测试版||hiker://home';}return r.openRule(x);},item.id);
 if(kind==='import')return $('#noLoading#').lazyRule(function(raw){return $.require('hiker://page/ruleRepoCore').importRule(raw);},JSON.stringify(item.raw));
 if(kind==='favorite')return $('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id);if(!x)return'toast://程序不存在';var on=r.toggleFav(x);return'toast://'+(on?'已收藏':'已取消收藏');},item.id);
 if(kind==='check')return $('#noLoading#').lazyRule(function(id){var r=$.require('hiker://page/ruleRepoCore'),x=r.findById(id,true);if(!x)return'toast://程序不存在';r.clearPresenceCache&&r.clearPresenceCache();return'toast://'+r.nativeStatusMeta(x).label+' · 云端 '+r.nativeVersionText(x);},item.id);
 return'hiker://empty';
};

R.workspaceChannelData=function(parent,c,index){
 var raw=this.channelInstallRaw(parent,c),ch=String(c.channel||''),current=String(parent.id||'')==='rule-repo'&&((this.isTestChannel()&&ch==='test')||(!this.isTestChannel()&&ch==='stable'));
 return{channel:ch,label:ch==='stable'?'正式版':(ch==='test'?'测试版':(ch==='local'?'本地版':'版本')),version:String(c.version||'--'),displayVersion:String(c.displayVersion||c.version||'--'),desc:String(c.desc||''),updatedAt:String(c.updatedAt||''),icon:String(c.icon||this.iconOf(parent)),highlights:Array.isArray(c.highlights)?c.highlights.slice(0,4):[],current:current,status:current?'当前运行':(ch==='stable'?'稳定推荐':(ch==='test'?'抢先体验':'独立安装')),action:$('#noLoading#').lazyRule(function(x){return $.require('hiker://page/ruleRepoCore').importRule(x);},JSON.stringify(raw)),order:Number(index||0)};
};

R.hybridProgramData=function(item,index){
 var st=this.nativeStatusMeta(item),tags=this.nativeProgramTags?this.nativeProgramTags(item):(item.tags||[]).slice(0,3),installed=this.actualInstalled?this.actualInstalled(item):!!this.installedVersion(item),group=String(item.entryType||'')==='channel-group'||!!item.channelsPath,channels=[];
 if(group){try{var meta=this.channelMeta(item),cs=meta&&meta.channels||[];for(var c=0;c<cs.length;c++)channels.push(this.workspaceChannelData(item,cs[c],c));}catch(e){}}
 return{
  id:String(item.id||''),name:String(item.name||'未命名程序'),version:this.nativeVersionText(item),localVersion:String(this.installedVersion(item)||'暂无'),status:String(st.label||'未安装'),statusColor:String(st.color||'#7A7F87'),installed:!!installed,update:String(st.label||'')==='可更新',favorite:!!this.isFav(item),channel:group,
  category:String(item.category||'other'),categoryName:String(item.categoryName||'程序'),subCategory:String(item.subCategory||''),mode:String(item.mode||''),typeText:group?'多版本程序':(item.mode==='remote'?'远程代码程序':'本地代码程序'),sizeText:item.bytes?Math.max(1,Math.round(Number(item.bytes)/1024))+' KB':'轻量规则',
  tags:tags.map(function(x){return String(x);}),desc:String(item.desc||this.nativeProgramSummary(item)||''),summary:String(this.nativeProgramSummary(item)||''),icon:String(this.iconOf(item)||''),updatedAt:String(item.updatedAt||'--'),order:Number(index||0),channels:channels,
  actions:{open:this.workspaceAction('open',item),import:group?'':this.workspaceAction('import',item),favorite:this.workspaceAction('favorite',item),check:this.workspaceAction('check',item)},
  search:[item.name,item.version,item.desc,item.categoryName,item.subCategory,(item.tags||[]).join(' ')].join(' ').toLowerCase()
 };
};

R.hybridPrograms=function(items){var out=[];for(var i=0;i<items.length;i++)out.push(this.hybridProgramData(items[i],i));return out;};

R.workspaceStaticActions=function(){
 var sync=$('#noLoading#').lazyRule(function(){showLoading('正在同步…');try{var r=$.require('hiker://page/ruleRepoCore'),x=r.syncManifest();r.clearPresenceCache&&r.clearPresenceCache();hideLoading();if(!x.ok)return'toast://同步失败，已保留当前目录';return x.fresh?'toast://目录已更新':'toast://当前已是最新目录';}catch(e){hideLoading();return'toast://同步失败，已保留当前目录';}});
 var backup=$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');return'copy://'+r.exportState();});
 var clearRecent=$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearOpenHistory();return'toast://最近打开已清空';});
 var clearSearch=$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearSearchHistory();return'toast://搜索历史已清空';});
 var clearImports=$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore');r.clearImportHistory();return'toast://导入记录已清空';});
 var recordSearch=$('#noLoading#').lazyRule(function(){var q=String(getVar('hc_repo_hybrid_search','')||'').trim();if(q)$.require('hiker://page/ruleRepoCore').recordSearch(q);return'toast://';});
 var diagnostics=$('#noLoading#').lazyRule(function(){var r=$.require('hiker://page/ruleRepoCore'),src=r.lastCloudSource?r.lastCloudSource():'--',rev=String(getItem(r.manifestRevisionKey,'--')||'--');return'confirm://Core '+r.version+'\\nbuild '+r.build+'\\nUI Single Workspace 13.0\\nrevision '+rev+'\\nsource '+src;});
 return{sync:sync,backup:backup,clearRecent:clearRecent,clearSearch:clearSearch,clearImports:clearImports,recordSearch:recordSearch,diagnostics:diagnostics};
};

R.workspaceData=function(items,initialView,initialId){
 var stats=this.stats(items),cats=this.nativeCategories(items),groups=[],programs=this.hybridPrograms(items),recentRaw=this.recentItems?this.recentItems(items,4):[],recent=[],imports=this.importHistory?this.importHistory().slice(0,20):[],opens=this.readOpenHistory?this.readOpenHistory().slice(0,20):[],tagsRaw=this.popularTags(items,10),tags=[],i,j;
 for(i=0;i<recentRaw.length;i++)recent.push(String(recentRaw[i].id||''));
 for(i=0;i<cats.length;i++){var subs=[];if(String(cats[i].id)!=='all'){var raw=this.subCategories(items,String(cats[i].id));for(j=0;j<raw.length;j++)if(String(raw[j].id||'all')!=='all')subs.push({id:String(raw[j].id||''),name:String(raw[j].name||'子分类'),count:Number(raw[j].count||0)});}groups.push({id:String(cats[i].id),name:String(cats[i].name),count:Number(cats[i].count||0),subs:subs});}
 for(i=0;i<tagsRaw.length;i++)tags.push(String(tagsRaw[i].name||''));
 var initialCategory=String(getVar('hc_repo_hybrid_category',getMyVar('hc_repo_home_category','all'))||'all'),initialScope=String(getVar('hc_repo_hybrid_scope',getMyVar('hc_repo_home_view','all'))||'all'),rawSearch=String(getParam('kw','')||getParam('s','')||''),initialSearch=String(this.safeDecodeKeyword?this.safeDecodeKeyword(rawSearch):rawSearch).trim();
 var valid=false;for(i=0;i<groups.length;i++)if(groups[i].id===initialCategory)valid=true;if(!valid)initialCategory='all';
 if(initialSearch&&this.recordSearch)this.recordSearch(initialSearch);
 return{ruleName:this.hybridRuleName(),title:'我的规则仓库',subtitle:'海阔视界专属 · 规则管理中心',icon:String((this.findById('rule-repo')||{}).icon||this.uiIcon('home')),version:String(this.version||'--'),build:Number(this.build||0),channel:this.isTestChannel()?'Test':'Stable',ui:'Single Workspace 13.0',stats:stats,categories:groups,programs:programs,recent:recent,history:{imports:imports,opens:opens},searchHistory:this.searchHistory?this.searchHistory().slice(0,8):[],popularTags:tags,initialView:String(initialView||'home'),initialId:String(initialId||''),initialCategory:initialCategory,initialScope:initialScope,initialSearch:initialSearch,settings:{probeMs:this.probeMs?Number(this.probeMs()||0):0,cacheMs:Number(this.cacheMs()||0),source:this.lastCloudSource?String(this.lastCloudSource()||'--'):'--',lastSync:this.formatTime(this.lastManifestTime?this.lastManifestTime():0)},actions:this.workspaceStaticActions(),navIcons:{home:[this.uiIconState('home',false),this.uiIconState('home',true)],category:[this.uiIconState('category',false),this.uiIconState('category',true)],search:[this.uiIconState('search',false),this.uiIconState('search',true)],updates:[this.uiIconState('updates',false),this.uiIconState('updates',true)],settings:[this.uiIconState('settings',false),this.uiIconState('settings',true)]}};
};

R.hybridBaseCss=function(){return[
 '*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}html,body{margin:0;width:100%;height:100%;max-width:100%;overflow:hidden;background:#fff;color:#20242a;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif}button,input,select{font:inherit;color:inherit}button{border:0;background:none;padding:0}img{display:block}.shell{width:100%;height:100%;display:grid;grid-template-rows:minmax(0,1fr) 64px;overflow:hidden}.view-host{min-width:0;min-height:0;overflow:hidden}.screen{width:100%;height:100%;display:flex;flex-direction:column;overflow:hidden;background:#fff}.fixed{flex:none;min-width:0}.scroll{flex:1;min-height:0;overflow-y:auto;overflow-x:hidden;overscroll-behavior:contain;-webkit-overflow-scrolling:touch;touch-action:pan-y;scrollbar-width:none}.scroll::-webkit-scrollbar{display:none}.pad{padding:0 14px}.muted{color:#858b94}.blue{color:#087bf0}.green{color:#16a36a}.amber{color:#e99a13}.hairline{height:1px;background:#edf0f3}.empty{padding:48px 16px;text-align:center;color:#8a9099;font-size:14px}.hidden{display:none!important}',
 '.bottom-nav{height:64px;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));align-items:center;border-top:1px solid #e8ebef;background:#fff;box-shadow:0 -4px 16px rgba(25,38,56,.05);z-index:30}.nav-item{height:63px;min-width:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;color:#67707a;font-size:11px}.nav-item img{width:25px;height:25px}.nav-item.active{color:#087bf0;font-weight:700}',
 '.hero{display:grid;grid-template-columns:56px minmax(0,1fr) 38px;gap:11px;align-items:center;padding:10px 14px 7px}.hero-icon{width:56px;height:56px;border-radius:15px;object-fit:cover;background:#edf4ff}.hero-title{font-size:20px;line-height:25px;font-weight:760;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hero-sub{font-size:12px;color:#7b828b;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.circle-btn{width:38px;height:38px;border-radius:19px;background:#f5f7f9;display:flex;align-items:center;justify-content:center;font-size:22px}',
 '.chip-row{display:flex;gap:7px;overflow-x:auto;padding:5px 14px 8px;scrollbar-width:none;touch-action:pan-x}.chip-row::-webkit-scrollbar{display:none}.chip{flex:0 0 auto;min-height:34px;padding:7px 13px;border-radius:11px;background:#f5f6f8;font-size:13px;white-space:nowrap}.chip.active{background:#e4f0ff;color:#087bf0;font-weight:700}',
 '.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;padding:1px 14px 8px}.metric{min-width:0;height:70px;border:1px solid #e9edf2;border-radius:13px;background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center}.metric.active{border-color:#9dccff;background:#f3f9ff}.metric-num{font-size:25px;line-height:28px;font-weight:760}.metric.active .metric-num{color:#087bf0}.metric-label{font-size:11px;color:#6f7781;margin-top:4px}',
 '.recent-head,.section-head,.page-head{display:flex;align-items:center;gap:8px;min-width:0}.recent-head{padding:2px 14px 5px}.section-head{padding:7px 14px;border-bottom:1px solid #edf0f3}.page-head{height:52px;padding:0 14px;border-bottom:1px solid #e9ecf0}.head-title,.section-title{font-weight:750;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.head-title{font-size:19px}.section-title{font-size:17px;flex:1}.section-count{font-size:12px;color:#8a9099;white-space:nowrap}.back-btn{font-size:27px;width:34px;height:42px;display:flex;align-items:center}.head-spacer{width:34px}.recent-strip{display:flex;gap:15px;overflow-x:auto;padding:0 14px 8px;scrollbar-width:none}.recent-strip::-webkit-scrollbar{display:none}.recent-card{flex:0 0 50px;text-align:center;font-size:10px}.recent-card img{width:40px;height:40px;border-radius:11px;object-fit:cover;margin:0 auto 4px}.recent-card span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
 '.tools{display:flex;align-items:center;gap:6px;min-width:0;flex:none}.tool,.tool-select{min-width:0;height:32px;padding:0 9px;border-radius:9px;background:#f5f6f8;color:#5f6770;font-size:11px;border:0;outline:0}.tool-select{width:92px;max-width:92px;padding-right:4px}.program-list{width:100%;min-width:0;overflow-x:hidden}.program{width:100%;min-width:0;display:grid;grid-template-columns:48px minmax(0,1fr) auto;gap:10px;text-align:left;padding:11px 14px;border-bottom:1px solid #edf0f3;align-items:start;background:#fff;overflow:hidden}.program.compact{grid-template-columns:38px minmax(0,1fr) auto;padding:9px 8px}.program-icon{width:48px;height:48px;border-radius:12px;object-fit:cover;background:#f1f3f5}.program.compact .program-icon{width:38px;height:38px;border-radius:10px}.program-main{min-width:0;overflow:hidden}.program-name{display:block;font-size:15px;line-height:21px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.program-version{font-size:12px;font-weight:400;color:#858b94;margin-left:5px}.program-tags{display:flex;gap:8px;overflow:hidden;margin-top:5px}.tag{font-size:11px;color:#087bf0;white-space:nowrap}.program-desc{display:block;font-size:10px;color:#8a9099;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.status{font-size:11px;white-space:nowrap;padding-top:2px}',
 '.tree{flex:1;min-height:0;display:grid;grid-template-columns:35% 65%;overflow:hidden;border-top:1px solid #edf0f3}.tree-left{min-height:0;overflow-y:auto;background:#f6f8fa;padding:7px}.tree-right{min-height:0;overflow-y:auto;padding:7px 10px 18px}.main-cat{width:100%;min-height:48px;border-radius:11px;padding:10px 9px;display:flex;align-items:center;justify-content:space-between;text-align:left;font-size:14px}.main-cat.active{background:#deecff;color:#087bf0;font-weight:750}.cat-count{font-size:11px;color:#949aa2}.target-row{width:100%;min-height:50px;display:flex;align-items:center;justify-content:space-between;text-align:left;padding:8px 6px;border-bottom:1px solid #eef1f4}.target-name{font-size:14px}.target-meta{font-size:11px;color:#939aa3}.target-row.active{color:#087bf0;font-weight:700}.accordion{border-bottom:1px solid #e9edf2;background:#fbfdff;padding:2px 0 5px}.accordion .program{background:#fbfdff}',
 '.search-fixed{padding:10px 14px 8px}.search-box{display:grid;grid-template-columns:minmax(0,1fr) 62px;border:1.5px solid #25282d;border-radius:12px;overflow:hidden;height:43px}.search-input{min-width:0;border:0;outline:0;padding:0 12px;font-size:15px;background:transparent}.search-go{color:#16a36a;font-weight:750}.scope-row{display:flex;gap:7px;overflow-x:auto;padding-top:9px;scrollbar-width:none}.scope{flex:0 0 auto;padding:8px 13px;border-radius:10px;background:#f5f6f8;font-size:12px}.scope.active{background:#e4f0ff;color:#087bf0;font-weight:700}.discover{padding:10px 14px}.block-title{font-size:17px;font-weight:750;margin:10px 0}.tag-grid{display:flex;gap:8px;flex-wrap:wrap}.tag-button{padding:8px 11px;border-radius:10px;background:#f5f6f8;color:#5f6670;font-size:12px}',
 '.detail-hero{display:grid;grid-template-columns:68px minmax(0,1fr);gap:13px;align-items:center;padding:16px 14px 12px}.detail-icon{width:68px;height:68px;border-radius:17px;object-fit:cover}.detail-name{font-size:21px;font-weight:780}.detail-summary{font-size:12px;color:#7e858e;margin-top:5px}.info-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:3px 14px 10px}.info-card{min-height:48px;border-radius:11px;background:#f6f7f9;padding:9px 11px}.info-key{font-size:10px;color:#8b9199}.info-value{font-size:13px;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.detail-tags{display:flex;gap:8px;flex-wrap:wrap;padding:2px 14px 9px}.detail-desc{font-size:12px;line-height:19px;color:#6f7780;padding:0 14px 12px}.primary-row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;padding:5px 14px 12px}.primary,.secondary{height:42px;border-radius:10px;font-size:14px;font-weight:700}.primary{background:#1685f8;color:#fff}.secondary{background:#e8f2ff;color:#087bf0}.quick-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));border-top:1px solid #edf0f3;border-bottom:1px solid #edf0f3;padding:8px 5px}.quick{min-width:0;height:54px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;font-size:10px}.quick-symbol{font-size:22px;color:#69717a}.version-list{padding:2px 14px 10px}.version-card{width:100%;display:grid;grid-template-columns:44px minmax(0,1fr) auto;gap:10px;text-align:left;padding:12px 0;border-bottom:1px solid #edf0f3}.version-card img{width:44px;height:44px;border-radius:11px}.version-name{font-size:15px;font-weight:700}.version-desc{font-size:11px;color:#818891;margin-top:4px;line-height:16px}.version-status{font-size:11px;white-space:nowrap}.highlight-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:5px}.highlight{font-size:10px;color:#087bf0}',
 '.update-actions,.setting-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;padding:10px 14px}.panel-button{height:42px;border-radius:10px;background:#f4f6f8;font-size:13px}.setting-section{padding:10px 14px 3px}.setting-title{font-size:17px;font-weight:750;margin-bottom:6px}.setting-sub{font-size:11px;color:#899099;margin-bottom:6px}.setting-row{min-height:50px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #edf0f3;gap:10px}.setting-name{font-size:14px}.setting-value{font-size:12px;color:#858c95;text-align:right}.history-row{display:grid;grid-template-columns:40px minmax(0,1fr);gap:10px;padding:10px 14px;border-bottom:1px solid #edf0f3}.history-row img{width:40px;height:40px;border-radius:10px}.history-name{font-size:14px;font-weight:650}.history-meta{font-size:11px;color:#878e97;margin-top:4px}.toast{position:fixed;left:50%;bottom:76px;transform:translateX(-50%) translateY(12px);max-width:88%;padding:9px 14px;border-radius:19px;background:rgba(31,36,43,.9);color:#fff;font-size:12px;opacity:0;pointer-events:none;transition:.18s;z-index:80}.toast.show{opacity:1;transform:translateX(-50%) translateY(0)}',
 '@media(prefers-color-scheme:dark){html,body,.screen,.bottom-nav,.program{background:#111317;color:#eef1f4}.bottom-nav,.page-head,.section-head,.program,.target-row,.accordion,.quick-grid,.version-card,.setting-row,.history-row,.hairline{border-color:#292d34}.circle-btn,.chip,.tool,.tool-select,.scope,.tag-button,.panel-button,.info-card{background:#22262c;color:#d8dce1}.chip.active,.scope.active,.metric.active,.main-cat.active{background:#16385f;color:#67b4ff}.metric{background:#171a1f;border-color:#292d34}.tree-left{background:#181b20}.tree-right,.accordion,.accordion .program{background:#111317}.hero-sub,.muted,.program-version,.program-desc,.metric-label,.detail-summary,.detail-desc,.setting-sub,.setting-value{color:#9da4ad}.primary{background:#1685f8}.secondary{background:#173a61;color:#67b4ff}}'
 ].join('');};

R.hybridCommonScript=function(){return'';};
R.hybridBottomNav=function(){return'';};

R.workspaceClient=function(){
 var state={view:DATA.initialView||'home',id:DATA.initialId||'',homeCategory:DATA.initialCategory||'all',homeScope:DATA.initialScope||'all',homeSort:'default',categoryMain:DATA.initialCategory||'all',expanded:'',search:DATA.initialSearch||'',searchScope:'all',stack:[],scrolls:{}};
 var host=document.getElementById('viewHost'),nav=document.getElementById('bottomNav'),toastTimer=0;
 function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
 function bridge(){return typeof fba!=='undefined'?fba:(typeof fy_bridge_app!=='undefined'?fy_bridge_app:null);}
 function byId(id){for(var i=0;i<DATA.programs.length;i++)if(DATA.programs[i].id===id)return DATA.programs[i];return null;}
 function category(id){for(var i=0;i<DATA.categories.length;i++)if(DATA.categories[i].id===id)return DATA.categories[i];return null;}
 function activeTab(){if(state.view==='category')return'category';if(state.view==='search')return'search';if(state.view==='updates')return'updates';if(state.view==='settings'||state.view==='history')return'settings';return'home';}
 function showToast(text){var el=document.getElementById('toast');if(!el)return;el.textContent=String(text||'操作完成');el.className='toast show';clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.className='toast';},2200);}
 function bridgeOpen(url,title,windowId){var b=bridge();if(!b||!url){showToast('当前环境暂不支持此操作');return;}try{b.open(JSON.stringify({rule:DATA.ruleName,title:title||DATA.title,url:url,group:'',col_type:'',findRule:'',preRule:'',extra:{newWindow:true,windowId:windowId||'rule-repo-action'}}));}catch(e){showToast('操作失败：'+String(e.message||e));}}
 function runAction(url,mode,program,channel){var b=bridge(),result=url;if(!b){showToast('桥接服务不可用');return;}try{if(url&&url.indexOf('@lazyRule=')>=0&&b.parseLazyRule)result=b.parseLazyRule(url);if(!result)return;if(String(result).indexOf('海阔视界')===0){b.importRule(String(result));return;}if(String(result).indexOf('copy://')===0){if(b.copy)b.copy(String(result).substring(7));else bridgeOpen(String(result),'复制备份','rule-repo-business');showToast('备份内容已复制');return;}if(String(result).indexOf('toast://')===0){var message=String(result).substring(8);if(message)showToast(message);if(mode==='favorite'&&program){program.favorite=!program.favorite;DATA.stats.favorites=Math.max(0,Number(DATA.stats.favorites||0)+(program.favorite?1:-1));refresh(true);}else if(mode==='clearRecent'){DATA.recent=[];DATA.history.opens=[];refresh(true);}else if(mode==='clearSearch'){DATA.searchHistory=[];refresh(true);}else if(mode==='clearImports'){DATA.history.imports=[];refresh(true);}if(mode==='sync'&&b.refreshPage)setTimeout(function(){b.refreshPage(true);},500);return;}if(mode==='import'&&String(result).indexOf('rule://')===0){b.importRule(String(result));return;}bridgeOpen(String(result),program?program.name:DATA.title,program?'rule-repo-business':(channel?'rule-repo-business':'rule-repo-action'));}catch(e){showToast('操作失败：'+String(e.message||e));}}
 function navHtml(){var a=[['home','首页'],['category','分类'],['search','搜索'],['updates','更新'],['settings','设置']],on=activeTab(),out='';for(var i=0;i<a.length;i++){var k=a[i][0],icons=DATA.navIcons[k]||['',''];out+='<button class="nav-item '+(on===k?'active':'')+'" data-nav="'+k+'"><img src="'+esc(icons[on===k?1:0])+'"><span>'+a[i][1]+'</span></button>';}return out;}
 function statusColor(p){return p.update?'#e99a13':(p.installed?'#16a36a':(p.channel?'#087bf0':'#858b94'));}
 function card(p,compact){var tags='',i;for(i=0;i<p.tags.length&&i<3;i++)tags+='<span class="tag">'+esc(p.tags[i])+'</span>';return'<button class="program '+(compact?'compact':'')+'" data-program="'+esc(p.id)+'"><img class="program-icon" src="'+esc(p.icon)+'"><span class="program-main"><span class="program-name">'+esc(p.name)+'<span class="program-version">'+esc(p.version)+'</span></span><span class="program-tags">'+tags+'</span><span class="program-desc">'+esc(p.desc||p.summary)+'</span></span><span class="status" style="color:'+statusColor(p)+'">'+esc(p.status)+'</span></button>';}
 function visibleHome(p){if(state.homeCategory!=='all'&&p.category!==state.homeCategory)return false;if(state.homeScope==='installed'&&!p.installed)return false;if(state.homeScope==='updates'&&!p.update)return false;if(state.homeScope==='favorites'&&!p.favorite)return false;return true;}
 function homePrograms(){var a=DATA.programs.filter(visibleHome).slice();if(state.homeSort==='updated')a.sort(function(x,y){return String(y.updatedAt).localeCompare(String(x.updatedAt));});else if(state.homeSort==='name')a.sort(function(x,y){return x.name.localeCompare(y.name);});else if(state.homeSort==='version')a.sort(function(x,y){return String(y.version).localeCompare(String(x.version));});return a;}
 function home(){var cats='',metrics='',recent='',a=homePrograms(),i;for(i=0;i<DATA.categories.length;i++){var c=DATA.categories[i];cats+='<button class="chip '+(state.homeCategory===c.id?'active':'')+'" data-home-cat="'+esc(c.id)+'">'+esc(c.name)+(state.homeCategory===c.id?' '+c.count:'')+'</button>';}
  var ms=[['all','全部',DATA.stats.all],['installed','已安装',DATA.stats.installed],['updates','可更新',DATA.stats.updates],['favorites','收藏',DATA.stats.favorites]];for(i=0;i<ms.length;i++)metrics+='<button class="metric '+(state.homeScope===ms[i][0]?'active':'')+'" data-home-scope="'+ms[i][0]+'"><span class="metric-num">'+Number(ms[i][2]||0)+'</span><span class="metric-label">'+ms[i][1]+'</span></button>';
  for(i=0;i<DATA.recent.length;i++){var p=byId(DATA.recent[i]);if(p)recent+='<button class="recent-card" data-program="'+esc(p.id)+'"><img src="'+esc(p.icon)+'"><span>'+esc(p.name)+'</span></button>';}
  return'<section class="screen"><div class="fixed"><div class="hero"><img class="hero-icon" src="'+esc(DATA.icon)+'"><div><div class="hero-title">'+esc(DATA.title)+'</div><div class="hero-sub">'+esc(DATA.subtitle)+'</div></div><button class="circle-btn" data-nav="search">⌕</button></div><div class="chip-row">'+cats+'</div><div class="metrics">'+metrics+'</div>'+(recent?'<div class="recent-head"><div class="section-title">继续使用</div><span class="section-count">最近打开</span></div><div class="recent-strip">'+recent+'</div>':'')+'<div class="section-head"><div class="section-title">我的程序</div><span class="section-count">'+a.length+' 个</span><div class="tools"><select id="homeSort" class="tool-select"><option value="default">默认排序</option><option value="updated">最近更新</option><option value="name">名称排序</option><option value="version">版本排序</option></select><button class="tool" data-nav="category">分类</button><button class="tool" data-static="sync">同步</button></div></div></div><div class="scroll program-list">'+(a.length?a.map(function(x){return card(x,false);}).join(''):'<div class="empty">没有匹配程序，换一个分类或状态试试</div>')+'</div></section>';
 }
 function categoryPrograms(main,sub){return DATA.programs.filter(function(p){if(main!=='all'&&p.category!==main)return false;if(sub!=='all'&&p.subCategory!==sub)return false;return true;});}
 function targetRow(main,sub,name,count){var key=main+'|'+sub,on=state.expanded===key,a=categoryPrograms(main,sub),out='<button class="target-row '+(on?'active':'')+'" data-target="'+esc(key)+'"><span class="target-name">'+esc(name)+'</span><span class="target-meta">'+count+' 个 '+(on?'⌃':'⌄')+'</span></button>';if(on)out+='<div class="accordion">'+(a.length?a.map(function(p){return card(p,true);}).join(''):'<div class="empty">该分类暂无程序</div>')+'</div>';return out;}
 function categoryView(){var left='',right='',i,g=category(state.categoryMain)||category('all');for(i=0;i<DATA.categories.length;i++){var c=DATA.categories[i];left+='<button class="main-cat '+(g&&g.id===c.id?'active':'')+'" data-main-cat="'+esc(c.id)+'"><span>'+esc(c.name)+'</span><span class="cat-count">'+c.count+'</span></button>';}
  if(!g)g=DATA.categories[0];if(g.id==='all'){right+=targetRow('all','all','全部程序',DATA.stats.all);for(i=0;i<DATA.categories.length;i++)if(DATA.categories[i].id!=='all'&&DATA.categories[i].count)right+=targetRow(DATA.categories[i].id,'all','全部'+DATA.categories[i].name,DATA.categories[i].count);}else{right+=targetRow(g.id,'all','全部'+g.name,g.count);for(i=0;i<g.subs.length;i++)right+=targetRow(g.id,g.subs[i].id,g.subs[i].name,g.subs[i].count);}
  return'<section class="screen"><div class="fixed"><div class="page-head"><div class="head-spacer"></div><div class="head-title" style="flex:1">分类管理</div><button class="circle-btn" data-nav="search">⌕</button></div><div class="section-head"><div class="section-title">分类目录</div><span class="section-count">'+DATA.stats.all+' 个程序 · 点分类展开</span></div></div><div class="tree"><nav class="tree-left">'+left+'</nav><div class="tree-right">'+right+'</div></div></section>';
 }
 function searchMatch(p){if(state.searchScope==='installed'&&!p.installed)return false;if(state.searchScope==='updates'&&!p.update)return false;if(state.searchScope==='favorites'&&!p.favorite)return false;var q=state.search.trim().toLowerCase();return!q||p.search.indexOf(q)>=0;}
 function searchView(){var scopes='',discover='',i,a=DATA.programs.filter(searchMatch),ss=[['all','全部'],['installed','已安装'],['updates','可更新'],['favorites','收藏']];for(i=0;i<ss.length;i++)scopes+='<button class="scope '+(state.searchScope===ss[i][0]?'active':'')+'" data-search-scope="'+ss[i][0]+'">'+ss[i][1]+'</button>';if(!state.search){var h='',t='';for(i=0;i<DATA.searchHistory.length;i++)h+='<button class="tag-button" data-query="'+esc(DATA.searchHistory[i])+'">'+esc(DATA.searchHistory[i])+'</button>';for(i=0;i<DATA.popularTags.length;i++)t+='<button class="tag-button" data-query="'+esc(DATA.popularTags[i])+'">#'+esc(DATA.popularTags[i])+'</button>';discover='<div class="discover">'+(h?'<div class="block-title">最近搜索</div><div class="tag-grid">'+h+'</div>':'')+(t?'<div class="block-title">热门标签</div><div class="tag-grid">'+t+'</div>':'')+'</div>';}
  return'<section class="screen"><div class="fixed"><div class="page-head"><button class="back-btn" data-back>‹</button><div class="head-title" style="flex:1">搜索</div><div class="head-spacer"></div></div><div class="search-fixed"><div class="search-box"><input id="searchInput" class="search-input" type="search" value="'+esc(state.search)+'" placeholder="搜索名称、描述、标签或版本"><button class="search-go" data-search-go>搜索</button></div><div class="scope-row">'+scopes+'</div></div></div><div class="scroll">'+discover+'<div class="section-head"><div class="section-title">'+(state.search?'搜索结果':'全部程序')+'</div><span class="section-count">'+a.length+' 个</span></div><div class="program-list">'+(a.length?a.map(function(p){return card(p,false);}).join(''):'<div class="empty">没有找到相关程序，换个关键词试试</div>')+'</div></div></section>';
 }
 function infoCard(k,v){return'<div class="info-card"><div class="info-key">'+esc(k)+'</div><div class="info-value">'+esc(v)+'</div></div>';}
 function detailView(){var p=byId(state.id);if(!p)return'<section class="screen"><div class="page-head"><button class="back-btn" data-back>‹</button><div class="head-title">程序信息</div></div><div class="empty">程序不存在，云端目录可能已更新</div></section>';var tags='',i;for(i=0;i<p.tags.length;i++)tags+='<span class="chip">'+esc(p.tags[i])+'</span>';var body='<div class="detail-hero"><img class="detail-icon" src="'+esc(p.icon)+'"><div><div class="detail-name">'+esc(p.name)+'</div><div class="detail-summary">'+esc(p.summary||p.desc)+'</div></div></div>';
  if(p.channel){body+='<div class="info-grid">'+infoCard('当前版本',p.version)+infoCard('运行状态',p.status)+infoCard('版本数量',p.channels.length+' 个')+infoCard('程序类型',p.typeText)+infoCard('主分类',p.categoryName)+infoCard('更新时间',p.updatedAt)+'</div><div class="detail-tags">'+tags+'</div><div class="primary-row"><button class="primary" data-program-action="open" data-id="'+esc(p.id)+'">打开程序</button><button class="secondary" data-program-action="check" data-id="'+esc(p.id)+'">检查版本</button></div><div class="section-head"><div class="section-title">可用版本</div><span class="section-count">'+p.channels.length+' 个 · 点击导入或切换</span></div><div class="version-list">';for(i=0;i<p.channels.length;i++){var c=p.channels[i],hl='';for(var j=0;j<c.highlights.length;j++)hl+='<span class="highlight">'+esc(c.highlights[j])+'</span>';body+='<button class="version-card" data-channel="'+i+'" data-id="'+esc(p.id)+'"><img src="'+esc(c.icon)+'"><span><span class="version-name">'+esc(c.label)+' '+esc(c.version)+'</span><span class="version-desc">'+esc(c.desc||c.displayVersion)+'</span><span class="highlight-row">'+hl+'</span></span><span class="version-status" style="color:'+(c.current?'#16a36a':(c.channel==='test'?'#e99a13':'#087bf0'))+'">'+esc(c.status)+'</span></button>';}body+='</div>';}
  else{var primaryKind=p.installed?'open':'import',secondaryKind=p.installed?'import':'check',primaryText=p.installed?'打开程序':'导入程序',secondaryText=p.installed?(p.update?'更新到最新版':'重新导入'):'检查版本';body+='<div class="info-grid">'+infoCard('安装状态',p.status)+infoCard('云端版本',p.version)+infoCard('本地版本',p.localVersion)+infoCard('大小',p.sizeText)+infoCard('程序类型',p.typeText)+infoCard('更新时间',p.updatedAt)+infoCard('主分类',p.categoryName)+infoCard('子分类',p.subCategory||'未分类')+'</div><div class="detail-tags">'+tags+'</div><div class="detail-desc">'+esc(p.desc||p.summary)+'</div><div class="primary-row"><button class="primary" data-program-action="'+primaryKind+'" data-id="'+esc(p.id)+'">'+primaryText+'</button><button class="secondary" data-program-action="'+secondaryKind+'" data-id="'+esc(p.id)+'">'+secondaryText+'</button></div>';}
  body+='<div class="quick-grid"><button class="quick" data-program-action="favorite" data-id="'+esc(p.id)+'"><span class="quick-symbol">'+(p.favorite?'★':'☆')+'</span><span>'+(p.favorite?'已收藏':'收藏')+'</span></button><button class="quick" data-program-action="check" data-id="'+esc(p.id)+'"><span class="quick-symbol">↻</span><span>检查</span></button><button class="quick" data-view="history"><span class="quick-symbol">◴</span><span>活动记录</span></button><button class="quick" data-nav="settings"><span class="quick-symbol">☷</span><span>设置</span></button><button class="quick" data-nav="home"><span class="quick-symbol">⌂</span><span>返回仓库</span></button></div><div class="setting-section"><div class="setting-title">程序说明</div><div class="setting-sub">'+esc(p.channel?'正式、测试与本地版本在同一页面切换；测试异常时可直接导入正式版恢复。':'程序资料、版本状态和常用操作已集中在本页，返回不会新增海阔页面。')+'</div></div>';
  return'<section class="screen"><div class="fixed page-head"><button class="back-btn" data-back>‹</button><div class="head-title" style="flex:1">'+esc(p.name)+'</div><div class="head-spacer"></div></div><div class="scroll">'+body+'</div></section>';
 }
 function updatesView(){var a=DATA.programs.filter(function(p){return p.update&&!p.channel;}),metrics=[['全部',DATA.stats.all],['已安装',DATA.stats.installed],['可更新',a.length],['收藏',DATA.stats.favorites]],m='',i;for(i=0;i<metrics.length;i++)m+='<div class="metric '+(i===2&&a.length?'active':'')+'"><span class="metric-num">'+Number(metrics[i][1]||0)+'</span><span class="metric-label">'+metrics[i][0]+'</span></div>';return'<section class="screen"><div class="fixed"><div class="page-head"><div class="head-spacer"></div><div class="head-title" style="flex:1">更新中心</div><div class="head-spacer"></div></div><div class="update-actions"><button class="primary" data-native-page="ruleRepoUpdate">检查 Core 更新</button><button class="secondary" data-static="sync">同步程序目录</button></div><div class="metrics">'+m+'</div><div class="section-head"><div class="section-title">待更新程序</div><span class="section-count">'+a.length+' 个</span></div></div><div class="scroll program-list">'+(a.length?a.map(function(p){return card(p,false);}).join(''):'<div class="empty">已是最新状态<br><span class="muted">程序目录变化后可手动同步检查</span></div>')+'</div></section>';}
 function settingsView(){var probe=DATA.settings.probeMs<=0?'已关闭':'每 '+Math.round(DATA.settings.probeMs/1000)+' 秒',cache=Math.round(DATA.settings.cacheMs/60000)+' 分钟';return'<section class="screen"><div class="fixed page-head"><div class="head-spacer"></div><div class="head-title" style="flex:1">设置</div><div class="head-spacer"></div></div><div class="scroll"><div class="setting-section"><div class="setting-title">体验与同步</div><div class="setting-sub">高频设置和状态直接显示，不再逐层打开页面</div><div class="setting-row"><span class="setting-name">自动检查</span><span class="setting-value">'+esc(probe)+'</span></div><div class="setting-row"><span class="setting-name">离线缓存</span><span class="setting-value">'+esc(cache)+'</span></div><div class="setting-row"><span class="setting-name">云端通道</span><span class="setting-value">'+esc(DATA.settings.source)+'</span></div><div class="setting-row"><span class="setting-name">最近同步</span><span class="setting-value">'+esc(DATA.settings.lastSync)+'</span></div></div><div class="setting-actions"><button class="panel-button" data-static="sync">立即同步</button><button class="panel-button" data-native-page="ruleRepoUpdate">版本更新</button></div><div class="setting-section"><div class="setting-title">数据管理</div><div class="setting-sub">只处理规则仓库自己的记录与偏好</div></div><div class="setting-actions"><button class="panel-button" data-static="backup">备份状态</button><button class="panel-button" data-view="history">活动记录</button><button class="panel-button" data-static="clearSearch">清搜索记录</button><button class="panel-button" data-static="clearRecent">清最近打开</button></div><div class="setting-section"><div class="setting-title">关于</div><div class="setting-row"><span class="setting-name">版本</span><span class="setting-value">'+esc(DATA.version)+' · Build '+DATA.build+'</span></div><div class="setting-row"><span class="setting-name">通道</span><span class="setting-value">'+esc(DATA.channel)+'</span></div><div class="setting-row"><span class="setting-name">界面</span><span class="setting-value">'+esc(DATA.ui)+'</span></div></div><div class="setting-actions"><button class="panel-button" data-static="diagnostics">诊断信息</button><button class="panel-button" data-nav="home">返回首页</button></div></div></section>';}
 function historyView(){var opens='',imports='',i;for(i=0;i<DATA.history.opens.length;i++){var o=DATA.history.opens[i],p=byId(String(o.id||''));if(p)opens+='<button class="history-row" data-program="'+esc(p.id)+'"><img src="'+esc(p.icon)+'"><span><span class="history-name">'+esc(p.name)+'</span><span class="history-meta">最近打开 · '+esc(new Date(Number(o.time||0)).toLocaleString())+'</span></span></button>';}for(i=0;i<DATA.history.imports.length;i++){var h=DATA.history.imports[i],q=byId(String(h.id||'')),icon=q?q.icon:DATA.icon;imports+='<button class="history-row" '+(q?'data-program="'+esc(q.id)+'"':'')+'><img src="'+esc(icon)+'"><span><span class="history-name">'+esc(h.name||h.id)+'</span><span class="history-meta">'+esc(h.version||'--')+' · 导入记录</span></span></button>';}
  return'<section class="screen"><div class="fixed page-head"><button class="back-btn" data-back>‹</button><div class="head-title" style="flex:1">活动记录</div><div class="head-spacer"></div></div><div class="scroll"><div class="section-head"><div class="section-title">最近打开</div><button class="tool" data-static="clearRecent">清空</button></div>'+(opens||'<div class="empty">暂无最近打开记录</div>')+'<div class="section-head"><div class="section-title">导入记录</div><button class="tool" data-static="clearImports">清空</button></div>'+(imports||'<div class="empty">暂无导入记录</div>')+'</div></section>';}
 function routeKey(view,id){return String(view||state.view)+(String(view||state.view)==='detail'?':'+String(id==null?state.id:id):'');}
 function rememberScroll(){var nodes=host.querySelectorAll('.scroll,.tree-left,.tree-right'),a=[];for(var i=0;i<nodes.length;i++)a.push(Number(nodes[i].scrollTop||0));state.scrolls[routeKey()]=a;}
 function restoreScroll(){var nodes=host.querySelectorAll('.scroll,.tree-left,.tree-right'),a=state.scrolls[routeKey()]||[];for(var i=0;i<nodes.length;i++)nodes[i].scrollTop=Number(a[i]||0);}
 function render(){if(state.view==='category')host.innerHTML=categoryView();else if(state.view==='search')host.innerHTML=searchView();else if(state.view==='detail')host.innerHTML=detailView();else if(state.view==='updates')host.innerHTML=updatesView();else if(state.view==='settings')host.innerHTML=settingsView();else if(state.view==='history')host.innerHTML=historyView();else host.innerHTML=home();nav.innerHTML=navHtml();if(state.view==='home'){var s=document.getElementById('homeSort');if(s)s.value=state.homeSort;}restoreScroll();try{history.replaceState({view:state.view,id:state.id},'');}catch(e){}}
 function refresh(keepScroll){if(keepScroll)rememberScroll();else state.scrolls[routeKey()]=[];render();}
 function snapshot(){return{view:state.view,id:state.id};}
 function go(view,id){rememberScroll();if(state.view!==view||String(state.id)!==String(id||''))state.stack.push(snapshot());state.view=view;state.id=view==='detail'?String(id||''):'';render();}
 function navTo(view){rememberScroll();state.stack=[];state.view=view;state.id='';render();}
 function back(){rememberScroll();if(state.stack.length){var x=state.stack.pop();state.view=x.view||'home';state.id=x.id||'';render();return true;}if(state.view!=='home'){state.view='home';state.id='';render();return true;}var b=bridge();try{if(b&&b.back)b.back(false);}catch(e){}return false;}
 function armBackTrap(){try{history.replaceState({ruleRepoBase:true},'');history.pushState({ruleRepoShell:true},'');return true;}catch(e){return false;}}
 function submitSearch(){var input=document.getElementById('searchInput');if(input){state.search=input.value||state.search;try{input.blur();var b=bridge();if(b)b.putVar('hc_repo_hybrid_search',state.search);}catch(e){}}if(state.search)runAction(DATA.actions.recordSearch,'recordSearch');refresh(true);}
 document.addEventListener('click',function(e){var el=e.target;while(el&&el!==document.body&&!el.getAttribute('data-nav')&&!el.getAttribute('data-program')&&!el.getAttribute('data-home-cat')&&!el.getAttribute('data-home-scope')&&!el.getAttribute('data-main-cat')&&!el.getAttribute('data-target')&&!el.getAttribute('data-search-scope')&&!el.getAttribute('data-query')&&!el.getAttribute('data-program-action')&&!el.getAttribute('data-channel')&&!el.getAttribute('data-static')&&!el.getAttribute('data-native-page')&&!el.getAttribute('data-view')&&!el.hasAttribute('data-search-go')&&!el.hasAttribute('data-back'))el=el.parentNode;if(!el||el===document.body)return;
  var v;if((v=el.getAttribute('data-nav'))){navTo(v);return;}if(el.hasAttribute('data-back')){back();return;}if(el.hasAttribute('data-search-go')){submitSearch();return;}if((v=el.getAttribute('data-program'))){go('detail',v);return;}if((v=el.getAttribute('data-home-cat'))){state.homeCategory=v;state.categoryMain=v;state.expanded='';try{bridge().putVar('hc_repo_hybrid_category',v);}catch(x){}refresh(false);return;}if((v=el.getAttribute('data-home-scope'))){state.homeScope=v;try{bridge().putVar('hc_repo_hybrid_scope',v);}catch(y){}refresh(false);return;}if((v=el.getAttribute('data-main-cat'))){state.categoryMain=v;state.expanded='';refresh(false);return;}if((v=el.getAttribute('data-target'))){rememberScroll();state.expanded=state.expanded===v?'':v;render();return;}if((v=el.getAttribute('data-search-scope'))){state.searchScope=v;refresh(false);return;}if((v=el.getAttribute('data-query'))){state.search=v;try{var qb=bridge();if(qb)qb.putVar('hc_repo_hybrid_search',v);}catch(qe){}runAction(DATA.actions.recordSearch,'recordSearch');refresh(false);return;}if((v=el.getAttribute('data-view'))){go(v);return;}if((v=el.getAttribute('data-program-action'))){var p=byId(el.getAttribute('data-id')),u=p&&p.actions[v];if(u)runAction(u,v,p);return;}if(el.hasAttribute('data-channel')){var cp=byId(el.getAttribute('data-id')),ci=Number(el.getAttribute('data-channel')),ch=cp&&cp.channels[ci];if(ch)runAction(ch.action,'import',cp,ch);return;}if((v=el.getAttribute('data-static'))){runAction(DATA.actions[v],v==='sync'?'sync':v);return;}if((v=el.getAttribute('data-native-page'))){bridgeOpen('hiker://page/'+v+'?rule='+DATA.ruleName+'&simple=true#noHistory#','版本更新','rule-repo-core-update');return;}
 });
 document.addEventListener('change',function(e){if(e.target&&e.target.id==='homeSort'){state.homeSort=e.target.value||'default';refresh(false);}});
 document.addEventListener('input',function(e){if(e.target&&e.target.id==='searchInput'){state.search=e.target.value||'';var a=DATA.programs.filter(searchMatch),list=host.querySelector('.program-list'),count=host.querySelector('.section-count'),discover=host.querySelector('.discover'),title=host.querySelector('.scroll>.section-head .section-title');if(list)list.innerHTML=a.length?a.map(function(p){return card(p,false);}).join(''):'<div class="empty">没有找到相关程序，换个关键词试试</div>';if(count)count.textContent=a.length+' 个';if(title)title.textContent=state.search?'搜索结果':'全部程序';if(discover)discover.className=state.search?'discover hidden':'discover';}});
 document.addEventListener('keydown',function(e){if(e.target&&e.target.id==='searchInput'&&(e.key==='Enter'||e.keyCode===13)){e.preventDefault();submitSearch();}});
 var backTrap=false;window.addEventListener('popstate',function(){var internal=state.stack.length>0||state.view!=='home';if(internal){back();if(backTrap)try{history.pushState({ruleRepoShell:true},'');}catch(e){backTrap=false;}}else{var b=bridge();try{if(b&&b.back)b.back(false);}catch(x){}}});
 render();backTrap=armBackTrap();
};

R.hybridDocument=function(title,data,body,script){return'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover"><title>'+String(title||'我的规则仓库')+'</title><style>'+this.hybridBaseCss()+'</style></head><body><div class="shell"><main id="viewHost" class="view-host"></main><nav id="bottomNav" class="bottom-nav" aria-label="主导航"></nav></div><div id="toast" class="toast"></div><script>var DATA='+this.hybridJson(data)+';('+this.workspaceClient.toString()+')();<\/script></body></html>';};
R.workspaceHtml=function(items,initialView,initialId){var data=this.workspaceData(items,initialView,initialId);return this.hybridDocument('我的规则仓库',data,'','');};
R.hybridHomeHtml=function(items){return this.workspaceHtml(items,'home','');};
R.hybridCategoryHtml=function(items){return this.workspaceHtml(items,'category','');};
R.hybridSearchHtml=function(items){return this.workspaceHtml(items,'search','');};

R.workspacePage=function(initialView,initialId,fallbackFn){
 if(!this.hybridCanWeb())return fallbackFn.call(this);
 try{setPageTitle(initialView==='category'?'分类管理':(initialView==='search'?'搜索':(initialView==='updates'?'更新':(initialView==='settings'?'设置':'我的规则仓库'))));var items=this.items(false),html=this.workspaceHtml(items,initialView,initialId);setResult([this.hybridWebItem(html,'workspace')]);}catch(e){return fallbackFn.call(this);}
};
R.home=function(){return this.workspacePage('home','',fallback.home);};
R.categoryPage=function(){return this.workspacePage('category','',fallback.category);};
R.searchPage=function(){return this.workspacePage('search','',fallback.search);};
R.updatesPage=function(){return this.workspacePage('updates','',fallback.updates);};
R.settingsPage=function(){return this.workspacePage('settings','',fallback.settings);};
R.historyPage=function(){return this.workspacePage('history','',fallback.history);};
R.aboutPage=function(){return this.workspacePage('settings','',fallback.about);};
R.detailPage=function(){var params=typeof MY_PARAMS==='object'&&MY_PARAMS?MY_PARAMS:{},id=String(params.hc_repo_item_id||getParam('id')||'');return this.workspacePage('detail',id,fallback.detail);};
R.channelPage=function(parent){var id=String(parent&&parent.id||'');return this.workspacePage('detail',id,fallback.channel);};

R.ruleRepoChannelFallback=function(){
 var icon='https://cdn.jsdelivr.net/gh/huoguotiankong/asset-core-7f3@main/apps/tools/rule-repo/assets/icon.svg';return{schema:4,id:'rule-repo',name:'我的规则仓库',updatedAt:'2026-08-21',channels:[
  {channel:'stable',label:'正式版',id:'rule-repo',name:'我的规则仓库',version:'3.5.3',build:377,path:'apps/tools/rule-repo/rule_repo_remote_v353.txt',mode:'remote',updatedAt:'2026-08-21',recommended:true,desc:'实机验证稳定 · 日常使用与恢复入口',highlights:['稳定日常使用','安全同步与多镜像','异常恢复入口'],icon:icon},
  {channel:'test',label:'测试版',id:'rule-repo-test',name:'我的规则仓库·测试版',version:'3.5.4-rc5',baseVersion:'3.5.3',targetVersion:'3.5.4',build:382,path:'apps/tools/rule-repo/rule_repo_test_v128.txt',mode:'remote',updatedAt:'2026-08-21',recommended:false,desc:'Single Workspace 13.0 · 单页状态工作台',highlights:['只滚动程序区','分类原地展开','详情单页重构','不累积页面栈','Stable 恢复隔离'],icon:icon}
 ]};
};
})(HikerRuleRepo);
